OPALX (Object Oriented Parallel Accelerator Library for Exascal): ParseError Class Reference
ParseError Class Reference
Parse exception.
#include <ParseError.h>
Public Member Functions
ParseError (const std::string &meth, const std::string &msg)
The usual constructor.
ParseError (const ParseError &)
virtual ~ParseError ()
virtual const std::string & what () const
Return the message string for the exception.
virtual const std::string & where () const
Return the name of the method or function which detected the exception.
Private Member Functions
ParseError ()
Private Attributes
const std::string message
const std::string method
Detailed Description
Parse exception.
Definition at line 31 of file ParseError.h.
Constructor & Destructor Documentation
ParseError() [1/3]
ParseError::ParseError (const std::string & meth, const std::string & msg)
The usual constructor.
Definition at line 26 of file ParseError.cpp.
References OpalException::OpalException().
Referenced by ParseError().
ParseError() [2/3]
ParseError::ParseError (const ParseError & rhs)
Definition at line 29 of file ParseError.cpp.
References OpalException::OpalException(), and ParseError().
~ParseError()
ParseError::~ParseError () virtual
Definition at line 31 of file ParseError.cpp.
ParseError() [3/3]
ParseError::ParseError () private
Member Function Documentation
what()
const std::string & OpalException::what () const virtual inherited
Return the message string for the exception.
Definition at line 31 of file OpalException.cpp.
References message.
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), main(), OpalParser::readStatement(), OpalParser::run(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and TEST_F().
where()
const std::string & OpalException::where () const virtual inherited
Return the name of the method or function which detected the exception.
Definition at line 33 of file OpalException.cpp.
References method.
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), main(), OpalParser::run(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and TEST_F().
Member Data Documentation
message
const std::string OpalException::message private inherited
Definition at line 56 of file OpalException.h.
Referenced by OpalException(), OpalException(), and what().
method
const std::string OpalException::method private inherited
Definition at line 57 of file OpalException.h.
Referenced by DivideError::DivideError(), OpalException(), OpalException(), and where().
The documentation for this class was generated from the following files:
ParseError.h
ParseError.cpp