OPALX (Object Oriented Parallel Accelerator Library for Exascal): ElementGeometry Class Reference
ElementGeometry Class Reference
Named body-relative ports used for placement and chaining.
#include <ElementGeometry.h>
Public Member Functions
ElementGeometry ()
ElementGeometry (const Port &entry, const Port &body, const Port &exit)
const Port & getEntry () const
const Port & getBody () const
const Port & getExit () const
Private Attributes
Port entry_m
Port body_m
Port exit_m
Detailed Description
Named body-relative ports used for placement and chaining.
This is a lightweight implementation holder for the canonical local chart and its named interface frames. In the language of the placement note, these ports represent marked boundary charts with adapted frames. The first redesign stage keeps the set minimal: entry, body, and exit.
Definition at line 15 of file ElementGeometry.h.
Constructor & Destructor Documentation
ElementGeometry() [1/2]
ElementGeometry::ElementGeometry () inline
Definition at line 17 of file ElementGeometry.h.
ElementGeometry() [2/2]
ElementGeometry::ElementGeometry (const Port & entry, const Port & body, const Port & exit) inline
Definition at line 22 of file ElementGeometry.h.
Member Function Documentation
getBody()
const Port & ElementGeometry::getBody () const inline
Definition at line 26 of file ElementGeometry.h.
References body_m.
Referenced by PlacedElement::getBodyTransform(), PlacedElement::getNominalBodyPortTransform(), TEST_F(), and TEST_F().
getEntry()
const Port & ElementGeometry::getEntry () const inline
Definition at line 25 of file ElementGeometry.h.
References entry_m.
Referenced by PlacedElement::getEntryTransform(), PlacedElement::getNominalEntryTransform(), TEST_F(), TEST_F(), and TEST_F().
getExit()
const Port & ElementGeometry::getExit () const inline
Definition at line 27 of file ElementGeometry.h.
References exit_m.
Referenced by PlacedElement::getExitTransform(), PlacedElement::getNominalExitTransform(), TEST_F(), TEST_F(), and TEST_F().
Member Data Documentation
body_m
Port ElementGeometry::body_m private
Definition at line 31 of file ElementGeometry.h.
Referenced by getBody().
entry_m
Port ElementGeometry::entry_m private
Definition at line 30 of file ElementGeometry.h.
Referenced by getEntry().
exit_m
Port ElementGeometry::exit_m private
Definition at line 32 of file ElementGeometry.h.
Referenced by getExit().
The documentation for this class was generated from the following file:
ElementGeometry.h