OPALX (Object Oriented Parallel Accelerator Library for Exascal): Euclid3DGeometry Class Reference
Euclid3DGeometry Class Reference
#include <Euclid3DGeometry.h>
Public Member Functions
Euclid3DGeometry (Euclid3D transformation)
Euclid3DGeometry (const Euclid3DGeometry &right)
virtual ~Euclid3DGeometry ()
const Euclid3DGeometry & operator= (const Euclid3DGeometry &right)
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get geometry length.
virtual void setElementLength (double length)
Set geometry length.
virtual Euclid3D getTransform (double fromS, double toS) const
virtual Euclid3D getTransform (double fromS) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get total transform from beginning to end.
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
Private Attributes
Euclid3D transformation_m
Detailed Description
class Euclid3DGeometry
Euclid3DGeometry is a straight line from input to output followed by a rotation.
Definition at line 43 of file Euclid3DGeometry.h.
Constructor & Destructor Documentation
Euclid3DGeometry() [1/2]
Euclid3DGeometry::Euclid3DGeometry (Euclid3D transformation)
Definition at line 34 of file Euclid3DGeometry.cpp.
Euclid3DGeometry() [2/2]
Euclid3DGeometry::Euclid3DGeometry (const Euclid3DGeometry & right)
Definition at line 37 of file Euclid3DGeometry.cpp.
~Euclid3DGeometry()
Euclid3DGeometry::~Euclid3DGeometry () virtual
Definition at line 40 of file Euclid3DGeometry.cpp.
Member Function Documentation
getArcLength()
double Euclid3DGeometry::getArcLength () const virtual
Get arc length.
Implements BGeometryBase.
Definition at line 49 of file Euclid3DGeometry.cpp.
References dot(), Euclid3D::getVector(), and transformation_m.
Referenced by getElementLength(), and setElementLength().
getElementLength()
double Euclid3DGeometry::getElementLength () const virtual
Get geometry length.
Implements BGeometryBase.
Definition at line 53 of file Euclid3DGeometry.cpp.
References getArcLength().
getEntrance()
double BGeometryBase::getEntrance () const virtual inherited
Get entrance position.
Reimplemented in PlanarArcGeometry, StraightGeometry, and BeamlineGeometry.
Definition at line 33 of file Geometry.cpp.
References BGeometryBase::getOrigin().
Referenced by ElementBase::getEntrance(), BGeometryBase::getEntranceFrame(), and BGeometryBase::getTotalTransform().
getEntranceFrame()
Euclid3D BGeometryBase::getEntranceFrame () const virtual inherited
Get transform.
Reimplemented in PlanarArcGeometry, RBendGeometry, StraightGeometry, and BeamlineGeometry.
Definition at line 41 of file Geometry.cpp.
References BGeometryBase::getEntrance(), and BGeometryBase::getTransform().
Referenced by ElementBase::getEntranceFrame().
getEntrancePatch()
Euclid3D BGeometryBase::getEntrancePatch () const virtual inherited
Get patch.
Reimplemented in RBendGeometry.
Definition at line 45 of file Geometry.cpp.
References Euclid3D::identity().
Referenced by ElementBase::getEntrancePatch().
getExit()
double BGeometryBase::getExit () const virtual inherited
Get exit position.
Reimplemented in PlanarArcGeometry, StraightGeometry, and BeamlineGeometry.
Definition at line 35 of file Geometry.cpp.
References BGeometryBase::getArcLength(), and BGeometryBase::getOrigin().
Referenced by ElementBase::getExit(), BGeometryBase::getExitFrame(), and BGeometryBase::getTotalTransform().
getExitFrame()
Euclid3D BGeometryBase::getExitFrame () const virtual inherited
Get transform.
Reimplemented in PlanarArcGeometry, RBendGeometry, StraightGeometry, and BeamlineGeometry.
Definition at line 43 of file Geometry.cpp.
References BGeometryBase::getExit(), and BGeometryBase::getTransform().
Referenced by ElementBase::getExitFrame().
getExitPatch()
Euclid3D BGeometryBase::getExitPatch () const virtual inherited
Get patch.
Reimplemented in RBendGeometry.
Definition at line 47 of file Geometry.cpp.
References Euclid3D::identity().
Referenced by ElementBase::getExitPatch().
getOrigin()
double BGeometryBase::getOrigin () const virtual inherited
Get origin position.
Reimplemented in NullGeometry, PlanarArcGeometry, StraightGeometry, and BeamlineGeometry.
Definition at line 31 of file Geometry.cpp.
References BGeometryBase::getArcLength().
Referenced by BGeometryBase::getEntrance(), BGeometryBase::getExit(), and ElementBase::getOrigin().
getTotalTransform()
Euclid3D Euclid3DGeometry::getTotalTransform () const virtual
Get total transform from beginning to end.
Reimplemented from BGeometryBase.
Definition at line 73 of file Euclid3DGeometry.cpp.
References transformation_m.
getTransform() [1/2]
Euclid3D Euclid3DGeometry::getTransform (double s) const virtual
Get transform.
Reimplemented from BGeometryBase.
Definition at line 69 of file Euclid3DGeometry.cpp.
getTransform() [2/2]
Euclid3D Euclid3DGeometry::getTransform (double fromS, double toS) const virtual
Not Implemented - raises GeneralOpalException Get transform.
Implements BGeometryBase.
Definition at line 65 of file Euclid3DGeometry.cpp.
operator=()
const Euclid3DGeometry & Euclid3DGeometry::operator= (const Euclid3DGeometry & right)
Definition at line 42 of file Euclid3DGeometry.cpp.
References transformation_m.
setElementLength()
void Euclid3DGeometry::setElementLength (double length) virtual
Set geometry length.
Reimplemented from BGeometryBase.
Definition at line 55 of file Euclid3DGeometry.cpp.
References getArcLength(), Euclid3D::getVector(), Euclid3D::setDisplacement(), and transformation_m.
Member Data Documentation
transformation_m
Euclid3D Euclid3DGeometry::transformation_m private
Definition at line 79 of file Euclid3DGeometry.h.
Referenced by getArcLength(), getTotalTransform(), operator=(), and setElementLength().
The documentation for this class was generated from the following files:
Euclid3DGeometry.h
Euclid3DGeometry.cpp