OPALX (Object Oriented Parallel Accelerator Library for Exascal): BeamlineVisitor Class Reference
BeamlineVisitor Class Reference abstract
#include <BeamlineVisitor.h>
Public Member Functions
BeamlineVisitor ()
virtual ~BeamlineVisitor ()
virtual void execute ()=0
Execute the algorithm on the attached beam line.
virtual void visitBeamline (const Beamline &)=0
Apply the algorithm to a beam line.
virtual void visitComponent (const Component &)=0
Apply the algorithm to an arbitrary component.
virtual void visitConstantEFieldCavity (const ConstantEFieldCavity &)=0
Apply the algorithm to a constant E-field cavity element.
virtual void visitDrift (const Drift &)=0
Apply the algorithm to a drift space.
virtual void visitLaser (const Laser &)=0
Apply the algorithm to a laser element.
virtual void visitFlaggedElmPtr (const FlaggedElmPtr &)=0
Apply the algorithm to a FlaggedElmPtr.
virtual void visitMarker (const Marker &)=0
Apply the algorithm to a marker.
virtual void visitMonitor (const Monitor &)=0
Apply the algorithm to a beam position monitor.
virtual void visitMultipole (const Multipole &)=0
Apply the algorithm to a multipole.
virtual void visitMultipoleT (const MultipoleT &)=0
Apply the algorithm to an arbitrary multipole.
virtual void visitRBend (const RBend &)=0
Apply the algorithm to a rectangular bend.
virtual void visitRFCavity (const RFCavity &)=0
Apply the algorithm to a RF cavity.
virtual void visitVariableRFCavity (const VariableRFCavity &)=0
Apply the algorithm to a variable RF cavity.
virtual void visitScalingFFAMagnet (const ScalingFFAMagnet &)=0
virtual void visitRing (const Ring &)=0
Apply the algorithm to a Ring element.
virtual void visitSBend (const SBend &)=0
Apply the algorithm to a sector bend.
virtual void visitSolenoid (const Solenoid &)=0
Apply the algorithm to a Solenoid element.
virtual void visitTravelingWave (const TravelingWave &)=0
Apply the algorithm to a traveling wave.
virtual void visitVerticalFFAMagnet (const VerticalFFAMagnet &)=0
Apply the algorithm to a vertical FFA magnet.
virtual void visitProbe (const Probe &)=0
Apply the algorithm to a Probe.
Private Member Functions
BeamlineVisitor (const BeamlineVisitor &)
void operator= (const BeamlineVisitor &)
Detailed Description
Definition at line 63 of file BeamlineVisitor.h.
Constructor & Destructor Documentation
BeamlineVisitor() [1/2]
BeamlineVisitor::BeamlineVisitor ()
Definition at line 36 of file BeamlineVisitor.cpp.
Referenced by BeamlineVisitor(), operator=(), and SpecificElementVisitor< ELEM >::SpecificElementVisitor().
~BeamlineVisitor()
BeamlineVisitor::~BeamlineVisitor () virtual
Definition at line 38 of file BeamlineVisitor.cpp.
BeamlineVisitor() [2/2]
BeamlineVisitor::BeamlineVisitor (const BeamlineVisitor &) private
References BeamlineVisitor().
Member Function Documentation
execute()
virtual void BeamlineVisitor::execute () pure virtual
Execute the algorithm on the attached beam line.
Implemented in DefaultVisitor, ParallelTracker, RangeSelector, Selector, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
operator=()
void BeamlineVisitor::operator= (const BeamlineVisitor &) private
References BeamlineVisitor().
visitBeamline()
virtual void BeamlineVisitor::visitBeamline (const Beamline &) pure virtual
Apply the algorithm to a beam line.
Implemented in DefaultVisitor, ParallelTracker, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
Referenced by DummyBeamline::accept(), and TBeamline< T >::accept().
visitComponent()
virtual void BeamlineVisitor::visitComponent (const Component &) pure virtual
Apply the algorithm to an arbitrary component.
Implemented in DefaultVisitor, ParallelTracker, SpecificElementVisitor< ELEM >, TestMultipoleT, TestVariableRFCavity, and Tracker.
visitConstantEFieldCavity()
virtual void BeamlineVisitor::visitConstantEFieldCavity (const ConstantEFieldCavity &) pure virtual
Apply the algorithm to a constant E-field cavity element.
Implemented in DefaultVisitor, ParallelTracker, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
Referenced by ConstantEFieldCavity::accept().
visitDrift()
virtual void BeamlineVisitor::visitDrift (const Drift &) pure virtual
Apply the algorithm to a drift space.
Implemented in DefaultVisitor, ParallelTracker, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
Referenced by Drift::accept().
visitFlaggedElmPtr()
virtual void BeamlineVisitor::visitFlaggedElmPtr (const FlaggedElmPtr &) pure virtual
Apply the algorithm to a FlaggedElmPtr.
Implemented in DefaultVisitor, Flagger, RangeSelector, Replacer, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
Referenced by FlaggedElmPtr::accept().
visitLaser()
virtual void BeamlineVisitor::visitLaser (const Laser &) pure virtual
Apply the algorithm to a laser element.
Implemented in DefaultVisitor, ParallelTracker, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
Referenced by Laser::accept().
visitMarker()
virtual void BeamlineVisitor::visitMarker (const Marker &) pure virtual
Apply the algorithm to a marker.
Implemented in DefaultVisitor, ParallelTracker, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
Referenced by Marker::accept().
visitMonitor()
virtual void BeamlineVisitor::visitMonitor (const Monitor &) pure virtual
Apply the algorithm to a beam position monitor.
Implemented in DefaultVisitor, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
Referenced by Monitor::accept().
visitMultipole()
virtual void BeamlineVisitor::visitMultipole (const Multipole &) pure virtual
Apply the algorithm to a multipole.
Implemented in DefaultVisitor, ParallelTracker, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
Referenced by Multipole::accept().
visitMultipoleT()
virtual void BeamlineVisitor::visitMultipoleT (const MultipoleT &) pure virtual
Apply the algorithm to an arbitrary multipole.
Implemented in DefaultVisitor, ParallelTracker, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
Referenced by MultipoleT::accept().
visitProbe()
virtual void BeamlineVisitor::visitProbe (const Probe &) pure virtual
Apply the algorithm to a Probe.
Implemented in DefaultVisitor, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
Referenced by Probe::accept().
visitRBend()
virtual void BeamlineVisitor::visitRBend (const RBend &) pure virtual
Apply the algorithm to a rectangular bend.
Implemented in DefaultVisitor, ParallelTracker, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
Referenced by RBend::accept().
visitRFCavity()
virtual void BeamlineVisitor::visitRFCavity (const RFCavity &) pure virtual
Apply the algorithm to a RF cavity.
Implemented in DefaultVisitor, ParallelTracker, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
Referenced by RFCavity::accept().
visitRing()
virtual void BeamlineVisitor::visitRing (const Ring &) pure virtual
Apply the algorithm to a Ring element.
Implemented in DefaultVisitor, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
Referenced by Ring::accept().
visitSBend()
virtual void BeamlineVisitor::visitSBend (const SBend &) pure virtual
Apply the algorithm to a sector bend.
Implemented in DefaultVisitor, ParallelTracker, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
Referenced by SBend::accept().
visitScalingFFAMagnet()
virtual void BeamlineVisitor::visitScalingFFAMagnet (const ScalingFFAMagnet &) pure virtual
Implemented in DefaultVisitor, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
Referenced by ScalingFFAMagnet::accept().
visitSolenoid()
virtual void BeamlineVisitor::visitSolenoid (const Solenoid &) pure virtual
Apply the algorithm to a Solenoid element.
Implemented in DefaultVisitor, ParallelTracker, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
Referenced by Solenoid::accept().
visitTravelingWave()
virtual void BeamlineVisitor::visitTravelingWave (const TravelingWave &) pure virtual
Apply the algorithm to a traveling wave.
Implemented in DefaultVisitor, ParallelTracker, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
Referenced by TravelingWave::accept().
visitVariableRFCavity()
virtual void BeamlineVisitor::visitVariableRFCavity (const VariableRFCavity &) pure virtual
Apply the algorithm to a variable RF cavity.
Implemented in DefaultVisitor, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
Referenced by VariableRFCavity::accept().
visitVerticalFFAMagnet()
virtual void BeamlineVisitor::visitVerticalFFAMagnet (const VerticalFFAMagnet &) pure virtual
Apply the algorithm to a vertical FFA magnet.
Implemented in DefaultVisitor, SpecificElementVisitor< ELEM >, TestMultipoleT, and TestVariableRFCavity.
Referenced by VerticalFFAMagnet::accept().
The documentation for this class was generated from the following files:
BeamlineVisitor.h
BeamlineVisitor.cpp