OPALX (Object Oriented Parallel Accelerator Library for Exascal): IndexMap::OutOfBounds Class Reference
IndexMap::OutOfBounds Class Reference
#include <IndexMap.h>
Public Member Functions
OutOfBounds (const std::string &meth, const std::string &msg)
OutOfBounds (const OutOfBounds &rhs)
virtual ~OutOfBounds ()
virtual const std::string & what () const
Return the message string for the exception.
virtual const std::string & where () const
Return the name of the method or function which detected the exception.
Private Member Functions
OutOfBounds ()
Private Attributes
const std::string message
const std::string method
Detailed Description
Definition at line 65 of file IndexMap.h.
Constructor & Destructor Documentation
OutOfBounds() [1/3]
IndexMap::OutOfBounds::OutOfBounds (const std::string & meth, const std::string & msg) inline
Definition at line 67 of file IndexMap.h.
References OpalException::OpalException().
Referenced by OutOfBounds().
OutOfBounds() [2/3]
IndexMap::OutOfBounds::OutOfBounds (const OutOfBounds & rhs) inline
Definition at line 69 of file IndexMap.h.
References OpalException::OpalException(), and OutOfBounds().
~OutOfBounds()
virtual IndexMap::OutOfBounds::~OutOfBounds () inline virtual
Definition at line 71 of file IndexMap.h.
OutOfBounds() [3/3]
IndexMap::OutOfBounds::OutOfBounds () private
Member Function Documentation
what()
const std::string & OpalException::what () const virtual inherited
Return the message string for the exception.
Definition at line 31 of file OpalException.cpp.
References message.
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), main(), OpalParser::readStatement(), OpalParser::run(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and TEST_F().
where()
const std::string & OpalException::where () const virtual inherited
Return the name of the method or function which detected the exception.
Definition at line 33 of file OpalException.cpp.
References method.
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), main(), OpalParser::run(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and TEST_F().
Member Data Documentation
message
const std::string OpalException::message private inherited
Definition at line 56 of file OpalException.h.
Referenced by OpalException(), OpalException(), and what().
method
const std::string OpalException::method private inherited
Definition at line 57 of file OpalException.h.
Referenced by DivideError::DivideError(), OpalException(), OpalException(), and where().
The documentation for this class was generated from the following file:
IndexMap.h