OPALX (Object Oriented Parallel Accelerator Library for Exascal): Channel Class Reference
Channel Class Reference abstract
Abstract interface for read/write access to variable.
#include <Channel.h>
Public Member Functions
Channel ()
virtual ~Channel ()
virtual Channel * clone () const =0
Duplicate the channel.
double operator= (double value)
Assign [b]value[/b] to channel.
double operator+= (double value)
Add and assign [b]value[/b] to channel.
double operator-= (double value)
Subtract and assign [b]value[/b] to channel.
virtual bool set (double value)=0
Store [b]value[/b] into channel.
virtual bool isSettable () const
Test if settable.
virtual bool get (double &value) const =0
Read channel.
operator double () const
Read channel.
Private Member Functions
Channel (const Channel &)
const Channel & operator= (const Channel &)
Detailed Description
Abstract interface for read/write access to variable.
Definition at line 30 of file Channel.h.
Constructor & Destructor Documentation
Channel() [1/2]
Channel::Channel ()
Definition at line 26 of file Channel.cpp.
References ConstChannel::ConstChannel().
Referenced by Channel(), clone(), DirectChannel::DirectChannel(), IndexedChannel< T >::IndexedChannel(), IndirectChannel< T >::IndirectChannel(), and operator=().
~Channel()
Channel::~Channel () virtual
Definition at line 28 of file Channel.cpp.
Channel() [2/2]
Channel::Channel (const Channel &) private
References Channel().
Member Function Documentation
clone()
virtual Channel * Channel::clone () const pure virtual
Duplicate the channel.
Implements ConstChannel.
Implemented in DirectChannel, IndexedChannel< T >, and IndirectChannel< T >.
References Channel().
get()
virtual bool ConstChannel::get (double & value) const pure virtual inherited
Read channel.
Implemented in DirectChannel, IndexedChannel< T >, and IndirectChannel< T >.
Referenced by operator double(), Channel::operator+=(), and Channel::operator-=().
isSettable()
bool Channel::isSettable () const virtual
Test if settable.
Reimplemented from ConstChannel.
Reimplemented in IndexedChannel< T >, and IndirectChannel< T >.
Definition at line 30 of file Channel.cpp.
Referenced by ElementBase::setAttribute().
operator double()
ConstChannel::operator double () const inline inherited
Read channel.
Definition at line 43 of file ConstChannel.h.
References get().
operator+=()
double Channel::operator+= (double value) inline
Add and assign [b]value[/b] to channel.
Definition at line 45 of file Channel.h.
References ConstChannel::get(), and set().
operator-=()
double Channel::operator-= (double value) inline
Subtract and assign [b]value[/b] to channel.
Definition at line 54 of file Channel.h.
References ConstChannel::get(), and set().
operator=() [1/2]
const Channel & Channel::operator= (const Channel &) private
References Channel().
operator=() [2/2]
double Channel::operator= (double value) inline
Assign [b]value[/b] to channel.
Definition at line 39 of file Channel.h.
References set().
set()
virtual bool Channel::set (double value) pure virtual
Store [b]value[/b] into channel.
Implemented in DirectChannel, IndexedChannel< T >, and IndirectChannel< T >.
Referenced by operator+=(), operator-=(), and operator=().
The documentation for this class was generated from the following files:
Channel.h
Channel.cpp