OPALX (Object Oriented Parallel Accelerator Library for Exascal): TrackParser Class Reference
TrackParser Class Reference
#include <TrackParser.h>
Public Member Functions
TrackParser ()
virtual ~TrackParser ()
virtual void parse (Statement &) const
Parse and execute current statement.
virtual Statement * readStatement (TokenStream *) const
Read complete statement from a token stream.
virtual void run () const
Read current stream.
virtual void run (TokenStream *) const
Read given stream.
void stop () const
Set stop flag.
Static Public Member Functions
static Token readToken ()
Return next input token.
Protected Member Functions
virtual Object * find (const std::string &) const
Find object by name in the track command directory.
void execute (Object *, const std::string &) const
Execute or check the current command.
virtual void parseAction (Statement &) const
Parse executable command.
virtual void parseAssign (Statement &) const
Parse assignment statement.
virtual void parseDefine (Statement &) const
Parse definition.
virtual void parseEnd (Statement &) const
Check for end of statement.
virtual void parseMacro (const std::string &name, Statement &) const
Parse macro definition or call.
virtual void printHelp (const std::string &) const
Print help on named command.
Private Member Functions
TrackParser (const TrackParser &)
void operator= (const TrackParser &)
Static Private Member Functions
static void parseBracketList (char close, Statement &)
static void parseTokenList (Statement &)
static std::string getHint (const std::string &, const std::string &="attribute")
Private Attributes
Directory trackDirectory
bool stopFlag
Static Private Attributes
static std::vector< std::shared_ptr< TokenStream > > inputStack
Detailed Description
Definition at line 28 of file TrackParser.h.
Constructor & Destructor Documentation
TrackParser() [1/2]
TrackParser::TrackParser ()
Definition at line 25 of file TrackParser.cpp.
References Directory::insert(), and trackDirectory.
~TrackParser()
TrackParser::~TrackParser () virtual
Definition at line 32 of file TrackParser.cpp.
TrackParser() [2/2]
TrackParser::TrackParser (const TrackParser &) private
Member Function Documentation
execute()
void OpalParser::execute (Object * object, const std::string & name) const protected inherited
Execute or check the current command.
Definition at line 118 of file OpalParser.cpp.
References OpalData::getInstance(), gmsg, Options::mtrace, Object::shouldTrace(), Object::shouldUpdate(), and OpalData::update().
Referenced by OpalParser::parseAction(), OpalParser::parseDefine(), and OpalParser::parseMacro().
find()
Object * TrackParser::find (const std::string & name) const protected virtual
Find object by name in the track command directory.
Reimplemented from OpalParser.
Definition at line 36 of file TrackParser.cpp.
References Directory::find(), and trackDirectory.
getHint()
std::string OpalParser::getHint (const std::string & name, const std::string & type = "attribute") static private inherited
Definition at line 623 of file OpalParser.cpp.
References AttributeHandler::COMMAND, AttributeHandler::ELEMENT, AttributeHandler::getOwner(), AttributeHandler::STATEMENT, and AttributeHandler::SUB_COMMAND.
Referenced by OpalParser::parse(), and OpalParser::parseAction().
operator=()
void TrackParser::operator= (const TrackParser &) private
parse()
void OpalParser::parse (Statement & stat) const virtual inherited
Parse and execute current statement.
Implements Parser.
Reimplemented in SequenceParser.
Definition at line 62 of file OpalParser.cpp.
References Statement::atEnd(), Statement::delimiter(), OpalParser::find(), Statement::getCurrent(), OpalParser::getHint(), OpalData::getInstance(), Token::getLex(), Statement::keyword(), Statement::mark(), OpalParser::parseAction(), OpalParser::parseAssign(), OpalParser::parseDefine(), OpalParser::parseMacro(), Expressions::parseString(), Statement::position(), Statement::print(), OpalParser::printHelp(), Statement::restore(), and Statement::start().
parseAction()
void OpalParser::parseAction (Statement & stat) const protected virtual inherited
Parse executable command.
Definition at line 146 of file OpalParser.cpp.
References Object::clone(), Statement::delimiter(), OpalParser::execute(), OpalParser::find(), OpalParser::getHint(), Object::parse(), OpalParser::parseEnd(), Expressions::parseString(), OpalParser::printHelp(), Statement::start(), and OpalParser::stopFlag.
Referenced by OpalParser::parse().
parseAssign()
void OpalParser::parseAssign (Statement & stat) const protected virtual inherited
Parse assignment statement.
Definition at line 179 of file OpalParser.cpp.
References Object::clone(), OpalData::define(), Statement::delimiter(), OpalParser::find(), OpalData::find(), Object::findAttribute(), OpalData::getInstance(), Object::isTreeMember(), Statement::keyword(), OpalData::makeDirty(), Expressions::parseDelimiter(), OpalParser::parseEnd(), Expressions::parseRealConst(), Expressions::parseString(), and Statement::start().
Referenced by OpalParser::parse().
parseBracketList()
void OpalParser::parseBracketList (char close, Statement & stat) static private inherited
Definition at line 437 of file OpalParser.cpp.
References Statement::append(), Token::isDel(), Token::isEOF(), OpalParser::parseBracketList(), and OpalParser::readToken().
Referenced by OpalParser::parseBracketList(), OpalParser::parseTokenList(), and OpalParser::readStatement().
parseDefine()
void OpalParser::parseDefine (Statement & stat) const protected virtual inherited
Parse definition.
Definition at line 312 of file OpalParser.cpp.
References Object::clone(), OpalData::define(), Statement::delimiter(), OpalParser::execute(), OpalParser::find(), OpalData::getInstance(), Statement::keyword(), Object::makeInstance(), Object::parse(), OpalParser::parseEnd(), Expressions::parseString(), Object::setShared(), and Statement::start().
Referenced by OpalParser::parse().
parseEnd()
void OpalParser::parseEnd (Statement & stat) const protected virtual inherited
Check for end of statement.
Definition at line 359 of file OpalParser.cpp.
References Statement::atEnd(), Statement::delimiter(), Statement::position(), and Statement::print().
Referenced by SequenceParser::parse(), OpalParser::parseAction(), OpalParser::parseAssign(), OpalParser::parseDefine(), and SequenceParser::parseMember().
parseMacro()
void OpalParser::parseMacro (const std::string & name, Statement & stat) const protected virtual inherited
Parse macro definition or call.
Definition at line 372 of file OpalParser.cpp.
References OpalData::define(), Statement::delimiter(), OpalParser::execute(), OpalParser::find(), Statement::getCurrent(), OpalData::getInstance(), OpalParser::inputStack, Object::makeInstance(), Object::makeTemplate(), Statement::mark(), Expressions::parseString(), and Statement::restore().
Referenced by OpalParser::parse().
parseTokenList()
void OpalParser::parseTokenList (Statement & stat) static private inherited
Definition at line 457 of file OpalParser.cpp.
References Statement::append(), Token::isDel(), Token::isEOF(), OpalParser::parseBracketList(), and OpalParser::readToken().
Referenced by OpalParser::readStatement().
printHelp()
void OpalParser::printHelp (const std::string & cmdName) const protected virtual inherited
Print help on named command.
Definition at line 427 of file OpalParser.cpp.
References OpalParser::find(), and gmsg.
Referenced by OpalParser::parse(), and OpalParser::parseAction().
readStatement()
Statement * OpalParser::readStatement (TokenStream * is) const virtual inherited
Read complete statement from a token stream.
Todo:
check this /stat->printWhere(*IpplInfo::Error, true);
Implements Parser.
Definition at line 486 of file OpalParser.cpp.
References Statement::append(), Token::getFile(), Token::getLine(), gmsg, OpalParser::inputStack, Token::isDel(), Token::isEOF(), Token::isKey(), Token::isString(), Token::isWord(), OpalParser::parseBracketList(), OpalParser::parseTokenList(), OpalParser::readStatement(), TokenStream::readToken(), Statement::start(), and OpalException::what().
Referenced by OpalParser::readStatement(), and OpalParser::run().
readToken()
Token OpalParser::readToken () static inherited
Return next input token.
Definition at line 478 of file OpalParser.cpp.
References OpalParser::inputStack, and Token::IS_EOF.
Referenced by OpalParser::parseBracketList(), and OpalParser::parseTokenList().
run() [1/2]
void OpalParser::run () const virtual inherited
Read current stream.
Definition at line 584 of file OpalParser.cpp.
References Statement::execute(), OpalParser::inputStack, OpalParser::readStatement(), OpalParser::stopFlag, OpalException::what(), and OpalException::where().
Referenced by Call::execute(), TrackCmd::execute(), main(), SequenceTemplate::makeInstance(), Sequence::parse(), and OpalParser::run().
run() [2/2]
void OpalParser::run (TokenStream * is) const virtual inherited
Read given stream.
Implements Parser.
Definition at line 613 of file OpalParser.cpp.
References OpalParser::inputStack, and OpalParser::run().
stop()
void OpalParser::stop () const inherited
Set stop flag.
Definition at line 619 of file OpalParser.cpp.
References OpalParser::stopFlag.
Referenced by TrackEnd::execute(), and SequenceParser::parse().
Member Data Documentation
inputStack
std::vector< std::shared_ptr< TokenStream > > OpalParser::inputStack static private inherited
Definition at line 119 of file OpalParser.h.
Referenced by OpalParser::parseMacro(), OpalParser::readStatement(), OpalParser::readToken(), OpalParser::run(), and OpalParser::run().
stopFlag
bool OpalParser::stopFlag mutable private inherited
Definition at line 116 of file OpalParser.h.
Referenced by OpalParser::parseAction(), OpalParser::run(), and OpalParser::stop().
trackDirectory
Directory TrackParser::trackDirectory private
Definition at line 47 of file TrackParser.h.
Referenced by find(), and TrackParser().
The documentation for this class was generated from the following files:
TrackParser.h
TrackParser.cpp