OPALX (Object Oriented Parallel Accelerator Library for Exascal): Euclid3D Class Reference
Euclid3D Class Reference
Displacement and rotation in space.
#include <Euclid3D.h>
Public Member Functions
Euclid3D ()
Default constructor.
Euclid3D (const Vector3D &V, const Rotation3D &R)
Constructor/.
Euclid3D (double x, double y, double z, double vx, double vy, double vz)
Constructor.
bool operator== (const Euclid3D &) const
bool operator!= (const Euclid3D &) const
void getAll (double &x, double &y, double &z, double &vx, double &vy, double &vz) const
Unpack.
double getX () const
Get displacement.
double getY () const
Get displacement.
double getZ () const
Get displacement.
const Vector3D & getVector () const
Get displacement.
const Rotation3D & getRotation () const
Get rotation.
double M (int row, int col) const
Get component.
void setX (double x)
Set displacement.
void setY (double y)
Set displacement.
void setZ (double z)
Set displacement.
void setDisplacement (const Vector3D &V)
Set displacement.
void setRotation (const Rotation3D &R)
Set rotation.
Euclid3D dot (const Euclid3D &rhs) const
Dot product.
const Euclid3D & dotBy (const Euclid3D &rhs)
Dot product with assign.
Euclid3D operator* (const Euclid3D &rhs) const
Dot product.
const Euclid3D & operator*= (const Euclid3D &rhs)
Dot product with assign.
Euclid3D inverse () const
Inverse.
bool isIdentity () const
Test for identity.
bool isPureTranslation () const
Test for translation.
bool isPureXRotation () const
Test for rotation.
bool isPureYRotation () const
Test for rotation.
bool isPureZRotation () const
Test for rotation.
Static Public Member Functions
static Euclid3D identity ()
Make identity.
static Euclid3D translation (double x, double y, double z)
Make translation.
static Euclid3D XRotation (double angle)
Make rotation.
static Euclid3D YRotation (double angle)
Make rotation.
static Euclid3D ZRotation (double angle)
Make rotation.
Private Attributes
Vector3D V
Rotation3D R
bool is_identity
Detailed Description
Displacement and rotation in space.
Definition at line 67 of file Euclid3D.h.
Constructor & Destructor Documentation
Euclid3D() [1/3]
Euclid3D::Euclid3D () inline
Default constructor.
Definition at line 204 of file Euclid3D.h.
Referenced by identity(), inverse(), translation(), XRotation(), YRotation(), and ZRotation().
Euclid3D() [2/3]
Euclid3D::Euclid3D (const Vector3D & V, const Rotation3D & R)
Constructor/.
Definition at line 33 of file Euclid3D.cpp.
Euclid3D() [3/3]
Euclid3D::Euclid3D (double x, double y, double z, double vx, double vy, double vz)
Constructor.
Definition at line 30 of file Euclid3D.cpp.
Member Function Documentation
dot()
Euclid3D Euclid3D::dot (const Euclid3D & rhs) const
Dot product.
Definition at line 65 of file Euclid3D.cpp.
References dotBy().
dotBy()
const Euclid3D & Euclid3D::dotBy (const Euclid3D & rhs)
Dot product with assign.
Definition at line 70 of file Euclid3D.cpp.
References is_identity, R, and V.
Referenced by dot(), TBeamline< T >::getTotalTransform(), operator*(), and operator*=().
getAll()
void Euclid3D::getAll (double & x, double & y, double & z, double & vx, double & vy, double & vz) const
Unpack.
Definition at line 40 of file Euclid3D.cpp.
References Rotation3D::getAxis(), Vector3D::getComponents(), R, and V.
getRotation()
const Rotation3D & Euclid3D::getRotation () const
Get rotation.
Definition at line 47 of file Euclid3D.cpp.
References R.
Referenced by Ring::appendElement(), Ring::checkMidplane(), Ring::getRotationStartToEnd(), and Ring::rotateToCyclCoordinates().
getVector()
const Vector3D & Euclid3D::getVector () const
Get displacement.
Definition at line 45 of file Euclid3D.cpp.
References V.
Referenced by Ring::appendElement(), Ring::checkMidplane(), Euclid3DGeometry::getArcLength(), BendBase::getChordLength(), Ring::rotateToCyclCoordinates(), and Euclid3DGeometry::setElementLength().
getX()
double Euclid3D::getX () const inline
Get displacement.
Definition at line 206 of file Euclid3D.h.
References Vector3D::getX(), and V.
getY()
double Euclid3D::getY () const inline
Get displacement.
Definition at line 208 of file Euclid3D.h.
References Vector3D::getY(), and V.
getZ()
double Euclid3D::getZ () const inline
Get displacement.
Definition at line 210 of file Euclid3D.h.
References Vector3D::getZ(), and V.
identity()
Euclid3D Euclid3D::identity () static
Make identity.
Definition at line 97 of file Euclid3D.cpp.
References Euclid3D().
Referenced by BGeometryBase::getEntrancePatch(), BGeometryBase::getExitPatch(), NullGeometry::getTransform(), and NullGeometry::getTransform().
inverse()
Euclid3D Euclid3D::inverse () const
Inverse.
Definition at line 84 of file Euclid3D.cpp.
References Euclid3D(), Rotation3D::inverse(), R, and V.
Referenced by Inverse().
isIdentity()
bool Euclid3D::isIdentity () const inline
Test for identity.
Definition at line 214 of file Euclid3D.h.
References is_identity.
isPureTranslation()
bool Euclid3D::isPureTranslation () const
Test for translation.
Definition at line 89 of file Euclid3D.cpp.
References Rotation3D::isIdentity(), and R.
isPureXRotation()
bool Euclid3D::isPureXRotation () const
Test for rotation.
Definition at line 91 of file Euclid3D.cpp.
References Rotation3D::isPureXRotation(), Vector3D::isZero(), R, and V.
isPureYRotation()
bool Euclid3D::isPureYRotation () const
Test for rotation.
Definition at line 93 of file Euclid3D.cpp.
References Rotation3D::isPureYRotation(), Vector3D::isZero(), R, and V.
isPureZRotation()
bool Euclid3D::isPureZRotation () const
Test for rotation.
Definition at line 95 of file Euclid3D.cpp.
References Rotation3D::isPureZRotation(), Vector3D::isZero(), R, and V.
M()
double Euclid3D::M (int row, int col) const inline
Get component.
Definition at line 212 of file Euclid3D.h.
References R.
operator!=()
bool Euclid3D::operator!= (const Euclid3D & rhs) const
Definition at line 38 of file Euclid3D.cpp.
References R, and V.
operator*()
Euclid3D Euclid3D::operator* (const Euclid3D & rhs) const
Dot product.
Definition at line 77 of file Euclid3D.cpp.
References dotBy().
operator*=()
const Euclid3D & Euclid3D::operator*= (const Euclid3D & rhs)
Dot product with assign.
Definition at line 82 of file Euclid3D.cpp.
References dotBy().
operator==()
bool Euclid3D::operator== (const Euclid3D & rhs) const
Definition at line 36 of file Euclid3D.cpp.
References R, and V.
setDisplacement()
void Euclid3D::setDisplacement (const Vector3D & V)
Set displacement.
Definition at line 55 of file Euclid3D.cpp.
References is_identity, Vector3D::isZero(), and V.
Referenced by Euclid3DGeometry::setElementLength().
setRotation()
void Euclid3D::setRotation (const Rotation3D & R)
Set rotation.
Definition at line 60 of file Euclid3D.cpp.
References is_identity, Rotation3D::isIdentity(), and R.
setX()
void Euclid3D::setX (double x)
Set displacement.
Definition at line 49 of file Euclid3D.cpp.
References Vector3D::setX(), and V.
setY()
void Euclid3D::setY (double y)
Set displacement.
Definition at line 51 of file Euclid3D.cpp.
References Vector3D::setY(), and V.
setZ()
void Euclid3D::setZ (double z)
Set displacement.
Definition at line 53 of file Euclid3D.cpp.
References Vector3D::setZ(), and V.
translation()
Euclid3D Euclid3D::translation (double x, double y, double z) static
Make translation.
Definition at line 99 of file Euclid3D.cpp.
References Euclid3D(), and Rotation3D::Identity().
Referenced by StraightGeometry::getEntranceFrame(), RBendGeometry::getEntrancePatch(), StraightGeometry::getExitFrame(), RBendGeometry::getExitPatch(), StraightGeometry::getTotalTransform(), StraightGeometry::getTransform(), and StraightGeometry::getTransform().
XRotation()
Euclid3D Euclid3D::XRotation (double angle) static
Make rotation.
Definition at line 103 of file Euclid3D.cpp.
References Euclid3D(), is_identity, and Rotation3D::XRotation().
YRotation()
Euclid3D Euclid3D::YRotation (double angle) static
Make rotation.
Definition at line 109 of file Euclid3D.cpp.
References Euclid3D(), is_identity, and Rotation3D::YRotation().
Referenced by RBendGeometry::getEntranceFrame(), RBendGeometry::getEntrancePatch(), RBendGeometry::getExitFrame(), RBendGeometry::getExitPatch(), and RBendGeometry::getTotalTransform().
ZRotation()
Euclid3D Euclid3D::ZRotation (double angle) static
Make rotation.
Definition at line 115 of file Euclid3D.cpp.
References Euclid3D(), is_identity, and Rotation3D::ZRotation().
Member Data Documentation
is_identity
bool Euclid3D::is_identity mutable private
Definition at line 192 of file Euclid3D.h.
Referenced by dotBy(), isIdentity(), setDisplacement(), setRotation(), XRotation(), YRotation(), and ZRotation().
R
Rotation3D Euclid3D::R private
Definition at line 191 of file Euclid3D.h.
Referenced by dotBy(), getAll(), getRotation(), inverse(), isPureTranslation(), isPureXRotation(), isPureYRotation(), isPureZRotation(), M(), operator!=(), operator==(), and setRotation().
V
Vector3D Euclid3D::V private
Definition at line 190 of file Euclid3D.h.
Referenced by dotBy(), getAll(), getVector(), getX(), getY(), getZ(), inverse(), isPureXRotation(), isPureYRotation(), isPureZRotation(), operator!=(), operator==(), setDisplacement(), setX(), setY(), and setZ().
The documentation for this class was generated from the following files:
Euclid3D.h
Euclid3D.cpp