OPALX (Object Oriented Parallel Accelerator Library for Exascal): Random Class Reference
Random Class Reference
The OPALX expression random generator.
#include <ExpressionRandom.h>
Public Member Functions
Random ()
Constructor with default seed.
Random (int seed)
Constructor with given seed.
~Random ()
void reseed (int seed=123456789)
Set a new seed.
double uniform ()
Uniform distribution.
void gauss (double &gr1, double &gr2)
Gaussian distribution.
int integer ()
Uniform distribution.
void init55 (int seed)
Initialise random number generator.
Private Member Functions
void irngen ()
Private Attributes
int irn [nr]
int next
Detailed Description
The OPALX expression random generator.
Definition at line 35 of file ExpressionRandom.h.
Constructor & Destructor Documentation
Random() [1/2]
Random::Random ()
Constructor with default seed.
Definition at line 27 of file ExpressionRandom.cpp.
References init55().
Random() [2/2]
Random::Random (int seed)
Constructor with given seed.
Definition at line 33 of file ExpressionRandom.cpp.
References init55().
~Random()
Random::~Random ()
Definition at line 36 of file ExpressionRandom.cpp.
Member Function Documentation
gauss()
void Random::gauss (double & gr1, double & gr2)
Gaussian distribution.
Definition at line 51 of file ExpressionRandom.cpp.
References uniform().
Referenced by Expressions::gauss(), and Expressions::Tgauss().
init55()
void Random::init55 (int seed)
Initialise random number generator.
Definition at line 76 of file ExpressionRandom.cpp.
References irn, irngen(), next, and nr.
Referenced by Option::execute(), Random(), Random(), and reseed().
integer()
int Random::integer ()
Uniform distribution.
Definition at line 69 of file ExpressionRandom.cpp.
References irn, irngen(), next, and nr.
irngen()
void Random::irngen () private
Definition at line 106 of file ExpressionRandom.cpp.
References irn, next, and nr.
Referenced by init55(), integer(), and uniform().
reseed()
void Random::reseed (int seed = 123456789)
Set a new seed.
Definition at line 39 of file ExpressionRandom.cpp.
References init55().
uniform()
double Random::uniform ()
Uniform distribution.
Definition at line 42 of file ExpressionRandom.cpp.
References irn, irngen(), next, and nr.
Referenced by gauss(), and Expressions::ranf().
Member Data Documentation
irn
int Random::irn[nr] private
Definition at line 71 of file ExpressionRandom.h.
Referenced by init55(), integer(), irngen(), and uniform().
next
int Random::next private
Definition at line 74 of file ExpressionRandom.h.
Referenced by init55(), integer(), irngen(), and uniform().
The documentation for this class was generated from the following files:
ExpressionRandom.h
ExpressionRandom.cpp