OPALX (Object Oriented Parallel Accelerator Library for Exascal): OscillatingField< Field > Class Template Reference
OscillatingField< Field > Class Template Reference
An oscillating electromagnetic field.
#include <OscillatingField.h>
Inherits Field.
Public Member Functions
OscillatingField ()
Default constructor.
virtual ~OscillatingField ()
virtual double getFrequency () const
Return the RF frequency in Hz.
virtual double getPhase () const
Return the RF phase in rad.
virtual void setFrequency (double f)
Assign the RF frequency in Hz.
virtual void setPhase (double phi)
Assign the RF phase in rad.
virtual EVector Efield (const Point3D &point) const
Get field.
virtual EVector Efield (const Point3D &point, double time) const
Get field.
virtual BVector Bfield (const Point3D &point) const
Get field.
virtual BVector Bfield (const Point3D &point, double time) const
Get field.
Private Attributes
double frequency
double phase
Detailed Description
template<class Field>
class OscillatingField< Field >
An oscillating electromagnetic field.
Definition at line 38 of file OscillatingField.h.
Constructor & Destructor Documentation
OscillatingField()
template<class Field > OscillatingField< Field >::OscillatingField ()
Default constructor.
Definition at line 84 of file OscillatingField.h.
~OscillatingField()
template<class Field > OscillatingField< Field >::~OscillatingField () virtual
Definition at line 87 of file OscillatingField.h.
Member Function Documentation
Bfield() [1/2]
template<class Field > BVector OscillatingField< Field >::Bfield (const Point3D & point) const virtual
Get field.
Definition at line 120 of file OscillatingField.h.
Bfield() [2/2]
template<class Field > BVector OscillatingField< Field >::Bfield (const Point3D & point, double time) const virtual
Get field.
Definition at line 125 of file OscillatingField.h.
Efield() [1/2]
template<class Field > EVector OscillatingField< Field >::Efield (const Point3D & point) const virtual
Get field.
Definition at line 110 of file OscillatingField.h.
Efield() [2/2]
template<class Field > EVector OscillatingField< Field >::Efield (const Point3D & point, double time) const virtual
Get field.
Definition at line 115 of file OscillatingField.h.
getFrequency()
template<class Field > double OscillatingField< Field >::getFrequency () const inline virtual
Return the RF frequency in Hz.
Definition at line 90 of file OscillatingField.h.
Referenced by RFCavityRep::getFrequency(), and TravelingWaveRep::getFrequency().
getPhase()
template<class Field > double OscillatingField< Field >::getPhase () const inline virtual
Return the RF phase in rad.
Definition at line 95 of file OscillatingField.h.
Referenced by RFCavityRep::getPhase(), and TravelingWaveRep::getPhase().
setFrequency()
template<class Field > void OscillatingField< Field >::setFrequency (double f) inline virtual
Assign the RF frequency in Hz.
Definition at line 100 of file OscillatingField.h.
Referenced by RFCavityRep::setFrequency(), and TravelingWaveRep::setFrequency().
setPhase()
template<class Field > void OscillatingField< Field >::setPhase (double phi) inline virtual
Assign the RF phase in rad.
Definition at line 105 of file OscillatingField.h.
Referenced by RFCavityRep::setPhase(), and TravelingWaveRep::setPhase().
Member Data Documentation
frequency
template<class Field > double OscillatingField< Field >::frequency private
Definition at line 76 of file OscillatingField.h.
phase
template<class Field > double OscillatingField< Field >::phase private
Definition at line 77 of file OscillatingField.h.
The documentation for this class was generated from the following file:
OscillatingField.h