OPALX (Object Oriented Parallel Accelerator Library for Exascal): SolenoidPlacementTest Class Reference
SolenoidPlacementTest Class Reference
Inherits testing::Test.
Classes
class TestableFieldSolverCmd
Protected Member Functions
void SetUp () override
void TearDown () override
std::shared_ptr< PartBunch_t > makeBunch (const size_t numParticles)
std::filesystem::path writeXZFieldmap (const std::string &filename, double zBeginCm, double zEndCm, int nz, double rBeginCm, double rEndCm, int nr, double bzValue=1.0, double brValue=0.0)
std::filesystem::path outputPath (const std::string &suffix) const
void cleanupOutputs () const
Static Protected Member Functions
static void SetUpTestSuite ()
static void TearDownTestSuite ()
static std::tuple< double, double, double > parsePositionLine (const std::string &line)
static std::vector< std::string > splitWhitespace (const std::string &line)
Protected Attributes
std::string testStem_
std::filesystem::path fieldmapFile_
std::shared_ptr< FieldSolverCmd > fsCmdBase_m
std::shared_ptr< DataSink > dataSink_m
Detailed Description
Definition at line 28 of file TestSolenoid.cpp.
Member Function Documentation
cleanupOutputs()
void SolenoidPlacementTest::cleanupOutputs () const inline protected
Definition at line 122 of file TestSolenoid.cpp.
References fieldmapFile_, and outputPath().
Referenced by SetUp(), and TearDown().
makeBunch()
std::shared_ptr< PartBunch_t > SolenoidPlacementTest::makeBunch (const size_t numParticles) inline protected
Definition at line 77 of file TestSolenoid.cpp.
References dataSink_m, Beam::find(), and fsCmdBase_m.
outputPath()
std::filesystem::path SolenoidPlacementTest::outputPath (const std::string & suffix) const inline protected
Definition at line 118 of file TestSolenoid.cpp.
References testStem_.
Referenced by cleanupOutputs().
parsePositionLine()
static std::tuple< double, double, double > SolenoidPlacementTest::parsePositionLine (const std::string & line) inline static protected
Definition at line 134 of file TestSolenoid.cpp.
SetUp()
void SolenoidPlacementTest::SetUp () inline override protected
Definition at line 45 of file TestSolenoid.cpp.
References cleanupOutputs(), OpalData::getInstance(), OpalData::setOpenMode(), OpalData::storeInputFn(), testStem_, and OpalData::WRITE.
SetUpTestSuite()
static void SolenoidPlacementTest::SetUpTestSuite () inline static protected
Definition at line 30 of file TestSolenoid.cpp.
References Options::enableHDF5, and gmsg.
splitWhitespace()
static std::vector< std::string > SolenoidPlacementTest::splitWhitespace (const std::string & line) inline static protected
Definition at line 143 of file TestSolenoid.cpp.
TearDown()
void SolenoidPlacementTest::TearDown () inline override protected
Definition at line 53 of file TestSolenoid.cpp.
References cleanupOutputs(), and fieldmapFile_.
TearDownTestSuite()
static void SolenoidPlacementTest::TearDownTestSuite () inline static protected
Definition at line 39 of file TestSolenoid.cpp.
References gmsg.
writeXZFieldmap()
std::filesystem::path SolenoidPlacementTest::writeXZFieldmap (const std::string & filename, double zBeginCm, double zEndCm, int nz, double rBeginCm, double rEndCm, int nr, double bzValue = 1.0, double brValue = 0.0) inline protected
Definition at line 102 of file TestSolenoid.cpp.
References fieldmapFile_, and nr.
Member Data Documentation
dataSink_m
std::shared_ptr<DataSink> SolenoidPlacementTest::dataSink_m protected
Definition at line 156 of file TestSolenoid.cpp.
Referenced by makeBunch().
fieldmapFile_
std::filesystem::path SolenoidPlacementTest::fieldmapFile_ protected
Definition at line 154 of file TestSolenoid.cpp.
Referenced by cleanupOutputs(), TearDown(), and writeXZFieldmap().
fsCmdBase_m
std::shared_ptr<FieldSolverCmd> SolenoidPlacementTest::fsCmdBase_m protected
Definition at line 155 of file TestSolenoid.cpp.
Referenced by makeBunch().
testStem_
std::string SolenoidPlacementTest::testStem_ protected
Definition at line 153 of file TestSolenoid.cpp.
Referenced by outputPath(), and SetUp().
The documentation for this class was generated from the following file:
TestSolenoid.cpp