OPALX (Object Oriented Parallel Accelerator Library for Exascal): FixedFFTLowPassFilter Class Reference
FixedFFTLowPassFilter Class Reference
#include <FixedFFTLowPass.h>
Public Member Functions
FixedFFTLowPassFilter (const int &N)
void apply (std::vector< double > &LineDensity)
void calc_derivative (std::vector< double > &histogram, const double &h)
Private Attributes
int number_frequencies_m
Detailed Description
Definition at line 6 of file FixedFFTLowPass.h.
Constructor & Destructor Documentation
FixedFFTLowPassFilter()
FixedFFTLowPassFilter::FixedFFTLowPassFilter (const int & N)
Definition at line 5 of file FixedFFTLowPass.cpp.
References number_frequencies_m.
Member Function Documentation
apply()
void FixedFFTLowPassFilter::apply (std::vector< double > & LineDensity) virtual
Implements Filter.
Definition at line 7 of file FixedFFTLowPass.cpp.
References gsl_fft_halfcomplex_inverse(), gsl_fft_halfcomplex_wavetable_alloc(), gsl_fft_halfcomplex_wavetable_free(), gsl_fft_real_transform(), gsl_fft_real_wavetable_alloc(), gsl_fft_real_wavetable_free(), gsl_fft_real_workspace_alloc(), gsl_fft_real_workspace_free(), and number_frequencies_m.
calc_derivative()
void FixedFFTLowPassFilter::calc_derivative (std::vector< double > & histogram, const double & h) virtual
Implements Filter.
Definition at line 36 of file FixedFFTLowPass.cpp.
References gsl_fft_halfcomplex_inverse(), gsl_fft_halfcomplex_wavetable_alloc(), gsl_fft_halfcomplex_wavetable_free(), gsl_fft_real_transform(), gsl_fft_real_wavetable_alloc(), gsl_fft_real_wavetable_free(), gsl_fft_real_workspace_alloc(), gsl_fft_real_workspace_free(), number_frequencies_m, and Physics::pi.
Member Data Documentation
number_frequencies_m
int FixedFFTLowPassFilter::number_frequencies_m private
Definition at line 13 of file FixedFFTLowPass.h.
Referenced by apply(), calc_derivative(), and FixedFFTLowPassFilter().
The documentation for this class was generated from the following files:
FixedFFTLowPass.h
FixedFFTLowPass.cpp