OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions::SRefAttr< T > Class Template Reference
Expressions::SRefAttr< T > Class Template Reference
An attribute defined as a reference to a scalar.
#include <SRefAttr.h>
Public Member Functions
SRefAttr (const std::string &oName, const std::string &aName, int index)
Constructor.
SRefAttr (const SRefAttr &)
virtual ~SRefAttr ()
virtual SRefAttr< T > * clone () const
Make clone.
virtual T evaluate () const
Evaluate.
virtual double getReal ()
Return real value.
virtual void invalidate ()
Invalidate.
virtual void print (std::ostream &) const
Print the reference.
virtual void set (const T &) const
Store new value.
double getReal ()
std::string getImage () const
Convert to string.
virtual bool isExpression () const
Test for expression.
Private Member Functions
SRefAttr ()
void operator= (const SRefAttr &)
void fill () const
Private Attributes
const std::string obj_name
const std::string att_name
const int itsIndex
Object * itsObject
Attribute * itsAttr
Static Private Attributes
static const std::string typeName
Detailed Description
template<class T>
class Expressions::SRefAttr< T >
An attribute defined as a reference to a scalar.
Definition at line 47 of file SRefAttr.h.
Constructor & Destructor Documentation
SRefAttr() [1/3]
template<class T> Expressions::SRefAttr< T >::SRefAttr (const std::string & oName, const std::string & aName, int index)
Constructor.
Definition at line 110 of file SRefAttr.h.
References att_name, itsAttr, itsIndex, itsObject, and obj_name.
Referenced by clone(), fill(), operator=(), and SRefAttr().
SRefAttr() [2/3]
template<class T> Expressions::SRefAttr< T >::SRefAttr (const SRefAttr< T > & rhs)
Definition at line 114 of file SRefAttr.h.
References att_name, AttributeBase::AttributeBase(), itsAttr, itsIndex, itsObject, obj_name, and SRefAttr().
~SRefAttr()
template<class T> Expressions::SRefAttr< T >::~SRefAttr () virtual
Definition at line 123 of file SRefAttr.h.
References itsObject.
SRefAttr() [3/3]
template<class T> Expressions::SRefAttr< T >::SRefAttr () private
Member Function Documentation
clone()
template<class T> SRefAttr< T > * Expressions::SRefAttr< T >::clone () const virtual
Make clone.
Implements AttributeBase.
Definition at line 128 of file SRefAttr.h.
References SRefAttr().
evaluate()
template<class T> T Expressions::SRefAttr< T >::evaluate () const virtual
Evaluate.
Definition at line 133 of file SRefAttr.h.
References AttributeBase::AttributeBase(), fill(), AttributeBase::getImage(), itsAttr, and itsIndex.
Referenced by Attributes::getBool(), Attributes::getReal(), getReal(), and Attributes::getString().
fill()
template<class T> void Expressions::SRefAttr< T >::fill () const private
Definition at line 205 of file SRefAttr.h.
References att_name, OpalData::find(), OpalData::getInstance(), itsAttr, itsIndex, itsObject, obj_name, and SRefAttr().
Referenced by evaluate(), and set().
getImage()
std::string AttributeBase::getImage () const inherited
Convert to string.
Definition at line 29 of file AttributeBase.cpp.
References print().
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), and Expressions::SRefAttr< T >::evaluate().
getReal() [1/2]
template<class T> double Expressions::SRefAttr< T >::getReal () virtual
Return real value.
Definition at line 166 of file SRefAttr.h.
getReal() [2/2]
double Expressions::SRefAttr< double >::getReal () inline
Definition at line 171 of file SRefAttr.h.
References evaluate().
invalidate()
template<class T> void Expressions::SRefAttr< T >::invalidate () virtual
Invalidate.
Reimplemented from Invalidator.
Definition at line 184 of file SRefAttr.h.
References itsAttr, and itsObject.
isExpression()
bool AttributeBase::isExpression () const virtual inherited
Test for expression.
Reimplemented in Expressions::ADeferred< T >, and Expressions::SDeferred< T >.
Definition at line 36 of file AttributeBase.cpp.
Referenced by OpalElement::printMultipoleStrength().
operator=()
template<class T> void Expressions::SRefAttr< T >::operator= (const SRefAttr< T > &) private
References SRefAttr().
print()
template<class T> void Expressions::SRefAttr< T >::print (std::ostream & os) const virtual
Print the reference.
Implements AttributeBase.
Definition at line 176 of file SRefAttr.h.
References att_name, itsIndex, and obj_name.
Referenced by Expressions::operator<<().
set()
template<class T> void Expressions::SRefAttr< T >::set (const T & value) const virtual
Store new value.
Definition at line 190 of file SRefAttr.h.
References AttributeBase::AttributeBase(), fill(), and itsAttr.
Referenced by Attributes::setBool(), Attributes::setPredefinedString(), Attributes::setReal(), Attributes::setString(), and Attributes::setUpperCaseString().
Member Data Documentation
att_name
template<class T> const std::string Expressions::SRefAttr< T >::att_name private
Definition at line 92 of file SRefAttr.h.
Referenced by fill(), print(), SRefAttr(), and SRefAttr().
itsAttr
template<class T> Attribute* Expressions::SRefAttr< T >::itsAttr mutable private
Definition at line 97 of file SRefAttr.h.
Referenced by evaluate(), fill(), invalidate(), set(), SRefAttr(), and SRefAttr().
itsIndex
template<class T> const int Expressions::SRefAttr< T >::itsIndex private
Definition at line 93 of file SRefAttr.h.
Referenced by evaluate(), fill(), print(), SRefAttr(), and SRefAttr().
itsObject
template<class T> Object* Expressions::SRefAttr< T >::itsObject mutable private
Definition at line 96 of file SRefAttr.h.
Referenced by fill(), invalidate(), SRefAttr(), SRefAttr(), and ~SRefAttr().
obj_name
template<class T> const std::string Expressions::SRefAttr< T >::obj_name private
Definition at line 91 of file SRefAttr.h.
Referenced by fill(), print(), SRefAttr(), and SRefAttr().
typeName
template<class T> const std::string Expressions::SRefAttr< T >::typeName static private
Definition at line 88 of file SRefAttr.h.
The documentation for this class was generated from the following files:
AbstractObjects/Expressions.h
SRefAttr.h