OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions::AAutomatic< T > Class Template Reference
Expressions::AAutomatic< T > Class Template Reference
Object attribute with an `‘automatic’' array value.
#include <AAutomatic.h>
Public Member Functions
AAutomatic (PtrToArray< T > expr)
Constructor.
AAutomatic (ArrayOfPtrs< T > expr)
Constructor.
AAutomatic (const AAutomatic &)
virtual ~AAutomatic ()
virtual AAutomatic< T > * clone () const
Make a clone.
virtual std::vector< T > evaluate ()
Evaluate.
virtual void invalidate ()
Invalidate.
virtual bool isExpression () const
Get expression flag.
virtual void print (std::ostream &) const
Print the attribute value.
void setComponent (int i, const PtrToScalar< T > expr)
Set a component of the value.
std::string getImage () const
Convert to string.
Protected Attributes
PtrToArray< T > itsLaw
The generating law for the array expression.
ArrayOfPtrs< T > itsOverrides
Overrides for single components.
std::vector< T > value
The value of the attribute.
Private Member Functions
AAutomatic ()
void operator= (const AAutomatic &)
Private Attributes
bool is_known
bool in_evaluation
Detailed Description
template<class T>
class Expressions::AAutomatic< T >
Object attribute with an `‘automatic’' array value.
Definition at line 39 of file AAutomatic.h.
Constructor & Destructor Documentation
AAutomatic() [1/4]
template<class T > Expressions::AAutomatic< T >::AAutomatic (PtrToArray< T > expr) explicit
Constructor.
Definition at line 88 of file AAutomatic.h.
References OpalData::getInstance(), and OpalData::registerExpression().
AAutomatic() [2/4]
template<class T > Expressions::AAutomatic< T >::AAutomatic (ArrayOfPtrs< T > expr) explicit
Constructor.
Definition at line 96 of file AAutomatic.h.
References OpalData::getInstance(), and OpalData::registerExpression().
AAutomatic() [3/4]
template<class T > Expressions::AAutomatic< T >::AAutomatic (const AAutomatic< T > &)
~AAutomatic()
template<class T > Expressions::AAutomatic< T >::~AAutomatic () virtual
Definition at line 104 of file AAutomatic.h.
References OpalData::getInstance(), and OpalData::unregisterExpression().
AAutomatic() [4/4]
template<class T > Expressions::AAutomatic< T >::AAutomatic () private
Member Function Documentation
clone()
template<class T > AAutomatic< T > * Expressions::AAutomatic< T >::clone () const virtual
Make a clone.
Reimplemented from Expressions::ADeferred< T >.
Definition at line 111 of file AAutomatic.h.
evaluate()
template<class T > std::vector< T > Expressions::AAutomatic< T >::evaluate () virtual
Evaluate.
Reimplemented from Expressions::ADeferred< T >.
Definition at line 117 of file AAutomatic.h.
References Expressions::ADeferred< T >::evaluate().
getImage()
std::string AttributeBase::getImage () const inherited
Convert to string.
Definition at line 33 of file AttributeBase.cpp.
References AttributeBase::print().
invalidate()
template<class T > void Expressions::AAutomatic< T >::invalidate () virtual
Invalidate.
Reimplemented from Invalidator.
Definition at line 128 of file AAutomatic.h.
isExpression()
template<class T > bool Expressions::ADeferred< T >::isExpression () const virtual inherited
Get expression flag.
Reimplemented from AttributeBase.
Definition at line 208 of file ADeferred.h.
operator=()
template<class T > void Expressions::AAutomatic< T >::operator= (const AAutomatic< T > &) private
print()
template<class T > void Expressions::ADeferred< T >::print (std::ostream & os) const virtual inherited
Print the attribute value.
Reimplemented from Expressions::AValue< T >.
Definition at line 214 of file ADeferred.h.
setComponent()
template<class T > void Expressions::ADeferred< T >::setComponent (int i, const PtrToScalar< T > expr) inherited
Set a component of the value.
Definition at line 237 of file ADeferred.h.
Referenced by Attributes::BoolArray::parseComponent(), and Attributes::RealArray::parseComponent().
Member Data Documentation
in_evaluation
template<class T > bool Expressions::ADeferred< T >::in_evaluation mutable private inherited
Definition at line 99 of file ADeferred.h.
is_known
template<class T > bool Expressions::AAutomatic< T >::is_known mutable private
Definition at line 72 of file AAutomatic.h.
itsLaw
template<class T > PtrToArray<T> Expressions::ADeferred< T >::itsLaw protected inherited
The generating law for the array expression.
Definition at line 85 of file ADeferred.h.
itsOverrides
template<class T > ArrayOfPtrs<T> Expressions::ADeferred< T >::itsOverrides protected inherited
Overrides for single components.
Definition at line 91 of file ADeferred.h.
Referenced by Expressions::ADeferred< T >::ADeferred().
value
template<class T > std::vector<T> Expressions::AValue< T >::value mutable protected inherited
The value of the attribute.
Definition at line 63 of file AValue.h.
The documentation for this class was generated from the following file:
AAutomatic.h