OPALX (Object Oriented Parallel Accelerator Library for Exascal): Statement Class Reference
Statement Class Reference abstract
Interface for statements.
#include <Statement.h>
Public Types
typedef std::list< Token > TokenList
The type of the enclosed token list.
Public Member Functions
Statement (const std::string &name, int line)
Constructor.
Statement (const std::string &name, TokenList &)
Constructor.
virtual ~Statement ()
void append (const Token &)
Append a token.
bool atEnd () const
Test for end of command.
bool boolean (bool &value)
Return boolean value.
bool delimiter (char c)
Test for delimiter.
bool delimiter (const char *s)
Test for delimiter choice.
virtual void execute (const Parser &)=0
Execute.
Token & getCurrent ()
Return current token and skip it.
bool integer (int &value)
Return signed integer.
bool integer (unsigned &value)
Return unsigned integer.
bool keyword (const char *s)
Test for keyword.
bool real (double &value)
Return real value.
bool str (std::string &value)
Return string value.
bool word (std::string &value)
Return word value.
void mark ()
Mark position in command.
void restore ()
Return to marked position.
void start ()
Return to start.
void skip ()
Skip.
unsigned int position () const
Return current character number in line.
virtual void print (std::ostream &os) const
Print statement.
virtual void printWhere (Inform &msg, bool withToken) const
Print position.
std::string str () const
Protected Attributes
int stat_line
std::string buffer_name
TokenList tokens
TokenList::iterator curr
TokenList::iterator keep
Detailed Description
Interface for statements.
Definition at line 37 of file Statement.h.
Member Typedef Documentation
TokenList
typedef std::list<Token> Statement::TokenList
The type of the enclosed token list.
Definition at line 40 of file Statement.h.
Constructor & Destructor Documentation
Statement() [1/2]
Statement::Statement (const std::string & name, int line)
Constructor.
Definition at line 28 of file Statement.cpp.
Statement() [2/2]
Statement::Statement (const std::string & name, TokenList & list)
Constructor.
Definition at line 31 of file Statement.cpp.
References curr, and tokens.
~Statement()
Statement::~Statement () virtual
Definition at line 37 of file Statement.cpp.
References tokens.
Member Function Documentation
append()
void Statement::append (const Token & token)
Append a token.
Definition at line 39 of file Statement.cpp.
References tokens.
Referenced by IfStatement::IfStatement(), LineTemplate::makeInstance(), OpalParser::parseBracketList(), OpalParser::parseTokenList(), OpalParser::readStatement(), and WhileStatement::WhileStatement().
atEnd()
bool Statement::atEnd () const
Test for end of command.
Definition at line 41 of file Statement.cpp.
References curr, and tokens.
Referenced by MacroCmd::makeTemplate(), OpalParser::parse(), Expressions::parseBracketList(), OpalParser::parseEnd(), LineTemplate::parseTemplate(), Expressions::parseTokenList(), and skip().
boolean()
bool Statement::boolean (bool & value)
Return boolean value.
Definition at line 43 of file Statement.cpp.
References curr, tokens, and word().
Referenced by Expressions::parseRelation().
delimiter() [1/2]
bool Statement::delimiter (char c)
Test for delimiter.
Definition at line 83 of file Statement.cpp.
References curr, and tokens.
Referenced by MacroCmd::makeTemplate(), Object::parse(), OpalElement::parse(), OpalParser::parse(), Line::parse(), OpalParser::parseAction(), Macro::parseActuals(), Expressions::parseAnd(), Expressions::parseArrayFactor(), Expressions::parseArrayPrimary(), Expressions::parseArrayTerm(), OpalParser::parseAssign(), Expressions::parseBool(), Expressions::parseBoolArray(), Expressions::parseBracketList(), Expressions::parseColumnGenerator(), OpalParser::parseDefine(), Expressions::parseDelimiter(), Expressions::parseDelimiter(), OpalParser::parseEnd(), Expressions::parseFactor(), Macro::parseFormals(), Line::parseList(), EmissionSourceList::parseList(), OpalParser::parseMacro(), SequenceParser::parseMember(), Expressions::parsePlace(), SequenceParser::parsePosition(), Expressions::parsePrimary(), Expressions::parseRange(), Expressions::parseReal(), Expressions::parseRealArray(), Expressions::parseReference(), Expressions::parseRelation(), Expressions::parseRowGenerator(), Expressions::parseString(), Expressions::parseStringArray(), Expressions::parseStringValue(), Expressions::parseTableGenerator(), Expressions::parseTerm(), Expressions::parseTokenListArray(), and TrackRun::print().
delimiter() [2/2]
bool Statement::delimiter (const char * s)
Test for delimiter choice.
Definition at line 92 of file Statement.cpp.
References curr, and tokens.
execute()
virtual void Statement::execute (const Parser &) pure virtual
Execute.
Implemented in CompoundStatement, IfStatement, SimpleStatement, and WhileStatement.
Referenced by IfStatement::execute(), WhileStatement::execute(), and OpalParser::run().
getCurrent()
Token & Statement::getCurrent ()
Return current token and skip it.
Definition at line 61 of file Statement.cpp.
References curr.
Referenced by MacroCmd::makeTemplate(), OpalParser::parse(), Macro::parseActuals(), Expressions::parseBracketList(), OpalParser::parseMacro(), LineTemplate::parseTemplate(), and Expressions::parseTokenList().
integer() [1/2]
bool Statement::integer (int & value)
Return signed integer.
Definition at line 63 of file Statement.cpp.
References curr, Token::getInteger(), and tokens.
Referenced by Line::parseList().
integer() [2/2]
bool Statement::integer (unsigned & value)
Return unsigned integer.
Definition at line 73 of file Statement.cpp.
References curr, and tokens.
keyword()
bool Statement::keyword (const char * s)
Test for keyword.
Definition at line 101 of file Statement.cpp.
References curr, and tokens.
Referenced by MacroCmd::makeTemplate(), SequenceParser::parse(), OpalParser::parse(), Expressions::parseArrayPrimary(), OpalParser::parseAssign(), OpalParser::parseDefine(), Expressions::parsePlace(), SequenceParser::parsePosition(), Expressions::parseRange(), SequenceTemplate::parseTemplate(), and LineTemplate::parseTemplate().
mark()
void Statement::mark ()
Mark position in command.
Definition at line 146 of file Statement.cpp.
References curr, and keep.
Referenced by OpalParser::parse(), OpalParser::parseMacro(), Expressions::parseRelation(), Expressions::parseTokenList(), and TrackRun::print().
position()
unsigned int Statement::position () const
Return current character number in line.
Definition at line 157 of file Statement.cpp.
References curr, and tokens.
Referenced by OpalParser::parse(), and OpalParser::parseEnd().
print()
void Statement::print (std::ostream & os) const virtual
Print statement.
Definition at line 171 of file Statement.cpp.
References tokens.
Referenced by IfStatement::execute(), WhileStatement::execute(), operator<<(), operator<<(), OpalParser::parse(), OpalParser::parseEnd(), and str().
printWhere()
void Statement::printWhere (Inform & msg, bool withToken) const virtual
Print position.
Definition at line 183 of file Statement.cpp.
References buffer_name, curr, stat_line, and tokens.
real()
bool Statement::real (double & value)
Return real value.
Definition at line 110 of file Statement.cpp.
References curr, and tokens.
Referenced by Expressions::parseArrayPrimary(), and Expressions::parsePrimary().
restore()
void Statement::restore ()
Return to marked position.
Definition at line 148 of file Statement.cpp.
References curr, and keep.
Referenced by OpalParser::parse(), OpalParser::parseMacro(), Expressions::parseRelation(), and Expressions::parseTokenList().
skip()
void Statement::skip ()
Skip.
Definition at line 152 of file Statement.cpp.
References atEnd(), and curr.
start()
void Statement::start ()
Return to start.
Definition at line 150 of file Statement.cpp.
References curr, and tokens.
Referenced by IfStatement::execute(), LineTemplate::makeInstance(), SequenceParser::parse(), OpalParser::parse(), OpalParser::parseAction(), OpalParser::parseAssign(), OpalParser::parseDefine(), and OpalParser::readStatement().
str() [1/2]
std::string Statement::str () const
Definition at line 197 of file Statement.cpp.
References print(), and str().
Referenced by str().
str() [2/2]
bool Statement::str (std::string & value)
Return string value.
Definition at line 126 of file Statement.cpp.
References curr, and tokens.
Referenced by Expressions::parseString(), and Expressions::parseStringValue().
word()
bool Statement::word (std::string & value)
Return word value.
Definition at line 136 of file Statement.cpp.
References curr, and tokens.
Referenced by boolean(), Expressions::parseRelation(), Expressions::parseString(), Expressions::parseStringValue(), and TrackRun::print().
Member Data Documentation
buffer_name
std::string Statement::buffer_name protected
Definition at line 173 of file Statement.h.
Referenced by CompoundStatement::CompoundStatement(), and printWhere().
curr
TokenList::iterator Statement::curr protected
Definition at line 177 of file Statement.h.
Referenced by atEnd(), boolean(), delimiter(), delimiter(), SimpleStatement::execute(), WhileStatement::execute(), getCurrent(), integer(), integer(), keyword(), mark(), position(), printWhere(), real(), restore(), skip(), start(), Statement(), str(), and word().
keep
TokenList::iterator Statement::keep protected
Definition at line 178 of file Statement.h.
Referenced by SimpleStatement::execute(), WhileStatement::execute(), mark(), and restore().
stat_line
int Statement::stat_line protected
Definition at line 170 of file Statement.h.
Referenced by CompoundStatement::CompoundStatement(), and printWhere().
tokens
TokenList Statement::tokens protected
Definition at line 176 of file Statement.h.
Referenced by append(), atEnd(), boolean(), delimiter(), delimiter(), SimpleStatement::execute(), WhileStatement::execute(), integer(), integer(), keyword(), position(), print(), printWhere(), real(), start(), Statement(), str(), word(), and ~Statement().
The documentation for this class was generated from the following files:
Statement.h
Statement.cpp