OPALX (Object Oriented Parallel Accelerator Library for Exascal): ConstBField Class Reference
ConstBField Class Reference abstract
A homogenous magnetostatic field.
#include <ConstBField.h>
Public Member Functions
ConstBField ()
Default constructor.
virtual ~ConstBField ()
virtual double getBx () const
Get component.
virtual double getBy () const
Get component.
virtual double getBz () const
Get component.
virtual void setBx (double)
Set component.
virtual void setBy (double)
Set component.
virtual void setBz (double)
Set component.
virtual EVector Efield (const Point3D &P) const
Get field.
virtual EVector Efield (const Point3D &P, double t) const
Get field.
virtual BVector Bfield (const Point3D &P) const
Get field.
virtual BVector Bfield (const Point3D &P, double t) const
Get field.
virtual EBVectors EBfield (const Point3D &P) const
Get field.
virtual EBVectors EBfield (const Point3D &P, double t) const
Get field.
virtual void scale (double scalar)=0
Scale the field.
Static Public Attributes
static const EVector ZeroEfield
The constant representing a zero electric field.
static const BVector ZeroBfield
The constant representing a zero magnetic field.
static const EBVectors ZeroEBfield
The constant representing a zero electromagnetic field.
Detailed Description
A homogenous magnetostatic field.
Definition at line 30 of file ConstBField.h.
Constructor & Destructor Documentation
ConstBField()
ConstBField::ConstBField ()
Default constructor.
Definition at line 26 of file ConstBField.cpp.
~ConstBField()
ConstBField::~ConstBField () virtual
Definition at line 28 of file ConstBField.cpp.
Member Function Documentation
Bfield() [1/2]
BVector EMField::Bfield (const Point3D & P) const virtual inherited
Get field.
Reimplemented in BDipoleField, BMultipoleField, ConstBzField, and OscillatingField< ConstEzField >.
Definition at line 121 of file EMField.cpp.
References EMField::ZeroBfield.
Referenced by Component::Bfield(), Component::Bfield(), EMField::Bfield(), and EMField::EBfield().
Bfield() [2/2]
BVector EMField::Bfield (const Point3D & P, double t) const virtual inherited
Get field.
Reimplemented in BDipoleField, BMultipoleField, ConstBzField, and OscillatingField< ConstEzField >.
Definition at line 125 of file EMField.cpp.
References EMField::Bfield().
EBfield() [1/2]
EBVectors EMField::EBfield (const Point3D & P) const virtual inherited
Get field.
Definition at line 127 of file EMField.cpp.
References EMField::Bfield(), and EMField::Efield().
Referenced by Component::EBfield(), Component::EBfield(), and EMField::EBfield().
EBfield() [2/2]
EBVectors EMField::EBfield (const Point3D & P, double t) const virtual inherited
Get field.
Definition at line 129 of file EMField.cpp.
References EMField::EBfield().
Efield() [1/2]
EVector EMField::Efield (const Point3D & P) const virtual inherited
Get field.
Reimplemented in ConstEzField, and OscillatingField< ConstEzField >.
Definition at line 119 of file EMField.cpp.
References EMField::ZeroEfield.
Referenced by EMField::EBfield(), Component::Efield(), Component::Efield(), and EMField::Efield().
Efield() [2/2]
EVector EMField::Efield (const Point3D & P, double t) const virtual inherited
Get field.
Reimplemented in ConstEzField, and OscillatingField< ConstEzField >.
Definition at line 123 of file EMField.cpp.
References EMField::Efield().
getBx()
double ConstBField::getBx () const virtual
Get component.
Reimplemented in BDipoleField.
Definition at line 30 of file ConstBField.cpp.
getBy()
double ConstBField::getBy () const virtual
Get component.
Reimplemented in BDipoleField.
Definition at line 32 of file ConstBField.cpp.
getBz()
double ConstBField::getBz () const virtual
Get component.
Reimplemented in ConstBzField.
Definition at line 34 of file ConstBField.cpp.
scale()
virtual void EMField::scale (double scalar) pure virtual inherited
Scale the field.
Implemented in BDipoleField, BMultipoleField, ConstBzField, ConstEzField, NullField, DummyField, and DummyFieldTW.
setBx()
void ConstBField::setBx (double) virtual
Set component.
Reimplemented in BDipoleField.
Definition at line 36 of file ConstBField.cpp.
setBy()
void ConstBField::setBy (double) virtual
Set component.
Reimplemented in BDipoleField.
Definition at line 38 of file ConstBField.cpp.
setBz()
void ConstBField::setBz (double) virtual
Set component.
Reimplemented in ConstBzField.
Definition at line 40 of file ConstBField.cpp.
Member Data Documentation
ZeroBfield
const BVector EMField::ZeroBfield static inherited
The constant representing a zero magnetic field.
Definition at line 220 of file EMField.h.
Referenced by EMField::Bfield().
ZeroEBfield
const EBVectors EMField::ZeroEBfield static inherited
The constant representing a zero electromagnetic field.
Definition at line 223 of file EMField.h.
ZeroEfield
const EVector EMField::ZeroEfield static inherited
The constant representing a zero electric field.
Definition at line 217 of file EMField.h.
Referenced by EMField::Efield().
The documentation for this class was generated from the following files:
ConstBField.h
ConstBField.cpp