OPALX (Object Oriented Parallel Accelerator Library for Exascal): RandomTest Class Reference
RandomTest Class Reference
Inherits testing::Test.
Protected Member Functions
void SetUp () override
void TearDown () override
Protected Attributes
gsl_rng * rng
Detailed Description
Definition at line 44 of file TestRandom.cpp.
Member Function Documentation
SetUp()
void RandomTest::SetUp () inline override protected
Definition at line 46 of file TestRandom.cpp.
References gsl_rng_alloc(), gsl_rng_default, rng, and gsl_rng::seed().
TearDown()
void RandomTest::TearDown () inline override protected
Definition at line 51 of file TestRandom.cpp.
References gsl_rng_free(), and rng.
Member Data Documentation
rng
gsl_rng* RandomTest::rng protected
Definition at line 53 of file TestRandom.cpp.
Referenced by SetUp(), and TearDown().
The documentation for this class was generated from the following file:
TestRandom.cpp