OPALX (Object Oriented Parallel Accelerator Library for Exascal): EBVectors Class Reference
EBVectors Class Reference
A representation of an electromagnetic field.
#include <EMField.h>
Public Member Functions
EBVectors (const EVector &E, const BVector &B)
Constructor.
EVector getE () const
Get component.
double getEx () const
Get component.
double getEy () const
Get component.
double getEz () const
Get component.
BVector getB () const
Get field.
double getBx () const
Get component.
double getBy () const
Get component.
double getBz () const
Get component.
Private Attributes
EVector E
BVector B
Detailed Description
A representation of an electromagnetic field.
Definition at line 120 of file EMField.h.
Constructor & Destructor Documentation
EBVectors()
EBVectors::EBVectors (const EVector & E, const BVector & B)
Constructor.
Definition at line 83 of file EMField.cpp.
Member Function Documentation
getB()
BVector EBVectors::getB () const
Get field.
Definition at line 93 of file EMField.cpp.
References B.
getBx()
double EBVectors::getBx () const
Get component.
Definition at line 95 of file EMField.cpp.
References B, and BVector::getBx().
getBy()
double EBVectors::getBy () const
Get component.
Definition at line 97 of file EMField.cpp.
References B, and BVector::getBy().
getBz()
double EBVectors::getBz () const
Get component.
Definition at line 99 of file EMField.cpp.
References B, and BVector::getBy().
getE()
EVector EBVectors::getE () const
Get component.
Definition at line 85 of file EMField.cpp.
References E.
getEx()
double EBVectors::getEx () const
Get component.
Definition at line 87 of file EMField.cpp.
References E, and EVector::getEx().
getEy()
double EBVectors::getEy () const
Get component.
Definition at line 89 of file EMField.cpp.
References E, and EVector::getEy().
getEz()
double EBVectors::getEz () const
Get component.
Definition at line 91 of file EMField.cpp.
References E, and EVector::getEz().
Member Data Documentation
B
BVector EBVectors::B private
Definition at line 161 of file EMField.h.
Referenced by getB(), getBx(), getBy(), and getBz().
E
EVector EBVectors::E private
Definition at line 160 of file EMField.h.
Referenced by getE(), getEx(), getEy(), and getEz().
The documentation for this class was generated from the following files:
EMField.h
EMField.cpp