OPALX (Object Oriented Parallel Accelerator Library for Exascal): AttributeBase Class Reference
AttributeBase Class Reference abstract
Abstract base class for attribute values of different types.
#include <AttributeBase.h>
Public Member Functions
AttributeBase ()
virtual ~AttributeBase ()
virtual AttributeBase * clone () const =0
Make clone.
std::string getImage () const
Convert to string.
virtual bool isExpression () const
Test for expression.
virtual void print (std::ostream &) const =0
Print value.
virtual void invalidate ()
Force re-evaluation.
Private Member Functions
AttributeBase (AttributeBase &)
void operator= (AttributeBase &)
Detailed Description
Abstract base class for attribute values of different types.
Definition at line 31 of file AttributeBase.h.
Constructor & Destructor Documentation
AttributeBase() [1/2]
AttributeBase::AttributeBase ()
Definition at line 25 of file AttributeBase.cpp.
Referenced by AttributeBase(), clone(), Expressions::SRefAttr< T >::evaluate(), operator=(), Expressions::SRefAttr< T >::set(), and Expressions::SRefAttr< T >::SRefAttr().
~AttributeBase()
AttributeBase::~AttributeBase () virtual
Definition at line 27 of file AttributeBase.cpp.
AttributeBase() [2/2]
AttributeBase::AttributeBase (AttributeBase &) private
References AttributeBase().
Member Function Documentation
clone()
virtual AttributeBase * AttributeBase::clone () const pure virtual
Make clone.
Implemented in Expressions::AAutomatic< T >, Expressions::ADeferred< T >, Expressions::AValue< T >, Expressions::SAutomatic< T >, Expressions::SDeferred< T >, Expressions::SRefAttr< T >, and Expressions::SValue< T >.
References AttributeBase().
getImage()
std::string AttributeBase::getImage () const
Convert to string.
Definition at line 29 of file AttributeBase.cpp.
References print().
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), and Expressions::SRefAttr< T >::evaluate().
invalidate()
void Invalidator::invalidate () virtual inherited
Force re-evaluation.
Reimplemented in Expressions::AAutomatic< T >, Expressions::SAutomatic< T >, Expressions::SRefAttr< T >, and Expressions::SRefExpr< T >.
Definition at line 25 of file Invalidator.cpp.
isExpression()
bool AttributeBase::isExpression () const virtual
Test for expression.
Reimplemented in Expressions::ADeferred< T >, and Expressions::SDeferred< T >.
Definition at line 36 of file AttributeBase.cpp.
Referenced by OpalElement::printMultipoleStrength().
operator=()
void AttributeBase::operator= (AttributeBase &) private
References AttributeBase().
print()
virtual void AttributeBase::print (std::ostream &) const pure virtual
Print value.
Implemented in Expressions::ADeferred< T >, Expressions::AValue< T >, Expressions::AValue< T >, Expressions::AValue< T >, Expressions::AValue< T >, Expressions::AValue< T >, Expressions::SDeferred< T >, Expressions::SRefAttr< T >, Expressions::SValue< T >, Expressions::SValue< T >, Expressions::SValue< T >, and Expressions::SValue< T >.
Referenced by getImage(), and operator<<().
The documentation for this class was generated from the following files:
AttributeBase.h
AttributeBase.cpp