OPALX (Object Oriented Parallel Accelerator Library for Exascal): Tracker Class Reference
Tracker Class Reference
#include <Tracker.h>
Public Types
enum {
X , PX , Y , PY ,
T , PT
}
Public Member Functions
Tracker (const Beamline &, bool backBeam, bool backTrack)
Constructor.
Tracker (const Beamline &, PartBunch_t &bunch, bool backBeam, bool backTrack)
Construct a tracker that borrows an existing particle bunch.
virtual ~Tracker ()
PartBunch_t & getBunch () const
Return the currently attached borrowed bunch.
void addToBunch (const OpalParticle &)
Add particle to bunch.
virtual void visitComponent (const Component &)
Store the bunch.
virtual void setNumBunch (short)
set total number of tracked bunches
virtual short getNumBunch ()
get total number of tracked bunches
void execute () override
Apply the algorithm to the top-level beamline.
void visitBeamline (const Beamline &) override
Apply the algorithm to a beam line.
void visitConstantEFieldCavity (const ConstantEFieldCavity &) override
Apply the algorithm to a constant E-field cavity element.
void visitDrift (const Drift &) override
Apply the algorithm to a drift space.
void visitLaser (const Laser &) override
Apply the algorithm to a laser.
void visitFlaggedElmPtr (const FlaggedElmPtr &) override
Apply the algorithm to a FlaggedElmPtr.
void visitMarker (const Marker &) override
Apply the algorithm to a marker.
void visitMonitor (const Monitor &) override
Apply the algorithm to a beam position monitor.
void visitMultipole (const Multipole &) override
Apply the algorithm to a multipole.
void visitMultipoleT (const MultipoleT &) override
Apply the algorithm to an arbitrary multipole.
void visitRBend (const RBend &) override
Apply the algorithm to a rectangular bend.
void visitRing (const Ring &) override
Apply the algorithm to a Ring.
void visitSBend (const SBend &) override
Apply the algorithm to a sector bend.
void visitRFCavity (const RFCavity &) override
Apply the algorithm to a RF cavity.
void visitSolenoid (const Solenoid &) override
Apply the algorithm to a Solenoid.
void visitTravelingWave (const TravelingWave &) override
Apply the algorithm to a traveling wave.
void visitScalingFFAMagnet (const ScalingFFAMagnet &spiral) override
Apply the algorithm to a scaling FFA magnet.
void visitVerticalFFAMagnet (const VerticalFFAMagnet &) override
Apply the algorithm to a vertical FFA magnet.
void visitVariableRFCavity (const VariableRFCavity &) override
Apply the algorithm to a variable RF cavity.
void visitProbe (const Probe &prob) override
Apply the algorithm to a Probe.
Public Attributes
FieldList cavities_m
const Beamline & itsBeamline_m
Protected Attributes
PartBunch_t * itsBunch_m
The bunch of particles to be tracked. Borrowed; lifetime is managed by TrackRun.
const Beamline & itsLine
bool back_beam
bool back_track
bool back_path
double flip_B
double flip_s
Private Member Functions
Tracker ()
Tracker (const Tracker &)
void operator= (const Tracker &)
virtual void applyDefault (const ElementBase &)
Private Attributes
bool local_flip
Detailed Description
Definition at line 76 of file Tracker.h.
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
Enumerator
X
PX
Y
PY
T
PT
Definition at line 36 of file AbstractTracker.h.
Constructor & Destructor Documentation
Tracker() [1/4]
Tracker::Tracker (const Beamline & beamline, bool backBeam, bool backTrack)
Constructor.
Definition at line 76 of file Tracker.cpp.
Tracker() [2/4]
Tracker::Tracker (const Beamline & beamline, PartBunch_t & bunch, bool backBeam, bool backTrack)
Construct a tracker that borrows an existing particle bunch.
Parameters
bunch Particle bunch to track. Ownership remains with the caller.
Definition at line 81 of file Tracker.cpp.
~Tracker()
Tracker::~Tracker () virtual
Definition at line 84 of file Tracker.cpp.
Tracker() [3/4]
Tracker::Tracker () private
Tracker() [4/4]
Tracker::Tracker (const Tracker &) private
Member Function Documentation
addToBunch()
void Tracker::addToBunch (const OpalParticle &)
Add particle to bunch.
Definition at line 93 of file Tracker.cpp.
References gmsg.
applyDefault()
void DefaultVisitor::applyDefault (const ElementBase &) private virtual inherited
Definition at line 113 of file DefaultVisitor.cpp.
Referenced by DefaultVisitor::visitComponent(), DefaultVisitor::visitConstantEFieldCavity(), DefaultVisitor::visitDrift(), DefaultVisitor::visitLaser(), DefaultVisitor::visitMarker(), DefaultVisitor::visitMonitor(), DefaultVisitor::visitMultipole(), DefaultVisitor::visitMultipoleT(), DefaultVisitor::visitProbe(), DefaultVisitor::visitRBend(), DefaultVisitor::visitRFCavity(), DefaultVisitor::visitRing(), DefaultVisitor::visitSBend(), DefaultVisitor::visitScalingFFAMagnet(), DefaultVisitor::visitSolenoid(), DefaultVisitor::visitTravelingWave(), DefaultVisitor::visitVariableRFCavity(), and DefaultVisitor::visitVerticalFFAMagnet().
execute()
void DefaultVisitor::execute () override virtual inherited
Apply the algorithm to the top-level beamline.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker, RangeSelector, and Selector.
Definition at line 54 of file DefaultVisitor.cpp.
References ElementBase::accept(), DefaultVisitor::back_beam, DefaultVisitor::back_track, DefaultVisitor::itsLine, and DefaultVisitor::local_flip.
Referenced by RangeSelector::execute(), Line::replace(), Sequence::replace(), and Select::select().
getBunch()
PartBunch_t & Tracker::getBunch () const
Return the currently attached borrowed bunch.
Definition at line 86 of file Tracker.cpp.
References itsBunch_m.
getNumBunch()
virtual short Tracker::getNumBunch () inline virtual
get total number of tracked bunches
Definition at line 110 of file Tracker.h.
operator=()
void Tracker::operator= (const Tracker &) private
setNumBunch()
virtual void Tracker::setNumBunch (short) inline virtual
set total number of tracked bunches
Definition at line 107 of file Tracker.h.
visitBeamline()
void DefaultVisitor::visitBeamline (const Beamline & bl) override virtual inherited
Apply the algorithm to a beam line.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 97 of file DefaultVisitor.cpp.
References Beamline::iterate(), and DefaultVisitor::local_flip.
visitComponent()
void Tracker::visitComponent (const Component & comp) virtual
Store the bunch.
Apply the algorithm to an arbitrary component.
Reimplemented from DefaultVisitor.
Reimplemented in ParallelTracker.
Definition at line 101 of file Tracker.cpp.
References DefaultVisitor::back_beam, DefaultVisitor::back_track, PartBunch< T, Dim >::getReference(), itsBunch_m, and Component::trackBunch().
Referenced by ParallelTracker::visitComponent().
visitConstantEFieldCavity()
void DefaultVisitor::visitConstantEFieldCavity (const ConstantEFieldCavity & cav) override virtual inherited
Apply the algorithm to a constant E-field cavity element.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 61 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitDrift()
void DefaultVisitor::visitDrift (const Drift & drf) override virtual inherited
Apply the algorithm to a drift space.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 65 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitFlaggedElmPtr()
void DefaultVisitor::visitFlaggedElmPtr (const FlaggedElmPtr & fep) override virtual inherited
Apply the algorithm to a FlaggedElmPtr.
Implements BeamlineVisitor.
Reimplemented in Flagger, Replacer, and RangeSelector.
Definition at line 103 of file DefaultVisitor.cpp.
References ElementBase::accept(), ElmPtr::getElement(), FlaggedElmPtr::getReflectionFlag(), and DefaultVisitor::local_flip.
Referenced by RangeSelector::handleBeamline(), RangeSelector::handleElement(), Flagger::visitFlaggedElmPtr(), and Replacer::visitFlaggedElmPtr().
visitLaser()
void DefaultVisitor::visitLaser (const Laser & laser) override virtual inherited
Apply the algorithm to a laser.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 67 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitMarker()
void DefaultVisitor::visitMarker (const Marker & mark) override virtual inherited
Apply the algorithm to a marker.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 69 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitMonitor()
void DefaultVisitor::visitMonitor (const Monitor & mon) override virtual inherited
Apply the algorithm to a beam position monitor.
Implements BeamlineVisitor.
Definition at line 71 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitMultipole()
void DefaultVisitor::visitMultipole (const Multipole & mult) override virtual inherited
Apply the algorithm to a multipole.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 73 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitMultipoleT()
void DefaultVisitor::visitMultipoleT (const MultipoleT & multT) override virtual inherited
Apply the algorithm to an arbitrary multipole.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 75 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitProbe()
void DefaultVisitor::visitProbe (const Probe & prob) override virtual inherited
Apply the algorithm to a Probe.
Implements BeamlineVisitor.
Definition at line 95 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitRBend()
void DefaultVisitor::visitRBend (const RBend & bend) override virtual inherited
Apply the algorithm to a rectangular bend.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 77 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitRFCavity()
void DefaultVisitor::visitRFCavity (const RFCavity & cav) override virtual inherited
Apply the algorithm to a RF cavity.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 81 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitRing()
void DefaultVisitor::visitRing (const Ring & ring) override virtual inherited
Apply the algorithm to a Ring.
Implements BeamlineVisitor.
Definition at line 79 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitSBend()
void DefaultVisitor::visitSBend (const SBend & bend) override virtual inherited
Apply the algorithm to a sector bend.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 83 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitScalingFFAMagnet()
void DefaultVisitor::visitScalingFFAMagnet (const ScalingFFAMagnet & spiral) override virtual inherited
Apply the algorithm to a scaling FFA magnet.
Implements BeamlineVisitor.
Definition at line 89 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitSolenoid()
void DefaultVisitor::visitSolenoid (const Solenoid & so) override virtual inherited
Apply the algorithm to a Solenoid.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 85 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitTravelingWave()
void DefaultVisitor::visitTravelingWave (const TravelingWave & trw) override virtual inherited
Apply the algorithm to a traveling wave.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 87 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitVariableRFCavity()
void DefaultVisitor::visitVariableRFCavity (const VariableRFCavity & cavity) override virtual inherited
Apply the algorithm to a variable RF cavity.
Implements BeamlineVisitor.
Definition at line 93 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitVerticalFFAMagnet()
void DefaultVisitor::visitVerticalFFAMagnet (const VerticalFFAMagnet & mag) override virtual inherited
Apply the algorithm to a vertical FFA magnet.
Implements BeamlineVisitor.
Definition at line 91 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
Member Data Documentation
back_beam
bool DefaultVisitor::back_beam protected inherited
Definition at line 110 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor(), DefaultVisitor::execute(), and visitComponent().
back_path
bool DefaultVisitor::back_path protected inherited
Definition at line 112 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor().
back_track
bool DefaultVisitor::back_track protected inherited
Definition at line 111 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor(), DefaultVisitor::execute(), and visitComponent().
cavities_m
FieldList Tracker::cavities_m
Definition at line 113 of file Tracker.h.
flip_B
double DefaultVisitor::flip_B protected inherited
Definition at line 115 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor().
flip_s
double DefaultVisitor::flip_s protected inherited
Definition at line 116 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor().
itsBeamline_m
const Beamline& Tracker::itsBeamline_m
Definition at line 115 of file Tracker.h.
Referenced by ParallelTracker::prepareSections().
itsBunch_m
PartBunch_t* Tracker::itsBunch_m protected
The bunch of particles to be tracked. Borrowed; lifetime is managed by TrackRun.
Definition at line 119 of file Tracker.h.
Referenced by ParallelTracker::activateEmittingContainers(), ParallelTracker::applyGlobalProcesses(), ParallelTracker::autophaseCavities(), ParallelTracker::changeDT(), ParallelTracker::computeExternalFields(), ParallelTracker::computeInitialBounds(), ParallelTracker::computeSpaceChargeFields(), ParallelTracker::doBinaryRepartition(), ParallelTracker::dumpStats(), ParallelTracker::emitFromEmissionSources(), ParallelTracker::execute(), ParallelTracker::findStartPositions(), getBunch(), ParallelTracker::hasEndOfLineReached(), ParallelTracker::printInitialContainerRefs(), ParallelTracker::resetFields(), ParallelTracker::selectDT(), ParallelTracker::setTime(), ParallelTracker::timeIntegration1(), ParallelTracker::timeIntegration2(), ParallelTracker::updateReferenceParticles(), ParallelTracker::updateRefToLabCSTrafo(), visitComponent(), ParallelTracker::visitConstantEFieldCavity(), ParallelTracker::visitDrift(), ParallelTracker::visitMarker(), ParallelTracker::visitMultipole(), ParallelTracker::visitMultipoleT(), ParallelTracker::visitRBend(), ParallelTracker::visitRFCavity(), ParallelTracker::visitSBend(), ParallelTracker::visitSolenoid(), ParallelTracker::visitTravelingWave(), and ParallelTracker::writePhaseSpace().
itsLine
const Beamline& DefaultVisitor::itsLine protected inherited
Definition at line 107 of file DefaultVisitor.h.
Referenced by DefaultVisitor::execute().
local_flip
bool DefaultVisitor::local_flip private inherited
Definition at line 130 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor(), DefaultVisitor::execute(), DefaultVisitor::visitBeamline(), and DefaultVisitor::visitFlaggedElmPtr().
The documentation for this class was generated from the following files:
Tracker.h
Tracker.cpp