OPALX (Object Oriented Parallel Accelerator Library for Exascal): SinusoidalTimeDependence Class Reference
SinusoidalTimeDependence Class Reference final
#include <SinusoidalTimeDependence.h>
Public Member Functions
SinusoidalTimeDependence (const std::vector< double > &f, const std::vector< double > &p, const std::vector< double > &a, const std::vector< double > &o)
SinusoidalTimeDependence ()=default
~SinusoidalTimeDependence () override=default
double getValue (double time) override
double getIntegral (double time) override
SinusoidalTimeDependence * clone () override
Inform & print (Inform &os) const
const std::vector< double > & getFrequencies () const
const std::vector< double > & getAmplitudes () const
const std::vector< double > & getOffsets () const
const std::vector< double > & getPhases () const
Static Public Member Functions
static std::shared_ptr< AbstractTimeDependence > getTimeDependence (const std::string &name)
static void setTimeDependence (const std::string &name, std::shared_ptr< AbstractTimeDependence > time_dep)
static std::string getName (const std::shared_ptr< AbstractTimeDependence > &time_dep)
Private Attributes
std::vector< double > f_m
std::vector< double > p_m
std::vector< double > a_m
std::vector< double > o_m
Static Private Attributes
static std::map< std::string, std::shared_ptr< AbstractTimeDependence > > td_map
Detailed Description
Time dependence that follows sum of a set of sinusoids sigma_over_i(a[i] / 2 * sin(2 * pi * f[i] * t + p[i]) + o[i]) a is the peak to peak amplitude, f is the frequency, p is the phase offset, o is the DC offset, t is the time.
Definition at line 32 of file SinusoidalTimeDependence.h.
Constructor & Destructor Documentation
SinusoidalTimeDependence() [1/2]
SinusoidalTimeDependence::SinusoidalTimeDependence (const std::vector< double > & f, const std::vector< double > & p, const std::vector< double > & a, const std::vector< double > & o)
Constructor
Parameters
f the frequencies in Hz; can be of arbitrary length
p the phase offsets in radians; can be of arbitrary length
a the peak-to-peak amplitude; can be of arbitrary length
o the DC offset; can be of arbitrary length (user is responsible for issues like floating point precision).
Definition at line 24 of file SinusoidalTimeDependence.cpp.
References a_m, f_m, o_m, and p_m.
Referenced by clone(), and ~SinusoidalTimeDependence().
SinusoidalTimeDependence() [2/2]
SinusoidalTimeDependence::SinusoidalTimeDependence () default
Default Constructor makes a 0 length polynomial
Referenced by clone().
~SinusoidalTimeDependence()
SinusoidalTimeDependence::~SinusoidalTimeDependence () override default
Destructor does default
References SinusoidalTimeDependence().
Member Function Documentation
clone()
SinusoidalTimeDependence * SinusoidalTimeDependence::clone () override virtual
Inheritable clone function
Returns
new SinusoidalTimeDependence that is a copy of this. User owns returned memory.
Implements AbstractTimeDependence.
Definition at line 74 of file SinusoidalTimeDependence.cpp.
References a_m, f_m, o_m, p_m, SinusoidalTimeDependence(), and SinusoidalTimeDependence().
Referenced by TEST().
getAmplitudes()
const std::vector< double > & SinusoidalTimeDependence::getAmplitudes () const inline nodiscard
Definition at line 74 of file SinusoidalTimeDependence.h.
References a_m.
getFrequencies()
const std::vector< double > & SinusoidalTimeDependence::getFrequencies () const inline nodiscard
Definition at line 73 of file SinusoidalTimeDependence.h.
References f_m.
getIntegral()
double SinusoidalTimeDependence::getIntegral (double time) override virtual
Return the integral from 0 to time
Parameters
time simulation time in seconds
Implements AbstractTimeDependence.
Definition at line 51 of file SinusoidalTimeDependence.cpp.
References a_m, f_m, o_m, p_m, and Physics::two_pi.
getName()
std::string AbstractTimeDependence::getName (const std::shared_ptr< AbstractTimeDependence > & time_dep) static inherited
Get the name corresponding to a given time_dep
Parameters
time_dep time dependence to lookup
Returns
name corresponding to the time dependence. Note that this just does a dumb loop over the stored map values; so O(N).
Exceptions
GeneralOpalException if time_dep is not recognised
Definition at line 40 of file AbstractTimeDependence.cpp.
References td_map.
Referenced by TEST(), and TEST().
getOffsets()
const std::vector< double > & SinusoidalTimeDependence::getOffsets () const inline nodiscard
Definition at line 75 of file SinusoidalTimeDependence.h.
References o_m.
getPhases()
const std::vector< double > & SinusoidalTimeDependence::getPhases () const inline nodiscard
Definition at line 76 of file SinusoidalTimeDependence.h.
References p_m.
getTimeDependence()
std::shared_ptr< AbstractTimeDependence > AbstractTimeDependence::getTimeDependence (const std::string & name) static inherited
Look up the time dependence that has a given name
Parameters
name name of the time dependence
Returns
shared_ptr to the appropriate time dependence.
Exceptions
GeneralOpalException if name is not recognised
Definition at line 24 of file AbstractTimeDependence.cpp.
References td_map.
Referenced by MultipoleT::initialiseTimeDependencies(), VariableRFCavity::initialiseTimeDependencies(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
getValue()
double SinusoidalTimeDependence::getValue (double time) override virtual
Return the sinusoidal value
Parameters
time simulation time in seconds
Implements AbstractTimeDependence.
Definition at line 29 of file SinusoidalTimeDependence.cpp.
References a_m, f_m, o_m, p_m, and Physics::pi.
Referenced by TEST().
print()
Inform & SinusoidalTimeDependence::print (Inform & os) const
Print the sinusoidals
Parameters
os "Inform" stream to which the sinusoidals are printed.
Definition at line 78 of file SinusoidalTimeDependence.cpp.
References a_m, f_m, o_m, and p_m.
Referenced by operator<<().
setTimeDependence()
void AbstractTimeDependence::setTimeDependence (const std::string & name, std::shared_ptr< AbstractTimeDependence > time_dep) static inherited
Add a value to the lookup table
Parameters
name name of the time dependence. If name already exists in the map, it is overwritten with the new value.
time_dep shared_ptr to the time dependence.
Definition at line 35 of file AbstractTimeDependence.cpp.
References td_map.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), and OpalSplineTimeDependence::update().
Member Data Documentation
a_m
std::vector<double> SinusoidalTimeDependence::a_m private
Definition at line 81 of file SinusoidalTimeDependence.h.
Referenced by clone(), getAmplitudes(), getIntegral(), getValue(), print(), and SinusoidalTimeDependence().
f_m
std::vector<double> SinusoidalTimeDependence::f_m private
Definition at line 79 of file SinusoidalTimeDependence.h.
Referenced by clone(), getFrequencies(), getIntegral(), getValue(), print(), and SinusoidalTimeDependence().
o_m
std::vector<double> SinusoidalTimeDependence::o_m private
Definition at line 82 of file SinusoidalTimeDependence.h.
Referenced by clone(), getIntegral(), getOffsets(), getValue(), print(), and SinusoidalTimeDependence().
p_m
std::vector<double> SinusoidalTimeDependence::p_m private
Definition at line 80 of file SinusoidalTimeDependence.h.
Referenced by clone(), getIntegral(), getPhases(), getValue(), print(), and SinusoidalTimeDependence().
td_map
std::map< std::string, std::shared_ptr< AbstractTimeDependence > > AbstractTimeDependence::td_map static private inherited
Initial value:
=
        std::map<std::string, std::shared_ptr<AbstractTimeDependence> >()
Definition at line 87 of file AbstractTimeDependence.h.
Referenced by getName(), getTimeDependence(), and setTimeDependence().
The documentation for this class was generated from the following files:
SinusoidalTimeDependence.h
SinusoidalTimeDependence.cpp