OPALX (Object Oriented Parallel Accelerator Library for Exascal): RangeSelector Class Reference
RangeSelector Class Reference
#include <RangeSelector.h>
Public Member Functions
RangeSelector (const Beamline &, const RangeRep &range)
Constructor.
virtual ~RangeSelector ()
virtual void execute ()
Execute the algorithm.
virtual void visitFlaggedElmPtr (const FlaggedElmPtr &)
Apply the visitor to an FlaggedElmPtr.
void visitComponent (const Component &) override
Apply the algorithm to an arbitrary component.
void visitBeamline (const Beamline &) override
Apply the algorithm to a beam line.
void visitConstantEFieldCavity (const ConstantEFieldCavity &) override
Apply the algorithm to a constant E-field cavity element.
void visitDrift (const Drift &) override
Apply the algorithm to a drift space.
void visitMarker (const Marker &) override
Apply the algorithm to a marker.
void visitMonitor (const Monitor &) override
Apply the algorithm to a beam position monitor.
void visitMultipole (const Multipole &) override
Apply the algorithm to a multipole.
void visitMultipoleT (const MultipoleT &) override
Apply the algorithm to an arbitrary multipole.
void visitRing (const Ring &) override
Apply the algorithm to a Ring.
void visitRFCavity (const RFCavity &) override
Apply the algorithm to a RF cavity.
void visitSolenoid (const Solenoid &) override
Apply the algorithm to a Solenoid.
void visitTravelingWave (const TravelingWave &) override
Apply the algorithm to a traveling wave.
void visitScalingFFAMagnet (const ScalingFFAMagnet &spiral) override
Apply the algorithm to a scaling FFA magnet.
void visitVerticalFFAMagnet (const VerticalFFAMagnet &) override
Apply the algorithm to a vertical FFA magnet.
void visitVariableRFCavity (const VariableRFCavity &) override
Apply the algorithm to a variable RF cavity.
void visitProbe (const Probe &prob) override
Apply the algorithm to a Probe.
Protected Member Functions
virtual void handleBeamline (const FlaggedElmPtr &)
The operation to be done for beamlines.
virtual void handleElement (const FlaggedElmPtr &)
The operation to be done for elements.
Protected Attributes
RangeRep itsRange
Working data for range.
const Beamline & itsLine
bool back_beam
bool back_track
bool back_path
double flip_B
double flip_s
Private Member Functions
RangeSelector ()
RangeSelector (const RangeSelector &)
void operator= (const RangeSelector &)
virtual void applyDefault (const ElementBase &)
Private Attributes
bool local_flip
Detailed Description
Definition at line 29 of file RangeSelector.h.
Constructor & Destructor Documentation
RangeSelector() [1/3]
RangeSelector::RangeSelector (const Beamline & beamline, const RangeRep & range)
Constructor.
Definition at line 31 of file RangeSelector.cpp.
~RangeSelector()
RangeSelector::~RangeSelector () virtual
Definition at line 36 of file RangeSelector.cpp.
RangeSelector() [2/3]
RangeSelector::RangeSelector () private
RangeSelector() [3/3]
RangeSelector::RangeSelector (const RangeSelector &) private
Member Function Documentation
applyDefault()
void DefaultVisitor::applyDefault (const ElementBase &) private virtual inherited
Definition at line 132 of file DefaultVisitor.cpp.
Referenced by DefaultVisitor::visitComponent(), DefaultVisitor::visitConstantEFieldCavity(), DefaultVisitor::visitDrift(), DefaultVisitor::visitMarker(), DefaultVisitor::visitMonitor(), DefaultVisitor::visitMultipole(), DefaultVisitor::visitMultipoleT(), DefaultVisitor::visitProbe(), DefaultVisitor::visitRFCavity(), DefaultVisitor::visitRing(), DefaultVisitor::visitScalingFFAMagnet(), DefaultVisitor::visitSolenoid(), DefaultVisitor::visitTravelingWave(), DefaultVisitor::visitVariableRFCavity(), and DefaultVisitor::visitVerticalFFAMagnet().
execute()
void RangeSelector::execute () virtual
Execute the algorithm.
Reimplemented from DefaultVisitor.
Reimplemented in Selector.
Definition at line 40 of file RangeSelector.cpp.
References DefaultVisitor::execute(), RangeRep::initialize(), and itsRange.
Referenced by Selector::execute().
handleBeamline()
void RangeSelector::handleBeamline (const FlaggedElmPtr & fep) protected virtual
The operation to be done for beamlines.
Definition at line 64 of file RangeSelector.cpp.
References DefaultVisitor::visitFlaggedElmPtr().
Referenced by visitFlaggedElmPtr().
handleElement()
void RangeSelector::handleElement (const FlaggedElmPtr & fep) protected virtual
The operation to be done for elements.
Reimplemented in Selector.
Definition at line 69 of file RangeSelector.cpp.
References RangeRep::isActive(), itsRange, and DefaultVisitor::visitFlaggedElmPtr().
Referenced by visitFlaggedElmPtr().
operator=()
void RangeSelector::operator= (const RangeSelector &) private
visitBeamline()
void DefaultVisitor::visitBeamline (const Beamline & bl) override virtual inherited
Apply the algorithm to a beam line.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 116 of file DefaultVisitor.cpp.
References Beamline::iterate(), and DefaultVisitor::local_flip.
visitComponent()
void DefaultVisitor::visitComponent (const Component &) override virtual inherited
Apply the algorithm to an arbitrary component.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker, and Tracker.
Definition at line 56 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitConstantEFieldCavity()
void DefaultVisitor::visitConstantEFieldCavity (const ConstantEFieldCavity & cav) override virtual inherited
Apply the algorithm to a constant E-field cavity element.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 60 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitDrift()
void DefaultVisitor::visitDrift (const Drift & drf) override virtual inherited
Apply the algorithm to a drift space.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 64 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitFlaggedElmPtr()
void RangeSelector::visitFlaggedElmPtr (const FlaggedElmPtr & fep) virtual
Apply the visitor to an FlaggedElmPtr.
Reimplemented from DefaultVisitor.
Definition at line 46 of file RangeSelector.cpp.
References RangeRep::enter(), ElmPtr::getElement(), handleBeamline(), handleElement(), itsRange, and RangeRep::leave().
visitMarker()
void DefaultVisitor::visitMarker (const Marker & mark) override virtual inherited
Apply the algorithm to a marker.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 68 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitMonitor()
void DefaultVisitor::visitMonitor (const Monitor & mon) override virtual inherited
Apply the algorithm to a beam position monitor.
Implements BeamlineVisitor.
Definition at line 72 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitMultipole()
void DefaultVisitor::visitMultipole (const Multipole & mult) override virtual inherited
Apply the algorithm to a multipole.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 76 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitMultipoleT()
void DefaultVisitor::visitMultipoleT (const MultipoleT & multT) override virtual inherited
Apply the algorithm to an arbitrary multipole.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 80 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitProbe()
void DefaultVisitor::visitProbe (const Probe & prob) override virtual inherited
Apply the algorithm to a Probe.
Implements BeamlineVisitor.
Definition at line 112 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitRFCavity()
void DefaultVisitor::visitRFCavity (const RFCavity & cav) override virtual inherited
Apply the algorithm to a RF cavity.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 88 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitRing()
void DefaultVisitor::visitRing (const Ring & ring) override virtual inherited
Apply the algorithm to a Ring.
Implements BeamlineVisitor.
Definition at line 84 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitScalingFFAMagnet()
void DefaultVisitor::visitScalingFFAMagnet (const ScalingFFAMagnet & spiral) override virtual inherited
Apply the algorithm to a scaling FFA magnet.
Implements BeamlineVisitor.
Definition at line 100 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitSolenoid()
void DefaultVisitor::visitSolenoid (const Solenoid & so) override virtual inherited
Apply the algorithm to a Solenoid.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 92 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitTravelingWave()
void DefaultVisitor::visitTravelingWave (const TravelingWave & trw) override virtual inherited
Apply the algorithm to a traveling wave.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 96 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitVariableRFCavity()
void DefaultVisitor::visitVariableRFCavity (const VariableRFCavity & cavity) override virtual inherited
Apply the algorithm to a variable RF cavity.
Implements BeamlineVisitor.
Definition at line 108 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitVerticalFFAMagnet()
void DefaultVisitor::visitVerticalFFAMagnet (const VerticalFFAMagnet & mag) override virtual inherited
Apply the algorithm to a vertical FFA magnet.
Implements BeamlineVisitor.
Definition at line 104 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
Member Data Documentation
back_beam
bool DefaultVisitor::back_beam protected inherited
Definition at line 101 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor(), DefaultVisitor::execute(), and Tracker::visitComponent().
back_path
bool DefaultVisitor::back_path protected inherited
Definition at line 103 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor().
back_track
bool DefaultVisitor::back_track protected inherited
Definition at line 102 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor(), DefaultVisitor::execute(), and Tracker::visitComponent().
flip_B
double DefaultVisitor::flip_B protected inherited
Definition at line 106 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor().
flip_s
double DefaultVisitor::flip_s protected inherited
Definition at line 107 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor().
itsLine
const Beamline& DefaultVisitor::itsLine protected inherited
Definition at line 98 of file DefaultVisitor.h.
Referenced by DefaultVisitor::execute().
itsRange
RangeRep RangeSelector::itsRange protected
Working data for range.
Definition at line 55 of file RangeSelector.h.
Referenced by execute(), handleElement(), Selector::handleElement(), and visitFlaggedElmPtr().
local_flip
bool DefaultVisitor::local_flip private inherited
Definition at line 121 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor(), DefaultVisitor::execute(), DefaultVisitor::visitBeamline(), and DefaultVisitor::visitFlaggedElmPtr().
The documentation for this class was generated from the following files:
RangeSelector.h
RangeSelector.cpp