OPALX (Object Oriented Parallel Accelerator Library for Exascal): interpolation::ThreeDGrid Class Reference
interpolation::ThreeDGrid Class Reference
#include <ThreeDGrid.h>
Public Member Functions
ThreeDGrid * clone ()
Mesh * dual () const
ThreeDGrid ()
ThreeDGrid (double dX, double dY, double dZ, double minX, double minY, double minZ, int numberOfXCoords, int numberOfYCoords, int numberOfZCoords)
ThreeDGrid (int xSize, const double *x, int ySize, const double *y, int zSize, const double *z)
ThreeDGrid (std::vector< double > x, std::vector< double > y, std::vector< double > z)
~ThreeDGrid ()
double & x (const int &i)
double & y (const int &j)
double & z (const int &k)
const double & x (const int &i) const
const double & y (const int &j) const
const double & z (const int &j) const
int xSize () const
int ySize () const
int zSize () const
std::vector< double > xVector ()
std::vector< double > yVector ()
std::vector< double > zVector ()
double * newXArray ()
double * newYArray ()
double * newZArray ()
void xLowerBound (const double &x, int &xIndex) const
void yLowerBound (const double &y, int &yIndex) const
void zLowerBound (const double &z, int &zIndex) const
void lowerBound (const double &x, int &xIndex, const double &y, int &yIndex, const double &z, int &zIndex) const
void lowerBound (const double &x, const double &y, const double &z, Mesh::Iterator &it) const
double minX () const
double maxX () const
double minY () const
double maxY () const
double minZ () const
double maxZ () const
void setX (int nXCoords, double *x)
void setY (int nYCoords, double *y)
void setZ (int nZCoords, double *z)
void add (VectorMap *map)
void remove (VectorMap *map)
Mesh::Iterator begin () const
Mesh::Iterator end () const
virtual void getPosition (const Mesh::Iterator &it, double *position) const
int getPositionDimension () const
int toInteger (const Mesh::Iterator &lhs) const
void setConstantSpacing (bool spacing)
void setConstantSpacing ()
bool getConstantSpacing () const
Mesh::Iterator getNearest (const double *position) const
Static Public Member Functions
static void vectorLowerBound (std::vector< double > vec, double x, int &index)
Protected Member Functions
virtual Mesh::Iterator & addEquals (Mesh::Iterator &lhs, int difference) const
virtual Mesh::Iterator & subEquals (Mesh::Iterator &lhs, int difference) const
virtual Mesh::Iterator & addEquals (Mesh::Iterator &lhs, const Mesh::Iterator &rhs) const
virtual Mesh::Iterator & subEquals (Mesh::Iterator &lhs, const Mesh::Iterator &rhs) const
virtual Mesh::Iterator & addOne (Mesh::Iterator &lhs) const
virtual Mesh::Iterator & subOne (Mesh::Iterator &lhs) const
virtual bool isGreater (const Mesh::Iterator &lhs, const Mesh::Iterator &rhs) const
Private Attributes
std::vector< double > x_m
std::vector< double > y_m
std::vector< double > z_m
int xSize_m
int ySize_m
int zSize_m
std::vector< VectorMap * > maps_m
bool constantSpacing_m
Friends
Mesh::Iterator operator++ (Mesh::Iterator &lhs, int)
Mesh::Iterator operator-- (Mesh::Iterator &lhs, int)
Mesh::Iterator & operator++ (Mesh::Iterator &lhs)
Mesh::Iterator & operator-- (Mesh::Iterator &lhs)
Mesh::Iterator operator- (const Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
Mesh::Iterator operator+ (const Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
Mesh::Iterator & operator-= (Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
Mesh::Iterator & operator+= (Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
bool operator== (const Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
bool operator!= (const Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
bool operator>= (const Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
bool operator<= (const Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
bool operator< (const Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
bool operator> (const Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
Detailed Description
ThreeDGrid holds grid information for a rectangular grid used in e.g. interpolation
ThreeDGrid holds the necessary information for regular and irregular grid data for interpolation routines.
Constructor is provided to generate a regular grid given grid spacing etc and an irregular grid given lists of x, y, z data for the grid points. Nearest either calculates nearest grid point a priori for regular grids or uses std::lower_bound to calculate nearest grid point (list bisection or somesuch). Controlled by _constantSpacing flag. The regular spacing lookup is quicker, so prefer constant spacing.
ThreeDGrid holds a list of pointers to VectorMaps that use the grid for interpolation and functions to Add and Remove VectorMaps. If the Remove function removes the last VectorMap, then the ThreeDGrid is deleted. It's a sort of smart pointer.
Definition at line 57 of file ThreeDGrid.h.
Constructor & Destructor Documentation
ThreeDGrid() [1/4]
interpolation::ThreeDGrid::ThreeDGrid ()
Default constructor
Definition at line 33 of file ThreeDGrid.cpp.
References setConstantSpacing(), x_m, y_m, and z_m.
Referenced by clone(), and dual().
ThreeDGrid() [2/4]
interpolation::ThreeDGrid::ThreeDGrid (double dX, double dY, double dZ, double minX, double minY, double minZ, int numberOfXCoords, int numberOfYCoords, int numberOfZCoords)
Make a regular rectangular ThreeDGrid
Set up a ThreeDGrid with regular grid spacing (same distance between every point)
Parameters
dX step size in x; should be positive
dY step size in y; should be positive
dZ step size in z; should be positive
minX x position of grid lower edge
minY y position of grid lower edge
minZ z position of grid lower edge
numberOfXCoords number of x coordinates on grid; should be > 1
numberOfYCoords number of y coordinates on grid; should be > 1
numberOfZCoords number of z coordinates on grid; should be > 1
Definition at line 70 of file ThreeDGrid.cpp.
References minX(), minY(), minZ(), setConstantSpacing(), x_m, y_m, and z_m.
ThreeDGrid() [3/4]
interpolation::ThreeDGrid::ThreeDGrid (int xSize, const double * x, int ySize, const double * y, int zSize, const double * z)
Make a irregular rectangular ThreeDGrid
Set up a ThreeDGrid with irregular grid spacing
Parameters
xSize number of points in x
x x points array
ySize number of points in y
y y points array
zSize number of points in Z
z z point array ThreeDGrid deep copies the data pointed to by x, y, z (i.e. it does not take ownership of these arrays).
Definition at line 40 of file ThreeDGrid.cpp.
References setConstantSpacing(), xSize_m, ySize_m, and zSize_m.
ThreeDGrid() [4/4]
interpolation::ThreeDGrid::ThreeDGrid (std::vector< double > x, std::vector< double > y, std::vector< double > z)
Make a irregular rectangular ThreeDGrid
Set up a ThreeDGrid with irregular grid spacing
Parameters
x x points array
y y points array
z z point array
Definition at line 55 of file ThreeDGrid.cpp.
References setConstantSpacing(), xSize_m, ySize_m, and zSize_m.
~ThreeDGrid()
interpolation::ThreeDGrid::~ThreeDGrid ()
Destructor
Definition at line 87 of file ThreeDGrid.cpp.
Member Function Documentation
add()
void interpolation::ThreeDGrid::add (VectorMap * map)
Add *map to the maps_m list if it has not already been added
Definition at line 257 of file ThreeDGrid.cpp.
References maps_m.
Referenced by interpolation::Interpolator3dGridTo3d::setAll(), interpolation::Interpolator3dGridTo1d::setGrid(), interpolation::Interpolator3dGridTo3d::setGrid(), and interpolation::TriLinearInterpolator::TriLinearInterpolator().
addEquals() [1/2]
Mesh::Iterator & interpolation::ThreeDGrid::addEquals (Mesh::Iterator & lhs, const Mesh::Iterator & rhs) const protected virtual
Add difference to lhs and then return lhs
Implements interpolation::Mesh.
Definition at line 192 of file ThreeDGrid.cpp.
References addEquals(), and interpolation::Mesh::Iterator::toInteger().
addEquals() [2/2]
Mesh::Iterator & interpolation::ThreeDGrid::addEquals (Mesh::Iterator & lhs, int difference) const protected virtual
Add difference to lhs and then return lhs
Implements interpolation::Mesh.
Definition at line 124 of file ThreeDGrid.cpp.
References interpolation::Mesh::Iterator::state_m, subEquals(), ySize_m, and zSize_m.
Referenced by addEquals(), and subEquals().
addOne()
Mesh::Iterator & interpolation::ThreeDGrid::addOne (Mesh::Iterator & lhs) const protected virtual
Increment position of lhs by one and then return lhs
Implements interpolation::Mesh.
Definition at line 202 of file ThreeDGrid.cpp.
References interpolation::Mesh::Iterator::state_m, ySize_m, and zSize_m.
begin()
Mesh::Iterator interpolation::ThreeDGrid::begin () const virtual
Return an iterator pointing at the first element in the ThreeDGrid
Implements interpolation::Mesh.
Definition at line 91 of file ThreeDGrid.cpp.
clone()
ThreeDGrid * interpolation::ThreeDGrid::clone () inline virtual
Deep copy the grid
Implements interpolation::Mesh.
Definition at line 62 of file ThreeDGrid.h.
References ThreeDGrid().
dual()
Mesh * interpolation::ThreeDGrid::dual () const virtual
Not implemented (returns nullptr)
Implements interpolation::Mesh.
Definition at line 108 of file ThreeDGrid.cpp.
References ThreeDGrid(), x_m, y_m, and z_m.
end()
Mesh::Iterator interpolation::ThreeDGrid::end () const virtual
Return an iterator pointing at the last+1 element in the ThreeDGrid
Implements interpolation::Mesh.
Definition at line 95 of file ThreeDGrid.cpp.
References end(), and xSize_m.
Referenced by end().
getConstantSpacing()
bool interpolation::ThreeDGrid::getConstantSpacing () const inline
Return true if using constant spacing
Definition at line 472 of file ThreeDGrid.h.
References constantSpacing_m.
getNearest()
Mesh::Iterator interpolation::ThreeDGrid::getNearest (const double * position) const virtual
Return the point in the mesh nearest to position
Implements interpolation::Mesh.
Definition at line 284 of file ThreeDGrid.cpp.
References lowerBound(), x_m, xSize_m, y_m, ySize_m, z_m, and zSize_m.
getPosition()
void interpolation::ThreeDGrid::getPosition (const Mesh::Iterator & it, double * position) const virtual
Fill position with the position of it
Parameters
it iterator pointing at a grid position
position array of length >= 3 that will be filled with the position of it
Implements interpolation::Mesh.
Definition at line 101 of file ThreeDGrid.cpp.
References interpolation::Mesh::Iterator::state_m, x(), y(), and z().
getPositionDimension()
int interpolation::ThreeDGrid::getPositionDimension () const inline virtual
Returns 3, the dimension of the space of the grid
Implements interpolation::Mesh.
Definition at line 458 of file ThreeDGrid.h.
isGreater()
bool interpolation::ThreeDGrid::isGreater (const Mesh::Iterator & lhs, const Mesh::Iterator & rhs) const protected virtual
Return true if rhs is greater than lhs
Implements interpolation::Mesh.
Definition at line 230 of file ThreeDGrid.cpp.
References interpolation::Mesh::Iterator::state_m.
lowerBound() [1/2]
void interpolation::ThreeDGrid::lowerBound (const double & x, const double & y, const double & z, Mesh::Iterator & it) const inline
Find the iterator of the nearest point on the grid less than x, y, z
Note that in the case of a regular grid there is no bound checking; in the case of an irregular grid we always return an element in the grid
Definition at line 387 of file ThreeDGrid.h.
References x(), xLowerBound(), y(), yLowerBound(), z(), and zLowerBound().
lowerBound() [2/2]
void interpolation::ThreeDGrid::lowerBound (const double & x, int & xIndex, const double & y, int & yIndex, const double & z, int & zIndex) const inline
Find the indices of the nearest point on the grid less than x, y, z
Note that in the case of a regular grid there is no bound checking; in the case of an irregular grid we always return an element in the grid
Definition at line 379 of file ThreeDGrid.h.
References x(), xLowerBound(), y(), yLowerBound(), z(), and zLowerBound().
Referenced by interpolation::TriLinearInterpolator::function(), and getNearest().
maxX()
double interpolation::ThreeDGrid::maxX () const inline
Return the largest value of x in the grid
Definition at line 426 of file ThreeDGrid.h.
References x_m, and xSize_m.
Referenced by interpolation::Interpolator3dGridTo3d::function().
maxY()
double interpolation::ThreeDGrid::maxY () const inline
Return the largest value of y in the grid
Definition at line 434 of file ThreeDGrid.h.
References y_m, and ySize_m.
Referenced by interpolation::Interpolator3dGridTo3d::function().
maxZ()
double interpolation::ThreeDGrid::maxZ () const inline
Return the largest value of z in the grid
Definition at line 442 of file ThreeDGrid.h.
References z_m, and zSize_m.
Referenced by interpolation::Interpolator3dGridTo3d::function().
minX()
double interpolation::ThreeDGrid::minX () const inline
Return the smallest value of x in the grid
Definition at line 422 of file ThreeDGrid.h.
References x_m.
Referenced by interpolation::Interpolator3dGridTo3d::function(), and ThreeDGrid().
minY()
double interpolation::ThreeDGrid::minY () const inline
Return the smallest value of y in the grid
Definition at line 430 of file ThreeDGrid.h.
References y_m.
Referenced by interpolation::Interpolator3dGridTo3d::function(), and ThreeDGrid().
minZ()
double interpolation::ThreeDGrid::minZ () const inline
Return the smallest value of z in the grid
Definition at line 438 of file ThreeDGrid.h.
References z_m.
Referenced by interpolation::Interpolator3dGridTo3d::function(), and ThreeDGrid().
newXArray()
double * interpolation::ThreeDGrid::newXArray () inline
Allocate a new array containing x grid data
Definition at line 358 of file ThreeDGrid.h.
References x(), and x_m.
newYArray()
double * interpolation::ThreeDGrid::newYArray () inline
Allocate a new array containing y grid data
Definition at line 365 of file ThreeDGrid.h.
References y(), and y_m.
newZArray()
double * interpolation::ThreeDGrid::newZArray () inline
Allocate a new array containing z grid data
Definition at line 372 of file ThreeDGrid.h.
References z(), and z_m.
remove()
void interpolation::ThreeDGrid::remove (VectorMap * map)
Remove *map from the maps_m list if it has not already been removed. If there are no more maps in the list, delete this
Definition at line 245 of file ThreeDGrid.cpp.
References maps_m.
Referenced by interpolation::Interpolator3dGridTo1d::clear(), interpolation::Interpolator3dGridTo3d::clear(), interpolation::Interpolator3dGridTo3d::setAll(), interpolation::Interpolator3dGridTo1d::setGrid(), and interpolation::Interpolator3dGridTo3d::setGrid().
setConstantSpacing() [1/2]
void interpolation::ThreeDGrid::setConstantSpacing ()
Autodetect constant spacing with float tolerance of 1e-9
Definition at line 265 of file ThreeDGrid.cpp.
References constantSpacing_m, x_m, y_m, and z_m.
Referenced by ThreeDGrid(), ThreeDGrid(), ThreeDGrid(), and ThreeDGrid().
setConstantSpacing() [2/2]
void interpolation::ThreeDGrid::setConstantSpacing (bool spacing) inline
Set to true to use constant spacing
If constant spacing is true, assume regular grid with spacing given by separation of first two elements in each dimension
Definition at line 468 of file ThreeDGrid.h.
References constantSpacing_m.
setX()
void interpolation::ThreeDGrid::setX (int nXCoords, double * x) inline
Reset x grid points - note may need to set SetConstantSpacing()
Definition at line 446 of file ThreeDGrid.h.
References x(), and x_m.
Referenced by interpolation::Interpolator3dGridTo1d::setX(), and interpolation::Interpolator3dGridTo3d::setX().
setY()
void interpolation::ThreeDGrid::setY (int nYCoords, double * y) inline
Reset y grid points - note may need to set SetConstantSpacing()
Definition at line 450 of file ThreeDGrid.h.
References y(), and y_m.
Referenced by interpolation::Interpolator3dGridTo1d::setY(), and interpolation::Interpolator3dGridTo3d::setY().
setZ()
void interpolation::ThreeDGrid::setZ (int nZCoords, double * z) inline
Reset z grid points - note may need to set SetConstantSpacing()
Definition at line 454 of file ThreeDGrid.h.
References z(), and z_m.
Referenced by interpolation::Interpolator3dGridTo1d::setZ(), and interpolation::Interpolator3dGridTo3d::setZ().
subEquals() [1/2]
Mesh::Iterator & interpolation::ThreeDGrid::subEquals (Mesh::Iterator & lhs, const Mesh::Iterator & rhs) const protected virtual
Subtract difference from lhs and then return lhs
Implements interpolation::Mesh.
Definition at line 197 of file ThreeDGrid.cpp.
References subEquals(), and interpolation::Mesh::Iterator::toInteger().
subEquals() [2/2]
Mesh::Iterator & interpolation::ThreeDGrid::subEquals (Mesh::Iterator & lhs, int difference) const protected virtual
Subtract difference from lhs and then return lhs
Implements interpolation::Mesh.
Definition at line 146 of file ThreeDGrid.cpp.
References addEquals(), interpolation::Mesh::Iterator::state_m, ySize_m, and zSize_m.
Referenced by addEquals(), and subEquals().
subOne()
Mesh::Iterator & interpolation::ThreeDGrid::subOne (Mesh::Iterator & lhs) const protected virtual
Decrement position of lhs by one and then return lhs
Implements interpolation::Mesh.
Definition at line 215 of file ThreeDGrid.cpp.
References interpolation::Mesh::Iterator::state_m, ySize_m, and zSize_m.
toInteger()
int interpolation::ThreeDGrid::toInteger (const Mesh::Iterator & lhs) const inline virtual
Converts from iterator to integer value
0 corresponds to the mesh beginning. integers index (right most index) indexes z, middle index is y, most significant (left most index) indexes x.
Implements interpolation::Mesh.
Definition at line 462 of file ThreeDGrid.h.
References interpolation::Mesh::Iterator::getState(), ySize_m, and zSize_m.
vectorLowerBound()
void interpolation::ThreeDGrid::vectorLowerBound (std::vector< double > vec, double x, int & index) static
Custom LowerBound routine like std::lower_bound
Make a binary search to find the element in vec with vec[i] <= x.
Parameters
vec STL vector object (could make this any sorted iterator...)
x object for which to search.
index vectorLowerBound sets index to the position of the element. If x < vec[0], vectorLowerBound fills with -1.
Definition at line 168 of file ThreeDGrid.cpp.
References x().
Referenced by xLowerBound(), yLowerBound(), and zLowerBound().
x() [1/2]
double & interpolation::ThreeDGrid::x (const int & i) inline
Get ith coordinate in x
Round bracket indexing starts at 1 goes to nCoords
Definition at line 122 of file ThreeDGrid.h.
References x_m.
Referenced by interpolation::TriLinearInterpolator::function(), getPosition(), lowerBound(), lowerBound(), newXArray(), setX(), vectorLowerBound(), and xLowerBound().
x() [2/2]
const double & interpolation::ThreeDGrid::x (const int & i) const inline
Get ith coordinate in x
Round bracket indexing starts at 1 goes to nCoords
Definition at line 140 of file ThreeDGrid.h.
References x_m.
xLowerBound()
void interpolation::ThreeDGrid::xLowerBound (const double & x, int & xIndex) const inline
Find the index of the nearest point less than x
Note that in the case of a regular grid there is no bound checking; in the case of an irregular grid we always return an element in the grid
Definition at line 399 of file ThreeDGrid.h.
References constantSpacing_m, vectorLowerBound(), x(), and x_m.
Referenced by lowerBound(), and lowerBound().
xSize()
int interpolation::ThreeDGrid::xSize () const inline
Get size of x data
Definition at line 155 of file ThreeDGrid.h.
References x_m.
Referenced by interpolation::TriLinearInterpolator::function(), interpolation::Interpolator3dGridTo1d::getNumberOfXCoords(), interpolation::Interpolator3dGridTo3d::getNumberOfXCoords(), and interpolation::TriLinearInterpolator::TriLinearInterpolator().
xVector()
std::vector< double > interpolation::ThreeDGrid::xVector () inline
Get vector containing x grid data
Definition at line 164 of file ThreeDGrid.h.
References x_m.
y() [1/2]
double & interpolation::ThreeDGrid::y (const int & j) inline
Get ith coordinate in y
Round bracket indexing starts at 1 goes to nCoords
Definition at line 128 of file ThreeDGrid.h.
References y_m.
Referenced by interpolation::TriLinearInterpolator::function(), getPosition(), lowerBound(), lowerBound(), newYArray(), setY(), and yLowerBound().
y() [2/2]
const double & interpolation::ThreeDGrid::y (const int & j) const inline
Get ith coordinate in y
Round bracket indexing starts at 1 goes to nCoords
Definition at line 146 of file ThreeDGrid.h.
References y_m.
yLowerBound()
void interpolation::ThreeDGrid::yLowerBound (const double & y, int & yIndex) const inline
Find the index of the nearest point less than y
Note that in the case of a regular grid there is no bound checking; in the case of an irregular grid we always return an element in the grid
Definition at line 408 of file ThreeDGrid.h.
References constantSpacing_m, vectorLowerBound(), y(), and y_m.
Referenced by lowerBound(), and lowerBound().
ySize()
int interpolation::ThreeDGrid::ySize () const inline
Get size of y data
Definition at line 158 of file ThreeDGrid.h.
References y_m.
Referenced by interpolation::TriLinearInterpolator::function(), interpolation::Interpolator3dGridTo1d::getNumberOfYCoords(), interpolation::Interpolator3dGridTo3d::getNumberOfYCoords(), and interpolation::TriLinearInterpolator::TriLinearInterpolator().
yVector()
std::vector< double > interpolation::ThreeDGrid::yVector () inline
Get vector containing y grid data
Definition at line 167 of file ThreeDGrid.h.
References y_m.
z() [1/2]
const double & interpolation::ThreeDGrid::z (const int & j) const inline
Get ith coordinate in z
Round bracket indexing starts at 1 goes to nCoords
Definition at line 152 of file ThreeDGrid.h.
References z_m.
z() [2/2]
double & interpolation::ThreeDGrid::z (const int & k) inline
Get ith coordinate in z
Round bracket indexing starts at 1 goes to nCoords
Definition at line 134 of file ThreeDGrid.h.
References z_m.
Referenced by interpolation::TriLinearInterpolator::function(), getPosition(), lowerBound(), lowerBound(), newZArray(), setZ(), and zLowerBound().
zLowerBound()
void interpolation::ThreeDGrid::zLowerBound (const double & z, int & zIndex) const inline
Find the index of the nearest point less than z
Note that in the case of a regular grid there is no bound checking; in the case of an irregular grid we always return an element in the grid
Definition at line 415 of file ThreeDGrid.h.
References constantSpacing_m, vectorLowerBound(), z(), and z_m.
Referenced by lowerBound(), and lowerBound().
zSize()
int interpolation::ThreeDGrid::zSize () const inline
Get size of z data
Definition at line 161 of file ThreeDGrid.h.
References z_m.
Referenced by interpolation::TriLinearInterpolator::function(), interpolation::Interpolator3dGridTo1d::getNumberOfZCoords(), interpolation::Interpolator3dGridTo3d::getNumberOfZCoords(), and interpolation::TriLinearInterpolator::TriLinearInterpolator().
zVector()
std::vector< double > interpolation::ThreeDGrid::zVector () inline
Get vector containing z grid data
Definition at line 170 of file ThreeDGrid.h.
References z_m.
Friends And Related Symbol Documentation
operator!=
bool operator!= (const Mesh::Iterator & lhs, const Mesh::Iterator & rhs) friend
Return true if lhs does not index the same position as rhs
operator+
Mesh::Iterator operator+ (const Mesh::Iterator & lhs, const Mesh::Iterator & rhs) friend
Addition operator - adds offset of rhs of rhs relative to Begin() to lhs
operator++ [1/2]
Mesh::Iterator & operator++ (Mesh::Iterator & lhs) friend
Prefix increment operator ++it
operator++ [2/2]
Mesh::Iterator operator++ (Mesh::Iterator & lhs, int) friend
Postfix increment operator it++ advances iterator by one
operator+=
Mesh::Iterator & operator+= (Mesh::Iterator & lhs, const Mesh::Iterator & rhs) friend
Addition operator - adds offset of rhs of rhs relative to Begin() to lhs and returns lhs
operator-
Mesh::Iterator operator- (const Mesh::Iterator & lhs, const Mesh::Iterator & rhs) friend
Subtraction operator - subtracts offset of rhs relative to Begin() from lhs
operator-- [1/2]
Mesh::Iterator & operator-- (Mesh::Iterator & lhs) friend
Prefix decrement operator –it retreats iterator by one
operator-- [2/2]
Mesh::Iterator operator-- (Mesh::Iterator & lhs, int) friend
Postfix decrement operator it– retreats iterator by one
operator-=
Mesh::Iterator & operator-= (Mesh::Iterator & lhs, const Mesh::Iterator & rhs) friend
Subtraction operator - subtracts offset of rhs relative to Begin() from lhs and returns lhs
operator<
bool operator< (const Mesh::Iterator & lhs, const Mesh::Iterator & rhs) friend
Return true if lhs indexes a position less than rhs i.e. successive operation of decrement operator would eventually reach lhs
operator<=
bool operator<= (const Mesh::Iterator & lhs, const Mesh::Iterator & rhs) friend
Return true if lhs indexes a position less than or equal to rhs i.e. successive operation of decrement operator would eventually reach lhs
operator==
bool operator== (const Mesh::Iterator & lhs, const Mesh::Iterator & rhs) friend
Return true if lhs indexes the same position as rhs
operator>
bool operator> (const Mesh::Iterator & lhs, const Mesh::Iterator & rhs) friend
Return true if lhs indexes a position greater than rhs i.e. successive operation of increment operator would eventually reach lhs
operator>=
bool operator>= (const Mesh::Iterator & lhs, const Mesh::Iterator & rhs) friend
Return true if lhs indexes a position greater than or equal to rhs i.e. successive operation of increment operator would eventually reach lhs
Member Data Documentation
constantSpacing_m
bool interpolation::ThreeDGrid::constantSpacing_m private
Definition at line 329 of file ThreeDGrid.h.
Referenced by getConstantSpacing(), setConstantSpacing(), setConstantSpacing(), xLowerBound(), yLowerBound(), and zLowerBound().
maps_m
std::vector<VectorMap*> interpolation::ThreeDGrid::maps_m private
Definition at line 328 of file ThreeDGrid.h.
Referenced by add(), and remove().
x_m
std::vector<double> interpolation::ThreeDGrid::x_m private
Definition at line 322 of file ThreeDGrid.h.
Referenced by dual(), getNearest(), maxX(), minX(), newXArray(), setConstantSpacing(), setX(), ThreeDGrid(), ThreeDGrid(), x(), x(), xLowerBound(), xSize(), and xVector().
xSize_m
int interpolation::ThreeDGrid::xSize_m private
Definition at line 325 of file ThreeDGrid.h.
Referenced by end(), getNearest(), maxX(), ThreeDGrid(), and ThreeDGrid().
y_m
std::vector<double> interpolation::ThreeDGrid::y_m private
Definition at line 323 of file ThreeDGrid.h.
Referenced by dual(), getNearest(), maxY(), minY(), newYArray(), setConstantSpacing(), setY(), ThreeDGrid(), ThreeDGrid(), y(), y(), yLowerBound(), ySize(), and yVector().
ySize_m
int interpolation::ThreeDGrid::ySize_m private
Definition at line 326 of file ThreeDGrid.h.
Referenced by addEquals(), addOne(), getNearest(), maxY(), subEquals(), subOne(), ThreeDGrid(), ThreeDGrid(), and toInteger().
z_m
std::vector<double> interpolation::ThreeDGrid::z_m private
Definition at line 324 of file ThreeDGrid.h.
Referenced by dual(), getNearest(), maxZ(), minZ(), newZArray(), setConstantSpacing(), setZ(), ThreeDGrid(), ThreeDGrid(), z(), z(), zLowerBound(), zSize(), and zVector().
zSize_m
int interpolation::ThreeDGrid::zSize_m private
Definition at line 327 of file ThreeDGrid.h.
Referenced by addEquals(), addOne(), getNearest(), maxZ(), subEquals(), subOne(), ThreeDGrid(), ThreeDGrid(), and toInteger().
The documentation for this class was generated from the following files:
ThreeDGrid.h
ThreeDGrid.cpp