OPALX (Object Oriented Parallel Accelerator Library for Exascal): matheval::detail::SimpleMathParser< real_t > Class Template Reference
matheval::detail::SimpleMathParser< real_t > Class Template Reference
#include <matheval.hpp>
Public Member Functions
SimpleMathParser (const std::string &input)
expr_ast< real_t > parse ()
Private Member Functions
void skipWhitespace ()
bool match (char c)
bool match (const std::string &str)
void expect (char c)
expr_ast< real_t > parseExpression ()
expr_ast< real_t > parseTerm ()
expr_ast< real_t > parseFactor ()
expr_ast< real_t > parsePrimary ()
expr_ast< real_t > parseNumber ()
std::string parseIdentifier ()
Static Private Member Functions
static const std::map< std::string, real_t > & getConstants ()
static const std::map< std::string, typename unary_op< real_t >::op_t > & getUnaryFunctions ()
static const std::map< std::string, typename binary_op< real_t >::op_t > & getBinaryFunctions ()
Private Attributes
std::string input_
size_t pos_
Detailed Description
template<typename real_t>
class matheval::detail::SimpleMathParser< real_t >
Definition at line 409 of file matheval.hpp.
Constructor & Destructor Documentation
SimpleMathParser()
template<typename real_t> matheval::detail::SimpleMathParser< real_t >::SimpleMathParser (const std::string & input) inline
Definition at line 411 of file matheval.hpp.
References input_, and pos_.
Member Function Documentation
expect()
template<typename real_t> void matheval::detail::SimpleMathParser< real_t >::expect (char c) inline private
Definition at line 453 of file matheval.hpp.
References match().
Referenced by parsePrimary().
getBinaryFunctions()
template<typename real_t> const std::map< std::string, typename binary_op< real_t >::op_t > & matheval::detail::SimpleMathParser< real_t >::getBinaryFunctions () inline static private
Definition at line 666 of file matheval.hpp.
Referenced by parsePrimary().
getConstants()
template<typename real_t> const std::map< std::string, real_t > & matheval::detail::SimpleMathParser< real_t >::getConstants () inline static private
Definition at line 619 of file matheval.hpp.
Referenced by parsePrimary().
getUnaryFunctions()
template<typename real_t> const std::map< std::string, typename unary_op< real_t >::op_t > & matheval::detail::SimpleMathParser< real_t >::getUnaryFunctions () inline static private
Definition at line 629 of file matheval.hpp.
References matheval::detail::math::deg(), matheval::detail::math::isinf(), matheval::detail::math::isnan(), matheval::detail::math::rad(), and matheval::detail::math::sgn().
Referenced by parsePrimary().
match() [1/2]
template<typename real_t> bool matheval::detail::SimpleMathParser< real_t >::match (char c) inline private
Definition at line 435 of file matheval.hpp.
References input_, pos_, and skipWhitespace().
Referenced by expect(), parseExpression(), parseFactor(), parsePrimary(), and parseTerm().
match() [2/2]
template<typename real_t> bool matheval::detail::SimpleMathParser< real_t >::match (const std::string & str) inline private
Definition at line 444 of file matheval.hpp.
References input_, pos_, and skipWhitespace().
parse()
template<typename real_t> expr_ast< real_t > matheval::detail::SimpleMathParser< real_t >::parse () inline
Definition at line 413 of file matheval.hpp.
References input_, parseExpression(), pos_, and skipWhitespace().
Referenced by matheval::detail::parse().
parseExpression()
template<typename real_t> expr_ast< real_t > matheval::detail::SimpleMathParser< real_t >::parseExpression () inline private
Definition at line 459 of file matheval.hpp.
References match(), and parseTerm().
Referenced by parse(), and parsePrimary().
parseFactor()
template<typename real_t> expr_ast< real_t > matheval::detail::SimpleMathParser< real_t >::parseFactor () inline private
Definition at line 491 of file matheval.hpp.
References match(), parseFactor(), and parsePrimary().
Referenced by parseFactor(), and parseTerm().
parseIdentifier()
template<typename real_t> std::string matheval::detail::SimpleMathParser< real_t >::parseIdentifier () inline private
Definition at line 602 of file matheval.hpp.
References input_, pos_, and skipWhitespace().
Referenced by parsePrimary().
parseNumber()
template<typename real_t> expr_ast< real_t > matheval::detail::SimpleMathParser< real_t >::parseNumber () inline private
Definition at line 561 of file matheval.hpp.
References input_, pos_, and skipWhitespace().
Referenced by parsePrimary().
parsePrimary()
template<typename real_t> expr_ast< real_t > matheval::detail::SimpleMathParser< real_t >::parsePrimary () inline private
Definition at line 500 of file matheval.hpp.
References expect(), getBinaryFunctions(), getConstants(), getUnaryFunctions(), input_, match(), parseExpression(), parseIdentifier(), parseNumber(), parsePrimary(), pos_, and skipWhitespace().
Referenced by parseFactor(), and parsePrimary().
parseTerm()
template<typename real_t> expr_ast< real_t > matheval::detail::SimpleMathParser< real_t >::parseTerm () inline private
Definition at line 473 of file matheval.hpp.
References match(), and parseFactor().
Referenced by parseExpression().
skipWhitespace()
template<typename real_t> void matheval::detail::SimpleMathParser< real_t >::skipWhitespace () inline private
Definition at line 428 of file matheval.hpp.
References input_, and pos_.
Referenced by match(), match(), parse(), parseIdentifier(), parseNumber(), and parsePrimary().
Member Data Documentation
input_
template<typename real_t> std::string matheval::detail::SimpleMathParser< real_t >::input_ private
Definition at line 425 of file matheval.hpp.
Referenced by match(), match(), parse(), parseIdentifier(), parseNumber(), parsePrimary(), SimpleMathParser(), and skipWhitespace().
pos_
template<typename real_t> size_t matheval::detail::SimpleMathParser< real_t >::pos_ private
Definition at line 426 of file matheval.hpp.
Referenced by match(), match(), parse(), parseIdentifier(), parseNumber(), parsePrimary(), SimpleMathParser(), and skipWhitespace().
The documentation for this class was generated from the following file:
matheval.hpp