OPALX (Object Oriented Parallel Accelerator Library for Exascal): ValueRange< T > Class Template Reference
ValueRange< T > Class Template Reference
#include <ValueRange.h>
Public Member Functions
ValueRange ()
void enlargeIfOutside (T value)
bool isInside (T value) const
bool isOutside (T value) const
void print (Inform &out) const
Private Attributes
T minValue_m
T maxValue_m
Detailed Description
template<class T>
class ValueRange< T >
Definition at line 29 of file ValueRange.h.
Constructor & Destructor Documentation
ValueRange()
template<class T > ValueRange< T >::ValueRange () inline
Definition at line 31 of file ValueRange.h.
Member Function Documentation
enlargeIfOutside()
template<class T > void ValueRange< T >::enlargeIfOutside (T value) inline
Definition at line 36 of file ValueRange.h.
References ValueRange< T >::maxValue_m, and ValueRange< T >::minValue_m.
Referenced by OrbitThreader::execute(), StepSizeConfig::getPathLengthRange(), OrbitThreader::OrbitThreader(), and OrbitThreader::trackBack().
isInside()
template<class T > bool ValueRange< T >::isInside (T value) const inline
Definition at line 41 of file ValueRange.h.
References ValueRange< T >::maxValue_m, and ValueRange< T >::minValue_m.
Referenced by OrbitThreader::execute(), and ValueRange< T >::isOutside().
isOutside()
template<class T > bool ValueRange< T >::isOutside (T value) const inline
Definition at line 46 of file ValueRange.h.
References ValueRange< T >::isInside().
Referenced by OrbitThreader::execute(), and OrbitThreader::integrate().
print()
template<class T > void ValueRange< T >::print (Inform & out) const inline
Definition at line 51 of file ValueRange.h.
References ValueRange< T >::maxValue_m, and ValueRange< T >::minValue_m.
Referenced by operator<<().
Member Data Documentation
maxValue_m
template<class T > T ValueRange< T >::maxValue_m private
Definition at line 57 of file ValueRange.h.
Referenced by ValueRange< T >::enlargeIfOutside(), ValueRange< T >::isInside(), and ValueRange< T >::print().
minValue_m
template<class T > T ValueRange< T >::minValue_m private
Definition at line 56 of file ValueRange.h.
Referenced by ValueRange< T >::enlargeIfOutside(), ValueRange< T >::isInside(), and ValueRange< T >::print().
The documentation for this class was generated from the following file:
ValueRange.h