OPALX (Object Oriented Parallel Accelerator Library for Exascal): Replacer Class Reference
Replacer Class Reference
Replace all references to named element by a new version.
#include <Replacer.h>
Public Member Functions
Replacer (const Beamline &, const std::string &name, ElementBase *elm)
Constructor.
virtual ~Replacer ()
virtual void visitFlaggedElmPtr (const FlaggedElmPtr &)
Apply the visitor to an FlaggedElmPtr.
void execute () override
Apply the algorithm to the top-level beamline.
void visitComponent (const Component &) override
Apply the algorithm to an arbitrary component.
void visitBeamline (const Beamline &) override
Apply the algorithm to a beam line.
void visitConstantEFieldCavity (const ConstantEFieldCavity &) override
Apply the algorithm to a constant E-field cavity element.
void visitDrift (const Drift &) override
Apply the algorithm to a drift space.
void visitLaser (const Laser &) override
Apply the algorithm to a laser.
void visitMarker (const Marker &) override
Apply the algorithm to a marker.
void visitMonitor (const Monitor &) override
Apply the algorithm to a beam position monitor.
void visitMultipole (const Multipole &) override
Apply the algorithm to a multipole.
void visitMultipoleT (const MultipoleT &) override
Apply the algorithm to an arbitrary multipole.
void visitRBend (const RBend &) override
Apply the algorithm to a rectangular bend.
void visitRing (const Ring &) override
Apply the algorithm to a Ring.
void visitSBend (const SBend &) override
Apply the algorithm to a sector bend.
void visitRFCavity (const RFCavity &) override
Apply the algorithm to a RF cavity.
void visitSolenoid (const Solenoid &) override
Apply the algorithm to a Solenoid.
void visitTravelingWave (const TravelingWave &) override
Apply the algorithm to a traveling wave.
void visitScalingFFAMagnet (const ScalingFFAMagnet &spiral) override
Apply the algorithm to a scaling FFA magnet.
void visitVerticalFFAMagnet (const VerticalFFAMagnet &) override
Apply the algorithm to a vertical FFA magnet.
void visitVariableRFCavity (const VariableRFCavity &) override
Apply the algorithm to a variable RF cavity.
void visitProbe (const Probe &prob) override
Apply the algorithm to a Probe.
Protected Attributes
const Beamline & itsLine
bool back_beam
bool back_track
bool back_path
double flip_B
double flip_s
Private Member Functions
Replacer ()
Replacer (const Replacer &)
void operator= (const Replacer &)
virtual void applyDefault (const ElementBase &)
Private Attributes
const std::string itsName
ElementBase * newBase
bool local_flip
Detailed Description
Replace all references to named element by a new version.
Definition at line 31 of file Replacer.h.
Constructor & Destructor Documentation
Replacer() [1/3]
Replacer::Replacer (const Beamline & beamline, const std::string & name, ElementBase * elm)
Constructor.
Definition at line 31 of file Replacer.cpp.
~Replacer()
Replacer::~Replacer () virtual
Definition at line 34 of file Replacer.cpp.
Replacer() [2/3]
Replacer::Replacer () private
Replacer() [3/3]
Replacer::Replacer (const Replacer &) private
Member Function Documentation
applyDefault()
void DefaultVisitor::applyDefault (const ElementBase &) private virtual inherited
Definition at line 113 of file DefaultVisitor.cpp.
Referenced by DefaultVisitor::visitComponent(), DefaultVisitor::visitConstantEFieldCavity(), DefaultVisitor::visitDrift(), DefaultVisitor::visitLaser(), DefaultVisitor::visitMarker(), DefaultVisitor::visitMonitor(), DefaultVisitor::visitMultipole(), DefaultVisitor::visitMultipoleT(), DefaultVisitor::visitProbe(), DefaultVisitor::visitRBend(), DefaultVisitor::visitRFCavity(), DefaultVisitor::visitRing(), DefaultVisitor::visitSBend(), DefaultVisitor::visitScalingFFAMagnet(), DefaultVisitor::visitSolenoid(), DefaultVisitor::visitTravelingWave(), DefaultVisitor::visitVariableRFCavity(), and DefaultVisitor::visitVerticalFFAMagnet().
execute()
void DefaultVisitor::execute () override virtual inherited
Apply the algorithm to the top-level beamline.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker, RangeSelector, and Selector.
Definition at line 54 of file DefaultVisitor.cpp.
References ElementBase::accept(), DefaultVisitor::back_beam, DefaultVisitor::back_track, DefaultVisitor::itsLine, and DefaultVisitor::local_flip.
Referenced by RangeSelector::execute(), Line::replace(), Sequence::replace(), and Select::select().
operator=()
void Replacer::operator= (const Replacer &) private
visitBeamline()
void DefaultVisitor::visitBeamline (const Beamline & bl) override virtual inherited
Apply the algorithm to a beam line.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 97 of file DefaultVisitor.cpp.
References Beamline::iterate(), and DefaultVisitor::local_flip.
visitComponent()
void DefaultVisitor::visitComponent (const Component &) override virtual inherited
Apply the algorithm to an arbitrary component.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker, and Tracker.
Definition at line 59 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitConstantEFieldCavity()
void DefaultVisitor::visitConstantEFieldCavity (const ConstantEFieldCavity & cav) override virtual inherited
Apply the algorithm to a constant E-field cavity element.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 61 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitDrift()
void DefaultVisitor::visitDrift (const Drift & drf) override virtual inherited
Apply the algorithm to a drift space.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 65 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitFlaggedElmPtr()
void Replacer::visitFlaggedElmPtr (const FlaggedElmPtr & fep) virtual
Apply the visitor to an FlaggedElmPtr.
Reimplemented from DefaultVisitor.
Definition at line 36 of file Replacer.cpp.
References ElementBase::copyStructure(), ElmPtr::getElement(), ElementBase::getName(), itsName, newBase, and DefaultVisitor::visitFlaggedElmPtr().
visitLaser()
void DefaultVisitor::visitLaser (const Laser & laser) override virtual inherited
Apply the algorithm to a laser.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 67 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitMarker()
void DefaultVisitor::visitMarker (const Marker & mark) override virtual inherited
Apply the algorithm to a marker.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 69 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitMonitor()
void DefaultVisitor::visitMonitor (const Monitor & mon) override virtual inherited
Apply the algorithm to a beam position monitor.
Implements BeamlineVisitor.
Definition at line 71 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitMultipole()
void DefaultVisitor::visitMultipole (const Multipole & mult) override virtual inherited
Apply the algorithm to a multipole.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 73 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitMultipoleT()
void DefaultVisitor::visitMultipoleT (const MultipoleT & multT) override virtual inherited
Apply the algorithm to an arbitrary multipole.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 75 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitProbe()
void DefaultVisitor::visitProbe (const Probe & prob) override virtual inherited
Apply the algorithm to a Probe.
Implements BeamlineVisitor.
Definition at line 95 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitRBend()
void DefaultVisitor::visitRBend (const RBend & bend) override virtual inherited
Apply the algorithm to a rectangular bend.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 77 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitRFCavity()
void DefaultVisitor::visitRFCavity (const RFCavity & cav) override virtual inherited
Apply the algorithm to a RF cavity.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 81 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitRing()
void DefaultVisitor::visitRing (const Ring & ring) override virtual inherited
Apply the algorithm to a Ring.
Implements BeamlineVisitor.
Definition at line 79 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitSBend()
void DefaultVisitor::visitSBend (const SBend & bend) override virtual inherited
Apply the algorithm to a sector bend.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 83 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitScalingFFAMagnet()
void DefaultVisitor::visitScalingFFAMagnet (const ScalingFFAMagnet & spiral) override virtual inherited
Apply the algorithm to a scaling FFA magnet.
Implements BeamlineVisitor.
Definition at line 89 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitSolenoid()
void DefaultVisitor::visitSolenoid (const Solenoid & so) override virtual inherited
Apply the algorithm to a Solenoid.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 85 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitTravelingWave()
void DefaultVisitor::visitTravelingWave (const TravelingWave & trw) override virtual inherited
Apply the algorithm to a traveling wave.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 87 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitVariableRFCavity()
void DefaultVisitor::visitVariableRFCavity (const VariableRFCavity & cavity) override virtual inherited
Apply the algorithm to a variable RF cavity.
Implements BeamlineVisitor.
Definition at line 93 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitVerticalFFAMagnet()
void DefaultVisitor::visitVerticalFFAMagnet (const VerticalFFAMagnet & mag) override virtual inherited
Apply the algorithm to a vertical FFA magnet.
Implements BeamlineVisitor.
Definition at line 91 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
Member Data Documentation
back_beam
bool DefaultVisitor::back_beam protected inherited
Definition at line 110 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor(), DefaultVisitor::execute(), and Tracker::visitComponent().
back_path
bool DefaultVisitor::back_path protected inherited
Definition at line 112 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor().
back_track
bool DefaultVisitor::back_track protected inherited
Definition at line 111 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor(), DefaultVisitor::execute(), and Tracker::visitComponent().
flip_B
double DefaultVisitor::flip_B protected inherited
Definition at line 115 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor().
flip_s
double DefaultVisitor::flip_s protected inherited
Definition at line 116 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor().
itsLine
const Beamline& DefaultVisitor::itsLine protected inherited
Definition at line 107 of file DefaultVisitor.h.
Referenced by DefaultVisitor::execute().
itsName
const std::string Replacer::itsName private
Definition at line 49 of file Replacer.h.
Referenced by visitFlaggedElmPtr().
local_flip
bool DefaultVisitor::local_flip private inherited
Definition at line 130 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor(), DefaultVisitor::execute(), DefaultVisitor::visitBeamline(), and DefaultVisitor::visitFlaggedElmPtr().
newBase
ElementBase* Replacer::newBase private
Definition at line 52 of file Replacer.h.
Referenced by visitFlaggedElmPtr().
The documentation for this class was generated from the following files:
Replacer.h
Replacer.cpp