OPALX (Object Oriented Parallel Accelerator Library for Exascal): DummyGeometry Class Reference
DummyGeometry Class Reference
Public Member Functions
double getArcLength () const override
Get arc length.
double getElementLength () const override
Get geometry length.
void setElementLength (double length) override
Set geometry length.
Euclid3D getTransform (double, double) const override
Get transform.
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
Private Attributes
double length_m = 0.0
Detailed Description
Definition at line 118 of file TestRFCavity.cpp.
Member Function Documentation
getArcLength()
double DummyGeometry::getArcLength () const inline override virtual
Get arc length.
Implements BGeometryBase.
Definition at line 120 of file TestRFCavity.cpp.
getElementLength()
double DummyGeometry::getElementLength () const inline override virtual
Get geometry length.
Implements BGeometryBase.
Definition at line 121 of file TestRFCavity.cpp.
References length_m.
getEntrance()
double BGeometryBase::getEntrance () const virtual inherited
Get entrance position.
Reimplemented in PlanarArcGeometry, StraightGeometry, and BeamlineGeometry.
Definition at line 33 of file Geometry.cpp.
References BGeometryBase::getOrigin().
Referenced by ElementBase::getEntrance(), BGeometryBase::getEntranceFrame(), and BGeometryBase::getTotalTransform().
getEntranceFrame()
Euclid3D BGeometryBase::getEntranceFrame () const virtual inherited
Get transform.
Reimplemented in PlanarArcGeometry, RBendGeometry, StraightGeometry, and BeamlineGeometry.
Definition at line 41 of file Geometry.cpp.
References BGeometryBase::getEntrance(), and BGeometryBase::getTransform().
Referenced by ElementBase::getEntranceFrame().
getEntrancePatch()
Euclid3D BGeometryBase::getEntrancePatch () const virtual inherited
Get patch.
Reimplemented in RBendGeometry.
Definition at line 45 of file Geometry.cpp.
References Euclid3D::identity().
Referenced by ElementBase::getEntrancePatch().
getExit()
double BGeometryBase::getExit () const virtual inherited
Get exit position.
Reimplemented in PlanarArcGeometry, StraightGeometry, and BeamlineGeometry.
Definition at line 35 of file Geometry.cpp.
References BGeometryBase::getArcLength(), and BGeometryBase::getOrigin().
Referenced by ElementBase::getExit(), BGeometryBase::getExitFrame(), and BGeometryBase::getTotalTransform().
getExitFrame()
Euclid3D BGeometryBase::getExitFrame () const virtual inherited
Get transform.
Reimplemented in PlanarArcGeometry, RBendGeometry, StraightGeometry, and BeamlineGeometry.
Definition at line 43 of file Geometry.cpp.
References BGeometryBase::getExit(), and BGeometryBase::getTransform().
Referenced by ElementBase::getExitFrame().
getExitPatch()
Euclid3D BGeometryBase::getExitPatch () const virtual inherited
Get patch.
Reimplemented in RBendGeometry.
Definition at line 47 of file Geometry.cpp.
References Euclid3D::identity().
Referenced by ElementBase::getExitPatch().
getOrigin()
double BGeometryBase::getOrigin () const virtual inherited
Get origin position.
Reimplemented in NullGeometry, PlanarArcGeometry, StraightGeometry, and BeamlineGeometry.
Definition at line 31 of file Geometry.cpp.
References BGeometryBase::getArcLength().
Referenced by BGeometryBase::getEntrance(), BGeometryBase::getExit(), and ElementBase::getOrigin().
getTotalTransform()
Euclid3D BGeometryBase::getTotalTransform () const virtual inherited
Get transform.
Reimplemented in Euclid3DGeometry, PlanarArcGeometry, RBendGeometry, StraightGeometry, and BeamlineGeometry.
Definition at line 37 of file Geometry.cpp.
References BGeometryBase::getEntrance(), BGeometryBase::getExit(), and BGeometryBase::getTransform().
Referenced by Ring::appendElement(), and ElementBase::getTotalTransform().
getTransform() [1/2]
Euclid3D BGeometryBase::getTransform (double s) const virtual inherited
Get transform.
Reimplemented in Euclid3DGeometry, NullGeometry, PlanarArcGeometry, StraightGeometry, and BeamlineGeometry.
Definition at line 39 of file Geometry.cpp.
References BGeometryBase::getTransform().
getTransform() [2/2]
Euclid3D DummyGeometry::getTransform (double fromS, double toS) const inline override virtual
Get transform.
Implements BGeometryBase.
Definition at line 124 of file TestRFCavity.cpp.
setElementLength()
void DummyGeometry::setElementLength (double length) inline override virtual
Set geometry length.
Reimplemented from BGeometryBase.
Definition at line 122 of file TestRFCavity.cpp.
References length_m.
Member Data Documentation
length_m
double DummyGeometry::length_m = 0.0 private
Definition at line 127 of file TestRFCavity.cpp.
Referenced by getElementLength(), and setElementLength().
The documentation for this class was generated from the following file:
TestRFCavity.cpp