OPALX (Object Oriented Parallel Accelerator Library for Exascal): interpolation::MVector< Tmplt > Class Template Reference
interpolation::MVector< Tmplt > Class Template Reference
#include <MVector.h>
Public Member Functions
MVector ()
MVector (const MVector< Tmplt > &mv)
MVector (const Tmplt *ta_beg, const Tmplt *ta_end)
MVector (std::vector< Tmplt > tv)
MVector (size_t i)
MVector (size_t i, Tmplt value)
template<class Tmplt2>
MVector (MVector< Tmplt2 >)
~MVector ()
size_t num_row () const
Tmplt & operator() (size_t i)
const Tmplt & operator() (size_t i) const
MVector< Tmplt > sub (size_t n1, size_t n2) const
MMatrix< Tmplt > T () const
MVector< Tmplt > & operator= (const MVector< Tmplt > &mv)
const double & operator() (const size_t i) const
const m_complex & operator() (const size_t i) const
double & operator() (const size_t i)
m_complex & operator() (const size_t i)
MVector< double > & operator= (const MVector< double > &mv)
MVector< m_complex > & operator= (const MVector< m_complex > &mv)
Private Member Functions
void build_vector (size_t size)
void build_vector (const Tmplt *data_start, const Tmplt *data_end)
void delete_vector ()
void build_vector (size_t size)
void build_vector (size_t size)
void delete_vector ()
void delete_vector ()
Static Private Member Functions
static gsl_vector * get_vector (const MVector< double > &m)
static gsl_vector_complex * get_vector (const MVector< m_complex > &m)
Private Attributes
void * _vector
Friends
class MMatrix< Tmplt >
class MMatrix< double >
MVector< m_complex > & operator*= (MVector< m_complex > &v, m_complex c)
MVector< double > & operator*= (MVector< double > &v, double d)
MVector< m_complex > & operator+= (MVector< m_complex > &v1, MVector< m_complex > v2)
MVector< double > & operator+= (MVector< double > &v1, MVector< double > v2)
MVector< m_complex > operator* (MMatrix< m_complex > m, MVector< m_complex > v)
MVector< double > operator* (MMatrix< double > m, MVector< double > v)
Detailed Description
template<class Tmplt>
class interpolation::MVector< Tmplt >
Definition at line 156 of file MVector.h.
Constructor & Destructor Documentation
MVector() [1/7]
template<class Tmplt> interpolation::MVector< Tmplt >::MVector () inline
Definition at line 158 of file MVector.h.
References _vector.
Referenced by delete_vector(), get_vector(), get_vector(), MMatrix< double >, MVector(), MVector(), operator()(), operator*=, operator*=, operator+=, operator+=, operator=(), operator=(), operator=(), and sub().
MVector() [2/7]
template<typename Tmplt> interpolation::MVector< Tmplt >::MVector (const MVector< Tmplt > & mv)
Definition at line 72 of file MVector.cpp.
References _vector, and MVector().
MVector() [3/7]
template<class Tmplt> interpolation::MVector< Tmplt >::MVector (const Tmplt * ta_beg, const Tmplt * ta_end) inline
Definition at line 160 of file MVector.h.
References _vector, and build_vector().
MVector() [4/7]
template<class Tmplt> interpolation::MVector< Tmplt >::MVector (std::vector< Tmplt > tv) inline
Definition at line 163 of file MVector.h.
References _vector, and build_vector().
MVector() [5/7]
template<typename Tmplt> interpolation::MVector< Tmplt >::MVector (size_t i)
Definition at line 67 of file MVector.cpp.
References _vector, and build_vector().
MVector() [6/7]
template<typename Tmplt> interpolation::MVector< Tmplt >::MVector (size_t i, Tmplt value)
Definition at line 77 of file MVector.cpp.
References _vector, and build_vector().
MVector() [7/7]
template<class Tmplt> template<class Tmplt2> interpolation::MVector< Tmplt >::MVector (MVector< Tmplt2 >)
References MVector().
~MVector()
template<class Tmplt> interpolation::MVector< Tmplt >::~MVector () inline
Definition at line 262 of file MVector.h.
References delete_vector().
Member Function Documentation
build_vector() [1/4]
template<class Tmplt> void interpolation::MVector< Tmplt >::build_vector (const Tmplt * data_start, const Tmplt * data_end) private
Definition at line 96 of file MVector.cpp.
References build_vector(), and num_row().
build_vector() [2/4]
void interpolation::MVector< double >::build_vector (size_t size) private
Definition at line 84 of file MVector.cpp.
References _vector, gsl_vector_alloc(), and gsl_vector_free().
build_vector() [3/4]
void interpolation::MVector< m_complex >::build_vector (size_t size) private
Definition at line 90 of file MVector.cpp.
References _vector, gsl_vector_complex_alloc(), and gsl_vector_complex_free().
build_vector() [4/4]
template<class Tmplt> void interpolation::MVector< Tmplt >::build_vector (size_t size) private
Referenced by build_vector(), MVector(), MVector(), MVector(), and MVector().
delete_vector() [1/3]
template<class Tmplt> void interpolation::MVector< Tmplt >::delete_vector () private
References MVector().
Referenced by operator=(), operator=(), and ~MVector().
delete_vector() [2/3]
void interpolation::MVector< double >::delete_vector () inline private
Definition at line 266 of file MVector.h.
References _vector, and gsl_vector_free().
delete_vector() [3/3]
void interpolation::MVector< m_complex >::delete_vector () inline private
Definition at line 270 of file MVector.h.
References _vector, and gsl_vector_complex_free().
get_vector() [1/2]
template<class Tmplt> gsl_vector inline * interpolation::MVector< Tmplt >::get_vector (const MVector< double > & m) static private
Definition at line 336 of file MVector.h.
References _vector, and MVector().
Referenced by interpolation::MMatrix< Tmplt >::eigenvalues(), and interpolation::MMatrix< Tmplt >::eigenvectors().
get_vector() [2/2]
template<class Tmplt> gsl_vector_complex inline * interpolation::MVector< Tmplt >::get_vector (const MVector< m_complex > & m) static private
Definition at line 344 of file MVector.h.
References _vector, and MVector().
num_row()
template<class Tmplt> template size_t interpolation::MVector< Tmplt >::num_row () const
Definition at line 103 of file MVector.cpp.
References _vector.
Referenced by build_vector(), interpolation::complex(), interpolation::complex(), interpolation::operator-(), interpolation::operator<<(), operator=(), operator=(), interpolation::operator==(), interpolation::operator>>(), and T().
operator()() [1/6]
double & interpolation::MVector< double >::operator() (const size_t i)
Definition at line 121 of file MVector.cpp.
References _vector, and gsl_vector_ptr().
operator()() [2/6]
m_complex & interpolation::MVector< m_complex >::operator() (const size_t i)
Definition at line 125 of file MVector.cpp.
References _vector, and gsl_vector_complex_ptr().
operator()() [3/6]
const double & interpolation::MVector< double >::operator() (const size_t i) const
Definition at line 113 of file MVector.cpp.
References _vector, and gsl_vector_ptr().
operator()() [4/6]
const m_complex & interpolation::MVector< m_complex >::operator() (const size_t i) const
Definition at line 117 of file MVector.cpp.
References _vector, and gsl_vector_complex_ptr().
operator()() [5/6]
template<class Tmplt> Tmplt & interpolation::MVector< Tmplt >::operator() (size_t i)
Referenced by sub(), and T().
operator()() [6/6]
template<class Tmplt> const Tmplt & interpolation::MVector< Tmplt >::operator() (size_t i) const
References MVector().
operator=() [1/3]
MVector< double > & interpolation::MVector< double >::operator= (const MVector< double > & mv)
Definition at line 150 of file MVector.cpp.
References _vector, delete_vector(), gsl_vector_alloc(), gsl_vector_memcpy(), MVector(), and num_row().
operator=() [2/3]
MVector< m_complex > & interpolation::MVector< m_complex >::operator= (const MVector< m_complex > & mv)
Definition at line 163 of file MVector.cpp.
References _vector, delete_vector(), gsl_vector_complex_alloc(), gsl_vector_complex_memcpy(), MVector(), and num_row().
operator=() [3/3]
template<class Tmplt> MVector< Tmplt > & interpolation::MVector< Tmplt >::operator= (const MVector< Tmplt > & mv)
References MVector().
sub()
template<class Tmplt> MVector< Tmplt > interpolation::MVector< Tmplt >::sub (size_t n1, size_t n2) const
Definition at line 195 of file MVector.cpp.
References MVector(), and operator()().
T()
template<class Tmplt> template MMatrix< m_complex > interpolation::MVector< Tmplt >::T () const
Definition at line 130 of file MVector.cpp.
References num_row(), and operator()().
Friends And Related Symbol Documentation
MMatrix< double >
template<class Tmplt> friend class MMatrix< double > friend
Definition at line 189 of file MVector.h.
References MVector().
MMatrix< Tmplt >
template<class Tmplt> friend class MMatrix< Tmplt > friend
Definition at line 189 of file MVector.h.
operator* [1/2]
template<class Tmplt> MVector< double > operator* (MMatrix< double > m, MVector< double > v) friend
Definition at line 293 of file MMatrix.h.
operator* [2/2]
template<class Tmplt> MVector< m_complex > operator* (MMatrix< m_complex > m, MVector< m_complex > v) friend
Definition at line 284 of file MMatrix.h.
operator*= [1/2]
template<class Tmplt> MVector< double > & operator*= (MVector< double > & v, double d) friend
Definition at line 278 of file MVector.h.
References _vector, gsl_vector_scale(), and MVector().
operator*= [2/2]
template<class Tmplt> MVector< m_complex > & operator*= (MVector< m_complex > & v, m_complex c) friend
Definition at line 274 of file MVector.h.
References _vector, gsl_vector_complex_scale(), and MVector().
operator+= [1/2]
template<class Tmplt> MVector< double > & operator+= (MVector< double > & v1, MVector< double > v2) friend
Definition at line 305 of file MVector.h.
References _vector, gsl_vector_add(), and MVector().
operator+= [2/2]
template<class Tmplt> MVector< m_complex > & operator+= (MVector< m_complex > & v1, MVector< m_complex > v2) friend
Definition at line 301 of file MVector.h.
References _vector, gsl_vector_complex_add(), and MVector().
Member Data Documentation
_vector
template<class Tmplt> void* interpolation::MVector< Tmplt >::_vector private
Definition at line 205 of file MVector.h.
Referenced by build_vector(), delete_vector(), get_vector(), get_vector(), MVector(), MVector(), MVector(), MVector(), MVector(), MVector(), num_row(), operator()(), operator()(), interpolation::MMatrix< Tmplt >::operator*, interpolation::MMatrix< Tmplt >::operator*, operator*=, operator*=, operator+=, operator+=, operator=(), and operator=().
The documentation for this class was generated from the following files:
MVector.h
MVector.cpp