OPALX (Object Oriented Parallel Accelerator Library for Exascal): Port Class Reference
Port Class Reference
Named local frame attached to an element body.
#include <Port.h>
Public Member Functions
Port ()=default
Port (const std::string &name, const CoordinateSystemTrafo &bodyToPort)
const std::string & getName () const
const CoordinateSystemTrafo & getBodyToPort () const
Private Attributes
std::string name_m
CoordinateSystemTrafo bodyToPort_m
Detailed Description
Named local frame attached to an element body.
A port stores the rigid transform from the canonical body frame of an element to a named interface frame such as entry, body, or exit.
Definition at line 15 of file Port.h.
Constructor & Destructor Documentation
Port() [1/2]
Port::Port () default
Port() [2/2]
Port::Port (const std::string & name, const CoordinateSystemTrafo & bodyToPort) inline
Definition at line 18 of file Port.h.
Member Function Documentation
getBodyToPort()
const CoordinateSystemTrafo & Port::getBodyToPort () const inline
Definition at line 22 of file Port.h.
References bodyToPort_m.
Referenced by PlacedElement::getBodyTransform(), PlacedElement::getEntryTransform(), PlacedElement::getExitTransform(), PlacedElement::getNominalBodyPortTransform(), PlacedElement::getNominalEntryTransform(), PlacedElement::getNominalExitTransform(), TEST_F(), and TEST_F().
getName()
const std::string & Port::getName () const inline
Definition at line 21 of file Port.h.
References name_m.
Referenced by TEST_F(), TEST_F(), and TEST_F().
Member Data Documentation
bodyToPort_m
CoordinateSystemTrafo Port::bodyToPort_m private
Definition at line 26 of file Port.h.
Referenced by getBodyToPort().
name_m
std::string Port::name_m private
Definition at line 25 of file Port.h.
Referenced by getName().
The documentation for this class was generated from the following file:
Port.h