OPALX (Object Oriented Parallel Accelerator Library for Exascal): Attributes::Bool Class Reference
Attributes::Bool Class Reference
Parser for attribute of type logical.
#include <Bool.h>
Public Types
enum OwnerType {
ELEMENT , COMMAND , SUB_COMMAND , STATEMENT ,
NONE
}
Public Member Functions
Bool (const std::string &name, const std::string &help)
Constructor.
virtual ~Bool ()
virtual const std::string & getType () const
Return attribute type string `‘logical’'.
virtual void parse (Attribute &, Statement &, bool) const
Parse the attribute.
virtual AttributeBase * getDefault () const
Return default value.
virtual const std::string & getHelp () const
Return help string.
virtual const std::string & getName () const
Return attribute name.
virtual void parseComponent (Attribute &a, Statement &s, bool eval, int i) const
Parse component value.
bool isDeferred () const
Return defer flag.
void setDeferred (bool)
Set or reset defer flag.
bool isReadOnly () const
Return read-only flag.
void setReadOnly (bool)
Set or reset read-only flag.
void setPredefinedValues (const std::set< std::string > &, const std::string &)
Add predefined strings values to the help.
Static Public Member Functions
static std::multimap< OwnerType, std::string > getOwner (const std::string &att)
static void addAttributeOwner (const std::string &owner, const OwnerType &type, const std::string &name)
Protected Attributes
const std::string itsName
Attribute name.
const std::string itsHelp
Help text.
std::shared_ptr< AttributeBase > itsDefault
Default value.
bool is_deferred
Defer flag.
bool is_readonly
Read-only flag.
Private Member Functions
Bool ()
Bool (const Bool &)
void operator= (const Bool &)
Static Private Attributes
static std::multimap< std::string, std::pair< OwnerType, std::string > > attributeOwnerDictionary_s
Detailed Description
Parser for attribute of type logical.
Definition at line 30 of file Bool.h.
Member Enumeration Documentation
OwnerType
enum AttributeHandler::OwnerType inherited
Enumerator
ELEMENT
COMMAND
SUB_COMMAND
STATEMENT
NONE
Definition at line 109 of file AttributeHandler.h.
Constructor & Destructor Documentation
Bool() [1/3]
Attributes::Bool::Bool (const std::string & name, const std::string & help)
Constructor.
Definition at line 38 of file Bool.cpp.
~Bool()
Attributes::Bool::~Bool () virtual
Definition at line 41 of file Bool.cpp.
Bool() [2/3]
Attributes::Bool::Bool () private
Bool() [3/3]
Attributes::Bool::Bool (const Bool &) private
Member Function Documentation
addAttributeOwner()
void AttributeHandler::addAttributeOwner (const std::string & owner, const OwnerType & type, const std::string & name) static inherited
Definition at line 101 of file AttributeHandler.cpp.
References AttributeHandler::attributeOwnerDictionary_s.
Referenced by OpalElement::OpalElement(), OpalElement::registerOwnership(), Object::registerOwnership(), and TrackCmd::TrackCmd().
getDefault()
AttributeBase * AttributeHandler::getDefault () const virtual inherited
Return default value.
Definition at line 40 of file AttributeHandler.cpp.
References AttributeHandler::itsDefault, and AttributeHandler::itsName.
getHelp()
const std::string & AttributeHandler::getHelp () const virtual inherited
Return help string.
Definition at line 50 of file AttributeHandler.cpp.
References AttributeHandler::itsHelp.
Referenced by Attribute::getHelp().
getName()
const std::string & AttributeHandler::getName () const virtual inherited
Return attribute name.
Definition at line 52 of file AttributeHandler.cpp.
References AttributeHandler::itsName.
getOwner()
std::multimap< AttributeHandler::OwnerType, std::string > AttributeHandler::getOwner (const std::string & att) static inherited
Definition at line 84 of file AttributeHandler.cpp.
References AttributeHandler::attributeOwnerDictionary_s.
Referenced by OpalParser::getHint().
getType()
const std::string & Attributes::Bool::getType () const virtual
Return attribute type string `‘logical’'.
Implements AttributeHandler.
Definition at line 43 of file Bool.cpp.
isDeferred()
bool AttributeHandler::isDeferred () const inherited
Return defer flag.
Definition at line 61 of file AttributeHandler.cpp.
References AttributeHandler::is_deferred.
Referenced by Attributes::Real::parse().
isReadOnly()
bool AttributeHandler::isReadOnly () const inherited
Return read-only flag.
Definition at line 65 of file AttributeHandler.cpp.
References AttributeHandler::is_readonly.
operator=()
void Attributes::Bool::operator= (const Bool &) private
parse()
void Attributes::Bool::parse (Attribute & attr, Statement & stat, bool eval) const virtual
Parse the attribute.
Implements AttributeHandler.
Definition at line 48 of file Bool.cpp.
References AttributeHandler::is_deferred, Expressions::parseBool(), and Attribute::set().
parseComponent()
void AttributeHandler::parseComponent (Attribute & a, Statement & s, bool eval, int i) const virtual inherited
Parse component value.
Reimplemented in Attributes::BoolArray, Attributes::RealArray, Attributes::StringArray, Attributes::TokenListArray, and Attributes::UpperCaseStringArray.
Definition at line 54 of file AttributeHandler.cpp.
References AttributeHandler::itsName.
setDeferred()
void AttributeHandler::setDeferred (bool flag) inherited
Set or reset defer flag.
Definition at line 63 of file AttributeHandler.cpp.
References AttributeHandler::is_deferred.
setPredefinedValues()
void AttributeHandler::setPredefinedValues (const std::set< std::string > & predefinedValues, const std::string & defaultValue) inherited
Add predefined strings values to the help.
Definition at line 69 of file AttributeHandler.cpp.
References AttributeHandler::itsHelp.
Referenced by Attributes::PredefinedString::PredefinedString().
setReadOnly()
void AttributeHandler::setReadOnly (bool flag) inherited
Set or reset read-only flag.
Definition at line 67 of file AttributeHandler.cpp.
References AttributeHandler::is_readonly.
Member Data Documentation
attributeOwnerDictionary_s
std::multimap< std::string, std::pair< AttributeHandler::OwnerType, std::string > > AttributeHandler::attributeOwnerDictionary_s static private inherited
Definition at line 138 of file AttributeHandler.h.
Referenced by AttributeHandler::addAttributeOwner(), and AttributeHandler::getOwner().
is_deferred
bool AttributeHandler::is_deferred protected inherited
Defer flag.
Definition at line 126 of file AttributeHandler.h.
Referenced by AttributeHandler::isDeferred(), parse(), Attributes::BoolArray::parse(), Attributes::RealArray::parse(), and AttributeHandler::setDeferred().
is_readonly
bool AttributeHandler::is_readonly protected inherited
Read-only flag.
Definition at line 129 of file AttributeHandler.h.
Referenced by AttributeHandler::isReadOnly(), and AttributeHandler::setReadOnly().
itsDefault
std::shared_ptr<AttributeBase> AttributeHandler::itsDefault protected inherited
Default value.
Definition at line 123 of file AttributeHandler.h.
Referenced by AttributeHandler::getDefault().
itsHelp
const std::string AttributeHandler::itsHelp protected inherited
Help text.
Definition at line 120 of file AttributeHandler.h.
Referenced by AttributeHandler::getHelp(), and AttributeHandler::setPredefinedValues().
itsName
const std::string AttributeHandler::itsName protected inherited
Attribute name.
Definition at line 117 of file AttributeHandler.h.
Referenced by AttributeHandler::getDefault(), AttributeHandler::getName(), and AttributeHandler::parseComponent().
The documentation for this class was generated from the following files:
Bool.h
Bool.cpp