OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestVariableRFCavity Class Reference
TestVariableRFCavity Class Reference
Classes
class TestableFieldSolverCmd
Public Member Functions
TestVariableRFCavity ()
void execute () override
Execute the algorithm on the attached beam line.
void visitBeamline (const Beamline &) override
Apply the algorithm to a beam line.
void visitComponent (const Component &) override
Apply the algorithm to an arbitrary component.
void visitConstantEFieldCavity (const ConstantEFieldCavity &) override
Apply the algorithm to a constant E-field cavity element.
void visitDrift (const Drift &) override
Apply the algorithm to a drift space.
void visitFlaggedElmPtr (const FlaggedElmPtr &) override
Apply the algorithm to a FlaggedElmPtr.
void visitLaser (const Laser &) override
Apply the algorithm to a laser element.
void visitMarker (const Marker &) override
Apply the algorithm to a marker.
void visitMonitor (const Monitor &) override
Apply the algorithm to a beam position monitor.
void visitMultipole (const Multipole &) override
Apply the algorithm to a multipole.
void visitMultipoleT (const MultipoleT &) override
Apply the algorithm to an arbitrary multipole.
void visitRBend (const RBend &) override
Apply the algorithm to a rectangular bend.
void visitRFCavity (const RFCavity &) override
Apply the algorithm to a RF cavity.
void visitScalingFFAMagnet (const ScalingFFAMagnet &) override
void visitRing (const Ring &) override
Apply the algorithm to a Ring element.
void visitSBend (const SBend &) override
Apply the algorithm to a sector bend.
void visitSolenoid (const Solenoid &) override
Apply the algorithm to a Solenoid element.
void visitTravelingWave (const TravelingWave &) override
Apply the algorithm to a traveling wave.
void visitVerticalFFAMagnet (const VerticalFFAMagnet &) override
Apply the algorithm to a vertical FFA magnet.
void visitProbe (const Probe &) override
Apply the algorithm to a Probe.
void visitVariableRFCavity (const VariableRFCavity &) override
Apply the algorithm to a variable RF cavity.
std::shared_ptr< PartBunch_t > makeBunch (const size_t numParticles)
void accept (BeamlineVisitor &) const override
ElementBase * clone () const override
bool apply (const std::shared_ptr< ParticleContainer_t > &pc) override
bool apply (const size_t &i, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
bool apply (const Vector_t< double, 3 > &R, const Vector_t< double, 3 > &P, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
bool applyToReferenceParticle (const Vector_t< double, 3 > &R, const Vector_t< double, 3 > &P, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
void initialise (PartBunch_t *bunch, double &startField, double &endField) override
void finalise () override
bool bends () const override
void getFieldExtend (double &zBegin, double &zEnd) const override
virtual double getAmplitude (const double time) const
virtual double getFrequency (const double time) const
virtual double getPhase (const double time) const
virtual double getHeight () const
virtual double getWidth () const
virtual double getLength () const
virtual void setHeight (const double fullHeight)
virtual void setWidth (const double fullWidth)
virtual void setLength (double length)
virtual std::shared_ptr< AbstractTimeDependence > getAmplitudeModel () const
virtual std::shared_ptr< AbstractTimeDependence > getPhaseModel () const
virtual std::shared_ptr< AbstractTimeDependence > getFrequencyModel () const
virtual void setAmplitudeModel (std::shared_ptr< AbstractTimeDependence > amplitude_td)
virtual void setPhaseModel (std::shared_ptr< AbstractTimeDependence > phase_td)
virtual void setFrequencyModel (std::shared_ptr< AbstractTimeDependence > frequency_td)
virtual void setAmplitudeName (const std::string &amplitude)
virtual void setPhaseName (const std::string &phase)
virtual void setFrequencyName (const std::string &frequency)
StraightGeometry & getGeometry () override
const StraightGeometry & getGeometry () const override
void initialiseTimeDependencies () const
EMField & getField () override
Not implemented.
const EMField & getField () const override
Not implemented.
EVector Efield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool getPotential (const Vector_t< double, 3 > &, const double &, Vector_t< double, 3 > &, double &)
Calculate the four-potential at some position relative to the component.
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual void goOnline (const double &kineticEnergy)
virtual void goOffline ()
virtual bool Online ()
virtual ElementType getType () const
Get element type std::string.
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunch_t &bunch, const PartData &, bool revBeam, bool revTrack) const
Track a borrowed particle bunch through a non-standard component.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
Return the nominal body extent of the element.
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
virtual Port getEntryPort () const
Return the entrance port of the canonical local chart.
virtual Port getBodyPort () const
Return the body port of the canonical local chart.
virtual Port getExitPort () const
Return the exit port of the canonical local chart.
PlacementPose getPlacementPose () const
Return the nominal rigid placement transform of the element.
void setPlacementPose (const PlacementPose &pose)
Set the nominal rigid placement transform of the element.
Misalignment getPlacementMisalignment () const
Return the local nominal-to-actual correction stored for the element.
ElementGeometry getPlacementGeometry () const
Return the bridge geometry ports assembled from legacy edge state.
SupportPlacement getPlacementSupport () const
Return the support-frame bridge object. The default is the body frame.
PlacedElement getPlacedElement () const
Return a placed-element view assembled from the current bridge objects.
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t< double, 3 > &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Static Public Member Functions
static void SetUpTestSuite ()
static void TearDownTestSuite ()
static void testGetSet (VariableRFCavity &cav1, std::shared_ptr< AbstractTimeDependence >(VariableRFCavity::*getMethod)() const, void(VariableRFCavity::*setMethod)(std::shared_ptr< AbstractTimeDependence >))
static void testNull (const VariableRFCavity &cav1)
static std::string getTypeString (ElementType type)
Public Attributes
std::shared_ptr< FieldSolverCmd > fsCmdBase_m
std::shared_ptr< DataSink > dataSink_m
Protected Member Functions
void initNull ()
bool isInsideTransverse (const Vector_t< double, 3 > &r) const
Static Protected Member Functions
static KOKKOS_INLINE_FUNCTION bool computeField (const Vector_t< double, 3 > &R, Vector_t< double, 3 > &E, double E0, double integralF, double phi, double halfWidth, double halfHeight, double length)
Protected Attributes
std::shared_ptr< AbstractTimeDependence > phaseTD_m
std::shared_ptr< AbstractTimeDependence > amplitudeTD_m
std::shared_ptr< AbstractTimeDependence > frequencyTD_m
std::string phaseName_m
std::string amplitudeName_m
std::string frequencyName_m
double halfWidth_m
double halfHeight_m
double length_m
StraightGeometry geometry
The cavity's geometry.
double exit_face_slope_m
PartBunch_t * RefPartBunch_m
bool online_m
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes
static const std::vector< double > defaultAperture_m = std::vector<double>({1e6, 1e6, 1.0})
Private Attributes
std::string elementID
AttributeSet userAttribs
WakeFunction * wake_m
BoundaryGeometry * bgeometry_m
ParticleMatterInteractionHandler * parmatint_m
bool positionIsFixed
std::queue< std::pair< double, double > > actionRange_m
std::string outputfn_m
bool deleteOnTransverseExit_m = true
double elementPosition_m
ELEMEDGE attribute.
bool elemedgeSet_m
Static Private Attributes
static const std::map< ElementType, std::string > elementTypeToString_s
Detailed Description
Definition at line 29 of file TestVariableRFCavity.cpp.
Constructor & Destructor Documentation
TestVariableRFCavity()
TestVariableRFCavity::TestVariableRFCavity () inline
Definition at line 31 of file TestVariableRFCavity.cpp.
References VariableRFCavity::VariableRFCavity().
Member Function Documentation
accept()
void VariableRFCavity::accept (BeamlineVisitor & visitor) const override virtual inherited
Apply visitor to RFCavity.
The RF cavity finds the "time dependence" models by doing a string lookup against a list held by AbstractTimeDependence at accept time.
Implements ElementBase.
Definition at line 171 of file VariableRFCavity.cpp.
References initialiseTimeDependencies(), and BeamlineVisitor::visitVariableRFCavity().
Referenced by TEST_F().
apply() [1/3]
bool VariableRFCavity::apply (const size_t & i, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual inherited
Calculate the field at the position of the i^th particle
Parameters
i indexes the particle whose field we need
t the time at which the field is calculated
E return value with electric field strength
B return value with magnetic field strength
Returns
True if particle is outside the boundaries; else False
Reimplemented from Component.
Definition at line 113 of file VariableRFCavity.cpp.
References amplitudeTD_m, computeField(), frequencyTD_m, ElementBase::getElementLength(), halfHeight_m, halfWidth_m, Units::MHz2Hz, Units::MVpm2Vpm, phaseTD_m, and Component::RefPartBunch_m.
apply() [2/3]
bool VariableRFCavity::apply (const std::shared_ptr< ParticleContainer_t > & pc) override virtual inherited
Calculate the field for all particles
Reimplemented from Component.
Definition at line 136 of file VariableRFCavity.cpp.
References amplitudeTD_m, computeField(), frequencyTD_m, ElementBase::getElementLength(), halfHeight_m, halfWidth_m, Units::MHz2Hz, Units::MVpm2Vpm, phaseTD_m, and Component::RefPartBunch_m.
Referenced by applyToReferenceParticle(), TEST_F(), and TEST_F().
apply() [3/3]
bool VariableRFCavity::apply (const Vector_t< double, 3 > & R, const Vector_t< double, 3 > & P, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual inherited
Calculate the field at a given position
Parameters
R the position at which the field is calculated
P the momentum (not used)
t the time at which the field is calculated
E return value; filled with electric field strength
B return value; filled with magnetic field strength
Returns
True if particle is outside the boundaries; else False
Reimplemented from Component.
Definition at line 127 of file VariableRFCavity.cpp.
References amplitudeTD_m, computeField(), frequencyTD_m, ElementBase::getElementLength(), halfHeight_m, halfWidth_m, Units::MHz2Hz, Units::MVpm2Vpm, and phaseTD_m.
applyToReferenceParticle()
bool VariableRFCavity::applyToReferenceParticle (const Vector_t< double, 3 > & R, const Vector_t< double, 3 > & P, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual inherited
Calculate the field at a given position. This is identical to "apply".
Parameters
R the position at which the field is calculated
P the momentum (not used)
t the time at which the field is calculated
E return value; filled with electric field strength
B return value; filled with magnetic field strength
Returns
True if particle is outside the boundaries; else False
Reimplemented from Component.
Definition at line 156 of file VariableRFCavity.cpp.
References apply().
bends()
bool VariableRFCavity::bends () const inline override virtual inherited
Returns
false (cavity does not bend the trajectory)
Implements Component.
Definition at line 121 of file VariableRFCavity.h.
Referenced by TEST_F().
Bfield() [1/2]
BVector Component::Bfield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 234 of file Component.h.
References EMField::Bfield(), and getField().
Bfield() [2/2]
BVector Component::Bfield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 240 of file Component.h.
References EMField::Bfield(), and getField().
clone()
ElementBase * VariableRFCavity::clone () const override virtual inherited
Inheritable deepcopy method
Implements ElementBase.
Definition at line 169 of file VariableRFCavity.cpp.
References ElementBase::ElementBase(), and VariableRFCavity().
Referenced by TEST_F().
computeField()
KOKKOS_INLINE_FUNCTION bool VariableRFCavity::computeField (const Vector_t< double, 3 > & R, Vector_t< double, 3 > & E, double E0, double integralF, double phi, double halfWidth, double halfHeight, double length) static protected inherited
Definition at line 241 of file VariableRFCavity.h.
References Physics::two_pi.
Referenced by apply(), apply(), and apply().
copyStructure()
ElementBase * ElementBase::copyStructure () virtual inherited
Make a structural copy.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 193 of file ElementBase.cpp.
References clone(), ElementBase(), and isSharable().
Referenced by Sequence::copy(), Line::parse(), and SequenceParser::parseMember().
EBfield() [1/2]
EBVectors Component::EBfield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 244 of file Component.h.
References EMField::EBfield(), and getField().
EBfield() [2/2]
EBVectors Component::EBfield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 246 of file Component.h.
References EMField::EBfield(), and getField().
Efield() [1/2]
EVector Component::Efield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 232 of file Component.h.
References EMField::Efield(), and getField().
Efield() [2/2]
EVector Component::Efield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 236 of file Component.h.
References EMField::Efield(), and getField().
execute()
void TestVariableRFCavity::execute () inline override virtual
Execute the algorithm on the attached beam line.
Implements BeamlineVisitor.
Definition at line 53 of file TestVariableRFCavity.cpp.
finalise()
void VariableRFCavity::finalise () override virtual inherited
Finalise following tracking
Just sets RefPartBunch_m to nullptr
Implements Component.
Definition at line 167 of file VariableRFCavity.cpp.
References Component::RefPartBunch_m.
fixPosition()
void ElementBase::fixPosition () inline inherited
Definition at line 596 of file ElementBase.h.
References positionIsFixed.
Referenced by OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
getAmplitude()
virtual double VariableRFCavity::getAmplitude (const double time) const inline virtual inherited
Get the amplitude at a given time
Parameters
time the time at which the amplitude is calculated
Returns
the RF field gradient.
Definition at line 140 of file VariableRFCavity.h.
References amplitudeTD_m.
Referenced by TEST_F().
getAmplitudeModel()
std::shared_ptr< AbstractTimeDependence > VariableRFCavity::getAmplitudeModel () const virtual inherited
Returns
shared_ptr to the amplitude (field gradient) time dependence
Definition at line 74 of file VariableRFCavity.cpp.
References amplitudeTD_m.
Referenced by TEST_F(), TEST_F(), and TestVariableRFCavity::testNull().
getAperture()
std::pair< ApertureType, std::vector< double > > ElementBase::getAperture () const inline inherited
Definition at line 581 of file ElementBase.h.
References aperture_m.
Referenced by MeshGenerator::add(), Solenoid::getSupportEnvelope(), and MeshGenerator::getTransverseSupport().
getArcLength()
double ElementBase::getArcLength () const inline virtual inherited
Get arc length.
Reimplemented in MarkerRep, TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 478 of file ElementBase.h.
References BGeometryBase::getArcLength(), and getGeometry().
Referenced by TBeamline< T >::getTransform().
getAttribute()
double ElementBase::getAttribute (const std::string & aKey) const virtual inherited
Get attribute value.
Definition at line 146 of file ElementBase.cpp.
References getConstChannel().
getBodyPort()
Port ElementBase::getBodyPort () const inline virtual inherited
Return the body port of the canonical local chart.
The body port \(p_{i,\mathrm{body}}\) is the identity port of the element's canonical local chart. Its rigid transform is therefore the identity element of \(SE(3)\) in the first redesign stage.
Definition at line 546 of file ElementBase.h.
Referenced by getPlacementGeometry(), and TEST_F().
getBoundaryGeometry()
BoundaryGeometry * ElementBase::getBoundaryGeometry () const inline virtual inherited
return the attached boundary geometrt object if there is any
Definition at line 512 of file ElementBase.h.
References bgeometry_m.
getBoundingBoxInLabCoords()
BoundingBox ElementBase::getBoundingBoxInLabCoords () const virtual inherited
Definition at line 263 of file ElementBase.cpp.
References csTrafoGlobal2Local_m, getEdgeToBegin(), and getEdgeToEnd().
getChannel()
Channel * ElementBase::getChannel (const std::string & aKey, bool create = false) virtual inherited
Construct a read/write channel.
Reimplemented in ConstantEFieldCavityRep, DriftRep, LaserRep, MonitorRep, MultipoleRep, ProbeRep, RBendRep, RFCavityRep, SBendRep, SolenoidRep, and TravelingWaveRep.
Definition at line 181 of file ElementBase.cpp.
References userAttribs.
Referenced by ConstantEFieldCavityRep::getChannel(), DriftRep::getChannel(), LaserRep::getChannel(), MonitorRep::getChannel(), MultipoleRep::getChannel(), ProbeRep::getChannel(), RBendRep::getChannel(), RFCavityRep::getChannel(), SBendRep::getChannel(), SolenoidRep::getChannel(), TravelingWaveRep::getChannel(), getConstChannel(), and setAttribute().
getConstChannel()
const ConstChannel * ElementBase::getConstChannel (const std::string & aKey) const virtual inherited
Construct a read-only channel.
Definition at line 185 of file ElementBase.cpp.
References ElementBase(), and getChannel().
Referenced by getAttribute(), and hasAttribute().
getCSTrafoGlobal2Local()
CoordinateSystemTrafo ElementBase::getCSTrafoGlobal2Local () const inline inherited
Definition at line 528 of file ElementBase.h.
References csTrafoGlobal2Local_m.
Referenced by getPlacementPose(), OpalRBend::update(), and OpalSBend::update().
getDesign()
const ElementBase & Component::getDesign () const virtual inherited
Return design element.
Definition at line 33 of file Component.cpp.
References ElementBase::ElementBase().
getDesignEnergy()
double Component::getDesignEnergy () const inline virtual inherited
Reimplemented in BendBase, and RFCavity.
Definition at line 254 of file Component.h.
getEdgeToBegin()
CoordinateSystemTrafo ElementBase::getEdgeToBegin () const inline virtual inherited
Reimplemented in BendBase, RFCavity, Solenoid, and TravelingWave.
Definition at line 532 of file ElementBase.h.
Referenced by getBoundingBoxInLabCoords(), getEntryPort(), and isInsideTransverse().
getEdgeToEnd()
CoordinateSystemTrafo ElementBase::getEdgeToEnd () const inline virtual inherited
Reimplemented in BendBase, RFCavity, Solenoid, and TravelingWave.
Definition at line 537 of file ElementBase.h.
References getElementLength().
Referenced by getBoundingBoxInLabCoords(), and getExitPort().
getElementDimensions()
virtual void ElementBase::getElementDimensions (double & begin, double & end) const inline virtual inherited
Return the nominal body extent of the element.
The first placement redesign stage distinguishes between the nominal body extent and the field-support extent. The body extent is the canonical longitudinal interval of the placed hardware, \([z_\mathrm{body}^{\mathrm{begin}}, z_\mathrm{body}^{\mathrm{end}}]\), and therefore drives ports, placement, and visualization. By default it coincides with the geometry length \([0, L]\) in the local chart.
Reimplemented in RFCavity, Solenoid, and TravelingWave.
Definition at line 177 of file ElementBase.h.
References getElementLength().
Referenced by MeshGenerator::add().
getElementLength()
double ElementBase::getElementLength () const inline virtual inherited
Get design length.
Reimplemented in MarkerRep, RFCavity, TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 480 of file ElementBase.h.
References BGeometryBase::getElementLength(), and getGeometry().
Referenced by MeshGenerator::add(), BendBase::apply(), Component::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Multipole::apply(), Multipole::apply(), Multipole::apply(), VariableRFCavity::apply(), VariableRFCavity::apply(), VariableRFCavity::apply(), Component::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), getEdgeToEnd(), Solenoid::getEdgeToEnd(), getElementDimensions(), Solenoid::getElementDimensions(), RFCavity::getElementLength(), BendBase::getFieldExtend(), ConstantEFieldCavity::getFieldExtend(), Corrector::getFieldExtend(), Drift::getFieldExtend(), Laser::getFieldExtend(), Multipole::getFieldExtend(), MultipoleT::getFieldExtend(), VariableRFCavity::getFieldExtend(), BendBase::getLength(), BendBase::initialise(), ConstantEFieldCavity::initialise(), Corrector::initialise(), Drift::initialise(), Laser::initialise(), Multipole::initialise(), BendBase::isInside(), isInside(), Monitor::isInside(), Multipole::isInside(), isInsideTransverse(), and TEST_F().
getElementPosition()
double ElementBase::getElementPosition () const inline inherited
Definition at line 617 of file ElementBase.h.
References elemedgeSet_m, elementPosition_m, and getName().
getEntrance()
double ElementBase::getEntrance () const inline virtual inherited
Get entrance position.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 486 of file ElementBase.h.
References BGeometryBase::getEntrance(), and getGeometry().
Referenced by BendBase::getDesignPath().
getEntranceFrame()
Euclid3D ElementBase::getEntranceFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 498 of file ElementBase.h.
References BGeometryBase::getEntranceFrame(), and getGeometry().
Referenced by BendBase::getChordLength(), and BendBase::getEdgeToBegin().
getEntrancePatch()
Euclid3D ElementBase::getEntrancePatch () const inline virtual inherited
Get patch.
Definition at line 502 of file ElementBase.h.
References BGeometryBase::getEntrancePatch(), and getGeometry().
getEntryPort()
Port ElementBase::getEntryPort () const inline virtual inherited
Return the entrance port of the canonical local chart.
In the placement-note language, this is the marked entrance port \(p_{i,\mathrm{entry}}\) of element \(i\). For straight elements in the bridge stage, the body-to-entry transform is taken from the legacy getEdgeToBegin() result.
Definition at line 544 of file ElementBase.h.
References getEdgeToBegin().
Referenced by getPlacementGeometry(), and TEST_F().
getExit()
double ElementBase::getExit () const inline virtual inherited
Get exit position.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 488 of file ElementBase.h.
References BGeometryBase::getExit(), and getGeometry().
Referenced by BendBase::getDesignPath().
getExitFrame()
Euclid3D ElementBase::getExitFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 500 of file ElementBase.h.
References BGeometryBase::getExitFrame(), and getGeometry().
Referenced by BendBase::getChordLength(), and BendBase::getEdgeToEnd().
getExitPatch()
Euclid3D ElementBase::getExitPatch () const inline virtual inherited
Get patch.
Definition at line 504 of file ElementBase.h.
References BGeometryBase::getExitPatch(), and getGeometry().
getExitPort()
Port ElementBase::getExitPort () const inline virtual inherited
Return the exit port of the canonical local chart.
In the placement-note language, this is the marked exit port \(p_{i,\mathrm{exit}}\). For straight elements in the bridge stage, the body-to-exit transform is taken from the legacy getEdgeToEnd() result.
Definition at line 548 of file ElementBase.h.
References getEdgeToEnd().
Referenced by getPlacementGeometry(), and TEST_F().
getField() [1/2]
const EMField & VariableRFCavity::getField () const override virtual inherited
Not implemented.
Implements Component.
Definition at line 108 of file VariableRFCavity.cpp.
getField() [2/2]
EMField & VariableRFCavity::getField () override virtual inherited
Not implemented.
Implements Component.
Definition at line 104 of file VariableRFCavity.cpp.
Referenced by TEST_F().
getFieldExtend()
void VariableRFCavity::getFieldExtend (double & zBegin, double & zEnd) const inline override virtual inherited
Return the longitudinal field-support extent.
For a VariableRFCavity the field support coincides with the nominal body extent, i.e. the interval latexmath:[z \in [0, L)] in the local element frame.
Implements Component.
Definition at line 129 of file VariableRFCavity.h.
References ElementBase::getElementLength().
Referenced by TEST_F().
getFlagDeleteOnTransverseExit()
bool ElementBase::getFlagDeleteOnTransverseExit () const inline inherited
Definition at line 633 of file ElementBase.h.
References deleteOnTransverseExit_m.
Referenced by BendBase::apply(), BendBase::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Multipole::apply(), Multipole::apply(), RFCavity::apply(), Solenoid::apply(), and TravelingWave::apply().
getFrequency()
virtual double VariableRFCavity::getFrequency (const double time) const inline virtual inherited
Get the frequency at a given time
Parameters
time the time at which the frequency is calculated
Returns
the RF cavity frequency.
Definition at line 148 of file VariableRFCavity.h.
References frequencyTD_m.
Referenced by TEST_F().
getFrequencyModel()
std::shared_ptr< AbstractTimeDependence > VariableRFCavity::getFrequencyModel () const virtual inherited
Returns
shared_ptr to the frequency
Definition at line 82 of file VariableRFCavity.cpp.
References frequencyTD_m.
Referenced by TEST_F(), TEST_F(), and TestVariableRFCavity::testNull().
getGeometry() [1/2]
const StraightGeometry & VariableRFCavity::getGeometry () const override virtual inherited
Returns
the cavity geometry
Implements ElementBase.
Definition at line 102 of file VariableRFCavity.cpp.
References geometry.
getGeometry() [2/2]
StraightGeometry & VariableRFCavity::getGeometry () override virtual inherited
Set the cavity geometry
Implements ElementBase.
Definition at line 100 of file VariableRFCavity.cpp.
References geometry.
Referenced by TEST_F().
getHeight()
virtual double VariableRFCavity::getHeight () const inline virtual inherited
Returns
the full height of the cavity
Definition at line 159 of file VariableRFCavity.h.
References halfHeight_m.
Referenced by TEST_F().
getLength()
virtual double VariableRFCavity::getLength () const inline virtual inherited
Returns
the length of the cavity
Definition at line 163 of file VariableRFCavity.h.
References length_m.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TestVariableRFCavity::testNull().
getMisalignment() [1/2]
CoordinateSystemTrafo ElementBase::getMisalignment () const inline inherited
Definition at line 592 of file ElementBase.h.
References misalignment_m.
Referenced by getPlacementMisalignment().
getMisalignment() [2/2]
void ElementBase::getMisalignment (double & x, double & y, double & s) const inherited
getName()
const std::string & ElementBase::getName () const virtual inherited
Get element name.
Definition at line 131 of file ElementBase.cpp.
References elementID.
Referenced by Ring::appendElement(), TBeamline< T >::clone(), TBeamline< T >::copyStructure(), Probe::doGoOffline(), PlaceRep::enter(), getElementPosition(), RFCavity::getMomentaKick(), getOutputFN(), CavityAutophaser::getPhaseAtMaxEnergy(), Selector::handleElement(), RFCavity::initialise(), Ring::initialise(), Solenoid::initialise(), PlaceRep::leave(), VariableRFCavity::operator=(), Sequence::print(), Ring::Ring(), BeamlineFieldElement::SortAsc(), TEST_F(), Component::trackBunch(), Component::trackMap(), OpalRBend::update(), OpalSBend::update(), Sequence::updateList(), ParallelTracker::updateRFElement(), and Replacer::visitFlaggedElmPtr().
getOrigin()
double ElementBase::getOrigin () const inline virtual inherited
Get origin position.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 484 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getOrigin().
getOutputFN()
std::string ElementBase::getOutputFN () const inherited
Get output filename.
Definition at line 137 of file ElementBase.cpp.
References getName(), and outputfn_m.
Referenced by Probe::doInitialise(), Monitor::initialise(), and PluginElement::initialise().
getParticleMatterInteraction()
ParticleMatterInteractionHandler * ElementBase::getParticleMatterInteraction () const inline virtual inherited
Definition at line 516 of file ElementBase.h.
References parmatint_m.
getPhase()
virtual double VariableRFCavity::getPhase (const double time) const inline virtual inherited
Get the phase at a given time
Parameters
time the time at which the phase is calculated
Returns
the RF cavity phase.
Definition at line 156 of file VariableRFCavity.h.
References phaseTD_m.
Referenced by TEST_F().
getPhaseModel()
std::shared_ptr< AbstractTimeDependence > VariableRFCavity::getPhaseModel () const virtual inherited
Returns
shared_ptr to the phase time dependence
Definition at line 78 of file VariableRFCavity.cpp.
References phaseTD_m.
Referenced by TEST_F(), TEST_F(), and TestVariableRFCavity::testNull().
getPlacedElement()
PlacedElement ElementBase::getPlacedElement () const inline inherited
Return a placed-element view assembled from the current bridge objects.
Definition at line 570 of file ElementBase.h.
References getPlacementGeometry(), getPlacementMisalignment(), getPlacementPose(), and getPlacementSupport().
Referenced by MeshGenerator::add(), and TEST_F().
getPlacementGeometry()
ElementGeometry ElementBase::getPlacementGeometry () const inline inherited
Return the bridge geometry ports assembled from legacy edge state.
The first redesign stage defines a minimal explicit port contract with three named body-relative ports: \(p_{i,\mathrm{entry}}\), \(p_{i,\mathrm{body}}\), \(p_{i,\mathrm{exit}}\). The default bridge preserves current OPALX behavior by deriving those ports from getEntryPort(), getBodyPort(), and getExitPort(), whose straight-element implementations are backed by the legacy getEdgeToBegin() and getEdgeToEnd() methods.
Definition at line 562 of file ElementBase.h.
References getBodyPort(), getEntryPort(), and getExitPort().
Referenced by getPlacedElement().
getPlacementMisalignment()
Misalignment ElementBase::getPlacementMisalignment () const inline inherited
Return the local nominal-to-actual correction stored for the element.
Definition at line 558 of file ElementBase.h.
References getMisalignment().
Referenced by getPlacedElement().
getPlacementPose()
PlacementPose ElementBase::getPlacementPose () const inline inherited
Return the nominal rigid placement transform of the element.
This is the bridge from the legacy stored CoordinateSystemTrafo to the new placement vocabulary. It preserves current nominal placement semantics and does not apply misalignment.
Definition at line 550 of file ElementBase.h.
References getCSTrafoGlobal2Local().
Referenced by getPlacedElement().
getPlacementSupport()
SupportPlacement ElementBase::getPlacementSupport () const inline inherited
Return the support-frame bridge object. The default is the body frame.
Definition at line 566 of file ElementBase.h.
Referenced by getPlacedElement().
getPotential()
virtual bool Component::getPotential (const Vector_t< double, 3 > & , const double & , Vector_t< double, 3 > & , double &) inline virtual inherited
Calculate the four-potential at some position relative to the component.
Parameters
R position in the local coordinate system of the component
t time
A filled with the calculated magnetic vector potential
phi filled with the calculated electric potential Note that any existing values in A and phi may be overwritten by this method.
Returns
true if particle is outside the field map, else false Default for component is to return false and make no change to A and phi
Definition at line 155 of file Component.h.
getRequiredNumberOfTimeSteps()
int ElementBase::getRequiredNumberOfTimeSteps () const inline virtual inherited
Reimplemented in BendBase, Drift, Laser, Marker, and Monitor.
Definition at line 627 of file ElementBase.h.
getRotationAboutZ()
double ElementBase::getRotationAboutZ () const inline inherited
Definition at line 608 of file ElementBase.h.
References rotationZAxis_m.
Referenced by OpalBeamline::compileCompatibilityPlacement().
getTotalTransform()
Euclid3D ElementBase::getTotalTransform () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 494 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getTotalTransform().
getTransform() [1/2]
Euclid3D ElementBase::getTransform (double fromS, double toS) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 490 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getTransform().
Referenced by BendBase::getDesignPath(), and TBeamline< T >::getTransform().
getTransform() [2/2]
Euclid3D ElementBase::getTransform (double s) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 496 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getTransform().
getType()
ElementType Component::getType () const virtual inherited
Get element type std::string.
Implements ElementBase.
Reimplemented in ConstantEFieldCavity, Corrector, Drift, Laser, Marker, Monitor, Multipole, Probe, RBend, RFCavity, SBend, Solenoid, and TravelingWave.
Definition at line 49 of file Component.cpp.
References ANY.
Referenced by ParallelTracker::visitComponent().
getTypeString() [1/2]
std::string ElementBase::getTypeString () const inline inherited
Definition at line 610 of file ElementBase.h.
References getType(), and getTypeString().
Referenced by getTypeString().
getTypeString() [2/2]
std::string ElementBase::getTypeString (ElementType type) static inherited
Definition at line 191 of file ElementBase.cpp.
References elementTypeToString_s.
getWake()
WakeFunction * ElementBase::getWake () const inline virtual inherited
return the attached wake object if there is any
Definition at line 508 of file ElementBase.h.
References wake_m.
getWidth()
virtual double VariableRFCavity::getWidth () const inline virtual inherited
Returns
the full width of the cavity
Definition at line 161 of file VariableRFCavity.h.
References halfWidth_m.
Referenced by TEST_F().
goOffline()
void Component::goOffline () virtual inherited
Reimplemented in Monitor, PluginElement, RFCavity, Solenoid, and TravelingWave.
Definition at line 45 of file Component.cpp.
References online_m.
goOnline()
void Component::goOnline (const double & kineticEnergy) virtual inherited
Reimplemented in Corrector, Monitor, RFCavity, Solenoid, and TravelingWave.
Definition at line 43 of file Component.cpp.
References online_m.
Referenced by PluginElement::initialise().
hasAttribute()
bool ElementBase::hasAttribute (const std::string & aKey) const virtual inherited
Test for existence of an attribute.
Definition at line 158 of file ElementBase.cpp.
References getConstChannel().
hasBoundaryGeometry()
bool ElementBase::hasBoundaryGeometry () const inline virtual inherited
Definition at line 514 of file ElementBase.h.
References bgeometry_m.
hasParticleMatterInteraction()
bool ElementBase::hasParticleMatterInteraction () const inline virtual inherited
Definition at line 520 of file ElementBase.h.
References parmatint_m.
hasWake()
bool ElementBase::hasWake () const inline virtual inherited
Definition at line 510 of file ElementBase.h.
References wake_m.
initialise()
void VariableRFCavity::initialise (PartBunch_t * bunch, double & startField, double & endField) override virtual inherited
Initialise ready for tracking
Just sets RefPartBunch_m
Implements Component.
Definition at line 162 of file VariableRFCavity.cpp.
References Component::RefPartBunch_m.
initialiseTimeDependencies()
void VariableRFCavity::initialiseTimeDependencies () const inherited
Lookup the time dependencies and update.
Throws if the named time dependencies can't be found. Also throws if the width or height is < 1 nm
Definition at line 176 of file VariableRFCavity.cpp.
References amplitudeName_m, amplitudeTD_m, frequencyName_m, frequencyTD_m, AbstractTimeDependence::getTimeDependence(), halfHeight_m, halfWidth_m, phaseName_m, and phaseTD_m.
Referenced by accept().
initNull()
void VariableRFCavity::initNull () protected inherited
Definition at line 64 of file VariableRFCavity.cpp.
References amplitudeName_m, frequencyName_m, halfHeight_m, halfWidth_m, length_m, phaseName_m, and Component::RefPartBunch_m.
Referenced by VariableRFCavity(), VariableRFCavity(), and VariableRFCavity().
isElementPositionSet()
bool ElementBase::isElementPositionSet () const inline inherited
Definition at line 625 of file ElementBase.h.
References elemedgeSet_m.
isInside()
bool ElementBase::isInside (const Vector_t< double, 3 > & r) const inline virtual inherited
Reimplemented in BendBase, Monitor, Multipole, RFCavity, Solenoid, and TravelingWave.
Definition at line 585 of file ElementBase.h.
References getElementLength(), and isInsideTransverse().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
isInsideTransverse()
bool ElementBase::isInsideTransverse (const Vector_t< double, 3 > & r) const protected inherited
Definition at line 232 of file ElementBase.cpp.
References aperture_m, CONIC_ELLIPTICAL, CONIC_RECTANGULAR, getEdgeToBegin(), getElementLength(), and CoordinateSystemTrafo::transformTo().
Referenced by BendBase::apply(), BendBase::apply(), Component::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Multipole::apply(), Multipole::apply(), BendBase::applyToReferenceParticle(), Component::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), BendBase::isInside(), isInside(), Monitor::isInside(), Multipole::isInside(), RFCavity::isInside(), Solenoid::isInside(), and TravelingWave::isInside().
isPositioned()
bool ElementBase::isPositioned () const inline inherited
Definition at line 598 of file ElementBase.h.
References positionIsFixed.
Referenced by OpalRBend::update(), and OpalSBend::update().
isSharable()
bool ElementBase::isSharable () const inline inherited
Test if the element can be shared.
Definition at line 506 of file ElementBase.h.
References shareFlag.
Referenced by copyStructure(), TBeamline< T >::copyStructure(), and Sequence::updateList().
makeBunch()
std::shared_ptr< PartBunch_t > TestVariableRFCavity::makeBunch (const size_t numParticles) inline
Definition at line 97 of file TestVariableRFCavity.cpp.
References dataSink_m, Beam::find(), and fsCmdBase_m.
makeSharable()
void ElementBase::makeSharable () virtual inherited
Set sharable flag.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 201 of file ElementBase.cpp.
References shareFlag.
Referenced by OpalMarker::OpalMarker().
Online()
bool Component::Online () virtual inherited
Definition at line 47 of file Component.cpp.
References online_m.
releasePosition()
void ElementBase::releasePosition () inline inherited
Definition at line 594 of file ElementBase.h.
References positionIsFixed.
Referenced by OpalRBend::update(), and OpalSBend::update().
removeAttribute()
void ElementBase::removeAttribute (const std::string & aKey) virtual inherited
Remove an existing attribute.
Definition at line 169 of file ElementBase.cpp.
References userAttribs.
setActionRange()
void ElementBase::setActionRange (const std::queue< std::pair< double, double > > & range) inline inherited
Definition at line 600 of file ElementBase.h.
References actionRange_m, and elementEdge_m.
setAmplitudeModel()
void VariableRFCavity::setAmplitudeModel (std::shared_ptr< AbstractTimeDependence > amplitude_td) virtual inherited
Set the amplitude (field gradient) time dependence
Definition at line 86 of file VariableRFCavity.cpp.
References amplitudeTD_m.
Referenced by operator=(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
setAmplitudeName()
virtual void VariableRFCavity::setAmplitudeName (const std::string & amplitude) inline virtual inherited
Set the amplitude time dependence name
The name is used to find the amplitude model at accept time
Definition at line 189 of file VariableRFCavity.h.
References amplitudeName_m.
Referenced by TEST_F().
setAperture()
void ElementBase::setAperture (const ApertureType & type, const std::vector< double > & args) inline inherited
Definition at line 576 of file ElementBase.h.
References aperture_m.
Referenced by Component::Component(), TEST_F(), TEST_F(), TEST_F(), OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
setAttribute()
void ElementBase::setAttribute (const std::string & aKey, double val) virtual inherited
Set value of an attribute.
Definition at line 171 of file ElementBase.cpp.
References getChannel(), and Channel::isSettable().
Referenced by update(), and OpalElement::updateUnknown().
setBoundaryGeometry()
void ElementBase::setBoundaryGeometry (BoundaryGeometry * geo) virtual inherited
attach a boundary geometry field to the element
Definition at line 215 of file ElementBase.cpp.
References bgeometry_m.
setCSTrafoGlobal2Local()
void ElementBase::setCSTrafoGlobal2Local (const CoordinateSystemTrafo & ori) inline inherited
Definition at line 522 of file ElementBase.h.
References csTrafoGlobal2Local_m, and positionIsFixed.
Referenced by setPlacementPose(), TEST_F(), OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
setCurrentSCoordinate()
void ElementBase::setCurrentSCoordinate (double s) inherited
Definition at line 223 of file ElementBase.cpp.
References actionRange_m, and elementEdge_m.
setDesignEnergy()
void Component::setDesignEnergy (const double & energy, bool changeable = true) inline virtual inherited
Reimplemented in BendBase, Corrector, and RFCavity.
Definition at line 252 of file Component.h.
setElementLength()
void ElementBase::setElementLength (double length) inline virtual inherited
Set design length.
Reimplemented in ConstantEFieldCavityRep, and MultipoleT.
Definition at line 482 of file ElementBase.h.
References getGeometry(), and BGeometryBase::setElementLength().
Referenced by MultipoleT::setElementLength(), BendBase::setLength(), SequenceMember::setLength(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), OpalCavity::update(), OpalMonitor::update(), OpalMultipole::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalSolenoid::update(), and OpalTravelingWave::update().
setElementPosition()
void ElementBase::setElementPosition (double elemedge) inline inherited
Access to ELEMEDGE attribute.
Definition at line 612 of file ElementBase.h.
References elemedgeSet_m, and elementPosition_m.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and OpalElement::update().
setExitFaceSlope()
void Component::setExitFaceSlope (const double & m) inline inherited
Definition at line 250 of file Component.h.
References exit_face_slope_m.
setFlagDeleteOnTransverseExit()
void ElementBase::setFlagDeleteOnTransverseExit (bool flag = true) inline inherited
Definition at line 629 of file ElementBase.h.
References deleteOnTransverseExit_m.
Referenced by OpalElement::update().
setFrequencyModel()
void VariableRFCavity::setFrequencyModel (std::shared_ptr< AbstractTimeDependence > frequency_td) virtual inherited
Set the frequency time dependence
Definition at line 95 of file VariableRFCavity.cpp.
References frequencyTD_m.
Referenced by operator=(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
setFrequencyName()
virtual void VariableRFCavity::setFrequencyName (const std::string & frequency) inline virtual inherited
Set the frequency time dependence name
The name is used to find the frequency model at accept time
Definition at line 201 of file VariableRFCavity.h.
References frequencyName_m.
Referenced by TEST_F().
setHeight()
virtual void VariableRFCavity::setHeight (const double fullHeight) inline virtual inherited
Set the full height of the cavity
Definition at line 165 of file VariableRFCavity.h.
References halfHeight_m.
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
setLength()
void VariableRFCavity::setLength (double length) virtual inherited
Set the length of the cavity
Definition at line 192 of file VariableRFCavity.cpp.
References geometry, and length_m.
Referenced by operator=(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
setMisalignment()
void ElementBase::setMisalignment (const CoordinateSystemTrafo & cst) inline inherited
Definition at line 590 of file ElementBase.h.
References misalignment_m.
Referenced by TEST_F(), and OpalElement::update().
setName()
void ElementBase::setName (const std::string & name) virtual inherited
Set element name.
Definition at line 133 of file ElementBase.cpp.
References elementID.
Referenced by Sequence::insertDrifts(), and VariableRFCavity::operator=().
setOutputFN()
void ElementBase::setOutputFN (std::string fn) inherited
Set output filename.
Definition at line 135 of file ElementBase.cpp.
Referenced by OpalMonitor::update(), and OpalProbe::update().
setParticleMatterInteraction()
void ElementBase::setParticleMatterInteraction (ParticleMatterInteractionHandler * spys) virtual inherited
Definition at line 219 of file ElementBase.cpp.
References parmatint_m.
setPhaseModel()
void VariableRFCavity::setPhaseModel (std::shared_ptr< AbstractTimeDependence > phase_td) virtual inherited
Set the phase time dependence
Definition at line 91 of file VariableRFCavity.cpp.
References phaseTD_m.
Referenced by operator=(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
setPhaseName()
virtual void VariableRFCavity::setPhaseName (const std::string & phase) inline virtual inherited
Set the phase time dependence name
The name is used to find the phase model at accept time
Definition at line 195 of file VariableRFCavity.h.
References phaseName_m.
Referenced by TEST_F().
setPlacementPose()
void ElementBase::setPlacementPose (const PlacementPose & pose) inline inherited
Set the nominal rigid placement transform of the element.
This bridge setter preserves the existing storage model by delegating to setCSTrafoGlobal2Local().
Definition at line 554 of file ElementBase.h.
References PlacementPose::getParentToNominal(), and setCSTrafoGlobal2Local().
setRotationAboutZ()
void ElementBase::setRotationAboutZ (double rotation) inline inherited
Set rotation about z axis in bend frame.
Definition at line 606 of file ElementBase.h.
References rotationZAxis_m.
Referenced by OpalElement::update().
SetUpTestSuite()
void TestVariableRFCavity::SetUpTestSuite () inline static
Definition at line 33 of file TestVariableRFCavity.cpp.
References Options::enableHDF5, OpalData::getInstance(), gmsg, and OpalData::storeInputFn().
setWake()
void ElementBase::setWake (WakeFunction * wf) virtual inherited
attach a wake field to the element
Definition at line 211 of file ElementBase.cpp.
References wake_m.
setWidth()
virtual void VariableRFCavity::setWidth (const double fullWidth) inline virtual inherited
Set the full width of the cavity
Definition at line 167 of file VariableRFCavity.h.
References halfWidth_m.
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
TearDownTestSuite()
void TestVariableRFCavity::TearDownTestSuite () inline static
Definition at line 46 of file TestVariableRFCavity.cpp.
References gmsg.
testGetSet()
void TestVariableRFCavity::testGetSet (VariableRFCavity & cav1, std::shared_ptr< AbstractTimeDependence >(VariableRFCavity::* getMethod)() const, void(VariableRFCavity::* setMethod)(std::shared_ptr< AbstractTimeDependence >)) inline static
Definition at line 121 of file TestVariableRFCavity.cpp.
References VariableRFCavity::VariableRFCavity().
testNull()
void TestVariableRFCavity::testNull (const VariableRFCavity & cav1) inline static
Definition at line 139 of file TestVariableRFCavity.cpp.
References VariableRFCavity::getAmplitudeModel(), VariableRFCavity::getFrequencyModel(), VariableRFCavity::getLength(), VariableRFCavity::getPhaseModel(), and VariableRFCavity::VariableRFCavity().
trackBunch()
void Component::trackBunch (PartBunch_t & bunch, const PartData & , bool revBeam, bool revTrack) const virtual inherited
Track a borrowed particle bunch through a non-standard component.
The default implementation throws a LogicalError.
Parameters
bunch Particle bunch to track. The component does not take ownership.
Definition at line 35 of file Component.cpp.
References ElementBase::getName().
Referenced by Tracker::visitComponent().
trackMap()
void Component::trackMap (FVps< double, 6 > & map, const PartData & , bool revBeam, bool revTrack) const virtual inherited
Track a map.
Definition at line 39 of file Component.cpp.
References ElementBase::getName().
update()
bool ElementBase::update (const AttributeSet & set) inherited
Update element.
Definition at line 203 of file ElementBase.cpp.
References AttributeSet::begin(), AttributeSet::end(), and setAttribute().
visitBeamline()
void TestVariableRFCavity::visitBeamline (const Beamline &) inline override virtual
Apply the algorithm to a beam line.
Implements BeamlineVisitor.
Definition at line 54 of file TestVariableRFCavity.cpp.
visitComponent()
void TestVariableRFCavity::visitComponent (const Component &) inline override virtual
Apply the algorithm to an arbitrary component.
Implements BeamlineVisitor.
Definition at line 55 of file TestVariableRFCavity.cpp.
References Component::Component().
visitConstantEFieldCavity()
void TestVariableRFCavity::visitConstantEFieldCavity (const ConstantEFieldCavity &) inline override virtual
Apply the algorithm to a constant E-field cavity element.
Implements BeamlineVisitor.
Definition at line 56 of file TestVariableRFCavity.cpp.
visitDrift()
void TestVariableRFCavity::visitDrift (const Drift &) inline override virtual
Apply the algorithm to a drift space.
Implements BeamlineVisitor.
Definition at line 57 of file TestVariableRFCavity.cpp.
visitFlaggedElmPtr()
void TestVariableRFCavity::visitFlaggedElmPtr (const FlaggedElmPtr &) inline override virtual
Apply the algorithm to a FlaggedElmPtr.
Implements BeamlineVisitor.
Definition at line 58 of file TestVariableRFCavity.cpp.
visitLaser()
void TestVariableRFCavity::visitLaser (const Laser &) inline override virtual
Apply the algorithm to a laser element.
Implements BeamlineVisitor.
Definition at line 59 of file TestVariableRFCavity.cpp.
visitMarker()
void TestVariableRFCavity::visitMarker (const Marker &) inline override virtual
Apply the algorithm to a marker.
Implements BeamlineVisitor.
Definition at line 60 of file TestVariableRFCavity.cpp.
visitMonitor()
void TestVariableRFCavity::visitMonitor (const Monitor &) inline override virtual
Apply the algorithm to a beam position monitor.
Implements BeamlineVisitor.
Definition at line 61 of file TestVariableRFCavity.cpp.
visitMultipole()
void TestVariableRFCavity::visitMultipole (const Multipole &) inline override virtual
Apply the algorithm to a multipole.
Implements BeamlineVisitor.
Definition at line 62 of file TestVariableRFCavity.cpp.
visitMultipoleT()
void TestVariableRFCavity::visitMultipoleT (const MultipoleT &) inline override virtual
Apply the algorithm to an arbitrary multipole.
Implements BeamlineVisitor.
Definition at line 63 of file TestVariableRFCavity.cpp.
visitProbe()
void TestVariableRFCavity::visitProbe (const Probe &) inline override virtual
Apply the algorithm to a Probe.
Implements BeamlineVisitor.
Definition at line 72 of file TestVariableRFCavity.cpp.
visitRBend()
void TestVariableRFCavity::visitRBend (const RBend &) inline override virtual
Apply the algorithm to a rectangular bend.
Implements BeamlineVisitor.
Definition at line 64 of file TestVariableRFCavity.cpp.
visitRFCavity()
void TestVariableRFCavity::visitRFCavity (const RFCavity &) inline override virtual
Apply the algorithm to a RF cavity.
Implements BeamlineVisitor.
Definition at line 65 of file TestVariableRFCavity.cpp.
visitRing()
void TestVariableRFCavity::visitRing (const Ring &) inline override virtual
Apply the algorithm to a Ring element.
Implements BeamlineVisitor.
Definition at line 67 of file TestVariableRFCavity.cpp.
visitSBend()
void TestVariableRFCavity::visitSBend (const SBend &) inline override virtual
Apply the algorithm to a sector bend.
Implements BeamlineVisitor.
Definition at line 68 of file TestVariableRFCavity.cpp.
visitScalingFFAMagnet()
void TestVariableRFCavity::visitScalingFFAMagnet (const ScalingFFAMagnet &) inline override virtual
Implements BeamlineVisitor.
Definition at line 66 of file TestVariableRFCavity.cpp.
visitSolenoid()
void TestVariableRFCavity::visitSolenoid (const Solenoid &) inline override virtual
Apply the algorithm to a Solenoid element.
Implements BeamlineVisitor.
Definition at line 69 of file TestVariableRFCavity.cpp.
visitTravelingWave()
void TestVariableRFCavity::visitTravelingWave (const TravelingWave &) inline override virtual
Apply the algorithm to a traveling wave.
Implements BeamlineVisitor.
Definition at line 70 of file TestVariableRFCavity.cpp.
visitVariableRFCavity()
void TestVariableRFCavity::visitVariableRFCavity (const VariableRFCavity &) inline override virtual
Apply the algorithm to a variable RF cavity.
Implements BeamlineVisitor.
Definition at line 73 of file TestVariableRFCavity.cpp.
References VariableRFCavity::VariableRFCavity().
visitVerticalFFAMagnet()
void TestVariableRFCavity::visitVerticalFFAMagnet (const VerticalFFAMagnet &) inline override virtual
Apply the algorithm to a vertical FFA magnet.
Implements BeamlineVisitor.
Definition at line 71 of file TestVariableRFCavity.cpp.
Member Data Documentation
actionRange_m
std::queue<std::pair<double, double> > ElementBase::actionRange_m private inherited
Definition at line 468 of file ElementBase.h.
Referenced by setActionRange(), and setCurrentSCoordinate().
amplitudeName_m
std::string VariableRFCavity::amplitudeName_m protected inherited
Definition at line 226 of file VariableRFCavity.h.
Referenced by initialiseTimeDependencies(), initNull(), operator=(), and setAmplitudeName().
amplitudeTD_m
std::shared_ptr<AbstractTimeDependence> VariableRFCavity::amplitudeTD_m mutable protected inherited
Definition at line 223 of file VariableRFCavity.h.
Referenced by apply(), apply(), apply(), getAmplitude(), getAmplitudeModel(), initialiseTimeDependencies(), operator=(), and setAmplitudeModel().
aperture_m
std::pair<ApertureType, std::vector<double> > ElementBase::aperture_m protected inherited
Definition at line 439 of file ElementBase.h.
Referenced by ElementBase(), getAperture(), isInsideTransverse(), and setAperture().
bgeometry_m
BoundaryGeometry* ElementBase::bgeometry_m private inherited
Definition at line 459 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getBoundaryGeometry(), hasBoundaryGeometry(), and setBoundaryGeometry().
csTrafoGlobal2Local_m
CoordinateSystemTrafo ElementBase::csTrafoGlobal2Local_m protected inherited
Definition at line 436 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getBoundingBoxInLabCoords(), getCSTrafoGlobal2Local(), and setCSTrafoGlobal2Local().
dataSink_m
std::shared_ptr<DataSink> TestVariableRFCavity::dataSink_m
Definition at line 95 of file TestVariableRFCavity.cpp.
Referenced by makeBunch().
defaultAperture_m
const std::vector< double > Component::defaultAperture_m = std::vector<double>({1e6, 1e6, 1.0}) static protected inherited
Definition at line 221 of file Component.h.
Referenced by Component().
deleteOnTransverseExit_m
bool ElementBase::deleteOnTransverseExit_m = true private inherited
Definition at line 472 of file ElementBase.h.
Referenced by ElementBase(), getFlagDeleteOnTransverseExit(), and setFlagDeleteOnTransverseExit().
elemedgeSet_m
bool ElementBase::elemedgeSet_m private inherited
Definition at line 466 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getElementPosition(), isElementPositionSet(), and setElementPosition().
elementEdge_m
double ElementBase::elementEdge_m protected inherited
Definition at line 441 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), setActionRange(), and setCurrentSCoordinate().
elementID
std::string ElementBase::elementID private inherited
Definition at line 450 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getName(), and setName().
elementPosition_m
double ElementBase::elementPosition_m private inherited
ELEMEDGE attribute.
Definition at line 465 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getElementPosition(), and setElementPosition().
elementTypeToString_s
const std::map< ElementType, std::string > ElementBase::elementTypeToString_s static private inherited
Initial value:
= {
        {ElementType::ANY, "Any"},
        {ElementType::BEAMLINE, "Beamline"},
        {ElementType::DRIFT, "Drift"},
        {ElementType::LASER, "Laser"},
        {ElementType::MARKER, "Marker"},
        {ElementType::MULTIPOLE, "Multipole"},
        {ElementType::RFCAVITY, "RFCavity"},
        {ElementType::TRAVELINGWAVE, "TravelingWave"},
        {ElementType::SBEND, "SBEND"},
        {ElementType::RBEND, "RBEND"},
        {ElementType::RBEND3D, "RBEND3D"},
        {ElementType::RING, "Ring"},
        {ElementType::SOURCE, "SOURCE"},
        {ElementType::SOLENOID, "SOLENOID"},
        {ElementType::PROBE, "Probe"},
        {ElementType::VACUUM, "Vacuum"},
        {ElementType::CONSTANTEFIELDCAVITY, "ConstantEFieldCavity"}}
Definition at line 73 of file ElementBase.h.
Referenced by getTypeString().
exit_face_slope_m
double Component::exit_face_slope_m protected inherited
Definition at line 222 of file Component.h.
Referenced by Component(), Component(), and setExitFaceSlope().
frequencyName_m
std::string VariableRFCavity::frequencyName_m protected inherited
Definition at line 227 of file VariableRFCavity.h.
Referenced by initialiseTimeDependencies(), initNull(), operator=(), and setFrequencyName().
frequencyTD_m
std::shared_ptr<AbstractTimeDependence> VariableRFCavity::frequencyTD_m mutable protected inherited
Definition at line 224 of file VariableRFCavity.h.
Referenced by apply(), apply(), apply(), getFrequency(), getFrequencyModel(), initialiseTimeDependencies(), operator=(), and setFrequencyModel().
fsCmdBase_m
std::shared_ptr<FieldSolverCmd> TestVariableRFCavity::fsCmdBase_m
Definition at line 94 of file TestVariableRFCavity.cpp.
Referenced by makeBunch().
geometry
StraightGeometry VariableRFCavity::geometry protected inherited
The cavity's geometry.
Definition at line 233 of file VariableRFCavity.h.
Referenced by getGeometry(), getGeometry(), and setLength().
halfHeight_m
double VariableRFCavity::halfHeight_m protected inherited
Definition at line 229 of file VariableRFCavity.h.
Referenced by apply(), apply(), apply(), getHeight(), initialiseTimeDependencies(), initNull(), operator=(), and setHeight().
halfWidth_m
double VariableRFCavity::halfWidth_m protected inherited
Definition at line 228 of file VariableRFCavity.h.
Referenced by apply(), apply(), apply(), getWidth(), initialiseTimeDependencies(), initNull(), operator=(), and setWidth().
length_m
double VariableRFCavity::length_m protected inherited
Definition at line 230 of file VariableRFCavity.h.
Referenced by getLength(), initNull(), operator=(), and setLength().
misalignment_m
CoordinateSystemTrafo ElementBase::misalignment_m protected inherited
Definition at line 437 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getMisalignment(), and setMisalignment().
online_m
bool Component::online_m protected inherited
Definition at line 226 of file Component.h.
Referenced by Component(), Component(), Probe::doGoOffline(), BendBase::finalise(), Multipole::finalise(), PluginElement::finalise(), Ring::finalise(), goOffline(), PluginElement::goOffline(), RFCavity::goOffline(), Solenoid::goOffline(), goOnline(), Corrector::goOnline(), Monitor::goOnline(), RFCavity::goOnline(), Solenoid::goOnline(), TravelingWave::goOnline(), BendBase::initialise(), Multipole::initialise(), Ring::initialise(), Online(), and PluginElement::~PluginElement().
outputfn_m
std::string ElementBase::outputfn_m private inherited
The name of the outputfile
Definition at line 470 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), and getOutputFN().
parmatint_m
ParticleMatterInteractionHandler* ElementBase::parmatint_m private inherited
Definition at line 461 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getParticleMatterInteraction(), hasParticleMatterInteraction(), and setParticleMatterInteraction().
phaseName_m
std::string VariableRFCavity::phaseName_m protected inherited
Definition at line 225 of file VariableRFCavity.h.
Referenced by initialiseTimeDependencies(), initNull(), operator=(), and setPhaseName().
phaseTD_m
std::shared_ptr<AbstractTimeDependence> VariableRFCavity::phaseTD_m mutable protected inherited
Definition at line 222 of file VariableRFCavity.h.
Referenced by apply(), apply(), apply(), getPhase(), getPhaseModel(), initialiseTimeDependencies(), operator=(), and setPhaseModel().
positionIsFixed
bool ElementBase::positionIsFixed private inherited
Definition at line 463 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), fixPosition(), isPositioned(), releasePosition(), and setCSTrafoGlobal2Local().
RefPartBunch_m
PartBunch_t* Component::RefPartBunch_m protected inherited
Definition at line 225 of file Component.h.
Referenced by BendBase::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Corrector::apply(), Multipole::apply(), MultipoleT::apply(), MultipoleT::apply(), RFCavity::apply(), RFCavity::apply(), Ring::apply(), ScalingFFAMagnet::apply(), Solenoid::apply(), TravelingWave::apply(), TravelingWave::apply(), VariableRFCavity::apply(), VariableRFCavity::apply(), VerticalFFAMagnet::apply(), BendBase::calcDesignRadius(), BendBase::calcFieldAmplitude(), BendBase::calcGamma(), Component(), MultipoleT::finalise(), ScalingFFAMagnet::finalise(), VariableRFCavity::finalise(), VerticalFFAMagnet::finalise(), Corrector::goOnline(), BendBase::initialise(), ConstantEFieldCavity::initialise(), Corrector::initialise(), Drift::initialise(), Laser::initialise(), Marker::initialise(), Monitor::initialise(), Multipole::initialise(), MultipoleT::initialise(), PluginElement::initialise(), RFCavity::initialise(), RFCavity::initialise(), ScalingFFAMagnet::initialise(), Solenoid::initialise(), TravelingWave::initialise(), VariableRFCavity::initialise(), VerticalFFAMagnet::initialise(), VariableRFCavity::initNull(), Multipole::isFocusing(), MultipoleT::MultipoleT(), ScalingFFAMagnet::ScalingFFAMagnet(), Corrector::setDesignEnergy(), Ring::setRefPartBunch(), RFCavity::trackOnAxisParticle(), and VerticalFFAMagnet::VerticalFFAMagnet().
rotationZAxis_m
double ElementBase::rotationZAxis_m protected inherited
Definition at line 443 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getRotationAboutZ(), and setRotationAboutZ().
shareFlag
bool ElementBase::shareFlag mutable protected inherited
Definition at line 434 of file ElementBase.h.
Referenced by Beamline::Beamline(), Beamline::Beamline(), Beamline::Beamline(), ElementBase(), ElementBase(), isSharable(), makeSharable(), and TBeamline< T >::makeSharable().
userAttribs
AttributeSet ElementBase::userAttribs private inherited
Definition at line 455 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getChannel(), and removeAttribute().
wake_m
WakeFunction* ElementBase::wake_m private inherited
Definition at line 457 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getWake(), hasWake(), and setWake().
The documentation for this class was generated from the following file:
TestVariableRFCavity.cpp