OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions::SHash Class Reference
Expressions::SHash Class Reference
A scalar expression.
#include <SHash.h>
Public Member Functions
SHash (const ATable &)
Constructor.
SHash (const SHash &)
virtual ~SHash ()
virtual Scalar< double > * clone () const
Make clone.
virtual double evaluate () const
Evaluate.
virtual void print (std::ostream &str, int precedence=99) const
Print expression.
virtual bool isConstant () const
Test for constant.
Private Member Functions
SHash ()
void operator= (const SHash &)
Private Attributes
const ATable & itsTable
Detailed Description
A scalar expression.
Definition at line 35 of file SHash.h.
Constructor & Destructor Documentation
SHash() [1/3]
Expressions::SHash::SHash (const ATable & table) explicit
Constructor.
Definition at line 31 of file SHash.cpp.
References itsTable.
Referenced by operator=(), and SHash().
SHash() [2/3]
Expressions::SHash::SHash (const SHash & rhs)
Definition at line 29 of file SHash.cpp.
References itsTable, Expressions::Scalar< double >::Scalar(), and SHash().
~SHash()
Expressions::SHash::~SHash () virtual
Definition at line 33 of file SHash.cpp.
SHash() [3/3]
Expressions::SHash::SHash () private
Member Function Documentation
clone()
Scalar< double > * Expressions::SHash::clone () const virtual
Make clone.
Implements Expressions::Scalar< double >.
Definition at line 35 of file SHash.cpp.
References itsTable, and Expressions::Scalar< double >::Scalar().
evaluate()
double Expressions::SHash::evaluate () const virtual
Evaluate.
Implements Expressions::Scalar< double >.
Definition at line 37 of file SHash.cpp.
References itsTable.
isConstant()
bool Expressions::Scalar< double >::isConstant () const inline virtual inherited
Test for constant.
Definition at line 88 of file AbstractObjects/Expressions.h.
operator=()
void Expressions::SHash::operator= (const SHash &) private
References SHash().
print()
void Expressions::SHash::print (std::ostream & str, int precedence = 99) const virtual
Print expression.
Implements Expressions::Scalar< double >.
Definition at line 39 of file SHash.cpp.
Member Data Documentation
itsTable
const ATable& Expressions::SHash::itsTable private
Definition at line 61 of file SHash.h.
Referenced by clone(), evaluate(), SHash(), and SHash().
The documentation for this class was generated from the following files:
SHash.h
SHash.cpp