OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions::AColumn Class Reference
Expressions::AColumn Class Reference
An array expression defined as a table column.
#include <AColumn.h>
Public Member Functions
AColumn (const std::string &tName, const std::string &cName, const RangeRep &rng)
Constructor.
AColumn (const AColumn &)
~AColumn ()
virtual OArray< double > * clone () const
Make clone.
virtual std::vector< double > evaluate () const
Evaluate.
virtual void print (std::ostream &os, int precedence=99) const
Print expression.
virtual bool isConstant () const
Test for constant.
Private Member Functions
AColumn ()
const AColumn & operator= (const AColumn &)
Private Attributes
const std::string tab_name
const std::string col_name
RangeRep itsRange
Detailed Description
An array expression defined as a table column.
Definition at line 35 of file AColumn.h.
Constructor & Destructor Documentation
AColumn() [1/3]
Expressions::AColumn::AColumn (const std::string & tName, const std::string & cName, const RangeRep & rng)
Constructor.
Definition at line 37 of file AColumn.cpp.
References col_name, itsRange, Expressions::OArray< double >::OArray(), and tab_name.
Referenced by AColumn(), and operator=().
AColumn() [2/3]
Expressions::AColumn::AColumn (const AColumn & rhs)
Definition at line 31 of file AColumn.cpp.
References AColumn(), col_name, itsRange, Expressions::OArray< double >::OArray(), and tab_name.
~AColumn()
Expressions::AColumn::~AColumn ()
Definition at line 40 of file AColumn.cpp.
AColumn() [3/3]
Expressions::AColumn::AColumn () private
Referenced by clone().
Member Function Documentation
clone()
OArray< double > * Expressions::AColumn::clone () const virtual
Make clone.
Implements Expressions::OArray< double >.
Definition at line 42 of file AColumn.cpp.
References AColumn(), and Expressions::OArray< double >::OArray().
evaluate()
std::vector< double > Expressions::AColumn::evaluate () const virtual
Evaluate.
Implements Expressions::OArray< double >.
Definition at line 44 of file AColumn.cpp.
References col_name, Table::fill(), Table::find(), Table::getColumn(), itsRange, and tab_name.
isConstant()
bool Expressions::OArray< double >::isConstant () const inline virtual inherited
Test for constant.
Definition at line 165 of file AbstractObjects/Expressions.h.
operator=()
const AColumn & Expressions::AColumn::operator= (const AColumn &) private
References AColumn().
print()
void Expressions::AColumn::print (std::ostream & os, int precedence = 99) const virtual
Print expression.
Implements Expressions::OArray< double >.
Definition at line 50 of file AColumn.cpp.
References col_name, itsRange, and tab_name.
Member Data Documentation
col_name
const std::string Expressions::AColumn::col_name private
Definition at line 61 of file AColumn.h.
Referenced by AColumn(), AColumn(), evaluate(), and print().
itsRange
RangeRep Expressions::AColumn::itsRange private
Definition at line 64 of file AColumn.h.
Referenced by AColumn(), AColumn(), evaluate(), and print().
tab_name
const std::string Expressions::AColumn::tab_name private
Definition at line 60 of file AColumn.h.
Referenced by AColumn(), AColumn(), evaluate(), and print().
The documentation for this class was generated from the following files:
AColumn.h
AColumn.cpp