OPALX (Object Oriented Parallel Accelerator Library for Exascal): Gaussian Class Reference
Gaussian Class Reference
Generating particles following a Gaussian distribution.
#include <Gaussian.h>
Public Member Functions
Gaussian (std::shared_ptr< ParticleContainer_t > pc, std::shared_ptr< FieldContainer_t > fc, Distribution_t *opalDist)
Constructor for the Gaussian sampler.
Gaussian (std::shared_ptr< ParticleContainer_t > pc, const Vector_t< double, 3 > &sigmaR, const Vector_t< double, 3 > &sigmaP, double avrgpz, const Vector_t< double, 3 > &cutoffR, bool fix_meanR=true)
Constructor for the Gaussian sampler without field container and distribution object.
void generateParticles (size_t &numberOfParticles, Vector_t< double, 3 > nr) override
Generates particles with a Gaussian distribution.
void emitParticles (double t, double dt) override
Time-stepped emission hook for one-shot delayed injection.
void setSigmaR (const Vector_t< double, 3 > &sigmaR)
void setSigmaP (const Vector_t< double, 3 > &sigmaP)
void setAvrgpz (double avrgpz)
void setCutoffR (const Vector_t< double, 3 > &cutoffR)
void getParameters (Vector_t< double, 3 > &sigmaR, Vector_t< double, 3 > &sigmaP, double &avrgpz, Vector_t< double, 3 > &cutoffR) const
void setFixMeanR (bool fixMeanR)
void getFixMeanR (bool &fixMeanR) const
void setEmissionOffsets (ippl::Vector< double, 3 > R0, ippl::Vector< double, 3 > P0, double t0, const std::string &emissionModel="NONE")
Vector_t< double, 3 > getEmissionR0 () const
virtual bool isEmissionDone (double t) const
Whether this sampler has finished all emission (no more particles will be created).
virtual void testNumEmitParticles (size_t, double)
virtual void testEmitParticles (size_t, double)
virtual void initDomainDecomp (double)
virtual void setWithDomainDecomp (bool)
size_t computeLocalEmitCount (size_t totalToSample) const
Computes the number of particles this rank should emit so that the global total equals totalToSample and no rank exceeds its capacity (space left).
Public Attributes
IpplTimings::TimerRef samperTimer_m
Timer for performance profiling.
Protected Attributes
std::shared_ptr< ParticleContainer_t > pc_m
std::shared_ptr< FieldContainer_t > fc_m
Distribution_t * opalDist_m
std::string samplingMethod_m
Vector_t< double, 3 > R0_m = 0.0
Emission source offset: position R0, momentum P0, start time t0 (applied in sample step).
Vector_t< double, 3 > P0_m = 0.0
double t0_m = 0.0
std::string emissionModel_m = "NONE"
bool hasEmittedOnce_m = false
For one-shot emitters (e.g. Gaussian at delayed t0): guard to avoid double sampling.
Private Member Functions
void initRandomPool ()
Initializes the random number generator pool.
Private Attributes
GeneratorPool randPool_m
Pool of random number generators for parallel sampling.
Vector_t< double, 3 > sigmaR_m
Standard deviations for position and momentum distributions.
Vector_t< double, 3 > sigmaP_m
double avrgpz_m
Average momentum in the z-direction.
Vector_t< double, 3 > cutoffR_m
Cutoff multiplier for position distribution.
bool fixMeanR_m = true
Flag to exactly fix the mean position of particles after sampling.
Detailed Description
Generating particles following a Gaussian distribution.
This function samples particle positions R and momenta P given following normal distributions a normal distribution R ~ N ([0, 0, 0 ], sdR) P ~ N ([0, 0, avrgpz], sdP) where sdR = [SigmaR[0] 0 0 0 SigmaR[1] 0 0 0 SigmaR[2]]
and sdP = [SigmaP[0] 0 0 0 SigmaP[1] 0 0 0 SigmaP[2]].
Here, R is sampled in a bounded domains R \in [-CutoffR*SigmaR, CutoffR*SigmaR]^3 and corrected by translation to ensure mean = [0,0,0].
Parameters
numberOfParticles The total number of particles to generate.
nr The number of grid points in each dimension (not used here).
Definition at line 38 of file Gaussian.h.
Constructor & Destructor Documentation
Gaussian() [1/2]
Gaussian::Gaussian (std::shared_ptr< ParticleContainer_t > pc, std::shared_ptr< FieldContainer_t > fc, Distribution_t * opalDist)
Constructor for the Gaussian sampler.
Constructs a Gaussian sampler.
Parameters
pc Shared pointer to the particle container.
fc Shared pointer to the field container.
opalDist Borrowed distribution object.
Definition at line 15 of file Gaussian.cpp.
References Distribution::getAvrgpz(), Distribution::getCutoffR(), Distribution::getSigmaP(), Distribution::getSigmaR(), initRandomPool(), samperTimer_m, setAvrgpz(), setCutoffR(), setSigmaP(), and setSigmaR().
Gaussian() [2/2]
Gaussian::Gaussian (std::shared_ptr< ParticleContainer_t > pc, const Vector_t< double, 3 > & sigmaR, const Vector_t< double, 3 > & sigmaP, double avrgpz, const Vector_t< double, 3 > & cutoffR, bool fix_meanR = true)
Constructor for the Gaussian sampler without field container and distribution object.
Parameters
pc Shared pointer to the particle container.
sigmaR Standard deviation for position distribution.
sigmaP Standard deviation for momentum distribution.
avrgpz Average momentum in the z-direction.
cutoffR Cutoff multiplier for position distribution.
fix_meanR Flag to exactly fix the mean position of particles after sampling.
Definition at line 27 of file Gaussian.cpp.
References initRandomPool(), samperTimer_m, setAvrgpz(), setCutoffR(), setFixMeanR(), setSigmaP(), and setSigmaR().
Member Function Documentation
computeLocalEmitCount()
size_t SamplingBase::computeLocalEmitCount (size_t totalToSample) const inherited
Computes the number of particles this rank should emit so that the global total equals totalToSample and no rank exceeds its capacity (space left).
Parameters
totalToSample Global number of particles to emit this timestep.
Returns
Local number of particles this rank should create/emit.
Definition at line 6 of file SamplingBase.cpp.
References SamplingBase::pc_m.
Referenced by FlatTop::countEnteringParticlesPerRank(), FromFile::generateParticles(), generateParticles(), and MultiVariateGaussian::generateParticles().
emitParticles()
void Gaussian::emitParticles (double t, double dt) override virtual
Time-stepped emission hook for one-shot delayed injection.
For GAUSS, this emits once when [t, t+dt] crosses t0 for sources with t0 > 0. Initial sampling at t0 == 0 is handled via generateParticles.
Reimplemented from SamplingBase.
Definition at line 185 of file Gaussian.cpp.
References generateParticles(), Distribution::getNumParticles(), SamplingBase::hasEmittedOnce_m, SamplingBase::opalDist_m, SamplingBase::pc_m, and SamplingBase::t0_m.
generateParticles()
void Gaussian::generateParticles (size_t & numberOfParticles, Vector_t< double, 3 > nr) override virtual
Generates particles with a Gaussian distribution.
Generates particles following a Gaussian distribution.
Parameters
numberOfParticles The total number of particles to generate.
nr the number of grid cells in R (used in domain decomposition).
numberOfParticles The total number of particles to generate.
nr The number of grid points in each dimension (not used here).
Reimplemented from SamplingBase.
Definition at line 64 of file Gaussian.cpp.
References avrgpz_m, SamplingBase::computeLocalEmitCount(), cutoffR_m, SamplingBase::emissionModel_m, fixMeanR_m, SamplingBase::hasEmittedOnce_m, SamplingBase::P0_m, SamplingBase::pc_m, SamplingBase::R0_m, randPool_m, samperTimer_m, sigmaP_m, sigmaR_m, and SamplingBase::t0_m.
Referenced by emitParticles(), TEST_F(), TEST_F(), and TEST_F().
getEmissionR0()
Vector_t< double, 3 > SamplingBase::getEmissionR0 () const inline inherited
Definition at line 52 of file SamplingBase.hpp.
References SamplingBase::R0_m.
getFixMeanR()
void Gaussian::getFixMeanR (bool & fixMeanR) const inline
Definition at line 116 of file Gaussian.h.
References fixMeanR_m.
getParameters()
void Gaussian::getParameters (Vector_t< double, 3 > & sigmaR, Vector_t< double, 3 > & sigmaP, double & avrgpz, Vector_t< double, 3 > & cutoffR) const inline
Definition at line 102 of file Gaussian.h.
References avrgpz_m, cutoffR_m, sigmaP_m, and sigmaR_m.
initDomainDecomp()
virtual void SamplingBase::initDomainDecomp (double) inline virtual inherited
Reimplemented in FlatTop.
Definition at line 71 of file SamplingBase.hpp.
initRandomPool()
void Gaussian::initRandomPool () private
Initializes the random number generator pool.
Definition at line 42 of file Gaussian.cpp.
References gmsg, randPool_m, and Options::seed.
Referenced by Gaussian(), and Gaussian().
isEmissionDone()
virtual bool SamplingBase::isEmissionDone (double t) const inline virtual inherited
Whether this sampler has finished all emission (no more particles will be created).
Parameters
t Current simulation time (s).
Reimplemented in FlatTop.
Definition at line 60 of file SamplingBase.hpp.
References SamplingBase::hasEmittedOnce_m.
setAvrgpz()
void Gaussian::setAvrgpz (double avrgpz) inline
Definition at line 94 of file Gaussian.h.
References avrgpz_m.
Referenced by Gaussian(), and Gaussian().
setCutoffR()
void Gaussian::setCutoffR (const Vector_t< double, 3 > & cutoffR) inline
Definition at line 98 of file Gaussian.h.
References cutoffR_m.
Referenced by Gaussian(), and Gaussian().
setEmissionOffsets()
void SamplingBase::setEmissionOffsets (ippl::Vector< double, 3 > R0, ippl::Vector< double, 3 > P0, double t0, const std::string & emissionModel = "NONE") inline inherited
Definition at line 43 of file SamplingBase.hpp.
References SamplingBase::emissionModel_m, SamplingBase::P0_m, SamplingBase::R0_m, and SamplingBase::t0_m.
setFixMeanR()
void Gaussian::setFixMeanR (bool fixMeanR) inline
Definition at line 112 of file Gaussian.h.
References fixMeanR_m.
Referenced by Gaussian().
setSigmaP()
void Gaussian::setSigmaP (const Vector_t< double, 3 > & sigmaP) inline
Definition at line 90 of file Gaussian.h.
References sigmaP_m.
Referenced by Gaussian(), and Gaussian().
setSigmaR()
void Gaussian::setSigmaR (const Vector_t< double, 3 > & sigmaR) inline
Definition at line 86 of file Gaussian.h.
References sigmaR_m.
Referenced by Gaussian(), and Gaussian().
setWithDomainDecomp()
virtual void SamplingBase::setWithDomainDecomp (bool) inline virtual inherited
Reimplemented in FlatTop.
Definition at line 73 of file SamplingBase.hpp.
testEmitParticles()
virtual void SamplingBase::testEmitParticles (size_t , double) inline virtual inherited
Definition at line 69 of file SamplingBase.hpp.
testNumEmitParticles()
virtual void SamplingBase::testNumEmitParticles (size_t , double) inline virtual inherited
Definition at line 66 of file SamplingBase.hpp.
Member Data Documentation
avrgpz_m
double Gaussian::avrgpz_m private
Average momentum in the z-direction.
Definition at line 140 of file Gaussian.h.
Referenced by generateParticles(), getParameters(), and setAvrgpz().
cutoffR_m
Vector_t<double, 3> Gaussian::cutoffR_m private
Cutoff multiplier for position distribution.
Definition at line 145 of file Gaussian.h.
Referenced by generateParticles(), getParameters(), and setCutoffR().
emissionModel_m
std::string SamplingBase::emissionModel_m = "NONE" protected inherited
Definition at line 25 of file SamplingBase.hpp.
Referenced by FromFile::generateParticles(), generateParticles(), MultiVariateGaussian::generateParticles(), FlatTop::generateUniformDisk(), and SamplingBase::setEmissionOffsets().
fc_m
std::shared_ptr<FieldContainer_t> SamplingBase::fc_m protected inherited
Definition at line 18 of file SamplingBase.hpp.
Referenced by FlatTop::initDomainDecomp(), and FlatTop::setParameters().
fixMeanR_m
bool Gaussian::fixMeanR_m = true private
Flag to exactly fix the mean position of particles after sampling.
Definition at line 150 of file Gaussian.h.
Referenced by generateParticles(), getFixMeanR(), and setFixMeanR().
hasEmittedOnce_m
bool SamplingBase::hasEmittedOnce_m = false protected inherited
For one-shot emitters (e.g. Gaussian at delayed t0): guard to avoid double sampling.
Definition at line 28 of file SamplingBase.hpp.
Referenced by FromFile::emitParticles(), emitParticles(), MultiVariateGaussian::emitParticles(), FromFile::generateParticles(), generateParticles(), MultiVariateGaussian::generateParticles(), and SamplingBase::isEmissionDone().
opalDist_m
Distribution_t* SamplingBase::opalDist_m protected inherited
Definition at line 19 of file SamplingBase.hpp.
Referenced by FromFile::emitParticles(), emitParticles(), MultiVariateGaussian::emitParticles(), MultiVariateGaussian::MultiVariateGaussian(), and FlatTop::setParameters().
P0_m
Vector_t<double, 3> SamplingBase::P0_m = 0.0 protected inherited
Definition at line 23 of file SamplingBase.hpp.
Referenced by FromFile::generateParticles(), generateParticles(), MultiVariateGaussian::generateParticles(), FlatTop::generateUniformDisk(), and SamplingBase::setEmissionOffsets().
pc_m
std::shared_ptr<ParticleContainer_t> SamplingBase::pc_m protected inherited
Definition at line 17 of file SamplingBase.hpp.
Referenced by SamplingBase::computeLocalEmitCount(), FlatTop::countEnteringParticlesPerRank(), FlatTop::emitParticles(), FromFile::emitParticles(), emitParticles(), MultiVariateGaussian::emitParticles(), FromFile::generateParticles(), generateParticles(), MultiVariateGaussian::generateParticles(), FlatTop::generateUniformDisk(), FlatTop::initDomainDecomp(), and FlatTop::testNumEmitParticles().
R0_m
Vector_t<double, 3> SamplingBase::R0_m = 0.0 protected inherited
Emission source offset: position R0, momentum P0, start time t0 (applied in sample step).
Definition at line 22 of file SamplingBase.hpp.
Referenced by FromFile::generateParticles(), generateParticles(), MultiVariateGaussian::generateParticles(), FlatTop::generateUniformDisk(), SamplingBase::getEmissionR0(), and SamplingBase::setEmissionOffsets().
randPool_m
GeneratorPool Gaussian::randPool_m private
Pool of random number generators for parallel sampling.
Definition at line 129 of file Gaussian.h.
Referenced by generateParticles(), and initRandomPool().
samperTimer_m
IpplTimings::TimerRef Gaussian::samperTimer_m
Timer for performance profiling.
Definition at line 43 of file Gaussian.h.
Referenced by Gaussian(), Gaussian(), and generateParticles().
samplingMethod_m
std::string SamplingBase::samplingMethod_m protected inherited
Definition at line 20 of file SamplingBase.hpp.
sigmaP_m
Vector_t<double, 3> Gaussian::sigmaP_m private
Definition at line 135 of file Gaussian.h.
Referenced by generateParticles(), getParameters(), and setSigmaP().
sigmaR_m
Vector_t<double, 3> Gaussian::sigmaR_m private
Standard deviations for position and momentum distributions.
Definition at line 134 of file Gaussian.h.
Referenced by generateParticles(), getParameters(), and setSigmaR().
t0_m
double SamplingBase::t0_m = 0.0 protected inherited
Definition at line 24 of file SamplingBase.hpp.
Referenced by FlatTop::emitParticles(), FromFile::emitParticles(), emitParticles(), MultiVariateGaussian::emitParticles(), FromFile::generateParticles(), generateParticles(), MultiVariateGaussian::generateParticles(), FlatTop::isEmissionDone(), and SamplingBase::setEmissionOffsets().
The documentation for this class was generated from the following files:
Gaussian.h
Gaussian.cpp