OPALX (Object Oriented Parallel Accelerator Library for Exascal): SupportPlacement Class Reference
SupportPlacement Class Reference
Optional offset from the canonical body frame to the support frame.
#include <SupportPlacement.h>
Public Member Functions
SupportPlacement ()=default
SupportPlacement (const CoordinateSystemTrafo &bodyToSupport)
const CoordinateSystemTrafo & getBodyToSupport () const
Private Attributes
CoordinateSystemTrafo bodyToSupport_m
Detailed Description
Optional offset from the canonical body frame to the support frame.
This is the bridge to the document's distinction between the canonical local chart and the support region \(\Omega_i\) on which field, aperture, or material data are defined. The first redesign stage keeps this as a rigid body-to-support transform.
Definition at line 15 of file SupportPlacement.h.
Constructor & Destructor Documentation
SupportPlacement() [1/2]
SupportPlacement::SupportPlacement () default
SupportPlacement() [2/2]
SupportPlacement::SupportPlacement (const CoordinateSystemTrafo & bodyToSupport) inline explicit
Definition at line 18 of file SupportPlacement.h.
Member Function Documentation
getBodyToSupport()
const CoordinateSystemTrafo & SupportPlacement::getBodyToSupport () const inline
Definition at line 21 of file SupportPlacement.h.
References bodyToSupport_m.
Referenced by PlacedElement::getNominalSupportTransform(), PlacedElement::getSupportTransform(), and TEST_F().
Member Data Documentation
bodyToSupport_m
CoordinateSystemTrafo SupportPlacement::bodyToSupport_m private
Definition at line 24 of file SupportPlacement.h.
Referenced by getBodyToSupport().
The documentation for this class was generated from the following file:
SupportPlacement.h