OPALX (Object Oriented Parallel Accelerator Library for Exascal): DivideError Class Reference
DivideError Class Reference
Zero divide error.
#include <DivideError.h>
Public Member Functions
DivideError (const std::string &meth)
The usual constructor.
DivideError (const DivideError &)
virtual ~DivideError ()
virtual const std::string & what () const
Return the message string for the exception.
virtual const std::string & where () const
Return the name of the method or function which detected the exception.
Private Member Functions
DivideError ()
Private Attributes
const std::string message
const std::string method
Detailed Description
Zero divide error.
Definition at line 32 of file DivideError.h.
Constructor & Destructor Documentation
DivideError() [1/3]
DivideError::DivideError (const std::string & meth) explicit
The usual constructor.
Definition at line 26 of file DivideError.cpp.
References ArithmeticError::ArithmeticError(), and OpalException::method.
Referenced by DivideError().
DivideError() [2/3]
DivideError::DivideError (const DivideError & rhs)
Definition at line 28 of file DivideError.cpp.
References ArithmeticError::ArithmeticError(), and DivideError().
~DivideError()
DivideError::~DivideError () virtual
Definition at line 30 of file DivideError.cpp.
DivideError() [3/3]
DivideError::DivideError () private
Member Function Documentation
what()
const std::string & OpalException::what () const virtual inherited
Return the message string for the exception.
Definition at line 31 of file OpalException.cpp.
References message.
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), main(), OpalParser::readStatement(), OpalParser::run(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and TEST_F().
where()
const std::string & OpalException::where () const virtual inherited
Return the name of the method or function which detected the exception.
Definition at line 33 of file OpalException.cpp.
References method.
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), main(), OpalParser::run(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and TEST_F().
Member Data Documentation
message
const std::string OpalException::message private inherited
Definition at line 56 of file OpalException.h.
Referenced by OpalException(), OpalException(), and what().
method
const std::string OpalException::method private inherited
Definition at line 57 of file OpalException.h.
Referenced by DivideError::DivideError(), OpalException(), OpalException(), and where().
The documentation for this class was generated from the following files:
DivideError.h
DivideError.cpp