OPALX (Object Oriented Parallel Accelerator Library for Exascal): BinConfigWriter Class Reference
BinConfigWriter Class Reference
Helper to write binning configuration snapshots as a JSON array.
#include <BinConfigWriter.h>
Public Member Functions
BinConfigWriter (const std::string &fileName)
~BinConfigWriter ()
void writeEntry (long long step, double time, bool preMerge, const std::vector< std::size_t > &binCounts, const std::vector< double > &binWidths, double xMin)
Private Attributes
std::ofstream os_
bool first_
Detailed Description
Helper to write binning configuration snapshots as a JSON array.
The writer owns a single JSON file. On construction it opens the file in truncate mode and emits the opening '['. Each call to writeEntry appends a JSON object (with comma handling). The destructor closes the array and file.
Definition at line 34 of file BinConfigWriter.h.
Constructor & Destructor Documentation
BinConfigWriter()
BinConfigWriter::BinConfigWriter (const std::string & fileName) explicit
Definition at line 15 of file BinConfigWriter.cpp.
References first_, and os_.
~BinConfigWriter()
BinConfigWriter::~BinConfigWriter ()
Definition at line 30 of file BinConfigWriter.cpp.
References os_.
Member Function Documentation
writeEntry()
void BinConfigWriter::writeEntry (long long step, double time, bool preMerge, const std::vector< std::size_t > & binCounts, const std::vector< double > & binWidths, double xMin)
Definition at line 39 of file BinConfigWriter.cpp.
References first_, and os_.
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
Member Data Documentation
first_
bool BinConfigWriter::first_ private
Definition at line 46 of file BinConfigWriter.h.
Referenced by BinConfigWriter(), and writeEntry().
os_
std::ofstream BinConfigWriter::os_ private
Definition at line 45 of file BinConfigWriter.h.
Referenced by BinConfigWriter(), writeEntry(), and ~BinConfigWriter().
The documentation for this class was generated from the following files:
BinConfigWriter.h
BinConfigWriter.cpp