OPALX (Object Oriented Parallel Accelerator Library for Exascal): RBendRep Class Reference
RBendRep Class Reference
Concrete OPALX representation of an analytic rectangular bend.
#include <RBendRep.h>
Public Member Functions
RBendRep ()
RBendRep (const std::string &name)
RBendRep (const RBendRep &)
~RBendRep () override
ElementBase * clone () const override
Return clone.
Channel * getChannel (const std::string &aKey, bool create=false) override
Construct a read/write channel.
BMultipoleField & getField () override
Return field.
const BMultipoleField & getField () const override
Return field.
RBendGeometry & getGeometry () override
Get geometry.
const RBendGeometry & getGeometry () const override
Get geometry.
void setField (const BMultipoleField &field)
void accept (BeamlineVisitor &visitor) const override
Apply visitor.
ElementType getType () const override
Get element type std::string.
double getExitAngle () const override
bool bends () const override
void initialise (PartBunch_t *bunch, double &startField, double &endField) override
void finalise () override
bool apply (const std::shared_ptr< ParticleContainer_t > &pc) override
Apply to all particles. Kernel launch moved inside the function.
bool apply (const size_t &i, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
Apply to particle i.
bool apply (const Vector_t< double, 3 > &R, const Vector_t< double, 3 > &P, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
Apply to particle with position R and momentum P.
bool applyToReferenceParticle (const Vector_t< double, 3 > &R, const Vector_t< double, 3 > &P, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
Apply to reference particle with position R and momemtum P.
void getFieldExtend (double &zBegin, double &zEnd) const override
Return the field-support extent of the component.
bool isInside (const Vector_t< double, 3 > &r) const override
CoordinateSystemTrafo getEdgeToBegin () const override
CoordinateSystemTrafo getEdgeToEnd () const override
void setLength (double length)
Set the nominal body length.
double getLength () const
double getChordLength () const
Return the geometric chord between entrance and exit frames.
virtual void setBendAngle (double angle)
double getBendAngle () const
virtual void setEntranceAngle (double entranceAngle)
double getEntranceAngle () const
virtual void setExitAngle (double exitAngle)
void setFullGap (double gap)
double getFullGap () const
void setDesignEnergy (const double &energy, bool changeable=true) override
double getDesignEnergy () const override
std::vector< Vector_t< double, 3 > > getDesignPath (std::size_t minSamples=32) const
Sample the local curved reference path of the bend body.
void setFieldAmplitude (double k0, double k0s)
Store the dipole design amplitudes used by the analytic field.
double getFieldAmplitude () const
void setFieldMapFN (std::string fileName)
std::string getFieldMapFN () const
double getB () const
void setB (double B)
void setEntryFaceRotation (double rotation)
double getEntryFaceRotation () const
void setExitFaceRotation (double rotation)
double getExitFaceRotation () const
void setEntryFaceCurvature (double curvature)
double getEntryFaceCurvature () const
void setExitFaceCurvature (double curvature)
double getExitFaceCurvature () const
void setSlices (double slices)
double getSlices () const
void setStepsize (double stepSize)
double getStepsize () const
void setNSlices (const std::size_t &nSlices)
std::size_t getNSlices () const
void setK1 (double k1)
double getK1 () const
int getRequiredNumberOfTimeSteps () const override
EVector Efield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool getPotential (const Vector_t< double, 3 > &, const double &, Vector_t< double, 3 > &, double &)
Calculate the four-potential at some position relative to the component.
virtual void goOnline (const double &kineticEnergy)
virtual void goOffline ()
virtual bool Online ()
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunch_t &bunch, const PartData &, bool revBeam, bool revTrack) const
Track a borrowed particle bunch through a non-standard component.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
Return the nominal body extent of the element.
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual Port getEntryPort () const
Return the entrance port of the canonical local chart.
virtual Port getBodyPort () const
Return the body port of the canonical local chart.
virtual Port getExitPort () const
Return the exit port of the canonical local chart.
PlacementPose getPlacementPose () const
Return the nominal rigid placement transform of the element.
void setPlacementPose (const PlacementPose &pose)
Set the nominal rigid placement transform of the element.
Misalignment getPlacementMisalignment () const
Return the local nominal-to-actual correction stored for the element.
ElementGeometry getPlacementGeometry () const
Return the bridge geometry ports assembled from legacy edge state.
SupportPlacement getPlacementSupport () const
Return the support-frame bridge object. The default is the body frame.
PlacedElement getPlacedElement () const
Return a placed-element view assembled from the current bridge objects.
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Static Public Member Functions
static std::string getTypeString (ElementType type)
Protected Member Functions
double calcDesignRadius (double fieldAmplitude) const
double calcDesignRadius (double chordLength, double angle) const
double calcFieldAmplitude (double radius) const
double calcBendAngle (double chordLength, double radius) const
double calcGamma () const
double calcBetaGamma () const
double getStoredExitAngle () const
bool isInsideTransverse (const Vector_t< double, 3 > &r) const
Protected Attributes
double exit_face_slope_m
PartBunch_t * RefPartBunch_m
bool online_m
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes
static const std::vector< double > defaultAperture_m = std::vector<double>({1e6, 1e6, 1.0})
Static Private Member Functions
static void computeFieldHost (const Vector_t< double, 3 > &R, const BMultipoleField &field, Vector_t< double, 3 > &B)
Private Attributes
RBendGeometry geometry_m
BMultipoleField field_m
double startField_m
double endField_m
double angle_m
double entranceAngle_m
double exitAngle_m
double gap_m
double designEnergy_m
bool designEnergyChangeable_m
double fieldAmplitudeX_m
double fieldAmplitudeY_m
double fieldAmplitude_m
std::string fileName_m
double entryFaceRotation_m
double exitFaceRotation_m
double entryFaceCurvature_m
double exitFaceCurvature_m
double slices_m
double stepSize_m
std::size_t nSlices_m
double k1_m
std::string elementID
AttributeSet userAttribs
WakeFunction * wake_m
BoundaryGeometry * bgeometry_m
ParticleMatterInteractionHandler * parmatint_m
bool positionIsFixed
std::queue< std::pair< double, double > > actionRange_m
std::string outputfn_m
bool deleteOnTransverseExit_m = true
double elementPosition_m
ELEMEDGE attribute.
bool elemedgeSet_m
Static Private Attributes
static const std::map< ElementType, std::string > elementTypeToString_s
Detailed Description
Concrete OPALX representation of an analytic rectangular bend.
The representation owns the rectangular bend geometry and the local analytic multipole field expansion used by the first OPALX-native RBEND port.
Definition at line 13 of file RBendRep.h.
Constructor & Destructor Documentation
RBendRep() [1/3]
RBendRep::RBendRep ()
Definition at line 22 of file RBendRep.cpp.
References field_m, geometry_m, and RBend::RBend().
Referenced by clone(), and RBendRep().
RBendRep() [2/3]
RBendRep::RBendRep (const std::string & name) explicit
Definition at line 27 of file RBendRep.cpp.
References field_m, geometry_m, and RBend::RBend().
RBendRep() [3/3]
RBendRep::RBendRep (const RBendRep & right)
Definition at line 24 of file RBendRep.cpp.
References field_m, geometry_m, RBend::RBend(), and RBendRep().
~RBendRep()
RBendRep::~RBendRep () override default
Member Function Documentation
accept()
void RBend::accept (BeamlineVisitor & visitor) const override virtual inherited
Apply visitor.
Implements ElementBase.
Definition at line 13 of file RBend.cpp.
References BeamlineVisitor::visitRBend().
Referenced by TEST().
apply() [1/3]
bool BendBase::apply (const size_t & i, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual inherited
Apply to particle i.
Parameters
i Particle index
t Time
E Electric Field
B Magnetic Field
Returns
true if particle is out-of-bounds (lost), false otherwise
Reimplemented from Component.
Definition at line 147 of file BendBase.cpp.
References computeFieldHost(), getField(), ElementBase::getFlagDeleteOnTransverseExit(), isInside(), ElementBase::isInsideTransverse(), and Component::RefPartBunch_m.
apply() [2/3]
bool BendBase::apply (const std::shared_ptr< ParticleContainer_t > & pc) override virtual inherited
Apply to all particles. Kernel launch moved inside the function.
Apply functions apply the components electromagnetic field to the particles. They are called inside ParalleTracker::computeExternalFields()
Returns
true if particle is out-of-bounds (lost), false otherwise
true if particle is out-of-bounds (lost), false otherwise
Reimplemented from Component.
Definition at line 92 of file BendBase.cpp.
References ElementBase::getElementLength(), getField(), BMultipoleField::getNormalComponent(), BMultipoleField::getSkewComponent(), and BMultipoleField::order().
apply() [3/3]
bool BendBase::apply (const Vector_t< double, 3 > & R, const Vector_t< double, 3 > & P, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual inherited
Apply to particle with position R and momentum P.
Parameters
R Position
P Momentum
t Time
E Electric Field
B Magnetic Field
Returns
true if particle is out-of-bounds (lost), false otherwise
Reimplemented from Component.
Definition at line 164 of file BendBase.cpp.
References computeFieldHost(), getField(), ElementBase::getFlagDeleteOnTransverseExit(), isInside(), and ElementBase::isInsideTransverse().
applyToReferenceParticle()
bool BendBase::applyToReferenceParticle (const Vector_t< double, 3 > & R, const Vector_t< double, 3 > & P, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual inherited
Apply to reference particle with position R and momemtum P.
Parameters
R Position
P Momentum
t Time
E Electric Field
B Magnetic Field
Returns
true if particle is out-of-bounds (lost), false otherwise
Reimplemented from Component.
Definition at line 179 of file BendBase.cpp.
References computeFieldHost(), getField(), isInside(), and ElementBase::isInsideTransverse().
bends()
bool BendBase::bends () const inline override virtual inherited
Implements Component.
Definition at line 184 of file BendBase.h.
Bfield() [1/2]
BVector Component::Bfield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 234 of file Component.h.
References EMField::Bfield(), and getField().
Bfield() [2/2]
BVector Component::Bfield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 240 of file Component.h.
References EMField::Bfield(), and getField().
calcBendAngle()
double BendBase::calcBendAngle (double chordLength, double radius) const protected inherited
Definition at line 256 of file BendBase.cpp.
calcBetaGamma()
double BendBase::calcBetaGamma () const protected inherited
Definition at line 270 of file BendBase.cpp.
References calcGamma().
Referenced by calcDesignRadius(), and calcFieldAmplitude().
calcDesignRadius() [1/2]
double BendBase::calcDesignRadius (double chordLength, double angle) const protected inherited
Definition at line 260 of file BendBase.cpp.
calcDesignRadius() [2/2]
double BendBase::calcDesignRadius (double fieldAmplitude) const protected inherited
Definition at line 240 of file BendBase.cpp.
References Physics::c, calcBetaGamma(), and Component::RefPartBunch_m.
calcFieldAmplitude()
double BendBase::calcFieldAmplitude (double radius) const protected inherited
Definition at line 248 of file BendBase.cpp.
References Physics::c, calcBetaGamma(), and Component::RefPartBunch_m.
calcGamma()
double BendBase::calcGamma () const protected inherited
Definition at line 264 of file BendBase.cpp.
References designEnergy_m, and Component::RefPartBunch_m.
Referenced by calcBetaGamma().
clone()
ElementBase * RBendRep::clone () const override virtual
Return clone.
Implements ElementBase.
Definition at line 31 of file RBendRep.cpp.
References RBendRep().
computeFieldHost()
void BendBase::computeFieldHost (const Vector_t< double, 3 > & R, const BMultipoleField & field, Vector_t< double, 3 > & B) static private inherited
Definition at line 275 of file BendBase.cpp.
References BMultipoleField::getNormalComponent(), BMultipoleField::getSkewComponent(), and BMultipoleField::order().
Referenced by apply(), apply(), and applyToReferenceParticle().
copyStructure()
ElementBase * ElementBase::copyStructure () virtual inherited
Make a structural copy.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 193 of file ElementBase.cpp.
References clone(), ElementBase(), and isSharable().
Referenced by Sequence::copy(), Line::parse(), and SequenceParser::parseMember().
EBfield() [1/2]
EBVectors Component::EBfield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 244 of file Component.h.
References EMField::EBfield(), and getField().
EBfield() [2/2]
EBVectors Component::EBfield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 246 of file Component.h.
References EMField::EBfield(), and getField().
Efield() [1/2]
EVector Component::Efield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 232 of file Component.h.
References EMField::Efield(), and getField().
Efield() [2/2]
EVector Component::Efield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 236 of file Component.h.
References EMField::Efield(), and getField().
finalise()
void BendBase::finalise () override virtual inherited
Implements Component.
Definition at line 90 of file BendBase.cpp.
References Component::online_m.
fixPosition()
void ElementBase::fixPosition () inline inherited
Definition at line 596 of file ElementBase.h.
References positionIsFixed.
Referenced by OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
getAperture()
std::pair< ApertureType, std::vector< double > > ElementBase::getAperture () const inline inherited
Definition at line 581 of file ElementBase.h.
References aperture_m.
Referenced by MeshGenerator::add(), Solenoid::getSupportEnvelope(), and MeshGenerator::getTransverseSupport().
getArcLength()
double ElementBase::getArcLength () const inline virtual inherited
Get arc length.
Reimplemented in MarkerRep, TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 478 of file ElementBase.h.
References BGeometryBase::getArcLength(), and getGeometry().
Referenced by TBeamline< T >::getTransform().
getAttribute()
double ElementBase::getAttribute (const std::string & aKey) const virtual inherited
Get attribute value.
Definition at line 146 of file ElementBase.cpp.
References getConstChannel().
getB()
double BendBase::getB () const inline inherited
Definition at line 225 of file BendBase.h.
References getField(), and BMultipoleField::getNormalComponent().
getBendAngle()
double BendBase::getBendAngle () const inline inherited
Definition at line 192 of file BendBase.h.
References angle_m.
Referenced by OpalBeamline::compileCompatibilityPlacement(), RBend::getExitAngle(), and OpalBeamline::save3DLattice().
getBodyPort()
Port ElementBase::getBodyPort () const inline virtual inherited
Return the body port of the canonical local chart.
The body port \(p_{i,\mathrm{body}}\) is the identity port of the element's canonical local chart. Its rigid transform is therefore the identity element of \(SE(3)\) in the first redesign stage.
Definition at line 546 of file ElementBase.h.
Referenced by getPlacementGeometry(), and TEST_F().
getBoundaryGeometry()
BoundaryGeometry * ElementBase::getBoundaryGeometry () const inline virtual inherited
return the attached boundary geometrt object if there is any
Definition at line 512 of file ElementBase.h.
References bgeometry_m.
getBoundingBoxInLabCoords()
BoundingBox ElementBase::getBoundingBoxInLabCoords () const virtual inherited
Definition at line 263 of file ElementBase.cpp.
References csTrafoGlobal2Local_m, getEdgeToBegin(), and getEdgeToEnd().
getChannel()
Channel * RBendRep::getChannel (const std::string & aKey, bool create = false) override virtual
Construct a read/write channel.
Reimplemented from ElementBase.
Definition at line 33 of file RBendRep.cpp.
References ElementBase::getChannel().
getChordLength()
double BendBase::getChordLength () const inherited
Return the geometric chord between entrance and exit frames.
For sector bends this is shorter than the arc length, while for rectangular bends it equals the straight body length.
Definition at line 211 of file BendBase.cpp.
References ElementBase::getEntranceFrame(), ElementBase::getExitFrame(), Euclid3D::getVector(), Vector3D::getX(), Vector3D::getY(), and Vector3D::getZ().
Referenced by OpalBeamline::compileCompatibilityPlacement().
getConstChannel()
const ConstChannel * ElementBase::getConstChannel (const std::string & aKey) const virtual inherited
Construct a read-only channel.
Definition at line 185 of file ElementBase.cpp.
References ElementBase(), and getChannel().
Referenced by getAttribute(), and hasAttribute().
getCSTrafoGlobal2Local()
CoordinateSystemTrafo ElementBase::getCSTrafoGlobal2Local () const inline inherited
Definition at line 528 of file ElementBase.h.
References csTrafoGlobal2Local_m.
Referenced by getPlacementPose(), OpalRBend::update(), and OpalSBend::update().
getDesign()
const ElementBase & Component::getDesign () const virtual inherited
Return design element.
Definition at line 33 of file Component.cpp.
References ElementBase::ElementBase().
getDesignEnergy()
double BendBase::getDesignEnergy () const inline override virtual inherited
Reimplemented from Component.
Definition at line 211 of file BendBase.h.
References designEnergy_m.
getDesignPath()
std::vector< Vector_t< double, 3 > > BendBase::getDesignPath (std::size_t minSamples = 32) const inherited
Sample the local curved reference path of the bend body.
The returned points lie in the canonical local chart and can be mapped to lab space via the placed body transform. The sampling is uniform in the body parameter \(s\) between the entrance and exit frames.
Definition at line 220 of file BendBase.cpp.
References ElementBase::getEntrance(), ElementBase::getExit(), and ElementBase::getTransform().
Referenced by OpalBeamline::compileCompatibilityPlacement(), and OpalBeamline::save3DLattice().
getEdgeToBegin()
CoordinateSystemTrafo BendBase::getEdgeToBegin () const override virtual inherited
Reimplemented from ElementBase.
Definition at line 203 of file BendBase.cpp.
References ElementBase::getEntranceFrame().
getEdgeToEnd()
CoordinateSystemTrafo BendBase::getEdgeToEnd () const override virtual inherited
Reimplemented from ElementBase.
Definition at line 207 of file BendBase.cpp.
References ElementBase::getExitFrame().
getElementDimensions()
virtual void ElementBase::getElementDimensions (double & begin, double & end) const inline virtual inherited
Return the nominal body extent of the element.
The first placement redesign stage distinguishes between the nominal body extent and the field-support extent. The body extent is the canonical longitudinal interval of the placed hardware, \([z_\mathrm{body}^{\mathrm{begin}}, z_\mathrm{body}^{\mathrm{end}}]\), and therefore drives ports, placement, and visualization. By default it coincides with the geometry length \([0, L]\) in the local chart.
Reimplemented in RFCavity, Solenoid, and TravelingWave.
Definition at line 177 of file ElementBase.h.
References getElementLength().
Referenced by MeshGenerator::add().
getElementLength()
double ElementBase::getElementLength () const inline virtual inherited
Get design length.
Reimplemented in MarkerRep, RFCavity, TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 480 of file ElementBase.h.
References BGeometryBase::getElementLength(), and getGeometry().
Referenced by MeshGenerator::add(), BendBase::apply(), Component::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Multipole::apply(), Multipole::apply(), Multipole::apply(), VariableRFCavity::apply(), VariableRFCavity::apply(), VariableRFCavity::apply(), Component::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), getEdgeToEnd(), Solenoid::getEdgeToEnd(), getElementDimensions(), Solenoid::getElementDimensions(), RFCavity::getElementLength(), BendBase::getFieldExtend(), ConstantEFieldCavity::getFieldExtend(), Corrector::getFieldExtend(), Drift::getFieldExtend(), Laser::getFieldExtend(), Multipole::getFieldExtend(), MultipoleT::getFieldExtend(), VariableRFCavity::getFieldExtend(), BendBase::getLength(), BendBase::initialise(), ConstantEFieldCavity::initialise(), Corrector::initialise(), Drift::initialise(), Laser::initialise(), Multipole::initialise(), BendBase::isInside(), isInside(), Monitor::isInside(), Multipole::isInside(), isInsideTransverse(), and TEST_F().
getElementPosition()
double ElementBase::getElementPosition () const inline inherited
Definition at line 617 of file ElementBase.h.
References elemedgeSet_m, elementPosition_m, and getName().
getEntrance()
double ElementBase::getEntrance () const inline virtual inherited
Get entrance position.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 486 of file ElementBase.h.
References BGeometryBase::getEntrance(), and getGeometry().
Referenced by BendBase::getDesignPath().
getEntranceAngle()
double BendBase::getEntranceAngle () const inline inherited
Definition at line 196 of file BendBase.h.
References entranceAngle_m.
Referenced by OpalBeamline::compileCompatibilityPlacement(), and RBend::getExitAngle().
getEntranceFrame()
Euclid3D ElementBase::getEntranceFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 498 of file ElementBase.h.
References BGeometryBase::getEntranceFrame(), and getGeometry().
Referenced by BendBase::getChordLength(), and BendBase::getEdgeToBegin().
getEntrancePatch()
Euclid3D ElementBase::getEntrancePatch () const inline virtual inherited
Get patch.
Definition at line 502 of file ElementBase.h.
References BGeometryBase::getEntrancePatch(), and getGeometry().
getEntryFaceCurvature()
double BendBase::getEntryFaceCurvature () const inline inherited
Definition at line 239 of file BendBase.h.
References entryFaceCurvature_m.
getEntryFaceRotation()
double BendBase::getEntryFaceRotation () const inline inherited
Definition at line 231 of file BendBase.h.
References entryFaceRotation_m.
getEntryPort()
Port ElementBase::getEntryPort () const inline virtual inherited
Return the entrance port of the canonical local chart.
In the placement-note language, this is the marked entrance port \(p_{i,\mathrm{entry}}\) of element \(i\). For straight elements in the bridge stage, the body-to-entry transform is taken from the legacy getEdgeToBegin() result.
Definition at line 544 of file ElementBase.h.
References getEdgeToBegin().
Referenced by getPlacementGeometry(), and TEST_F().
getExit()
double ElementBase::getExit () const inline virtual inherited
Get exit position.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 488 of file ElementBase.h.
References BGeometryBase::getExit(), and getGeometry().
Referenced by BendBase::getDesignPath().
getExitAngle()
double RBend::getExitAngle () const override virtual inherited
Implements BendBase.
Definition at line 17 of file RBend.cpp.
References BendBase::getBendAngle(), and BendBase::getEntranceAngle().
getExitFaceCurvature()
double BendBase::getExitFaceCurvature () const inline inherited
Definition at line 243 of file BendBase.h.
References exitFaceCurvature_m.
getExitFaceRotation()
double BendBase::getExitFaceRotation () const inline inherited
Definition at line 235 of file BendBase.h.
References exitFaceRotation_m.
getExitFrame()
Euclid3D ElementBase::getExitFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 500 of file ElementBase.h.
References BGeometryBase::getExitFrame(), and getGeometry().
Referenced by BendBase::getChordLength(), and BendBase::getEdgeToEnd().
getExitPatch()
Euclid3D ElementBase::getExitPatch () const inline virtual inherited
Get patch.
Definition at line 504 of file ElementBase.h.
References BGeometryBase::getExitPatch(), and getGeometry().
getExitPort()
Port ElementBase::getExitPort () const inline virtual inherited
Return the exit port of the canonical local chart.
In the placement-note language, this is the marked exit port \(p_{i,\mathrm{exit}}\). For straight elements in the bridge stage, the body-to-exit transform is taken from the legacy getEdgeToEnd() result.
Definition at line 548 of file ElementBase.h.
References getEdgeToEnd().
Referenced by getPlacementGeometry(), and TEST_F().
getField() [1/2]
const BMultipoleField & RBendRep::getField () const override virtual
Return field.
Implements BendBase.
Definition at line 45 of file RBendRep.cpp.
References field_m.
getField() [2/2]
BMultipoleField & RBendRep::getField () override virtual
Return field.
Implements BendBase.
Definition at line 43 of file RBendRep.cpp.
References field_m.
getFieldAmplitude()
double BendBase::getFieldAmplitude () const inline inherited
Definition at line 219 of file BendBase.h.
References fieldAmplitude_m.
getFieldExtend()
void BendBase::getFieldExtend (double & zBegin, double & zEnd) const override virtual inherited
Return the field-support extent of the component.
This is the longitudinal interval \([z_\mathrm{field}^{\mathrm{begin}}, z_\mathrm{field}^{\mathrm{end}}]\) on which the external field model is evaluated in the element-local chart. In the first extent model this may differ from the nominal body extent returned by getElementDimensions(), for example when fringe fields extend beyond the hardware body or when a field map occupies only part of the body.
Implements Component.
Definition at line 194 of file BendBase.cpp.
References ElementBase::getElementLength().
getFieldMapFN()
std::string BendBase::getFieldMapFN () const inline inherited
Definition at line 223 of file BendBase.h.
References fileName_m.
getFlagDeleteOnTransverseExit()
bool ElementBase::getFlagDeleteOnTransverseExit () const inline inherited
Definition at line 633 of file ElementBase.h.
References deleteOnTransverseExit_m.
Referenced by BendBase::apply(), BendBase::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Multipole::apply(), Multipole::apply(), RFCavity::apply(), Solenoid::apply(), and TravelingWave::apply().
getFullGap()
double BendBase::getFullGap () const inline inherited
Definition at line 202 of file BendBase.h.
References gap_m.
getGeometry() [1/2]
const RBendGeometry & RBendRep::getGeometry () const override virtual
Get geometry.
Implements RBend.
Definition at line 49 of file RBendRep.cpp.
References geometry_m.
getGeometry() [2/2]
RBendGeometry & RBendRep::getGeometry () override virtual
Get geometry.
Implements RBend.
Definition at line 47 of file RBendRep.cpp.
References geometry_m.
Referenced by OpalRBend::update().
getK1()
double BendBase::getK1 () const inline inherited
Definition at line 259 of file BendBase.h.
References k1_m.
getLength()
double BendBase::getLength () const inline inherited
Definition at line 188 of file BendBase.h.
References ElementBase::getElementLength().
getMisalignment() [1/2]
CoordinateSystemTrafo ElementBase::getMisalignment () const inline inherited
Definition at line 592 of file ElementBase.h.
References misalignment_m.
Referenced by getPlacementMisalignment().
getMisalignment() [2/2]
void ElementBase::getMisalignment (double & x, double & y, double & s) const inherited
getName()
const std::string & ElementBase::getName () const virtual inherited
Get element name.
Definition at line 131 of file ElementBase.cpp.
References elementID.
Referenced by Ring::appendElement(), TBeamline< T >::clone(), TBeamline< T >::copyStructure(), Probe::doGoOffline(), PlaceRep::enter(), getElementPosition(), RFCavity::getMomentaKick(), getOutputFN(), CavityAutophaser::getPhaseAtMaxEnergy(), Selector::handleElement(), RFCavity::initialise(), Ring::initialise(), Solenoid::initialise(), PlaceRep::leave(), VariableRFCavity::operator=(), Sequence::print(), Ring::Ring(), BeamlineFieldElement::SortAsc(), TEST_F(), Component::trackBunch(), Component::trackMap(), OpalRBend::update(), OpalSBend::update(), Sequence::updateList(), ParallelTracker::updateRFElement(), and Replacer::visitFlaggedElmPtr().
getNSlices()
std::size_t BendBase::getNSlices () const inline inherited
Definition at line 255 of file BendBase.h.
References nSlices_m.
getOrigin()
double ElementBase::getOrigin () const inline virtual inherited
Get origin position.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 484 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getOrigin().
getOutputFN()
std::string ElementBase::getOutputFN () const inherited
Get output filename.
Definition at line 137 of file ElementBase.cpp.
References getName(), and outputfn_m.
Referenced by Probe::doInitialise(), Monitor::initialise(), and PluginElement::initialise().
getParticleMatterInteraction()
ParticleMatterInteractionHandler * ElementBase::getParticleMatterInteraction () const inline virtual inherited
Definition at line 516 of file ElementBase.h.
References parmatint_m.
getPlacedElement()
PlacedElement ElementBase::getPlacedElement () const inline inherited
Return a placed-element view assembled from the current bridge objects.
Definition at line 570 of file ElementBase.h.
References getPlacementGeometry(), getPlacementMisalignment(), getPlacementPose(), and getPlacementSupport().
Referenced by MeshGenerator::add(), and TEST_F().
getPlacementGeometry()
ElementGeometry ElementBase::getPlacementGeometry () const inline inherited
Return the bridge geometry ports assembled from legacy edge state.
The first redesign stage defines a minimal explicit port contract with three named body-relative ports: \(p_{i,\mathrm{entry}}\), \(p_{i,\mathrm{body}}\), \(p_{i,\mathrm{exit}}\). The default bridge preserves current OPALX behavior by deriving those ports from getEntryPort(), getBodyPort(), and getExitPort(), whose straight-element implementations are backed by the legacy getEdgeToBegin() and getEdgeToEnd() methods.
Definition at line 562 of file ElementBase.h.
References getBodyPort(), getEntryPort(), and getExitPort().
Referenced by getPlacedElement().
getPlacementMisalignment()
Misalignment ElementBase::getPlacementMisalignment () const inline inherited
Return the local nominal-to-actual correction stored for the element.
Definition at line 558 of file ElementBase.h.
References getMisalignment().
Referenced by getPlacedElement().
getPlacementPose()
PlacementPose ElementBase::getPlacementPose () const inline inherited
Return the nominal rigid placement transform of the element.
This is the bridge from the legacy stored CoordinateSystemTrafo to the new placement vocabulary. It preserves current nominal placement semantics and does not apply misalignment.
Definition at line 550 of file ElementBase.h.
References getCSTrafoGlobal2Local().
Referenced by getPlacedElement().
getPlacementSupport()
SupportPlacement ElementBase::getPlacementSupport () const inline inherited
Return the support-frame bridge object. The default is the body frame.
Definition at line 566 of file ElementBase.h.
Referenced by getPlacedElement().
getPotential()
virtual bool Component::getPotential (const Vector_t< double, 3 > & , const double & , Vector_t< double, 3 > & , double &) inline virtual inherited
Calculate the four-potential at some position relative to the component.
Parameters
R position in the local coordinate system of the component
t time
A filled with the calculated magnetic vector potential
phi filled with the calculated electric potential Note that any existing values in A and phi may be overwritten by this method.
Returns
true if particle is outside the field map, else false Default for component is to return false and make no change to A and phi
Definition at line 155 of file Component.h.
getRequiredNumberOfTimeSteps()
int BendBase::getRequiredNumberOfTimeSteps () const inline override virtual inherited
Reimplemented from ElementBase.
Definition at line 261 of file BendBase.h.
getRotationAboutZ()
double ElementBase::getRotationAboutZ () const inline inherited
Definition at line 608 of file ElementBase.h.
References rotationZAxis_m.
Referenced by OpalBeamline::compileCompatibilityPlacement().
getSlices()
double BendBase::getSlices () const inline inherited
Definition at line 247 of file BendBase.h.
References slices_m.
getStepsize()
double BendBase::getStepsize () const inline inherited
Definition at line 251 of file BendBase.h.
References stepSize_m.
getStoredExitAngle()
double BendBase::getStoredExitAngle () const inline protected inherited
Definition at line 263 of file BendBase.h.
References exitAngle_m.
Referenced by SBend::getExitAngle().
getTotalTransform()
Euclid3D ElementBase::getTotalTransform () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 494 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getTotalTransform().
getTransform() [1/2]
Euclid3D ElementBase::getTransform (double fromS, double toS) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 490 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getTransform().
Referenced by BendBase::getDesignPath(), and TBeamline< T >::getTransform().
getTransform() [2/2]
Euclid3D ElementBase::getTransform (double s) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 496 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getTransform().
getType()
ElementType RBend::getType () const override virtual inherited
Get element type std::string.
Reimplemented from Component.
Definition at line 15 of file RBend.cpp.
References RBEND.
getTypeString() [1/2]
std::string ElementBase::getTypeString () const inline inherited
Definition at line 610 of file ElementBase.h.
References getType(), and getTypeString().
Referenced by getTypeString().
getTypeString() [2/2]
std::string ElementBase::getTypeString (ElementType type) static inherited
Definition at line 191 of file ElementBase.cpp.
References elementTypeToString_s.
getWake()
WakeFunction * ElementBase::getWake () const inline virtual inherited
return the attached wake object if there is any
Definition at line 508 of file ElementBase.h.
References wake_m.
goOffline()
void Component::goOffline () virtual inherited
Reimplemented in Monitor, PluginElement, RFCavity, Solenoid, and TravelingWave.
Definition at line 45 of file Component.cpp.
References online_m.
goOnline()
void Component::goOnline (const double & kineticEnergy) virtual inherited
Reimplemented in Corrector, Monitor, RFCavity, Solenoid, and TravelingWave.
Definition at line 43 of file Component.cpp.
References online_m.
Referenced by PluginElement::initialise().
hasAttribute()
bool ElementBase::hasAttribute (const std::string & aKey) const virtual inherited
Test for existence of an attribute.
Definition at line 158 of file ElementBase.cpp.
References getConstChannel().
hasBoundaryGeometry()
bool ElementBase::hasBoundaryGeometry () const inline virtual inherited
Definition at line 514 of file ElementBase.h.
References bgeometry_m.
hasParticleMatterInteraction()
bool ElementBase::hasParticleMatterInteraction () const inline virtual inherited
Definition at line 520 of file ElementBase.h.
References parmatint_m.
hasWake()
bool ElementBase::hasWake () const inline virtual inherited
Definition at line 510 of file ElementBase.h.
References wake_m.
initialise()
void BendBase::initialise (PartBunch_t * bunch, double & startField, double & endField) override virtual inherited
Implements Component.
Definition at line 82 of file BendBase.cpp.
References endField_m, ElementBase::getElementLength(), Component::online_m, Component::RefPartBunch_m, and startField_m.
isElementPositionSet()
bool ElementBase::isElementPositionSet () const inline inherited
Definition at line 625 of file ElementBase.h.
References elemedgeSet_m.
isInside()
bool BendBase::isInside (const Vector_t< double, 3 > & r) const override virtual inherited
Reimplemented from ElementBase.
Definition at line 199 of file BendBase.cpp.
References ElementBase::getElementLength(), and ElementBase::isInsideTransverse().
Referenced by apply(), apply(), and applyToReferenceParticle().
isInsideTransverse()
bool ElementBase::isInsideTransverse (const Vector_t< double, 3 > & r) const protected inherited
Definition at line 232 of file ElementBase.cpp.
References aperture_m, CONIC_ELLIPTICAL, CONIC_RECTANGULAR, getEdgeToBegin(), getElementLength(), and CoordinateSystemTrafo::transformTo().
Referenced by BendBase::apply(), BendBase::apply(), Component::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Multipole::apply(), Multipole::apply(), BendBase::applyToReferenceParticle(), Component::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), BendBase::isInside(), isInside(), Monitor::isInside(), Multipole::isInside(), RFCavity::isInside(), Solenoid::isInside(), and TravelingWave::isInside().
isPositioned()
bool ElementBase::isPositioned () const inline inherited
Definition at line 598 of file ElementBase.h.
References positionIsFixed.
Referenced by OpalRBend::update(), and OpalSBend::update().
isSharable()
bool ElementBase::isSharable () const inline inherited
Test if the element can be shared.
Definition at line 506 of file ElementBase.h.
References shareFlag.
Referenced by copyStructure(), TBeamline< T >::copyStructure(), and Sequence::updateList().
makeSharable()
void ElementBase::makeSharable () virtual inherited
Set sharable flag.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 201 of file ElementBase.cpp.
References shareFlag.
Referenced by OpalMarker::OpalMarker().
Online()
bool Component::Online () virtual inherited
Definition at line 47 of file Component.cpp.
References online_m.
releasePosition()
void ElementBase::releasePosition () inline inherited
Definition at line 594 of file ElementBase.h.
References positionIsFixed.
Referenced by OpalRBend::update(), and OpalSBend::update().
removeAttribute()
void ElementBase::removeAttribute (const std::string & aKey) virtual inherited
Remove an existing attribute.
Definition at line 169 of file ElementBase.cpp.
References userAttribs.
setActionRange()
void ElementBase::setActionRange (const std::queue< std::pair< double, double > > & range) inline inherited
Definition at line 600 of file ElementBase.h.
References actionRange_m, and elementEdge_m.
setAperture()
void ElementBase::setAperture (const ApertureType & type, const std::vector< double > & args) inline inherited
Definition at line 576 of file ElementBase.h.
References aperture_m.
Referenced by Component::Component(), TEST_F(), TEST_F(), TEST_F(), OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
setAttribute()
void ElementBase::setAttribute (const std::string & aKey, double val) virtual inherited
Set value of an attribute.
Definition at line 171 of file ElementBase.cpp.
References getChannel(), and Channel::isSettable().
Referenced by update(), and OpalElement::updateUnknown().
setB()
void BendBase::setB (double B) inline inherited
Definition at line 227 of file BendBase.h.
References getField(), and BMultipoleField::setNormalComponent().
setBendAngle()
void BendBase::setBendAngle (double angle) inline virtual inherited
Definition at line 190 of file BendBase.h.
References angle_m.
Referenced by OpalRBend::update(), and OpalSBend::update().
setBoundaryGeometry()
void ElementBase::setBoundaryGeometry (BoundaryGeometry * geo) virtual inherited
attach a boundary geometry field to the element
Definition at line 215 of file ElementBase.cpp.
References bgeometry_m.
setCSTrafoGlobal2Local()
void ElementBase::setCSTrafoGlobal2Local (const CoordinateSystemTrafo & ori) inline inherited
Definition at line 522 of file ElementBase.h.
References csTrafoGlobal2Local_m, and positionIsFixed.
Referenced by setPlacementPose(), TEST_F(), OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
setCurrentSCoordinate()
void ElementBase::setCurrentSCoordinate (double s) inherited
Definition at line 223 of file ElementBase.cpp.
References actionRange_m, and elementEdge_m.
setDesignEnergy()
void BendBase::setDesignEnergy (const double & energy, bool changeable = true) inline override virtual inherited
Reimplemented from Component.
Definition at line 204 of file BendBase.h.
References designEnergy_m, and designEnergyChangeable_m.
Referenced by OpalRBend::update(), and OpalSBend::update().
setElementLength()
void ElementBase::setElementLength (double length) inline virtual inherited
Set design length.
Reimplemented in ConstantEFieldCavityRep, and MultipoleT.
Definition at line 482 of file ElementBase.h.
References getGeometry(), and BGeometryBase::setElementLength().
Referenced by MultipoleT::setElementLength(), BendBase::setLength(), SequenceMember::setLength(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), OpalCavity::update(), OpalMonitor::update(), OpalMultipole::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalSolenoid::update(), and OpalTravelingWave::update().
setElementPosition()
void ElementBase::setElementPosition (double elemedge) inline inherited
Access to ELEMEDGE attribute.
Definition at line 612 of file ElementBase.h.
References elemedgeSet_m, and elementPosition_m.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and OpalElement::update().
setEntranceAngle()
void BendBase::setEntranceAngle (double entranceAngle) inline virtual inherited
Definition at line 194 of file BendBase.h.
References entranceAngle_m.
Referenced by OpalRBend::update(), and OpalSBend::update().
setEntryFaceCurvature()
void BendBase::setEntryFaceCurvature (double curvature) inline inherited
Definition at line 237 of file BendBase.h.
References entryFaceCurvature_m.
Referenced by OpalRBend::update(), and OpalSBend::update().
setEntryFaceRotation()
void BendBase::setEntryFaceRotation (double rotation) inline inherited
Definition at line 229 of file BendBase.h.
References entryFaceRotation_m.
Referenced by OpalRBend::update(), and OpalSBend::update().
setExitAngle()
void BendBase::setExitAngle (double exitAngle) inline virtual inherited
Reimplemented in SBend.
Definition at line 198 of file BendBase.h.
References exitAngle_m.
Referenced by SBend::setExitAngle().
setExitFaceCurvature()
void BendBase::setExitFaceCurvature (double curvature) inline inherited
Definition at line 241 of file BendBase.h.
References exitFaceCurvature_m.
Referenced by OpalRBend::update(), and OpalSBend::update().
setExitFaceRotation()
void BendBase::setExitFaceRotation (double rotation) inline inherited
Definition at line 233 of file BendBase.h.
References exitFaceRotation_m.
Referenced by OpalRBend::update(), and OpalSBend::update().
setExitFaceSlope()
void Component::setExitFaceSlope (const double & m) inline inherited
Definition at line 250 of file Component.h.
References exit_face_slope_m.
setField()
void RBendRep::setField (const BMultipoleField & field)
Definition at line 51 of file RBendRep.cpp.
References field_m.
Referenced by OpalRBend::update().
setFieldAmplitude()
void BendBase::setFieldAmplitude (double k0, double k0s) inline inherited
Store the dipole design amplitudes used by the analytic field.
The normal and skew dipole strengths are the leading coefficients of the local multipole expansion
\[B_y + i B_x = \sum_{n=0}^{N} (B_n + i A_n) (x + i y)^n . \]
Definition at line 213 of file BendBase.h.
References fieldAmplitude_m, fieldAmplitudeX_m, and fieldAmplitudeY_m.
Referenced by OpalRBend::update(), and OpalSBend::update().
setFieldMapFN()
void BendBase::setFieldMapFN (std::string fileName) inline inherited
Definition at line 221 of file BendBase.h.
References fileName_m.
Referenced by OpalRBend::update(), and OpalSBend::update().
setFlagDeleteOnTransverseExit()
void ElementBase::setFlagDeleteOnTransverseExit (bool flag = true) inline inherited
Definition at line 629 of file ElementBase.h.
References deleteOnTransverseExit_m.
Referenced by OpalElement::update().
setFullGap()
void BendBase::setFullGap (double gap) inline inherited
Definition at line 200 of file BendBase.h.
References gap_m.
Referenced by OpalRBend::update(), and OpalSBend::update().
setK1()
void BendBase::setK1 (double k1) inline inherited
Definition at line 257 of file BendBase.h.
References k1_m.
Referenced by OpalRBend::update(), and OpalSBend::update().
setLength()
void BendBase::setLength (double length) inline inherited
Set the nominal body length.
The bend body length is the placed hardware length and therefore drives ports and visualization. The geometry itself remains the source of truth for the placed body extent.
Definition at line 186 of file BendBase.h.
References ElementBase::setElementLength().
Referenced by OpalRBend::update(), and OpalSBend::update().
setMisalignment()
void ElementBase::setMisalignment (const CoordinateSystemTrafo & cst) inline inherited
Definition at line 590 of file ElementBase.h.
References misalignment_m.
Referenced by TEST_F(), and OpalElement::update().
setName()
void ElementBase::setName (const std::string & name) virtual inherited
Set element name.
Definition at line 133 of file ElementBase.cpp.
References elementID.
Referenced by Sequence::insertDrifts(), and VariableRFCavity::operator=().
setNSlices()
void BendBase::setNSlices (const std::size_t & nSlices) inline inherited
Definition at line 253 of file BendBase.h.
References nSlices_m.
Referenced by OpalRBend::update(), and OpalSBend::update().
setOutputFN()
void ElementBase::setOutputFN (std::string fn) inherited
Set output filename.
Definition at line 135 of file ElementBase.cpp.
Referenced by OpalMonitor::update(), and OpalProbe::update().
setParticleMatterInteraction()
void ElementBase::setParticleMatterInteraction (ParticleMatterInteractionHandler * spys) virtual inherited
Definition at line 219 of file ElementBase.cpp.
References parmatint_m.
setPlacementPose()
void ElementBase::setPlacementPose (const PlacementPose & pose) inline inherited
Set the nominal rigid placement transform of the element.
This bridge setter preserves the existing storage model by delegating to setCSTrafoGlobal2Local().
Definition at line 554 of file ElementBase.h.
References PlacementPose::getParentToNominal(), and setCSTrafoGlobal2Local().
setRotationAboutZ()
void ElementBase::setRotationAboutZ (double rotation) inline inherited
Set rotation about z axis in bend frame.
Definition at line 606 of file ElementBase.h.
References rotationZAxis_m.
Referenced by OpalElement::update().
setSlices()
void BendBase::setSlices (double slices) inline inherited
Definition at line 245 of file BendBase.h.
References slices_m.
Referenced by OpalRBend::update(), and OpalSBend::update().
setStepsize()
void BendBase::setStepsize (double stepSize) inline inherited
Definition at line 249 of file BendBase.h.
References stepSize_m.
Referenced by OpalRBend::update(), and OpalSBend::update().
setWake()
void ElementBase::setWake (WakeFunction * wf) virtual inherited
attach a wake field to the element
Definition at line 211 of file ElementBase.cpp.
References wake_m.
trackBunch()
void Component::trackBunch (PartBunch_t & bunch, const PartData & , bool revBeam, bool revTrack) const virtual inherited
Track a borrowed particle bunch through a non-standard component.
The default implementation throws a LogicalError.
Parameters
bunch Particle bunch to track. The component does not take ownership.
Definition at line 35 of file Component.cpp.
References ElementBase::getName().
Referenced by Tracker::visitComponent().
trackMap()
void Component::trackMap (FVps< double, 6 > & map, const PartData & , bool revBeam, bool revTrack) const virtual inherited
Track a map.
Definition at line 39 of file Component.cpp.
References ElementBase::getName().
update()
bool ElementBase::update (const AttributeSet & set) inherited
Update element.
Definition at line 203 of file ElementBase.cpp.
References AttributeSet::begin(), AttributeSet::end(), and setAttribute().
Member Data Documentation
actionRange_m
std::queue<std::pair<double, double> > ElementBase::actionRange_m private inherited
Definition at line 468 of file ElementBase.h.
Referenced by setActionRange(), and setCurrentSCoordinate().
angle_m
double BendBase::angle_m private inherited
Definition at line 164 of file BendBase.h.
Referenced by BendBase(), BendBase(), getBendAngle(), and setBendAngle().
aperture_m
std::pair<ApertureType, std::vector<double> > ElementBase::aperture_m protected inherited
Definition at line 439 of file ElementBase.h.
Referenced by ElementBase(), getAperture(), isInsideTransverse(), and setAperture().
bgeometry_m
BoundaryGeometry* ElementBase::bgeometry_m private inherited
Definition at line 459 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getBoundaryGeometry(), hasBoundaryGeometry(), and setBoundaryGeometry().
csTrafoGlobal2Local_m
CoordinateSystemTrafo ElementBase::csTrafoGlobal2Local_m protected inherited
Definition at line 436 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getBoundingBoxInLabCoords(), getCSTrafoGlobal2Local(), and setCSTrafoGlobal2Local().
defaultAperture_m
const std::vector< double > Component::defaultAperture_m = std::vector<double>({1e6, 1e6, 1.0}) static protected inherited
Definition at line 221 of file Component.h.
Referenced by Component().
deleteOnTransverseExit_m
bool ElementBase::deleteOnTransverseExit_m = true private inherited
Definition at line 472 of file ElementBase.h.
Referenced by ElementBase(), getFlagDeleteOnTransverseExit(), and setFlagDeleteOnTransverseExit().
designEnergy_m
double BendBase::designEnergy_m private inherited
Definition at line 168 of file BendBase.h.
Referenced by BendBase(), BendBase(), calcGamma(), getDesignEnergy(), and setDesignEnergy().
designEnergyChangeable_m
bool BendBase::designEnergyChangeable_m private inherited
Definition at line 169 of file BendBase.h.
Referenced by BendBase(), BendBase(), and setDesignEnergy().
elemedgeSet_m
bool ElementBase::elemedgeSet_m private inherited
Definition at line 466 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getElementPosition(), isElementPositionSet(), and setElementPosition().
elementEdge_m
double ElementBase::elementEdge_m protected inherited
Definition at line 441 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), setActionRange(), and setCurrentSCoordinate().
elementID
std::string ElementBase::elementID private inherited
Definition at line 450 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getName(), and setName().
elementPosition_m
double ElementBase::elementPosition_m private inherited
ELEMEDGE attribute.
Definition at line 465 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getElementPosition(), and setElementPosition().
elementTypeToString_s
const std::map< ElementType, std::string > ElementBase::elementTypeToString_s static private inherited
Initial value:
= {
        {ElementType::ANY, "Any"},
        {ElementType::BEAMLINE, "Beamline"},
        {ElementType::DRIFT, "Drift"},
        {ElementType::LASER, "Laser"},
        {ElementType::MARKER, "Marker"},
        {ElementType::MULTIPOLE, "Multipole"},
        {ElementType::RFCAVITY, "RFCavity"},
        {ElementType::TRAVELINGWAVE, "TravelingWave"},
        {ElementType::SBEND, "SBEND"},
        {ElementType::RBEND, "RBEND"},
        {ElementType::RBEND3D, "RBEND3D"},
        {ElementType::RING, "Ring"},
        {ElementType::SOURCE, "SOURCE"},
        {ElementType::SOLENOID, "SOLENOID"},
        {ElementType::PROBE, "Probe"},
        {ElementType::VACUUM, "Vacuum"},
        {ElementType::CONSTANTEFIELDCAVITY, "ConstantEFieldCavity"}}
Definition at line 73 of file ElementBase.h.
Referenced by getTypeString().
endField_m
double BendBase::endField_m private inherited
Definition at line 163 of file BendBase.h.
Referenced by BendBase(), BendBase(), and initialise().
entranceAngle_m
double BendBase::entranceAngle_m private inherited
Definition at line 165 of file BendBase.h.
Referenced by BendBase(), BendBase(), getEntranceAngle(), and setEntranceAngle().
entryFaceCurvature_m
double BendBase::entryFaceCurvature_m private inherited
Definition at line 176 of file BendBase.h.
Referenced by BendBase(), BendBase(), getEntryFaceCurvature(), and setEntryFaceCurvature().
entryFaceRotation_m
double BendBase::entryFaceRotation_m private inherited
Definition at line 174 of file BendBase.h.
Referenced by BendBase(), BendBase(), getEntryFaceRotation(), and setEntryFaceRotation().
exit_face_slope_m
double Component::exit_face_slope_m protected inherited
Definition at line 222 of file Component.h.
Referenced by Component(), Component(), and setExitFaceSlope().
exitAngle_m
double BendBase::exitAngle_m private inherited
Definition at line 166 of file BendBase.h.
Referenced by BendBase(), BendBase(), getStoredExitAngle(), and setExitAngle().
exitFaceCurvature_m
double BendBase::exitFaceCurvature_m private inherited
Definition at line 177 of file BendBase.h.
Referenced by BendBase(), BendBase(), getExitFaceCurvature(), and setExitFaceCurvature().
exitFaceRotation_m
double BendBase::exitFaceRotation_m private inherited
Definition at line 175 of file BendBase.h.
Referenced by BendBase(), BendBase(), getExitFaceRotation(), and setExitFaceRotation().
field_m
BMultipoleField RBendRep::field_m private
Definition at line 33 of file RBendRep.h.
Referenced by getField(), getField(), RBendRep(), RBendRep(), RBendRep(), and setField().
fieldAmplitude_m
double BendBase::fieldAmplitude_m private inherited
Definition at line 172 of file BendBase.h.
Referenced by BendBase(), BendBase(), getFieldAmplitude(), and setFieldAmplitude().
fieldAmplitudeX_m
double BendBase::fieldAmplitudeX_m private inherited
Definition at line 170 of file BendBase.h.
Referenced by BendBase(), BendBase(), and setFieldAmplitude().
fieldAmplitudeY_m
double BendBase::fieldAmplitudeY_m private inherited
Definition at line 171 of file BendBase.h.
Referenced by BendBase(), BendBase(), and setFieldAmplitude().
fileName_m
std::string BendBase::fileName_m private inherited
Definition at line 173 of file BendBase.h.
Referenced by BendBase(), BendBase(), getFieldMapFN(), and setFieldMapFN().
gap_m
double BendBase::gap_m private inherited
Definition at line 167 of file BendBase.h.
Referenced by BendBase(), BendBase(), getFullGap(), and setFullGap().
geometry_m
RBendGeometry RBendRep::geometry_m private
Definition at line 32 of file RBendRep.h.
Referenced by getGeometry(), getGeometry(), RBendRep(), RBendRep(), and RBendRep().
k1_m
double BendBase::k1_m private inherited
Definition at line 181 of file BendBase.h.
Referenced by BendBase(), BendBase(), getK1(), and setK1().
misalignment_m
CoordinateSystemTrafo ElementBase::misalignment_m protected inherited
Definition at line 437 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getMisalignment(), and setMisalignment().
nSlices_m
std::size_t BendBase::nSlices_m private inherited
Definition at line 180 of file BendBase.h.
Referenced by BendBase(), BendBase(), getNSlices(), and setNSlices().
online_m
bool Component::online_m protected inherited
Definition at line 226 of file Component.h.
Referenced by Component(), Component(), Probe::doGoOffline(), BendBase::finalise(), Multipole::finalise(), PluginElement::finalise(), Ring::finalise(), goOffline(), PluginElement::goOffline(), RFCavity::goOffline(), Solenoid::goOffline(), goOnline(), Corrector::goOnline(), Monitor::goOnline(), RFCavity::goOnline(), Solenoid::goOnline(), TravelingWave::goOnline(), BendBase::initialise(), Multipole::initialise(), Ring::initialise(), Online(), and PluginElement::~PluginElement().
outputfn_m
std::string ElementBase::outputfn_m private inherited
The name of the outputfile
Definition at line 470 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), and getOutputFN().
parmatint_m
ParticleMatterInteractionHandler* ElementBase::parmatint_m private inherited
Definition at line 461 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getParticleMatterInteraction(), hasParticleMatterInteraction(), and setParticleMatterInteraction().
positionIsFixed
bool ElementBase::positionIsFixed private inherited
Definition at line 463 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), fixPosition(), isPositioned(), releasePosition(), and setCSTrafoGlobal2Local().
RefPartBunch_m
PartBunch_t* Component::RefPartBunch_m protected inherited
Definition at line 225 of file Component.h.
Referenced by BendBase::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Corrector::apply(), Multipole::apply(), MultipoleT::apply(), MultipoleT::apply(), RFCavity::apply(), RFCavity::apply(), Ring::apply(), ScalingFFAMagnet::apply(), Solenoid::apply(), TravelingWave::apply(), TravelingWave::apply(), VariableRFCavity::apply(), VariableRFCavity::apply(), VerticalFFAMagnet::apply(), BendBase::calcDesignRadius(), BendBase::calcFieldAmplitude(), BendBase::calcGamma(), Component(), MultipoleT::finalise(), ScalingFFAMagnet::finalise(), VariableRFCavity::finalise(), VerticalFFAMagnet::finalise(), Corrector::goOnline(), BendBase::initialise(), ConstantEFieldCavity::initialise(), Corrector::initialise(), Drift::initialise(), Laser::initialise(), Marker::initialise(), Monitor::initialise(), Multipole::initialise(), MultipoleT::initialise(), PluginElement::initialise(), RFCavity::initialise(), RFCavity::initialise(), ScalingFFAMagnet::initialise(), Solenoid::initialise(), TravelingWave::initialise(), VariableRFCavity::initialise(), VerticalFFAMagnet::initialise(), VariableRFCavity::initNull(), Multipole::isFocusing(), MultipoleT::MultipoleT(), ScalingFFAMagnet::ScalingFFAMagnet(), Corrector::setDesignEnergy(), Ring::setRefPartBunch(), RFCavity::trackOnAxisParticle(), and VerticalFFAMagnet::VerticalFFAMagnet().
rotationZAxis_m
double ElementBase::rotationZAxis_m protected inherited
Definition at line 443 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getRotationAboutZ(), and setRotationAboutZ().
shareFlag
bool ElementBase::shareFlag mutable protected inherited
Definition at line 434 of file ElementBase.h.
Referenced by Beamline::Beamline(), Beamline::Beamline(), Beamline::Beamline(), ElementBase(), ElementBase(), isSharable(), makeSharable(), and TBeamline< T >::makeSharable().
slices_m
double BendBase::slices_m private inherited
Definition at line 178 of file BendBase.h.
Referenced by BendBase(), BendBase(), getSlices(), and setSlices().
startField_m
double BendBase::startField_m private inherited
Definition at line 162 of file BendBase.h.
Referenced by BendBase(), BendBase(), and initialise().
stepSize_m
double BendBase::stepSize_m private inherited
Definition at line 179 of file BendBase.h.
Referenced by BendBase(), BendBase(), getStepsize(), and setStepsize().
userAttribs
AttributeSet ElementBase::userAttribs private inherited
Definition at line 455 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getChannel(), and removeAttribute().
wake_m
WakeFunction* ElementBase::wake_m private inherited
Definition at line 457 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getWake(), hasWake(), and setWake().
The documentation for this class was generated from the following files:
RBendRep.h
RBendRep.cpp