OPALX (Object Oriented Parallel Accelerator Library for Exascal): BCHandler< Dim > Class Template Reference
BCHandler< Dim > Class Template Reference
Handler for boundary conditions per spatial dimension.
#include <BCHandler.hpp>
Public Types
enum BCType { OPEN , PERIODIC , DIRICHLET }
Supported boundary condition types.
Public Member Functions
BCHandler (const BCHandler &other)=default
Defaulted copy constructor.
template<typename... Bcs>
BCHandler (Bcs... bcs)
Variadic constructor accepting exactly Dim BC values.
bool isAll (BCType bc_type) const
Return true if every stored BC equals bc_type.
bool isAllEqual () const
Check whether all stored BCs are equal (all the same value).
template<typename Field>
ippl::BConds< Field, Dim > toIPPLBConds () const
Static Public Member Functions
static BCType strToBCType (const std::string &str)
Convert a textual boundary-condition name to BCType enum.
Private Attributes
std::array< BCType, Dim > bcs_m
Internal storage of boundary conditions, one per dimension.
Friends
std::ostream & operator<< (std::ostream &os, const BCHandler &h)
Stream output helper for debugging and logging.
Detailed Description
template<unsigned Dim>
class BCHandler< Dim >
Handler for boundary conditions per spatial dimension.
BCHandler<Dim> stores a boundary-condition type for each of the Dim dimensions. It offers simple construction, string-to-enum parsing, and some basic functionality used in the field container environment.
Usage examples:
Construct for 3D: BCHandler<3> b(BCHandler<3>::OPEN, BCHandler<3>::PERIODIC, BCHandler<3>::OPEN);
More likely: construct from strToBCType, e.g. from FieldSolverCmd: BCH_t::strToBCType(Attributes::getString(itsAttr[FIELDSOLVER::BCFFTX]))
Template Parameters
Dim Number of spatial dimensions.
Note
This class is currently not designed to be used on device.
Examples
/Users/adelmann/git/physics-manual-opalx/.external/OPALX/src/PartBunch/BCHandler.hpp.
Definition at line 29 of file BCHandler.hpp.
Member Enumeration Documentation
BCType
template<unsigned Dim> enum BCHandler::BCType
Supported boundary condition types.
OPEN: non-periodic/open boundary.
PERIODIC: periodic boundary across the corresponding dimension.
DIRICHLET: fixed potential (zero for now) at the boundary.
Note
This enum needs to be updated should there be other supported BC types in the future (DIRICHLET!).
Enumerator
OPEN
PERIODIC
DIRICHLET
Examples
/Users/adelmann/git/physics-manual-opalx/.external/OPALX/src/PartBunch/BCHandler.hpp.
Definition at line 41 of file BCHandler.hpp.
Constructor & Destructor Documentation
BCHandler() [1/2]
template<unsigned Dim> BCHandler< Dim >::BCHandler (const BCHandler< Dim > & other) default
Defaulted copy constructor.
Examples
/Users/adelmann/git/physics-manual-opalx/.external/OPALX/src/PartBunch/BCHandler.hpp.
References BCHandler().
Referenced by BCHandler(), and operator<<.
BCHandler() [2/2]
template<unsigned Dim> template<typename... Bcs> BCHandler< Dim >::BCHandler (Bcs... bcs) inline
Variadic constructor accepting exactly Dim BC values.
Each argument should be convertible to BCType. The constructor validates that the number of provided BCs equals Dim and throws an OpalException otherwise.
Template Parameters
Bcs Variadic parameter pack type.
Parameters
bcs Boundary condition values for each dimension.
Exceptions
OpalException when the number of provided BCs != Dim.
Definition at line 85 of file BCHandler.hpp.
References bcs_m.
Member Function Documentation
isAll()
template<unsigned Dim> bool BCHandler< Dim >::isAll (BCType bc_type) const inline
Return true if every stored BC equals bc_type.
Parameters
bc_type Boundary condition value to compare against.
Returns
true if all dimensions have bc_type, otherwise false.
Examples
/Users/adelmann/git/physics-manual-opalx/.external/OPALX/src/PartBunch/BCHandler.hpp.
Definition at line 98 of file BCHandler.hpp.
References bcs_m, and Dim.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
isAllEqual()
template<unsigned Dim> bool BCHandler< Dim >::isAllEqual () const inline
Check whether all stored BCs are equal (all the same value).
This function is necesary, since current IPPL does not support mixed BCs, so this consistency check validates user input.
Returns
true when every element in the internal array equals the first element.
Examples
/Users/adelmann/git/physics-manual-opalx/.external/OPALX/src/PartBunch/BCHandler.hpp.
Definition at line 114 of file BCHandler.hpp.
References bcs_m, and Dim.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
strToBCType()
template<unsigned Dim> BCType BCHandler< Dim >::strToBCType (const std::string & str) inline static
Convert a textual boundary-condition name to BCType enum.
Currently recognised strings are "OPEN", "PERIODIC", and "DIRICHLET". The strings come from the pre-defined strings in the FieldSolverCmd class. If these don't match, you might get an exception during current FieldSolver construction.
Parameters
str Input string representing the boundary condition.
Returns
Corresponding BCType value.
Exceptions
OpalException if the string does not match an implemented BC type.
Examples
/Users/adelmann/git/physics-manual-opalx/.external/OPALX/src/PartBunch/BCHandler.hpp.
Definition at line 55 of file BCHandler.hpp.
References DIRICHLET, OPEN, and PERIODIC.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
toIPPLBConds()
template<unsigned Dim> template<typename Field> ippl::BConds< Field, Dim > BCHandler< Dim >::toIPPLBConds () const inline
Examples
/Users/adelmann/git/physics-manual-opalx/.external/OPALX/src/PartBunch/BCHandler.hpp.
Definition at line 179 of file BCHandler.hpp.
References bcs_m, Dim, DIRICHLET, OPEN, and PERIODIC.
Friends And Related Symbol Documentation
operator<<
template<unsigned Dim> std::ostream & operator<< (std::ostream & os, const BCHandler< Dim > & h) friend
Stream output helper for debugging and logging.
Produces a compact, human-readable representation such as: * BCHandler<3>: [OPEN, PERIODIC, OPEN].
Examples
/Users/adelmann/git/physics-manual-opalx/.external/OPALX/src/PartBunch/BCHandler.hpp.
Definition at line 128 of file BCHandler.hpp.
References BCHandler(), bcs_m, Dim, DIRICHLET, OPEN, and PERIODIC.
Member Data Documentation
bcs_m
template<unsigned Dim> std::array<BCType, Dim> BCHandler< Dim >::bcs_m private
Internal storage of boundary conditions, one per dimension.
Examples
/Users/adelmann/git/physics-manual-opalx/.external/OPALX/src/PartBunch/BCHandler.hpp.
Definition at line 202 of file BCHandler.hpp.
Referenced by BCHandler(), isAll(), isAllEqual(), operator<<, and toIPPLBConds().
The documentation for this class was generated from the following file:
BCHandler.hpp