OPALX (Object Oriented Parallel Accelerator Library for Exascal): ScalingFFAMagnet Class Reference
ScalingFFAMagnet Class Reference
#include <ScalingFFAMagnet.h>
Public Member Functions
ScalingFFAMagnet (const std::string &name)
~ScalingFFAMagnet ()
ScalingFFAMagnet * clone () const override
bool apply (const std::shared_ptr< ParticleContainer_t > &pc) override
bool apply (const size_t &i, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
Apply to particle i.
bool apply (const Vector_t< double, 3 > &R, const Vector_t< double, 3 > &P, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
bool getFieldValue (const Vector_t< double, 3 > &R, Vector_t< double, 3 > &B) const
bool getFieldValueCylindrical (const Vector_t< double, 3 > &R, Vector_t< double, 3 > &B) const
void initialise (PartBunch_t *bunch, double &startField, double &endField) override
void initialise ()
void finalise () override
bool bends () const override
void getFieldExtend (double &, double &) const override
BGeometryBase & getGeometry () override
const BGeometryBase & getGeometry () const override
EMField & getField () override
const EMField & getField () const override
void accept (BeamlineVisitor &visitor) const override
double getTanDelta () const
void setTanDelta (double tanDelta)
double getFieldIndex () const
void setFieldIndex (double k)
double getDipoleConstant () const
void setDipoleConstant (double Bz)
double getR0 () const
void setR0 (double r0)
Vector_t< double, 3 > getCentre () const
void setCentre (Vector_t< double, 3 > centre)
endfieldmodel::EndFieldModel * getEndField () const
void setEndField (endfieldmodel::EndFieldModel *endField)
size_t getMaxOrder () const
void setMaxOrder (size_t maxOrder)
double getPhiStart () const
void setPhiStart (double phiStart)
double getPhiEnd () const
void setPhiEnd (double phiEnd)
double getRMin () const
void setRMin (double rMin)
double getRMax () const
void setRMax (double rMax)
double getAzimuthalExtent () const
void setAzimuthalExtent (double azimuthalExtent)
double getVerticalExtent () const
void setVerticalExtent (double verticalExtent)
std::vector< std::vector< double > > getDfCoefficients ()
void setupEndField ()
void setEndFieldName (std::string name)
std::string getEndFieldName () const
EVector Efield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool applyToReferenceParticle (const Vector_t< double, 3 > &R, const Vector_t< double, 3 > &P, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B)
Apply to reference particle with position R and momemtum P.
virtual bool getPotential (const Vector_t< double, 3 > &, const double &, Vector_t< double, 3 > &, double &)
Calculate the four-potential at some position relative to the component.
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual void goOnline (const double &kineticEnergy)
virtual void goOffline ()
virtual bool Online ()
virtual ElementType getType () const
Get element type std::string.
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunch_t &bunch, const PartData &, bool revBeam, bool revTrack) const
Track a borrowed particle bunch through a non-standard component.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
Return the nominal body extent of the element.
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
virtual Port getEntryPort () const
Return the entrance port of the canonical local chart.
virtual Port getBodyPort () const
Return the body port of the canonical local chart.
virtual Port getExitPort () const
Return the exit port of the canonical local chart.
PlacementPose getPlacementPose () const
Return the nominal rigid placement transform of the element.
void setPlacementPose (const PlacementPose &pose)
Set the nominal rigid placement transform of the element.
Misalignment getPlacementMisalignment () const
Return the local nominal-to-actual correction stored for the element.
ElementGeometry getPlacementGeometry () const
Return the bridge geometry ports assembled from legacy edge state.
SupportPlacement getPlacementSupport () const
Return the support-frame bridge object. The default is the body frame.
PlacedElement getPlacedElement () const
Return a placed-element view assembled from the current bridge objects.
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t< double, 3 > &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Static Public Member Functions
static std::string getTypeString (ElementType type)
Protected Member Functions
bool isInsideTransverse (const Vector_t< double, 3 > &r) const
Protected Attributes
double exit_face_slope_m
PartBunch_t * RefPartBunch_m
bool online_m
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes
static const std::vector< double > defaultAperture_m = std::vector<double>({1e6, 1e6, 1.0})
Private Member Functions
void calculateDfCoefficients ()
ScalingFFAMagnet (const ScalingFFAMagnet &right)
ScalingFFAMagnet & operator= (const ScalingFFAMagnet &rhs)
Private Attributes
PlanarArcGeometry planarArcGeometry_m
BMultipoleField dummy
size_t maxOrder_m = 0
double tanDelta_m = 0.
double k_m = 0.
double Bz_m = 0.
double r0_m = 0.
double rMin_m = 0.
double rMax_m = 0.
double phiStart_m = 0.
double phiEnd_m = 0.
double azimuthalExtent_m = 0.
double verticalExtent_m = 0.
Vector_t< double, 3 > centre_m
endfieldmodel::EndFieldModel * endField_m = nullptr
std::string endFieldName_m = ""
const double fp_tolerance = 1e-18
std::vector< std::vector< double > > dfCoefficients_m
std::string elementID
AttributeSet userAttribs
WakeFunction * wake_m
BoundaryGeometry * bgeometry_m
ParticleMatterInteractionHandler * parmatint_m
bool positionIsFixed
std::queue< std::pair< double, double > > actionRange_m
std::string outputfn_m
bool deleteOnTransverseExit_m = true
double elementPosition_m
ELEMEDGE attribute.
bool elemedgeSet_m
Static Private Attributes
static const std::map< ElementType, std::string > elementTypeToString_s
Detailed Description
Sector bending magnet with an FFA-style field index and spiral end shape
Note about placement and end field; in order to get a user-defined end field shape, we do a lookup from user defined end fields, which is pulled from the EndFieldModel object and done by setupEndField(). Because end fields tie into the geometry, this has to be done before placements; but it also needs to be done after parsing has finished. setupEndField() is called by e.g. ParallelCyclotronTracker just before the object is handed to OpalRing for placement.
Definition at line 47 of file ScalingFFAMagnet.h.
Constructor & Destructor Documentation
ScalingFFAMagnet() [1/2]
ScalingFFAMagnet::ScalingFFAMagnet (const std::string & name) explicit
Construct a new ScalingFFAMagnet
Parameters
name User-defined name of the ScalingFFAMagnet
Definition at line 33 of file ScalingFFAMagnet.cpp.
~ScalingFFAMagnet()
ScalingFFAMagnet::~ScalingFFAMagnet ()
Destructor - deletes map
Definition at line 61 of file ScalingFFAMagnet.cpp.
References endField_m.
ScalingFFAMagnet() [2/2]
ScalingFFAMagnet::ScalingFFAMagnet (const ScalingFFAMagnet & right) private
Copy constructor
Definition at line 36 of file ScalingFFAMagnet.cpp.
References Bz_m, endfieldmodel::EndFieldModel::clone(), endField_m, r0_m, and Component::RefPartBunch_m.
Member Function Documentation
accept()
void ScalingFFAMagnet::accept (BeamlineVisitor & visitor) const override virtual
Accept a beamline visitor
Implements ElementBase.
Definition at line 102 of file ScalingFFAMagnet.cpp.
References BeamlineVisitor::visitScalingFFAMagnet().
apply() [1/3]
bool ScalingFFAMagnet::apply (const size_t & i, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual
Apply to particle i.
Parameters
i Particle index
t Time
E Electric Field
B Magnetic Field
Returns
true if particle is out-of-bounds (lost), false otherwise
Reimplemented from Component.
Definition at line 75 of file ScalingFFAMagnet.cpp.
References apply(), PartBunch< T, Dim >::R(), and Component::RefPartBunch_m.
apply() [2/3]
bool ScalingFFAMagnet::apply (const std::shared_ptr< ParticleContainer_t > & pc) override virtual
Calculate the field at the position of the ith particle
Parameters
i index of the particle event override; field is calculated at this position
t time at which the field is to be calculated
E calculated electric field - always 0 (no E-field)
B calculated magnetic field
Returns
true if particle is outside the field map
Reimplemented from Component.
Definition at line 73 of file ScalingFFAMagnet.cpp.
Referenced by apply().
apply() [3/3]
bool ScalingFFAMagnet::apply (const Vector_t< double, 3 > & R, const Vector_t< double, 3 > & P, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual
Calculate the field at some arbitrary position
Parameters
R position in the local coordinate system of the bend
P not used
t not used
E not used
B calculated magnetic field
Returns
true if particle is outside the field map, else false
Reimplemented from Component.
Definition at line 170 of file ScalingFFAMagnet.cpp.
References getFieldValue().
applyToReferenceParticle()
bool Component::applyToReferenceParticle (const Vector_t< double, 3 > & R, const Vector_t< double, 3 > & P, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) virtual inherited
Apply to reference particle with position R and momemtum P.
Parameters
R Position
P Momentum
t Time
E Electric Field
B Magnetic Field
Returns
true if particle is out-of-bounds (lost), false otherwise
Reimplemented in BendBase, ConstantEFieldCavity, Monitor, Multipole, PluginElement, RFCavity, Solenoid, TravelingWave, and VariableRFCavity.
Definition at line 114 of file Component.cpp.
References ElementBase::getElementLength(), and ElementBase::isInsideTransverse().
bends()
bool ScalingFFAMagnet::bends () const inline override virtual
Return true - ScalingFFAMagnet always bends the reference particle
Implements Component.
Definition at line 96 of file ScalingFFAMagnet.cpp.
Bfield() [1/2]
BVector Component::Bfield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 234 of file Component.h.
References EMField::Bfield(), and Component::getField().
Bfield() [2/2]
BVector Component::Bfield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 240 of file Component.h.
References EMField::Bfield(), and Component::getField().
calculateDfCoefficients()
void ScalingFFAMagnet::calculateDfCoefficients () private
Calculate the df coefficients, ready for field generation
Must be called following any update to the the field parameters, in order for correct field to be calculated.
Definition at line 176 of file ScalingFFAMagnet.cpp.
References dfCoefficients_m, k_m, maxOrder_m, and tanDelta_m.
Referenced by initialise().
clone()
ScalingFFAMagnet * ScalingFFAMagnet::clone () const override virtual
Inheritable copy constructor
Implements ElementBase.
Definition at line 63 of file ScalingFFAMagnet.cpp.
References initialise().
copyStructure()
ElementBase * ElementBase::copyStructure () virtual inherited
Make a structural copy.
Reimplemented in TBeamline< T >.
Definition at line 193 of file ElementBase.cpp.
References ElementBase::clone(), and ElementBase::isSharable().
Referenced by Sequence::copy(), Line::parse(), SequenceParser::parseMember(), and Replacer::visitFlaggedElmPtr().
EBfield() [1/2]
EBVectors Component::EBfield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 244 of file Component.h.
References EMField::EBfield(), and Component::getField().
EBfield() [2/2]
EBVectors Component::EBfield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 246 of file Component.h.
References EMField::EBfield(), and Component::getField().
Efield() [1/2]
EVector Component::Efield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 232 of file Component.h.
References EMField::Efield(), and Component::getField().
Efield() [2/2]
EVector Component::Efield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 236 of file Component.h.
References EMField::Efield(), and Component::getField().
finalise()
void ScalingFFAMagnet::finalise () override virtual
Finalise the ScalingFFAMagnet - sets bunch to nullptr
Implements Component.
Definition at line 94 of file ScalingFFAMagnet.cpp.
References Component::RefPartBunch_m.
fixPosition()
void ElementBase::fixPosition () inline inherited
Definition at line 596 of file ElementBase.h.
References ElementBase::positionIsFixed.
Referenced by OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
getAperture()
std::pair< ApertureType, std::vector< double > > ElementBase::getAperture () const inline inherited
Definition at line 581 of file ElementBase.h.
References ElementBase::aperture_m.
Referenced by MeshGenerator::add(), Solenoid::getSupportEnvelope(), and MeshGenerator::getTransverseSupport().
getArcLength()
double ElementBase::getArcLength () const inline virtual inherited
Get arc length.
Reimplemented in MarkerRep, and TBeamline< T >.
Definition at line 478 of file ElementBase.h.
References BGeometryBase::getArcLength(), and ElementBase::getGeometry().
Referenced by BeamlineGeometry::getArcLength(), and TBeamline< T >::getTransform().
getAttribute()
double ElementBase::getAttribute (const std::string & aKey) const virtual inherited
Get attribute value.
Definition at line 146 of file ElementBase.cpp.
References ElementBase::getConstChannel().
getAzimuthalExtent()
double ScalingFFAMagnet::getAzimuthalExtent () const inline
Get the maximum azimuthal displacement from \psi=0
Definition at line 231 of file ScalingFFAMagnet.h.
References azimuthalExtent_m.
getBodyPort()
Port ElementBase::getBodyPort () const inline virtual inherited
Return the body port of the canonical local chart.
The body port \(p_{i,\mathrm{body}}\) is the identity port of the element's canonical local chart. Its rigid transform is therefore the identity element of \(SE(3)\) in the first redesign stage.
Definition at line 546 of file ElementBase.h.
Referenced by ElementBase::getPlacementGeometry(), and TEST_F().
getBoundaryGeometry()
BoundaryGeometry * ElementBase::getBoundaryGeometry () const inline virtual inherited
return the attached boundary geometrt object if there is any
Definition at line 512 of file ElementBase.h.
References ElementBase::bgeometry_m.
getBoundingBoxInLabCoords()
BoundingBox ElementBase::getBoundingBoxInLabCoords () const virtual inherited
Definition at line 263 of file ElementBase.cpp.
References ElementBase::aperture_m, ElementBase::csTrafoGlobal2Local_m, BoundingBox::getBoundingBox(), ElementBase::getEdgeToBegin(), ElementBase::getEdgeToEnd(), and CoordinateSystemTrafo::transformFrom().
getCentre()
Vector_t< double, 3 > ScalingFFAMagnet::getCentre () const inline
Get the centre of the sector
Definition at line 170 of file ScalingFFAMagnet.h.
References centre_m.
getChannel()
Channel * ElementBase::getChannel (const std::string & aKey, bool create = false) virtual inherited
Construct a read/write channel.
Reimplemented in LaserRep, RBendRep, SBendRep, DriftRep, MonitorRep, MultipoleRep, ProbeRep, RFCavityRep, SolenoidRep, TravelingWaveRep, and ConstantEFieldCavityRep.
Definition at line 181 of file ElementBase.cpp.
References AttributeSet::getChannel(), and ElementBase::userAttribs.
Referenced by LaserRep::getChannel(), RBendRep::getChannel(), SBendRep::getChannel(), DriftRep::getChannel(), MonitorRep::getChannel(), MultipoleRep::getChannel(), ProbeRep::getChannel(), RFCavityRep::getChannel(), SolenoidRep::getChannel(), TravelingWaveRep::getChannel(), ConstantEFieldCavityRep::getChannel(), ElementBase::getConstChannel(), and ElementBase::setAttribute().
getConstChannel()
const ConstChannel * ElementBase::getConstChannel (const std::string & aKey) const virtual inherited
Construct a read-only channel.
Definition at line 185 of file ElementBase.cpp.
References ElementBase::getChannel().
Referenced by ElementBase::getAttribute(), and ElementBase::hasAttribute().
getCSTrafoGlobal2Local()
CoordinateSystemTrafo ElementBase::getCSTrafoGlobal2Local () const inline inherited
Definition at line 528 of file ElementBase.h.
References ElementBase::csTrafoGlobal2Local_m.
Referenced by ElementBase::getPlacementPose(), OpalRBend::update(), and OpalSBend::update().
getDesign()
const ElementBase & Component::getDesign () const virtual inherited
Return design element.
Definition at line 33 of file Component.cpp.
getDesignEnergy()
double Component::getDesignEnergy () const inline virtual inherited
Reimplemented in BendBase, and RFCavity.
Definition at line 254 of file Component.h.
getDfCoefficients()
std::vector< std::vector< double > > ScalingFFAMagnet::getDfCoefficients () inline
Return the calculated df coefficients
Definition at line 246 of file ScalingFFAMagnet.h.
References dfCoefficients_m.
getDipoleConstant()
double ScalingFFAMagnet::getDipoleConstant () const inline
Get the dipole constant B_0
Definition at line 158 of file ScalingFFAMagnet.h.
References Bz_m.
getEdgeToBegin()
CoordinateSystemTrafo ElementBase::getEdgeToBegin () const inline virtual inherited
Reimplemented in BendBase, RFCavity, Solenoid, and TravelingWave.
Definition at line 532 of file ElementBase.h.
Referenced by ElementBase::getBoundingBoxInLabCoords(), ElementBase::getEntryPort(), and ElementBase::isInsideTransverse().
getEdgeToEnd()
CoordinateSystemTrafo ElementBase::getEdgeToEnd () const inline virtual inherited
Reimplemented in BendBase, RFCavity, Solenoid, and TravelingWave.
Definition at line 537 of file ElementBase.h.
References ElementBase::getElementLength().
Referenced by ElementBase::getBoundingBoxInLabCoords(), and ElementBase::getExitPort().
getElementDimensions()
virtual void ElementBase::getElementDimensions (double & begin, double & end) const inline virtual inherited
Return the nominal body extent of the element.
The first placement redesign stage distinguishes between the nominal body extent and the field-support extent. The body extent is the canonical longitudinal interval of the placed hardware, \([z_\mathrm{body}^{\mathrm{begin}}, z_\mathrm{body}^{\mathrm{end}}]\), and therefore drives ports, placement, and visualization. By default it coincides with the geometry length \([0, L]\) in the local chart.
Reimplemented in RFCavity, TravelingWave, and Solenoid.
Definition at line 177 of file ElementBase.h.
References ElementBase::getElementLength().
Referenced by MeshGenerator::add().
getElementLength()
double ElementBase::getElementLength () const inline virtual inherited
Get design length.
Reimplemented in MarkerRep, TBeamline< T >, and RFCavity.
Definition at line 480 of file ElementBase.h.
References BGeometryBase::getElementLength(), and ElementBase::getGeometry().
Referenced by MeshGenerator::add(), ConstantEFieldCavity::apply(), Multipole::apply(), VariableRFCavity::apply(), BendBase::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), VariableRFCavity::apply(), Component::apply(), Corrector::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), VariableRFCavity::apply(), Component::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), ElementBase::getEdgeToEnd(), Solenoid::getEdgeToEnd(), ElementBase::getElementDimensions(), Solenoid::getElementDimensions(), BeamlineGeometry::getElementLength(), RFCavity::getElementLength(), Corrector::getFieldExtend(), BendBase::getFieldExtend(), ConstantEFieldCavity::getFieldExtend(), Drift::getFieldExtend(), Laser::getFieldExtend(), Multipole::getFieldExtend(), MultipoleT::getFieldExtend(), VariableRFCavity::getFieldExtend(), BendBase::getLength(), Corrector::initialise(), BendBase::initialise(), ConstantEFieldCavity::initialise(), Drift::initialise(), Laser::initialise(), Multipole::initialise(), ElementBase::isInside(), BendBase::isInside(), Monitor::isInside(), Multipole::isInside(), ElementBase::isInsideTransverse(), and TEST_F().
getElementPosition()
double ElementBase::getElementPosition () const inline inherited
Definition at line 617 of file ElementBase.h.
References ElementBase::elemedgeSet_m, ElementBase::elementPosition_m, and ElementBase::getName().
getEndField()
endfieldmodel::EndFieldModel * ScalingFFAMagnet::getEndField () const inline
Get the fringe field
Returns the fringe field model; ScalingFFAMagnet retains ownership of the returned memory.
Definition at line 180 of file ScalingFFAMagnet.h.
References endField_m.
getEndFieldName()
std::string ScalingFFAMagnet::getEndFieldName () const inline
Return the end field name.
Definition at line 266 of file ScalingFFAMagnet.h.
References endFieldName_m.
getEntrance()
double ElementBase::getEntrance () const inline virtual inherited
Get entrance position.
Reimplemented in TBeamline< T >.
Definition at line 486 of file ElementBase.h.
References BGeometryBase::getEntrance(), and ElementBase::getGeometry().
Referenced by BendBase::getDesignPath(), and BeamlineGeometry::getEntrance().
getEntranceFrame()
Euclid3D ElementBase::getEntranceFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 498 of file ElementBase.h.
References BGeometryBase::getEntranceFrame(), and ElementBase::getGeometry().
Referenced by BendBase::getChordLength(), BendBase::getEdgeToBegin(), and BeamlineGeometry::getEntranceFrame().
getEntrancePatch()
Euclid3D ElementBase::getEntrancePatch () const inline virtual inherited
Get patch.
Definition at line 502 of file ElementBase.h.
References BGeometryBase::getEntrancePatch(), and ElementBase::getGeometry().
getEntryPort()
Port ElementBase::getEntryPort () const inline virtual inherited
Return the entrance port of the canonical local chart.
In the placement-note language, this is the marked entrance port \(p_{i,\mathrm{entry}}\) of element \(i\). For straight elements in the bridge stage, the body-to-entry transform is taken from the legacy getEdgeToBegin() result.
Definition at line 544 of file ElementBase.h.
References ElementBase::getEdgeToBegin().
Referenced by ElementBase::getPlacementGeometry(), and TEST_F().
getExit()
double ElementBase::getExit () const inline virtual inherited
Get exit position.
Reimplemented in TBeamline< T >.
Definition at line 488 of file ElementBase.h.
References BGeometryBase::getExit(), and ElementBase::getGeometry().
Referenced by BendBase::getDesignPath(), and BeamlineGeometry::getExit().
getExitFrame()
Euclid3D ElementBase::getExitFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 500 of file ElementBase.h.
References BGeometryBase::getExitFrame(), and ElementBase::getGeometry().
Referenced by BendBase::getChordLength(), BendBase::getEdgeToEnd(), and BeamlineGeometry::getExitFrame().
getExitPatch()
Euclid3D ElementBase::getExitPatch () const inline virtual inherited
Get patch.
Definition at line 504 of file ElementBase.h.
References BGeometryBase::getExitPatch(), and ElementBase::getGeometry().
getExitPort()
Port ElementBase::getExitPort () const inline virtual inherited
Return the exit port of the canonical local chart.
In the placement-note language, this is the marked exit port \(p_{i,\mathrm{exit}}\). For straight elements in the bridge stage, the body-to-exit transform is taken from the legacy getEdgeToEnd() result.
Definition at line 548 of file ElementBase.h.
References ElementBase::getEdgeToEnd().
Referenced by ElementBase::getPlacementGeometry(), and TEST_F().
getField() [1/2]
const EMField & ScalingFFAMagnet::getField () const override virtual
Return a dummy (0.) field value (what is this for?)
Implements Component.
Definition at line 71 of file ScalingFFAMagnet.cpp.
References dummy.
getField() [2/2]
EMField & ScalingFFAMagnet::getField () override virtual
Return a dummy (0.) field value (what is this for?)
Implements Component.
Definition at line 69 of file ScalingFFAMagnet.cpp.
References dummy.
getFieldExtend()
void ScalingFFAMagnet::getFieldExtend (double & , double &) const inline override virtual
Not implemented
Implements Component.
Definition at line 128 of file ScalingFFAMagnet.h.
getFieldIndex()
double ScalingFFAMagnet::getFieldIndex () const inline
Get the field index k
Definition at line 152 of file ScalingFFAMagnet.h.
References k_m.
getFieldValue()
bool ScalingFFAMagnet::getFieldValue (const Vector_t< double, 3 > & R, Vector_t< double, 3 > & B) const
Calculate the field at some arbitrary position in cartesian coordinates
Parameters
R position in the local coordinate system of the bend, in cartesian coordinates defined like (x, y, z)
B calculated magnetic field defined like (Bx, By, Bz)
Returns
true if particle is outside the field map, else false
Definition at line 106 of file ScalingFFAMagnet.cpp.
References centre_m, and getFieldValueCylindrical().
Referenced by apply().
getFieldValueCylindrical()
bool ScalingFFAMagnet::getFieldValueCylindrical (const Vector_t< double, 3 > & R, Vector_t< double, 3 > & B) const
Calculate the field at some arbitrary position in cylindrical coordinates
Parameters
R position in the local coordinate system of the bend, in cylindrical polar coordinates defined like (r, y, phi)
B calculated magnetic field defined like (Br, By, Bphi)
Returns
true if particle is outside the field map, else false
Definition at line 121 of file ScalingFFAMagnet.cpp.
References azimuthalExtent_m, Bz_m, dfCoefficients_m, endField_m, endfieldmodel::EndFieldModel::function(), k_m, maxOrder_m, phiStart_m, r0_m, rMax_m, tanDelta_m, and verticalExtent_m.
Referenced by getFieldValue().
getFlagDeleteOnTransverseExit()
bool ElementBase::getFlagDeleteOnTransverseExit () const inline inherited
Definition at line 633 of file ElementBase.h.
References ElementBase::deleteOnTransverseExit_m.
Referenced by BendBase::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), Corrector::apply(), BendBase::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), RFCavity::apply(), Solenoid::apply(), and TravelingWave::apply().
getGeometry() [1/2]
const BGeometryBase & ScalingFFAMagnet::getGeometry () const override virtual
Return the cell geometry
Implements ElementBase.
Definition at line 100 of file ScalingFFAMagnet.cpp.
References planarArcGeometry_m.
getGeometry() [2/2]
BGeometryBase & ScalingFFAMagnet::getGeometry () override virtual
Return the cell geometry
Implements ElementBase.
Definition at line 98 of file ScalingFFAMagnet.cpp.
References planarArcGeometry_m.
getMaxOrder()
size_t ScalingFFAMagnet::getMaxOrder () const inline
Get the maximum power of y modelled in the off-midplane expansion;
Definition at line 191 of file ScalingFFAMagnet.h.
References maxOrder_m.
getMisalignment() [1/2]
CoordinateSystemTrafo ElementBase::getMisalignment () const inline inherited
Definition at line 592 of file ElementBase.h.
References ElementBase::misalignment_m.
Referenced by ElementBase::getPlacementMisalignment().
getMisalignment() [2/2]
void ElementBase::getMisalignment (double & x, double & y, double & s) const inherited
getName()
const std::string & ElementBase::getName () const virtual inherited
Get element name.
Definition at line 131 of file ElementBase.cpp.
References ElementBase::elementID.
Referenced by Ring::appendElement(), Probe::doGoOffline(), PlaceRep::enter(), ElementBase::getElementPosition(), RFCavity::getMomentaKick(), ElementBase::getOutputFN(), CavityAutophaser::getPhaseAtMaxEnergy(), Selector::handleElement(), Ring::initialise(), RFCavity::initialise(), Solenoid::initialise(), PlaceRep::leave(), VariableRFCavity::operator=(), Sequence::print(), TEST_F(), Component::trackBunch(), Component::trackMap(), OpalRBend::update(), OpalSBend::update(), Sequence::updateList(), ParallelTracker::updateRFElement(), and Replacer::visitFlaggedElmPtr().
getOrigin()
double ElementBase::getOrigin () const inline virtual inherited
Get origin position.
Reimplemented in TBeamline< T >.
Definition at line 484 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getOrigin().
Referenced by BeamlineGeometry::getOrigin().
getOutputFN()
std::string ElementBase::getOutputFN () const inherited
Get output filename.
Definition at line 137 of file ElementBase.cpp.
References ElementBase::getName(), and ElementBase::outputfn_m.
Referenced by Probe::doInitialise(), PluginElement::initialise(), and Monitor::initialise().
getParticleMatterInteraction()
ParticleMatterInteractionHandler * ElementBase::getParticleMatterInteraction () const inline virtual inherited
Definition at line 516 of file ElementBase.h.
References ElementBase::parmatint_m.
getPhiEnd()
double ScalingFFAMagnet::getPhiEnd () const inline
Get the offset of the magnet end from the start
Definition at line 207 of file ScalingFFAMagnet.h.
References phiEnd_m.
getPhiStart()
double ScalingFFAMagnet::getPhiStart () const inline
Get the offset of the magnet centre from the start
Definition at line 199 of file ScalingFFAMagnet.h.
References phiStart_m.
Referenced by setupEndField().
getPlacedElement()
PlacedElement ElementBase::getPlacedElement () const inline inherited
Return a placed-element view assembled from the current bridge objects.
Definition at line 570 of file ElementBase.h.
References ElementBase::getPlacementGeometry(), ElementBase::getPlacementMisalignment(), ElementBase::getPlacementPose(), and ElementBase::getPlacementSupport().
Referenced by MeshGenerator::add(), and TEST_F().
getPlacementGeometry()
ElementGeometry ElementBase::getPlacementGeometry () const inline inherited
Return the bridge geometry ports assembled from legacy edge state.
The first redesign stage defines a minimal explicit port contract with three named body-relative ports: \(p_{i,\mathrm{entry}}\), \(p_{i,\mathrm{body}}\), \(p_{i,\mathrm{exit}}\). The default bridge preserves current OPALX behavior by deriving those ports from getEntryPort(), getBodyPort(), and getExitPort(), whose straight-element implementations are backed by the legacy getEdgeToBegin() and getEdgeToEnd() methods.
Definition at line 562 of file ElementBase.h.
References ElementBase::getBodyPort(), ElementBase::getEntryPort(), and ElementBase::getExitPort().
Referenced by ElementBase::getPlacedElement().
getPlacementMisalignment()
Misalignment ElementBase::getPlacementMisalignment () const inline inherited
Return the local nominal-to-actual correction stored for the element.
Definition at line 558 of file ElementBase.h.
References ElementBase::getMisalignment().
Referenced by ElementBase::getPlacedElement().
getPlacementPose()
PlacementPose ElementBase::getPlacementPose () const inline inherited
Return the nominal rigid placement transform of the element.
This is the bridge from the legacy stored CoordinateSystemTrafo to the new placement vocabulary. It preserves current nominal placement semantics and does not apply misalignment.
Definition at line 550 of file ElementBase.h.
References ElementBase::getCSTrafoGlobal2Local().
Referenced by ElementBase::getPlacedElement().
getPlacementSupport()
SupportPlacement ElementBase::getPlacementSupport () const inline inherited
Return the support-frame bridge object. The default is the body frame.
Definition at line 566 of file ElementBase.h.
Referenced by ElementBase::getPlacedElement().
getPotential()
virtual bool Component::getPotential (const Vector_t< double, 3 > & , const double & , Vector_t< double, 3 > & , double &) inline virtual inherited
Calculate the four-potential at some position relative to the component.
Parameters
R position in the local coordinate system of the component
t time
A filled with the calculated magnetic vector potential
phi filled with the calculated electric potential Note that any existing values in A and phi may be overwritten by this method.
Returns
true if particle is outside the field map, else false Default for component is to return false and make no change to A and phi
Definition at line 155 of file Component.h.
getR0()
double ScalingFFAMagnet::getR0 () const inline
Get the radius constant R_0
Definition at line 164 of file ScalingFFAMagnet.h.
References r0_m.
Referenced by setupEndField().
getRequiredNumberOfTimeSteps()
int ElementBase::getRequiredNumberOfTimeSteps () const inline virtual inherited
Reimplemented in BendBase, Drift, Laser, Marker, and Monitor.
Definition at line 627 of file ElementBase.h.
getRMax()
double ScalingFFAMagnet::getRMax () const inline
Get the maximum radius
Definition at line 223 of file ScalingFFAMagnet.h.
References rMax_m.
getRMin()
double ScalingFFAMagnet::getRMin () const inline
Get the maximum radius
Definition at line 215 of file ScalingFFAMagnet.h.
References rMin_m.
getRotationAboutZ()
double ElementBase::getRotationAboutZ () const inline inherited
Definition at line 608 of file ElementBase.h.
References ElementBase::rotationZAxis_m.
Referenced by OpalBeamline::compileCompatibilityPlacement().
getTanDelta()
double ScalingFFAMagnet::getTanDelta () const inline
Get tan delta - delta is the spiral angle
Definition at line 146 of file ScalingFFAMagnet.h.
References tanDelta_m.
getTotalTransform()
Euclid3D ElementBase::getTotalTransform () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 494 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getTotalTransform().
Referenced by BeamlineGeometry::getTotalTransform().
getTransform() [1/2]
Euclid3D ElementBase::getTransform (double fromS, double toS) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 490 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getTransform().
Referenced by BendBase::getDesignPath(), BeamlineGeometry::getTransform(), TBeamline< T >::getTransform(), and BeamlineGeometry::getTransform().
getTransform() [2/2]
Euclid3D ElementBase::getTransform (double s) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 496 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getTransform().
getType()
ElementType Component::getType () const virtual inherited
Get element type std::string.
Implements ElementBase.
Reimplemented in Corrector, ConstantEFieldCavity, Drift, Laser, Marker, Monitor, Multipole, Probe, RBend, RFCavity, SBend, Solenoid, and TravelingWave.
Definition at line 49 of file Component.cpp.
References ANY.
Referenced by ParallelTracker::visitComponent().
getTypeString() [1/2]
std::string ElementBase::getTypeString () const inline inherited
Definition at line 610 of file ElementBase.h.
References ElementBase::getType(), and ElementBase::getTypeString().
Referenced by ElementBase::getTypeString().
getTypeString() [2/2]
std::string ElementBase::getTypeString (ElementType type) static inherited
Definition at line 191 of file ElementBase.cpp.
References ElementBase::elementTypeToString_s.
getVerticalExtent()
double ScalingFFAMagnet::getVerticalExtent () const inline
Get the maximum vertical displacement from the midplane
Definition at line 239 of file ScalingFFAMagnet.h.
References verticalExtent_m.
getWake()
WakeFunction * ElementBase::getWake () const inline virtual inherited
return the attached wake object if there is any
Definition at line 508 of file ElementBase.h.
References ElementBase::wake_m.
goOffline()
void Component::goOffline () virtual inherited
Reimplemented in PluginElement, Monitor, RFCavity, Solenoid, and TravelingWave.
Definition at line 45 of file Component.cpp.
References Component::online_m.
goOnline()
void Component::goOnline (const double & kineticEnergy) virtual inherited
Reimplemented in Corrector, Monitor, RFCavity, Solenoid, and TravelingWave.
Definition at line 43 of file Component.cpp.
References Component::online_m.
Referenced by PluginElement::initialise().
hasAttribute()
bool ElementBase::hasAttribute (const std::string & aKey) const virtual inherited
Test for existence of an attribute.
Definition at line 158 of file ElementBase.cpp.
References ElementBase::getConstChannel().
hasBoundaryGeometry()
bool ElementBase::hasBoundaryGeometry () const inline virtual inherited
Definition at line 514 of file ElementBase.h.
References ElementBase::bgeometry_m.
hasParticleMatterInteraction()
bool ElementBase::hasParticleMatterInteraction () const inline virtual inherited
Definition at line 520 of file ElementBase.h.
References ElementBase::parmatint_m.
hasWake()
bool ElementBase::hasWake () const inline virtual inherited
Definition at line 510 of file ElementBase.h.
References ElementBase::wake_m.
initialise() [1/2]
void ScalingFFAMagnet::initialise ()
Initialise the ScalingFFAMagnet
Sets up the field expansion and the geometry; call after changing any field parameters
Definition at line 86 of file ScalingFFAMagnet.cpp.
References calculateDfCoefficients().
Referenced by initialise().
initialise() [2/2]
void ScalingFFAMagnet::initialise (PartBunch_t * bunch, double & startField, double & endField) override virtual
Initialise the ScalingFFAMagnet
Parameters
bunch the global bunch object
startField not used
endField not used
Implements Component.
Definition at line 88 of file ScalingFFAMagnet.cpp.
References initialise(), and Component::RefPartBunch_m.
Referenced by clone().
isElementPositionSet()
bool ElementBase::isElementPositionSet () const inline inherited
Definition at line 625 of file ElementBase.h.
References ElementBase::elemedgeSet_m.
isInside()
bool ElementBase::isInside (const Vector_t< double, 3 > & r) const inline virtual inherited
Reimplemented in BendBase, Monitor, Multipole, RFCavity, Solenoid, and TravelingWave.
Definition at line 585 of file ElementBase.h.
References ElementBase::getElementLength(), and ElementBase::isInsideTransverse().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
isInsideTransverse()
bool ElementBase::isInsideTransverse (const Vector_t< double, 3 > & r) const protected inherited
Definition at line 232 of file ElementBase.cpp.
References ElementBase::aperture_m, CONIC_ELLIPTICAL, CONIC_RECTANGULAR, ELLIPTICAL, ElementBase::getEdgeToBegin(), ElementBase::getElementLength(), RECTANGULAR, and CoordinateSystemTrafo::transformTo().
Referenced by BendBase::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), Component::apply(), Corrector::apply(), BendBase::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), Component::applyToReferenceParticle(), BendBase::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), ElementBase::isInside(), BendBase::isInside(), Monitor::isInside(), Multipole::isInside(), RFCavity::isInside(), Solenoid::isInside(), and TravelingWave::isInside().
isPositioned()
bool ElementBase::isPositioned () const inline inherited
Definition at line 598 of file ElementBase.h.
References ElementBase::positionIsFixed.
Referenced by OpalRBend::update(), and OpalSBend::update().
isSharable()
bool ElementBase::isSharable () const inline inherited
Test if the element can be shared.
Definition at line 506 of file ElementBase.h.
References ElementBase::shareFlag.
Referenced by ElementBase::copyStructure(), and Sequence::updateList().
makeSharable()
void ElementBase::makeSharable () virtual inherited
Set sharable flag.
Reimplemented in TBeamline< T >.
Definition at line 201 of file ElementBase.cpp.
References ElementBase::shareFlag.
Referenced by OpalMarker::OpalMarker().
Online()
bool Component::Online () virtual inherited
Definition at line 47 of file Component.cpp.
References Component::online_m.
operator=()
ScalingFFAMagnet & ScalingFFAMagnet::operator= (const ScalingFFAMagnet & rhs) private
releasePosition()
void ElementBase::releasePosition () inline inherited
Definition at line 594 of file ElementBase.h.
References ElementBase::positionIsFixed.
Referenced by OpalRBend::update(), and OpalSBend::update().
removeAttribute()
void ElementBase::removeAttribute (const std::string & aKey) virtual inherited
Remove an existing attribute.
Definition at line 169 of file ElementBase.cpp.
References AttributeSet::removeAttribute(), and ElementBase::userAttribs.
setActionRange()
void ElementBase::setActionRange (const std::queue< std::pair< double, double > > & range) inline inherited
Definition at line 600 of file ElementBase.h.
References ElementBase::actionRange_m, and ElementBase::elementEdge_m.
setAperture()
void ElementBase::setAperture (const ApertureType & type, const std::vector< double > & args) inline inherited
Definition at line 576 of file ElementBase.h.
References ElementBase::aperture_m.
Referenced by Component::Component(), TEST_F(), TEST_F(), TEST_F(), OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
setAttribute()
void ElementBase::setAttribute (const std::string & aKey, double val) virtual inherited
Set value of an attribute.
Definition at line 171 of file ElementBase.cpp.
References ElementBase::getChannel(), and Channel::isSettable().
Referenced by ElementBase::update(), and OpalElement::updateUnknown().
setAzimuthalExtent()
void ScalingFFAMagnet::setAzimuthalExtent (double azimuthalExtent) inline
Set the maximum azimuthal displacement from \psi=0
Definition at line 235 of file ScalingFFAMagnet.h.
References azimuthalExtent_m.
Referenced by setupEndField().
setBoundaryGeometry()
void ElementBase::setBoundaryGeometry (BoundaryGeometry * geo) virtual inherited
attach a boundary geometry field to the element
Definition at line 215 of file ElementBase.cpp.
References ElementBase::bgeometry_m.
setCentre()
void ScalingFFAMagnet::setCentre (Vector_t< double, 3 > centre) inline
Set the centre of the sector
Definition at line 173 of file ScalingFFAMagnet.h.
References centre_m.
setCSTrafoGlobal2Local()
void ElementBase::setCSTrafoGlobal2Local (const CoordinateSystemTrafo & ori) inline inherited
Definition at line 522 of file ElementBase.h.
References ElementBase::csTrafoGlobal2Local_m, and ElementBase::positionIsFixed.
Referenced by ElementBase::setPlacementPose(), TEST_F(), OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
setCurrentSCoordinate()
void ElementBase::setCurrentSCoordinate (double s) inherited
Definition at line 223 of file ElementBase.cpp.
References ElementBase::actionRange_m, and ElementBase::elementEdge_m.
setDesignEnergy()
void Component::setDesignEnergy (const double & energy, bool changeable = true) inline virtual inherited
Reimplemented in Corrector, RFCavity, and BendBase.
Definition at line 252 of file Component.h.
setDipoleConstant()
void ScalingFFAMagnet::setDipoleConstant (double Bz) inline
Set the dipole constant B_0
Definition at line 161 of file ScalingFFAMagnet.h.
References Bz_m.
setElementLength()
void ElementBase::setElementLength (double length) inline virtual inherited
Set design length.
Reimplemented in MultipoleT, and ConstantEFieldCavityRep.
Definition at line 482 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::setElementLength().
Referenced by MultipoleT::setElementLength(), SequenceMember::setLength(), BendBase::setLength(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), OpalCavity::update(), OpalMonitor::update(), OpalMultipole::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalSolenoid::update(), and OpalTravelingWave::update().
setElementPosition()
void ElementBase::setElementPosition (double elemedge) inline inherited
Access to ELEMEDGE attribute.
Definition at line 612 of file ElementBase.h.
References ElementBase::elemedgeSet_m, and ElementBase::elementPosition_m.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and OpalElement::update().
setEndField()
void ScalingFFAMagnet::setEndField (endfieldmodel::EndFieldModel * endField)
Set the fringe field
endField: the new fringe field; ScalingFFAMagnet takes ownership of the memory associated with endField.
Definition at line 201 of file ScalingFFAMagnet.cpp.
References endField_m.
Referenced by setupEndField().
setEndFieldName()
void ScalingFFAMagnet::setEndFieldName (std::string name) inline
Set the end field name.
Called during parsing of the input file; OPAL looks for the endFieldName when setupEndField() is called.
Definition at line 263 of file ScalingFFAMagnet.h.
References endFieldName_m.
setExitFaceSlope()
void Component::setExitFaceSlope (const double & m) inline inherited
Definition at line 250 of file Component.h.
References Component::exit_face_slope_m.
setFieldIndex()
void ScalingFFAMagnet::setFieldIndex (double k) inline
Set the field index k
Definition at line 155 of file ScalingFFAMagnet.h.
References k_m.
setFlagDeleteOnTransverseExit()
void ElementBase::setFlagDeleteOnTransverseExit (bool flag = true) inline inherited
Definition at line 629 of file ElementBase.h.
References ElementBase::deleteOnTransverseExit_m.
Referenced by OpalElement::update().
setMaxOrder()
void ScalingFFAMagnet::setMaxOrder (size_t maxOrder) inline
Set the maximum power of y modelled in the off-midplane expansion;
Definition at line 195 of file ScalingFFAMagnet.h.
References maxOrder_m.
setMisalignment()
void ElementBase::setMisalignment (const CoordinateSystemTrafo & cst) inline inherited
Definition at line 590 of file ElementBase.h.
References ElementBase::misalignment_m.
Referenced by TEST_F(), and OpalElement::update().
setName()
void ElementBase::setName (const std::string & name) virtual inherited
Set element name.
Definition at line 133 of file ElementBase.cpp.
References ElementBase::elementID.
Referenced by Sequence::insertDrifts(), and VariableRFCavity::operator=().
setOutputFN()
void ElementBase::setOutputFN (std::string fn) inherited
Set output filename.
Definition at line 135 of file ElementBase.cpp.
References ElementBase::outputfn_m.
Referenced by OpalMonitor::update(), and OpalProbe::update().
setParticleMatterInteraction()
void ElementBase::setParticleMatterInteraction (ParticleMatterInteractionHandler * spys) virtual inherited
Definition at line 219 of file ElementBase.cpp.
References ElementBase::parmatint_m.
setPhiEnd()
void ScalingFFAMagnet::setPhiEnd (double phiEnd) inline
Set the offset of the magnet end from the start
Definition at line 211 of file ScalingFFAMagnet.h.
References phiEnd_m.
Referenced by setupEndField().
setPhiStart()
void ScalingFFAMagnet::setPhiStart (double phiStart) inline
Set the offset of the magnet centre from the start
Definition at line 203 of file ScalingFFAMagnet.h.
References phiStart_m.
Referenced by setupEndField().
setPlacementPose()
void ElementBase::setPlacementPose (const PlacementPose & pose) inline inherited
Set the nominal rigid placement transform of the element.
This bridge setter preserves the existing storage model by delegating to setCSTrafoGlobal2Local().
Definition at line 554 of file ElementBase.h.
References PlacementPose::getParentToNominal(), and ElementBase::setCSTrafoGlobal2Local().
setR0()
void ScalingFFAMagnet::setR0 (double r0) inline
Set the radius constant R_0
Definition at line 167 of file ScalingFFAMagnet.h.
References r0_m.
setRMax()
void ScalingFFAMagnet::setRMax (double rMax) inline
Set the maximum radius
Definition at line 227 of file ScalingFFAMagnet.h.
References rMax_m.
setRMin()
void ScalingFFAMagnet::setRMin (double rMin) inline
Set the maximum radius
Definition at line 219 of file ScalingFFAMagnet.h.
References rMin_m.
setRotationAboutZ()
void ElementBase::setRotationAboutZ (double rotation) inline inherited
Set rotation about z axis in bend frame.
Definition at line 606 of file ElementBase.h.
References ElementBase::rotationZAxis_m.
Referenced by OpalElement::update().
setTanDelta()
void ScalingFFAMagnet::setTanDelta (double tanDelta) inline
Set tan delta - delta is the spiral angle
Definition at line 149 of file ScalingFFAMagnet.h.
References tanDelta_m.
setupEndField()
void ScalingFFAMagnet::setupEndField ()
setupEndField does some end field and geometry set-up
This is normally called just before the magnet is placed; can only set up the end field after everything has been parsed from input (otherwise OPAL may not know about an end field model).
sets PhiStart, PhiEnd, AzimuthalExtent and the end field model itself.
Definition at line 211 of file ScalingFFAMagnet.cpp.
References azimuthalExtent_m, endfieldmodel::EndFieldModel::clone(), endFieldName_m, endfieldmodel::EndFieldModel::getCentreLength(), endfieldmodel::EndFieldModel::getEndFieldModel(), endfieldmodel::EndFieldModel::getEndLength(), getPhiStart(), getR0(), Units::m2mm, phiEnd_m, phiStart_m, planarArcGeometry_m, r0_m, endfieldmodel::EndFieldModel::rescale(), setAzimuthalExtent(), PlanarArcGeometry::setCurvature(), PlanarArcGeometry::setElementLength(), setEndField(), setPhiEnd(), and setPhiStart().
setVerticalExtent()
void ScalingFFAMagnet::setVerticalExtent (double verticalExtent) inline
Set the maximum vertical displacement from the midplane
Definition at line 243 of file ScalingFFAMagnet.h.
References verticalExtent_m.
setWake()
void ElementBase::setWake (WakeFunction * wf) virtual inherited
attach a wake field to the element
Definition at line 211 of file ElementBase.cpp.
References ElementBase::wake_m.
trackBunch()
void Component::trackBunch (PartBunch_t & bunch, const PartData & , bool revBeam, bool revTrack) const virtual inherited
Track a borrowed particle bunch through a non-standard component.
The default implementation throws a LogicalError.
Parameters
bunch Particle bunch to track. The component does not take ownership.
Definition at line 35 of file Component.cpp.
References ElementBase::getName().
Referenced by Tracker::visitComponent().
trackMap()
void Component::trackMap (FVps< double, 6 > & map, const PartData & , bool revBeam, bool revTrack) const virtual inherited
Track a map.
Definition at line 39 of file Component.cpp.
References ElementBase::getName().
update()
bool ElementBase::update (const AttributeSet & set) inherited
Update element.
Definition at line 203 of file ElementBase.cpp.
References AttributeSet::begin(), AttributeSet::end(), and ElementBase::setAttribute().
Member Data Documentation
actionRange_m
std::queue<std::pair<double, double> > ElementBase::actionRange_m private inherited
Definition at line 468 of file ElementBase.h.
Referenced by ElementBase::setActionRange(), and ElementBase::setCurrentSCoordinate().
aperture_m
std::pair<ApertureType, std::vector<double> > ElementBase::aperture_m protected inherited
Definition at line 439 of file ElementBase.h.
Referenced by ElementBase::getAperture(), ElementBase::getBoundingBoxInLabCoords(), ElementBase::isInsideTransverse(), and ElementBase::setAperture().
azimuthalExtent_m
double ScalingFFAMagnet::azimuthalExtent_m = 0. private
Definition at line 292 of file ScalingFFAMagnet.h.
Referenced by getAzimuthalExtent(), getFieldValueCylindrical(), setAzimuthalExtent(), and setupEndField().
bgeometry_m
BoundaryGeometry* ElementBase::bgeometry_m private inherited
Definition at line 459 of file ElementBase.h.
Referenced by ElementBase::getBoundaryGeometry(), ElementBase::hasBoundaryGeometry(), and ElementBase::setBoundaryGeometry().
Bz_m
double ScalingFFAMagnet::Bz_m = 0. private
Definition at line 286 of file ScalingFFAMagnet.h.
Referenced by getDipoleConstant(), getFieldValueCylindrical(), ScalingFFAMagnet(), and setDipoleConstant().
centre_m
Vector_t<double, 3> ScalingFFAMagnet::centre_m private
Definition at line 294 of file ScalingFFAMagnet.h.
Referenced by getCentre(), getFieldValue(), and setCentre().
csTrafoGlobal2Local_m
CoordinateSystemTrafo ElementBase::csTrafoGlobal2Local_m protected inherited
Definition at line 436 of file ElementBase.h.
Referenced by ElementBase::getBoundingBoxInLabCoords(), ElementBase::getCSTrafoGlobal2Local(), and ElementBase::setCSTrafoGlobal2Local().
defaultAperture_m
const std::vector< double > Component::defaultAperture_m = std::vector<double>({1e6, 1e6, 1.0}) static protected inherited
Definition at line 221 of file Component.h.
Referenced by Component::Component().
deleteOnTransverseExit_m
bool ElementBase::deleteOnTransverseExit_m = true private inherited
Definition at line 472 of file ElementBase.h.
Referenced by ElementBase::getFlagDeleteOnTransverseExit(), and ElementBase::setFlagDeleteOnTransverseExit().
dfCoefficients_m
std::vector<std::vector<double> > ScalingFFAMagnet::dfCoefficients_m private
Definition at line 298 of file ScalingFFAMagnet.h.
Referenced by calculateDfCoefficients(), getDfCoefficients(), and getFieldValueCylindrical().
dummy
BMultipoleField ScalingFFAMagnet::dummy private
Definition at line 281 of file ScalingFFAMagnet.h.
Referenced by getField(), and getField().
elemedgeSet_m
bool ElementBase::elemedgeSet_m private inherited
Definition at line 466 of file ElementBase.h.
Referenced by ElementBase::getElementPosition(), ElementBase::isElementPositionSet(), and ElementBase::setElementPosition().
elementEdge_m
double ElementBase::elementEdge_m protected inherited
Definition at line 441 of file ElementBase.h.
Referenced by ElementBase::setActionRange(), and ElementBase::setCurrentSCoordinate().
elementID
std::string ElementBase::elementID private inherited
Definition at line 450 of file ElementBase.h.
Referenced by ElementBase::getName(), and ElementBase::setName().
elementPosition_m
double ElementBase::elementPosition_m private inherited
ELEMEDGE attribute.
Definition at line 465 of file ElementBase.h.
Referenced by ElementBase::getElementPosition(), and ElementBase::setElementPosition().
elementTypeToString_s
const std::map< ElementType, std::string > ElementBase::elementTypeToString_s static private inherited
Initial value:
= {
        {ElementType::ANY, "Any"},
        {ElementType::BEAMLINE, "Beamline"},
        {ElementType::DRIFT, "Drift"},
        {ElementType::LASER, "Laser"},
        {ElementType::MARKER, "Marker"},
        {ElementType::MULTIPOLE, "Multipole"},
        {ElementType::RFCAVITY, "RFCavity"},
        {ElementType::TRAVELINGWAVE, "TravelingWave"},
        {ElementType::SBEND, "SBEND"},
        {ElementType::RBEND, "RBEND"},
        {ElementType::RBEND3D, "RBEND3D"},
        {ElementType::RING, "Ring"},
        {ElementType::SOURCE, "SOURCE"},
        {ElementType::SOLENOID, "SOLENOID"},
        {ElementType::PROBE, "Probe"},
        {ElementType::VACUUM, "Vacuum"},
        {ElementType::CONSTANTEFIELDCAVITY, "ConstantEFieldCavity"}}
Definition at line 73 of file ElementBase.h.
Referenced by ElementBase::getTypeString().
endField_m
endfieldmodel::EndFieldModel* ScalingFFAMagnet::endField_m = nullptr private
Definition at line 295 of file ScalingFFAMagnet.h.
Referenced by getEndField(), getFieldValueCylindrical(), ScalingFFAMagnet(), setEndField(), and ~ScalingFFAMagnet().
endFieldName_m
std::string ScalingFFAMagnet::endFieldName_m = "" private
Definition at line 296 of file ScalingFFAMagnet.h.
Referenced by getEndFieldName(), setEndFieldName(), and setupEndField().
exit_face_slope_m
double Component::exit_face_slope_m protected inherited
Definition at line 222 of file Component.h.
Referenced by Component::setExitFaceSlope().
fp_tolerance
const double ScalingFFAMagnet::fp_tolerance = 1e-18 private
Definition at line 297 of file ScalingFFAMagnet.h.
k_m
double ScalingFFAMagnet::k_m = 0. private
Definition at line 285 of file ScalingFFAMagnet.h.
Referenced by calculateDfCoefficients(), getFieldIndex(), getFieldValueCylindrical(), and setFieldIndex().
maxOrder_m
size_t ScalingFFAMagnet::maxOrder_m = 0 private
Definition at line 283 of file ScalingFFAMagnet.h.
Referenced by calculateDfCoefficients(), getFieldValueCylindrical(), getMaxOrder(), and setMaxOrder().
misalignment_m
CoordinateSystemTrafo ElementBase::misalignment_m protected inherited
Definition at line 437 of file ElementBase.h.
Referenced by ElementBase::getMisalignment(), and ElementBase::setMisalignment().
online_m
bool Component::online_m protected inherited
Definition at line 226 of file Component.h.
Referenced by Probe::doGoOffline(), PluginElement::finalise(), BendBase::finalise(), Multipole::finalise(), Ring::finalise(), Component::goOffline(), PluginElement::goOffline(), RFCavity::goOffline(), Solenoid::goOffline(), Component::goOnline(), Corrector::goOnline(), Monitor::goOnline(), RFCavity::goOnline(), Solenoid::goOnline(), TravelingWave::goOnline(), Ring::initialise(), BendBase::initialise(), Multipole::initialise(), Component::Online(), and PluginElement::~PluginElement().
outputfn_m
std::string ElementBase::outputfn_m private inherited
The name of the outputfile
Definition at line 470 of file ElementBase.h.
Referenced by ElementBase::getOutputFN(), and ElementBase::setOutputFN().
parmatint_m
ParticleMatterInteractionHandler* ElementBase::parmatint_m private inherited
Definition at line 461 of file ElementBase.h.
Referenced by ElementBase::getParticleMatterInteraction(), ElementBase::hasParticleMatterInteraction(), and ElementBase::setParticleMatterInteraction().
phiEnd_m
double ScalingFFAMagnet::phiEnd_m = 0. private
Definition at line 291 of file ScalingFFAMagnet.h.
Referenced by getPhiEnd(), setPhiEnd(), and setupEndField().
phiStart_m
double ScalingFFAMagnet::phiStart_m = 0. private
Definition at line 290 of file ScalingFFAMagnet.h.
Referenced by getFieldValueCylindrical(), getPhiStart(), setPhiStart(), and setupEndField().
planarArcGeometry_m
PlanarArcGeometry ScalingFFAMagnet::planarArcGeometry_m private
Definition at line 280 of file ScalingFFAMagnet.h.
Referenced by getGeometry(), getGeometry(), and setupEndField().
positionIsFixed
bool ElementBase::positionIsFixed private inherited
Definition at line 463 of file ElementBase.h.
Referenced by ElementBase::fixPosition(), ElementBase::isPositioned(), ElementBase::releasePosition(), and ElementBase::setCSTrafoGlobal2Local().
r0_m
double ScalingFFAMagnet::r0_m = 0. private
Definition at line 287 of file ScalingFFAMagnet.h.
Referenced by getFieldValueCylindrical(), getR0(), ScalingFFAMagnet(), setR0(), and setupEndField().
RefPartBunch_m
PartBunch_t* Component::RefPartBunch_m protected inherited
Definition at line 225 of file Component.h.
Referenced by Corrector::apply(), VerticalFFAMagnet::apply(), BendBase::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), MultipoleT::apply(), RFCavity::apply(), apply(), Solenoid::apply(), TravelingWave::apply(), VariableRFCavity::apply(), Ring::apply(), MultipoleT::apply(), RFCavity::apply(), TravelingWave::apply(), VariableRFCavity::apply(), Corrector::apply(), BendBase::calcDesignRadius(), BendBase::calcFieldAmplitude(), BendBase::calcGamma(), VerticalFFAMagnet::finalise(), MultipoleT::finalise(), finalise(), VariableRFCavity::finalise(), Corrector::goOnline(), PluginElement::initialise(), Corrector::initialise(), VerticalFFAMagnet::initialise(), BendBase::initialise(), ConstantEFieldCavity::initialise(), Drift::initialise(), Laser::initialise(), Marker::initialise(), Monitor::initialise(), Multipole::initialise(), MultipoleT::initialise(), RFCavity::initialise(), initialise(), Solenoid::initialise(), TravelingWave::initialise(), VariableRFCavity::initialise(), RFCavity::initialise(), VariableRFCavity::initNull(), Multipole::isFocusing(), MultipoleT::MultipoleT(), ScalingFFAMagnet(), Corrector::setDesignEnergy(), Ring::setRefPartBunch(), RFCavity::trackOnAxisParticle(), and VerticalFFAMagnet::VerticalFFAMagnet().
rMax_m
double ScalingFFAMagnet::rMax_m = 0. private
Definition at line 289 of file ScalingFFAMagnet.h.
Referenced by getFieldValueCylindrical(), getRMax(), and setRMax().
rMin_m
double ScalingFFAMagnet::rMin_m = 0. private
Definition at line 288 of file ScalingFFAMagnet.h.
Referenced by getRMin(), and setRMin().
rotationZAxis_m
double ElementBase::rotationZAxis_m protected inherited
Definition at line 443 of file ElementBase.h.
Referenced by ElementBase::getRotationAboutZ(), and ElementBase::setRotationAboutZ().
shareFlag
bool ElementBase::shareFlag mutable protected inherited
Definition at line 434 of file ElementBase.h.
Referenced by Beamline::Beamline(), Beamline::Beamline(), Beamline::Beamline(), ElementBase::isSharable(), and ElementBase::makeSharable().
tanDelta_m
double ScalingFFAMagnet::tanDelta_m = 0. private
Definition at line 284 of file ScalingFFAMagnet.h.
Referenced by calculateDfCoefficients(), getFieldValueCylindrical(), getTanDelta(), and setTanDelta().
userAttribs
AttributeSet ElementBase::userAttribs private inherited
Definition at line 455 of file ElementBase.h.
Referenced by ElementBase::getChannel(), and ElementBase::removeAttribute().
verticalExtent_m
double ScalingFFAMagnet::verticalExtent_m = 0. private
Definition at line 293 of file ScalingFFAMagnet.h.
Referenced by getFieldValueCylindrical(), getVerticalExtent(), and setVerticalExtent().
wake_m
WakeFunction* ElementBase::wake_m private inherited
Definition at line 457 of file ElementBase.h.
Referenced by ElementBase::getWake(), ElementBase::hasWake(), and ElementBase::setWake().
The documentation for this class was generated from the following files:
ScalingFFAMagnet.h
ScalingFFAMagnet.cpp