OPALX (Object Oriented Parallel Accelerator Library for Exascal): OpalBeamlinePlacementTest Class Reference
OpalBeamlinePlacementTest Class Reference
Inherits testing::Test.
Classes
class TestableFieldSolverCmd
Protected Member Functions
void SetUp () override
std::shared_ptr< PartBunch_t > makeBunch (const size_t numParticles)
Static Protected Member Functions
static void SetUpTestSuite ()
static void TearDownTestSuite ()
Protected Attributes
std::shared_ptr< FieldSolverCmd > fsCmdBase_m
std::shared_ptr< DataSink > dataSink_m
Detailed Description
Definition at line 50 of file TestOpalBeamlinePlacement.cpp.
Member Function Documentation
makeBunch()
std::shared_ptr< PartBunch_t > OpalBeamlinePlacementTest::makeBunch (const size_t numParticles) inline protected
Definition at line 91 of file TestOpalBeamlinePlacement.cpp.
References dataSink_m, Beam::find(), and fsCmdBase_m.
SetUp()
void OpalBeamlinePlacementTest::SetUp () inline override protected
Definition at line 67 of file TestOpalBeamlinePlacement.cpp.
References OpalData::getInstance(), OpalData::setOpenMode(), OpalData::storeInputFn(), and OpalData::WRITE.
SetUpTestSuite()
static void OpalBeamlinePlacementTest::SetUpTestSuite () inline static protected
Definition at line 52 of file TestOpalBeamlinePlacement.cpp.
References Options::enableHDF5, and gmsg.
TearDownTestSuite()
static void OpalBeamlinePlacementTest::TearDownTestSuite () inline static protected
Definition at line 61 of file TestOpalBeamlinePlacement.cpp.
References gmsg.
Member Data Documentation
dataSink_m
std::shared_ptr<DataSink> OpalBeamlinePlacementTest::dataSink_m protected
Definition at line 115 of file TestOpalBeamlinePlacement.cpp.
Referenced by makeBunch().
fsCmdBase_m
std::shared_ptr<FieldSolverCmd> OpalBeamlinePlacementTest::fsCmdBase_m protected
Definition at line 114 of file TestOpalBeamlinePlacement.cpp.
Referenced by makeBunch().
The documentation for this class was generated from the following file:
TestOpalBeamlinePlacement.cpp