OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions::ARefExpr< T > Class Template Reference
Expressions::ARefExpr< T > Class Template Reference
An expression defined as a reference to an array.
#include <ARefExpr.h>
Public Member Functions
ARefExpr (const std::string &objName, const std::string &attName)
Constructor.
ARefExpr (const ARefExpr< T > &rhs)
virtual ~ARefExpr ()
virtual OArray< T > * clone () const
Make clone.
virtual std::vector< T > evaluate () const
Evaluate the reference and return the value referred to.
virtual void print (std::ostream &os, int precedence=99) const
Print expression.
virtual bool isConstant () const
Test for constant.
virtual void invalidate ()
Force re-evaluation.
Private Member Functions
void operator= (const ARefExpr &)
void fill () const
const std::string getImage () const
Private Attributes
const std::string obj_name
const std::string att_name
Object * itsObject
Attribute * itsAttr
Detailed Description
template<class T>
class Expressions::ARefExpr< T >
An expression defined as a reference to an array.
Definition at line 41 of file ARefExpr.h.
Constructor & Destructor Documentation
ARefExpr() [1/2]
template<class T> Expressions::ARefExpr< T >::ARefExpr (const std::string & objName, const std::string & attName)
Constructor.
Definition at line 83 of file ARefExpr.h.
References att_name, itsAttr, itsObject, and obj_name.
Referenced by ARefExpr(), clone(), fill(), and operator=().
ARefExpr() [2/2]
template<class T> Expressions::ARefExpr< T >::ARefExpr (const ARefExpr< T > & rhs)
Definition at line 87 of file ARefExpr.h.
References ARefExpr(), att_name, itsAttr, itsObject, Expressions::OArray< T >::OArray(), and obj_name.
~ARefExpr()
template<class T> Expressions::ARefExpr< T >::~ARefExpr () virtual
Definition at line 96 of file ARefExpr.h.
References itsObject.
Member Function Documentation
clone()
template<class T> OArray< T > * Expressions::ARefExpr< T >::clone () const virtual
Make clone.
Implements Expressions::OArray< T >.
Definition at line 101 of file ARefExpr.h.
References ARefExpr(), and Expressions::OArray< T >::OArray().
evaluate()
template<class T> std::vector< T > Expressions::ARefExpr< T >::evaluate () const inline virtual
Evaluate the reference and return the value referred to.
Implements Expressions::OArray< T >.
Definition at line 106 of file ARefExpr.h.
References fill(), getImage(), and itsAttr.
fill()
template<class T> void Expressions::ARefExpr< T >::fill () const private
Definition at line 139 of file ARefExpr.h.
References ARefExpr(), att_name, OpalData::find(), OpalData::getInstance(), itsAttr, itsObject, and obj_name.
Referenced by evaluate().
getImage()
template<class T> const std::string Expressions::ARefExpr< T >::getImage () const private
Definition at line 125 of file ARefExpr.h.
References print().
Referenced by evaluate().
invalidate()
void Invalidator::invalidate () virtual inherited
Force re-evaluation.
Reimplemented in Expressions::AAutomatic< T >, Expressions::SAutomatic< T >, Expressions::SRefAttr< T >, and Expressions::SRefExpr< T >.
Definition at line 25 of file Invalidator.cpp.
isConstant()
template<class T> bool Expressions::OArray< T >::isConstant () const inline virtual inherited
Test for constant.
Definition at line 304 of file AbstractObjects/Expressions.h.
operator=()
template<class T> void Expressions::ARefExpr< T >::operator= (const ARefExpr< T > &) private
References ARefExpr().
print()
template<class T> void Expressions::ARefExpr< T >::print (std::ostream & os, int precedence = 99) const virtual
Print expression.
Implements Expressions::OArray< T >.
Definition at line 133 of file ARefExpr.h.
References att_name, and obj_name.
Referenced by getImage().
Member Data Documentation
att_name
template<class T> const std::string Expressions::ARefExpr< T >::att_name private
Definition at line 72 of file ARefExpr.h.
Referenced by ARefExpr(), ARefExpr(), fill(), and print().
itsAttr
template<class T> Attribute* Expressions::ARefExpr< T >::itsAttr mutable private
Definition at line 76 of file ARefExpr.h.
Referenced by ARefExpr(), ARefExpr(), evaluate(), and fill().
itsObject
template<class T> Object* Expressions::ARefExpr< T >::itsObject mutable private
Definition at line 75 of file ARefExpr.h.
Referenced by ARefExpr(), ARefExpr(), fill(), and ~ARefExpr().
obj_name
template<class T> const std::string Expressions::ARefExpr< T >::obj_name private
Definition at line 71 of file ARefExpr.h.
Referenced by ARefExpr(), ARefExpr(), fill(), and print().
The documentation for this class was generated from the following file:
ARefExpr.h