OPALX (Object Oriented Parallel Accelerator Library for Exascal): LF2< FieldFunction, Arguments > Class Template Reference
LF2< FieldFunction, Arguments > Class Template Reference
Leap-Frog 2nd order.
#include <LF2.h>
Public Member Functions
LF2 (const FieldFunction &fieldfunc)
virtual bool advance (PartBunch_t *bunch, const size_t &i, const double &t, const double dt, Arguments &... args) const
Protected Attributes
const FieldFunction & fieldfunc_m
Private Member Functions
bool doAdvance_m (PartBunch_t *bunch, const size_t &i, const double &t, const double dt, Arguments &... args) const
void push_m (Vector_t< double, 3 > &R, const Vector_t< double, 3 > &P, const double &h) const
bool kick_m (PartBunch_t *bunch, const size_t &i, const double &t, const double &h, Arguments &... args) const
Detailed Description
template<typename FieldFunction, typename... Arguments>
class LF2< FieldFunction, Arguments >
Leap-Frog 2nd order.
Definition at line 26 of file LF2.h.
Constructor & Destructor Documentation
LF2()
template<typename FieldFunction, typename... Arguments> LF2< FieldFunction, Arguments >::LF2 (const FieldFunction & fieldfunc) inline
Definition at line 28 of file LF2.h.
References Stepper< FieldFunction, Arguments... >::Stepper().
Member Function Documentation
advance()
virtual bool Stepper< FieldFunction, Arguments >::advance (PartBunch_t * bunch, const size_t & i, const double & t, const double dt, Arguments &... args) const inline virtual inherited
Definition at line 41 of file Stepper.h.
doAdvance_m()
template<typename FieldFunction, typename... Arguments> bool LF2< FieldFunction, Arguments >::doAdvance_m (PartBunch_t * bunch, const size_t & i, const double & t, const double dt, Arguments &... args) const private virtual
Implements Stepper< FieldFunction, Arguments... >.
Definition at line 22 of file LF2.hpp.
References kick_m(), Units::ns2s, PartBunch< T, Dim >::P(), push_m(), and PartBunch< T, Dim >::R().
kick_m()
template<typename FieldFunction, typename... Arguments> bool LF2< FieldFunction, Arguments >::kick_m (PartBunch_t * bunch, const size_t & i, const double & t, const double & h, Arguments &... args) const private
Definition at line 48 of file LF2.hpp.
References Stepper< FieldFunction, Arguments... >::fieldfunc_m.
Referenced by doAdvance_m().
push_m()
template<typename FieldFunction, typename... Arguments> void LF2< FieldFunction, Arguments >::push_m (Vector_t< double, 3 > & R, const Vector_t< double, 3 > & P, const double & h) const private
Definition at line 39 of file LF2.hpp.
References Physics::c, and dot().
Referenced by doAdvance_m().
Member Data Documentation
fieldfunc_m
const FieldFunction& Stepper< FieldFunction, Arguments >::fieldfunc_m protected inherited
Definition at line 64 of file Stepper.h.
Referenced by RK4< FieldFunction, Arguments >::derivate_m(), and LF2< FieldFunction, Arguments >::kick_m().
The documentation for this class was generated from the following files:
LF2.h
LF2.hpp