OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions::SDeferred< T > Class Template Reference
Expressions::SDeferred< T > Class Template Reference
Object attribute with a `‘deferred’' scalar value.
#include <SDeferred.h>
Public Member Functions
SDeferred (PtrToScalar< T > expr)
Constructor.
SDeferred (const SDeferred< T > &)
virtual ~SDeferred ()
virtual SDeferred< T > * clone () const
Make clone.
virtual T evaluate ()
Evaluate.
virtual bool isExpression () const
Return expression flag.
virtual void print (std::ostream &) const
Print the attribute value.
std::string getImage () const
Convert to string.
virtual void invalidate ()
Force re-evaluation.
Protected Attributes
PtrToScalar< T > expr_ptr
Pointer to expression.
T value
The value of the attribute.
Private Member Functions
SDeferred ()
void operator= (const SDeferred< T > &)
Private Attributes
bool in_evaluation
Detailed Description
template<class T>
class Expressions::SDeferred< T >
Object attribute with a `‘deferred’' scalar value.
Definition at line 39 of file SDeferred.h.
Constructor & Destructor Documentation
SDeferred() [1/3]
template<class T> Expressions::SDeferred< T >::SDeferred (PtrToScalar< T > expr) explicit
Constructor.
Definition at line 83 of file SDeferred.h.
References expr_ptr, in_evaluation, and Expressions::SValue< T >::SValue().
Referenced by clone(), operator=(), Expressions::SAutomatic< T >::SAutomatic(), Expressions::SAutomatic< T >::SAutomatic(), and SDeferred().
SDeferred() [2/3]
template<class T> Expressions::SDeferred< T >::SDeferred (const SDeferred< T > & rhs)
Definition at line 79 of file SDeferred.h.
References clone(), expr_ptr, in_evaluation, SDeferred(), and Expressions::SValue< T >::SValue().
~SDeferred()
template<class T> Expressions::SDeferred< T >::~SDeferred () virtual
Definition at line 87 of file SDeferred.h.
SDeferred() [3/3]
template<class T> Expressions::SDeferred< T >::SDeferred () private
Member Function Documentation
clone()
template<class T> SDeferred< T > * Expressions::SDeferred< T >::clone () const virtual
Make clone.
Reimplemented from Expressions::SValue< T >.
Reimplemented in Expressions::SAutomatic< T >.
Definition at line 90 of file SDeferred.h.
References SDeferred().
Referenced by SDeferred().
evaluate()
template<class T> T Expressions::SDeferred< T >::evaluate () virtual
Evaluate.
Reimplemented from Expressions::SValue< T >.
Reimplemented in Expressions::SAutomatic< T >.
Definition at line 95 of file SDeferred.h.
References expr_ptr, AttributeBase::getImage(), in_evaluation, Expressions::SValue< T >::value, OpalException::what(), and OpalException::where().
Referenced by Expressions::SAutomatic< T >::evaluate().
getImage()
std::string AttributeBase::getImage () const inherited
Convert to string.
Definition at line 29 of file AttributeBase.cpp.
References print().
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), and Expressions::SRefAttr< T >::evaluate().
invalidate()
void Invalidator::invalidate () virtual inherited
Force re-evaluation.
Reimplemented in Expressions::AAutomatic< T >, Expressions::SAutomatic< T >, Expressions::SRefAttr< T >, and Expressions::SRefExpr< T >.
Definition at line 25 of file Invalidator.cpp.
isExpression()
template<class T> bool Expressions::SDeferred< T >::isExpression () const virtual
Return expression flag.
Reimplemented from AttributeBase.
Definition at line 125 of file SDeferred.h.
operator=()
template<class T> void Expressions::SDeferred< T >::operator= (const SDeferred< T > &) private
References SDeferred().
print()
template<class T> void Expressions::SDeferred< T >::print (std::ostream & stream) const virtual
Print the attribute value.
Reimplemented from Expressions::SValue< T >.
Definition at line 130 of file SDeferred.h.
References expr_ptr.
Member Data Documentation
expr_ptr
template<class T> PtrToScalar<T> Expressions::SDeferred< T >::expr_ptr protected
Pointer to expression.
Definition at line 64 of file SDeferred.h.
Referenced by evaluate(), print(), SDeferred(), and SDeferred().
in_evaluation
template<class T> bool Expressions::SDeferred< T >::in_evaluation mutable private
Definition at line 72 of file SDeferred.h.
Referenced by evaluate(), SDeferred(), and SDeferred().
value
template<class T> T Expressions::SValue< T >::value mutable protected inherited
The value of the attribute.
Definition at line 59 of file SValue.h.
Referenced by clone(), Expressions::SAutomatic< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), evaluate(), print(), print(), SValue(), SValue(), and SValue().
The documentation for this class was generated from the following file:
SDeferred.h