OPALX (Object Oriented Parallel Accelerator Library for Exascal): SDDS::parser::ValueParser Class Reference
SDDS::parser::ValueParser Class Reference
#include <value_parser.hpp>
Public Member Functions
ValueParser (const std::string &input, size_t start_pos=0)
void skipWhitespace ()
bool parseFloat (float &value)
bool parseDouble (double &value)
bool parseShort (short &value)
bool parseLong (long &value)
bool parseChar (char &value)
bool parseQuotedString (std::string &value)
bool parseString (std::string &value)
size_t getPosition () const
void setPosition (size_t pos)
Private Attributes
const std::string & input_
size_t pos_
Detailed Description
Definition at line 17 of file value_parser.hpp.
Constructor & Destructor Documentation
ValueParser()
SDDS::parser::ValueParser::ValueParser (const std::string & input, size_t start_pos = 0) inline
Definition at line 19 of file value_parser.hpp.
Member Function Documentation
getPosition()
size_t SDDS::parser::ValueParser::getPosition () const inline
Definition at line 224 of file value_parser.hpp.
References pos_.
Referenced by SDDS::column::parse(), and SDDS::parameter::parse().
parseChar()
bool SDDS::parser::ValueParser::parseChar (char & value) inline
Definition at line 162 of file value_parser.hpp.
References input_, pos_, and skipWhitespace().
Referenced by SDDS::column::parse(), and SDDS::parameter::parse().
parseDouble()
bool SDDS::parser::ValueParser::parseDouble (double & value) inline
Definition at line 76 of file value_parser.hpp.
References input_, pos_, and skipWhitespace().
Referenced by SDDS::column::parse(), and SDDS::parameter::parse().
parseFloat()
bool SDDS::parser::ValueParser::parseFloat (float & value) inline
Definition at line 37 of file value_parser.hpp.
References input_, pos_, and skipWhitespace().
Referenced by SDDS::column::parse(), and SDDS::parameter::parse().
parseLong()
bool SDDS::parser::ValueParser::parseLong (long & value) inline
Definition at line 139 of file value_parser.hpp.
References input_, pos_, and skipWhitespace().
Referenced by SDDS::column::parse(), and SDDS::parameter::parse().
parseQuotedString()
bool SDDS::parser::ValueParser::parseQuotedString (std::string & value) inline
Definition at line 172 of file value_parser.hpp.
References input_, pos_, and skipWhitespace().
Referenced by SDDS::column::parse(), and parseString().
parseShort()
bool SDDS::parser::ValueParser::parseShort (short & value) inline
Definition at line 115 of file value_parser.hpp.
References input_, pos_, and skipWhitespace().
Referenced by SDDS::column::parse(), and SDDS::parameter::parse().
parseString()
bool SDDS::parser::ValueParser::parseString (std::string & value) inline
Definition at line 197 of file value_parser.hpp.
References input_, parseQuotedString(), pos_, and skipWhitespace().
Referenced by SDDS::parameter::parse().
setPosition()
void SDDS::parser::ValueParser::setPosition (size_t pos) inline
Definition at line 225 of file value_parser.hpp.
References pos_.
skipWhitespace()
void SDDS::parser::ValueParser::skipWhitespace () inline
Definition at line 22 of file value_parser.hpp.
References input_, and pos_.
Referenced by parseChar(), parseDouble(), parseFloat(), parseLong(), parseQuotedString(), parseShort(), and parseString().
Member Data Documentation
input_
const std::string& SDDS::parser::ValueParser::input_ private
Definition at line 228 of file value_parser.hpp.
Referenced by parseChar(), parseDouble(), parseFloat(), parseLong(), parseQuotedString(), parseShort(), parseString(), and skipWhitespace().
pos_
size_t SDDS::parser::ValueParser::pos_ private
Definition at line 229 of file value_parser.hpp.
Referenced by getPosition(), parseChar(), parseDouble(), parseFloat(), parseLong(), parseQuotedString(), parseShort(), parseString(), setPosition(), and skipWhitespace().
The documentation for this class was generated from the following file:
value_parser.hpp