OPALX (Object Oriented Parallel Accelerator Library for Exascal): DumpEMFields Class Reference
DumpEMFields Class Reference
#include <DumpEMFields.h>
Public Types
enum {
FILE_NAME , COORDINATE_SYSTEM , X_START , DX ,
X_STEPS , Y_START , DY , Y_STEPS ,
Z_START , DZ , Z_STEPS , T_START ,
DT , T_STEPS , R_START , DR ,
R_STEPS , PHI_START , DPHI , PHI_STEPS ,
CYL_ORIGIN_X , CYL_ORIGIN_Y , CYL_ORIGIN_Z , SIZE
}
The common attributes of DumpEMFields.
Public Member Functions
DumpEMFields ()
DumpEMFields (const std::string &name, DumpEMFields *parent)
~DumpEMFields () override=default
DumpEMFields * clone (const std::string &name) override
void execute () override
void print (std::ostream &os) const override
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Static Public Member Functions
static void writeFields (const std::set< std::shared_ptr< Component > > &elements)
static void failGrid ()
static void failWrite ()
static void clearDumps ()
Public Attributes
std::vector< Attribute > itsAttr
The object attributes.
Protected Attributes
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Private Types
enum class CoordinateSystem : unsigned short { CARTESIAN , CYLINDRICAL }
Private Member Functions
virtual void writeFieldThis (const std::set< std::shared_ptr< Component > > &elements)
virtual void buildGrid ()
void parseCoordinateSystem ()
void writeHeader (std::ofstream &fout) const
void writeFieldLine (const std::set< std::shared_ptr< Component > > &elements, const Vector_t< double, 3 > &point, const double &time, std::ofstream &fout) const
DumpEMFields (const DumpEMFields &dump)=delete
DumpEMFields & operator= (const DumpEMFields &dump)=delete
Static Private Member Functions
static void checkInt (double value, const std::string &name, double tolerance=1e-9)
Private Attributes
std::unique_ptr< interpolation::NDGrid > grid_m {}
Vector_t< double, 3 > cylindricalOrigin_m {}
std::string filename_m {}
CoordinateSystem coordinates_m {CoordinateSystem::CARTESIAN}
bool failWrite_m {false}
Object * itsParent
std::string itsName
std::string itsHelp
int occurrence
double timeStamp
std::set< Invalidator * > references
bool sharedFlag
Static Private Attributes
static std::unordered_set< std::unique_ptr< DumpEMFields > > dumpsSet_m
Detailed Description
DumpEMFields dumps the dynamically changing fields of a Ring in a user- defined grid.
The idea is to print out the field map across a 4D grid in space-time for debugging purposes. The problem is to manage the DumpEMFields object through three phases of program execution; initial construction, parsing and then actual field map writing (where we need to somehow let DumpFields know what the field maps are). So for each DumpEMFields object created, we store in a set. When the execute() method is called, DumpEMFields builds a grid using the parsed information.
When the ParallelCyclotronTracker is about to start tracking, it calls writeFields method which loops over the static set of DumpEMFields and writes each one. It is not the cleanest implementation, but I can't see a better way.
The DumpEMFields themselves operate by iterating over a NDGrid object and looking up the field/writing it out on each grid point.
Definition at line 55 of file DumpEMFields.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
The common attributes of DumpEMFields.
Enumerator
FILE_NAME
COORDINATE_SYSTEM
X_START
DX
X_STEPS
Y_START
DY
Y_STEPS
Z_START
DZ
Z_STEPS
T_START
DT
T_STEPS
R_START
DR
R_STEPS
PHI_START
DPHI
PHI_STEPS
CYL_ORIGIN_X
CYL_ORIGIN_Y
CYL_ORIGIN_Z
SIZE
Definition at line 58 of file DumpEMFields.h.
CoordinateSystem
enum class DumpEMFields::CoordinateSystem : unsigned short strong private
Enumerator
CARTESIAN
CYLINDRICAL
Definition at line 144 of file DumpEMFields.h.
Constructor & Destructor Documentation
DumpEMFields() [1/3]
DumpEMFields::DumpEMFields ()
Constructor
Definition at line 32 of file DumpEMFields.cpp.
References Action::Action(), COORDINATE_SYSTEM, CYL_ORIGIN_X, CYL_ORIGIN_Y, CYL_ORIGIN_Z, DPHI, DR, DT, DX, DY, DZ, FILE_NAME, Object::itsAttr, Attributes::makePredefinedString(), Attributes::makeReal(), Attributes::makeString(), PHI_START, PHI_STEPS, R_START, R_STEPS, Object::registerOwnership(), SIZE, AttributeHandler::STATEMENT, T_START, T_STEPS, X_START, X_STEPS, Y_START, Y_STEPS, Z_START, and Z_STEPS.
Referenced by clone(), DumpEMFields(), DumpEMFields(), operator=(), and ~DumpEMFields().
DumpEMFields() [2/3]
DumpEMFields::DumpEMFields (const std::string & name, DumpEMFields * parent)
Constructor
Definition at line 97 of file DumpEMFields.cpp.
References Action::Action(), and DumpEMFields().
~DumpEMFields()
DumpEMFields::~DumpEMFields () override default
Destructor
References DumpEMFields().
DumpEMFields() [3/3]
DumpEMFields::DumpEMFields (const DumpEMFields & dump) private delete
References DumpEMFields().
Member Function Documentation
buildGrid()
void DumpEMFields::buildGrid () private virtual
Definition at line 126 of file DumpEMFields.cpp.
References CARTESIAN, checkInt(), coordinates_m, CYL_ORIGIN_X, CYL_ORIGIN_Y, CYL_ORIGIN_Z, cylindricalOrigin_m, DPHI, DR, DT, DX, DY, DZ, FILE_NAME, filename_m, Attributes::getReal(), Attributes::getString(), grid_m, Object::itsAttr, parseCoordinateSystem(), PHI_START, PHI_STEPS, R_START, R_STEPS, T_START, T_STEPS, X_START, X_STEPS, Y_START, Y_STEPS, Z_START, and Z_STEPS.
Referenced by execute().
canReplaceBy()
bool Action::canReplaceBy (Object * object) virtual inherited
Test if replacement is allowed.
Reimplemented from Object.
Definition at line 26 of file Action.cpp.
References Object::Object().
checkInt()
void DumpEMFields::checkInt (double value, const std::string & name, double tolerance = 1e-9) static private
Definition at line 190 of file DumpEMFields.cpp.
Referenced by buildGrid().
clear()
void Object::clear () inherited
Clear the occurrence counter.
Definition at line 285 of file Object.cpp.
References occurrence.
clearDumps()
void DumpEMFields::clearDumps () inline static
Definition at line 141 of file DumpEMFields.h.
References dumpsSet_m.
clone()
DumpEMFields * DumpEMFields::clone (const std::string & name) override virtual
Make a clone (overloadable copy-constructor).
Parameters
name not used If this is in the dumpsSet_m, so will the clone. Not sure how the itsAttr stuff works, so this may not get properly copied?
Implements Object.
Definition at line 99 of file DumpEMFields.cpp.
References coordinates_m, cylindricalOrigin_m, DumpEMFields(), filename_m, and grid_m.
Referenced by execute().
copyAttributes()
void Object::copyAttributes (const Object & source) inherited
Copy attributes from another object.
Definition at line 50 of file Object.cpp.
References itsAttr, and Object().
Referenced by LineTemplate::makeInstance(), and SequenceTemplate::makeInstance().
execute()
void DumpEMFields::execute () override virtual
Builds the grid but does not write the field map
Builds a grid of points in x-y-z space using the NDGrid algorithm. Checks that X_STEPS, Y_STEPS, Z_STEPS are integers or throws OpalException.
Reimplemented from Object.
Definition at line 117 of file DumpEMFields.cpp.
References buildGrid(), clone(), and dumpsSet_m.
failGrid()
void DumpEMFields::failGrid () inline static
Definition at line 129 of file DumpEMFields.h.
References dumpsSet_m.
failWrite()
void DumpEMFields::failWrite () inline static
Definition at line 135 of file DumpEMFields.h.
References dumpsSet_m.
findAttribute() [1/2]
Attribute * Object::findAttribute (const std::string & name) virtual inherited
Find an attribute by name.
Definition at line 56 of file Object.cpp.
References itsAttr.
Referenced by OpalElement::getParticleMatterInteraction(), OpalElement::getTypeName(), OpalElement::getWakeF(), Line::parse(), parse(), OpalElement::parse(), OpalParser::parseAssign(), SequenceParser::parsePosition(), TrackRun::print(), and TEST().
findAttribute() [2/2]
const Attribute * Object::findAttribute (const std::string & name) const virtual inherited
Find an attribute by name.
Definition at line 63 of file Object.cpp.
References itsAttr.
getBaseObject()
const Object * Object::getBaseObject () const inherited
Return the object's base type object.
Definition at line 260 of file Object.cpp.
References itsParent, and Object().
getCategory()
const std::string Action::getCategory () const virtual inherited
Return the object category as a string.
Implements Object.
Definition at line 28 of file Action.cpp.
getOpalName()
const std::string & Object::getOpalName () const inherited
Return object name.
Definition at line 267 of file Object.cpp.
References itsName.
Referenced by Macro::clone(), OpalVariableRFCavity::clone(), OpalData::create(), OpalData::define(), Sequence::findDriftLength(), ValueDefinition::getBool(), ValueDefinition::getBoolComponent(), ValueDefinition::getReal(), ValueDefinition::getRealComponent(), ValueDefinition::getString(), ValueDefinition::getStringComponent(), LineTemplate::makeInstance(), makeInstance(), SequenceTemplate::makeInstance(), parse(), SequenceParser::parsePosition(), Beam::print(), BoolConstant::print(), Line::print(), print(), OpalElement::print(), OpalFilter::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), Sequence::print(), StringConstant::print(), TrackRun::print(), BinningCmd::printInfo(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), registerOwnership(), OpalElement::registerOwnership(), Line::replace(), Sequence::replace(), PartBunch< T, Dim >::setBins(), TEST(), TEST(), TEST(), TEST_F(), Beam::update(), BoundaryGeometry::update(), OpalFilter::update(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), and OpalSplineTimeDependence::update().
getParent()
Object * Object::getParent () const inherited
Return parent pointer.
Definition at line 269 of file Object.cpp.
References itsParent, and Object().
Referenced by OpalData::erase(), print(), OpalElement::print(), registerOwnership(), and OpalElement::registerOwnership().
increment()
int Object::increment () inherited
Increment and return the occurrence counter.
Definition at line 287 of file Object.cpp.
References occurrence.
Referenced by Line::parse(), and Sequence::storeLine().
isBuiltin()
bool Object::isBuiltin () const inherited
True, if [b]this[/b] is a built-in object.
Definition at line 243 of file Object.cpp.
References builtin.
Referenced by OpalData::define(), and OpalData::getVariableNames().
isDirty()
bool Object::isDirty () const inherited
True, if the [b]modified[/b] flag is set.
Definition at line 254 of file Object.cpp.
References modified.
isFlagged()
bool Object::isFlagged () const inherited
True, if [b]this[/b] is flagged by setFlag(true).
Definition at line 258 of file Object.cpp.
References flagged.
isShared()
bool Object::isShared () const virtual inherited
Shared flag.
Definition at line 245 of file Object.cpp.
References sharedFlag.
Referenced by Sequence::print().
isTreeMember()
bool Object::isTreeMember (const Object * subTree) const inherited
Test for tree membership.
Definition at line 271 of file Object.cpp.
References Object().
Referenced by Selector::handleElement(), and OpalParser::parseAssign().
makeInstance()
Object * Object::makeInstance (const std::string & name, Statement & , const Parser *) virtual inherited
Macro handler function.
Reimplemented in LineTemplate, MacroCmd, and SequenceTemplate.
Definition at line 76 of file Object.cpp.
References getOpalName(), and Object().
Referenced by OpalParser::parseDefine(), and OpalParser::parseMacro().
makeTemplate()
Object * Object::makeTemplate (const std::string & name, TokenStream & , Statement &) virtual inherited
Macro handler function.
Reimplemented in Line, LineTemplate, MacroCmd, Sequence, and SequenceTemplate.
Definition at line 71 of file Object.cpp.
References Object().
Referenced by OpalParser::parseMacro().
occurrenceCount()
int Object::occurrenceCount () inherited
Return the occurrence counter.
Definition at line 289 of file Object.cpp.
References occurrence.
operator=()
DumpEMFields & DumpEMFields::operator= (const DumpEMFields & dump) private delete
References DumpEMFields().
parse()
void Object::parse (Statement & stat) virtual inherited
Parse the object.
Reimplemented in Call, Echo, EmissionSourceList, Help, Line, OpalElement, PSystem, Sequence, System, Title, and Value.
Definition at line 82 of file Object.cpp.
References Statement::delimiter(), findAttribute(), getOpalName(), Expressions::parseDelimiter(), Expressions::parseRealConst(), and Expressions::parseString().
Referenced by Sequence::parse(), OpalParser::parseAction(), OpalParser::parseDefine(), and SequenceTemplate::parseTemplate().
parseCoordinateSystem()
void DumpEMFields::parseCoordinateSystem () private
Definition at line 110 of file DumpEMFields.cpp.
References CARTESIAN, COORDINATE_SYSTEM, coordinates_m, CYLINDRICAL, Attributes::getString(), and Object::itsAttr.
Referenced by buildGrid().
parseShortcut()
void Object::parseShortcut (Statement & stat, bool eval = true) virtual inherited
Parser for single-attribute commands.
Definition at line 113 of file Object.cpp.
Referenced by Call::parse(), Echo::parse(), Help::parse(), PSystem::parse(), System::parse(), Title::parse(), and Value::parse().
print()
void DumpEMFields::print (std::ostream & os) const override virtual
Print the attributes of DumpEMFields to standard out
Reimplemented from Object.
Definition at line 324 of file DumpEMFields.cpp.
References CARTESIAN, COORDINATE_SYSTEM, coordinates_m, DPHI, DR, DT, DX, DY, DZ, filename_m, Attributes::getReal(), Attributes::getString(), Object::itsAttr, PHI_START, PHI_STEPS, R_START, R_STEPS, T_START, T_STEPS, X_START, X_STEPS, Y_START, Y_STEPS, Z_START, and Z_STEPS.
Referenced by operator<<().
printHelp()
void Object::printHelp (std::ostream &) const virtual inherited
Print help.
Definition at line 179 of file Object.cpp.
References gmsg, itsAttr, and itsHelp.
Referenced by Help::execute(), and main().
printValue()
void Object::printValue (std::ostream & os) const inline virtual inherited
Reimplemented in BoolConstant, RealConstant, RealVariable, RealVector, and StringConstant.
Definition at line 270 of file Object.h.
References print().
registerOwnership()
void Object::registerOwnership (const AttributeHandler::OwnerType & itsClass) const inherited
Definition at line 169 of file Object.cpp.
References AttributeHandler::addAttributeOwner(), getOpalName(), getParent(), and itsAttr.
Referenced by Beam::Beam(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), Call::Call(), Distribution::Distribution(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), EmissionSourceList::EmissionSourceList(), Help::Help(), Line::Line(), OpalFilter::OpalFilter(), Option::Option(), PSystem::PSystem(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVector::RealVector(), Select::Select(), Sequence::Sequence(), StringConstant::StringConstant(), System::System(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), and Value::Value().
registerReference()
void Object::registerReference (Invalidator * a) inherited
Register a reference to this object.
Definition at line 165 of file Object.cpp.
References references.
replace()
void Object::replace (Object * oldObject, Object * newObject) virtual inherited
Replace references.
Reimplemented in Line, and Sequence.
Definition at line 235 of file Object.cpp.
References Object().
setDirty()
void Object::setDirty (bool dirty) inherited
Set/reset the [b]modified[/b] flag.
Definition at line 249 of file Object.cpp.
References modified.
Referenced by OpalData::define(), OpalData::makeDirty(), and RealVariable::RealVariable().
setFlag()
void Object::setFlag (bool flag) inherited
Flag/unflag this object, e. g. to control output of objects for.
Definition at line 256 of file Object.cpp.
References flagged.
setOpalName()
void Object::setOpalName (const std::string & name) inherited
Set object name.
Definition at line 281 of file Object.cpp.
References itsName.
Referenced by TEST(), TEST(), TEST(), Beam::update(), BoundaryGeometry::update(), and OpalFilter::update().
setParent()
void Object::setParent (Object * parent) inherited
Set parent object.
Definition at line 283 of file Object.cpp.
References itsParent, and Object().
Referenced by OpalData::erase().
setShared()
void Object::setShared (bool flag) virtual inherited
Set/reset shared flag.
Reimplemented in Element.
Definition at line 247 of file Object.cpp.
References sharedFlag.
Referenced by OpalParser::parseDefine(), and Element::setShared().
shouldTrace()
bool Action::shouldTrace () const virtual inherited
Trace flag.
Implements Object.
Definition at line 30 of file Action.cpp.
shouldUpdate()
bool Action::shouldUpdate () const virtual inherited
Update flag.
Implements Object.
Definition at line 32 of file Action.cpp.
unregisterReference()
void Object::unregisterReference (Invalidator * a) inherited
Unegister a reference to this object.
Definition at line 167 of file Object.cpp.
References references.
update()
void Object::update () virtual inherited
Update this object.
Reimplemented in Beam, BinningCmd, BoundaryGeometry, FieldSolverCmd, OpalCavity, OpalConstantEFieldCavity, OpalDrift, OpalElement, OpalFilter, OpalLaser, OpalMarker, OpalMonitor, OpalMultipole, OpalMultipoleT, OpalPolynomialTimeDependence, OpalProbe, OpalQuadrupole, OpalRBend, OpalRingDefinition, OpalSBend, OpalSinusoidalTimeDependence, OpalSolenoid, OpalSource, OpalSplineTimeDependence, OpalTravelingWave, OpalVacuum, OpalVariableRFCavity, OpalVerticalFFAMagnet, Option, and Sequence.
Definition at line 239 of file Object.cpp.
Referenced by Distribution::execute().
writeFieldLine()
void DumpEMFields::writeFieldLine (const std::set< std::shared_ptr< Component > > & elements, const Vector_t< double, 3 > & point, const double & time, std::ofstream & fout) const private
Definition at line 230 of file DumpEMFields.cpp.
References coordinates_m, CYLINDRICAL, cylindricalOrigin_m, Units::rad2deg, and Units::Vpm2MVpm.
Referenced by writeFieldThis().
writeFields()
void DumpEMFields::writeFields (const std::set< std::shared_ptr< Component > > & elements) static
Write the fields for all defined DumpEMFields objects
Parameters
elements the set of components. Iterates over the DumpEMFields in the dumpsSet_m and calls writeFieldThis on each DumpEMFields. This writes each field map in turn. Format is: <number of rows> <column 1> <units> <column 2> <units> <column 3> <units> <column 4> <units> <column 5> <units> <column 6> <units> 0 <field map data>
Definition at line 183 of file DumpEMFields.cpp.
References dumpsSet_m.
Referenced by ParallelTracker::execute().
writeFieldThis()
void DumpEMFields::writeFieldThis (const std::set< std::shared_ptr< Component > > & elements) private virtual
Definition at line 277 of file DumpEMFields.cpp.
References Util::combineFilePath(), failWrite_m, filename_m, OpalData::getAuxiliaryOutputDirectory(), OpalData::getInstance(), gmsg, grid_m, writeFieldLine(), and writeHeader().
writeHeader()
void DumpEMFields::writeHeader (std::ofstream & fout) const private
Definition at line 202 of file DumpEMFields.cpp.
References CARTESIAN, coordinates_m, and grid_m.
Referenced by writeFieldThis().
Member Data Documentation
builtin
bool Object::builtin protected inherited
Built-in flag.
Definition at line 226 of file Object.h.
Referenced by Beam::Beam(), BoundaryGeometry::BoundaryGeometry(), isBuiltin(), Object(), Object(), OpalFilter::OpalFilter(), OpalMarker::OpalMarker(), RealConstant::RealConstant(), StringConstant::StringConstant(), and Table::~Table().
coordinates_m
CoordinateSystem DumpEMFields::coordinates_m {CoordinateSystem::CARTESIAN} private
Definition at line 159 of file DumpEMFields.h.
Referenced by buildGrid(), clone(), parseCoordinateSystem(), print(), writeFieldLine(), and writeHeader().
cylindricalOrigin_m
Vector_t<double, 3> DumpEMFields::cylindricalOrigin_m {} private
Definition at line 156 of file DumpEMFields.h.
Referenced by buildGrid(), clone(), and writeFieldLine().
dumpsSet_m
std::unordered_set< std::unique_ptr< DumpEMFields > > DumpEMFields::dumpsSet_m static private
Definition at line 161 of file DumpEMFields.h.
Referenced by clearDumps(), execute(), failGrid(), failWrite(), and writeFields().
failWrite_m
bool DumpEMFields::failWrite_m {false} private
Definition at line 167 of file DumpEMFields.h.
Referenced by writeFieldThis().
filename_m
std::string DumpEMFields::filename_m {} private
Definition at line 157 of file DumpEMFields.h.
Referenced by buildGrid(), clone(), print(), and writeFieldThis().
flagged
bool Object::flagged protected inherited
Object flag.
Definition at line 235 of file Object.h.
Referenced by isFlagged(), Object(), Object(), and setFlag().
grid_m
std::unique_ptr<interpolation::NDGrid> DumpEMFields::grid_m {} private
Definition at line 155 of file DumpEMFields.h.
Referenced by buildGrid(), clone(), writeFieldThis(), and writeHeader().
itsAttr
std::vector<Attribute> Object::itsAttr inherited
The object attributes.
Definition at line 210 of file Object.h.
Referenced by Beam::Beam(), BinningCmd::BinningCmd(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), BoundaryGeometry::BoundaryGeometry(), DumpEMFields::buildGrid(), Call::Call(), FieldSolverCmd::constructBCHandler(), copyAttributes(), Distribution::Distribution(), BinningCmd::dumpBinsToFile(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), Beam::execute(), Call::execute(), Echo::execute(), Help::execute(), Option::execute(), PSystem::execute(), Select::execute(), System::execute(), Title::execute(), TrackCmd::execute(), TrackRun::execute(), Value::execute(), FieldSolverCmd::FieldSolverCmd(), findAttribute(), findAttribute(), BoundaryGeometry::getA(), OpalElement::getApert(), BoundaryGeometry::getB(), BinningCmd::getBinningAlpha(), BinningCmd::getBinningBeta(), FieldSolverCmd::getBinsName(), BoolConstant::getBool(), FieldSolverCmd::getBoxIncr(), Beam::getBunchCharge(), BoundaryGeometry::getC(), Beam::getCharge(), Beam::getCurrent(), Beam::getDaughterBeamName(), BinningCmd::getDesiredWidth(), EmissionSource::getDistributionName(), FieldSolverCmd::getDomDec(), TrackCmd::getDT(), TrackCmd::getDTAU(), TrackCmd::getDTSCINIT(), BinningCmd::getDumpBinsFileName(), BinningCmd::getDumpBinsFrequency(), EmissionSource::getEmissionModel(), Beam::getEmissionSourceListName(), BoundaryGeometry::getFilename(), Distribution::getFilename(), Beam::getFrequency(), Beam::getGlobalProcessNames(), BoundaryGeometry::getL1(), BoundaryGeometry::getL2(), BoundaryGeometry::getLength(), Line::getLength(), OpalElement::getLength(), Sequence::getLength(), Beam::getMass(), BinningCmd::getMaxBins(), TrackCmd::getMaxSteps(), Beam::getNumAlloc(), FieldSolverCmd::getNX(), FieldSolverCmd::getNY(), FieldSolverCmd::getNZ(), EmissionSource::getP0(), BinningCmd::getParameter(), Beam::getParticleName(), EmissionSource::getR0(), RealConstant::getReal(), RealVariable::getReal(), RealVector::getRealComponent(), Sequence::getReference(), BoundaryGeometry::getS(), EmissionSource::getShiftedGreensFunction(), TrackCmd::getStepsPerTurn(), StringConstant::getString(), EmissionSource::getT0(), TrackCmd::getT0(), BinningCmd::getTablePrintFrequency(), TrackCmd::getTimeIntegrator(), BoundaryGeometry::getTopology(), FieldSolverCmd::getType(), EmissionSource::getZerofaceMaxSteps(), EmissionSource::getZeroFacePlaneDumpFrequency(), EmissionSource::getZeroFaceR0Z(), TrackCmd::getZStart(), TrackCmd::getZStop(), Beam::hasExplicitEnergy(), Help::Help(), BoundaryGeometry::initialize(), OpalFilter::initOpalFilter(), Beam::isPhoton(), Line::Line(), Object(), Object(), OpalBend::OpalBend(), OpalCavity::OpalCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalDrift::OpalDrift(), OpalElement::OpalElement(), OpalFilter::OpalFilter(), OpalLaser::OpalLaser(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalPolynomialTimeDependence::OpalPolynomialTimeDependence(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalRingDefinition::OpalRingDefinition(), OpalSinusoidalTimeDependence::OpalSinusoidalTimeDependence(), OpalSolenoid::OpalSolenoid(), OpalSplineTimeDependence::OpalSplineTimeDependence(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), Option::Option(), Option::Option(), Line::parse(), Sequence::parse(), DumpEMFields::parseCoordinateSystem(), Beam::print(), BoolConstant::print(), DumpEMFields::print(), print(), OpalFilter::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), Sequence::print(), StringConstant::print(), printHelp(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), BoolConstant::printValue(), RealConstant::printValue(), RealVariable::printValue(), RealVector::printValue(), StringConstant::printValue(), PSystem::PSystem(), RealConstant::RealConstant(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVariable::RealVariable(), RealVector::RealVector(), registerOwnership(), OpalElement::registerOwnership(), Select::Select(), Select::select(), Sequence::Sequence(), Distribution::setAttributes(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCX(), OrbitThreaderTest::TestableFieldSolverCmd::setBCX(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCX(), TestMultipoleT::TestableFieldSolverCmd::setBCX(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCX(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCX(), TestVariableRFCavity::TestableFieldSolverCmd::setBCX(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCY(), OrbitThreaderTest::TestableFieldSolverCmd::setBCY(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCY(), TestMultipoleT::TestableFieldSolverCmd::setBCY(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCY(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCY(), TestVariableRFCavity::TestableFieldSolverCmd::setBCY(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCZ(), OrbitThreaderTest::TestableFieldSolverCmd::setBCZ(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCZ(), TestMultipoleT::TestableFieldSolverCmd::setBCZ(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCZ(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCZ(), TestVariableRFCavity::TestableFieldSolverCmd::setBCZ(), TestableBinningCmd::setBinningAlpha(), TestableBinningCmd::setBinningBeta(), TestableBinningCmd::setDesiredWidth(), Distribution::setDistParametersFlatTop(), Distribution::setDistParametersMultiVariateGauss(), Distribution::setDistType(), TestableBinningCmd::setDumpBinsFile(), TestableBinningCmd::setDumpBinsFreq(), TestableBinningCmd::setMaxBins(), FieldSolverCmd::setNX(), FieldSolverCmd::setNY(), FieldSolverCmd::setNZ(), TestableBinningCmd::setParameterString(), TrackRun::setRunMethod(), Distribution::setSigmaP_m(), Distribution::setSigmaR_m(), TestableBinningCmd::setTablePrintFrequency(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setType(), OrbitThreaderTest::TestableFieldSolverCmd::setType(), SolenoidPlacementTest::TestableFieldSolverCmd::setType(), TestMultipoleT::TestableFieldSolverCmd::setType(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setType(), TestMultipoleTStraight::TestableFieldSolverCmd::setType(), TestVariableRFCavity::TestableFieldSolverCmd::setType(), TrackRun::setupBoundaryGeometry(), StringConstant::StringConstant(), StringConstant::StringConstant(), System::System(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), Beam::update(), BinningCmd::update(), FieldSolverCmd::update(), OpalCavity::update(), OpalConstantEFieldCavity::update(), OpalDrift::update(), OpalElement::update(), OpalLaser::update(), OpalMonitor::update(), OpalMultipole::update(), OpalMultipoleT::update(), OpalPolynomialTimeDependence::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalRBend::update(), OpalRingDefinition::update(), OpalSBend::update(), OpalSinusoidalTimeDependence::update(), OpalSolenoid::update(), OpalSplineTimeDependence::update(), OpalTravelingWave::update(), OpalVacuum::update(), OpalVariableRFCavity::update(), OpalVerticalFFAMagnet::update(), Option::update(), OpalElement::updateUnknown(), Value::Value(), ValueDefinition::value(), and ValueDefinition::value().
itsHelp
std::string Object::itsHelp private inherited
Definition at line 250 of file Object.h.
Referenced by Object(), Object(), and printHelp().
itsName
std::string Object::itsName private inherited
Definition at line 247 of file Object.h.
Referenced by getOpalName(), Object(), Object(), and setOpalName().
itsParent
Object* Object::itsParent private inherited
Definition at line 244 of file Object.h.
Referenced by getBaseObject(), getParent(), Object(), Object(), and setParent().
modified
bool Object::modified protected inherited
Dirty flag.
Definition at line 231 of file Object.h.
Referenced by isDirty(), Object(), Object(), and setDirty().
occurrence
int Object::occurrence private inherited
Definition at line 253 of file Object.h.
Referenced by clear(), increment(), Object(), Object(), and occurrenceCount().
references
std::set<Invalidator*> Object::references private inherited
Definition at line 260 of file Object.h.
Referenced by registerReference(), unregisterReference(), and ~Object().
sharedFlag
bool Object::sharedFlag private inherited
Definition at line 263 of file Object.h.
Referenced by isShared(), Object(), Object(), and setShared().
timeStamp
double Object::timeStamp private inherited
Definition at line 256 of file Object.h.
The documentation for this class was generated from the following files:
DumpEMFields.h
DumpEMFields.cpp