OPALX (Object Oriented Parallel Accelerator Library for Exascal): RegularExpression Class Reference
RegularExpression Class Reference
A regular expression.
#include <RegularExpression.h>
Classes
class Expression
Public Member Functions
RegularExpression (const std::string &pattern, bool ignore=false)
Constructor.
RegularExpression (const RegularExpression &)
~RegularExpression ()
bool match (const std::string &s) const
Match a string against the pattern.
bool OK () const
Check the regular expression for sanity.
Private Member Functions
void operator= (const RegularExpression &)
void init ()
Private Attributes
const std::string patt
bool caseIgnore
Expression * expr
int state
Detailed Description
A regular expression.
Definition at line 30 of file RegularExpression.h.
Constructor & Destructor Documentation
RegularExpression() [1/2]
RegularExpression::RegularExpression (const std::string & pattern, bool ignore = false)
Constructor.
Definition at line 39 of file RegularExpression.cpp.
References caseIgnore, init(), and patt.
Referenced by operator=(), and RegularExpression().
RegularExpression() [2/2]
RegularExpression::RegularExpression (const RegularExpression & rhs)
Definition at line 44 of file RegularExpression.cpp.
References caseIgnore, init(), patt, and RegularExpression().
~RegularExpression()
RegularExpression::~RegularExpression ()
Definition at line 49 of file RegularExpression.cpp.
References expr.
Member Function Documentation
init()
void RegularExpression::init () private
Definition at line 73 of file RegularExpression.cpp.
References caseIgnore, expr, patt, and state.
Referenced by RegularExpression(), and RegularExpression().
match()
bool RegularExpression::match (const std::string & s) const
Match a string against the pattern.
Definition at line 51 of file RegularExpression.cpp.
References expr, and state.
Referenced by OpalData::printNames().
OK()
bool RegularExpression::OK () const
Check the regular expression for sanity.
Definition at line 71 of file RegularExpression.cpp.
References expr, and state.
operator=()
void RegularExpression::operator= (const RegularExpression &) private
References RegularExpression().
Member Data Documentation
caseIgnore
bool RegularExpression::caseIgnore private
Definition at line 57 of file RegularExpression.h.
Referenced by init(), RegularExpression(), and RegularExpression().
expr
Expression* RegularExpression::expr private
Definition at line 61 of file RegularExpression.h.
Referenced by init(), match(), OK(), and ~RegularExpression().
patt
const std::string RegularExpression::patt private
Definition at line 54 of file RegularExpression.h.
Referenced by init(), RegularExpression(), and RegularExpression().
state
int RegularExpression::state private
Definition at line 64 of file RegularExpression.h.
Referenced by init(), match(), and OK().
The documentation for this class was generated from the following files:
RegularExpression.h
RegularExpression.cpp