OPALX (Object Oriented Parallel Accelerator Library for Exascal): TrackRun Class Reference
TrackRun Class Reference
#include <TrackRun.h>
Public Member Functions
TrackRun ()
Exemplar constructor.
virtual ~TrackRun ()
virtual TrackRun * clone (const std::string &name)
Make clone.
virtual void execute ()
Execute the command.
Inform & print (Inform &os) const
virtual void print (std::ostream &) const
Print the object.
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Attributes
std::vector< Attribute > itsAttr
The object attributes.
Protected Attributes
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Private Types
enum class RunMethod : unsigned short { NONE , PARALLEL }
using emittingSamplers_t = std::vector<std::shared_ptr<SamplingBase>>
using bunch_type = PartBunch_t
Private Member Functions
TrackRun (const TrackRun &)
void operator= (const TrackRun &)
TrackRun (const std::string &name, TrackRun *parent)
void setRunMethod ()
std::string getRunMethodName () const
void initDataSink (size_t numParticleContainers)
std::vector< H5PartWrapper * > borrowedPhaseSpaceSinks () const
void setupBoundaryGeometry ()
void setupGlobalProcesses (std::vector< std::vector< std::unique_ptr< GlobalProcess > > > globalProcessesLists)
Attach prebuilt global process vector to each particle container.
void wireDaughterContainers (const std::vector< Beam * > &beams)
Wire daughter containers to cross-container processes (e.g. muon decay -> electron).
void setupDistributionsAndSamplers (const std::vector< EmissionSource * > &sources, Beam *beam, emittingSamplers_t &emittingSamplers, size_t index=0)
void configureImageChargeFromSources (const std::vector< std::vector< EmissionSource * > > &emissionSourcesLists)
Configure image-charge mode from all configured emission sources.
size_t computeTotalAllocationForBunch (Beam *beam, const std::vector< EmissionSource * > &sources) const
Private Attributes
std::unique_ptr< Tracker > itsTracker_m
std::vector< Distribution * > distrs_m
Distributions referenced by all emission sources (non-owning raw pointers).
FieldSolverCmd * fs_m
Samplers for time-dependent (emitting) sources; tracker calls emitParticles(t, dt) on each.
DataSink * ds_m
std::vector< std::unique_ptr< H5PartWrapper > > phaseSpaceSinks_m
OpalData * opal_m
std::unique_ptr< bunch_type > bunch_m
bool isFollowupTrack_m
RunMethod method_m
Object * itsParent
std::string itsName
std::string itsHelp
int occurrence
double timeStamp
std::set< Invalidator * > references
bool sharedFlag
Static Private Attributes
static const BiMap< RunMethod, std::string > stringMethod_s
Detailed Description
Definition at line 45 of file TrackRun.h.
Member Typedef Documentation
bunch_type
using TrackRun::bunch_type = PartBunch_t private
Definition at line 143 of file TrackRun.h.
emittingSamplers_t
using TrackRun::emittingSamplers_t = std::vector<std::shared_ptr<SamplingBase>> private
Definition at line 46 of file TrackRun.h.
Member Enumeration Documentation
RunMethod
enum class TrackRun::RunMethod : unsigned short strong private
Enumerator
NONE
PARALLEL
Definition at line 66 of file TrackRun.h.
Constructor & Destructor Documentation
TrackRun() [1/3]
TrackRun::TrackRun ()
Exemplar constructor.
Definition at line 179 of file TrackRun.cpp.
References Action::Action(), TRACKRUN::BOUNDARYGEOMETRY, ds_m, TRACKRUN::FIELDSOLVER, fs_m, OpalData::getInstance(), isFollowupTrack_m, Object::itsAttr, itsTracker_m, Attributes::makeBool(), Attributes::makePredefinedString(), Attributes::makeReal(), Attributes::makeString(), TRACKRUN::METHOD, method_m, NONE, opal_m, phaseSpaceSinks_m, Object::registerOwnership(), SIZE, AttributeHandler::SUB_COMMAND, TRACKRUN::TRACKBACK, and TRACKRUN::TURNS.
Referenced by clone(), operator=(), TrackRun(), and TrackRun().
~TrackRun()
TrackRun::~TrackRun () virtual
Definition at line 239 of file TrackRun.cpp.
TrackRun() [2/3]
TrackRun::TrackRun (const TrackRun &) private
References TrackRun().
TrackRun() [3/3]
TrackRun::TrackRun (const std::string & name, TrackRun * parent) private
Definition at line 211 of file TrackRun.cpp.
References Action::Action(), ds_m, fs_m, OpalData::getInstance(), isFollowupTrack_m, itsTracker_m, method_m, NONE, nr, opal_m, phaseSpaceSinks_m, and TrackRun().
Member Function Documentation
borrowedPhaseSpaceSinks()
std::vector< H5PartWrapper * > TrackRun::borrowedPhaseSpaceSinks () const private
Definition at line 548 of file TrackRun.cpp.
References phaseSpaceSinks_m.
Referenced by initDataSink().
canReplaceBy()
bool Action::canReplaceBy (Object * object) virtual inherited
Test if replacement is allowed.
Reimplemented from Object.
Definition at line 26 of file Action.cpp.
References Object::Object().
clear()
void Object::clear () inherited
Clear the occurrence counter.
Definition at line 285 of file Object.cpp.
References occurrence.
clone()
TrackRun * TrackRun::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 241 of file TrackRun.cpp.
References TrackRun().
computeTotalAllocationForBunch()
size_t TrackRun::computeTotalAllocationForBunch (Beam * beam, const std::vector< EmissionSource * > & sources) const private
Compute total number of macroparticles for the bunch from BEAM::NALLOC and optional per-distribution NPARTDIST values on the emission sources.
Definition at line 624 of file TrackRun.cpp.
References Distribution::find(), Beam::getNumAlloc(), and gmsg.
Referenced by execute().
configureImageChargeFromSources()
void TrackRun::configureImageChargeFromSources (const std::vector< std::vector< EmissionSource * > > & emissionSourcesLists) private
Configure image-charge mode from all configured emission sources.
Scans all sources across all selected beams for ZEROFACE_R0Z=true. If exactly one source requests zero-face handling, image-charge mode is enabled and the mirror plane is set to that source's R0Z. The same source also provides ZEROFACEPLANEDUMP, which controls diagnostic potential-plane dumping frequency (0 disables dumping). If none request it, image-charge mode is disabled.
Parameters
emissionSourcesLists Per-beam source lists assembled during RUN setup.
Exceptions
OpalException If more than one source requests ZEROFACE_R0Z=true.
Definition at line 744 of file TrackRun.cpp.
References bunch_m, and fs_m.
Referenced by execute().
copyAttributes()
void Object::copyAttributes (const Object & source) inherited
Copy attributes from another object.
Definition at line 50 of file Object.cpp.
References itsAttr, and Object().
Referenced by LineTemplate::makeInstance(), and SequenceTemplate::makeInstance().
execute()
void TrackRun::execute () virtual
Execute the command.
Reimplemented from Object.
Definition at line 243 of file TrackRun.cpp.
References Track::block, bunch_m, Versions::changes, computeTotalAllocationForBunch(), configureImageChargeFromSources(), ds_m, EmissionSourceList::fetchSources(), TRACKRUN::FIELDSOLVER, Beam::find(), EmissionSourceList::find(), FieldSolverCmd::find(), fs_m, Beam::getCharge(), Beam::getChargePerParticle(), Beam::getEmissionSourceListName(), Beam::getMassPerParticle(), Attributes::getString(), gmsg, initDataSink(), isFollowupTrack_m, Object::itsAttr, itsTracker_m, method_m, opal_m, PARALLEL, Physics::q_e, setRunMethod(), setupBoundaryGeometry(), setupDistributionsAndSamplers(), setupGlobalProcesses(), Options::version, and wireDaughterContainers().
findAttribute() [1/2]
Attribute * Object::findAttribute (const std::string & name) virtual inherited
Find an attribute by name.
Definition at line 56 of file Object.cpp.
References itsAttr.
Referenced by OpalElement::getParticleMatterInteraction(), OpalElement::getTypeName(), OpalElement::getWakeF(), Line::parse(), parse(), OpalElement::parse(), OpalParser::parseAssign(), SequenceParser::parsePosition(), TrackRun::print(), and TEST().
findAttribute() [2/2]
const Attribute * Object::findAttribute (const std::string & name) const virtual inherited
Find an attribute by name.
Definition at line 63 of file Object.cpp.
References itsAttr.
getBaseObject()
const Object * Object::getBaseObject () const inherited
Return the object's base type object.
Definition at line 260 of file Object.cpp.
References itsParent, and Object().
getCategory()
const std::string Action::getCategory () const virtual inherited
Return the object category as a string.
Implements Object.
Definition at line 28 of file Action.cpp.
getOpalName()
const std::string & Object::getOpalName () const inherited
Return object name.
Definition at line 267 of file Object.cpp.
References itsName.
Referenced by Macro::clone(), OpalVariableRFCavity::clone(), OpalData::create(), OpalData::define(), Sequence::findDriftLength(), ValueDefinition::getBool(), ValueDefinition::getBoolComponent(), ValueDefinition::getReal(), ValueDefinition::getRealComponent(), ValueDefinition::getString(), ValueDefinition::getStringComponent(), LineTemplate::makeInstance(), makeInstance(), SequenceTemplate::makeInstance(), parse(), SequenceParser::parsePosition(), Beam::print(), BoolConstant::print(), Line::print(), print(), OpalElement::print(), OpalFilter::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), Sequence::print(), StringConstant::print(), TrackRun::print(), BinningCmd::printInfo(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), registerOwnership(), OpalElement::registerOwnership(), Line::replace(), Sequence::replace(), PartBunch< T, Dim >::setBins(), TEST(), TEST(), TEST(), TEST_F(), Beam::update(), BoundaryGeometry::update(), OpalFilter::update(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), and OpalSplineTimeDependence::update().
getParent()
Object * Object::getParent () const inherited
Return parent pointer.
Definition at line 269 of file Object.cpp.
References itsParent, and Object().
Referenced by OpalData::erase(), print(), OpalElement::print(), registerOwnership(), and OpalElement::registerOwnership().
getRunMethodName()
std::string TrackRun::getRunMethodName () const private
Definition at line 504 of file TrackRun.cpp.
References method_m, and stringMethod_s.
Referenced by print().
increment()
int Object::increment () inherited
Increment and return the occurrence counter.
Definition at line 287 of file Object.cpp.
References occurrence.
Referenced by Line::parse(), and Sequence::storeLine().
initDataSink()
void TrackRun::initDataSink (size_t numParticleContainers) private
Definition at line 506 of file TrackRun.cpp.
References borrowedPhaseSpaceSinks(), DataSink::changeH5Wrappers(), DataSink::diagnosticStemForContainer(), ds_m, OpalData::getInstance(), isFollowupTrack_m, opal_m, and phaseSpaceSinks_m.
Referenced by execute().
isBuiltin()
bool Object::isBuiltin () const inherited
True, if [b]this[/b] is a built-in object.
Definition at line 243 of file Object.cpp.
References builtin.
Referenced by OpalData::define(), and OpalData::getVariableNames().
isDirty()
bool Object::isDirty () const inherited
True, if the [b]modified[/b] flag is set.
Definition at line 254 of file Object.cpp.
References modified.
isFlagged()
bool Object::isFlagged () const inherited
True, if [b]this[/b] is flagged by setFlag(true).
Definition at line 258 of file Object.cpp.
References flagged.
isShared()
bool Object::isShared () const virtual inherited
Shared flag.
Definition at line 245 of file Object.cpp.
References sharedFlag.
Referenced by Sequence::print().
isTreeMember()
bool Object::isTreeMember (const Object * subTree) const inherited
Test for tree membership.
Definition at line 271 of file Object.cpp.
References Object().
Referenced by Selector::handleElement(), and OpalParser::parseAssign().
makeInstance()
Object * Object::makeInstance (const std::string & name, Statement & , const Parser *) virtual inherited
Macro handler function.
Reimplemented in LineTemplate, MacroCmd, and SequenceTemplate.
Definition at line 76 of file Object.cpp.
References getOpalName(), and Object().
Referenced by OpalParser::parseDefine(), and OpalParser::parseMacro().
makeTemplate()
Object * Object::makeTemplate (const std::string & name, TokenStream & , Statement &) virtual inherited
Macro handler function.
Reimplemented in Line, LineTemplate, MacroCmd, Sequence, and SequenceTemplate.
Definition at line 71 of file Object.cpp.
References Object().
Referenced by OpalParser::parseMacro().
occurrenceCount()
int Object::occurrenceCount () inherited
Return the occurrence counter.
Definition at line 289 of file Object.cpp.
References occurrence.
operator=()
void TrackRun::operator= (const TrackRun &) private
References TrackRun().
parse()
void Object::parse (Statement & stat) virtual inherited
Parse the object.
Reimplemented in Call, Echo, EmissionSourceList, Help, Line, OpalElement, PSystem, Sequence, System, Title, and Value.
Definition at line 82 of file Object.cpp.
References Statement::delimiter(), findAttribute(), getOpalName(), Expressions::parseDelimiter(), Expressions::parseRealConst(), and Expressions::parseString().
Referenced by Sequence::parse(), OpalParser::parseAction(), OpalParser::parseDefine(), and SequenceTemplate::parseTemplate().
parseShortcut()
void Object::parseShortcut (Statement & stat, bool eval = true) virtual inherited
Parser for single-attribute commands.
Definition at line 113 of file Object.cpp.
Referenced by Call::parse(), Echo::parse(), Help::parse(), PSystem::parse(), System::parse(), Title::parse(), and Value::parse().
print() [1/2]
Inform & TrackRun::print (Inform & os) const
Definition at line 853 of file TrackRun.cpp.
References Track::block, Beam::find(), Beam::getChargePerParticle(), Beam::getMassPerParticle(), getRunMethodName(), isFollowupTrack_m, Options::psDumpFreq, and Options::statDumpFreq.
Referenced by operator<<().
print() [2/2]
void Object::print (std::ostream & msg) const virtual
Print the object.
Reimplemented from Object.
Definition at line 114 of file Object.cpp.
References Statement::delimiter(), Object::findAttribute(), Object::getOpalName(), Statement::mark(), and Statement::word().
printHelp()
void Object::printHelp (std::ostream &) const virtual inherited
Print help.
Definition at line 179 of file Object.cpp.
References gmsg, itsAttr, and itsHelp.
Referenced by Help::execute(), and main().
printValue()
void Object::printValue (std::ostream & os) const inline virtual inherited
Reimplemented in BoolConstant, RealConstant, RealVariable, RealVector, and StringConstant.
Definition at line 270 of file Object.h.
References print().
registerOwnership()
void Object::registerOwnership (const AttributeHandler::OwnerType & itsClass) const inherited
Definition at line 169 of file Object.cpp.
References AttributeHandler::addAttributeOwner(), getOpalName(), getParent(), and itsAttr.
Referenced by Beam::Beam(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), Call::Call(), Distribution::Distribution(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), EmissionSourceList::EmissionSourceList(), Help::Help(), Line::Line(), OpalFilter::OpalFilter(), Option::Option(), PSystem::PSystem(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVector::RealVector(), Select::Select(), Sequence::Sequence(), StringConstant::StringConstant(), System::System(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), and Value::Value().
registerReference()
void Object::registerReference (Invalidator * a) inherited
Register a reference to this object.
Definition at line 165 of file Object.cpp.
References references.
replace()
void Object::replace (Object * oldObject, Object * newObject) virtual inherited
Replace references.
Reimplemented in Line, and Sequence.
Definition at line 235 of file Object.cpp.
References Object().
setDirty()
void Object::setDirty (bool dirty) inherited
Set/reset the [b]modified[/b] flag.
Definition at line 249 of file Object.cpp.
References modified.
Referenced by OpalData::define(), OpalData::makeDirty(), and RealVariable::RealVariable().
setFlag()
void Object::setFlag (bool flag) inherited
Flag/unflag this object, e. g. to control output of objects for.
Definition at line 256 of file Object.cpp.
References flagged.
setOpalName()
void Object::setOpalName (const std::string & name) inherited
Set object name.
Definition at line 281 of file Object.cpp.
References itsName.
Referenced by TEST(), TEST(), TEST(), Beam::update(), BoundaryGeometry::update(), and OpalFilter::update().
setParent()
void Object::setParent (Object * parent) inherited
Set parent object.
Definition at line 283 of file Object.cpp.
References itsParent, and Object().
Referenced by OpalData::erase().
setRunMethod()
void TrackRun::setRunMethod () private
Definition at line 491 of file TrackRun.cpp.
References Attributes::getString(), Object::itsAttr, TRACKRUN::METHOD, method_m, and stringMethod_s.
Referenced by execute().
setShared()
void Object::setShared (bool flag) virtual inherited
Set/reset shared flag.
Reimplemented in Element.
Definition at line 247 of file Object.cpp.
References sharedFlag.
Referenced by OpalParser::parseDefine(), and Element::setShared().
setupBoundaryGeometry()
void TrackRun::setupBoundaryGeometry () private
Definition at line 557 of file TrackRun.cpp.
References TRACKRUN::BOUNDARYGEOMETRY, BoundaryGeometry::clone(), BoundaryGeometry::find(), OpalData::getInstance(), Attributes::getString(), Object::itsAttr, and OpalData::setGlobalGeometry().
Referenced by execute().
setupDistributionsAndSamplers()
void TrackRun::setupDistributionsAndSamplers (const std::vector< EmissionSource * > & sources, Beam * beam, emittingSamplers_t & emittingSamplers, size_t index = 0) private
Build samplers for all emission sources, perform initial sampling for t0 == 0 sources, and populate emittingSamplers_m for time-dependent or delayed sources. Applied to particle container [index]
Definition at line 649 of file TrackRun.cpp.
References bunch_m, distrs_m, Distribution::emitting_m, Distribution::find(), FLATTOP, FROMFILE, GAUSS, Beam::getMass(), Beam::getMomentum(), Distribution::getNumParticles(), Distribution::getType(), Distribution::getTypeofDistribution(), gmsg, Beam::hasExplicitEnergy(), MULTIVARIATEGAUSS, nr, Distribution::setAvrgPz(), Distribution::setDist(), and Distribution::setDistType().
Referenced by execute().
setupGlobalProcesses()
void TrackRun::setupGlobalProcesses (std::vector< std::vector< std::unique_ptr< GlobalProcess > > > globalProcessesLists) private
Attach prebuilt global process vector to each particle container.
Definition at line 570 of file TrackRun.cpp.
References bunch_m.
Referenced by execute().
shouldTrace()
bool Action::shouldTrace () const virtual inherited
Trace flag.
Implements Object.
Definition at line 30 of file Action.cpp.
shouldUpdate()
bool Action::shouldUpdate () const virtual inherited
Update flag.
Implements Object.
Definition at line 32 of file Action.cpp.
unregisterReference()
void Object::unregisterReference (Invalidator * a) inherited
Unegister a reference to this object.
Definition at line 167 of file Object.cpp.
References references.
update()
void Object::update () virtual inherited
Update this object.
Reimplemented in Beam, BinningCmd, BoundaryGeometry, FieldSolverCmd, OpalCavity, OpalConstantEFieldCavity, OpalDrift, OpalElement, OpalFilter, OpalLaser, OpalMarker, OpalMonitor, OpalMultipole, OpalMultipoleT, OpalPolynomialTimeDependence, OpalProbe, OpalQuadrupole, OpalRBend, OpalRingDefinition, OpalSBend, OpalSinusoidalTimeDependence, OpalSolenoid, OpalSource, OpalSplineTimeDependence, OpalTravelingWave, OpalVacuum, OpalVariableRFCavity, OpalVerticalFFAMagnet, Option, and Sequence.
Definition at line 239 of file Object.cpp.
Referenced by Distribution::execute().
wireDaughterContainers()
void TrackRun::wireDaughterContainers (const std::vector< Beam * > & beams) private
Wire daughter containers to cross-container processes (e.g. muon decay -> electron).
Note
Must be called after setupGlobalProcesses — reads processes from the containers.
Definition at line 587 of file TrackRun.cpp.
References Track::block, bunch_m, and gmsg.
Referenced by execute().
Member Data Documentation
builtin
bool Object::builtin protected inherited
Built-in flag.
Definition at line 226 of file Object.h.
Referenced by Beam::Beam(), BoundaryGeometry::BoundaryGeometry(), isBuiltin(), Object(), Object(), OpalFilter::OpalFilter(), OpalMarker::OpalMarker(), RealConstant::RealConstant(), StringConstant::StringConstant(), and Table::~Table().
bunch_m
std::unique_ptr<bunch_type> TrackRun::bunch_m private
Definition at line 144 of file TrackRun.h.
Referenced by configureImageChargeFromSources(), execute(), setupDistributionsAndSamplers(), setupGlobalProcesses(), and wireDaughterContainers().
distrs_m
std::vector<Distribution*> TrackRun::distrs_m private
Distributions referenced by all emission sources (non-owning raw pointers).
Definition at line 125 of file TrackRun.h.
Referenced by setupDistributionsAndSamplers().
ds_m
DataSink* TrackRun::ds_m private
Definition at line 132 of file TrackRun.h.
Referenced by execute(), initDataSink(), TrackRun(), and TrackRun().
flagged
bool Object::flagged protected inherited
Object flag.
Definition at line 235 of file Object.h.
Referenced by isFlagged(), Object(), Object(), and setFlag().
fs_m
FieldSolverCmd* TrackRun::fs_m private
Samplers for time-dependent (emitting) sources; tracker calls emitParticles(t, dt) on each.
Definition at line 130 of file TrackRun.h.
Referenced by configureImageChargeFromSources(), execute(), TrackRun(), and TrackRun().
isFollowupTrack_m
bool TrackRun::isFollowupTrack_m private
Definition at line 146 of file TrackRun.h.
Referenced by execute(), initDataSink(), print(), TrackRun(), and TrackRun().
itsAttr
std::vector<Attribute> Object::itsAttr inherited
The object attributes.
Definition at line 210 of file Object.h.
Referenced by Beam::Beam(), BinningCmd::BinningCmd(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), BoundaryGeometry::BoundaryGeometry(), DumpEMFields::buildGrid(), Call::Call(), FieldSolverCmd::constructBCHandler(), copyAttributes(), Distribution::Distribution(), BinningCmd::dumpBinsToFile(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), Beam::execute(), Call::execute(), Echo::execute(), Help::execute(), Option::execute(), PSystem::execute(), Select::execute(), System::execute(), Title::execute(), TrackCmd::execute(), TrackRun::execute(), Value::execute(), FieldSolverCmd::FieldSolverCmd(), findAttribute(), findAttribute(), BoundaryGeometry::getA(), OpalElement::getApert(), BoundaryGeometry::getB(), BinningCmd::getBinningAlpha(), BinningCmd::getBinningBeta(), FieldSolverCmd::getBinsName(), BoolConstant::getBool(), FieldSolverCmd::getBoxIncr(), Beam::getBunchCharge(), BoundaryGeometry::getC(), Beam::getCharge(), Beam::getCurrent(), Beam::getDaughterBeamName(), BinningCmd::getDesiredWidth(), EmissionSource::getDistributionName(), FieldSolverCmd::getDomDec(), TrackCmd::getDT(), TrackCmd::getDTAU(), TrackCmd::getDTSCINIT(), BinningCmd::getDumpBinsFileName(), BinningCmd::getDumpBinsFrequency(), EmissionSource::getEmissionModel(), Beam::getEmissionSourceListName(), BoundaryGeometry::getFilename(), Distribution::getFilename(), Beam::getFrequency(), Beam::getGlobalProcessNames(), BoundaryGeometry::getL1(), BoundaryGeometry::getL2(), BoundaryGeometry::getLength(), Line::getLength(), OpalElement::getLength(), Sequence::getLength(), Beam::getMass(), BinningCmd::getMaxBins(), TrackCmd::getMaxSteps(), Beam::getNumAlloc(), FieldSolverCmd::getNX(), FieldSolverCmd::getNY(), FieldSolverCmd::getNZ(), EmissionSource::getP0(), BinningCmd::getParameter(), Beam::getParticleName(), EmissionSource::getR0(), RealConstant::getReal(), RealVariable::getReal(), RealVector::getRealComponent(), Sequence::getReference(), BoundaryGeometry::getS(), EmissionSource::getShiftedGreensFunction(), TrackCmd::getStepsPerTurn(), StringConstant::getString(), EmissionSource::getT0(), TrackCmd::getT0(), BinningCmd::getTablePrintFrequency(), TrackCmd::getTimeIntegrator(), BoundaryGeometry::getTopology(), FieldSolverCmd::getType(), EmissionSource::getZerofaceMaxSteps(), EmissionSource::getZeroFacePlaneDumpFrequency(), EmissionSource::getZeroFaceR0Z(), TrackCmd::getZStart(), TrackCmd::getZStop(), Beam::hasExplicitEnergy(), Help::Help(), BoundaryGeometry::initialize(), OpalFilter::initOpalFilter(), Beam::isPhoton(), Line::Line(), Object(), Object(), OpalBend::OpalBend(), OpalCavity::OpalCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalDrift::OpalDrift(), OpalElement::OpalElement(), OpalFilter::OpalFilter(), OpalLaser::OpalLaser(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalPolynomialTimeDependence::OpalPolynomialTimeDependence(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalRingDefinition::OpalRingDefinition(), OpalSinusoidalTimeDependence::OpalSinusoidalTimeDependence(), OpalSolenoid::OpalSolenoid(), OpalSplineTimeDependence::OpalSplineTimeDependence(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), Option::Option(), Option::Option(), Line::parse(), Sequence::parse(), DumpEMFields::parseCoordinateSystem(), Beam::print(), BoolConstant::print(), DumpEMFields::print(), print(), OpalFilter::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), Sequence::print(), StringConstant::print(), printHelp(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), BoolConstant::printValue(), RealConstant::printValue(), RealVariable::printValue(), RealVector::printValue(), StringConstant::printValue(), PSystem::PSystem(), RealConstant::RealConstant(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVariable::RealVariable(), RealVector::RealVector(), registerOwnership(), OpalElement::registerOwnership(), Select::Select(), Select::select(), Sequence::Sequence(), Distribution::setAttributes(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCX(), OrbitThreaderTest::TestableFieldSolverCmd::setBCX(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCX(), TestMultipoleT::TestableFieldSolverCmd::setBCX(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCX(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCX(), TestVariableRFCavity::TestableFieldSolverCmd::setBCX(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCY(), OrbitThreaderTest::TestableFieldSolverCmd::setBCY(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCY(), TestMultipoleT::TestableFieldSolverCmd::setBCY(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCY(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCY(), TestVariableRFCavity::TestableFieldSolverCmd::setBCY(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCZ(), OrbitThreaderTest::TestableFieldSolverCmd::setBCZ(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCZ(), TestMultipoleT::TestableFieldSolverCmd::setBCZ(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCZ(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCZ(), TestVariableRFCavity::TestableFieldSolverCmd::setBCZ(), TestableBinningCmd::setBinningAlpha(), TestableBinningCmd::setBinningBeta(), TestableBinningCmd::setDesiredWidth(), Distribution::setDistParametersFlatTop(), Distribution::setDistParametersMultiVariateGauss(), Distribution::setDistType(), TestableBinningCmd::setDumpBinsFile(), TestableBinningCmd::setDumpBinsFreq(), TestableBinningCmd::setMaxBins(), FieldSolverCmd::setNX(), FieldSolverCmd::setNY(), FieldSolverCmd::setNZ(), TestableBinningCmd::setParameterString(), TrackRun::setRunMethod(), Distribution::setSigmaP_m(), Distribution::setSigmaR_m(), TestableBinningCmd::setTablePrintFrequency(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setType(), OrbitThreaderTest::TestableFieldSolverCmd::setType(), SolenoidPlacementTest::TestableFieldSolverCmd::setType(), TestMultipoleT::TestableFieldSolverCmd::setType(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setType(), TestMultipoleTStraight::TestableFieldSolverCmd::setType(), TestVariableRFCavity::TestableFieldSolverCmd::setType(), TrackRun::setupBoundaryGeometry(), StringConstant::StringConstant(), StringConstant::StringConstant(), System::System(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), Beam::update(), BinningCmd::update(), FieldSolverCmd::update(), OpalCavity::update(), OpalConstantEFieldCavity::update(), OpalDrift::update(), OpalElement::update(), OpalLaser::update(), OpalMonitor::update(), OpalMultipole::update(), OpalMultipoleT::update(), OpalPolynomialTimeDependence::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalRBend::update(), OpalRingDefinition::update(), OpalSBend::update(), OpalSinusoidalTimeDependence::update(), OpalSolenoid::update(), OpalSplineTimeDependence::update(), OpalTravelingWave::update(), OpalVacuum::update(), OpalVariableRFCavity::update(), OpalVerticalFFAMagnet::update(), Option::update(), OpalElement::updateUnknown(), Value::Value(), ValueDefinition::value(), and ValueDefinition::value().
itsHelp
std::string Object::itsHelp private inherited
Definition at line 250 of file Object.h.
Referenced by Object(), Object(), and printHelp().
itsName
std::string Object::itsName private inherited
Definition at line 247 of file Object.h.
Referenced by getOpalName(), Object(), Object(), and setOpalName().
itsParent
Object* Object::itsParent private inherited
Definition at line 244 of file Object.h.
Referenced by getBaseObject(), getParent(), Object(), Object(), and setParent().
itsTracker_m
std::unique_ptr<Tracker> TrackRun::itsTracker_m private
Definition at line 122 of file TrackRun.h.
Referenced by execute(), TrackRun(), and TrackRun().
method_m
RunMethod TrackRun::method_m private
Definition at line 148 of file TrackRun.h.
Referenced by execute(), getRunMethodName(), setRunMethod(), TrackRun(), and TrackRun().
modified
bool Object::modified protected inherited
Dirty flag.
Definition at line 231 of file Object.h.
Referenced by isDirty(), Object(), Object(), and setDirty().
occurrence
int Object::occurrence private inherited
Definition at line 253 of file Object.h.
Referenced by clear(), increment(), Object(), Object(), and occurrenceCount().
opal_m
OpalData* TrackRun::opal_m private
Definition at line 136 of file TrackRun.h.
Referenced by execute(), initDataSink(), TrackRun(), and TrackRun().
phaseSpaceSinks_m
std::vector<std::unique_ptr<H5PartWrapper> > TrackRun::phaseSpaceSinks_m private
Definition at line 134 of file TrackRun.h.
Referenced by borrowedPhaseSpaceSinks(), initDataSink(), TrackRun(), and TrackRun().
references
std::set<Invalidator*> Object::references private inherited
Definition at line 260 of file Object.h.
Referenced by registerReference(), unregisterReference(), and ~Object().
sharedFlag
bool Object::sharedFlag private inherited
Definition at line 263 of file Object.h.
Referenced by isShared(), Object(), Object(), and setShared().
stringMethod_s
const BiMap< TrackRun::RunMethod, std::string > TrackRun::stringMethod_s static private
Initial value:
= []() {
    BiMap<TrackRun::RunMethod, std::string> bimap;
    bimap.insert(TrackRun::RunMethod::PARALLEL, "PARALLEL");
    return bimap;
}()
Definition at line 173 of file TrackRun.h.
Referenced by getRunMethodName(), and setRunMethod().
timeStamp
double Object::timeStamp private inherited
Definition at line 256 of file Object.h.
The documentation for this class was generated from the following files:
TrackRun.h
TrackRun.cpp