OPALX (Object Oriented Parallel Accelerator Library for Exascal): SequenceParser Class Reference
SequenceParser Class Reference
The parser for SEQUENCE members.
#include <SequenceParser.h>
Classes
struct Reference
Public Member Functions
SequenceParser (Sequence *)
Constructor.
virtual ~SequenceParser ()
virtual void parse (Statement &) const
Parse sequence member.
virtual Statement * readStatement (TokenStream *) const
Read complete statement from a token stream.
virtual void run () const
Read current stream.
virtual void run (TokenStream *) const
Read given stream.
void stop () const
Set stop flag.
Static Public Member Functions
static Token readToken ()
Return next input token.
Protected Member Functions
void execute (Object *, const std::string &) const
Execute or check the current command.
virtual Object * find (const std::string &) const
Find object by name in the main directory.
virtual void parseAction (Statement &) const
Parse executable command.
virtual void parseAssign (Statement &) const
Parse assignment statement.
virtual void parseDefine (Statement &) const
Parse definition.
virtual void parseEnd (Statement &) const
Check for end of statement.
virtual void parseMacro (const std::string &name, Statement &) const
Parse macro definition or call.
virtual void printHelp (const std::string &) const
Print help on named command.
Private Types
typedef std::list< Reference > RefList
typedef Sequence::TLine TLine
Private Member Functions
SequenceParser ()
SequenceParser (const SequenceParser &)
void operator= (const SequenceParser &)
void fillPositions () const
void findFromPositions () const
void findNeighbourPositions () const
void parseMember (Statement &) const
void parsePosition (Statement &, Object &, bool defined) const
Static Private Member Functions
static void parseBracketList (char close, Statement &)
static void parseTokenList (Statement &)
static std::string getHint (const std::string &, const std::string &="attribute")
Private Attributes
Sequence * itsSequence
bool okFlag
RefList references
TLine itsLine
bool stopFlag
Static Private Attributes
static std::vector< std::shared_ptr< TokenStream > > inputStack
Detailed Description
The parser for SEQUENCE members.
Definition at line 40 of file SequenceParser.h.
Member Typedef Documentation
RefList
typedef std::list<Reference> SequenceParser::RefList private
Definition at line 71 of file SequenceParser.h.
TLine
typedef Sequence::TLine SequenceParser::TLine private
Definition at line 74 of file SequenceParser.h.
Constructor & Destructor Documentation
SequenceParser() [1/3]
SequenceParser::SequenceParser (Sequence * seq)
Constructor.
Definition at line 37 of file SequenceParser.cpp.
~SequenceParser()
SequenceParser::~SequenceParser () virtual
Definition at line 42 of file SequenceParser.cpp.
SequenceParser() [2/3]
SequenceParser::SequenceParser () private
SequenceParser() [3/3]
SequenceParser::SequenceParser (const SequenceParser &) private
Member Function Documentation
execute()
void OpalParser::execute (Object * object, const std::string & name) const protected inherited
Execute or check the current command.
Definition at line 118 of file OpalParser.cpp.
References OpalData::getInstance(), gmsg, Options::mtrace, Object::shouldTrace(), Object::shouldUpdate(), and OpalData::update().
Referenced by OpalParser::parseAction(), OpalParser::parseDefine(), and OpalParser::parseMacro().
fillPositions()
void SequenceParser::fillPositions () const private
Definition at line 85 of file SequenceParser.cpp.
References SequenceMember::ABSOLUTE, findFromPositions(), findNeighbourPositions(), and references.
Referenced by parse().
find()
Object * OpalParser::find (const std::string & name) const protected virtual inherited
Find object by name in the main directory.
Reimplemented in TrackParser.
Definition at line 142 of file OpalParser.cpp.
References OpalData::find(), and OpalData::getInstance().
Referenced by OpalParser::parse(), OpalParser::parseAction(), OpalParser::parseAssign(), OpalParser::parseDefine(), OpalParser::parseMacro(), parseMember(), and OpalParser::printHelp().
findFromPositions()
void SequenceParser::findFromPositions () const private
Definition at line 117 of file SequenceParser.cpp.
References Sequence::findNamedPosition(), itsLine, itsSequence, and references.
Referenced by fillPositions().
findNeighbourPositions()
void SequenceParser::findNeighbourPositions () const private
Definition at line 131 of file SequenceParser.cpp.
References SequenceMember::ABSOLUTE, SequenceMember::DRIFT, SequenceMember::END, Element::find(), Object::findAttribute(), SequenceParser::Reference::fromPosition, Element::getLength(), Object::getOpalName(), Attributes::getReal(), Attributes::getString(), SequenceMember::IMMEDIATE, Element::IS_CENTRE, Element::IS_ENTRY, Element::IS_EXIT, SequenceMember::itsFlag, itsLine, itsSequence, SequenceMember::NEXT, SequenceMember::PREVIOUS, and references.
Referenced by fillPositions().
getHint()
std::string OpalParser::getHint (const std::string & name, const std::string & type = "attribute") static private inherited
Definition at line 623 of file OpalParser.cpp.
References AttributeHandler::COMMAND, AttributeHandler::ELEMENT, AttributeHandler::getOwner(), AttributeHandler::STATEMENT, and AttributeHandler::SUB_COMMAND.
Referenced by OpalParser::parse(), and OpalParser::parseAction().
operator=()
void SequenceParser::operator= (const SequenceParser &) private
parse()
void SequenceParser::parse (Statement & stat) const virtual
Parse sequence member.
Reimplemented from OpalParser.
Definition at line 46 of file SequenceParser.cpp.
References Sequence::addEndMarkers(), fillPositions(), OpalData::getInstance(), Sequence::insertDrifts(), itsLine, itsSequence, Statement::keyword(), OpalData::makeDirty(), okFlag, OpalParser::parseEnd(), parseMember(), Statement::start(), OpalParser::stop(), and Sequence::storeLine().
parseAction()
void OpalParser::parseAction (Statement & stat) const protected virtual inherited
Parse executable command.
Definition at line 146 of file OpalParser.cpp.
References Object::clone(), Statement::delimiter(), OpalParser::execute(), OpalParser::find(), OpalParser::getHint(), Object::parse(), OpalParser::parseEnd(), Expressions::parseString(), OpalParser::printHelp(), Statement::start(), and OpalParser::stopFlag.
Referenced by OpalParser::parse().
parseAssign()
void OpalParser::parseAssign (Statement & stat) const protected virtual inherited
Parse assignment statement.
Definition at line 179 of file OpalParser.cpp.
References Object::clone(), OpalData::define(), Statement::delimiter(), OpalParser::find(), OpalData::find(), Object::findAttribute(), OpalData::getInstance(), Object::isTreeMember(), Statement::keyword(), OpalData::makeDirty(), Expressions::parseDelimiter(), OpalParser::parseEnd(), Expressions::parseRealConst(), Expressions::parseString(), and Statement::start().
Referenced by OpalParser::parse().
parseBracketList()
void OpalParser::parseBracketList (char close, Statement & stat) static private inherited
Definition at line 437 of file OpalParser.cpp.
References Statement::append(), Token::isDel(), Token::isEOF(), OpalParser::parseBracketList(), and OpalParser::readToken().
Referenced by OpalParser::parseBracketList(), OpalParser::parseTokenList(), and OpalParser::readStatement().
parseDefine()
void OpalParser::parseDefine (Statement & stat) const protected virtual inherited
Parse definition.
Definition at line 312 of file OpalParser.cpp.
References Object::clone(), OpalData::define(), Statement::delimiter(), OpalParser::execute(), OpalParser::find(), OpalData::getInstance(), Statement::keyword(), Object::makeInstance(), Object::parse(), OpalParser::parseEnd(), Expressions::parseString(), Object::setShared(), and Statement::start().
Referenced by OpalParser::parse().
parseEnd()
void OpalParser::parseEnd (Statement & stat) const protected virtual inherited
Check for end of statement.
Definition at line 359 of file OpalParser.cpp.
References Statement::atEnd(), Statement::delimiter(), Statement::position(), and Statement::print().
Referenced by parse(), OpalParser::parseAction(), OpalParser::parseAssign(), OpalParser::parseDefine(), and parseMember().
parseMacro()
void OpalParser::parseMacro (const std::string & name, Statement & stat) const protected virtual inherited
Parse macro definition or call.
Definition at line 372 of file OpalParser.cpp.
References OpalData::define(), Statement::delimiter(), OpalParser::execute(), OpalParser::find(), Statement::getCurrent(), OpalData::getInstance(), OpalParser::inputStack, Object::makeInstance(), Object::makeTemplate(), Statement::mark(), Expressions::parseString(), and Statement::restore().
Referenced by OpalParser::parse().
parseMember()
void SequenceParser::parseMember (Statement & stat) const private
Definition at line 234 of file SequenceParser.cpp.
References ElementBase::copyStructure(), OpalData::define(), Statement::delimiter(), OpalParser::find(), OpalData::getInstance(), Object::getOpalName(), SequenceMember::GLOBAL, itsLine, itsSequence, SequenceMember::itsType, SequenceMember::LOCAL, SequenceMember::OpalElement, OpalParser::parseEnd(), parsePosition(), Expressions::parseString(), ElmPtr::setElement(), and FlaggedElmPtr::setReflectionFlag().
Referenced by parse().
parsePosition()
void SequenceParser::parsePosition (Statement & stat, Object & elem, bool defined) const private
Definition at line 318 of file SequenceParser.cpp.
References SequenceMember::ABSOLUTE, Statement::delimiter(), SequenceMember::DRIFT, SequenceMember::END, Object::findAttribute(), SequenceMember::FROM, SequenceParser::Reference::fromName, Object::getOpalName(), SequenceMember::IMMEDIATE, SequenceMember::itsFlag, itsLine, SequenceParser::Reference::itsList, SequenceMember::itsPosition, Statement::keyword(), SequenceMember::NEXT, Expressions::parseDelimiter(), Expressions::parseRealConst(), Expressions::parseString(), SequenceMember::PREVIOUS, and references.
Referenced by parseMember().
parseTokenList()
void OpalParser::parseTokenList (Statement & stat) static private inherited
Definition at line 457 of file OpalParser.cpp.
References Statement::append(), Token::isDel(), Token::isEOF(), OpalParser::parseBracketList(), and OpalParser::readToken().
Referenced by OpalParser::readStatement().
printHelp()
void OpalParser::printHelp (const std::string & cmdName) const protected virtual inherited
Print help on named command.
Definition at line 427 of file OpalParser.cpp.
References OpalParser::find(), and gmsg.
Referenced by OpalParser::parse(), and OpalParser::parseAction().
readStatement()
Statement * OpalParser::readStatement (TokenStream * is) const virtual inherited
Read complete statement from a token stream.
Todo:
check this /stat->printWhere(*IpplInfo::Error, true);
Implements Parser.
Definition at line 486 of file OpalParser.cpp.
References Statement::append(), Token::getFile(), Token::getLine(), gmsg, OpalParser::inputStack, Token::isDel(), Token::isEOF(), Token::isKey(), Token::isString(), Token::isWord(), OpalParser::parseBracketList(), OpalParser::parseTokenList(), OpalParser::readStatement(), TokenStream::readToken(), Statement::start(), and OpalException::what().
Referenced by OpalParser::readStatement(), and OpalParser::run().
readToken()
Token OpalParser::readToken () static inherited
Return next input token.
Definition at line 478 of file OpalParser.cpp.
References OpalParser::inputStack, and Token::IS_EOF.
Referenced by OpalParser::parseBracketList(), and OpalParser::parseTokenList().
run() [1/2]
void OpalParser::run () const virtual inherited
Read current stream.
Definition at line 584 of file OpalParser.cpp.
References Statement::execute(), OpalParser::inputStack, OpalParser::readStatement(), OpalParser::stopFlag, OpalException::what(), and OpalException::where().
Referenced by Call::execute(), TrackCmd::execute(), main(), SequenceTemplate::makeInstance(), Sequence::parse(), and OpalParser::run().
run() [2/2]
void OpalParser::run (TokenStream * is) const virtual inherited
Read given stream.
Implements Parser.
Definition at line 613 of file OpalParser.cpp.
References OpalParser::inputStack, and OpalParser::run().
stop()
void OpalParser::stop () const inherited
Set stop flag.
Definition at line 619 of file OpalParser.cpp.
References OpalParser::stopFlag.
Referenced by TrackEnd::execute(), and parse().
Member Data Documentation
inputStack
std::vector< std::shared_ptr< TokenStream > > OpalParser::inputStack static private inherited
Definition at line 119 of file OpalParser.h.
Referenced by OpalParser::parseMacro(), OpalParser::readStatement(), OpalParser::readToken(), OpalParser::run(), and OpalParser::run().
itsLine
TLine SequenceParser::itsLine mutable private
Definition at line 106 of file SequenceParser.h.
Referenced by findFromPositions(), findNeighbourPositions(), parse(), parseMember(), and parsePosition().
itsSequence
Sequence* SequenceParser::itsSequence private
Definition at line 97 of file SequenceParser.h.
Referenced by findFromPositions(), findNeighbourPositions(), parse(), and parseMember().
okFlag
bool SequenceParser::okFlag mutable private
Definition at line 100 of file SequenceParser.h.
Referenced by parse().
references
RefList SequenceParser::references mutable private
Definition at line 103 of file SequenceParser.h.
Referenced by fillPositions(), findFromPositions(), findNeighbourPositions(), and parsePosition().
stopFlag
bool OpalParser::stopFlag mutable private inherited
Definition at line 116 of file OpalParser.h.
Referenced by OpalParser::parseAction(), OpalParser::run(), and OpalParser::stop().
The documentation for this class was generated from the following files:
SequenceParser.h
SequenceParser.cpp