OPALX (Object Oriented Parallel Accelerator Library for Exascal): ConstEzField Class Reference
ConstEzField Class Reference
#include <ConstEzField.h>
Public Member Functions
ConstEzField ()
Default constructor.
virtual ~ConstEzField ()
virtual EVector Efield (const Point3D &P) const
Get field.
virtual EVector Efield (const Point3D &P, double t) const
Get field.
virtual double getEz () const
Get component.
virtual void setEz (double)
Set component.
virtual void scale (double scalar)
Scale the field.
virtual BVector Bfield (const Point3D &P) const
Get field.
virtual BVector Bfield (const Point3D &P, double t) const
Get field.
virtual EBVectors EBfield (const Point3D &P) const
Get field.
virtual EBVectors EBfield (const Point3D &P, double t) const
Get field.
Static Public Attributes
static const EVector ZeroEfield
The constant representing a zero electric field.
static const BVector ZeroBfield
The constant representing a zero magnetic field.
static const EBVectors ZeroEBfield
The constant representing a zero electromagnetic field.
Private Attributes
double Ez
Detailed Description
Definition at line 23 of file ConstEzField.h.
Constructor & Destructor Documentation
ConstEzField()
ConstEzField::ConstEzField ()
Default constructor.
Definition at line 20 of file ConstEzField.cpp.
~ConstEzField()
ConstEzField::~ConstEzField () virtual
Definition at line 22 of file ConstEzField.cpp.
Member Function Documentation
Bfield() [1/2]
BVector EMField::Bfield (const Point3D & P) const virtual inherited
Get field.
Reimplemented in BDipoleField, BMultipoleField, ConstBzField, and OscillatingField< ConstEzField >.
Definition at line 121 of file EMField.cpp.
References EMField::ZeroBfield.
Referenced by Component::Bfield(), Component::Bfield(), EMField::Bfield(), and EMField::EBfield().
Bfield() [2/2]
BVector EMField::Bfield (const Point3D & P, double t) const virtual inherited
Get field.
Reimplemented in BDipoleField, BMultipoleField, ConstBzField, and OscillatingField< ConstEzField >.
Definition at line 125 of file EMField.cpp.
References EMField::Bfield().
EBfield() [1/2]
EBVectors EMField::EBfield (const Point3D & P) const virtual inherited
Get field.
Definition at line 127 of file EMField.cpp.
References EMField::Bfield(), and EMField::Efield().
Referenced by Component::EBfield(), Component::EBfield(), and EMField::EBfield().
EBfield() [2/2]
EBVectors EMField::EBfield (const Point3D & P, double t) const virtual inherited
Get field.
Definition at line 129 of file EMField.cpp.
References EMField::EBfield().
Efield() [1/2]
EVector ConstEzField::Efield (const Point3D & P) const virtual
Get field.
Reimplemented from EMField.
Reimplemented in OscillatingField< ConstEzField >.
Definition at line 24 of file ConstEzField.cpp.
References Ez.
Efield() [2/2]
EVector ConstEzField::Efield (const Point3D & P, double t) const virtual
Get field.
Reimplemented from EMField.
Reimplemented in OscillatingField< ConstEzField >.
Definition at line 26 of file ConstEzField.cpp.
References Ez.
getEz()
double ConstEzField::getEz () const virtual
Get component.
Definition at line 28 of file ConstEzField.cpp.
References Ez.
Referenced by RFCavityRep::getAmplitude(), and TravelingWaveRep::getAmplitude().
scale()
void ConstEzField::scale (double scalar) virtual
Scale the field.
Implements EMField.
Definition at line 32 of file ConstEzField.cpp.
References Ez.
setEz()
void ConstEzField::setEz (double value) virtual
Set component.
Definition at line 30 of file ConstEzField.cpp.
References Ez.
Referenced by RFCavityRep::setAmplitude(), TravelingWaveRep::setAmplitude(), and ConstantEFieldCavityRep::setEz().
Member Data Documentation
Ez
double ConstEzField::Ez private
Definition at line 53 of file ConstEzField.h.
Referenced by Efield(), Efield(), getEz(), scale(), and setEz().
ZeroBfield
const BVector EMField::ZeroBfield static inherited
The constant representing a zero magnetic field.
Definition at line 220 of file EMField.h.
Referenced by EMField::Bfield().
ZeroEBfield
const EBVectors EMField::ZeroEBfield static inherited
The constant representing a zero electromagnetic field.
Definition at line 223 of file EMField.h.
ZeroEfield
const EVector EMField::ZeroEfield static inherited
The constant representing a zero electric field.
Definition at line 217 of file EMField.h.
Referenced by EMField::Efield().
The documentation for this class was generated from the following files:
ConstEzField.h
ConstEzField.cpp