OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions::PtrToScalar< T > Class Template Reference
Expressions::PtrToScalar< T > Class Template Reference
A pointer to a scalar expression.
#include <Expressions.h>
Public Member Functions
PtrToScalar (Scalar< T > *rhs)
Constructor from an object just created.
PtrToScalar ()
PtrToScalar (const PtrToScalar &rhs)
PtrToScalar (PtrToScalar &&rhs) noexcept=default
~PtrToScalar ()
PtrToScalar & operator= (const PtrToScalar &)
PtrToScalar & operator= (PtrToScalar &&) noexcept=default
PtrToScalar & operator= (Scalar< T > *rhs)
Scalar< T > * operator-> () const
Scalar< T > & operator* () const
operator bool () const
bool isValid () const
Scalar< T > * release ()
Scalar< T > * get () const
Private Attributes
std::unique_ptr< Scalar< T > > ptr_m
Detailed Description
template<class T>
class Expressions::PtrToScalar< T >
A pointer to a scalar expression.
Definition at line 105 of file AbstractObjects/Expressions.h.
Constructor & Destructor Documentation
PtrToScalar() [1/4]
template<class T > Expressions::PtrToScalar< T >::PtrToScalar (Scalar< T > * rhs) inline
Constructor from an object just created.
Definition at line 318 of file AbstractObjects/Expressions.h.
PtrToScalar() [2/4]
template<class T > Expressions::PtrToScalar< T >::PtrToScalar () inline
Definition at line 312 of file AbstractObjects/Expressions.h.
PtrToScalar() [3/4]
template<class T > Expressions::PtrToScalar< T >::PtrToScalar (const PtrToScalar< T > & rhs) inline
Definition at line 315 of file AbstractObjects/Expressions.h.
PtrToScalar() [4/4]
template<class T > Expressions::PtrToScalar< T >::PtrToScalar (PtrToScalar< T > && rhs) default noexcept
~PtrToScalar()
template<class T > Expressions::PtrToScalar< T >::~PtrToScalar () inline
Definition at line 321 of file AbstractObjects/Expressions.h.
Member Function Documentation
get()
template<class T > Scalar< T > * Expressions::PtrToScalar< T >::get () const inline
Definition at line 123 of file AbstractObjects/Expressions.h.
References Expressions::PtrToScalar< T >::ptr_m.
isValid()
template<class T > bool Expressions::PtrToScalar< T >::isValid () const inline
Definition at line 121 of file AbstractObjects/Expressions.h.
References Expressions::PtrToScalar< T >::ptr_m.
Referenced by Line::parse(), and Expressions::parsePrimary().
operator bool()
template<class T > Expressions::PtrToScalar< T >::operator bool () const inline explicit
Definition at line 120 of file AbstractObjects/Expressions.h.
References Expressions::PtrToScalar< T >::ptr_m.
operator*()
template<class T > Scalar< T > & Expressions::PtrToScalar< T >::operator* () const inline
Definition at line 119 of file AbstractObjects/Expressions.h.
References Expressions::PtrToScalar< T >::ptr_m.
operator->()
template<class T > Scalar< T > * Expressions::PtrToScalar< T >::operator-> () const inline
Definition at line 118 of file AbstractObjects/Expressions.h.
References Expressions::PtrToScalar< T >::ptr_m.
operator=() [1/3]
template<class T > PtrToScalar< T > & Expressions::PtrToScalar< T >::operator= (const PtrToScalar< T > & rhs) inline
Definition at line 324 of file AbstractObjects/Expressions.h.
References Expressions::PtrToScalar< T >::ptr_m.
operator=() [2/3]
template<class T > PtrToScalar & Expressions::PtrToScalar< T >::operator= (PtrToScalar< T > &&) default noexcept
operator=() [3/3]
template<class T > PtrToScalar< T > & Expressions::PtrToScalar< T >::operator= (Scalar< T > * rhs) inline
Definition at line 332 of file AbstractObjects/Expressions.h.
release()
template<class T > Scalar< T > * Expressions::PtrToScalar< T >::release () inline
Definition at line 122 of file AbstractObjects/Expressions.h.
References Expressions::PtrToScalar< T >::ptr_m.
Referenced by Expressions::ASUnary< T >::make(), Expressions::SUnary< T, U >::make(), and Expressions::SBinary< T, U >::make().
Member Data Documentation
ptr_m
template<class T > std::unique_ptr<Scalar<T> > Expressions::PtrToScalar< T >::ptr_m mutable private
Definition at line 127 of file AbstractObjects/Expressions.h.
Referenced by Expressions::PtrToScalar< T >::get(), Expressions::PtrToScalar< T >::isValid(), Expressions::PtrToScalar< T >::operator bool(), Expressions::PtrToScalar< T >::operator*(), Expressions::PtrToScalar< T >::operator->(), Expressions::PtrToScalar< T >::operator=(), and Expressions::PtrToScalar< T >::release().
The documentation for this class was generated from the following file:
AbstractObjects/Expressions.h