OPALX (Object Oriented Parallel Accelerator Library for Exascal): OrbitThreaderTest Class Reference
OrbitThreaderTest Class Reference
Inherits testing::Test.
Classes
class TestableFieldSolverCmd
Protected Member Functions
void SetUp () override
std::shared_ptr< PartBunch_t > makeBunch (const size_t numParticles)
std::shared_ptr< MultipoleRep > makePlacedQuadrupole (const std::string &name, const double length, const double entryPosition, const double normalComponent)
std::shared_ptr< FieldSupportOnlyComponent > makePlacedFieldSupportOnlyComponent (const std::string &name, const double entryPosition, const double fieldLength)
Static Protected Member Functions
static void SetUpTestSuite ()
static void TearDownTestSuite ()
Protected Attributes
std::shared_ptr< FieldSolverCmd > fsCmdBase_m
std::shared_ptr< DataSink > dataSink_m
Detailed Description
Definition at line 99 of file TestOrbitThreader.cpp.
Member Function Documentation
makeBunch()
std::shared_ptr< PartBunch_t > OrbitThreaderTest::makeBunch (const size_t numParticles) inline protected
Definition at line 141 of file TestOrbitThreader.cpp.
References dataSink_m, Beam::find(), and fsCmdBase_m.
makePlacedFieldSupportOnlyComponent()
std::shared_ptr< FieldSupportOnlyComponent > OrbitThreaderTest::makePlacedFieldSupportOnlyComponent (const std::string & name, const double entryPosition, const double fieldLength) inline protected
Definition at line 176 of file TestOrbitThreader.cpp.
makePlacedQuadrupole()
std::shared_ptr< MultipoleRep > OrbitThreaderTest::makePlacedQuadrupole (const std::string & name, const double length, const double entryPosition, const double normalComponent) inline protected
Definition at line 164 of file TestOrbitThreader.cpp.
SetUp()
void OrbitThreaderTest::SetUp () inline override protected
Definition at line 116 of file TestOrbitThreader.cpp.
References OpalData::getInstance(), OpalData::setOpenMode(), OpalData::storeInputFn(), and OpalData::WRITE.
SetUpTestSuite()
static void OrbitThreaderTest::SetUpTestSuite () inline static protected
Definition at line 101 of file TestOrbitThreader.cpp.
References Options::enableHDF5, and gmsg.
TearDownTestSuite()
static void OrbitThreaderTest::TearDownTestSuite () inline static protected
Definition at line 110 of file TestOrbitThreader.cpp.
References gmsg.
Member Data Documentation
dataSink_m
std::shared_ptr<DataSink> OrbitThreaderTest::dataSink_m protected
Definition at line 187 of file TestOrbitThreader.cpp.
Referenced by makeBunch().
fsCmdBase_m
std::shared_ptr<FieldSolverCmd> OrbitThreaderTest::fsCmdBase_m protected
Definition at line 186 of file TestOrbitThreader.cpp.
Referenced by makeBunch().
The documentation for this class was generated from the following file:
TestOrbitThreader.cpp