OPALX (Object Oriented Parallel Accelerator Library for Exascal): interpolation::Interpolator3dGridTo1d Class Reference
interpolation::Interpolator3dGridTo1d Class Reference abstract
#include <Interpolator3dGridTo1d.h>
Public Member Functions
Interpolator3dGridTo1d (ThreeDGrid *grid, double ***F)
Interpolator3dGridTo1d ()
virtual ~Interpolator3dGridTo1d ()
virtual void function (const Mesh::Iterator &point, double *value) const
virtual void function (const double Point[3], double Value[1]) const =0
virtual Interpolator3dGridTo1d * clone () const =0
int getNumberOfXCoords () const
int getNumberOfYCoords () const
int getNumberOfZCoords () const
unsigned int getPointDimension () const
unsigned int getValueDimension () const
ThreeDGrid * getMesh () const
void setGrid (ThreeDGrid *grid)
void setX (int nCoords, double *x)
void setY (int nCoords, double *y)
void setZ (int nCoords, double *z)
void setF (double ***inF)
void deleteFunc (double ***func)
double *** function () const
void setAll (ThreeDGrid *grid, double ***F)
void clear ()
virtual void function (const double *point, double *value) const =0
virtual void functionAppend (const std::vector< std::vector< double > > &point_vec, std::vector< std::vector< double > > &value_vec) const
virtual bool checkPoint (const std::vector< double > &point) const
virtual bool checkValue (const std::vector< double > &value) const
Protected Attributes
ThreeDGrid * coordinates_m
double *** f_m
Detailed Description
Interpolator3dGridTo1d is an abstraction for lookup on a 3D mesh to get a 1D value.
Interpolator3dGridTo1d abstracts the lookup from a 3D mesh to get a 1D value This is a building block for higher dimension (e.g. field vector lookup) where we can do multiple lookups one for each field, at the cost of doing multiple access/interpolation operations to the grid.
Definition at line 44 of file Interpolator3dGridTo1d.h.
Constructor & Destructor Documentation
Interpolator3dGridTo1d() [1/2]
interpolation::Interpolator3dGridTo1d::Interpolator3dGridTo1d (ThreeDGrid * grid, double *** F) inline
Constructor for grids with constant spacing
Parameters
grid 3d mesh on which data is stored - adds a reference to *this into the mesh smart pointer thing.
F function data with points on each element of the grid. Indexing goes like [index_x][index_y][index_z]. Interpolator3dGridTo1d now owns this memory
Definition at line 143 of file Interpolator3dGridTo1d.h.
References setAll().
Interpolator3dGridTo1d() [2/2]
interpolation::Interpolator3dGridTo1d::Interpolator3dGridTo1d () inline
Default constructor - initialises data to nullptr
Note I have no nullptr checking on most member functions so be careful
Definition at line 148 of file Interpolator3dGridTo1d.h.
~Interpolator3dGridTo1d()
interpolation::Interpolator3dGridTo1d::~Interpolator3dGridTo1d () inline virtual
Deletes F data and removes *this from ThreeDGrid smart pointer thing.
Definition at line 150 of file Interpolator3dGridTo1d.h.
References clear().
Member Function Documentation
checkPoint()
bool interpolation::VectorMap::checkPoint (const std::vector< double > & point) const inline virtual inherited
Return true if point.size() is the same as this->PointDimension()
Definition at line 94 of file VectorMap.h.
checkValue()
bool interpolation::VectorMap::checkValue (const std::vector< double > & value) const inline virtual inherited
Return true if value.size() is the same as this->ValueDimension()
Definition at line 98 of file VectorMap.h.
clear()
void interpolation::Interpolator3dGridTo1d::clear () inline
Clear all private data
Definition at line 194 of file Interpolator3dGridTo1d.h.
References coordinates_m, deleteFunc(), f_m, and interpolation::ThreeDGrid::remove().
Referenced by ~Interpolator3dGridTo1d().
clone()
virtual Interpolator3dGridTo1d * interpolation::Interpolator3dGridTo1d::clone () const pure virtual
Copy constructor
Implements interpolation::VectorMap.
Implemented in interpolation::TriLinearInterpolator.
Referenced by interpolation::Interpolator3dGridTo3d::Interpolator3dGridTo3d().
deleteFunc()
void interpolation::Interpolator3dGridTo1d::deleteFunc (double *** func)
Delete any existing function data
Definition at line 31 of file Interpolator3dGridTo1d.cpp.
References getNumberOfXCoords(), and getNumberOfYCoords().
Referenced by clear(), and setF().
function() [1/4]
double *** interpolation::Interpolator3dGridTo1d::function () const inline
Return a pointer to the function data
Definition at line 187 of file Interpolator3dGridTo1d.h.
References f_m.
function() [2/4]
virtual void interpolation::VectorMap::function (const double * point, double * value) const pure virtual inherited
Pure virtual function to fill the array value with data evaluated at point.
Implemented in interpolation::PolynomialPatch.
Referenced by function(), interpolation::Interpolator3dGridTo3d::function(), interpolation::PolynomialPatch::function(), interpolation::TriLinearInterpolator::function(), interpolation::VectorMap::function(), and interpolation::VectorMap::functionAppend().
function() [3/4]
virtual void interpolation::Interpolator3dGridTo1d::function (const double Point[3], double Value[1]) const pure virtual
Get the interpolated function data
Implemented in interpolation::TriLinearInterpolator.
function() [4/4]
virtual void interpolation::Interpolator3dGridTo1d::function (const Mesh::Iterator & point, double * value) const inline virtual
Call function at a particular point in the mesh
Reimplemented from interpolation::VectorMap.
Reimplemented in interpolation::TriLinearInterpolator.
Definition at line 66 of file Interpolator3dGridTo1d.h.
References interpolation::VectorMap::function().
Referenced by interpolation::Interpolator3dGridTo3d::function().
functionAppend()
void interpolation::VectorMap::functionAppend (const std::vector< std::vector< double > > & point_vec, std::vector< std::vector< double > > & value_vec) const inline virtual inherited
Calculate F, appending output values to value_vec.
For each item in point_vec not in value_vec, calculate value_vec (urgh)
Definition at line 109 of file VectorMap.h.
References interpolation::VectorMap::function(), and interpolation::VectorMap::getValueDimension().
getMesh()
ThreeDGrid * interpolation::Interpolator3dGridTo1d::getMesh () const inline virtual
Return a pointer to the mesh
Reimplemented from interpolation::VectorMap.
Definition at line 162 of file Interpolator3dGridTo1d.h.
References coordinates_m.
getNumberOfXCoords()
int interpolation::Interpolator3dGridTo1d::getNumberOfXCoords () const inline
Number of x coordinates in the grid
Definition at line 152 of file Interpolator3dGridTo1d.h.
References coordinates_m, and interpolation::ThreeDGrid::xSize().
Referenced by deleteFunc().
getNumberOfYCoords()
int interpolation::Interpolator3dGridTo1d::getNumberOfYCoords () const inline
Number of y coordinates in the grid
Definition at line 154 of file Interpolator3dGridTo1d.h.
References coordinates_m, and interpolation::ThreeDGrid::ySize().
Referenced by deleteFunc().
getNumberOfZCoords()
int interpolation::Interpolator3dGridTo1d::getNumberOfZCoords () const inline
Number of z coordinates in the grid
Definition at line 156 of file Interpolator3dGridTo1d.h.
References coordinates_m, and interpolation::ThreeDGrid::zSize().
getPointDimension()
unsigned int interpolation::Interpolator3dGridTo1d::getPointDimension () const inline virtual
Dimension of input points
Implements interpolation::VectorMap.
Definition at line 158 of file Interpolator3dGridTo1d.h.
getValueDimension()
unsigned int interpolation::Interpolator3dGridTo1d::getValueDimension () const inline virtual
Dimension of output values
Implements interpolation::VectorMap.
Definition at line 160 of file Interpolator3dGridTo1d.h.
setAll()
void interpolation::Interpolator3dGridTo1d::setAll (ThreeDGrid * grid, double *** F) inline
Set function and mesh data
Definition at line 189 of file Interpolator3dGridTo1d.h.
References setF(), and setGrid().
Referenced by Interpolator3dGridTo1d().
setF()
void interpolation::Interpolator3dGridTo1d::setF (double *** inF) inline
Set function data, deleting any existing function data
Definition at line 164 of file Interpolator3dGridTo1d.h.
References deleteFunc(), and f_m.
Referenced by setAll().
setGrid()
void interpolation::Interpolator3dGridTo1d::setGrid (ThreeDGrid * grid) inline
Reset the mesh
Removes reference to this from mesh smart pointer if appropriate
Definition at line 169 of file Interpolator3dGridTo1d.h.
References interpolation::ThreeDGrid::add(), coordinates_m, and interpolation::ThreeDGrid::remove().
Referenced by setAll().
setX()
void interpolation::Interpolator3dGridTo1d::setX (int nCoords, double * x) inline
Set x coordinates in the mesh to an arbitrary set of points
If mesh is nullptr, does nothing
Definition at line 175 of file Interpolator3dGridTo1d.h.
References coordinates_m, and interpolation::ThreeDGrid::setX().
setY()
void interpolation::Interpolator3dGridTo1d::setY (int nCoords, double * y) inline
Set y coordinates in the mesh to an arbitrary set of points
If mesh is nullptr, does nothing
Definition at line 179 of file Interpolator3dGridTo1d.h.
References coordinates_m, and interpolation::ThreeDGrid::setY().
setZ()
void interpolation::Interpolator3dGridTo1d::setZ (int nCoords, double * z) inline
Set z coordinates in the mesh to an arbitrary set of points
If mesh is nullptr, does nothing
Definition at line 183 of file Interpolator3dGridTo1d.h.
References coordinates_m, and interpolation::ThreeDGrid::setZ().
Member Data Documentation
coordinates_m
ThreeDGrid* interpolation::Interpolator3dGridTo1d::coordinates_m protected
Definition at line 139 of file Interpolator3dGridTo1d.h.
Referenced by clear(), interpolation::TriLinearInterpolator::function(), getMesh(), getNumberOfXCoords(), getNumberOfYCoords(), getNumberOfZCoords(), setGrid(), setX(), setY(), setZ(), and interpolation::TriLinearInterpolator::TriLinearInterpolator().
f_m
double*** interpolation::Interpolator3dGridTo1d::f_m protected
Definition at line 140 of file Interpolator3dGridTo1d.h.
Referenced by clear(), function(), interpolation::TriLinearInterpolator::function(), setF(), and interpolation::TriLinearInterpolator::TriLinearInterpolator().
The documentation for this class was generated from the following files:
Interpolator3dGridTo1d.h
Interpolator3dGridTo1d.cpp