OPALX (Object Oriented Parallel Accelerator Library for Exascal): Triangle Class Reference
Triangle Class Reference
Public Member Functions
Triangle ()
Triangle (const Vector_t< double, 3 > &v1, const Vector_t< double, 3 > &v2, const Vector_t< double, 3 > &v3)
const Vector_t< double, 3 > & v1 () const
double v1 (int i) const
const Vector_t< double, 3 > & v2 () const
double v2 (int i) const
const Vector_t< double, 3 > & v3 () const
double v3 (int i) const
void scale (const Vector_t< double, 3 > &scaleby, const Vector_t< double, 3 > &shiftby)
Public Attributes
Vector_t< double, 3 > pts [3]
Detailed Description
Definition at line 420 of file BoundaryGeometry.cpp.
Constructor & Destructor Documentation
Triangle() [1/2]
Triangle::Triangle () inline
Definition at line 422 of file BoundaryGeometry.cpp.
Triangle() [2/2]
Triangle::Triangle (const Vector_t< double, 3 > & v1, const Vector_t< double, 3 > & v2, const Vector_t< double, 3 > & v3) inline
Definition at line 424 of file BoundaryGeometry.cpp.
References pts, v1(), v2(), and v3().
Member Function Documentation
scale()
void Triangle::scale (const Vector_t< double, 3 > & scaleby, const Vector_t< double, 3 > & shiftby) inline
Definition at line 451 of file BoundaryGeometry.cpp.
References pts.
Referenced by Voxel::intersect().
v1() [1/2]
const Vector_t< double, 3 > & Triangle::v1 () const inline
Definition at line 432 of file BoundaryGeometry.cpp.
References pts.
Referenced by Triangle().
v1() [2/2]
double Triangle::v1 (int i) const inline
Definition at line 435 of file BoundaryGeometry.cpp.
References pts.
v2() [1/2]
const Vector_t< double, 3 > & Triangle::v2 () const inline
Definition at line 438 of file BoundaryGeometry.cpp.
References pts.
Referenced by Triangle().
v2() [2/2]
double Triangle::v2 (int i) const inline
Definition at line 441 of file BoundaryGeometry.cpp.
References pts.
v3() [1/2]
const Vector_t< double, 3 > & Triangle::v3 () const inline
Definition at line 444 of file BoundaryGeometry.cpp.
References pts.
Referenced by Triangle().
v3() [2/2]
double Triangle::v3 (int i) const inline
Definition at line 447 of file BoundaryGeometry.cpp.
References pts.
Member Data Documentation
pts
Vector_t<double, 3> Triangle::pts[3]
Definition at line 466 of file BoundaryGeometry.cpp.
Referenced by scale(), Triangle(), v1(), v1(), v2(), v2(), v3(), and v3().
The documentation for this class was generated from the following file:
BoundaryGeometry.cpp