OPALX (Object Oriented Parallel Accelerator Library for Exascal): PlacementPose Class Reference
PlacementPose Class Reference
Nominal rigid placement transform.
#include <PlacementPose.h>
Public Member Functions
PlacementPose ()=default
PlacementPose (const CoordinateSystemTrafo &parentToNominal)
const CoordinateSystemTrafo & getParentToNominal () const
Private Attributes
CoordinateSystemTrafo parentToNominal_m
Detailed Description
Nominal rigid placement transform.
In the language of the placement note, this stores the nominal rigid placement transform \(T_i\) that embeds the canonical local chart of an element into its parent frame before any local correction is applied.
Definition at line 14 of file PlacementPose.h.
Constructor & Destructor Documentation
PlacementPose() [1/2]
PlacementPose::PlacementPose () default
PlacementPose() [2/2]
PlacementPose::PlacementPose (const CoordinateSystemTrafo & parentToNominal) inline explicit
Definition at line 17 of file PlacementPose.h.
Member Function Documentation
getParentToNominal()
const CoordinateSystemTrafo & PlacementPose::getParentToNominal () const inline
Definition at line 20 of file PlacementPose.h.
References parentToNominal_m.
Referenced by PlacedElement::getActualBodyTransform(), PlacedElement::getNominalBodyTransform(), ElementBase::setPlacementPose(), and TEST_F().
Member Data Documentation
parentToNominal_m
CoordinateSystemTrafo PlacementPose::parentToNominal_m private
Definition at line 23 of file PlacementPose.h.
Referenced by getParentToNominal().
The documentation for this class was generated from the following file:
PlacementPose.h