OPALX (Object Oriented Parallel Accelerator Library for Exascal): AttributeHandler Class Reference
AttributeHandler Class Reference abstract
Abstract base class for attribute parsers.
#include <AttributeHandler.h>
Public Types
enum OwnerType {
ELEMENT , COMMAND , SUB_COMMAND , STATEMENT ,
NONE
}
Public Member Functions
AttributeHandler (const std::string &name, const std::string &help, AttributeBase *def)
Constructor.
virtual ~AttributeHandler ()
virtual AttributeBase * getDefault () const
Return default value.
virtual const std::string & getHelp () const
Return help string.
virtual const std::string & getName () const
Return attribute name.
virtual const std::string & getType () const =0
Return attribute type.
virtual void parse (Attribute &a, Statement &s, bool eval) const =0
Parse new value.
virtual void parseComponent (Attribute &a, Statement &s, bool eval, int i) const
Parse component value.
bool isDeferred () const
Return defer flag.
void setDeferred (bool)
Set or reset defer flag.
bool isReadOnly () const
Return read-only flag.
void setReadOnly (bool)
Set or reset read-only flag.
void setPredefinedValues (const std::set< std::string > &, const std::string &)
Add predefined strings values to the help.
Static Public Member Functions
static std::multimap< OwnerType, std::string > getOwner (const std::string &att)
static void addAttributeOwner (const std::string &owner, const OwnerType &type, const std::string &name)
Protected Attributes
const std::string itsName
Attribute name.
const std::string itsHelp
Help text.
std::shared_ptr< AttributeBase > itsDefault
Default value.
bool is_deferred
Defer flag.
bool is_readonly
Read-only flag.
Private Member Functions
AttributeHandler ()
AttributeHandler (const AttributeHandler &)
void operator= (const AttributeHandler &)
Static Private Attributes
static std::multimap< std::string, std::pair< OwnerType, std::string > > attributeOwnerDictionary_s
Detailed Description
Abstract base class for attribute parsers.
Definition at line 49 of file AttributeHandler.h.
Member Enumeration Documentation
OwnerType
enum AttributeHandler::OwnerType
Enumerator
ELEMENT
COMMAND
SUB_COMMAND
STATEMENT
NONE
Definition at line 109 of file AttributeHandler.h.
Constructor & Destructor Documentation
AttributeHandler() [1/3]
AttributeHandler::AttributeHandler (const std::string & name, const std::string & help, AttributeBase * def)
Constructor.
Definition at line 30 of file AttributeHandler.cpp.
References is_deferred, is_readonly, itsDefault, itsHelp, and itsName.
Referenced by AttributeHandler(), Attributes::Bool::Bool(), Attributes::BoolArray::BoolArray(), operator=(), Attributes::Place::Place(), Attributes::PredefinedString::PredefinedString(), Attributes::Range::Range(), Attributes::Real::Real(), Attributes::RealArray::RealArray(), Attributes::Reference::Reference(), Attributes::String::String(), Attributes::StringArray::StringArray(), Attributes::TableRow::TableRow(), Attributes::TokenList::TokenList(), Attributes::TokenListArray::TokenListArray(), Attributes::UpperCaseString::UpperCaseString(), and Attributes::UpperCaseStringArray::UpperCaseStringArray().
~AttributeHandler()
AttributeHandler::~AttributeHandler () virtual
Definition at line 38 of file AttributeHandler.cpp.
AttributeHandler() [2/3]
AttributeHandler::AttributeHandler () private
AttributeHandler() [3/3]
AttributeHandler::AttributeHandler (const AttributeHandler &) private
References AttributeHandler().
Member Function Documentation
addAttributeOwner()
void AttributeHandler::addAttributeOwner (const std::string & owner, const OwnerType & type, const std::string & name) static
Definition at line 101 of file AttributeHandler.cpp.
References attributeOwnerDictionary_s.
Referenced by OpalElement::OpalElement(), Object::registerOwnership(), OpalElement::registerOwnership(), and TrackCmd::TrackCmd().
getDefault()
AttributeBase * AttributeHandler::getDefault () const virtual
Return default value.
Definition at line 40 of file AttributeHandler.cpp.
References itsDefault, and itsName.
getHelp()
const std::string & AttributeHandler::getHelp () const virtual
Return help string.
Definition at line 50 of file AttributeHandler.cpp.
References itsHelp.
getName()
const std::string & AttributeHandler::getName () const virtual
Return attribute name.
Definition at line 52 of file AttributeHandler.cpp.
References itsName.
getOwner()
std::multimap< AttributeHandler::OwnerType, std::string > AttributeHandler::getOwner (const std::string & att) static
Definition at line 84 of file AttributeHandler.cpp.
References attributeOwnerDictionary_s.
Referenced by OpalParser::getHint().
getType()
virtual const std::string & AttributeHandler::getType () const pure virtual
Return attribute type.
Implemented in Attributes::Bool, Attributes::BoolArray, Attributes::Place, Attributes::PredefinedString, Attributes::Range, Attributes::Real, Attributes::RealArray, Attributes::Reference, Attributes::String, Attributes::StringArray, Attributes::TableRow, Attributes::TokenList, Attributes::TokenListArray, Attributes::UpperCaseString, and Attributes::UpperCaseStringArray.
isDeferred()
bool AttributeHandler::isDeferred () const
Return defer flag.
Definition at line 61 of file AttributeHandler.cpp.
References is_deferred.
Referenced by Attributes::Real::parse().
isReadOnly()
bool AttributeHandler::isReadOnly () const
Return read-only flag.
Definition at line 65 of file AttributeHandler.cpp.
References is_readonly.
operator=()
void AttributeHandler::operator= (const AttributeHandler &) private
References AttributeHandler().
parse()
virtual void AttributeHandler::parse (Attribute & a, Statement & s, bool eval) const pure virtual
Parse new value.
Implemented in Attributes::Bool, Attributes::BoolArray, Attributes::Place, Attributes::PredefinedString, Attributes::Range, Attributes::Real, Attributes::RealArray, Attributes::Reference, Attributes::String, Attributes::StringArray, Attributes::TableRow, Attributes::TokenList, Attributes::TokenListArray, Attributes::UpperCaseString, and Attributes::UpperCaseStringArray.
parseComponent()
void AttributeHandler::parseComponent (Attribute & a, Statement & s, bool eval, int i) const virtual
Parse component value.
Reimplemented in Attributes::BoolArray, Attributes::RealArray, Attributes::StringArray, Attributes::TokenListArray, and Attributes::UpperCaseStringArray.
Definition at line 54 of file AttributeHandler.cpp.
References itsName.
setDeferred()
void AttributeHandler::setDeferred (bool flag)
Set or reset defer flag.
Definition at line 63 of file AttributeHandler.cpp.
References is_deferred.
setPredefinedValues()
void AttributeHandler::setPredefinedValues (const std::set< std::string > & predefinedValues, const std::string & defaultValue)
Add predefined strings values to the help.
Definition at line 69 of file AttributeHandler.cpp.
References itsHelp.
Referenced by Attributes::PredefinedString::PredefinedString().
setReadOnly()
void AttributeHandler::setReadOnly (bool flag)
Set or reset read-only flag.
Definition at line 67 of file AttributeHandler.cpp.
References is_readonly.
Member Data Documentation
attributeOwnerDictionary_s
std::multimap< std::string, std::pair< AttributeHandler::OwnerType, std::string > > AttributeHandler::attributeOwnerDictionary_s static private
Definition at line 138 of file AttributeHandler.h.
Referenced by addAttributeOwner(), and getOwner().
is_deferred
bool AttributeHandler::is_deferred protected
Defer flag.
Definition at line 126 of file AttributeHandler.h.
Referenced by AttributeHandler(), isDeferred(), Attributes::Bool::parse(), Attributes::BoolArray::parse(), Attributes::RealArray::parse(), and setDeferred().
is_readonly
bool AttributeHandler::is_readonly protected
Read-only flag.
Definition at line 129 of file AttributeHandler.h.
Referenced by AttributeHandler(), isReadOnly(), and setReadOnly().
itsDefault
std::shared_ptr<AttributeBase> AttributeHandler::itsDefault protected
Default value.
Definition at line 123 of file AttributeHandler.h.
Referenced by AttributeHandler(), and getDefault().
itsHelp
const std::string AttributeHandler::itsHelp protected
Help text.
Definition at line 120 of file AttributeHandler.h.
Referenced by AttributeHandler(), getHelp(), and setPredefinedValues().
itsName
const std::string AttributeHandler::itsName protected
Attribute name.
Definition at line 117 of file AttributeHandler.h.
Referenced by AttributeHandler(), getDefault(), getName(), and parseComponent().
The documentation for this class was generated from the following files:
AttributeHandler.h
AttributeHandler.cpp