OPALX (Object Oriented Parallel Accelerator Library for Exascal): IfStatement Class Reference
IfStatement Class Reference
If statement.
#include <IfStatement.h>
Public Types
typedef std::list< Token > TokenList
The type of the enclosed token list.
Public Member Functions
IfStatement (const Parser &, TokenStream &)
Constructor.
virtual ~IfStatement ()
virtual void execute (const Parser &)
Execute.
void append (const Token &)
Append a token.
bool atEnd () const
Test for end of command.
bool boolean (bool &value)
Return boolean value.
bool delimiter (char c)
Test for delimiter.
bool delimiter (const char *s)
Test for delimiter choice.
Token & getCurrent ()
Return current token and skip it.
bool integer (int &value)
Return signed integer.
bool integer (unsigned &value)
Return unsigned integer.
bool keyword (const char *s)
Test for keyword.
bool real (double &value)
Return real value.
bool str (std::string &value)
Return string value.
std::string str () const
bool word (std::string &value)
Return word value.
void mark ()
Mark position in command.
void restore ()
Return to marked position.
void start ()
Return to start.
void skip ()
Skip.
unsigned int position () const
Return current character number in line.
virtual void print (std::ostream &os) const
Print statement.
virtual void printWhere (Inform &msg, bool withToken) const
Print position.
Protected Attributes
int stat_line
std::string buffer_name
TokenList tokens
TokenList::iterator curr
TokenList::iterator keep
Private Member Functions
IfStatement ()
IfStatement (const IfStatement &)
void operator= (const IfStatement &)
Private Attributes
Statement * then_block
Statement * else_block
Detailed Description
If statement.
Definition at line 35 of file IfStatement.h.
Member Typedef Documentation
TokenList
typedef std::list<Token> Statement::TokenList inherited
The type of the enclosed token list.
Definition at line 40 of file Statement.h.
Constructor & Destructor Documentation
IfStatement() [1/3]
IfStatement::IfStatement (const Parser & parser, TokenStream & is)
Constructor.
Definition at line 35 of file IfStatement.cpp.
References Statement::append(), else_block, Token::isDel(), Token::isEOF(), Token::isKey(), TokenStream::putBack(), Parser::readStatement(), TokenStream::readToken(), and then_block.
~IfStatement()
IfStatement::~IfStatement () virtual
Definition at line 72 of file IfStatement.cpp.
References else_block, and then_block.
IfStatement() [2/3]
IfStatement::IfStatement () private
IfStatement() [3/3]
IfStatement::IfStatement (const IfStatement &) private
Member Function Documentation
append()
void Statement::append (const Token & token) inherited
Append a token.
Definition at line 45 of file Statement.cpp.
References Statement::tokens.
Referenced by IfStatement(), LineTemplate::makeInstance(), OpalParser::parseBracketList(), OpalParser::parseTokenList(), OpalParser::readStatement(), and WhileStatement::WhileStatement().
atEnd()
bool Statement::atEnd () const inherited
Test for end of command.
Definition at line 50 of file Statement.cpp.
References Statement::curr, and Statement::tokens.
Referenced by MacroCmd::makeTemplate(), OpalParser::parse(), Expressions::parseBracketList(), OpalParser::parseEnd(), LineTemplate::parseTemplate(), Expressions::parseTokenList(), and Statement::skip().
boolean()
bool Statement::boolean (bool & value) inherited
Return boolean value.
Definition at line 55 of file Statement.cpp.
References Statement::curr, Statement::tokens, and Statement::word().
Referenced by Expressions::parseRelation().
delimiter() [1/2]
bool Statement::delimiter (char c) inherited
Test for delimiter.
Definition at line 101 of file Statement.cpp.
References Statement::curr, and Statement::tokens.
Referenced by MacroCmd::makeTemplate(), Object::parse(), OpalElement::parse(), OpalParser::parse(), Line::parse(), OpalParser::parseAction(), Macro::parseActuals(), Expressions::parseAnd(), Expressions::parseArrayFactor(), Expressions::parseArrayPrimary(), Expressions::parseArrayTerm(), OpalParser::parseAssign(), Expressions::parseBool(), Expressions::parseBoolArray(), Expressions::parseBracketList(), Expressions::parseColumnGenerator(), OpalParser::parseDefine(), Expressions::parseDelimiter(), Expressions::parseDelimiter(), OpalParser::parseEnd(), Expressions::parseFactor(), Macro::parseFormals(), Line::parseList(), EmissionSourceList::parseList(), OpalParser::parseMacro(), SequenceParser::parseMember(), Expressions::parsePlace(), SequenceParser::parsePosition(), Expressions::parsePrimary(), Expressions::parseRange(), Expressions::parseReal(), Expressions::parseRealArray(), Expressions::parseReference(), Expressions::parseRelation(), Expressions::parseRowGenerator(), Object::parseShortcut(), Expressions::parseString(), Expressions::parseStringArray(), Expressions::parseStringValue(), Expressions::parseTableGenerator(), Expressions::parseTerm(), and Expressions::parseTokenListArray().
delimiter() [2/2]
bool Statement::delimiter (const char * s) inherited
Test for delimiter choice.
Definition at line 111 of file Statement.cpp.
References Statement::curr, and Statement::tokens.
execute()
void IfStatement::execute (const Parser & parser) virtual
Execute.
Implements Statement.
Definition at line 77 of file IfStatement.cpp.
References else_block, Statement::execute(), Attributes::getBool(), OpalData::getInstance(), Attributes::makeBool(), Attribute::parse(), Statement::print(), Statement::start(), then_block, and OpalData::update().
getCurrent()
Token & Statement::getCurrent () inherited
Return current token and skip it.
Definition at line 74 of file Statement.cpp.
References Statement::curr.
Referenced by MacroCmd::makeTemplate(), OpalParser::parse(), Macro::parseActuals(), Expressions::parseBracketList(), OpalParser::parseMacro(), LineTemplate::parseTemplate(), and Expressions::parseTokenList().
integer() [1/2]
bool Statement::integer (int & value) inherited
Return signed integer.
Definition at line 79 of file Statement.cpp.
References Statement::curr, Token::getInteger(), and Statement::tokens.
Referenced by Line::parseList().
integer() [2/2]
bool Statement::integer (unsigned & value) inherited
Return unsigned integer.
Definition at line 90 of file Statement.cpp.
References Statement::curr, and Statement::tokens.
keyword()
bool Statement::keyword (const char * s) inherited
Test for keyword.
Definition at line 121 of file Statement.cpp.
References Statement::curr, and Statement::tokens.
Referenced by MacroCmd::makeTemplate(), SequenceParser::parse(), OpalParser::parse(), Expressions::parseArrayPrimary(), OpalParser::parseAssign(), OpalParser::parseDefine(), Expressions::parsePlace(), SequenceParser::parsePosition(), Expressions::parseRange(), SequenceTemplate::parseTemplate(), and LineTemplate::parseTemplate().
mark()
void Statement::mark () inherited
Mark position in command.
Definition at line 170 of file Statement.cpp.
References Statement::curr, and Statement::keep.
Referenced by OpalParser::parse(), OpalParser::parseMacro(), Expressions::parseRelation(), Object::parseShortcut(), and Expressions::parseTokenList().
operator=()
void IfStatement::operator= (const IfStatement &) private
position()
unsigned int Statement::position () const inherited
Return current character number in line.
Definition at line 190 of file Statement.cpp.
References Statement::curr, and Statement::tokens.
Referenced by OpalParser::parse(), and OpalParser::parseEnd().
print()
void Statement::print (std::ostream & os) const virtual inherited
Print statement.
Definition at line 204 of file Statement.cpp.
References Statement::tokens.
Referenced by execute(), WhileStatement::execute(), operator<<(), operator<<(), OpalParser::parse(), OpalParser::parseEnd(), and Statement::str().
printWhere()
void Statement::printWhere (Inform & msg, bool withToken) const virtual inherited
Print position.
Definition at line 217 of file Statement.cpp.
References Statement::buffer_name, Statement::curr, Statement::stat_line, and Statement::tokens.
real()
bool Statement::real (double & value) inherited
Return real value.
Definition at line 131 of file Statement.cpp.
References Statement::curr, and Statement::tokens.
Referenced by Expressions::parseArrayPrimary(), and Expressions::parsePrimary().
restore()
void Statement::restore () inherited
Return to marked position.
Definition at line 175 of file Statement.cpp.
References Statement::curr, and Statement::keep.
Referenced by OpalParser::parse(), OpalParser::parseMacro(), Expressions::parseRelation(), and Expressions::parseTokenList().
skip()
void Statement::skip () inherited
Skip.
Definition at line 185 of file Statement.cpp.
References Statement::atEnd(), and Statement::curr.
start()
void Statement::start () inherited
Return to start.
Definition at line 180 of file Statement.cpp.
References Statement::curr, and Statement::tokens.
Referenced by execute(), LineTemplate::makeInstance(), SequenceParser::parse(), OpalParser::parse(), OpalParser::parseAction(), OpalParser::parseAssign(), OpalParser::parseDefine(), and OpalParser::readStatement().
str() [1/2]
std::string Statement::str () const inherited
Definition at line 232 of file Statement.cpp.
References Statement::print(), and Statement::str().
Referenced by Statement::str().
str() [2/2]
bool Statement::str (std::string & value) inherited
Return string value.
Definition at line 148 of file Statement.cpp.
References Statement::curr, and Statement::tokens.
Referenced by Expressions::parseString(), and Expressions::parseStringValue().
word()
bool Statement::word (std::string & value) inherited
Return word value.
Definition at line 159 of file Statement.cpp.
References Statement::curr, and Statement::tokens.
Referenced by Statement::boolean(), Expressions::parseRelation(), Object::parseShortcut(), Expressions::parseString(), and Expressions::parseStringValue().
Member Data Documentation
buffer_name
std::string Statement::buffer_name protected inherited
Definition at line 173 of file Statement.h.
Referenced by CompoundStatement::CompoundStatement(), and Statement::printWhere().
curr
TokenList::iterator Statement::curr protected inherited
Definition at line 177 of file Statement.h.
Referenced by Statement::atEnd(), Statement::boolean(), Statement::delimiter(), Statement::delimiter(), SimpleStatement::execute(), WhileStatement::execute(), Statement::getCurrent(), Statement::integer(), Statement::integer(), Statement::keyword(), Statement::mark(), Statement::position(), Statement::printWhere(), Statement::real(), Statement::restore(), Statement::skip(), Statement::start(), Statement::Statement(), Statement::str(), and Statement::word().
else_block
Statement* IfStatement::else_block private
Definition at line 57 of file IfStatement.h.
Referenced by execute(), IfStatement(), and ~IfStatement().
keep
TokenList::iterator Statement::keep protected inherited
Definition at line 178 of file Statement.h.
Referenced by SimpleStatement::execute(), WhileStatement::execute(), Statement::mark(), and Statement::restore().
stat_line
int Statement::stat_line protected inherited
Definition at line 170 of file Statement.h.
Referenced by CompoundStatement::CompoundStatement(), and Statement::printWhere().
then_block
Statement* IfStatement::then_block private
Definition at line 56 of file IfStatement.h.
Referenced by execute(), IfStatement(), and ~IfStatement().
tokens
TokenList Statement::tokens protected inherited
Definition at line 176 of file Statement.h.
Referenced by Statement::append(), Statement::atEnd(), Statement::boolean(), Statement::delimiter(), Statement::delimiter(), SimpleStatement::execute(), WhileStatement::execute(), Statement::integer(), Statement::integer(), Statement::keyword(), Statement::position(), Statement::print(), Statement::printWhere(), Statement::real(), Statement::start(), Statement::Statement(), Statement::str(), Statement::word(), and Statement::~Statement().
The documentation for this class was generated from the following files:
IfStatement.h
IfStatement.cpp