OPALX (Object Oriented Parallel Accelerator Library for Exascal): OPALTimer::Timer Class Reference
OPALTimer::Timer Class Reference
#include <Timer.h>
Public Member Functions
Timer ()
Constructor.
~Timer ()
std::string date () const
Return date.
std::string time () const
Return time.
Private Member Functions
Timer (const Timer &)
void operator= (const Timer &)
Private Attributes
time_t timer
Detailed Description
Definition at line 32 of file Timer.h.
Constructor & Destructor Documentation
Timer() [1/2]
OPALTimer::Timer::Timer ()
Constructor.
Definition at line 26 of file Timer.cpp.
References time(), and timer.
Referenced by operator=(), and Timer().
~Timer()
OPALTimer::Timer::~Timer ()
Definition at line 28 of file Timer.cpp.
Timer() [2/2]
OPALTimer::Timer::Timer (const Timer &) private
References Timer().
Member Function Documentation
date()
std::string OPALTimer::Timer::date () const
Return date.
Definition at line 30 of file Timer.cpp.
References timer.
Referenced by LBalWriter::fillHeader(), StatWriter::fillHeader(), MemoryProfiler::header(), and OPALXMAIN::printStdoutHeader().
operator=()
void OPALTimer::Timer::operator= (const Timer &) private
References Timer().
time()
std::string OPALTimer::Timer::time () const
Return time.
Definition at line 36 of file Timer.cpp.
References timer.
Referenced by ParallelTracker::dumpStats(), ParallelTracker::execute(), LBalWriter::fillHeader(), StatWriter::fillHeader(), MemoryProfiler::header(), OPALXMAIN::printStdoutHeader(), and Timer().
Member Data Documentation
timer
time_t OPALTimer::Timer::timer private
Definition at line 51 of file Timer.h.
Referenced by date(), time(), and Timer().
The documentation for this class was generated from the following files:
Timer.h
Timer.cpp