OPALX (Object Oriented Parallel Accelerator Library for Exascal): gsl_rng Class Reference
gsl_rng Class Reference
#include <Random.h>
Public Member Functions
gsl_rng ()
double uniform ()
double gaussian (double sigma)
void seed (unsigned long seed)
std::mt19937_64 & engine ()
const std::mt19937_64 & engine () const
Private Attributes
std::mt19937_64 engine_
std::uniform_real_distribution< double > uniform_dist_ {0.0, 1.0}
Detailed Description
Definition at line 26 of file Random.h.
Constructor & Destructor Documentation
gsl_rng()
gsl_rng::gsl_rng () inline
Definition at line 28 of file Random.h.
References engine_.
Member Function Documentation
engine() [1/2]
std::mt19937_64 & gsl_rng::engine () inline
Definition at line 39 of file Random.h.
References engine_.
engine() [2/2]
const std::mt19937_64 & gsl_rng::engine () const inline
Definition at line 40 of file Random.h.
References engine_.
gaussian()
double gsl_rng::gaussian (double sigma) inline
Definition at line 32 of file Random.h.
References engine_.
Referenced by gsl_ran_gaussian().
seed()
void gsl_rng::seed (unsigned long seed) inline
Definition at line 37 of file Random.h.
References engine_, and seed().
Referenced by seed(), TEST_F(), and TEST_F().
uniform()
double gsl_rng::uniform () inline
Definition at line 30 of file Random.h.
References engine_, and uniform_dist_.
Referenced by gsl_rng_uniform().
Member Data Documentation
engine_
std::mt19937_64 gsl_rng::engine_ private
Definition at line 43 of file Random.h.
Referenced by engine(), engine(), gaussian(), gsl_rng(), seed(), and uniform().
uniform_dist_
std::uniform_real_distribution<double> gsl_rng::uniform_dist_ {0.0, 1.0} private
Definition at line 44 of file Random.h.
Referenced by uniform().
The documentation for this class was generated from the following file:
Random.h