OPALX (Object Oriented Parallel Accelerator Library for Exascal): gsl_qrng Class Reference
gsl_qrng Class Reference
#include <QuasiRandom.h>
Public Member Functions
gsl_qrng ()
void init (size_t dimension)
void get (double *x)
Private Member Functions
void init_sobol ()
double sobol_sample (size_t dim)
Private Attributes
size_t dimension_
size_t count_
std::vector< unsigned int > direction_numbers_
Detailed Description
Definition at line 26 of file QuasiRandom.h.
Constructor & Destructor Documentation
gsl_qrng()
gsl_qrng::gsl_qrng () inline
Definition at line 28 of file QuasiRandom.h.
References count_, and dimension_.
Member Function Documentation
get()
void gsl_qrng::get (double * x) inline
Definition at line 37 of file QuasiRandom.h.
References count_, dimension_, and sobol_sample().
init()
void gsl_qrng::init (size_t dimension) inline
Definition at line 30 of file QuasiRandom.h.
References count_, dimension_, and init_sobol().
Referenced by gsl_qrng_alloc().
init_sobol()
void gsl_qrng::init_sobol () inline private
Definition at line 45 of file QuasiRandom.h.
References dimension_, and direction_numbers_.
Referenced by init().
sobol_sample()
double gsl_qrng::sobol_sample (size_t dim) inline private
Definition at line 54 of file QuasiRandom.h.
References count_, and dimension_.
Referenced by get().
Member Data Documentation
count_
size_t gsl_qrng::count_ private
Definition at line 73 of file QuasiRandom.h.
Referenced by get(), gsl_qrng(), init(), and sobol_sample().
dimension_
size_t gsl_qrng::dimension_ private
Definition at line 72 of file QuasiRandom.h.
Referenced by get(), gsl_qrng(), init(), init_sobol(), and sobol_sample().
direction_numbers_
std::vector<unsigned int> gsl_qrng::direction_numbers_ private
Definition at line 74 of file QuasiRandom.h.
Referenced by init_sobol().
The documentation for this class was generated from the following file:
QuasiRandom.h