OPALX (Object Oriented Parallel Accelerator Library for Exascal): Directory Class Reference
Directory Class Reference
A map of string versus pointer to Object.
#include <Directory.h>
Public Member Functions
Directory ()
Constructor.
~Directory ()
ObjectDir::iterator begin ()
First object in alphabetic order of name.
ObjectDir::const_iterator begin () const
First object in alphabetic order of name.
ObjectDir::iterator end ()
Last object in alphabetic order of name.
ObjectDir::const_iterator end () const
Last object in alphabetic order of name.
void erase ()
Delete all entries.
void erase (const std::string &name)
Remove existing entry.
Object * find (const std::string &name) const
Find entry.
void insert (const std::string &name, Object *newObject)
Define new object.
Private Attributes
ObjectDir dir
Detailed Description
A map of string versus pointer to Object.
Definition at line 38 of file Directory.h.
Constructor & Destructor Documentation
Directory()
Directory::Directory ()
Constructor.
Definition at line 26 of file Directory.cpp.
~Directory()
Directory::~Directory ()
Definition at line 31 of file Directory.cpp.
References erase().
Member Function Documentation
begin() [1/2]
ObjectDir::iterator Directory::begin ()
First object in alphabetic order of name.
Definition at line 36 of file Directory.cpp.
References dir.
Referenced by OpalData::apply(), OpalData::define(), OpalData::erase(), OpalData::getVariableNames(), OpalData::printAllNames(), OpalData::printNames(), and OpalData::update().
begin() [2/2]
ObjectDir::const_iterator Directory::begin () const
First object in alphabetic order of name.
Definition at line 41 of file Directory.cpp.
References dir.
end() [1/2]
ObjectDir::iterator Directory::end ()
Last object in alphabetic order of name.
Definition at line 46 of file Directory.cpp.
References dir.
Referenced by OpalData::apply(), OpalData::define(), OpalData::erase(), OpalData::getVariableNames(), OpalData::printAllNames(), OpalData::printNames(), and OpalData::update().
end() [2/2]
ObjectDir::const_iterator Directory::end () const
Last object in alphabetic order of name.
Definition at line 51 of file Directory.cpp.
References dir.
erase() [1/2]
void Directory::erase ()
Delete all entries.
Definition at line 56 of file Directory.cpp.
References dir.
Referenced by OpalData::erase(), ~Directory(), and OpalDataImpl::~OpalDataImpl().
erase() [2/2]
void Directory::erase (const std::string & name)
Remove existing entry.
Definition at line 61 of file Directory.cpp.
References dir.
find()
Object * Directory::find (const std::string & name) const
Find entry.
Definition at line 66 of file Directory.cpp.
References dir.
Referenced by OpalData::create(), OpalData::define(), OpalData::erase(), TrackParser::find(), and OpalData::find().
insert()
void Directory::insert (const std::string & name, Object * newObject)
Define new object.
Definition at line 76 of file Directory.cpp.
References dir.
Referenced by OpalData::create(), OpalData::define(), and TrackParser::TrackParser().
Member Data Documentation
dir
ObjectDir Directory::dir private
Definition at line 84 of file Directory.h.
Referenced by begin(), begin(), end(), end(), erase(), erase(), find(), and insert().
The documentation for this class was generated from the following files:
Directory.h
Directory.cpp