OPALX (Object Oriented Parallel Accelerator Library for Exascal): FakeTWFieldmap Class Reference
FakeTWFieldmap Class Reference
Public Member Functions
FakeTWFieldmap ()
void setOutOfBounds (bool v)
bool getFieldstrength (const Vector_t< double, 3 > &, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) const override
Get the field strength at a given point.
void getFieldDimensions (double &zBegin, double &zEnd) const override
Get the longitudinal dimensions of the field.
void getFieldDimensions (double &xIni, double &xFinal, double &yIni, double &yFinal, double &zIni, double &zFinal) const override
Get the full 3D bounding box of the field.
bool isInside (const Vector_t< double, 3 > &) const override
Check if a point is inside the field map.
void applyField (std::shared_ptr< ParticleContainer_t >, double=1.0) override
Apply the FM to all the particles.
bool getFieldDerivative (const Vector_t< double, 3 > &, Vector_t< double, 3 > &, Vector_t< double, 3 > &, const DiffDirection &) const override
Get the field derivative with respect to a direction.
void swap () override
Swap coordinates (implementation dependent).
void getInfo (Inform *) override
Print info about the field map.
double getFrequency () const override
Get the frequency.
void setFrequency (double) override
Set the frequency.
void readMap () override
Pure virtual method to read the map data. Called by the public static readMap().
void freeMap () override
Pure virtual method to free the map data.
void getOnaxisEz (std::vector< std::pair< double, double > > &F) override
virtual void setEdgeConstants (const double &bendAngle, const double &entranceAngle, const double &exitAngle)
virtual void setFieldLength (const double &)
virtual void get1DProfile1EngeCoeffs (std::vector< double > &engeCoeffsEntry, std::vector< double > &engeCoeffsExit)
virtual void get1DProfile1EntranceParam (double &entranceParameter1, double &entranceParameter2, double &entranceParameter3)
virtual void get1DProfile1ExitParam (double &exitParameter1, double &exitParameter2, double &exitParameter3)
virtual double getFieldGap ()
virtual void setFieldGap (double gap)
MapType getType ()
template<class T>
bool interpretLine (std::ifstream &in, T &value, const bool &file_length_known)
Parses a single value of type T from a line in the stream.
Static Public Member Functions
static Fieldmap * getFieldmap (std::string Filename, bool fast=false)
Get a field map instance. Use this factory method to obtain a field map. It checks the cache (FieldmapDictionary) first.
static std::vector< std::string > getListFieldmapNames ()
Get a list of all loaded field map names.
static void deleteFieldmap (std::string Filename)
Delete a specific field map from the cache and memory.
static void clearDictionary ()
Clear the entire field map cache.
static MapType readHeader (std::string Filename)
Read the header of a field map file to determine its type.
static void readMap (std::string Filename)
Trigger the actual reading of the field map data.
static void freeMap (std::string Filename)
Decrease reference count or delete field map if unused.
static std::string typeset_msg (const std::string &msg, const std::string &title)
Protected Member Functions
void getLine (std::ifstream &in, std::string &buffer)
template<class S>
bool interpretLine (std::ifstream &in, S &value, const bool &file_length_known=true)
template<class S, class T>
bool interpretLine (std::ifstream &in, S &value1, T &value2, const bool &file_length_known=true)
Parses two values (types S, T) from a line.
template<class S, class T, class U>
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, const bool &file_length_known=true)
Parses three values (types S, T, U) from a line.
template<class S, class T, class U, class V>
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, V &value4, const bool &file_length_known=true)
Parses four values (types S, T, U, V) from a line.
template<class S>
bool interpretLine (std::ifstream &in, S &value1, S &value2, S &value3, S &value4, S &value5, S &value6, const bool &file_length_known=true)
Parses six values of the same type S from a line.
bool interpreteEOF (std::ifstream &in)
void interpretWarning (const std::ios_base::iostate &state, const bool &read_all, const std::string &error_msg, const std::string &found)
void missingValuesWarning ()
void exceedingValuesWarning ()
void disableFieldmapWarning ()
void noFieldmapWarning ()
void lowResolutionWarning (double squareError, double maxError)
void checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void checkMap (unsigned int accuracy, double length, const std::vector< double > &zSampling, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > &xrange, const std::pair< double, double > &yrange, const std::pair< double, double > &zrange, const std::vector< Vector_t< double, 3 > > &ef, const std::vector< Vector_t< double, 3 > > &bf)
Static Protected Member Functions
static void getLine (std::ifstream &in, int &lines_read, std::string &buffer)
Protected Attributes
MapType Type
std::string Filename_m
int lines_read_m
bool normalize_m
Private Attributes
bool outOfBounds_
Static Private Attributes
static char buffer_m [256]
static std::string alpha_numeric
static std::map< std::string, FieldmapDescription > FieldmapDictionary
Detailed Description
Definition at line 69 of file TestTravelingWave.cpp.
Constructor & Destructor Documentation
FakeTWFieldmap()
FakeTWFieldmap::FakeTWFieldmap () inline
Definition at line 71 of file TestTravelingWave.cpp.
References Fieldmap::Fieldmap(), and outOfBounds_.
Member Function Documentation
applyField()
void FakeTWFieldmap::applyField (std::shared_ptr< ParticleContainer_t > pc, double scale = 1.0) inline override virtual
Apply the FM to all the particles.
Parameters
pc Particle container
scale Scaling factor applied to the field (default 1.0)
Implements Fieldmap.
Definition at line 102 of file TestTravelingWave.cpp.
checkMap() [1/2]
void Fieldmap::checkMap (unsigned int accuracy, double length, const std::vector< double > & zSampling, const std::vector< double > & fourierCoefficients, gsl_spline * splineCoefficients, gsl_interp_accel * splineAccelerator) protected inherited
Definition at line 326 of file Fieldmap.cpp.
References checkMap(), Util::combineFilePath(), Filename_m, OpalData::getInstance(), gsl_spline_eval(), lowResolutionWarning(), and Physics::two_pi.
checkMap() [2/2]
void Fieldmap::checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > & fourierCoefficients, gsl_spline * splineCoefficients, gsl_interp_accel * splineAccelerator) protected inherited
Definition at line 310 of file Fieldmap.cpp.
References checkMap().
Referenced by checkMap(), and checkMap().
clearDictionary()
void Fieldmap::clearDictionary () static inherited
Clear the entire field map cache.
Definition at line 140 of file Fieldmap.cpp.
References clearDictionary(), and FieldmapDictionary.
Referenced by clearDictionary().
deleteFieldmap()
void Fieldmap::deleteFieldmap (std::string Filename) static inherited
Delete a specific field map from the cache and memory.
Parameters
Filename The filename of the map to delete.
Definition at line 138 of file Fieldmap.cpp.
References deleteFieldmap(), and freeMap().
Referenced by deleteFieldmap().
disableFieldmapWarning()
void Fieldmap::disableFieldmapWarning () protected inherited
Definition at line 469 of file Fieldmap.cpp.
References disableFieldmapWarning(), and Filename_m.
Referenced by Astra1DDynamic::Astra1DDynamic(), disableFieldmapWarning(), FM2DDynamic::FM2DDynamic(), and FM2DMagnetoStatic::FM2DMagnetoStatic().
exceedingValuesWarning()
void Fieldmap::exceedingValuesWarning () protected inherited
Definition at line 459 of file Fieldmap.cpp.
References exceedingValuesWarning(), Filename_m, and lines_read_m.
Referenced by exceedingValuesWarning(), and interpreteEOF().
freeMap() [1/2]
void FakeTWFieldmap::freeMap () inline override virtual
Pure virtual method to free the map data.
Implements Fieldmap.
Definition at line 114 of file TestTravelingWave.cpp.
freeMap() [2/2]
void Fieldmap::freeMap (std::string Filename) static inherited
Decrease reference count or delete field map if unused.
Parameters
Filename The file to free.
Definition at line 291 of file Fieldmap.cpp.
References FieldmapDictionary, and freeMap().
Referenced by freeMap(), TEST_F(), TEST_F(), and TEST_F().
get1DProfile1EngeCoeffs()
void Fieldmap::get1DProfile1EngeCoeffs (std::vector< double > & engeCoeffsEntry, std::vector< double > & engeCoeffsExit) virtual inherited
Definition at line 570 of file Fieldmap.cpp.
References get1DProfile1EngeCoeffs().
Referenced by get1DProfile1EngeCoeffs().
get1DProfile1EntranceParam()
void Fieldmap::get1DProfile1EntranceParam (double & entranceParameter1, double & entranceParameter2, double & entranceParameter3) virtual inherited
Definition at line 573 of file Fieldmap.cpp.
References get1DProfile1EntranceParam().
Referenced by get1DProfile1EntranceParam().
get1DProfile1ExitParam()
void Fieldmap::get1DProfile1ExitParam (double & exitParameter1, double & exitParameter2, double & exitParameter3) virtual inherited
Definition at line 577 of file Fieldmap.cpp.
References get1DProfile1ExitParam().
Referenced by get1DProfile1ExitParam().
getFieldDerivative()
bool FakeTWFieldmap::getFieldDerivative (const Vector_t< double, 3 > & R, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B, const DiffDirection & dir) const inline override virtual
Get the field derivative with respect to a direction.
Parameters
R Position [m].
E Output derivative of Electric field.
B Output derivative of Magnetic field.
dir Direction of derivative (DX, DY, DZ).
Returns
true if R is outside, false otherwise.
Implements Fieldmap.
Definition at line 103 of file TestTravelingWave.cpp.
getFieldDimensions() [1/2]
void FakeTWFieldmap::getFieldDimensions (double & xIni, double & xFinal, double & yIni, double & yFinal, double & zIni, double & zFinal) const inline override virtual
Get the full 3D bounding box of the field.
Parameters
xIni Output minimum x [m].
xFinal Output maximum x [m].
yIni Output minimum y [m].
yFinal Output maximum y [m].
zIni Output minimum z [m].
zFinal Output maximum z [m].
Implements Fieldmap.
Definition at line 90 of file TestTravelingWave.cpp.
getFieldDimensions() [2/2]
void FakeTWFieldmap::getFieldDimensions (double & zBegin, double & zEnd) const inline override virtual
Get the longitudinal dimensions of the field.
Parameters
zBegin Output start of field [m].
zEnd Output end of field [m].
Implements Fieldmap.
Definition at line 85 of file TestTravelingWave.cpp.
getFieldGap()
double Fieldmap::getFieldGap () virtual inherited
Definition at line 580 of file Fieldmap.cpp.
References getFieldGap().
Referenced by getFieldGap().
getFieldmap()
Fieldmap * Fieldmap::getFieldmap (std::string Filename, bool fast = false) static inherited
Get a field map instance. Use this factory method to obtain a field map. It checks the cache (FieldmapDictionary) first.
Factory method to obtain a Fieldmap instance.
Parameters
Filename The path to the field map file.
fast If true, load a "fast" version if available (implementation dependent).
Returns
Pointer to the Fieldmap instance.
Checks the FieldmapDictionary cache to see if the file is already loaded. If not, it calls readHeader() to determine the map type, instantiates the corresponding subclass, and adds it to the dictionary.
Parameters
Filename Absolute path to the fieldmap file.
fast Not implemented. Previously attempted to load a "fast" version.
Returns
Fieldmap* Pointer to the managed fieldmap instance.
Found matching entry?
Return fieldmap pointer
Determine fieldmap type
Based on type:
Create new fieldmap object by parsing the fieldmap file
Create new FieldmapDescription object for this fieldmap
Insert FieldmapDescription into FieldmapDictionary
Return pointer to the fieldmap
Definition at line 69 of file Fieldmap.cpp.
References Fieldmap(), FieldmapDictionary, getFieldmap(), readHeader(), T2DDynamic, T2DMagnetoStatic, and TAstraDynamic.
Referenced by getFieldmap().
getFieldstrength()
bool FakeTWFieldmap::getFieldstrength (const Vector_t< double, 3 > & R, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) const inline override virtual
Get the field strength at a given point.
Parameters
R Position [m] relative to the field map origin.
E Output Electric field [MV/m].
B Output Magnetic field [T].
Returns
true if R is outside of the field map, false otherwise.
Implements Fieldmap.
Definition at line 75 of file TestTravelingWave.cpp.
References outOfBounds_.
getFrequency()
double FakeTWFieldmap::getFrequency () const inline override virtual
Get the frequency.
Returns
Frequency [MHz].
Implements Fieldmap.
Definition at line 111 of file TestTravelingWave.cpp.
getInfo()
void FakeTWFieldmap::getInfo (Inform * msg) inline override virtual
Print info about the field map.
Implements Fieldmap.
Definition at line 110 of file TestTravelingWave.cpp.
getLine() [1/2]
void Fieldmap::getLine (std::ifstream & in, int & lines_read, std::string & buffer) static protected inherited
Definition at line 394 of file Fieldmap.cpp.
References alpha_numeric, buffer_m, getLine(), and READ_BUFFER_LENGTH.
getLine() [2/2]
void Fieldmap::getLine (std::ifstream & in, std::string & buffer) inline protected inherited
Definition at line 237 of file Fieldmap.h.
References getLine(), and lines_read_m.
Referenced by getLine(), getLine(), interpretLine(), interpretLine(), interpretLine(), interpretLine(), interpretLine(), readHeader(), Astra1DDynamic::readMap(), FM2DDynamic::readMap(), and FM2DMagnetoStatic::readMap().
getListFieldmapNames()
std::vector< std::string > Fieldmap::getListFieldmapNames () static inherited
Get a list of all loaded field map names.
Returns
Vector of filenames.
Definition at line 129 of file Fieldmap.cpp.
References FieldmapDictionary, and getListFieldmapNames().
Referenced by getListFieldmapNames().
getOnaxisEz()
void FakeTWFieldmap::getOnaxisEz (std::vector< std::pair< double, double > > & F) inline override virtual
Reimplemented from Fieldmap.
Definition at line 115 of file TestTravelingWave.cpp.
getType()
MapType Fieldmap::getType () inline inherited
Definition at line 206 of file Fieldmap.h.
References Type.
Referenced by TEST_F(), TEST_F(), and TEST_F().
interpreteEOF()
bool Fieldmap::interpreteEOF (std::ifstream & in) protected inherited
Definition at line 416 of file Fieldmap.cpp.
References alpha_numeric, buffer_m, exceedingValuesWarning(), interpreteEOF(), lines_read_m, and READ_BUFFER_LENGTH.
Referenced by FM2DDynamic::FM2DDynamic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), and interpreteEOF().
interpretLine() [1/6]
template<class S> bool Fieldmap::interpretLine (std::ifstream & in, S & value, const bool & file_length_known = true) protected inherited
Referenced by Astra1DDynamic::Astra1DDynamic(), FM2DDynamic::FM2DDynamic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), Astra1DDynamic::getOnaxisEz(), interpretLine(), interpretLine(), interpretLine(), interpretLine(), interpretLine(), Astra1DDynamic::readMap(), FM2DDynamic::readMap(), and FM2DMagnetoStatic::readMap().
interpretLine() [2/6]
template<class S> bool Fieldmap::interpretLine (std::ifstream & in, S & value1, S & value2, S & value3, S & value4, S & value5, S & value6, const bool & file_length_known = true) protected inherited
Parses six values of the same type S from a line.
See also
interpretLine<T>
Definition at line 176 of file Fieldmap.hpp.
References getLine(), interpretLine(), interpretWarning(), and missingValuesWarning().
interpretLine() [3/6]
template<class S, class T> bool Fieldmap::interpretLine (std::ifstream & in, S & value1, T & value2, const bool & file_length_known = true) protected inherited
Parses two values (types S, T) from a line.
See also
interpretLine<T>
Definition at line 55 of file Fieldmap.hpp.
References getLine(), interpretLine(), interpretWarning(), and missingValuesWarning().
interpretLine() [4/6]
template<class S, class T, class U> bool Fieldmap::interpretLine (std::ifstream & in, S & value1, T & value2, U & value3, const bool & file_length_known = true) protected inherited
Parses three values (types S, T, U) from a line.
See also
interpretLine<T>
Definition at line 92 of file Fieldmap.hpp.
References getLine(), interpretLine(), interpretWarning(), and missingValuesWarning().
interpretLine() [5/6]
template<class S, class T, class U, class V> bool Fieldmap::interpretLine (std::ifstream & in, S & value1, T & value2, U & value3, V & value4, const bool & file_length_known = true) protected inherited
Parses four values (types S, T, U, V) from a line.
See also
interpretLine<T>
Definition at line 132 of file Fieldmap.hpp.
References getLine(), interpretLine(), interpretWarning(), and missingValuesWarning().
interpretLine() [6/6]
template<class T> bool Fieldmap::interpretLine (std::ifstream & in, T & value, const bool & file_length_known) inherited
Parses a single value of type T from a line in the stream.
Reads a line using getLine(), then attempts to extract one value. Validates that the extraction matches the type and that no unexpected data remains on the line.
Parameters
in Input file stream.
value Output variable reference.
file_length_known If false, EOF is acceptable.
Returns
true if successful, false if EOF (and permitted).
Definition at line 23 of file Fieldmap.hpp.
References getLine(), interpretLine(), interpretWarning(), and missingValuesWarning().
interpretWarning()
void Fieldmap::interpretWarning (const std::ios_base::iostate & state, const bool & read_all, const std::string & error_msg, const std::string & found) protected inherited
Definition at line 432 of file Fieldmap.cpp.
References Filename_m, interpretWarning(), and lines_read_m.
Referenced by interpretLine(), interpretLine(), interpretLine(), interpretLine(), interpretLine(), and interpretWarning().
isInside()
bool FakeTWFieldmap::isInside (const Vector_t< double, 3 > &) const inline override virtual
Check if a point is inside the field map.
Implements Fieldmap.
Definition at line 99 of file TestTravelingWave.cpp.
References outOfBounds_.
lowResolutionWarning()
void Fieldmap::lowResolutionWarning (double squareError, double maxError) protected inherited
Definition at line 483 of file Fieldmap.cpp.
References Filename_m, OpalData::getAuxiliaryOutputDirectory(), OpalData::getInstance(), lowResolutionWarning(), and typeset_msg().
Referenced by checkMap(), and lowResolutionWarning().
missingValuesWarning()
void Fieldmap::missingValuesWarning () protected inherited
Definition at line 450 of file Fieldmap.cpp.
References Filename_m, lines_read_m, and missingValuesWarning().
Referenced by interpretLine(), interpretLine(), interpretLine(), interpretLine(), interpretLine(), and missingValuesWarning().
noFieldmapWarning()
void Fieldmap::noFieldmapWarning () protected inherited
Definition at line 476 of file Fieldmap.cpp.
References Filename_m, and noFieldmapWarning().
Referenced by noFieldmapWarning().
readHeader()
MapType Fieldmap::readHeader (std::string Filename) static inherited
Read the header of a field map file to determine its type.
Determines the fieldmap type.
Parameters
Filename The file to check.
Returns
The MapType determined from the file header.
MapType
Definition at line 154 of file Fieldmap.cpp.
References getLine(), lines_read_m, readHeader(), T1DDynamic, T1DElectroStatic, T1DMagnetoStatic, T1DProfile1, T2DDynamic, T2DElectroStatic, T2DMagnetoStatic, T3DDynamic, T3DDynamicH5Block, T3DElectroStatic, T3DMagnetoStatic, T3DMagnetoStatic_Extended, T3DMagnetoStaticH5Block, TAstraDynamic, TAstraElectroStatic, TAstraMagnetoStatic, and UNKNOWN.
Referenced by getFieldmap(), and readHeader().
readMap() [1/2]
void FakeTWFieldmap::readMap () inline override virtual
Pure virtual method to read the map data. Called by the public static readMap().
Implements Fieldmap.
Definition at line 113 of file TestTravelingWave.cpp.
readMap() [2/2]
void Fieldmap::readMap (std::string Filename) static inherited
Trigger the actual reading of the field map data.
Parameters
Filename The file to read.
Definition at line 281 of file Fieldmap.cpp.
References FieldmapDictionary, and readMap().
Referenced by readMap(), TEST_F(), TEST_F(), and TEST_F().
setEdgeConstants()
void Fieldmap::setEdgeConstants (const double & bendAngle, const double & entranceAngle, const double & exitAngle) virtual inherited
Definition at line 388 of file Fieldmap.cpp.
References setEdgeConstants().
Referenced by setEdgeConstants().
setFieldGap()
void Fieldmap::setFieldGap (double gap) virtual inherited
Definition at line 582 of file Fieldmap.cpp.
References setFieldGap().
Referenced by setFieldGap().
setFieldLength()
void Fieldmap::setFieldLength (const double &) virtual inherited
Definition at line 392 of file Fieldmap.cpp.
References setFieldLength().
Referenced by setFieldLength().
setFrequency()
void FakeTWFieldmap::setFrequency (double freq) inline override virtual
Set the frequency.
Parameters
freq Frequency [MHz].
Implements Fieldmap.
Definition at line 112 of file TestTravelingWave.cpp.
setOutOfBounds()
void FakeTWFieldmap::setOutOfBounds (bool v) inline
Definition at line 73 of file TestTravelingWave.cpp.
References outOfBounds_.
swap()
void FakeTWFieldmap::swap () inline override virtual
Swap coordinates (implementation dependent).
Implements Fieldmap.
Definition at line 109 of file TestTravelingWave.cpp.
typeset_msg()
std::string Fieldmap::typeset_msg (const std::string & msg, const std::string & title) static inherited
Definition at line 507 of file Fieldmap.cpp.
References typeset_msg().
Referenced by FM2DMagnetoStatic::freeMap(), lowResolutionWarning(), FM2DMagnetoStatic::readMap(), and typeset_msg().
write3DField()
void Fieldmap::write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > & xrange, const std::pair< double, double > & yrange, const std::pair< double, double > & zrange, const std::vector< Vector_t< double, 3 > > & ef, const std::vector< Vector_t< double, 3 > > & bf) protected inherited
Definition at line 584 of file Fieldmap.cpp.
References Util::combineFilePath(), Filename_m, OpalData::getAuxiliaryOutputDirectory(), OpalData::getInstance(), and write3DField().
Referenced by write3DField().
Member Data Documentation
alpha_numeric
std::string Fieldmap::alpha_numeric static private inherited
Definition at line 302 of file Fieldmap.h.
Referenced by getLine(), and interpreteEOF().
buffer_m
char Fieldmap::buffer_m static private inherited
Definition at line 301 of file Fieldmap.h.
Referenced by getLine(), and interpreteEOF().
FieldmapDictionary
std::map< std::string, Fieldmap::FieldmapDescription > Fieldmap::FieldmapDictionary static private inherited
Initial value:
=
        std::map<std::string, Fieldmap::FieldmapDescription>()
Definition at line 313 of file Fieldmap.h.
Referenced by clearDictionary(), freeMap(), getFieldmap(), getListFieldmapNames(), and readMap().
Filename_m
std::string Fieldmap::Filename_m protected inherited
Definition at line 233 of file Fieldmap.h.
Referenced by Astra1DDynamic::Astra1DDynamic(), checkMap(), disableFieldmapWarning(), exceedingValuesWarning(), Fieldmap(), FM2DDynamic::FM2DDynamic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), Astra1DDynamic::freeMap(), FM2DDynamic::freeMap(), FM2DMagnetoStatic::freeMap(), Astra1DDynamic::getInfo(), FM2DDynamic::getInfo(), FM2DMagnetoStatic::getInfo(), Astra1DDynamic::getOnaxisEz(), interpretWarning(), lowResolutionWarning(), missingValuesWarning(), noFieldmapWarning(), Astra1DDynamic::readMap(), FM2DDynamic::readMap(), FM2DMagnetoStatic::readMap(), and write3DField().
lines_read_m
int Fieldmap::lines_read_m protected inherited
Definition at line 234 of file Fieldmap.h.
Referenced by Astra1DDynamic::Astra1DDynamic(), exceedingValuesWarning(), Fieldmap(), FM2DDynamic::FM2DDynamic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), getLine(), interpreteEOF(), interpretWarning(), missingValuesWarning(), and readHeader().
normalize_m
bool Fieldmap::normalize_m protected inherited
Definition at line 236 of file Fieldmap.h.
Referenced by Astra1DDynamic::Astra1DDynamic(), Fieldmap(), FM2DDynamic::FM2DDynamic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), Astra1DDynamic::readMap(), FM2DDynamic::readMap(), and FM2DMagnetoStatic::readMap().
outOfBounds_
bool FakeTWFieldmap::outOfBounds_ private
Definition at line 123 of file TestTravelingWave.cpp.
Referenced by FakeTWFieldmap(), getFieldstrength(), isInside(), and setOutOfBounds().
Type
MapType Fieldmap::Type protected inherited
Definition at line 231 of file Fieldmap.h.
Referenced by Astra1DDynamic::Astra1DDynamic(), FM2DDynamic::FM2DDynamic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), and getType().
The documentation for this class was generated from the following file:
TestTravelingWave.cpp