OPALX (Object Oriented Parallel Accelerator Library for Exascal): LogicalError Class Reference
LogicalError Class Reference
Logical error exception.
#include <LogicalError.h>
Public Member Functions
LogicalError (const std::string &meth, const std::string &msg)
The usual constructor.
LogicalError (const LogicalError &)
virtual ~LogicalError ()
virtual const std::string & what () const
Return the message string for the exception.
virtual const std::string & where () const
Return the name of the method or function which detected the exception.
Private Member Functions
LogicalError ()
Private Attributes
const std::string message
const std::string method
Detailed Description
Logical error exception.
Definition at line 33 of file LogicalError.h.
Constructor & Destructor Documentation
LogicalError() [1/3]
LogicalError::LogicalError (const std::string & meth, const std::string & msg)
The usual constructor.
Definition at line 26 of file LogicalError.cpp.
References OpalException::OpalException().
Referenced by LogicalError().
LogicalError() [2/3]
LogicalError::LogicalError (const LogicalError & rhs)
Definition at line 29 of file LogicalError.cpp.
References LogicalError(), and OpalException::OpalException().
~LogicalError()
LogicalError::~LogicalError () virtual
Definition at line 31 of file LogicalError.cpp.
LogicalError() [3/3]
LogicalError::LogicalError () private
Member Function Documentation
what()
const std::string & OpalException::what () const virtual inherited
Return the message string for the exception.
Definition at line 31 of file OpalException.cpp.
References message.
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), main(), OpalParser::readStatement(), OpalParser::run(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and TEST_F().
where()
const std::string & OpalException::where () const virtual inherited
Return the name of the method or function which detected the exception.
Definition at line 33 of file OpalException.cpp.
References method.
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), main(), OpalParser::run(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and TEST_F().
Member Data Documentation
message
const std::string OpalException::message private inherited
Definition at line 56 of file OpalException.h.
Referenced by OpalException(), OpalException(), and what().
method
const std::string OpalException::method private inherited
Definition at line 57 of file OpalException.h.
Referenced by DivideError::DivideError(), OpalException(), OpalException(), and where().
The documentation for this class was generated from the following files:
LogicalError.h
LogicalError.cpp