OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions::SNull< T > Class Template Reference
Expressions::SNull< T > Class Template Reference
A scalar expression without operands.
#include <SNull.h>
Public Member Functions
SNull (const TFunction0< T > &function)
Constructor.
SNull (const SNull< T > &)
virtual ~SNull ()
virtual Scalar< T > * clone () const
Make clone.
virtual T evaluate () const
Evaluate.
virtual void print (std::ostream &str, int precedence=99) const
Print expression.
virtual bool isConstant () const
Test for constant.
Static Public Member Functions
static Scalar< T > * make (const TFunction0< T > &function)
Make expression.
Private Member Functions
SNull ()
void operator= (const SNull &)
Private Attributes
const TFunction0< T > & fun
Detailed Description
template<class T>
class Expressions::SNull< T >
A scalar expression without operands.
Definition at line 37 of file SNull.h.
Constructor & Destructor Documentation
SNull() [1/3]
template<class T> Expressions::SNull< T >::SNull (const TFunction0< T > & function) inline explicit
Constructor.
Definition at line 76 of file SNull.h.
References fun.
Referenced by clone(), make(), operator=(), and SNull().
SNull() [2/3]
template<class T> Expressions::SNull< T >::SNull (const SNull< T > & rhs) inline
Definition at line 73 of file SNull.h.
References fun, Expressions::Scalar< T >::Scalar(), and SNull().
~SNull()
template<class T> Expressions::SNull< T >::~SNull () inline virtual
Definition at line 79 of file SNull.h.
SNull() [3/3]
template<class T> Expressions::SNull< T >::SNull () private
Member Function Documentation
clone()
template<class T> Scalar< T > * Expressions::SNull< T >::clone () const inline virtual
Make clone.
Implements Expressions::Scalar< T >.
Definition at line 82 of file SNull.h.
References Expressions::Scalar< T >::Scalar(), and SNull().
evaluate()
template<class T> T Expressions::SNull< T >::evaluate () const inline virtual
Evaluate.
Implements Expressions::Scalar< T >.
Definition at line 87 of file SNull.h.
References fun.
isConstant()
template<class T> bool Expressions::Scalar< T >::isConstant () const inline virtual inherited
Test for constant.
Reimplemented in Expressions::SConstant< T >.
Definition at line 287 of file AbstractObjects/Expressions.h.
make()
template<class T> Scalar< T > * Expressions::SNull< T >::make (const TFunction0< T > & function) inline static
Make expression.
Definition at line 107 of file SNull.h.
References fun, Expressions::Scalar< T >::Scalar(), and SNull().
Referenced by Expressions::parseArrayPrimary(), and Expressions::parsePrimary().
operator=()
template<class T> void Expressions::SNull< T >::operator= (const SNull< T > &) private
References SNull().
print()
template<class T> void Expressions::SNull< T >::print (std::ostream & str, int precedence = 99) const inline virtual
Print expression.
Implements Expressions::Scalar< T >.
Definition at line 112 of file SNull.h.
References fun.
Member Data Documentation
fun
template<class T> const TFunction0<T>& Expressions::SNull< T >::fun private
Definition at line 66 of file SNull.h.
Referenced by evaluate(), make(), print(), SNull(), and SNull().
The documentation for this class was generated from the following file:
SNull.h