OPALX (Object Oriented Parallel Accelerator Library for Exascal): Distribution Class Reference
Distribution Class Reference
#include <Distribution.h>
Classes
class BinomialBehaviorSplitter
class GaussianLikeBehavior
class MDependentBehavior
Public Types
using Matrix_t = ippl::Vector< ippl::Vector< double, 6 >, 6 >
Public Member Functions
Distribution ()
virtual ~Distribution ()
virtual bool canReplaceBy (Object *object)
Distribution can only be replaced by another distribution.
virtual Distribution * clone (const std::string &name)
Return a clone.
virtual void execute ()
Execute the command.
size_t getNumOfLocalParticlesToCreate (size_t n)
std::string getTypeofDistribution ()
DistributionType getType () const
size_t getNumParticles () const
Inform & printInfo (Inform &os) const
ippl::Vector< double, 3 > get_pmean () const
ippl::Vector< double, 3 > get_xmean () const
ippl::Vector< double, 3 > getSigmaR () const
ippl::Vector< double, 3 > getSigmaP () const
double getSigmaTRise () const
double getSigmaTFall () const
double getTPulseLengthFWHM () const
double getFTOSCAmplitude () const
double getFTOSCPeriods () const
void setDistType ()
void setDist ()
void setAvrgPz (double avrgpz)
double getAvrgpz () const
ippl::Vector< double, 3 > getCutoffR () const
ippl::Vector< double, 3 > getCutoffP () const
double getTEmission () const
void setTEmission (double tEmission)
std::string getFilename () const
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Static Public Member Functions
static Distribution * find (const std::string &name)
Public Attributes
Matrix_t correlationMatrix_m
bool emitting_m
std::vector< Attribute > itsAttr
The object attributes.
Protected Attributes
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Private Types
enum class EmissionModel : unsigned short { NONE , ASTRA , NONEQUIL }
enum class InputMomentumUnits : unsigned short { NONE , EVOVERC }
Private Member Functions
Distribution (const std::string &name, Distribution *parent)
Distribution (const Distribution &)=delete
void operator= (const Distribution &)=delete
void addDistributions ()
void calcPartPerDist (size_t numberOfParticles)
void checkParticleNumber (size_t &numberOfParticles)
void chooseInputMomentumUnits (InputMomentumUnits inputMoUnits)
size_t getNumberOfParticlesInFile (std::ifstream &inputFile)
void printDist (Inform &os, size_t numberOfParticles) const
void printDistGauss (Inform &os) const
void printDistMultiVariateGauss (Inform &os) const
void printDistFlatTop (Inform &os) const
void printDistFromFile (Inform &os) const
void setAttributes ()
void setDistParametersGauss ()
void setDistParametersMultiVariateGauss ()
void setDistParametersFlatTop ()
void setSigmaR_m ()
void setSigmaP_m ()
Private Attributes
std::string distT_m
PartData particleRefData_m
Distribution type strings.
size_t totalNumberParticles_m
ippl::Vector< double, 3 > pmean_m
ippl::Vector< double, 3 > xmean_m
ippl::Vector< double, 3 > sigmaR_m
ippl::Vector< double, 3 > sigmaP_m
ippl::Vector< double, 3 > cutoffR_m
ippl::Vector< double, 3 > cutoffP_m
double sigmaTRise_m
double sigmaTFall_m
double tPulseLengthFWHM_m
DistributionType distrTypeT_m
double avrgpz_m
double FTOSCAmplitude_m
double FTOSCPeriods_m
double tEmission_m
Object * itsParent
std::string itsName
std::string itsHelp
int occurrence
double timeStamp
std::set< Invalidator * > references
bool sharedFlag
Detailed Description
Definition at line 61 of file Distribution.h.
Member Typedef Documentation
Matrix_t
using Distribution::Matrix_t = ippl::Vector<ippl::Vector<double, 6>, 6>
Definition at line 67 of file Distribution.h.
Member Enumeration Documentation
EmissionModel
enum class Distribution::EmissionModel : unsigned short strong private
Enumerator
NONE
ASTRA
NONEQUIL
Definition at line 127 of file Distribution.h.
InputMomentumUnits
enum class Distribution::InputMomentumUnits : unsigned short strong private
Enumerator
NONE
EVOVERC
Definition at line 129 of file Distribution.h.
Constructor & Destructor Documentation
Distribution() [1/3]
Distribution::Distribution ()
Definition at line 103 of file Distribution.cpp.
References DISTRIBUTION::CORR, DISTRIBUTION::CORRT, DISTRIBUTION::CORRX, DISTRIBUTION::CORRY, DISTRIBUTION::CORRZ, DISTRIBUTION::CUTOFFLONG, DISTRIBUTION::CUTOFFPX, DISTRIBUTION::CUTOFFPY, DISTRIBUTION::CUTOFFPZ, DISTRIBUTION::CUTOFFX, DISTRIBUTION::CUTOFFY, DISTRIBUTION::EMITTED, DISTRIBUTION::FNAME, DISTRIBUTION::FTOSCAMPLITUDE, DISTRIBUTION::FTOSCPERIODS, Object::itsAttr, Attributes::makeBool(), Attributes::makePredefinedString(), Attributes::makeReal(), Attributes::makeRealArray(), Attributes::makeString(), DISTRIBUTION::NPARTDIST, Object::registerOwnership(), DISTRIBUTION::SIGMAPX, DISTRIBUTION::SIGMAPY, DISTRIBUTION::SIGMAPZ, DISTRIBUTION::SIGMAT, DISTRIBUTION::SIGMAX, DISTRIBUTION::SIGMAY, DISTRIBUTION::SIGMAZ, AttributeHandler::STATEMENT, DISTRIBUTION::TFALL, DISTRIBUTION::TPULSEFWHM, DISTRIBUTION::TRISE, and DISTRIBUTION::TYPE.
Referenced by clone().
~Distribution()
Distribution::~Distribution () virtual
Definition at line 190 of file Distribution.cpp.
Distribution() [2/3]
Distribution::Distribution (const std::string & name, Distribution * parent) private
Definition at line 187 of file Distribution.cpp.
Distribution() [3/3]
Distribution::Distribution (const Distribution &) private delete
Member Function Documentation
addDistributions()
void Distribution::addDistributions () private
calcPartPerDist()
void Distribution::calcPartPerDist (size_t numberOfParticles) private
Create the particle distribution.
Parameters
numberOfParticles to create
massIneV particle charge in eV
charge of the particle type in elementary charge
canReplaceBy()
bool Distribution::canReplaceBy (Object * object) virtual
Distribution can only be replaced by another distribution.
Reimplemented from Object.
Definition at line 212 of file Distribution.cpp.
checkParticleNumber()
void Distribution::checkParticleNumber (size_t & numberOfParticles) private
chooseInputMomentumUnits()
void Distribution::chooseInputMomentumUnits (InputMomentumUnits inputMoUnits) private
clear()
void Object::clear () inherited
Clear the occurrence counter.
Definition at line 285 of file Object.cpp.
References Object::occurrence.
clone()
Distribution * Distribution::clone (const std::string & name) virtual
Return a clone.
Implements Object.
Definition at line 214 of file Distribution.cpp.
References Distribution().
copyAttributes()
void Object::copyAttributes (const Object & source) inherited
Copy attributes from another object.
Definition at line 50 of file Object.cpp.
References Object::itsAttr.
Referenced by SequenceTemplate::makeInstance(), and LineTemplate::makeInstance().
execute()
void Distribution::execute () virtual
Execute the command.
Reimplemented from Object.
Definition at line 216 of file Distribution.cpp.
References setAttributes(), and Object::update().
find()
Distribution * Distribution::find (const std::string & name) static
Definition at line 221 of file Distribution.cpp.
References OpalData::find(), and OpalData::getInstance().
Referenced by TrackRun::computeTotalAllocationForBunch(), and TrackRun::setupDistributionsAndSamplers().
findAttribute() [1/2]
Attribute * Object::findAttribute (const std::string & name) virtual inherited
Find an attribute by name.
Definition at line 56 of file Object.cpp.
References Object::itsAttr.
Referenced by SequenceParser::findNeighbourPositions(), OpalElement::getParticleMatterInteraction(), OpalElement::getTypeName(), OpalElement::getWakeF(), Object::parse(), OpalElement::parse(), Line::parse(), OpalParser::parseAssign(), SequenceParser::parsePosition(), TrackRun::print(), and TEST().
findAttribute() [2/2]
const Attribute * Object::findAttribute (const std::string & name) const virtual inherited
Find an attribute by name.
Definition at line 63 of file Object.cpp.
References Object::itsAttr.
get_pmean()
ippl::Vector< double, 3 > Distribution::get_pmean () const inline
Definition at line 236 of file Distribution.h.
References pmean_m.
get_xmean()
ippl::Vector< double, 3 > Distribution::get_xmean () const inline
Definition at line 238 of file Distribution.h.
References xmean_m.
getAvrgpz()
double Distribution::getAvrgpz () const inline
Definition at line 256 of file Distribution.h.
References avrgpz_m.
Referenced by Gaussian::Gaussian(), and MultiVariateGaussian::MultiVariateGaussian().
getBaseObject()
const Object * Object::getBaseObject () const inherited
Return the object's base type object.
Definition at line 260 of file Object.cpp.
References Object::itsParent.
getCategory()
const std::string Definition::getCategory () const virtual inherited
Return the object category as a string.
Implements Object.
Definition at line 26 of file Definition.cpp.
getCutoffP()
ippl::Vector< double, 3 > Distribution::getCutoffP () const inline
Definition at line 242 of file Distribution.h.
References cutoffP_m.
Referenced by MultiVariateGaussian::MultiVariateGaussian().
getCutoffR()
ippl::Vector< double, 3 > Distribution::getCutoffR () const inline
Definition at line 240 of file Distribution.h.
References cutoffR_m.
Referenced by Gaussian::Gaussian(), MultiVariateGaussian::MultiVariateGaussian(), and FlatTop::setParameters().
getFilename()
std::string Distribution::getFilename () const
Definition at line 479 of file Distribution.cpp.
References DISTRIBUTION::FNAME, Attributes::getString(), and Object::itsAttr.
Referenced by FromFile::FromFile(), and printDistFromFile().
getFTOSCAmplitude()
double Distribution::getFTOSCAmplitude () const inline
Definition at line 250 of file Distribution.h.
References FTOSCAmplitude_m.
getFTOSCPeriods()
double Distribution::getFTOSCPeriods () const inline
Definition at line 252 of file Distribution.h.
References FTOSCPeriods_m.
getNumberOfParticlesInFile()
size_t Distribution::getNumberOfParticlesInFile (std::ifstream & inputFile) private
getNumOfLocalParticlesToCreate()
size_t Distribution::getNumOfLocalParticlesToCreate (size_t n)
Calculate the local number of particles evenly and adjust node 0 such that n is matched exactly.
Parameters
n total number of particles
Returns
n / #cores
Parameters
Definition at line 200 of file Distribution.cpp.
getNumParticles()
size_t Distribution::getNumParticles () const inline
Return the number of macroparticles assigned to this distribution. If 0, the distribution did not specify its own NPARTDIST.
Definition at line 258 of file Distribution.h.
References totalNumberParticles_m.
Referenced by FromFile::emitParticles(), Gaussian::emitParticles(), MultiVariateGaussian::emitParticles(), and TrackRun::setupDistributionsAndSamplers().
getOpalName()
const std::string & Object::getOpalName () const inherited
Return object name.
Definition at line 267 of file Object.cpp.
References Object::itsName.
Referenced by OpalVariableRFCavity::clone(), Macro::clone(), OpalData::create(), OpalData::define(), Sequence::findDriftLength(), SequenceParser::findNeighbourPositions(), ValueDefinition::getBool(), ValueDefinition::getBoolComponent(), ValueDefinition::getReal(), ValueDefinition::getRealComponent(), ValueDefinition::getString(), ValueDefinition::getStringComponent(), Object::makeInstance(), SequenceTemplate::makeInstance(), LineTemplate::makeInstance(), Object::parse(), SequenceParser::parseMember(), SequenceParser::parsePosition(), Object::print(), OpalElement::print(), Sequence::print(), TrackRun::print(), BoolConstant::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), StringConstant::print(), Beam::print(), OpalFilter::print(), Line::print(), BinningCmd::printInfo(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), OpalElement::registerOwnership(), Object::registerOwnership(), Line::replace(), Sequence::replace(), PartBunch< T, Dim >::setBins(), TEST(), TEST(), TEST(), TEST_F(), Beam::update(), BoundaryGeometry::update(), OpalFilter::update(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), and OpalSplineTimeDependence::update().
getParent()
Object * Object::getParent () const inherited
Return parent pointer.
Definition at line 269 of file Object.cpp.
References Object::itsParent.
Referenced by OpalData::erase(), Object::print(), OpalElement::print(), OpalElement::registerOwnership(), and Object::registerOwnership().
getSigmaP()
ippl::Vector< double, 3 > Distribution::getSigmaP () const inline
Definition at line 234 of file Distribution.h.
References sigmaP_m.
Referenced by Gaussian::Gaussian(), and MultiVariateGaussian::MultiVariateGaussian().
getSigmaR()
ippl::Vector< double, 3 > Distribution::getSigmaR () const inline
Definition at line 232 of file Distribution.h.
References sigmaR_m.
Referenced by Gaussian::Gaussian(), MultiVariateGaussian::MultiVariateGaussian(), and FlatTop::setParameters().
getSigmaTFall()
double Distribution::getSigmaTFall () const inline
Definition at line 246 of file Distribution.h.
References sigmaTFall_m.
Referenced by FlatTop::setParameters().
getSigmaTRise()
double Distribution::getSigmaTRise () const inline
Definition at line 244 of file Distribution.h.
References sigmaTRise_m.
Referenced by FlatTop::setParameters().
getTEmission()
double Distribution::getTEmission () const
Distribution is an emitted, and is currently emitting, rather than an injected, beam.
Definition at line 269 of file Distribution.cpp.
References tEmission_m.
getTPulseLengthFWHM()
double Distribution::getTPulseLengthFWHM () const inline
Definition at line 248 of file Distribution.h.
References tPulseLengthFWHM_m.
Referenced by FlatTop::setParameters().
getType()
DistributionType Distribution::getType () const inline
Definition at line 254 of file Distribution.h.
References distrTypeT_m.
Referenced by TrackRun::setupDistributionsAndSamplers().
getTypeofDistribution()
std::string Distribution::getTypeofDistribution () inline
Definition at line 260 of file Distribution.h.
References distT_m.
Referenced by TrackRun::setupDistributionsAndSamplers().
increment()
int Object::increment () inherited
Increment and return the occurrence counter.
Definition at line 287 of file Object.cpp.
References Object::occurrence.
Referenced by Line::parse(), and Sequence::storeLine().
isBuiltin()
bool Object::isBuiltin () const inherited
True, if [b]this[/b] is a built-in object.
Definition at line 243 of file Object.cpp.
References Object::builtin.
Referenced by OpalData::define(), and OpalData::getVariableNames().
isDirty()
bool Object::isDirty () const inherited
True, if the [b]modified[/b] flag is set.
Definition at line 254 of file Object.cpp.
References Object::modified.
isFlagged()
bool Object::isFlagged () const inherited
True, if [b]this[/b] is flagged by setFlag(true).
Definition at line 258 of file Object.cpp.
References Object::flagged.
isShared()
bool Object::isShared () const virtual inherited
Shared flag.
Definition at line 245 of file Object.cpp.
References Object::sharedFlag.
Referenced by Sequence::print().
isTreeMember()
bool Object::isTreeMember (const Object * subTree) const inherited
Test for tree membership.
Definition at line 271 of file Object.cpp.
References Object::itsParent.
Referenced by Selector::handleElement(), and OpalParser::parseAssign().
makeInstance()
Object * Object::makeInstance (const std::string & name, Statement & , const Parser *) virtual inherited
Macro handler function.
Reimplemented in SequenceTemplate, MacroCmd, and LineTemplate.
Definition at line 76 of file Object.cpp.
References Object::getOpalName().
Referenced by OpalParser::parseDefine(), and OpalParser::parseMacro().
makeTemplate()
Object * Object::makeTemplate (const std::string & name, TokenStream & , Statement &) virtual inherited
Macro handler function.
Reimplemented in LineTemplate, Sequence, MacroCmd, SequenceTemplate, and Line.
Definition at line 71 of file Object.cpp.
Referenced by OpalParser::parseMacro().
occurrenceCount()
int Object::occurrenceCount () inherited
Return the occurrence counter.
Definition at line 289 of file Object.cpp.
References Object::occurrence.
operator=()
void Distribution::operator= (const Distribution &) private delete
parse()
void Object::parse (Statement & stat) virtual inherited
Parse the object.
Reimplemented in Call, Echo, Help, PSystem, System, Title, Value, OpalElement, Sequence, EmissionSourceList, and Line.
Definition at line 82 of file Object.cpp.
References Statement::delimiter(), Object::findAttribute(), Object::getOpalName(), Expressions::parseDelimiter(), Expressions::parseRealConst(), and Expressions::parseString().
Referenced by Sequence::parse(), OpalParser::parseAction(), OpalParser::parseDefine(), and SequenceTemplate::parseTemplate().
parseShortcut()
void Object::parseShortcut (Statement & stat, bool eval = true) virtual inherited
Parser for single-attribute commands.
Definition at line 113 of file Object.cpp.
Referenced by Call::parse(), Echo::parse(), Help::parse(), PSystem::parse(), System::parse(), Title::parse(), and Value::parse().
print()
void Object::print (std::ostream & msg) const virtual inherited
Print the object.
Reimplemented in OpalBend, OpalElement, OpalMarker, OpalMultipole, OpalQuadrupole, OpalRingDefinition, Sequence, TrackRun, BoolConstant, RealConstant, RealVariable, RealVector, StringConstant, OpalPolynomialTimeDependence, OpalSinusoidalTimeDependence, OpalSplineTimeDependence, Beam, OpalFilter, DumpEMFields, OpalMultipoleT, and Line.
Definition at line 146 of file Object.cpp.
References Object::getOpalName(), Object::getParent(), and Object::itsAttr.
Referenced by Object::printValue().
printDist()
void Distribution::printDist (Inform & os, size_t numberOfParticles) const private
printDistFlatTop()
void Distribution::printDistFlatTop (Inform & os) const private
Definition at line 445 of file Distribution.cpp.
References cutoffR_m, emitting_m, sigmaR_m, sigmaTFall_m, sigmaTRise_m, and tPulseLengthFWHM_m.
Referenced by printInfo().
printDistFromFile()
void Distribution::printDistFromFile (Inform & os) const private
Definition at line 468 of file Distribution.cpp.
References getFilename().
Referenced by printInfo().
printDistGauss()
void Distribution::printDistGauss (Inform & os) const private
Definition at line 415 of file Distribution.cpp.
References sigmaP_m, and sigmaR_m.
Referenced by printInfo().
printDistMultiVariateGauss()
void Distribution::printDistMultiVariateGauss (Inform & os) const private
Definition at line 426 of file Distribution.cpp.
References correlationMatrix_m, sigmaP_m, and sigmaR_m.
Referenced by printInfo().
printHelp()
void Object::printHelp (std::ostream &) const virtual inherited
Print help.
Definition at line 179 of file Object.cpp.
References gmsg, Object::itsAttr, and Object::itsHelp.
Referenced by Help::execute().
printInfo()
Inform & Distribution::printInfo (Inform & os) const
Definition at line 231 of file Distribution.cpp.
References distrTypeT_m, FLATTOP, FROMFILE, GAUSS, OpalData::getInstance(), MULTIVARIATEGAUSS, printDistFlatTop(), printDistFromFile(), printDistGauss(), and printDistMultiVariateGauss().
Referenced by operator<<().
printValue()
void Object::printValue (std::ostream & os) const inline virtual inherited
Reimplemented in BoolConstant, RealConstant, RealVariable, RealVector, and StringConstant.
Definition at line 270 of file Object.h.
References Object::print().
registerOwnership()
void Object::registerOwnership (const AttributeHandler::OwnerType & itsClass) const inherited
Definition at line 169 of file Object.cpp.
References AttributeHandler::addAttributeOwner(), Object::getOpalName(), Object::getParent(), and Object::itsAttr.
Referenced by Beam::Beam(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), Call::Call(), Distribution(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), EmissionSourceList::EmissionSourceList(), Help::Help(), Line::Line(), OpalFilter::OpalFilter(), Option::Option(), PSystem::PSystem(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVector::RealVector(), Select::Select(), Sequence::Sequence(), StringConstant::StringConstant(), System::System(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), and Value::Value().
registerReference()
void Object::registerReference (Invalidator * a) inherited
Register a reference to this object.
Definition at line 165 of file Object.cpp.
References Object::references.
replace()
void Object::replace (Object * oldObject, Object * newObject) virtual inherited
Replace references.
Reimplemented in Line, and Sequence.
Definition at line 235 of file Object.cpp.
setAttributes()
void Distribution::setAttributes () private
Definition at line 483 of file Distribution.cpp.
References Attributes::getReal(), Object::itsAttr, DISTRIBUTION::NPARTDIST, setDist(), and totalNumberParticles_m.
Referenced by execute().
setAvrgPz()
void Distribution::setAvrgPz (double avrgpz)
Definition at line 265 of file Distribution.cpp.
References avrgpz_m.
Referenced by TrackRun::setupDistributionsAndSamplers().
setDirty()
void Object::setDirty (bool dirty) inherited
Set/reset the [b]modified[/b] flag.
Definition at line 249 of file Object.cpp.
References Object::modified.
Referenced by OpalData::define(), OpalData::makeDirty(), and RealVariable::RealVariable().
setDist()
void Distribution::setDist ()
Definition at line 494 of file Distribution.cpp.
References distrTypeT_m, FLATTOP, FROMFILE, GAUSS, MULTIVARIATEGAUSS, setDistParametersFlatTop(), setDistParametersGauss(), setDistParametersMultiVariateGauss(), and setDistType().
Referenced by setAttributes(), and TrackRun::setupDistributionsAndSamplers().
setDistParametersFlatTop()
void Distribution::setDistParametersFlatTop () private
Definition at line 348 of file Distribution.cpp.
References correlationMatrix_m, DISTRIBUTION::CORRT, DISTRIBUTION::CORRX, DISTRIBUTION::CORRY, DISTRIBUTION::CORRZ, DISTRIBUTION::CUTOFFLONG, cutoffP_m, cutoffR_m, DISTRIBUTION::CUTOFFX, DISTRIBUTION::CUTOFFY, DISTRIBUTION::EMITTED, emitting_m, DISTRIBUTION::FTOSCAMPLITUDE, FTOSCAmplitude_m, DISTRIBUTION::FTOSCPERIODS, FTOSCPeriods_m, Attributes::getBool(), Attributes::getReal(), Object::itsAttr, setSigmaP_m(), setSigmaR_m(), sigmaR_m, DISTRIBUTION::SIGMAT, sigmaTFall_m, sigmaTRise_m, DISTRIBUTION::TFALL, DISTRIBUTION::TPULSEFWHM, tPulseLengthFWHM_m, and DISTRIBUTION::TRISE.
Referenced by setDist().
setDistParametersGauss()
void Distribution::setDistParametersGauss () private
Definition at line 271 of file Distribution.cpp.
References avrgpz_m, cutoffP_m, cutoffR_m, setSigmaP_m(), and setSigmaR_m().
Referenced by setDist().
setDistParametersMultiVariateGauss()
void Distribution::setDistParametersMultiVariateGauss () private
Definition at line 302 of file Distribution.cpp.
References avrgpz_m, DISTRIBUTION::CORR, correlationMatrix_m, cutoffP_m, cutoffR_m, Attributes::getRealArray(), gmsg, Object::itsAttr, setSigmaP_m(), setSigmaR_m(), sigmaP_m, and sigmaR_m.
Referenced by setDist().
setDistType()
void Distribution::setDistType ()
Definition at line 517 of file Distribution.cpp.
References distrTypeT_m, distT_m, FLATTOP, FROMFILE, GAUSS, Attributes::getString(), Object::itsAttr, MULTIVARIATEGAUSS, NODIST, and DISTRIBUTION::TYPE.
Referenced by setDist(), and TrackRun::setupDistributionsAndSamplers().
setFlag()
void Object::setFlag (bool flag) inherited
Flag/unflag this object, e. g. to control output of objects for.
Definition at line 256 of file Object.cpp.
References Object::flagged.
setOpalName()
void Object::setOpalName (const std::string & name) inherited
Set object name.
Definition at line 281 of file Object.cpp.
References Object::itsName.
Referenced by TEST(), TEST(), TEST(), Beam::update(), BoundaryGeometry::update(), and OpalFilter::update().
setParent()
void Object::setParent (Object * parent) inherited
Set parent object.
Definition at line 283 of file Object.cpp.
References Object::itsParent.
Referenced by OpalData::erase().
setShared()
void Object::setShared (bool flag) virtual inherited
Set/reset shared flag.
Reimplemented in Element.
Definition at line 247 of file Object.cpp.
References Object::sharedFlag.
Referenced by OpalParser::parseDefine(), and Element::setShared().
setSigmaP_m()
void Distribution::setSigmaP_m () private
Definition at line 543 of file Distribution.cpp.
References Attributes::getReal(), Object::itsAttr, sigmaP_m, DISTRIBUTION::SIGMAPX, DISTRIBUTION::SIGMAPY, and DISTRIBUTION::SIGMAPZ.
Referenced by setDistParametersFlatTop(), setDistParametersGauss(), and setDistParametersMultiVariateGauss().
setSigmaR_m()
void Distribution::setSigmaR_m () private
Definition at line 536 of file Distribution.cpp.
References Attributes::getReal(), Object::itsAttr, sigmaR_m, DISTRIBUTION::SIGMAX, DISTRIBUTION::SIGMAY, and DISTRIBUTION::SIGMAZ.
Referenced by setDistParametersFlatTop(), setDistParametersGauss(), and setDistParametersMultiVariateGauss().
setTEmission()
void Distribution::setTEmission (double tEmission)
Definition at line 267 of file Distribution.cpp.
References tEmission_m.
Referenced by FlatTop::setParameters().
shouldTrace()
bool Definition::shouldTrace () const virtual inherited
Trace flag.
Implements Object.
Definition at line 28 of file Definition.cpp.
shouldUpdate()
bool Definition::shouldUpdate () const virtual inherited
Update flag.
Implements Object.
Definition at line 30 of file Definition.cpp.
unregisterReference()
void Object::unregisterReference (Invalidator * a) inherited
Unegister a reference to this object.
Definition at line 167 of file Object.cpp.
References Object::references.
update()
void Object::update () virtual inherited
Update this object.
Reimplemented in Option, OpalCavity, OpalConstantEFieldCavity, OpalDrift, OpalElement, OpalMarker, OpalMonitor, OpalMultipole, OpalProbe, OpalQuadrupole, OpalRBend, OpalRingDefinition, OpalSBend, OpalSolenoid, OpalSource, OpalTravelingWave, OpalVacuum, OpalVerticalFFAMagnet, Sequence, Beam, BinningCmd, BoundaryGeometry, FieldSolverCmd, OpalFilter, OpalLaser, OpalMultipoleT, OpalPolynomialTimeDependence, OpalSinusoidalTimeDependence, OpalSplineTimeDependence, and OpalVariableRFCavity.
Definition at line 239 of file Object.cpp.
Referenced by execute().
Member Data Documentation
avrgpz_m
double Distribution::avrgpz_m private
Definition at line 222 of file Distribution.h.
Referenced by getAvrgpz(), setAvrgPz(), setDistParametersGauss(), and setDistParametersMultiVariateGauss().
builtin
bool Object::builtin protected inherited
Built-in flag.
Definition at line 226 of file Object.h.
Referenced by Beam::Beam(), BoundaryGeometry::BoundaryGeometry(), Object::isBuiltin(), Object::Object(), Object::Object(), OpalFilter::OpalFilter(), OpalMarker::OpalMarker(), RealConstant::RealConstant(), StringConstant::StringConstant(), and Table::~Table().
correlationMatrix_m
Matrix_t Distribution::correlationMatrix_m
Definition at line 116 of file Distribution.h.
Referenced by MultiVariateGaussian::MultiVariateGaussian(), printDistMultiVariateGauss(), setDistParametersFlatTop(), and setDistParametersMultiVariateGauss().
cutoffP_m
ippl::Vector<double, 3> Distribution::cutoffP_m private
Definition at line 214 of file Distribution.h.
Referenced by getCutoffP(), setDistParametersFlatTop(), setDistParametersGauss(), and setDistParametersMultiVariateGauss().
cutoffR_m
ippl::Vector<double, 3> Distribution::cutoffR_m private
Definition at line 214 of file Distribution.h.
Referenced by getCutoffR(), printDistFlatTop(), setDistParametersFlatTop(), setDistParametersGauss(), and setDistParametersMultiVariateGauss().
distrTypeT_m
DistributionType Distribution::distrTypeT_m private
Definition at line 220 of file Distribution.h.
Referenced by getType(), printInfo(), setDist(), and setDistType().
distT_m
std::string Distribution::distT_m private
Definition at line 207 of file Distribution.h.
Referenced by getTypeofDistribution(), and setDistType().
emitting_m
bool Distribution::emitting_m
Definition at line 118 of file Distribution.h.
Referenced by printDistFlatTop(), setDistParametersFlatTop(), FlatTop::setParameters(), and TrackRun::setupDistributionsAndSamplers().
flagged
bool Object::flagged protected inherited
Object flag.
Definition at line 235 of file Object.h.
Referenced by Object::isFlagged(), Object::Object(), Object::Object(), and Object::setFlag().
FTOSCAmplitude_m
double Distribution::FTOSCAmplitude_m private
Definition at line 224 of file Distribution.h.
Referenced by getFTOSCAmplitude(), and setDistParametersFlatTop().
FTOSCPeriods_m
double Distribution::FTOSCPeriods_m private
Definition at line 225 of file Distribution.h.
Referenced by getFTOSCPeriods(), and setDistParametersFlatTop().
itsAttr
std::vector<Attribute> Object::itsAttr inherited
The object attributes.
Definition at line 210 of file Object.h.
Referenced by Beam::Beam(), BinningCmd::BinningCmd(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), BoundaryGeometry::BoundaryGeometry(), DumpEMFields::buildGrid(), Call::Call(), FieldSolverCmd::constructBCHandler(), Object::copyAttributes(), Distribution(), BinningCmd::dumpBinsToFile(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), Call::execute(), Echo::execute(), Help::execute(), Option::execute(), PSystem::execute(), Select::execute(), System::execute(), Title::execute(), Value::execute(), Beam::execute(), TrackCmd::execute(), TrackRun::execute(), FieldSolverCmd::FieldSolverCmd(), Object::findAttribute(), Object::findAttribute(), BoundaryGeometry::getA(), OpalElement::getApert(), BoundaryGeometry::getB(), BinningCmd::getBinningAlpha(), BinningCmd::getBinningBeta(), FieldSolverCmd::getBinsName(), BoolConstant::getBool(), FieldSolverCmd::getBoxIncr(), Beam::getBunchCharge(), BoundaryGeometry::getC(), Beam::getCharge(), Beam::getCurrent(), Beam::getDaughterBeamName(), BinningCmd::getDesiredWidth(), EmissionSource::getDistributionName(), FieldSolverCmd::getDomDec(), TrackCmd::getDT(), TrackCmd::getDTAU(), TrackCmd::getDTSCINIT(), BinningCmd::getDumpBinsFileName(), BinningCmd::getDumpBinsFrequency(), EmissionSource::getEmissionModel(), Beam::getEmissionSourceListName(), getFilename(), BoundaryGeometry::getFilename(), Beam::getFrequency(), Beam::getGlobalProcessNames(), BoundaryGeometry::getL1(), BoundaryGeometry::getL2(), BoundaryGeometry::getLength(), OpalElement::getLength(), Line::getLength(), Sequence::getLength(), Beam::getMass(), BinningCmd::getMaxBins(), TrackCmd::getMaxSteps(), Beam::getNumAlloc(), FieldSolverCmd::getNX(), FieldSolverCmd::getNY(), FieldSolverCmd::getNZ(), EmissionSource::getP0(), BinningCmd::getParameter(), Beam::getParticleName(), EmissionSource::getR0(), RealConstant::getReal(), RealVariable::getReal(), RealVector::getRealComponent(), Sequence::getReference(), BoundaryGeometry::getS(), EmissionSource::getShiftedGreensFunction(), TrackCmd::getStepsPerTurn(), StringConstant::getString(), EmissionSource::getT0(), TrackCmd::getT0(), BinningCmd::getTablePrintFrequency(), TrackCmd::getTimeIntegrator(), BoundaryGeometry::getTopology(), FieldSolverCmd::getType(), EmissionSource::getZerofaceMaxSteps(), EmissionSource::getZeroFacePlaneDumpFrequency(), EmissionSource::getZeroFaceR0Z(), TrackCmd::getZStart(), TrackCmd::getZStop(), Beam::hasExplicitEnergy(), Help::Help(), BoundaryGeometry::initialize(), OpalFilter::initOpalFilter(), Beam::isPhoton(), Line::Line(), OpalBend::OpalBend(), OpalCavity::OpalCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalDrift::OpalDrift(), OpalElement::OpalElement(), OpalFilter::OpalFilter(), OpalLaser::OpalLaser(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalPolynomialTimeDependence::OpalPolynomialTimeDependence(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalRingDefinition::OpalRingDefinition(), OpalSinusoidalTimeDependence::OpalSinusoidalTimeDependence(), OpalSolenoid::OpalSolenoid(), OpalSplineTimeDependence::OpalSplineTimeDependence(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), Option::Option(), Option::Option(), Sequence::parse(), Line::parse(), DumpEMFields::parseCoordinateSystem(), Object::print(), Sequence::print(), BoolConstant::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), StringConstant::print(), Beam::print(), OpalFilter::print(), DumpEMFields::print(), Object::printHelp(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), BoolConstant::printValue(), RealConstant::printValue(), RealVariable::printValue(), RealVector::printValue(), StringConstant::printValue(), PSystem::PSystem(), RealConstant::RealConstant(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVariable::RealVariable(), RealVector::RealVector(), OpalElement::registerOwnership(), Object::registerOwnership(), Select::Select(), Select::select(), Sequence::Sequence(), setAttributes(), TestMultipoleT::TestableFieldSolverCmd::setBCX(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCX(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCX(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCX(), TestVariableRFCavity::TestableFieldSolverCmd::setBCX(), OrbitThreaderTest::TestableFieldSolverCmd::setBCX(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCX(), TestMultipoleT::TestableFieldSolverCmd::setBCY(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCY(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCY(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCY(), TestVariableRFCavity::TestableFieldSolverCmd::setBCY(), OrbitThreaderTest::TestableFieldSolverCmd::setBCY(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCY(), TestMultipoleT::TestableFieldSolverCmd::setBCZ(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCZ(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCZ(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCZ(), TestVariableRFCavity::TestableFieldSolverCmd::setBCZ(), OrbitThreaderTest::TestableFieldSolverCmd::setBCZ(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCZ(), TestableBinningCmd::setBinningAlpha(), TestableBinningCmd::setBinningBeta(), TestableBinningCmd::setDesiredWidth(), setDistParametersFlatTop(), setDistParametersMultiVariateGauss(), setDistType(), TestableBinningCmd::setDumpBinsFile(), TestableBinningCmd::setDumpBinsFreq(), TestableBinningCmd::setMaxBins(), FieldSolverCmd::setNX(), FieldSolverCmd::setNY(), FieldSolverCmd::setNZ(), TestableBinningCmd::setParameterString(), TrackRun::setRunMethod(), setSigmaP_m(), setSigmaR_m(), TestableBinningCmd::setTablePrintFrequency(), TestMultipoleT::TestableFieldSolverCmd::setType(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setType(), TestMultipoleTStraight::TestableFieldSolverCmd::setType(), SolenoidPlacementTest::TestableFieldSolverCmd::setType(), TestVariableRFCavity::TestableFieldSolverCmd::setType(), OrbitThreaderTest::TestableFieldSolverCmd::setType(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setType(), TrackRun::setupBoundaryGeometry(), StringConstant::StringConstant(), StringConstant::StringConstant(), System::System(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), OpalCavity::update(), OpalConstantEFieldCavity::update(), OpalDrift::update(), OpalElement::update(), OpalMonitor::update(), OpalMultipole::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalRBend::update(), OpalRingDefinition::update(), OpalSBend::update(), OpalSolenoid::update(), OpalTravelingWave::update(), OpalVacuum::update(), OpalVerticalFFAMagnet::update(), Beam::update(), BinningCmd::update(), FieldSolverCmd::update(), OpalLaser::update(), OpalMultipoleT::update(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), OpalSplineTimeDependence::update(), OpalVariableRFCavity::update(), Option::update(), OpalElement::updateUnknown(), ValueDefinition::value(), Value::Value(), and ValueDefinition::value().
itsHelp
std::string Object::itsHelp private inherited
Definition at line 250 of file Object.h.
Referenced by Object::printHelp().
itsName
std::string Object::itsName private inherited
Definition at line 247 of file Object.h.
Referenced by Object::getOpalName(), and Object::setOpalName().
itsParent
Object* Object::itsParent private inherited
Definition at line 244 of file Object.h.
Referenced by Object::getBaseObject(), Object::getParent(), Object::isTreeMember(), and Object::setParent().
modified
bool Object::modified protected inherited
Dirty flag.
Definition at line 231 of file Object.h.
Referenced by Object::isDirty(), Object::Object(), Object::Object(), and Object::setDirty().
occurrence
int Object::occurrence private inherited
Definition at line 253 of file Object.h.
Referenced by Object::clear(), Object::increment(), and Object::occurrenceCount().
particleRefData_m
PartData Distribution::particleRefData_m private
Distribution type strings.
Definition at line 209 of file Distribution.h.
pmean_m
ippl::Vector<double, 3> Distribution::pmean_m private
Definition at line 214 of file Distribution.h.
Referenced by get_pmean().
references
std::set<Invalidator*> Object::references private inherited
Definition at line 260 of file Object.h.
Referenced by Object::registerReference(), Object::unregisterReference(), and Object::~Object().
sharedFlag
bool Object::sharedFlag private inherited
Definition at line 263 of file Object.h.
Referenced by Object::isShared(), and Object::setShared().
sigmaP_m
ippl::Vector<double, 3> Distribution::sigmaP_m private
Definition at line 214 of file Distribution.h.
Referenced by getSigmaP(), printDistGauss(), printDistMultiVariateGauss(), setDistParametersMultiVariateGauss(), and setSigmaP_m().
sigmaR_m
ippl::Vector<double, 3> Distribution::sigmaR_m private
Definition at line 214 of file Distribution.h.
Referenced by getSigmaR(), printDistFlatTop(), printDistGauss(), printDistMultiVariateGauss(), setDistParametersFlatTop(), setDistParametersMultiVariateGauss(), and setSigmaR_m().
sigmaTFall_m
double Distribution::sigmaTFall_m private
Definition at line 217 of file Distribution.h.
Referenced by getSigmaTFall(), printDistFlatTop(), and setDistParametersFlatTop().
sigmaTRise_m
double Distribution::sigmaTRise_m private
Definition at line 216 of file Distribution.h.
Referenced by getSigmaTRise(), printDistFlatTop(), and setDistParametersFlatTop().
tEmission_m
double Distribution::tEmission_m private
Definition at line 227 of file Distribution.h.
Referenced by getTEmission(), and setTEmission().
timeStamp
double Object::timeStamp private inherited
Definition at line 256 of file Object.h.
totalNumberParticles_m
size_t Distribution::totalNumberParticles_m private
Reference data for particle type (charge, mass etc.)
Definition at line 212 of file Distribution.h.
Referenced by getNumParticles(), and setAttributes().
tPulseLengthFWHM_m
double Distribution::tPulseLengthFWHM_m private
Definition at line 218 of file Distribution.h.
Referenced by getTPulseLengthFWHM(), printDistFlatTop(), and setDistParametersFlatTop().
xmean_m
ippl::Vector<double, 3> Distribution::xmean_m private
Definition at line 214 of file Distribution.h.
Referenced by get_xmean().
The documentation for this class was generated from the following files:
Distribution.h
Distribution.cpp