OPALX (Object Oriented Parallel Accelerator Library for Exascal): Mesher Class Reference
Mesher Class Reference
#include <Mesher.h>
Public Member Functions
Mesher (std::vector< Vector_t< double, 3 > > &vertices)
std::vector< mslang::Triangle > getTriangles () const
Private Member Functions
void orientVerticesCCW ()
bool isConvex (unsigned int i) const
double crossProduct (const Vector_t< double, 3 > &a, const Vector_t< double, 3 > &b) const
bool isPointOnLine (unsigned int i, unsigned int j, const Vector_t< double, 3 > &pt) const
bool isPointRightOfLine (unsigned int i, unsigned int j, const Vector_t< double, 3 > &pt) const
bool lineSegmentTouchesOrCrossesLine (unsigned int i, unsigned int j, unsigned int k, unsigned int l) const
bool isPotentialEdgeIntersected (unsigned int i) const
double dotProduct (unsigned int i, unsigned int j, const Vector_t< double, 3 > &pt) const
bool isPointInsideCone (unsigned int i, unsigned int j, unsigned int jPlusOne, unsigned int jMinusOne) const
bool isEar (unsigned int i) const
std::vector< unsigned int > findAllEars () const
double computeMinimumAngle (unsigned int i) const
unsigned int selectBestEar (std::vector< unsigned int > &ears) const
void apply ()
Private Attributes
std::vector< mslang::Triangle > triangles_m
std::vector< Vector_t< double, 3 > > vertices_m
Detailed Description
Definition at line 6 of file Mesher.h.
Constructor & Destructor Documentation
Mesher()
Mesher::Mesher (std::vector< Vector_t< double, 3 > > & vertices)
Definition at line 3 of file Mesher.cpp.
References apply(), and vertices_m.
Member Function Documentation
apply()
void Mesher::apply () private
Definition at line 192 of file Mesher.cpp.
References findAllEars(), mslang::Triangle::nodes_m, orientVerticesCCW(), selectBestEar(), triangles_m, and vertices_m.
Referenced by Mesher().
computeMinimumAngle()
double Mesher::computeMinimumAngle (unsigned int i) const private
Definition at line 155 of file Mesher.cpp.
References mslang::euclidean_norm2D(), and vertices_m.
Referenced by selectBestEar().
crossProduct()
double Mesher::crossProduct (const Vector_t< double, 3 > & a, const Vector_t< double, 3 > & b) const private
Definition at line 38 of file Mesher.cpp.
Referenced by isPointOnLine(), and isPointRightOfLine().
dotProduct()
double Mesher::dotProduct (unsigned int i, unsigned int j, const Vector_t< double, 3 > & pt) const private
Definition at line 106 of file Mesher.cpp.
References vertices_m.
Referenced by isPointInsideCone().
findAllEars()
std::vector< unsigned int > Mesher::findAllEars () const private
Definition at line 142 of file Mesher.cpp.
References isEar(), and vertices_m.
Referenced by apply().
getTriangles()
std::vector< mslang::Triangle > Mesher::getTriangles () const
Definition at line 5 of file Mesher.cpp.
References triangles_m.
Referenced by mslang::Polygon::triangulize().
isConvex()
bool Mesher::isConvex (unsigned int i) const private
Definition at line 24 of file Mesher.cpp.
References vertices_m.
Referenced by isEar().
isEar()
bool Mesher::isEar (unsigned int i) const private
Definition at line 126 of file Mesher.cpp.
References isConvex(), isPointInsideCone(), isPotentialEdgeIntersected(), and vertices_m.
Referenced by findAllEars().
isPointInsideCone()
bool Mesher::isPointInsideCone (unsigned int i, unsigned int j, unsigned int jPlusOne, unsigned int jMinusOne) const private
Definition at line 117 of file Mesher.cpp.
References dotProduct(), isPointRightOfLine(), and vertices_m.
Referenced by isEar().
isPointOnLine()
bool Mesher::isPointOnLine (unsigned int i, unsigned int j, const Vector_t< double, 3 > & pt) const private
Definition at line 42 of file Mesher.cpp.
References crossProduct(), and vertices_m.
Referenced by lineSegmentTouchesOrCrossesLine().
isPointRightOfLine()
bool Mesher::isPointRightOfLine (unsigned int i, unsigned int j, const Vector_t< double, 3 > & pt) const private
Definition at line 51 of file Mesher.cpp.
References crossProduct(), and vertices_m.
Referenced by isPointInsideCone(), and lineSegmentTouchesOrCrossesLine().
isPotentialEdgeIntersected()
bool Mesher::isPotentialEdgeIntersected (unsigned int i) const private
Definition at line 65 of file Mesher.cpp.
References mslang::BoundingBox2D::center_m, mslang::BoundingBox2D::doesIntersect(), mslang::BoundingBox2D::height_m, lineSegmentTouchesOrCrossesLine(), vertices_m, and mslang::BoundingBox2D::width_m.
Referenced by isEar().
lineSegmentTouchesOrCrossesLine()
bool Mesher::lineSegmentTouchesOrCrossesLine (unsigned int i, unsigned int j, unsigned int k, unsigned int l) const private
Definition at line 59 of file Mesher.cpp.
References isPointOnLine(), isPointRightOfLine(), and vertices_m.
Referenced by isPotentialEdgeIntersected().
orientVerticesCCW()
void Mesher::orientVerticesCCW () private
Definition at line 7 of file Mesher.cpp.
References vertices_m.
Referenced by apply().
selectBestEar()
unsigned int Mesher::selectBestEar (std::vector< unsigned int > & ears) const private
Definition at line 174 of file Mesher.cpp.
References computeMinimumAngle().
Referenced by apply().
Member Data Documentation
triangles_m
std::vector<mslang::Triangle> Mesher::triangles_m private
Definition at line 30 of file Mesher.h.
Referenced by apply(), and getTriangles().
vertices_m
std::vector<Vector_t<double, 3> > Mesher::vertices_m private
Definition at line 31 of file Mesher.h.
Referenced by apply(), computeMinimumAngle(), dotProduct(), findAllEars(), isConvex(), isEar(), isPointInsideCone(), isPointOnLine(), isPointRightOfLine(), isPotentialEdgeIntersected(), lineSegmentTouchesOrCrossesLine(), Mesher(), and orientVerticesCCW().
The documentation for this class was generated from the following files:
Mesher.h
Mesher.cpp