OPALX (Object Oriented Parallel Accelerator Library for Exascal): Astra1DDynamic Class Reference
Astra1DDynamic Class Reference
#include <Astra1DDynamic.h>
Public Member Functions
virtual bool getFieldstrength (const Vector_t< double, 3 > &R, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) const override
Get the field strength at a given point.
virtual bool getFieldDerivative (const Vector_t< double, 3 > &R, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B, const DiffDirection &dir) const override
Get the field derivative with respect to a direction.
virtual void getFieldDimensions (double &zBegin, double &zEnd) const override
Get the longitudinal dimensions of the field.
virtual void getFieldDimensions (double &xIni, double &xFinal, double &yIni, double &yFinal, double &zIni, double &zFinal) const override
Get the full 3D bounding box of the field.
virtual void swap () override
Swap coordinates.
virtual void getInfo (Inform *msg) override
Print info about the field map.
virtual double getFrequency () const override
Get the frequency.
virtual void setFrequency (double freq) override
Set the frequency.
bool isInside (const Vector_t< double, 3 > &r) const override
Checks if the given coordinate is inside the volume covered by the fieldmap.
void applyField (std::shared_ptr< ParticleContainer_t > pc, double) override
Apply the FM to all the particles.
void applyTravelingWave (std::shared_ptr< ParticleContainer_t > pc, double entryElectricScale, double entryMagneticScale, double core1ElectricScale, double core1MagneticScale, double core2ElectricScale, double core2MagneticScale, double exitElectricScale, double exitMagneticScale, double startField, double startCoreField, double startExitField, double mappedStartExitField, double periodLength, double cellLength, double elementLength)
Apply the traveling-wave RF field map to all particles.
virtual void getOnaxisEz (std::vector< std::pair< double, double > > &F) override
virtual void setEdgeConstants (const double &bendAngle, const double &entranceAngle, const double &exitAngle)
virtual void setFieldLength (const double &)
virtual void get1DProfile1EngeCoeffs (std::vector< double > &engeCoeffsEntry, std::vector< double > &engeCoeffsExit)
virtual void get1DProfile1EntranceParam (double &entranceParameter1, double &entranceParameter2, double &entranceParameter3)
virtual void get1DProfile1ExitParam (double &exitParameter1, double &exitParameter2, double &exitParameter3)
virtual double getFieldGap ()
virtual void setFieldGap (double gap)
MapType getType ()
template<class T >
bool interpretLine (std::ifstream &in, T &value, const bool &file_length_known)
Parses a single value of type T from a line in the stream.
Static Public Member Functions
template<class ViewType >
static KOKKOS_INLINE_FUNCTION void computeField (const Vector_t< double, 3 > &R, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B, const ViewType &FourCoefs, double zbegin, double length, double xlrep, int accuracy)
template<class ViewType >
static KOKKOS_INLINE_FUNCTION void computeTravelingWaveField (const Vector_t< double, 3 > &R, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B, const ViewType &FourCoefs, double zbegin, double zend, double length, double xlrep, int accuracy, double entryElectricScale, double entryMagneticScale, double core1ElectricScale, double core1MagneticScale, double core2ElectricScale, double core2MagneticScale, double exitElectricScale, double exitMagneticScale, double startCoreField, double startExitField, double mappedStartExitField, double periodLength, double cellLength, double elementLength)
static Fieldmap * getFieldmap (std::string Filename, bool fast=false)
Get a field map instance. Use this factory method to obtain a field map. It checks the cache (FieldmapDictionary) first.
static std::vector< std::string > getListFieldmapNames ()
Get a list of all loaded field map names.
static void deleteFieldmap (std::string Filename)
Delete a specific field map from the cache and memory.
static void clearDictionary ()
Clear the entire field map cache.
static MapType readHeader (std::string Filename)
Read the header of a field map file to determine its type.
static void readMap (std::string Filename)
Trigger the actual reading of the field map data.
static void freeMap (std::string Filename)
Decrease reference count or delete field map if unused.
static std::string typeset_msg (const std::string &msg, const std::string &title)
Protected Member Functions
void getLine (std::ifstream &in, std::string &buffer)
template<class S >
bool interpretLine (std::ifstream &in, S &value, const bool &file_length_known=true)
template<class S , class T >
bool interpretLine (std::ifstream &in, S &value1, T &value2, const bool &file_length_known=true)
Parses two values (types S, T) from a line.
template<class S , class T , class U >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, const bool &file_length_known=true)
Parses three values (types S, T, U) from a line.
template<class S , class T , class U , class V >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, V &value4, const bool &file_length_known=true)
Parses four values (types S, T, U, V) from a line.
template<class S >
bool interpretLine (std::ifstream &in, S &value1, S &value2, S &value3, S &value4, S &value5, S &value6, const bool &file_length_known=true)
Parses six values of the same type S from a line.
bool interpreteEOF (std::ifstream &in)
void interpretWarning (const std::ios_base::iostate &state, const bool &read_all, const std::string &error_msg, const std::string &found)
void missingValuesWarning ()
void exceedingValuesWarning ()
void disableFieldmapWarning ()
void noFieldmapWarning ()
void lowResolutionWarning (double squareError, double maxError)
void checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void checkMap (unsigned int accuracy, double length, const std::vector< double > &zSampling, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > &xrange, const std::pair< double, double > &yrange, const std::pair< double, double > &zrange, const std::vector< Vector_t< double, 3 > > &ef, const std::vector< Vector_t< double, 3 > > &bf)
Static Protected Member Functions
static void getLine (std::ifstream &in, int &lines_read, std::string &buffer)
Protected Attributes
MapType Type
std::string Filename_m
int lines_read_m
bool normalize_m
Private Member Functions
Astra1DDynamic (const std::string &filename)
~Astra1DDynamic ()
void readMap () override
Pure virtual method to read the map data. Called by the public static readMap().
void freeMap () override
Pure virtual method to free the map data.
Private Attributes
Kokkos::DualView< double * > FourCoefs_m
Fourier coefficients of Ez(z) (device-accessible) Stored as: [a0, a1, b1, a2, b2, ..., aN, bN] and used in the reconstruction Ez(z) = a0 + sum_l [ a_l cos(l*kz) - b_l sin(l*kz) ].
std::vector< double > zRaw_m
std::vector< double > ezRaw_m
double frequency_m
double zbegin_m
Z Bounds relative to element edge.
double zend_m
double xlrep_m
Wave number (omega / c)
double length_m
Effective periodic length of the field map [m].
int accuracy_m
Number of Fourier modes used.
int num_gridpz_m
Number of grid points in z-direction (input sampling)
Static Private Attributes
static char buffer_m [256]
static std::string alpha_numeric
static std::map< std::string, FieldmapDescription > FieldmapDictionary
Friends
class Fieldmap
Allow Fieldmap factory access.
Detailed Description
Definition at line 10 of file Astra1DDynamic.h.
Constructor & Destructor Documentation
Astra1DDynamic()
Astra1DDynamic::Astra1DDynamic (const std::string & filename) private
Definition at line 17 of file Astra1DDynamic.cpp.
References accuracy_m, Astra1DDynamic(), Physics::c, Fieldmap::disableFieldmapWarning(), Fieldmap::Filename_m, frequency_m, length_m, Fieldmap::lines_read_m, Units::MHz2Hz, Fieldmap::noFieldmapWarning(), Fieldmap::normalize_m, num_gridpz_m, TAstraDynamic, Util::toUpper(), Physics::two_pi, Fieldmap::Type, xlrep_m, zbegin_m, and zend_m.
Referenced by Astra1DDynamic().
~Astra1DDynamic()
Astra1DDynamic::~Astra1DDynamic () private
Definition at line 105 of file Astra1DDynamic.cpp.
References freeMap(), and ~Astra1DDynamic().
Referenced by ~Astra1DDynamic().
Member Function Documentation
applyField()
void Astra1DDynamic::applyField (std::shared_ptr< ParticleContainer_t > pc, double) override virtual
Apply the FM to all the particles.
Parameters
pc Particle container
pc Particle container
scale Scaling factor for the field (currently not used)
Implements Fieldmap.
Definition at line 306 of file Astra1DDynamic.cpp.
References accuracy_m, applyField(), computeField(), FourCoefs_m, length_m, xlrep_m, zbegin_m, and zend_m.
Referenced by applyField().
applyTravelingWave()
void Astra1DDynamic::applyTravelingWave (std::shared_ptr< ParticleContainer_t > pc, double entryElectricScale, double entryMagneticScale, double core1ElectricScale, double core1MagneticScale, double core2ElectricScale, double core2MagneticScale, double exitElectricScale, double exitMagneticScale, double startField, double startCoreField, double startExitField, double mappedStartExitField, double periodLength, double cellLength, double elementLength)
Apply the traveling-wave RF field map to all particles.
This is the device-safe path used by TravelingWave. It avoids calling the virtual Fieldmap::getFieldstrength() interface inside a Kokkos kernel and reproduces the traveling-wave cavity region logic directly on device.
The cavity is split into three longitudinal regions:
entry region: direct field-map application with entry phase/scale
core region: superposition of two periodically shifted field contributions
exit region: remapped field-map application with exit phase/scale
Parameters
pc Particle container.
entryElectricScale Scale factor applied to E in the entry region.
entryMagneticScale Scale factor applied to B in the entry region.
core1ElectricScale Scale factor applied to the first core contribution in E.
core1MagneticScale Scale factor applied to the first core contribution in B.
core2ElectricScale Scale factor applied to the second core contribution in E.
core2MagneticScale Scale factor applied to the second core contribution in B.
exitElectricScale Scale factor applied to E in the exit region.
exitMagneticScale Scale factor applied to B in the exit region.
startField Longitudinal beginning of the full traveling-wave structure.
startCoreField Longitudinal beginning of the periodic core region.
startExitField Longitudinal beginning of the exit region.
mappedStartExitField Shift used to remap the exit region into field-map coordinates.
periodLength Period length of the base field-map cell.
cellLength Cell-to-cell longitudinal shift in the core region.
elementLength Total longitudinal length of the traveling-wave element.
Definition at line 345 of file Astra1DDynamic.cpp.
References accuracy_m, applyTravelingWave(), computeTravelingWaveField(), FourCoefs_m, length_m, xlrep_m, zbegin_m, and zend_m.
Referenced by applyTravelingWave().
checkMap() [1/2]
void Fieldmap::checkMap (unsigned int accuracy, double length, const std::vector< double > & zSampling, const std::vector< double > & fourierCoefficients, gsl_spline * splineCoefficients, gsl_interp_accel * splineAccelerator) protected inherited
Definition at line 330 of file Fieldmap.cpp.
References Fieldmap::checkMap(), Util::combineFilePath(), Fieldmap::Filename_m, OpalData::getInstance(), gsl_spline_eval(), Fieldmap::lowResolutionWarning(), and Physics::two_pi.
checkMap() [2/2]
void Fieldmap::checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > & fourierCoefficients, gsl_spline * splineCoefficients, gsl_interp_accel * splineAccelerator) protected inherited
Definition at line 315 of file Fieldmap.cpp.
References Fieldmap::checkMap().
Referenced by Fieldmap::checkMap(), and Fieldmap::checkMap().
clearDictionary()
void Fieldmap::clearDictionary () static inherited
Clear the entire field map cache.
Definition at line 138 of file Fieldmap.cpp.
References Fieldmap::clearDictionary(), and Fieldmap::FieldmapDictionary.
Referenced by Fieldmap::clearDictionary().
computeField()
template<class ViewType > static KOKKOS_INLINE_FUNCTION void Astra1DDynamic::computeField (const Vector_t< double, 3 > & R, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B, const ViewType & FourCoefs, double zbegin, double length, double xlrep, int accuracy) inline static
Definition at line 97 of file Astra1DDynamic.h.
References Physics::c, Physics::pi, and Physics::two_pi.
Referenced by applyField(), computeTravelingWaveField(), and getFieldstrength().
computeTravelingWaveField()
template<class ViewType > static KOKKOS_INLINE_FUNCTION void Astra1DDynamic::computeTravelingWaveField (const Vector_t< double, 3 > & R, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B, const ViewType & FourCoefs, double zbegin, double zend, double length, double xlrep, int accuracy, double entryElectricScale, double entryMagneticScale, double core1ElectricScale, double core1MagneticScale, double core2ElectricScale, double core2MagneticScale, double exitElectricScale, double exitMagneticScale, double startCoreField, double startExitField, double mappedStartExitField, double periodLength, double cellLength, double elementLength) inline static
Definition at line 148 of file Astra1DDynamic.h.
References computeField().
Referenced by applyTravelingWave().
deleteFieldmap()
void Fieldmap::deleteFieldmap (std::string Filename) static inherited
Delete a specific field map from the cache and memory.
Parameters
Filename The filename of the map to delete.
Definition at line 134 of file Fieldmap.cpp.
References Fieldmap::deleteFieldmap(), and Fieldmap::freeMap().
Referenced by Fieldmap::deleteFieldmap().
disableFieldmapWarning()
void Fieldmap::disableFieldmapWarning () protected inherited
Definition at line 471 of file Fieldmap.cpp.
References Fieldmap::disableFieldmapWarning(), and Fieldmap::Filename_m.
Referenced by Astra1DDynamic(), Fieldmap::disableFieldmapWarning(), FM2DDynamic::FM2DDynamic(), and FM2DMagnetoStatic::FM2DMagnetoStatic().
exceedingValuesWarning()
void Fieldmap::exceedingValuesWarning () protected inherited
Definition at line 461 of file Fieldmap.cpp.
References Fieldmap::exceedingValuesWarning(), Fieldmap::Filename_m, and Fieldmap::lines_read_m.
Referenced by Fieldmap::exceedingValuesWarning(), and Fieldmap::interpreteEOF().
freeMap() [1/2]
void Astra1DDynamic::freeMap () override private virtual
Pure virtual method to free the map data.
Implements Fieldmap.
Definition at line 288 of file Astra1DDynamic.cpp.
References Fieldmap::Filename_m, FourCoefs_m, and freeMap().
Referenced by freeMap(), and ~Astra1DDynamic().
freeMap() [2/2]
void Fieldmap::freeMap (std::string Filename) static inherited
Decrease reference count or delete field map if unused.
Parameters
Filename The file to free.
Definition at line 296 of file Fieldmap.cpp.
References Fieldmap::FieldmapDictionary, and Fieldmap::freeMap().
Referenced by Fieldmap::freeMap(), TEST_F(), TEST_F(), and TEST_F().
get1DProfile1EngeCoeffs()
void Fieldmap::get1DProfile1EngeCoeffs (std::vector< double > & engeCoeffsEntry, std::vector< double > & engeCoeffsExit) virtual inherited
Definition at line 573 of file Fieldmap.cpp.
References Fieldmap::get1DProfile1EngeCoeffs().
Referenced by Fieldmap::get1DProfile1EngeCoeffs().
get1DProfile1EntranceParam()
void Fieldmap::get1DProfile1EntranceParam (double & entranceParameter1, double & entranceParameter2, double & entranceParameter3) virtual inherited
Definition at line 577 of file Fieldmap.cpp.
References Fieldmap::get1DProfile1EntranceParam().
Referenced by Fieldmap::get1DProfile1EntranceParam().
get1DProfile1ExitParam()
void Fieldmap::get1DProfile1ExitParam (double & exitParameter1, double & exitParameter2, double & exitParameter3) virtual inherited
Definition at line 582 of file Fieldmap.cpp.
References Fieldmap::get1DProfile1ExitParam().
Referenced by Fieldmap::get1DProfile1ExitParam().
getFieldDerivative()
bool Astra1DDynamic::getFieldDerivative (const Vector_t< double, 3 > & R, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B, const DiffDirection & dir) const override virtual
Get the field derivative with respect to a direction.
Get the derivative of the field at position R.
Parameters
R Position [m].
E Output derivative of Electric field.
B Output derivative of Magnetic field.
dir Direction of derivative (DX, DY, DZ).
Returns
true if R is outside, false otherwise.
Parameters
R Position
E Electric Field
B Derivate of the magnetic field (unused)
Implements Fieldmap.
Definition at line 437 of file Astra1DDynamic.cpp.
References accuracy_m, FourCoefs_m, getFieldDerivative(), length_m, Physics::pi, Physics::two_pi, and zbegin_m.
Referenced by getFieldDerivative().
getFieldDimensions() [1/2]
void Astra1DDynamic::getFieldDimensions (double & xIni, double & xFinal, double & yIni, double & yFinal, double & zIni, double & zFinal) const override virtual
Get the full 3D bounding box of the field.
Parameters
xIni Output minimum x [m].
xFinal Output maximum x [m].
yIni Output minimum y [m].
yFinal Output maximum y [m].
zIni Output minimum z [m].
zFinal Output maximum z [m].
Implements Fieldmap.
Definition at line 466 of file Astra1DDynamic.cpp.
References getFieldDimensions().
getFieldDimensions() [2/2]
void Astra1DDynamic::getFieldDimensions (double & zBegin, double & zEnd) const override virtual
Get the longitudinal dimensions of the field.
Parameters
zBegin Output start of field [m].
zEnd Output end of field [m].
Implements Fieldmap.
Definition at line 460 of file Astra1DDynamic.cpp.
References getFieldDimensions(), zbegin_m, and zend_m.
Referenced by getFieldDimensions(), and getFieldDimensions().
getFieldGap()
double Fieldmap::getFieldGap () virtual inherited
Definition at line 586 of file Fieldmap.cpp.
References Fieldmap::getFieldGap().
Referenced by Fieldmap::getFieldGap().
getFieldmap()
Fieldmap * Fieldmap::getFieldmap (std::string Filename, bool fast = false) static inherited
Get a field map instance. Use this factory method to obtain a field map. It checks the cache (FieldmapDictionary) first.
Factory method to obtain a Fieldmap instance.
Parameters
Filename The path to the field map file.
fast If true, load a "fast" version if available (implementation dependent).
Returns
Pointer to the Fieldmap instance.
Checks the FieldmapDictionary cache to see if the file is already loaded. If not, it calls readHeader() to determine the map type, instantiates the corresponding subclass, and adds it to the dictionary.
Parameters
Filename Absolute path to the fieldmap file.
fast Not implemented. Previously attempted to load a "fast" version.
Returns
Fieldmap* Pointer to the managed fieldmap instance.
Found matching entry?
Return fieldmap pointer
Determine fieldmap type
Based on type:
Create new fieldmap object by parsing the fieldmap file
Create new FieldmapDescription object for this fieldmap
Insert FieldmapDescription into FieldmapDictionary
Return pointer to the fieldmap
Definition at line 69 of file Fieldmap.cpp.
References Fieldmap::FieldmapDictionary, Fieldmap::getFieldmap(), Fieldmap::readHeader(), T2DDynamic, T2DMagnetoStatic, and TAstraDynamic.
Referenced by Fieldmap::getFieldmap().
getFieldstrength()
bool Astra1DDynamic::getFieldstrength (const Vector_t< double, 3 > & R, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) const override virtual
Get the field strength at a given point.
Parameters
R Position [m] relative to the field map origin.
E Output Electric field [MV/m].
B Output Magnetic field [T].
Returns
true if R is outside of the field map, false otherwise.
Implements Fieldmap.
Definition at line 407 of file Astra1DDynamic.cpp.
References accuracy_m, computeField(), FourCoefs_m, getFieldstrength(), isInside(), length_m, xlrep_m, and zbegin_m.
Referenced by getFieldstrength().
getFrequency()
double Astra1DDynamic::getFrequency () const override virtual
Get the frequency.
Returns
Frequency [MHz].
Note
Not implemented yet
Implements Fieldmap.
Definition at line 486 of file Astra1DDynamic.cpp.
References frequency_m, and getFrequency().
Referenced by getFrequency().
getInfo()
void Astra1DDynamic::getInfo (Inform * msg) override virtual
Print info about the field map.
Implements Fieldmap.
Definition at line 479 of file Astra1DDynamic.cpp.
References Fieldmap::Filename_m, getInfo(), zbegin_m, and zend_m.
Referenced by getInfo().
getLine() [1/2]
void Fieldmap::getLine (std::ifstream & in, int & lines_read, std::string & buffer) static protected inherited
Definition at line 396 of file Fieldmap.cpp.
References Fieldmap::alpha_numeric, Fieldmap::buffer_m, Fieldmap::getLine(), and READ_BUFFER_LENGTH.
getLine() [2/2]
void Fieldmap::getLine (std::ifstream & in, std::string & buffer) inline protected inherited
Definition at line 256 of file Fieldmap.h.
References Fieldmap::getLine(), and Fieldmap::lines_read_m.
Referenced by Fieldmap::getLine(), Fieldmap::getLine(), Fieldmap::interpretLine(), Fieldmap::interpretLine(), Fieldmap::interpretLine(), Fieldmap::interpretLine(), Fieldmap::interpretLine(), Fieldmap::readHeader(), readMap(), FM2DDynamic::readMap(), and FM2DMagnetoStatic::readMap().
getListFieldmapNames()
std::vector< std::string > Fieldmap::getListFieldmapNames () static inherited
Get a list of all loaded field map names.
Returns
Vector of filenames.
Definition at line 125 of file Fieldmap.cpp.
References Fieldmap::FieldmapDictionary, and Fieldmap::getListFieldmapNames().
Referenced by Fieldmap::getListFieldmapNames().
getOnaxisEz()
void Astra1DDynamic::getOnaxisEz (std::vector< std::pair< double, double > > & F) override virtual
Reimplemented from Fieldmap.
Definition at line 501 of file Astra1DDynamic.cpp.
References Fieldmap::Filename_m, getOnaxisEz(), and num_gridpz_m.
Referenced by getOnaxisEz().
getType()
MapType Fieldmap::getType () inline inherited
Definition at line 221 of file Fieldmap.h.
References Fieldmap::Type.
Referenced by TEST_F(), TEST_F(), and TEST_F().
interpreteEOF()
bool Fieldmap::interpreteEOF (std::ifstream & in) protected inherited
Definition at line 418 of file Fieldmap.cpp.
References Fieldmap::alpha_numeric, Fieldmap::buffer_m, Fieldmap::exceedingValuesWarning(), Fieldmap::interpreteEOF(), Fieldmap::lines_read_m, and READ_BUFFER_LENGTH.
Referenced by FM2DDynamic::FM2DDynamic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), and Fieldmap::interpreteEOF().
interpretLine() [1/6]
template<class S > bool Fieldmap::interpretLine (std::ifstream & in, S & value, const bool & file_length_known = true) protected inherited
Referenced by Fieldmap::interpretLine(), Fieldmap::interpretLine(), Fieldmap::interpretLine(), Fieldmap::interpretLine(), and Fieldmap::interpretLine().
interpretLine() [2/6]
template<class S > bool Fieldmap::interpretLine (std::ifstream & in, S & value1, S & value2, S & value3, S & value4, S & value5, S & value6, const bool & file_length_known = true) protected inherited
Parses six values of the same type S from a line.
See also
interpretLine<T>
Definition at line 169 of file Fieldmap.hpp.
References Fieldmap::getLine(), Fieldmap::interpretLine(), Fieldmap::interpretWarning(), and Fieldmap::missingValuesWarning().
interpretLine() [3/6]
template<class S , class T > bool Fieldmap::interpretLine (std::ifstream & in, S & value1, T & value2, const bool & file_length_known = true) protected inherited
Parses two values (types S, T) from a line.
See also
interpretLine<T>
Definition at line 55 of file Fieldmap.hpp.
References Fieldmap::getLine(), Fieldmap::interpretLine(), Fieldmap::interpretWarning(), and Fieldmap::missingValuesWarning().
interpretLine() [4/6]
template<class S , class T , class U > bool Fieldmap::interpretLine (std::ifstream & in, S & value1, T & value2, U & value3, const bool & file_length_known = true) protected inherited
Parses three values (types S, T, U) from a line.
See also
interpretLine<T>
Definition at line 90 of file Fieldmap.hpp.
References Fieldmap::getLine(), Fieldmap::interpretLine(), Fieldmap::interpretWarning(), and Fieldmap::missingValuesWarning().
interpretLine() [5/6]
template<class S , class T , class U , class V > bool Fieldmap::interpretLine (std::ifstream & in, S & value1, T & value2, U & value3, V & value4, const bool & file_length_known = true) protected inherited
Parses four values (types S, T, U, V) from a line.
See also
interpretLine<T>
Definition at line 128 of file Fieldmap.hpp.
References Fieldmap::getLine(), Fieldmap::interpretLine(), Fieldmap::interpretWarning(), and Fieldmap::missingValuesWarning().
interpretLine() [6/6]
template<class T > bool Fieldmap::interpretLine (std::ifstream & in, T & value, const bool & file_length_known) inherited
Parses a single value of type T from a line in the stream.
Reads a line using getLine(), then attempts to extract one value. Validates that the extraction matches the type and that no unexpected data remains on the line.
Parameters
in Input file stream.
value Output variable reference.
file_length_known If false, EOF is acceptable.
Returns
true if successful, false if EOF (and permitted).
Definition at line 24 of file Fieldmap.hpp.
References Fieldmap::getLine(), Fieldmap::interpretLine(), Fieldmap::interpretWarning(), and Fieldmap::missingValuesWarning().
interpretWarning()
void Fieldmap::interpretWarning (const std::ios_base::iostate & state, const bool & read_all, const std::string & error_msg, const std::string & found) protected inherited
Definition at line 434 of file Fieldmap.cpp.
References Fieldmap::Filename_m, Fieldmap::interpretWarning(), and Fieldmap::lines_read_m.
Referenced by Fieldmap::interpretLine(), Fieldmap::interpretLine(), Fieldmap::interpretLine(), Fieldmap::interpretLine(), Fieldmap::interpretLine(), and Fieldmap::interpretWarning().
isInside()
bool Astra1DDynamic::isInside (const Vector_t< double, 3 > & r) const inline override virtual
Checks if the given coordinate is inside the volume covered by the fieldmap.
Parameters
r Coordinate
Note
This cannot be called inside a GPU kernel (implicit capture of the 'this' pointer not allowed on device)
Implements Fieldmap.
Definition at line 90 of file Astra1DDynamic.h.
References zbegin_m, and zend_m.
Referenced by getFieldstrength().
lowResolutionWarning()
void Fieldmap::lowResolutionWarning (double squareError, double maxError) protected inherited
Definition at line 485 of file Fieldmap.cpp.
References Fieldmap::Filename_m, OpalData::getAuxiliaryOutputDirectory(), OpalData::getInstance(), Fieldmap::lowResolutionWarning(), and Fieldmap::typeset_msg().
Referenced by Fieldmap::checkMap(), and Fieldmap::lowResolutionWarning().
missingValuesWarning()
void Fieldmap::missingValuesWarning () protected inherited
Definition at line 452 of file Fieldmap.cpp.
References Fieldmap::Filename_m, Fieldmap::lines_read_m, and Fieldmap::missingValuesWarning().
Referenced by Fieldmap::interpretLine(), Fieldmap::interpretLine(), Fieldmap::interpretLine(), Fieldmap::interpretLine(), Fieldmap::interpretLine(), and Fieldmap::missingValuesWarning().
noFieldmapWarning()
void Fieldmap::noFieldmapWarning () protected inherited
Definition at line 478 of file Fieldmap.cpp.
References Fieldmap::Filename_m, and Fieldmap::noFieldmapWarning().
Referenced by Astra1DDynamic(), FM2DDynamic::FM2DDynamic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), and Fieldmap::noFieldmapWarning().
readHeader()
MapType Fieldmap::readHeader (std::string Filename) static inherited
Read the header of a field map file to determine its type.
Determines the fieldmap type.
Parameters
Filename The file to check.
Returns
The MapType determined from the file header.
MapType
Definition at line 152 of file Fieldmap.cpp.
References Fieldmap::getLine(), Fieldmap::lines_read_m, Fieldmap::readHeader(), T1DDynamic, T1DElectroStatic, T1DMagnetoStatic, T1DProfile1, T2DDynamic, T2DElectroStatic, T2DMagnetoStatic, T3DDynamic, T3DDynamicH5Block, T3DElectroStatic, T3DMagnetoStatic, T3DMagnetoStatic_Extended, T3DMagnetoStaticH5Block, TAstraDynamic, TAstraElectroStatic, TAstraMagnetoStatic, and UNKNOWN.
Referenced by Fieldmap::getFieldmap(), and Fieldmap::readHeader().
readMap() [1/2]
void Astra1DDynamic::readMap () override private virtual
Pure virtual method to read the map data. Called by the public static readMap().
Implements Fieldmap.
Definition at line 109 of file Astra1DDynamic.cpp.
References accuracy_m, ezRaw_m, Fieldmap::Filename_m, FourCoefs_m, Fieldmap::getLine(), gsl_interp_accel_alloc(), gsl_interp_accel_free(), gsl_interp_cspline, gsl_spline_alloc(), gsl_spline_eval(), gsl_spline_free(), gsl_spline_init(), Fieldmap::normalize_m, num_gridpz_m, readMap(), Physics::two_pi, Units::Vpm2MVpm, zbegin_m, zend_m, and zRaw_m.
Referenced by readMap().
readMap() [2/2]
void Fieldmap::readMap (std::string Filename) static inherited
Trigger the actual reading of the field map data.
Parameters
Filename The file to read.
Definition at line 286 of file Fieldmap.cpp.
References Fieldmap::FieldmapDictionary, and Fieldmap::readMap().
Referenced by Fieldmap::readMap(), TEST_F(), TEST_F(), and TEST_F().
setEdgeConstants()
void Fieldmap::setEdgeConstants (const double & bendAngle, const double & entranceAngle, const double & exitAngle) virtual inherited
Definition at line 391 of file Fieldmap.cpp.
References Fieldmap::setEdgeConstants().
Referenced by Fieldmap::setEdgeConstants().
setFieldGap()
void Fieldmap::setFieldGap (double gap) virtual inherited
Definition at line 590 of file Fieldmap.cpp.
References Fieldmap::setFieldGap().
Referenced by Fieldmap::setFieldGap().
setFieldLength()
void Fieldmap::setFieldLength (const double &) virtual inherited
Definition at line 394 of file Fieldmap.cpp.
References Fieldmap::setFieldLength().
Referenced by Fieldmap::setFieldLength().
setFrequency()
void Astra1DDynamic::setFrequency (double freq) override virtual
Set the frequency.
Parameters
freq Frequency [MHz].
Note
Not implemented yet
Implements Fieldmap.
Definition at line 491 of file Astra1DDynamic.cpp.
References frequency_m, and setFrequency().
Referenced by setFrequency().
swap()
void Astra1DDynamic::swap () override virtual
Swap coordinates.
Implements Fieldmap.
Definition at line 475 of file Astra1DDynamic.cpp.
References swap().
Referenced by swap().
typeset_msg()
std::string Fieldmap::typeset_msg (const std::string & msg, const std::string & title) static inherited
Definition at line 509 of file Fieldmap.cpp.
References Fieldmap::typeset_msg().
Referenced by FM2DMagnetoStatic::freeMap(), Fieldmap::lowResolutionWarning(), FM2DMagnetoStatic::readMap(), and Fieldmap::typeset_msg().
write3DField()
void Fieldmap::write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > & xrange, const std::pair< double, double > & yrange, const std::pair< double, double > & zrange, const std::vector< Vector_t< double, 3 > > & ef, const std::vector< Vector_t< double, 3 > > & bf) protected inherited
Definition at line 593 of file Fieldmap.cpp.
References Util::combineFilePath(), Fieldmap::Filename_m, OpalData::getAuxiliaryOutputDirectory(), OpalData::getInstance(), and Fieldmap::write3DField().
Referenced by Fieldmap::write3DField().
Friends And Related Symbol Documentation
Fieldmap
friend class Fieldmap friend
Allow Fieldmap factory access.
Definition at line 331 of file Astra1DDynamic.h.
Member Data Documentation
accuracy_m
int Astra1DDynamic::accuracy_m private
Number of Fourier modes used.
Definition at line 325 of file Astra1DDynamic.h.
Referenced by applyField(), applyTravelingWave(), Astra1DDynamic(), getFieldDerivative(), getFieldstrength(), and readMap().
alpha_numeric
std::string Fieldmap::alpha_numeric static private inherited
Definition at line 355 of file Fieldmap.h.
Referenced by Fieldmap::getLine(), and Fieldmap::interpreteEOF().
buffer_m
char Fieldmap::buffer_m static private inherited
Definition at line 354 of file Fieldmap.h.
Referenced by Fieldmap::getLine(), and Fieldmap::interpreteEOF().
ezRaw_m
std::vector<double> Astra1DDynamic::ezRaw_m private
Definition at line 310 of file Astra1DDynamic.h.
Referenced by readMap().
FieldmapDictionary
std::map< std::string, Fieldmap::FieldmapDescription > Fieldmap::FieldmapDictionary static private inherited
Initial value:
=
    std::map<std::string, Fieldmap::FieldmapDescription>()
Definition at line 367 of file Fieldmap.h.
Referenced by Fieldmap::clearDictionary(), Fieldmap::freeMap(), Fieldmap::getFieldmap(), Fieldmap::getListFieldmapNames(), and Fieldmap::readMap().
Filename_m
std::string Fieldmap::Filename_m protected inherited
Definition at line 252 of file Fieldmap.h.
Referenced by Astra1DDynamic(), Fieldmap::checkMap(), Fieldmap::disableFieldmapWarning(), Fieldmap::exceedingValuesWarning(), FM2DDynamic::FM2DDynamic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), freeMap(), FM2DDynamic::freeMap(), FM2DMagnetoStatic::freeMap(), getInfo(), FM2DDynamic::getInfo(), FM2DMagnetoStatic::getInfo(), getOnaxisEz(), Fieldmap::interpretWarning(), Fieldmap::lowResolutionWarning(), Fieldmap::missingValuesWarning(), Fieldmap::noFieldmapWarning(), readMap(), FM2DDynamic::readMap(), FM2DMagnetoStatic::readMap(), and Fieldmap::write3DField().
FourCoefs_m
Kokkos::DualView<double*> Astra1DDynamic::FourCoefs_m private
Fourier coefficients of Ez(z) (device-accessible) Stored as: [a0, a1, b1, a2, b2, ..., aN, bN] and used in the reconstruction Ez(z) = a0 + sum_l [ a_l cos(l*kz) - b_l sin(l*kz) ].
Definition at line 307 of file Astra1DDynamic.h.
Referenced by applyField(), applyTravelingWave(), freeMap(), getFieldDerivative(), getFieldstrength(), and readMap().
frequency_m
double Astra1DDynamic::frequency_m private
Definition at line 312 of file Astra1DDynamic.h.
Referenced by Astra1DDynamic(), getFrequency(), and setFrequency().
length_m
double Astra1DDynamic::length_m private
Effective periodic length of the field map [m].
Definition at line 322 of file Astra1DDynamic.h.
Referenced by applyField(), applyTravelingWave(), Astra1DDynamic(), getFieldDerivative(), and getFieldstrength().
lines_read_m
int Fieldmap::lines_read_m protected inherited
Definition at line 253 of file Fieldmap.h.
Referenced by Astra1DDynamic(), Fieldmap::exceedingValuesWarning(), FM2DDynamic::FM2DDynamic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), Fieldmap::getLine(), Fieldmap::interpreteEOF(), Fieldmap::interpretWarning(), Fieldmap::missingValuesWarning(), and Fieldmap::readHeader().
normalize_m
bool Fieldmap::normalize_m protected inherited
Definition at line 255 of file Fieldmap.h.
Referenced by Astra1DDynamic(), FM2DDynamic::FM2DDynamic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), readMap(), FM2DDynamic::readMap(), and FM2DMagnetoStatic::readMap().
num_gridpz_m
int Astra1DDynamic::num_gridpz_m private
Number of grid points in z-direction (input sampling)
Definition at line 328 of file Astra1DDynamic.h.
Referenced by Astra1DDynamic(), getOnaxisEz(), and readMap().
Type
MapType Fieldmap::Type protected inherited
Definition at line 250 of file Fieldmap.h.
Referenced by Astra1DDynamic(), FM2DDynamic::FM2DDynamic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), and Fieldmap::getType().
xlrep_m
double Astra1DDynamic::xlrep_m private
Wave number (omega / c)
Definition at line 319 of file Astra1DDynamic.h.
Referenced by applyField(), applyTravelingWave(), Astra1DDynamic(), and getFieldstrength().
zbegin_m
double Astra1DDynamic::zbegin_m private
Z Bounds relative to element edge.
Start position of field map [m]
Definition at line 315 of file Astra1DDynamic.h.
Referenced by applyField(), applyTravelingWave(), Astra1DDynamic(), getFieldDerivative(), getFieldDimensions(), getFieldstrength(), getInfo(), isInside(), and readMap().
zend_m
double Astra1DDynamic::zend_m private
End position of field map [m]
Definition at line 316 of file Astra1DDynamic.h.
Referenced by applyField(), applyTravelingWave(), Astra1DDynamic(), getFieldDimensions(), getInfo(), isInside(), and readMap().
zRaw_m
std::vector<double> Astra1DDynamic::zRaw_m private
Definition at line 309 of file Astra1DDynamic.h.
Referenced by readMap().
The documentation for this class was generated from the following files:
Astra1DDynamic.h
Astra1DDynamic.cpp