OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions::Scalar< T > Class Template Reference
Expressions::Scalar< T > Class Template Reference abstract
A scalar expression.
#include <Expressions.h>
Public Member Functions
Scalar ()
Scalar (const Scalar &)
virtual ~Scalar ()
virtual Scalar< T > * clone () const =0
Copy scalar expression.
virtual T evaluate () const =0
Evaluate.
virtual bool isConstant () const
Test for constant.
virtual void print (std::ostream &, int precedence=99) const =0
Print expression.
Private Member Functions
void operator= (const Scalar &)
Detailed Description
template<class T>
class Expressions::Scalar< T >
A scalar expression.
Definition at line 71 of file AbstractObjects/Expressions.h.
Constructor & Destructor Documentation
Scalar() [1/2]
template<class T> Expressions::Scalar< T >::Scalar () inline
Definition at line 278 of file AbstractObjects/Expressions.h.
Referenced by Expressions::ASUnary< T >::ASUnary(), Expressions::ASUnary< T >::clone(), Expressions::Indexer< T >::clone(), Expressions::SBinary< T, U >::clone(), clone(), Expressions::SConstant< T >::clone(), Expressions::SNull< T >::clone(), Expressions::SRefExpr< T >::clone(), Expressions::SUnary< T, U >::clone(), Expressions::Indexer< T >::Indexer(), Expressions::SBinary< T, U >::make(), Expressions::SNull< T >::make(), Expressions::SUnary< T, U >::make(), operator=(), Expressions::SBinary< T, U >::SBinary(), Scalar(), Expressions::SNull< T >::SNull(), Expressions::SRefExpr< T >::SRefExpr(), and Expressions::SUnary< T, U >::SUnary().
Scalar() [2/2]
template<class T> Expressions::Scalar< T >::Scalar (const Scalar< T > &)
References Scalar().
~Scalar()
template<class T> Expressions::Scalar< T >::~Scalar () inline virtual
Definition at line 284 of file AbstractObjects/Expressions.h.
Member Function Documentation
clone()
template<class T> virtual Scalar< T > * Expressions::Scalar< T >::clone () const pure virtual
Copy scalar expression.
Implemented in Expressions::ASUnary< T >, Expressions::Indexer< T >, Expressions::SBinary< T, U >, Expressions::SCell, Expressions::SConstant< T >, Expressions::SHash, Expressions::SNull< T >, Expressions::SRefExpr< T >, and Expressions::SUnary< T, U >.
References Scalar().
evaluate()
template<class T> virtual T Expressions::Scalar< T >::evaluate () const pure virtual
Evaluate.
Implemented in Expressions::ASUnary< T >, Expressions::Indexer< T >, Expressions::SBinary< T, U >, Expressions::SCell, Expressions::SConstant< T >, Expressions::SHash, Expressions::SNull< T >, Expressions::SRefExpr< T >, and Expressions::SUnary< T, U >.
isConstant()
template<class T> bool Expressions::Scalar< T >::isConstant () const inline virtual
Test for constant.
Reimplemented in Expressions::SConstant< T >.
Definition at line 287 of file AbstractObjects/Expressions.h.
operator=()
template<class T> void Expressions::Scalar< T >::operator= (const Scalar< T > &) private
References Scalar().
print()
template<class T> virtual void Expressions::Scalar< T >::print (std::ostream & , int precedence = 99) const pure virtual
Print expression.
Implemented in Expressions::ASUnary< T >, Expressions::Indexer< T >, Expressions::SBinary< T, U >, Expressions::SCell, Expressions::SConstant< T >, Expressions::SConstant< T >, Expressions::SConstant< T >, Expressions::SConstant< T >, Expressions::SConstant< T >, Expressions::SHash, Expressions::SNull< T >, Expressions::SRefExpr< T >, and Expressions::SUnary< T, U >.
The documentation for this class was generated from the following file:
AbstractObjects/Expressions.h