OPALX (Object Oriented Parallel Accelerator Library for Exascal): BDipoleField Class Reference
BDipoleField Class Reference
The field of a magnetic dipole.
#include <BDipoleField.h>
Public Member Functions
BDipoleField ()
Default constructor.
virtual ~BDipoleField ()
virtual BVector Bfield (const Point3D &P) const
Get field.
virtual BVector Bfield (const Point3D &P, double t) const
Get field.
virtual double getBx () const
Get horizontal component.
virtual double getBy () const
Get vertical component.
virtual void setBx (double Bx)
Set horizontal component.
virtual void setBy (double By)
Set vertical component.
BDipoleField & addField (const BDipoleField &field)
Add to field.
BDipoleField & subtractField (const BDipoleField &field)
Subtract from field.
virtual void scale (double scalar)
Scale the field.
virtual double getBz () const
Get component.
virtual void setBz (double)
Set component.
virtual EVector Efield (const Point3D &P) const
Get field.
virtual EVector Efield (const Point3D &P, double t) const
Get field.
virtual EBVectors EBfield (const Point3D &P) const
Get field.
virtual EBVectors EBfield (const Point3D &P, double t) const
Get field.
Static Public Attributes
static const EVector ZeroEfield
The constant representing a zero electric field.
static const BVector ZeroBfield
The constant representing a zero magnetic field.
static const EBVectors ZeroEBfield
The constant representing a zero electromagnetic field.
Private Attributes
double Bx
double By
Detailed Description
The field of a magnetic dipole.
Definition at line 30 of file BDipoleField.h.
Constructor & Destructor Documentation
BDipoleField()
BDipoleField::BDipoleField ()
Default constructor.
Definition at line 26 of file BDipoleField.cpp.
References Bx, and By.
Referenced by addField(), and subtractField().
~BDipoleField()
BDipoleField::~BDipoleField () virtual
Definition at line 28 of file BDipoleField.cpp.
Member Function Documentation
addField()
BDipoleField & BDipoleField::addField (const BDipoleField & field)
Add to field.
Definition at line 42 of file BDipoleField.cpp.
References BDipoleField(), Bx, and By.
Bfield() [1/2]
BVector BDipoleField::Bfield (const Point3D & P) const virtual
Get field.
Reimplemented from EMField.
Definition at line 30 of file BDipoleField.cpp.
References Bx, and By.
Bfield() [2/2]
BVector BDipoleField::Bfield (const Point3D & P, double t) const virtual
Get field.
Reimplemented from EMField.
Definition at line 32 of file BDipoleField.cpp.
References Bx, and By.
EBfield() [1/2]
EBVectors EMField::EBfield (const Point3D & P) const virtual inherited
Get field.
Definition at line 127 of file EMField.cpp.
References Bfield(), and Efield().
Referenced by Component::EBfield(), Component::EBfield(), and EBfield().
EBfield() [2/2]
EBVectors EMField::EBfield (const Point3D & P, double t) const virtual inherited
Get field.
Definition at line 129 of file EMField.cpp.
References EBfield().
Efield() [1/2]
EVector EMField::Efield (const Point3D & P) const virtual inherited
Get field.
Reimplemented in ConstEzField, and OscillatingField< ConstEzField >.
Definition at line 119 of file EMField.cpp.
References ZeroEfield.
Referenced by EBfield(), Component::Efield(), Component::Efield(), and Efield().
Efield() [2/2]
EVector EMField::Efield (const Point3D & P, double t) const virtual inherited
Get field.
Reimplemented in ConstEzField, and OscillatingField< ConstEzField >.
Definition at line 123 of file EMField.cpp.
References Efield().
getBx()
double BDipoleField::getBx () const virtual
Get horizontal component.
Reimplemented from ConstBField.
Definition at line 34 of file BDipoleField.cpp.
References Bx.
getBy()
double BDipoleField::getBy () const virtual
Get vertical component.
Reimplemented from ConstBField.
Definition at line 36 of file BDipoleField.cpp.
References By.
getBz()
double ConstBField::getBz () const virtual inherited
Get component.
Reimplemented in ConstBzField.
Definition at line 34 of file ConstBField.cpp.
scale()
void BDipoleField::scale (double scalar) virtual
Scale the field.
Implements EMField.
Definition at line 54 of file BDipoleField.cpp.
References Bx, and By.
setBx()
void BDipoleField::setBx (double Bx) virtual
Set horizontal component.
Reimplemented from ConstBField.
Definition at line 38 of file BDipoleField.cpp.
References Bx.
setBy()
void BDipoleField::setBy (double By) virtual
Set vertical component.
Reimplemented from ConstBField.
Definition at line 40 of file BDipoleField.cpp.
References By.
setBz()
void ConstBField::setBz (double) virtual inherited
Set component.
Reimplemented in ConstBzField.
Definition at line 40 of file ConstBField.cpp.
subtractField()
BDipoleField & BDipoleField::subtractField (const BDipoleField & field)
Subtract from field.
Definition at line 48 of file BDipoleField.cpp.
References BDipoleField(), Bx, and By.
Member Data Documentation
Bx
double BDipoleField::Bx private
Definition at line 78 of file BDipoleField.h.
Referenced by addField(), BDipoleField(), Bfield(), Bfield(), getBx(), scale(), setBx(), and subtractField().
By
double BDipoleField::By private
Definition at line 78 of file BDipoleField.h.
Referenced by addField(), BDipoleField(), Bfield(), Bfield(), getBy(), scale(), setBy(), and subtractField().
ZeroBfield
const BVector EMField::ZeroBfield static inherited
The constant representing a zero magnetic field.
Definition at line 220 of file EMField.h.
Referenced by Bfield().
ZeroEBfield
const EBVectors EMField::ZeroEBfield static inherited
The constant representing a zero electromagnetic field.
Definition at line 223 of file EMField.h.
ZeroEfield
const EVector EMField::ZeroEfield static inherited
The constant representing a zero electric field.
Definition at line 217 of file EMField.h.
Referenced by Efield().
The documentation for this class was generated from the following files:
BDipoleField.h
BDipoleField.cpp