OPALX (Object Oriented Parallel Accelerator Library for Exascal): OpalException Class Reference
OpalException Class Reference
#include <OpalException.h>
Public Member Functions
OpalException (const std::string &meth, const std::string &msg)
The usual constructor.
OpalException (const OpalException &)
virtual ~OpalException ()
virtual const std::string & what () const
Return the message string for the exception.
virtual const std::string & where () const
Return the name of the method or function which detected the exception.
Private Member Functions
OpalException ()
Private Attributes
const std::string message
const std::string method
Detailed Description
The base class for all OPAL exceptions.
Stores the detecting method and diagnostic message used by the top-level OPAL error handler. Concrete subclasses should keep domain-specific type information and derive from this class directly or indirectly.
Examples
/Users/adelmann/git/physics-manual-opalx/.external/OPALX/src/PartBunch/BCHandler.hpp.
Definition at line 30 of file OpalException.h.
Constructor & Destructor Documentation
OpalException() [1/3]
OpalException::OpalException (const std::string & meth, const std::string & msg) explicit
The usual constructor.
Definition at line 24 of file OpalException.cpp.
References message, and method.
Referenced by ArithmeticError::ArithmeticError(), ArithmeticError::ArithmeticError(), FormatError::FormatError(), FormatError::FormatError(), GeneralOpalException::GeneralOpalException(), GeneralOpalException::GeneralOpalException(), LogicalError::LogicalError(), LogicalError::LogicalError(), OpalException(), IndexMap::OutOfBounds::OutOfBounds(), IndexMap::OutOfBounds::OutOfBounds(), ParseError::ParseError(), ParseError::ParseError(), and SDDSParserException::SDDSParserException().
OpalException() [2/3]
OpalException::OpalException (const OpalException & rhs)
Definition at line 27 of file OpalException.cpp.
References message, method, and OpalException().
~OpalException()
OpalException::~OpalException () virtual
Definition at line 29 of file OpalException.cpp.
OpalException() [3/3]
OpalException::OpalException () private
Member Function Documentation
what()
const std::string & OpalException::what () const virtual
Return the message string for the exception.
Definition at line 31 of file OpalException.cpp.
References message.
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), main(), OpalParser::readStatement(), OpalParser::run(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and TEST_F().
where()
const std::string & OpalException::where () const virtual
Return the name of the method or function which detected the exception.
Definition at line 33 of file OpalException.cpp.
References method.
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), main(), OpalParser::run(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and TEST_F().
Member Data Documentation
message
const std::string OpalException::message private
Definition at line 56 of file OpalException.h.
Referenced by OpalException(), OpalException(), and what().
method
const std::string OpalException::method private
Definition at line 57 of file OpalException.h.
Referenced by DivideError::DivideError(), OpalException(), OpalException(), and where().
The documentation for this class was generated from the following files:
OpalException.h
OpalException.cpp