OPALX (Object Oriented Parallel Accelerator Library for Exascal): RelativeFFTLowPassFilter Class Reference
RelativeFFTLowPassFilter Class Reference
#include <RelativeFFTLowPass.h>
Public Member Functions
RelativeFFTLowPassFilter (const double &threshold)
void apply (std::vector< double > &LineDensity)
void calc_derivative (std::vector< double > &histogram, const double &h)
Private Attributes
double threshold_m
Detailed Description
Definition at line 6 of file RelativeFFTLowPass.h.
Constructor & Destructor Documentation
RelativeFFTLowPassFilter()
RelativeFFTLowPassFilter::RelativeFFTLowPassFilter (const double & threshold)
Definition at line 7 of file RelativeFFTLowPass.cpp.
References threshold_m.
Member Function Documentation
apply()
void RelativeFFTLowPassFilter::apply (std::vector< double > & LineDensity) virtual
Implements Filter.
Definition at line 10 of file RelativeFFTLowPass.cpp.
References gsl_fft_halfcomplex_inverse(), gsl_fft_halfcomplex_wavetable_alloc(), gsl_fft_halfcomplex_wavetable_free(), gsl_fft_real_transform(), gsl_fft_real_wavetable_alloc(), gsl_fft_real_wavetable_free(), gsl_fft_real_workspace_alloc(), gsl_fft_real_workspace_free(), and threshold_m.
calc_derivative()
void RelativeFFTLowPassFilter::calc_derivative (std::vector< double > & histogram, const double & h) virtual
Implements Filter.
Definition at line 52 of file RelativeFFTLowPass.cpp.
References gsl_fft_halfcomplex_inverse(), gsl_fft_halfcomplex_wavetable_alloc(), gsl_fft_halfcomplex_wavetable_free(), gsl_fft_real_transform(), gsl_fft_real_wavetable_alloc(), gsl_fft_real_wavetable_free(), gsl_fft_real_workspace_alloc(), gsl_fft_real_workspace_free(), Physics::pi, and threshold_m.
Member Data Documentation
threshold_m
double RelativeFFTLowPassFilter::threshold_m private
Definition at line 13 of file RelativeFFTLowPass.h.
Referenced by apply(), calc_derivative(), and RelativeFFTLowPassFilter().
The documentation for this class was generated from the following files:
RelativeFFTLowPass.h
RelativeFFTLowPass.cpp