OPALX (Object Oriented Parallel Accelerator Library for Exascal): PartBunch< T, Dim > Class Template Reference
PartBunch< T, Dim > Class Template Reference
#include <PartBunch.h>
Inherits ippl::PicManager< T, Dim, ParticleContainer< T, Dim >, FieldContainer< T, Dim >, LoadBalancer< T, Dim > >.
Public Types
using ParticleContainer_t = ParticleContainer< T, Dim >
using FieldContainer_t = FieldContainer< T, Dim >
using BinnedFieldSolver_t = BinnedFieldSolver< T, Dim >
using LoadBalancer_t = LoadBalancer< T, Dim >
using Base = ippl::ParticleBase< ippl::ParticleSpatialLayout< T, Dim > >
using CoordinateSelector_t = typename ParticleBinning::CoordinateSelector< ParticleContainer_t >
using GammaSelector_t = typename ParticleBinning::GammaSelector< ParticleContainer_t >
using AdaptBins_t = typename ParticleBinning::AdaptBinsBase< ParticleContainer_t >
using binIndex_t = typename ParticleContainer_t::bin_index_type
using BCHandler_t = BCHandler< Dim >
Public Member Functions
PartBunch (std::vector< double > qi, std::vector< double > mi, const std::vector< Beam * > &beams, std::vector< size_t > totalParticlesPerBeam, double lbt, std::string integration_method, FieldSolverCmd *OPALFieldSolver, DataSink *dataSink)
Construct a multi-beam bunch: mesh, solver, containers, and capacity.
void bunchUpdate ()
Refresh mesh from particle extents, update layouts, and recompute moments.
void computeBoundsForFieldSolve (Vector_t< double, Dim > &lower, Vector_t< double, Dim > &upper)
Computes the spatial bounds for the field solver based on the current particle distribution.
void applyGridUpdate (const Vector_t< double, Dim > &lower, const Vector_t< double, Dim > &upper)
Updates the mesh/grid and internal data structures to match the given spatial bounds.
void reinitializeGridZ (int nrZ)
Reinitialize the z dimension of the field grid to nrZ cells.
void setImageChargeConfiguration (bool enabled, double zPlane)
Set the image-charge configuration for the field solver.
void setShiftedGreensConfiguration (bool enabled, double zPlane)
Set the shifted Green's function Dirichlet-correction configuration.
void setZeroFacePlaneDumpFrequency (int frequency)
Configure diagnostic dump frequency for the ZEROFACE plane potential.
void setZerofaceMaxSteps (int maxSteps)
Set the maximum number of timesteps for which image charges are active (0 = unlimited).
size_t getTotalNumAllContainers () const
Sum of getTotalNum() over all particle containers.
void setSolver ()
Build field solver and load balancer from OPALFieldSolver_m.
void setBins ()
Create adaptive bins from the binning command (VELOCITYZ / GAMMAZ).
void pre_run () override
Warm-up: zero rho and run the field solver once (skip full dumps).
void performBunchSanityChecks () const
Validate BC handler, solver wiring, field pointers, and layout extents.
void resetPcActive ()
At segment start: active if container is non-empty; inactive if empty.
bool isPcActive (size_t i) const
void setPcActive (size_t i)
Force container i active (e.g. for containers with pending emission).
bool pcAtZStop (size_t i) const
void setPcAtZStop (size_t i)
Deactivate container i until the next step-size segment (z-stop reached).
void refreshPcActiveAfterEmit ()
After emission: reactivate non-empty containers not marked at z-stop.
bool anyPcActive () const
void advance () override
PicManager hook; throws (tracking does not use this path).
void par2grid () override
PicManager hook; throws (scatter handled elsewhere).
void grid2par () override
PicManager hook; throws (gather handled elsewhere).
std::shared_ptr< VField_t< T, Dim > > getTempEField ()
Scratch E field used by the binned solver path.
void setTempEField (std::shared_ptr< VField_t< T, Dim > > Etmp)
std::shared_ptr< VField_t< T, Dim > > getTempBField ()
Scratch B field used by the binned solver path.
void setTempBField (std::shared_ptr< VField_t< T, Dim > > Btmp)
std::shared_ptr< AdaptBins_t > getBins ()
Non-const access to adaptive binning state.
std::shared_ptr< AdaptBins_t > getBins () const
Const access to adaptive binning state.
void setBins (std::shared_ptr< AdaptBins_t > bins)
void setBCHandler (std::shared_ptr< BCHandler_t > bcHandler)
std::shared_ptr< BCHandler_t > getBCHandler () const
Current boundary-condition handler.
DataSink * getDataSink () const
std::shared_ptr< BunchStateHandler > getBunchStateHandler ()
std::shared_ptr< const BunchStateHandler > getBunchStateHandler () const
void updateMoments ()
void calcBeamParameters ()
Update moments and set rmin_m / rmax_m from the primary (first) container.
void setCharge ()
Set the per-particle charge for each particle container.
void setMass ()
Set the per-particle mass for each particle container.
double getCharge (size_t containerIndex=0) const
Get the total charge for a given particle container.
double getChargePerParticle (size_t containerIndex=0) const
Get the charge per particle for a given particle container.
double getMassPerParticle (size_t containerIndex=0) const
Get the mass per particle for a given particle container.
double getQ (size_t containerIndex=0) const
Alias for getCharge(containerIndex).
double getM (size_t containerIndex=0) const
Get the total mass for a given particle container.
double getTotalCharge () const
Get the total charge across all particle containers.
double getTotalMass () const
Get the total mass across all particle containers.
double getdE ()
const PartData * getReference () const
void setReference (const PartData *ref)
Set inside TrackRun::execute.
void gatherLoadBalanceStatistics ()
size_t getLoadBalance (int p)
size_t calcNumPartsOutside (Vector_t< double, Dim >)
Stub; logs and returns 0.
void calcLineDensity (unsigned int, std::vector< double > &, std::pair< double, double > &)
Stub; logs only.
Vector_t< double, Dim > getEExtrema ()
Stub; logs and returns zero vector.
void computeSelfFields ()
Compute the bunch self-fields (binned when available).
void dumpBinConfig (bool preMerge)
Write bin edges/counts to the data sink when configured.
Inform & print (Inform &os)
Human-readable dump of each container to os.
bool hasFieldSolver () const
BinnedFieldSolver_t * getFieldSolver ()
Non-const pointer to the concrete BinnedFieldSolver.
const BinnedFieldSolver_t * getFieldSolver () const
Const overload of getFieldSolver().
std::string getFieldSolverType ()
Backend type string (e.g. FFT, OPEN, CG, NONE).
bool hasBinning () const
int getCurrentNBins () const
Effective bin count for diagnostics (1 if binning inactive or still at max bins).
double calcMeanPhi ()
Compatibility stub; logs and returns 0.
std::string getParticleName (size_t i) const
Particle species name for container i (from BEAM PARTICLE input).
Vector_t< double, Dim > R (size_t)
Do not use; throws (access positions via ParticleContainer::R).
Vector_t< double, Dim > P (size_t)
Do not use; throws (access momenta via ParticleContainer::P).
void get_bounds (Vector_t< double, Dim > &rmin, Vector_t< double, Dim > &rmax)
Copy cached bunch extent (rmin_m, rmax_m) from calcBeamParameters.
void setdT (double dt)
Set the global time step.
double getdT () const
Get the global time step.
void setT (double t)
Set the current simulation time.
void incrementT ()
Advance time by one global time step.
double getT () const
Get the current simulation time.
Vector_t< double, Dim > get_origin () const
Cached minimum extent (rmin_m); prefer per-container min/max for multi-beam detail.
Vector_t< double, Dim > get_maxExtent () const
Cached maximum extent (rmax_m).
Vector_t< double, Dim > get_halo () const
Stub; logs and returns zero vector.
Vector_t< double, Dim > get_hr () const
Get mesh spacing.
void setGlobalTrackStep (long long n)
long long getGlobalTrackStep () const
Current global tracking step.
void incTrackSteps ()
Increment globalTrackStep_m by one.
void do_binaryRepart ()
ORB/binary repartition when the load balancer requests it (primary container).
double get_rmsDensity () const
Legacy RMS density field (may be unused).
Public Attributes
double dt_m
Global time step \(\Delta t\) (s).
int it_m
Iteration counter (legacy / diagnostics).
std::string integration_method_m
Integrator name (e.g. leapfrog).
std::string solver_m
Field solver type string from input.
Vector_t< int, Dim > nr_m
Mesh cell count per dimension.
int nrZBase_m = 0
Base z grid count before any image-charge doubling; used to reset nr_m.
Vector_t< double, Dim > origin_m
Mesh origin (lab coordinates).
Vector_t< double, Dim > rmin_m
Vector_t< double, Dim > rmax_m
Current bunch spatial maximum (from primary container stats).
Vector_t< double, Dim > hr_m
Mesh spacing (m).
double lbt_m
Load-balancer timescale parameter.
bool isFirstRepartition_m
True until the first ORB-style repartition completes.
ippl::NDIndex< Dim > domain_m
Global mesh index extent per dimension.
std::array< bool, Dim > decomp_m
Domain decomposition flags (per axis).
Private Attributes
std::vector< bool > pcActive_m
Per-container: participate in this track segment.
std::vector< bool > pcAtZStop_m
Per-container: frozen at current z-stop until next segment.
std::vector< std::string > particleNames_m
Per-container beam particle names.
std::vector< double > qi_m
Charge per macroparticle [C], one entry per container.
std::vector< double > mi_m
Mass per macroparticle [GeV], one entry per container.
const PartData * reference_m = nullptr
Reference particle data (set by TrackRun::execute).
std::shared_ptr< BunchStateHandler > bunchState_m
Bunch state: unitless flag, repartition flag, etc.
std::shared_ptr< BCHandler_t > bcHandler_m
Field boundary conditions.
std::shared_ptr< AdaptBins_t > bins_m
Adaptive velocity/gamma binning (optional).
FieldSolverCmd * OPALFieldSolver_m
Borrowed parsed FIELD_SOLVER command.
DataSink * dataSink_m
Borrowed diagnostics and dump output sink.
double t_m
Current simulation time (s).
std::shared_ptr< VField_t< T, Dim > > Etmp_m
std::shared_ptr< VField_t< T, Dim > > Btmp_m
long long globalTrackStep_m
Global integration step counter.
std::unique_ptr< size_t[]> globalPartPerNode_m
Per-rank particle counts for load-balance stats.
double rmsDensity_m
Legacy RMS density placeholder (may still appear in stats).
Detailed Description
template<typename T, unsigned Dim>
class PartBunch< T, Dim >
Definition at line 52 of file PartBunch.h.
Member Typedef Documentation
AdaptBins_t
template<typename T , unsigned Dim> using PartBunch< T, Dim >::AdaptBins_t = typename ParticleBinning::AdaptBinsBase<ParticleContainer_t>
Definition at line 64 of file PartBunch.h.
Base
template<typename T , unsigned Dim> using PartBunch< T, Dim >::Base = ippl::ParticleBase<ippl::ParticleSpatialLayout<T, Dim> >
Definition at line 60 of file PartBunch.h.
BCHandler_t
template<typename T , unsigned Dim> using PartBunch< T, Dim >::BCHandler_t = BCHandler<Dim>
Definition at line 67 of file PartBunch.h.
binIndex_t
template<typename T , unsigned Dim> using PartBunch< T, Dim >::binIndex_t = typename ParticleContainer_t::bin_index_type
Definition at line 65 of file PartBunch.h.
BinnedFieldSolver_t
template<typename T , unsigned Dim> using PartBunch< T, Dim >::BinnedFieldSolver_t = BinnedFieldSolver<T, Dim>
Definition at line 58 of file PartBunch.h.
CoordinateSelector_t
template<typename T , unsigned Dim> using PartBunch< T, Dim >::CoordinateSelector_t = typename ParticleBinning::CoordinateSelector<ParticleContainer_t>
Definition at line 62 of file PartBunch.h.
FieldContainer_t
template<typename T , unsigned Dim> using PartBunch< T, Dim >::FieldContainer_t = FieldContainer<T, Dim>
Definition at line 57 of file PartBunch.h.
GammaSelector_t
template<typename T , unsigned Dim> using PartBunch< T, Dim >::GammaSelector_t = typename ParticleBinning::GammaSelector<ParticleContainer_t>
Definition at line 63 of file PartBunch.h.
LoadBalancer_t
template<typename T , unsigned Dim> using PartBunch< T, Dim >::LoadBalancer_t = LoadBalancer<T, Dim>
Definition at line 59 of file PartBunch.h.
ParticleContainer_t
template<typename T , unsigned Dim> using PartBunch< T, Dim >::ParticleContainer_t = ParticleContainer<T, Dim>
Definition at line 56 of file PartBunch.h.
Constructor & Destructor Documentation
PartBunch()
template<typename T , unsigned Dim> PartBunch< T, Dim >::PartBunch (std::vector< double > qi, std::vector< double > mi, const std::vector< Beam * > & beams, std::vector< size_t > totalParticlesPerBeam, double lbt, std::string integration_method, FieldSolverCmd * OPALFieldSolver, DataSink * dataSink)
Construct a multi-beam bunch: mesh, solver, containers, and capacity.
Construct a multi-beam bunch: mesh, solver, containers, and capacity.
Parameters
qi Macrocharge per container (C).
mi Macromass per container (GeV/c²).
beams One Beam per container (reference particle, species).
totalParticlesPerBeam Target macroparticle count per beam (for local allocation).
lbt Load-balancer timescale.
integration_method Integrator label (e.g. leapfrog).
OPALFieldSolver Borrowed field solver command (mesh, BCs, optional binning).
dataSink Borrowed non-null diagnostics output sink.
Todo:
if we want, we could also have a separate BunchStateHandler for each container later? But I think it could also make sense to only have one global handler.
Definition at line 22 of file PartBunch.cpp.
References PartBunch< T, Dim >::bunchState_m, FieldSolverCmd::constructBCHandler(), PartBunch< T, Dim >::dataSink_m, PartBunch< T, Dim >::decomp_m, Dim, PartBunch< T, Dim >::domain_m, PartBunch< T, Dim >::dt_m, PartBunch< T, Dim >::getBCHandler(), FieldSolverCmd::getDomDec(), FieldSolverCmd::getNX(), FieldSolverCmd::getNY(), FieldSolverCmd::getNZ(), PartBunch< T, Dim >::getParticleName(), ParticleProperties::getParticleType(), PartBunch< T, Dim >::getReference(), PartBunch< T, Dim >::getTempBField(), PartBunch< T, Dim >::getTempEField(), PartBunch< T, Dim >::globalPartPerNode_m, gmsg, PartBunch< T, Dim >::hr_m, PartBunch< T, Dim >::mi_m, PartBunch< T, Dim >::nr_m, PartBunch< T, Dim >::nrZBase_m, PartBunch< T, Dim >::OPALFieldSolver_m, PartBunch< T, Dim >::origin_m, PartBunch< T, Dim >::particleNames_m, BCHandler< Dim >::PERIODIC, PartBunch< T, Dim >::pre_run(), PartBunch< T, Dim >::qi_m, PartBunch< T, Dim >::resetPcActive(), PartBunch< T, Dim >::rmax_m, PartBunch< T, Dim >::rmin_m, PartBunch< T, Dim >::setBCHandler(), PartBunch< T, Dim >::setSolver(), PartBunch< T, Dim >::setT(), PartBunch< T, Dim >::setTempBField(), and PartBunch< T, Dim >::setTempEField().
Member Function Documentation
advance()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::advance () inline override
PicManager hook; throws (tracking does not use this path).
Definition at line 285 of file PartBunch.h.
anyPcActive()
template<typename T , unsigned Dim> bool PartBunch< T, Dim >::anyPcActive () const inline
Returns
True if any container is active.
Definition at line 275 of file PartBunch.h.
References PartBunch< T, Dim >::pcActive_m.
Referenced by ParallelTracker::execute().
applyGridUpdate()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::applyGridUpdate (const Vector_t< double, Dim > & lower, const Vector_t< double, Dim > & upper)
Updates the mesh/grid and internal data structures to match the given spatial bounds.
Sets the mesh spacing and origin for the field container based on the difference between lower and upper, updates references to domain boundaries, and applies these updates to the underlying mesh and field layout. Triggers a reevaluation of particle container layouts to ensure the grid matches the computed domain.
Parameters
[in] lower The minimum coordinates (origin) for the domain in all dimensions.
[in] upper The maximum coordinates for the domain in all dimensions.
Todo:
there might be a case where we can keep the moments clean if we know more about what exactly was changed due to update().
Definition at line 670 of file PartBunch.cpp.
bunchUpdate()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::bunchUpdate ()
Refresh mesh from particle extents, update layouts, and recompute moments.
Typical call sites
Track/TrackRun.cpp (initial layout)
PartBunch.cpp (space-charge path; review if still appropriate)
ParallelTracker.cpp (after position push / frame changes)
Definition at line 570 of file PartBunch.cpp.
References BinnedFieldSolver< T, Dim >::isImageChargeActiveForStep().
Referenced by ParallelTracker::computeSpaceChargeFields(), and ParallelTracker::execute().
calcBeamParameters()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::calcBeamParameters ()
Update moments and set rmin_m / rmax_m from the primary (first) container.
Update moments and set rmin_m / rmax_m from the primary (first) container.
Note
Space-charge and mesh updates currently use container 0 only.
Definition at line 349 of file PartBunch.cpp.
References Dim.
Referenced by ParallelTracker::computeSpaceChargeFields(), and DataSink::dumpSDDS().
calcLineDensity()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::calcLineDensity (unsigned int , std::vector< double > & , std::pair< double, double > &) inline
Stub; logs only.
Definition at line 518 of file PartBunch.h.
References gmsg.
calcMeanPhi()
template<typename T , unsigned Dim> double PartBunch< T, Dim >::calcMeanPhi () inline
Compatibility stub; logs and returns 0.
Definition at line 595 of file PartBunch.h.
References gmsg.
calcNumPartsOutside()
template<typename T , unsigned Dim> size_t PartBunch< T, Dim >::calcNumPartsOutside (Vector_t< double, Dim >) inline
Stub; logs and returns 0.
Definition at line 511 of file PartBunch.h.
References gmsg.
Referenced by DataSink::dumpSDDS().
computeBoundsForFieldSolve()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::computeBoundsForFieldSolve (Vector_t< double, Dim > & lower, Vector_t< double, Dim > & upper)
Computes the spatial bounds for the field solver based on the current particle distribution.
Determines the minimum and maximum coordinates (lower, upper) in each dimension that encompass all particles in the current container. Adjusts these bounds if image-charge boundary conditions are enabled to ensure the domain includes both the real and mirrored charge distributions. Guarantees a minimal span (e.g., 1e-6) in each dimension for validity and applies an additional extension based on the field solver's box increment percentage.
Parameters
[out] lower The lowest coordinate per dimension after considering all particles and any boundary extensions.
[out] upper The highest coordinate per dimension after considering all particles and any boundary extensions.
Definition at line 605 of file PartBunch.cpp.
References Dim, BinnedFieldSolver< T, Dim >::getImageChargePlaneZ(), and BinnedFieldSolver< T, Dim >::isImageChargeActiveForStep().
computeSelfFields()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::computeSelfFields ()
Compute the bunch self-fields (binned when available).
Compute the bunch self-fields (binned when available).
The actual implementation lives in the solver object (see BinnedFieldSolver). ParallelTracker only orchestrates reference/beam-frame transforms and calls this delegator once per step.
Definition at line 731 of file PartBunch.cpp.
References BinnedFieldSolver< T, Dim >::computeSelfFields().
Referenced by ParallelTracker::computeSpaceChargeFields().
do_binaryRepart()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::do_binaryRepart ()
ORB/binary repartition when the load balancer requests it (primary container).
ORB/binary repartition when the load balancer requests it (primary container).
Definition at line 221 of file PartBunch.cpp.
References FieldContainer< T, Dim >::getRho().
Referenced by ParallelTracker::doBinaryRepartition().
dumpBinConfig()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::dumpBinConfig (bool preMerge)
Write bin edges/counts to the data sink when configured.
Write bin edges/counts to the data sink when configured.
Parameters
preMerge True if called before a bin-merge step.
Definition at line 741 of file PartBunch.cpp.
References BinningCmd::dumpBinsToFile(), BinningCmd::getDumpBinsFileName(), and BinningCmd::getDumpBinsFrequency().
gatherLoadBalanceStatistics()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::gatherLoadBalanceStatistics ()
Definition at line 244 of file PartBunch.cpp.
Referenced by DataSink::dumpSDDS().
get_bounds()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::get_bounds (Vector_t< double, Dim > & rmin, Vector_t< double, Dim > & rmax) inline
Copy cached bunch extent (rmin_m, rmax_m) from calcBeamParameters.
Parameters
[out] rmin Lower corner.
[out] rmax Upper corner.
Definition at line 632 of file PartBunch.h.
References PartBunch< T, Dim >::rmax_m, and PartBunch< T, Dim >::rmin_m.
Referenced by Probe::doPreCheck(), and ParallelTracker::writePhaseSpace().
get_halo()
template<typename T , unsigned Dim> Vector_t< double, Dim > PartBunch< T, Dim >::get_halo () const inline
Stub; logs and returns zero vector.
Definition at line 659 of file PartBunch.h.
References gmsg.
Referenced by StatWriter::write().
get_hr()
template<typename T , unsigned Dim> Vector_t< double, Dim > PartBunch< T, Dim >::get_hr () const inline
Get mesh spacing.
Definition at line 666 of file PartBunch.h.
References PartBunch< T, Dim >::hr_m.
get_maxExtent()
template<typename T , unsigned Dim> Vector_t< double, Dim > PartBunch< T, Dim >::get_maxExtent () const inline
Cached maximum extent (rmax_m).
Definition at line 656 of file PartBunch.h.
References PartBunch< T, Dim >::rmax_m.
Referenced by H5PartWrapperForPT::writeStepHeader().
get_origin()
template<typename T , unsigned Dim> Vector_t< double, Dim > PartBunch< T, Dim >::get_origin () const inline
Cached minimum extent (rmin_m); prefer per-container min/max for multi-beam detail.
Definition at line 654 of file PartBunch.h.
References PartBunch< T, Dim >::rmin_m.
Referenced by H5PartWrapperForPT::writeStepHeader().
get_rmsDensity()
template<typename T , unsigned Dim> double PartBunch< T, Dim >::get_rmsDensity () const inline
Legacy RMS density field (may be unused).
Definition at line 681 of file PartBunch.h.
References PartBunch< T, Dim >::rmsDensity_m.
Referenced by StatWriter::write().
getBCHandler()
template<typename T , unsigned Dim> std::shared_ptr< BCHandler_t > PartBunch< T, Dim >::getBCHandler () const inline
Current boundary-condition handler.
Definition at line 330 of file PartBunch.h.
References PartBunch< T, Dim >::bcHandler_m.
Referenced by PartBunch< T, Dim >::PartBunch().
getBins() [1/2]
template<typename T , unsigned Dim> std::shared_ptr< AdaptBins_t > PartBunch< T, Dim >::getBins () inline
Non-const access to adaptive binning state.
Definition at line 318 of file PartBunch.h.
References PartBunch< T, Dim >::bins_m.
Referenced by PartBunch< T, Dim >::getCurrentNBins().
getBins() [2/2]
template<typename T , unsigned Dim> std::shared_ptr< AdaptBins_t > PartBunch< T, Dim >::getBins () const inline
Const access to adaptive binning state.
Definition at line 321 of file PartBunch.h.
References PartBunch< T, Dim >::bins_m.
getBunchStateHandler() [1/2]
template<typename T , unsigned Dim> std::shared_ptr< BunchStateHandler > PartBunch< T, Dim >::getBunchStateHandler () inline
Definition at line 334 of file PartBunch.h.
References PartBunch< T, Dim >::bunchState_m.
getBunchStateHandler() [2/2]
template<typename T , unsigned Dim> std::shared_ptr< const BunchStateHandler > PartBunch< T, Dim >::getBunchStateHandler () const inline
Definition at line 335 of file PartBunch.h.
References PartBunch< T, Dim >::bunchState_m.
getCharge()
template<typename T , unsigned Dim> double PartBunch< T, Dim >::getCharge (size_t containerIndex = 0) const inline
Get the total charge for a given particle container.
Parameters
containerIndex Index of the particle container.
Returns
qi_m[containerIndex] * getParticleContainers()[containerIndex]->getTotalNum().
Note
Throws if the number of particle containers and qi_m entries do not match, or if containerIndex is out of range.
Definition at line 386 of file PartBunch.h.
References PartBunch< T, Dim >::qi_m.
Referenced by PartBunch< T, Dim >::getQ().
getChargePerParticle()
template<typename T , unsigned Dim> double PartBunch< T, Dim >::getChargePerParticle (size_t containerIndex = 0) const inline
Get the charge per particle for a given particle container.
Parameters
containerIndex Index of the particle container.
Returns
qi_m[containerIndex].
Note
Throws if containerIndex is out of range.
Definition at line 405 of file PartBunch.h.
References PartBunch< T, Dim >::qi_m.
Referenced by Multipole::isFocusing().
getCurrentNBins()
template<typename T , unsigned Dim> int PartBunch< T, Dim >::getCurrentNBins () const inline
Effective bin count for diagnostics (1 if binning inactive or still at max bins).
Definition at line 573 of file PartBunch.h.
References PartBunch< T, Dim >::bins_m, PartBunch< T, Dim >::getBins(), and PartBunch< T, Dim >::hasBinning().
Referenced by StatWriter::write().
getDataSink()
template<typename T , unsigned Dim> DataSink * PartBunch< T, Dim >::getDataSink () const inline
Definition at line 332 of file PartBunch.h.
References PartBunch< T, Dim >::dataSink_m.
getdE()
template<typename T , unsigned Dim> double PartBunch< T, Dim >::getdE () inline
Definition at line 489 of file PartBunch.h.
getdT()
template<typename T , unsigned Dim> double PartBunch< T, Dim >::getdT () const inline
Get the global time step.
Definition at line 641 of file PartBunch.h.
References PartBunch< T, Dim >::dt_m.
Referenced by RFCavity::apply(), TravelingWave::apply(), Corrector::apply(), ParallelTracker::autophaseCavities(), ParallelTracker::changeDT(), ParallelTracker::execute(), ParallelTracker::findStartPositions(), Corrector::goOnline(), ParallelTracker::setTime(), ParallelTracker::updateReferenceParticles(), ParallelTracker::updateRefToLabCSTrafo(), StatWriter::write(), and ParallelTracker::writePhaseSpace().
getEExtrema()
template<typename T , unsigned Dim> Vector_t< double, Dim > PartBunch< T, Dim >::getEExtrema () inline
Stub; logs and returns zero vector.
Definition at line 526 of file PartBunch.h.
References gmsg.
getFieldSolver() [1/2]
template<typename T , unsigned Dim> PartBunch< T, Dim >::BinnedFieldSolver_t * PartBunch< T, Dim >::getFieldSolver ()
Non-const pointer to the concrete BinnedFieldSolver.
Create adaptive bins from the binning command (VELOCITYZ / GAMMAZ).
Note
Definition in PartBunch.cpp; requires complete BinnedFieldSolver type.
Definition at line 288 of file PartBunch.cpp.
Referenced by ParallelTracker::execute().
getFieldSolver() [2/2]
template<typename T , unsigned Dim> const PartBunch< T, Dim >::BinnedFieldSolver_t * PartBunch< T, Dim >::getFieldSolver () const
Const overload of getFieldSolver().
Definition at line 293 of file PartBunch.cpp.
getFieldSolverType()
template<typename T , unsigned Dim> std::string PartBunch< T, Dim >::getFieldSolverType ()
Backend type string (e.g. FFT, OPEN, CG, NONE).
Definition at line 298 of file PartBunch.cpp.
getGlobalTrackStep()
template<typename T , unsigned Dim> long long PartBunch< T, Dim >::getGlobalTrackStep () const inline
Current global tracking step.
Definition at line 672 of file PartBunch.h.
References PartBunch< T, Dim >::globalTrackStep_m.
Referenced by ParallelTracker::applyGlobalProcesses(), ParallelTracker::dumpStats(), ParallelTracker::execute(), and H5PartWrapperForPT::writeStepHeader().
getLoadBalance()
template<typename T , unsigned Dim> size_t PartBunch< T, Dim >::getLoadBalance (int p) inline
Definition at line 508 of file PartBunch.h.
References PartBunch< T, Dim >::globalPartPerNode_m.
getM()
template<typename T , unsigned Dim> double PartBunch< T, Dim >::getM (size_t containerIndex = 0) const inline
Get the total mass for a given particle container.
Parameters
containerIndex Index of the particle container.
Returns
mi_m[containerIndex] * getParticleContainers()[containerIndex]->getTotalNum().
Note
Throws if the number of particle containers and mi_m entries do not match, or if containerIndex is out of range.
Definition at line 439 of file PartBunch.h.
References PartBunch< T, Dim >::mi_m.
getMassPerParticle()
template<typename T , unsigned Dim> double PartBunch< T, Dim >::getMassPerParticle (size_t containerIndex = 0) const inline
Get the mass per particle for a given particle container.
Parameters
containerIndex Index of the particle container.
Returns
mi_m[containerIndex].
Note
Throws if containerIndex is out of range.
Definition at line 418 of file PartBunch.h.
References PartBunch< T, Dim >::mi_m.
getParticleName()
template<typename T , unsigned Dim> std::string PartBunch< T, Dim >::getParticleName (size_t i) const inline
Particle species name for container i (from BEAM PARTICLE input).
Definition at line 602 of file PartBunch.h.
References PartBunch< T, Dim >::particleNames_m.
Referenced by PartBunch< T, Dim >::PartBunch(), and StatWriter::write().
getQ()
template<typename T , unsigned Dim> double PartBunch< T, Dim >::getQ (size_t containerIndex = 0) const inline
Alias for getCharge(containerIndex).
Parameters
containerIndex Index of the particle container.
Returns
Equivalent to getCharge(containerIndex).
Definition at line 430 of file PartBunch.h.
References PartBunch< T, Dim >::getCharge().
getReference()
template<typename T , unsigned Dim> const PartData * PartBunch< T, Dim >::getReference () const inline
Definition at line 493 of file PartBunch.h.
References PartBunch< T, Dim >::reference_m.
Referenced by ParallelTracker::autophaseCavities(), ParallelTracker::execute(), PartBunch< T, Dim >::PartBunch(), RFCavity::trackOnAxisParticle(), and Tracker::visitComponent().
getT()
template<typename T , unsigned Dim> double PartBunch< T, Dim >::getT () const inline
Get the current simulation time.
Definition at line 650 of file PartBunch.h.
References PartBunch< T, Dim >::t_m.
Referenced by MultipoleT::apply(), RFCavity::apply(), TravelingWave::apply(), VariableRFCavity::apply(), ParallelTracker::autophaseCavities(), ParallelTracker::dumpStats(), ParallelTracker::execute(), ParallelTracker::findStartPositions(), ParallelTracker::updateReferenceParticles(), LBalWriter::write(), MemoryProfiler::write(), StatWriter::write(), DataSink::writeImpactStatistics(), ParallelTracker::writePhaseSpace(), and H5PartWrapperForPT::writeStepHeader().
getTempBField()
template<typename T , unsigned Dim> std::shared_ptr< VField_t< T, Dim > > PartBunch< T, Dim >::getTempBField () inline
Scratch B field used by the binned solver path.
Definition at line 312 of file PartBunch.h.
References PartBunch< T, Dim >::Btmp_m.
Referenced by PartBunch< T, Dim >::PartBunch().
getTempEField()
template<typename T , unsigned Dim> std::shared_ptr< VField_t< T, Dim > > PartBunch< T, Dim >::getTempEField () inline
Scratch E field used by the binned solver path.
Definition at line 306 of file PartBunch.h.
References PartBunch< T, Dim >::Etmp_m.
Referenced by PartBunch< T, Dim >::PartBunch().
getTotalCharge()
template<typename T , unsigned Dim> double PartBunch< T, Dim >::getTotalCharge () const inline
Get the total charge across all particle containers.
Returns
sum_i(qi_m[i] * containers[i]->getTotalNum()).
Note
Throws if the number of particle containers and qi_m entries do not match.
Definition at line 456 of file PartBunch.h.
References PartBunch< T, Dim >::qi_m.
Referenced by RFCavity::initialise(), and DataSink::writeImpactStatistics().
getTotalMass()
template<typename T , unsigned Dim> double PartBunch< T, Dim >::getTotalMass () const inline
Get the total mass across all particle containers.
Returns
sum_i(mi_m[i] * containers[i]->getTotalNum()).
Note
Throws if the number of particle containers and mi_m entries do not match.
Definition at line 475 of file PartBunch.h.
References PartBunch< T, Dim >::mi_m.
getTotalNumAllContainers()
template<typename T , unsigned Dim> size_t PartBunch< T, Dim >::getTotalNumAllContainers () const inline
Sum of getTotalNum() over all particle containers.
Definition at line 225 of file PartBunch.h.
Referenced by ParallelTracker::dumpStats(), ParallelTracker::execute(), ParallelTracker::printInitialContainerRefs(), and ParallelTracker::writePhaseSpace().
grid2par()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::grid2par () inline override
PicManager hook; throws (gather handled elsewhere).
Definition at line 299 of file PartBunch.h.
hasBinning()
template<typename T , unsigned Dim> bool PartBunch< T, Dim >::hasBinning () const inline
Returns
True if adaptive binning is configured.
Definition at line 568 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::getCurrentNBins().
hasFieldSolver()
template<typename T , unsigned Dim> bool PartBunch< T, Dim >::hasFieldSolver () const inline
Returns
True if a field solver instance is installed.
Definition at line 553 of file PartBunch.h.
Referenced by ParallelTracker::computeSpaceChargeFields(), ParallelTracker::doBinaryRepartition(), and ParallelTracker::execute().
incrementT()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::incrementT () inline
Advance time by one global time step.
Definition at line 647 of file PartBunch.h.
References PartBunch< T, Dim >::dt_m, and PartBunch< T, Dim >::t_m.
Referenced by ParallelTracker::execute().
incTrackSteps()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::incTrackSteps () inline
Increment globalTrackStep_m by one.
Definition at line 675 of file PartBunch.h.
References PartBunch< T, Dim >::globalTrackStep_m.
Referenced by ParallelTracker::execute().
isPcActive()
template<typename T , unsigned Dim> bool PartBunch< T, Dim >::isPcActive (size_t i) const inline
Parameters
i Container index.
Returns
Whether container i participates in the current segment.
Definition at line 255 of file PartBunch.h.
References PartBunch< T, Dim >::pcActive_m.
Referenced by ParallelTracker::computeExternalFields(), ParallelTracker::execute(), ParallelTracker::resetFields(), ParallelTracker::timeIntegration1(), ParallelTracker::timeIntegration2(), ParallelTracker::updateReferenceParticles(), and ParallelTracker::updateRefToLabCSTrafo().
P()
template<typename T , unsigned Dim> Vector_t< double, Dim > PartBunch< T, Dim >::P (size_t) inline
Do not use; throws (access momenta via ParticleContainer::P).
Definition at line 619 of file PartBunch.h.
Referenced by Corrector::apply(), PluginElement::changeWidth(), LF2< FieldFunction, Arguments >::doAdvance_m(), and Probe::doCheck().
par2grid()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::par2grid () inline override
PicManager hook; throws (scatter handled elsewhere).
Definition at line 292 of file PartBunch.h.
pcAtZStop()
template<typename T , unsigned Dim> bool PartBunch< T, Dim >::pcAtZStop (size_t i) const inline
Parameters
i Container index.
Returns
Whether container i is frozen at the current z-stop.
Definition at line 266 of file PartBunch.h.
References PartBunch< T, Dim >::pcAtZStop_m.
Referenced by ParallelTracker::emitFromEmissionSources().
performBunchSanityChecks()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::performBunchSanityChecks () const
Validate BC handler, solver wiring, field pointers, and layout extents.
Validate BC handler, solver wiring, field pointers, and layout extents.
Exceptions
OpalException if initialization is inconsistent.
Definition at line 792 of file PartBunch.cpp.
Referenced by ParallelTracker::execute().
pre_run()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::pre_run () override
Warm-up: zero rho and run the field solver once (skip full dumps).
Warm-up: zero rho and run the field solver once (skip full dumps).
Definition at line 450 of file PartBunch.cpp.
Referenced by PartBunch< T, Dim >::PartBunch().
print()
template<typename T , unsigned Dim> Inform & PartBunch< T, Dim >::print (Inform & os)
Human-readable dump of each container to os.
Human-readable dump of each container to os.
Parameters
os Output stream wrapper.
Returns
Reference to os.
Definition at line 470 of file PartBunch.cpp.
References ParticleContainer< T, Dim >::Attributes, Dim, Util::getEnergyString(), and Util::getLengthString().
R()
template<typename T , unsigned Dim> Vector_t< double, Dim > PartBunch< T, Dim >::R (size_t) inline
Do not use; throws (access positions via ParticleContainer::R).
Definition at line 610 of file PartBunch.h.
Referenced by Corrector::apply(), VerticalFFAMagnet::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), RFCavity::apply(), ScalingFFAMagnet::apply(), Solenoid::apply(), TravelingWave::apply(), Ring::apply(), ParallelTracker::computeSpaceChargeFields(), LF2< FieldFunction, Arguments >::doAdvance_m(), Probe::doCheck(), ParallelTracker::emitFromEmissionSources(), and H5PartWrapperForPT::writeStepData().
refreshPcActiveAfterEmit()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::refreshPcActiveAfterEmit ()
After emission: reactivate non-empty containers not marked at z-stop.
After emission: reactivate non-empty containers not marked at z-stop.
Definition at line 200 of file PartBunch.cpp.
Referenced by ParallelTracker::emitFromEmissionSources().
reinitializeGridZ()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::reinitializeGridZ (int nrZ)
Reinitialize the z dimension of the field grid to nrZ cells.
Refresh mesh from particle extents, update layouts, and recompute moments.
Rebuilds the FieldLayout, all field arrays, the accumulation buffers, and the IPPL Poisson solver to match the new z extent. A no-op if nrZ equals the current z cell count. Called from bunchUpdate to double the z resolution while image charges are active.
Parameters
nrZ Target number of z grid cells.
Definition at line 538 of file PartBunch.cpp.
References Dim.
resetPcActive()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::resetPcActive ()
At segment start: active if container is non-empty; inactive if empty.
At segment start: active if container is non-empty; inactive if empty.
Definition at line 168 of file PartBunch.cpp.
Referenced by ParallelTracker::execute(), and PartBunch< T, Dim >::PartBunch().
setBCHandler()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::setBCHandler (std::shared_ptr< BCHandler_t > bcHandler) inline
Parameters
bcHandler Boundary-condition handler for the mesh.
Definition at line 327 of file PartBunch.h.
References PartBunch< T, Dim >::bcHandler_m.
Referenced by PartBunch< T, Dim >::PartBunch().
setBins() [1/2]
template<typename T , unsigned Dim> void PartBunch< T, Dim >::setBins ()
Create adaptive bins from the binning command (VELOCITYZ / GAMMAZ).
Definition at line 303 of file PartBunch.cpp.
References GAMMAZ, BinningCmd::getBinningAlpha(), BinningCmd::getBinningBeta(), BinningCmd::getDesiredWidth(), BinningCmd::getMaxBins(), Object::getOpalName(), BinningCmd::getParameter(), BinningCmd::getParameterType(), and VELOCITYZ.
setBins() [2/2]
template<typename T , unsigned Dim> void PartBunch< T, Dim >::setBins (std::shared_ptr< AdaptBins_t > bins) inline
Parameters
bins Adaptive binning object (or nullptr to clear).
Definition at line 324 of file PartBunch.h.
References PartBunch< T, Dim >::bins_m.
setCharge()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::setCharge () inline
Set the per-particle charge for each particle container.
Note
Copies values from qi_m into each particle container via setQ.
Throws if the number of particle containers and qi_m entries do not match.
Definition at line 350 of file PartBunch.h.
References PartBunch< T, Dim >::qi_m.
setdT()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::setdT (double dt) inline
Set the global time step.
Definition at line 638 of file PartBunch.h.
References PartBunch< T, Dim >::dt_m.
Referenced by ParallelTracker::execute(), and ParallelTracker::selectDT().
setGlobalTrackStep()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::setGlobalTrackStep (long long n) inline
Parameters
n Global step counter to store.
Definition at line 669 of file PartBunch.h.
References PartBunch< T, Dim >::globalTrackStep_m.
Referenced by H5PartWrapperForPT::readStepHeader().
setImageChargeConfiguration()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::setImageChargeConfiguration (bool enabled, double zPlane)
Set the image-charge configuration for the field solver.
Parameters
enabled Enable image-charge scatter mirror when true.
zPlane Mirror plane position in z [m].
Definition at line 708 of file PartBunch.cpp.
setMass()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::setMass () inline
Set the per-particle mass for each particle container.
Note
Copies values from mi_m into each particle container via setM.
Throws if the number of particle containers and mi_m entries do not match.
Definition at line 367 of file PartBunch.h.
References PartBunch< T, Dim >::mi_m.
setPcActive()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::setPcActive (size_t i) inline
Force container i active (e.g. for containers with pending emission).
Definition at line 258 of file PartBunch.h.
References PartBunch< T, Dim >::pcActive_m.
Referenced by ParallelTracker::activateEmittingContainers().
setPcAtZStop()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::setPcAtZStop (size_t i)
Deactivate container i until the next step-size segment (z-stop reached).
Deactivate container i until the next step-size segment (z-stop reached).
Definition at line 188 of file PartBunch.cpp.
Referenced by ParallelTracker::execute().
setReference()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::setReference (const PartData * ref) inline
Set inside TrackRun::execute.
Definition at line 496 of file PartBunch.h.
References Units::eV2GeV, PartData::getM(), and PartBunch< T, Dim >::reference_m.
setShiftedGreensConfiguration()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::setShiftedGreensConfiguration (bool enabled, double zPlane)
Set the shifted Green's function Dirichlet-correction configuration.
Alternative to setImageChargeConfiguration. Mutually exclusive with it. Requires the OPEN field solver (checked at runtime in the correction pass).
Parameters
enabled Enable the shifted-Green's-function correction when true.
zPlane Dirichlet plane position in z [m].
Definition at line 713 of file PartBunch.cpp.
setSolver()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::setSolver ()
Build field solver and load balancer from OPALFieldSolver_m.
Build field solver and load balancer from OPALFieldSolver_m.
Definition at line 254 of file PartBunch.cpp.
Referenced by PartBunch< T, Dim >::PartBunch().
setT()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::setT (double t) inline
Set the current simulation time.
Definition at line 644 of file PartBunch.h.
References PartBunch< T, Dim >::t_m.
Referenced by ParallelTracker::execute(), ParallelTracker::findStartPositions(), PartBunch< T, Dim >::PartBunch(), and H5PartWrapperForPT::readStepHeader().
setTempBField()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::setTempBField (std::shared_ptr< VField_t< T, Dim > > Btmp) inline
Parameters
Btmp Scratch B field matching the mesh layout.
Definition at line 315 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::PartBunch().
setTempEField()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::setTempEField (std::shared_ptr< VField_t< T, Dim > > Etmp) inline
Parameters
Etmp Scratch E field matching the mesh layout.
Definition at line 309 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::PartBunch().
setZerofaceMaxSteps()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::setZerofaceMaxSteps (int maxSteps)
Set the maximum number of timesteps for which image charges are active (0 = unlimited).
Definition at line 723 of file PartBunch.cpp.
setZeroFacePlaneDumpFrequency()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::setZeroFacePlaneDumpFrequency (int frequency)
Configure diagnostic dump frequency for the ZEROFACE plane potential.
Parameters
frequency Dump every n-th global timestep. 0 disables dumping.
Definition at line 718 of file PartBunch.cpp.
updateMoments()
template<typename T , unsigned Dim> void PartBunch< T, Dim >::updateMoments () inline
Definition at line 337 of file PartBunch.h.
Referenced by DataSink::dumpSDDS(), and ParallelTracker::dumpStats().
Member Data Documentation
bcHandler_m
template<typename T , unsigned Dim> std::shared_ptr<BCHandler_t> PartBunch< T, Dim >::bcHandler_m private
Field boundary conditions.
Definition at line 103 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::getBCHandler(), and PartBunch< T, Dim >::setBCHandler().
bins_m
template<typename T , unsigned Dim> std::shared_ptr<AdaptBins_t> PartBunch< T, Dim >::bins_m private
Adaptive velocity/gamma binning (optional).
Definition at line 104 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::getBins(), PartBunch< T, Dim >::getBins(), PartBunch< T, Dim >::getCurrentNBins(), and PartBunch< T, Dim >::setBins().
Btmp_m
template<typename T , unsigned Dim> std::shared_ptr<VField_t<T, Dim> > PartBunch< T, Dim >::Btmp_m private
Scratch B field for binned accumulation (same layout as mesh B).
Definition at line 113 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::getTempBField().
bunchState_m
template<typename T , unsigned Dim> std::shared_ptr<BunchStateHandler> PartBunch< T, Dim >::bunchState_m private
Bunch state: unitless flag, repartition flag, etc.
Definition at line 101 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::getBunchStateHandler(), PartBunch< T, Dim >::getBunchStateHandler(), and PartBunch< T, Dim >::PartBunch().
dataSink_m
template<typename T , unsigned Dim> DataSink* PartBunch< T, Dim >::dataSink_m private
Borrowed diagnostics and dump output sink.
Definition at line 106 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::getDataSink(), and PartBunch< T, Dim >::PartBunch().
decomp_m
template<typename T , unsigned Dim> std::array<bool, Dim> PartBunch< T, Dim >::decomp_m
Domain decomposition flags (per axis).
Definition at line 88 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::PartBunch().
domain_m
template<typename T , unsigned Dim> ippl::NDIndex<Dim> PartBunch< T, Dim >::domain_m
Global mesh index extent per dimension.
Definition at line 87 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::PartBunch().
dt_m
template<typename T , unsigned Dim> double PartBunch< T, Dim >::dt_m
Global time step \(\Delta t\) (s).
Definition at line 72 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::getdT(), PartBunch< T, Dim >::incrementT(), PartBunch< T, Dim >::PartBunch(), and PartBunch< T, Dim >::setdT().
Etmp_m
template<typename T , unsigned Dim> std::shared_ptr<VField_t<T, Dim> > PartBunch< T, Dim >::Etmp_m private
Scratch E field for binned accumulation (same layout as mesh E).
Definition at line 111 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::getTempEField().
globalPartPerNode_m
template<typename T , unsigned Dim> std::unique_ptr<size_t[]> PartBunch< T, Dim >::globalPartPerNode_m private
Per-rank particle counts for load-balance stats.
Definition at line 118 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::getLoadBalance(), and PartBunch< T, Dim >::PartBunch().
globalTrackStep_m
template<typename T , unsigned Dim> long long PartBunch< T, Dim >::globalTrackStep_m private
Global integration step counter.
Definition at line 115 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::getGlobalTrackStep(), PartBunch< T, Dim >::incTrackSteps(), and PartBunch< T, Dim >::setGlobalTrackStep().
hr_m
template<typename T , unsigned Dim> Vector_t<double, Dim> PartBunch< T, Dim >::hr_m
Mesh spacing (m).
Definition at line 83 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::get_hr(), and PartBunch< T, Dim >::PartBunch().
integration_method_m
template<typename T , unsigned Dim> std::string PartBunch< T, Dim >::integration_method_m
Integrator name (e.g. leapfrog).
Definition at line 74 of file PartBunch.h.
isFirstRepartition_m
template<typename T , unsigned Dim> bool PartBunch< T, Dim >::isFirstRepartition_m
True until the first ORB-style repartition completes.
Definition at line 86 of file PartBunch.h.
it_m
template<typename T , unsigned Dim> int PartBunch< T, Dim >::it_m
Iteration counter (legacy / diagnostics).
Definition at line 73 of file PartBunch.h.
lbt_m
template<typename T , unsigned Dim> double PartBunch< T, Dim >::lbt_m
Load-balancer timescale parameter.
Definition at line 85 of file PartBunch.h.
mi_m
template<typename T , unsigned Dim> std::vector<double> PartBunch< T, Dim >::mi_m private
Mass per macroparticle [GeV], one entry per container.
Definition at line 96 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::getM(), PartBunch< T, Dim >::getMassPerParticle(), PartBunch< T, Dim >::getTotalMass(), PartBunch< T, Dim >::PartBunch(), and PartBunch< T, Dim >::setMass().
nr_m
template<typename T , unsigned Dim> Vector_t<int, Dim> PartBunch< T, Dim >::nr_m
Mesh cell count per dimension.
Definition at line 76 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::PartBunch().
nrZBase_m
template<typename T , unsigned Dim> int PartBunch< T, Dim >::nrZBase_m = 0
Base z grid count before any image-charge doubling; used to reset nr_m.
Definition at line 77 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::PartBunch().
OPALFieldSolver_m
template<typename T , unsigned Dim> FieldSolverCmd* PartBunch< T, Dim >::OPALFieldSolver_m private
Borrowed parsed FIELD_SOLVER command.
Definition at line 105 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::PartBunch().
origin_m
template<typename T , unsigned Dim> Vector_t<double, Dim> PartBunch< T, Dim >::origin_m
Mesh origin (lab coordinates).
Definition at line 78 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::PartBunch().
particleNames_m
template<typename T , unsigned Dim> std::vector<std::string> PartBunch< T, Dim >::particleNames_m private
Per-container beam particle names.
Definition at line 93 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::getParticleName(), and PartBunch< T, Dim >::PartBunch().
pcActive_m
template<typename T , unsigned Dim> std::vector<bool> PartBunch< T, Dim >::pcActive_m private
Per-container: participate in this track segment.
Definition at line 91 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::anyPcActive(), PartBunch< T, Dim >::isPcActive(), and PartBunch< T, Dim >::setPcActive().
pcAtZStop_m
template<typename T , unsigned Dim> std::vector<bool> PartBunch< T, Dim >::pcAtZStop_m private
Per-container: frozen at current z-stop until next segment.
Definition at line 92 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::pcAtZStop().
qi_m
template<typename T , unsigned Dim> std::vector<double> PartBunch< T, Dim >::qi_m private
Charge per macroparticle [C], one entry per container.
Definition at line 95 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::getCharge(), PartBunch< T, Dim >::getChargePerParticle(), PartBunch< T, Dim >::getTotalCharge(), PartBunch< T, Dim >::PartBunch(), and PartBunch< T, Dim >::setCharge().
reference_m
template<typename T , unsigned Dim> const PartData* PartBunch< T, Dim >::reference_m = nullptr private
Reference particle data (set by TrackRun::execute).
Definition at line 98 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::getReference(), and PartBunch< T, Dim >::setReference().
rmax_m
template<typename T , unsigned Dim> Vector_t<double, Dim> PartBunch< T, Dim >::rmax_m
Current bunch spatial maximum (from primary container stats).
Definition at line 82 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::get_bounds(), PartBunch< T, Dim >::get_maxExtent(), and PartBunch< T, Dim >::PartBunch().
rmin_m
template<typename T , unsigned Dim> Vector_t<double, Dim> PartBunch< T, Dim >::rmin_m
Current bunch spatial minimum (from primary container stats; see calcBeamParameters).
Definition at line 79 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::get_bounds(), PartBunch< T, Dim >::get_origin(), and PartBunch< T, Dim >::PartBunch().
rmsDensity_m
template<typename T , unsigned Dim> double PartBunch< T, Dim >::rmsDensity_m private
Legacy RMS density placeholder (may still appear in stats).
Definition at line 120 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::get_rmsDensity().
solver_m
template<typename T , unsigned Dim> std::string PartBunch< T, Dim >::solver_m
Field solver type string from input.
Definition at line 75 of file PartBunch.h.
t_m
template<typename T , unsigned Dim> double PartBunch< T, Dim >::t_m private
Current simulation time (s).
Definition at line 108 of file PartBunch.h.
Referenced by PartBunch< T, Dim >::getT(), PartBunch< T, Dim >::incrementT(), and PartBunch< T, Dim >::setT().
The documentation for this class was generated from the following files:
PartBunch.h
PartBunch.cpp