OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions::AList< T > Class Template Reference
Expressions::AList< T > Class Template Reference
An array expression defined by a list of scalar expressions.
#include <AList.h>
Public Member Functions
AList ()
Default constructor.
AList (const ArrayOfPtrs< T > &)
Constructor.
AList (const AList &)
virtual ~AList ()
virtual OArray< T > * clone () const
Make clone.
virtual std::vector< T > evaluate () const
Evaluate.
virtual void print (std::ostream &, int precedence=99) const
Print array expression.
virtual bool isConstant () const
Test for constant.
Protected Attributes
ArrayOfPtrs< T > itsValue
The vector of expressions.
Private Member Functions
void operator= (const AList &)
Detailed Description
template<class T>
class Expressions::AList< T >
An array expression defined by a list of scalar expressions.
Definition at line 35 of file AList.h.
Constructor & Destructor Documentation
AList() [1/3]
template<class T> Expressions::AList< T >::AList ()
Default constructor.
Definition at line 70 of file AList.h.
References itsValue.
Referenced by Expressions::ABinary< T, U >::ABinary(), AList(), Expressions::AUnary< T, U >::AUnary(), Expressions::AUnary< T, U >::AUnary(), clone(), and operator=().
AList() [2/3]
template<class T> Expressions::AList< T >::AList (const ArrayOfPtrs< T > & value) explicit
Constructor.
Definition at line 76 of file AList.h.
References itsValue.
AList() [3/3]
template<class T> Expressions::AList< T >::AList (const AList< T > &)
References AList(), and Expressions::OArray< T >::OArray().
~AList()
template<class T> Expressions::AList< T >::~AList () virtual
Definition at line 79 of file AList.h.
Member Function Documentation
clone()
template<class T> OArray< T > * Expressions::AList< T >::clone () const virtual
Make clone.
Implements Expressions::OArray< T >.
Reimplemented in Expressions::ABinary< T, U >, and Expressions::AUnary< T, U >.
Definition at line 82 of file AList.h.
References AList(), and Expressions::OArray< T >::OArray().
evaluate()
template<class T> std::vector< T > Expressions::AList< T >::evaluate () const virtual
Evaluate.
Implements Expressions::OArray< T >.
Reimplemented in Expressions::ABinary< T, U >, and Expressions::AUnary< T, U >.
Definition at line 87 of file AList.h.
References itsValue.
isConstant()
template<class T> bool Expressions::OArray< T >::isConstant () const inline virtual inherited
Test for constant.
Definition at line 304 of file AbstractObjects/Expressions.h.
operator=()
template<class T> void Expressions::AList< T >::operator= (const AList< T > &) private
References AList().
print()
template<class T> void Expressions::AList< T >::print (std::ostream & os, int precedence = 99) const virtual
Print array expression.
Implements Expressions::OArray< T >.
Reimplemented in Expressions::ABinary< T, U >, and Expressions::AUnary< T, U >.
Definition at line 98 of file AList.h.
References itsValue.
Member Data Documentation
itsValue
template<class T> ArrayOfPtrs<T> Expressions::AList< T >::itsValue protected
The vector of expressions.
Definition at line 59 of file AList.h.
Referenced by AList(), AList(), evaluate(), and print().
The documentation for this class was generated from the following file:
AList.h