OPALX (Object Oriented Parallel Accelerator Library for Exascal): ConstChannel Class Reference
ConstChannel Class Reference abstract
Abstract interface for read-only access to variable.
#include <ConstChannel.h>
Public Member Functions
ConstChannel ()
virtual ~ConstChannel ()
virtual ConstChannel * clone () const =0
Duplicate the channel.
virtual bool get (double &value) const =0
Read channel.
operator double () const
Read channel.
virtual bool isSettable () const
Check if settable.
Private Member Functions
ConstChannel (const ConstChannel &)
const ConstChannel & operator= (const ConstChannel &)
Detailed Description
Abstract interface for read-only access to variable.
Definition at line 28 of file ConstChannel.h.
Constructor & Destructor Documentation
ConstChannel() [1/2]
ConstChannel::ConstChannel ()
Definition at line 26 of file ConstChannel.cpp.
Referenced by Channel::Channel(), clone(), ConstChannel(), and operator=().
~ConstChannel()
ConstChannel::~ConstChannel () virtual
Definition at line 28 of file ConstChannel.cpp.
ConstChannel() [2/2]
ConstChannel::ConstChannel (const ConstChannel &) private
References ConstChannel().
Member Function Documentation
clone()
virtual ConstChannel * ConstChannel::clone () const pure virtual
Duplicate the channel.
Implemented in Channel, DirectChannel, IndexedChannel< T >, and IndirectChannel< T >.
References ConstChannel().
get()
virtual bool ConstChannel::get (double & value) const pure virtual
Read channel.
Implemented in DirectChannel, IndexedChannel< T >, and IndirectChannel< T >.
Referenced by operator double(), Channel::operator+=(), and Channel::operator-=().
isSettable()
bool ConstChannel::isSettable () const virtual
Check if settable.
Reimplemented in Channel, IndexedChannel< T >, and IndirectChannel< T >.
Definition at line 30 of file ConstChannel.cpp.
operator double()
ConstChannel::operator double () const inline
Read channel.
Definition at line 43 of file ConstChannel.h.
References get().
operator=()
const ConstChannel & ConstChannel::operator= (const ConstChannel &) private
References ConstChannel().
The documentation for this class was generated from the following files:
ConstChannel.h
ConstChannel.cpp