OPALX (Object Oriented Parallel Accelerator Library for Exascal): NullGeometry Class Reference
NullGeometry Class Reference
Geometry representing an identity transform.
#include <NullGeometry.h>
Public Member Functions
NullGeometry ()
NullGeometry (const NullGeometry &)
virtual ~NullGeometry ()
const NullGeometry & operator= (const NullGeometry &)
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual double getOrigin () const
Get origin position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual void setElementLength (double length)
Set geometry length.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
Detailed Description
Geometry representing an identity transform.
Definition at line 31 of file NullGeometry.h.
Constructor & Destructor Documentation
NullGeometry() [1/2]
NullGeometry::NullGeometry () inline
Definition at line 63 of file NullGeometry.h.
Referenced by NullGeometry(), and operator=().
NullGeometry() [2/2]
NullGeometry::NullGeometry (const NullGeometry & o) inline
Definition at line 65 of file NullGeometry.h.
References BGeometryBase::BGeometryBase(), and NullGeometry().
~NullGeometry()
NullGeometry::~NullGeometry () virtual
Definition at line 27 of file NullGeometry.cpp.
Member Function Documentation
getArcLength()
double NullGeometry::getArcLength () const virtual
Get arc length.
Implements BGeometryBase.
Definition at line 29 of file NullGeometry.cpp.
getElementLength()
double NullGeometry::getElementLength () const virtual
Get design length.
Implements BGeometryBase.
Definition at line 31 of file NullGeometry.cpp.
getEntrance()
double BGeometryBase::getEntrance () const virtual inherited
Get entrance position.
Reimplemented in BeamlineGeometry, PlanarArcGeometry, and StraightGeometry.
Definition at line 33 of file Geometry.cpp.
References getOrigin().
Referenced by ElementBase::getEntrance(), getEntranceFrame(), and getTotalTransform().
getEntranceFrame()
Euclid3D BGeometryBase::getEntranceFrame () const virtual inherited
Get transform.
Reimplemented in BeamlineGeometry, PlanarArcGeometry, RBendGeometry, and StraightGeometry.
Definition at line 41 of file Geometry.cpp.
References getEntrance(), and getTransform().
Referenced by ElementBase::getEntranceFrame().
getEntrancePatch()
Euclid3D BGeometryBase::getEntrancePatch () const virtual inherited
Get patch.
Reimplemented in RBendGeometry.
Definition at line 45 of file Geometry.cpp.
References Euclid3D::identity().
Referenced by ElementBase::getEntrancePatch().
getExit()
double BGeometryBase::getExit () const virtual inherited
Get exit position.
Reimplemented in BeamlineGeometry, PlanarArcGeometry, and StraightGeometry.
Definition at line 35 of file Geometry.cpp.
References getArcLength(), and getOrigin().
Referenced by ElementBase::getExit(), getExitFrame(), and getTotalTransform().
getExitFrame()
Euclid3D BGeometryBase::getExitFrame () const virtual inherited
Get transform.
Reimplemented in BeamlineGeometry, PlanarArcGeometry, RBendGeometry, and StraightGeometry.
Definition at line 43 of file Geometry.cpp.
References getExit(), and getTransform().
Referenced by ElementBase::getExitFrame().
getExitPatch()
Euclid3D BGeometryBase::getExitPatch () const virtual inherited
Get patch.
Reimplemented in RBendGeometry.
Definition at line 47 of file Geometry.cpp.
References Euclid3D::identity().
Referenced by ElementBase::getExitPatch().
getOrigin()
double NullGeometry::getOrigin () const virtual
Get origin position.
Reimplemented from BGeometryBase.
Definition at line 33 of file NullGeometry.cpp.
getTotalTransform()
Euclid3D BGeometryBase::getTotalTransform () const virtual inherited
Get transform.
Reimplemented in BeamlineGeometry, Euclid3DGeometry, PlanarArcGeometry, RBendGeometry, and StraightGeometry.
Definition at line 37 of file Geometry.cpp.
References getEntrance(), getExit(), and getTransform().
Referenced by Ring::appendElement(), and ElementBase::getTotalTransform().
getTransform() [1/2]
Euclid3D NullGeometry::getTransform (double fromS, double toS) const virtual
Get transform.
Implements BGeometryBase.
Definition at line 35 of file NullGeometry.cpp.
References Euclid3D::identity().
getTransform() [2/2]
Euclid3D NullGeometry::getTransform (double s) const virtual
Get transform.
Reimplemented from BGeometryBase.
Definition at line 37 of file NullGeometry.cpp.
References Euclid3D::identity().
operator=()
const NullGeometry & NullGeometry::operator= (const NullGeometry &) inline
Definition at line 67 of file NullGeometry.h.
References NullGeometry().
setElementLength()
void BGeometryBase::setElementLength (double length) virtual inherited
Set geometry length.
Reimplemented in DummyGeometry, DummyGeometryTW, Euclid3DGeometry, PlanarArcGeometry, and StraightGeometry.
Definition at line 29 of file Geometry.cpp.
Referenced by ElementBase::setElementLength().
The documentation for this class was generated from the following files:
NullGeometry.h
NullGeometry.cpp