OPALX (Object Oriented Parallel Accelerator Library for Exascal): endfieldmodel::Tanh Class Reference
endfieldmodel::Tanh Class Reference
#include <Tanh.h>
Public Member Functions
Tanh (double x0, double lambda, int max_index)
Tanh ()
Tanh (const Tanh &rhs)
~Tanh ()
Tanh * clone () const
void rescale (double scaleFactor)
double function (double x, int n) const
double getCentreLength () const
double getEndLength () const
double getTanh (double x, int n) const
double getNegTanh (double x, int n) const
double getLambda () const
double getX0 () const
void setLambda (double lambda)
void setX0 (double x0)
virtual void setMaximumDerivative (size_t n)
std::ostream & print (std::ostream &out) const
Static Public Member Functions
static std::vector< std::vector< int > > getTanhDiffIndices (size_t n)
static void setTanhDiffIndices (size_t n)
static std::shared_ptr< EndFieldModel > getEndFieldModel (std::string name)
static void setEndFieldModel (std::string name, std::shared_ptr< EndFieldModel > efm)
static std::string getName (std::shared_ptr< EndFieldModel > efm)
Private Attributes
double _x0
double _lambda
Static Private Attributes
static std::vector< std::vector< std::vector< int > > > _tdi
static std::map< std::string, std::shared_ptr< EndFieldModel > > efm_map
Detailed Description
Calculate the Tanh function (e.g. for multipole end fields).
DoubleTanh function is given by
\(T(x) = (tanh((x+x0)/\lambda)-tanh((x-x0)/\lambda))/2\)
The derivatives of tanh(x) are given by
\(d^p tanh(x)/dx^p = \sum_q I_{pq} tanh^{q}(x)\)
where \(I_{pq}\) are calculated using some recursion relation. Using these expressions, one can calculate a recursion relation for higher order derivatives and hence calculate analytical derivatives at arbitrary order.
Definition at line 48 of file Tanh.h.
Constructor & Destructor Documentation
Tanh() [1/3]
endfieldmodel::Tanh::Tanh (double x0, double lambda, int max_index)
Create a double tanh function
Here x0 is the centre length and lambda is the end length. max_index is used to set up for differentiation - don't try to calculate higher differentials than exist in max_index.
Definition at line 38 of file Tanh.cpp.
References setTanhDiffIndices().
Tanh() [2/3]
endfieldmodel::Tanh::Tanh () inline
Default constructor (initialises x0 and lambda to 0)
Definition at line 59 of file Tanh.h.
References setTanhDiffIndices().
Referenced by clone().
Tanh() [3/3]
endfieldmodel::Tanh::Tanh (const Tanh & rhs) inline
Copy constructor
Definition at line 62 of file Tanh.h.
~Tanh()
endfieldmodel::Tanh::~Tanh ()
Destructor (no mallocs so does nothing)
Definition at line 42 of file Tanh.cpp.
Member Function Documentation
clone()
Tanh * endfieldmodel::Tanh::clone () const virtual
Inherited copy constructor.
Implements endfieldmodel::EndFieldModel.
Definition at line 44 of file Tanh.cpp.
References Tanh().
function()
double endfieldmodel::Tanh::function (double x, int n) const virtual
Double Tanh is given by
\(d(x) = \)
Implements endfieldmodel::EndFieldModel.
Definition at line 68 of file Tanh.cpp.
References getNegTanh(), and getTanh().
getCentreLength()
double endfieldmodel::Tanh::getCentreLength () const inline virtual
Nominal flat top length is twice x0 (one x0 in each direction)
Implements endfieldmodel::EndFieldModel.
Definition at line 79 of file Tanh.h.
References getX0().
getEndFieldModel()
std::shared_ptr< EndFieldModel > endfieldmodel::EndFieldModel::getEndFieldModel (std::string name) static inherited
Look up the EndFieldModel that has a given name
Parameters
name name of the EndFieldModel
Returns
shared_ptr to the appropriate EndFieldModel.
Exceptions
GeneralOpalException if name is not recognised
Definition at line 63 of file EndFieldModel.cpp.
References endfieldmodel::EndFieldModel::efm_map.
Referenced by ScalingFFAMagnet::setupEndField().
getEndLength()
double endfieldmodel::Tanh::getEndLength () const inline virtual
Return nominal fringe field length
Implements endfieldmodel::EndFieldModel.
Definition at line 82 of file Tanh.h.
References getLambda().
getLambda()
double endfieldmodel::Tanh::getLambda () const inline
Return lambda (end length)
Definition at line 101 of file Tanh.h.
References _lambda.
Referenced by getEndLength().
getName()
std::string endfieldmodel::EndFieldModel::getName (std::shared_ptr< EndFieldModel > efm) static inherited
Get the name corresponding to a given EndFieldModel
Parameters
efm EndFieldModel to lookup
Returns
name corresponding to the EndFieldModel. Note that this just does a dumb loop over the stored map values; so O(N).
Exceptions
GeneralOpalException if efm is not recognised
Definition at line 77 of file EndFieldModel.cpp.
References endfieldmodel::EndFieldModel::efm_map.
getNegTanh()
double endfieldmodel::Tanh::getNegTanh (double x, int n) const
Returns the value of tanh((x-x0)/lambda) or its \(n^{th}\) derivative.
Definition at line 57 of file Tanh.cpp.
References _lambda, _tdi, _x0, and gsl_sf_pow_int().
Referenced by function().
getTanh()
double endfieldmodel::Tanh::getTanh (double x, int n) const
Returns the value of tanh((x+x0)/lambda) or its \(n^{th}\) derivative.
Definition at line 46 of file Tanh.cpp.
References _lambda, _tdi, _x0, and gsl_sf_pow_int().
Referenced by function().
getTanhDiffIndices()
std::vector< std::vector< int > > endfieldmodel::Tanh::getTanhDiffIndices (size_t n) static
Get all the tanh differential indices \(I_{pq}\).
Returns vector of vector of ints where p indexes the differential and q indexes the tanh power - so
Definition at line 98 of file Tanh.cpp.
References _tdi, and setTanhDiffIndices().
getX0()
double endfieldmodel::Tanh::getX0 () const inline
Return x0 (flat top length)
Definition at line 104 of file Tanh.h.
References _x0.
Referenced by getCentreLength().
print()
std::ostream & endfieldmodel::Tanh::print (std::ostream & out) const virtual
Prints a human readable string to out
Implements endfieldmodel::EndFieldModel.
Definition at line 108 of file Tanh.cpp.
References _lambda, and _x0.
rescale()
void endfieldmodel::Tanh::rescale (double scaleFactor) virtual
Rescale the end field by a factor x0
Implements endfieldmodel::EndFieldModel.
Definition at line 103 of file Tanh.cpp.
References _lambda, and _x0.
setEndFieldModel()
void endfieldmodel::EndFieldModel::setEndFieldModel (std::string name, std::shared_ptr< EndFieldModel > efm) static inherited
Add a value to the lookup table
Parameters
name name of the EndFieldModel. If name already exists in the map, it is overwritten with the new value.
efm shared_ptr to the EndFieldModel.
Definition at line 73 of file EndFieldModel.cpp.
References endfieldmodel::EndFieldModel::efm_map.
setLambda()
void endfieldmodel::Tanh::setLambda (double lambda) inline
Set lambda (end length)
Definition at line 107 of file Tanh.h.
References _lambda.
Referenced by OpalVerticalFFAMagnet::update().
setMaximumDerivative()
void endfieldmodel::Tanh::setMaximumDerivative (size_t n) virtual
Set the maximum derivative prior to tracking
Implements endfieldmodel::EndFieldModel.
Definition at line 70 of file Tanh.cpp.
References setTanhDiffIndices().
setTanhDiffIndices()
void endfieldmodel::Tanh::setTanhDiffIndices (size_t n) static
Set the value of tanh differential indices to nth order differentials.
Definition at line 72 of file Tanh.cpp.
References _tdi, and endfieldmodel::CompactVector().
Referenced by getTanhDiffIndices(), setMaximumDerivative(), Tanh(), Tanh(), and OpalVerticalFFAMagnet::update().
setX0()
void endfieldmodel::Tanh::setX0 (double x0) inline
Set x0 (flat top length)
Definition at line 110 of file Tanh.h.
References _x0.
Referenced by OpalVerticalFFAMagnet::update().
Member Data Documentation
_lambda
double endfieldmodel::Tanh::_lambda private
Definition at line 119 of file Tanh.h.
Referenced by getLambda(), getNegTanh(), getTanh(), print(), rescale(), and setLambda().
_tdi
std::vector< std::vector< std::vector< int > > > endfieldmodel::Tanh::_tdi static private
_tdi indexes powers of tanh in d^n tanh/dx^n as sum of powers of tanh
For some reason we index as n, +a, -a, but the third index is redundant
Definition at line 125 of file Tanh.h.
Referenced by getNegTanh(), getTanh(), getTanhDiffIndices(), and setTanhDiffIndices().
_x0
double endfieldmodel::Tanh::_x0 private
Definition at line 119 of file Tanh.h.
Referenced by getNegTanh(), getTanh(), getX0(), print(), rescale(), and setX0().
efm_map
std::map< std::string, std::shared_ptr< EndFieldModel > > endfieldmodel::EndFieldModel::efm_map static private inherited
Definition at line 108 of file EndFieldModel.h.
Referenced by endfieldmodel::EndFieldModel::getEndFieldModel(), endfieldmodel::EndFieldModel::getName(), and endfieldmodel::EndFieldModel::setEndFieldModel().
The documentation for this class was generated from the following files:
Tanh.h
Tanh.cpp