OPALX (Object Oriented Parallel Accelerator Library for Exascal): StaticElectricField Class Reference
StaticElectricField Class Reference abstract
Abstract base class for static electric fields.
#include <StaticElectricField.h>
Public Member Functions
StaticElectricField ()
virtual ~StaticElectricField ()
virtual EVector Efield (const Point3D &P) const
Get field.
virtual EVector Efield (const Point3D &P, double t) const
Get field.
virtual BVector Bfield (const Point3D &P) const
Get field.
virtual BVector Bfield (const Point3D &P, double t) const
Get field.
virtual EBVectors EBfield (const Point3D &P) const
Get field.
virtual EBVectors EBfield (const Point3D &P, double t) const
Get field.
virtual void scale (double scalar)=0
Scale the field.
Static Public Attributes
static const EVector ZeroEfield
The constant representing a zero electric field.
static const BVector ZeroBfield
The constant representing a zero magnetic field.
static const EBVectors ZeroEBfield
The constant representing a zero electromagnetic field.
Detailed Description
Abstract base class for static electric fields.
Definition at line 30 of file StaticElectricField.h.
Constructor & Destructor Documentation
StaticElectricField()
StaticElectricField::StaticElectricField ()
Definition at line 27 of file StaticElectricField.cpp.
~StaticElectricField()
StaticElectricField::~StaticElectricField () virtual
Definition at line 31 of file StaticElectricField.cpp.
Member Function Documentation
Bfield() [1/2]
BVector EMField::Bfield (const Point3D & P) const virtual inherited
Get field.
Reimplemented in BDipoleField, BMultipoleField, ConstBzField, and OscillatingField< ConstEzField >.
Definition at line 168 of file EMField.cpp.
References EMField::ZeroBfield.
Referenced by Component::Bfield(), Component::Bfield(), EMField::Bfield(), and EMField::EBfield().
Bfield() [2/2]
BVector EMField::Bfield (const Point3D & P, double t) const virtual inherited
Get field.
Reimplemented in BDipoleField, BMultipoleField, ConstBzField, and OscillatingField< ConstEzField >.
Definition at line 178 of file EMField.cpp.
References EMField::Bfield().
EBfield() [1/2]
EBVectors EMField::EBfield (const Point3D & P) const virtual inherited
Get field.
Definition at line 183 of file EMField.cpp.
References EMField::Bfield(), and EMField::Efield().
Referenced by Component::EBfield(), Component::EBfield(), and EMField::EBfield().
EBfield() [2/2]
EBVectors EMField::EBfield (const Point3D & P, double t) const virtual inherited
Get field.
Definition at line 188 of file EMField.cpp.
References EMField::EBfield().
Efield() [1/2]
EVector EMField::Efield (const Point3D & P) const virtual inherited
Get field.
Reimplemented in ConstEzField, and OscillatingField< ConstEzField >.
Definition at line 163 of file EMField.cpp.
References EMField::ZeroEfield.
Referenced by EMField::EBfield(), Component::Efield(), Component::Efield(), and EMField::Efield().
Efield() [2/2]
EVector EMField::Efield (const Point3D & P, double t) const virtual inherited
Get field.
Reimplemented in ConstEzField, and OscillatingField< ConstEzField >.
Definition at line 173 of file EMField.cpp.
References EMField::Efield().
scale()
virtual void EMField::scale (double scalar) pure virtual inherited
Scale the field.
Implemented in BDipoleField, BMultipoleField, ConstBzField, ConstEzField, NullField, DummyField, and DummyFieldTW.
Member Data Documentation
ZeroBfield
const BVector EMField::ZeroBfield static inherited
The constant representing a zero magnetic field.
Definition at line 239 of file EMField.h.
Referenced by EMField::Bfield().
ZeroEBfield
const EBVectors EMField::ZeroEBfield static inherited
The constant representing a zero electromagnetic field.
Definition at line 242 of file EMField.h.
ZeroEfield
const EVector EMField::ZeroEfield static inherited
The constant representing a zero electric field.
Definition at line 236 of file EMField.h.
Referenced by EMField::Efield().
The documentation for this class was generated from the following files:
StaticElectricField.h
StaticElectricField.cpp