OPALX (Object Oriented Parallel Accelerator Library for Exascal): StepSizeConfig Class Reference
StepSizeConfig Class Reference
#include <StepSizeConfig.h>
Public Member Functions
StepSizeConfig ()
StepSizeConfig (const StepSizeConfig &right)
void operator= (const StepSizeConfig &)=delete
void push_back (double dt, double zstop, unsigned long numSteps)
void sortAscendingZStop ()
void resetIterator ()
bool reachedStart () const
bool reachedEnd () const
void clear ()
void reverseDirection ()
StepSizeConfig & advanceToPos (double spos)
StepSizeConfig & operator++ ()
StepSizeConfig & operator-- ()
void shiftZStopRight (double front)
double getdT () const
double getZStop () const
unsigned long getNumSteps () const
unsigned long long getMaxSteps () const
unsigned long long getNumStepsFinestResolution () const
double getMinTimeStep () const
double getFinalZStop () const
Inform & print (Inform &out) const
void printDirect (Inform &out) const
ValueRange< double > getPathLengthRange () const
Private Types
typedef std::tuple< double, double, unsigned long > entry_t
typedef std::list< entry_t > container_t
Private Attributes
container_t configurations_m
container_t::iterator it_m
Detailed Description
Definition at line 30 of file StepSizeConfig.h.
Member Typedef Documentation
container_t
typedef std::list<entry_t> StepSizeConfig::container_t private
Definition at line 81 of file StepSizeConfig.h.
entry_t
typedef std::tuple<double, double, unsigned long> StepSizeConfig::entry_t private
Definition at line 80 of file StepSizeConfig.h.
Constructor & Destructor Documentation
StepSizeConfig() [1/2]
StepSizeConfig::StepSizeConfig () inline
Definition at line 91 of file StepSizeConfig.h.
References configurations_m, and it_m.
Referenced by advanceToPos(), operator++(), operator--(), operator=(), and StepSizeConfig().
StepSizeConfig() [2/2]
StepSizeConfig::StepSizeConfig (const StepSizeConfig & right) inline
Definition at line 93 of file StepSizeConfig.h.
References configurations_m, it_m, and StepSizeConfig().
Member Function Documentation
advanceToPos()
StepSizeConfig & StepSizeConfig::advanceToPos (double spos)
Definition at line 42 of file StepSizeConfig.cpp.
References configurations_m, getZStop(), it_m, and StepSizeConfig().
clear()
void StepSizeConfig::clear () inline
Definition at line 106 of file StepSizeConfig.h.
References configurations_m, and it_m.
getdT()
double StepSizeConfig::getdT () const
Definition at line 87 of file StepSizeConfig.cpp.
References it_m, and reachedEnd().
Referenced by ParallelTracker::findStartPositions().
getFinalZStop()
double StepSizeConfig::getFinalZStop () const
Definition at line 153 of file StepSizeConfig.cpp.
References configurations_m.
getMaxSteps()
unsigned long long StepSizeConfig::getMaxSteps () const
Definition at line 114 of file StepSizeConfig.cpp.
References configurations_m.
getMinTimeStep()
double StepSizeConfig::getMinTimeStep () const
Definition at line 142 of file StepSizeConfig.cpp.
References configurations_m.
getNumSteps()
unsigned long StepSizeConfig::getNumSteps () const
Definition at line 105 of file StepSizeConfig.cpp.
References it_m, and reachedEnd().
getNumStepsFinestResolution()
unsigned long long StepSizeConfig::getNumStepsFinestResolution () const
Definition at line 123 of file StepSizeConfig.cpp.
References configurations_m.
getPathLengthRange()
ValueRange< double > StepSizeConfig::getPathLengthRange () const
Definition at line 188 of file StepSizeConfig.cpp.
References configurations_m, and ValueRange< T >::enlargeIfOutside().
getZStop()
double StepSizeConfig::getZStop () const
Definition at line 96 of file StepSizeConfig.cpp.
References it_m, and reachedEnd().
Referenced by advanceToPos(), and ParallelTracker::findStartPositions().
operator++()
StepSizeConfig & StepSizeConfig::operator++ ()
Definition at line 50 of file StepSizeConfig.cpp.
References it_m, reachedEnd(), and StepSizeConfig().
operator--()
StepSizeConfig & StepSizeConfig::operator-- ()
Definition at line 61 of file StepSizeConfig.cpp.
References it_m, reachedStart(), and StepSizeConfig().
operator=()
void StepSizeConfig::operator= (const StepSizeConfig &) delete
References StepSizeConfig().
print()
Inform & StepSizeConfig::print (Inform & out) const
Definition at line 155 of file StepSizeConfig.cpp.
References configurations_m, and it_m.
printDirect()
void StepSizeConfig::printDirect (Inform & out) const
Definition at line 172 of file StepSizeConfig.cpp.
References configurations_m, and it_m.
push_back()
void StepSizeConfig::push_back (double dt, double zstop, unsigned long numSteps) inline
Definition at line 96 of file StepSizeConfig.h.
References configurations_m.
Referenced by TEST_F(), TEST_F(), and TEST_F().
reachedEnd()
bool StepSizeConfig::reachedEnd () const inline
Definition at line 104 of file StepSizeConfig.h.
References configurations_m, and it_m.
Referenced by ParallelTracker::findStartPositions(), getdT(), getNumSteps(), getZStop(), and operator++().
reachedStart()
bool StepSizeConfig::reachedStart () const inline
Definition at line 102 of file StepSizeConfig.h.
References configurations_m, and it_m.
Referenced by operator--().
resetIterator()
void StepSizeConfig::resetIterator () inline
Definition at line 100 of file StepSizeConfig.h.
References configurations_m, and it_m.
Referenced by TEST_F(), TEST_F(), and TEST_F().
reverseDirection()
void StepSizeConfig::reverseDirection ()
Definition at line 35 of file StepSizeConfig.cpp.
References configurations_m, and it_m.
shiftZStopRight()
void StepSizeConfig::shiftZStopRight (double front)
Definition at line 72 of file StepSizeConfig.cpp.
References configurations_m.
sortAscendingZStop()
void StepSizeConfig::sortAscendingZStop ()
Definition at line 29 of file StepSizeConfig.cpp.
References configurations_m.
Member Data Documentation
configurations_m
container_t StepSizeConfig::configurations_m private
Definition at line 83 of file StepSizeConfig.h.
Referenced by advanceToPos(), clear(), getFinalZStop(), getMaxSteps(), getMinTimeStep(), getNumStepsFinestResolution(), getPathLengthRange(), print(), printDirect(), push_back(), reachedEnd(), reachedStart(), resetIterator(), reverseDirection(), shiftZStopRight(), sortAscendingZStop(), StepSizeConfig(), and StepSizeConfig().
it_m
container_t::iterator StepSizeConfig::it_m private
Definition at line 84 of file StepSizeConfig.h.
Referenced by advanceToPos(), clear(), getdT(), getNumSteps(), getZStop(), operator++(), operator--(), print(), printDirect(), reachedEnd(), reachedStart(), resetIterator(), reverseDirection(), StepSizeConfig(), and StepSizeConfig().
The documentation for this class was generated from the following files:
StepSizeConfig.h
StepSizeConfig.cpp