OPALX (Object Oriented Parallel Accelerator Library for Exascal): Sequence Class Reference
Sequence Class Reference
#include <Sequence.h>
Public Types
typedef TBeamline< SequenceMember > TLine
The type of a sequence line.
enum ReferenceType { IS_ENTRY , IS_CENTRE , IS_EXIT }
Reference for element positioning.
Public Member Functions
Sequence ()
Exemplar constructor.
virtual ~Sequence ()
virtual Sequence * clone (const std::string &name)
Make clone.
virtual Sequence * copy (const std::string &name)
Make copy of the sequence line.
virtual double getLength () const
Return sequence length.
virtual double getEntrance (ReferenceType) const
Return the arc length from origin to entrance.
virtual double getExit (ReferenceType) const
Return the arc length from origin to exit.
ReferenceType getReference () const
Return the reference type flag.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Make a sequence template.
virtual void parse (Statement &)
Parse sequence.
virtual void print (std::ostream &) const
Print sequence.
virtual void replace (Object *oldObject, Object *newObject)
Replace references to elements.
virtual void update ()
Update the embedded OPALX beam line.
virtual TLine * fetchLine () const
Return the embedded OPALX beam line.
void storeLine (TLine &line)
Store sequence line.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual void setShared (bool)
Set shared flag.
ElementBase * getElement () const
Return the embedded OPALX element.
std::shared_ptr< ElementBase > getElementPtr () const
Return the embedded OPALX element as shared_ptr.
void setElement (ElementBase *)
Assign new OPALX element.
void setElement (std::shared_ptr< ElementBase > base)
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Static Public Member Functions
static BeamSequence * find (const std::string &name)
Find a BeamSequence by name.
Public Attributes
std::vector< Attribute > itsAttr
The object attributes.
Protected Attributes
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Private Member Functions
Sequence (const Sequence &)
void operator= (const Sequence &)
Sequence (const std::string &name, Sequence *parent)
void addEndMarkers (TLine &line) const
double findDriftLength (TLine::iterator drift) const
TLine::iterator findNamedPosition (TLine &, const std::string &) const
void insertDrifts (TLine &line)
Static Private Member Functions
static void updateList (Sequence *, TLine *)
Private Attributes
ReferenceType itsCode
std::string itsRefPoint
std::shared_ptr< ElementBase > itsOPALXElement
Object * itsParent
std::string itsName
std::string itsHelp
int occurrence
double timeStamp
std::set< Invalidator * > references
bool sharedFlag
Friends
class Edit
class SequenceParser
class SequenceTemplate
Detailed Description
Definition at line 33 of file Sequence.h.
Member Typedef Documentation
TLine
typedef TBeamline<SequenceMember> Sequence::TLine
The type of a sequence line.
Definition at line 40 of file Sequence.h.
Member Enumeration Documentation
ReferenceType
enum Element::ReferenceType inherited
Reference for element positioning.
Enumerator
IS_ENTRY
IS_CENTRE
IS_EXIT
Definition at line 43 of file Element.h.
Constructor & Destructor Documentation
Sequence() [1/3]
Sequence::Sequence ()
Exemplar constructor.
Definition at line 52 of file Sequence.cpp.
References Object::itsAttr, Attributes::makeReal(), Attributes::makeString(), Object::registerOwnership(), Element::setElement(), and AttributeHandler::STATEMENT.
Referenced by clone().
~Sequence()
Sequence::~Sequence () virtual
Definition at line 91 of file Sequence.cpp.
Sequence() [2/3]
Sequence::Sequence (const Sequence &) private
Sequence() [3/3]
Sequence::Sequence (const std::string & name, Sequence * parent) private
Definition at line 82 of file Sequence.cpp.
References Element::setElement().
Member Function Documentation
addEndMarkers()
void Sequence::addEndMarkers (TLine & line) const private
Definition at line 283 of file Sequence.cpp.
References SequenceMember::ABSOLUTE, Element::find(), Element::getElementPtr(), getLength(), SequenceMember::GLOBAL, SequenceMember::itsFlag, SequenceMember::itsPosition, SequenceMember::itsType, and ElmPtr::setElement().
Referenced by SequenceParser::parse().
canReplaceBy()
bool Element::canReplaceBy (Object * object) virtual inherited
Test if replacement is allowed.
Reimplemented from Object.
Definition at line 37 of file Element.cpp.
clear()
void Object::clear () inherited
Clear the occurrence counter.
Definition at line 285 of file Object.cpp.
References Object::occurrence.
clone()
Sequence * Sequence::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 93 of file Sequence.cpp.
References Sequence().
Referenced by copy(), and SequenceTemplate::makeInstance().
copy()
Sequence * Sequence::copy (const std::string & name) virtual
Make copy of the sequence line.
Implements BeamSequence.
Definition at line 95 of file Sequence.cpp.
References ElementBase::clone(), clone(), ElementBase::copyStructure(), fetchLine(), SequenceMember::GENERATED, ElmPtr::getElement(), ElmPtr::setElement(), and storeLine().
copyAttributes()
void Object::copyAttributes (const Object & source) inherited
Copy attributes from another object.
Definition at line 50 of file Object.cpp.
References Object::itsAttr.
Referenced by SequenceTemplate::makeInstance(), and LineTemplate::makeInstance().
execute()
void Object::execute () virtual inherited
Execute the command.
Reimplemented in Call, Echo, Help, Option, PSystem, Quit, Select, Stop, System, Title, Value, Distribution, EmissionSourceList, MacroCmd, Beam, BinningCmd, BoundaryGeometry, EmissionSource, FieldSolverCmd, TrackCmd, TrackEnd, TrackRun, OpalFilter, and DumpEMFields.
Definition at line 52 of file Object.cpp.
fetchLine()
Sequence::TLine * Sequence::fetchLine () const virtual
Return the embedded OPALX beam line.
Implements BeamSequence.
Definition at line 253 of file Sequence.cpp.
References Element::getElement().
Referenced by copy(), getEntrance(), getExit(), print(), replace(), storeLine(), and update().
find()
BeamSequence * BeamSequence::find (const std::string & name) static inherited
Find a BeamSequence by name.
Definition at line 30 of file BeamSequence.cpp.
References OpalData::find(), and OpalData::getInstance().
Referenced by TrackCmd::execute().
findAttribute() [1/2]
Attribute * Object::findAttribute (const std::string & name) virtual inherited
Find an attribute by name.
Definition at line 56 of file Object.cpp.
References Object::itsAttr.
Referenced by SequenceParser::findNeighbourPositions(), OpalElement::getParticleMatterInteraction(), OpalElement::getTypeName(), OpalElement::getWakeF(), Object::parse(), OpalElement::parse(), Line::parse(), OpalParser::parseAssign(), SequenceParser::parsePosition(), TrackRun::print(), and TEST().
findAttribute() [2/2]
const Attribute * Object::findAttribute (const std::string & name) const virtual inherited
Find an attribute by name.
Definition at line 63 of file Object.cpp.
References Object::itsAttr.
findDriftLength()
double Sequence::findDriftLength (TLine::iterator drift) const private
Definition at line 295 of file Sequence.cpp.
References Object::getOpalName(), and itsCode.
Referenced by updateList().
findNamedPosition()
Sequence::TLine::iterator Sequence::findNamedPosition (TLine & line, const std::string & name) const private
Definition at line 116 of file Sequence.cpp.
References SequenceMember::GENERATED.
Referenced by SequenceParser::findFromPositions(), getEntrance(), and getExit().
getBaseObject()
const Object * Object::getBaseObject () const inherited
Return the object's base type object.
Definition at line 260 of file Object.cpp.
References Object::itsParent.
getCategory()
const std::string BeamSequence::getCategory () const virtual inherited
Return the object category as a string.
Reimplemented from Element.
Definition at line 28 of file BeamSequence.cpp.
getElement()
ElementBase * Element::getElement () const inline inherited
Return the embedded OPALX element.
Definition at line 119 of file Element.h.
References Element::itsOPALXElement.
Referenced by Line::fetchLine(), fetchLine(), OpalMarker::OpalMarker(), OpalVariableRFCavity::OpalVariableRFCavity(), Line::replace(), replace(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), OpalCavity::update(), OpalConstantEFieldCavity::update(), OpalDrift::update(), OpalElement::update(), OpalMarker::update(), OpalMonitor::update(), OpalMultipole::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalRBend::update(), OpalRingDefinition::update(), OpalSBend::update(), OpalSolenoid::update(), OpalTravelingWave::update(), OpalVacuum::update(), OpalVerticalFFAMagnet::update(), OpalLaser::update(), OpalMultipoleT::update(), and OpalVariableRFCavity::update().
getElementPtr()
std::shared_ptr< ElementBase > Element::getElementPtr () const inline inherited
Return the embedded OPALX element as shared_ptr.
Definition at line 121 of file Element.h.
References Element::itsOPALXElement.
Referenced by addEndMarkers(), and Line::parse().
getEntrance()
double Sequence::getEntrance (ReferenceType ref) const virtual
Return the arc length from origin to entrance.
Reimplemented from Element.
Definition at line 144 of file Sequence.cpp.
References fetchLine(), findNamedPosition(), Element::getEntrance(), and itsRefPoint.
getExit()
double Sequence::getExit (ReferenceType ref) const virtual
Return the arc length from origin to exit.
Reimplemented from Element.
Definition at line 154 of file Sequence.cpp.
References fetchLine(), findNamedPosition(), Element::getExit(), getLength(), and itsRefPoint.
getLength()
double Sequence::getLength () const virtual
Return sequence length.
Implements Element.
Definition at line 142 of file Sequence.cpp.
References Attributes::getReal(), and Object::itsAttr.
Referenced by addEndMarkers(), and getExit().
getOpalName()
const std::string & Object::getOpalName () const inherited
Return object name.
Definition at line 267 of file Object.cpp.
References Object::itsName.
Referenced by OpalVariableRFCavity::clone(), Macro::clone(), OpalData::create(), OpalData::define(), findDriftLength(), SequenceParser::findNeighbourPositions(), ValueDefinition::getBool(), ValueDefinition::getBoolComponent(), ValueDefinition::getReal(), ValueDefinition::getRealComponent(), ValueDefinition::getString(), ValueDefinition::getStringComponent(), Object::makeInstance(), SequenceTemplate::makeInstance(), LineTemplate::makeInstance(), Object::parse(), SequenceParser::parseMember(), SequenceParser::parsePosition(), Object::print(), OpalElement::print(), print(), TrackRun::print(), BoolConstant::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), StringConstant::print(), Beam::print(), OpalFilter::print(), Line::print(), BinningCmd::printInfo(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), OpalElement::registerOwnership(), Object::registerOwnership(), Line::replace(), replace(), PartBunch< T, Dim >::setBins(), TEST(), TEST(), TEST(), TEST_F(), Beam::update(), BoundaryGeometry::update(), OpalFilter::update(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), and OpalSplineTimeDependence::update().
getParent()
Object * Object::getParent () const inherited
Return parent pointer.
Definition at line 269 of file Object.cpp.
References Object::itsParent.
Referenced by OpalData::erase(), Object::print(), OpalElement::print(), OpalElement::registerOwnership(), and Object::registerOwnership().
getReference()
Sequence::ReferenceType Sequence::getReference () const
Return the reference type flag.
Definition at line 164 of file Sequence.cpp.
References Attributes::getString(), Element::IS_CENTRE, Element::IS_ENTRY, Element::IS_EXIT, and Object::itsAttr.
Referenced by storeLine().
increment()
int Object::increment () inherited
Increment and return the occurrence counter.
Definition at line 287 of file Object.cpp.
References Object::occurrence.
Referenced by Line::parse(), and storeLine().
insertDrifts()
void Sequence::insertDrifts (Sequence::TLine & line) private
Definition at line 336 of file Sequence.cpp.
References SequenceMember::GENERATED, SequenceMember::itsType, ElmPtr::setElement(), and ElementBase::setName().
Referenced by SequenceParser::parse().
isBuiltin()
bool Object::isBuiltin () const inherited
True, if [b]this[/b] is a built-in object.
Definition at line 243 of file Object.cpp.
References Object::builtin.
Referenced by OpalData::define(), and OpalData::getVariableNames().
isDirty()
bool Object::isDirty () const inherited
True, if the [b]modified[/b] flag is set.
Definition at line 254 of file Object.cpp.
References Object::modified.
isFlagged()
bool Object::isFlagged () const inherited
True, if [b]this[/b] is flagged by setFlag(true).
Definition at line 258 of file Object.cpp.
References Object::flagged.
isShared()
bool Object::isShared () const virtual inherited
Shared flag.
Definition at line 245 of file Object.cpp.
References Object::sharedFlag.
Referenced by print().
isTreeMember()
bool Object::isTreeMember (const Object * subTree) const inherited
Test for tree membership.
Definition at line 271 of file Object.cpp.
References Object::itsParent.
Referenced by Selector::handleElement(), and OpalParser::parseAssign().
makeInstance()
Object * Object::makeInstance (const std::string & name, Statement & , const Parser *) virtual inherited
Macro handler function.
Reimplemented in SequenceTemplate, MacroCmd, and LineTemplate.
Definition at line 76 of file Object.cpp.
References Object::getOpalName().
Referenced by OpalParser::parseDefine(), and OpalParser::parseMacro().
makeTemplate()
Object * Sequence::makeTemplate (const std::string & name, TokenStream & is, Statement & statement) virtual
Make a sequence template.
Reimplemented from Object.
Definition at line 177 of file Sequence.cpp.
References SequenceTemplate::parseTemplate(), and SequenceTemplate.
occurrenceCount()
int Object::occurrenceCount () inherited
Return the occurrence counter.
Definition at line 289 of file Object.cpp.
References Object::occurrence.
operator=()
void Sequence::operator= (const Sequence &) private
parse()
void Sequence::parse (Statement & statement) virtual
Parse sequence.
Reimplemented from Object.
Definition at line 190 of file Sequence.cpp.
References Attributes::getString(), Object::itsAttr, itsRefPoint, Object::parse(), and OpalParser::run().
parseShortcut()
void Object::parseShortcut (Statement & stat, bool eval = true) virtual inherited
Parser for single-attribute commands.
Definition at line 113 of file Object.cpp.
Referenced by Call::parse(), Echo::parse(), Help::parse(), PSystem::parse(), System::parse(), Title::parse(), and Value::parse().
print()
void Sequence::print (std::ostream & os) const virtual
Print sequence.
Reimplemented from Object.
Definition at line 200 of file Sequence.cpp.
References fetchLine(), SequenceMember::GENERATED, ElmPtr::getElement(), ElementBase::getName(), Object::getOpalName(), FlaggedElmPtr::getReflectionFlag(), Object::isShared(), Object::itsAttr, SequenceMember::itsPosition, and SequenceMember::itsType.
printHelp()
void Object::printHelp (std::ostream &) const virtual inherited
Print help.
Definition at line 179 of file Object.cpp.
References gmsg, Object::itsAttr, and Object::itsHelp.
Referenced by Help::execute().
printValue()
void Object::printValue (std::ostream & os) const inline virtual inherited
Reimplemented in BoolConstant, RealConstant, RealVariable, RealVector, and StringConstant.
Definition at line 270 of file Object.h.
References Object::print().
registerOwnership()
void Object::registerOwnership (const AttributeHandler::OwnerType & itsClass) const inherited
Definition at line 169 of file Object.cpp.
References AttributeHandler::addAttributeOwner(), Object::getOpalName(), Object::getParent(), and Object::itsAttr.
Referenced by Beam::Beam(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), Call::Call(), Distribution::Distribution(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), EmissionSourceList::EmissionSourceList(), Help::Help(), Line::Line(), OpalFilter::OpalFilter(), Option::Option(), PSystem::PSystem(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVector::RealVector(), Select::Select(), Sequence(), StringConstant::StringConstant(), System::System(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), and Value::Value().
registerReference()
void Object::registerReference (Invalidator * a) inherited
Register a reference to this object.
Definition at line 165 of file Object.cpp.
References Object::references.
replace()
void Sequence::replace (Object * oldObject, Object * newObject) virtual
Replace references to elements.
Reimplemented from Object.
Definition at line 238 of file Sequence.cpp.
References DefaultVisitor::execute(), fetchLine(), Element::getElement(), and Object::getOpalName().
setDirty()
void Object::setDirty (bool dirty) inherited
Set/reset the [b]modified[/b] flag.
Definition at line 249 of file Object.cpp.
References Object::modified.
Referenced by OpalData::define(), OpalData::makeDirty(), and RealVariable::RealVariable().
setElement() [1/2]
void Element::setElement (ElementBase * base) inline inherited
Assign new OPALX element.
Definition at line 123 of file Element.h.
References Element::itsOPALXElement.
Referenced by Line::Line(), Line::Line(), OpalCavity::OpalCavity(), OpalCavity::OpalCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalDrift::OpalDrift(), OpalDrift::OpalDrift(), OpalLaser::OpalLaser(), OpalLaser::OpalLaser(), OpalMarker::OpalMarker(), OpalMarker::OpalMarker(), OpalMonitor::OpalMonitor(), OpalMonitor::OpalMonitor(), OpalMultipole::OpalMultipole(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalMultipoleT::OpalMultipoleT(), OpalProbe::OpalProbe(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalQuadrupole::OpalQuadrupole(), OpalRBend::OpalRBend(), OpalRBend::OpalRBend(), OpalRingDefinition::OpalRingDefinition(), OpalRingDefinition::OpalRingDefinition(), OpalSBend::OpalSBend(), OpalSBend::OpalSBend(), OpalSolenoid::OpalSolenoid(), OpalSolenoid::OpalSolenoid(), OpalTravelingWave::OpalTravelingWave(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), Sequence(), Sequence(), and OpalVariableRFCavity::update().
setElement() [2/2]
void Element::setElement (std::shared_ptr< ElementBase > base) inline inherited
Definition at line 130 of file Element.h.
References Element::itsOPALXElement.
setFlag()
void Object::setFlag (bool flag) inherited
Flag/unflag this object, e. g. to control output of objects for.
Definition at line 256 of file Object.cpp.
References Object::flagged.
setOpalName()
void Object::setOpalName (const std::string & name) inherited
Set object name.
Definition at line 281 of file Object.cpp.
References Object::itsName.
Referenced by TEST(), TEST(), TEST(), Beam::update(), BoundaryGeometry::update(), and OpalFilter::update().
setParent()
void Object::setParent (Object * parent) inherited
Set parent object.
Definition at line 283 of file Object.cpp.
References Object::itsParent.
Referenced by OpalData::erase().
setShared()
void Element::setShared (bool flag) virtual inherited
Set shared flag.
Reimplemented from Object.
Definition at line 80 of file Element.cpp.
References Element::itsOPALXElement, and Object::setShared().
shouldTrace()
bool Element::shouldTrace () const virtual inherited
Trace flag.
Implements Object.
Definition at line 50 of file Element.cpp.
shouldUpdate()
bool Element::shouldUpdate () const virtual inherited
Update flag.
Implements Object.
Definition at line 52 of file Element.cpp.
storeLine()
void Sequence::storeLine (TLine & line)
Store sequence line.
Definition at line 255 of file Sequence.cpp.
References OpalData::apply(), fetchLine(), Element::find(), SequenceMember::GENERATED, OpalData::getInstance(), getReference(), Object::increment(), and itsCode.
Referenced by copy(), and SequenceParser::parse().
unregisterReference()
void Object::unregisterReference (Invalidator * a) inherited
Unegister a reference to this object.
Definition at line 167 of file Object.cpp.
References Object::references.
update()
void Sequence::update () virtual
Update the embedded OPALX beam line.
Reimplemented from Object.
Definition at line 248 of file Sequence.cpp.
References fetchLine(), and updateList().
updateList()
void Sequence::updateList (Sequence * seq, TLine * line) static private
Definition at line 350 of file Sequence.cpp.
References OpalData::find(), findDriftLength(), OpalData::getInstance(), ElementBase::getName(), ElementBase::isSharable(), and updateList().
Referenced by update(), and updateList().
Friends And Related Symbol Documentation
Edit
friend class Edit friend
Definition at line 34 of file Sequence.h.
SequenceParser
friend class SequenceParser friend
Definition at line 35 of file Sequence.h.
SequenceTemplate
friend class SequenceTemplate friend
Definition at line 36 of file Sequence.h.
Referenced by makeTemplate().
Member Data Documentation
builtin
bool Object::builtin protected inherited
Built-in flag.
Definition at line 226 of file Object.h.
Referenced by Beam::Beam(), BoundaryGeometry::BoundaryGeometry(), Object::isBuiltin(), Object::Object(), Object::Object(), OpalFilter::OpalFilter(), OpalMarker::OpalMarker(), RealConstant::RealConstant(), StringConstant::StringConstant(), and Table::~Table().
flagged
bool Object::flagged protected inherited
Object flag.
Definition at line 235 of file Object.h.
Referenced by Object::isFlagged(), Object::Object(), Object::Object(), and Object::setFlag().
itsAttr
std::vector<Attribute> Object::itsAttr inherited
The object attributes.
Definition at line 210 of file Object.h.
Referenced by Beam::Beam(), BinningCmd::BinningCmd(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), BoundaryGeometry::BoundaryGeometry(), DumpEMFields::buildGrid(), Call::Call(), FieldSolverCmd::constructBCHandler(), Object::copyAttributes(), Distribution::Distribution(), BinningCmd::dumpBinsToFile(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), Call::execute(), Echo::execute(), Help::execute(), Option::execute(), PSystem::execute(), Select::execute(), System::execute(), Title::execute(), Value::execute(), Beam::execute(), TrackCmd::execute(), TrackRun::execute(), FieldSolverCmd::FieldSolverCmd(), Object::findAttribute(), Object::findAttribute(), BoundaryGeometry::getA(), OpalElement::getApert(), BoundaryGeometry::getB(), BinningCmd::getBinningAlpha(), BinningCmd::getBinningBeta(), FieldSolverCmd::getBinsName(), BoolConstant::getBool(), FieldSolverCmd::getBoxIncr(), Beam::getBunchCharge(), BoundaryGeometry::getC(), Beam::getCharge(), Beam::getCurrent(), Beam::getDaughterBeamName(), BinningCmd::getDesiredWidth(), EmissionSource::getDistributionName(), FieldSolverCmd::getDomDec(), TrackCmd::getDT(), TrackCmd::getDTAU(), TrackCmd::getDTSCINIT(), BinningCmd::getDumpBinsFileName(), BinningCmd::getDumpBinsFrequency(), EmissionSource::getEmissionModel(), Beam::getEmissionSourceListName(), Distribution::getFilename(), BoundaryGeometry::getFilename(), Beam::getFrequency(), Beam::getGlobalProcessNames(), BoundaryGeometry::getL1(), BoundaryGeometry::getL2(), BoundaryGeometry::getLength(), OpalElement::getLength(), Line::getLength(), getLength(), Beam::getMass(), BinningCmd::getMaxBins(), TrackCmd::getMaxSteps(), Beam::getNumAlloc(), FieldSolverCmd::getNX(), FieldSolverCmd::getNY(), FieldSolverCmd::getNZ(), EmissionSource::getP0(), BinningCmd::getParameter(), Beam::getParticleName(), EmissionSource::getR0(), RealConstant::getReal(), RealVariable::getReal(), RealVector::getRealComponent(), getReference(), BoundaryGeometry::getS(), EmissionSource::getShiftedGreensFunction(), TrackCmd::getStepsPerTurn(), StringConstant::getString(), EmissionSource::getT0(), TrackCmd::getT0(), BinningCmd::getTablePrintFrequency(), TrackCmd::getTimeIntegrator(), BoundaryGeometry::getTopology(), FieldSolverCmd::getType(), EmissionSource::getZerofaceMaxSteps(), EmissionSource::getZeroFacePlaneDumpFrequency(), EmissionSource::getZeroFaceR0Z(), TrackCmd::getZStart(), TrackCmd::getZStop(), Beam::hasExplicitEnergy(), Help::Help(), BoundaryGeometry::initialize(), OpalFilter::initOpalFilter(), Beam::isPhoton(), Line::Line(), OpalBend::OpalBend(), OpalCavity::OpalCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalDrift::OpalDrift(), OpalElement::OpalElement(), OpalFilter::OpalFilter(), OpalLaser::OpalLaser(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalPolynomialTimeDependence::OpalPolynomialTimeDependence(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalRingDefinition::OpalRingDefinition(), OpalSinusoidalTimeDependence::OpalSinusoidalTimeDependence(), OpalSolenoid::OpalSolenoid(), OpalSplineTimeDependence::OpalSplineTimeDependence(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), Option::Option(), Option::Option(), parse(), Line::parse(), DumpEMFields::parseCoordinateSystem(), Object::print(), print(), BoolConstant::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), StringConstant::print(), Beam::print(), OpalFilter::print(), DumpEMFields::print(), Object::printHelp(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), BoolConstant::printValue(), RealConstant::printValue(), RealVariable::printValue(), RealVector::printValue(), StringConstant::printValue(), PSystem::PSystem(), RealConstant::RealConstant(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVariable::RealVariable(), RealVector::RealVector(), OpalElement::registerOwnership(), Object::registerOwnership(), Select::Select(), Select::select(), Sequence(), Distribution::setAttributes(), TestMultipoleT::TestableFieldSolverCmd::setBCX(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCX(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCX(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCX(), TestVariableRFCavity::TestableFieldSolverCmd::setBCX(), OrbitThreaderTest::TestableFieldSolverCmd::setBCX(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCX(), TestMultipoleT::TestableFieldSolverCmd::setBCY(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCY(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCY(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCY(), TestVariableRFCavity::TestableFieldSolverCmd::setBCY(), OrbitThreaderTest::TestableFieldSolverCmd::setBCY(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCY(), TestMultipoleT::TestableFieldSolverCmd::setBCZ(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCZ(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCZ(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCZ(), TestVariableRFCavity::TestableFieldSolverCmd::setBCZ(), OrbitThreaderTest::TestableFieldSolverCmd::setBCZ(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCZ(), TestableBinningCmd::setBinningAlpha(), TestableBinningCmd::setBinningBeta(), TestableBinningCmd::setDesiredWidth(), Distribution::setDistParametersFlatTop(), Distribution::setDistParametersMultiVariateGauss(), Distribution::setDistType(), TestableBinningCmd::setDumpBinsFile(), TestableBinningCmd::setDumpBinsFreq(), TestableBinningCmd::setMaxBins(), FieldSolverCmd::setNX(), FieldSolverCmd::setNY(), FieldSolverCmd::setNZ(), TestableBinningCmd::setParameterString(), TrackRun::setRunMethod(), Distribution::setSigmaP_m(), Distribution::setSigmaR_m(), TestableBinningCmd::setTablePrintFrequency(), TestMultipoleT::TestableFieldSolverCmd::setType(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setType(), TestMultipoleTStraight::TestableFieldSolverCmd::setType(), SolenoidPlacementTest::TestableFieldSolverCmd::setType(), TestVariableRFCavity::TestableFieldSolverCmd::setType(), OrbitThreaderTest::TestableFieldSolverCmd::setType(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setType(), TrackRun::setupBoundaryGeometry(), StringConstant::StringConstant(), StringConstant::StringConstant(), System::System(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), OpalCavity::update(), OpalConstantEFieldCavity::update(), OpalDrift::update(), OpalElement::update(), OpalMonitor::update(), OpalMultipole::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalRBend::update(), OpalRingDefinition::update(), OpalSBend::update(), OpalSolenoid::update(), OpalTravelingWave::update(), OpalVacuum::update(), OpalVerticalFFAMagnet::update(), Beam::update(), BinningCmd::update(), FieldSolverCmd::update(), OpalLaser::update(), OpalMultipoleT::update(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), OpalSplineTimeDependence::update(), OpalVariableRFCavity::update(), Option::update(), OpalElement::updateUnknown(), ValueDefinition::value(), Value::Value(), and ValueDefinition::value().
itsCode
ReferenceType Sequence::itsCode private
Definition at line 121 of file Sequence.h.
Referenced by findDriftLength(), and storeLine().
itsHelp
std::string Object::itsHelp private inherited
Definition at line 250 of file Object.h.
Referenced by Object::printHelp().
itsName
std::string Object::itsName private inherited
Definition at line 247 of file Object.h.
Referenced by Object::getOpalName(), and Object::setOpalName().
itsOPALXElement
std::shared_ptr<ElementBase> Element::itsOPALXElement private inherited
Definition at line 113 of file Element.h.
Referenced by Element::getElement(), Element::getElementPtr(), Element::setElement(), Element::setElement(), and Element::setShared().
itsParent
Object* Object::itsParent private inherited
Definition at line 244 of file Object.h.
Referenced by Object::getBaseObject(), Object::getParent(), Object::isTreeMember(), and Object::setParent().
itsRefPoint
std::string Sequence::itsRefPoint private
Definition at line 124 of file Sequence.h.
Referenced by getEntrance(), getExit(), and parse().
modified
bool Object::modified protected inherited
Dirty flag.
Definition at line 231 of file Object.h.
Referenced by Object::isDirty(), Object::Object(), Object::Object(), and Object::setDirty().
occurrence
int Object::occurrence private inherited
Definition at line 253 of file Object.h.
Referenced by Object::clear(), Object::increment(), and Object::occurrenceCount().
references
std::set<Invalidator*> Object::references private inherited
Definition at line 260 of file Object.h.
Referenced by Object::registerReference(), Object::unregisterReference(), and Object::~Object().
sharedFlag
bool Object::sharedFlag private inherited
Definition at line 263 of file Object.h.
Referenced by Object::isShared(), and Object::setShared().
timeStamp
double Object::timeStamp private inherited
Definition at line 256 of file Object.h.
The documentation for this class was generated from the following files:
Sequence.h
Sequence.cpp