OPALX (Object Oriented Parallel Accelerator Library for Exascal): LossDataSink Class Reference
LossDataSink Class Reference
#include <LossDataSink.h>
Public Member Functions
LossDataSink ()=default
LossDataSink (std::string outfn, bool hdf5Save, CollectionType=CollectionType::TEMPORAL)
LossDataSink (const LossDataSink &rsh)
~LossDataSink () noexcept(false)
bool inH5Mode ()
void save (unsigned int numSets=1, OpalData::OpenMode openMode=OpalData::OpenMode::UNDEFINED)
void addReferenceParticle (const Vector_t< double, 3 > &x, const Vector_t< double, 3 > &p, double time, double spos, long long globalTrackStep)
void addParticle (const OpalParticle &, const std::optional< std::pair< int, short int > > &turnBunchNumPair=std::nullopt)
size_t size () const
std::set< SetStatistics > computeStatistics (unsigned int numSets)
Private Member Functions
void openASCII ()
void openH5 (h5_int32_t mode=H5_O_WRONLY)
void appendASCII ()
void writeHeaderASCII ()
void writeHeaderH5 ()
void saveASCII ()
void saveH5 (unsigned int setIdx)
void closeASCII ()
bool hasNoParticlesToDump () const
bool hasTurnInformations () const
void reportOnError (h5_int64_t rc, const char *file, int line)
void splitSets (unsigned int numSets)
SetStatistics computeSetStatistics (unsigned int setIdx)
Private Attributes
std::string fileName_m
bool h5hut_mode_m
std::ofstream os_m
h5_file_t H5file_m
used to write out data in H5hut mode
std::string outputName_m
h5_int64_t H5call_m
Current record, or time step, of H5 file.
std::vector< OpalParticle > particles_m
std::vector< size_t > bunchNumber_m
std::vector< size_t > turnNumber_m
std::vector< Vector_t< double, 3 > > RefPartR_m
std::vector< Vector_t< double, 3 > > RefPartP_m
std::vector< h5_int64_t > globalTrackStep_m
std::vector< double > refTime_m
std::vector< double > spos_m
std::vector< unsigned long > startSet_m
CollectionType collectionType_m
Detailed Description
Definition at line 76 of file LossDataSink.h.
Constructor & Destructor Documentation
LossDataSink() [1/3]
LossDataSink::LossDataSink () default
References LossDataSink(), and TEMPORAL.
Referenced by LossDataSink(), and LossDataSink().
LossDataSink() [2/3]
LossDataSink::LossDataSink (std::string outfn, bool hdf5Save, CollectionType collectionType = CollectionType::TEMPORAL)
Definition at line 177 of file LossDataSink.cpp.
References OpalData::APPEND, bunchNumber_m, OpalData::checkAndAddOutputFileName(), collectionType_m, Options::enableHDF5, OpalData::getInstance(), H5call_m, H5file_m, h5hut_mode_m, outputName_m, particles_m, OpalData::setOpenMode(), and turnNumber_m.
LossDataSink() [3/3]
LossDataSink::LossDataSink (const LossDataSink & rsh)
Definition at line 201 of file LossDataSink.cpp.
References bunchNumber_m, collectionType_m, globalTrackStep_m, H5call_m, H5file_m, h5hut_mode_m, LossDataSink(), outputName_m, particles_m, RefPartP_m, RefPartR_m, refTime_m, spos_m, and turnNumber_m.
~LossDataSink()
LossDataSink::~LossDataSink ()
Definition at line 217 of file LossDataSink.cpp.
References CLOSE_FILE, and H5file_m.
Member Function Documentation
addParticle()
void LossDataSink::addParticle (const OpalParticle & , const std::optional< std::pair< int, short int > > & turnBunchNumPair = std::nullopt)
Definition at line 313 of file LossDataSink.cpp.
References bunchNumber_m, particles_m, and turnNumber_m.
addReferenceParticle()
void LossDataSink::addReferenceParticle (const Vector_t< double, 3 > & x, const Vector_t< double, 3 > & p, double time, double spos, long long globalTrackStep)
Definition at line 303 of file LossDataSink.cpp.
References globalTrackStep_m, RefPartP_m, RefPartR_m, refTime_m, and spos_m.
appendASCII()
void LossDataSink::appendASCII () inline private
Definition at line 110 of file LossDataSink.h.
References fileName_m, and os_m.
Referenced by save().
closeASCII()
void LossDataSink::closeASCII () inline private
Definition at line 122 of file LossDataSink.h.
References os_m.
Referenced by save().
computeSetStatistics()
SetStatistics LossDataSink::computeSetStatistics (unsigned int setIdx) private
Definition at line 700 of file LossDataSink.cpp.
References SetStatistics::eps2_m, SetStatistics::eps_norm_m, SetStatistics::fac_m, OpalParticle::getPx(), OpalParticle::getPy(), OpalParticle::getPz(), OpalParticle::getTime(), OpalParticle::getX(), OpalParticle::getY(), OpalParticle::getZ(), SetStatistics::nTotal_m, outputName_m, SetStatistics::outputName_m, particles_m, SetStatistics::pmean_m, SetStatistics::prms_m, SetStatistics::psqsum_m, RefPartP_m, SetStatistics::RefPartP_m, RefPartR_m, SetStatistics::RefPartR_m, refTime_m, SetStatistics::refTime_m, SetStatistics::rmax_m, SetStatistics::rmean_m, SetStatistics::rmin_m, SetStatistics::rprms_m, SetStatistics::rpsum_m, SetStatistics::rrms_m, SetStatistics::rsqsum_m, spos_m, SetStatistics::spos_m, startSet_m, Util::KahanAccumulation::sum, SetStatistics::tmean_m, and SetStatistics::trms_m.
Referenced by computeStatistics().
computeStatistics()
std::set< SetStatistics > LossDataSink::computeStatistics (unsigned int numSets) inline
Definition at line 170 of file LossDataSink.h.
References computeSetStatistics(), and splitSets().
hasNoParticlesToDump()
bool LossDataSink::hasNoParticlesToDump () const private
Definition at line 385 of file LossDataSink.cpp.
References particles_m.
Referenced by save().
hasTurnInformations()
bool LossDataSink::hasTurnInformations () const private
Definition at line 391 of file LossDataSink.cpp.
References turnNumber_m.
Referenced by saveH5(), and writeHeaderASCII().
inH5Mode()
bool LossDataSink::inH5Mode () inline
Definition at line 85 of file LossDataSink.h.
References h5hut_mode_m, and inH5Mode().
Referenced by inH5Mode().
openASCII()
void LossDataSink::openASCII () inline private
Definition at line 103 of file LossDataSink.h.
References fileName_m, and os_m.
Referenced by save().
openH5()
void LossDataSink::openH5 (h5_int32_t mode = H5_O_WRONLY) private
Definition at line 225 of file LossDataSink.cpp.
References fileName_m, and OPEN_FILE.
Referenced by save().
reportOnError()
void LossDataSink::reportOnError (h5_int64_t rc, const char * file, int line) private
save()
void LossDataSink::save (unsigned int numSets = 1, OpalData::OpenMode openMode = OpalData::OpenMode::UNDEFINED)
Definition at line 329 of file LossDataSink.cpp.
References appendASCII(), bunchNumber_m, CLOSE_FILE, closeASCII(), fileName_m, GET_NUM_STEPS, OpalData::getInstance(), OpalData::getOpenMode(), globalTrackStep_m, gmsg, H5file_m, h5hut_mode_m, hasNoParticlesToDump(), openASCII(), openH5(), outputName_m, particles_m, RefPartP_m, RefPartR_m, refTime_m, saveASCII(), saveH5(), spos_m, turnNumber_m, OpalData::UNDEFINED, OpalData::WRITE, writeHeaderASCII(), and writeHeaderH5().
saveASCII()
void LossDataSink::saveASCII () private
Definition at line 539 of file LossDataSink.cpp.
Referenced by save().
saveH5()
void LossDataSink::saveH5 (unsigned int setIdx) private
Set current record/time step.
Definition at line 399 of file LossDataSink.cpp.
References bunchNumber_m, DistributionMoments::compute(), Options::computePercentiles, DistributionMoments::get68Percentile(), DistributionMoments::get95Percentile(), DistributionMoments::get99_99Percentile(), DistributionMoments::get99Percentile(), OpalParticle::getCharge(), DistributionMoments::getGeometricEmittance(), OpalParticle::getId(), OpalParticle::getMass(), DistributionMoments::getMaxR(), DistributionMoments::getMeanKineticEnergy(), DistributionMoments::getMeanMomentum(), DistributionMoments::getMeanPosition(), DistributionMoments::getMeanTime(), DistributionMoments::getNormalizedEmittance(), DistributionMoments::getNormalizedEmittance68Percentile(), DistributionMoments::getNormalizedEmittance95Percentile(), DistributionMoments::getNormalizedEmittance99_99Percentile(), DistributionMoments::getNormalizedEmittance99Percentile(), OpalParticle::getPx(), OpalParticle::getPy(), OpalParticle::getPz(), DistributionMoments::getStandardDeviationMomentum(), DistributionMoments::getStandardDeviationPosition(), DistributionMoments::getStdKineticEnergy(), DistributionMoments::getStdTime(), OpalParticle::getTime(), DistributionMoments::getTotalCharge(), DistributionMoments::getTotalMass(), OpalParticle::getX(), OpalParticle::getY(), OpalParticle::getZ(), globalTrackStep_m, H5call_m, hasTurnInformations(), particles_m, RefPartP_m, RefPartR_m, refTime_m, SET_NUM_PARTICLES, SET_STEP, size(), spos_m, startSet_m, turnNumber_m, WRITE_DATA_FLOAT64, WRITE_DATA_INT64, WRITE_STEPATTRIB_FLOAT64, and WRITE_STEPATTRIB_INT64.
Referenced by save().
size()
size_t LossDataSink::size () const inline
Definition at line 168 of file LossDataSink.h.
References particles_m.
Referenced by saveH5().
splitSets()
void LossDataSink::splitSets (unsigned int numSets) private
In Opal-T monitors can be traversed several times. We know how many times the bunch passes because we register the passage of the reference particle. This code tries to determine to which bunch (same bunch but different times) a particle belongs. For this we could use algorithms from data science such as k-means or dbscan. But they are an overkill for this application because the bunches are well separated.
In a first step we a assign to each bunch the same number of particles and compute the mean time of passage and with it a time range. Of course this is only an approximation. So we reassign the particles to the bunches using the time ranges compute a better approximation. Two iterations should be sufficient for Opal-T where the temporal separation is large.
Parameters
numSets number of passes of the reference particle
Definition at line 642 of file LossDataSink.cpp.
References particles_m, and startSet_m.
Referenced by computeStatistics().
writeHeaderASCII()
void LossDataSink::writeHeaderASCII () private
Definition at line 292 of file LossDataSink.cpp.
References hasTurnInformations(), and os_m.
Referenced by save().
writeHeaderH5()
void LossDataSink::writeHeaderH5 () private
Definition at line 233 of file LossDataSink.cpp.
References collectionType_m, Options::computePercentiles, Util::getGitRevision(), TEMPORAL, and WRITE_FILEATTRIB_STRING.
Referenced by save().
Member Data Documentation
bunchNumber_m
std::vector<size_t> LossDataSink::bunchNumber_m private
Definition at line 154 of file LossDataSink.h.
Referenced by addParticle(), LossDataSink(), LossDataSink(), save(), and saveH5().
collectionType_m
CollectionType LossDataSink::collectionType_m private
Definition at line 165 of file LossDataSink.h.
Referenced by LossDataSink(), LossDataSink(), and writeHeaderH5().
fileName_m
std::string LossDataSink::fileName_m private
Definition at line 137 of file LossDataSink.h.
Referenced by appendASCII(), openASCII(), openH5(), and save().
globalTrackStep_m
std::vector<h5_int64_t> LossDataSink::globalTrackStep_m private
Definition at line 159 of file LossDataSink.h.
Referenced by addReferenceParticle(), LossDataSink(), save(), and saveH5().
H5call_m
h5_int64_t LossDataSink::H5call_m private
Current record, or time step, of H5 file.
Definition at line 151 of file LossDataSink.h.
Referenced by LossDataSink(), LossDataSink(), and saveH5().
H5file_m
h5_file_t LossDataSink::H5file_m private
used to write out data in H5hut mode
Definition at line 146 of file LossDataSink.h.
Referenced by LossDataSink(), LossDataSink(), save(), and ~LossDataSink().
h5hut_mode_m
bool LossDataSink::h5hut_mode_m private
Definition at line 140 of file LossDataSink.h.
Referenced by inH5Mode(), LossDataSink(), LossDataSink(), and save().
os_m
std::ofstream LossDataSink::os_m private
Definition at line 143 of file LossDataSink.h.
Referenced by appendASCII(), closeASCII(), openASCII(), and writeHeaderASCII().
outputName_m
std::string LossDataSink::outputName_m private
Definition at line 148 of file LossDataSink.h.
Referenced by computeSetStatistics(), LossDataSink(), LossDataSink(), and save().
particles_m
std::vector<OpalParticle> LossDataSink::particles_m private
Definition at line 153 of file LossDataSink.h.
Referenced by addParticle(), computeSetStatistics(), hasNoParticlesToDump(), LossDataSink(), LossDataSink(), save(), saveH5(), size(), and splitSets().
RefPartP_m
std::vector<Vector_t<double, 3> > LossDataSink::RefPartP_m private
Definition at line 158 of file LossDataSink.h.
Referenced by addReferenceParticle(), computeSetStatistics(), LossDataSink(), save(), and saveH5().
RefPartR_m
std::vector<Vector_t<double, 3> > LossDataSink::RefPartR_m private
Definition at line 157 of file LossDataSink.h.
Referenced by addReferenceParticle(), computeSetStatistics(), LossDataSink(), save(), and saveH5().
refTime_m
std::vector<double> LossDataSink::refTime_m private
Definition at line 160 of file LossDataSink.h.
Referenced by addReferenceParticle(), computeSetStatistics(), LossDataSink(), save(), and saveH5().
spos_m
std::vector<double> LossDataSink::spos_m private
Definition at line 161 of file LossDataSink.h.
Referenced by addReferenceParticle(), computeSetStatistics(), LossDataSink(), save(), and saveH5().
startSet_m
std::vector<unsigned long> LossDataSink::startSet_m private
Definition at line 163 of file LossDataSink.h.
Referenced by computeSetStatistics(), saveH5(), and splitSets().
turnNumber_m
std::vector<size_t> LossDataSink::turnNumber_m private
Definition at line 155 of file LossDataSink.h.
Referenced by addParticle(), hasTurnInformations(), LossDataSink(), LossDataSink(), save(), and saveH5().
The documentation for this class was generated from the following files:
LossDataSink.h
LossDataSink.cpp