OPALX (Object Oriented Parallel Accelerator Library for Exascal): ParticleContainer< T, Dim > Class Template Reference
ParticleContainer< T, Dim > Class Template Reference
Container for all per-particle (and per-simulation) fields tracked during OPALX tracking.
#include <ParticleContainer.hpp>
Inherits ippl::ParticleBase< ippl::ParticleSpatialLayout< T, 3 >, Kokkos::DefaultExecutionSpace::memory_space >.
Public Types
enum class QMStorageMode { SingleValue , Attributes }
using bin_index_type = short int
Defines which type to use as a particle bin.
using qm_view_type = typename ippl::ParticleAttrib< double >::view_type
View types of Q and M values.
Public Member Functions
qm_view_type getQView () const
qm_view_type getMView () const
ParticleContainer (Mesh_t< Dim > &mesh, FieldLayout_t< Dim > &FL)
~ParticleContainer ()
void registerAttributes ()
void setupBCs ()
void transformBunch (const CoordinateSystemTrafo &trafo)
Apply coordinate transform to local particles: translate R, rotate P, E, B.
PLayout_t< T, Dim > & getPL ()
void setBunchStateHandler (std::shared_ptr< BunchStateHandler > handler)
bool isUnitlessPositions () const
bool isMomentsDirty () const
void markMomentsDirty ()
void markMomentsClean ()
void updateMoments ()
void setEnergyReferenceMass (double referenceMassGeV, bool rescaleToReference=true)
Vector_t< double, 3 > getMeanP () const
Vector_t< double, 3 > getRmsP () const
Vector_t< double, 3 > getMeanR () const
Vector_t< double, 3 > getRmsR () const
Vector_t< double, 3 > getRmsRP () const
void computeMinMaxR ()
Vector_t< double, 3 > getMinR () const
Vector_t< double, 3 > getMaxR () const
matrix6x6_t getCovMatrix () const
double getMeanKineticEnergy () const
double getStdKineticEnergy () const
Vector_t< double, 6 > getMeans () const
Vector_t< double, 6 > getCentroid () const
Vector_t< double, 3 > getNormEmit () const
Vector_t< double, 3 > getGeometricEmit () const
double getDx () const
double getDDx () const
double getDy () const
double getDDy () const
double getDebyeLength () const
double getMeanGammaZ () const
double getTemperature () const
double getPlasmaParameter () const
double computeDebyeLength (double density)
void setQ (double q)
Set particle charge for the active Q storage mode.
double getChargePerParticle () const
Get charge per particle [Cb].
double getTotalCharge () const
Get total charge [Cb] in this container.
void setM (double m)
Set particle mass for the active M storage mode.
double getMassPerParticle () const
Get mass per particle [GeV].
double getTotalMass () const
Get total mass [GeV] in this container.
const Vector_t< double, Dim > & getRefPartR () const
Get the reference particle position (const).
Vector_t< double, Dim > & getRefPartR ()
Get the reference particle position.
void setRefPartR (const Vector_t< double, Dim > &refPartR)
Set the reference particle position.
const Vector_t< double, Dim > & getRefPartP () const
Get the reference particle momentum (const).
Vector_t< double, Dim > & getRefPartP ()
Get the reference particle momentum.
void setRefPartP (const Vector_t< double, Dim > &refPartP)
Set the reference particle momentum.
void setReference (const PartData *ref)
Set reference particle data.
const PartData * getReference () const
Get reference particle data.
void set_sPos (double sPos)
Set longitudinal position along design trajectory.
double get_sPos () const
Get longitudinal position along design trajectory.
void setGlobalToLocalQuaternion (const Quaternion_t &globalToLocalQuaternion)
Set global-to-local rotation quaternion.
Quaternion_t getGlobalToLocalQuaternion () const
Get global-to-local rotation quaternion.
const CoordinateSystemTrafo & getToLabTrafo () const
Get local-to-lab coordinate transformation (const).
CoordinateSystemTrafo & getToLabTrafo ()
Get local-to-lab coordinate transformation.
void setToLabTrafo (const CoordinateSystemTrafo &toLabTrafo)
Set local-to-lab coordinate transformation.
void updateRefToLabCSTrafo (double bunchDT)
Advance reference/lab transform state and map bunch accordingly.
template<typename Pusher >
void applyFractionalStep (const Pusher &pusher, double tau, double pathLengthTarget)
Apply a fractional Boris step and update reference/lab transform state.
void scaleDtByCharge ()
Scale particle time-step weights by charge before scatter.
void unscaleDtByCharge ()
Restore original dt values after scaleDtByCharge().
void switchToUnitlessPositions ()
Transform positions to unitless coordinates using each particle's dt[i].
void switchOffUnitlessPositions ()
Restore physical positions from unitless form using each particle's dt[i].
QMStorageMode getQMStorageMode () const
void setGlobalProcesses (std::vector< std::unique_ptr< GlobalProcess > > processes)
const std::vector< std::unique_ptr< GlobalProcess > > & getGlobalProcesses () const
size_type deleteParticlesOutside (double sigmasAway)
Delete particles whose position is more than sigmasAway standard deviations from the bunch mean in any spatial dimension.
void createParticles (size_type numParticles)
Create/allocate a specified number of particles.
void allocateParticles (size_type numParticles)
template<typename... Properties>
void destroyParticles (const Kokkos::View< bool *, Properties... > &invalid, size_type localDestroyNum)
Destroy the particles marked invalid in this container.
Public Attributes
ippl::ParticleAttrib< double > dt
timestep in [s]
ippl::ParticleAttrib< double > Phi
the scalar potential in [Cb/s]
ippl::ParticleAttrib< bin_index_type > Bin
the energy bin the particle is in
short Sp = 0
the particle specis
Base::particle_position_type P
particle momenta [\beta\gamma]
Base::particle_position_type E
electric field at particle position
Base::particle_position_type B
electric field for gun simulation with bins
ippl::ParticleAttrib< bool > InvalidMask
particle deletion mask (indicates which particles are deleted every timestep)
Private Types
using Base = ippl::ParticleBase< ippl::ParticleSpatialLayout< T, Dim >, Kokkos::DefaultExecutionSpace::memory_space >
Alias for the ippl::ParticleBase specialization this container inherits from.
Private Member Functions
void setBCAllPeriodic ()
Private Attributes
PLayout_t< T, Dim > pl_m
QMStorageMode qmStorageMode_m = QMStorageMode::SingleValue
DistributionMoments distMoments_m
std::shared_ptr< BunchStateHandler::ContainerState > containerState_m
qm_view_type QView_m
qm_view_type MView_m
ippl::ParticleAttrib< double > QAttr
ippl::ParticleAttrib< double > MAttr
Vector_t< double, Dim > refPartR_m
Vector_t< double, Dim > refPartP_m
Quaternion_t globalToLocalQuaternion_m
CoordinateSystemTrafo toLabTrafo_m
const PartData * reference_m = nullptr
double sPos_m = 0.0
std::vector< std::unique_ptr< GlobalProcess > > globalProcesses_m
Global physics processes attached to this container.
Detailed Description
template<typename T, unsigned Dim = 3>
class ParticleContainer< T, Dim >
Container for all per-particle (and per-simulation) fields tracked during OPALX tracking.
The values tracked in Kokkos::Views during the simulation are: R - Position (from base class) P - Momentum [beta*gamma] dt - Time step Phi- Scalar potential Bin- Energy bin E - Electric field B - Magnetic field
Charge (Q) and mass (M):
Default: QM_MODE="SINGLE" -> QMStorageMode=SingleValue
Q and M are stored as a single shared value per container (memory-efficient).
Access via getQView() / getMView() returns the shared views.
Alternative: QM_MODE="ATTRIBUTES" -> QMStorageMode=Attributes
Q and M are stored as per-particle attributes.
Access via getQView() / getMView() returns the per-particle attribute views.
Access to Q/M should be done with getQView() / getMView(). They automatically select the correct underlying storage mode.
Definition at line 60 of file ParticleContainer.hpp.
Member Typedef Documentation
Base
template<typename T , unsigned Dim = 3> using ParticleContainer< T, Dim >::Base = ippl::ParticleBase< ippl::ParticleSpatialLayout<T, Dim>, Kokkos::DefaultExecutionSpace::memory_space> private
Alias for the ippl::ParticleBase specialization this container inherits from.
The second template argument is a parameter pack of Kokkos view properties forwarded to the optional ID attribute's storage. IPPL gates the ID attribute on sizeof...(IDProperties) > 0, so passing any property here turns IDs ON; an empty pack would leave them disabled. We pass Kokkos::DefaultExecutionSpace::memory_space so the ID view lives in the same space as the rest of the bunch (host or device, matching the build backend). With IDs enabled, IPPL auto-assigns globally unique std::int64_t IDs in Base::create().
Definition at line 74 of file ParticleContainer.hpp.
bin_index_type
template<typename T , unsigned Dim = 3> using ParticleContainer< T, Dim >::bin_index_type = short int
Defines which type to use as a particle bin.
Definition at line 91 of file ParticleContainer.hpp.
qm_view_type
template<typename T , unsigned Dim = 3> using ParticleContainer< T, Dim >::qm_view_type = typename ippl::ParticleAttrib<double>::view_type
View types of Q and M values.
Definition at line 94 of file ParticleContainer.hpp.
Member Enumeration Documentation
QMStorageMode
template<typename T , unsigned Dim = 3> enum class ParticleContainer::QMStorageMode strong
Enumerator
SingleValue
Attributes
Definition at line 88 of file ParticleContainer.hpp.
Constructor & Destructor Documentation
ParticleContainer()
template<typename T , unsigned Dim = 3> ParticleContainer< T, Dim >::ParticleContainer (Mesh_t< Dim > & mesh, FieldLayout_t< Dim > & FL) inline
Definition at line 144 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::MView_m, ParticleContainer< T, Dim >::pl_m, ParticleContainer< T, Dim >::QView_m, ParticleContainer< T, Dim >::registerAttributes(), and ParticleContainer< T, Dim >::setupBCs().
~ParticleContainer()
template<typename T , unsigned Dim = 3> ParticleContainer< T, Dim >::~ParticleContainer () inline
Definition at line 159 of file ParticleContainer.hpp.
Member Function Documentation
allocateParticles()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::allocateParticles (size_type numParticles) inline
Definition at line 669 of file ParticleContainer.hpp.
applyFractionalStep()
template<typename T , unsigned Dim = 3> template<typename Pusher > void ParticleContainer< T, Dim >::applyFractionalStep (const Pusher & pusher, double tau, double pathLengthTarget) inline
Apply a fractional Boris step and update reference/lab transform state.
Definition at line 441 of file ParticleContainer.hpp.
References Physics::c, getQuaternion(), CoordinateSystemTrafo::inverted(), ParticleContainer< T, Dim >::P, ParticleContainer< T, Dim >::refPartP_m, ParticleContainer< T, Dim >::refPartR_m, CoordinateSystemTrafo::rotateFrom(), ParticleContainer< T, Dim >::sPos_m, ParticleContainer< T, Dim >::toLabTrafo_m, and CoordinateSystemTrafo::transformFrom().
computeDebyeLength()
template<typename T , unsigned Dim = 3> double ParticleContainer< T, Dim >::computeDebyeLength (double density) inline
Definition at line 280 of file ParticleContainer.hpp.
References DistributionMoments::computeDebyeLength(), ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getDebyeLength().
computeMinMaxR()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::computeMinMaxR () inline
Definition at line 241 of file ParticleContainer.hpp.
References DistributionMoments::computeMinMaxPosition(), and ParticleContainer< T, Dim >::distMoments_m.
createParticles()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::createParticles (size_type numParticles) inline
Create/allocate a specified number of particles.
This function creates a given number of particles in the container. It's a wrapper around the non destructive IPPL particle create function, but will print out a warning if the create call led to unnecessary reallocation (i.e. if the new total number of particles exceeds the previous capacity).
Note
The underlying create is a collective call, so all MPI ranks must call this function. IPPL automatically handles the short-circuit if internal capacity is sufficient.
Parameters
numParticles The number of particles to create.
Definition at line 644 of file ParticleContainer.hpp.
deleteParticlesOutside()
template<typename T , unsigned Dim = 3> size_type ParticleContainer< T, Dim >::deleteParticlesOutside (double sigmasAway) inline
Delete particles whose position is more than sigmasAway standard deviations from the bunch mean in any spatial dimension.
Recomputes distribution moments, marks all particles outside the [mean - sigmasAway*sigma, mean + sigmasAway*sigma] hyper-rectangle as invalid, then calls the IPPL ParticleBase::destroy to compact the particle arrays.
Parameters
sigmasAway Number of standard deviations defining the boundary.
Returns
Global number of particles destroyed (across all MPI ranks).
Definition at line 579 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::destroyParticles(), ParticleContainer< T, Dim >::getMeanR(), ParticleContainer< T, Dim >::getRmsR(), ParticleContainer< T, Dim >::markMomentsDirty(), and ParticleContainer< T, Dim >::updateMoments().
destroyParticles()
template<typename T , unsigned Dim = 3> template<typename... Properties> void ParticleContainer< T, Dim >::destroyParticles (const Kokkos::View< bool *, Properties... > & invalid, size_type localDestroyNum) inline
Destroy the particles marked invalid in this container.
Wraps ippl::ParticleBase::destroy with input validation: throws if localDestroyNum exceeds the local particle count, or if the invalid mask is smaller than the local particle count. The underlying call is collective (allreduce of localNum_m) so all MPI ranks must call this function, even with localDestroyNum == 0.
Note
Does NOT mark moments dirty automatically. Callers that depend on moment freshness must call markMomentsDirty() themselves.
Template Parameters
Properties Kokkos view properties of the invalid mask.
Parameters
invalid Boolean mask of length >= getLocalNum(); true entries are removed.
localDestroyNum Number of true entries in invalid on this rank.
Definition at line 707 of file ParticleContainer.hpp.
Referenced by Decay::apply(), and ParticleContainer< T, Dim >::deleteParticlesOutside().
get_sPos()
template<typename T , unsigned Dim = 3> double ParticleContainer< T, Dim >::get_sPos () const inline
Get longitudinal position along design trajectory.
Definition at line 406 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::sPos_m.
getCentroid()
template<typename T , unsigned Dim = 3> Vector_t< double, 6 > ParticleContainer< T, Dim >::getCentroid () const inline
Definition at line 258 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getCentroid().
getChargePerParticle()
template<typename T , unsigned Dim = 3> double ParticleContainer< T, Dim >::getChargePerParticle () const inline
Get charge per particle [Cb].
Definition at line 314 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::Attributes, ParticleContainer< T, Dim >::QAttr, ParticleContainer< T, Dim >::qmStorageMode_m, and ParticleContainer< T, Dim >::QView_m.
Referenced by ParticleContainer< T, Dim >::getTotalCharge().
getCovMatrix()
template<typename T , unsigned Dim = 3> matrix6x6_t ParticleContainer< T, Dim >::getCovMatrix () const inline
Definition at line 250 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getMoments6x6().
getDDx()
template<typename T , unsigned Dim = 3> double ParticleContainer< T, Dim >::getDDx () const inline
Definition at line 266 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getDDx().
getDDy()
template<typename T , unsigned Dim = 3> double ParticleContainer< T, Dim >::getDDy () const inline
Definition at line 270 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getDDy().
getDebyeLength()
template<typename T , unsigned Dim = 3> double ParticleContainer< T, Dim >::getDebyeLength () const inline
Definition at line 272 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getDebyeLength().
getDx()
template<typename T , unsigned Dim = 3> double ParticleContainer< T, Dim >::getDx () const inline
Definition at line 264 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getDx().
getDy()
template<typename T , unsigned Dim = 3> double ParticleContainer< T, Dim >::getDy () const inline
Definition at line 268 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getDy().
getGeometricEmit()
template<typename T , unsigned Dim = 3> Vector_t< double, 3 > ParticleContainer< T, Dim >::getGeometricEmit () const inline
Definition at line 262 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getGeometricEmittance().
getGlobalProcesses()
template<typename T , unsigned Dim = 3> const std::vector< std::unique_ptr< GlobalProcess > > & ParticleContainer< T, Dim >::getGlobalProcesses () const inline
Definition at line 563 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::globalProcesses_m.
getGlobalToLocalQuaternion()
template<typename T , unsigned Dim = 3> Quaternion_t ParticleContainer< T, Dim >::getGlobalToLocalQuaternion () const inline
Get global-to-local rotation quaternion.
Definition at line 414 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::globalToLocalQuaternion_m.
getMassPerParticle()
template<typename T , unsigned Dim = 3> double ParticleContainer< T, Dim >::getMassPerParticle () const inline
Get mass per particle [GeV].
Definition at line 354 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::Attributes, ParticleContainer< T, Dim >::MAttr, ParticleContainer< T, Dim >::MView_m, and ParticleContainer< T, Dim >::qmStorageMode_m.
Referenced by ParticleContainer< T, Dim >::getTotalMass().
getMaxR()
template<typename T , unsigned Dim = 3> Vector_t< double, 3 > ParticleContainer< T, Dim >::getMaxR () const inline
Definition at line 248 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getMaxPosition().
getMeanGammaZ()
template<typename T , unsigned Dim = 3> double ParticleContainer< T, Dim >::getMeanGammaZ () const inline
Definition at line 274 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getMeanGammaZ().
getMeanKineticEnergy()
template<typename T , unsigned Dim = 3> double ParticleContainer< T, Dim >::getMeanKineticEnergy () const inline
Definition at line 252 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getMeanKineticEnergy().
getMeanP()
template<typename T , unsigned Dim = 3> Vector_t< double, 3 > ParticleContainer< T, Dim >::getMeanP () const inline
Definition at line 231 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getMeanMomentum().
getMeanR()
template<typename T , unsigned Dim = 3> Vector_t< double, 3 > ParticleContainer< T, Dim >::getMeanR () const inline
Definition at line 235 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getMeanPosition().
Referenced by ParticleContainer< T, Dim >::deleteParticlesOutside().
getMeans()
template<typename T , unsigned Dim = 3> Vector_t< double, 6 > ParticleContainer< T, Dim >::getMeans () const inline
Definition at line 256 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getMeans().
getMinR()
template<typename T , unsigned Dim = 3> Vector_t< double, 3 > ParticleContainer< T, Dim >::getMinR () const inline
Definition at line 246 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getMinPosition().
getMView()
template<typename T , unsigned Dim = 3> qm_view_type ParticleContainer< T, Dim >::getMView () const inline
Mass view in [GeV]. In SingleValue mode this is a rank-1 view of length 1. In Attributes mode this is the per-particle attribute view.
Definition at line 110 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::Attributes, ParticleContainer< T, Dim >::MAttr, ParticleContainer< T, Dim >::MView_m, and ParticleContainer< T, Dim >::qmStorageMode_m.
Referenced by ParticleContainer< T, Dim >::updateMoments().
getNormEmit()
template<typename T , unsigned Dim = 3> Vector_t< double, 3 > ParticleContainer< T, Dim >::getNormEmit () const inline
Definition at line 260 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getNormalizedEmittance().
getPL()
template<typename T , unsigned Dim = 3> PLayout_t< T, Dim > & ParticleContainer< T, Dim >::getPL () inline
Definition at line 186 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::pl_m.
getPlasmaParameter()
template<typename T , unsigned Dim = 3> double ParticleContainer< T, Dim >::getPlasmaParameter () const inline
Definition at line 278 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getPlasmaParameter().
getQMStorageMode()
template<typename T , unsigned Dim = 3> QMStorageMode ParticleContainer< T, Dim >::getQMStorageMode () const inline
Definition at line 557 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::qmStorageMode_m.
getQView()
template<typename T , unsigned Dim = 3> qm_view_type ParticleContainer< T, Dim >::getQView () const inline
Charge view in [Cb]. In SingleValue mode this is a rank-1 view of length 1. In Attributes mode this is the per-particle attribute view.
Definition at line 100 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::Attributes, ParticleContainer< T, Dim >::QAttr, ParticleContainer< T, Dim >::qmStorageMode_m, and ParticleContainer< T, Dim >::QView_m.
getReference()
template<typename T , unsigned Dim = 3> const PartData * ParticleContainer< T, Dim >::getReference () const inline
Get reference particle data.
Definition at line 400 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::reference_m.
Referenced by ParallelTracker::kickParticles().
getRefPartP() [1/2]
template<typename T , unsigned Dim = 3> Vector_t< double, Dim > & ParticleContainer< T, Dim >::getRefPartP () inline
Get the reference particle momentum.
Definition at line 385 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::refPartP_m.
getRefPartP() [2/2]
template<typename T , unsigned Dim = 3> const Vector_t< double, Dim > & ParticleContainer< T, Dim >::getRefPartP () const inline
Get the reference particle momentum (const).
Definition at line 382 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::refPartP_m.
getRefPartR() [1/2]
template<typename T , unsigned Dim = 3> Vector_t< double, Dim > & ParticleContainer< T, Dim >::getRefPartR () inline
Get the reference particle position.
Definition at line 376 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::refPartR_m.
getRefPartR() [2/2]
template<typename T , unsigned Dim = 3> const Vector_t< double, Dim > & ParticleContainer< T, Dim >::getRefPartR () const inline
Get the reference particle position (const).
Definition at line 373 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::refPartR_m.
getRmsP()
template<typename T , unsigned Dim = 3> Vector_t< double, 3 > ParticleContainer< T, Dim >::getRmsP () const inline
Definition at line 233 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getStandardDeviationMomentum().
getRmsR()
template<typename T , unsigned Dim = 3> Vector_t< double, 3 > ParticleContainer< T, Dim >::getRmsR () const inline
Definition at line 237 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getStandardDeviationPosition().
Referenced by ParticleContainer< T, Dim >::deleteParticlesOutside().
getRmsRP()
template<typename T , unsigned Dim = 3> Vector_t< double, 3 > ParticleContainer< T, Dim >::getRmsRP () const inline
Definition at line 239 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getStandardDeviationRP().
getStdKineticEnergy()
template<typename T , unsigned Dim = 3> double ParticleContainer< T, Dim >::getStdKineticEnergy () const inline
Definition at line 254 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getStdKineticEnergy().
getTemperature()
template<typename T , unsigned Dim = 3> double ParticleContainer< T, Dim >::getTemperature () const inline
Definition at line 276 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::getTemperature().
getToLabTrafo() [1/2]
template<typename T , unsigned Dim = 3> CoordinateSystemTrafo & ParticleContainer< T, Dim >::getToLabTrafo () inline
Get local-to-lab coordinate transformation.
Definition at line 420 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::toLabTrafo_m.
getToLabTrafo() [2/2]
template<typename T , unsigned Dim = 3> const CoordinateSystemTrafo & ParticleContainer< T, Dim >::getToLabTrafo () const inline
Get local-to-lab coordinate transformation (const).
Definition at line 417 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::toLabTrafo_m.
getTotalCharge()
template<typename T , unsigned Dim = 3> double ParticleContainer< T, Dim >::getTotalCharge () const inline
Get total charge [Cb] in this container.
Definition at line 330 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::getChargePerParticle().
getTotalMass()
template<typename T , unsigned Dim = 3> double ParticleContainer< T, Dim >::getTotalMass () const inline
Get total mass [GeV] in this container.
Definition at line 370 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::getMassPerParticle().
isMomentsDirty()
template<typename T , unsigned Dim = 3> bool ParticleContainer< T, Dim >::isMomentsDirty () const inline
Definition at line 202 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::containerState_m.
isUnitlessPositions()
template<typename T , unsigned Dim = 3> bool ParticleContainer< T, Dim >::isUnitlessPositions () const inline
Definition at line 200 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::containerState_m.
markMomentsClean()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::markMomentsClean () inline
Definition at line 204 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::containerState_m.
markMomentsDirty()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::markMomentsDirty () inline
Definition at line 203 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::containerState_m.
Referenced by ParticleContainer< T, Dim >::deleteParticlesOutside(), ParallelTracker::kickParticles(), and ParallelTracker::pushParticles().
registerAttributes()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::registerAttributes () inline
Definition at line 161 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::Attributes, ParticleContainer< T, Dim >::B, ParticleContainer< T, Dim >::Bin, ParticleContainer< T, Dim >::dt, ParticleContainer< T, Dim >::E, ParticleContainer< T, Dim >::InvalidMask, ParticleContainer< T, Dim >::MAttr, ParticleContainer< T, Dim >::P, ParticleContainer< T, Dim >::Phi, ParticleContainer< T, Dim >::QAttr, and ParticleContainer< T, Dim >::qmStorageMode_m.
Referenced by ParticleContainer< T, Dim >::ParticleContainer().
scaleDtByCharge()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::scaleDtByCharge () inline
Scale particle time-step weights by charge before scatter.
Multiplies each local dt[i] by the corresponding charge used for deposition. In QMStorageMode::Attributes, the per-particle QAttr(i) is used. In QMStorageMode::SingleValue, the shared scalar QView_m(0) is used.
Definition at line 463 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::Attributes, ParticleContainer< T, Dim >::dt, ParticleContainer< T, Dim >::QAttr, ParticleContainer< T, Dim >::qmStorageMode_m, and ParticleContainer< T, Dim >::QView_m.
set_sPos()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::set_sPos (double sPos) inline
Set longitudinal position along design trajectory.
Definition at line 403 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::sPos_m.
setBCAllPeriodic()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::setBCAllPeriodic () inline private
Definition at line 736 of file ParticleContainer.hpp.
Referenced by ParticleContainer< T, Dim >::setupBCs().
setBunchStateHandler()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::setBunchStateHandler (std::shared_ptr< BunchStateHandler > handler) inline
Definition at line 188 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::containerState_m, ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::setContainerState().
setEnergyReferenceMass()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::setEnergyReferenceMass (double referenceMassGeV, bool rescaleToReference = true) inline
Definition at line 227 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::distMoments_m, and DistributionMoments::setEnergyReferenceMass().
Referenced by ParticleContainer< T, Dim >::setReference().
setGlobalProcesses()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::setGlobalProcesses (std::vector< std::unique_ptr< GlobalProcess > > processes) inline
Definition at line 559 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::globalProcesses_m.
setGlobalToLocalQuaternion()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::setGlobalToLocalQuaternion (const Quaternion_t & globalToLocalQuaternion) inline
Set global-to-local rotation quaternion.
Definition at line 409 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::globalToLocalQuaternion_m.
setM()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::setM (double m) inline
Set particle mass for the active M storage mode.
Parameters
m Mass value in [GeV].
In QMStorageMode::Attributes, this assigns m to every local particle. In QMStorageMode::SingleValue, this updates the shared scalar mass view.
Definition at line 339 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::Attributes, ParticleContainer< T, Dim >::MAttr, ParticleContainer< T, Dim >::MView_m, and ParticleContainer< T, Dim >::qmStorageMode_m.
setQ()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::setQ (double q) inline
Set particle charge for the active Q storage mode.
Parameters
q Charge value in [Cb].
In QMStorageMode::Attributes, this assigns q to every local particle. In QMStorageMode::SingleValue, this updates the shared scalar charge view.
Definition at line 297 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::Attributes, ParticleContainer< T, Dim >::QAttr, ParticleContainer< T, Dim >::qmStorageMode_m, and ParticleContainer< T, Dim >::QView_m.
setReference()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::setReference (const PartData * ref) inline
Set reference particle data.
Definition at line 391 of file ParticleContainer.hpp.
References Units::eV2GeV, PartData::getM(), ParticleContainer< T, Dim >::reference_m, and ParticleContainer< T, Dim >::setEnergyReferenceMass().
setRefPartP()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::setRefPartP (const Vector_t< double, Dim > & refPartP) inline
Set the reference particle momentum.
Definition at line 388 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::refPartP_m.
setRefPartR()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::setRefPartR (const Vector_t< double, Dim > & refPartR) inline
Set the reference particle position.
Definition at line 379 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::refPartR_m.
setToLabTrafo()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::setToLabTrafo (const CoordinateSystemTrafo & toLabTrafo) inline
Set local-to-lab coordinate transformation.
Definition at line 423 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::toLabTrafo_m.
setupBCs()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::setupBCs () inline
Definition at line 176 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::setBCAllPeriodic().
Referenced by ParticleContainer< T, Dim >::ParticleContainer().
switchOffUnitlessPositions()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::switchOffUnitlessPositions () inline
Restore physical positions from unitless form using each particle's dt[i].
Applies \(R_i = R'_i \, c \, dt_i \).
Exceptions
OpalException if this container is not currently in unitless positions.
Definition at line 542 of file ParticleContainer.hpp.
References Physics::c, and ParticleContainer< T, Dim >::containerState_m.
Referenced by ParallelTracker::pushParticles().
switchToUnitlessPositions()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::switchToUnitlessPositions () inline
Transform positions to unitless coordinates using each particle's dt[i].
Applies \(R'_i = R_i / (c \, dt_i) \). Requires valid non-zero dt values per particle.
Exceptions
OpalException if this container is already in unitless positions.
Definition at line 519 of file ParticleContainer.hpp.
References Physics::c, and ParticleContainer< T, Dim >::containerState_m.
Referenced by ParallelTracker::pushParticles().
transformBunch()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::transformBunch (const CoordinateSystemTrafo & trafo) inline
Apply coordinate transform to local particles: translate R, rotate P, E, B.
Definition at line 179 of file ParticleContainer.hpp.
References CoordinateSystemTrafo::rotateBunchTo(), and CoordinateSystemTrafo::transformBunchTo().
Referenced by ParticleContainer< T, Dim >::updateRefToLabCSTrafo().
unscaleDtByCharge()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::unscaleDtByCharge () inline
Restore original dt values after scaleDtByCharge().
Divides each local dt[i] by the same charge factor applied in scaleDtByCharge().
Definition at line 491 of file ParticleContainer.hpp.
References ParticleContainer< T, Dim >::Attributes, ParticleContainer< T, Dim >::dt, ParticleContainer< T, Dim >::QAttr, ParticleContainer< T, Dim >::qmStorageMode_m, and ParticleContainer< T, Dim >::QView_m.
updateMoments()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::updateMoments () inline
Definition at line 206 of file ParticleContainer.hpp.
References DistributionMoments::computeMoments(), ParticleContainer< T, Dim >::containerState_m, ParticleContainer< T, Dim >::distMoments_m, and ParticleContainer< T, Dim >::getMView().
Referenced by ParticleContainer< T, Dim >::deleteParticlesOutside().
updateRefToLabCSTrafo()
template<typename T , unsigned Dim = 3> void ParticleContainer< T, Dim >::updateRefToLabCSTrafo (double bunchDT) inline
Advance reference/lab transform state and map bunch accordingly.
Definition at line 426 of file ParticleContainer.hpp.
References getQuaternion(), CoordinateSystemTrafo::inverted(), ParticleContainer< T, Dim >::P, ParticleContainer< T, Dim >::refPartP_m, ParticleContainer< T, Dim >::refPartR_m, CoordinateSystemTrafo::rotateFrom(), ParticleContainer< T, Dim >::sPos_m, ParticleContainer< T, Dim >::toLabTrafo_m, ParticleContainer< T, Dim >::transformBunch(), and CoordinateSystemTrafo::transformFrom().
Member Data Documentation
B
template<typename T , unsigned Dim = 3> Base::particle_position_type ParticleContainer< T, Dim >::B
electric field for gun simulation with bins
magnetic field at particle position
Definition at line 139 of file ParticleContainer.hpp.
Referenced by ParallelTracker::kickParticles(), and ParticleContainer< T, Dim >::registerAttributes().
Bin
template<typename T , unsigned Dim = 3> ippl::ParticleAttrib<bin_index_type> ParticleContainer< T, Dim >::Bin
the energy bin the particle is in
Definition at line 124 of file ParticleContainer.hpp.
Referenced by ParticleContainer< T, Dim >::registerAttributes().
containerState_m
template<typename T , unsigned Dim = 3> std::shared_ptr<BunchStateHandler::ContainerState> ParticleContainer< T, Dim >::containerState_m private
Per-container state slot allocated by the handler at setBunchStateHandler. Owned here as the only strong reference; the handler keeps a weak_ptr, so destroying this container automatically releases the slot. The slot's own methods handle MPI consistency, so no direct handler reference is needed.
Definition at line 748 of file ParticleContainer.hpp.
Referenced by ParticleContainer< T, Dim >::isMomentsDirty(), ParticleContainer< T, Dim >::isUnitlessPositions(), ParticleContainer< T, Dim >::markMomentsClean(), ParticleContainer< T, Dim >::markMomentsDirty(), ParticleContainer< T, Dim >::setBunchStateHandler(), ParticleContainer< T, Dim >::switchOffUnitlessPositions(), ParticleContainer< T, Dim >::switchToUnitlessPositions(), and ParticleContainer< T, Dim >::updateMoments().
distMoments_m
template<typename T , unsigned Dim = 3> DistributionMoments ParticleContainer< T, Dim >::distMoments_m private
Definition at line 742 of file ParticleContainer.hpp.
Referenced by ParticleContainer< T, Dim >::computeDebyeLength(), ParticleContainer< T, Dim >::computeMinMaxR(), ParticleContainer< T, Dim >::getCentroid(), ParticleContainer< T, Dim >::getCovMatrix(), ParticleContainer< T, Dim >::getDDx(), ParticleContainer< T, Dim >::getDDy(), ParticleContainer< T, Dim >::getDebyeLength(), ParticleContainer< T, Dim >::getDx(), ParticleContainer< T, Dim >::getDy(), ParticleContainer< T, Dim >::getGeometricEmit(), ParticleContainer< T, Dim >::getMaxR(), ParticleContainer< T, Dim >::getMeanGammaZ(), ParticleContainer< T, Dim >::getMeanKineticEnergy(), ParticleContainer< T, Dim >::getMeanP(), ParticleContainer< T, Dim >::getMeanR(), ParticleContainer< T, Dim >::getMeans(), ParticleContainer< T, Dim >::getMinR(), ParticleContainer< T, Dim >::getNormEmit(), ParticleContainer< T, Dim >::getPlasmaParameter(), ParticleContainer< T, Dim >::getRmsP(), ParticleContainer< T, Dim >::getRmsR(), ParticleContainer< T, Dim >::getRmsRP(), ParticleContainer< T, Dim >::getStdKineticEnergy(), ParticleContainer< T, Dim >::getTemperature(), ParticleContainer< T, Dim >::setBunchStateHandler(), ParticleContainer< T, Dim >::setEnergyReferenceMass(), and ParticleContainer< T, Dim >::updateMoments().
dt
template<typename T , unsigned Dim = 3> ippl::ParticleAttrib<double> ParticleContainer< T, Dim >::dt
timestep in [s]
Definition at line 118 of file ParticleContainer.hpp.
Referenced by Decay::apply(), ParallelTracker::kickParticles(), ParticleContainer< T, Dim >::registerAttributes(), ParticleContainer< T, Dim >::scaleDtByCharge(), and ParticleContainer< T, Dim >::unscaleDtByCharge().
E
template<typename T , unsigned Dim = 3> Base::particle_position_type ParticleContainer< T, Dim >::E
electric field at particle position
Definition at line 133 of file ParticleContainer.hpp.
Referenced by ParallelTracker::kickParticles(), and ParticleContainer< T, Dim >::registerAttributes().
globalProcesses_m
template<typename T , unsigned Dim = 3> std::vector<std::unique_ptr<GlobalProcess> > ParticleContainer< T, Dim >::globalProcesses_m private
Global physics processes attached to this container.
Definition at line 775 of file ParticleContainer.hpp.
Referenced by ParticleContainer< T, Dim >::getGlobalProcesses(), and ParticleContainer< T, Dim >::setGlobalProcesses().
globalToLocalQuaternion_m
template<typename T , unsigned Dim = 3> Quaternion_t ParticleContainer< T, Dim >::globalToLocalQuaternion_m private
Definition at line 763 of file ParticleContainer.hpp.
Referenced by ParticleContainer< T, Dim >::getGlobalToLocalQuaternion(), and ParticleContainer< T, Dim >::setGlobalToLocalQuaternion().
InvalidMask
template<typename T , unsigned Dim = 3> ippl::ParticleAttrib<bool> ParticleContainer< T, Dim >::InvalidMask
particle deletion mask (indicates which particles are deleted every timestep)
Definition at line 142 of file ParticleContainer.hpp.
Referenced by ParticleContainer< T, Dim >::registerAttributes().
MAttr
template<typename T , unsigned Dim = 3> ippl::ParticleAttrib<double> ParticleContainer< T, Dim >::MAttr private
Definition at line 756 of file ParticleContainer.hpp.
Referenced by ParticleContainer< T, Dim >::getMassPerParticle(), ParticleContainer< T, Dim >::getMView(), ParticleContainer< T, Dim >::registerAttributes(), and ParticleContainer< T, Dim >::setM().
MView_m
template<typename T , unsigned Dim = 3> qm_view_type ParticleContainer< T, Dim >::MView_m private
Definition at line 752 of file ParticleContainer.hpp.
Referenced by ParticleContainer< T, Dim >::getMassPerParticle(), ParticleContainer< T, Dim >::getMView(), ParticleContainer< T, Dim >::ParticleContainer(), and ParticleContainer< T, Dim >::setM().
P
template<typename T , unsigned Dim = 3> Base::particle_position_type ParticleContainer< T, Dim >::P
particle momenta [\beta\gamma]
Definition at line 130 of file ParticleContainer.hpp.
Referenced by Decay::apply(), ParticleContainer< T, Dim >::applyFractionalStep(), ParallelTracker::kickParticles(), ParallelTracker::pushParticles(), ParticleContainer< T, Dim >::registerAttributes(), and ParticleContainer< T, Dim >::updateRefToLabCSTrafo().
Phi
template<typename T , unsigned Dim = 3> ippl::ParticleAttrib<double> ParticleContainer< T, Dim >::Phi
the scalar potential in [Cb/s]
Definition at line 121 of file ParticleContainer.hpp.
Referenced by ParticleContainer< T, Dim >::registerAttributes().
pl_m
template<typename T , unsigned Dim = 3> PLayout_t<T, Dim> ParticleContainer< T, Dim >::pl_m private
Definition at line 738 of file ParticleContainer.hpp.
Referenced by ParticleContainer< T, Dim >::getPL(), and ParticleContainer< T, Dim >::ParticleContainer().
QAttr
template<typename T , unsigned Dim = 3> ippl::ParticleAttrib<double> ParticleContainer< T, Dim >::QAttr private
Definition at line 755 of file ParticleContainer.hpp.
Referenced by ParticleContainer< T, Dim >::getChargePerParticle(), ParticleContainer< T, Dim >::getQView(), ParticleContainer< T, Dim >::registerAttributes(), ParticleContainer< T, Dim >::scaleDtByCharge(), ParticleContainer< T, Dim >::setQ(), and ParticleContainer< T, Dim >::unscaleDtByCharge().
qmStorageMode_m
template<typename T , unsigned Dim = 3> QMStorageMode ParticleContainer< T, Dim >::qmStorageMode_m = QMStorageMode::SingleValue private
Definition at line 740 of file ParticleContainer.hpp.
Referenced by ParticleContainer< T, Dim >::getChargePerParticle(), ParticleContainer< T, Dim >::getMassPerParticle(), ParticleContainer< T, Dim >::getMView(), ParticleContainer< T, Dim >::getQMStorageMode(), ParticleContainer< T, Dim >::getQView(), ParticleContainer< T, Dim >::registerAttributes(), ParticleContainer< T, Dim >::scaleDtByCharge(), ParticleContainer< T, Dim >::setM(), ParticleContainer< T, Dim >::setQ(), and ParticleContainer< T, Dim >::unscaleDtByCharge().
QView_m
template<typename T , unsigned Dim = 3> qm_view_type ParticleContainer< T, Dim >::QView_m private
Definition at line 751 of file ParticleContainer.hpp.
Referenced by ParticleContainer< T, Dim >::getChargePerParticle(), ParticleContainer< T, Dim >::getQView(), ParticleContainer< T, Dim >::ParticleContainer(), ParticleContainer< T, Dim >::scaleDtByCharge(), ParticleContainer< T, Dim >::setQ(), and ParticleContainer< T, Dim >::unscaleDtByCharge().
reference_m
template<typename T , unsigned Dim = 3> const PartData* ParticleContainer< T, Dim >::reference_m = nullptr private
Definition at line 769 of file ParticleContainer.hpp.
Referenced by ParticleContainer< T, Dim >::getReference(), and ParticleContainer< T, Dim >::setReference().
refPartP_m
template<typename T , unsigned Dim = 3> Vector_t<double, Dim> ParticleContainer< T, Dim >::refPartP_m private
Definition at line 760 of file ParticleContainer.hpp.
Referenced by ParticleContainer< T, Dim >::applyFractionalStep(), ParticleContainer< T, Dim >::getRefPartP(), ParticleContainer< T, Dim >::getRefPartP(), ParticleContainer< T, Dim >::setRefPartP(), and ParticleContainer< T, Dim >::updateRefToLabCSTrafo().
refPartR_m
template<typename T , unsigned Dim = 3> Vector_t<double, Dim> ParticleContainer< T, Dim >::refPartR_m private
Definition at line 759 of file ParticleContainer.hpp.
Referenced by ParticleContainer< T, Dim >::applyFractionalStep(), ParticleContainer< T, Dim >::getRefPartR(), ParticleContainer< T, Dim >::getRefPartR(), ParticleContainer< T, Dim >::setRefPartR(), and ParticleContainer< T, Dim >::updateRefToLabCSTrafo().
Sp
template<typename T , unsigned Dim = 3> short ParticleContainer< T, Dim >::Sp = 0
the particle specis
Definition at line 127 of file ParticleContainer.hpp.
sPos_m
template<typename T , unsigned Dim = 3> double ParticleContainer< T, Dim >::sPos_m = 0.0 private
Definition at line 772 of file ParticleContainer.hpp.
Referenced by ParticleContainer< T, Dim >::applyFractionalStep(), ParticleContainer< T, Dim >::get_sPos(), ParticleContainer< T, Dim >::set_sPos(), and ParticleContainer< T, Dim >::updateRefToLabCSTrafo().
toLabTrafo_m
template<typename T , unsigned Dim = 3> CoordinateSystemTrafo ParticleContainer< T, Dim >::toLabTrafo_m private
Definition at line 766 of file ParticleContainer.hpp.
Referenced by ParticleContainer< T, Dim >::applyFractionalStep(), ParticleContainer< T, Dim >::getToLabTrafo(), ParticleContainer< T, Dim >::getToLabTrafo(), ParticleContainer< T, Dim >::setToLabTrafo(), and ParticleContainer< T, Dim >::updateRefToLabCSTrafo().
The documentation for this class was generated from the following files:
PartBunchFwd.h
ParticleContainer.hpp