OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestableBinningCmd Class Reference
TestableBinningCmd Class Reference
Public Member Functions
void setMaxBins (int value)
void setDesiredWidth (double value)
void setBinningAlpha (double value)
void setBinningBeta (double value)
void setParameterString (const std::string &value)
void setDumpBinsFile (const std::string &value)
void setDumpBinsFreq (double value)
void setTablePrintFrequency (double value)
virtual BinningCmd * clone (const std::string &name)
Make clone.
int getMaxBins () const
double getDesiredWidth () const
double getBinningAlpha () const
double getBinningBeta () const
std::string getParameter ()
BinningParameter getParameterType () const
std::string getDumpBinsFileName () const
Get the file name for dumping bins to a file.
int getDumpBinsFrequency () const
Get the frequency of dumping bins to a file.
int getTablePrintFrequency () const
bool dumpBinsToFile () const
Check if dumping bins to a file is enabled.
virtual void update ()
Update the binning data (internal cache of attributes).
virtual void execute ()
Execute the BINNING command (currently a thin wrapper around update()).
Inform & printInfo (Inform &os) const
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Static Public Member Functions
static BinningCmd * find (const std::string &name)
Find named BINNING command.
Public Attributes
std::vector< Attribute > itsAttr
The object attributes.
Protected Attributes
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Private Member Functions
void setParameterType ()
Recompute the enum-valued parameter from the string attribute.
Private Attributes
std::string parameterName_m
BinningParameter parameterType_m
Object * itsParent
std::string itsName
std::string itsHelp
int occurrence
double timeStamp
std::set< Invalidator * > references
bool sharedFlag
Detailed Description
Definition at line 38 of file TestBinningCmd.cpp.
Member Function Documentation
canReplaceBy()
bool Object::canReplaceBy (Object * object) virtual inherited
Test if replacement is allowed.
Reimplemented in Table, Action, Element, Distribution, EmissionSourceList, Beam, BoundaryGeometry, EmissionSource, OpalFilter, BoolConstant, RealConstant, StringConstant, RealVariable, and RealVector.
Definition at line 48 of file Object.cpp.
Referenced by OpalData::define().
clear()
void Object::clear () inherited
Clear the occurrence counter.
Definition at line 339 of file Object.cpp.
References Object::occurrence.
clone()
BinningCmd * BinningCmd::clone (const std::string & name) virtual inherited
Make clone.
Implements Object.
Definition at line 73 of file BinningCmd.cpp.
References BinningCmd::BinningCmd().
Referenced by TEST_F().
copyAttributes()
void Object::copyAttributes (const Object & source) inherited
Copy attributes from another object.
Definition at line 54 of file Object.cpp.
References Object::itsAttr.
Referenced by SequenceTemplate::makeInstance(), and LineTemplate::makeInstance().
dumpBinsToFile()
bool BinningCmd::dumpBinsToFile () const inherited
Check if dumping bins to a file is enabled.
Definition at line 216 of file BinningCmd.cpp.
References BINNING::DUMPBINSFILE, Attributes::getString(), and Object::itsAttr.
Referenced by PartBunch< T, Dim >::dumpBinConfig(), BinningCmd::getDumpBinsFrequency(), BinningCmd::printInfo(), TEST_F(), and TEST_F().
execute()
void BinningCmd::execute () virtual inherited
Execute the BINNING command (currently a thin wrapper around update()).
Reimplemented from Object.
Definition at line 86 of file BinningCmd.cpp.
References BinningCmd::setParameterType(), and BinningCmd::update().
Referenced by TEST_F(), TEST_F(), and TEST_F().
find()
BinningCmd * BinningCmd::find (const std::string & name) static inherited
Find named BINNING command.
Definition at line 77 of file BinningCmd.cpp.
References OpalData::find(), and OpalData::getInstance().
Referenced by FieldSolverCmd::getBinningCmd().
findAttribute() [1/2]
Attribute * Object::findAttribute (const std::string & name) virtual inherited
Find an attribute by name.
Definition at line 64 of file Object.cpp.
References Object::itsAttr.
Referenced by SequenceParser::findNeighbourPositions(), OpalElement::getParticleMatterInteraction(), OpalElement::getTypeName(), OpalElement::getWakeF(), Object::parse(), OpalElement::parse(), Line::parse(), OpalParser::parseAssign(), SequenceParser::parsePosition(), Object::parseShortcut(), and TEST().
findAttribute() [2/2]
const Attribute * Object::findAttribute (const std::string & name) const virtual inherited
Find an attribute by name.
Definition at line 72 of file Object.cpp.
References Object::itsAttr.
getBaseObject()
const Object * Object::getBaseObject () const inherited
Return the object's base type object.
Definition at line 301 of file Object.cpp.
References Object::itsParent.
getBinningAlpha()
double BinningCmd::getBinningAlpha () const inherited
Definition at line 181 of file BinningCmd.cpp.
References BINNING::BINNINGALPHA, Attributes::getReal(), and Object::itsAttr.
Referenced by BinningCmd::printInfo(), PartBunch< T, Dim >::setBins(), TEST_F(), TEST_F(), and TEST_F().
getBinningBeta()
double BinningCmd::getBinningBeta () const inherited
Definition at line 185 of file BinningCmd.cpp.
References BINNING::BINNINGBETA, Attributes::getReal(), and Object::itsAttr.
Referenced by BinningCmd::printInfo(), PartBunch< T, Dim >::setBins(), TEST_F(), TEST_F(), and TEST_F().
getCategory()
const std::string Definition::getCategory () const virtual inherited
Return the object category as a string.
Implements Object.
Definition at line 29 of file Definition.cpp.
getDesiredWidth()
double BinningCmd::getDesiredWidth () const inherited
Definition at line 177 of file BinningCmd.cpp.
References BINNING::DESIREDWIDTH, Attributes::getReal(), and Object::itsAttr.
Referenced by BinningCmd::printInfo(), PartBunch< T, Dim >::setBins(), TEST_F(), TEST_F(), and TEST_F().
getDumpBinsFileName()
std::string BinningCmd::getDumpBinsFileName () const inherited
Get the file name for dumping bins to a file.
Definition at line 193 of file BinningCmd.cpp.
References BINNING::DUMPBINSFILE, Attributes::getString(), and Object::itsAttr.
Referenced by PartBunch< T, Dim >::dumpBinConfig(), BinningCmd::printInfo(), and TEST_F().
getDumpBinsFrequency()
int BinningCmd::getDumpBinsFrequency () const inherited
Get the frequency of dumping bins to a file.
Definition at line 197 of file BinningCmd.cpp.
References BINNING::DUMPBINSFREQ, BinningCmd::dumpBinsToFile(), Attributes::getReal(), and Object::itsAttr.
Referenced by PartBunch< T, Dim >::dumpBinConfig(), BinningCmd::printInfo(), and TEST_F().
getMaxBins()
int BinningCmd::getMaxBins () const inherited
Definition at line 173 of file BinningCmd.cpp.
References Attributes::getReal(), Object::itsAttr, and BINNING::MAXBINS.
Referenced by BinningCmd::printInfo(), PartBunch< T, Dim >::setBins(), TEST_F(), TEST_F(), and TEST_F().
getOpalName()
const std::string & Object::getOpalName () const inherited
Return object name.
Definition at line 308 of file Object.cpp.
References Object::itsName.
Referenced by OpalVariableRFCavity::clone(), Macro::clone(), OpalData::create(), OpalData::define(), Sequence::findDriftLength(), SequenceParser::findNeighbourPositions(), ValueDefinition::getBool(), ValueDefinition::getBoolComponent(), ValueDefinition::getReal(), ValueDefinition::getRealComponent(), ValueDefinition::getString(), ValueDefinition::getStringComponent(), Object::makeInstance(), SequenceTemplate::makeInstance(), LineTemplate::makeInstance(), SequenceParser::parseMember(), SequenceParser::parsePosition(), Object::print(), OpalElement::print(), Sequence::print(), BoolConstant::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), StringConstant::print(), Beam::print(), OpalFilter::print(), Line::print(), BinningCmd::printInfo(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), OpalElement::registerOwnership(), Object::registerOwnership(), Line::replace(), Sequence::replace(), PartBunch< T, Dim >::setBins(), TEST(), TEST(), TEST(), TEST_F(), Beam::update(), BoundaryGeometry::update(), OpalFilter::update(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), and OpalSplineTimeDependence::update().
getParameter()
std::string BinningCmd::getParameter () inherited
Definition at line 189 of file BinningCmd.cpp.
References Attributes::getString(), Object::itsAttr, and BINNING::PARAMETER.
Referenced by PartBunch< T, Dim >::setBins(), BinningCmd::setParameterType(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
getParameterType()
BinningParameter BinningCmd::getParameterType () const inherited
Definition at line 221 of file BinningCmd.cpp.
References BinningCmd::parameterType_m.
Referenced by PartBunch< T, Dim >::setBins(), TEST_F(), TEST_F(), and TEST_F().
getParent()
Object * Object::getParent () const inherited
Return parent pointer.
Definition at line 313 of file Object.cpp.
References Object::itsParent.
Referenced by OpalData::erase(), Object::print(), OpalElement::print(), OpalElement::registerOwnership(), and Object::registerOwnership().
getTablePrintFrequency()
int BinningCmd::getTablePrintFrequency () const inherited
Get frequency (in global timesteps) of printing bin stats to console. Returns an integer >= 0. If 0, printing is disabled.
Definition at line 206 of file BinningCmd.cpp.
References Attributes::getReal(), Object::itsAttr, and BINNING::TABLEPRINTFREQ.
Referenced by BinningCmd::printInfo(), TEST_F(), and TEST_F().
increment()
int Object::increment () inherited
Increment and return the occurrence counter.
Definition at line 344 of file Object.cpp.
References Object::occurrence.
Referenced by Line::parse(), and Sequence::storeLine().
isBuiltin()
bool Object::isBuiltin () const inherited
True, if [b]this[/b] is a built-in object.
Definition at line 266 of file Object.cpp.
References Object::builtin.
Referenced by OpalData::define(), and OpalData::getVariableNames().
isDirty()
bool Object::isDirty () const inherited
True, if the [b]modified[/b] flag is set.
Definition at line 287 of file Object.cpp.
References Object::modified.
isFlagged()
bool Object::isFlagged () const inherited
True, if [b]this[/b] is flagged by setFlag(true).
Definition at line 297 of file Object.cpp.
References Object::flagged.
isShared()
bool Object::isShared () const virtual inherited
Shared flag.
Definition at line 271 of file Object.cpp.
References Object::sharedFlag.
Referenced by Sequence::print().
isTreeMember()
bool Object::isTreeMember (const Object * subTree) const inherited
Test for tree membership.
Definition at line 318 of file Object.cpp.
References Object::itsParent.
Referenced by Selector::handleElement(), and OpalParser::parseAssign().
makeInstance()
Object * Object::makeInstance (const std::string & name, Statement & , const Parser *) virtual inherited
Macro handler function.
Reimplemented in SequenceTemplate, MacroCmd, and LineTemplate.
Definition at line 89 of file Object.cpp.
References Object::getOpalName().
Referenced by OpalParser::parseDefine(), and OpalParser::parseMacro().
makeTemplate()
Object * Object::makeTemplate (const std::string & name, TokenStream & , Statement &) virtual inherited
Macro handler function.
Reimplemented in LineTemplate, Sequence, MacroCmd, SequenceTemplate, and Line.
Definition at line 82 of file Object.cpp.
Referenced by OpalParser::parseMacro().
occurrenceCount()
int Object::occurrenceCount () inherited
Return the occurrence counter.
Definition at line 349 of file Object.cpp.
References Object::occurrence.
parse()
void Object::parse (Statement & stat) virtual inherited
Parse the object.
Reimplemented in Call, Echo, Help, PSystem, System, Title, Value, OpalElement, Sequence, EmissionSourceList, and Line.
Definition at line 95 of file Object.cpp.
References Statement::delimiter(), Object::findAttribute(), Expressions::parseDelimiter(), Expressions::parseRealConst(), and Expressions::parseString().
Referenced by Sequence::parse(), OpalParser::parseAction(), OpalParser::parseDefine(), and SequenceTemplate::parseTemplate().
parseShortcut()
void Object::parseShortcut (Statement & stat, bool eval = true) virtual inherited
Parser for single-attribute commands.
Definition at line 127 of file Object.cpp.
References Statement::delimiter(), Object::findAttribute(), Statement::mark(), and Statement::word().
Referenced by Call::parse(), Echo::parse(), Help::parse(), PSystem::parse(), System::parse(), Title::parse(), and Value::parse().
print()
void Object::print (std::ostream & msg) const virtual inherited
Print the object.
Reimplemented in OpalElement, OpalMarker, OpalMultipole, OpalQuadrupole, OpalRingDefinition, Sequence, TrackRun, BoolConstant, RealConstant, RealVariable, RealVector, StringConstant, OpalPolynomialTimeDependence, OpalSinusoidalTimeDependence, OpalSplineTimeDependence, Beam, OpalFilter, DumpEMFields, OpalMultipoleT, and Line.
Definition at line 159 of file Object.cpp.
References Object::getOpalName(), Object::getParent(), and Object::itsAttr.
Referenced by Object::printValue().
printHelp()
void Object::printHelp (std::ostream &) const virtual inherited
Print help.
Definition at line 199 of file Object.cpp.
References gmsg, Object::itsAttr, and Object::itsHelp.
Referenced by Help::execute().
printInfo()
Inform & BinningCmd::printInfo (Inform & os) const inherited
Definition at line 153 of file BinningCmd.cpp.
References BinningCmd::dumpBinsToFile(), BinningCmd::getBinningAlpha(), BinningCmd::getBinningBeta(), BinningCmd::getDesiredWidth(), BinningCmd::getDumpBinsFileName(), BinningCmd::getDumpBinsFrequency(), BinningCmd::getMaxBins(), Object::getOpalName(), BinningCmd::getTablePrintFrequency(), and BinningCmd::parameterName_m.
Referenced by operator<<(), and TEST_F().
printValue()
void Object::printValue (std::ostream & os) const inline virtual inherited
Reimplemented in BoolConstant, RealConstant, RealVariable, RealVector, and StringConstant.
Definition at line 277 of file Object.h.
References Object::print().
registerOwnership()
void Object::registerOwnership (const AttributeHandler::OwnerType & itsClass) const inherited
Definition at line 189 of file Object.cpp.
References AttributeHandler::addAttributeOwner(), Object::getOpalName(), Object::getParent(), and Object::itsAttr.
Referenced by Beam::Beam(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), Call::Call(), Distribution::Distribution(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), EmissionSourceList::EmissionSourceList(), Help::Help(), Line::Line(), OpalFilter::OpalFilter(), Option::Option(), PSystem::PSystem(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVector::RealVector(), Select::Select(), Sequence::Sequence(), StringConstant::StringConstant(), System::System(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), and Value::Value().
registerReference()
void Object::registerReference (Invalidator * a) inherited
Register a reference to this object.
Definition at line 180 of file Object.cpp.
References Object::references.
replace()
void Object::replace (Object * oldObject, Object * newObject) virtual inherited
Replace references.
Reimplemented in Line, and Sequence.
Definition at line 256 of file Object.cpp.
setBinningAlpha()
void TestableBinningCmd::setBinningAlpha (double value) inline
Definition at line 48 of file TestBinningCmd.cpp.
References BINNING::BINNINGALPHA, Object::itsAttr, and Attributes::setReal().
Referenced by TEST_F(), and TEST_F().
setBinningBeta()
void TestableBinningCmd::setBinningBeta (double value) inline
Definition at line 52 of file TestBinningCmd.cpp.
References BINNING::BINNINGBETA, Object::itsAttr, and Attributes::setReal().
Referenced by TEST_F(), and TEST_F().
setDesiredWidth()
void TestableBinningCmd::setDesiredWidth (double value) inline
Definition at line 44 of file TestBinningCmd.cpp.
References BINNING::DESIREDWIDTH, Object::itsAttr, and Attributes::setReal().
Referenced by TEST_F(), and TEST_F().
setDirty()
void Object::setDirty (bool dirty) inherited
Set/reset the [b]modified[/b] flag.
Definition at line 281 of file Object.cpp.
References Object::modified.
Referenced by OpalData::define(), OpalData::makeDirty(), and RealVariable::RealVariable().
setDumpBinsFile()
void TestableBinningCmd::setDumpBinsFile (const std::string & value) inline
Definition at line 61 of file TestBinningCmd.cpp.
References BINNING::DUMPBINSFILE, Object::itsAttr, and Attributes::setString().
Referenced by TEST_F(), TEST_F(), and TEST_F().
setDumpBinsFreq()
void TestableBinningCmd::setDumpBinsFreq (double value) inline
Definition at line 65 of file TestBinningCmd.cpp.
References BINNING::DUMPBINSFREQ, Object::itsAttr, and Attributes::setReal().
Referenced by TEST_F(), and TEST_F().
setFlag()
void Object::setFlag (bool flag) inherited
Flag/unflag this object, e. g. to control output of objects for.
Definition at line 292 of file Object.cpp.
References Object::flagged.
setMaxBins()
void TestableBinningCmd::setMaxBins (int value) inline
Definition at line 40 of file TestBinningCmd.cpp.
References Object::itsAttr, BINNING::MAXBINS, and Attributes::setReal().
Referenced by TEST_F(), and TEST_F().
setOpalName()
void Object::setOpalName (const std::string & name) inherited
Set object name.
Definition at line 329 of file Object.cpp.
References Object::itsName.
Referenced by TEST(), TEST(), TEST(), Beam::update(), BoundaryGeometry::update(), and OpalFilter::update().
setParameterString()
void TestableBinningCmd::setParameterString (const std::string & value) inline
Definition at line 56 of file TestBinningCmd.cpp.
References Object::itsAttr, BINNING::PARAMETER, and Attributes::setPredefinedString().
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
setParameterType()
void BinningCmd::setParameterType () private inherited
Recompute the enum-valued parameter from the string attribute.
Definition at line 133 of file BinningCmd.cpp.
References GAMMAZ, BinningCmd::getParameter(), BinningCmd::parameterName_m, BinningCmd::parameterType_m, POSITIONZ, PZ, and VELOCITYZ.
Referenced by BinningCmd::execute().
setParent()
void Object::setParent (Object * parent) inherited
Set parent object.
Definition at line 334 of file Object.cpp.
References Object::itsParent.
Referenced by OpalData::erase().
setShared()
void Object::setShared (bool flag) virtual inherited
Set/reset shared flag.
Reimplemented in Element.
Definition at line 276 of file Object.cpp.
References Object::sharedFlag.
Referenced by OpalParser::parseDefine(), and Element::setShared().
setTablePrintFrequency()
void TestableBinningCmd::setTablePrintFrequency (double value) inline
Definition at line 69 of file TestBinningCmd.cpp.
References Object::itsAttr, Attributes::setReal(), and BINNING::TABLEPRINTFREQ.
Referenced by TEST_F(), and TEST_F().
shouldTrace()
bool Definition::shouldTrace () const virtual inherited
Trace flag.
Implements Object.
Definition at line 34 of file Definition.cpp.
shouldUpdate()
bool Definition::shouldUpdate () const virtual inherited
Update flag.
Implements Object.
Definition at line 39 of file Definition.cpp.
unregisterReference()
void Object::unregisterReference (Invalidator * a) inherited
Unegister a reference to this object.
Definition at line 185 of file Object.cpp.
References Object::references.
update()
void BinningCmd::update () virtual inherited
Update the binning data (internal cache of attributes).
Reimplemented from Object.
Definition at line 91 of file BinningCmd.cpp.
References BINNING::DUMPBINSFILE, BINNING::DUMPBINSFREQ, Attributes::getReal(), Attributes::getString(), Object::itsAttr, BINNING::PARAMETER, BinningCmd::parameterName_m, Attributes::setString(), and BINNING::TABLEPRINTFREQ.
Referenced by BinningCmd::execute(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
Member Data Documentation
builtin
bool Object::builtin protected inherited
Built-in flag.
Definition at line 230 of file Object.h.
Referenced by Beam::Beam(), BoundaryGeometry::BoundaryGeometry(), Object::isBuiltin(), Object::Object(), Object::Object(), OpalFilter::OpalFilter(), OpalMarker::OpalMarker(), RealConstant::RealConstant(), StringConstant::StringConstant(), and Table::~Table().
flagged
bool Object::flagged protected inherited
Object flag.
Definition at line 239 of file Object.h.
Referenced by Object::isFlagged(), Object::Object(), Object::Object(), and Object::setFlag().
itsAttr
std::vector<Attribute> Object::itsAttr inherited
The object attributes.
Definition at line 213 of file Object.h.
Referenced by Beam::Beam(), BinningCmd::BinningCmd(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), BoundaryGeometry::BoundaryGeometry(), DumpEMFields::buildGrid(), Call::Call(), FieldSolverCmd::constructBCHandler(), Object::copyAttributes(), Distribution::Distribution(), BinningCmd::dumpBinsToFile(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), Call::execute(), Echo::execute(), Help::execute(), Option::execute(), PSystem::execute(), Select::execute(), System::execute(), Title::execute(), Value::execute(), Beam::execute(), TrackCmd::execute(), TrackRun::execute(), FieldSolverCmd::FieldSolverCmd(), Object::findAttribute(), Object::findAttribute(), BoundaryGeometry::getA(), OpalElement::getApert(), BoundaryGeometry::getB(), BinningCmd::getBinningAlpha(), BinningCmd::getBinningBeta(), FieldSolverCmd::getBinsName(), BoolConstant::getBool(), FieldSolverCmd::getBoxIncr(), Beam::getBunchCharge(), BoundaryGeometry::getC(), Beam::getCharge(), Beam::getCurrent(), Beam::getDaughterBeamName(), BinningCmd::getDesiredWidth(), EmissionSource::getDistributionName(), FieldSolverCmd::getDomDec(), TrackCmd::getDT(), TrackCmd::getDTAU(), TrackCmd::getDTSCINIT(), BinningCmd::getDumpBinsFileName(), BinningCmd::getDumpBinsFrequency(), EmissionSource::getEmissionModel(), Beam::getEmissionSourceListName(), Distribution::getFilename(), BoundaryGeometry::getFilename(), Beam::getFrequency(), Beam::getGlobalProcessNames(), BoundaryGeometry::getL1(), BoundaryGeometry::getL2(), BoundaryGeometry::getLength(), OpalElement::getLength(), Line::getLength(), Sequence::getLength(), Beam::getMass(), BinningCmd::getMaxBins(), TrackCmd::getMaxSteps(), Beam::getNumAlloc(), FieldSolverCmd::getNX(), FieldSolverCmd::getNY(), FieldSolverCmd::getNZ(), EmissionSource::getP0(), BinningCmd::getParameter(), Beam::getParticleName(), EmissionSource::getR0(), RealConstant::getReal(), RealVariable::getReal(), RealVector::getRealComponent(), Sequence::getReference(), BoundaryGeometry::getS(), EmissionSource::getShiftedGreensFunction(), TrackCmd::getStepsPerTurn(), StringConstant::getString(), EmissionSource::getT0(), TrackCmd::getT0(), BinningCmd::getTablePrintFrequency(), TrackCmd::getTimeIntegrator(), BoundaryGeometry::getTopology(), FieldSolverCmd::getType(), EmissionSource::getZerofaceMaxSteps(), EmissionSource::getZeroFacePlaneDumpFrequency(), EmissionSource::getZeroFaceR0Z(), TrackCmd::getZStart(), TrackCmd::getZStop(), Beam::hasExplicitEnergy(), Help::Help(), BoundaryGeometry::initialize(), OpalFilter::initOpalFilter(), Beam::isPhoton(), Line::Line(), OpalCavity::OpalCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalDrift::OpalDrift(), OpalElement::OpalElement(), OpalFilter::OpalFilter(), OpalLaser::OpalLaser(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalPolynomialTimeDependence::OpalPolynomialTimeDependence(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalRingDefinition::OpalRingDefinition(), OpalSinusoidalTimeDependence::OpalSinusoidalTimeDependence(), OpalSolenoid::OpalSolenoid(), OpalSplineTimeDependence::OpalSplineTimeDependence(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), Option::Option(), Option::Option(), Sequence::parse(), Line::parse(), DumpEMFields::parseCoordinateSystem(), Object::print(), Sequence::print(), BoolConstant::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), StringConstant::print(), Beam::print(), OpalFilter::print(), DumpEMFields::print(), Object::printHelp(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), BoolConstant::printValue(), RealConstant::printValue(), RealVariable::printValue(), RealVector::printValue(), StringConstant::printValue(), PSystem::PSystem(), RealConstant::RealConstant(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVariable::RealVariable(), RealVector::RealVector(), OpalElement::registerOwnership(), Object::registerOwnership(), Select::Select(), Select::select(), Sequence::Sequence(), Distribution::setAttributes(), TestMultipoleT::TestableFieldSolverCmd::setBCX(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCX(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCX(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCX(), TestVariableRFCavity::TestableFieldSolverCmd::setBCX(), TestMultipoleT::TestableFieldSolverCmd::setBCY(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCY(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCY(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCY(), TestVariableRFCavity::TestableFieldSolverCmd::setBCY(), TestMultipoleT::TestableFieldSolverCmd::setBCZ(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCZ(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCZ(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCZ(), TestVariableRFCavity::TestableFieldSolverCmd::setBCZ(), setBinningAlpha(), setBinningBeta(), setDesiredWidth(), Distribution::setDistParametersFlatTop(), Distribution::setDistParametersMultiVariateGauss(), Distribution::setDistType(), setDumpBinsFile(), setDumpBinsFreq(), setMaxBins(), FieldSolverCmd::setNX(), FieldSolverCmd::setNY(), FieldSolverCmd::setNZ(), setParameterString(), TrackRun::setRunMethod(), Distribution::setSigmaP_m(), Distribution::setSigmaR_m(), setTablePrintFrequency(), TestMultipoleT::TestableFieldSolverCmd::setType(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setType(), TestMultipoleTStraight::TestableFieldSolverCmd::setType(), SolenoidPlacementTest::TestableFieldSolverCmd::setType(), TestVariableRFCavity::TestableFieldSolverCmd::setType(), TrackRun::setupBoundaryGeometry(), StringConstant::StringConstant(), StringConstant::StringConstant(), System::System(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), OpalCavity::update(), OpalConstantEFieldCavity::update(), OpalDrift::update(), OpalElement::update(), OpalMonitor::update(), OpalMultipole::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalRingDefinition::update(), OpalSolenoid::update(), OpalTravelingWave::update(), OpalVacuum::update(), OpalVerticalFFAMagnet::update(), Beam::update(), BinningCmd::update(), FieldSolverCmd::update(), OpalLaser::update(), OpalMultipoleT::update(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), OpalSplineTimeDependence::update(), OpalVariableRFCavity::update(), Option::update(), OpalElement::updateUnknown(), ValueDefinition::value(), Value::Value(), and ValueDefinition::value().
itsHelp
std::string Object::itsHelp private inherited
Definition at line 255 of file Object.h.
Referenced by Object::printHelp().
itsName
std::string Object::itsName private inherited
Definition at line 252 of file Object.h.
Referenced by Object::getOpalName(), and Object::setOpalName().
itsParent
Object* Object::itsParent private inherited
Definition at line 249 of file Object.h.
Referenced by Object::getBaseObject(), Object::getParent(), Object::isTreeMember(), and Object::setParent().
modified
bool Object::modified protected inherited
Dirty flag.
Definition at line 235 of file Object.h.
Referenced by Object::isDirty(), Object::Object(), Object::Object(), and Object::setDirty().
occurrence
int Object::occurrence private inherited
Definition at line 258 of file Object.h.
Referenced by Object::clear(), Object::increment(), and Object::occurrenceCount().
parameterName_m
std::string BinningCmd::parameterName_m private inherited
Definition at line 110 of file BinningCmd.h.
Referenced by BinningCmd::printInfo(), BinningCmd::setParameterType(), and BinningCmd::update().
parameterType_m
BinningParameter BinningCmd::parameterType_m private inherited
Definition at line 111 of file BinningCmd.h.
Referenced by BinningCmd::getParameterType(), and BinningCmd::setParameterType().
references
std::set<Invalidator *> Object::references private inherited
Definition at line 265 of file Object.h.
Referenced by Object::registerReference(), Object::unregisterReference(), and Object::~Object().
sharedFlag
bool Object::sharedFlag private inherited
Definition at line 268 of file Object.h.
Referenced by Object::isShared(), and Object::setShared().
timeStamp
double Object::timeStamp private inherited
Definition at line 261 of file Object.h.
The documentation for this class was generated from the following file:
TestBinningCmd.cpp