OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions::ARow Class Reference
Expressions::ARow Class Reference
An array expression defined as a table row.
#include <ARow.h>
Public Member Functions
ARow (const std::string &tabName, const PlaceRep &row, const std::vector< std::string > &col)
Constructor.
ARow (const ARow &)
~ARow ()
virtual OArray< double > * clone () const
Make clone.
virtual std::vector< double > evaluate () const
Evaluate.
virtual void print (std::ostream &os, int precedence=99) const
Print expression.
virtual bool isConstant () const
Test for constant.
Private Member Functions
ARow ()
const ARow & operator= (const ARow &)
Private Attributes
const std::string tabName
PlaceRep position
const std::vector< std::string > columns
Detailed Description
An array expression defined as a table row.
Definition at line 34 of file ARow.h.
Constructor & Destructor Documentation
ARow() [1/3]
Expressions::ARow::ARow (const std::string & tabName, const PlaceRep & row, const std::vector< std::string > & col)
Constructor.
Definition at line 32 of file ARow.cpp.
ARow() [2/3]
Expressions::ARow::ARow (const ARow & rhs)
Definition at line 29 of file ARow.cpp.
~ARow()
Expressions::ARow::~ARow ()
Definition at line 35 of file ARow.cpp.
ARow() [3/3]
Expressions::ARow::ARow () private
Referenced by clone().
Member Function Documentation
clone()
OArray< double > * Expressions::ARow::clone () const virtual
Make clone.
Implements Expressions::OArray< double >.
Definition at line 37 of file ARow.cpp.
References ARow().
evaluate()
std::vector< double > Expressions::ARow::evaluate () const virtual
Evaluate.
Implements Expressions::OArray< double >.
Definition at line 39 of file ARow.cpp.
References columns, Table::fill(), Table::find(), Table::getRow(), position, and tabName.
isConstant()
bool Expressions::OArray< double >::isConstant () const inline virtual inherited
Test for constant.
Definition at line 165 of file AbstractObjects/Expressions.h.
operator=()
const ARow & Expressions::ARow::operator= (const ARow &) private
print()
void Expressions::ARow::print (std::ostream & os, int precedence = 99) const virtual
Print expression.
Implements Expressions::OArray< double >.
Definition at line 45 of file ARow.cpp.
References columns, position, and tabName.
Member Data Documentation
columns
const std::vector<std::string> Expressions::ARow::columns private
Definition at line 66 of file ARow.h.
Referenced by evaluate(), and print().
position
PlaceRep Expressions::ARow::position private
Definition at line 63 of file ARow.h.
Referenced by evaluate(), and print().
tabName
const std::string Expressions::ARow::tabName private
Definition at line 60 of file ARow.h.
Referenced by evaluate(), and print().
The documentation for this class was generated from the following files:
ARow.h
ARow.cpp