OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions::SCell Class Reference
Expressions::SCell Class Reference
A scalar expression referring to a table cell.
#include <SCell.h>
Public Member Functions
SCell (const std::string &tab, const PlaceRep &place, const std::string &col)
Constructor.
virtual ~SCell ()
virtual Scalar< double > * clone () const
Make clone.
virtual double evaluate () const
Evaluate.
virtual void print (std::ostream &stream, int) const
Print expression.
virtual bool isConstant () const
Test for constant.
Private Member Functions
SCell ()
void operator= (const SCell &)
Private Attributes
const std::string tab_name
const PlaceRep position
const std::string col_name
ConstChannel * itsChannel
Detailed Description
A scalar expression referring to a table cell.
Definition at line 35 of file SCell.h.
Constructor & Destructor Documentation
SCell() [1/2]
Expressions::SCell::SCell (const std::string & tab, const PlaceRep & place, const std::string & col)
Constructor.
Definition at line 30 of file SCell.cpp.
References col_name, itsChannel, position, and tab_name.
Referenced by operator=().
~SCell()
Expressions::SCell::~SCell () virtual
Definition at line 33 of file SCell.cpp.
References itsChannel.
SCell() [2/2]
Expressions::SCell::SCell () private
Referenced by clone().
Member Function Documentation
clone()
Scalar< double > * Expressions::SCell::clone () const virtual
Make clone.
Implements Expressions::Scalar< double >.
Definition at line 35 of file SCell.cpp.
References col_name, position, Expressions::Scalar< double >::Scalar(), SCell(), and tab_name.
evaluate()
double Expressions::SCell::evaluate () const virtual
Evaluate.
Implements Expressions::Scalar< double >.
Definition at line 37 of file SCell.cpp.
References col_name, Table::fill(), Table::find(), Table::getCell(), position, and tab_name.
isConstant()
bool Expressions::Scalar< double >::isConstant () const inline virtual inherited
Test for constant.
Definition at line 88 of file AbstractObjects/Expressions.h.
operator=()
void Expressions::SCell::operator= (const SCell &) private
References SCell().
print()
void Expressions::SCell::print (std::ostream & stream, int) const virtual
Print expression.
Implements Expressions::Scalar< double >.
Definition at line 46 of file SCell.cpp.
References col_name, position, and tab_name.
Member Data Documentation
col_name
const std::string Expressions::SCell::col_name private
Definition at line 62 of file SCell.h.
Referenced by clone(), evaluate(), print(), and SCell().
itsChannel
ConstChannel* Expressions::SCell::itsChannel mutable private
Definition at line 65 of file SCell.h.
Referenced by SCell(), and ~SCell().
position
const PlaceRep Expressions::SCell::position private
Definition at line 61 of file SCell.h.
Referenced by clone(), evaluate(), print(), and SCell().
tab_name
const std::string Expressions::SCell::tab_name private
Definition at line 60 of file SCell.h.
Referenced by clone(), evaluate(), print(), and SCell().
The documentation for this class was generated from the following files:
SCell.h
SCell.cpp