OPALX (Object Oriented Parallel Accelerator Library for Exascal): SDDSColumnSet Class Reference
SDDSColumnSet Class Reference
#include <SDDSColumnSet.h>
Public Member Functions
SDDSColumnSet ()
void addColumn (const std::string &name, const std::string &type, const std::string &unit, const std::string &desc, std::ios_base::fmtflags flags=std::ios_base::scientific, unsigned short precision=15)
template<typename T >
void addColumnValue (const std::string &name, const T &val)
void writeHeader (std::ostream &os, const std::string &indent) const
void writeRow (std::ostream &os) const
bool hasColumns () const
Private Attributes
std::vector< SDDSColumn > columns_m
std::map< std::string, size_t > name2idx_m
Detailed Description
Definition at line 29 of file SDDSColumnSet.h.
Constructor & Destructor Documentation
SDDSColumnSet()
SDDSColumnSet::SDDSColumnSet () inline
Definition at line 58 of file SDDSColumnSet.h.
Member Function Documentation
addColumn()
void SDDSColumnSet::addColumn (const std::string & name, const std::string & type, const std::string & unit, const std::string & desc, std::ios_base::fmtflags flags = std::ios_base::scientific, unsigned short precision = 15)
Definition at line 20 of file SDDSColumnSet.cpp.
References columns_m, and name2idx_m.
Referenced by ElementPositionWriter::fillHeader(), LBalWriter::fillHeader(), MonitorStatisticsWriter::fillHeader(), StatWriter::fillHeader(), and MemoryProfiler::header().
addColumnValue()
template<typename T > void SDDSColumnSet::addColumnValue (const std::string & name, const T & val)
Definition at line 63 of file SDDSColumnSet.h.
References columns_m, and name2idx_m.
Referenced by MonitorStatisticsWriter::addRow(), ElementPositionWriter::addRow(), LBalWriter::write(), MemoryProfiler::write(), and StatWriter::write().
hasColumns()
bool SDDSColumnSet::hasColumns () const inline
Definition at line 78 of file SDDSColumnSet.h.
References name2idx_m.
Referenced by SDDSWriter::hasColumns().
writeHeader()
void SDDSColumnSet::writeHeader (std::ostream & os, const std::string & indent) const
Definition at line 37 of file SDDSColumnSet.cpp.
References columns_m.
Referenced by SDDSWriter::writeColumns().
writeRow()
void SDDSColumnSet::writeRow (std::ostream & os) const
Definition at line 46 of file SDDSColumnSet.cpp.
References columns_m.
Referenced by SDDSWriter::writeRow().
Member Data Documentation
columns_m
std::vector<SDDSColumn> SDDSColumnSet::columns_m private
Definition at line 52 of file SDDSColumnSet.h.
Referenced by addColumn(), addColumnValue(), writeHeader(), and writeRow().
name2idx_m
std::map<std::string, size_t> SDDSColumnSet::name2idx_m private
Definition at line 53 of file SDDSColumnSet.h.
Referenced by addColumn(), addColumnValue(), and hasColumns().
The documentation for this class was generated from the following files:
SDDSColumnSet.h
SDDSColumnSet.cpp