OPALX (Object Oriented Parallel Accelerator Library for Exascal): OpalBend Class Reference
OpalBend Class Reference abstract
Base class for all bending magnets.
#include <OpalBend.h>
Public Types
enum {
ANGLE = COMMON , K0 , K0S , K1 ,
K1S , K2 , K2S , K3 ,
K3S , E1 , E2 , H1 ,
H2 , HGAP , FINT , SLICES ,
STEPSIZE , FMAPFN , GAP , HAPERT ,
ROTATION , DESIGNENERGY , GREATERTHANPI , NSLICES ,
SIZE
}
The attribute numbers for OPAL bend magnets.
enum {
TYPE , APERT , LENGTH , ELEMEDGE ,
WAKEF , PARTICLEMATTERINTERACTION , ORIGIN , ORIENTATION ,
X , Y , Z , THETA ,
PHI , PSI , DX , DY ,
DZ , DTHETA , DPHI , DPSI ,
OUTFN , DELETEONTRANSVERSEEXIT , COMMON
}
The common attributes for all elements.
enum ReferenceType { IS_ENTRY , IS_CENTRE , IS_EXIT }
Reference for element positioning.
Public Member Functions
OpalBend (const char *name, const char *help)
Exemplar constructor.
virtual ~OpalBend ()
virtual void print (std::ostream &) const
Print the bend magnet.
virtual double getLength () const
Return element length.
const std::string getTypeName () const
Return the element's type name.
std::pair< ApertureType, std::vector< double > > getApert () const
const std::string getWakeF () const
Return the element's type name.
const std::string getParticleMatterInteraction () const
const std::string getWMaterial () const
const std::string getWakeGeom () const
std::vector< double > getWakeParam () const
const std::string getWakeConductivity () const
virtual void parse (Statement &)
Parse the element.
virtual void update ()
Update the embedded OPALX element.
virtual void updateUnknown (ElementBase *)
Transmit the `‘unknown’' (not known to OPALX) attributes to OPALX.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual double getEntrance (ReferenceType) const
Return arc length from origin to entrance (negative !).
virtual double getExit (ReferenceType) const
Return arc length from origin to exit (positive !).
virtual void setShared (bool)
Set shared flag.
ElementBase * getElement () const
Return the embedded OPALX element.
std::shared_ptr< ElementBase > getElementPtr () const
Return the embedded OPALX element as shared_ptr.
void setElement (ElementBase *)
Assign new OPALX element.
void setElement (std::shared_ptr< ElementBase > base)
virtual Object * clone (const std::string &name)=0
Return a clone.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
Static Public Member Functions
static Element * find (const std::string &name)
Find named Element.
Public Attributes
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions
OpalBend (const std::string &name, OpalBend *parent)
Clone constructor.
void registerOwnership () const
Static Protected Member Functions
static void printMultipoleStrength (std::ostream &os, int order, int &len, const std::string &sName, const std::string &tName, const Attribute &length, const Attribute &vNorm, const Attribute &vSkew)
Print multipole components in OPAL-8 format.
static void printAttribute (std::ostream &os, const std::string &name, const std::string &image, int &len)
Print an attribute with a OPAL-8 name (as an expression).
static void printAttribute (std::ostream &os, const std::string &name, double value, int &len)
Print an attribute with a OPAL-8 name (as a constant).
Protected Attributes
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Private Member Functions
OpalBend (const OpalBend &)
void operator= (const OpalBend &)
Private Attributes
int itsSize
std::shared_ptr< ElementBase > itsOPALXElement
Object * itsParent
std::string itsName
std::string itsHelp
int occurrence
double timeStamp
std::set< Invalidator * > references
bool sharedFlag
Detailed Description
Base class for all bending magnets.
Definition at line 29 of file OpalBend.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
The attribute numbers for OPAL bend magnets.
Enumerator
ANGLE
K0
K0S
K1
K1S
K2
K2S
K3
K3S
E1
E2
H1
H2
HGAP
FINT
SLICES
STEPSIZE
FMAPFN
GAP
HAPERT
ROTATION
DESIGNENERGY
GREATERTHANPI
NSLICES
SIZE
Definition at line 32 of file OpalBend.h.
anonymous enum
anonymous enum inherited
The common attributes for all elements.
Enumerator
TYPE
APERT
LENGTH
ELEMEDGE
WAKEF
PARTICLEMATTERINTERACTION
ORIGIN
ORIENTATION
X
Y
Z
THETA
PHI
PSI
DX
DY
DZ
DTHETA
DPHI
DPSI
OUTFN
DELETEONTRANSVERSEEXIT
COMMON
Definition at line 34 of file OpalElement.h.
ReferenceType
enum Element::ReferenceType inherited
Reference for element positioning.
Enumerator
IS_ENTRY
IS_CENTRE
IS_EXIT
Definition at line 43 of file Element.h.
Constructor & Destructor Documentation
OpalBend() [1/3]
OpalBend::OpalBend (const char * name, const char * help)
Exemplar constructor.
Definition at line 29 of file OpalBend.cpp.
References ANGLE, DESIGNENERGY, E1, E2, FINT, FMAPFN, GAP, GREATERTHANPI, H1, H2, HAPERT, HGAP, Object::itsAttr, K0, K0S, K1, K1S, K2, K2S, K3, K3S, Attributes::makeBool(), Attributes::makeReal(), Attributes::makeString(), NSLICES, OpalElement::OpalElement(), ROTATION, SIZE, SLICES, and STEPSIZE.
Referenced by OpalBend(), OpalBend(), OpalRBend::OpalRBend(), OpalRBend::OpalRBend(), OpalSBend::OpalSBend(), OpalSBend::OpalSBend(), and operator=().
~OpalBend()
OpalBend::~OpalBend () virtual
Definition at line 61 of file OpalBend.cpp.
OpalBend() [2/3]
OpalBend::OpalBend (const std::string & name, OpalBend * parent) protected
Clone constructor.
Definition at line 59 of file OpalBend.cpp.
References OpalBend(), and OpalElement::OpalElement().
OpalBend() [3/3]
OpalBend::OpalBend (const OpalBend &) private
References OpalBend().
Member Function Documentation
canReplaceBy()
bool Element::canReplaceBy (Object * object) virtual inherited
Test if replacement is allowed.
Reimplemented from Object.
Definition at line 37 of file Element.cpp.
References Element(), and Object::Object().
clear()
void Object::clear () inherited
Clear the occurrence counter.
Definition at line 285 of file Object.cpp.
References occurrence.
clone()
virtual Object * Object::clone (const std::string & name) pure virtual inherited
Return a clone.
Implemented in Beam, BinningCmd, BoolConstant, BoundaryGeometry, Call, Distribution, DumpEMFields, Echo, EmissionSource, EmissionSourceList, FieldSolverCmd, Help, Line, LineTemplate, Macro, OpalCavity, OpalConstantEFieldCavity, OpalDrift, OpalFilter, OpalLaser, OpalMarker, OpalMonitor, OpalMultipole, OpalMultipoleT, OpalPolynomialTimeDependence, OpalProbe, OpalQuadrupole, OpalRBend, OpalRingDefinition, OpalSBend, OpalSinusoidalTimeDependence, OpalSolenoid, OpalSource, OpalSplineTimeDependence, OpalTravelingWave, OpalVacuum, OpalVariableRFCavity, OpalVerticalFFAMagnet, Option, PSystem, Quit, RealConstant, RealVariable, RealVector, Select, Sequence, SequenceTemplate, Stop, StringConstant, System, Title, TrackCmd, TrackEnd, TrackRun, and Value.
References Object().
Referenced by OpalParser::parseAction(), OpalParser::parseAssign(), and OpalParser::parseDefine().
copyAttributes()
void Object::copyAttributes (const Object & source) inherited
Copy attributes from another object.
Definition at line 50 of file Object.cpp.
References itsAttr, and Object().
Referenced by LineTemplate::makeInstance(), and SequenceTemplate::makeInstance().
execute()
void Object::execute () virtual inherited
Execute the command.
Reimplemented in Beam, BinningCmd, BoundaryGeometry, Call, Distribution, DumpEMFields, Echo, EmissionSource, EmissionSourceList, FieldSolverCmd, Help, MacroCmd, OpalFilter, Option, PSystem, Quit, Select, Stop, System, Title, TrackCmd, TrackEnd, TrackRun, and Value.
Definition at line 52 of file Object.cpp.
find()
Element * Element::find (const std::string & name) static inherited
Find named Element.
Definition at line 39 of file Element.cpp.
References Element(), OpalData::find(), and OpalData::getInstance().
Referenced by Sequence::addEndMarkers(), SequenceParser::findNeighbourPositions(), Selector::handleElement(), Line::parse(), Selector::Selector(), and Sequence::storeLine().
findAttribute() [1/2]
Attribute * Object::findAttribute (const std::string & name) virtual inherited
Find an attribute by name.
Definition at line 56 of file Object.cpp.
References itsAttr.
Referenced by OpalElement::getParticleMatterInteraction(), OpalElement::getTypeName(), OpalElement::getWakeF(), Line::parse(), parse(), OpalElement::parse(), OpalParser::parseAssign(), SequenceParser::parsePosition(), TrackRun::print(), and TEST().
findAttribute() [2/2]
const Attribute * Object::findAttribute (const std::string & name) const virtual inherited
Find an attribute by name.
Definition at line 63 of file Object.cpp.
References itsAttr.
getApert()
std::pair< ApertureType, std::vector< double > > OpalElement::getApert () const inherited
Definition at line 103 of file OpalElement.cpp.
References APERT, CONIC_ELLIPTICAL, CONIC_RECTANGULAR, ELLIPTICAL, Attributes::getString(), Object::itsAttr, and RECTANGULAR.
Referenced by update().
getBaseObject()
const Object * Object::getBaseObject () const inherited
Return the object's base type object.
Definition at line 260 of file Object.cpp.
References itsParent, and Object().
getCategory()
const std::string Element::getCategory () const virtual inherited
Return the object category as a string.
Implements Object.
Reimplemented in BeamSequence.
Definition at line 48 of file Element.cpp.
getElement()
ElementBase * Element::getElement () const inline inherited
Return the embedded OPALX element.
Definition at line 119 of file Element.h.
References itsOPALXElement.
Referenced by Line::fetchLine(), Sequence::fetchLine(), OpalMarker::OpalMarker(), OpalVariableRFCavity::OpalVariableRFCavity(), Line::replace(), Sequence::replace(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), OpalCavity::update(), OpalConstantEFieldCavity::update(), OpalDrift::update(), OpalElement::update(), OpalLaser::update(), OpalMarker::update(), OpalMonitor::update(), OpalMultipole::update(), OpalMultipoleT::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalRBend::update(), OpalRingDefinition::update(), OpalSBend::update(), OpalSolenoid::update(), OpalTravelingWave::update(), OpalVacuum::update(), OpalVariableRFCavity::update(), and OpalVerticalFFAMagnet::update().
getElementPtr()
std::shared_ptr< ElementBase > Element::getElementPtr () const inline inherited
Return the embedded OPALX element as shared_ptr.
Definition at line 121 of file Element.h.
References itsOPALXElement.
Referenced by Sequence::addEndMarkers(), and Line::parse().
getEntrance()
double Element::getEntrance (ReferenceType ref) const virtual inherited
Return arc length from origin to entrance (negative !).
Reimplemented in Sequence.
Definition at line 54 of file Element.cpp.
References getLength(), IS_CENTRE, and IS_EXIT.
Referenced by Sequence::getEntrance().
getExit()
double Element::getExit (ReferenceType ref) const virtual inherited
Return arc length from origin to exit (positive !).
Reimplemented in Sequence.
Definition at line 67 of file Element.cpp.
References getLength(), IS_CENTRE, and IS_ENTRY.
Referenced by Sequence::getExit().
getLength()
double OpalElement::getLength () const virtual inherited
Return element length.
Implements Element.
Definition at line 277 of file OpalElement.cpp.
References Attributes::getReal(), Object::itsAttr, and LENGTH.
Referenced by OpalConstantEFieldCavity::update(), OpalMultipole::update(), and OpalQuadrupole::update().
getOpalName()
const std::string & Object::getOpalName () const inherited
Return object name.
Definition at line 267 of file Object.cpp.
References itsName.
Referenced by Macro::clone(), OpalVariableRFCavity::clone(), OpalData::create(), OpalData::define(), Sequence::findDriftLength(), ValueDefinition::getBool(), ValueDefinition::getBoolComponent(), ValueDefinition::getReal(), ValueDefinition::getRealComponent(), ValueDefinition::getString(), ValueDefinition::getStringComponent(), LineTemplate::makeInstance(), makeInstance(), SequenceTemplate::makeInstance(), parse(), SequenceParser::parsePosition(), Beam::print(), BoolConstant::print(), Line::print(), print(), OpalElement::print(), OpalFilter::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), Sequence::print(), StringConstant::print(), TrackRun::print(), BinningCmd::printInfo(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), registerOwnership(), OpalElement::registerOwnership(), Line::replace(), Sequence::replace(), PartBunch< T, Dim >::setBins(), TEST(), TEST(), TEST(), TEST_F(), Beam::update(), BoundaryGeometry::update(), OpalFilter::update(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), and OpalSplineTimeDependence::update().
getParent()
Object * Object::getParent () const inherited
Return parent pointer.
Definition at line 269 of file Object.cpp.
References itsParent, and Object().
Referenced by OpalData::erase(), print(), OpalElement::print(), registerOwnership(), and OpalElement::registerOwnership().
getParticleMatterInteraction()
const std::string OpalElement::getParticleMatterInteraction () const inherited
Definition at line 292 of file OpalElement.cpp.
References Object::findAttribute(), and Attributes::getString().
getTypeName()
const std::string OpalElement::getTypeName () const inherited
Return the element's type name.
Definition at line 279 of file OpalElement.cpp.
References Object::findAttribute(), and Attributes::getString().
Referenced by Selector::handleElement().
getWakeConductivity()
const std::string OpalElement::getWakeConductivity () const inherited
References OpalElement().
getWakeF()
const std::string OpalElement::getWakeF () const inherited
Return the element's type name.
Functions to get the wake field parametes
Definition at line 287 of file OpalElement.cpp.
References Object::findAttribute(), and Attributes::getString().
getWakeGeom()
const std::string OpalElement::getWakeGeom () const inherited
getWakeParam()
std::vector< double > OpalElement::getWakeParam () const inherited
getWMaterial()
const std::string OpalElement::getWMaterial () const inherited
increment()
int Object::increment () inherited
Increment and return the occurrence counter.
Definition at line 287 of file Object.cpp.
References occurrence.
Referenced by Line::parse(), and Sequence::storeLine().
isBuiltin()
bool Object::isBuiltin () const inherited
True, if [b]this[/b] is a built-in object.
Definition at line 243 of file Object.cpp.
References builtin.
Referenced by OpalData::define(), and OpalData::getVariableNames().
isDirty()
bool Object::isDirty () const inherited
True, if the [b]modified[/b] flag is set.
Definition at line 254 of file Object.cpp.
References modified.
isFlagged()
bool Object::isFlagged () const inherited
True, if [b]this[/b] is flagged by setFlag(true).
Definition at line 258 of file Object.cpp.
References flagged.
isShared()
bool Object::isShared () const virtual inherited
Shared flag.
Definition at line 245 of file Object.cpp.
References sharedFlag.
Referenced by Sequence::print().
isTreeMember()
bool Object::isTreeMember (const Object * subTree) const inherited
Test for tree membership.
Definition at line 271 of file Object.cpp.
References Object().
Referenced by Selector::handleElement(), and OpalParser::parseAssign().
makeInstance()
Object * Object::makeInstance (const std::string & name, Statement & , const Parser *) virtual inherited
Macro handler function.
Reimplemented in LineTemplate, MacroCmd, and SequenceTemplate.
Definition at line 76 of file Object.cpp.
References getOpalName(), and Object().
Referenced by OpalParser::parseDefine(), and OpalParser::parseMacro().
makeTemplate()
Object * Object::makeTemplate (const std::string & name, TokenStream & , Statement &) virtual inherited
Macro handler function.
Reimplemented in Line, LineTemplate, MacroCmd, Sequence, and SequenceTemplate.
Definition at line 71 of file Object.cpp.
References Object().
Referenced by OpalParser::parseMacro().
occurrenceCount()
int Object::occurrenceCount () inherited
Return the occurrence counter.
Definition at line 289 of file Object.cpp.
References occurrence.
operator=()
void OpalBend::operator= (const OpalBend &) private
References OpalBend().
parse()
void OpalElement::parse (Statement & stat) virtual inherited
Parse the element.
Reimplemented from Object.
Definition at line 297 of file OpalElement.cpp.
References Statement::delimiter(), Object::findAttribute(), Attribute::parse(), Attribute::parseComponent(), Expressions::parseDelimiter(), Expressions::parseRealConst(), Expressions::parseString(), and Attribute::setDefault().
parseShortcut()
void Object::parseShortcut (Statement & stat, bool eval = true) virtual inherited
Parser for single-attribute commands.
Definition at line 113 of file Object.cpp.
Referenced by Call::parse(), Echo::parse(), Help::parse(), PSystem::parse(), System::parse(), Title::parse(), and Value::parse().
print()
void OpalBend::print (std::ostream & os) const virtual
Print the bend magnet.
Reimplemented from OpalElement.
Definition at line 63 of file OpalBend.cpp.
References OpalElement::print().
printAttribute() [1/2]
void OpalElement::printAttribute (std::ostream & os, const std::string & name, const std::string & image, int & len) static protected inherited
Print an attribute with a OPAL-8 name (as an expression).
Definition at line 540 of file OpalElement.cpp.
Referenced by printAttribute(), and printMultipoleStrength().
printAttribute() [2/2]
void OpalElement::printAttribute (std::ostream & os, const std::string & name, double value, int & len) static protected inherited
Print an attribute with a OPAL-8 name (as a constant).
Definition at line 552 of file OpalElement.cpp.
References printAttribute().
printHelp()
void Object::printHelp (std::ostream &) const virtual inherited
Print help.
Definition at line 179 of file Object.cpp.
References gmsg, itsAttr, and itsHelp.
Referenced by Help::execute(), and main().
printMultipoleStrength()
void OpalElement::printMultipoleStrength (std::ostream & os, int order, int & len, const std::string & sName, const std::string & tName, const Attribute & length, const Attribute & vNorm, const Attribute & vSkew) static protected inherited
Print multipole components in OPAL-8 format.
Definition at line 343 of file OpalElement.cpp.
References Attribute::getBase(), Attribute::getImage(), Attributes::getReal(), AttributeBase::isExpression(), Physics::pi, and printAttribute().
printValue()
void Object::printValue (std::ostream & os) const inline virtual inherited
Reimplemented in BoolConstant, RealConstant, RealVariable, RealVector, and StringConstant.
Definition at line 270 of file Object.h.
References print().
registerOwnership() [1/2]
void Object::registerOwnership (const AttributeHandler::OwnerType & itsClass) const inherited
Definition at line 169 of file Object.cpp.
References AttributeHandler::addAttributeOwner(), getOpalName(), getParent(), and itsAttr.
Referenced by Beam::Beam(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), Call::Call(), Distribution::Distribution(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), EmissionSourceList::EmissionSourceList(), Help::Help(), Line::Line(), OpalFilter::OpalFilter(), Option::Option(), PSystem::PSystem(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVector::RealVector(), Select::Select(), Sequence::Sequence(), StringConstant::StringConstant(), System::System(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), and Value::Value().
registerOwnership() [2/2]
void OpalElement::registerOwnership () const protected inherited
Definition at line 559 of file OpalElement.cpp.
References AttributeHandler::addAttributeOwner(), COMMON, AttributeHandler::ELEMENT, Object::getOpalName(), Object::getParent(), Object::itsAttr, and itsSize.
Referenced by OpalCavity::OpalCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalDrift::OpalDrift(), OpalLaser::OpalLaser(), OpalMonitor::OpalMonitor(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalPolynomialTimeDependence::OpalPolynomialTimeDependence(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalRBend::OpalRBend(), OpalRingDefinition::OpalRingDefinition(), OpalSBend::OpalSBend(), OpalSinusoidalTimeDependence::OpalSinusoidalTimeDependence(), OpalSolenoid::OpalSolenoid(), OpalSplineTimeDependence::OpalSplineTimeDependence(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), and OpalVerticalFFAMagnet::OpalVerticalFFAMagnet().
registerReference()
void Object::registerReference (Invalidator * a) inherited
Register a reference to this object.
Definition at line 165 of file Object.cpp.
References references.
replace()
void Object::replace (Object * oldObject, Object * newObject) virtual inherited
Replace references.
Reimplemented in Line, and Sequence.
Definition at line 235 of file Object.cpp.
References Object().
setDirty()
void Object::setDirty (bool dirty) inherited
Set/reset the [b]modified[/b] flag.
Definition at line 249 of file Object.cpp.
References modified.
Referenced by OpalData::define(), OpalData::makeDirty(), and RealVariable::RealVariable().
setElement() [1/2]
void Element::setElement (ElementBase * base) inline inherited
Assign new OPALX element.
Definition at line 123 of file Element.h.
References itsOPALXElement.
Referenced by Line::Line(), Line::Line(), OpalCavity::OpalCavity(), OpalCavity::OpalCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalDrift::OpalDrift(), OpalDrift::OpalDrift(), OpalLaser::OpalLaser(), OpalLaser::OpalLaser(), OpalMarker::OpalMarker(), OpalMarker::OpalMarker(), OpalMonitor::OpalMonitor(), OpalMonitor::OpalMonitor(), OpalMultipole::OpalMultipole(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalMultipoleT::OpalMultipoleT(), OpalProbe::OpalProbe(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalQuadrupole::OpalQuadrupole(), OpalRBend::OpalRBend(), OpalRBend::OpalRBend(), OpalRingDefinition::OpalRingDefinition(), OpalRingDefinition::OpalRingDefinition(), OpalSBend::OpalSBend(), OpalSBend::OpalSBend(), OpalSolenoid::OpalSolenoid(), OpalSolenoid::OpalSolenoid(), OpalTravelingWave::OpalTravelingWave(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), Sequence::Sequence(), Sequence::Sequence(), and OpalVariableRFCavity::update().
setElement() [2/2]
void Element::setElement (std::shared_ptr< ElementBase > base) inline inherited
Definition at line 130 of file Element.h.
References itsOPALXElement.
setFlag()
void Object::setFlag (bool flag) inherited
Flag/unflag this object, e. g. to control output of objects for.
Definition at line 256 of file Object.cpp.
References flagged.
setOpalName()
void Object::setOpalName (const std::string & name) inherited
Set object name.
Definition at line 281 of file Object.cpp.
References itsName.
Referenced by TEST(), TEST(), TEST(), Beam::update(), BoundaryGeometry::update(), and OpalFilter::update().
setParent()
void Object::setParent (Object * parent) inherited
Set parent object.
Definition at line 283 of file Object.cpp.
References itsParent, and Object().
Referenced by OpalData::erase().
setShared()
void Element::setShared (bool flag) virtual inherited
Set shared flag.
Reimplemented from Object.
Definition at line 80 of file Element.cpp.
References itsOPALXElement, and Object::setShared().
shouldTrace()
bool Element::shouldTrace () const virtual inherited
Trace flag.
Implements Object.
Definition at line 50 of file Element.cpp.
shouldUpdate()
bool Element::shouldUpdate () const virtual inherited
Update flag.
Implements Object.
Definition at line 52 of file Element.cpp.
unregisterReference()
void Object::unregisterReference (Invalidator * a) inherited
Unegister a reference to this object.
Definition at line 167 of file Object.cpp.
References references.
update()
void OpalElement::update () virtual inherited
Update the embedded OPALX element.
Reimplemented from Object.
Reimplemented in OpalCavity, OpalConstantEFieldCavity, OpalDrift, OpalLaser, OpalMarker, OpalMonitor, OpalMultipole, OpalMultipoleT, OpalPolynomialTimeDependence, OpalProbe, OpalQuadrupole, OpalRBend, OpalRingDefinition, OpalSBend, OpalSinusoidalTimeDependence, OpalSolenoid, OpalSource, OpalSplineTimeDependence, OpalTravelingWave, OpalVacuum, OpalVariableRFCavity, and OpalVerticalFFAMagnet.
Definition at line 445 of file OpalElement.cpp.
References Quaternion::conjugate(), DELETEONTRANSVERSEEXIT, DPHI, DPSI, DTHETA, DX, DY, DZ, ELEMEDGE, ElementBase::fixPosition(), getApert(), Attributes::getBool(), Element::getElement(), Attributes::getReal(), Attributes::getRealArray(), Object::itsAttr, ORIENTATION, ORIGIN, PHI, PSI, ElementBase::setAperture(), ElementBase::setCSTrafoGlobal2Local(), ElementBase::setElementPosition(), ElementBase::setFlagDeleteOnTransverseExit(), ElementBase::setMisalignment(), ElementBase::setRotationAboutZ(), THETA, X, Y, and Z.
Referenced by OpalCavity::update(), OpalConstantEFieldCavity::update(), OpalDrift::update(), OpalLaser::update(), OpalMonitor::update(), OpalMultipole::update(), OpalMultipoleT::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalRBend::update(), OpalRingDefinition::update(), OpalSBend::update(), OpalSolenoid::update(), OpalTravelingWave::update(), OpalVacuum::update(), and OpalVariableRFCavity::update().
updateUnknown()
void OpalElement::updateUnknown (ElementBase * base) virtual inherited
Transmit the `‘unknown’' (not known to OPALX) attributes to OPALX.
Definition at line 533 of file OpalElement.cpp.
References Attribute::getName(), Attributes::getReal(), Object::itsAttr, itsSize, and ElementBase::setAttribute().
Referenced by OpalCavity::update(), OpalConstantEFieldCavity::update(), OpalDrift::update(), OpalLaser::update(), OpalMarker::update(), OpalMonitor::update(), OpalMultipole::update(), OpalMultipoleT::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalRBend::update(), OpalRingDefinition::update(), OpalSBend::update(), OpalSolenoid::update(), OpalTravelingWave::update(), and OpalVacuum::update().
Member Data Documentation
builtin
bool Object::builtin protected inherited
Built-in flag.
Definition at line 226 of file Object.h.
Referenced by Beam::Beam(), BoundaryGeometry::BoundaryGeometry(), isBuiltin(), Object(), Object(), OpalFilter::OpalFilter(), OpalMarker::OpalMarker(), RealConstant::RealConstant(), StringConstant::StringConstant(), and Table::~Table().
flagged
bool Object::flagged protected inherited
Object flag.
Definition at line 235 of file Object.h.
Referenced by isFlagged(), Object(), Object(), and setFlag().
itsAttr
std::vector<Attribute> Object::itsAttr inherited
The object attributes.
Definition at line 210 of file Object.h.
Referenced by Beam::Beam(), BinningCmd::BinningCmd(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), BoundaryGeometry::BoundaryGeometry(), DumpEMFields::buildGrid(), Call::Call(), FieldSolverCmd::constructBCHandler(), copyAttributes(), Distribution::Distribution(), BinningCmd::dumpBinsToFile(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), Beam::execute(), Call::execute(), Echo::execute(), Help::execute(), Option::execute(), PSystem::execute(), Select::execute(), System::execute(), Title::execute(), TrackCmd::execute(), TrackRun::execute(), Value::execute(), FieldSolverCmd::FieldSolverCmd(), findAttribute(), findAttribute(), BoundaryGeometry::getA(), OpalElement::getApert(), BoundaryGeometry::getB(), BinningCmd::getBinningAlpha(), BinningCmd::getBinningBeta(), FieldSolverCmd::getBinsName(), BoolConstant::getBool(), FieldSolverCmd::getBoxIncr(), Beam::getBunchCharge(), BoundaryGeometry::getC(), Beam::getCharge(), Beam::getCurrent(), Beam::getDaughterBeamName(), BinningCmd::getDesiredWidth(), EmissionSource::getDistributionName(), FieldSolverCmd::getDomDec(), TrackCmd::getDT(), TrackCmd::getDTAU(), TrackCmd::getDTSCINIT(), BinningCmd::getDumpBinsFileName(), BinningCmd::getDumpBinsFrequency(), EmissionSource::getEmissionModel(), Beam::getEmissionSourceListName(), BoundaryGeometry::getFilename(), Distribution::getFilename(), Beam::getFrequency(), Beam::getGlobalProcessNames(), BoundaryGeometry::getL1(), BoundaryGeometry::getL2(), BoundaryGeometry::getLength(), Line::getLength(), OpalElement::getLength(), Sequence::getLength(), Beam::getMass(), BinningCmd::getMaxBins(), TrackCmd::getMaxSteps(), Beam::getNumAlloc(), FieldSolverCmd::getNX(), FieldSolverCmd::getNY(), FieldSolverCmd::getNZ(), EmissionSource::getP0(), BinningCmd::getParameter(), Beam::getParticleName(), EmissionSource::getR0(), RealConstant::getReal(), RealVariable::getReal(), RealVector::getRealComponent(), Sequence::getReference(), BoundaryGeometry::getS(), EmissionSource::getShiftedGreensFunction(), TrackCmd::getStepsPerTurn(), StringConstant::getString(), EmissionSource::getT0(), TrackCmd::getT0(), BinningCmd::getTablePrintFrequency(), TrackCmd::getTimeIntegrator(), BoundaryGeometry::getTopology(), FieldSolverCmd::getType(), EmissionSource::getZerofaceMaxSteps(), EmissionSource::getZeroFacePlaneDumpFrequency(), EmissionSource::getZeroFaceR0Z(), TrackCmd::getZStart(), TrackCmd::getZStop(), Beam::hasExplicitEnergy(), Help::Help(), BoundaryGeometry::initialize(), OpalFilter::initOpalFilter(), Beam::isPhoton(), Line::Line(), Object(), Object(), OpalBend::OpalBend(), OpalCavity::OpalCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalDrift::OpalDrift(), OpalElement::OpalElement(), OpalFilter::OpalFilter(), OpalLaser::OpalLaser(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalPolynomialTimeDependence::OpalPolynomialTimeDependence(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalRingDefinition::OpalRingDefinition(), OpalSinusoidalTimeDependence::OpalSinusoidalTimeDependence(), OpalSolenoid::OpalSolenoid(), OpalSplineTimeDependence::OpalSplineTimeDependence(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), Option::Option(), Option::Option(), Line::parse(), Sequence::parse(), DumpEMFields::parseCoordinateSystem(), Beam::print(), BoolConstant::print(), DumpEMFields::print(), print(), OpalFilter::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), Sequence::print(), StringConstant::print(), printHelp(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), BoolConstant::printValue(), RealConstant::printValue(), RealVariable::printValue(), RealVector::printValue(), StringConstant::printValue(), PSystem::PSystem(), RealConstant::RealConstant(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVariable::RealVariable(), RealVector::RealVector(), registerOwnership(), OpalElement::registerOwnership(), Select::Select(), Select::select(), Sequence::Sequence(), Distribution::setAttributes(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCX(), OrbitThreaderTest::TestableFieldSolverCmd::setBCX(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCX(), TestMultipoleT::TestableFieldSolverCmd::setBCX(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCX(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCX(), TestVariableRFCavity::TestableFieldSolverCmd::setBCX(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCY(), OrbitThreaderTest::TestableFieldSolverCmd::setBCY(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCY(), TestMultipoleT::TestableFieldSolverCmd::setBCY(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCY(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCY(), TestVariableRFCavity::TestableFieldSolverCmd::setBCY(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCZ(), OrbitThreaderTest::TestableFieldSolverCmd::setBCZ(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCZ(), TestMultipoleT::TestableFieldSolverCmd::setBCZ(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCZ(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCZ(), TestVariableRFCavity::TestableFieldSolverCmd::setBCZ(), TestableBinningCmd::setBinningAlpha(), TestableBinningCmd::setBinningBeta(), TestableBinningCmd::setDesiredWidth(), Distribution::setDistParametersFlatTop(), Distribution::setDistParametersMultiVariateGauss(), Distribution::setDistType(), TestableBinningCmd::setDumpBinsFile(), TestableBinningCmd::setDumpBinsFreq(), TestableBinningCmd::setMaxBins(), FieldSolverCmd::setNX(), FieldSolverCmd::setNY(), FieldSolverCmd::setNZ(), TestableBinningCmd::setParameterString(), TrackRun::setRunMethod(), Distribution::setSigmaP_m(), Distribution::setSigmaR_m(), TestableBinningCmd::setTablePrintFrequency(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setType(), OrbitThreaderTest::TestableFieldSolverCmd::setType(), SolenoidPlacementTest::TestableFieldSolverCmd::setType(), TestMultipoleT::TestableFieldSolverCmd::setType(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setType(), TestMultipoleTStraight::TestableFieldSolverCmd::setType(), TestVariableRFCavity::TestableFieldSolverCmd::setType(), TrackRun::setupBoundaryGeometry(), StringConstant::StringConstant(), StringConstant::StringConstant(), System::System(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), Beam::update(), BinningCmd::update(), FieldSolverCmd::update(), OpalCavity::update(), OpalConstantEFieldCavity::update(), OpalDrift::update(), OpalElement::update(), OpalLaser::update(), OpalMonitor::update(), OpalMultipole::update(), OpalMultipoleT::update(), OpalPolynomialTimeDependence::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalRBend::update(), OpalRingDefinition::update(), OpalSBend::update(), OpalSinusoidalTimeDependence::update(), OpalSolenoid::update(), OpalSplineTimeDependence::update(), OpalTravelingWave::update(), OpalVacuum::update(), OpalVariableRFCavity::update(), OpalVerticalFFAMagnet::update(), Option::update(), OpalElement::updateUnknown(), Value::Value(), ValueDefinition::value(), and ValueDefinition::value().
itsHelp
std::string Object::itsHelp private inherited
Definition at line 250 of file Object.h.
Referenced by Object(), Object(), and printHelp().
itsName
std::string Object::itsName private inherited
Definition at line 247 of file Object.h.
Referenced by getOpalName(), Object(), Object(), and setOpalName().
itsOPALXElement
std::shared_ptr<ElementBase> Element::itsOPALXElement private inherited
Definition at line 113 of file Element.h.
Referenced by getElement(), getElementPtr(), setElement(), setElement(), and setShared().
itsParent
Object* Object::itsParent private inherited
Definition at line 244 of file Object.h.
Referenced by getBaseObject(), getParent(), Object(), Object(), and setParent().
itsSize
int OpalElement::itsSize private inherited
Definition at line 129 of file OpalElement.h.
Referenced by OpalElement(), OpalElement(), registerOwnership(), and updateUnknown().
modified
bool Object::modified protected inherited
Dirty flag.
Definition at line 231 of file Object.h.
Referenced by isDirty(), Object(), Object(), and setDirty().
occurrence
int Object::occurrence private inherited
Definition at line 253 of file Object.h.
Referenced by clear(), increment(), Object(), Object(), and occurrenceCount().
references
std::set<Invalidator*> Object::references private inherited
Definition at line 260 of file Object.h.
Referenced by registerReference(), unregisterReference(), and ~Object().
sharedFlag
bool Object::sharedFlag private inherited
Definition at line 263 of file Object.h.
Referenced by isShared(), Object(), Object(), and setShared().
timeStamp
double Object::timeStamp private inherited
Definition at line 256 of file Object.h.
The documentation for this class was generated from the following files:
OpalBend.h
OpalBend.cpp