OPALX (Object Oriented Parallel Accelerator Library for Exascal): AbstractTracker Class Reference
AbstractTracker Class Reference
Track particles or bunches.
#include <AbstractTracker.h>
Public Types
enum {
X , PX , Y , PY ,
T , PT
}
Public Member Functions
AbstractTracker (const Beamline &, bool backBeam, bool backTrack)
Constructor.
virtual ~AbstractTracker ()
void execute () override
Apply the algorithm to the top-level beamline.
void visitComponent (const Component &) override
Apply the algorithm to an arbitrary component.
void visitBeamline (const Beamline &) override
Apply the algorithm to a beam line.
void visitConstantEFieldCavity (const ConstantEFieldCavity &) override
Apply the algorithm to a constant E-field cavity element.
void visitDrift (const Drift &) override
Apply the algorithm to a drift space.
void visitLaser (const Laser &) override
Apply the algorithm to a laser.
void visitFlaggedElmPtr (const FlaggedElmPtr &) override
Apply the algorithm to a FlaggedElmPtr.
void visitMarker (const Marker &) override
Apply the algorithm to a marker.
void visitMonitor (const Monitor &) override
Apply the algorithm to a beam position monitor.
void visitMultipole (const Multipole &) override
Apply the algorithm to a multipole.
void visitMultipoleT (const MultipoleT &) override
Apply the algorithm to an arbitrary multipole.
void visitRBend (const RBend &) override
Apply the algorithm to a rectangular bend.
void visitRing (const Ring &) override
Apply the algorithm to a Ring.
void visitSBend (const SBend &) override
Apply the algorithm to a sector bend.
void visitRFCavity (const RFCavity &) override
Apply the algorithm to a RF cavity.
void visitSolenoid (const Solenoid &) override
Apply the algorithm to a Solenoid.
void visitTravelingWave (const TravelingWave &) override
Apply the algorithm to a traveling wave.
void visitScalingFFAMagnet (const ScalingFFAMagnet &spiral) override
Apply the algorithm to a scaling FFA magnet.
void visitVerticalFFAMagnet (const VerticalFFAMagnet &) override
Apply the algorithm to a vertical FFA magnet.
void visitVariableRFCavity (const VariableRFCavity &) override
Apply the algorithm to a variable RF cavity.
void visitProbe (const Probe &prob) override
Apply the algorithm to a Probe.
Protected Attributes
const Beamline & itsLine
bool back_beam
bool back_track
bool back_path
double flip_B
double flip_s
Private Member Functions
AbstractTracker ()
AbstractTracker (const AbstractTracker &)
void operator= (const AbstractTracker &)
virtual void applyDefault (const ElementBase &)
Private Attributes
bool local_flip
Detailed Description
Track particles or bunches.
Definition at line 33 of file AbstractTracker.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
X
PX
Y
PY
T
PT
Definition at line 36 of file AbstractTracker.h.
Constructor & Destructor Documentation
AbstractTracker() [1/3]
AbstractTracker::AbstractTracker (const Beamline & beamline, bool backBeam, bool backTrack)
Constructor.
Definition at line 33 of file AbstractTracker.cpp.
References DefaultVisitor::DefaultVisitor().
Referenced by AbstractTracker(), operator=(), Tracker::Tracker(), and Tracker::Tracker().
~AbstractTracker()
AbstractTracker::~AbstractTracker () virtual
Definition at line 36 of file AbstractTracker.cpp.
AbstractTracker() [2/3]
AbstractTracker::AbstractTracker () private
AbstractTracker() [3/3]
AbstractTracker::AbstractTracker (const AbstractTracker &) private
References AbstractTracker().
Member Function Documentation
applyDefault()
void DefaultVisitor::applyDefault (const ElementBase &) private virtual inherited
Definition at line 113 of file DefaultVisitor.cpp.
Referenced by visitComponent(), visitConstantEFieldCavity(), visitDrift(), visitLaser(), visitMarker(), visitMonitor(), visitMultipole(), visitMultipoleT(), visitProbe(), visitRBend(), visitRFCavity(), visitRing(), visitSBend(), visitScalingFFAMagnet(), visitSolenoid(), visitTravelingWave(), visitVariableRFCavity(), and visitVerticalFFAMagnet().
execute()
void DefaultVisitor::execute () override virtual inherited
Apply the algorithm to the top-level beamline.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker, RangeSelector, and Selector.
Definition at line 54 of file DefaultVisitor.cpp.
References back_beam, back_track, itsLine, and local_flip.
Referenced by RangeSelector::execute(), Line::replace(), Sequence::replace(), and Select::select().
operator=()
void AbstractTracker::operator= (const AbstractTracker &) private
References AbstractTracker().
visitBeamline()
void DefaultVisitor::visitBeamline (const Beamline & bl) override virtual inherited
Apply the algorithm to a beam line.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 97 of file DefaultVisitor.cpp.
References Beamline::iterate(), and local_flip.
visitComponent()
void DefaultVisitor::visitComponent (const Component &) override virtual inherited
Apply the algorithm to an arbitrary component.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker, and Tracker.
Definition at line 59 of file DefaultVisitor.cpp.
References applyDefault().
visitConstantEFieldCavity()
void DefaultVisitor::visitConstantEFieldCavity (const ConstantEFieldCavity & cav) override virtual inherited
Apply the algorithm to a constant E-field cavity element.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 61 of file DefaultVisitor.cpp.
References applyDefault().
visitDrift()
void DefaultVisitor::visitDrift (const Drift & drf) override virtual inherited
Apply the algorithm to a drift space.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 65 of file DefaultVisitor.cpp.
References applyDefault().
visitFlaggedElmPtr()
void DefaultVisitor::visitFlaggedElmPtr (const FlaggedElmPtr & fep) override virtual inherited
Apply the algorithm to a FlaggedElmPtr.
Implements BeamlineVisitor.
Reimplemented in Flagger, RangeSelector, and Replacer.
Definition at line 103 of file DefaultVisitor.cpp.
References ElementBase::accept(), ElmPtr::getElement(), FlaggedElmPtr::getReflectionFlag(), and local_flip.
Referenced by RangeSelector::handleBeamline(), RangeSelector::handleElement(), Flagger::visitFlaggedElmPtr(), and Replacer::visitFlaggedElmPtr().
visitLaser()
void DefaultVisitor::visitLaser (const Laser & laser) override virtual inherited
Apply the algorithm to a laser.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 67 of file DefaultVisitor.cpp.
References applyDefault().
visitMarker()
void DefaultVisitor::visitMarker (const Marker & mark) override virtual inherited
Apply the algorithm to a marker.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 69 of file DefaultVisitor.cpp.
References applyDefault().
visitMonitor()
void DefaultVisitor::visitMonitor (const Monitor & mon) override virtual inherited
Apply the algorithm to a beam position monitor.
Implements BeamlineVisitor.
Definition at line 71 of file DefaultVisitor.cpp.
References applyDefault().
visitMultipole()
void DefaultVisitor::visitMultipole (const Multipole & mult) override virtual inherited
Apply the algorithm to a multipole.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 73 of file DefaultVisitor.cpp.
References applyDefault().
visitMultipoleT()
void DefaultVisitor::visitMultipoleT (const MultipoleT & multT) override virtual inherited
Apply the algorithm to an arbitrary multipole.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 75 of file DefaultVisitor.cpp.
References applyDefault().
visitProbe()
void DefaultVisitor::visitProbe (const Probe & prob) override virtual inherited
Apply the algorithm to a Probe.
Implements BeamlineVisitor.
Definition at line 95 of file DefaultVisitor.cpp.
References applyDefault().
visitRBend()
void DefaultVisitor::visitRBend (const RBend & bend) override virtual inherited
Apply the algorithm to a rectangular bend.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 77 of file DefaultVisitor.cpp.
References applyDefault().
visitRFCavity()
void DefaultVisitor::visitRFCavity (const RFCavity & cav) override virtual inherited
Apply the algorithm to a RF cavity.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 81 of file DefaultVisitor.cpp.
References applyDefault().
visitRing()
void DefaultVisitor::visitRing (const Ring & ring) override virtual inherited
Apply the algorithm to a Ring.
Implements BeamlineVisitor.
Definition at line 79 of file DefaultVisitor.cpp.
References applyDefault().
visitSBend()
void DefaultVisitor::visitSBend (const SBend & bend) override virtual inherited
Apply the algorithm to a sector bend.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 83 of file DefaultVisitor.cpp.
References applyDefault().
visitScalingFFAMagnet()
void DefaultVisitor::visitScalingFFAMagnet (const ScalingFFAMagnet & spiral) override virtual inherited
Apply the algorithm to a scaling FFA magnet.
Implements BeamlineVisitor.
Definition at line 89 of file DefaultVisitor.cpp.
References applyDefault().
visitSolenoid()
void DefaultVisitor::visitSolenoid (const Solenoid & so) override virtual inherited
Apply the algorithm to a Solenoid.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 85 of file DefaultVisitor.cpp.
References applyDefault().
visitTravelingWave()
void DefaultVisitor::visitTravelingWave (const TravelingWave & trw) override virtual inherited
Apply the algorithm to a traveling wave.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 87 of file DefaultVisitor.cpp.
References applyDefault().
visitVariableRFCavity()
void DefaultVisitor::visitVariableRFCavity (const VariableRFCavity & cavity) override virtual inherited
Apply the algorithm to a variable RF cavity.
Implements BeamlineVisitor.
Definition at line 93 of file DefaultVisitor.cpp.
References applyDefault().
visitVerticalFFAMagnet()
void DefaultVisitor::visitVerticalFFAMagnet (const VerticalFFAMagnet & mag) override virtual inherited
Apply the algorithm to a vertical FFA magnet.
Implements BeamlineVisitor.
Definition at line 91 of file DefaultVisitor.cpp.
References applyDefault().
Member Data Documentation
back_beam
bool DefaultVisitor::back_beam protected inherited
Definition at line 110 of file DefaultVisitor.h.
Referenced by DefaultVisitor(), execute(), and Tracker::visitComponent().
back_path
bool DefaultVisitor::back_path protected inherited
Definition at line 112 of file DefaultVisitor.h.
Referenced by DefaultVisitor().
back_track
bool DefaultVisitor::back_track protected inherited
Definition at line 111 of file DefaultVisitor.h.
Referenced by DefaultVisitor(), execute(), and Tracker::visitComponent().
flip_B
double DefaultVisitor::flip_B protected inherited
Definition at line 115 of file DefaultVisitor.h.
Referenced by DefaultVisitor().
flip_s
double DefaultVisitor::flip_s protected inherited
Definition at line 116 of file DefaultVisitor.h.
Referenced by DefaultVisitor().
itsLine
const Beamline& DefaultVisitor::itsLine protected inherited
Definition at line 107 of file DefaultVisitor.h.
Referenced by DefaultVisitor(), and execute().
local_flip
bool DefaultVisitor::local_flip private inherited
Definition at line 130 of file DefaultVisitor.h.
Referenced by DefaultVisitor(), execute(), visitBeamline(), and visitFlaggedElmPtr().
The documentation for this class was generated from the following files:
AbstractTracker.h
AbstractTracker.cpp