OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions::ASUnary< T > Class Template Reference
Expressions::ASUnary< T > Class Template Reference
A scalar expression with one array operand.
#include <ASUnary.h>
Public Member Functions
ASUnary (const TFunction1< T, const std::vector< T > & > &function, PtrToArray< T > &oper)
Constructor.
ASUnary (const ASUnary< T > &)
virtual ~ASUnary ()
virtual Scalar< T > * clone () const
Make clone.
virtual T evaluate () const
Evaluate expression.
virtual void print (std::ostream &, int precedence=99) const
Print expression.
virtual bool isConstant () const
Test for constant.
Static Public Member Functions
static PtrToScalar< T > make (const TFunction1< T, const std::vector< T > & > &function, PtrToArray< T > &oper)
Make new expression.
Private Member Functions
ASUnary ()
void operator= (const ASUnary &)
Private Attributes
const TFunction1< T, const std::vector< T > & > & fun
PtrToArray< T > opr
Detailed Description
template<class T>
class Expressions::ASUnary< T >
A scalar expression with one array operand.
Definition at line 40 of file ASUnary.h.
Constructor & Destructor Documentation
ASUnary() [1/3]
template<class T> Expressions::ASUnary< T >::ASUnary (const TFunction1< T, const std::vector< T > & > & function, PtrToArray< T > & oper) inline
Constructor.
Definition at line 85 of file ASUnary.h.
References fun, and opr.
Referenced by ASUnary(), clone(), make(), and operator=().
ASUnary() [2/3]
template<class T> Expressions::ASUnary< T >::ASUnary (const ASUnary< T > & rhs) inline
Definition at line 81 of file ASUnary.h.
References ASUnary(), clone(), fun, opr, and Expressions::Scalar< T >::Scalar().
~ASUnary()
template<class T> Expressions::ASUnary< T >::~ASUnary () inline virtual
Definition at line 90 of file ASUnary.h.
ASUnary() [3/3]
template<class T> Expressions::ASUnary< T >::ASUnary () private
Member Function Documentation
clone()
template<class T> Scalar< T > * Expressions::ASUnary< T >::clone () const inline virtual
Make clone.
Implements Expressions::Scalar< T >.
Definition at line 93 of file ASUnary.h.
References ASUnary(), and Expressions::Scalar< T >::Scalar().
Referenced by ASUnary().
evaluate()
template<class T> T Expressions::ASUnary< T >::evaluate () const inline virtual
Evaluate expression.
Implements Expressions::Scalar< T >.
Definition at line 98 of file ASUnary.h.
References fun, and opr.
isConstant()
template<class T> bool Expressions::Scalar< T >::isConstant () const inline virtual inherited
Test for constant.
Reimplemented in Expressions::SConstant< T >.
Definition at line 287 of file AbstractObjects/Expressions.h.
make()
template<class T> PtrToScalar< T > Expressions::ASUnary< T >::make (const TFunction1< T, const std::vector< T > & > & function, PtrToArray< T > & oper) inline static
Make new expression.
Definition at line 120 of file ASUnary.h.
References ASUnary(), and Expressions::PtrToScalar< T >::release().
operator=()
template<class T> void Expressions::ASUnary< T >::operator= (const ASUnary< T > &) private
References ASUnary().
print()
template<class T> void Expressions::ASUnary< T >::print (std::ostream & os, int precedence = 99) const inline virtual
Print expression.
Implements Expressions::Scalar< T >.
Definition at line 140 of file ASUnary.h.
References fun, and opr.
Member Data Documentation
fun
template<class T> const TFunction1<T, const std::vector<T>&>& Expressions::ASUnary< T >::fun private
Definition at line 71 of file ASUnary.h.
Referenced by ASUnary(), ASUnary(), evaluate(), and print().
opr
template<class T> PtrToArray<T> Expressions::ASUnary< T >::opr private
Definition at line 74 of file ASUnary.h.
Referenced by ASUnary(), ASUnary(), evaluate(), and print().
The documentation for this class was generated from the following file:
ASUnary.h