OPALX (Object Oriented Parallel Accelerator Library for Exascal): TravelingWaveRep Class Reference
TravelingWaveRep Class Reference
#include <TravelingWaveRep.h>
Public Member Functions
TravelingWaveRep (const std::string &name)
Constructor with given name.
TravelingWaveRep ()
TravelingWaveRep (const TravelingWaveRep &)
virtual ~TravelingWaveRep ()
virtual ElementBase * clone () const
Return clone.
virtual Channel * getChannel (const std::string &aKey, bool=false)
Construct a read/write channel.
virtual AcceleratingField & getField ()
Get field.
virtual const AcceleratingField & getField () const
Get field.
virtual StraightGeometry & getGeometry ()
Get geometry.
virtual const StraightGeometry & getGeometry () const
Get geometry.
virtual double getAmplitude () const
Get amplitude.
virtual double getFrequency () const
Get frequency.
virtual double getPhase () const
Get phase.
virtual void setAmplitude (double V)
Set amplitude.
virtual void setFrequency (double f)
Set frequency.
virtual void setPhase (double phi)
Set phase.
virtual void accept (BeamlineVisitor &) const override
Apply visitor to TravelingWave.
virtual void setPhasem (double phase) override
void setNumCells (int NumCells)
void setMode (double mode)
virtual double getAutoPhaseEstimate (const double &E0, const double &t0, const double &q, const double &m) override
virtual bool apply (const std::shared_ptr< ParticleContainer_t > &pc) override
Applies the Traveling Wave RF Cavity field to all particles inside the RF cavity Note: The field is applied in three regions: the core region, the exit region, and the transition region in between. The field in the transition region is calculated as the superposition of two fields from the core region, which are phase-shifted by 90 degrees and spatially shifted by one cell length. This approach allows for a smooth transition of the field from the core to the exit region, while maintaining the correct phase relationship between the fields.
virtual bool apply (const size_t &i, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
Apply to particle i.
virtual bool apply (const Vector_t< double, 3 > &R, const Vector_t< double, 3 > &P, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
Apply to particle with position R and momentum P.
virtual bool applyToReferenceParticle (const Vector_t< double, 3 > &R, const Vector_t< double, 3 > &P, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
Apply to reference particle with position R and momemtum P.
virtual void initialise (PartBunch_t *bunch, double &startField, double &endField) override
virtual void initialise (PartBunch_t *bunch, std::shared_ptr< AbstractTimeDependence > freq_atd, std::shared_ptr< AbstractTimeDependence > ampl_atd, std::shared_ptr< AbstractTimeDependence > phase_atd) override
virtual void finalise () override
virtual bool bends () const override
virtual void goOnline (const double &kineticEnergy) override
virtual void goOffline () override
virtual ElementType getType () const override
Get element type std::string.
virtual void getFieldExtend (double &zBegin, double &zEnd) const override
Return the field-support interval of the traveling-wave structure.
virtual bool isInside (const Vector_t< double, 3 > &r) const override
virtual void getElementDimensions (double &begin, double &end) const override
Return the nominal body extent of the element.
virtual CoordinateSystemTrafo getEdgeToBegin () const override
virtual CoordinateSystemTrafo getEdgeToEnd () const override
void dropFieldmaps ()
virtual void setFieldMapFN (const std::string &fmapfn)
Set the name of the field map.
virtual std::string getFieldMapFN () const
virtual void setAmplitudem (double vPeak)
virtual double getAmplitudem () const
virtual void setAmplitudeError (double vPeakError)
virtual double getAmplitudeError () const
virtual void setFrequencym (double freq)
virtual double getFrequencym () const
virtual double getPhasem () const
double getPhasem (double t) const
virtual void setPhaseError (double phaseError)
virtual double getPhaseError () const
void setCavityType (const std::string &type)
CavityType getCavityType () const
std::string getCavityTypeString () const
virtual void setFast (bool fast)
virtual bool getFast () const
virtual void setAutophaseVeto (bool veto=true)
virtual bool getAutophaseVeto () const
virtual double getAutoPhaseEstimateFallback (double E0, double t0, double q, double m)
virtual std::pair< double, double > trackOnAxisParticle (const double &p0, const double &t0, const double &dt, const double &q, const double &mass, std::ofstream *out=nullptr)
virtual void setDesignEnergy (const double &ekin, bool changeable=true) override
virtual double getDesignEnergy () const override
void setRmin (double rmin)
virtual double getRmin () const
void setRmax (double rmax)
virtual double getRmax () const
void setAzimuth (double angle)
virtual double getAzimuth () const
void setPerpenDistance (double pdis)
virtual double getPerpenDistance () const
void setGapWidth (double gapwidth)
virtual double getGapWidth () const
void setPhi0 (double phi0)
virtual double getPhi0 () const
virtual double getCosAzimuth () const
virtual double getSinAzimuth () const
virtual double getCycFrequency () const
void getMomentaKick (const double normalRadius, double momentum[], const double t, const double dtCorrt, const int PID, const double restMass, const int chargenumber)
used in OPAL-cycl
double spline (double z, double *za)
void setAmplitudeModel (std::shared_ptr< AbstractTimeDependence > time_dep)
void setAmplitudeModelName (std::string name)
std::string getAmplitudeModelName ()
void setPhaseModel (std::shared_ptr< AbstractTimeDependence > time_dep)
void setPhaseModelName (std::string name)
std::string getPhaseModelName ()
void setFrequencyModel (std::shared_ptr< AbstractTimeDependence > time_dep)
void setFrequencyModelName (std::string name)
std::string getFrequencyModelName ()
virtual double getElementLength () const override
Return the nominal body length of the cavity.
EVector Efield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool getPotential (const Vector_t< double, 3 > &, const double &, Vector_t< double, 3 > &, double &)
Calculate the four-potential at some position relative to the component.
virtual bool Online ()
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunch_t &bunch, const PartData &, bool revBeam, bool revTrack) const
Track a borrowed particle bunch through a non-standard component.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual void setElementLength (double length)
Set design length.
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual Port getEntryPort () const
Return the entrance port of the canonical local chart.
virtual Port getBodyPort () const
Return the body port of the canonical local chart.
virtual Port getExitPort () const
Return the exit port of the canonical local chart.
PlacementPose getPlacementPose () const
Return the nominal rigid placement transform of the element.
void setPlacementPose (const PlacementPose &pose)
Set the nominal rigid placement transform of the element.
Misalignment getPlacementMisalignment () const
Return the local nominal-to-actual correction stored for the element.
ElementGeometry getPlacementGeometry () const
Return the bridge geometry ports assembled from legacy edge state.
SupportPlacement getPlacementSupport () const
Return the support-frame bridge object. The default is the body frame.
PlacedElement getPlacedElement () const
Return a placed-element view assembled from the current bridge objects.
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Static Public Member Functions
static void setIgnore (bool ignore=false)
Set ignore switch.
static std::string getTypeString (ElementType type)
Protected Member Functions
bool isInsideTransverse (const Vector_t< double, 3 > &r) const
Protected Attributes
std::shared_ptr< AbstractTimeDependence > phaseTD_m
std::string phaseName_m
std::shared_ptr< AbstractTimeDependence > amplitudeTD_m
std::string amplitudeName_m
std::shared_ptr< AbstractTimeDependence > frequencyTD_m
std::string frequencyName_m
std::string filename_m
double scale_m
double scaleError_m
double phase_m
double phaseError_m
double frequency_m
bool fast_m
bool autophaseVeto_m
double designEnergy_m
Fieldmap * fieldmap_m
double startField_m
double endField_m
double exit_face_slope_m
PartBunch_t * RefPartBunch_m
bool online_m
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes
static const std::vector< double > defaultAperture_m = std::vector<double>({1e6, 1e6, 1.0})
Private Member Functions
void operator= (const TravelingWaveRep &)
double getdE (const int &i, const int &I, const std::vector< double > &t, const double &phi, const std::vector< std::pair< double, double > > &F) const
double getdT (const int &i, const int &I, const std::vector< double > &E, const std::vector< std::pair< double, double > > &F, const double mass) const
double getdA (const int &i, const int &I, const std::vector< double > &t, const double &phi, const std::vector< std::pair< double, double > > &F) const
double getdB (const int &i, const int &I, const std::vector< double > &t, const double &phi, const std::vector< std::pair< double, double > > &F) const
Private Attributes
StraightGeometry geometry
The cavity's geometry.
AcceleratingField field
The cavity's field.
double scaleCore_m
double scaleCoreError_m
double phaseCore1_m
double phaseCore2_m
double phaseExit_m
double startCoreField_m
double startExitField_m
double mappedStartExitField_m
double periodLength_m
int numCells_m
double cellLength_m
double mode_m
CavityType type_m
double rmin_m
double rmax_m
double angle_m
double sinAngle_m
double cosAngle_m
double pdis_m
double gapwidth_m
double phi0_m
std::unique_ptr< double[]> RNormal_m
std::unique_ptr< double[]> VrNormal_m
std::unique_ptr< double[]> DvDr_m
int num_points_m
std::string elementID
AttributeSet userAttribs
WakeFunction * wake_m
BoundaryGeometry * bgeometry_m
ParticleMatterInteractionHandler * parmatint_m
bool positionIsFixed
std::queue< std::pair< double, double > > actionRange_m
std::string outputfn_m
bool deleteOnTransverseExit_m = true
double elementPosition_m
ELEMEDGE attribute.
bool elemedgeSet_m
Static Private Attributes
static bool ignoreCavities = false
Cavities are ignored (amplitude = 0) when this switch is set.
static const BiMap< CavityType, std::string > bmCavityTypeString_s
static const std::map< ElementType, std::string > elementTypeToString_s
Detailed Description
Definition at line 25 of file TravelingWaveRep.h.
Constructor & Destructor Documentation
TravelingWaveRep() [1/3]
TravelingWaveRep::TravelingWaveRep (const std::string & name) explicit
Constructor with given name.
Definition at line 42 of file TravelingWaveRep.cpp.
References TravelingWave::TravelingWave().
Referenced by operator=(), and TravelingWaveRep().
TravelingWaveRep() [2/3]
TravelingWaveRep::TravelingWaveRep ()
Definition at line 38 of file TravelingWaveRep.cpp.
References TravelingWave::TravelingWave().
Referenced by clone().
TravelingWaveRep() [3/3]
TravelingWaveRep::TravelingWaveRep (const TravelingWaveRep & right)
Definition at line 40 of file TravelingWaveRep.cpp.
References TravelingWave::TravelingWave(), and TravelingWaveRep().
~TravelingWaveRep()
TravelingWaveRep::~TravelingWaveRep () virtual
Definition at line 44 of file TravelingWaveRep.cpp.
Member Function Documentation
accept()
void TravelingWave::accept (BeamlineVisitor & visitor) const override virtual inherited
Apply visitor to TravelingWave.
Reimplemented from RFCavity.
Definition at line 53 of file TravelingWave.cpp.
References BeamlineVisitor::visitTravelingWave().
apply() [1/3]
bool TravelingWave::apply (const size_t & i, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual inherited
Apply to particle i.
Parameters
i Particle index
t Time
E Electric Field
B Magnetic Field
Returns
true if particle is out-of-bounds (lost), false otherwise
Reimplemented from RFCavity.
Definition at line 114 of file TravelingWave.cpp.
References apply(), and Component::RefPartBunch_m.
apply() [2/3]
bool TravelingWave::apply (const std::shared_ptr< ParticleContainer_t > & pc) override virtual inherited
Applies the Traveling Wave RF Cavity field to all particles inside the RF cavity Note: The field is applied in three regions: the core region, the exit region, and the transition region in between. The field in the transition region is calculated as the superposition of two fields from the core region, which are phase-shifted by 90 degrees and spatially shifted by one cell length. This approach allows for a smooth transition of the field from the core to the exit region, while maintaining the correct phase relationship between the fields.
Reimplemented from RFCavity.
Definition at line 66 of file TravelingWave.cpp.
References Astra1DDynamic::applyTravelingWave(), cellLength_m, RFCavity::endField_m, RFCavity::fieldmap_m, RFCavity::frequency_m, mappedStartExitField_m, periodLength_m, RFCavity::phase_m, phaseCore1_m, phaseCore2_m, RFCavity::phaseError_m, phaseExit_m, Component::RefPartBunch_m, RFCavity::scale_m, scaleCore_m, scaleCoreError_m, RFCavity::scaleError_m, startCoreField_m, startExitField_m, and RFCavity::startField_m.
Referenced by apply().
apply() [3/3]
bool TravelingWave::apply (const Vector_t< double, 3 > & R, const Vector_t< double, 3 > & P, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual inherited
Apply to particle with position R and momentum P.
Parameters
R Position
P Momentum
t Time
E Electric Field
B Magnetic Field
Returns
true if particle is out-of-bounds (lost), false otherwise
Reimplemented from RFCavity.
Definition at line 125 of file TravelingWave.cpp.
References cellLength_m, RFCavity::endField_m, RFCavity::fieldmap_m, RFCavity::frequency_m, ElementBase::getFlagDeleteOnTransverseExit(), mappedStartExitField_m, periodLength_m, RFCavity::phase_m, phaseCore1_m, phaseCore2_m, RFCavity::phaseError_m, phaseExit_m, RFCavity::scale_m, scaleCore_m, scaleCoreError_m, RFCavity::scaleError_m, startCoreField_m, startExitField_m, and RFCavity::startField_m.
applyToReferenceParticle()
bool TravelingWave::applyToReferenceParticle (const Vector_t< double, 3 > & R, const Vector_t< double, 3 > & P, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual inherited
Apply to reference particle with position R and momemtum P.
Parameters
R Position
P Momentum
t Time
E Electric Field
B Magnetic Field
Returns
true if particle is out-of-bounds (lost), false otherwise
Reimplemented from RFCavity.
Definition at line 183 of file TravelingWave.cpp.
References cellLength_m, RFCavity::endField_m, RFCavity::fieldmap_m, RFCavity::frequency_m, mappedStartExitField_m, periodLength_m, RFCavity::phase_m, phaseCore1_m, phaseCore2_m, phaseExit_m, RFCavity::scale_m, scaleCore_m, startCoreField_m, startExitField_m, and RFCavity::startField_m.
bends()
bool TravelingWave::bends () const override virtual inherited
Reimplemented from RFCavity.
Definition at line 290 of file TravelingWave.cpp.
Bfield() [1/2]
BVector Component::Bfield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 234 of file Component.h.
References EMField::Bfield(), and getField().
Bfield() [2/2]
BVector Component::Bfield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 240 of file Component.h.
References EMField::Bfield(), and getField().
clone()
ElementBase * TravelingWaveRep::clone () const virtual
Return clone.
Implements ElementBase.
Definition at line 46 of file TravelingWaveRep.cpp.
References TravelingWaveRep().
copyStructure()
ElementBase * ElementBase::copyStructure () virtual inherited
Make a structural copy.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 193 of file ElementBase.cpp.
References clone(), ElementBase(), and isSharable().
Referenced by Sequence::copy(), Line::parse(), and SequenceParser::parseMember().
dropFieldmaps()
void RFCavity::dropFieldmaps () inline inherited
Definition at line 325 of file RFCavity.h.
References fieldmap_m.
Referenced by OpalCavity::update().
EBfield() [1/2]
EBVectors Component::EBfield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 244 of file Component.h.
References EMField::EBfield(), and getField().
EBfield() [2/2]
EBVectors Component::EBfield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 246 of file Component.h.
References EMField::EBfield(), and getField().
Efield() [1/2]
EVector Component::Efield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 232 of file Component.h.
References EMField::Efield(), and getField().
Efield() [2/2]
EVector Component::Efield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 236 of file Component.h.
References EMField::Efield(), and getField().
finalise()
void TravelingWave::finalise () override virtual inherited
Reimplemented from RFCavity.
Definition at line 288 of file TravelingWave.cpp.
fixPosition()
void ElementBase::fixPosition () inline inherited
Definition at line 596 of file ElementBase.h.
References positionIsFixed.
Referenced by OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
getAmplitude()
double TravelingWaveRep::getAmplitude () const virtual
Get amplitude.
Implements TravelingWave.
Definition at line 66 of file TravelingWaveRep.cpp.
References field, and ignoreCavities.
getAmplitudeError()
double RFCavity::getAmplitudeError () const inline virtual inherited
Definition at line 335 of file RFCavity.h.
References scaleError_m.
getAmplitudem()
double RFCavity::getAmplitudem () const inline virtual inherited
Definition at line 331 of file RFCavity.h.
References scale_m.
Referenced by CavityAutophaser::getPhaseAtMaxEnergy().
getAmplitudeModelName()
std::string RFCavity::getAmplitudeModelName () inline inherited
Definition at line 369 of file RFCavity.h.
References amplitudeName_m.
getAperture()
std::pair< ApertureType, std::vector< double > > ElementBase::getAperture () const inline inherited
Definition at line 581 of file ElementBase.h.
References aperture_m.
Referenced by MeshGenerator::add(), Solenoid::getSupportEnvelope(), and MeshGenerator::getTransverseSupport().
getArcLength()
double ElementBase::getArcLength () const inline virtual inherited
Get arc length.
Reimplemented in MarkerRep, TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 478 of file ElementBase.h.
References BGeometryBase::getArcLength(), and getGeometry().
Referenced by TBeamline< T >::getTransform().
getAttribute()
double ElementBase::getAttribute (const std::string & aKey) const virtual inherited
Get attribute value.
Definition at line 146 of file ElementBase.cpp.
References getConstChannel().
getAutoPhaseEstimate()
double TravelingWave::getAutoPhaseEstimate (const double & E0, const double & t0, const double & q, const double & m) override virtual inherited
Reimplemented from RFCavity.
Definition at line 311 of file TravelingWave.cpp.
References Units::deg2rad, RFCavity::fieldmap_m, RFCavity::frequency_m, getdA(), getdB(), getdE(), getdT(), mode_m, numCells_m, RFCavity::phase_m, phaseCore1_m, phaseCore2_m, phaseExit_m, Physics::pi, Units::rad2deg, RFCavity::scale_m, scaleCore_m, and Physics::two_pi.
getAutoPhaseEstimateFallback()
double RFCavity::getAutoPhaseEstimateFallback (double E0, double t0, double q, double m) virtual inherited
Definition at line 477 of file RFCavity.cpp.
References Util::getBetaGamma(), Util::getKineticEnergy(), getPhasem(), Physics::pi, Units::rad2deg, setPhasem(), trackOnAxisParticle(), and Physics::two_pi.
Referenced by getAutoPhaseEstimate().
getAutophaseVeto()
bool RFCavity::getAutophaseVeto () const inline virtual inherited
Definition at line 361 of file RFCavity.h.
References autophaseVeto_m.
Referenced by ParallelTracker::autophaseCavities(), CavityAutophaser::getPhaseAtMaxEnergy(), CavityAutophaser::guessCavityPhase(), and CavityAutophaser::optimizeCavityPhase().
getAzimuth()
double RFCavity::getAzimuth () const virtual inherited
Definition at line 301 of file RFCavity.cpp.
References angle_m.
getBodyPort()
Port ElementBase::getBodyPort () const inline virtual inherited
Return the body port of the canonical local chart.
The body port \(p_{i,\mathrm{body}}\) is the identity port of the element's canonical local chart. Its rigid transform is therefore the identity element of \(SE(3)\) in the first redesign stage.
Definition at line 546 of file ElementBase.h.
Referenced by getPlacementGeometry(), and TEST_F().
getBoundaryGeometry()
BoundaryGeometry * ElementBase::getBoundaryGeometry () const inline virtual inherited
return the attached boundary geometrt object if there is any
Definition at line 512 of file ElementBase.h.
References bgeometry_m.
getBoundingBoxInLabCoords()
BoundingBox ElementBase::getBoundingBoxInLabCoords () const virtual inherited
Definition at line 263 of file ElementBase.cpp.
References csTrafoGlobal2Local_m, getEdgeToBegin(), and getEdgeToEnd().
getCavityType()
CavityType RFCavity::getCavityType () const inline inherited
Definition at line 353 of file RFCavity.h.
References type_m.
getCavityTypeString()
std::string RFCavity::getCavityTypeString () const inherited
Definition at line 322 of file RFCavity.cpp.
References bmCavityTypeString_s, and type_m.
getChannel()
Channel * TravelingWaveRep::getChannel (const std::string & aKey, bool create = false) virtual
Construct a read/write channel.
Reimplemented from ElementBase.
Definition at line 48 of file TravelingWaveRep.cpp.
References ElementBase::getChannel().
getConstChannel()
const ConstChannel * ElementBase::getConstChannel (const std::string & aKey) const virtual inherited
Construct a read-only channel.
Definition at line 185 of file ElementBase.cpp.
References ElementBase(), and getChannel().
Referenced by getAttribute(), and hasAttribute().
getCosAzimuth()
double RFCavity::getCosAzimuth () const virtual inherited
Definition at line 305 of file RFCavity.cpp.
References cosAngle_m.
getCSTrafoGlobal2Local()
CoordinateSystemTrafo ElementBase::getCSTrafoGlobal2Local () const inline inherited
Definition at line 528 of file ElementBase.h.
References csTrafoGlobal2Local_m.
Referenced by getPlacementPose(), OpalRBend::update(), and OpalSBend::update().
getCycFrequency()
double RFCavity::getCycFrequency () const virtual inherited
Definition at line 339 of file RFCavity.cpp.
References frequency_m.
getdA()
double TravelingWave::getdA (const int & i, const int & I, const std::vector< double > & t, const double & phi, const std::vector< std::pair< double, double > > & F) const inline private inherited
Definition at line 181 of file TravelingWave.h.
References RFCavity::frequency_m.
Referenced by getAutoPhaseEstimate().
getdB()
double TravelingWave::getdB (const int & i, const int & I, const std::vector< double > & t, const double & phi, const std::vector< std::pair< double, double > > & F) const inline private inherited
Definition at line 194 of file TravelingWave.h.
References RFCavity::frequency_m.
Referenced by getAutoPhaseEstimate().
getdE()
double TravelingWave::getdE (const int & i, const int & I, const std::vector< double > & t, const double & phi, const std::vector< std::pair< double, double > > & F) const inline private inherited
Definition at line 141 of file TravelingWave.h.
References RFCavity::frequency_m.
Referenced by getAutoPhaseEstimate().
getDesign()
const ElementBase & Component::getDesign () const virtual inherited
Return design element.
Definition at line 33 of file Component.cpp.
References ElementBase::ElementBase().
getDesignEnergy()
double RFCavity::getDesignEnergy () const inline override virtual inherited
Reimplemented from Component.
Definition at line 323 of file RFCavity.h.
References designEnergy_m.
Referenced by OrbitThreader::getMaxDesignEnergy(), and CavityAutophaser::getPhaseAtMaxEnergy().
getdT()
double TravelingWave::getdT (const int & i, const int & I, const std::vector< double > & E, const std::vector< std::pair< double, double > > & F, const double mass) const inline private inherited
Definition at line 154 of file TravelingWave.h.
References Physics::c.
Referenced by getAutoPhaseEstimate().
getEdgeToBegin()
CoordinateSystemTrafo TravelingWave::getEdgeToBegin () const inline override virtual inherited
Reimplemented from RFCavity.
Definition at line 220 of file TravelingWave.h.
getEdgeToEnd()
CoordinateSystemTrafo TravelingWave::getEdgeToEnd () const inline override virtual inherited
Reimplemented from RFCavity.
Definition at line 225 of file TravelingWave.h.
References RFCavity::getElementLength().
getElementDimensions()
void TravelingWave::getElementDimensions (double & begin, double & end) const override virtual inherited
Return the nominal body extent of the element.
The first placement redesign stage distinguishes between the nominal body extent and the field-support extent. The body extent is the canonical longitudinal interval of the placed hardware, \([z_\mathrm{body}^{\mathrm{begin}}, z_\mathrm{body}^{\mathrm{end}}]\), and therefore drives ports, placement, and visualization. By default it coincides with the geometry length \([0, L]\) in the local chart.
Reimplemented from RFCavity.
Definition at line 304 of file TravelingWave.cpp.
References RFCavity::getElementLength().
getElementLength()
double RFCavity::getElementLength () const override virtual inherited
Return the nominal body length of the cavity.
The body length is the placed hardware extent configured on the cavity geometry. It is independent of the field-support extent returned by getFieldExtend().
Reimplemented from ElementBase.
Definition at line 710 of file RFCavity.cpp.
References ElementBase::getElementLength().
Referenced by getEdgeToEnd(), TravelingWave::getEdgeToEnd(), getElementDimensions(), and TravelingWave::getElementDimensions().
getElementPosition()
double ElementBase::getElementPosition () const inline inherited
Definition at line 617 of file ElementBase.h.
References elemedgeSet_m, elementPosition_m, and getName().
getEntrance()
double ElementBase::getEntrance () const inline virtual inherited
Get entrance position.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 486 of file ElementBase.h.
References BGeometryBase::getEntrance(), and getGeometry().
Referenced by BendBase::getDesignPath().
getEntranceFrame()
Euclid3D ElementBase::getEntranceFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 498 of file ElementBase.h.
References BGeometryBase::getEntranceFrame(), and getGeometry().
Referenced by BendBase::getChordLength(), and BendBase::getEdgeToBegin().
getEntrancePatch()
Euclid3D ElementBase::getEntrancePatch () const inline virtual inherited
Get patch.
Definition at line 502 of file ElementBase.h.
References BGeometryBase::getEntrancePatch(), and getGeometry().
getEntryPort()
Port ElementBase::getEntryPort () const inline virtual inherited
Return the entrance port of the canonical local chart.
In the placement-note language, this is the marked entrance port \(p_{i,\mathrm{entry}}\) of element \(i\). For straight elements in the bridge stage, the body-to-entry transform is taken from the legacy getEdgeToBegin() result.
Definition at line 544 of file ElementBase.h.
References getEdgeToBegin().
Referenced by getPlacementGeometry(), and TEST_F().
getExit()
double ElementBase::getExit () const inline virtual inherited
Get exit position.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 488 of file ElementBase.h.
References BGeometryBase::getExit(), and getGeometry().
Referenced by BendBase::getDesignPath().
getExitFrame()
Euclid3D ElementBase::getExitFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 500 of file ElementBase.h.
References BGeometryBase::getExitFrame(), and getGeometry().
Referenced by BendBase::getChordLength(), and BendBase::getEdgeToEnd().
getExitPatch()
Euclid3D ElementBase::getExitPatch () const inline virtual inherited
Get patch.
Definition at line 504 of file ElementBase.h.
References BGeometryBase::getExitPatch(), and getGeometry().
getExitPort()
Port ElementBase::getExitPort () const inline virtual inherited
Return the exit port of the canonical local chart.
In the placement-note language, this is the marked exit port \(p_{i,\mathrm{exit}}\). For straight elements in the bridge stage, the body-to-exit transform is taken from the legacy getEdgeToEnd() result.
Definition at line 548 of file ElementBase.h.
References getEdgeToEnd().
Referenced by getPlacementGeometry(), and TEST_F().
getFast()
bool RFCavity::getFast () const inline virtual inherited
Definition at line 357 of file RFCavity.h.
References fast_m.
getField() [1/2]
AcceleratingField & TravelingWaveRep::getField () virtual
Get field.
Implements Component.
Definition at line 58 of file TravelingWaveRep.cpp.
References field.
getField() [2/2]
const AcceleratingField & TravelingWaveRep::getField () const virtual
Get field.
Implements Component.
Definition at line 60 of file TravelingWaveRep.cpp.
References field.
getFieldExtend()
void TravelingWave::getFieldExtend (double & zBegin, double & zEnd) const override virtual inherited
Return the field-support interval of the traveling-wave structure.
The field-support extent covers the entry, core, and exit field regions including the half-period fringe offsets. It is distinct from the nominal body extent used for placement and visualization.
Reimplemented from RFCavity.
Definition at line 299 of file TravelingWave.cpp.
References RFCavity::endField_m, and RFCavity::startField_m.
getFieldMapFN()
std::string RFCavity::getFieldMapFN () const virtual inherited
Definition at line 324 of file RFCavity.cpp.
References filename_m.
getFlagDeleteOnTransverseExit()
bool ElementBase::getFlagDeleteOnTransverseExit () const inline inherited
Definition at line 633 of file ElementBase.h.
References deleteOnTransverseExit_m.
Referenced by BendBase::apply(), BendBase::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Multipole::apply(), Multipole::apply(), RFCavity::apply(), Solenoid::apply(), and TravelingWave::apply().
getFrequency()
double TravelingWaveRep::getFrequency () const virtual
Get frequency.
Implements TravelingWave.
Definition at line 68 of file TravelingWaveRep.cpp.
References field.
getFrequencym()
double RFCavity::getFrequencym () const inline virtual inherited
Definition at line 341 of file RFCavity.h.
References frequency_m.
Referenced by CavityAutophaser::getPhaseAtMaxEnergy(), and CavityAutophaser::optimizeCavityPhase().
getFrequencyModelName()
std::string RFCavity::getFrequencyModelName () inline inherited
Definition at line 385 of file RFCavity.h.
References frequencyName_m.
getGapWidth()
double RFCavity::getGapWidth () const virtual inherited
Definition at line 309 of file RFCavity.cpp.
References gapwidth_m.
getGeometry() [1/2]
StraightGeometry & TravelingWaveRep::getGeometry () virtual
Get geometry.
Implements ElementBase.
Definition at line 62 of file TravelingWaveRep.cpp.
References geometry.
getGeometry() [2/2]
const StraightGeometry & TravelingWaveRep::getGeometry () const virtual
Get geometry.
Implements ElementBase.
Definition at line 64 of file TravelingWaveRep.cpp.
References geometry.
getMisalignment() [1/2]
CoordinateSystemTrafo ElementBase::getMisalignment () const inline inherited
Definition at line 592 of file ElementBase.h.
References misalignment_m.
Referenced by getPlacementMisalignment().
getMisalignment() [2/2]
void ElementBase::getMisalignment (double & x, double & y, double & s) const inherited
getMomentaKick()
void RFCavity::getMomentaKick (const double normalRadius, double momentum[], const double t, const double dtCorrt, const int PID, const double restMass, const int chargenumber) inherited
used in OPAL-cycl
Is called from OPAL-cycl and can handle time dependent frequency, amplitude and phase
At the moment (test) only the frequency is time dependent
B field effects
Definition at line 351 of file RFCavity.cpp.
References Physics::c, cosAngle_m, Units::deg2rad, Units::eV2MeV, frequency_m, frequencyTD_m, gapwidth_m, ElementBase::getName(), gmsg, Units::mm2m, Units::MVpm2Vpm, Units::ns2s, phi0_m, Units::rad2deg, rmax_m, rmin_m, scale_m, sinAngle_m, spline(), and Physics::two_pi.
getName()
const std::string & ElementBase::getName () const virtual inherited
Get element name.
Definition at line 131 of file ElementBase.cpp.
References elementID.
Referenced by Ring::appendElement(), TBeamline< T >::clone(), TBeamline< T >::copyStructure(), Probe::doGoOffline(), PlaceRep::enter(), getElementPosition(), RFCavity::getMomentaKick(), getOutputFN(), CavityAutophaser::getPhaseAtMaxEnergy(), Selector::handleElement(), RFCavity::initialise(), Ring::initialise(), Solenoid::initialise(), PlaceRep::leave(), VariableRFCavity::operator=(), Sequence::print(), Ring::Ring(), BeamlineFieldElement::SortAsc(), TEST_F(), Component::trackBunch(), Component::trackMap(), OpalRBend::update(), OpalSBend::update(), Sequence::updateList(), ParallelTracker::updateRFElement(), and Replacer::visitFlaggedElmPtr().
getOrigin()
double ElementBase::getOrigin () const inline virtual inherited
Get origin position.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 484 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getOrigin().
getOutputFN()
std::string ElementBase::getOutputFN () const inherited
Get output filename.
Definition at line 137 of file ElementBase.cpp.
References getName(), and outputfn_m.
Referenced by Probe::doInitialise(), Monitor::initialise(), and PluginElement::initialise().
getParticleMatterInteraction()
ParticleMatterInteractionHandler * ElementBase::getParticleMatterInteraction () const inline virtual inherited
Definition at line 516 of file ElementBase.h.
References parmatint_m.
getPerpenDistance()
double RFCavity::getPerpenDistance () const virtual inherited
Definition at line 307 of file RFCavity.cpp.
References pdis_m.
getPhase()
double TravelingWaveRep::getPhase () const virtual
Get phase.
Implements TravelingWave.
Definition at line 70 of file TravelingWaveRep.cpp.
References field.
getPhaseError()
double RFCavity::getPhaseError () const inline virtual inherited
Definition at line 351 of file RFCavity.h.
References phaseError_m.
getPhasem() [1/2]
double RFCavity::getPhasem () const inline virtual inherited
Definition at line 345 of file RFCavity.h.
References phase_m.
Referenced by getAutoPhaseEstimateFallback(), CavityAutophaser::getPhaseAtMaxEnergy(), CavityAutophaser::guessCavityPhase(), CavityAutophaser::optimizeCavityPhase(), and CavityAutophaser::track().
getPhasem() [2/2]
double RFCavity::getPhasem (double t) const inline inherited
Definition at line 347 of file RFCavity.h.
References frequency_m, and phase_m.
getPhaseModelName()
std::string RFCavity::getPhaseModelName () inline inherited
Definition at line 377 of file RFCavity.h.
References phaseName_m.
getPhi0()
double RFCavity::getPhi0 () const virtual inherited
Definition at line 311 of file RFCavity.cpp.
References phi0_m.
getPlacedElement()
PlacedElement ElementBase::getPlacedElement () const inline inherited
Return a placed-element view assembled from the current bridge objects.
Definition at line 570 of file ElementBase.h.
References getPlacementGeometry(), getPlacementMisalignment(), getPlacementPose(), and getPlacementSupport().
Referenced by MeshGenerator::add(), and TEST_F().
getPlacementGeometry()
ElementGeometry ElementBase::getPlacementGeometry () const inline inherited
Return the bridge geometry ports assembled from legacy edge state.
The first redesign stage defines a minimal explicit port contract with three named body-relative ports: \(p_{i,\mathrm{entry}}\), \(p_{i,\mathrm{body}}\), \(p_{i,\mathrm{exit}}\). The default bridge preserves current OPALX behavior by deriving those ports from getEntryPort(), getBodyPort(), and getExitPort(), whose straight-element implementations are backed by the legacy getEdgeToBegin() and getEdgeToEnd() methods.
Definition at line 562 of file ElementBase.h.
References getBodyPort(), getEntryPort(), and getExitPort().
Referenced by getPlacedElement().
getPlacementMisalignment()
Misalignment ElementBase::getPlacementMisalignment () const inline inherited
Return the local nominal-to-actual correction stored for the element.
Definition at line 558 of file ElementBase.h.
References getMisalignment().
Referenced by getPlacedElement().
getPlacementPose()
PlacementPose ElementBase::getPlacementPose () const inline inherited
Return the nominal rigid placement transform of the element.
This is the bridge from the legacy stored CoordinateSystemTrafo to the new placement vocabulary. It preserves current nominal placement semantics and does not apply misalignment.
Definition at line 550 of file ElementBase.h.
References getCSTrafoGlobal2Local().
Referenced by getPlacedElement().
getPlacementSupport()
SupportPlacement ElementBase::getPlacementSupport () const inline inherited
Return the support-frame bridge object. The default is the body frame.
Definition at line 566 of file ElementBase.h.
Referenced by getPlacedElement().
getPotential()
virtual bool Component::getPotential (const Vector_t< double, 3 > & , const double & , Vector_t< double, 3 > & , double &) inline virtual inherited
Calculate the four-potential at some position relative to the component.
Parameters
R position in the local coordinate system of the component
t time
A filled with the calculated magnetic vector potential
phi filled with the calculated electric potential Note that any existing values in A and phi may be overwritten by this method.
Returns
true if particle is outside the field map, else false Default for component is to return false and make no change to A and phi
Definition at line 155 of file Component.h.
getRequiredNumberOfTimeSteps()
int ElementBase::getRequiredNumberOfTimeSteps () const inline virtual inherited
Reimplemented in BendBase, Drift, Laser, Marker, and Monitor.
Definition at line 627 of file ElementBase.h.
getRmax()
double RFCavity::getRmax () const virtual inherited
Definition at line 299 of file RFCavity.cpp.
References rmax_m.
getRmin()
double RFCavity::getRmin () const virtual inherited
Definition at line 297 of file RFCavity.cpp.
References rmin_m.
getRotationAboutZ()
double ElementBase::getRotationAboutZ () const inline inherited
Definition at line 608 of file ElementBase.h.
References rotationZAxis_m.
Referenced by OpalBeamline::compileCompatibilityPlacement().
getSinAzimuth()
double RFCavity::getSinAzimuth () const virtual inherited
Definition at line 303 of file RFCavity.cpp.
References sinAngle_m.
getTotalTransform()
Euclid3D ElementBase::getTotalTransform () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 494 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getTotalTransform().
getTransform() [1/2]
Euclid3D ElementBase::getTransform (double fromS, double toS) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 490 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getTransform().
Referenced by BendBase::getDesignPath(), and TBeamline< T >::getTransform().
getTransform() [2/2]
Euclid3D ElementBase::getTransform (double s) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 496 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getTransform().
getType()
ElementType TravelingWave::getType () const override virtual inherited
Get element type std::string.
Reimplemented from RFCavity.
Definition at line 309 of file TravelingWave.cpp.
References TRAVELINGWAVE.
getTypeString() [1/2]
std::string ElementBase::getTypeString () const inline inherited
Definition at line 610 of file ElementBase.h.
References getType(), and getTypeString().
Referenced by getTypeString().
getTypeString() [2/2]
std::string ElementBase::getTypeString (ElementType type) static inherited
Definition at line 191 of file ElementBase.cpp.
References elementTypeToString_s.
getWake()
WakeFunction * ElementBase::getWake () const inline virtual inherited
return the attached wake object if there is any
Definition at line 508 of file ElementBase.h.
References wake_m.
goOffline()
void TravelingWave::goOffline () override virtual inherited
Reimplemented from RFCavity.
Definition at line 297 of file TravelingWave.cpp.
References RFCavity::filename_m.
goOnline()
void TravelingWave::goOnline (const double & kineticEnergy) override virtual inherited
Reimplemented from RFCavity.
Definition at line 292 of file TravelingWave.cpp.
References RFCavity::filename_m, and Component::online_m.
hasAttribute()
bool ElementBase::hasAttribute (const std::string & aKey) const virtual inherited
Test for existence of an attribute.
Definition at line 158 of file ElementBase.cpp.
References getConstChannel().
hasBoundaryGeometry()
bool ElementBase::hasBoundaryGeometry () const inline virtual inherited
Definition at line 514 of file ElementBase.h.
References bgeometry_m.
hasParticleMatterInteraction()
bool ElementBase::hasParticleMatterInteraction () const inline virtual inherited
Definition at line 520 of file ElementBase.h.
References parmatint_m.
hasWake()
bool ElementBase::hasWake () const inline virtual inherited
Definition at line 510 of file ElementBase.h.
References wake_m.
initialise() [1/2]
void TravelingWave::initialise (PartBunch_t * bunch, double & startField, double & endField) override virtual inherited
Reimplemented from RFCavity.
Definition at line 240 of file TravelingWave.cpp.
References cellLength_m, RFCavity::endField_m, gmsg, RFCavity::initialise(), mappedStartExitField_m, mode_m, numCells_m, periodLength_m, RFCavity::phase_m, phaseCore1_m, phaseCore2_m, phaseExit_m, Physics::pi, Component::RefPartBunch_m, RFCavity::scale_m, scaleCore_m, scaleCoreError_m, RFCavity::scaleError_m, startCoreField_m, startExitField_m, RFCavity::startField_m, and Physics::two_pi.
initialise() [2/2]
void TravelingWave::initialise (PartBunch_t * bunch, std::shared_ptr< AbstractTimeDependence > freq_atd, std::shared_ptr< AbstractTimeDependence > ampl_atd, std::shared_ptr< AbstractTimeDependence > phase_atd) override virtual inherited
Reimplemented from RFCavity.
Definition at line 280 of file TravelingWave.cpp.
References gmsg.
isElementPositionSet()
bool ElementBase::isElementPositionSet () const inline inherited
Definition at line 625 of file ElementBase.h.
References elemedgeSet_m.
isInside()
bool TravelingWave::isInside (const Vector_t< double, 3 > & r) const override virtual inherited
Reimplemented from RFCavity.
Definition at line 469 of file TravelingWave.cpp.
References ElementBase::isInsideTransverse(), periodLength_m, and startExitField_m.
isInsideTransverse()
bool ElementBase::isInsideTransverse (const Vector_t< double, 3 > & r) const protected inherited
Definition at line 232 of file ElementBase.cpp.
References aperture_m, CONIC_ELLIPTICAL, CONIC_RECTANGULAR, getEdgeToBegin(), getElementLength(), and CoordinateSystemTrafo::transformTo().
Referenced by BendBase::apply(), BendBase::apply(), Component::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Multipole::apply(), Multipole::apply(), BendBase::applyToReferenceParticle(), Component::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), BendBase::isInside(), isInside(), Monitor::isInside(), Multipole::isInside(), RFCavity::isInside(), Solenoid::isInside(), and TravelingWave::isInside().
isPositioned()
bool ElementBase::isPositioned () const inline inherited
Definition at line 598 of file ElementBase.h.
References positionIsFixed.
Referenced by OpalRBend::update(), and OpalSBend::update().
isSharable()
bool ElementBase::isSharable () const inline inherited
Test if the element can be shared.
Definition at line 506 of file ElementBase.h.
References shareFlag.
Referenced by copyStructure(), TBeamline< T >::copyStructure(), and Sequence::updateList().
makeSharable()
void ElementBase::makeSharable () virtual inherited
Set sharable flag.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 201 of file ElementBase.cpp.
References shareFlag.
Referenced by OpalMarker::OpalMarker().
Online()
bool Component::Online () virtual inherited
Definition at line 47 of file Component.cpp.
References online_m.
operator=()
void TravelingWaveRep::operator= (const TravelingWaveRep &) private
References TravelingWaveRep().
releasePosition()
void ElementBase::releasePosition () inline inherited
Definition at line 594 of file ElementBase.h.
References positionIsFixed.
Referenced by OpalRBend::update(), and OpalSBend::update().
removeAttribute()
void ElementBase::removeAttribute (const std::string & aKey) virtual inherited
Remove an existing attribute.
Definition at line 169 of file ElementBase.cpp.
References userAttribs.
setActionRange()
void ElementBase::setActionRange (const std::queue< std::pair< double, double > > & range) inline inherited
Definition at line 600 of file ElementBase.h.
References actionRange_m, and elementEdge_m.
setAmplitude()
void TravelingWaveRep::setAmplitude (double V) virtual
Set amplitude.
Definition at line 72 of file TravelingWaveRep.cpp.
References field.
Referenced by OpalTravelingWave::update().
setAmplitudeError()
void RFCavity::setAmplitudeError (double vPeakError) inline virtual inherited
Definition at line 333 of file RFCavity.h.
References scaleError_m.
Referenced by OpalCavity::update(), and OpalTravelingWave::update().
setAmplitudem()
void RFCavity::setAmplitudem (double vPeak) inline virtual inherited
Definition at line 329 of file RFCavity.h.
References scale_m.
Referenced by CavityAutophaser::getPhaseAtMaxEnergy(), OpalCavity::update(), and OpalTravelingWave::update().
setAmplitudeModel()
void RFCavity::setAmplitudeModel (std::shared_ptr< AbstractTimeDependence > time_dep) inline inherited
Definition at line 363 of file RFCavity.h.
References amplitudeTD_m.
Referenced by initialise().
setAmplitudeModelName()
void RFCavity::setAmplitudeModelName (std::string name) inline inherited
Definition at line 367 of file RFCavity.h.
References amplitudeName_m.
Referenced by OpalCavity::update().
setAperture()
void ElementBase::setAperture (const ApertureType & type, const std::vector< double > & args) inline inherited
Definition at line 576 of file ElementBase.h.
References aperture_m.
Referenced by Component::Component(), TEST_F(), TEST_F(), TEST_F(), OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
setAttribute()
void ElementBase::setAttribute (const std::string & aKey, double val) virtual inherited
Set value of an attribute.
Definition at line 171 of file ElementBase.cpp.
References getChannel(), and Channel::isSettable().
Referenced by update(), and OpalElement::updateUnknown().
setAutophaseVeto()
void RFCavity::setAutophaseVeto (bool veto = true) inline virtual inherited
Definition at line 359 of file RFCavity.h.
References autophaseVeto_m.
Referenced by CavityAutophaser::getPhaseAtMaxEnergy(), OpalCavity::update(), OpalTravelingWave::update(), and ParallelTracker::updateRFElement().
setAzimuth()
void RFCavity::setAzimuth (double angle) inherited
Definition at line 289 of file RFCavity.cpp.
References angle_m.
Referenced by OpalCavity::update().
setBoundaryGeometry()
void ElementBase::setBoundaryGeometry (BoundaryGeometry * geo) virtual inherited
attach a boundary geometry field to the element
Definition at line 215 of file ElementBase.cpp.
References bgeometry_m.
setCavityType()
void RFCavity::setCavityType (const std::string & type) inherited
Definition at line 313 of file RFCavity.cpp.
References bmCavityTypeString_s, SW, and type_m.
Referenced by OpalCavity::update().
setCSTrafoGlobal2Local()
void ElementBase::setCSTrafoGlobal2Local (const CoordinateSystemTrafo & ori) inline inherited
Definition at line 522 of file ElementBase.h.
References csTrafoGlobal2Local_m, and positionIsFixed.
Referenced by setPlacementPose(), TEST_F(), OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
setCurrentSCoordinate()
void ElementBase::setCurrentSCoordinate (double s) inherited
Definition at line 223 of file ElementBase.cpp.
References actionRange_m, and elementEdge_m.
setDesignEnergy()
void RFCavity::setDesignEnergy (const double & ekin, bool changeable = true) inline override virtual inherited
Reimplemented from Component.
Definition at line 321 of file RFCavity.h.
References designEnergy_m.
Referenced by OpalCavity::update(), and OpalTravelingWave::update().
setElementLength()
void ElementBase::setElementLength (double length) inline virtual inherited
Set design length.
Reimplemented in ConstantEFieldCavityRep, and MultipoleT.
Definition at line 482 of file ElementBase.h.
References getGeometry(), and BGeometryBase::setElementLength().
Referenced by MultipoleT::setElementLength(), BendBase::setLength(), SequenceMember::setLength(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), OpalCavity::update(), OpalMonitor::update(), OpalMultipole::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalSolenoid::update(), and OpalTravelingWave::update().
setElementPosition()
void ElementBase::setElementPosition (double elemedge) inline inherited
Access to ELEMEDGE attribute.
Definition at line 612 of file ElementBase.h.
References elemedgeSet_m, and elementPosition_m.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and OpalElement::update().
setExitFaceSlope()
void Component::setExitFaceSlope (const double & m) inline inherited
Definition at line 250 of file Component.h.
References exit_face_slope_m.
setFast()
void RFCavity::setFast (bool fast) inline virtual inherited
Definition at line 355 of file RFCavity.h.
References fast_m.
Referenced by OpalCavity::update(), and OpalTravelingWave::update().
setFieldMapFN()
void RFCavity::setFieldMapFN (const std::string & fmapfn) inline virtual inherited
Set the name of the field map.
Definition at line 327 of file RFCavity.h.
References filename_m.
Referenced by OpalCavity::update(), and OpalTravelingWave::update().
setFlagDeleteOnTransverseExit()
void ElementBase::setFlagDeleteOnTransverseExit (bool flag = true) inline inherited
Definition at line 629 of file ElementBase.h.
References deleteOnTransverseExit_m.
Referenced by OpalElement::update().
setFrequency()
void TravelingWaveRep::setFrequency (double f) virtual
Set frequency.
Definition at line 74 of file TravelingWaveRep.cpp.
References field.
Referenced by OpalTravelingWave::update().
setFrequencym()
void RFCavity::setFrequencym (double freq) inline virtual inherited
Definition at line 339 of file RFCavity.h.
References frequency_m.
Referenced by OpalCavity::update(), and OpalTravelingWave::update().
setFrequencyModel()
void RFCavity::setFrequencyModel (std::shared_ptr< AbstractTimeDependence > time_dep) inline inherited
Definition at line 379 of file RFCavity.h.
References frequencyTD_m.
Referenced by initialise().
setFrequencyModelName()
void RFCavity::setFrequencyModelName (std::string name) inline inherited
Definition at line 383 of file RFCavity.h.
References frequencyName_m.
Referenced by OpalCavity::update().
setGapWidth()
void RFCavity::setGapWidth (double gapwidth) inherited
Definition at line 293 of file RFCavity.cpp.
References gapwidth_m.
Referenced by OpalCavity::update().
setIgnore()
void TravelingWaveRep::setIgnore (bool ignore = false) static
Set ignore switch.
Definition at line 78 of file TravelingWaveRep.cpp.
References ignoreCavities.
setMisalignment()
void ElementBase::setMisalignment (const CoordinateSystemTrafo & cst) inline inherited
Definition at line 590 of file ElementBase.h.
References misalignment_m.
Referenced by TEST_F(), and OpalElement::update().
setMode()
void TravelingWave::setMode (double mode) inline inherited
Definition at line 218 of file TravelingWave.h.
References mode_m.
Referenced by OpalTravelingWave::update().
setName()
void ElementBase::setName (const std::string & name) virtual inherited
Set element name.
Definition at line 133 of file ElementBase.cpp.
References elementID.
Referenced by Sequence::insertDrifts(), and VariableRFCavity::operator=().
setNumCells()
void TravelingWave::setNumCells (int NumCells) inline inherited
Definition at line 216 of file TravelingWave.h.
References numCells_m.
Referenced by OpalTravelingWave::update().
setOutputFN()
void ElementBase::setOutputFN (std::string fn) inherited
Set output filename.
Definition at line 135 of file ElementBase.cpp.
Referenced by OpalMonitor::update(), and OpalProbe::update().
setParticleMatterInteraction()
void ElementBase::setParticleMatterInteraction (ParticleMatterInteractionHandler * spys) virtual inherited
Definition at line 219 of file ElementBase.cpp.
References parmatint_m.
setPerpenDistance()
void RFCavity::setPerpenDistance (double pdis) inherited
Definition at line 291 of file RFCavity.cpp.
References pdis_m.
Referenced by OpalCavity::update().
setPhase()
void TravelingWaveRep::setPhase (double phi) virtual
Set phase.
Definition at line 76 of file TravelingWaveRep.cpp.
References field.
Referenced by OpalTravelingWave::update().
setPhaseError()
void RFCavity::setPhaseError (double phaseError) inline virtual inherited
Definition at line 349 of file RFCavity.h.
References phaseError_m.
Referenced by OpalCavity::update(), and OpalTravelingWave::update().
setPhasem()
void TravelingWave::setPhasem (double phase) inline override virtual inherited
Reimplemented from RFCavity.
Definition at line 207 of file TravelingWave.h.
References mode_m, numCells_m, RFCavity::phase_m, phaseCore1_m, phaseCore2_m, phaseExit_m, Physics::pi, and Physics::two_pi.
Referenced by OpalTravelingWave::update().
setPhaseModel()
void RFCavity::setPhaseModel (std::shared_ptr< AbstractTimeDependence > time_dep) inline inherited
Definition at line 371 of file RFCavity.h.
References phaseTD_m.
Referenced by initialise().
setPhaseModelName()
void RFCavity::setPhaseModelName (std::string name) inline inherited
Definition at line 375 of file RFCavity.h.
References phaseName_m.
Referenced by OpalCavity::update().
setPhi0()
void RFCavity::setPhi0 (double phi0) inherited
Definition at line 295 of file RFCavity.cpp.
References phi0_m.
Referenced by OpalCavity::update().
setPlacementPose()
void ElementBase::setPlacementPose (const PlacementPose & pose) inline inherited
Set the nominal rigid placement transform of the element.
This bridge setter preserves the existing storage model by delegating to setCSTrafoGlobal2Local().
Definition at line 554 of file ElementBase.h.
References PlacementPose::getParentToNominal(), and setCSTrafoGlobal2Local().
setRmax()
void RFCavity::setRmax (double rmax) inherited
Definition at line 287 of file RFCavity.cpp.
References rmax_m.
Referenced by OpalCavity::update().
setRmin()
void RFCavity::setRmin (double rmin) inherited
Definition at line 285 of file RFCavity.cpp.
References rmin_m.
Referenced by OpalCavity::update().
setRotationAboutZ()
void ElementBase::setRotationAboutZ (double rotation) inline inherited
Set rotation about z axis in bend frame.
Definition at line 606 of file ElementBase.h.
References rotationZAxis_m.
Referenced by OpalElement::update().
setWake()
void ElementBase::setWake (WakeFunction * wf) virtual inherited
attach a wake field to the element
Definition at line 211 of file ElementBase.cpp.
References wake_m.
spline()
double RFCavity::spline (double z, double * za) inherited
Definition at line 411 of file RFCavity.cpp.
References DvDr_m, num_points_m, RNormal_m, and VrNormal_m.
Referenced by getMomentaKick().
trackBunch()
void Component::trackBunch (PartBunch_t & bunch, const PartData & , bool revBeam, bool revTrack) const virtual inherited
Track a borrowed particle bunch through a non-standard component.
The default implementation throws a LogicalError.
Parameters
bunch Particle bunch to track. The component does not take ownership.
Definition at line 35 of file Component.cpp.
References ElementBase::getName().
Referenced by Tracker::visitComponent().
trackMap()
void Component::trackMap (FVps< double, 6 > & map, const PartData & , bool revBeam, bool revTrack) const virtual inherited
Track a map.
Definition at line 39 of file Component.cpp.
References ElementBase::getName().
trackOnAxisParticle()
std::pair< double, double > RFCavity::trackOnAxisParticle (const double & p0, const double & t0, const double & dt, const double & q, const double & mass, std::ofstream * out = nullptr) virtual inherited
Definition at line 653 of file RFCavity.cpp.
References applyToReferenceParticle(), Physics::c, dot(), endField_m, Util::getGamma(), Util::getKineticEnergy(), PartData::getM(), PartData::getQ(), BorisPusher::kick(), BorisPusher::push(), Component::RefPartBunch_m, and startField_m.
Referenced by getAutoPhaseEstimateFallback(), and CavityAutophaser::track().
update()
bool ElementBase::update (const AttributeSet & set) inherited
Update element.
Definition at line 203 of file ElementBase.cpp.
References AttributeSet::begin(), AttributeSet::end(), and setAttribute().
Member Data Documentation
actionRange_m
std::queue<std::pair<double, double> > ElementBase::actionRange_m private inherited
Definition at line 468 of file ElementBase.h.
Referenced by setActionRange(), and setCurrentSCoordinate().
amplitudeName_m
std::string RFCavity::amplitudeName_m protected inherited
Definition at line 202 of file RFCavity.h.
Referenced by getAmplitudeModelName(), RFCavity(), and setAmplitudeModelName().
amplitudeTD_m
std::shared_ptr<AbstractTimeDependence> RFCavity::amplitudeTD_m protected inherited
Definition at line 201 of file RFCavity.h.
Referenced by RFCavity(), RFCavity(), and setAmplitudeModel().
angle_m
double RFCavity::angle_m private inherited
Definition at line 230 of file RFCavity.h.
Referenced by getAzimuth(), initialise(), RFCavity(), RFCavity(), and setAzimuth().
aperture_m
std::pair<ApertureType, std::vector<double> > ElementBase::aperture_m protected inherited
Definition at line 439 of file ElementBase.h.
Referenced by ElementBase(), getAperture(), isInsideTransverse(), and setAperture().
autophaseVeto_m
bool RFCavity::autophaseVeto_m protected inherited
Definition at line 215 of file RFCavity.h.
Referenced by getAutophaseVeto(), RFCavity(), RFCavity(), and setAutophaseVeto().
bgeometry_m
BoundaryGeometry* ElementBase::bgeometry_m private inherited
Definition at line 459 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getBoundaryGeometry(), hasBoundaryGeometry(), and setBoundaryGeometry().
bmCavityTypeString_s
const BiMap< CavityType, std::string > RFCavity::bmCavityTypeString_s static private inherited
Initial value:
= []() {
    BiMap<CavityType, std::string> bimap;
    bimap.insert(CavityType::SW, "STANDING");
    bimap.insert(CavityType::SGSW, "SINGLEGAP");
    return bimap;
}()
Definition at line 31 of file RFCavity.h.
Referenced by getCavityTypeString(), and setCavityType().
cellLength_m
double TravelingWave::cellLength_m private inherited
Definition at line 119 of file TravelingWave.h.
Referenced by apply(), apply(), applyToReferenceParticle(), initialise(), TravelingWave(), and TravelingWave().
cosAngle_m
double RFCavity::cosAngle_m private inherited
Definition at line 232 of file RFCavity.h.
Referenced by getCosAzimuth(), getMomentaKick(), initialise(), RFCavity(), and RFCavity().
csTrafoGlobal2Local_m
CoordinateSystemTrafo ElementBase::csTrafoGlobal2Local_m protected inherited
Definition at line 436 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getBoundingBoxInLabCoords(), getCSTrafoGlobal2Local(), and setCSTrafoGlobal2Local().
defaultAperture_m
const std::vector< double > Component::defaultAperture_m = std::vector<double>({1e6, 1e6, 1.0}) static protected inherited
Definition at line 221 of file Component.h.
Referenced by Component().
deleteOnTransverseExit_m
bool ElementBase::deleteOnTransverseExit_m = true private inherited
Definition at line 472 of file ElementBase.h.
Referenced by ElementBase(), getFlagDeleteOnTransverseExit(), and setFlagDeleteOnTransverseExit().
designEnergy_m
double RFCavity::designEnergy_m protected inherited
Definition at line 217 of file RFCavity.h.
Referenced by getDesignEnergy(), RFCavity(), RFCavity(), and setDesignEnergy().
DvDr_m
std::unique_ptr<double[]> RFCavity::DvDr_m private inherited
Definition at line 239 of file RFCavity.h.
Referenced by initialise(), RFCavity(), RFCavity(), and spline().
elemedgeSet_m
bool ElementBase::elemedgeSet_m private inherited
Definition at line 466 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getElementPosition(), isElementPositionSet(), and setElementPosition().
elementEdge_m
double ElementBase::elementEdge_m protected inherited
Definition at line 441 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), setActionRange(), and setCurrentSCoordinate().
elementID
std::string ElementBase::elementID private inherited
Definition at line 450 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getName(), and setName().
elementPosition_m
double ElementBase::elementPosition_m private inherited
ELEMEDGE attribute.
Definition at line 465 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getElementPosition(), and setElementPosition().
elementTypeToString_s
const std::map< ElementType, std::string > ElementBase::elementTypeToString_s static private inherited
Initial value:
= {
        {ElementType::ANY, "Any"},
        {ElementType::BEAMLINE, "Beamline"},
        {ElementType::DRIFT, "Drift"},
        {ElementType::LASER, "Laser"},
        {ElementType::MARKER, "Marker"},
        {ElementType::MULTIPOLE, "Multipole"},
        {ElementType::RFCAVITY, "RFCavity"},
        {ElementType::TRAVELINGWAVE, "TravelingWave"},
        {ElementType::SBEND, "SBEND"},
        {ElementType::RBEND, "RBEND"},
        {ElementType::RBEND3D, "RBEND3D"},
        {ElementType::RING, "Ring"},
        {ElementType::SOURCE, "SOURCE"},
        {ElementType::SOLENOID, "SOLENOID"},
        {ElementType::PROBE, "Probe"},
        {ElementType::VACUUM, "Vacuum"},
        {ElementType::CONSTANTEFIELDCAVITY, "ConstantEFieldCavity"}}
Definition at line 73 of file ElementBase.h.
Referenced by getTypeString().
endField_m
double RFCavity::endField_m protected inherited
end point of field support(m)
Definition at line 221 of file RFCavity.h.
Referenced by apply(), apply(), TravelingWave::apply(), TravelingWave::apply(), applyToReferenceParticle(), TravelingWave::applyToReferenceParticle(), getFieldExtend(), TravelingWave::getFieldExtend(), initialise(), TravelingWave::initialise(), RFCavity(), RFCavity(), TestRFCavity::setEndField(), TestTravelingWave::setEndField(), and trackOnAxisParticle().
exit_face_slope_m
double Component::exit_face_slope_m protected inherited
Definition at line 222 of file Component.h.
Referenced by Component(), Component(), and setExitFaceSlope().
fast_m
bool RFCavity::fast_m protected inherited
Definition at line 214 of file RFCavity.h.
Referenced by getFast(), initialise(), RFCavity(), RFCavity(), and setFast().
field
AcceleratingField TravelingWaveRep::field private
The cavity's field.
Definition at line 98 of file TravelingWaveRep.h.
Referenced by getAmplitude(), getField(), getField(), getFrequency(), getPhase(), setAmplitude(), setFrequency(), and setPhase().
fieldmap_m
Fieldmap* RFCavity::fieldmap_m protected inherited
Definition at line 219 of file RFCavity.h.
Referenced by apply(), apply(), TravelingWave::apply(), TravelingWave::apply(), applyToReferenceParticle(), TravelingWave::applyToReferenceParticle(), dropFieldmaps(), getAutoPhaseEstimate(), TravelingWave::getAutoPhaseEstimate(), initialise(), isInside(), RFCavity(), RFCavity(), TestRFCavity::setFieldmap(), and TestTravelingWave::setFieldmap().
filename_m
std::string RFCavity::filename_m protected inherited
The name of the inputfile
Definition at line 206 of file RFCavity.h.
Referenced by getFieldMapFN(), goOffline(), TravelingWave::goOffline(), goOnline(), TravelingWave::goOnline(), initialise(), initialise(), RFCavity(), RFCavity(), and setFieldMapFN().
frequency_m
double RFCavity::frequency_m protected inherited
Read in frequency of time varying field(Hz)
Definition at line 212 of file RFCavity.h.
Referenced by apply(), apply(), TravelingWave::apply(), TravelingWave::apply(), applyToReferenceParticle(), TravelingWave::applyToReferenceParticle(), getAutoPhaseEstimate(), TravelingWave::getAutoPhaseEstimate(), getCycFrequency(), TravelingWave::getdA(), TravelingWave::getdB(), TravelingWave::getdE(), getFrequencym(), getMomentaKick(), getPhasem(), initialise(), RFCavity(), RFCavity(), setFrequency(), TestRFCavity::setFrequencyInternal(), TestTravelingWave::setFrequencyInternal(), and setFrequencym().
frequencyName_m
std::string RFCavity::frequencyName_m protected inherited
Definition at line 204 of file RFCavity.h.
Referenced by getFrequencyModelName(), initialise(), RFCavity(), and setFrequencyModelName().
frequencyTD_m
std::shared_ptr<AbstractTimeDependence> RFCavity::frequencyTD_m protected inherited
Definition at line 203 of file RFCavity.h.
Referenced by getMomentaKick(), RFCavity(), RFCavity(), and setFrequencyModel().
gapwidth_m
double RFCavity::gapwidth_m private inherited
Definition at line 234 of file RFCavity.h.
Referenced by getGapWidth(), getMomentaKick(), RFCavity(), RFCavity(), and setGapWidth().
geometry
StraightGeometry TravelingWaveRep::geometry private
The cavity's geometry.
Definition at line 95 of file TravelingWaveRep.h.
Referenced by getGeometry(), and getGeometry().
ignoreCavities
bool TravelingWaveRep::ignoreCavities = false static private
Cavities are ignored (amplitude = 0) when this switch is set.
Definition at line 101 of file TravelingWaveRep.h.
Referenced by getAmplitude(), and setIgnore().
mappedStartExitField_m
double TravelingWave::mappedStartExitField_m private inherited
Definition at line 115 of file TravelingWave.h.
Referenced by apply(), apply(), applyToReferenceParticle(), initialise(), TravelingWave(), and TravelingWave().
misalignment_m
CoordinateSystemTrafo ElementBase::misalignment_m protected inherited
Definition at line 437 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getMisalignment(), and setMisalignment().
mode_m
double TravelingWave::mode_m private inherited
Definition at line 120 of file TravelingWave.h.
Referenced by getAutoPhaseEstimate(), initialise(), setMode(), setPhasem(), TravelingWave(), and TravelingWave().
num_points_m
int RFCavity::num_points_m private inherited
Definition at line 240 of file RFCavity.h.
Referenced by initialise(), RFCavity(), RFCavity(), and spline().
numCells_m
int TravelingWave::numCells_m private inherited
Definition at line 118 of file TravelingWave.h.
Referenced by getAutoPhaseEstimate(), initialise(), setNumCells(), setPhasem(), TravelingWave(), and TravelingWave().
online_m
bool Component::online_m protected inherited
Definition at line 226 of file Component.h.
Referenced by Component(), Component(), Probe::doGoOffline(), BendBase::finalise(), Multipole::finalise(), PluginElement::finalise(), Ring::finalise(), goOffline(), PluginElement::goOffline(), RFCavity::goOffline(), Solenoid::goOffline(), goOnline(), Corrector::goOnline(), Monitor::goOnline(), RFCavity::goOnline(), Solenoid::goOnline(), TravelingWave::goOnline(), BendBase::initialise(), Multipole::initialise(), Ring::initialise(), Online(), and PluginElement::~PluginElement().
outputfn_m
std::string ElementBase::outputfn_m private inherited
The name of the outputfile
Definition at line 470 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), and getOutputFN().
parmatint_m
ParticleMatterInteractionHandler* ElementBase::parmatint_m private inherited
Definition at line 461 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getParticleMatterInteraction(), hasParticleMatterInteraction(), and setParticleMatterInteraction().
pdis_m
double RFCavity::pdis_m private inherited
Definition at line 233 of file RFCavity.h.
Referenced by getPerpenDistance(), RFCavity(), RFCavity(), and setPerpenDistance().
periodLength_m
double TravelingWave::periodLength_m private inherited
Definition at line 117 of file TravelingWave.h.
Referenced by apply(), apply(), applyToReferenceParticle(), initialise(), isInside(), TravelingWave(), and TravelingWave().
phase_m
double RFCavity::phase_m protected inherited
phase shift of time varying field (rad)
Definition at line 210 of file RFCavity.h.
Referenced by apply(), apply(), TravelingWave::apply(), TravelingWave::apply(), applyToReferenceParticle(), TravelingWave::applyToReferenceParticle(), TravelingWave::getAutoPhaseEstimate(), getPhasem(), getPhasem(), TravelingWave::initialise(), RFCavity(), RFCavity(), TestRFCavity::setPhaseInternal(), TestTravelingWave::setPhaseInternal(), setPhasem(), and TravelingWave::setPhasem().
phaseCore1_m
double TravelingWave::phaseCore1_m private inherited
Definition at line 109 of file TravelingWave.h.
Referenced by apply(), apply(), applyToReferenceParticle(), getAutoPhaseEstimate(), initialise(), setPhasem(), TravelingWave(), and TravelingWave().
phaseCore2_m
double TravelingWave::phaseCore2_m private inherited
Definition at line 110 of file TravelingWave.h.
Referenced by apply(), apply(), applyToReferenceParticle(), getAutoPhaseEstimate(), initialise(), setPhasem(), TravelingWave(), and TravelingWave().
phaseError_m
double RFCavity::phaseError_m protected inherited
phase shift error (rad)
Definition at line 211 of file RFCavity.h.
Referenced by apply(), apply(), TravelingWave::apply(), TravelingWave::apply(), getPhaseError(), RFCavity(), RFCavity(), and setPhaseError().
phaseExit_m
double TravelingWave::phaseExit_m private inherited
Definition at line 111 of file TravelingWave.h.
Referenced by apply(), apply(), applyToReferenceParticle(), getAutoPhaseEstimate(), initialise(), setPhasem(), TravelingWave(), and TravelingWave().
phaseName_m
std::string RFCavity::phaseName_m protected inherited
Definition at line 200 of file RFCavity.h.
Referenced by getPhaseModelName(), RFCavity(), and setPhaseModelName().
phaseTD_m
std::shared_ptr<AbstractTimeDependence> RFCavity::phaseTD_m protected inherited
Definition at line 199 of file RFCavity.h.
Referenced by RFCavity(), RFCavity(), and setPhaseModel().
phi0_m
double RFCavity::phi0_m private inherited
Definition at line 235 of file RFCavity.h.
Referenced by getMomentaKick(), getPhi0(), RFCavity(), RFCavity(), and setPhi0().
positionIsFixed
bool ElementBase::positionIsFixed private inherited
Definition at line 463 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), fixPosition(), isPositioned(), releasePosition(), and setCSTrafoGlobal2Local().
RefPartBunch_m
PartBunch_t* Component::RefPartBunch_m protected inherited
Definition at line 225 of file Component.h.
Referenced by BendBase::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Corrector::apply(), Multipole::apply(), MultipoleT::apply(), MultipoleT::apply(), RFCavity::apply(), RFCavity::apply(), Ring::apply(), ScalingFFAMagnet::apply(), Solenoid::apply(), TravelingWave::apply(), TravelingWave::apply(), VariableRFCavity::apply(), VariableRFCavity::apply(), VerticalFFAMagnet::apply(), BendBase::calcDesignRadius(), BendBase::calcFieldAmplitude(), BendBase::calcGamma(), Component(), MultipoleT::finalise(), ScalingFFAMagnet::finalise(), VariableRFCavity::finalise(), VerticalFFAMagnet::finalise(), Corrector::goOnline(), BendBase::initialise(), ConstantEFieldCavity::initialise(), Corrector::initialise(), Drift::initialise(), Laser::initialise(), Marker::initialise(), Monitor::initialise(), Multipole::initialise(), MultipoleT::initialise(), PluginElement::initialise(), RFCavity::initialise(), RFCavity::initialise(), ScalingFFAMagnet::initialise(), Solenoid::initialise(), TravelingWave::initialise(), VariableRFCavity::initialise(), VerticalFFAMagnet::initialise(), VariableRFCavity::initNull(), Multipole::isFocusing(), MultipoleT::MultipoleT(), ScalingFFAMagnet::ScalingFFAMagnet(), Corrector::setDesignEnergy(), Ring::setRefPartBunch(), RFCavity::trackOnAxisParticle(), and VerticalFFAMagnet::VerticalFFAMagnet().
rmax_m
double RFCavity::rmax_m private inherited
Definition at line 229 of file RFCavity.h.
Referenced by getMomentaKick(), getRmax(), RFCavity(), RFCavity(), and setRmax().
rmin_m
double RFCavity::rmin_m private inherited
Definition at line 228 of file RFCavity.h.
Referenced by getMomentaKick(), getRmin(), RFCavity(), RFCavity(), and setRmin().
RNormal_m
std::unique_ptr<double[]> RFCavity::RNormal_m private inherited
Definition at line 237 of file RFCavity.h.
Referenced by initialise(), RFCavity(), RFCavity(), and spline().
rotationZAxis_m
double ElementBase::rotationZAxis_m protected inherited
Definition at line 443 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getRotationAboutZ(), and setRotationAboutZ().
scale_m
double RFCavity::scale_m protected inherited
scale multiplier
Definition at line 208 of file RFCavity.h.
Referenced by apply(), apply(), TravelingWave::apply(), TravelingWave::apply(), applyToReferenceParticle(), TravelingWave::applyToReferenceParticle(), getAmplitudem(), getAutoPhaseEstimate(), TravelingWave::getAutoPhaseEstimate(), getMomentaKick(), TravelingWave::initialise(), RFCavity(), RFCavity(), setAmplitudem(), TestRFCavity::setScale(), and TestTravelingWave::setScale().
scaleCore_m
double TravelingWave::scaleCore_m private inherited
Definition at line 106 of file TravelingWave.h.
Referenced by apply(), apply(), applyToReferenceParticle(), getAutoPhaseEstimate(), initialise(), TestTravelingWave::setScaleCore(), TravelingWave(), and TravelingWave().
scaleCoreError_m
double TravelingWave::scaleCoreError_m private inherited
Definition at line 107 of file TravelingWave.h.
Referenced by apply(), apply(), initialise(), TestTravelingWave::setScaleCoreError(), TravelingWave(), and TravelingWave().
scaleError_m
double RFCavity::scaleError_m protected inherited
additive scale error
Definition at line 209 of file RFCavity.h.
Referenced by apply(), apply(), TravelingWave::apply(), TravelingWave::apply(), getAmplitudeError(), TravelingWave::initialise(), RFCavity(), RFCavity(), setAmplitudeError(), and TestTravelingWave::setScaleError().
shareFlag
bool ElementBase::shareFlag mutable protected inherited
Definition at line 434 of file ElementBase.h.
Referenced by Beamline::Beamline(), Beamline::Beamline(), Beamline::Beamline(), ElementBase(), ElementBase(), isSharable(), makeSharable(), and TBeamline< T >::makeSharable().
sinAngle_m
double RFCavity::sinAngle_m private inherited
Definition at line 231 of file RFCavity.h.
Referenced by getMomentaKick(), getSinAzimuth(), initialise(), RFCavity(), and RFCavity().
startCoreField_m
double TravelingWave::startCoreField_m private inherited
starting point of field(m)
Definition at line 113 of file TravelingWave.h.
Referenced by apply(), apply(), applyToReferenceParticle(), initialise(), TravelingWave(), and TravelingWave().
startExitField_m
double TravelingWave::startExitField_m private inherited
Definition at line 114 of file TravelingWave.h.
Referenced by apply(), apply(), applyToReferenceParticle(), initialise(), isInside(), TravelingWave(), and TravelingWave().
startField_m
double RFCavity::startField_m protected inherited
starting point of field(m)
Definition at line 220 of file RFCavity.h.
Referenced by apply(), apply(), TravelingWave::apply(), TravelingWave::apply(), applyToReferenceParticle(), TravelingWave::applyToReferenceParticle(), getFieldExtend(), TravelingWave::getFieldExtend(), initialise(), TravelingWave::initialise(), RFCavity(), RFCavity(), TestRFCavity::setStartField(), TestTravelingWave::setStartField(), and trackOnAxisParticle().
type_m
CavityType RFCavity::type_m private inherited
Definition at line 224 of file RFCavity.h.
Referenced by getCavityType(), getCavityTypeString(), RFCavity(), RFCavity(), and setCavityType().
userAttribs
AttributeSet ElementBase::userAttribs private inherited
Definition at line 455 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getChannel(), and removeAttribute().
VrNormal_m
std::unique_ptr<double[]> RFCavity::VrNormal_m private inherited
Definition at line 238 of file RFCavity.h.
Referenced by initialise(), RFCavity(), RFCavity(), and spline().
wake_m
WakeFunction* ElementBase::wake_m private inherited
Definition at line 457 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getWake(), hasWake(), and setWake().
The documentation for this class was generated from the following files:
TravelingWaveRep.h
TravelingWaveRep.cpp