OPALX (Object Oriented Parallel Accelerator Library for Exascal): Attributes::UpperCaseStringArray Class Reference
Attributes::UpperCaseStringArray Class Reference
Parser for an attribute of type string array.
#include <UpperCaseStringArray.h>
Public Types
enum OwnerType {
ELEMENT , COMMAND , SUB_COMMAND , STATEMENT ,
NONE
}
Public Member Functions
UpperCaseStringArray (const std::string &name, const std::string &help)
Constructor.
virtual ~UpperCaseStringArray ()
virtual const std::string & getType () const
Return attribute type string `‘string array’'.
virtual void parse (Attribute &, Statement &, bool) const
Parse the attribute.
virtual void parseComponent (Attribute &, Statement &, bool, int) const
Parse a component of the array.
virtual AttributeBase * getDefault () const
Return default value.
virtual const std::string & getHelp () const
Return help string.
virtual const std::string & getName () const
Return attribute name.
bool isDeferred () const
Return defer flag.
void setDeferred (bool)
Set or reset defer flag.
bool isReadOnly () const
Return read-only flag.
void setReadOnly (bool)
Set or reset read-only flag.
void setPredefinedValues (const std::set< std::string > &, const std::string &)
Add predefined strings values to the help.
Static Public Member Functions
static std::multimap< OwnerType, std::string > getOwner (const std::string &att)
static void addAttributeOwner (const std::string &owner, const OwnerType &type, const std::string &name)
Protected Attributes
const std::string itsName
Attribute name.
const std::string itsHelp
Help text.
std::shared_ptr< AttributeBase > itsDefault
Default value.
bool is_deferred
Defer flag.
bool is_readonly
Read-only flag.
Private Member Functions
UpperCaseStringArray ()
UpperCaseStringArray (const UpperCaseStringArray &)
void operator= (const UpperCaseStringArray &)
Static Private Attributes
static std::multimap< std::string, std::pair< OwnerType, std::string > > attributeOwnerDictionary_s
Detailed Description
Parser for an attribute of type string array.
Definition at line 30 of file UpperCaseStringArray.h.
Member Enumeration Documentation
OwnerType
enum AttributeHandler::OwnerType inherited
Enumerator
ELEMENT
COMMAND
SUB_COMMAND
STATEMENT
NONE
Definition at line 113 of file AttributeHandler.h.
Constructor & Destructor Documentation
UpperCaseStringArray() [1/3]
Attributes::UpperCaseStringArray::UpperCaseStringArray (const std::string & name, const std::string & help)
Constructor.
Definition at line 33 of file UpperCaseStringArray.cpp.
~UpperCaseStringArray()
Attributes::UpperCaseStringArray::~UpperCaseStringArray () virtual
Definition at line 38 of file UpperCaseStringArray.cpp.
UpperCaseStringArray() [2/3]
Attributes::UpperCaseStringArray::UpperCaseStringArray () private
UpperCaseStringArray() [3/3]
Attributes::UpperCaseStringArray::UpperCaseStringArray (const UpperCaseStringArray &) private
Member Function Documentation
addAttributeOwner()
void AttributeHandler::addAttributeOwner (const std::string & owner, const OwnerType & type, const std::string & name) static inherited
Definition at line 123 of file AttributeHandler.cpp.
References AttributeHandler::attributeOwnerDictionary_s.
Referenced by OpalElement::OpalElement(), OpalElement::registerOwnership(), Object::registerOwnership(), and TrackCmd::TrackCmd().
getDefault()
AttributeBase * AttributeHandler::getDefault () const virtual inherited
Return default value.
Definition at line 43 of file AttributeHandler.cpp.
References AttributeHandler::itsDefault, and AttributeHandler::itsName.
getHelp()
const std::string & AttributeHandler::getHelp () const virtual inherited
Return help string.
Definition at line 53 of file AttributeHandler.cpp.
References AttributeHandler::itsHelp.
Referenced by Attribute::getHelp().
getName()
const std::string & AttributeHandler::getName () const virtual inherited
Return attribute name.
Definition at line 58 of file AttributeHandler.cpp.
References AttributeHandler::itsName.
getOwner()
std::multimap< AttributeHandler::OwnerType, std::string > AttributeHandler::getOwner (const std::string & att) static inherited
Definition at line 107 of file AttributeHandler.cpp.
References AttributeHandler::attributeOwnerDictionary_s.
Referenced by OpalParser::getHint().
getType()
const std::string & Attributes::UpperCaseStringArray::getType () const virtual
Return attribute type string `‘string array’'.
Implements AttributeHandler.
Definition at line 42 of file UpperCaseStringArray.cpp.
isDeferred()
bool AttributeHandler::isDeferred () const inherited
Return defer flag.
Definition at line 72 of file AttributeHandler.cpp.
References AttributeHandler::is_deferred.
Referenced by Attributes::Real::parse().
isReadOnly()
bool AttributeHandler::isReadOnly () const inherited
Return read-only flag.
Definition at line 82 of file AttributeHandler.cpp.
References AttributeHandler::is_readonly.
operator=()
void Attributes::UpperCaseStringArray::operator= (const UpperCaseStringArray &) private
parse()
void Attributes::UpperCaseStringArray::parse (Attribute & attr, Statement & stat, bool) const virtual
Parse the attribute.
Implements AttributeHandler.
Definition at line 48 of file UpperCaseStringArray.cpp.
References Expressions::parseStringArray(), and Attributes::setUpperCaseStringArray().
parseComponent()
void Attributes::UpperCaseStringArray::parseComponent (Attribute & attr, Statement & statement, bool , int index) const virtual
Parse a component of the array.
Reimplemented from AttributeHandler.
Definition at line 54 of file UpperCaseStringArray.cpp.
References Attribute::getBase(), Attributes::getStringArray(), Expressions::parseStringValue(), and Attributes::setUpperCaseStringArray().
setDeferred()
void AttributeHandler::setDeferred (bool flag) inherited
Set or reset defer flag.
Definition at line 77 of file AttributeHandler.cpp.
References AttributeHandler::is_deferred.
setPredefinedValues()
void AttributeHandler::setPredefinedValues (const std::set< std::string > & predefinedValues, const std::string & defaultValue) inherited
Add predefined strings values to the help.
Definition at line 91 of file AttributeHandler.cpp.
References AttributeHandler::itsHelp.
Referenced by Attributes::PredefinedString::PredefinedString().
setReadOnly()
void AttributeHandler::setReadOnly (bool flag) inherited
Set or reset read-only flag.
Definition at line 87 of file AttributeHandler.cpp.
References AttributeHandler::is_readonly.
Member Data Documentation
attributeOwnerDictionary_s
std::multimap< std::string, std::pair< AttributeHandler::OwnerType, std::string > > AttributeHandler::attributeOwnerDictionary_s static private inherited
Definition at line 146 of file AttributeHandler.h.
Referenced by AttributeHandler::addAttributeOwner(), and AttributeHandler::getOwner().
is_deferred
bool AttributeHandler::is_deferred protected inherited
Defer flag.
Definition at line 134 of file AttributeHandler.h.
Referenced by AttributeHandler::isDeferred(), Attributes::Bool::parse(), Attributes::BoolArray::parse(), Attributes::RealArray::parse(), and AttributeHandler::setDeferred().
is_readonly
bool AttributeHandler::is_readonly protected inherited
Read-only flag.
Definition at line 137 of file AttributeHandler.h.
Referenced by AttributeHandler::isReadOnly(), and AttributeHandler::setReadOnly().
itsDefault
std::shared_ptr<AttributeBase> AttributeHandler::itsDefault protected inherited
Default value.
Definition at line 131 of file AttributeHandler.h.
Referenced by AttributeHandler::getDefault().
itsHelp
const std::string AttributeHandler::itsHelp protected inherited
Help text.
Definition at line 128 of file AttributeHandler.h.
Referenced by AttributeHandler::getHelp(), and AttributeHandler::setPredefinedValues().
itsName
const std::string AttributeHandler::itsName protected inherited
Attribute name.
Definition at line 125 of file AttributeHandler.h.
Referenced by AttributeHandler::getDefault(), AttributeHandler::getName(), and AttributeHandler::parseComponent().
The documentation for this class was generated from the following files:
UpperCaseStringArray.h
UpperCaseStringArray.cpp