OPALX (Object Oriented Parallel Accelerator Library for Exascal): ElementBase Class Reference
ElementBase Class Reference abstract
#include <ElementBase.h>
Public Member Functions
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
virtual ElementType getType () const =0
Get element type std::string.
std::string getTypeString () const
virtual BGeometryBase & getGeometry ()=0
Get geometry.
virtual const BGeometryBase & getGeometry () const =0
Get geometry.
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
Return the nominal body extent of the element.
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual void accept (BeamlineVisitor &visitor) const =0
Apply visitor.
virtual ElementBase * clone () const =0
Return clone.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
virtual Port getEntryPort () const
Return the entrance port of the canonical local chart.
virtual Port getBodyPort () const
Return the body port of the canonical local chart.
virtual Port getExitPort () const
Return the exit port of the canonical local chart.
PlacementPose getPlacementPose () const
Return the nominal rigid placement transform of the element.
void setPlacementPose (const PlacementPose &pose)
Set the nominal rigid placement transform of the element.
Misalignment getPlacementMisalignment () const
Return the local nominal-to-actual correction stored for the element.
ElementGeometry getPlacementGeometry () const
Return the bridge geometry ports assembled from legacy edge state.
SupportPlacement getPlacementSupport () const
Return the support-frame bridge object. The default is the body frame.
PlacedElement getPlacedElement () const
Return a placed-element view assembled from the current bridge objects.
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t< double, 3 > &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Static Public Member Functions
static std::string getTypeString (ElementType type)
Protected Member Functions
bool isInsideTransverse (const Vector_t< double, 3 > &r) const
Protected Attributes
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Private Member Functions
void operator= (const ElementBase &)
Private Attributes
std::string elementID
AttributeSet userAttribs
WakeFunction * wake_m
BoundaryGeometry * bgeometry_m
ParticleMatterInteractionHandler * parmatint_m
bool positionIsFixed
std::queue< std::pair< double, double > > actionRange_m
std::string outputfn_m
bool deleteOnTransverseExit_m = true
double elementPosition_m
ELEMEDGE attribute.
bool elemedgeSet_m
Static Private Attributes
static const std::map< ElementType, std::string > elementTypeToString_s
Detailed Description
Definition at line 122 of file ElementBase.h.
Constructor & Destructor Documentation
ElementBase() [1/3]
ElementBase::ElementBase (const std::string & name) explicit
Constructor with given name.
Definition at line 113 of file ElementBase.cpp.
References bgeometry_m, csTrafoGlobal2Local_m, elemedgeSet_m, elementEdge_m, elementID, elementPosition_m, misalignment_m, outputfn_m, parmatint_m, positionIsFixed, rotationZAxis_m, shareFlag, userAttribs, and wake_m.
Referenced by Beamline::Beamline(), Beamline::Beamline(), Beamline::Beamline(), ConstantEFieldCavityRep::clone(), DriftRep::clone(), DummyBeamline::clone(), clone(), LaserRep::clone(), MarkerRep::clone(), MonitorRep::clone(), MultipoleRep::clone(), MultipoleT::clone(), RFCavityRep::clone(), Ring::clone(), SolenoidRep::clone(), TestRFCavity::clone(), VariableRFCavity::clone(), VerticalFFAMagnet::clone(), Component::Component(), Component::Component(), copyStructure(), ElementBase(), ElementBase(), getConstChannel(), Component::getDesign(), Component::getFieldExtend(), TBeamline< T >::getTransform(), operator=(), MultipoleT::~MultipoleT(), and VariableRFCavity::~VariableRFCavity().
ElementBase() [2/3]
ElementBase::ElementBase ()
Definition at line 92 of file ElementBase.cpp.
References ElementBase().
ElementBase() [3/3]
ElementBase::ElementBase (const ElementBase & right)
Definition at line 94 of file ElementBase.cpp.
References aperture_m, bgeometry_m, csTrafoGlobal2Local_m, deleteOnTransverseExit_m, elemedgeSet_m, ElementBase(), elementEdge_m, elementID, elementPosition_m, misalignment_m, outputfn_m, parmatint_m, positionIsFixed, rotationZAxis_m, shareFlag, userAttribs, and wake_m.
~ElementBase()
ElementBase::~ElementBase () virtual
Definition at line 129 of file ElementBase.cpp.
Member Function Documentation
accept()
virtual void ElementBase::accept (BeamlineVisitor & visitor) const pure virtual
Apply visitor.
Implemented in ConstantEFieldCavity, Corrector, Drift, DummyBeamline, Laser, Marker, Monitor, Multipole, MultipoleT, Probe, RBend, RFCavity, Ring, SBend, ScalingFFAMagnet, Solenoid, TBeamline< T >, TBeamline< FlaggedElmPtr >, TBeamline< SequenceMember >, TravelingWave, VariableRFCavity, and VerticalFFAMagnet.
Referenced by DefaultVisitor::visitFlaggedElmPtr(), and SpecificElementVisitor< ELEM >::visitFlaggedElmPtr().
clone()
virtual ElementBase * ElementBase::clone () const pure virtual
Return clone.
Implemented in ConstantEFieldCavityRep, DriftRep, DummyBeamline, LaserRep, MarkerRep, MonitorRep, MultipoleRep, MultipoleT, ProbeRep, RBendRep, RFCavityRep, Ring, SBendRep, ScalingFFAMagnet, SolenoidRep, TBeamline< T >, TBeamline< FlaggedElmPtr >, TBeamline< SequenceMember >, TestRFCavity, TestTravelingWave, TravelingWaveRep, VariableRFCavity, and VerticalFFAMagnet.
References ElementBase().
Referenced by Ring::appendElement(), Sequence::copy(), copyStructure(), and RingSection::operator=().
copyStructure()
ElementBase * ElementBase::copyStructure () virtual
Make a structural copy.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 193 of file ElementBase.cpp.
References clone(), ElementBase(), and isSharable().
Referenced by Sequence::copy(), Line::parse(), and SequenceParser::parseMember().
fixPosition()
void ElementBase::fixPosition () inline
Definition at line 596 of file ElementBase.h.
References positionIsFixed.
Referenced by OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
getAperture()
std::pair< ApertureType, std::vector< double > > ElementBase::getAperture () const inline
Definition at line 581 of file ElementBase.h.
References aperture_m.
Referenced by MeshGenerator::add(), Solenoid::getSupportEnvelope(), and MeshGenerator::getTransverseSupport().
getArcLength()
double ElementBase::getArcLength () const inline virtual
Get arc length.
Reimplemented in MarkerRep, TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 478 of file ElementBase.h.
References BGeometryBase::getArcLength(), and getGeometry().
Referenced by TBeamline< T >::getTransform().
getAttribute()
double ElementBase::getAttribute (const std::string & aKey) const virtual
Get attribute value.
Definition at line 146 of file ElementBase.cpp.
References getConstChannel().
getBodyPort()
Port ElementBase::getBodyPort () const inline virtual
Return the body port of the canonical local chart.
The body port \(p_{i,\mathrm{body}}\) is the identity port of the element's canonical local chart. Its rigid transform is therefore the identity element of \(SE(3)\) in the first redesign stage.
Definition at line 546 of file ElementBase.h.
Referenced by getPlacementGeometry(), and TEST_F().
getBoundaryGeometry()
BoundaryGeometry * ElementBase::getBoundaryGeometry () const inline virtual
return the attached boundary geometrt object if there is any
Definition at line 512 of file ElementBase.h.
References bgeometry_m.
getBoundingBoxInLabCoords()
BoundingBox ElementBase::getBoundingBoxInLabCoords () const virtual
Definition at line 263 of file ElementBase.cpp.
References csTrafoGlobal2Local_m, getEdgeToBegin(), and getEdgeToEnd().
getChannel()
Channel * ElementBase::getChannel (const std::string & aKey, bool create = false) virtual
Construct a read/write channel.
Reimplemented in ConstantEFieldCavityRep, DriftRep, LaserRep, MonitorRep, MultipoleRep, ProbeRep, RBendRep, RFCavityRep, SBendRep, SolenoidRep, and TravelingWaveRep.
Definition at line 181 of file ElementBase.cpp.
References userAttribs.
Referenced by ConstantEFieldCavityRep::getChannel(), DriftRep::getChannel(), LaserRep::getChannel(), MonitorRep::getChannel(), MultipoleRep::getChannel(), ProbeRep::getChannel(), RBendRep::getChannel(), RFCavityRep::getChannel(), SBendRep::getChannel(), SolenoidRep::getChannel(), TravelingWaveRep::getChannel(), getConstChannel(), and setAttribute().
getConstChannel()
const ConstChannel * ElementBase::getConstChannel (const std::string & aKey) const virtual
Construct a read-only channel.
Definition at line 185 of file ElementBase.cpp.
References ElementBase(), and getChannel().
Referenced by getAttribute(), and hasAttribute().
getCSTrafoGlobal2Local()
CoordinateSystemTrafo ElementBase::getCSTrafoGlobal2Local () const inline
Definition at line 528 of file ElementBase.h.
References csTrafoGlobal2Local_m.
Referenced by getPlacementPose(), OpalRBend::update(), and OpalSBend::update().
getEdgeToBegin()
CoordinateSystemTrafo ElementBase::getEdgeToBegin () const inline virtual
Reimplemented in BendBase, RFCavity, Solenoid, and TravelingWave.
Definition at line 532 of file ElementBase.h.
Referenced by getBoundingBoxInLabCoords(), getEntryPort(), and isInsideTransverse().
getEdgeToEnd()
CoordinateSystemTrafo ElementBase::getEdgeToEnd () const inline virtual
Reimplemented in BendBase, RFCavity, Solenoid, and TravelingWave.
Definition at line 537 of file ElementBase.h.
References getElementLength().
Referenced by getBoundingBoxInLabCoords(), and getExitPort().
getElementDimensions()
virtual void ElementBase::getElementDimensions (double & begin, double & end) const inline virtual
Return the nominal body extent of the element.
The first placement redesign stage distinguishes between the nominal body extent and the field-support extent. The body extent is the canonical longitudinal interval of the placed hardware, \([z_\mathrm{body}^{\mathrm{begin}}, z_\mathrm{body}^{\mathrm{end}}]\), and therefore drives ports, placement, and visualization. By default it coincides with the geometry length \([0, L]\) in the local chart.
Reimplemented in RFCavity, Solenoid, and TravelingWave.
Definition at line 177 of file ElementBase.h.
References getElementLength().
Referenced by MeshGenerator::add().
getElementLength()
double ElementBase::getElementLength () const inline virtual
Get design length.
Reimplemented in MarkerRep, RFCavity, TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 480 of file ElementBase.h.
References BGeometryBase::getElementLength(), and getGeometry().
Referenced by MeshGenerator::add(), BendBase::apply(), Component::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Multipole::apply(), Multipole::apply(), Multipole::apply(), VariableRFCavity::apply(), VariableRFCavity::apply(), VariableRFCavity::apply(), Component::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), getEdgeToEnd(), Solenoid::getEdgeToEnd(), getElementDimensions(), Solenoid::getElementDimensions(), RFCavity::getElementLength(), BendBase::getFieldExtend(), ConstantEFieldCavity::getFieldExtend(), Corrector::getFieldExtend(), Drift::getFieldExtend(), Laser::getFieldExtend(), Multipole::getFieldExtend(), MultipoleT::getFieldExtend(), VariableRFCavity::getFieldExtend(), BendBase::getLength(), BendBase::initialise(), ConstantEFieldCavity::initialise(), Corrector::initialise(), Drift::initialise(), Laser::initialise(), Multipole::initialise(), BendBase::isInside(), isInside(), Monitor::isInside(), Multipole::isInside(), isInsideTransverse(), and TEST_F().
getElementPosition()
double ElementBase::getElementPosition () const inline
Definition at line 617 of file ElementBase.h.
References elemedgeSet_m, elementPosition_m, and getName().
getEntrance()
double ElementBase::getEntrance () const inline virtual
Get entrance position.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 486 of file ElementBase.h.
References BGeometryBase::getEntrance(), and getGeometry().
Referenced by BendBase::getDesignPath().
getEntranceFrame()
Euclid3D ElementBase::getEntranceFrame () const inline virtual
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 498 of file ElementBase.h.
References BGeometryBase::getEntranceFrame(), and getGeometry().
Referenced by BendBase::getChordLength(), and BendBase::getEdgeToBegin().
getEntrancePatch()
Euclid3D ElementBase::getEntrancePatch () const inline virtual
Get patch.
Definition at line 502 of file ElementBase.h.
References BGeometryBase::getEntrancePatch(), and getGeometry().
getEntryPort()
Port ElementBase::getEntryPort () const inline virtual
Return the entrance port of the canonical local chart.
In the placement-note language, this is the marked entrance port \(p_{i,\mathrm{entry}}\) of element \(i\). For straight elements in the bridge stage, the body-to-entry transform is taken from the legacy getEdgeToBegin() result.
Definition at line 544 of file ElementBase.h.
References getEdgeToBegin().
Referenced by getPlacementGeometry(), and TEST_F().
getExit()
double ElementBase::getExit () const inline virtual
Get exit position.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 488 of file ElementBase.h.
References BGeometryBase::getExit(), and getGeometry().
Referenced by BendBase::getDesignPath().
getExitFrame()
Euclid3D ElementBase::getExitFrame () const inline virtual
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 500 of file ElementBase.h.
References BGeometryBase::getExitFrame(), and getGeometry().
Referenced by BendBase::getChordLength(), and BendBase::getEdgeToEnd().
getExitPatch()
Euclid3D ElementBase::getExitPatch () const inline virtual
Get patch.
Definition at line 504 of file ElementBase.h.
References BGeometryBase::getExitPatch(), and getGeometry().
getExitPort()
Port ElementBase::getExitPort () const inline virtual
Return the exit port of the canonical local chart.
In the placement-note language, this is the marked exit port \(p_{i,\mathrm{exit}}\). For straight elements in the bridge stage, the body-to-exit transform is taken from the legacy getEdgeToEnd() result.
Definition at line 548 of file ElementBase.h.
References getEdgeToEnd().
Referenced by getPlacementGeometry(), and TEST_F().
getFlagDeleteOnTransverseExit()
bool ElementBase::getFlagDeleteOnTransverseExit () const inline
Definition at line 633 of file ElementBase.h.
References deleteOnTransverseExit_m.
Referenced by BendBase::apply(), BendBase::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Multipole::apply(), Multipole::apply(), RFCavity::apply(), Solenoid::apply(), and TravelingWave::apply().
getGeometry() [1/2]
virtual const BGeometryBase & ElementBase::getGeometry () const pure virtual
Get geometry.
Implemented in ConstantEFieldCavityRep, Corrector, DriftRep, DummyBeamline, LaserRep, MarkerRep, Monitor, MonitorRep, Multipole, MultipoleRep, MultipoleT, ProbeRep, RBend, RBendRep, RFCavityRep, Ring, SBend, SBendRep, ScalingFFAMagnet, SolenoidRep, TBeamline< T >, TBeamline< FlaggedElmPtr >, TBeamline< SequenceMember >, TestRFCavity, TestTravelingWave, TravelingWaveRep, VariableRFCavity, and VerticalFFAMagnet.
getGeometry() [2/2]
virtual BGeometryBase & ElementBase::getGeometry () pure virtual
Get geometry.
Implemented in ConstantEFieldCavityRep, Corrector, DriftRep, DummyBeamline, LaserRep, MarkerRep, Monitor, MonitorRep, Multipole, MultipoleRep, MultipoleT, ProbeRep, RBend, RBendRep, RFCavityRep, Ring, SBend, SBendRep, ScalingFFAMagnet, SolenoidRep, TBeamline< T >, TBeamline< FlaggedElmPtr >, TBeamline< SequenceMember >, TestRFCavity, TestTravelingWave, TravelingWaveRep, VariableRFCavity, and VerticalFFAMagnet.
Referenced by Ring::appendElement(), getArcLength(), getElementLength(), getEntrance(), getEntranceFrame(), getEntrancePatch(), getExit(), getExitFrame(), getExitPatch(), getOrigin(), getTotalTransform(), getTransform(), getTransform(), and setElementLength().
getMisalignment() [1/2]
CoordinateSystemTrafo ElementBase::getMisalignment () const inline
Definition at line 592 of file ElementBase.h.
References misalignment_m.
Referenced by getPlacementMisalignment().
getMisalignment() [2/2]
void ElementBase::getMisalignment (double & x, double & y, double & s) const
getName()
const std::string & ElementBase::getName () const virtual
Get element name.
Definition at line 131 of file ElementBase.cpp.
References elementID.
Referenced by Ring::appendElement(), TBeamline< T >::clone(), TBeamline< T >::copyStructure(), Probe::doGoOffline(), PlaceRep::enter(), getElementPosition(), RFCavity::getMomentaKick(), getOutputFN(), CavityAutophaser::getPhaseAtMaxEnergy(), Selector::handleElement(), RFCavity::initialise(), Ring::initialise(), Solenoid::initialise(), PlaceRep::leave(), VariableRFCavity::operator=(), Sequence::print(), Ring::Ring(), BeamlineFieldElement::SortAsc(), TEST_F(), Component::trackBunch(), Component::trackMap(), OpalRBend::update(), OpalSBend::update(), Sequence::updateList(), ParallelTracker::updateRFElement(), and Replacer::visitFlaggedElmPtr().
getOrigin()
double ElementBase::getOrigin () const inline virtual
Get origin position.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 484 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getOrigin().
getOutputFN()
std::string ElementBase::getOutputFN () const
Get output filename.
Definition at line 137 of file ElementBase.cpp.
References getName(), and outputfn_m.
Referenced by Probe::doInitialise(), Monitor::initialise(), and PluginElement::initialise().
getParticleMatterInteraction()
ParticleMatterInteractionHandler * ElementBase::getParticleMatterInteraction () const inline virtual
Definition at line 516 of file ElementBase.h.
References parmatint_m.
getPlacedElement()
PlacedElement ElementBase::getPlacedElement () const inline
Return a placed-element view assembled from the current bridge objects.
Definition at line 570 of file ElementBase.h.
References getPlacementGeometry(), getPlacementMisalignment(), getPlacementPose(), and getPlacementSupport().
Referenced by MeshGenerator::add(), and TEST_F().
getPlacementGeometry()
ElementGeometry ElementBase::getPlacementGeometry () const inline
Return the bridge geometry ports assembled from legacy edge state.
The first redesign stage defines a minimal explicit port contract with three named body-relative ports: \(p_{i,\mathrm{entry}}\), \(p_{i,\mathrm{body}}\), \(p_{i,\mathrm{exit}}\). The default bridge preserves current OPALX behavior by deriving those ports from getEntryPort(), getBodyPort(), and getExitPort(), whose straight-element implementations are backed by the legacy getEdgeToBegin() and getEdgeToEnd() methods.
Definition at line 562 of file ElementBase.h.
References getBodyPort(), getEntryPort(), and getExitPort().
Referenced by getPlacedElement().
getPlacementMisalignment()
Misalignment ElementBase::getPlacementMisalignment () const inline
Return the local nominal-to-actual correction stored for the element.
Definition at line 558 of file ElementBase.h.
References getMisalignment().
Referenced by getPlacedElement().
getPlacementPose()
PlacementPose ElementBase::getPlacementPose () const inline
Return the nominal rigid placement transform of the element.
This is the bridge from the legacy stored CoordinateSystemTrafo to the new placement vocabulary. It preserves current nominal placement semantics and does not apply misalignment.
Definition at line 550 of file ElementBase.h.
References getCSTrafoGlobal2Local().
Referenced by getPlacedElement().
getPlacementSupport()
SupportPlacement ElementBase::getPlacementSupport () const inline
Return the support-frame bridge object. The default is the body frame.
Definition at line 566 of file ElementBase.h.
Referenced by getPlacedElement().
getRequiredNumberOfTimeSteps()
int ElementBase::getRequiredNumberOfTimeSteps () const inline virtual
Reimplemented in BendBase, Drift, Laser, Marker, and Monitor.
Definition at line 627 of file ElementBase.h.
getRotationAboutZ()
double ElementBase::getRotationAboutZ () const inline
Definition at line 608 of file ElementBase.h.
References rotationZAxis_m.
Referenced by OpalBeamline::compileCompatibilityPlacement().
getTotalTransform()
Euclid3D ElementBase::getTotalTransform () const inline virtual
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 494 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getTotalTransform().
getTransform() [1/2]
Euclid3D ElementBase::getTransform (double fromS, double toS) const inline virtual
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 490 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getTransform().
Referenced by BendBase::getDesignPath(), and TBeamline< T >::getTransform().
getTransform() [2/2]
Euclid3D ElementBase::getTransform (double s) const inline virtual
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 496 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getTransform().
getType()
virtual ElementType ElementBase::getType () const pure virtual
Get element type std::string.
Implemented in Component, ConstantEFieldCavity, Corrector, Drift, DummyBeamline, Laser, Marker, Monitor, Multipole, Probe, RBend, RFCavity, SBend, Solenoid, TBeamline< T >, TBeamline< FlaggedElmPtr >, TBeamline< SequenceMember >, and TravelingWave.
Referenced by MeshGenerator::add(), MeshGenerator::getTransverseSupport(), and getTypeString().
getTypeString() [1/2]
std::string ElementBase::getTypeString () const inline
Definition at line 610 of file ElementBase.h.
References getType(), and getTypeString().
Referenced by getTypeString().
getTypeString() [2/2]
std::string ElementBase::getTypeString (ElementType type) static
Definition at line 191 of file ElementBase.cpp.
References elementTypeToString_s.
getWake()
WakeFunction * ElementBase::getWake () const inline virtual
return the attached wake object if there is any
Definition at line 508 of file ElementBase.h.
References wake_m.
hasAttribute()
bool ElementBase::hasAttribute (const std::string & aKey) const virtual
Test for existence of an attribute.
Definition at line 158 of file ElementBase.cpp.
References getConstChannel().
hasBoundaryGeometry()
bool ElementBase::hasBoundaryGeometry () const inline virtual
Definition at line 514 of file ElementBase.h.
References bgeometry_m.
hasParticleMatterInteraction()
bool ElementBase::hasParticleMatterInteraction () const inline virtual
Definition at line 520 of file ElementBase.h.
References parmatint_m.
hasWake()
bool ElementBase::hasWake () const inline virtual
Definition at line 510 of file ElementBase.h.
References wake_m.
isElementPositionSet()
bool ElementBase::isElementPositionSet () const inline
Definition at line 625 of file ElementBase.h.
References elemedgeSet_m.
isInside()
bool ElementBase::isInside (const Vector_t< double, 3 > & r) const inline virtual
Reimplemented in BendBase, Monitor, Multipole, RFCavity, Solenoid, and TravelingWave.
Definition at line 585 of file ElementBase.h.
References getElementLength(), and isInsideTransverse().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
isInsideTransverse()
bool ElementBase::isInsideTransverse (const Vector_t< double, 3 > & r) const protected
Definition at line 232 of file ElementBase.cpp.
References aperture_m, CONIC_ELLIPTICAL, CONIC_RECTANGULAR, getEdgeToBegin(), getElementLength(), and CoordinateSystemTrafo::transformTo().
Referenced by BendBase::apply(), BendBase::apply(), Component::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Multipole::apply(), Multipole::apply(), BendBase::applyToReferenceParticle(), Component::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), BendBase::isInside(), isInside(), Monitor::isInside(), Multipole::isInside(), RFCavity::isInside(), Solenoid::isInside(), and TravelingWave::isInside().
isPositioned()
bool ElementBase::isPositioned () const inline
Definition at line 598 of file ElementBase.h.
References positionIsFixed.
Referenced by OpalRBend::update(), and OpalSBend::update().
isSharable()
bool ElementBase::isSharable () const inline
Test if the element can be shared.
Definition at line 506 of file ElementBase.h.
References shareFlag.
Referenced by copyStructure(), TBeamline< T >::copyStructure(), and Sequence::updateList().
makeSharable()
void ElementBase::makeSharable () virtual
Set sharable flag.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 201 of file ElementBase.cpp.
References shareFlag.
Referenced by OpalMarker::OpalMarker().
operator=()
void ElementBase::operator= (const ElementBase &) private
References ElementBase().
releasePosition()
void ElementBase::releasePosition () inline
Definition at line 594 of file ElementBase.h.
References positionIsFixed.
Referenced by OpalRBend::update(), and OpalSBend::update().
removeAttribute()
void ElementBase::removeAttribute (const std::string & aKey) virtual
Remove an existing attribute.
Definition at line 169 of file ElementBase.cpp.
References userAttribs.
setActionRange()
void ElementBase::setActionRange (const std::queue< std::pair< double, double > > & range) inline
Definition at line 600 of file ElementBase.h.
References actionRange_m, and elementEdge_m.
setAperture()
void ElementBase::setAperture (const ApertureType & type, const std::vector< double > & args) inline
Definition at line 576 of file ElementBase.h.
References aperture_m.
Referenced by Component::Component(), TEST_F(), TEST_F(), TEST_F(), OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
setAttribute()
void ElementBase::setAttribute (const std::string & aKey, double val) virtual
Set value of an attribute.
Definition at line 171 of file ElementBase.cpp.
References getChannel(), and Channel::isSettable().
Referenced by update(), and OpalElement::updateUnknown().
setBoundaryGeometry()
void ElementBase::setBoundaryGeometry (BoundaryGeometry * geo) virtual
attach a boundary geometry field to the element
Definition at line 215 of file ElementBase.cpp.
References bgeometry_m.
setCSTrafoGlobal2Local()
void ElementBase::setCSTrafoGlobal2Local (const CoordinateSystemTrafo & ori) inline
Definition at line 522 of file ElementBase.h.
References csTrafoGlobal2Local_m, and positionIsFixed.
Referenced by setPlacementPose(), TEST_F(), OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
setCurrentSCoordinate()
void ElementBase::setCurrentSCoordinate (double s)
Definition at line 223 of file ElementBase.cpp.
References actionRange_m, and elementEdge_m.
setElementLength()
void ElementBase::setElementLength (double length) inline virtual
Set design length.
Reimplemented in ConstantEFieldCavityRep, and MultipoleT.
Definition at line 482 of file ElementBase.h.
References getGeometry(), and BGeometryBase::setElementLength().
Referenced by MultipoleT::setElementLength(), BendBase::setLength(), SequenceMember::setLength(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), OpalCavity::update(), OpalMonitor::update(), OpalMultipole::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalSolenoid::update(), and OpalTravelingWave::update().
setElementPosition()
void ElementBase::setElementPosition (double elemedge) inline
Access to ELEMEDGE attribute.
Definition at line 612 of file ElementBase.h.
References elemedgeSet_m, and elementPosition_m.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and OpalElement::update().
setFlagDeleteOnTransverseExit()
void ElementBase::setFlagDeleteOnTransverseExit (bool flag = true) inline
Definition at line 629 of file ElementBase.h.
References deleteOnTransverseExit_m.
Referenced by OpalElement::update().
setMisalignment()
void ElementBase::setMisalignment (const CoordinateSystemTrafo & cst) inline
Definition at line 590 of file ElementBase.h.
References misalignment_m.
Referenced by TEST_F(), and OpalElement::update().
setName()
void ElementBase::setName (const std::string & name) virtual
Set element name.
Definition at line 133 of file ElementBase.cpp.
References elementID.
Referenced by Sequence::insertDrifts(), and VariableRFCavity::operator=().
setOutputFN()
void ElementBase::setOutputFN (std::string fn)
Set output filename.
Definition at line 135 of file ElementBase.cpp.
Referenced by OpalMonitor::update(), and OpalProbe::update().
setParticleMatterInteraction()
void ElementBase::setParticleMatterInteraction (ParticleMatterInteractionHandler * spys) virtual
Definition at line 219 of file ElementBase.cpp.
References parmatint_m.
setPlacementPose()
void ElementBase::setPlacementPose (const PlacementPose & pose) inline
Set the nominal rigid placement transform of the element.
This bridge setter preserves the existing storage model by delegating to setCSTrafoGlobal2Local().
Definition at line 554 of file ElementBase.h.
References PlacementPose::getParentToNominal(), and setCSTrafoGlobal2Local().
setRotationAboutZ()
void ElementBase::setRotationAboutZ (double rotation) inline
Set rotation about z axis in bend frame.
Definition at line 606 of file ElementBase.h.
References rotationZAxis_m.
Referenced by OpalElement::update().
setWake()
void ElementBase::setWake (WakeFunction * wf) virtual
attach a wake field to the element
Definition at line 211 of file ElementBase.cpp.
References wake_m.
update()
bool ElementBase::update (const AttributeSet & set)
Update element.
Definition at line 203 of file ElementBase.cpp.
References AttributeSet::begin(), AttributeSet::end(), and setAttribute().
Member Data Documentation
actionRange_m
std::queue<std::pair<double, double> > ElementBase::actionRange_m private
Definition at line 468 of file ElementBase.h.
Referenced by setActionRange(), and setCurrentSCoordinate().
aperture_m
std::pair<ApertureType, std::vector<double> > ElementBase::aperture_m protected
Definition at line 439 of file ElementBase.h.
Referenced by ElementBase(), getAperture(), isInsideTransverse(), and setAperture().
bgeometry_m
BoundaryGeometry* ElementBase::bgeometry_m private
Definition at line 459 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getBoundaryGeometry(), hasBoundaryGeometry(), and setBoundaryGeometry().
csTrafoGlobal2Local_m
CoordinateSystemTrafo ElementBase::csTrafoGlobal2Local_m protected
Definition at line 436 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getBoundingBoxInLabCoords(), getCSTrafoGlobal2Local(), and setCSTrafoGlobal2Local().
deleteOnTransverseExit_m
bool ElementBase::deleteOnTransverseExit_m = true private
Definition at line 472 of file ElementBase.h.
Referenced by ElementBase(), getFlagDeleteOnTransverseExit(), and setFlagDeleteOnTransverseExit().
elemedgeSet_m
bool ElementBase::elemedgeSet_m private
Definition at line 466 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getElementPosition(), isElementPositionSet(), and setElementPosition().
elementEdge_m
double ElementBase::elementEdge_m protected
Definition at line 441 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), setActionRange(), and setCurrentSCoordinate().
elementID
std::string ElementBase::elementID private
Definition at line 450 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getName(), and setName().
elementPosition_m
double ElementBase::elementPosition_m private
ELEMEDGE attribute.
Definition at line 465 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getElementPosition(), and setElementPosition().
elementTypeToString_s
const std::map< ElementType, std::string > ElementBase::elementTypeToString_s static private
Initial value:
= {
        {ElementType::ANY, "Any"},
        {ElementType::BEAMLINE, "Beamline"},
        {ElementType::DRIFT, "Drift"},
        {ElementType::LASER, "Laser"},
        {ElementType::MARKER, "Marker"},
        {ElementType::MULTIPOLE, "Multipole"},
        {ElementType::RFCAVITY, "RFCavity"},
        {ElementType::TRAVELINGWAVE, "TravelingWave"},
        {ElementType::SBEND, "SBEND"},
        {ElementType::RBEND, "RBEND"},
        {ElementType::RBEND3D, "RBEND3D"},
        {ElementType::RING, "Ring"},
        {ElementType::SOURCE, "SOURCE"},
        {ElementType::SOLENOID, "SOLENOID"},
        {ElementType::PROBE, "Probe"},
        {ElementType::VACUUM, "Vacuum"},
        {ElementType::CONSTANTEFIELDCAVITY, "ConstantEFieldCavity"}}
Definition at line 73 of file ElementBase.h.
Referenced by getTypeString().
misalignment_m
CoordinateSystemTrafo ElementBase::misalignment_m protected
Definition at line 437 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getMisalignment(), and setMisalignment().
outputfn_m
std::string ElementBase::outputfn_m private
The name of the outputfile
Definition at line 470 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), and getOutputFN().
parmatint_m
ParticleMatterInteractionHandler* ElementBase::parmatint_m private
Definition at line 461 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getParticleMatterInteraction(), hasParticleMatterInteraction(), and setParticleMatterInteraction().
positionIsFixed
bool ElementBase::positionIsFixed private
Definition at line 463 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), fixPosition(), isPositioned(), releasePosition(), and setCSTrafoGlobal2Local().
rotationZAxis_m
double ElementBase::rotationZAxis_m protected
Definition at line 443 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getRotationAboutZ(), and setRotationAboutZ().
shareFlag
bool ElementBase::shareFlag mutable protected
Definition at line 434 of file ElementBase.h.
Referenced by Beamline::Beamline(), Beamline::Beamline(), Beamline::Beamline(), ElementBase(), ElementBase(), isSharable(), makeSharable(), and TBeamline< T >::makeSharable().
userAttribs
AttributeSet ElementBase::userAttribs private
Definition at line 455 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getChannel(), and removeAttribute().
wake_m
WakeFunction* ElementBase::wake_m private
Definition at line 457 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getWake(), hasWake(), and setWake().
The documentation for this class was generated from the following files:
ElementBase.h
ElementBase.cpp