OPALX (Object Oriented Parallel Accelerator Library for Exascal): BeamlineGeometry Class Reference
BeamlineGeometry Class Reference
Implements the composite geometry of a beam line.
#include <BeamlineGeometry.h>
Public Member Functions
BeamlineGeometry (const Beamline &line)
Constructor.
virtual ~BeamlineGeometry ()
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get element length.
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual void setElementLength (double length)
Set geometry length.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
Private Member Functions
BeamlineGeometry ()
BeamlineGeometry (const BeamlineGeometry &)
void operator= (const BeamlineGeometry &)
Private Attributes
const Beamline & itsLine
Detailed Description
Implements the composite geometry of a beam line.
Definition at line 32 of file BeamlineGeometry.h.
Constructor & Destructor Documentation
BeamlineGeometry() [1/3]
BeamlineGeometry::BeamlineGeometry (const Beamline & line) explicit
Constructor.
Definition at line 28 of file BeamlineGeometry.cpp.
~BeamlineGeometry()
BeamlineGeometry::~BeamlineGeometry () virtual
Definition at line 33 of file BeamlineGeometry.cpp.
BeamlineGeometry() [2/3]
BeamlineGeometry::BeamlineGeometry () private
BeamlineGeometry() [3/3]
BeamlineGeometry::BeamlineGeometry (const BeamlineGeometry &) private
Member Function Documentation
getArcLength()
double BeamlineGeometry::getArcLength () const virtual
Get arc length.
Implements BGeometryBase.
Definition at line 37 of file BeamlineGeometry.cpp.
References ElementBase::getArcLength(), and itsLine.
Referenced by TBeamline< T >::getArcLength().
getElementLength()
double BeamlineGeometry::getElementLength () const virtual
Get element length.
Implements BGeometryBase.
Definition at line 42 of file BeamlineGeometry.cpp.
References ElementBase::getElementLength(), and itsLine.
getEntrance()
double BeamlineGeometry::getEntrance () const virtual
Get entrance position.
Reimplemented from BGeometryBase.
Definition at line 52 of file BeamlineGeometry.cpp.
References ElementBase::getEntrance(), and itsLine.
getEntranceFrame()
Euclid3D BeamlineGeometry::getEntranceFrame () const virtual
Get transform.
Reimplemented from BGeometryBase.
Definition at line 77 of file BeamlineGeometry.cpp.
References ElementBase::getEntranceFrame(), and itsLine.
getEntrancePatch()
Euclid3D BGeometryBase::getEntrancePatch () const virtual inherited
Get patch.
Reimplemented in RBendGeometry.
Definition at line 71 of file Geometry.cpp.
References Euclid3D::identity().
Referenced by ElementBase::getEntrancePatch().
getExit()
double BeamlineGeometry::getExit () const virtual
Get exit position.
Reimplemented from BGeometryBase.
Definition at line 57 of file BeamlineGeometry.cpp.
References ElementBase::getExit(), and itsLine.
getExitFrame()
Euclid3D BeamlineGeometry::getExitFrame () const virtual
Get transform.
Reimplemented from BGeometryBase.
Definition at line 82 of file BeamlineGeometry.cpp.
References ElementBase::getExitFrame(), and itsLine.
getExitPatch()
Euclid3D BGeometryBase::getExitPatch () const virtual inherited
Get patch.
Reimplemented in RBendGeometry.
Definition at line 76 of file Geometry.cpp.
References Euclid3D::identity().
Referenced by ElementBase::getExitPatch().
getOrigin()
double BeamlineGeometry::getOrigin () const virtual
Get origin position.
Reimplemented from BGeometryBase.
Definition at line 47 of file BeamlineGeometry.cpp.
References ElementBase::getOrigin(), and itsLine.
getTotalTransform()
Euclid3D BeamlineGeometry::getTotalTransform () const virtual
Get transform.
Reimplemented from BGeometryBase.
Definition at line 67 of file BeamlineGeometry.cpp.
References ElementBase::getTotalTransform(), and itsLine.
getTransform() [1/2]
Euclid3D BeamlineGeometry::getTransform (double fromS, double toS) const virtual
Get transform.
Implements BGeometryBase.
Definition at line 62 of file BeamlineGeometry.cpp.
References ElementBase::getTransform(), and itsLine.
getTransform() [2/2]
Euclid3D BeamlineGeometry::getTransform (double s) const virtual
Get transform.
Reimplemented from BGeometryBase.
Definition at line 72 of file BeamlineGeometry.cpp.
References ElementBase::getTransform(), and itsLine.
operator=()
void BeamlineGeometry::operator= (const BeamlineGeometry &) private
setElementLength()
void BGeometryBase::setElementLength (double length) virtual inherited
Set geometry length.
Reimplemented in Euclid3DGeometry, StraightGeometry, DummyGeometry, DummyGeometryTW, and PlanarArcGeometry.
Definition at line 32 of file Geometry.cpp.
Referenced by ElementBase::setElementLength().
Member Data Documentation
itsLine
const Beamline& BeamlineGeometry::itsLine private
Definition at line 102 of file BeamlineGeometry.h.
Referenced by getArcLength(), getElementLength(), getEntrance(), getEntranceFrame(), getExit(), getExitFrame(), getOrigin(), getTotalTransform(), getTransform(), and getTransform().
The documentation for this class was generated from the following files:
BeamlineGeometry.h
BeamlineGeometry.cpp