OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions::SValue< T > Class Template Reference
Expressions::SValue< T > Class Template Reference
Object attribute with a constant scalar value.
#include <SValue.h>
Public Member Functions
SValue ()
Default constructor.
SValue (const T &val)
Constructor.
SValue (const SValue< T > &)
virtual ~SValue ()
virtual SValue< T > * clone () const
Make clone.
virtual T evaluate ()
Evaluate.
virtual void print (std::ostream &) const
Print the attribute value.
void print (std::ostream &os) const
Print value.
void print (std::ostream &os) const
Print value.
void print (std::ostream &os) const
Print value.
std::string getImage () const
Convert to string.
virtual bool isExpression () const
Test for expression.
virtual void invalidate ()
Force re-evaluation.
Protected Attributes
T value
The value of the attribute.
Private Member Functions
void operator= (const SValue< T > &)
Detailed Description
template<class T>
class Expressions::SValue< T >
Object attribute with a constant scalar value.
Definition at line 34 of file SValue.h.
Constructor & Destructor Documentation
SValue() [1/3]
template<class T> Expressions::SValue< T >::SValue ()
Default constructor.
Definition at line 70 of file SValue.h.
References value.
Referenced by clone(), operator=(), print(), Expressions::SDeferred< T >::SDeferred(), Expressions::SDeferred< T >::SDeferred(), and SValue().
SValue() [2/3]
template<class T> Expressions::SValue< T >::SValue (const T & val) explicit
Constructor.
Definition at line 76 of file SValue.h.
References value.
SValue() [3/3]
template<class T> Expressions::SValue< T >::SValue (const SValue< T > & rhs)
Definition at line 73 of file SValue.h.
References SValue(), and value.
~SValue()
template<class T> Expressions::SValue< T >::~SValue () virtual
Definition at line 79 of file SValue.h.
Member Function Documentation
clone()
template<class T> SValue< T > * Expressions::SValue< T >::clone () const virtual
Make clone.
Implements AttributeBase.
Reimplemented in Expressions::SAutomatic< T >, and Expressions::SDeferred< T >.
Definition at line 82 of file SValue.h.
References SValue(), and value.
evaluate()
template<class T> T Expressions::SValue< T >::evaluate () virtual
Evaluate.
Reimplemented in Expressions::SAutomatic< T >, and Expressions::SDeferred< T >.
Definition at line 87 of file SValue.h.
References value.
Referenced by Attributes::setBool(), Attributes::setPredefinedString(), Attributes::setReal(), Attributes::setString(), and Attributes::setUpperCaseString().
getImage()
std::string AttributeBase::getImage () const inherited
Convert to string.
Definition at line 29 of file AttributeBase.cpp.
References print().
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), and Expressions::SRefAttr< T >::evaluate().
invalidate()
void Invalidator::invalidate () virtual inherited
Force re-evaluation.
Reimplemented in Expressions::AAutomatic< T >, Expressions::SAutomatic< T >, Expressions::SRefAttr< T >, and Expressions::SRefExpr< T >.
Definition at line 25 of file Invalidator.cpp.
isExpression()
bool AttributeBase::isExpression () const virtual inherited
Test for expression.
Reimplemented in Expressions::ADeferred< T >, and Expressions::SDeferred< T >.
Definition at line 36 of file AttributeBase.cpp.
Referenced by OpalElement::printMultipoleStrength().
operator=()
template<class T> void Expressions::SValue< T >::operator= (const SValue< T > &) private
References SValue().
print() [1/4]
template<class T> void Expressions::SValue< T >::print (std::ostream & os) const virtual
Print the attribute value.
Implements AttributeBase.
Reimplemented in Expressions::SDeferred< T >.
Definition at line 95 of file SValue.h.
References value.
Referenced by print().
print() [2/4]
void Expressions::SValue< std::list< Token > >::print (std::ostream &) const inline virtual
Print value.
Implements AttributeBase.
Definition at line 101 of file SValue.h.
References print(), SValue(), and value.
print() [3/4]
void Expressions::SValue< bool >::print (std::ostream &) const inline virtual
Print value.
Implements AttributeBase.
Definition at line 110 of file SValue.h.
References value.
print() [4/4]
void Expressions::SValue< std::string >::print (std::ostream &) const inline virtual
Print value.
Implements AttributeBase.
Definition at line 116 of file SValue.h.
References value.
Member Data Documentation
value
template<class T> T Expressions::SValue< T >::value mutable protected
The value of the attribute.
Definition at line 59 of file SValue.h.
Referenced by clone(), Expressions::SAutomatic< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), evaluate(), print(), print(), SValue(), SValue(), and SValue().
The documentation for this class was generated from the following file:
SValue.h