OPALX (Object Oriented Parallel Accelerator Library for Exascal): ConvergenceError Class Reference
ConvergenceError Class Reference
Convergence error exception.
#include <ConvergenceError.h>
Public Member Functions
ConvergenceError (const std::string &method, const std::string &message)
The usual constructor.
ConvergenceError (const ConvergenceError &)
virtual ~ConvergenceError ()
virtual const std::string & what () const
Return the message string for the exception.
virtual const std::string & where () const
Return the name of the method or function which detected the exception.
Private Member Functions
ConvergenceError ()
Private Attributes
const std::string message
const std::string method
Detailed Description
Convergence error exception.
Definition at line 32 of file ConvergenceError.h.
Constructor & Destructor Documentation
ConvergenceError() [1/3]
ConvergenceError::ConvergenceError (const std::string & method, const std::string & message)
The usual constructor.
Definition at line 26 of file ConvergenceError.cpp.
References ArithmeticError::ArithmeticError().
Referenced by ConvergenceError().
ConvergenceError() [2/3]
ConvergenceError::ConvergenceError (const ConvergenceError & rhs)
Definition at line 29 of file ConvergenceError.cpp.
References ArithmeticError::ArithmeticError(), and ConvergenceError().
~ConvergenceError()
ConvergenceError::~ConvergenceError () virtual
Definition at line 31 of file ConvergenceError.cpp.
ConvergenceError() [3/3]
ConvergenceError::ConvergenceError () private
Member Function Documentation
what()
const std::string & OpalException::what () const virtual inherited
Return the message string for the exception.
Definition at line 31 of file OpalException.cpp.
References message.
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), main(), OpalParser::readStatement(), OpalParser::run(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and TEST_F().
where()
const std::string & OpalException::where () const virtual inherited
Return the name of the method or function which detected the exception.
Definition at line 33 of file OpalException.cpp.
References method.
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), main(), OpalParser::run(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and TEST_F().
Member Data Documentation
message
const std::string OpalException::message private inherited
Definition at line 56 of file OpalException.h.
Referenced by OpalException(), OpalException(), and what().
method
const std::string OpalException::method private inherited
Definition at line 57 of file OpalException.h.
Referenced by DivideError::DivideError(), OpalException(), OpalException(), and where().
The documentation for this class was generated from the following files:
ConvergenceError.h
ConvergenceError.cpp