OPALX (Object Oriented Parallel Accelerator Library for Exascal): FormatError Class Reference
FormatError Class Reference
Format error exception.
#include <FormatError.h>
Public Member Functions
FormatError (const std::string &meth, const std::string &msg)
The usual constructor.
FormatError (const FormatError &)
virtual ~FormatError ()
virtual const std::string & what () const
Return the message string for the exception.
virtual const std::string & where () const
Return the name of the method or function which detected the exception.
Private Member Functions
FormatError ()
Private Attributes
const std::string message
const std::string method
Detailed Description
Format error exception.
Definition at line 32 of file FormatError.h.
Constructor & Destructor Documentation
FormatError() [1/3]
FormatError::FormatError (const std::string & meth, const std::string & msg)
The usual constructor.
Definition at line 27 of file FormatError.cpp.
References OpalException::OpalException().
Referenced by FormatError().
FormatError() [2/3]
FormatError::FormatError (const FormatError & rhs)
Definition at line 30 of file FormatError.cpp.
References FormatError(), and OpalException::OpalException().
~FormatError()
FormatError::~FormatError () virtual
Definition at line 32 of file FormatError.cpp.
FormatError() [3/3]
FormatError::FormatError () private
Member Function Documentation
what()
const std::string & OpalException::what () const virtual inherited
Return the message string for the exception.
Definition at line 31 of file OpalException.cpp.
References message.
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), main(), OpalParser::readStatement(), OpalParser::run(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and TEST_F().
where()
const std::string & OpalException::where () const virtual inherited
Return the name of the method or function which detected the exception.
Definition at line 33 of file OpalException.cpp.
References method.
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), main(), OpalParser::run(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and TEST_F().
Member Data Documentation
message
const std::string OpalException::message private inherited
Definition at line 56 of file OpalException.h.
Referenced by OpalException(), OpalException(), and what().
method
const std::string OpalException::method private inherited
Definition at line 57 of file OpalException.h.
Referenced by DivideError::DivideError(), OpalException(), OpalException(), and where().
The documentation for this class was generated from the following files:
FormatError.h
FormatError.cpp