OPALX (Object Oriented Parallel Accelerator Library for Exascal): SDDS::SDDSParser Class Reference
SDDS::SDDSParser Class Reference
#include <SDDSParser.h>
Public Member Functions
SDDSParser ()
SDDSParser (const std::string &input)
void setInput (const std::string &input)
file run ()
file getData ()
ast::columnData_t getColumnData (const std::string &columnName)
ast::datatype getColumnType (const std::string &col_name)
template<typename T>
void getValue (int t, std::string column_name, T &nval)
template<typename T>
void getInterpolatedValue (std::string ref_name, double ref_val, std::string col_name, T &nval)
template<typename T>
void getInterpolatedValue (double spos, std::string col_name, T &nval)
template<typename T>
void getParameterValue (std::string parameter_name, T &nval)
template<typename T>
T getBoostVariantValue (const ast::variant_t &val, int datatype) const
Convert value from std::variant (only numeric types) to a value of type T.
Private Member Functions
std::string readFile ()
int getColumnIndex (std::string col_name) const
Static Private Member Functions
static void fixCaseSensitivity (std::string &for_string)
static std::string fixCaseSensitivity (const std::string &for_string)
Private Attributes
std::string sddsFileName_m
std::map< std::string, int > paramNameToID_m
mapping from parameter name to offset in params_m
std::map< std::string, int > columnNameToID_m
mapping from column name to ID in columns_m
SDDS::file sddsData_m
Detailed Description
Definition at line 42 of file SDDSParser.h.
Constructor & Destructor Documentation
SDDSParser() [1/2]
SDDS::SDDSParser::SDDSParser ()
Definition at line 23 of file SDDSParser.cpp.
References sddsFileName_m.
SDDSParser() [2/2]
SDDS::SDDSParser::SDDSParser (const std::string & input)
Definition at line 25 of file SDDSParser.cpp.
References sddsFileName_m.
Member Function Documentation
fixCaseSensitivity() [1/2]
std::string SDDS::SDDSParser::fixCaseSensitivity (const std::string & for_string) inline static private
Definition at line 46 of file SDDSParser.h.
References fixCaseSensitivity().
fixCaseSensitivity() [2/2]
void SDDS::SDDSParser::fixCaseSensitivity (std::string & for_string) static private
Definition at line 137 of file SDDSParser.cpp.
Referenced by fixCaseSensitivity(), getColumnIndex(), getParameterValue(), getValue(), and run().
getBoostVariantValue()
template<typename T> T SDDS::SDDSParser::getBoostVariantValue (const ast::variant_t & val, int datatype) const inline
Convert value from std::variant (only numeric types) to a value of type T.
Definition at line 202 of file SDDSParser.h.
References SDDS::ast::DOUBLE, SDDS::ast::FLOAT, SDDS::ast::LONG, and SDDS::ast::SHORT.
Referenced by getInterpolatedValue(), and getValue().
getColumnData()
SDDS::ast::columnData_t SDDS::SDDSParser::getColumnData (const std::string & columnName)
Definition at line 119 of file SDDSParser.cpp.
References getColumnIndex(), and sddsData_m.
getColumnIndex()
int SDDS::SDDSParser::getColumnIndex (std::string col_name) const private
Definition at line 125 of file SDDSParser.cpp.
References columnNameToID_m, and fixCaseSensitivity().
Referenced by getColumnData(), getColumnType(), getInterpolatedValue(), and getValue().
getColumnType()
ast::datatype SDDS::SDDSParser::getColumnType (const std::string & col_name) inline
Definition at line 69 of file SDDSParser.h.
References getColumnIndex(), and sddsData_m.
Referenced by getInterpolatedValue(), and getValue().
getData()
file SDDS::SDDSParser::getData () inline
Definition at line 234 of file SDDSParser.h.
References sddsData_m.
getInterpolatedValue() [1/2]
template<typename T> void SDDS::SDDSParser::getInterpolatedValue (double spos, std::string col_name, T & nval) inline
Converts the string value of a parameter at a position spos to a value of type T.
Parameters
spos interpolate value at spos
col_name parameter name
nval store result of type T in nval
Definition at line 172 of file SDDSParser.h.
References getInterpolatedValue().
getInterpolatedValue() [2/2]
template<typename T> void SDDS::SDDSParser::getInterpolatedValue (std::string ref_name, double ref_val, std::string col_name, T & nval) inline
Converts the string value of a parameter to a value of type T.
Parameters
ref_name reference quantity (e.g. spos)
ref_val interpolate value of reference quantity (e.g. spos)
col_name parameter name
nval store result of type T in nval
Definition at line 110 of file SDDSParser.h.
References getBoostVariantValue(), getColumnIndex(), getColumnType(), and sddsData_m.
Referenced by getInterpolatedValue().
getParameterValue()
template<typename T> void SDDS::SDDSParser::getParameterValue (std::string parameter_name, T & nval) inline
Converts the string value of a parameter to a value of type T.
Parameters
parameter_name parameter name
nval store result of type T in nval
Definition at line 184 of file SDDSParser.h.
References fixCaseSensitivity(), paramNameToID_m, and sddsData_m.
Referenced by SDDSWriter::replaceVersionString().
getValue()
template<typename T> void SDDS::SDDSParser::getValue (int t, std::string column_name, T & nval) inline
Converts the string value of a parameter at timestep t to a value of type T.
Parameters
t timestep (beginning at 1, -1 means last)
column_name parameter name
nval store result of type T in nval
Definition at line 83 of file SDDSParser.h.
References fixCaseSensitivity(), getBoostVariantValue(), getColumnIndex(), getColumnType(), and sddsData_m.
Referenced by SDDSWriter::getLastValue().
readFile()
std::string SDDS::SDDSParser::readFile () private
Definition at line 97 of file SDDSParser.cpp.
References sddsFileName_m.
Referenced by run().
run()
SDDS::file SDDS::SDDSParser::run ()
Definition at line 29 of file SDDSParser.cpp.
References columnNameToID_m, fixCaseSensitivity(), SDDS::column::name_m, SDDS::parameter::name_m, paramNameToID_m, readFile(), and sddsData_m.
Referenced by SDDSWriter::getLastValue(), and SDDSWriter::replaceVersionString().
setInput()
void SDDS::SDDSParser::setInput (const std::string & input)
Definition at line 27 of file SDDSParser.cpp.
References sddsFileName_m.
Member Data Documentation
columnNameToID_m
std::map<std::string, int> SDDS::SDDSParser::columnNameToID_m private
mapping from column name to ID in columns_m
Definition at line 56 of file SDDSParser.h.
Referenced by getColumnIndex(), and run().
paramNameToID_m
std::map<std::string, int> SDDS::SDDSParser::paramNameToID_m private
mapping from parameter name to offset in params_m
Definition at line 54 of file SDDSParser.h.
Referenced by getParameterValue(), and run().
sddsData_m
SDDS::file SDDS::SDDSParser::sddsData_m private
Definition at line 58 of file SDDSParser.h.
Referenced by getColumnData(), getColumnType(), getData(), getInterpolatedValue(), getParameterValue(), getValue(), and run().
sddsFileName_m
std::string SDDS::SDDSParser::sddsFileName_m private
Definition at line 51 of file SDDSParser.h.
Referenced by readFile(), SDDSParser(), SDDSParser(), and setInput().
The documentation for this class was generated from the following files:
SDDSParser.h
SDDSParser.cpp