OPALX (Object Oriented Parallel Accelerator Library for Exascal): DirectChannel Class Reference
DirectChannel Class Reference
Direct access to a [b]double[/b] variable.
#include <DirectChannel.h>
Public Member Functions
DirectChannel (double &value)
Constructor.
DirectChannel (const DirectChannel &)
virtual ~DirectChannel ()
virtual DirectChannel * clone () const
Duplicate the channel.
virtual bool set (double)
Store into channel.
virtual bool get (double &) const
Fetch from channel.
double operator+= (double value)
Add and assign [b]value[/b] to channel.
double operator-= (double value)
Subtract and assign [b]value[/b] to channel.
virtual bool isSettable () const
Test if settable.
operator double () const
Read channel.
Private Member Functions
DirectChannel ()
const DirectChannel & operator= (const DirectChannel &)
Private Attributes
double & reference
Detailed Description
Direct access to a [b]double[/b] variable.
Definition at line 30 of file DirectChannel.h.
Constructor & Destructor Documentation
DirectChannel() [1/3]
DirectChannel::DirectChannel (double & value) inline explicit
Constructor.
Definition at line 64 of file DirectChannel.h.
References reference.
Referenced by clone(), DirectChannel(), and operator=().
DirectChannel() [2/3]
DirectChannel::DirectChannel (const DirectChannel & rhs) inline
Definition at line 66 of file DirectChannel.h.
References Channel::Channel(), DirectChannel(), and reference.
~DirectChannel()
DirectChannel::~DirectChannel () inline virtual
Definition at line 69 of file DirectChannel.h.
DirectChannel() [3/3]
DirectChannel::DirectChannel () private
Referenced by clone().
Member Function Documentation
clone()
DirectChannel * DirectChannel::clone () const inline virtual
Duplicate the channel.
Implements Channel.
Definition at line 71 of file DirectChannel.h.
References DirectChannel(), and DirectChannel().
get()
bool DirectChannel::get (double & value) const inline virtual
Fetch from channel.
Implements ConstChannel.
Definition at line 78 of file DirectChannel.h.
References reference.
isSettable()
bool Channel::isSettable () const virtual inherited
Test if settable.
Reimplemented from ConstChannel.
Reimplemented in IndexedChannel< T >, and IndirectChannel< T >.
Definition at line 30 of file Channel.cpp.
Referenced by ElementBase::setAttribute().
operator double()
ConstChannel::operator double () const inline inherited
Read channel.
Definition at line 43 of file ConstChannel.h.
References get().
operator+=()
double Channel::operator+= (double value) inline inherited
Add and assign [b]value[/b] to channel.
Definition at line 45 of file Channel.h.
References ConstChannel::get(), and set().
operator-=()
double Channel::operator-= (double value) inline inherited
Subtract and assign [b]value[/b] to channel.
Definition at line 54 of file Channel.h.
References ConstChannel::get(), and set().
operator=()
const DirectChannel & DirectChannel::operator= (const DirectChannel &) private
References DirectChannel().
set()
bool DirectChannel::set (double value) inline virtual
Store into channel.
Implements Channel.
Definition at line 73 of file DirectChannel.h.
References reference.
Member Data Documentation
reference
double& DirectChannel::reference private
Definition at line 61 of file DirectChannel.h.
Referenced by DirectChannel(), DirectChannel(), get(), and set().
The documentation for this class was generated from the following file:
DirectChannel.h