OPALX (Object Oriented Parallel Accelerator Library for Exascal): BoundaryGeometry Class Reference
BoundaryGeometry Class Reference
#include <BoundaryGeometry.h>
Public Types
enum DebugFlags {
debug_isInside = 0x0001 , debug_fastIsInside = 0x0002 , debug_intersectRayBoundary = 0x0004 , debug_intersectLineSegmentBoundary = 0x0008 ,
debug_intersectTinyLineSegmentBoundary = 0x0010 , debug_PartInside = 0x0020
}
Public Member Functions
BoundaryGeometry ()
virtual ~BoundaryGeometry ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual BoundaryGeometry * clone (const std::string &name)
Return a clone.
virtual void execute ()
Execute the command.
virtual void update ()
Update this object.
void updateElement (ElementBase *element)
void initialize ()
int partInside (const Vector_t< double, 3 > &r, const Vector_t< double, 3 > &v, const double dt, Vector_t< double, 3 > &intecoords, int &triId)
Inform & printInfo (Inform &os) const
void writeGeomToVtk (std::string fn)
std::string getFilename () const
Topology getTopology () const
double getA ()
double getB ()
double getC ()
double getS ()
double getLength ()
double getL1 ()
double getL2 ()
size_t getNumBFaces ()
Vector_t< double, 3 > gethr ()
Vector_t< int, 3 > getnr ()
Vector_t< double, 3 > getmincoords ()
Vector_t< double, 3 > getmaxcoords ()
bool getInsidePoint (Vector_t< double, 3 > &pt)
bool findInsidePoint (void)
int intersectRayBoundary (const Vector_t< double, 3 > &P, const Vector_t< double, 3 > &v, Vector_t< double, 3 > &I)
int fastIsInside (const Vector_t< double, 3 > &reference_pt, const Vector_t< double, 3 > &P)
void enableDebug (enum DebugFlags flags)
void disableDebug (enum DebugFlags flags)
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Static Public Member Functions
static BoundaryGeometry * find (const std::string &name)
Public Attributes
std::vector< Attribute > itsAttr
The object attributes.
Protected Attributes
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Private Types
enum INTERSECTION_TESTS { SEGMENT , RAY , LINE }
enum {
FGEOM , LENGTH , S , L1 ,
L2 , A , B , C ,
TOPO , ZSHIFT , XYZSCALE , XSCALE ,
YSCALE , ZSCALE , INSIDEPOINT , SIZE
}
Private Member Functions
bool isInside (const Vector_t< double, 3 > &P)
int intersectTriangleVoxel (const int triangle_id, const int i, const int j, const int k)
int intersectTinyLineSegmentBoundary (const Vector_t< double, 3 > &, const Vector_t< double, 3 > &, Vector_t< double, 3 > &, int &)
int intersectLineSegmentBoundary (const Vector_t< double, 3 > &P0, const Vector_t< double, 3 > &P1, Vector_t< double, 3 > &intersection_pt, int &triangle_id)
BoundaryGeometry (const BoundaryGeometry &)
void operator= (const BoundaryGeometry &)
BoundaryGeometry (const std::string &name, BoundaryGeometry *parent)
const Vector_t< double, 3 > & getPoint (const int triangle_id, const int vertex_id)
int intersectLineTriangle (const enum INTERSECTION_TESTS kind, const Vector_t< double, 3 > &P0, const Vector_t< double, 3 > &P1, const int triangle_id, Vector_t< double, 3 > &I)
int mapVoxelIndices2ID (const int i, const int j, const int k)
Vector_t< double, 3 > mapIndices2Voxel (const int, const int, const int)
Vector_t< double, 3 > mapPoint2Voxel (const Vector_t< double, 3 > &)
void computeMeshVoxelization (void)
Private Attributes
std::string h5FileName_m
std::vector< Vector_t< double, 3 > > Points_m
std::vector< std::array< unsigned int, 4 > > Triangles_m
std::vector< Vector_t< double, 3 > > TriNormals_m
std::vector< double > TriAreas_m
Vector_t< double, 3 > minExtent_m
Vector_t< double, 3 > maxExtent_m
struct {
Vector_t< double, 3 > minExtent
Vector_t< double, 3 > maxExtent
Vector_t< double, 3 > sizeOfVoxel
Vector_t< int, 3 > nr_m
std::unordered_map< int, std::unordered_set< int > > ids
} voxelMesh_m
int debugFlags_m
bool haveInsidePoint_m
Vector_t< double, 3 > insidePoint_m
gsl_rng * randGen_m
IpplTimings::TimerRef Tinitialize_m
IpplTimings::TimerRef TisInside_m
IpplTimings::TimerRef TfastIsInside_m
IpplTimings::TimerRef TRayTrace_m
IpplTimings::TimerRef TPartInside_m
Object * itsParent
std::string itsName
std::string itsHelp
int occurrence
double timeStamp
std::set< Invalidator * > references
bool sharedFlag
Detailed Description
Definition at line 54 of file BoundaryGeometry.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
FGEOM
LENGTH
S
L1
L2
A
B
C
TOPO
ZSHIFT
XYZSCALE
XSCALE
YSCALE
ZSCALE
INSIDEPOINT
SIZE
Definition at line 237 of file BoundaryGeometry.h.
DebugFlags
enum BoundaryGeometry::DebugFlags
Enumerator
debug_isInside
debug_fastIsInside
debug_intersectRayBoundary
debug_intersectLineSegmentBoundary
debug_intersectTinyLineSegmentBoundary
debug_PartInside
Definition at line 150 of file BoundaryGeometry.h.
INTERSECTION_TESTS
enum BoundaryGeometry::INTERSECTION_TESTS private
Enumerator
SEGMENT
RAY
LINE
Definition at line 226 of file BoundaryGeometry.h.
Constructor & Destructor Documentation
BoundaryGeometry() [1/3]
BoundaryGeometry::BoundaryGeometry ()
Definition at line 872 of file BoundaryGeometry.cpp.
References A, B, BoundaryGeometry(), Object::builtin, C, clone(), OpalData::define(), Definition::Definition(), FGEOM, OpalData::getInstance(), Attributes::getString(), gsl_rng_alloc(), gsl_rng_default, gsl_rng_env_setup(), h5FileName_m, initialize(), INSIDEPOINT, Object::itsAttr, L1, L2, LENGTH, Attributes::makePredefinedString(), Attributes::makeReal(), Attributes::makeRealArray(), Attributes::makeString(), randGen_m, Object::registerOwnership(), S, SIZE, AttributeHandler::STATEMENT, TfastIsInside_m, Tinitialize_m, TisInside_m, TOPO, TPartInside_m, TRayTrace_m, update(), XSCALE, XYZSCALE, YSCALE, ZSCALE, and ZSHIFT.
Referenced by BoundaryGeometry(), BoundaryGeometry(), BoundaryGeometry(), clone(), find(), initialize(), and operator=().
~BoundaryGeometry()
BoundaryGeometry::~BoundaryGeometry () virtual
Definition at line 957 of file BoundaryGeometry.cpp.
References gsl_rng_free(), and randGen_m.
BoundaryGeometry() [2/3]
BoundaryGeometry::BoundaryGeometry (const BoundaryGeometry &) private
References BoundaryGeometry().
BoundaryGeometry() [3/3]
BoundaryGeometry::BoundaryGeometry (const std::string & name, BoundaryGeometry * parent) private
Definition at line 942 of file BoundaryGeometry.cpp.
References BoundaryGeometry(), Definition::Definition(), FGEOM, Attributes::getString(), gsl_rng_alloc(), gsl_rng_default, gsl_rng_env_setup(), h5FileName_m, initialize(), Object::itsAttr, randGen_m, TfastIsInside_m, Tinitialize_m, TisInside_m, TPartInside_m, and TRayTrace_m.
Member Function Documentation
canReplaceBy()
bool BoundaryGeometry::canReplaceBy (Object * object) virtual
Test if replacement is allowed.
Reimplemented from Object.
Definition at line 959 of file BoundaryGeometry.cpp.
References Object::Object().
clear()
void Object::clear () inherited
Clear the occurrence counter.
Definition at line 285 of file Object.cpp.
References occurrence.
clone()
BoundaryGeometry * BoundaryGeometry::clone (const std::string & name) virtual
Return a clone.
Implements Object.
Definition at line 964 of file BoundaryGeometry.cpp.
References BoundaryGeometry().
Referenced by BoundaryGeometry(), and TrackRun::setupBoundaryGeometry().
computeMeshVoxelization()
void BoundaryGeometry::computeMeshVoxelization (void) inline private
Definition at line 1411 of file BoundaryGeometry.cpp.
References Util::combineFilePath(), Options::enableVTK, OpalData::getAuxiliaryOutputDirectory(), OpalData::getInstance(), getPoint(), gmsg, h5FileName_m, INSIDE, intersectTriangleVoxel(), mapPoint2VoxelIndices, mapVoxelIndices2ID(), Triangles_m, and voxelMesh_m.
Referenced by initialize().
copyAttributes()
void Object::copyAttributes (const Object & source) inherited
Copy attributes from another object.
Definition at line 50 of file Object.cpp.
References itsAttr, and Object().
Referenced by LineTemplate::makeInstance(), and SequenceTemplate::makeInstance().
disableDebug()
void BoundaryGeometry::disableDebug (enum DebugFlags flags) inline
Definition at line 161 of file BoundaryGeometry.h.
References debugFlags_m.
enableDebug()
void BoundaryGeometry::enableDebug (enum DebugFlags flags) inline
Definition at line 159 of file BoundaryGeometry.h.
References debugFlags_m.
execute()
void BoundaryGeometry::execute () virtual
Execute the command.
Reimplemented from Object.
Definition at line 972 of file BoundaryGeometry.cpp.
References TfastIsInside_m, Tinitialize_m, TisInside_m, TPartInside_m, TRayTrace_m, and update().
fastIsInside()
int BoundaryGeometry::fastIsInside (const Vector_t< double, 3 > & reference_pt, const Vector_t< double, 3 > & P)
Definition at line 1280 of file BoundaryGeometry.cpp.
References debug_fastIsInside, debug_intersectTinyLineSegmentBoundary, debugFlags_m, gmsg, intersectTinyLineSegmentBoundary(), maxExtent_m, minExtent_m, TfastIsInside_m, and voxelMesh_m.
Referenced by findInsidePoint(), and isInside().
find()
BoundaryGeometry * BoundaryGeometry::find (const std::string & name) static
Definition at line 981 of file BoundaryGeometry.cpp.
References BoundaryGeometry(), OpalData::find(), and OpalData::getInstance().
Referenced by TrackRun::setupBoundaryGeometry().
findAttribute() [1/2]
Attribute * Object::findAttribute (const std::string & name) virtual inherited
Find an attribute by name.
Definition at line 56 of file Object.cpp.
References itsAttr.
Referenced by OpalElement::getParticleMatterInteraction(), OpalElement::getTypeName(), OpalElement::getWakeF(), Line::parse(), parse(), OpalElement::parse(), OpalParser::parseAssign(), SequenceParser::parsePosition(), TrackRun::print(), and TEST().
findAttribute() [2/2]
const Attribute * Object::findAttribute (const std::string & name) const virtual inherited
Find an attribute by name.
Definition at line 63 of file Object.cpp.
References itsAttr.
findInsidePoint()
bool BoundaryGeometry::findInsidePoint (void)
Definition at line 1223 of file BoundaryGeometry.cpp.
References B, fastIsInside(), gmsg, insidePoint_m, maxExtent_m, and minExtent_m.
Referenced by initialize().
getA()
double BoundaryGeometry::getA () inline
Definition at line 95 of file BoundaryGeometry.h.
References A, Attributes::getReal(), and Object::itsAttr.
getB()
double BoundaryGeometry::getB () inline
Definition at line 97 of file BoundaryGeometry.h.
References B, Attributes::getReal(), and Object::itsAttr.
getBaseObject()
const Object * Object::getBaseObject () const inherited
Return the object's base type object.
Definition at line 260 of file Object.cpp.
References itsParent, and Object().
getC()
double BoundaryGeometry::getC () inline
Definition at line 99 of file BoundaryGeometry.h.
References C, Attributes::getReal(), and Object::itsAttr.
getCategory()
const std::string Definition::getCategory () const virtual inherited
Return the object category as a string.
Implements Object.
Definition at line 26 of file Definition.cpp.
getFilename()
std::string BoundaryGeometry::getFilename () const inline
Definition at line 84 of file BoundaryGeometry.h.
References FGEOM, Attributes::getString(), and Object::itsAttr.
gethr()
Vector_t< double, 3 > BoundaryGeometry::gethr () inline
Return the hr_m.
Definition at line 117 of file BoundaryGeometry.h.
References voxelMesh_m.
getInsidePoint()
bool BoundaryGeometry::getInsidePoint (Vector_t< double, 3 > & pt) inline
Definition at line 132 of file BoundaryGeometry.h.
References haveInsidePoint_m, and insidePoint_m.
getL1()
double BoundaryGeometry::getL1 () inline
Definition at line 105 of file BoundaryGeometry.h.
References Attributes::getReal(), Object::itsAttr, and L1.
getL2()
double BoundaryGeometry::getL2 () inline
Definition at line 107 of file BoundaryGeometry.h.
References Attributes::getReal(), Object::itsAttr, and L2.
getLength()
double BoundaryGeometry::getLength () inline
Definition at line 103 of file BoundaryGeometry.h.
References Attributes::getReal(), Object::itsAttr, and LENGTH.
getmaxcoords()
Vector_t< double, 3 > BoundaryGeometry::getmaxcoords () inline
Return the maxcoords_m.
Definition at line 130 of file BoundaryGeometry.h.
References maxExtent_m.
getmincoords()
Vector_t< double, 3 > BoundaryGeometry::getmincoords () inline
Return the mincoords_m.
Definition at line 126 of file BoundaryGeometry.h.
References minExtent_m.
getnr()
Vector_t< int, 3 > BoundaryGeometry::getnr () inline
Return the nr_m.
Definition at line 121 of file BoundaryGeometry.h.
References voxelMesh_m.
getNumBFaces()
size_t BoundaryGeometry::getNumBFaces () inline
Return number of boundary faces.
Definition at line 112 of file BoundaryGeometry.h.
References Triangles_m.
getOpalName()
const std::string & Object::getOpalName () const inherited
Return object name.
Definition at line 267 of file Object.cpp.
References itsName.
Referenced by Macro::clone(), OpalVariableRFCavity::clone(), OpalData::create(), OpalData::define(), Sequence::findDriftLength(), ValueDefinition::getBool(), ValueDefinition::getBoolComponent(), ValueDefinition::getReal(), ValueDefinition::getRealComponent(), ValueDefinition::getString(), ValueDefinition::getStringComponent(), LineTemplate::makeInstance(), makeInstance(), SequenceTemplate::makeInstance(), parse(), SequenceParser::parsePosition(), Beam::print(), BoolConstant::print(), Line::print(), print(), OpalElement::print(), OpalFilter::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), Sequence::print(), StringConstant::print(), TrackRun::print(), BinningCmd::printInfo(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), registerOwnership(), OpalElement::registerOwnership(), Line::replace(), Sequence::replace(), PartBunch< T, Dim >::setBins(), TEST(), TEST(), TEST(), TEST_F(), Beam::update(), BoundaryGeometry::update(), OpalFilter::update(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), and OpalSplineTimeDependence::update().
getParent()
Object * Object::getParent () const inherited
Return parent pointer.
Definition at line 269 of file Object.cpp.
References itsParent, and Object().
Referenced by OpalData::erase(), print(), OpalElement::print(), registerOwnership(), and OpalElement::registerOwnership().
getPoint()
const Vector_t< double, 3 > & BoundaryGeometry::getPoint (const int triangle_id, const int vertex_id) inline private
Definition at line 221 of file BoundaryGeometry.h.
References Points_m, and Triangles_m.
Referenced by computeMeshVoxelization(), initialize(), intersectLineTriangle(), intersectTinyLineSegmentBoundary(), and intersectTriangleVoxel().
getS()
double BoundaryGeometry::getS () inline
Definition at line 101 of file BoundaryGeometry.h.
References Attributes::getReal(), Object::itsAttr, and S.
getTopology()
Topology BoundaryGeometry::getTopology () const inline
Definition at line 86 of file BoundaryGeometry.h.
References BOXCORNER, ELLIPTIC, Attributes::getString(), Object::itsAttr, RECTANGULAR, and TOPO.
Referenced by printInfo().
increment()
int Object::increment () inherited
Increment and return the occurrence counter.
Definition at line 287 of file Object.cpp.
References occurrence.
Referenced by Line::parse(), and Sequence::storeLine().
initialize()
void BoundaryGeometry::initialize ()
Definition at line 1464 of file BoundaryGeometry.cpp.
References A, B, BoundaryGeometry(), C, computeMeshVoxelization(), debugFlags_m, dot(), findInsidePoint(), getPoint(), Attributes::getReal(), Attributes::getRealArray(), gmsg, gsl_rng_uniform(), h5FileName_m, haveInsidePoint_m, INSIDEPOINT, insidePoint_m, intersectLineTriangle(), isInside(), Object::itsAttr, maxExtent_m, minExtent_m, PointID, Points_m, randGen_m, SEGMENT, SQR, Tinitialize_m, TisInside_m, Triangles_m, TriAreas_m, TriNormals_m, voxelMesh_m, XSCALE, XYZSCALE, YSCALE, ZSCALE, and ZSHIFT.
Referenced by BoundaryGeometry(), and BoundaryGeometry().
intersectLineSegmentBoundary()
int BoundaryGeometry::intersectLineSegmentBoundary (const Vector_t< double, 3 > & P0, const Vector_t< double, 3 > & P1, Vector_t< double, 3 > & intersection_pt, int & triangle_id) private
Definition at line 2089 of file BoundaryGeometry.cpp.
References debug_intersectLineSegmentBoundary, debug_intersectTinyLineSegmentBoundary, debugFlags_m, gmsg, intersectTinyLineSegmentBoundary(), and mapPoint2VoxelIndices.
Referenced by intersectRayBoundary().
intersectLineTriangle()
int BoundaryGeometry::intersectLineTriangle (const enum INTERSECTION_TESTS kind, const Vector_t< double, 3 > & P0, const Vector_t< double, 3 > & P1, const int triangle_id, Vector_t< double, 3 > & I) private
Definition at line 1044 of file BoundaryGeometry.cpp.
References cross(), dot(), cmp_ulp::eq_zero(), cmp_ulp::ge_zero(), getPoint(), cmp_ulp::gt(), cmp_ulp::le(), LINE, cmp_ulp::lt(), cmp_ulp::lt_zero(), RAY, and SEGMENT.
Referenced by initialize(), and intersectTinyLineSegmentBoundary().
intersectRayBoundary()
int BoundaryGeometry::intersectRayBoundary (const Vector_t< double, 3 > & P, const Vector_t< double, 3 > & v, Vector_t< double, 3 > & I)
Definition at line 1331 of file BoundaryGeometry.cpp.
References debug_intersectLineSegmentBoundary, debug_intersectRayBoundary, debugFlags_m, gmsg, intersectLineSegmentBoundary(), TRayTrace_m, and voxelMesh_m.
intersectTinyLineSegmentBoundary()
int BoundaryGeometry::intersectTinyLineSegmentBoundary (const Vector_t< double, 3 > & P, const Vector_t< double, 3 > & Q, Vector_t< double, 3 > & intersect_pt, int & triangle_id) private
Definition at line 1958 of file BoundaryGeometry.cpp.
References debug_intersectTinyLineSegmentBoundary, debugFlags_m, cmp_ulp::eq_zero(), getPoint(), gmsg, Voxel::intersect(), intersectLineTriangle(), LINE, mapIndices2Voxel(), mapPoint2VoxelIndices, mapVoxelIndices2ID(), Voxel::pts, and voxelMesh_m.
Referenced by fastIsInside(), intersectLineSegmentBoundary(), and partInside().
intersectTriangleVoxel()
int BoundaryGeometry::intersectTriangleVoxel (const int triangle_id, const int i, const int j, const int k) private
Definition at line 991 of file BoundaryGeometry.cpp.
References getPoint(), Voxel::intersect(), and voxelMesh_m.
Referenced by computeMeshVoxelization().
isBuiltin()
bool Object::isBuiltin () const inherited
True, if [b]this[/b] is a built-in object.
Definition at line 243 of file Object.cpp.
References builtin.
Referenced by OpalData::define(), and OpalData::getVariableNames().
isDirty()
bool Object::isDirty () const inherited
True, if the [b]modified[/b] flag is set.
Definition at line 254 of file Object.cpp.
References modified.
isFlagged()
bool Object::isFlagged () const inherited
True, if [b]this[/b] is flagged by setFlag(true).
Definition at line 258 of file Object.cpp.
References flagged.
isInside()
bool BoundaryGeometry::isInside (const Vector_t< double, 3 > & P) private
Definition at line 1119 of file BoundaryGeometry.cpp.
References fastIsInside(), cmp_ulp::lt(), maxExtent_m, and minExtent_m.
Referenced by initialize().
isShared()
bool Object::isShared () const virtual inherited
Shared flag.
Definition at line 245 of file Object.cpp.
References sharedFlag.
Referenced by Sequence::print().
isTreeMember()
bool Object::isTreeMember (const Object * subTree) const inherited
Test for tree membership.
Definition at line 271 of file Object.cpp.
References Object().
Referenced by Selector::handleElement(), and OpalParser::parseAssign().
makeInstance()
Object * Object::makeInstance (const std::string & name, Statement & , const Parser *) virtual inherited
Macro handler function.
Reimplemented in LineTemplate, MacroCmd, and SequenceTemplate.
Definition at line 76 of file Object.cpp.
References getOpalName(), and Object().
Referenced by OpalParser::parseDefine(), and OpalParser::parseMacro().
makeTemplate()
Object * Object::makeTemplate (const std::string & name, TokenStream & , Statement &) virtual inherited
Macro handler function.
Reimplemented in Line, LineTemplate, MacroCmd, Sequence, and SequenceTemplate.
Definition at line 71 of file Object.cpp.
References Object().
Referenced by OpalParser::parseMacro().
mapIndices2Voxel()
Vector_t< double, 3 > BoundaryGeometry::mapIndices2Voxel (const int i, const int j, const int k) inline private
Definition at line 1395 of file BoundaryGeometry.cpp.
References voxelMesh_m.
Referenced by intersectTinyLineSegmentBoundary(), and mapPoint2Voxel().
mapPoint2Voxel()
Vector_t< double, 3 > BoundaryGeometry::mapPoint2Voxel (const Vector_t< double, 3 > & pt) inline private
Definition at line 1403 of file BoundaryGeometry.cpp.
References mapIndices2Voxel(), and voxelMesh_m.
mapVoxelIndices2ID()
int BoundaryGeometry::mapVoxelIndices2ID (const int i, const int j, const int k) inline private
Definition at line 1374 of file BoundaryGeometry.cpp.
References voxelMesh_m.
Referenced by computeMeshVoxelization(), and intersectTinyLineSegmentBoundary().
occurrenceCount()
int Object::occurrenceCount () inherited
Return the occurrence counter.
Definition at line 289 of file Object.cpp.
References occurrence.
operator=()
void BoundaryGeometry::operator= (const BoundaryGeometry &) private
References BoundaryGeometry().
parse()
void Object::parse (Statement & stat) virtual inherited
Parse the object.
Reimplemented in Call, Echo, EmissionSourceList, Help, Line, OpalElement, PSystem, Sequence, System, Title, and Value.
Definition at line 82 of file Object.cpp.
References Statement::delimiter(), findAttribute(), getOpalName(), Expressions::parseDelimiter(), Expressions::parseRealConst(), and Expressions::parseString().
Referenced by Sequence::parse(), OpalParser::parseAction(), OpalParser::parseDefine(), and SequenceTemplate::parseTemplate().
parseShortcut()
void Object::parseShortcut (Statement & stat, bool eval = true) virtual inherited
Parser for single-attribute commands.
Definition at line 113 of file Object.cpp.
Referenced by Call::parse(), Echo::parse(), Help::parse(), PSystem::parse(), System::parse(), Title::parse(), and Value::parse().
partInside()
int BoundaryGeometry::partInside (const Vector_t< double, 3 > & r, const Vector_t< double, 3 > & v, const double dt, Vector_t< double, 3 > & intersect_pt, int & triangle_id)
Determine whether a particle with position
Parameters
r,momenta
param v , and time step
Parameters
dt will hit the boundary.
return value: -1 no collison with boundary 0 particle will collide with boundary in next time step
Definition at line 2149 of file BoundaryGeometry.cpp.
References Physics::c, debug_intersectTinyLineSegmentBoundary, debug_PartInside, debugFlags_m, dot(), gmsg, intersectTinyLineSegmentBoundary(), and TPartInside_m.
print()
void Object::print (std::ostream & msg) const virtual inherited
Print the object.
Reimplemented in Beam, BoolConstant, DumpEMFields, Line, OpalBend, OpalElement, OpalFilter, OpalMarker, OpalMultipole, OpalMultipoleT, OpalPolynomialTimeDependence, OpalQuadrupole, OpalRingDefinition, OpalSinusoidalTimeDependence, OpalSplineTimeDependence, RealConstant, RealVariable, RealVector, Sequence, StringConstant, and TrackRun.
Definition at line 146 of file Object.cpp.
References getOpalName(), getParent(), itsAttr, and Object().
Referenced by printValue().
printHelp()
void Object::printHelp (std::ostream &) const virtual inherited
Print help.
Definition at line 179 of file Object.cpp.
References gmsg, itsAttr, and itsHelp.
Referenced by Help::execute(), and main().
printInfo()
Inform & BoundaryGeometry::printInfo (Inform & os) const
Definition at line 2233 of file BoundaryGeometry.cpp.
References A, B, BOXCORNER, C, FGEOM, Object::getOpalName(), Attributes::getReal(), Attributes::getString(), getTopology(), Object::itsAttr, L1, L2, LENGTH, S, TOPO, XSCALE, XYZSCALE, YSCALE, and ZSCALE.
Referenced by operator<<().
printValue()
void Object::printValue (std::ostream & os) const inline virtual inherited
Reimplemented in BoolConstant, RealConstant, RealVariable, RealVector, and StringConstant.
Definition at line 270 of file Object.h.
References print().
registerOwnership()
void Object::registerOwnership (const AttributeHandler::OwnerType & itsClass) const inherited
Definition at line 169 of file Object.cpp.
References AttributeHandler::addAttributeOwner(), getOpalName(), getParent(), and itsAttr.
Referenced by Beam::Beam(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), Call::Call(), Distribution::Distribution(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), EmissionSourceList::EmissionSourceList(), Help::Help(), Line::Line(), OpalFilter::OpalFilter(), Option::Option(), PSystem::PSystem(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVector::RealVector(), Select::Select(), Sequence::Sequence(), StringConstant::StringConstant(), System::System(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), and Value::Value().
registerReference()
void Object::registerReference (Invalidator * a) inherited
Register a reference to this object.
Definition at line 165 of file Object.cpp.
References references.
replace()
void Object::replace (Object * oldObject, Object * newObject) virtual inherited
Replace references.
Reimplemented in Line, and Sequence.
Definition at line 235 of file Object.cpp.
References Object().
setDirty()
void Object::setDirty (bool dirty) inherited
Set/reset the [b]modified[/b] flag.
Definition at line 249 of file Object.cpp.
References modified.
Referenced by OpalData::define(), OpalData::makeDirty(), and RealVariable::RealVariable().
setFlag()
void Object::setFlag (bool flag) inherited
Flag/unflag this object, e. g. to control output of objects for.
Definition at line 256 of file Object.cpp.
References flagged.
setOpalName()
void Object::setOpalName (const std::string & name) inherited
Set object name.
Definition at line 281 of file Object.cpp.
References itsName.
Referenced by TEST(), TEST(), TEST(), Beam::update(), BoundaryGeometry::update(), and OpalFilter::update().
setParent()
void Object::setParent (Object * parent) inherited
Set parent object.
Definition at line 283 of file Object.cpp.
References itsParent, and Object().
Referenced by OpalData::erase().
setShared()
void Object::setShared (bool flag) virtual inherited
Set/reset shared flag.
Reimplemented in Element.
Definition at line 247 of file Object.cpp.
References sharedFlag.
Referenced by OpalParser::parseDefine(), and Element::setShared().
shouldTrace()
bool Definition::shouldTrace () const virtual inherited
Trace flag.
Implements Object.
Definition at line 28 of file Definition.cpp.
shouldUpdate()
bool Definition::shouldUpdate () const virtual inherited
Update flag.
Implements Object.
Definition at line 30 of file Definition.cpp.
unregisterReference()
void Object::unregisterReference (Invalidator * a) inherited
Unegister a reference to this object.
Definition at line 167 of file Object.cpp.
References references.
update()
void BoundaryGeometry::update () virtual
Update this object.
Reimplemented from Object.
Definition at line 968 of file BoundaryGeometry.cpp.
References Object::getOpalName(), and Object::setOpalName().
Referenced by BoundaryGeometry(), and execute().
updateElement()
void BoundaryGeometry::updateElement (ElementBase * element)
Definition at line 989 of file BoundaryGeometry.cpp.
writeGeomToVtk()
void BoundaryGeometry::writeGeomToVtk (std::string fn)
Definition at line 2201 of file BoundaryGeometry.cpp.
References PointID, Points_m, and Triangles_m.
Referenced by DataSink::writeGeomToVtk().
Member Data Documentation
builtin
bool Object::builtin protected inherited
Built-in flag.
Definition at line 226 of file Object.h.
Referenced by Beam::Beam(), BoundaryGeometry::BoundaryGeometry(), isBuiltin(), Object(), Object(), OpalFilter::OpalFilter(), OpalMarker::OpalMarker(), RealConstant::RealConstant(), StringConstant::StringConstant(), and Table::~Table().
debugFlags_m
int BoundaryGeometry::debugFlags_m private
Definition at line 202 of file BoundaryGeometry.h.
Referenced by disableDebug(), enableDebug(), fastIsInside(), initialize(), intersectLineSegmentBoundary(), intersectRayBoundary(), intersectTinyLineSegmentBoundary(), and partInside().
flagged
bool Object::flagged protected inherited
Object flag.
Definition at line 235 of file Object.h.
Referenced by isFlagged(), Object(), Object(), and setFlag().
h5FileName_m
std::string BoundaryGeometry::h5FileName_m private
Definition at line 177 of file BoundaryGeometry.h.
Referenced by BoundaryGeometry(), BoundaryGeometry(), computeMeshVoxelization(), and initialize().
haveInsidePoint_m
bool BoundaryGeometry::haveInsidePoint_m private
Definition at line 204 of file BoundaryGeometry.h.
Referenced by getInsidePoint(), and initialize().
insidePoint_m
Vector_t<double, 3> BoundaryGeometry::insidePoint_m private
Definition at line 205 of file BoundaryGeometry.h.
Referenced by findInsidePoint(), getInsidePoint(), and initialize().
itsAttr
std::vector<Attribute> Object::itsAttr inherited
The object attributes.
Definition at line 210 of file Object.h.
Referenced by Beam::Beam(), BinningCmd::BinningCmd(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), BoundaryGeometry::BoundaryGeometry(), DumpEMFields::buildGrid(), Call::Call(), FieldSolverCmd::constructBCHandler(), copyAttributes(), Distribution::Distribution(), BinningCmd::dumpBinsToFile(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), Beam::execute(), Call::execute(), Echo::execute(), Help::execute(), Option::execute(), PSystem::execute(), Select::execute(), System::execute(), Title::execute(), TrackCmd::execute(), TrackRun::execute(), Value::execute(), FieldSolverCmd::FieldSolverCmd(), findAttribute(), findAttribute(), BoundaryGeometry::getA(), OpalElement::getApert(), BoundaryGeometry::getB(), BinningCmd::getBinningAlpha(), BinningCmd::getBinningBeta(), FieldSolverCmd::getBinsName(), BoolConstant::getBool(), FieldSolverCmd::getBoxIncr(), Beam::getBunchCharge(), BoundaryGeometry::getC(), Beam::getCharge(), Beam::getCurrent(), Beam::getDaughterBeamName(), BinningCmd::getDesiredWidth(), EmissionSource::getDistributionName(), FieldSolverCmd::getDomDec(), TrackCmd::getDT(), TrackCmd::getDTAU(), TrackCmd::getDTSCINIT(), BinningCmd::getDumpBinsFileName(), BinningCmd::getDumpBinsFrequency(), EmissionSource::getEmissionModel(), Beam::getEmissionSourceListName(), BoundaryGeometry::getFilename(), Distribution::getFilename(), Beam::getFrequency(), Beam::getGlobalProcessNames(), BoundaryGeometry::getL1(), BoundaryGeometry::getL2(), BoundaryGeometry::getLength(), Line::getLength(), OpalElement::getLength(), Sequence::getLength(), Beam::getMass(), BinningCmd::getMaxBins(), TrackCmd::getMaxSteps(), Beam::getNumAlloc(), FieldSolverCmd::getNX(), FieldSolverCmd::getNY(), FieldSolverCmd::getNZ(), EmissionSource::getP0(), BinningCmd::getParameter(), Beam::getParticleName(), EmissionSource::getR0(), RealConstant::getReal(), RealVariable::getReal(), RealVector::getRealComponent(), Sequence::getReference(), BoundaryGeometry::getS(), EmissionSource::getShiftedGreensFunction(), TrackCmd::getStepsPerTurn(), StringConstant::getString(), EmissionSource::getT0(), TrackCmd::getT0(), BinningCmd::getTablePrintFrequency(), TrackCmd::getTimeIntegrator(), BoundaryGeometry::getTopology(), FieldSolverCmd::getType(), EmissionSource::getZerofaceMaxSteps(), EmissionSource::getZeroFacePlaneDumpFrequency(), EmissionSource::getZeroFaceR0Z(), TrackCmd::getZStart(), TrackCmd::getZStop(), Beam::hasExplicitEnergy(), Help::Help(), BoundaryGeometry::initialize(), OpalFilter::initOpalFilter(), Beam::isPhoton(), Line::Line(), Object(), Object(), OpalBend::OpalBend(), OpalCavity::OpalCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalDrift::OpalDrift(), OpalElement::OpalElement(), OpalFilter::OpalFilter(), OpalLaser::OpalLaser(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalPolynomialTimeDependence::OpalPolynomialTimeDependence(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalRingDefinition::OpalRingDefinition(), OpalSinusoidalTimeDependence::OpalSinusoidalTimeDependence(), OpalSolenoid::OpalSolenoid(), OpalSplineTimeDependence::OpalSplineTimeDependence(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), Option::Option(), Option::Option(), Line::parse(), Sequence::parse(), DumpEMFields::parseCoordinateSystem(), Beam::print(), BoolConstant::print(), DumpEMFields::print(), print(), OpalFilter::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), Sequence::print(), StringConstant::print(), printHelp(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), BoolConstant::printValue(), RealConstant::printValue(), RealVariable::printValue(), RealVector::printValue(), StringConstant::printValue(), PSystem::PSystem(), RealConstant::RealConstant(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVariable::RealVariable(), RealVector::RealVector(), registerOwnership(), OpalElement::registerOwnership(), Select::Select(), Select::select(), Sequence::Sequence(), Distribution::setAttributes(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCX(), OrbitThreaderTest::TestableFieldSolverCmd::setBCX(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCX(), TestMultipoleT::TestableFieldSolverCmd::setBCX(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCX(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCX(), TestVariableRFCavity::TestableFieldSolverCmd::setBCX(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCY(), OrbitThreaderTest::TestableFieldSolverCmd::setBCY(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCY(), TestMultipoleT::TestableFieldSolverCmd::setBCY(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCY(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCY(), TestVariableRFCavity::TestableFieldSolverCmd::setBCY(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCZ(), OrbitThreaderTest::TestableFieldSolverCmd::setBCZ(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCZ(), TestMultipoleT::TestableFieldSolverCmd::setBCZ(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCZ(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCZ(), TestVariableRFCavity::TestableFieldSolverCmd::setBCZ(), TestableBinningCmd::setBinningAlpha(), TestableBinningCmd::setBinningBeta(), TestableBinningCmd::setDesiredWidth(), Distribution::setDistParametersFlatTop(), Distribution::setDistParametersMultiVariateGauss(), Distribution::setDistType(), TestableBinningCmd::setDumpBinsFile(), TestableBinningCmd::setDumpBinsFreq(), TestableBinningCmd::setMaxBins(), FieldSolverCmd::setNX(), FieldSolverCmd::setNY(), FieldSolverCmd::setNZ(), TestableBinningCmd::setParameterString(), TrackRun::setRunMethod(), Distribution::setSigmaP_m(), Distribution::setSigmaR_m(), TestableBinningCmd::setTablePrintFrequency(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setType(), OrbitThreaderTest::TestableFieldSolverCmd::setType(), SolenoidPlacementTest::TestableFieldSolverCmd::setType(), TestMultipoleT::TestableFieldSolverCmd::setType(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setType(), TestMultipoleTStraight::TestableFieldSolverCmd::setType(), TestVariableRFCavity::TestableFieldSolverCmd::setType(), TrackRun::setupBoundaryGeometry(), StringConstant::StringConstant(), StringConstant::StringConstant(), System::System(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), Beam::update(), BinningCmd::update(), FieldSolverCmd::update(), OpalCavity::update(), OpalConstantEFieldCavity::update(), OpalDrift::update(), OpalElement::update(), OpalLaser::update(), OpalMonitor::update(), OpalMultipole::update(), OpalMultipoleT::update(), OpalPolynomialTimeDependence::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalRBend::update(), OpalRingDefinition::update(), OpalSBend::update(), OpalSinusoidalTimeDependence::update(), OpalSolenoid::update(), OpalSplineTimeDependence::update(), OpalTravelingWave::update(), OpalVacuum::update(), OpalVariableRFCavity::update(), OpalVerticalFFAMagnet::update(), Option::update(), OpalElement::updateUnknown(), Value::Value(), ValueDefinition::value(), and ValueDefinition::value().
itsHelp
std::string Object::itsHelp private inherited
Definition at line 250 of file Object.h.
Referenced by Object(), Object(), and printHelp().
itsName
std::string Object::itsName private inherited
Definition at line 247 of file Object.h.
Referenced by getOpalName(), Object(), Object(), and setOpalName().
itsParent
Object* Object::itsParent private inherited
Definition at line 244 of file Object.h.
Referenced by getBaseObject(), getParent(), Object(), Object(), and setParent().
maxExtent_m
Vector_t<double, 3> BoundaryGeometry::maxExtent_m private
Definition at line 188 of file BoundaryGeometry.h.
Referenced by fastIsInside(), findInsidePoint(), getmaxcoords(), initialize(), and isInside().
minExtent_m
Vector_t<double, 3> BoundaryGeometry::minExtent_m private
Definition at line 187 of file BoundaryGeometry.h.
Referenced by fastIsInside(), findInsidePoint(), getmincoords(), initialize(), and isInside().
modified
bool Object::modified protected inherited
Dirty flag.
Definition at line 231 of file Object.h.
Referenced by isDirty(), Object(), Object(), and setDirty().
occurrence
int Object::occurrence private inherited
Definition at line 253 of file Object.h.
Referenced by clear(), increment(), Object(), Object(), and occurrenceCount().
Points_m
std::vector<Vector_t<double, 3> > BoundaryGeometry::Points_m private
Definition at line 179 of file BoundaryGeometry.h.
Referenced by getPoint(), initialize(), and writeGeomToVtk().
randGen_m
gsl_rng* BoundaryGeometry::randGen_m private
Definition at line 207 of file BoundaryGeometry.h.
Referenced by BoundaryGeometry(), BoundaryGeometry(), initialize(), and ~BoundaryGeometry().
references
std::set<Invalidator*> Object::references private inherited
Definition at line 260 of file Object.h.
Referenced by registerReference(), unregisterReference(), and ~Object().
sharedFlag
bool Object::sharedFlag private inherited
Definition at line 263 of file Object.h.
Referenced by isShared(), Object(), Object(), and setShared().
TfastIsInside_m
IpplTimings::TimerRef BoundaryGeometry::TfastIsInside_m private
Definition at line 211 of file BoundaryGeometry.h.
Referenced by BoundaryGeometry(), BoundaryGeometry(), execute(), and fastIsInside().
timeStamp
double Object::timeStamp private inherited
Definition at line 256 of file Object.h.
Tinitialize_m
IpplTimings::TimerRef BoundaryGeometry::Tinitialize_m private
Definition at line 209 of file BoundaryGeometry.h.
Referenced by BoundaryGeometry(), BoundaryGeometry(), execute(), and initialize().
TisInside_m
IpplTimings::TimerRef BoundaryGeometry::TisInside_m private
Definition at line 210 of file BoundaryGeometry.h.
Referenced by BoundaryGeometry(), BoundaryGeometry(), execute(), and initialize().
TPartInside_m
IpplTimings::TimerRef BoundaryGeometry::TPartInside_m private
Definition at line 213 of file BoundaryGeometry.h.
Referenced by BoundaryGeometry(), BoundaryGeometry(), execute(), and partInside().
TRayTrace_m
IpplTimings::TimerRef BoundaryGeometry::TRayTrace_m private
Definition at line 212 of file BoundaryGeometry.h.
Referenced by BoundaryGeometry(), BoundaryGeometry(), execute(), and intersectRayBoundary().
Triangles_m
std::vector<std::array<unsigned int, 4> > BoundaryGeometry::Triangles_m private
Definition at line 181 of file BoundaryGeometry.h.
Referenced by computeMeshVoxelization(), getNumBFaces(), getPoint(), initialize(), and writeGeomToVtk().
TriAreas_m
std::vector<double> BoundaryGeometry::TriAreas_m private
Definition at line 185 of file BoundaryGeometry.h.
Referenced by initialize().
TriNormals_m
std::vector<Vector_t<double, 3> > BoundaryGeometry::TriNormals_m private
Definition at line 184 of file BoundaryGeometry.h.
Referenced by initialize().
[struct]
struct { ... } BoundaryGeometry::voxelMesh_m
Referenced by computeMeshVoxelization(), fastIsInside(), gethr(), getnr(), initialize(), intersectRayBoundary(), intersectTinyLineSegmentBoundary(), intersectTriangleVoxel(), mapIndices2Voxel(), mapPoint2Voxel(), and mapVoxelIndices2ID().
The documentation for this class was generated from the following files:
BoundaryGeometry.h
BoundaryGeometry.cpp