OPALX (Object Oriented Parallel Accelerator Library for Exascal): MemoryProfiler Class Reference
MemoryProfiler Class Reference
#include <MemoryProfiler.h>
Public Types
enum VirtualMemory {
VMPEAK = 0 , VMSIZE , VMHWM , VMRSS ,
VMDATA , VMSTK , VMEXE , VMLCK ,
VMPIN , VMLIB , VMPTE , VMPMD ,
VMSWAP
}
typedef std::vector< long double > vm_t
typedef std::vector< std::string > units_t
typedef std::pair< std::string, std::string > desc_t
typedef std::tuple< std::string, std::string, std::string > param_t
typedef std::pair< std::string, size_t > data_t
typedef std::tuple< std::string, std::string, std::string, std::string > cols_t
Public Member Functions
MemoryProfiler (const std::string &fname, bool restart)
void write (const PartBunch_t &beam) override
void rewindLines (size_t numberOfLines)
delete the last 'numberOfLines' lines of the file 'fileName'
void replaceVersionString ()
double getLastValue (const std::string &column)
bool exists () const
Protected Member Functions
void addDescription (const std::string &text, const std::string &content)
template<typename T>
void addParameter (const std::string &name, const std::string &type, const std::string &desc, const T &value)
void addDefaultParameters ()
void addColumn (const std::string &name, const std::string &type, const std::string &unit, const std::string &desc)
void addInfo (const std::string &mode, const size_t &no_row_counts)
void writeRow ()
void open ()
void close ()
void writeHeader ()
Write SDDS header.
template<typename T>
std::string toString (const T &val)
bool hasColumns () const
Protected Attributes
std::string fname_m
std::ios_base::openmode mode_m
First write to the statistics output file.
SDDSColumnSet columns_m
Private Member Functions
void header ()
void update ()
void compute (vm_t &vmMin, vm_t &vmMax, vm_t &vmAvg)
void writeDescription ()
void writeParameters ()
void writeColumns ()
void writeInfo ()
Private Attributes
std::map< std::string, int > procinfo_m
vm_t vmem_m
units_t unit_m
std::ofstream os_m
std::string indent_m
desc_t desc_m
std::queue< param_t > params_m
std::queue< std::string > paramValues_m
data_t info_m
Static Private Attributes
static constexpr unsigned int precision_m = 15
Detailed Description
Definition at line 31 of file MemoryProfiler.h.
Member Typedef Documentation
cols_t
typedef std::tuple<std::string, std::string, std::string, std::string> SDDSWriter::cols_t inherited
Definition at line 50 of file SDDSWriter.h.
data_t
typedef std::pair<std::string, size_t> SDDSWriter::data_t inherited
Definition at line 47 of file SDDSWriter.h.
desc_t
typedef std::pair<std::string, std::string> SDDSWriter::desc_t inherited
Definition at line 41 of file SDDSWriter.h.
param_t
typedef std::tuple<std::string, std::string, std::string> SDDSWriter::param_t inherited
Definition at line 44 of file SDDSWriter.h.
units_t
typedef std::vector<std::string> MemoryProfiler::units_t
Definition at line 39 of file MemoryProfiler.h.
vm_t
typedef std::vector<long double> MemoryProfiler::vm_t
Definition at line 38 of file MemoryProfiler.h.
Member Enumeration Documentation
VirtualMemory
enum MemoryProfiler::VirtualMemory
Enumerator
VMPEAK
VMSIZE
VMHWM
VMRSS
VMDATA
VMSTK
VMEXE
VMLCK
VMPIN
VMLIB
VMPTE
VMPMD
VMSWAP
Definition at line 43 of file MemoryProfiler.h.
Constructor & Destructor Documentation
MemoryProfiler()
MemoryProfiler::MemoryProfiler (const std::string & fname, bool restart)
Definition at line 40 of file MemoryProfiler.cpp.
References procinfo_m, SDDSWriter::SDDSWriter(), unit_m, VMDATA, vmem_m, VMEXE, VMHWM, VMLCK, VMLIB, VMPEAK, VMPIN, VMPMD, VMPTE, VMRSS, VMSIZE, VMSTK, and VMSWAP.
Member Function Documentation
addColumn()
void SDDSWriter::addColumn (const std::string & name, const std::string & type, const std::string & unit, const std::string & desc) protected inherited
addDefaultParameters()
void SDDSWriter::addDefaultParameters () protected inherited
Definition at line 190 of file SDDSWriter.cpp.
References addParameter(), Util::getGitRevision(), and OpalData::getInstance().
Referenced by ElementPositionWriter::fillHeader(), LBalWriter::fillHeader(), MonitorStatisticsWriter::fillHeader(), and MemoryProfiler::header().
addDescription()
void SDDSWriter::addDescription (const std::string & text, const std::string & content) inline protected inherited
Definition at line 141 of file SDDSWriter.h.
References desc_m.
Referenced by ElementPositionWriter::fillHeader(), LBalWriter::fillHeader(), MonitorStatisticsWriter::fillHeader(), StatWriter::fillHeader(), and MemoryProfiler::header().
addInfo()
void SDDSWriter::addInfo (const std::string & mode, const size_t & no_row_counts) inline protected inherited
Definition at line 154 of file SDDSWriter.h.
References info_m.
Referenced by ElementPositionWriter::fillHeader(), LBalWriter::fillHeader(), MonitorStatisticsWriter::fillHeader(), StatWriter::fillHeader(), and MemoryProfiler::header().
addParameter()
template<typename T> void SDDSWriter::addParameter (const std::string & name, const std::string & type, const std::string & desc, const T & value) protected inherited
Definition at line 146 of file SDDSWriter.h.
References params_m, and paramValues_m.
Referenced by addDefaultParameters(), and StatWriter::fillHeader().
close()
void SDDSWriter::close () protected inherited
Definition at line 131 of file SDDSWriter.cpp.
References os_m.
Referenced by ElementPositionWriter::addRow(), MonitorStatisticsWriter::addRow(), LBalWriter::write(), MemoryProfiler::write(), and StatWriter::write().
compute()
void MemoryProfiler::compute (vm_t & vmMin, vm_t & vmMax, vm_t & vmAvg) private
Definition at line 159 of file MemoryProfiler.cpp.
References vmem_m.
Referenced by write().
exists()
bool SDDSWriter::exists () const inline inherited
Definition at line 139 of file SDDSWriter.h.
References fname_m.
getLastValue()
double SDDSWriter::getLastValue (const std::string & column) inherited
Definition at line 115 of file SDDSWriter.cpp.
References fname_m, SDDS::SDDSParser::getValue(), and SDDS::SDDSParser::run().
hasColumns()
bool SDDSWriter::hasColumns () const inline protected inherited
Definition at line 168 of file SDDSWriter.h.
References columns_m.
Referenced by ElementPositionWriter::fillHeader(), LBalWriter::fillHeader(), MonitorStatisticsWriter::fillHeader(), StatWriter::fillHeader(), and MemoryProfiler::header().
header()
void MemoryProfiler::header () private
Definition at line 54 of file MemoryProfiler.cpp.
References SDDSWriter::addDefaultParameters(), SDDSWriter::addDescription(), SDDSWriter::addInfo(), SDDSWriter::columns_m, OPALTimer::Timer::date(), OpalData::getInputFn(), OpalData::getInstance(), SDDSWriter::hasColumns(), SDDSWriter::mode_m, OPALTimer::Timer::time(), unit_m, VMHWM, VMPEAK, VMRSS, VMSIZE, and VMSTK.
Referenced by write().
open()
void SDDSWriter::open () protected inherited
Definition at line 123 of file SDDSWriter.cpp.
References fname_m, mode_m, os_m, and precision_m.
Referenced by ElementPositionWriter::addRow(), MonitorStatisticsWriter::addRow(), LBalWriter::write(), MemoryProfiler::write(), and StatWriter::write().
replaceVersionString()
void SDDSWriter::replaceVersionString () inherited
Definition at line 74 of file SDDSWriter.cpp.
References fname_m, Util::getGitRevision(), SDDS::SDDSParser::getParameterValue(), and SDDS::SDDSParser::run().
rewindLines()
void SDDSWriter::rewindLines (size_t numberOfLines) inherited
delete the last 'numberOfLines' lines of the file 'fileName'
Definition at line 45 of file SDDSWriter.cpp.
References fname_m.
toString()
template<typename T> std::string SDDSWriter::toString (const T & val) protected inherited
Definition at line 161 of file SDDSWriter.h.
References precision_m.
Referenced by MemoryProfiler::write().
update()
void MemoryProfiler::update () private
Definition at line 131 of file MemoryProfiler.cpp.
References procinfo_m, unit_m, and vmem_m.
Referenced by write().
write()
void MemoryProfiler::write (const PartBunch_t & beam) override virtual
Reimplemented from SDDSWriter.
Definition at line 181 of file MemoryProfiler.cpp.
References SDDSWriter::close(), SDDSWriter::columns_m, compute(), PartBunch< T, Dim >::getT(), header(), SDDSWriter::open(), Units::s2ns, SDDSWriter::toString(), update(), vmem_m, VMHWM, VMPEAK, VMRSS, VMSIZE, VMSTK, SDDSWriter::writeHeader(), and SDDSWriter::writeRow().
writeColumns()
void SDDSWriter::writeColumns () private inherited
Definition at line 173 of file SDDSWriter.cpp.
References columns_m, indent_m, and os_m.
Referenced by writeHeader().
writeDescription()
void SDDSWriter::writeDescription () private inherited
Definition at line 151 of file SDDSWriter.cpp.
References desc_m, indent_m, and os_m.
Referenced by writeHeader().
writeHeader()
void SDDSWriter::writeHeader () protected inherited
Write SDDS header.
Writes the appropriate SDDS format header information, The SDDS tools can be used for plotting data.
Definition at line 137 of file SDDSWriter.cpp.
References mode_m, writeColumns(), writeDescription(), writeInfo(), and writeParameters().
Referenced by ElementPositionWriter::addRow(), MonitorStatisticsWriter::addRow(), LBalWriter::write(), MemoryProfiler::write(), and StatWriter::write().
writeInfo()
void SDDSWriter::writeInfo () private inherited
Definition at line 175 of file SDDSWriter.cpp.
References indent_m, info_m, os_m, and paramValues_m.
Referenced by writeHeader().
writeParameters()
void SDDSWriter::writeParameters () private inherited
Definition at line 159 of file SDDSWriter.cpp.
References indent_m, os_m, and params_m.
Referenced by writeHeader().
writeRow()
void SDDSWriter::writeRow () inline protected inherited
Definition at line 158 of file SDDSWriter.h.
References columns_m, and os_m.
Referenced by ElementPositionWriter::addRow(), MonitorStatisticsWriter::addRow(), LBalWriter::write(), MemoryProfiler::write(), and StatWriter::write().
Member Data Documentation
columns_m
SDDSColumnSet SDDSWriter::columns_m protected inherited
Definition at line 111 of file SDDSWriter.h.
Referenced by ElementPositionWriter::addRow(), MonitorStatisticsWriter::addRow(), ElementPositionWriter::fillHeader(), LBalWriter::fillHeader(), MonitorStatisticsWriter::fillHeader(), StatWriter::fillHeader(), hasColumns(), MemoryProfiler::header(), LBalWriter::write(), MemoryProfiler::write(), StatWriter::write(), writeColumns(), and writeRow().
desc_m
desc_t SDDSWriter::desc_m private inherited
Definition at line 131 of file SDDSWriter.h.
Referenced by addDescription(), and writeDescription().
fname_m
std::string SDDSWriter::fname_m protected inherited
Definition at line 101 of file SDDSWriter.h.
Referenced by exists(), getLastValue(), open(), replaceVersionString(), rewindLines(), StatBaseWriter::rewindToSpos(), and SDDSWriter().
indent_m
std::string SDDSWriter::indent_m private inherited
Definition at line 129 of file SDDSWriter.h.
Referenced by SDDSWriter(), writeColumns(), writeDescription(), writeInfo(), and writeParameters().
info_m
data_t SDDSWriter::info_m private inherited
Definition at line 134 of file SDDSWriter.h.
Referenced by addInfo(), and writeInfo().
mode_m
std::ios_base::openmode SDDSWriter::mode_m protected inherited
First write to the statistics output file.
Initially set to std::ios::out so that SDDS format header information is written to file during the first write call to the statistics output file. Variable is then reset to std::ios::app so that header information is only written once.
Definition at line 109 of file SDDSWriter.h.
Referenced by LBalWriter::fillHeader(), StatWriter::fillHeader(), MemoryProfiler::header(), open(), SDDSWriter(), and writeHeader().
os_m
std::ofstream SDDSWriter::os_m private inherited
Definition at line 127 of file SDDSWriter.h.
Referenced by close(), open(), writeColumns(), writeDescription(), writeInfo(), writeParameters(), and writeRow().
params_m
std::queue<param_t> SDDSWriter::params_m private inherited
Definition at line 132 of file SDDSWriter.h.
Referenced by addParameter(), and writeParameters().
paramValues_m
std::queue<std::string> SDDSWriter::paramValues_m private inherited
Definition at line 133 of file SDDSWriter.h.
Referenced by addParameter(), and writeInfo().
precision_m
unsigned int SDDSWriter::precision_m = 15 static constexpr private inherited
Definition at line 136 of file SDDSWriter.h.
Referenced by open(), and toString().
procinfo_m
std::map<std::string, int> MemoryProfiler::procinfo_m private
Definition at line 69 of file MemoryProfiler.h.
Referenced by MemoryProfiler(), and update().
unit_m
units_t MemoryProfiler::unit_m private
Definition at line 71 of file MemoryProfiler.h.
Referenced by header(), MemoryProfiler(), and update().
vmem_m
vm_t MemoryProfiler::vmem_m private
Definition at line 70 of file MemoryProfiler.h.
Referenced by compute(), MemoryProfiler(), update(), and write().
The documentation for this class was generated from the following files:
MemoryProfiler.h
MemoryProfiler.cpp