OPALX (Object Oriented Parallel Accelerator Library for Exascal): RBendGeometry Class Reference
RBendGeometry Class Reference
The geometry for a RBend element.
#include <RBendGeometry.h>
Public Member Functions
RBendGeometry (double length, double angle)
Constructor.
RBendGeometry (const RBendGeometry &)
virtual ~RBendGeometry ()
const RBendGeometry & operator= (const RBendGeometry &)
virtual double getArcLength () const
Get arc length.
virtual double getBendAngle () const
Get angle.
void setBendAngle (double angle)
Set angle.
Euclid3D getTotalTransform () const
Get transform.
Euclid3D getEntranceFrame () const
Get transform.
Euclid3D getExitFrame () const
Get transform.
Euclid3D getEntrancePatch () const
Get patch.
Euclid3D getExitPatch () const
Get patch.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
double getOrigin () const
Get origin.
double getEntrance () const
Get entrance.
double getExit () const
Get exit.
Euclid3D getTransform (double fromS, double toS) const
Get transform.
Euclid3D getTransform (double s) const
Get transform.
Private Attributes
double half_angle
double len
Detailed Description
The geometry for a RBend element.
Definition at line 41 of file RBendGeometry.h.
Constructor & Destructor Documentation
RBendGeometry() [1/2]
RBendGeometry::RBendGeometry (double length, double angle)
Constructor.
Definition at line 30 of file RBendGeometry.cpp.
RBendGeometry() [2/2]
RBendGeometry::RBendGeometry (const RBendGeometry & rhs)
Definition at line 35 of file RBendGeometry.cpp.
~RBendGeometry()
RBendGeometry::~RBendGeometry () virtual
Definition at line 40 of file RBendGeometry.cpp.
Member Function Documentation
getArcLength()
double RBendGeometry::getArcLength () const virtual
Get arc length.
Reimplemented from StraightGeometry.
Definition at line 44 of file RBendGeometry.cpp.
References StraightGeometry::getElementLength(), and half_angle.
getBendAngle()
double RBendGeometry::getBendAngle () const virtual
Get angle.
Definition at line 50 of file RBendGeometry.cpp.
References half_angle.
getElementLength()
double StraightGeometry::getElementLength () const virtual inherited
Get design length.
Implements BGeometryBase.
Definition at line 40 of file StraightGeometry.cpp.
References StraightGeometry::len.
Referenced by getArcLength(), getEntrancePatch(), getExitPatch(), Corrector::goOnline(), Corrector::setDesignEnergy(), and TEST_F().
getEntrance()
double StraightGeometry::getEntrance () const virtual inherited
Get entrance.
Reimplemented from BGeometryBase.
Definition at line 59 of file StraightGeometry.cpp.
References StraightGeometry::len.
getEntranceFrame()
Euclid3D RBendGeometry::getEntranceFrame () const virtual
Get transform.
Reimplemented from BGeometryBase.
Definition at line 67 of file RBendGeometry.cpp.
References StraightGeometry::getEntranceFrame(), half_angle, and Euclid3D::YRotation().
getEntrancePatch()
Euclid3D RBendGeometry::getEntrancePatch () const virtual
Get patch.
Reimplemented from BGeometryBase.
Definition at line 81 of file RBendGeometry.cpp.
References StraightGeometry::getElementLength(), half_angle, Euclid3D::translation(), and Euclid3D::YRotation().
getExit()
double StraightGeometry::getExit () const virtual inherited
Get exit.
Reimplemented from BGeometryBase.
Definition at line 64 of file StraightGeometry.cpp.
References StraightGeometry::len.
getExitFrame()
Euclid3D RBendGeometry::getExitFrame () const virtual
Get transform.
Reimplemented from BGeometryBase.
Definition at line 74 of file RBendGeometry.cpp.
References StraightGeometry::getExitFrame(), half_angle, and Euclid3D::YRotation().
getExitPatch()
Euclid3D RBendGeometry::getExitPatch () const virtual
Get patch.
Reimplemented from BGeometryBase.
Definition at line 88 of file RBendGeometry.cpp.
References StraightGeometry::getElementLength(), half_angle, Euclid3D::translation(), and Euclid3D::YRotation().
getOrigin()
double StraightGeometry::getOrigin () const virtual inherited
Get origin.
Reimplemented from BGeometryBase.
Definition at line 54 of file StraightGeometry.cpp.
References StraightGeometry::len.
getTotalTransform()
Euclid3D RBendGeometry::getTotalTransform () const virtual
Get transform.
Reimplemented from BGeometryBase.
Definition at line 60 of file RBendGeometry.cpp.
References StraightGeometry::getTotalTransform(), half_angle, and Euclid3D::YRotation().
getTransform() [1/2]
Euclid3D StraightGeometry::getTransform (double fromS, double toS) const virtual inherited
Get transform.
Implements BGeometryBase.
Definition at line 69 of file StraightGeometry.cpp.
References Euclid3D::translation().
getTransform() [2/2]
Euclid3D StraightGeometry::getTransform (double s) const virtual inherited
Get transform.
Reimplemented from BGeometryBase.
Definition at line 79 of file StraightGeometry.cpp.
References Euclid3D::translation().
operator=()
const RBendGeometry & RBendGeometry::operator= (const RBendGeometry &)
setBendAngle()
void RBendGeometry::setBendAngle (double angle)
Set angle.
Definition at line 55 of file RBendGeometry.cpp.
References half_angle.
Referenced by OpalRBend::update().
setElementLength()
void StraightGeometry::setElementLength (double length) virtual inherited
Set design length.
Reimplemented from BGeometryBase.
Definition at line 45 of file StraightGeometry.cpp.
References StraightGeometry::len.
Referenced by VerticalFFAMagnet::initialise(), MultipoleTStraight::initialise(), ConstantEFieldCavityRep::setElementLength(), VariableRFCavity::setLength(), and OpalRBend::update().
Member Data Documentation
half_angle
double RBendGeometry::half_angle private
Definition at line 96 of file RBendGeometry.h.
Referenced by getArcLength(), getBendAngle(), getEntranceFrame(), getEntrancePatch(), getExitFrame(), getExitPatch(), getTotalTransform(), and setBendAngle().
len
double StraightGeometry::len private inherited
Definition at line 104 of file StraightGeometry.h.
Referenced by StraightGeometry::getArcLength(), StraightGeometry::getElementLength(), StraightGeometry::getEntrance(), StraightGeometry::getEntranceFrame(), StraightGeometry::getExit(), StraightGeometry::getExitFrame(), StraightGeometry::getOrigin(), StraightGeometry::getTotalTransform(), StraightGeometry::operator=(), and StraightGeometry::setElementLength().
The documentation for this class was generated from the following files:
RBendGeometry.h
RBendGeometry.cpp