OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions::SUnary< T, U > Class Template Reference
Expressions::SUnary< T, U > Class Template Reference
A scalar expression with one scalar operand.
#include <SUnary.h>
Public Member Functions
SUnary (const TFunction1< T, U > &function, PtrToScalar< U > operand)
Constructor.
SUnary (const SUnary< T, U > &)
virtual ~SUnary ()
virtual Scalar< T > * clone () const
Make clone.
virtual T evaluate () const
Evaluate.
virtual void print (std::ostream &, int precedence=99) const
Print expression.
virtual bool isConstant () const
Test for constant.
Static Public Member Functions
static Scalar< T > * make (const TFunction1< T, U > &function, PtrToScalar< U > operand)
Make a new expression.
Private Member Functions
SUnary ()
void operator= (const SUnary &)
Private Attributes
const TFunction1< T, U > & fun
PtrToScalar< U > opr
Detailed Description
template<class T, class U>
class Expressions::SUnary< T, U >
A scalar expression with one scalar operand.
Definition at line 38 of file SUnary.h.
Constructor & Destructor Documentation
SUnary() [1/3]
template<class T, class U> Expressions::SUnary< T, U >::SUnary (const TFunction1< T, U > & function, PtrToScalar< U > operand) inline
Constructor.
Definition at line 82 of file SUnary.h.
References fun, and opr.
Referenced by clone(), make(), operator=(), and SUnary().
SUnary() [2/3]
template<class T, class U> Expressions::SUnary< T, U >::SUnary (const SUnary< T, U > & rhs) inline
Definition at line 78 of file SUnary.h.
References clone(), fun, opr, Expressions::Scalar< T >::Scalar(), and SUnary().
~SUnary()
template<class T, class U> Expressions::SUnary< T, U >::~SUnary () inline virtual
Definition at line 86 of file SUnary.h.
SUnary() [3/3]
template<class T, class U> Expressions::SUnary< T, U >::SUnary () private
Member Function Documentation
clone()
template<class T, class U> Scalar< T > * Expressions::SUnary< T, U >::clone () const inline virtual
Make clone.
Implements Expressions::Scalar< T >.
Definition at line 89 of file SUnary.h.
References Expressions::Scalar< T >::Scalar(), and SUnary().
Referenced by SUnary().
evaluate()
template<class T, class U> T Expressions::SUnary< T, U >::evaluate () const inline virtual
Evaluate.
Implements Expressions::Scalar< T >.
Definition at line 94 of file SUnary.h.
References fun, and opr.
isConstant()
template<class T> bool Expressions::Scalar< T >::isConstant () const inline virtual inherited
Test for constant.
Reimplemented in Expressions::SConstant< T >.
Definition at line 287 of file AbstractObjects/Expressions.h.
make()
template<class T, class U> Scalar< T > * Expressions::SUnary< T, U >::make (const TFunction1< T, U > & function, PtrToScalar< U > operand) inline static
Make a new expression.
Definition at line 116 of file SUnary.h.
References Expressions::TFunction1< T, U >::precedence, Expressions::PtrToScalar< T >::release(), Expressions::Scalar< T >::Scalar(), and SUnary().
Referenced by Expressions::parsePrimary(), and Expressions::parseReal().
operator=()
template<class T, class U> void Expressions::SUnary< T, U >::operator= (const SUnary< T, U > &) private
References SUnary().
print()
template<class T, class U> void Expressions::SUnary< T, U >::print (std::ostream & os, int precedence = 99) const inline virtual
Print expression.
Implements Expressions::Scalar< T >.
Definition at line 136 of file SUnary.h.
References fun, and opr.
Member Data Documentation
fun
template<class T, class U> const TFunction1<T, U>& Expressions::SUnary< T, U >::fun private
Definition at line 68 of file SUnary.h.
Referenced by evaluate(), print(), SUnary(), and SUnary().
opr
template<class T, class U> PtrToScalar<U> Expressions::SUnary< T, U >::opr private
Definition at line 71 of file SUnary.h.
Referenced by evaluate(), print(), SUnary(), and SUnary().
The documentation for this class was generated from the following file:
SUnary.h