OPALX (Object Oriented Parallel Accelerator Library for Exascal): EMField Class Reference
EMField Class Reference abstract
Abstract base class for electromagnetic fields.
#include <EMField.h>
Public Member Functions
EMField ()
Default constructor.
EMField (const EMField &right)
virtual ~EMField ()
const EMField & operator= (const EMField &right)
virtual EVector Efield (const Point3D &P) const
Get field.
virtual BVector Bfield (const Point3D &P) const
Get field.
virtual EVector Efield (const Point3D &P, double t) const
Get field.
virtual BVector Bfield (const Point3D &P, double t) const
Get field.
virtual EBVectors EBfield (const Point3D &P) const
Get field.
virtual EBVectors EBfield (const Point3D &P, double t) const
Get field.
virtual void scale (double scalar)=0
Scale the field.
Static Public Attributes
static const EVector ZeroEfield
The constant representing a zero electric field.
static const BVector ZeroBfield
The constant representing a zero magnetic field.
static const EBVectors ZeroEBfield
The constant representing a zero electromagnetic field.
Detailed Description
Abstract base class for electromagnetic fields.
Definition at line 171 of file EMField.h.
Constructor & Destructor Documentation
EMField() [1/2]
EMField::EMField ()
Default constructor.
Definition at line 111 of file EMField.cpp.
Referenced by EMField(), NullField::NullField(), and operator=().
EMField() [2/2]
EMField::EMField (const EMField & right)
Definition at line 113 of file EMField.cpp.
References EMField().
~EMField()
EMField::~EMField () virtual
Definition at line 115 of file EMField.cpp.
Member Function Documentation
Bfield() [1/2]
BVector EMField::Bfield (const Point3D & P) const virtual
Get field.
Reimplemented in BDipoleField, BMultipoleField, ConstBzField, and OscillatingField< ConstEzField >.
Definition at line 121 of file EMField.cpp.
References ZeroBfield.
Referenced by Component::Bfield(), Component::Bfield(), Bfield(), and EBfield().
Bfield() [2/2]
BVector EMField::Bfield (const Point3D & P, double t) const virtual
Get field.
Reimplemented in BDipoleField, BMultipoleField, ConstBzField, and OscillatingField< ConstEzField >.
Definition at line 125 of file EMField.cpp.
References Bfield().
EBfield() [1/2]
EBVectors EMField::EBfield (const Point3D & P) const virtual
Get field.
Definition at line 127 of file EMField.cpp.
References Bfield(), and Efield().
Referenced by Component::EBfield(), Component::EBfield(), and EBfield().
EBfield() [2/2]
EBVectors EMField::EBfield (const Point3D & P, double t) const virtual
Get field.
Definition at line 129 of file EMField.cpp.
References EBfield().
Efield() [1/2]
EVector EMField::Efield (const Point3D & P) const virtual
Get field.
Reimplemented in ConstEzField, and OscillatingField< ConstEzField >.
Definition at line 119 of file EMField.cpp.
References ZeroEfield.
Referenced by EBfield(), Component::Efield(), Component::Efield(), and Efield().
Efield() [2/2]
EVector EMField::Efield (const Point3D & P, double t) const virtual
Get field.
Reimplemented in ConstEzField, and OscillatingField< ConstEzField >.
Definition at line 123 of file EMField.cpp.
References Efield().
operator=()
const EMField & EMField::operator= (const EMField & right)
Definition at line 117 of file EMField.cpp.
References EMField().
scale()
virtual void EMField::scale (double scalar) pure virtual
Scale the field.
Implemented in BDipoleField, BMultipoleField, ConstBzField, ConstEzField, DummyField, DummyFieldTW, and NullField.
Member Data Documentation
ZeroBfield
const BVector EMField::ZeroBfield static
The constant representing a zero magnetic field.
Definition at line 220 of file EMField.h.
Referenced by Bfield().
ZeroEBfield
const EBVectors EMField::ZeroEBfield static
The constant representing a zero electromagnetic field.
Definition at line 223 of file EMField.h.
ZeroEfield
const EVector EMField::ZeroEfield static
The constant representing a zero electric field.
Definition at line 217 of file EMField.h.
Referenced by Efield().
The documentation for this class was generated from the following files:
EMField.h
EMField.cpp