OPALX (Object Oriented Parallel Accelerator Library for Exascal): VariableRFCavity Class Reference
VariableRFCavity Class Reference
#include <VariableRFCavity.h>
Public Member Functions
VariableRFCavity (const std::string &name)
Constructor with given name.
VariableRFCavity (const VariableRFCavity &)
VariableRFCavity ()
VariableRFCavity & operator= (const VariableRFCavity &)
~VariableRFCavity () override=default
void accept (BeamlineVisitor &) const override
ElementBase * clone () const override
bool apply (const std::shared_ptr< ParticleContainer_t > &pc) override
bool apply (const size_t &i, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
bool apply (const Vector_t< double, 3 > &R, const Vector_t< double, 3 > &P, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
bool applyToReferenceParticle (const Vector_t< double, 3 > &R, const Vector_t< double, 3 > &P, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
void initialise (PartBunch_t *bunch, double &startField, double &endField) override
void finalise () override
bool bends () const override
void getDimensions (double &, double &) const override
virtual double getAmplitude (const double time) const
virtual double getFrequency (const double time) const
virtual double getPhase (const double time) const
virtual double getHeight () const
virtual double getWidth () const
virtual double getLength () const
virtual void setHeight (const double fullHeight)
virtual void setWidth (const double fullWidth)
virtual void setLength (double length)
virtual std::shared_ptr< AbstractTimeDependence > getAmplitudeModel () const
virtual std::shared_ptr< AbstractTimeDependence > getPhaseModel () const
virtual std::shared_ptr< AbstractTimeDependence > getFrequencyModel () const
virtual void setAmplitudeModel (std::shared_ptr< AbstractTimeDependence > amplitude_td)
virtual void setPhaseModel (std::shared_ptr< AbstractTimeDependence > phase_td)
virtual void setFrequencyModel (std::shared_ptr< AbstractTimeDependence > frequency_td)
virtual void setAmplitudeName (const std::string &amplitude)
virtual void setPhaseName (const std::string &phase)
virtual void setFrequencyName (const std::string &frequency)
StraightGeometry & getGeometry () override
const StraightGeometry & getGeometry () const override
void initialiseTimeDependencies () const
EMField & getField () override
Not implemented.
const EMField & getField () const override
Not implemented.
EVector Efield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool getPotential (const Vector_t< double, 3 > &, const double &, Vector_t< double, 3 > &, double &)
Calculate the four-potential at some position relative to the component.
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual void goOnline (const double &kineticEnergy)
virtual void goOffline ()
virtual bool Online ()
virtual ElementType getType () const
Get element type std::string.
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunch_t &bunch, const PartData &, bool revBeam, bool revTrack) const
Track a borrowed particle bunch through a non-standard component.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t< double, 3 > &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Static Public Member Functions
static std::string getTypeString (ElementType type)
Protected Member Functions
void initNull ()
bool isInsideTransverse (const Vector_t< double, 3 > &r) const
Static Protected Member Functions
static KOKKOS_INLINE_FUNCTION bool computeField (const Vector_t< double, 3 > &R, Vector_t< double, 3 > &E, double E0, double integralF, double phi, double halfWidth, double halfHeight)
Protected Attributes
std::shared_ptr< AbstractTimeDependence > phaseTD_m
std::shared_ptr< AbstractTimeDependence > amplitudeTD_m
std::shared_ptr< AbstractTimeDependence > frequencyTD_m
std::string phaseName_m
std::string amplitudeName_m
std::string frequencyName_m
double halfWidth_m
double halfHeight_m
double length_m
StraightGeometry geometry
The cavity's geometry.
double exit_face_slope_m
PartBunch_t * RefPartBunch_m
bool online_m
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes
static const std::vector< double > defaultAperture_m
Private Attributes
std::string elementID
AttributeSet userAttribs
WakeFunction * wake_m
BoundaryGeometry * bgeometry_m
ParticleMatterInteractionHandler * parmatint_m
bool positionIsFixed
std::queue< std::pair< double, double > > actionRange_m
std::string outputfn_m
bool deleteOnTransverseExit_m = true
double elementPosition_m
ELEMEDGE attribute.
bool elemedgeSet_m
Static Private Attributes
static const std::map< ElementType, std::string > elementTypeToString_s
Detailed Description
Generates a field like E = a(t) * sin{2*pi * integral(f(tau),0,t) + q(t)} B = 0 where E0, B0 are user defined fields, a(t), f(t), q(t) are time dependent amplitude, frequency, phase respectively; it is assumed that these quantities vary sufficiently slowly that Maxwell is satisfied.
The time dependent quantities are
Definition at line 39 of file VariableRFCavity.h.
Constructor & Destructor Documentation
VariableRFCavity() [1/3]
VariableRFCavity::VariableRFCavity (const std::string & name) explicit
Constructor with given name.
Definition at line 25 of file VariableRFCavity.cpp.
References initNull().
VariableRFCavity() [2/3]
VariableRFCavity::VariableRFCavity (const VariableRFCavity & var)
Copy Constructor; performs deepcopy on time-dependence models
Definition at line 33 of file VariableRFCavity.cpp.
References initNull().
VariableRFCavity() [3/3]
VariableRFCavity::VariableRFCavity ()
Default constructor
Definition at line 29 of file VariableRFCavity.cpp.
References initNull().
Referenced by clone().
~VariableRFCavity()
VariableRFCavity::~VariableRFCavity () override default
Destructor does nothing
The shared_ptrs will self-destruct when reference count goes to 0
Member Function Documentation
accept()
void VariableRFCavity::accept (BeamlineVisitor & visitor) const override virtual
Apply visitor to RFCavity.
The RF cavity finds the "time dependence" models by doing a string lookup against a list held by AbstractTimeDependence at accept time.
Implements ElementBase.
Definition at line 170 of file VariableRFCavity.cpp.
References initialiseTimeDependencies(), and BeamlineVisitor::visitVariableRFCavity().
Referenced by TEST_F().
apply() [1/3]
bool VariableRFCavity::apply (const size_t & i, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual
Calculate the field at the position of the i^th particle
Parameters
i indexes the particle whose field we need
t the time at which the field is calculated
E return value with electric field strength
B return value with magnetic field strength
Returns
True if particle is outside the boundaries; else False
Reimplemented from Component.
Definition at line 113 of file VariableRFCavity.cpp.
References amplitudeTD_m, computeField(), frequencyTD_m, halfHeight_m, halfWidth_m, Units::MHz2Hz, Units::MVpm2Vpm, phaseTD_m, and Component::RefPartBunch_m.
apply() [2/3]
bool VariableRFCavity::apply (const std::shared_ptr< ParticleContainer_t > & pc) override virtual
Calculate the field for all particles
Reimplemented from Component.
Definition at line 136 of file VariableRFCavity.cpp.
References amplitudeTD_m, computeField(), frequencyTD_m, PartBunch< T, Dim >::getT(), halfHeight_m, halfWidth_m, Units::MHz2Hz, Units::MVpm2Vpm, phaseTD_m, and Component::RefPartBunch_m.
Referenced by applyToReferenceParticle(), TEST_F(), and TEST_F().
apply() [3/3]
bool VariableRFCavity::apply (const Vector_t< double, 3 > & R, const Vector_t< double, 3 > & P, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual
Calculate the field at a given position
Parameters
R the position at which the field is calculated
P the momentum (not used)
t the time at which the field is calculated
E return value; filled with electric field strength
B return value; filled with magnetic field strength
Returns
True if particle is outside the boundaries; else False
Reimplemented from Component.
Definition at line 127 of file VariableRFCavity.cpp.
References amplitudeTD_m, computeField(), frequencyTD_m, halfHeight_m, halfWidth_m, Units::MHz2Hz, Units::MVpm2Vpm, and phaseTD_m.
applyToReferenceParticle()
bool VariableRFCavity::applyToReferenceParticle (const Vector_t< double, 3 > & R, const Vector_t< double, 3 > & P, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual
Calculate the field at a given position. This is identical to "apply".
Parameters
R the position at which the field is calculated
P the momentum (not used)
t the time at which the field is calculated
E return value; filled with electric field strength
B return value; filled with magnetic field strength
Returns
True if particle is outside the boundaries; else False
Reimplemented from Component.
Definition at line 155 of file VariableRFCavity.cpp.
References apply().
bends()
bool VariableRFCavity::bends () const inline override virtual
Returns
false (cavity does not bend the trajectory)
Implements Component.
Definition at line 121 of file VariableRFCavity.h.
Referenced by TEST_F().
Bfield() [1/2]
BVector Component::Bfield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 248 of file Component.h.
References EMField::Bfield(), and Component::getField().
Bfield() [2/2]
BVector Component::Bfield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 256 of file Component.h.
References EMField::Bfield(), and Component::getField().
clone()
ElementBase * VariableRFCavity::clone () const override virtual
Inheritable deepcopy method
Implements ElementBase.
Definition at line 168 of file VariableRFCavity.cpp.
References VariableRFCavity().
Referenced by TEST_F().
computeField()
KOKKOS_INLINE_FUNCTION bool VariableRFCavity::computeField (const Vector_t< double, 3 > & R, Vector_t< double, 3 > & E, double E0, double integralF, double phi, double halfWidth, double halfHeight) static protected
Definition at line 233 of file VariableRFCavity.h.
References Physics::two_pi.
Referenced by apply(), apply(), and apply().
copyStructure()
ElementBase * ElementBase::copyStructure () virtual inherited
Make a structural copy.
Reimplemented in TBeamline< T >.
Definition at line 205 of file ElementBase.cpp.
References ElementBase::clone(), and ElementBase::isSharable().
Referenced by Sequence::copy(), Line::parse(), SequenceParser::parseMember(), and Replacer::visitFlaggedElmPtr().
EBfield() [1/2]
EBVectors Component::EBfield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 260 of file Component.h.
References EMField::EBfield(), and Component::getField().
EBfield() [2/2]
EBVectors Component::EBfield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 264 of file Component.h.
References EMField::EBfield(), and Component::getField().
Efield() [1/2]
EVector Component::Efield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 244 of file Component.h.
References EMField::Efield(), and Component::getField().
Efield() [2/2]
EVector Component::Efield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 252 of file Component.h.
References EMField::Efield(), and Component::getField().
finalise()
void VariableRFCavity::finalise () override virtual
Finalise following tracking
Just sets RefPartBunch_m to nullptr
Implements Component.
Definition at line 166 of file VariableRFCavity.cpp.
References Component::RefPartBunch_m.
fixPosition()
void ElementBase::fixPosition () inline inherited
Definition at line 523 of file ElementBase.h.
References ElementBase::positionIsFixed.
Referenced by OpalElement::update().
getAmplitude()
virtual double VariableRFCavity::getAmplitude (const double time) const inline virtual
Get the amplitude at a given time
Parameters
time the time at which the amplitude is calculated
Returns
the RF field gradient.
Definition at line 132 of file VariableRFCavity.h.
References amplitudeTD_m.
Referenced by TEST_F().
getAmplitudeModel()
std::shared_ptr< AbstractTimeDependence > VariableRFCavity::getAmplitudeModel () const virtual
Returns
shared_ptr to the amplitude (field gradient) time dependence
Definition at line 74 of file VariableRFCavity.cpp.
References amplitudeTD_m.
Referenced by TEST_F(), TEST_F(), and TestVariableRFCavity::testNull().
getAperture()
std::pair< ApertureType, std::vector< double > > ElementBase::getAperture () const inline inherited
Definition at line 502 of file ElementBase.h.
References ElementBase::aperture_m.
Referenced by MeshGenerator::add(), Solenoid::getSupportEnvelope(), and MeshGenerator::getTransverseSupport().
getArcLength()
double ElementBase::getArcLength () const inline virtual inherited
Get arc length.
Reimplemented in MarkerRep, and TBeamline< T >.
Definition at line 394 of file ElementBase.h.
References BGeometryBase::getArcLength(), and ElementBase::getGeometry().
Referenced by BeamlineGeometry::getArcLength(), and TBeamline< T >::getTransform().
getAttribute()
double ElementBase::getAttribute (const std::string & aKey) const virtual inherited
Get attribute value.
Definition at line 154 of file ElementBase.cpp.
References ElementBase::getConstChannel().
getBoundaryGeometry()
BoundaryGeometry * ElementBase::getBoundaryGeometry () const inline virtual inherited
return the attached boundary geometrt object if there is any
Definition at line 458 of file ElementBase.h.
References ElementBase::bgeometry_m.
getBoundingBoxInLabCoords()
BoundingBox ElementBase::getBoundingBoxInLabCoords () const virtual inherited
Definition at line 273 of file ElementBase.cpp.
References ElementBase::aperture_m, ElementBase::csTrafoGlobal2Local_m, BoundingBox::getBoundingBox(), ElementBase::getEdgeToBegin(), ElementBase::getEdgeToEnd(), and CoordinateSystemTrafo::transformFrom().
getChannel()
Channel * ElementBase::getChannel (const std::string & aKey, bool create = false) virtual inherited
Construct a read/write channel.
Reimplemented in LaserRep, DriftRep, MonitorRep, MultipoleRep, ProbeRep, RFCavityRep, SolenoidRep, TravelingWaveRep, and ConstantEFieldCavityRep.
Definition at line 191 of file ElementBase.cpp.
References AttributeSet::getChannel(), and ElementBase::userAttribs.
Referenced by LaserRep::getChannel(), DriftRep::getChannel(), MonitorRep::getChannel(), MultipoleRep::getChannel(), ProbeRep::getChannel(), RFCavityRep::getChannel(), SolenoidRep::getChannel(), TravelingWaveRep::getChannel(), ConstantEFieldCavityRep::getChannel(), ElementBase::getConstChannel(), and ElementBase::setAttribute().
getConstChannel()
const ConstChannel * ElementBase::getConstChannel (const std::string & aKey) const virtual inherited
Construct a read-only channel.
Definition at line 195 of file ElementBase.cpp.
References ElementBase::getChannel().
Referenced by ElementBase::getAttribute(), and ElementBase::hasAttribute().
getCSTrafoGlobal2Local()
CoordinateSystemTrafo ElementBase::getCSTrafoGlobal2Local () const inline inherited
Definition at line 481 of file ElementBase.h.
References ElementBase::csTrafoGlobal2Local_m.
Referenced by MeshGenerator::add().
getDesign()
const ElementBase & Component::getDesign () const virtual inherited
Return design element.
Definition at line 41 of file Component.cpp.
getDesignEnergy()
double Component::getDesignEnergy () const inline virtual inherited
Reimplemented in RFCavity.
Definition at line 278 of file Component.h.
getDimensions()
void VariableRFCavity::getDimensions (double & , double &) const inline override virtual
Not used (does nothing)
Implements Component.
Definition at line 124 of file VariableRFCavity.h.
Referenced by TEST_F().
getEdgeToBegin()
CoordinateSystemTrafo ElementBase::getEdgeToBegin () const inline virtual inherited
Reimplemented in RFCavity, Solenoid, and TravelingWave.
Definition at line 485 of file ElementBase.h.
Referenced by ElementBase::getBoundingBoxInLabCoords(), and ElementBase::isInsideTransverse().
getEdgeToEnd()
CoordinateSystemTrafo ElementBase::getEdgeToEnd () const inline virtual inherited
Reimplemented in RFCavity, Solenoid, and TravelingWave.
Definition at line 490 of file ElementBase.h.
References ElementBase::getElementLength().
Referenced by ElementBase::getBoundingBoxInLabCoords().
getElementDimensions()
virtual void ElementBase::getElementDimensions (double & begin, double & end) const inline virtual inherited
Reimplemented in RFCavity, TravelingWave, and Solenoid.
Definition at line 161 of file ElementBase.h.
References ElementBase::getElementLength().
Referenced by MeshGenerator::add().
getElementLength()
double ElementBase::getElementLength () const inline virtual inherited
Get design length.
Reimplemented in MarkerRep, TBeamline< T >, RFCavity, and TestTravelingWave.
Definition at line 398 of file ElementBase.h.
References BGeometryBase::getElementLength(), and ElementBase::getGeometry().
Referenced by MeshGenerator::add(), ConstantEFieldCavity::apply(), Multipole::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), Component::apply(), Corrector::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), Solenoid::apply(), Component::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), Solenoid::applyToReferenceParticle(), Corrector::getDimensions(), ConstantEFieldCavity::getDimensions(), Drift::getDimensions(), Laser::getDimensions(), Multipole::getDimensions(), Solenoid::getDimensions(), ElementBase::getEdgeToEnd(), Solenoid::getEdgeToEnd(), ElementBase::getElementDimensions(), Solenoid::getElementDimensions(), BeamlineGeometry::getElementLength(), RFCavity::getElementLength(), Corrector::initialise(), ConstantEFieldCavity::initialise(), Drift::initialise(), Laser::initialise(), Multipole::initialise(), Solenoid::initialise(), ElementBase::isInside(), Monitor::isInside(), Multipole::isInside(), ElementBase::isInsideTransverse(), and TEST_F().
getElementPosition()
double ElementBase::getElementPosition () const inline inherited
Definition at line 555 of file ElementBase.h.
References ElementBase::elemedgeSet_m, ElementBase::elementPosition_m, and ElementBase::getName().
getEntrance()
double ElementBase::getEntrance () const inline virtual inherited
Get entrance position.
Reimplemented in TBeamline< T >.
Definition at line 410 of file ElementBase.h.
References BGeometryBase::getEntrance(), and ElementBase::getGeometry().
Referenced by BeamlineGeometry::getEntrance().
getEntranceFrame()
Euclid3D ElementBase::getEntranceFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 430 of file ElementBase.h.
References BGeometryBase::getEntranceFrame(), and ElementBase::getGeometry().
Referenced by BeamlineGeometry::getEntranceFrame().
getEntrancePatch()
Euclid3D ElementBase::getEntrancePatch () const inline virtual inherited
Get patch.
Definition at line 438 of file ElementBase.h.
References BGeometryBase::getEntrancePatch(), and ElementBase::getGeometry().
getExit()
double ElementBase::getExit () const inline virtual inherited
Get exit position.
Reimplemented in TBeamline< T >.
Definition at line 414 of file ElementBase.h.
References BGeometryBase::getExit(), and ElementBase::getGeometry().
Referenced by BeamlineGeometry::getExit().
getExitFrame()
Euclid3D ElementBase::getExitFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 434 of file ElementBase.h.
References BGeometryBase::getExitFrame(), and ElementBase::getGeometry().
Referenced by BeamlineGeometry::getExitFrame().
getExitPatch()
Euclid3D ElementBase::getExitPatch () const inline virtual inherited
Get patch.
Definition at line 442 of file ElementBase.h.
References BGeometryBase::getExitPatch(), and ElementBase::getGeometry().
getField() [1/2]
const EMField & VariableRFCavity::getField () const override virtual
Not implemented.
Implements Component.
Definition at line 108 of file VariableRFCavity.cpp.
getField() [2/2]
EMField & VariableRFCavity::getField () override virtual
Not implemented.
Implements Component.
Definition at line 104 of file VariableRFCavity.cpp.
Referenced by TEST_F().
getFlagDeleteOnTransverseExit()
bool ElementBase::getFlagDeleteOnTransverseExit () const inline inherited
Definition at line 576 of file ElementBase.h.
References ElementBase::deleteOnTransverseExit_m.
Referenced by ConstantEFieldCavity::apply(), Multipole::apply(), Corrector::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), RFCavity::apply(), Solenoid::apply(), and TravelingWave::apply().
getFrequency()
virtual double VariableRFCavity::getFrequency (const double time) const inline virtual
Get the frequency at a given time
Parameters
time the time at which the frequency is calculated
Returns
the RF cavity frequency.
Definition at line 140 of file VariableRFCavity.h.
References frequencyTD_m.
Referenced by TEST_F().
getFrequencyModel()
std::shared_ptr< AbstractTimeDependence > VariableRFCavity::getFrequencyModel () const virtual
Returns
shared_ptr to the frequency
Definition at line 82 of file VariableRFCavity.cpp.
References frequencyTD_m.
Referenced by TEST_F(), TEST_F(), and TestVariableRFCavity::testNull().
getGeometry() [1/2]
const StraightGeometry & VariableRFCavity::getGeometry () const override virtual
Returns
the cavity geometry
Implements ElementBase.
Definition at line 102 of file VariableRFCavity.cpp.
References geometry.
getGeometry() [2/2]
StraightGeometry & VariableRFCavity::getGeometry () override virtual
Set the cavity geometry
Implements ElementBase.
Definition at line 100 of file VariableRFCavity.cpp.
References geometry.
Referenced by TEST_F().
getHeight()
virtual double VariableRFCavity::getHeight () const inline virtual
Returns
the full height of the cavity
Definition at line 151 of file VariableRFCavity.h.
References halfHeight_m.
Referenced by TEST_F().
getLength()
virtual double VariableRFCavity::getLength () const inline virtual
Returns
the length of the cavity
Definition at line 155 of file VariableRFCavity.h.
References length_m.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TestVariableRFCavity::testNull().
getMisalignment() [1/2]
CoordinateSystemTrafo ElementBase::getMisalignment () const inline inherited
Definition at line 515 of file ElementBase.h.
References ElementBase::misalignment_m.
getMisalignment() [2/2]
void ElementBase::getMisalignment (double & x, double & y, double & s) const inherited
getName()
const std::string & ElementBase::getName () const virtual inherited
Get element name.
Definition at line 133 of file ElementBase.cpp.
References ElementBase::elementID.
Referenced by Ring::appendElement(), Probe::doGoOffline(), PlaceRep::enter(), ElementBase::getElementPosition(), RFCavity::getMomentaKick(), ElementBase::getOutputFN(), CavityAutophaser::getPhaseAtMaxEnergy(), Selector::handleElement(), Ring::initialise(), RFCavity::initialise(), Solenoid::initialise(), PlaceRep::leave(), operator=(), Sequence::print(), TEST_F(), Component::trackBunch(), Component::trackMap(), Sequence::updateList(), ParallelTracker::updateRFElement(), and Replacer::visitFlaggedElmPtr().
getOrigin()
double ElementBase::getOrigin () const inline virtual inherited
Get origin position.
Reimplemented in TBeamline< T >.
Definition at line 406 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getOrigin().
Referenced by BeamlineGeometry::getOrigin().
getOutputFN()
std::string ElementBase::getOutputFN () const inherited
Get output filename.
Definition at line 145 of file ElementBase.cpp.
References ElementBase::getName(), and ElementBase::outputfn_m.
Referenced by Probe::doInitialise(), PluginElement::initialise(), and Monitor::initialise().
getParticleMatterInteraction()
ParticleMatterInteractionHandler * ElementBase::getParticleMatterInteraction () const inline virtual inherited
Definition at line 466 of file ElementBase.h.
References ElementBase::parmatint_m.
getPhase()
virtual double VariableRFCavity::getPhase (const double time) const inline virtual
Get the phase at a given time
Parameters
time the time at which the phase is calculated
Returns
the RF cavity phase.
Definition at line 148 of file VariableRFCavity.h.
References phaseTD_m.
Referenced by TEST_F().
getPhaseModel()
std::shared_ptr< AbstractTimeDependence > VariableRFCavity::getPhaseModel () const virtual
Returns
shared_ptr to the phase time dependence
Definition at line 78 of file VariableRFCavity.cpp.
References phaseTD_m.
Referenced by TEST_F(), TEST_F(), and TestVariableRFCavity::testNull().
getPotential()
virtual bool Component::getPotential (const Vector_t< double, 3 > & , const double & , Vector_t< double, 3 > & , double &) inline virtual inherited
Calculate the four-potential at some position relative to the component.
Parameters
R position in the local coordinate system of the component
t time
A filled with the calculated magnetic vector potential
phi filled with the calculated electric potential Note that any existing values in A and phi may be overwritten by this method.
Returns
true if particle is outside the field map, else false Default for component is to return false and make no change to A and phi
Definition at line 164 of file Component.h.
getRequiredNumberOfTimeSteps()
int ElementBase::getRequiredNumberOfTimeSteps () const inline virtual inherited
Reimplemented in Drift, Laser, Marker, and Monitor.
Definition at line 568 of file ElementBase.h.
getRotationAboutZ()
double ElementBase::getRotationAboutZ () const inline inherited
Definition at line 542 of file ElementBase.h.
References ElementBase::rotationZAxis_m.
getTotalTransform()
Euclid3D ElementBase::getTotalTransform () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 422 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getTotalTransform().
Referenced by BeamlineGeometry::getTotalTransform().
getTransform() [1/2]
Euclid3D ElementBase::getTransform (double fromS, double toS) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 418 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getTransform().
Referenced by BeamlineGeometry::getTransform(), TBeamline< T >::getTransform(), and BeamlineGeometry::getTransform().
getTransform() [2/2]
Euclid3D ElementBase::getTransform (double s) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 426 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getTransform().
getType()
ElementType Component::getType () const virtual inherited
Get element type std::string.
Implements ElementBase.
Reimplemented in Corrector, ConstantEFieldCavity, Drift, Laser, Marker, Monitor, Multipole, Probe, RFCavity, Solenoid, and TravelingWave.
Definition at line 75 of file Component.cpp.
References ANY.
Referenced by ParallelTracker::visitComponent().
getTypeString() [1/2]
std::string ElementBase::getTypeString () const inline inherited
Definition at line 546 of file ElementBase.h.
References ElementBase::getType(), and ElementBase::getTypeString().
Referenced by ElementBase::getTypeString().
getTypeString() [2/2]
std::string ElementBase::getTypeString (ElementType type) static inherited
Definition at line 201 of file ElementBase.cpp.
References ElementBase::elementTypeToString_s.
getWake()
WakeFunction * ElementBase::getWake () const inline virtual inherited
return the attached wake object if there is any
Definition at line 450 of file ElementBase.h.
References ElementBase::wake_m.
getWidth()
virtual double VariableRFCavity::getWidth () const inline virtual
Returns
the full width of the cavity
Definition at line 153 of file VariableRFCavity.h.
References halfWidth_m.
Referenced by TEST_F().
goOffline()
void Component::goOffline () virtual inherited
Reimplemented in PluginElement, Monitor, RFCavity, Solenoid, and TravelingWave.
Definition at line 67 of file Component.cpp.
References Component::online_m.
goOnline()
void Component::goOnline (const double & kineticEnergy) virtual inherited
Reimplemented in Corrector, Monitor, RFCavity, Solenoid, and TravelingWave.
Definition at line 63 of file Component.cpp.
References Component::online_m.
Referenced by PluginElement::initialise().
hasAttribute()
bool ElementBase::hasAttribute (const std::string & aKey) const virtual inherited
Test for existence of an attribute.
Definition at line 166 of file ElementBase.cpp.
References ElementBase::getConstChannel().
hasBoundaryGeometry()
bool ElementBase::hasBoundaryGeometry () const inline virtual inherited
Definition at line 462 of file ElementBase.h.
References ElementBase::bgeometry_m.
hasParticleMatterInteraction()
bool ElementBase::hasParticleMatterInteraction () const inline virtual inherited
Definition at line 470 of file ElementBase.h.
References ElementBase::parmatint_m.
hasWake()
bool ElementBase::hasWake () const inline virtual inherited
Definition at line 454 of file ElementBase.h.
References ElementBase::wake_m.
initialise()
void VariableRFCavity::initialise (PartBunch_t * bunch, double & startField, double & endField) override virtual
Initialise ready for tracking
Just sets RefPartBunch_m
Implements Component.
Definition at line 161 of file VariableRFCavity.cpp.
References Component::RefPartBunch_m.
initialiseTimeDependencies()
void VariableRFCavity::initialiseTimeDependencies () const
Lookup the time dependencies and update.
Throws if the named time dependencies can't be found. Also throws if the width or height is < 1 nm
Definition at line 175 of file VariableRFCavity.cpp.
References amplitudeName_m, amplitudeTD_m, frequencyName_m, frequencyTD_m, AbstractTimeDependence::getTimeDependence(), halfHeight_m, halfWidth_m, phaseName_m, and phaseTD_m.
Referenced by accept().
initNull()
void VariableRFCavity::initNull () protected
Definition at line 64 of file VariableRFCavity.cpp.
References amplitudeName_m, frequencyName_m, halfHeight_m, halfWidth_m, length_m, phaseName_m, and Component::RefPartBunch_m.
Referenced by VariableRFCavity(), VariableRFCavity(), and VariableRFCavity().
isElementPositionSet()
bool ElementBase::isElementPositionSet () const inline inherited
Definition at line 564 of file ElementBase.h.
References ElementBase::elemedgeSet_m.
isInside()
bool ElementBase::isInside (const Vector_t< double, 3 > & r) const inline virtual inherited
Reimplemented in Monitor, Multipole, RFCavity, Solenoid, and TravelingWave.
Definition at line 506 of file ElementBase.h.
References ElementBase::getElementLength(), and ElementBase::isInsideTransverse().
isInsideTransverse()
bool ElementBase::isInsideTransverse (const Vector_t< double, 3 > & r) const protected inherited
Definition at line 246 of file ElementBase.cpp.
References ElementBase::aperture_m, CONIC_ELLIPTICAL, CONIC_RECTANGULAR, ELLIPTICAL, ElementBase::getEdgeToBegin(), ElementBase::getElementLength(), RECTANGULAR, and CoordinateSystemTrafo::transformTo().
Referenced by ConstantEFieldCavity::apply(), Multipole::apply(), Component::apply(), Corrector::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), Component::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), ElementBase::isInside(), Monitor::isInside(), Multipole::isInside(), RFCavity::isInside(), Solenoid::isInside(), and TravelingWave::isInside().
isPositioned()
bool ElementBase::isPositioned () const inline inherited
Definition at line 527 of file ElementBase.h.
References ElementBase::positionIsFixed.
isSharable()
bool ElementBase::isSharable () const inline inherited
Test if the element can be shared.
Definition at line 446 of file ElementBase.h.
References ElementBase::shareFlag.
Referenced by ElementBase::copyStructure(), and Sequence::updateList().
makeSharable()
void ElementBase::makeSharable () virtual inherited
Set sharable flag.
Reimplemented in TBeamline< T >.
Definition at line 213 of file ElementBase.cpp.
References ElementBase::shareFlag.
Referenced by OpalMarker::OpalMarker().
Online()
bool Component::Online () virtual inherited
Definition at line 71 of file Component.cpp.
References Component::online_m.
operator=()
VariableRFCavity & VariableRFCavity::operator= (const VariableRFCavity & rhs)
Assignment operator; performs deepcopy on time-dependence models
Definition at line 38 of file VariableRFCavity.cpp.
References amplitudeName_m, amplitudeTD_m, frequencyName_m, frequencyTD_m, ElementBase::getName(), halfHeight_m, halfWidth_m, length_m, phaseName_m, phaseTD_m, setAmplitudeModel(), setFrequencyModel(), setLength(), ElementBase::setName(), and setPhaseModel().
releasePosition()
void ElementBase::releasePosition () inline inherited
Definition at line 519 of file ElementBase.h.
References ElementBase::positionIsFixed.
removeAttribute()
void ElementBase::removeAttribute (const std::string & aKey) virtual inherited
Remove an existing attribute.
Definition at line 177 of file ElementBase.cpp.
References AttributeSet::removeAttribute(), and ElementBase::userAttribs.
setActionRange()
void ElementBase::setActionRange (const std::queue< std::pair< double, double > > & range) inline inherited
Definition at line 531 of file ElementBase.h.
References ElementBase::actionRange_m, and ElementBase::elementEdge_m.
setAmplitudeModel()
void VariableRFCavity::setAmplitudeModel (std::shared_ptr< AbstractTimeDependence > amplitude_td) virtual
Set the amplitude (field gradient) time dependence
Definition at line 86 of file VariableRFCavity.cpp.
References amplitudeTD_m.
Referenced by operator=(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
setAmplitudeName()
virtual void VariableRFCavity::setAmplitudeName (const std::string & amplitude) inline virtual
Set the amplitude time dependence name
The name is used to find the amplitude model at accept time
Definition at line 181 of file VariableRFCavity.h.
References amplitudeName_m.
Referenced by TEST_F().
setAperture()
void ElementBase::setAperture (const ApertureType & type, const std::vector< double > & args) inline inherited
Definition at line 497 of file ElementBase.h.
References ElementBase::aperture_m.
Referenced by Component::Component(), TEST_F(), TEST_F(), TEST_F(), and OpalElement::update().
setAttribute()
void ElementBase::setAttribute (const std::string & aKey, double val) virtual inherited
Set value of an attribute.
Definition at line 181 of file ElementBase.cpp.
References ElementBase::getChannel(), and Channel::isSettable().
Referenced by ElementBase::update(), and OpalElement::updateUnknown().
setBoundaryGeometry()
void ElementBase::setBoundaryGeometry (BoundaryGeometry * geo) virtual inherited
attach a boundary geometry field to the element
Definition at line 229 of file ElementBase.cpp.
References ElementBase::bgeometry_m.
setCSTrafoGlobal2Local()
void ElementBase::setCSTrafoGlobal2Local (const CoordinateSystemTrafo & ori) inline inherited
Definition at line 474 of file ElementBase.h.
References ElementBase::csTrafoGlobal2Local_m, and ElementBase::positionIsFixed.
Referenced by OpalElement::update().
setCurrentSCoordinate()
void ElementBase::setCurrentSCoordinate (double s) inherited
Definition at line 237 of file ElementBase.cpp.
References ElementBase::actionRange_m, and ElementBase::elementEdge_m.
setDesignEnergy()
void Component::setDesignEnergy (const double & energy, bool changeable = true) inline virtual inherited
Reimplemented in Corrector, and RFCavity.
Definition at line 272 of file Component.h.
setElementLength()
void ElementBase::setElementLength (double length) inline virtual inherited
Set design length.
Reimplemented in MultipoleT, and ConstantEFieldCavityRep.
Definition at line 402 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::setElementLength().
Referenced by RFCavity::initialise(), Solenoid::initialise(), TravelingWave::initialise(), MultipoleT::setElementLength(), SequenceMember::setLength(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), OpalCavity::update(), OpalMonitor::update(), OpalMultipole::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalSolenoid::update(), and OpalTravelingWave::update().
setElementPosition()
void ElementBase::setElementPosition (double elemedge) inline inherited
Access to ELEMEDGE attribute.
Definition at line 550 of file ElementBase.h.
References ElementBase::elemedgeSet_m, and ElementBase::elementPosition_m.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and OpalElement::update().
setExitFaceSlope()
void Component::setExitFaceSlope (const double & m) inline inherited
Definition at line 268 of file Component.h.
References Component::exit_face_slope_m.
setFlagDeleteOnTransverseExit()
void ElementBase::setFlagDeleteOnTransverseExit (bool flag = true) inline inherited
Definition at line 572 of file ElementBase.h.
References ElementBase::deleteOnTransverseExit_m.
Referenced by OpalElement::update().
setFrequencyModel()
void VariableRFCavity::setFrequencyModel (std::shared_ptr< AbstractTimeDependence > frequency_td) virtual
Set the frequency time dependence
Definition at line 95 of file VariableRFCavity.cpp.
References frequencyTD_m.
Referenced by operator=(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
setFrequencyName()
virtual void VariableRFCavity::setFrequencyName (const std::string & frequency) inline virtual
Set the frequency time dependence name
The name is used to find the frequency model at accept time
Definition at line 193 of file VariableRFCavity.h.
References frequencyName_m.
Referenced by TEST_F().
setHeight()
virtual void VariableRFCavity::setHeight (const double fullHeight) inline virtual
Set the full height of the cavity
Definition at line 157 of file VariableRFCavity.h.
References halfHeight_m.
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
setLength()
void VariableRFCavity::setLength (double length) virtual
Set the length of the cavity
Definition at line 191 of file VariableRFCavity.cpp.
References geometry, length_m, and StraightGeometry::setElementLength().
Referenced by operator=(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
setMisalignment()
void ElementBase::setMisalignment (const CoordinateSystemTrafo & cst) inline inherited
Definition at line 511 of file ElementBase.h.
References ElementBase::misalignment_m.
Referenced by OpalElement::update().
setName()
void ElementBase::setName (const std::string & name) virtual inherited
Set element name.
Definition at line 137 of file ElementBase.cpp.
References ElementBase::elementID.
Referenced by Sequence::insertDrifts(), and operator=().
setOutputFN()
void ElementBase::setOutputFN (std::string fn) inherited
Set output filename.
Definition at line 141 of file ElementBase.cpp.
References ElementBase::outputfn_m.
Referenced by OpalMonitor::update(), and OpalProbe::update().
setParticleMatterInteraction()
void ElementBase::setParticleMatterInteraction (ParticleMatterInteractionHandler * spys) virtual inherited
Definition at line 233 of file ElementBase.cpp.
References ElementBase::parmatint_m.
setPhaseModel()
void VariableRFCavity::setPhaseModel (std::shared_ptr< AbstractTimeDependence > phase_td) virtual
Set the phase time dependence
Definition at line 91 of file VariableRFCavity.cpp.
References phaseTD_m.
Referenced by operator=(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
setPhaseName()
virtual void VariableRFCavity::setPhaseName (const std::string & phase) inline virtual
Set the phase time dependence name
The name is used to find the phase model at accept time
Definition at line 187 of file VariableRFCavity.h.
References phaseName_m.
Referenced by TEST_F().
setRotationAboutZ()
void ElementBase::setRotationAboutZ (double rotation) inline inherited
Set rotation about z axis in bend frame.
Definition at line 538 of file ElementBase.h.
References ElementBase::rotationZAxis_m.
Referenced by OpalElement::update().
setWake()
void ElementBase::setWake (WakeFunction * wf) virtual inherited
attach a wake field to the element
Definition at line 225 of file ElementBase.cpp.
References ElementBase::wake_m.
setWidth()
virtual void VariableRFCavity::setWidth (const double fullWidth) inline virtual
Set the full width of the cavity
Definition at line 159 of file VariableRFCavity.h.
References halfWidth_m.
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
trackBunch()
void Component::trackBunch (PartBunch_t & bunch, const PartData & , bool revBeam, bool revTrack) const virtual inherited
Track a borrowed particle bunch through a non-standard component.
The default implementation throws a LogicalError.
Parameters
bunch Particle bunch to track. The component does not take ownership.
Definition at line 45 of file Component.cpp.
References ElementBase::getName().
Referenced by Tracker::visitComponent().
trackMap()
void Component::trackMap (FVps< double, 6 > & map, const PartData & , bool revBeam, bool revTrack) const virtual inherited
Track a map.
Definition at line 54 of file Component.cpp.
References ElementBase::getName().
update()
bool ElementBase::update (const AttributeSet & set) inherited
Update element.
Definition at line 217 of file ElementBase.cpp.
References AttributeSet::begin(), AttributeSet::end(), and ElementBase::setAttribute().
Member Data Documentation
actionRange_m
std::queue<std::pair<double, double> > ElementBase::actionRange_m private inherited
Definition at line 384 of file ElementBase.h.
Referenced by ElementBase::setActionRange(), and ElementBase::setCurrentSCoordinate().
amplitudeName_m
std::string VariableRFCavity::amplitudeName_m protected
Definition at line 218 of file VariableRFCavity.h.
Referenced by initialiseTimeDependencies(), initNull(), operator=(), and setAmplitudeName().
amplitudeTD_m
std::shared_ptr<AbstractTimeDependence> VariableRFCavity::amplitudeTD_m mutable protected
Definition at line 215 of file VariableRFCavity.h.
Referenced by apply(), apply(), apply(), getAmplitude(), getAmplitudeModel(), initialiseTimeDependencies(), operator=(), and setAmplitudeModel().
aperture_m
std::pair<ApertureType, std::vector<double> > ElementBase::aperture_m protected inherited
Definition at line 355 of file ElementBase.h.
Referenced by ElementBase::getAperture(), ElementBase::getBoundingBoxInLabCoords(), ElementBase::isInsideTransverse(), and ElementBase::setAperture().
bgeometry_m
BoundaryGeometry* ElementBase::bgeometry_m private inherited
Definition at line 375 of file ElementBase.h.
Referenced by ElementBase::getBoundaryGeometry(), ElementBase::hasBoundaryGeometry(), and ElementBase::setBoundaryGeometry().
csTrafoGlobal2Local_m
CoordinateSystemTrafo ElementBase::csTrafoGlobal2Local_m protected inherited
Definition at line 352 of file ElementBase.h.
Referenced by ElementBase::getBoundingBoxInLabCoords(), ElementBase::getCSTrafoGlobal2Local(), and ElementBase::setCSTrafoGlobal2Local().
defaultAperture_m
const std::vector< double > Component::defaultAperture_m static protected inherited
Initial value:
=
    std::vector<double>({1e6, 1e6, 1.0})
Definition at line 233 of file Component.h.
Referenced by Component::Component().
deleteOnTransverseExit_m
bool ElementBase::deleteOnTransverseExit_m = true private inherited
Definition at line 388 of file ElementBase.h.
Referenced by ElementBase::getFlagDeleteOnTransverseExit(), and ElementBase::setFlagDeleteOnTransverseExit().
elemedgeSet_m
bool ElementBase::elemedgeSet_m private inherited
Definition at line 382 of file ElementBase.h.
Referenced by ElementBase::getElementPosition(), ElementBase::isElementPositionSet(), and ElementBase::setElementPosition().
elementEdge_m
double ElementBase::elementEdge_m protected inherited
Definition at line 357 of file ElementBase.h.
Referenced by ElementBase::setActionRange(), and ElementBase::setCurrentSCoordinate().
elementID
std::string ElementBase::elementID private inherited
Definition at line 366 of file ElementBase.h.
Referenced by ElementBase::getName(), and ElementBase::setName().
elementPosition_m
double ElementBase::elementPosition_m private inherited
ELEMEDGE attribute.
Definition at line 381 of file ElementBase.h.
Referenced by ElementBase::getElementPosition(), and ElementBase::setElementPosition().
elementTypeToString_s
const std::map< ElementType, std::string > ElementBase::elementTypeToString_s static private inherited
Initial value:
= {
    {ElementType::ANY, "Any"},
    {ElementType::BEAMLINE, "Beamline"},
    {ElementType::DRIFT, "Drift"},
    {ElementType::LASER, "Laser"},
    {ElementType::MARKER, "Marker"},
    {ElementType::MULTIPOLE, "Multipole"},
    {ElementType::RFCAVITY, "RFCavity"},
    {ElementType::TRAVELINGWAVE, "TravelingWave"},
    {ElementType::SBEND, "SBEND"},
    {ElementType::RBEND, "RBEND"},
    {ElementType::RBEND3D, "RBEND3D"},
    {ElementType::RING, "Ring"},
    {ElementType::SOURCE, "SOURCE"},
    {ElementType::SOLENOID, "SOLENOID"},
    {ElementType::PROBE, "Probe"},
    {ElementType::VACUUM, "Vacuum"},
    {ElementType::CONSTANTEFIELDCAVITY, "ConstantEFieldCavity"}}
Definition at line 69 of file ElementBase.h.
Referenced by ElementBase::getTypeString().
exit_face_slope_m
double Component::exit_face_slope_m protected inherited
Definition at line 234 of file Component.h.
Referenced by Component::setExitFaceSlope().
frequencyName_m
std::string VariableRFCavity::frequencyName_m protected
Definition at line 219 of file VariableRFCavity.h.
Referenced by initialiseTimeDependencies(), initNull(), operator=(), and setFrequencyName().
frequencyTD_m
std::shared_ptr<AbstractTimeDependence> VariableRFCavity::frequencyTD_m mutable protected
Definition at line 216 of file VariableRFCavity.h.
Referenced by apply(), apply(), apply(), getFrequency(), getFrequencyModel(), initialiseTimeDependencies(), operator=(), and setFrequencyModel().
geometry
StraightGeometry VariableRFCavity::geometry protected
The cavity's geometry.
Definition at line 225 of file VariableRFCavity.h.
Referenced by getGeometry(), getGeometry(), and setLength().
halfHeight_m
double VariableRFCavity::halfHeight_m protected
Definition at line 221 of file VariableRFCavity.h.
Referenced by apply(), apply(), apply(), getHeight(), initialiseTimeDependencies(), initNull(), operator=(), and setHeight().
halfWidth_m
double VariableRFCavity::halfWidth_m protected
Definition at line 220 of file VariableRFCavity.h.
Referenced by apply(), apply(), apply(), getWidth(), initialiseTimeDependencies(), initNull(), operator=(), and setWidth().
length_m
double VariableRFCavity::length_m protected
Definition at line 222 of file VariableRFCavity.h.
Referenced by getLength(), initNull(), operator=(), and setLength().
misalignment_m
CoordinateSystemTrafo ElementBase::misalignment_m protected inherited
Definition at line 353 of file ElementBase.h.
Referenced by ElementBase::getMisalignment(), and ElementBase::setMisalignment().
online_m
bool Component::online_m protected inherited
Definition at line 238 of file Component.h.
Referenced by Probe::doGoOffline(), PluginElement::finalise(), Multipole::finalise(), Ring::finalise(), Component::goOffline(), PluginElement::goOffline(), RFCavity::goOffline(), Solenoid::goOffline(), Component::goOnline(), Corrector::goOnline(), Monitor::goOnline(), RFCavity::goOnline(), Solenoid::goOnline(), TravelingWave::goOnline(), Ring::initialise(), Multipole::initialise(), Component::Online(), and PluginElement::~PluginElement().
outputfn_m
std::string ElementBase::outputfn_m private inherited
The name of the outputfile
Definition at line 386 of file ElementBase.h.
Referenced by ElementBase::getOutputFN(), and ElementBase::setOutputFN().
parmatint_m
ParticleMatterInteractionHandler* ElementBase::parmatint_m private inherited
Definition at line 377 of file ElementBase.h.
Referenced by ElementBase::getParticleMatterInteraction(), ElementBase::hasParticleMatterInteraction(), and ElementBase::setParticleMatterInteraction().
phaseName_m
std::string VariableRFCavity::phaseName_m protected
Definition at line 217 of file VariableRFCavity.h.
Referenced by initialiseTimeDependencies(), initNull(), operator=(), and setPhaseName().
phaseTD_m
std::shared_ptr<AbstractTimeDependence> VariableRFCavity::phaseTD_m mutable protected
Definition at line 214 of file VariableRFCavity.h.
Referenced by apply(), apply(), apply(), getPhase(), getPhaseModel(), initialiseTimeDependencies(), operator=(), and setPhaseModel().
positionIsFixed
bool ElementBase::positionIsFixed private inherited
Definition at line 379 of file ElementBase.h.
Referenced by ElementBase::fixPosition(), ElementBase::isPositioned(), ElementBase::releasePosition(), and ElementBase::setCSTrafoGlobal2Local().
RefPartBunch_m
PartBunch_t* Component::RefPartBunch_m protected inherited
Definition at line 237 of file Component.h.
Referenced by Corrector::apply(), VerticalFFAMagnet::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), MultipoleT::apply(), RFCavity::apply(), ScalingFFAMagnet::apply(), Solenoid::apply(), TravelingWave::apply(), apply(), Ring::apply(), MultipoleT::apply(), RFCavity::apply(), TravelingWave::apply(), apply(), Corrector::apply(), VerticalFFAMagnet::finalise(), MultipoleT::finalise(), ScalingFFAMagnet::finalise(), finalise(), Corrector::goOnline(), PluginElement::initialise(), Corrector::initialise(), VerticalFFAMagnet::initialise(), ConstantEFieldCavity::initialise(), Drift::initialise(), Laser::initialise(), Marker::initialise(), Monitor::initialise(), Multipole::initialise(), MultipoleT::initialise(), RFCavity::initialise(), ScalingFFAMagnet::initialise(), Solenoid::initialise(), TravelingWave::initialise(), initialise(), RFCavity::initialise(), initNull(), Multipole::isFocusing(), MultipoleT::MultipoleT(), ScalingFFAMagnet::ScalingFFAMagnet(), Corrector::setDesignEnergy(), Ring::setRefPartBunch(), RFCavity::trackOnAxisParticle(), and VerticalFFAMagnet::VerticalFFAMagnet().
rotationZAxis_m
double ElementBase::rotationZAxis_m protected inherited
Definition at line 359 of file ElementBase.h.
Referenced by ElementBase::getRotationAboutZ(), and ElementBase::setRotationAboutZ().
shareFlag
bool ElementBase::shareFlag mutable protected inherited
Definition at line 350 of file ElementBase.h.
Referenced by Beamline::Beamline(), Beamline::Beamline(), Beamline::Beamline(), ElementBase::isSharable(), and ElementBase::makeSharable().
userAttribs
AttributeSet ElementBase::userAttribs private inherited
Definition at line 371 of file ElementBase.h.
Referenced by ElementBase::getChannel(), and ElementBase::removeAttribute().
wake_m
WakeFunction* ElementBase::wake_m private inherited
Definition at line 373 of file ElementBase.h.
Referenced by ElementBase::getWake(), ElementBase::hasWake(), and ElementBase::setWake().
The documentation for this class was generated from the following files:
VariableRFCavity.h
VariableRFCavity.cpp