OPALX (Object Oriented Parallel Accelerator Library for Exascal): Beam Class Reference
Beam Class Reference
#include <Beam.h>
Public Member Functions
Beam ()
Exemplar constructor.
virtual ~Beam ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual Beam * clone (const std::string &name)
Make clone.
virtual void execute ()
Check the BEAM data.
size_t getNumAlloc () const
Return the allocation size (macroparticles) for this beam.
const PartData & getReference () const
Return the embedded OPALX PartData.
double getCurrent () const
Return the beam current in A (legacy; no longer used in OPALX)
double getBunchCharge () const
Return the bunch charge in C.
double getCharge () const
Return the charge number in elementary charge.
double getFrequency () const
Return the beam frequency in MHz.
std::string getParticleName () const
Return Particle's name.
bool isPhoton () const
True if this beam is configured as a photon beam.
double getMass () const
Return Particle's rest mass in GeV.
double getMomentum () const
double getChargePerParticle () const
Charge per macro particle in C.
double getMassPerParticle () const
Mass per macro particle in GeV/c^2.
std::string getEmissionSourceListName () const
std::vector< std::string > getGlobalProcessNames () const
Return the configured global process names for this beam.
std::string getDaughterBeamName () const
Return the name of the daughter beam (for decay products), or empty if not set.
bool hasExplicitEnergy () const
True if PC, ENERGY, or GAMMA was explicitly provided by the user.
virtual void update ()
Update the BEAM data.
void print (std::ostream &os) const
Print the object.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Static Public Member Functions
static Beam * find (const std::string &name)
Find named BEAM.
Public Attributes
std::vector< Attribute > itsAttr
The object attributes.
Protected Attributes
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Private Member Functions
Beam (const Beam &)
void operator= (const Beam &)
Beam (const std::string &name, Beam *parent)
Private Attributes
PartData reference
Object * itsParent
std::string itsName
std::string itsHelp
int occurrence
double timeStamp
std::set< Invalidator * > references
bool sharedFlag
Static Private Attributes
static const double energy_scale
Detailed Description
Definition at line 32 of file Beam.h.
Constructor & Destructor Documentation
Beam() [1/3]
Beam::Beam ()
Exemplar constructor.
Definition at line 59 of file Beam.cpp.
References Beam(), Object::builtin, clone(), OpalData::define(), Definition::Definition(), OpalData::getInstance(), Object::itsAttr, Attributes::makePredefinedString(), Attributes::makeReal(), Attributes::makeString(), Attributes::makeUpperCaseStringArray(), reference, Object::registerOwnership(), SIZE, AttributeHandler::STATEMENT, and update().
Referenced by Beam(), Beam(), Beam(), canReplaceBy(), clone(), find(), getReference(), and operator=().
~Beam()
Beam::~Beam () virtual
Definition at line 116 of file Beam.cpp.
Beam() [2/3]
Beam::Beam (const Beam &) private
References Beam().
Beam() [3/3]
Beam::Beam (const std::string & name, Beam * parent) private
Definition at line 113 of file Beam.cpp.
References Beam(), Definition::Definition(), and reference.
Member Function Documentation
canReplaceBy()
bool Beam::canReplaceBy (Object * object) virtual
Test if replacement is allowed.
Reimplemented from Object.
Definition at line 118 of file Beam.cpp.
References Beam(), and Object::Object().
clear()
void Object::clear () inherited
Clear the occurrence counter.
Definition at line 285 of file Object.cpp.
References occurrence.
clone()
Beam * Beam::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 123 of file Beam.cpp.
References Beam().
Referenced by Beam().
copyAttributes()
void Object::copyAttributes (const Object & source) inherited
Copy attributes from another object.
Definition at line 50 of file Object.cpp.
References itsAttr, and Object().
Referenced by LineTemplate::makeInstance(), and SequenceTemplate::makeInstance().
execute()
void Beam::execute () virtual
Check the BEAM data.
Reimplemented from Object.
Definition at line 125 of file Beam.cpp.
References getEmissionSourceListName(), getGlobalProcessNames(), getParticleName(), Attributes::getReal(), Object::itsAttr, and update().
find()
Beam * Beam::find (const std::string & name) static
Find named BEAM.
Definition at line 223 of file Beam.cpp.
References Beam(), OpalData::find(), and OpalData::getInstance().
Referenced by TrackCmd::execute(), TrackRun::execute(), OpalBeamlinePlacementTest::makeBunch(), OrbitThreaderTest::makeBunch(), SolenoidPlacementTest::makeBunch(), TestMultipoleTCurvedConstRadius::makeBunch(), TestMultipoleTStraight::makeBunch(), TestVariableRFCavity::makeBunch(), TrackRun::print(), and TEST_F().
findAttribute() [1/2]
Attribute * Object::findAttribute (const std::string & name) virtual inherited
Find an attribute by name.
Definition at line 56 of file Object.cpp.
References itsAttr.
Referenced by OpalElement::getParticleMatterInteraction(), OpalElement::getTypeName(), OpalElement::getWakeF(), Line::parse(), parse(), OpalElement::parse(), OpalParser::parseAssign(), SequenceParser::parsePosition(), TrackRun::print(), and TEST().
findAttribute() [2/2]
const Attribute * Object::findAttribute (const std::string & name) const virtual inherited
Find an attribute by name.
Definition at line 63 of file Object.cpp.
References itsAttr.
getBaseObject()
const Object * Object::getBaseObject () const inherited
Return the object's base type object.
Definition at line 260 of file Object.cpp.
References itsParent, and Object().
getBunchCharge()
double Beam::getBunchCharge () const
Return the bunch charge in C.
Definition at line 251 of file Beam.cpp.
References Attributes::getReal(), and Object::itsAttr.
Referenced by getChargePerParticle().
getCategory()
const std::string Definition::getCategory () const virtual inherited
Return the object category as a string.
Implements Object.
Definition at line 26 of file Definition.cpp.
getCharge()
double Beam::getCharge () const
Return the charge number in elementary charge.
Definition at line 253 of file Beam.cpp.
References Attributes::getReal(), and Object::itsAttr.
Referenced by TrackRun::execute(), getChargePerParticle(), getMassPerParticle(), and update().
getChargePerParticle()
double Beam::getChargePerParticle () const
Charge per macro particle in C.
Definition at line 267 of file Beam.cpp.
References getBunchCharge(), getCharge(), and getNumAlloc().
Referenced by TrackRun::execute(), getMassPerParticle(), and TrackRun::print().
getCurrent()
double Beam::getCurrent () const
Return the beam current in A (legacy; no longer used in OPALX)
Definition at line 249 of file Beam.cpp.
References Attributes::getReal(), and Object::itsAttr.
getDaughterBeamName()
std::string Beam::getDaughterBeamName () const
Return the name of the daughter beam (for decay products), or empty if not set.
Definition at line 219 of file Beam.cpp.
References Attributes::getString(), and Object::itsAttr.
getEmissionSourceListName()
std::string Beam::getEmissionSourceListName () const
Return the name of the EMISSIONSOURCELIST linked to this beam. Throws if SOURCES is not set.
Definition at line 199 of file Beam.cpp.
References Attributes::getString(), and Object::itsAttr.
Referenced by execute(), and TrackRun::execute().
getFrequency()
double Beam::getFrequency () const
Return the beam frequency in MHz.
Definition at line 263 of file Beam.cpp.
References Attributes::getReal(), and Object::itsAttr.
getGlobalProcessNames()
std::vector< std::string > Beam::getGlobalProcessNames () const
Return the configured global process names for this beam.
Definition at line 215 of file Beam.cpp.
References Attributes::getStringArray(), and Object::itsAttr.
Referenced by execute().
getMass()
double Beam::getMass () const
Return Particle's rest mass in GeV.
Definition at line 255 of file Beam.cpp.
References Attributes::getReal(), and Object::itsAttr.
Referenced by getMassPerParticle(), TrackRun::setupDistributionsAndSamplers(), and update().
getMassPerParticle()
double Beam::getMassPerParticle () const
Mass per macro particle in GeV/c^2.
Definition at line 271 of file Beam.cpp.
References getCharge(), getChargePerParticle(), getMass(), and Physics::q_e.
Referenced by TrackRun::execute(), and TrackRun::print().
getMomentum()
double Beam::getMomentum () const
Definition at line 257 of file Beam.cpp.
References reference.
Referenced by TrackRun::setupDistributionsAndSamplers().
getNumAlloc()
size_t Beam::getNumAlloc () const
Return the allocation size (macroparticles) for this beam.
Definition at line 233 of file Beam.cpp.
References Attributes::getReal(), and Object::itsAttr.
Referenced by TrackRun::computeTotalAllocationForBunch(), and getChargePerParticle().
getOpalName()
const std::string & Object::getOpalName () const inherited
Return object name.
Definition at line 267 of file Object.cpp.
References itsName.
Referenced by Macro::clone(), OpalVariableRFCavity::clone(), OpalData::create(), OpalData::define(), Sequence::findDriftLength(), ValueDefinition::getBool(), ValueDefinition::getBoolComponent(), ValueDefinition::getReal(), ValueDefinition::getRealComponent(), ValueDefinition::getString(), ValueDefinition::getStringComponent(), LineTemplate::makeInstance(), makeInstance(), SequenceTemplate::makeInstance(), parse(), SequenceParser::parsePosition(), Beam::print(), BoolConstant::print(), Line::print(), print(), OpalElement::print(), OpalFilter::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), Sequence::print(), StringConstant::print(), TrackRun::print(), BinningCmd::printInfo(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), registerOwnership(), OpalElement::registerOwnership(), Line::replace(), Sequence::replace(), PartBunch< T, Dim >::setBins(), TEST(), TEST(), TEST(), TEST_F(), Beam::update(), BoundaryGeometry::update(), OpalFilter::update(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), and OpalSplineTimeDependence::update().
getParent()
Object * Object::getParent () const inherited
Return parent pointer.
Definition at line 269 of file Object.cpp.
References itsParent, and Object().
Referenced by OpalData::erase(), print(), OpalElement::print(), registerOwnership(), and OpalElement::registerOwnership().
getParticleName()
std::string Beam::getParticleName () const
Return Particle's name.
Definition at line 259 of file Beam.cpp.
References Attributes::getString(), and Object::itsAttr.
Referenced by execute(), isPhoton(), and update().
getReference()
const PartData & Beam::getReference () const
Return the embedded OPALX PartData.
Definition at line 243 of file Beam.cpp.
References Beam(), reference, and update().
Referenced by TrackCmd::execute().
hasExplicitEnergy()
bool Beam::hasExplicitEnergy () const
True if PC, ENERGY, or GAMMA was explicitly provided by the user.
Definition at line 265 of file Beam.cpp.
References Object::itsAttr.
Referenced by TrackRun::setupDistributionsAndSamplers().
increment()
int Object::increment () inherited
Increment and return the occurrence counter.
Definition at line 287 of file Object.cpp.
References occurrence.
Referenced by Line::parse(), and Sequence::storeLine().
isBuiltin()
bool Object::isBuiltin () const inherited
True, if [b]this[/b] is a built-in object.
Definition at line 243 of file Object.cpp.
References builtin.
Referenced by OpalData::define(), and OpalData::getVariableNames().
isDirty()
bool Object::isDirty () const inherited
True, if the [b]modified[/b] flag is set.
Definition at line 254 of file Object.cpp.
References modified.
isFlagged()
bool Object::isFlagged () const inherited
True, if [b]this[/b] is flagged by setFlag(true).
Definition at line 258 of file Object.cpp.
References flagged.
isPhoton()
bool Beam::isPhoton () const
True if this beam is configured as a photon beam.
Definition at line 261 of file Beam.cpp.
References getParticleName(), and Object::itsAttr.
Referenced by update().
isShared()
bool Object::isShared () const virtual inherited
Shared flag.
Definition at line 245 of file Object.cpp.
References sharedFlag.
Referenced by Sequence::print().
isTreeMember()
bool Object::isTreeMember (const Object * subTree) const inherited
Test for tree membership.
Definition at line 271 of file Object.cpp.
References Object().
Referenced by Selector::handleElement(), and OpalParser::parseAssign().
makeInstance()
Object * Object::makeInstance (const std::string & name, Statement & , const Parser *) virtual inherited
Macro handler function.
Reimplemented in LineTemplate, MacroCmd, and SequenceTemplate.
Definition at line 76 of file Object.cpp.
References getOpalName(), and Object().
Referenced by OpalParser::parseDefine(), and OpalParser::parseMacro().
makeTemplate()
Object * Object::makeTemplate (const std::string & name, TokenStream & , Statement &) virtual inherited
Macro handler function.
Reimplemented in Line, LineTemplate, MacroCmd, Sequence, and SequenceTemplate.
Definition at line 71 of file Object.cpp.
References Object().
Referenced by OpalParser::parseMacro().
occurrenceCount()
int Object::occurrenceCount () inherited
Return the occurrence counter.
Definition at line 289 of file Object.cpp.
References occurrence.
operator=()
void Beam::operator= (const Beam &) private
References Beam().
parse()
void Object::parse (Statement & stat) virtual inherited
Parse the object.
Reimplemented in Call, Echo, EmissionSourceList, Help, Line, OpalElement, PSystem, Sequence, System, Title, and Value.
Definition at line 82 of file Object.cpp.
References Statement::delimiter(), findAttribute(), getOpalName(), Expressions::parseDelimiter(), Expressions::parseRealConst(), and Expressions::parseString().
Referenced by Sequence::parse(), OpalParser::parseAction(), OpalParser::parseDefine(), and SequenceTemplate::parseTemplate().
parseShortcut()
void Object::parseShortcut (Statement & stat, bool eval = true) virtual inherited
Parser for single-attribute commands.
Definition at line 113 of file Object.cpp.
Referenced by Call::parse(), Echo::parse(), Help::parse(), PSystem::parse(), System::parse(), Title::parse(), and Value::parse().
print()
void Beam::print (std::ostream & msg) const virtual
Print the object.
Reimplemented from Object.
Definition at line 327 of file Beam.cpp.
References Object::getOpalName(), Attributes::getReal(), Attributes::getString(), Object::itsAttr, and reference.
Referenced by operator<<().
printHelp()
void Object::printHelp (std::ostream &) const virtual inherited
Print help.
Definition at line 179 of file Object.cpp.
References gmsg, itsAttr, and itsHelp.
Referenced by Help::execute(), and main().
printValue()
void Object::printValue (std::ostream & os) const inline virtual inherited
Reimplemented in BoolConstant, RealConstant, RealVariable, RealVector, and StringConstant.
Definition at line 270 of file Object.h.
References print().
registerOwnership()
void Object::registerOwnership (const AttributeHandler::OwnerType & itsClass) const inherited
Definition at line 169 of file Object.cpp.
References AttributeHandler::addAttributeOwner(), getOpalName(), getParent(), and itsAttr.
Referenced by Beam::Beam(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), Call::Call(), Distribution::Distribution(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), EmissionSourceList::EmissionSourceList(), Help::Help(), Line::Line(), OpalFilter::OpalFilter(), Option::Option(), PSystem::PSystem(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVector::RealVector(), Select::Select(), Sequence::Sequence(), StringConstant::StringConstant(), System::System(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), and Value::Value().
registerReference()
void Object::registerReference (Invalidator * a) inherited
Register a reference to this object.
Definition at line 165 of file Object.cpp.
References references.
replace()
void Object::replace (Object * oldObject, Object * newObject) virtual inherited
Replace references.
Reimplemented in Line, and Sequence.
Definition at line 235 of file Object.cpp.
References Object().
setDirty()
void Object::setDirty (bool dirty) inherited
Set/reset the [b]modified[/b] flag.
Definition at line 249 of file Object.cpp.
References modified.
Referenced by OpalData::define(), OpalData::makeDirty(), and RealVariable::RealVariable().
setFlag()
void Object::setFlag (bool flag) inherited
Flag/unflag this object, e. g. to control output of objects for.
Definition at line 256 of file Object.cpp.
References flagged.
setOpalName()
void Object::setOpalName (const std::string & name) inherited
Set object name.
Definition at line 281 of file Object.cpp.
References itsName.
Referenced by TEST(), TEST(), TEST(), Beam::update(), BoundaryGeometry::update(), and OpalFilter::update().
setParent()
void Object::setParent (Object * parent) inherited
Set parent object.
Definition at line 283 of file Object.cpp.
References itsParent, and Object().
Referenced by OpalData::erase().
setShared()
void Object::setShared (bool flag) virtual inherited
Set/reset shared flag.
Reimplemented in Element.
Definition at line 247 of file Object.cpp.
References sharedFlag.
Referenced by OpalParser::parseDefine(), and Element::setShared().
shouldTrace()
bool Definition::shouldTrace () const virtual inherited
Trace flag.
Implements Object.
Definition at line 28 of file Definition.cpp.
shouldUpdate()
bool Definition::shouldUpdate () const virtual inherited
Update flag.
Implements Object.
Definition at line 30 of file Definition.cpp.
unregisterReference()
void Object::unregisterReference (Invalidator * a) inherited
Unegister a reference to this object.
Definition at line 167 of file Object.cpp.
References references.
update()
void Beam::update () virtual
Update the BEAM data.
Reimplemented from Object.
Definition at line 275 of file Beam.cpp.
References getCharge(), getMass(), Object::getOpalName(), ParticleProperties::getParticleCharge(), ParticleProperties::getParticleMass(), getParticleName(), ParticleProperties::getParticleType(), Attributes::getReal(), Units::GeV2eV, isPhoton(), Object::itsAttr, Physics::m_p, reference, Object::setOpalName(), and Attributes::setReal().
Referenced by Beam(), execute(), and getReference().
Member Data Documentation
builtin
bool Object::builtin protected inherited
Built-in flag.
Definition at line 226 of file Object.h.
Referenced by Beam::Beam(), BoundaryGeometry::BoundaryGeometry(), isBuiltin(), Object(), Object(), OpalFilter::OpalFilter(), OpalMarker::OpalMarker(), RealConstant::RealConstant(), StringConstant::StringConstant(), and Table::~Table().
energy_scale
const double Beam::energy_scale static private
Definition at line 118 of file Beam.h.
flagged
bool Object::flagged protected inherited
Object flag.
Definition at line 235 of file Object.h.
Referenced by isFlagged(), Object(), Object(), and setFlag().
itsAttr
std::vector<Attribute> Object::itsAttr inherited
The object attributes.
Definition at line 210 of file Object.h.
Referenced by Beam::Beam(), BinningCmd::BinningCmd(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), BoundaryGeometry::BoundaryGeometry(), DumpEMFields::buildGrid(), Call::Call(), FieldSolverCmd::constructBCHandler(), copyAttributes(), Distribution::Distribution(), BinningCmd::dumpBinsToFile(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), Beam::execute(), Call::execute(), Echo::execute(), Help::execute(), Option::execute(), PSystem::execute(), Select::execute(), System::execute(), Title::execute(), TrackCmd::execute(), TrackRun::execute(), Value::execute(), FieldSolverCmd::FieldSolverCmd(), findAttribute(), findAttribute(), BoundaryGeometry::getA(), OpalElement::getApert(), BoundaryGeometry::getB(), BinningCmd::getBinningAlpha(), BinningCmd::getBinningBeta(), FieldSolverCmd::getBinsName(), BoolConstant::getBool(), FieldSolverCmd::getBoxIncr(), Beam::getBunchCharge(), BoundaryGeometry::getC(), Beam::getCharge(), Beam::getCurrent(), Beam::getDaughterBeamName(), BinningCmd::getDesiredWidth(), EmissionSource::getDistributionName(), FieldSolverCmd::getDomDec(), TrackCmd::getDT(), TrackCmd::getDTAU(), TrackCmd::getDTSCINIT(), BinningCmd::getDumpBinsFileName(), BinningCmd::getDumpBinsFrequency(), EmissionSource::getEmissionModel(), Beam::getEmissionSourceListName(), BoundaryGeometry::getFilename(), Distribution::getFilename(), Beam::getFrequency(), Beam::getGlobalProcessNames(), BoundaryGeometry::getL1(), BoundaryGeometry::getL2(), BoundaryGeometry::getLength(), Line::getLength(), OpalElement::getLength(), Sequence::getLength(), Beam::getMass(), BinningCmd::getMaxBins(), TrackCmd::getMaxSteps(), Beam::getNumAlloc(), FieldSolverCmd::getNX(), FieldSolverCmd::getNY(), FieldSolverCmd::getNZ(), EmissionSource::getP0(), BinningCmd::getParameter(), Beam::getParticleName(), EmissionSource::getR0(), RealConstant::getReal(), RealVariable::getReal(), RealVector::getRealComponent(), Sequence::getReference(), BoundaryGeometry::getS(), EmissionSource::getShiftedGreensFunction(), TrackCmd::getStepsPerTurn(), StringConstant::getString(), EmissionSource::getT0(), TrackCmd::getT0(), BinningCmd::getTablePrintFrequency(), TrackCmd::getTimeIntegrator(), BoundaryGeometry::getTopology(), FieldSolverCmd::getType(), EmissionSource::getZerofaceMaxSteps(), EmissionSource::getZeroFacePlaneDumpFrequency(), EmissionSource::getZeroFaceR0Z(), TrackCmd::getZStart(), TrackCmd::getZStop(), Beam::hasExplicitEnergy(), Help::Help(), BoundaryGeometry::initialize(), OpalFilter::initOpalFilter(), Beam::isPhoton(), Line::Line(), Object(), Object(), OpalBend::OpalBend(), OpalCavity::OpalCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalDrift::OpalDrift(), OpalElement::OpalElement(), OpalFilter::OpalFilter(), OpalLaser::OpalLaser(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalPolynomialTimeDependence::OpalPolynomialTimeDependence(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalRingDefinition::OpalRingDefinition(), OpalSinusoidalTimeDependence::OpalSinusoidalTimeDependence(), OpalSolenoid::OpalSolenoid(), OpalSplineTimeDependence::OpalSplineTimeDependence(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), Option::Option(), Option::Option(), Line::parse(), Sequence::parse(), DumpEMFields::parseCoordinateSystem(), Beam::print(), BoolConstant::print(), DumpEMFields::print(), print(), OpalFilter::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), Sequence::print(), StringConstant::print(), printHelp(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), BoolConstant::printValue(), RealConstant::printValue(), RealVariable::printValue(), RealVector::printValue(), StringConstant::printValue(), PSystem::PSystem(), RealConstant::RealConstant(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVariable::RealVariable(), RealVector::RealVector(), registerOwnership(), OpalElement::registerOwnership(), Select::Select(), Select::select(), Sequence::Sequence(), Distribution::setAttributes(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCX(), OrbitThreaderTest::TestableFieldSolverCmd::setBCX(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCX(), TestMultipoleT::TestableFieldSolverCmd::setBCX(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCX(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCX(), TestVariableRFCavity::TestableFieldSolverCmd::setBCX(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCY(), OrbitThreaderTest::TestableFieldSolverCmd::setBCY(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCY(), TestMultipoleT::TestableFieldSolverCmd::setBCY(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCY(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCY(), TestVariableRFCavity::TestableFieldSolverCmd::setBCY(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCZ(), OrbitThreaderTest::TestableFieldSolverCmd::setBCZ(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCZ(), TestMultipoleT::TestableFieldSolverCmd::setBCZ(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCZ(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCZ(), TestVariableRFCavity::TestableFieldSolverCmd::setBCZ(), TestableBinningCmd::setBinningAlpha(), TestableBinningCmd::setBinningBeta(), TestableBinningCmd::setDesiredWidth(), Distribution::setDistParametersFlatTop(), Distribution::setDistParametersMultiVariateGauss(), Distribution::setDistType(), TestableBinningCmd::setDumpBinsFile(), TestableBinningCmd::setDumpBinsFreq(), TestableBinningCmd::setMaxBins(), FieldSolverCmd::setNX(), FieldSolverCmd::setNY(), FieldSolverCmd::setNZ(), TestableBinningCmd::setParameterString(), TrackRun::setRunMethod(), Distribution::setSigmaP_m(), Distribution::setSigmaR_m(), TestableBinningCmd::setTablePrintFrequency(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setType(), OrbitThreaderTest::TestableFieldSolverCmd::setType(), SolenoidPlacementTest::TestableFieldSolverCmd::setType(), TestMultipoleT::TestableFieldSolverCmd::setType(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setType(), TestMultipoleTStraight::TestableFieldSolverCmd::setType(), TestVariableRFCavity::TestableFieldSolverCmd::setType(), TrackRun::setupBoundaryGeometry(), StringConstant::StringConstant(), StringConstant::StringConstant(), System::System(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), Beam::update(), BinningCmd::update(), FieldSolverCmd::update(), OpalCavity::update(), OpalConstantEFieldCavity::update(), OpalDrift::update(), OpalElement::update(), OpalLaser::update(), OpalMonitor::update(), OpalMultipole::update(), OpalMultipoleT::update(), OpalPolynomialTimeDependence::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalRBend::update(), OpalRingDefinition::update(), OpalSBend::update(), OpalSinusoidalTimeDependence::update(), OpalSolenoid::update(), OpalSplineTimeDependence::update(), OpalTravelingWave::update(), OpalVacuum::update(), OpalVariableRFCavity::update(), OpalVerticalFFAMagnet::update(), Option::update(), OpalElement::updateUnknown(), Value::Value(), ValueDefinition::value(), and ValueDefinition::value().
itsHelp
std::string Object::itsHelp private inherited
Definition at line 250 of file Object.h.
Referenced by Object(), Object(), and printHelp().
itsName
std::string Object::itsName private inherited
Definition at line 247 of file Object.h.
Referenced by getOpalName(), Object(), Object(), and setOpalName().
itsParent
Object* Object::itsParent private inherited
Definition at line 244 of file Object.h.
Referenced by getBaseObject(), getParent(), Object(), Object(), and setParent().
modified
bool Object::modified protected inherited
Dirty flag.
Definition at line 231 of file Object.h.
Referenced by isDirty(), Object(), Object(), and setDirty().
occurrence
int Object::occurrence private inherited
Definition at line 253 of file Object.h.
Referenced by clear(), increment(), Object(), Object(), and occurrenceCount().
reference
PartData Beam::reference private
Definition at line 115 of file Beam.h.
Referenced by Beam(), Beam(), getMomentum(), getReference(), print(), and update().
references
std::set<Invalidator*> Object::references private inherited
Definition at line 260 of file Object.h.
Referenced by registerReference(), unregisterReference(), and ~Object().
sharedFlag
bool Object::sharedFlag private inherited
Definition at line 263 of file Object.h.
Referenced by isShared(), Object(), Object(), and setShared().
timeStamp
double Object::timeStamp private inherited
Definition at line 256 of file Object.h.
The documentation for this class was generated from the following files:
Beam.h
Beam.cpp