OPALX (Object Oriented Parallel Accelerator Library for Exascal): DummyBeamline Class Reference
DummyBeamline Class Reference final
Public Member Functions
DummyBeamline ()
ElementType getType () const override
Get element type std::string.
BGeometryBase & getGeometry () override
Get geometry.
const BGeometryBase & getGeometry () const override
Get geometry.
void accept (BeamlineVisitor &visitor) const override
Apply visitor.
ElementBase * clone () const override
Return clone.
void iterate (BeamlineVisitor &, bool) const override
Apply visitor to all elements of the line.
virtual Vector_t< double, 3 > getOrigin3D () const
virtual Quaternion getInitialDirection () const
virtual bool getRelativeFlag () const
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t< double, 3 > &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Static Public Member Functions
static std::string getTypeString (ElementType type)
Protected Member Functions
bool isInsideTransverse (const Vector_t< double, 3 > &r) const
Protected Attributes
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Private Attributes
NullGeometry geometry_
std::string elementID
AttributeSet userAttribs
WakeFunction * wake_m
BoundaryGeometry * bgeometry_m
ParticleMatterInteractionHandler * parmatint_m
bool positionIsFixed
std::queue< std::pair< double, double > > actionRange_m
std::string outputfn_m
bool deleteOnTransverseExit_m = true
double elementPosition_m
ELEMEDGE attribute.
bool elemedgeSet_m
Static Private Attributes
static const std::map< ElementType, std::string > elementTypeToString_s
Detailed Description
Definition at line 159 of file TestSolenoid.cpp.
Constructor & Destructor Documentation
DummyBeamline()
DummyBeamline::DummyBeamline () inline
Definition at line 161 of file TestSolenoid.cpp.
Referenced by clone().
Member Function Documentation
accept()
void DummyBeamline::accept (BeamlineVisitor & visitor) const inline override virtual
Apply visitor.
Implements ElementBase.
Definition at line 166 of file TestSolenoid.cpp.
References BeamlineVisitor::visitBeamline().
clone()
ElementBase * DummyBeamline::clone () const inline override virtual
Return clone.
Implements ElementBase.
Definition at line 167 of file TestSolenoid.cpp.
References DummyBeamline().
copyStructure()
ElementBase * ElementBase::copyStructure () virtual inherited
Make a structural copy.
Reimplemented in TBeamline< T >.
Definition at line 205 of file ElementBase.cpp.
References ElementBase::clone(), and ElementBase::isSharable().
Referenced by Sequence::copy(), Line::parse(), SequenceParser::parseMember(), and Replacer::visitFlaggedElmPtr().
fixPosition()
void ElementBase::fixPosition () inline inherited
Definition at line 523 of file ElementBase.h.
References ElementBase::positionIsFixed.
Referenced by OpalElement::update().
getAperture()
std::pair< ApertureType, std::vector< double > > ElementBase::getAperture () const inline inherited
Definition at line 502 of file ElementBase.h.
References ElementBase::aperture_m.
Referenced by MeshGenerator::add(), Solenoid::getSupportEnvelope(), and MeshGenerator::getTransverseSupport().
getArcLength()
double ElementBase::getArcLength () const inline virtual inherited
Get arc length.
Reimplemented in MarkerRep, and TBeamline< T >.
Definition at line 394 of file ElementBase.h.
References BGeometryBase::getArcLength(), and ElementBase::getGeometry().
Referenced by BeamlineGeometry::getArcLength(), and TBeamline< T >::getTransform().
getAttribute()
double ElementBase::getAttribute (const std::string & aKey) const virtual inherited
Get attribute value.
Definition at line 154 of file ElementBase.cpp.
References ElementBase::getConstChannel().
getBoundaryGeometry()
BoundaryGeometry * ElementBase::getBoundaryGeometry () const inline virtual inherited
return the attached boundary geometrt object if there is any
Definition at line 458 of file ElementBase.h.
References ElementBase::bgeometry_m.
getBoundingBoxInLabCoords()
BoundingBox ElementBase::getBoundingBoxInLabCoords () const virtual inherited
Definition at line 273 of file ElementBase.cpp.
References ElementBase::aperture_m, ElementBase::csTrafoGlobal2Local_m, BoundingBox::getBoundingBox(), ElementBase::getEdgeToBegin(), ElementBase::getEdgeToEnd(), and CoordinateSystemTrafo::transformFrom().
getChannel()
Channel * ElementBase::getChannel (const std::string & aKey, bool create = false) virtual inherited
Construct a read/write channel.
Reimplemented in LaserRep, DriftRep, MonitorRep, MultipoleRep, ProbeRep, RFCavityRep, SolenoidRep, TravelingWaveRep, and ConstantEFieldCavityRep.
Definition at line 191 of file ElementBase.cpp.
References AttributeSet::getChannel(), and ElementBase::userAttribs.
Referenced by LaserRep::getChannel(), DriftRep::getChannel(), MonitorRep::getChannel(), MultipoleRep::getChannel(), ProbeRep::getChannel(), RFCavityRep::getChannel(), SolenoidRep::getChannel(), TravelingWaveRep::getChannel(), ConstantEFieldCavityRep::getChannel(), ElementBase::getConstChannel(), and ElementBase::setAttribute().
getConstChannel()
const ConstChannel * ElementBase::getConstChannel (const std::string & aKey) const virtual inherited
Construct a read-only channel.
Definition at line 195 of file ElementBase.cpp.
References ElementBase::getChannel().
Referenced by ElementBase::getAttribute(), and ElementBase::hasAttribute().
getCSTrafoGlobal2Local()
CoordinateSystemTrafo ElementBase::getCSTrafoGlobal2Local () const inline inherited
Definition at line 481 of file ElementBase.h.
References ElementBase::csTrafoGlobal2Local_m.
Referenced by MeshGenerator::add().
getEdgeToBegin()
CoordinateSystemTrafo ElementBase::getEdgeToBegin () const inline virtual inherited
Reimplemented in RFCavity, Solenoid, and TravelingWave.
Definition at line 485 of file ElementBase.h.
Referenced by ElementBase::getBoundingBoxInLabCoords(), and ElementBase::isInsideTransverse().
getEdgeToEnd()
CoordinateSystemTrafo ElementBase::getEdgeToEnd () const inline virtual inherited
Reimplemented in RFCavity, Solenoid, and TravelingWave.
Definition at line 490 of file ElementBase.h.
References ElementBase::getElementLength().
Referenced by ElementBase::getBoundingBoxInLabCoords().
getElementDimensions()
virtual void ElementBase::getElementDimensions (double & begin, double & end) const inline virtual inherited
Reimplemented in RFCavity, TravelingWave, and Solenoid.
Definition at line 161 of file ElementBase.h.
References ElementBase::getElementLength().
Referenced by MeshGenerator::add().
getElementLength()
double ElementBase::getElementLength () const inline virtual inherited
Get design length.
Reimplemented in MarkerRep, TBeamline< T >, RFCavity, and TestTravelingWave.
Definition at line 398 of file ElementBase.h.
References BGeometryBase::getElementLength(), and ElementBase::getGeometry().
Referenced by MeshGenerator::add(), ConstantEFieldCavity::apply(), Multipole::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), Component::apply(), Corrector::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), Solenoid::apply(), Component::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), Solenoid::applyToReferenceParticle(), Corrector::getDimensions(), ConstantEFieldCavity::getDimensions(), Drift::getDimensions(), Laser::getDimensions(), Multipole::getDimensions(), Solenoid::getDimensions(), ElementBase::getEdgeToEnd(), Solenoid::getEdgeToEnd(), ElementBase::getElementDimensions(), Solenoid::getElementDimensions(), BeamlineGeometry::getElementLength(), RFCavity::getElementLength(), Corrector::initialise(), ConstantEFieldCavity::initialise(), Drift::initialise(), Laser::initialise(), Multipole::initialise(), Solenoid::initialise(), ElementBase::isInside(), Monitor::isInside(), Multipole::isInside(), ElementBase::isInsideTransverse(), and TEST_F().
getElementPosition()
double ElementBase::getElementPosition () const inline inherited
Definition at line 555 of file ElementBase.h.
References ElementBase::elemedgeSet_m, ElementBase::elementPosition_m, and ElementBase::getName().
getEntrance()
double ElementBase::getEntrance () const inline virtual inherited
Get entrance position.
Reimplemented in TBeamline< T >.
Definition at line 410 of file ElementBase.h.
References BGeometryBase::getEntrance(), and ElementBase::getGeometry().
Referenced by BeamlineGeometry::getEntrance().
getEntranceFrame()
Euclid3D ElementBase::getEntranceFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 430 of file ElementBase.h.
References BGeometryBase::getEntranceFrame(), and ElementBase::getGeometry().
Referenced by BeamlineGeometry::getEntranceFrame().
getEntrancePatch()
Euclid3D ElementBase::getEntrancePatch () const inline virtual inherited
Get patch.
Definition at line 438 of file ElementBase.h.
References BGeometryBase::getEntrancePatch(), and ElementBase::getGeometry().
getExit()
double ElementBase::getExit () const inline virtual inherited
Get exit position.
Reimplemented in TBeamline< T >.
Definition at line 414 of file ElementBase.h.
References BGeometryBase::getExit(), and ElementBase::getGeometry().
Referenced by BeamlineGeometry::getExit().
getExitFrame()
Euclid3D ElementBase::getExitFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 434 of file ElementBase.h.
References BGeometryBase::getExitFrame(), and ElementBase::getGeometry().
Referenced by BeamlineGeometry::getExitFrame().
getExitPatch()
Euclid3D ElementBase::getExitPatch () const inline virtual inherited
Get patch.
Definition at line 442 of file ElementBase.h.
References BGeometryBase::getExitPatch(), and ElementBase::getGeometry().
getFlagDeleteOnTransverseExit()
bool ElementBase::getFlagDeleteOnTransverseExit () const inline inherited
Definition at line 576 of file ElementBase.h.
References ElementBase::deleteOnTransverseExit_m.
Referenced by ConstantEFieldCavity::apply(), Multipole::apply(), Corrector::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), RFCavity::apply(), Solenoid::apply(), and TravelingWave::apply().
getGeometry() [1/2]
const BGeometryBase & DummyBeamline::getGeometry () const inline override virtual
Get geometry.
Implements ElementBase.
Definition at line 165 of file TestSolenoid.cpp.
References geometry_.
getGeometry() [2/2]
BGeometryBase & DummyBeamline::getGeometry () inline override virtual
Get geometry.
Implements ElementBase.
Definition at line 164 of file TestSolenoid.cpp.
References geometry_.
getInitialDirection()
Quaternion Beamline::getInitialDirection () const virtual inherited
Reimplemented in TBeamline< T >.
Definition at line 53 of file Beamline.cpp.
getMisalignment() [1/2]
CoordinateSystemTrafo ElementBase::getMisalignment () const inline inherited
Definition at line 515 of file ElementBase.h.
References ElementBase::misalignment_m.
getMisalignment() [2/2]
void ElementBase::getMisalignment (double & x, double & y, double & s) const inherited
getName()
const std::string & ElementBase::getName () const virtual inherited
Get element name.
Definition at line 133 of file ElementBase.cpp.
References ElementBase::elementID.
Referenced by Ring::appendElement(), Probe::doGoOffline(), PlaceRep::enter(), ElementBase::getElementPosition(), RFCavity::getMomentaKick(), ElementBase::getOutputFN(), CavityAutophaser::getPhaseAtMaxEnergy(), Selector::handleElement(), Ring::initialise(), RFCavity::initialise(), Solenoid::initialise(), PlaceRep::leave(), VariableRFCavity::operator=(), Sequence::print(), TEST_F(), Component::trackBunch(), Component::trackMap(), Sequence::updateList(), ParallelTracker::updateRFElement(), and Replacer::visitFlaggedElmPtr().
getOrigin()
double ElementBase::getOrigin () const inline virtual inherited
Get origin position.
Reimplemented in TBeamline< T >.
Definition at line 406 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getOrigin().
Referenced by BeamlineGeometry::getOrigin().
getOrigin3D()
Vector_t< double, 3 > Beamline::getOrigin3D () const virtual inherited
Reimplemented in TBeamline< T >.
Definition at line 49 of file Beamline.cpp.
getOutputFN()
std::string ElementBase::getOutputFN () const inherited
Get output filename.
Definition at line 145 of file ElementBase.cpp.
References ElementBase::getName(), and ElementBase::outputfn_m.
Referenced by Probe::doInitialise(), PluginElement::initialise(), and Monitor::initialise().
getParticleMatterInteraction()
ParticleMatterInteractionHandler * ElementBase::getParticleMatterInteraction () const inline virtual inherited
Definition at line 466 of file ElementBase.h.
References ElementBase::parmatint_m.
getRelativeFlag()
bool Beamline::getRelativeFlag () const virtual inherited
Reimplemented in TBeamline< T >.
Definition at line 57 of file Beamline.cpp.
getRequiredNumberOfTimeSteps()
int ElementBase::getRequiredNumberOfTimeSteps () const inline virtual inherited
Reimplemented in Drift, Laser, Marker, and Monitor.
Definition at line 568 of file ElementBase.h.
getRotationAboutZ()
double ElementBase::getRotationAboutZ () const inline inherited
Definition at line 542 of file ElementBase.h.
References ElementBase::rotationZAxis_m.
getTotalTransform()
Euclid3D ElementBase::getTotalTransform () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 422 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getTotalTransform().
Referenced by BeamlineGeometry::getTotalTransform().
getTransform() [1/2]
Euclid3D ElementBase::getTransform (double fromS, double toS) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 418 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getTransform().
Referenced by BeamlineGeometry::getTransform(), TBeamline< T >::getTransform(), and BeamlineGeometry::getTransform().
getTransform() [2/2]
Euclid3D ElementBase::getTransform (double s) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 426 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getTransform().
getType()
ElementType DummyBeamline::getType () const inline override virtual
Get element type std::string.
Implements ElementBase.
Definition at line 163 of file TestSolenoid.cpp.
References BEAMLINE.
getTypeString() [1/2]
std::string ElementBase::getTypeString () const inline inherited
Definition at line 546 of file ElementBase.h.
References ElementBase::getType(), and ElementBase::getTypeString().
Referenced by ElementBase::getTypeString().
getTypeString() [2/2]
std::string ElementBase::getTypeString (ElementType type) static inherited
Definition at line 201 of file ElementBase.cpp.
References ElementBase::elementTypeToString_s.
getWake()
WakeFunction * ElementBase::getWake () const inline virtual inherited
return the attached wake object if there is any
Definition at line 450 of file ElementBase.h.
References ElementBase::wake_m.
hasAttribute()
bool ElementBase::hasAttribute (const std::string & aKey) const virtual inherited
Test for existence of an attribute.
Definition at line 166 of file ElementBase.cpp.
References ElementBase::getConstChannel().
hasBoundaryGeometry()
bool ElementBase::hasBoundaryGeometry () const inline virtual inherited
Definition at line 462 of file ElementBase.h.
References ElementBase::bgeometry_m.
hasParticleMatterInteraction()
bool ElementBase::hasParticleMatterInteraction () const inline virtual inherited
Definition at line 470 of file ElementBase.h.
References ElementBase::parmatint_m.
hasWake()
bool ElementBase::hasWake () const inline virtual inherited
Definition at line 454 of file ElementBase.h.
References ElementBase::wake_m.
isElementPositionSet()
bool ElementBase::isElementPositionSet () const inline inherited
Definition at line 564 of file ElementBase.h.
References ElementBase::elemedgeSet_m.
isInside()
bool ElementBase::isInside (const Vector_t< double, 3 > & r) const inline virtual inherited
Reimplemented in Monitor, Multipole, RFCavity, Solenoid, and TravelingWave.
Definition at line 506 of file ElementBase.h.
References ElementBase::getElementLength(), and ElementBase::isInsideTransverse().
isInsideTransverse()
bool ElementBase::isInsideTransverse (const Vector_t< double, 3 > & r) const protected inherited
Definition at line 246 of file ElementBase.cpp.
References ElementBase::aperture_m, CONIC_ELLIPTICAL, CONIC_RECTANGULAR, ELLIPTICAL, ElementBase::getEdgeToBegin(), ElementBase::getElementLength(), RECTANGULAR, and CoordinateSystemTrafo::transformTo().
Referenced by ConstantEFieldCavity::apply(), Multipole::apply(), Component::apply(), Corrector::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), Component::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), ElementBase::isInside(), Monitor::isInside(), Multipole::isInside(), RFCavity::isInside(), Solenoid::isInside(), and TravelingWave::isInside().
isPositioned()
bool ElementBase::isPositioned () const inline inherited
Definition at line 527 of file ElementBase.h.
References ElementBase::positionIsFixed.
isSharable()
bool ElementBase::isSharable () const inline inherited
Test if the element can be shared.
Definition at line 446 of file ElementBase.h.
References ElementBase::shareFlag.
Referenced by ElementBase::copyStructure(), and Sequence::updateList().
iterate()
void DummyBeamline::iterate (BeamlineVisitor & , bool reverse) const inline override virtual
Apply visitor to all elements of the line.
Implements Beamline.
Definition at line 168 of file TestSolenoid.cpp.
makeSharable()
void ElementBase::makeSharable () virtual inherited
Set sharable flag.
Reimplemented in TBeamline< T >.
Definition at line 213 of file ElementBase.cpp.
References ElementBase::shareFlag.
Referenced by OpalMarker::OpalMarker().
releasePosition()
void ElementBase::releasePosition () inline inherited
Definition at line 519 of file ElementBase.h.
References ElementBase::positionIsFixed.
removeAttribute()
void ElementBase::removeAttribute (const std::string & aKey) virtual inherited
Remove an existing attribute.
Definition at line 177 of file ElementBase.cpp.
References AttributeSet::removeAttribute(), and ElementBase::userAttribs.
setActionRange()
void ElementBase::setActionRange (const std::queue< std::pair< double, double > > & range) inline inherited
Definition at line 531 of file ElementBase.h.
References ElementBase::actionRange_m, and ElementBase::elementEdge_m.
setAperture()
void ElementBase::setAperture (const ApertureType & type, const std::vector< double > & args) inline inherited
Definition at line 497 of file ElementBase.h.
References ElementBase::aperture_m.
Referenced by Component::Component(), TEST_F(), TEST_F(), TEST_F(), and OpalElement::update().
setAttribute()
void ElementBase::setAttribute (const std::string & aKey, double val) virtual inherited
Set value of an attribute.
Definition at line 181 of file ElementBase.cpp.
References ElementBase::getChannel(), and Channel::isSettable().
Referenced by ElementBase::update(), and OpalElement::updateUnknown().
setBoundaryGeometry()
void ElementBase::setBoundaryGeometry (BoundaryGeometry * geo) virtual inherited
attach a boundary geometry field to the element
Definition at line 229 of file ElementBase.cpp.
References ElementBase::bgeometry_m.
setCSTrafoGlobal2Local()
void ElementBase::setCSTrafoGlobal2Local (const CoordinateSystemTrafo & ori) inline inherited
Definition at line 474 of file ElementBase.h.
References ElementBase::csTrafoGlobal2Local_m, and ElementBase::positionIsFixed.
Referenced by OpalElement::update().
setCurrentSCoordinate()
void ElementBase::setCurrentSCoordinate (double s) inherited
Definition at line 237 of file ElementBase.cpp.
References ElementBase::actionRange_m, and ElementBase::elementEdge_m.
setElementLength()
void ElementBase::setElementLength (double length) inline virtual inherited
Set design length.
Reimplemented in MultipoleT, and ConstantEFieldCavityRep.
Definition at line 402 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::setElementLength().
Referenced by RFCavity::initialise(), Solenoid::initialise(), TravelingWave::initialise(), MultipoleT::setElementLength(), SequenceMember::setLength(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), OpalCavity::update(), OpalMonitor::update(), OpalMultipole::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalSolenoid::update(), and OpalTravelingWave::update().
setElementPosition()
void ElementBase::setElementPosition (double elemedge) inline inherited
Access to ELEMEDGE attribute.
Definition at line 550 of file ElementBase.h.
References ElementBase::elemedgeSet_m, and ElementBase::elementPosition_m.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and OpalElement::update().
setFlagDeleteOnTransverseExit()
void ElementBase::setFlagDeleteOnTransverseExit (bool flag = true) inline inherited
Definition at line 572 of file ElementBase.h.
References ElementBase::deleteOnTransverseExit_m.
Referenced by OpalElement::update().
setMisalignment()
void ElementBase::setMisalignment (const CoordinateSystemTrafo & cst) inline inherited
Definition at line 511 of file ElementBase.h.
References ElementBase::misalignment_m.
Referenced by OpalElement::update().
setName()
void ElementBase::setName (const std::string & name) virtual inherited
Set element name.
Definition at line 137 of file ElementBase.cpp.
References ElementBase::elementID.
Referenced by Sequence::insertDrifts(), and VariableRFCavity::operator=().
setOutputFN()
void ElementBase::setOutputFN (std::string fn) inherited
Set output filename.
Definition at line 141 of file ElementBase.cpp.
References ElementBase::outputfn_m.
Referenced by OpalMonitor::update(), and OpalProbe::update().
setParticleMatterInteraction()
void ElementBase::setParticleMatterInteraction (ParticleMatterInteractionHandler * spys) virtual inherited
Definition at line 233 of file ElementBase.cpp.
References ElementBase::parmatint_m.
setRotationAboutZ()
void ElementBase::setRotationAboutZ (double rotation) inline inherited
Set rotation about z axis in bend frame.
Definition at line 538 of file ElementBase.h.
References ElementBase::rotationZAxis_m.
Referenced by OpalElement::update().
setWake()
void ElementBase::setWake (WakeFunction * wf) virtual inherited
attach a wake field to the element
Definition at line 225 of file ElementBase.cpp.
References ElementBase::wake_m.
update()
bool ElementBase::update (const AttributeSet & set) inherited
Update element.
Definition at line 217 of file ElementBase.cpp.
References AttributeSet::begin(), AttributeSet::end(), and ElementBase::setAttribute().
Member Data Documentation
actionRange_m
std::queue<std::pair<double, double> > ElementBase::actionRange_m private inherited
Definition at line 384 of file ElementBase.h.
Referenced by ElementBase::setActionRange(), and ElementBase::setCurrentSCoordinate().
aperture_m
std::pair<ApertureType, std::vector<double> > ElementBase::aperture_m protected inherited
Definition at line 355 of file ElementBase.h.
Referenced by ElementBase::getAperture(), ElementBase::getBoundingBoxInLabCoords(), ElementBase::isInsideTransverse(), and ElementBase::setAperture().
bgeometry_m
BoundaryGeometry* ElementBase::bgeometry_m private inherited
Definition at line 375 of file ElementBase.h.
Referenced by ElementBase::getBoundaryGeometry(), ElementBase::hasBoundaryGeometry(), and ElementBase::setBoundaryGeometry().
csTrafoGlobal2Local_m
CoordinateSystemTrafo ElementBase::csTrafoGlobal2Local_m protected inherited
Definition at line 352 of file ElementBase.h.
Referenced by ElementBase::getBoundingBoxInLabCoords(), ElementBase::getCSTrafoGlobal2Local(), and ElementBase::setCSTrafoGlobal2Local().
deleteOnTransverseExit_m
bool ElementBase::deleteOnTransverseExit_m = true private inherited
Definition at line 388 of file ElementBase.h.
Referenced by ElementBase::getFlagDeleteOnTransverseExit(), and ElementBase::setFlagDeleteOnTransverseExit().
elemedgeSet_m
bool ElementBase::elemedgeSet_m private inherited
Definition at line 382 of file ElementBase.h.
Referenced by ElementBase::getElementPosition(), ElementBase::isElementPositionSet(), and ElementBase::setElementPosition().
elementEdge_m
double ElementBase::elementEdge_m protected inherited
Definition at line 357 of file ElementBase.h.
Referenced by ElementBase::setActionRange(), and ElementBase::setCurrentSCoordinate().
elementID
std::string ElementBase::elementID private inherited
Definition at line 366 of file ElementBase.h.
Referenced by ElementBase::getName(), and ElementBase::setName().
elementPosition_m
double ElementBase::elementPosition_m private inherited
ELEMEDGE attribute.
Definition at line 381 of file ElementBase.h.
Referenced by ElementBase::getElementPosition(), and ElementBase::setElementPosition().
elementTypeToString_s
const std::map< ElementType, std::string > ElementBase::elementTypeToString_s static private inherited
Initial value:
= {
    {ElementType::ANY, "Any"},
    {ElementType::BEAMLINE, "Beamline"},
    {ElementType::DRIFT, "Drift"},
    {ElementType::LASER, "Laser"},
    {ElementType::MARKER, "Marker"},
    {ElementType::MULTIPOLE, "Multipole"},
    {ElementType::RFCAVITY, "RFCavity"},
    {ElementType::TRAVELINGWAVE, "TravelingWave"},
    {ElementType::SBEND, "SBEND"},
    {ElementType::RBEND, "RBEND"},
    {ElementType::RBEND3D, "RBEND3D"},
    {ElementType::RING, "Ring"},
    {ElementType::SOURCE, "SOURCE"},
    {ElementType::SOLENOID, "SOLENOID"},
    {ElementType::PROBE, "Probe"},
    {ElementType::VACUUM, "Vacuum"},
    {ElementType::CONSTANTEFIELDCAVITY, "ConstantEFieldCavity"}}
Definition at line 69 of file ElementBase.h.
Referenced by ElementBase::getTypeString().
geometry_
NullGeometry DummyBeamline::geometry_ private
Definition at line 171 of file TestSolenoid.cpp.
Referenced by getGeometry(), and getGeometry().
misalignment_m
CoordinateSystemTrafo ElementBase::misalignment_m protected inherited
Definition at line 353 of file ElementBase.h.
Referenced by ElementBase::getMisalignment(), and ElementBase::setMisalignment().
outputfn_m
std::string ElementBase::outputfn_m private inherited
The name of the outputfile
Definition at line 386 of file ElementBase.h.
Referenced by ElementBase::getOutputFN(), and ElementBase::setOutputFN().
parmatint_m
ParticleMatterInteractionHandler* ElementBase::parmatint_m private inherited
Definition at line 377 of file ElementBase.h.
Referenced by ElementBase::getParticleMatterInteraction(), ElementBase::hasParticleMatterInteraction(), and ElementBase::setParticleMatterInteraction().
positionIsFixed
bool ElementBase::positionIsFixed private inherited
Definition at line 379 of file ElementBase.h.
Referenced by ElementBase::fixPosition(), ElementBase::isPositioned(), ElementBase::releasePosition(), and ElementBase::setCSTrafoGlobal2Local().
rotationZAxis_m
double ElementBase::rotationZAxis_m protected inherited
Definition at line 359 of file ElementBase.h.
Referenced by ElementBase::getRotationAboutZ(), and ElementBase::setRotationAboutZ().
shareFlag
bool ElementBase::shareFlag mutable protected inherited
Definition at line 350 of file ElementBase.h.
Referenced by Beamline::Beamline(), Beamline::Beamline(), Beamline::Beamline(), ElementBase::isSharable(), and ElementBase::makeSharable().
userAttribs
AttributeSet ElementBase::userAttribs private inherited
Definition at line 371 of file ElementBase.h.
Referenced by ElementBase::getChannel(), and ElementBase::removeAttribute().
wake_m
WakeFunction* ElementBase::wake_m private inherited
Definition at line 373 of file ElementBase.h.
Referenced by ElementBase::getWake(), ElementBase::hasWake(), and ElementBase::setWake().
The documentation for this class was generated from the following file:
TestSolenoid.cpp