OPALX (Object Oriented Parallel Accelerator Library for Exascal): StraightGeometry Class Reference
StraightGeometry Class Reference
A geometry representing a straight line.
#include <StraightGeometry.h>
Public Member Functions
StraightGeometry (double length=0.0)
Constructor.
StraightGeometry (const StraightGeometry &right)
virtual ~StraightGeometry ()
const StraightGeometry & operator= (const StraightGeometry &right)
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
double getOrigin () const
Get origin.
double getEntrance () const
Get entrance.
double getExit () const
Get exit.
Euclid3D getTransform (double fromS, double toS) const
Get transform.
Euclid3D getTransform (double s) const
Get transform.
Euclid3D getTotalTransform () const
Get transform.
Euclid3D getEntranceFrame () const
Get transform.
Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
Private Attributes
double len
Detailed Description
A geometry representing a straight line.
Definition at line 34 of file StraightGeometry.h.
Constructor & Destructor Documentation
StraightGeometry() [1/2]
StraightGeometry::StraightGeometry (double length = 0.0) inline
Constructor.
Definition at line 107 of file StraightGeometry.h.
StraightGeometry() [2/2]
StraightGeometry::StraightGeometry (const StraightGeometry & right) inline
Definition at line 109 of file StraightGeometry.h.
~StraightGeometry()
StraightGeometry::~StraightGeometry () virtual
Definition at line 31 of file StraightGeometry.cpp.
Member Function Documentation
getArcLength()
double StraightGeometry::getArcLength () const virtual
Get arc length.
Implements BGeometryBase.
Reimplemented in RBendGeometry.
Definition at line 33 of file StraightGeometry.cpp.
References len.
getElementLength()
double StraightGeometry::getElementLength () const virtual
Get design length.
Implements BGeometryBase.
Definition at line 35 of file StraightGeometry.cpp.
References len.
Referenced by RBendGeometry::getArcLength(), RBendGeometry::getEntrancePatch(), RBendGeometry::getExitPatch(), Corrector::goOnline(), Corrector::setDesignEnergy(), and TEST_F().
getEntrance()
double StraightGeometry::getEntrance () const virtual
Get entrance.
Reimplemented from BGeometryBase.
Definition at line 48 of file StraightGeometry.cpp.
References len.
getEntranceFrame()
Euclid3D StraightGeometry::getEntranceFrame () const virtual
Get transform.
Reimplemented from BGeometryBase.
Definition at line 60 of file StraightGeometry.cpp.
References len, and Euclid3D::translation().
Referenced by RBendGeometry::getEntranceFrame().
getEntrancePatch()
Euclid3D BGeometryBase::getEntrancePatch () const virtual inherited
Get patch.
Reimplemented in RBendGeometry.
Definition at line 45 of file Geometry.cpp.
References Euclid3D::identity().
Referenced by ElementBase::getEntrancePatch().
getExit()
double StraightGeometry::getExit () const virtual
Get exit.
Reimplemented from BGeometryBase.
Definition at line 50 of file StraightGeometry.cpp.
References len.
getExitFrame()
Euclid3D StraightGeometry::getExitFrame () const virtual
Get transform.
Reimplemented from BGeometryBase.
Definition at line 64 of file StraightGeometry.cpp.
References len, and Euclid3D::translation().
Referenced by RBendGeometry::getExitFrame().
getExitPatch()
Euclid3D BGeometryBase::getExitPatch () const virtual inherited
Get patch.
Reimplemented in RBendGeometry.
Definition at line 47 of file Geometry.cpp.
References Euclid3D::identity().
Referenced by ElementBase::getExitPatch().
getOrigin()
double StraightGeometry::getOrigin () const virtual
Get origin.
Reimplemented from BGeometryBase.
Definition at line 46 of file StraightGeometry.cpp.
References len.
getTotalTransform()
Euclid3D StraightGeometry::getTotalTransform () const virtual
Get transform.
Reimplemented from BGeometryBase.
Definition at line 56 of file StraightGeometry.cpp.
References len, and Euclid3D::translation().
Referenced by RBendGeometry::getTotalTransform().
getTransform() [1/2]
Euclid3D StraightGeometry::getTransform (double fromS, double toS) const virtual
Get transform.
Implements BGeometryBase.
Definition at line 52 of file StraightGeometry.cpp.
References Euclid3D::translation().
getTransform() [2/2]
Euclid3D StraightGeometry::getTransform (double s) const virtual
Get transform.
Reimplemented from BGeometryBase.
Definition at line 58 of file StraightGeometry.cpp.
References Euclid3D::translation().
operator=()
const StraightGeometry & StraightGeometry::operator= (const StraightGeometry & right) inline
Definition at line 112 of file StraightGeometry.h.
References len.
setElementLength()
void StraightGeometry::setElementLength (double length) virtual
Set design length.
Reimplemented from BGeometryBase.
Definition at line 37 of file StraightGeometry.cpp.
References len.
Referenced by VerticalFFAMagnet::initialise(), MultipoleTStraight::initialise(), ConstantEFieldCavityRep::setElementLength(), VariableRFCavity::setLength(), and OpalRBend::update().
Member Data Documentation
len
double StraightGeometry::len private
Definition at line 102 of file StraightGeometry.h.
Referenced by getArcLength(), getElementLength(), getEntrance(), getEntranceFrame(), getExit(), getExitFrame(), getOrigin(), getTotalTransform(), operator=(), and setElementLength().
The documentation for this class was generated from the following files:
StraightGeometry.h
StraightGeometry.cpp