OPALX (Object Oriented Parallel Accelerator Library for Exascal): ReferencePathModel Class Reference
ReferencePathModel Class Reference
Ordered collection of reference-path segments.
#include <ReferencePathModel.h>
Public Types
using container_type = std::vector< ReferencePathSegment >
Public Member Functions
void addSegment (const ReferencePathSegment &segment)
void clear ()
size_t size () const
bool empty () const
const container_type & getSegments () const
const ReferencePathSegment & operator[] (size_t idx) const
Private Attributes
container_type segments_m
Detailed Description
Ordered collection of reference-path segments.
The first redesign stage keeps this as a lightweight container that can later be populated from IndexMap and legacy ELEMEDGE information. In the terminology of the placement note, this belongs to the reference base \(\mathcal{B}\) and its reporting coordinate \(s\), not to the laboratory-space geometry layer.
Definition at line 18 of file ReferencePathModel.h.
Member Typedef Documentation
container_type
using ReferencePathModel::container_type = std::vector<ReferencePathSegment>
Definition at line 20 of file ReferencePathModel.h.
Member Function Documentation
addSegment()
void ReferencePathModel::addSegment (const ReferencePathSegment & segment) inline
Definition at line 22 of file ReferencePathModel.h.
References segments_m.
Referenced by IndexMap::rebuildReferencePathModel(), and TEST().
clear()
void ReferencePathModel::clear () inline
Definition at line 23 of file ReferencePathModel.h.
References segments_m.
Referenced by OrbitThreader::processElementRegister(), and IndexMap::rebuildReferencePathModel().
empty()
bool ReferencePathModel::empty () const inline
Definition at line 25 of file ReferencePathModel.h.
References segments_m.
Referenced by TEST_F(), and TEST_F().
getSegments()
const container_type & ReferencePathModel::getSegments () const inline
Definition at line 26 of file ReferencePathModel.h.
References segments_m.
Referenced by IndexMap::saveSDDS(), and TEST_F().
operator[]()
const ReferencePathSegment & ReferencePathModel::operator[] (size_t idx) const inline
Definition at line 27 of file ReferencePathModel.h.
References segments_m.
size()
size_t ReferencePathModel::size () const inline
Definition at line 24 of file ReferencePathModel.h.
References segments_m.
Referenced by TEST(), TEST(), and TEST_F().
Member Data Documentation
segments_m
container_type ReferencePathModel::segments_m private
Definition at line 30 of file ReferencePathModel.h.
Referenced by addSegment(), clear(), empty(), getSegments(), operator[](), and size().
The documentation for this class was generated from the following file:
ReferencePathModel.h