OPALX (Object Oriented Parallel Accelerator Library for Exascal): Ring Class Reference
Ring Class Reference
Ring describes a ring type geometry for tracking.
#include <Ring.h>
Public Member Functions
Ring (std::string ring)
Ring (const Ring &ring)
virtual ~Ring ()
virtual bool apply (const std::shared_ptr< ParticleContainer_t > &pc) override
virtual bool apply (const size_t &id, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
Apply to particle i.
virtual bool apply (const Vector_t< double, 3 > &R, const Vector_t< double, 3 > &P, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
virtual void initialise (PartBunch_t *bunch, double &startField, double &endField) override
virtual void initialise (PartBunch_t *bunch)
virtual void finalise () override
virtual bool bends () const override
virtual void accept (BeamlineVisitor &visitor) const override
virtual void getFieldExtend (double &zBegin, double &zEnd) const override
virtual ElementBase * clone () const override
void appendElement (const Component &element)
virtual EMField & getField () override
virtual const EMField & getField () const override
virtual PlanarArcGeometry & getGeometry () override
virtual const PlanarArcGeometry & getGeometry () const override
void setLossDataSink (LossDataSink *sink)
PartBunch_t * getLossDataSink () const
void setRefPartBunch (PartBunch_t *bunch)
PartBunch_t * getRefPartBunch () const
void setHarmonicNumber (double cyclHarm)
double getHarmonicNumber ()
void setRFFreq (double rfFreq)
double getRFFreq () const
void setBeamRInit (double rInit)
double getBeamRInit () const
void setBeamPhiInit (double phiInit)
double getBeamPhiInit () const
void setBeamPRInit (double pRInit)
double getBeamPRInit () const
void setLatticeRInit (double rInit)
double getLatticeRInit () const
void setLatticePhiInit (double phiInit)
double getLatticePhiInit () const
Vector_t< double, 3 > getNextPosition () const
Vector_t< double, 3 > getNextNormal () const
void setLatticeThetaInit (double thetaInit)
double getLatticeThetaInit () const
void setSymmetry (double symmetry)
void setScale (double scale)
double getSymmetry () const
void setIsClosed (bool isClosed)
double getIsClosed () const
void setRingAperture (double minR, double maxR)
double getRingMinR () const
double getRingMaxR () const
void lockRing ()
RingSection * getLastSectionPlaced () const
std::vector< RingSection * > getSectionsAt (const Vector_t< double, 3 > &pos)
EVector Efield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool applyToReferenceParticle (const Vector_t< double, 3 > &R, const Vector_t< double, 3 > &P, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B)
Apply to reference particle with position R and momemtum P.
virtual bool getPotential (const Vector_t< double, 3 > &, const double &, Vector_t< double, 3 > &, double &)
Calculate the four-potential at some position relative to the component.
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual void goOnline (const double &kineticEnergy)
virtual void goOffline ()
virtual bool Online ()
virtual ElementType getType () const
Get element type std::string.
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunch_t &bunch, const PartData &, bool revBeam, bool revTrack) const
Track a borrowed particle bunch through a non-standard component.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
Return the nominal body extent of the element.
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
virtual Port getEntryPort () const
Return the entrance port of the canonical local chart.
virtual Port getBodyPort () const
Return the body port of the canonical local chart.
virtual Port getExitPort () const
Return the exit port of the canonical local chart.
PlacementPose getPlacementPose () const
Return the nominal rigid placement transform of the element.
void setPlacementPose (const PlacementPose &pose)
Set the nominal rigid placement transform of the element.
Misalignment getPlacementMisalignment () const
Return the local nominal-to-actual correction stored for the element.
ElementGeometry getPlacementGeometry () const
Return the bridge geometry ports assembled from legacy edge state.
SupportPlacement getPlacementSupport () const
Return the support-frame bridge object. The default is the body frame.
PlacedElement getPlacedElement () const
Return a placed-element view assembled from the current bridge objects.
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t< double, 3 > &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Static Public Member Functions
static Vector_t< double, 3 > convert (const Vector3D &vec)
static Vector3D convert (const Vector_t< double, 3 > &vec)
static std::string getTypeString (ElementType type)
Protected Member Functions
bool isInsideTransverse (const Vector_t< double, 3 > &r) const
Protected Attributes
double exit_face_slope_m
PartBunch_t * RefPartBunch_m
bool online_m
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes
static const std::vector< double > defaultAperture_m = std::vector<double>({1e6, 1e6, 1.0})
Private Member Functions
void resetAzimuths ()
void checkAndClose ()
void buildRingSections ()
void rotateToCyclCoordinates (Euclid3D &euclid3d) const
Ring ()
Ring & operator= (const Ring &ring)
void checkMidplane (Euclid3D delta) const
Rotation3D getRotationStartToEnd (Euclid3D delta) const
Static Private Member Functions
static bool sectionCompare (RingSection const *const sec1, RingSection const *const sec2)
Private Attributes
PlanarArcGeometry planarArcGeometry_m
PartBunch_t * refPartBunch_m
LossDataSink * lossDS_m
double beamRInit_m
double beamPRInit_m
double beamPhiInit_m
double latticeRInit_m
double latticePhiInit_m
double latticeThetaInit_m
bool willDoAperture_m = false
double minR2_m
double maxR2_m
bool isLocked_m
bool isClosed_m
int symmetry_m
double scale_m = 1.
double cyclHarm_m
double rfFreq_m
double phiStep_m
std::vector< RingSectionList > ringSections_m
RingSectionList section_list_m
std::string elementID
AttributeSet userAttribs
WakeFunction * wake_m
BoundaryGeometry * bgeometry_m
ParticleMatterInteractionHandler * parmatint_m
bool positionIsFixed
std::queue< std::pair< double, double > > actionRange_m
std::string outputfn_m
bool deleteOnTransverseExit_m = true
double elementPosition_m
ELEMEDGE attribute.
bool elemedgeSet_m
Static Private Attributes
static const double lengthTolerance_m = 1e-2
static const double angleTolerance_m = 1e-2
static const std::map< ElementType, std::string > elementTypeToString_s
Detailed Description
Ring describes a ring type geometry for tracking.
Ring describes a ring type geometry for tracking. Ring provides the necessary interfaces for e.g. OPAL-CYCL to track through the ring geometry, while enabling the user to add arbitrary field elements in a closed geometry.
Ring uses similar routines to OPAL-T OpalBeamline class to set up geometry; note that as OPAL-CYCL places the beam in an x-y geometry we place in an x-y geometry for Ring (i.e. the axis of the ring is by default the z-axis). So far only placement of elements in the midplane is supported. It is not possible to give vertical displacements or rotations, or add elements that might create vertical displacements and rotations.
Also aim to maintain backwards compatibility with Cyclotron (i.e. use ParallelCyclotronTracker)
Definition at line 62 of file Ring.h.
Constructor & Destructor Documentation
Ring() [1/3]
Ring::Ring (std::string ring)
Constructor
Parameters
ring Name of the ring as defined in the input file
Definition at line 47 of file Ring.cpp.
References beamPhiInit_m, beamPRInit_m, beamRInit_m, Component::Component(), cyclHarm_m, isClosed_m, isLocked_m, latticePhiInit_m, latticeRInit_m, latticeThetaInit_m, lossDS_m, phiStep_m, planarArcGeometry_m, refPartBunch_m, rfFreq_m, ringSections_m, section_list_m, setRefPartBunch(), and symmetry_m.
Referenced by operator=(), and Ring().
Ring() [2/3]
Ring::Ring (const Ring & ring)
Copy constructor
Can't copy LossDataSink so throw exception if this is set
Definition at line 71 of file Ring.cpp.
References beamPhiInit_m, beamPRInit_m, beamRInit_m, buildRingSections(), Component::Component(), cyclHarm_m, ElementBase::getName(), isClosed_m, isLocked_m, latticePhiInit_m, latticeRInit_m, latticeThetaInit_m, lossDS_m, maxR2_m, minR2_m, phiStep_m, planarArcGeometry_m, refPartBunch_m, Ring(), ringSections_m, section_list_m, setRefPartBunch(), symmetry_m, and willDoAperture_m.
~Ring()
Ring::~Ring () virtual
Destructor - deletes lossDS_m if not nullptr
Definition at line 102 of file Ring.cpp.
References section_list_m.
Ring() [3/3]
Ring::Ring () private
Disabled
Referenced by clone().
Member Function Documentation
accept()
void Ring::accept (BeamlineVisitor & visitor) const override virtual
Accept the BeamlineVisitor
Just calls visitRing function on the visitor. I guess the point of this function is that it enables us to store a pointer to the visitor object or something
Implements ElementBase.
Definition at line 69 of file Ring.cpp.
References BeamlineVisitor::visitRing().
appendElement()
void Ring::appendElement (const Component & element)
Add element to the ring
Add element to the ring. Elements are assumed to occupy a region of space defined by a (flat) plane at the start and a plane at the end, both infinite in extent. The position and rotation of these planes are defined according to the Component geometry given by element.getGeometry().
Caller owns memory allocated to element - Ring makes a copy.
Throws an exception if the geometry would bend the element out of the midplane (elements out of midplane are not yet supported). Note that BeamlineGeometry considers midplane to be x-z, whereas Ring considers midplane to be x-y; we apply a rotation during set up.
The element is assumed to extend not beyond the element geometry; Ring applies a bounding box based on the element geometry, if there are field maps expanding outside this region they may get cut.
Definition at line 253 of file Ring.cpp.
References checkMidplane(), ElementBase::clone(), Component::Component(), Rotation3D::getAxis(), RingSection::getEndNormal(), RingSection::getEndPosition(), ElementBase::getGeometry(), ElementBase::getName(), getNextNormal(), getNextPosition(), Euclid3D::getRotation(), RingSection::getStartNormal(), RingSection::getStartPosition(), BGeometryBase::getTotalTransform(), Euclid3D::getVector(), isLocked_m, rotateToCyclCoordinates(), section_list_m, RingSection::setComponent(), RingSection::setComponentOrientation(), RingSection::setComponentPosition(), RingSection::setEndNormal(), RingSection::setEndPosition(), RingSection::setStartNormal(), and RingSection::setStartPosition().
Referenced by lockRing().
apply() [1/3]
bool Ring::apply (const size_t & i, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual
Apply to particle i.
Parameters
i Particle index
t Time
E Electric Field
B Magnetic Field
Returns
true if particle is out-of-bounds (lost), false otherwise
Reimplemented from Component.
Definition at line 109 of file Ring.cpp.
References apply(), and Component::RefPartBunch_m.
apply() [2/3]
bool Ring::apply (const std::shared_ptr< ParticleContainer_t > & pc) override virtual
Overwrite data in vector E and B with electric and magnetic field
Parameters
i index of item in RefPartBunch_m - particle bunch
t time
E array where electric field vector is stored - any existing data is overwritten
B array where magnetic field vector is stored - any existing data is overwritten
Returns
false if particle is outside of the field map apertures, else true. If particle is off the field maps, then set flag on the particle "Bin" data to -1 and store in LossDataSink
Reimplemented from Component.
Definition at line 107 of file Ring.cpp.
Referenced by apply().
apply() [3/3]
bool Ring::apply (const Vector_t< double, 3 > & R, const Vector_t< double, 3 > & P, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual
Overwrite data in vector E and B with electromagnetic field at point R
Parameters
R 3 vector position at which the field is found in Cartesian coordinates (i.e. x, y, z with z=vertical)
P 3 vector momentum
centroid unknown, but not used - bunch mean maybe?
t time
E vector where electric field vector will be stored - any existing data is overwritten
B vector where magnetic field vector will be stored - any existing data is overwritten
Returns
false if particle is outside of the ring aperture, else true. If particle is off the field maps, then set flag on the particle "Bin" data to -1
Reimplemented from Component.
Definition at line 140 of file Ring.cpp.
References getSectionsAt(), maxR2_m, refPartBunch_m, scale_m, and willDoAperture_m.
applyToReferenceParticle()
bool Component::applyToReferenceParticle (const Vector_t< double, 3 > & R, const Vector_t< double, 3 > & P, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) virtual inherited
Apply to reference particle with position R and momemtum P.
Parameters
R Position
P Momentum
t Time
E Electric Field
B Magnetic Field
Returns
true if particle is out-of-bounds (lost), false otherwise
Reimplemented in BendBase, ConstantEFieldCavity, Monitor, Multipole, PluginElement, RFCavity, Solenoid, TravelingWave, and VariableRFCavity.
Definition at line 114 of file Component.cpp.
References ElementBase::getElementLength(), and ElementBase::isInsideTransverse().
bends()
virtual bool Ring::bends () const inline override virtual
Returns true - Ring is assumed to bend particles, being a ring
Implements Component.
Definition at line 142 of file Ring.h.
Bfield() [1/2]
BVector Component::Bfield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 234 of file Component.h.
References EMField::Bfield(), and getField().
Bfield() [2/2]
BVector Component::Bfield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 240 of file Component.h.
References EMField::Bfield(), and getField().
buildRingSections()
void Ring::buildRingSections () private
Definition at line 367 of file Ring.cpp.
References phiStep_m, Physics::pi, ringSections_m, and section_list_m.
Referenced by lockRing(), and Ring().
checkAndClose()
void Ring::checkAndClose () private
Definition at line 353 of file Ring.cpp.
References angleTolerance_m, lengthTolerance_m, and section_list_m.
Referenced by lockRing().
checkMidplane()
void Ring::checkMidplane (Euclid3D delta) const private
Definition at line 217 of file Ring.cpp.
References angleTolerance_m, Rotation3D::getAxis(), Euclid3D::getRotation(), Euclid3D::getVector(), and lengthTolerance_m.
Referenced by appendElement().
clone()
virtual ElementBase * Ring::clone () const inline override virtual
Inherited copy constructor
Implements ElementBase.
Definition at line 156 of file Ring.h.
References ElementBase::ElementBase(), and Ring().
convert() [1/2]
Vector_t< double, 3 > Ring::convert (const Vector3D & vec) inline static
Convert from a Vector3D to a Vector_t<double, 3>
Definition at line 416 of file Ring.h.
convert() [2/2]
Vector3D Ring::convert (const Vector_t< double, 3 > & vec) inline static
Convert from a Vector_t<double, 3> to a Vector3D
Definition at line 420 of file Ring.h.
copyStructure()
ElementBase * ElementBase::copyStructure () virtual inherited
Make a structural copy.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 193 of file ElementBase.cpp.
References clone(), ElementBase(), and isSharable().
Referenced by Sequence::copy(), Line::parse(), and SequenceParser::parseMember().
EBfield() [1/2]
EBVectors Component::EBfield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 244 of file Component.h.
References EMField::EBfield(), and getField().
EBfield() [2/2]
EBVectors Component::EBfield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 246 of file Component.h.
References EMField::EBfield(), and getField().
Efield() [1/2]
EVector Component::Efield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 232 of file Component.h.
References EMField::Efield(), and getField().
Efield() [2/2]
EVector Component::Efield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 236 of file Component.h.
References EMField::Efield(), and getField().
finalise()
void Ring::finalise () override virtual
Clean up the Ring
Ring relinquishes RefPartBunch_t pointer and deletes LossDataSink
Implements Component.
Definition at line 191 of file Ring.cpp.
References lossDS_m, Component::online_m, and setLossDataSink().
fixPosition()
void ElementBase::fixPosition () inline inherited
Definition at line 596 of file ElementBase.h.
References positionIsFixed.
Referenced by OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
getAperture()
std::pair< ApertureType, std::vector< double > > ElementBase::getAperture () const inline inherited
Definition at line 581 of file ElementBase.h.
References aperture_m.
Referenced by MeshGenerator::add(), Solenoid::getSupportEnvelope(), and MeshGenerator::getTransverseSupport().
getArcLength()
double ElementBase::getArcLength () const inline virtual inherited
Get arc length.
Reimplemented in MarkerRep, TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 478 of file ElementBase.h.
References BGeometryBase::getArcLength(), and getGeometry().
Referenced by TBeamline< T >::getTransform().
getAttribute()
double ElementBase::getAttribute (const std::string & aKey) const virtual inherited
Get attribute value.
Definition at line 146 of file ElementBase.cpp.
References getConstChannel().
getBeamPhiInit()
double Ring::getBeamPhiInit () const inline
Get the initial beam azimuthal angle
Definition at line 246 of file Ring.h.
References beamPhiInit_m.
getBeamPRInit()
double Ring::getBeamPRInit () const inline
Get the initial beam radial momentum
Definition at line 252 of file Ring.h.
References beamPRInit_m.
getBeamRInit()
double Ring::getBeamRInit () const inline
Get the initial beam radius
Definition at line 240 of file Ring.h.
References beamRInit_m.
getBodyPort()
Port ElementBase::getBodyPort () const inline virtual inherited
Return the body port of the canonical local chart.
The body port \(p_{i,\mathrm{body}}\) is the identity port of the element's canonical local chart. Its rigid transform is therefore the identity element of \(SE(3)\) in the first redesign stage.
Definition at line 546 of file ElementBase.h.
Referenced by getPlacementGeometry(), and TEST_F().
getBoundaryGeometry()
BoundaryGeometry * ElementBase::getBoundaryGeometry () const inline virtual inherited
return the attached boundary geometrt object if there is any
Definition at line 512 of file ElementBase.h.
References bgeometry_m.
getBoundingBoxInLabCoords()
BoundingBox ElementBase::getBoundingBoxInLabCoords () const virtual inherited
Definition at line 263 of file ElementBase.cpp.
References csTrafoGlobal2Local_m, getEdgeToBegin(), and getEdgeToEnd().
getChannel()
Channel * ElementBase::getChannel (const std::string & aKey, bool create = false) virtual inherited
Construct a read/write channel.
Reimplemented in ConstantEFieldCavityRep, DriftRep, LaserRep, MonitorRep, MultipoleRep, ProbeRep, RBendRep, RFCavityRep, SBendRep, SolenoidRep, and TravelingWaveRep.
Definition at line 181 of file ElementBase.cpp.
References userAttribs.
Referenced by ConstantEFieldCavityRep::getChannel(), DriftRep::getChannel(), LaserRep::getChannel(), MonitorRep::getChannel(), MultipoleRep::getChannel(), ProbeRep::getChannel(), RBendRep::getChannel(), RFCavityRep::getChannel(), SBendRep::getChannel(), SolenoidRep::getChannel(), TravelingWaveRep::getChannel(), getConstChannel(), and setAttribute().
getConstChannel()
const ConstChannel * ElementBase::getConstChannel (const std::string & aKey) const virtual inherited
Construct a read-only channel.
Definition at line 185 of file ElementBase.cpp.
References ElementBase(), and getChannel().
Referenced by getAttribute(), and hasAttribute().
getCSTrafoGlobal2Local()
CoordinateSystemTrafo ElementBase::getCSTrafoGlobal2Local () const inline inherited
Definition at line 528 of file ElementBase.h.
References csTrafoGlobal2Local_m.
Referenced by getPlacementPose(), OpalRBend::update(), and OpalSBend::update().
getDesign()
const ElementBase & Component::getDesign () const virtual inherited
Return design element.
Definition at line 33 of file Component.cpp.
References ElementBase::ElementBase().
getDesignEnergy()
double Component::getDesignEnergy () const inline virtual inherited
Reimplemented in BendBase, and RFCavity.
Definition at line 254 of file Component.h.
getEdgeToBegin()
CoordinateSystemTrafo ElementBase::getEdgeToBegin () const inline virtual inherited
Reimplemented in BendBase, RFCavity, Solenoid, and TravelingWave.
Definition at line 532 of file ElementBase.h.
Referenced by getBoundingBoxInLabCoords(), getEntryPort(), and isInsideTransverse().
getEdgeToEnd()
CoordinateSystemTrafo ElementBase::getEdgeToEnd () const inline virtual inherited
Reimplemented in BendBase, RFCavity, Solenoid, and TravelingWave.
Definition at line 537 of file ElementBase.h.
References getElementLength().
Referenced by getBoundingBoxInLabCoords(), and getExitPort().
getElementDimensions()
virtual void ElementBase::getElementDimensions (double & begin, double & end) const inline virtual inherited
Return the nominal body extent of the element.
The first placement redesign stage distinguishes between the nominal body extent and the field-support extent. The body extent is the canonical longitudinal interval of the placed hardware, \([z_\mathrm{body}^{\mathrm{begin}}, z_\mathrm{body}^{\mathrm{end}}]\), and therefore drives ports, placement, and visualization. By default it coincides with the geometry length \([0, L]\) in the local chart.
Reimplemented in RFCavity, Solenoid, and TravelingWave.
Definition at line 177 of file ElementBase.h.
References getElementLength().
Referenced by MeshGenerator::add().
getElementLength()
double ElementBase::getElementLength () const inline virtual inherited
Get design length.
Reimplemented in MarkerRep, RFCavity, TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 480 of file ElementBase.h.
References BGeometryBase::getElementLength(), and getGeometry().
Referenced by MeshGenerator::add(), BendBase::apply(), Component::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Multipole::apply(), Multipole::apply(), Multipole::apply(), VariableRFCavity::apply(), VariableRFCavity::apply(), VariableRFCavity::apply(), Component::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), getEdgeToEnd(), Solenoid::getEdgeToEnd(), getElementDimensions(), Solenoid::getElementDimensions(), RFCavity::getElementLength(), BendBase::getFieldExtend(), ConstantEFieldCavity::getFieldExtend(), Corrector::getFieldExtend(), Drift::getFieldExtend(), Laser::getFieldExtend(), Multipole::getFieldExtend(), MultipoleT::getFieldExtend(), VariableRFCavity::getFieldExtend(), BendBase::getLength(), BendBase::initialise(), ConstantEFieldCavity::initialise(), Corrector::initialise(), Drift::initialise(), Laser::initialise(), Multipole::initialise(), BendBase::isInside(), isInside(), Monitor::isInside(), Multipole::isInside(), isInsideTransverse(), and TEST_F().
getElementPosition()
double ElementBase::getElementPosition () const inline inherited
Definition at line 617 of file ElementBase.h.
References elemedgeSet_m, elementPosition_m, and getName().
getEntrance()
double ElementBase::getEntrance () const inline virtual inherited
Get entrance position.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 486 of file ElementBase.h.
References BGeometryBase::getEntrance(), and getGeometry().
Referenced by BendBase::getDesignPath().
getEntranceFrame()
Euclid3D ElementBase::getEntranceFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 498 of file ElementBase.h.
References BGeometryBase::getEntranceFrame(), and getGeometry().
Referenced by BendBase::getChordLength(), and BendBase::getEdgeToBegin().
getEntrancePatch()
Euclid3D ElementBase::getEntrancePatch () const inline virtual inherited
Get patch.
Definition at line 502 of file ElementBase.h.
References BGeometryBase::getEntrancePatch(), and getGeometry().
getEntryPort()
Port ElementBase::getEntryPort () const inline virtual inherited
Return the entrance port of the canonical local chart.
In the placement-note language, this is the marked entrance port \(p_{i,\mathrm{entry}}\) of element \(i\). For straight elements in the bridge stage, the body-to-entry transform is taken from the legacy getEdgeToBegin() result.
Definition at line 544 of file ElementBase.h.
References getEdgeToBegin().
Referenced by getPlacementGeometry(), and TEST_F().
getExit()
double ElementBase::getExit () const inline virtual inherited
Get exit position.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 488 of file ElementBase.h.
References BGeometryBase::getExit(), and getGeometry().
Referenced by BendBase::getDesignPath().
getExitFrame()
Euclid3D ElementBase::getExitFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 500 of file ElementBase.h.
References BGeometryBase::getExitFrame(), and getGeometry().
Referenced by BendBase::getChordLength(), and BendBase::getEdgeToEnd().
getExitPatch()
Euclid3D ElementBase::getExitPatch () const inline virtual inherited
Get patch.
Definition at line 504 of file ElementBase.h.
References BGeometryBase::getExitPatch(), and getGeometry().
getExitPort()
Port ElementBase::getExitPort () const inline virtual inherited
Return the exit port of the canonical local chart.
In the placement-note language, this is the marked exit port \(p_{i,\mathrm{exit}}\). For straight elements in the bridge stage, the body-to-exit transform is taken from the legacy getEdgeToEnd() result.
Definition at line 548 of file ElementBase.h.
References getEdgeToEnd().
Referenced by getPlacementGeometry(), and TEST_F().
getField() [1/2]
virtual const EMField & Ring::getField () const inline override virtual
Not implemented, throws an exception
Implements Component.
Definition at line 185 of file Ring.h.
getField() [2/2]
virtual EMField & Ring::getField () inline override virtual
Not implemented, throws an exception
Implements Component.
Definition at line 180 of file Ring.h.
getFieldExtend()
void Ring::getFieldExtend (double & zBegin, double & zEnd) const override virtual
Not implemented - always throws an exception
Implements Component.
Definition at line 177 of file Ring.cpp.
getFlagDeleteOnTransverseExit()
bool ElementBase::getFlagDeleteOnTransverseExit () const inline inherited
Definition at line 633 of file ElementBase.h.
References deleteOnTransverseExit_m.
Referenced by BendBase::apply(), BendBase::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Multipole::apply(), Multipole::apply(), RFCavity::apply(), Solenoid::apply(), and TravelingWave::apply().
getGeometry() [1/2]
virtual const PlanarArcGeometry & Ring::getGeometry () const inline override virtual
Not implemented
Implements ElementBase.
Definition at line 193 of file Ring.h.
References planarArcGeometry_m.
getGeometry() [2/2]
virtual PlanarArcGeometry & Ring::getGeometry () inline override virtual
Not implemented
Implements ElementBase.
Definition at line 190 of file Ring.h.
References planarArcGeometry_m.
getHarmonicNumber()
double Ring::getHarmonicNumber () inline
Get the harmonic number for RF (number of bunches in the ring)
Definition at line 227 of file Ring.h.
References cyclHarm_m.
getIsClosed()
double Ring::getIsClosed () const inline
Get flag for closure checking
Definition at line 297 of file Ring.h.
References isClosed_m.
getLastSectionPlaced()
RingSection * Ring::getLastSectionPlaced () const
Get the last section placed or nullptr if no sections were placed yet
Definition at line 381 of file Ring.cpp.
References section_list_m.
getLatticePhiInit()
double Ring::getLatticePhiInit () const inline
Get the initial element's azimuthal angle
Definition at line 264 of file Ring.h.
References latticePhiInit_m.
getLatticeRInit()
double Ring::getLatticeRInit () const inline
Get the initial element's radius
Definition at line 258 of file Ring.h.
References latticeRInit_m.
getLatticeThetaInit()
double Ring::getLatticeThetaInit () const inline
Get the first element's horizontal angle
Get the angle in the ring plane with respect to the tangent vector
Definition at line 282 of file Ring.h.
References latticeThetaInit_m.
getLossDataSink()
PartBunch_t * Ring::getLossDataSink () const
Get pointer to lossDataSink.
Ring still owns the memory to which lossDataSink points.
getMisalignment() [1/2]
CoordinateSystemTrafo ElementBase::getMisalignment () const inline inherited
Definition at line 592 of file ElementBase.h.
References misalignment_m.
Referenced by getPlacementMisalignment().
getMisalignment() [2/2]
void ElementBase::getMisalignment (double & x, double & y, double & s) const inherited
getName()
const std::string & ElementBase::getName () const virtual inherited
Get element name.
Definition at line 131 of file ElementBase.cpp.
References elementID.
Referenced by Ring::appendElement(), TBeamline< T >::clone(), TBeamline< T >::copyStructure(), Probe::doGoOffline(), PlaceRep::enter(), getElementPosition(), RFCavity::getMomentaKick(), getOutputFN(), CavityAutophaser::getPhaseAtMaxEnergy(), Selector::handleElement(), RFCavity::initialise(), Ring::initialise(), Solenoid::initialise(), PlaceRep::leave(), VariableRFCavity::operator=(), Sequence::print(), Ring::Ring(), BeamlineFieldElement::SortAsc(), TEST_F(), Component::trackBunch(), Component::trackMap(), OpalRBend::update(), OpalSBend::update(), Sequence::updateList(), ParallelTracker::updateRFElement(), and Replacer::visitFlaggedElmPtr().
getNextNormal()
Vector_t< double, 3 > Ring::getNextNormal () const
Get the initial element's start normal in cartesian coordinates
Definition at line 244 of file Ring.cpp.
References latticePhiInit_m, latticeThetaInit_m, and section_list_m.
Referenced by appendElement().
getNextPosition()
Vector_t< double, 3 > Ring::getNextPosition () const
Get the initial element's start position in cartesian coordinates
Definition at line 235 of file Ring.cpp.
References latticePhiInit_m, latticeRInit_m, and section_list_m.
Referenced by appendElement().
getOrigin()
double ElementBase::getOrigin () const inline virtual inherited
Get origin position.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 484 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getOrigin().
getOutputFN()
std::string ElementBase::getOutputFN () const inherited
Get output filename.
Definition at line 137 of file ElementBase.cpp.
References getName(), and outputfn_m.
Referenced by Probe::doInitialise(), Monitor::initialise(), and PluginElement::initialise().
getParticleMatterInteraction()
ParticleMatterInteractionHandler * ElementBase::getParticleMatterInteraction () const inline virtual inherited
Definition at line 516 of file ElementBase.h.
References parmatint_m.
getPlacedElement()
PlacedElement ElementBase::getPlacedElement () const inline inherited
Return a placed-element view assembled from the current bridge objects.
Definition at line 570 of file ElementBase.h.
References getPlacementGeometry(), getPlacementMisalignment(), getPlacementPose(), and getPlacementSupport().
Referenced by MeshGenerator::add(), and TEST_F().
getPlacementGeometry()
ElementGeometry ElementBase::getPlacementGeometry () const inline inherited
Return the bridge geometry ports assembled from legacy edge state.
The first redesign stage defines a minimal explicit port contract with three named body-relative ports: \(p_{i,\mathrm{entry}}\), \(p_{i,\mathrm{body}}\), \(p_{i,\mathrm{exit}}\). The default bridge preserves current OPALX behavior by deriving those ports from getEntryPort(), getBodyPort(), and getExitPort(), whose straight-element implementations are backed by the legacy getEdgeToBegin() and getEdgeToEnd() methods.
Definition at line 562 of file ElementBase.h.
References getBodyPort(), getEntryPort(), and getExitPort().
Referenced by getPlacedElement().
getPlacementMisalignment()
Misalignment ElementBase::getPlacementMisalignment () const inline inherited
Return the local nominal-to-actual correction stored for the element.
Definition at line 558 of file ElementBase.h.
References getMisalignment().
Referenced by getPlacedElement().
getPlacementPose()
PlacementPose ElementBase::getPlacementPose () const inline inherited
Return the nominal rigid placement transform of the element.
This is the bridge from the legacy stored CoordinateSystemTrafo to the new placement vocabulary. It preserves current nominal placement semantics and does not apply misalignment.
Definition at line 550 of file ElementBase.h.
References getCSTrafoGlobal2Local().
Referenced by getPlacedElement().
getPlacementSupport()
SupportPlacement ElementBase::getPlacementSupport () const inline inherited
Return the support-frame bridge object. The default is the body frame.
Definition at line 566 of file ElementBase.h.
Referenced by getPlacedElement().
getPotential()
virtual bool Component::getPotential (const Vector_t< double, 3 > & , const double & , Vector_t< double, 3 > & , double &) inline virtual inherited
Calculate the four-potential at some position relative to the component.
Parameters
R position in the local coordinate system of the component
t time
A filled with the calculated magnetic vector potential
phi filled with the calculated electric potential Note that any existing values in A and phi may be overwritten by this method.
Returns
true if particle is outside the field map, else false Default for component is to return false and make no change to A and phi
Definition at line 155 of file Component.h.
getRefPartBunch()
PartBunch_t * Ring::getRefPartBunch () const
Get pointer to RefPartBunch_t from the bunch.
Ring does not own this memory (so neither does caller).
getRequiredNumberOfTimeSteps()
int ElementBase::getRequiredNumberOfTimeSteps () const inline virtual inherited
Reimplemented in BendBase, Drift, Laser, Marker, and Monitor.
Definition at line 627 of file ElementBase.h.
getRFFreq()
double Ring::getRFFreq () const inline
Get the nominal RF frequency
Definition at line 234 of file Ring.h.
References rfFreq_m.
getRingMaxR()
double Ring::getRingMaxR () const inline
Get the ring maximum
Definition at line 309 of file Ring.h.
References maxR2_m.
getRingMinR()
double Ring::getRingMinR () const inline
Get the ring minimum
Definition at line 306 of file Ring.h.
References minR2_m.
getRotationAboutZ()
double ElementBase::getRotationAboutZ () const inline inherited
Definition at line 608 of file ElementBase.h.
References rotationZAxis_m.
Referenced by OpalBeamline::compileCompatibilityPlacement().
getRotationStartToEnd()
Rotation3D Ring::getRotationStartToEnd (Euclid3D delta) const private
Definition at line 206 of file Ring.cpp.
References Euclid3D::getRotation(), and Rotation3D::ZRotation().
getSectionsAt()
std::vector< RingSection * > Ring::getSectionsAt (const Vector_t< double, 3 > & pos)
Get the list of sections at position pos
Definition at line 202 of file Ring.cpp.
References section_list_m.
Referenced by apply().
getSymmetry()
double Ring::getSymmetry () const inline
Get the rotational symmetry of the ring (number of cells)
Definition at line 291 of file Ring.h.
References symmetry_m.
getTotalTransform()
Euclid3D ElementBase::getTotalTransform () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 494 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getTotalTransform().
getTransform() [1/2]
Euclid3D ElementBase::getTransform (double fromS, double toS) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 490 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getTransform().
Referenced by BendBase::getDesignPath(), and TBeamline< T >::getTransform().
getTransform() [2/2]
Euclid3D ElementBase::getTransform (double s) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 496 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getTransform().
getType()
ElementType Component::getType () const virtual inherited
Get element type std::string.
Implements ElementBase.
Reimplemented in ConstantEFieldCavity, Corrector, Drift, Laser, Marker, Monitor, Multipole, Probe, RBend, RFCavity, SBend, Solenoid, and TravelingWave.
Definition at line 49 of file Component.cpp.
References ANY.
Referenced by ParallelTracker::visitComponent().
getTypeString() [1/2]
std::string ElementBase::getTypeString () const inline inherited
Definition at line 610 of file ElementBase.h.
References getType(), and getTypeString().
Referenced by getTypeString().
getTypeString() [2/2]
std::string ElementBase::getTypeString (ElementType type) static inherited
Definition at line 191 of file ElementBase.cpp.
References elementTypeToString_s.
getWake()
WakeFunction * ElementBase::getWake () const inline virtual inherited
return the attached wake object if there is any
Definition at line 508 of file ElementBase.h.
References wake_m.
goOffline()
void Component::goOffline () virtual inherited
Reimplemented in Monitor, PluginElement, RFCavity, Solenoid, and TravelingWave.
Definition at line 45 of file Component.cpp.
References online_m.
goOnline()
void Component::goOnline (const double & kineticEnergy) virtual inherited
Reimplemented in Corrector, Monitor, RFCavity, Solenoid, and TravelingWave.
Definition at line 43 of file Component.cpp.
References online_m.
Referenced by PluginElement::initialise().
hasAttribute()
bool ElementBase::hasAttribute (const std::string & aKey) const virtual inherited
Test for existence of an attribute.
Definition at line 158 of file ElementBase.cpp.
References getConstChannel().
hasBoundaryGeometry()
bool ElementBase::hasBoundaryGeometry () const inline virtual inherited
Definition at line 514 of file ElementBase.h.
References bgeometry_m.
hasParticleMatterInteraction()
bool ElementBase::hasParticleMatterInteraction () const inline virtual inherited
Definition at line 520 of file ElementBase.h.
References parmatint_m.
hasWake()
bool ElementBase::hasWake () const inline virtual inherited
Definition at line 510 of file ElementBase.h.
References wake_m.
initialise() [1/2]
void Ring::initialise (PartBunch_t * bunch) virtual
Initialise the Ring - set the bunch and allocate a new LossDataSink
Parameters
bunch the particle bunch. Ring borrows this pointer (caller owns memory)
Definition at line 181 of file Ring.cpp.
References ElementBase::getName(), Component::online_m, setLossDataSink(), and setRefPartBunch().
initialise() [2/2]
void Ring::initialise (PartBunch_t * bunch, double & startField, double & endField) override virtual
Initialise the Ring
Parameters
bunch the particle bunch. Ring borrows this pointer (caller owns memory)
startField - not used
endField - not used
scaleFactor - not used
Implements Component.
Definition at line 187 of file Ring.cpp.
References initialise().
Referenced by initialise().
isElementPositionSet()
bool ElementBase::isElementPositionSet () const inline inherited
Definition at line 625 of file ElementBase.h.
References elemedgeSet_m.
isInside()
bool ElementBase::isInside (const Vector_t< double, 3 > & r) const inline virtual inherited
Reimplemented in BendBase, Monitor, Multipole, RFCavity, Solenoid, and TravelingWave.
Definition at line 585 of file ElementBase.h.
References getElementLength(), and isInsideTransverse().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
isInsideTransverse()
bool ElementBase::isInsideTransverse (const Vector_t< double, 3 > & r) const protected inherited
Definition at line 232 of file ElementBase.cpp.
References aperture_m, CONIC_ELLIPTICAL, CONIC_RECTANGULAR, getEdgeToBegin(), getElementLength(), and CoordinateSystemTrafo::transformTo().
Referenced by BendBase::apply(), BendBase::apply(), Component::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Multipole::apply(), Multipole::apply(), BendBase::applyToReferenceParticle(), Component::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), BendBase::isInside(), isInside(), Monitor::isInside(), Multipole::isInside(), RFCavity::isInside(), Solenoid::isInside(), and TravelingWave::isInside().
isPositioned()
bool ElementBase::isPositioned () const inline inherited
Definition at line 598 of file ElementBase.h.
References positionIsFixed.
Referenced by OpalRBend::update(), and OpalSBend::update().
isSharable()
bool ElementBase::isSharable () const inline inherited
Test if the element can be shared.
Definition at line 506 of file ElementBase.h.
References shareFlag.
Referenced by copyStructure(), TBeamline< T >::copyStructure(), and Sequence::updateList().
lockRing()
void Ring::lockRing ()
Lock the ring
Lock the ring; apply closure checks and symmetry properties as required. Impose rule that start must be before end and switch objects around if this is not the case. Sort by startPosition azimuthal angle.
Sets isLocked_m to true. New elements can no longer be added (as it may break the symmetry/bound checking)
Definition at line 309 of file Ring.cpp.
References appendElement(), buildRingSections(), checkAndClose(), isClosed_m, isLocked_m, section_list_m, and symmetry_m.
makeSharable()
void ElementBase::makeSharable () virtual inherited
Set sharable flag.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 201 of file ElementBase.cpp.
References shareFlag.
Referenced by OpalMarker::OpalMarker().
Online()
bool Component::Online () virtual inherited
Definition at line 47 of file Component.cpp.
References online_m.
operator=()
Ring & Ring::operator= (const Ring & ring) private
Disabled
References Ring().
releasePosition()
void ElementBase::releasePosition () inline inherited
Definition at line 594 of file ElementBase.h.
References positionIsFixed.
Referenced by OpalRBend::update(), and OpalSBend::update().
removeAttribute()
void ElementBase::removeAttribute (const std::string & aKey) virtual inherited
Remove an existing attribute.
Definition at line 169 of file ElementBase.cpp.
References userAttribs.
resetAzimuths()
void Ring::resetAzimuths () private
Definition at line 338 of file Ring.cpp.
References section_list_m.
rotateToCyclCoordinates()
void Ring::rotateToCyclCoordinates (Euclid3D & euclid3d) const private
Definition at line 227 of file Ring.cpp.
References Rotation3D::getAxis(), Euclid3D::getRotation(), and Euclid3D::getVector().
Referenced by appendElement().
sectionCompare()
bool Ring::sectionCompare (RingSection const *const sec1, RingSection const *const sec2) static private
Definition at line 388 of file Ring.cpp.
setActionRange()
void ElementBase::setActionRange (const std::queue< std::pair< double, double > > & range) inline inherited
Definition at line 600 of file ElementBase.h.
References actionRange_m, and elementEdge_m.
setAperture()
void ElementBase::setAperture (const ApertureType & type, const std::vector< double > & args) inline inherited
Definition at line 576 of file ElementBase.h.
References aperture_m.
Referenced by Component::Component(), TEST_F(), TEST_F(), TEST_F(), OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
setAttribute()
void ElementBase::setAttribute (const std::string & aKey, double val) virtual inherited
Set value of an attribute.
Definition at line 171 of file ElementBase.cpp.
References getChannel(), and Channel::isSettable().
Referenced by update(), and OpalElement::updateUnknown().
setBeamPhiInit()
void Ring::setBeamPhiInit (double phiInit) inline
Set the initial beam azimuthal angle
Definition at line 243 of file Ring.h.
References beamPhiInit_m.
Referenced by OpalRingDefinition::update().
setBeamPRInit()
void Ring::setBeamPRInit (double pRInit) inline
Set the initial beam radial momentum
Definition at line 249 of file Ring.h.
References beamPRInit_m.
Referenced by OpalRingDefinition::update().
setBeamRInit()
void Ring::setBeamRInit (double rInit) inline
Set the initial beam radius
Definition at line 237 of file Ring.h.
References beamRInit_m.
Referenced by OpalRingDefinition::update().
setBoundaryGeometry()
void ElementBase::setBoundaryGeometry (BoundaryGeometry * geo) virtual inherited
attach a boundary geometry field to the element
Definition at line 215 of file ElementBase.cpp.
References bgeometry_m.
setCSTrafoGlobal2Local()
void ElementBase::setCSTrafoGlobal2Local (const CoordinateSystemTrafo & ori) inline inherited
Definition at line 522 of file ElementBase.h.
References csTrafoGlobal2Local_m, and positionIsFixed.
Referenced by setPlacementPose(), TEST_F(), OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
setCurrentSCoordinate()
void ElementBase::setCurrentSCoordinate (double s) inherited
Definition at line 223 of file ElementBase.cpp.
References actionRange_m, and elementEdge_m.
setDesignEnergy()
void Component::setDesignEnergy (const double & energy, bool changeable = true) inline virtual inherited
Reimplemented in BendBase, Corrector, and RFCavity.
Definition at line 252 of file Component.h.
setElementLength()
void ElementBase::setElementLength (double length) inline virtual inherited
Set design length.
Reimplemented in ConstantEFieldCavityRep, and MultipoleT.
Definition at line 482 of file ElementBase.h.
References getGeometry(), and BGeometryBase::setElementLength().
Referenced by MultipoleT::setElementLength(), BendBase::setLength(), SequenceMember::setLength(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), OpalCavity::update(), OpalMonitor::update(), OpalMultipole::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalSolenoid::update(), and OpalTravelingWave::update().
setElementPosition()
void ElementBase::setElementPosition (double elemedge) inline inherited
Access to ELEMEDGE attribute.
Definition at line 612 of file ElementBase.h.
References elemedgeSet_m, and elementPosition_m.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and OpalElement::update().
setExitFaceSlope()
void Component::setExitFaceSlope (const double & m) inline inherited
Definition at line 250 of file Component.h.
References exit_face_slope_m.
setFlagDeleteOnTransverseExit()
void ElementBase::setFlagDeleteOnTransverseExit (bool flag = true) inline inherited
Definition at line 629 of file ElementBase.h.
References deleteOnTransverseExit_m.
Referenced by OpalElement::update().
setHarmonicNumber()
void Ring::setHarmonicNumber (double cyclHarm) inline
Set the harmonic number for RF (number of bunches in the ring)
Definition at line 224 of file Ring.h.
References cyclHarm_m.
Referenced by OpalRingDefinition::update().
setIsClosed()
void Ring::setIsClosed (bool isClosed) inline
Set flag for closure checking
Definition at line 294 of file Ring.h.
References isClosed_m.
Referenced by OpalRingDefinition::update().
setLatticePhiInit()
void Ring::setLatticePhiInit (double phiInit) inline
Set the initial element's azimuthal angle
Definition at line 261 of file Ring.h.
References latticePhiInit_m.
Referenced by OpalRingDefinition::update().
setLatticeRInit()
void Ring::setLatticeRInit (double rInit) inline
Set the initial element's radius
Definition at line 255 of file Ring.h.
References latticeRInit_m.
Referenced by OpalRingDefinition::update().
setLatticeThetaInit()
void Ring::setLatticeThetaInit (double thetaInit) inline
Set the first element's horizontal angle
Set the angle in the ring plane with respect to the tangent vector
Definition at line 276 of file Ring.h.
References latticeThetaInit_m.
Referenced by OpalRingDefinition::update().
setLossDataSink()
void Ring::setLossDataSink (LossDataSink * sink)
Set LossDataSink to sink.
Parameters
sink The LossDataSink. Ring takes ownership of memory allocated to sink
Definition at line 172 of file Ring.cpp.
References lossDS_m.
Referenced by finalise(), and initialise().
setMisalignment()
void ElementBase::setMisalignment (const CoordinateSystemTrafo & cst) inline inherited
Definition at line 590 of file ElementBase.h.
References misalignment_m.
Referenced by TEST_F(), and OpalElement::update().
setName()
void ElementBase::setName (const std::string & name) virtual inherited
Set element name.
Definition at line 133 of file ElementBase.cpp.
References elementID.
Referenced by Sequence::insertDrifts(), and VariableRFCavity::operator=().
setOutputFN()
void ElementBase::setOutputFN (std::string fn) inherited
Set output filename.
Definition at line 135 of file ElementBase.cpp.
Referenced by OpalMonitor::update(), and OpalProbe::update().
setParticleMatterInteraction()
void ElementBase::setParticleMatterInteraction (ParticleMatterInteractionHandler * spys) virtual inherited
Definition at line 219 of file ElementBase.cpp.
References parmatint_m.
setPlacementPose()
void ElementBase::setPlacementPose (const PlacementPose & pose) inline inherited
Set the nominal rigid placement transform of the element.
This bridge setter preserves the existing storage model by delegating to setCSTrafoGlobal2Local().
Definition at line 554 of file ElementBase.h.
References PlacementPose::getParentToNominal(), and setCSTrafoGlobal2Local().
setRefPartBunch()
void Ring::setRefPartBunch (PartBunch_t * bunch)
Set RefPartBunch_t to bunch.
Parameters
sink The Bunch. Ring borrows memory allocated to bunch.
Note for compliance with style guide and compatibility with parent two pointer to RefPartBunch_t are stored; this keeps them aligned
Definition at line 197 of file Ring.cpp.
References Component::RefPartBunch_m, and refPartBunch_m.
Referenced by initialise(), Ring(), and Ring().
setRFFreq()
void Ring::setRFFreq (double rfFreq) inline
Set the nominal RF frequency
Definition at line 231 of file Ring.h.
References rfFreq_m.
Referenced by OpalRingDefinition::update().
setRingAperture()
void Ring::setRingAperture (double minR, double maxR)
Set the ring aperture limits
minR; the minimum radius allowed during tracking. Throws if minR < 0
maxR; the maximum radius allowed during tracking. Throws if maxR < 0 Sets willDoRingAperture_m to true.
Definition at line 392 of file Ring.cpp.
References maxR2_m, minR2_m, and willDoAperture_m.
Referenced by OpalRingDefinition::update().
setRotationAboutZ()
void ElementBase::setRotationAboutZ (double rotation) inline inherited
Set rotation about z axis in bend frame.
Definition at line 606 of file ElementBase.h.
References rotationZAxis_m.
Referenced by OpalElement::update().
setScale()
void Ring::setScale (double scale) inline
Set the scaling factor for the fields
Definition at line 288 of file Ring.h.
References scale_m.
Referenced by OpalRingDefinition::update().
setSymmetry()
void Ring::setSymmetry (double symmetry) inline
Set the rotational symmetry of the ring (number of cells)
Definition at line 285 of file Ring.h.
References symmetry_m.
Referenced by OpalRingDefinition::update().
setWake()
void ElementBase::setWake (WakeFunction * wf) virtual inherited
attach a wake field to the element
Definition at line 211 of file ElementBase.cpp.
References wake_m.
trackBunch()
void Component::trackBunch (PartBunch_t & bunch, const PartData & , bool revBeam, bool revTrack) const virtual inherited
Track a borrowed particle bunch through a non-standard component.
The default implementation throws a LogicalError.
Parameters
bunch Particle bunch to track. The component does not take ownership.
Definition at line 35 of file Component.cpp.
References ElementBase::getName().
Referenced by Tracker::visitComponent().
trackMap()
void Component::trackMap (FVps< double, 6 > & map, const PartData & , bool revBeam, bool revTrack) const virtual inherited
Track a map.
Definition at line 39 of file Component.cpp.
References ElementBase::getName().
update()
bool ElementBase::update (const AttributeSet & set) inherited
Update element.
Definition at line 203 of file ElementBase.cpp.
References AttributeSet::begin(), AttributeSet::end(), and setAttribute().
Member Data Documentation
actionRange_m
std::queue<std::pair<double, double> > ElementBase::actionRange_m private inherited
Definition at line 468 of file ElementBase.h.
Referenced by setActionRange(), and setCurrentSCoordinate().
angleTolerance_m
const double Ring::angleTolerance_m = 1e-2 static private
Definition at line 413 of file Ring.h.
Referenced by checkAndClose(), and checkMidplane().
aperture_m
std::pair<ApertureType, std::vector<double> > ElementBase::aperture_m protected inherited
Definition at line 439 of file ElementBase.h.
Referenced by ElementBase(), getAperture(), isInsideTransverse(), and setAperture().
beamPhiInit_m
double Ring::beamPhiInit_m private
Definition at line 375 of file Ring.h.
Referenced by getBeamPhiInit(), Ring(), Ring(), and setBeamPhiInit().
beamPRInit_m
double Ring::beamPRInit_m private
Definition at line 374 of file Ring.h.
Referenced by getBeamPRInit(), Ring(), Ring(), and setBeamPRInit().
beamRInit_m
double Ring::beamRInit_m private
Definition at line 373 of file Ring.h.
Referenced by getBeamRInit(), Ring(), Ring(), and setBeamRInit().
bgeometry_m
BoundaryGeometry* ElementBase::bgeometry_m private inherited
Definition at line 459 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getBoundaryGeometry(), hasBoundaryGeometry(), and setBoundaryGeometry().
csTrafoGlobal2Local_m
CoordinateSystemTrafo ElementBase::csTrafoGlobal2Local_m protected inherited
Definition at line 436 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getBoundingBoxInLabCoords(), getCSTrafoGlobal2Local(), and setCSTrafoGlobal2Local().
cyclHarm_m
double Ring::cyclHarm_m private
Definition at line 401 of file Ring.h.
Referenced by getHarmonicNumber(), Ring(), Ring(), and setHarmonicNumber().
defaultAperture_m
const std::vector< double > Component::defaultAperture_m = std::vector<double>({1e6, 1e6, 1.0}) static protected inherited
Definition at line 221 of file Component.h.
Referenced by Component().
deleteOnTransverseExit_m
bool ElementBase::deleteOnTransverseExit_m = true private inherited
Definition at line 472 of file ElementBase.h.
Referenced by ElementBase(), getFlagDeleteOnTransverseExit(), and setFlagDeleteOnTransverseExit().
elemedgeSet_m
bool ElementBase::elemedgeSet_m private inherited
Definition at line 466 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getElementPosition(), isElementPositionSet(), and setElementPosition().
elementEdge_m
double ElementBase::elementEdge_m protected inherited
Definition at line 441 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), setActionRange(), and setCurrentSCoordinate().
elementID
std::string ElementBase::elementID private inherited
Definition at line 450 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getName(), and setName().
elementPosition_m
double ElementBase::elementPosition_m private inherited
ELEMEDGE attribute.
Definition at line 465 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getElementPosition(), and setElementPosition().
elementTypeToString_s
const std::map< ElementType, std::string > ElementBase::elementTypeToString_s static private inherited
Initial value:
= {
        {ElementType::ANY, "Any"},
        {ElementType::BEAMLINE, "Beamline"},
        {ElementType::DRIFT, "Drift"},
        {ElementType::LASER, "Laser"},
        {ElementType::MARKER, "Marker"},
        {ElementType::MULTIPOLE, "Multipole"},
        {ElementType::RFCAVITY, "RFCavity"},
        {ElementType::TRAVELINGWAVE, "TravelingWave"},
        {ElementType::SBEND, "SBEND"},
        {ElementType::RBEND, "RBEND"},
        {ElementType::RBEND3D, "RBEND3D"},
        {ElementType::RING, "Ring"},
        {ElementType::SOURCE, "SOURCE"},
        {ElementType::SOLENOID, "SOLENOID"},
        {ElementType::PROBE, "Probe"},
        {ElementType::VACUUM, "Vacuum"},
        {ElementType::CONSTANTEFIELDCAVITY, "ConstantEFieldCavity"}}
Definition at line 73 of file ElementBase.h.
Referenced by getTypeString().
exit_face_slope_m
double Component::exit_face_slope_m protected inherited
Definition at line 222 of file Component.h.
Referenced by Component(), Component(), and setExitFaceSlope().
isClosed_m
bool Ring::isClosed_m private
Definition at line 393 of file Ring.h.
Referenced by getIsClosed(), lockRing(), Ring(), Ring(), and setIsClosed().
isLocked_m
bool Ring::isLocked_m private
Definition at line 389 of file Ring.h.
Referenced by appendElement(), lockRing(), Ring(), and Ring().
latticePhiInit_m
double Ring::latticePhiInit_m private
Definition at line 379 of file Ring.h.
Referenced by getLatticePhiInit(), getNextNormal(), getNextPosition(), Ring(), Ring(), and setLatticePhiInit().
latticeRInit_m
double Ring::latticeRInit_m private
Definition at line 378 of file Ring.h.
Referenced by getLatticeRInit(), getNextPosition(), Ring(), Ring(), and setLatticeRInit().
latticeThetaInit_m
double Ring::latticeThetaInit_m private
Definition at line 380 of file Ring.h.
Referenced by getLatticeThetaInit(), getNextNormal(), Ring(), Ring(), and setLatticeThetaInit().
lengthTolerance_m
const double Ring::lengthTolerance_m = 1e-2 static private
Definition at line 412 of file Ring.h.
Referenced by checkAndClose(), and checkMidplane().
lossDS_m
LossDataSink* Ring::lossDS_m private
Definition at line 370 of file Ring.h.
Referenced by finalise(), Ring(), Ring(), and setLossDataSink().
maxR2_m
double Ring::maxR2_m private
Definition at line 386 of file Ring.h.
Referenced by apply(), getRingMaxR(), Ring(), and setRingAperture().
minR2_m
double Ring::minR2_m private
Definition at line 385 of file Ring.h.
Referenced by getRingMinR(), Ring(), and setRingAperture().
misalignment_m
CoordinateSystemTrafo ElementBase::misalignment_m protected inherited
Definition at line 437 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getMisalignment(), and setMisalignment().
online_m
bool Component::online_m protected inherited
Definition at line 226 of file Component.h.
Referenced by Component(), Component(), Probe::doGoOffline(), BendBase::finalise(), Multipole::finalise(), PluginElement::finalise(), Ring::finalise(), goOffline(), PluginElement::goOffline(), RFCavity::goOffline(), Solenoid::goOffline(), goOnline(), Corrector::goOnline(), Monitor::goOnline(), RFCavity::goOnline(), Solenoid::goOnline(), TravelingWave::goOnline(), BendBase::initialise(), Multipole::initialise(), Ring::initialise(), Online(), and PluginElement::~PluginElement().
outputfn_m
std::string ElementBase::outputfn_m private inherited
The name of the outputfile
Definition at line 470 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), and getOutputFN().
parmatint_m
ParticleMatterInteractionHandler* ElementBase::parmatint_m private inherited
Definition at line 461 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getParticleMatterInteraction(), hasParticleMatterInteraction(), and setParticleMatterInteraction().
phiStep_m
double Ring::phiStep_m private
Definition at line 407 of file Ring.h.
Referenced by buildRingSections(), Ring(), and Ring().
planarArcGeometry_m
PlanarArcGeometry Ring::planarArcGeometry_m private
Definition at line 359 of file Ring.h.
Referenced by getGeometry(), getGeometry(), Ring(), and Ring().
positionIsFixed
bool ElementBase::positionIsFixed private inherited
Definition at line 463 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), fixPosition(), isPositioned(), releasePosition(), and setCSTrafoGlobal2Local().
RefPartBunch_m
PartBunch_t* Component::RefPartBunch_m protected inherited
Definition at line 225 of file Component.h.
Referenced by BendBase::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Corrector::apply(), Multipole::apply(), MultipoleT::apply(), MultipoleT::apply(), RFCavity::apply(), RFCavity::apply(), Ring::apply(), ScalingFFAMagnet::apply(), Solenoid::apply(), TravelingWave::apply(), TravelingWave::apply(), VariableRFCavity::apply(), VariableRFCavity::apply(), VerticalFFAMagnet::apply(), BendBase::calcDesignRadius(), BendBase::calcFieldAmplitude(), BendBase::calcGamma(), Component(), MultipoleT::finalise(), ScalingFFAMagnet::finalise(), VariableRFCavity::finalise(), VerticalFFAMagnet::finalise(), Corrector::goOnline(), BendBase::initialise(), ConstantEFieldCavity::initialise(), Corrector::initialise(), Drift::initialise(), Laser::initialise(), Marker::initialise(), Monitor::initialise(), Multipole::initialise(), MultipoleT::initialise(), PluginElement::initialise(), RFCavity::initialise(), RFCavity::initialise(), ScalingFFAMagnet::initialise(), Solenoid::initialise(), TravelingWave::initialise(), VariableRFCavity::initialise(), VerticalFFAMagnet::initialise(), VariableRFCavity::initNull(), Multipole::isFocusing(), MultipoleT::MultipoleT(), ScalingFFAMagnet::ScalingFFAMagnet(), Corrector::setDesignEnergy(), Ring::setRefPartBunch(), RFCavity::trackOnAxisParticle(), and VerticalFFAMagnet::VerticalFFAMagnet().
refPartBunch_m
PartBunch_t* Ring::refPartBunch_m private
Definition at line 365 of file Ring.h.
Referenced by apply(), Ring(), Ring(), and setRefPartBunch().
rfFreq_m
double Ring::rfFreq_m private
Definition at line 404 of file Ring.h.
Referenced by getRFFreq(), Ring(), and setRFFreq().
ringSections_m
std::vector<RingSectionList> Ring::ringSections_m private
Definition at line 408 of file Ring.h.
Referenced by buildRingSections(), Ring(), and Ring().
rotationZAxis_m
double ElementBase::rotationZAxis_m protected inherited
Definition at line 443 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getRotationAboutZ(), and setRotationAboutZ().
scale_m
double Ring::scale_m = 1. private
Definition at line 398 of file Ring.h.
Referenced by apply(), and setScale().
section_list_m
RingSectionList Ring::section_list_m private
Definition at line 409 of file Ring.h.
Referenced by appendElement(), buildRingSections(), checkAndClose(), getLastSectionPlaced(), getNextNormal(), getNextPosition(), getSectionsAt(), lockRing(), resetAzimuths(), Ring(), Ring(), and ~Ring().
shareFlag
bool ElementBase::shareFlag mutable protected inherited
Definition at line 434 of file ElementBase.h.
Referenced by Beamline::Beamline(), Beamline::Beamline(), Beamline::Beamline(), ElementBase(), ElementBase(), isSharable(), makeSharable(), and TBeamline< T >::makeSharable().
symmetry_m
int Ring::symmetry_m private
Definition at line 396 of file Ring.h.
Referenced by getSymmetry(), lockRing(), Ring(), Ring(), and setSymmetry().
userAttribs
AttributeSet ElementBase::userAttribs private inherited
Definition at line 455 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getChannel(), and removeAttribute().
wake_m
WakeFunction* ElementBase::wake_m private inherited
Definition at line 457 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getWake(), hasWake(), and setWake().
willDoAperture_m
bool Ring::willDoAperture_m = false private
Definition at line 384 of file Ring.h.
Referenced by apply(), Ring(), and setRingAperture().
The documentation for this class was generated from the following files:
Ring.h
Ring.cpp