OPALX (Object Oriented Parallel Accelerator Library for Exascal): Object Class Reference
Object Class Reference abstract
The base class for all OPAL objects.
#include <Object.h>
Public Member Functions
virtual ~Object ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual Object * clone (const std::string &name)=0
Return a clone.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual const std::string getCategory () const =0
Return the object category as a string.
virtual bool shouldTrace () const =0
Trace flag.
virtual bool shouldUpdate () const =0
Update flag.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Attributes
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Attributes
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Private Member Functions
Object ()
Object (const Object &object)
void operator= (const Object &)
Private Attributes
Object * itsParent
std::string itsName
std::string itsHelp
int occurrence
double timeStamp
std::set< Invalidator * > references
bool sharedFlag
Detailed Description
The base class for all OPAL objects.
Definition at line 45 of file Object.h.
Constructor & Destructor Documentation
~Object()
Object::~Object () virtual
Definition at line 38 of file Object.cpp.
References references.
Object() [1/4]
Object::Object (int size, const char * name, const char * help) protected
Constructor for exemplars.
Definition at line 291 of file Object.cpp.
References builtin, flagged, itsAttr, itsHelp, itsName, itsParent, modified, occurrence, and sharedFlag.
Referenced by Action::Action(), Action::Action(), Action::canReplaceBy(), Beam::canReplaceBy(), BoolConstant::canReplaceBy(), BoundaryGeometry::canReplaceBy(), Distribution::canReplaceBy(), Element::canReplaceBy(), EmissionSource::canReplaceBy(), EmissionSourceList::canReplaceBy(), canReplaceBy(), OpalFilter::canReplaceBy(), RealConstant::canReplaceBy(), RealVariable::canReplaceBy(), RealVector::canReplaceBy(), StringConstant::canReplaceBy(), Table::canReplaceBy(), clone(), copyAttributes(), Definition::Definition(), Definition::Definition(), Element::Element(), Element::Element(), Help::execute(), Select::execute(), EmissionSource::find(), EmissionSourceList::find(), getBaseObject(), getParent(), isTreeMember(), LineTemplate::Line, Line::LineTemplate, LineTemplate::LineTemplate(), Macro::Macro(), Macro::Macro(), LineTemplate::makeInstance(), MacroCmd::makeInstance(), makeInstance(), SequenceTemplate::makeInstance(), Line::makeTemplate(), LineTemplate::makeTemplate(), MacroCmd::makeTemplate(), makeTemplate(), Sequence::makeTemplate(), SequenceTemplate::makeTemplate(), Object(), Object(), Line::operator=(), LineTemplate::operator=(), operator=(), SequenceTemplate::operator=(), EmissionSourceList::parseList(), print(), OpalElement::print(), Line::replace(), replace(), Sequence::replace(), SequenceTemplate::Sequence, SequenceTemplate::SequenceTemplate(), setParent(), shouldUpdate(), Table::Table(), Table::Table(), ValueDefinition::ValueDefinition(), and ValueDefinition::ValueDefinition().
Object() [2/4]
Object::Object (const std::string & name, Object * parent) protected
Constructor for clones.
Definition at line 301 of file Object.cpp.
References builtin, flagged, itsAttr, itsHelp, itsName, itsParent, modified, Object(), occurrence, and sharedFlag.
Object() [3/4]
Object::Object () private
Object() [4/4]
Object::Object (const Object & object) private
References Object().
Member Function Documentation
canReplaceBy()
bool Object::canReplaceBy (Object * object) virtual
Test if replacement is allowed.
Reimplemented in Action, Beam, BoolConstant, BoundaryGeometry, Distribution, Element, EmissionSource, EmissionSourceList, OpalFilter, RealConstant, RealVariable, RealVector, StringConstant, and Table.
Definition at line 45 of file Object.cpp.
References Object().
Referenced by OpalData::define().
clear()
void Object::clear ()
Clear the occurrence counter.
Definition at line 285 of file Object.cpp.
References occurrence.
clone()
virtual Object * Object::clone (const std::string & name) pure virtual
Return a clone.
Implemented in Beam, BinningCmd, BoolConstant, BoundaryGeometry, Call, Distribution, DumpEMFields, Echo, EmissionSource, EmissionSourceList, FieldSolverCmd, Help, Line, LineTemplate, Macro, OpalCavity, OpalConstantEFieldCavity, OpalDrift, OpalFilter, OpalLaser, OpalMarker, OpalMonitor, OpalMultipole, OpalMultipoleT, OpalPolynomialTimeDependence, OpalProbe, OpalQuadrupole, OpalRBend, OpalRingDefinition, OpalSBend, OpalSinusoidalTimeDependence, OpalSolenoid, OpalSource, OpalSplineTimeDependence, OpalTravelingWave, OpalVacuum, OpalVariableRFCavity, OpalVerticalFFAMagnet, Option, PSystem, Quit, RealConstant, RealVariable, RealVector, Select, Sequence, SequenceTemplate, Stop, StringConstant, System, Title, TrackCmd, TrackEnd, TrackRun, and Value.
References Object().
Referenced by OpalParser::parseAction(), OpalParser::parseAssign(), and OpalParser::parseDefine().
copyAttributes()
void Object::copyAttributes (const Object & source)
Copy attributes from another object.
Definition at line 50 of file Object.cpp.
References itsAttr, and Object().
Referenced by LineTemplate::makeInstance(), and SequenceTemplate::makeInstance().
execute()
void Object::execute () virtual
Execute the command.
Reimplemented in Beam, BinningCmd, BoundaryGeometry, Call, Distribution, DumpEMFields, Echo, EmissionSource, EmissionSourceList, FieldSolverCmd, Help, MacroCmd, OpalFilter, Option, PSystem, Quit, Select, Stop, System, Title, TrackCmd, TrackEnd, TrackRun, and Value.
Definition at line 52 of file Object.cpp.
findAttribute() [1/2]
Attribute * Object::findAttribute (const std::string & name) virtual
Find an attribute by name.
Definition at line 56 of file Object.cpp.
References itsAttr.
Referenced by OpalElement::getParticleMatterInteraction(), OpalElement::getTypeName(), OpalElement::getWakeF(), Line::parse(), parse(), OpalElement::parse(), OpalParser::parseAssign(), SequenceParser::parsePosition(), TrackRun::print(), and TEST().
findAttribute() [2/2]
const Attribute * Object::findAttribute (const std::string & name) const virtual
Find an attribute by name.
Definition at line 63 of file Object.cpp.
References itsAttr.
getBaseObject()
const Object * Object::getBaseObject () const
Return the object's base type object.
Definition at line 260 of file Object.cpp.
References itsParent, and Object().
getCategory()
virtual const std::string Object::getCategory () const pure virtual
Return the object category as a string.
Implemented in Action, BeamSequence, Definition, Element, Macro, Table, and ValueDefinition.
Referenced by OpalData::getVariableNames().
getOpalName()
const std::string & Object::getOpalName () const
Return object name.
Definition at line 267 of file Object.cpp.
References itsName.
Referenced by Macro::clone(), OpalVariableRFCavity::clone(), OpalData::create(), OpalData::define(), Sequence::findDriftLength(), ValueDefinition::getBool(), ValueDefinition::getBoolComponent(), ValueDefinition::getReal(), ValueDefinition::getRealComponent(), ValueDefinition::getString(), ValueDefinition::getStringComponent(), LineTemplate::makeInstance(), makeInstance(), SequenceTemplate::makeInstance(), parse(), SequenceParser::parsePosition(), Beam::print(), BoolConstant::print(), Line::print(), print(), OpalElement::print(), OpalFilter::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), Sequence::print(), StringConstant::print(), TrackRun::print(), BinningCmd::printInfo(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), registerOwnership(), OpalElement::registerOwnership(), Line::replace(), Sequence::replace(), PartBunch< T, Dim >::setBins(), TEST(), TEST(), TEST(), TEST_F(), Beam::update(), BoundaryGeometry::update(), OpalFilter::update(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), and OpalSplineTimeDependence::update().
getParent()
Object * Object::getParent () const
Return parent pointer.
Definition at line 269 of file Object.cpp.
References itsParent, and Object().
Referenced by OpalData::erase(), print(), OpalElement::print(), registerOwnership(), and OpalElement::registerOwnership().
increment()
int Object::increment ()
Increment and return the occurrence counter.
Definition at line 287 of file Object.cpp.
References occurrence.
Referenced by Line::parse(), and Sequence::storeLine().
isBuiltin()
bool Object::isBuiltin () const
True, if [b]this[/b] is a built-in object.
Definition at line 243 of file Object.cpp.
References builtin.
Referenced by OpalData::define(), and OpalData::getVariableNames().
isDirty()
bool Object::isDirty () const
True, if the [b]modified[/b] flag is set.
Definition at line 254 of file Object.cpp.
References modified.
isFlagged()
bool Object::isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
Definition at line 258 of file Object.cpp.
References flagged.
isShared()
bool Object::isShared () const virtual
Shared flag.
Definition at line 245 of file Object.cpp.
References sharedFlag.
Referenced by Sequence::print().
isTreeMember()
bool Object::isTreeMember (const Object * subTree) const
Test for tree membership.
Definition at line 271 of file Object.cpp.
References Object().
Referenced by Selector::handleElement(), and OpalParser::parseAssign().
makeInstance()
Object * Object::makeInstance (const std::string & name, Statement & , const Parser *) virtual
Macro handler function.
Reimplemented in LineTemplate, MacroCmd, and SequenceTemplate.
Definition at line 76 of file Object.cpp.
References getOpalName(), and Object().
Referenced by OpalParser::parseDefine(), and OpalParser::parseMacro().
makeTemplate()
Object * Object::makeTemplate (const std::string & name, TokenStream & , Statement &) virtual
Macro handler function.
Reimplemented in Line, LineTemplate, MacroCmd, Sequence, and SequenceTemplate.
Definition at line 71 of file Object.cpp.
References Object().
Referenced by OpalParser::parseMacro().
occurrenceCount()
int Object::occurrenceCount ()
Return the occurrence counter.
Definition at line 289 of file Object.cpp.
References occurrence.
operator=()
void Object::operator= (const Object &) private
References Object().
parse()
void Object::parse (Statement & stat) virtual
Parse the object.
Reimplemented in Call, Echo, EmissionSourceList, Help, Line, OpalElement, PSystem, Sequence, System, Title, and Value.
Definition at line 82 of file Object.cpp.
References Statement::delimiter(), findAttribute(), getOpalName(), Expressions::parseDelimiter(), Expressions::parseRealConst(), and Expressions::parseString().
Referenced by Sequence::parse(), OpalParser::parseAction(), OpalParser::parseDefine(), and SequenceTemplate::parseTemplate().
parseShortcut()
void Object::parseShortcut (Statement & stat, bool eval = true) virtual
Parser for single-attribute commands.
Definition at line 113 of file Object.cpp.
Referenced by Call::parse(), Echo::parse(), Help::parse(), PSystem::parse(), System::parse(), Title::parse(), and Value::parse().
print()
void Object::print (std::ostream & msg) const virtual
Print the object.
Reimplemented in Beam, BoolConstant, DumpEMFields, Line, OpalBend, OpalElement, OpalFilter, OpalMarker, OpalMultipole, OpalMultipoleT, OpalPolynomialTimeDependence, OpalQuadrupole, OpalRingDefinition, OpalSinusoidalTimeDependence, OpalSplineTimeDependence, RealConstant, RealVariable, RealVector, Sequence, StringConstant, and TrackRun.
Definition at line 146 of file Object.cpp.
References getOpalName(), getParent(), itsAttr, and Object().
Referenced by printValue().
printHelp()
void Object::printHelp (std::ostream &) const virtual
Print help.
Definition at line 179 of file Object.cpp.
References gmsg, itsAttr, and itsHelp.
Referenced by Help::execute(), and main().
printValue()
void Object::printValue (std::ostream & os) const inline virtual
Reimplemented in BoolConstant, RealConstant, RealVariable, RealVector, and StringConstant.
Definition at line 270 of file Object.h.
References print().
registerOwnership()
void Object::registerOwnership (const AttributeHandler::OwnerType & itsClass) const
Definition at line 169 of file Object.cpp.
References AttributeHandler::addAttributeOwner(), getOpalName(), getParent(), and itsAttr.
Referenced by Beam::Beam(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), Call::Call(), Distribution::Distribution(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), EmissionSourceList::EmissionSourceList(), Help::Help(), Line::Line(), OpalFilter::OpalFilter(), Option::Option(), PSystem::PSystem(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVector::RealVector(), Select::Select(), Sequence::Sequence(), StringConstant::StringConstant(), System::System(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), and Value::Value().
registerReference()
void Object::registerReference (Invalidator * a)
Register a reference to this object.
Definition at line 165 of file Object.cpp.
References references.
replace()
void Object::replace (Object * oldObject, Object * newObject) virtual
Replace references.
Reimplemented in Line, and Sequence.
Definition at line 235 of file Object.cpp.
References Object().
setDirty()
void Object::setDirty (bool dirty)
Set/reset the [b]modified[/b] flag.
Definition at line 249 of file Object.cpp.
References modified.
Referenced by OpalData::define(), OpalData::makeDirty(), and RealVariable::RealVariable().
setFlag()
void Object::setFlag (bool flag)
Flag/unflag this object, e. g. to control output of objects for.
Definition at line 256 of file Object.cpp.
References flagged.
setOpalName()
void Object::setOpalName (const std::string & name)
Set object name.
Definition at line 281 of file Object.cpp.
References itsName.
Referenced by TEST(), TEST(), TEST(), Beam::update(), BoundaryGeometry::update(), and OpalFilter::update().
setParent()
void Object::setParent (Object * parent)
Set parent object.
Definition at line 283 of file Object.cpp.
References itsParent, and Object().
Referenced by OpalData::erase().
setShared()
void Object::setShared (bool flag) virtual
Set/reset shared flag.
Reimplemented in Element.
Definition at line 247 of file Object.cpp.
References sharedFlag.
Referenced by OpalParser::parseDefine(), and Element::setShared().
shouldTrace()
virtual bool Object::shouldTrace () const pure virtual
Trace flag.
Implemented in Action, Definition, Element, Macro, Table, and ValueDefinition.
Referenced by OpalParser::execute().
shouldUpdate()
virtual bool Object::shouldUpdate () const pure virtual
Update flag.
Implemented in Action, Definition, Element, Macro, Table, and ValueDefinition.
References Object().
Referenced by OpalParser::execute().
unregisterReference()
void Object::unregisterReference (Invalidator * a)
Unegister a reference to this object.
Definition at line 167 of file Object.cpp.
References references.
update()
void Object::update () virtual
Update this object.
Reimplemented in Beam, BinningCmd, BoundaryGeometry, FieldSolverCmd, OpalCavity, OpalConstantEFieldCavity, OpalDrift, OpalElement, OpalFilter, OpalLaser, OpalMarker, OpalMonitor, OpalMultipole, OpalMultipoleT, OpalPolynomialTimeDependence, OpalProbe, OpalQuadrupole, OpalRBend, OpalRingDefinition, OpalSBend, OpalSinusoidalTimeDependence, OpalSolenoid, OpalSource, OpalSplineTimeDependence, OpalTravelingWave, OpalVacuum, OpalVariableRFCavity, OpalVerticalFFAMagnet, Option, and Sequence.
Definition at line 239 of file Object.cpp.
Referenced by Distribution::execute().
Member Data Documentation
builtin
bool Object::builtin protected
Built-in flag.
Definition at line 226 of file Object.h.
Referenced by Beam::Beam(), BoundaryGeometry::BoundaryGeometry(), isBuiltin(), Object(), Object(), OpalFilter::OpalFilter(), OpalMarker::OpalMarker(), RealConstant::RealConstant(), StringConstant::StringConstant(), and Table::~Table().
flagged
bool Object::flagged protected
Object flag.
Definition at line 235 of file Object.h.
Referenced by isFlagged(), Object(), Object(), and setFlag().
itsAttr
std::vector<Attribute> Object::itsAttr
The object attributes.
Definition at line 210 of file Object.h.
Referenced by Beam::Beam(), BinningCmd::BinningCmd(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), BoundaryGeometry::BoundaryGeometry(), DumpEMFields::buildGrid(), Call::Call(), FieldSolverCmd::constructBCHandler(), copyAttributes(), Distribution::Distribution(), BinningCmd::dumpBinsToFile(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), Beam::execute(), Call::execute(), Echo::execute(), Help::execute(), Option::execute(), PSystem::execute(), Select::execute(), System::execute(), Title::execute(), TrackCmd::execute(), TrackRun::execute(), Value::execute(), FieldSolverCmd::FieldSolverCmd(), findAttribute(), findAttribute(), BoundaryGeometry::getA(), OpalElement::getApert(), BoundaryGeometry::getB(), BinningCmd::getBinningAlpha(), BinningCmd::getBinningBeta(), FieldSolverCmd::getBinsName(), BoolConstant::getBool(), FieldSolverCmd::getBoxIncr(), Beam::getBunchCharge(), BoundaryGeometry::getC(), Beam::getCharge(), Beam::getCurrent(), Beam::getDaughterBeamName(), BinningCmd::getDesiredWidth(), EmissionSource::getDistributionName(), FieldSolverCmd::getDomDec(), TrackCmd::getDT(), TrackCmd::getDTAU(), TrackCmd::getDTSCINIT(), BinningCmd::getDumpBinsFileName(), BinningCmd::getDumpBinsFrequency(), EmissionSource::getEmissionModel(), Beam::getEmissionSourceListName(), BoundaryGeometry::getFilename(), Distribution::getFilename(), Beam::getFrequency(), Beam::getGlobalProcessNames(), BoundaryGeometry::getL1(), BoundaryGeometry::getL2(), BoundaryGeometry::getLength(), Line::getLength(), OpalElement::getLength(), Sequence::getLength(), Beam::getMass(), BinningCmd::getMaxBins(), TrackCmd::getMaxSteps(), Beam::getNumAlloc(), FieldSolverCmd::getNX(), FieldSolverCmd::getNY(), FieldSolverCmd::getNZ(), EmissionSource::getP0(), BinningCmd::getParameter(), Beam::getParticleName(), EmissionSource::getR0(), RealConstant::getReal(), RealVariable::getReal(), RealVector::getRealComponent(), Sequence::getReference(), BoundaryGeometry::getS(), EmissionSource::getShiftedGreensFunction(), TrackCmd::getStepsPerTurn(), StringConstant::getString(), EmissionSource::getT0(), TrackCmd::getT0(), BinningCmd::getTablePrintFrequency(), TrackCmd::getTimeIntegrator(), BoundaryGeometry::getTopology(), FieldSolverCmd::getType(), EmissionSource::getZerofaceMaxSteps(), EmissionSource::getZeroFacePlaneDumpFrequency(), EmissionSource::getZeroFaceR0Z(), TrackCmd::getZStart(), TrackCmd::getZStop(), Beam::hasExplicitEnergy(), Help::Help(), BoundaryGeometry::initialize(), OpalFilter::initOpalFilter(), Beam::isPhoton(), Line::Line(), Object(), Object(), OpalBend::OpalBend(), OpalCavity::OpalCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalDrift::OpalDrift(), OpalElement::OpalElement(), OpalFilter::OpalFilter(), OpalLaser::OpalLaser(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalPolynomialTimeDependence::OpalPolynomialTimeDependence(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalRingDefinition::OpalRingDefinition(), OpalSinusoidalTimeDependence::OpalSinusoidalTimeDependence(), OpalSolenoid::OpalSolenoid(), OpalSplineTimeDependence::OpalSplineTimeDependence(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), Option::Option(), Option::Option(), Line::parse(), Sequence::parse(), DumpEMFields::parseCoordinateSystem(), Beam::print(), BoolConstant::print(), DumpEMFields::print(), print(), OpalFilter::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), Sequence::print(), StringConstant::print(), printHelp(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), BoolConstant::printValue(), RealConstant::printValue(), RealVariable::printValue(), RealVector::printValue(), StringConstant::printValue(), PSystem::PSystem(), RealConstant::RealConstant(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVariable::RealVariable(), RealVector::RealVector(), registerOwnership(), OpalElement::registerOwnership(), Select::Select(), Select::select(), Sequence::Sequence(), Distribution::setAttributes(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCX(), OrbitThreaderTest::TestableFieldSolverCmd::setBCX(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCX(), TestMultipoleT::TestableFieldSolverCmd::setBCX(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCX(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCX(), TestVariableRFCavity::TestableFieldSolverCmd::setBCX(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCY(), OrbitThreaderTest::TestableFieldSolverCmd::setBCY(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCY(), TestMultipoleT::TestableFieldSolverCmd::setBCY(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCY(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCY(), TestVariableRFCavity::TestableFieldSolverCmd::setBCY(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCZ(), OrbitThreaderTest::TestableFieldSolverCmd::setBCZ(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCZ(), TestMultipoleT::TestableFieldSolverCmd::setBCZ(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCZ(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCZ(), TestVariableRFCavity::TestableFieldSolverCmd::setBCZ(), TestableBinningCmd::setBinningAlpha(), TestableBinningCmd::setBinningBeta(), TestableBinningCmd::setDesiredWidth(), Distribution::setDistParametersFlatTop(), Distribution::setDistParametersMultiVariateGauss(), Distribution::setDistType(), TestableBinningCmd::setDumpBinsFile(), TestableBinningCmd::setDumpBinsFreq(), TestableBinningCmd::setMaxBins(), FieldSolverCmd::setNX(), FieldSolverCmd::setNY(), FieldSolverCmd::setNZ(), TestableBinningCmd::setParameterString(), TrackRun::setRunMethod(), Distribution::setSigmaP_m(), Distribution::setSigmaR_m(), TestableBinningCmd::setTablePrintFrequency(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setType(), OrbitThreaderTest::TestableFieldSolverCmd::setType(), SolenoidPlacementTest::TestableFieldSolverCmd::setType(), TestMultipoleT::TestableFieldSolverCmd::setType(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setType(), TestMultipoleTStraight::TestableFieldSolverCmd::setType(), TestVariableRFCavity::TestableFieldSolverCmd::setType(), TrackRun::setupBoundaryGeometry(), StringConstant::StringConstant(), StringConstant::StringConstant(), System::System(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), Beam::update(), BinningCmd::update(), FieldSolverCmd::update(), OpalCavity::update(), OpalConstantEFieldCavity::update(), OpalDrift::update(), OpalElement::update(), OpalLaser::update(), OpalMonitor::update(), OpalMultipole::update(), OpalMultipoleT::update(), OpalPolynomialTimeDependence::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalRBend::update(), OpalRingDefinition::update(), OpalSBend::update(), OpalSinusoidalTimeDependence::update(), OpalSolenoid::update(), OpalSplineTimeDependence::update(), OpalTravelingWave::update(), OpalVacuum::update(), OpalVariableRFCavity::update(), OpalVerticalFFAMagnet::update(), Option::update(), OpalElement::updateUnknown(), Value::Value(), ValueDefinition::value(), and ValueDefinition::value().
itsHelp
std::string Object::itsHelp private
Definition at line 250 of file Object.h.
Referenced by Object(), Object(), and printHelp().
itsName
std::string Object::itsName private
Definition at line 247 of file Object.h.
Referenced by getOpalName(), Object(), Object(), and setOpalName().
itsParent
Object* Object::itsParent private
Definition at line 244 of file Object.h.
Referenced by getBaseObject(), getParent(), Object(), Object(), and setParent().
modified
bool Object::modified protected
Dirty flag.
Definition at line 231 of file Object.h.
Referenced by isDirty(), Object(), Object(), and setDirty().
occurrence
int Object::occurrence private
Definition at line 253 of file Object.h.
Referenced by clear(), increment(), Object(), Object(), and occurrenceCount().
references
std::set<Invalidator*> Object::references private
Definition at line 260 of file Object.h.
Referenced by registerReference(), unregisterReference(), and ~Object().
sharedFlag
bool Object::sharedFlag private
Definition at line 263 of file Object.h.
Referenced by isShared(), Object(), Object(), and setShared().
timeStamp
double Object::timeStamp private
Definition at line 256 of file Object.h.
The documentation for this class was generated from the following files:
Object.h
Object.cpp