OPALX (Object Oriented Parallel Accelerator Library for Exascal): OpalData Class Reference
OpalData Class Reference
The global OPAL structure.
#include <OpalData.h>
Classes
struct ClearReference
Clear Reference.
Public Types
enum class OpenMode : unsigned short { UNDEFINED , WRITE , APPEND }
Enum for writing to files.
Public Member Functions
~OpalData ()
void reset ()
reset object for consecutive runs
void apply (const ObjectFunction &)
Apply a function to all objects.
void create (Object *newObject)
Create new object.
void define (Object *newObject)
Define a new object.
void erase (const std::string &name)
Delete existing entry.
Object * find (const std::string &name)
Find entry.
double getP0 () const
Return value of global reference momentum.
void makeDirty (Object *object)
Invalidate expressions.
void printNames (std::ostream &stream, const std::string &pattern)
Print all objects.
void printAllNames (std::ostream &stream)
void registerTable (Table *t)
Register table.
void unregisterTable (Table *t)
Unregister table.
void registerExpression (AttributeBase *)
Register expression.
void unregisterExpression (AttributeBase *)
Unregister expression.
void setP0 (ValueDefinition *p0)
Set the global momentum.
void storeTitle (const std::string &)
Store the page title.
void printTitle (std::ostream &)
Print the page title.
std::string getTitle ()
Get the title string.
void update ()
Update all objects.
std::map< std::string, std::string > getVariableData ()
std::vector< std::string > getVariableNames ()
bool isInOPALCyclMode ()
bool isInOPALTMode ()
bool isOptimizerRun ()
void setInOPALCyclMode ()
void setInOPALTMode ()
void setOptimizerFlag ()
bool isInPrepState ()
void setInPrepState (bool state)
bool hasPriorTrack ()
true if in follow-up track
void setPriorTrack (const bool &value=true)
true if in follow-up track
bool inRestartRun ()
true if we do a restart run
void setRestartRun (const bool &value=true)
set OPAL in restart mode
void setRestartStep (int s)
store the location where to restart
int getRestartStep ()
get the step where to restart
std::string getAuxiliaryOutputDirectory () const
get the name of the the additional data directory
std::string getInputFn ()
get opals input filename
std::string getInputBasename ()
get input file name without extension
void storeInputFn (const std::string &fn)
store opals input filename
void checkAndAddOutputFileName (const std::string &outfn)
checks the output file names of all items to avoid duplicates
std::string getRestartFileName ()
get opals restart h5 format filename
void setRestartFileName (std::string s)
store opals restart h5 format filename
bool hasRestartFile ()
true if we do a restart from specified h5 file
void setRestartDumpFreq (const int &N)
set the dump frequency as found in restart file
int getRestartDumpFreq () const
get the dump frequency as found in restart file
void setOpenMode (OpenMode openMode)
OpenMode getOpenMode () const
void setLastStep (const int &step)
set the last step in a run for possible follow-up run
int getLastStep () const
get the last step from a possible previous run
bool hasBunchAllocated ()
true if we already allocated a ParticleBunch object
void bunchIsAllocated ()
PartBunch_t * getPartBunch ()
void setPartBunch (PartBunch_t *p)
bool hasDataSinkAllocated ()
true if we already allocated a DataSink object
DataSink * getDataSink ()
void setDataSink (DataSink *s)
void setGlobalPhaseShift (double shift)
units: (sec)
double getGlobalPhaseShift ()
units: (sec)
void setGlobalGeometry (BoundaryGeometry *bg)
BoundaryGeometry * getGlobalGeometry ()
bool hasGlobalGeometry ()
void setMaxPhase (std::string elName, double phi)
std::vector< MaxPhasesT >::iterator getFirstMaxPhases ()
std::vector< MaxPhasesT >::iterator getLastMaxPhases ()
int getNumberOfMaxPhases ()
void addEnergyData (double spos, double ekin)
energyEvolution_t::iterator getFirstEnergyData ()
energyEvolution_t::iterator getLastEnergyData ()
unsigned long long getMaxTrackSteps ()
void setMaxTrackSteps (unsigned long long s)
void incMaxTrackSteps (unsigned long long s)
void addProblemCharacteristicValue (const std::string &name, unsigned int value)
const std::map< std::string, unsigned int > & getProblemCharacteristicValues () const
void storeArguments (int argc, char *argv[])
std::vector< std::string > getArguments ()
Static Public Member Functions
static OpalData * getInstance ()
static void deleteInstance ()
static void stashInstance ()
static OpalData * popInstance ()
Private Member Functions
OpalData ()
OpalData (const OpalData &)
void operator= (const OpalData &)
Private Attributes
struct OpalDataImpl * p
Static Private Attributes
static bool isInstantiated = false
static OpalData * instance = nullptr
static std::stack< OpalData * > stashedInstances
Detailed Description
The global OPAL structure.
Definition at line 45 of file OpalData.h.
Member Enumeration Documentation
OpenMode
enum class OpalData::OpenMode : unsigned short strong
Enum for writing to files.
Enumerator
UNDEFINED
WRITE
APPEND
Definition at line 58 of file OpalData.h.
Constructor & Destructor Documentation
~OpalData()
OpalData::~OpalData ()
Definition at line 239 of file OpalData.cpp.
References p.
OpalData() [1/2]
OpalData::OpalData () private
Definition at line 237 of file OpalData.cpp.
References p.
Referenced by getInstance().
OpalData() [2/2]
OpalData::OpalData (const OpalData &) private
Member Function Documentation
addEnergyData()
void OpalData::addEnergyData (double spos, double ekin)
Definition at line 333 of file OpalData.cpp.
References OpalDataImpl::energyEvolution_m, and p.
addProblemCharacteristicValue()
void OpalData::addProblemCharacteristicValue (const std::string & name, unsigned int value)
Definition at line 653 of file OpalData.cpp.
References p, and OpalDataImpl::problemSize_m.
apply()
void OpalData::apply (const ObjectFunction & fun)
Apply a function to all objects.
Definition at line 381 of file OpalData.cpp.
References Directory::begin(), Directory::end(), OpalDataImpl::mainDirectory, and p.
Referenced by Line::parse(), and Sequence::storeLine().
bunchIsAllocated()
void OpalData::bunchIsAllocated ()
Definition at line 308 of file OpalData.cpp.
References OpalDataImpl::hasBunchAllocated_m, and p.
checkAndAddOutputFileName()
void OpalData::checkAndAddOutputFileName (const std::string & outfn)
checks the output file names of all items to avoid duplicates
Definition at line 577 of file OpalData.cpp.
References hasBunchAllocated(), OpalDataImpl::outFiles_m, and p.
Referenced by LossDataSink::LossDataSink(), and PeakFinder::save().
create()
void OpalData::create (Object * newObject)
Create new object.
Definition at line 387 of file OpalData.cpp.
References Directory::find(), Object::getOpalName(), Directory::insert(), OpalDataImpl::mainDirectory, and p.
Referenced by OpalMarker::OpalMarker(), RealConstant::RealConstant(), RealVariable::RealVariable(), and StringConstant::StringConstant().
define()
void OpalData::define (Object * newObject)
Define a new object.
Definition at line 400 of file OpalData.cpp.
References Directory::begin(), Object::canReplaceBy(), Directory::end(), erase(), Directory::find(), Object::getOpalName(), Options::info, Directory::insert(), Object::isBuiltin(), Table::isDependent(), OpalDataImpl::mainDirectory, OpalDataImpl::modified, p, Object::setDirty(), setP0(), and OpalDataImpl::tableDirectory.
Referenced by Beam::Beam(), BoundaryGeometry::BoundaryGeometry(), OpalFilter::OpalFilter(), OpalParser::parseAssign(), OpalParser::parseDefine(), OpalParser::parseMacro(), and SequenceParser::parseMember().
deleteInstance()
void OpalData::deleteInstance () static
Definition at line 203 of file OpalData.cpp.
References instance, and isInstantiated.
Referenced by popInstance().
erase()
void OpalData::erase (const std::string & name)
Delete existing entry.
Definition at line 461 of file OpalData.cpp.
References Directory::begin(), Directory::end(), Directory::erase(), Directory::find(), Object::getParent(), OpalDataImpl::mainDirectory, p, and Object::setParent().
Referenced by define().
find()
Object * OpalData::find (const std::string & name)
Find entry.
Definition at line 477 of file OpalData.cpp.
References Directory::find(), OpalDataImpl::mainDirectory, and p.
Referenced by Option::execute(), Expressions::ARefExpr< T >::fill(), Expressions::SRefAttr< T >::fill(), Expressions::SRefExpr< T >::fill(), OpalParser::find(), BeamSequence::find(), Element::find(), Table::find(), Distribution::find(), EmissionSourceList::find(), Beam::find(), BinningCmd::find(), BoundaryGeometry::find(), EmissionSource::find(), FieldSolverCmd::find(), OpalFilter::find(), getVariableData(), getVariableNames(), main(), SequenceTemplate::makeInstance(), LineTemplate::makeInstance(), OpalParser::parseAssign(), Line::parseList(), EmissionSourceList::parseList(), Expressions::parseRelation(), Expressions::parseStringValue(), ParallelTracker::setOptionalVariables(), and Sequence::updateList().
getArguments()
std::vector< std::string > OpalData::getArguments ()
Definition at line 672 of file OpalData.cpp.
References OpalDataImpl::arguments_m, and p.
getAuxiliaryOutputDirectory()
std::string OpalData::getAuxiliaryOutputDirectory () const
get the name of the the additional data directory
Definition at line 567 of file OpalData.cpp.
Referenced by BoundaryGeometry::computeMeshVoxelization(), Fieldmap::lowResolutionWarning(), main(), LaserProfile::sampleDist(), OpalBeamline::save3DInput(), OpalBeamline::save3DLattice(), LaserProfile::saveData(), LaserProfile::saveHistogram(), IndexMap::saveSDDS(), MeshGenerator::write(), Fieldmap::write3DField(), and DumpEMFields::writeFieldThis().
getDataSink()
DataSink * OpalData::getDataSink ()
Definition at line 321 of file OpalData.cpp.
References OpalDataImpl::dataSink_m, and p.
Referenced by TrackRun::initDataSink().
getFirstEnergyData()
energyEvolution_t::iterator OpalData::getFirstEnergyData ()
Definition at line 337 of file OpalData.cpp.
References OpalDataImpl::energyEvolution_m, and p.
getFirstMaxPhases()
std::vector< MaxPhasesT >::iterator OpalData::getFirstMaxPhases ()
Definition at line 327 of file OpalData.cpp.
References OpalDataImpl::maxPhases_m, and p.
Referenced by ParallelTracker::restoreCavityPhases(), and H5PartWrapper::storeCavityInformation().
getGlobalGeometry()
BoundaryGeometry * OpalData::getGlobalGeometry ()
Definition at line 377 of file OpalData.cpp.
References OpalDataImpl::bg_m, and p.
getGlobalPhaseShift()
double OpalData::getGlobalPhaseShift ()
units: (sec)
units: (sec)
Definition at line 370 of file OpalData.cpp.
References OpalDataImpl::gPhaseShift_m, and p.
Referenced by H5PartWrapperForPT::writeHeader().
getInputBasename()
std::string OpalData::getInputBasename ()
get input file name without extension
Definition at line 571 of file OpalData.cpp.
References OpalDataImpl::inputFn_m, and p.
Referenced by FieldSolver< T, Dim >::dumpScalField(), FieldSolver< T, Dim >::dumpVectField(), DataSink::init(), TrackRun::initDataSink(), main(), OpalBeamline::save3DInput(), OpalBeamline::save3DLattice(), IndexMap::saveSDDS(), and Monitor::writeStatistics().
getInputFn()
std::string OpalData::getInputFn ()
get opals input filename
Definition at line 569 of file OpalData.cpp.
References OpalDataImpl::inputFn_m, and p.
Referenced by LBalWriter::fillHeader(), StatWriter::fillHeader(), FromFile::FromFile(), and MemoryProfiler::header().
getInstance()
OpalData * OpalData::getInstance () static
Definition at line 193 of file OpalData.cpp.
References instance, isInstantiated, and OpalData().
Referenced by Expressions::AAutomatic< T >::AAutomatic(), Expressions::AAutomatic< T >::AAutomatic(), SDDSWriter::addDefaultParameters(), Beam::Beam(), BoundaryGeometry::BoundaryGeometry(), Fieldmap::checkMap(), BoundaryGeometry::computeMeshVoxelization(), FieldSolver< T, Dim >::dumpScalField(), FieldSolver< T, Dim >::dumpVectField(), Help::execute(), Option::execute(), Select::execute(), Title::execute(), IfStatement::execute(), WhileStatement::execute(), OpalParser::execute(), Expressions::ARefExpr< T >::fill(), Expressions::SRefAttr< T >::fill(), Expressions::SRefExpr< T >::fill(), ElementPositionWriter::fillHeader(), LBalWriter::fillHeader(), StatWriter::fillHeader(), OpalParser::find(), BeamSequence::find(), Element::find(), Table::find(), Distribution::find(), EmissionSourceList::find(), Beam::find(), BinningCmd::find(), BoundaryGeometry::find(), EmissionSource::find(), FieldSolverCmd::find(), OpalFilter::find(), FromFile::FromFile(), Expressions::getEkin(), CavityAutophaser::getPhaseAtMaxEnergy(), Attributes::getString(), Attributes::getStringArray(), getVariableData(), getVariableNames(), H5PartWrapperForPT::H5PartWrapperForPT(), MemoryProfiler::header(), DataSink::init(), TrackRun::initDataSink(), OrbitThreader::integrate(), LossDataSink::LossDataSink(), Fieldmap::lowResolutionWarning(), main(), SequenceTemplate::makeInstance(), LineTemplate::makeInstance(), OpalFilter::OpalFilter(), OpalMarker::OpalMarker(), OrbitThreader::OrbitThreader(), SequenceParser::parse(), OpalParser::parse(), Line::parse(), OpalParser::parseAssign(), OpalParser::parseDefine(), Line::parseList(), EmissionSourceList::parseList(), OpalParser::parseMacro(), SequenceParser::parseMember(), Expressions::parseRelation(), Expressions::parseStringValue(), Distribution::printInfo(), H5PartWrapperForPT::readHeader(), RealConstant::RealConstant(), RealVariable::RealVariable(), ParallelTracker::restoreCavityPhases(), LaserProfile::sampleDist(), Expressions::SAutomatic< T >::SAutomatic(), Expressions::SAutomatic< T >::SAutomatic(), PluginElement::save(), PeakFinder::save(), LossDataSink::save(), OpalBeamline::save3DInput(), OpalBeamline::save3DLattice(), LaserProfile::saveData(), LaserProfile::saveHistogram(), IndexMap::saveSDDS(), ParallelTracker::setOptionalVariables(), SolenoidPlacementTest::SetUp(), OrbitThreaderTest::SetUp(), OpalBeamlinePlacementTest::SetUp(), TrackRun::setupBoundaryGeometry(), TestMultipoleT::SetUpTestSuite(), TestMultipoleTCurvedConstRadius::SetUpTestSuite(), TestMultipoleTStraight::SetUpTestSuite(), TestVariableRFCavity::SetUpTestSuite(), H5PartWrapper::storeCavityInformation(), Sequence::storeLine(), StringConstant::StringConstant(), Table::Table(), Track::Track(), TrackRun::TrackRun(), TrackRun::TrackRun(), OpalMultipole::update(), OpalQuadrupole::update(), OpalRBend::update(), OpalSBend::update(), OpalSolenoid::update(), Sequence::updateList(), MeshGenerator::write(), StatWriter::write(), Fieldmap::write3DField(), DumpEMFields::writeFieldThis(), H5PartWrapperForPT::writeHeader(), Monitor::writeStatistics(), Expressions::AAutomatic< T >::~AAutomatic(), Expressions::SAutomatic< T >::~SAutomatic(), and Table::~Table().
getLastEnergyData()
energyEvolution_t::iterator OpalData::getLastEnergyData ()
Definition at line 339 of file OpalData.cpp.
References OpalDataImpl::energyEvolution_m, and p.
getLastMaxPhases()
std::vector< MaxPhasesT >::iterator OpalData::getLastMaxPhases ()
Definition at line 329 of file OpalData.cpp.
References OpalDataImpl::maxPhases_m, and p.
Referenced by ParallelTracker::restoreCavityPhases(), and H5PartWrapper::storeCavityInformation().
getLastStep()
int OpalData::getLastStep () const
get the last step from a possible previous run
Definition at line 304 of file OpalData.cpp.
References OpalDataImpl::last_step_m, and p.
getMaxTrackSteps()
unsigned long long OpalData::getMaxTrackSteps ()
Definition at line 231 of file OpalData.cpp.
References OpalDataImpl::maxTrackSteps_m, and p.
getNumberOfMaxPhases()
int OpalData::getNumberOfMaxPhases ()
Definition at line 331 of file OpalData.cpp.
References OpalDataImpl::maxPhases_m, and p.
Referenced by H5PartWrapper::storeCavityInformation().
getOpenMode()
OpalData::OpenMode OpalData::getOpenMode () const
Definition at line 300 of file OpalData.cpp.
References OpalDataImpl::openMode_m, and p.
Referenced by PluginElement::save(), LossDataSink::save(), and OpalBeamline::save3DLattice().
getP0()
double OpalData::getP0 () const
Return value of global reference momentum.
Definition at line 479 of file OpalData.cpp.
References ValueDefinition::getReal(), Units::GeV2eV, p, and OpalDataImpl::referenceMomentum.
Referenced by OpalMultipole::update(), OpalQuadrupole::update(), OpalRBend::update(), OpalSBend::update(), and OpalSolenoid::update().
getPartBunch()
PartBunch_t * OpalData::getPartBunch ()
Definition at line 312 of file OpalData.cpp.
References OpalDataImpl::bunch_m, and p.
Referenced by Expressions::getEkin().
getProblemCharacteristicValues()
const std::map< std::string, unsigned int > & OpalData::getProblemCharacteristicValues () const
Definition at line 661 of file OpalData.cpp.
References p, and OpalDataImpl::problemSize_m.
getRestartDumpFreq()
int OpalData::getRestartDumpFreq () const
get the dump frequency as found in restart file
Definition at line 296 of file OpalData.cpp.
References p, and OpalDataImpl::restart_dump_freq_m.
getRestartFileName()
std::string OpalData::getRestartFileName ()
get opals restart h5 format filename
Definition at line 285 of file OpalData.cpp.
References p, and OpalDataImpl::restartFn_m.
getRestartStep()
int OpalData::getRestartStep ()
get the step where to restart
Definition at line 283 of file OpalData.cpp.
References p, and OpalDataImpl::restartStep_m.
Referenced by TrackRun::initDataSink().
getTitle()
std::string OpalData::getTitle ()
Get the title string.
Definition at line 565 of file OpalData.cpp.
References OpalDataImpl::itsTitle_m, and p.
getVariableData()
std::map< std::string, std::string > OpalData::getVariableData ()
Definition at line 612 of file OpalData.cpp.
References find(), getInstance(), RealVariable::getReal(), StringConstant::getString(), and getVariableNames().
getVariableNames()
std::vector< std::string > OpalData::getVariableNames ()
Definition at line 634 of file OpalData.cpp.
References Directory::begin(), Directory::end(), find(), Object::getCategory(), getInstance(), Object::isBuiltin(), OpalDataImpl::mainDirectory, and p.
Referenced by getVariableData().
hasBunchAllocated()
bool OpalData::hasBunchAllocated ()
true if we already allocated a ParticleBunch object
Definition at line 306 of file OpalData.cpp.
References OpalDataImpl::hasBunchAllocated_m, and p.
Referenced by checkAndAddOutputFileName(), and TrackRun::execute().
hasDataSinkAllocated()
bool OpalData::hasDataSinkAllocated ()
true if we already allocated a DataSink object
Definition at line 314 of file OpalData.cpp.
References OpalDataImpl::hasDataSinkAllocated_m, and p.
Referenced by TrackRun::initDataSink().
hasGlobalGeometry()
bool OpalData::hasGlobalGeometry ()
Definition at line 379 of file OpalData.cpp.
References OpalDataImpl::bg_m, and p.
hasPriorTrack()
bool OpalData::hasPriorTrack ()
true if in follow-up track
Definition at line 273 of file OpalData.cpp.
References OpalDataImpl::hasPriorRun_m, and p.
hasRestartFile()
bool OpalData::hasRestartFile ()
true if we do a restart from specified h5 file
Definition at line 292 of file OpalData.cpp.
References OpalDataImpl::hasRestartFile_m, and p.
incMaxTrackSteps()
void OpalData::incMaxTrackSteps (unsigned long long s)
Definition at line 235 of file OpalData.cpp.
References OpalDataImpl::maxTrackSteps_m, and p.
inRestartRun()
bool OpalData::inRestartRun ()
true if we do a restart run
Definition at line 277 of file OpalData.cpp.
References OpalDataImpl::isRestart_m, and p.
Referenced by TrackRun::initDataSink(), and main().
isInOPALCyclMode()
bool OpalData::isInOPALCyclMode ()
Definition at line 257 of file OpalData.cpp.
References OpalDataImpl::isInOPALCyclMode_m, and p.
isInOPALTMode()
bool OpalData::isInOPALTMode ()
Definition at line 259 of file OpalData.cpp.
References OpalDataImpl::isInOPALTMode_m, and p.
isInPrepState()
bool OpalData::isInPrepState ()
Definition at line 269 of file OpalData.cpp.
References OpalDataImpl::isInPrepState_m, and p.
isOptimizerRun()
bool OpalData::isOptimizerRun ()
Definition at line 261 of file OpalData.cpp.
References OpalDataImpl::isOptimizerFlag_m, and p.
makeDirty()
void OpalData::makeDirty (Object * object)
Invalidate expressions.
Definition at line 481 of file OpalData.cpp.
References OpalDataImpl::modified, p, and Object::setDirty().
Referenced by SequenceParser::parse(), and OpalParser::parseAssign().
operator=()
void OpalData::operator= (const OpalData &) private
popInstance()
OpalData * OpalData::popInstance () static
Definition at line 219 of file OpalData.cpp.
References deleteInstance(), instance, isInstantiated, and stashedInstances.
printAllNames()
void OpalData::printAllNames (std::ostream & stream)
Definition at line 486 of file OpalData.cpp.
References Directory::begin(), Directory::end(), OpalDataImpl::mainDirectory, and p.
printNames()
void OpalData::printNames (std::ostream & stream, const std::string & pattern)
Print all objects.
Definition at line 514 of file OpalData.cpp.
References Directory::begin(), Directory::end(), OpalDataImpl::mainDirectory, RegularExpression::match(), and p.
printTitle()
void OpalData::printTitle (std::ostream & os)
Print the page title.
Definition at line 563 of file OpalData.cpp.
References OpalDataImpl::itsTitle_m, and p.
registerExpression()
void OpalData::registerExpression (AttributeBase * expr)
Register expression.
Definition at line 553 of file OpalData.cpp.
References OpalDataImpl::exprDirectory, and p.
Referenced by Expressions::AAutomatic< T >::AAutomatic(), Expressions::AAutomatic< T >::AAutomatic(), Expressions::SAutomatic< T >::SAutomatic(), and Expressions::SAutomatic< T >::SAutomatic().
registerTable()
void OpalData::registerTable (Table * t)
Register table.
Definition at line 544 of file OpalData.cpp.
References p, and OpalDataImpl::tableDirectory.
Referenced by Table::Table().
reset()
void OpalData::reset ()
reset object for consecutive runs
Definition at line 241 of file OpalData.cpp.
References OpalDataImpl::gPhaseShift_m, OpalDataImpl::hasBunchAllocated_m, OpalDataImpl::hasDataSinkAllocated_m, OpalDataImpl::hasPriorRun_m, OpalDataImpl::hasRestartFile_m, OpalDataImpl::isInOPALCyclMode_m, OpalDataImpl::isInOPALTMode_m, OpalDataImpl::isInPrepState_m, OpalDataImpl::isOptimizerFlag_m, OpalDataImpl::isRestart_m, OpalDataImpl::maxPhases_m, and p.
setDataSink()
void OpalData::setDataSink (DataSink * s)
Definition at line 316 of file OpalData.cpp.
References OpalDataImpl::dataSink_m, OpalDataImpl::hasDataSinkAllocated_m, and p.
Referenced by TrackRun::initDataSink().
setGlobalGeometry()
void OpalData::setGlobalGeometry (BoundaryGeometry * bg)
Definition at line 375 of file OpalData.cpp.
References OpalDataImpl::bg_m, and p.
Referenced by TrackRun::setupBoundaryGeometry().
setGlobalPhaseShift()
void OpalData::setGlobalPhaseShift (double shift)
units: (sec)
units: (sec)
Definition at line 365 of file OpalData.cpp.
References OpalDataImpl::gPhaseShift_m, and p.
Referenced by H5PartWrapperForPT::readHeader().
setInOPALCyclMode()
void OpalData::setInOPALCyclMode ()
Definition at line 263 of file OpalData.cpp.
References OpalDataImpl::isInOPALCyclMode_m, and p.
setInOPALTMode()
void OpalData::setInOPALTMode ()
Definition at line 265 of file OpalData.cpp.
References OpalDataImpl::isInOPALTMode_m, and p.
setInPrepState()
void OpalData::setInPrepState (bool state)
Definition at line 271 of file OpalData.cpp.
References OpalDataImpl::isInPrepState_m, and p.
setLastStep()
void OpalData::setLastStep (const int & step)
set the last step in a run for possible follow-up run
Definition at line 302 of file OpalData.cpp.
References OpalDataImpl::last_step_m, and p.
setMaxPhase()
void OpalData::setMaxPhase (std::string elName, double phi)
Definition at line 323 of file OpalData.cpp.
References OpalDataImpl::maxPhases_m, and p.
Referenced by CavityAutophaser::getPhaseAtMaxEnergy().
setMaxTrackSteps()
void OpalData::setMaxTrackSteps (unsigned long long s)
Definition at line 233 of file OpalData.cpp.
References OpalDataImpl::maxTrackSteps_m, and p.
setOpenMode()
void OpalData::setOpenMode (OpenMode openMode)
Definition at line 298 of file OpalData.cpp.
References OpalDataImpl::openMode_m, and p.
Referenced by LossDataSink::LossDataSink(), SolenoidPlacementTest::SetUp(), OrbitThreaderTest::SetUp(), and OpalBeamlinePlacementTest::SetUp().
setOptimizerFlag()
void OpalData::setOptimizerFlag ()
Definition at line 267 of file OpalData.cpp.
References OpalDataImpl::isOptimizerFlag_m, and p.
setP0()
void OpalData::setP0 (ValueDefinition * p0)
Set the global momentum.
Definition at line 557 of file OpalData.cpp.
References p, and OpalDataImpl::referenceMomentum.
Referenced by define(), and RealVariable::RealVariable().
setPartBunch()
void OpalData::setPartBunch (PartBunch_t * p)
Definition at line 310 of file OpalData.cpp.
References OpalDataImpl::bunch_m, and p.
setPriorTrack()
void OpalData::setPriorTrack (const bool & value = true)
true if in follow-up track
Definition at line 275 of file OpalData.cpp.
References OpalDataImpl::hasPriorRun_m, and p.
setRestartDumpFreq()
void OpalData::setRestartDumpFreq (const int & N)
set the dump frequency as found in restart file
Definition at line 294 of file OpalData.cpp.
References p, and OpalDataImpl::restart_dump_freq_m.
Referenced by H5PartWrapperForPT::readHeader().
setRestartFileName()
void OpalData::setRestartFileName (std::string s)
store opals restart h5 format filename
Definition at line 287 of file OpalData.cpp.
References OpalDataImpl::hasRestartFile_m, p, and OpalDataImpl::restartFn_m.
Referenced by main().
setRestartRun()
void OpalData::setRestartRun (const bool & value = true)
set OPAL in restart mode
Definition at line 279 of file OpalData.cpp.
References OpalDataImpl::isRestart_m, and p.
Referenced by main().
setRestartStep()
void OpalData::setRestartStep (int s)
store the location where to restart
Definition at line 281 of file OpalData.cpp.
References p, and OpalDataImpl::restartStep_m.
Referenced by H5PartWrapperForPT::H5PartWrapperForPT(), and main().
stashInstance()
void OpalData::stashInstance () static
Definition at line 209 of file OpalData.cpp.
References instance, isInstantiated, MAX_NUM_INSTANCES, and stashedInstances.
storeArguments()
void OpalData::storeArguments (int argc, char * argv[])
Definition at line 665 of file OpalData.cpp.
References OpalDataImpl::arguments_m, and p.
Referenced by main().
storeInputFn()
void OpalData::storeInputFn (const std::string & fn)
store opals input filename
Definition at line 561 of file OpalData.cpp.
References OpalDataImpl::inputFn_m, and p.
Referenced by main(), SolenoidPlacementTest::SetUp(), OrbitThreaderTest::SetUp(), OpalBeamlinePlacementTest::SetUp(), TestMultipoleT::SetUpTestSuite(), TestMultipoleTCurvedConstRadius::SetUpTestSuite(), TestMultipoleTStraight::SetUpTestSuite(), and TestVariableRFCavity::SetUpTestSuite().
storeTitle()
void OpalData::storeTitle (const std::string & title)
Store the page title.
Definition at line 559 of file OpalData.cpp.
References OpalDataImpl::itsTitle_m, and p.
Referenced by Title::execute().
unregisterExpression()
void OpalData::unregisterExpression (AttributeBase * expr)
Unregister expression.
Definition at line 555 of file OpalData.cpp.
References OpalDataImpl::exprDirectory, and p.
Referenced by Expressions::AAutomatic< T >::~AAutomatic(), and Expressions::SAutomatic< T >::~SAutomatic().
unregisterTable()
void OpalData::unregisterTable (Table * t)
Unregister table.
Definition at line 546 of file OpalData.cpp.
References p, and OpalDataImpl::tableDirectory.
Referenced by Table::~Table().
update()
void OpalData::update ()
Update all objects.
Definition at line 587 of file OpalData.cpp.
References Directory::begin(), Directory::end(), OpalDataImpl::exprDirectory, OpalDataImpl::mainDirectory, OpalDataImpl::modified, p, and OpalDataImpl::tableDirectory.
Referenced by IfStatement::execute(), WhileStatement::execute(), and OpalParser::execute().
Member Data Documentation
instance
OpalData * OpalData::instance = nullptr static private
Definition at line 261 of file OpalData.h.
Referenced by deleteInstance(), getInstance(), popInstance(), and stashInstance().
isInstantiated
bool OpalData::isInstantiated = false static private
Definition at line 260 of file OpalData.h.
Referenced by deleteInstance(), getInstance(), popInstance(), and stashInstance().
p
struct OpalDataImpl* OpalData::p private
Definition at line 272 of file OpalData.h.
Referenced by addEnergyData(), addProblemCharacteristicValue(), apply(), bunchIsAllocated(), checkAndAddOutputFileName(), create(), define(), erase(), find(), getArguments(), getDataSink(), getFirstEnergyData(), getFirstMaxPhases(), getGlobalGeometry(), getGlobalPhaseShift(), getInputBasename(), getInputFn(), getLastEnergyData(), getLastMaxPhases(), getLastStep(), getMaxTrackSteps(), getNumberOfMaxPhases(), getOpenMode(), getP0(), getPartBunch(), getProblemCharacteristicValues(), getRestartDumpFreq(), getRestartFileName(), getRestartStep(), getTitle(), getVariableNames(), hasBunchAllocated(), hasDataSinkAllocated(), hasGlobalGeometry(), hasPriorTrack(), hasRestartFile(), incMaxTrackSteps(), inRestartRun(), isInOPALCyclMode(), isInOPALTMode(), isInPrepState(), isOptimizerRun(), makeDirty(), OpalData(), printAllNames(), printNames(), printTitle(), registerExpression(), registerTable(), reset(), setDataSink(), setGlobalGeometry(), setGlobalPhaseShift(), setInOPALCyclMode(), setInOPALTMode(), setInPrepState(), setLastStep(), setMaxPhase(), setMaxTrackSteps(), setOpenMode(), setOptimizerFlag(), setP0(), setPartBunch(), setPriorTrack(), setRestartDumpFreq(), setRestartFileName(), setRestartRun(), setRestartStep(), storeArguments(), storeInputFn(), storeTitle(), unregisterExpression(), unregisterTable(), update(), and ~OpalData().
stashedInstances
std::stack< OpalData * > OpalData::stashedInstances static private
Definition at line 263 of file OpalData.h.
Referenced by popInstance(), and stashInstance().
The documentation for this class was generated from the following files:
OpalData.h
OpalData.cpp