OPALX (Object Oriented Parallel Accelerator Library for Exascal): Voxel Class Reference
Voxel Class Reference
Public Member Functions
Voxel ()
Voxel (const Vector_t< double, 3 > &min, const Vector_t< double, 3 > &max)
void scale (const Vector_t< double, 3 > &scale)
bool intersect (const Ray &r, double &tmin, double &tmax) const
bool intersect (const Ray &r) const
int intersect (const Triangle &t) const
Vector_t< double, 3 > extent () const
bool isInside (const Vector_t< double, 3 > &P) const
Public Attributes
Vector_t< double, 3 > pts [2]
Detailed Description
Definition at line 782 of file BoundaryGeometry.cpp.
Constructor & Destructor Documentation
Voxel() [1/2]
Voxel::Voxel () inline
Definition at line 784 of file BoundaryGeometry.cpp.
Referenced by intersect().
Voxel() [2/2]
Voxel::Voxel (const Vector_t< double, 3 > & min, const Vector_t< double, 3 > & max) inline
Definition at line 785 of file BoundaryGeometry.cpp.
References pts.
Member Function Documentation
extent()
Vector_t< double, 3 > Voxel::extent () const inline
Definition at line 836 of file BoundaryGeometry.cpp.
References pts.
Referenced by intersect().
intersect() [1/3]
bool Voxel::intersect (const Ray & r) const inline
Definition at line 821 of file BoundaryGeometry.cpp.
References intersect().
intersect() [2/3]
bool Voxel::intersect (const Ray & r, double & tmin, double & tmax) const inline
Definition at line 799 of file BoundaryGeometry.cpp.
References cmp_ulp::ge_zero(), cmp_ulp::gt(), Ray::inv_direction, cmp_ulp::lt(), Ray::origin, pts, and Ray::sign.
Referenced by intersect(), BoundaryGeometry::intersectTinyLineSegmentBoundary(), and BoundaryGeometry::intersectTriangleVoxel().
intersect() [3/3]
int Voxel::intersect (const Triangle & t) const inline
Definition at line 827 of file BoundaryGeometry.cpp.
References extent(), pts, Triangle::scale(), scale(), and Voxel().
isInside()
bool Voxel::isInside (const Vector_t< double, 3 > & P) const inline
Definition at line 838 of file BoundaryGeometry.cpp.
References cmp_ulp::ge(), cmp_ulp::le(), and pts.
scale()
void Voxel::scale (const Vector_t< double, 3 > & scale) inline
Definition at line 789 of file BoundaryGeometry.cpp.
References pts, and scale().
Referenced by intersect(), and scale().
Member Data Documentation
pts
Vector_t<double, 3> Voxel::pts[2]
Definition at line 844 of file BoundaryGeometry.cpp.
Referenced by extent(), intersect(), intersect(), BoundaryGeometry::intersectTinyLineSegmentBoundary(), isInside(), scale(), and Voxel().
The documentation for this class was generated from the following file:
BoundaryGeometry.cpp