OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestMultipoleTStraight Class Reference
TestMultipoleTStraight Class Reference
Classes
class TestableFieldSolverCmd
Public Member Functions
TestMultipoleTStraight ()
void grabTransverseDataLine (std::vector< double > &line, const double s, const double width, const Vector_t< double, 3 > &elementEntry, const double elementLength)
void grabVerticalDataLine (std::vector< double > &line, const double s, const double height, const Vector_t< double, 3 > &elementEntry, const double elementLength)
void grabLongitudinalDivCurlLine (std::vector< double > &fieldLine, std::vector< double > &divLine, std::vector< Vector_t< double, 3 > > &curlLine, const double x, const double length, const Vector_t< double, 3 > &elementEntry, const double elementLength, const double dr)
std::shared_ptr< PartBunch_t > makeBunch (const size_t numParticles)
ElementBase * clone () const override
void accept (BeamlineVisitor &visitor) const override
BGeometryBase & getGeometry () override
const BGeometryBase & getGeometry () const override
EMField & getField () override
const EMField & getField () const override
bool apply (const std::shared_ptr< ParticleContainer_t > &pc) override
bool apply (const Vector_t< double, 3 > &R, const Vector_t< double, 3 > &P, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
bool apply (const size_t &i, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
void initialise (PartBunch_t *bunch, double &startField, double &endField) override
void finalise () override
bool bends () const override
size_t getMaxFOrder () const
size_t getMaxXOrder () const
void setMaxOrder (size_t orderZ, size_t orderX)
std::size_t getTransMaxOrder () const
void setTransProfile (const std::vector< double > &profile)
const Kokkos::Array< double, MultipoleTConfig::NumPoles > & getTransProfile () const
void setFringeField (const double &s0, const double &lambda_left, const double &lambda_right)
std::tuple< double, double, double > getFringeField () const
void setEntranceAngle (double entranceAngle)
void setEntryOffset (double offset)
double getEntryOffset () const
bool getVariableRadius () const
void setBendAngle (double angle, bool variableRadius)
double getBendAngle () const
double getEntranceAngle () const
void setElementLength (double length) override
double getLength () const
void setAperture (const double &vertAp, const double &horizAp)
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::tuple< double, double > getAperture ()
std::pair< ApertureType, std::vector< double > > getAperture () const
void setRotation (double rot)
double getRotation () const
double getBoundingBoxLength () const
void setBoundingBoxLength (double boundingBoxLength)
void getFieldExtend (double &zBegin, double &zEnd) const override
void setScalingName (const std::string &name)
std::string getScalingName () const
void initialiseTimeDependencies () const
MultipoleTConfig & getConfig ()
EVector Efield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool applyToReferenceParticle (const Vector_t< double, 3 > &R, const Vector_t< double, 3 > &P, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B)
Apply to reference particle with position R and momemtum P.
virtual bool getPotential (const Vector_t< double, 3 > &, const double &, Vector_t< double, 3 > &, double &)
Calculate the four-potential at some position relative to the component.
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual void goOnline (const double &kineticEnergy)
virtual void goOffline ()
virtual bool Online ()
virtual ElementType getType () const
Get element type std::string.
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunch_t &bunch, const PartData &, bool revBeam, bool revTrack) const
Track a borrowed particle bunch through a non-standard component.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void getElementDimensions (double &begin, double &end) const
Return the nominal body extent of the element.
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
virtual Port getEntryPort () const
Return the entrance port of the canonical local chart.
virtual Port getBodyPort () const
Return the body port of the canonical local chart.
virtual Port getExitPort () const
Return the exit port of the canonical local chart.
PlacementPose getPlacementPose () const
Return the nominal rigid placement transform of the element.
void setPlacementPose (const PlacementPose &pose)
Set the nominal rigid placement transform of the element.
Misalignment getPlacementMisalignment () const
Return the local nominal-to-actual correction stored for the element.
ElementGeometry getPlacementGeometry () const
Return the bridge geometry ports assembled from legacy edge state.
SupportPlacement getPlacementSupport () const
Return the support-frame bridge object. The default is the body frame.
PlacedElement getPlacedElement () const
Return a placed-element view assembled from the current bridge objects.
virtual bool isInside (const Vector_t< double, 3 > &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Static Public Member Functions
static void SetUpTestSuite ()
static void TearDownTestSuite ()
static Vector_t< double, 3 > curvilinearToGlobal (const Vector_t< double, 3 > &local, const Vector_t< double, 3 > &elementEntry, const double elementLength)
static std::string getTypeString (ElementType type)
Public Attributes
std::shared_ptr< FieldSolverCmd > fsCmdBase_m
std::shared_ptr< DataSink > dataSink_m
Protected Member Functions
void chooseImplementation ()
double getScaling (double t) const
void validateConfiguration () const
bool isInsideTransverse (const Vector_t< double, 3 > &r) const
Protected Attributes
MultipoleTConfig config_m
BMultipoleField dummy
std::string scalingName_m
std::shared_ptr< AbstractTimeDependence > scalingTD_m
std::unique_ptr< MultipoleTBase > implementation_ {}
double exit_face_slope_m
PartBunch_t * RefPartBunch_m
bool online_m
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes
static const std::vector< double > defaultAperture_m = std::vector<double>({1e6, 1e6, 1.0})
Private Attributes
std::string elementID
AttributeSet userAttribs
WakeFunction * wake_m
BoundaryGeometry * bgeometry_m
ParticleMatterInteractionHandler * parmatint_m
bool positionIsFixed
std::queue< std::pair< double, double > > actionRange_m
std::string outputfn_m
bool deleteOnTransverseExit_m = true
double elementPosition_m
ELEMEDGE attribute.
bool elemedgeSet_m
Static Private Attributes
static const std::map< ElementType, std::string > elementTypeToString_s
Detailed Description
Definition at line 25 of file TestMultipoleTStraight.cpp.
Constructor & Destructor Documentation
TestMultipoleTStraight()
TestMultipoleTStraight::TestMultipoleTStraight () inline
Definition at line 27 of file TestMultipoleTStraight.cpp.
References MultipoleT::MultipoleT().
Member Function Documentation
accept()
void MultipoleT::accept (BeamlineVisitor & visitor) const override virtual inherited
Accept a beamline visitor
Implements ElementBase.
Definition at line 36 of file MultipoleT.cpp.
References initialiseTimeDependencies(), and BeamlineVisitor::visitMultipoleT().
apply() [1/3]
bool MultipoleT::apply (const size_t & i, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual inherited
Calculate the field at the position of the ith particle
Parameters
i -> Index of the particle event; field is calculated at this position This overload is single-container only. In multi-container tracking, use apply(const std::shared_ptr<ParticleContainer_t>& pc). If particle is outside field map true is returned, otherwise false is returned
t -> Time at which the field is to be calculated
E -> Calculated electric field - always 0 (no E-field)
B -> Calculated magnetic field
Reimplemented from Component.
Definition at line 64 of file MultipoleT.cpp.
References getScaling(), implementation_, Component::RefPartBunch_m, and validateConfiguration().
apply() [2/3]
bool MultipoleT::apply (const std::shared_ptr< ParticleContainer_t > & pc) override virtual inherited
Calculate the field for all particles
Reimplemented from Component.
Definition at line 49 of file MultipoleT.cpp.
References getScaling(), implementation_, Component::RefPartBunch_m, and validateConfiguration().
Referenced by TestMultipoleT::fieldAtT(), TestMultipoleTCurvedConstRadius::grabLongitudinalDivCurlLine(), TestMultipoleTStraight::grabLongitudinalDivCurlLine(), TestMultipoleTCurvedConstRadius::grabTransverseDataLine(), TestMultipoleTStraight::grabTransverseDataLine(), TestMultipoleTCurvedConstRadius::grabVerticalDataLine(), and TestMultipoleTStraight::grabVerticalDataLine().
apply() [3/3]
bool MultipoleT::apply (const Vector_t< double, 3 > & R, const Vector_t< double, 3 > & P, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual inherited
Calculate the field at some arbitrary position
If particle is outside field map true is returned, otherwise false is returned
Parameters
R -> Position in the lab coordinate system of the multipole
P -> Not used
t -> Time at which the field is to be calculated
E -> Calculated electric field - always 0 (no E-field)
B -> Calculated magnetic field
Reimplemented from Component.
Definition at line 57 of file MultipoleT.cpp.
References getScaling(), implementation_, and validateConfiguration().
applyToReferenceParticle()
bool Component::applyToReferenceParticle (const Vector_t< double, 3 > & R, const Vector_t< double, 3 > & P, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) virtual inherited
Apply to reference particle with position R and momemtum P.
Parameters
R Position
P Momentum
t Time
E Electric Field
B Magnetic Field
Returns
true if particle is out-of-bounds (lost), false otherwise
Reimplemented in BendBase, ConstantEFieldCavity, Monitor, Multipole, PluginElement, RFCavity, Solenoid, TravelingWave, and VariableRFCavity.
Definition at line 114 of file Component.cpp.
References ElementBase::getElementLength(), and ElementBase::isInsideTransverse().
bends()
bool MultipoleT::bends () const override virtual inherited
Return true if dipole component not zero
Implements Component.
Definition at line 165 of file MultipoleT.cpp.
References config_m.
Bfield() [1/2]
BVector Component::Bfield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 234 of file Component.h.
References EMField::Bfield(), and getField().
Bfield() [2/2]
BVector Component::Bfield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 240 of file Component.h.
References EMField::Bfield(), and getField().
chooseImplementation()
void MultipoleT::chooseImplementation () protected inherited
Definition at line 117 of file MultipoleT.cpp.
References config_m, and implementation_.
Referenced by MultipoleT(), MultipoleT(), and setBendAngle().
clone()
ElementBase * MultipoleT::clone () const override virtual inherited
Inheritable copy constructor
Implements ElementBase.
Definition at line 34 of file MultipoleT.cpp.
References ElementBase::ElementBase(), and MultipoleT().
copyStructure()
ElementBase * ElementBase::copyStructure () virtual inherited
Make a structural copy.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 193 of file ElementBase.cpp.
References clone(), ElementBase(), and isSharable().
Referenced by Sequence::copy(), Line::parse(), and SequenceParser::parseMember().
curvilinearToGlobal()
Vector_t< double, 3 > TestMultipoleTStraight::curvilinearToGlobal (const Vector_t< double, 3 > & local, const Vector_t< double, 3 > & elementEntry, const double elementLength) inline static
Definition at line 49 of file TestMultipoleTStraight.cpp.
Referenced by grabLongitudinalDivCurlLine(), grabTransverseDataLine(), and grabVerticalDataLine().
EBfield() [1/2]
EBVectors Component::EBfield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 244 of file Component.h.
References EMField::EBfield(), and getField().
EBfield() [2/2]
EBVectors Component::EBfield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 246 of file Component.h.
References EMField::EBfield(), and getField().
Efield() [1/2]
EVector Component::Efield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 232 of file Component.h.
References EMField::Efield(), and getField().
Efield() [2/2]
EVector Component::Efield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 236 of file Component.h.
References EMField::Efield(), and getField().
finalise()
void MultipoleT::finalise () override virtual inherited
Finalise the MultipoleT - sets bunch to nullptr
Implements Component.
Definition at line 100 of file MultipoleT.cpp.
References Component::RefPartBunch_m.
fixPosition()
void ElementBase::fixPosition () inline inherited
Definition at line 596 of file ElementBase.h.
References positionIsFixed.
Referenced by OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
getAperture() [1/2]
std::pair< ApertureType, std::vector< double > > ElementBase::getAperture () const inline inherited
Definition at line 581 of file ElementBase.h.
References aperture_m.
Referenced by MeshGenerator::add(), Solenoid::getSupportEnvelope(), and MeshGenerator::getTransverseSupport().
getAperture() [2/2]
std::tuple< double, double > MultipoleT::getAperture () inline inherited
Get the aperture dimensions
Returns
{verticalApert, horizontalApert}
Definition at line 197 of file MultipoleT.h.
References config_m.
getArcLength()
double ElementBase::getArcLength () const inline virtual inherited
Get arc length.
Reimplemented in MarkerRep, TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 478 of file ElementBase.h.
References BGeometryBase::getArcLength(), and getGeometry().
Referenced by TBeamline< T >::getTransform().
getAttribute()
double ElementBase::getAttribute (const std::string & aKey) const virtual inherited
Get attribute value.
Definition at line 146 of file ElementBase.cpp.
References getConstChannel().
getBendAngle()
double MultipoleT::getBendAngle () const inline inherited
Get the bending angle of the magnet
Definition at line 178 of file MultipoleT.h.
References config_m.
getBodyPort()
Port ElementBase::getBodyPort () const inline virtual inherited
Return the body port of the canonical local chart.
The body port \(p_{i,\mathrm{body}}\) is the identity port of the element's canonical local chart. Its rigid transform is therefore the identity element of \(SE(3)\) in the first redesign stage.
Definition at line 546 of file ElementBase.h.
Referenced by getPlacementGeometry(), and TEST_F().
getBoundaryGeometry()
BoundaryGeometry * ElementBase::getBoundaryGeometry () const inline virtual inherited
return the attached boundary geometrt object if there is any
Definition at line 512 of file ElementBase.h.
References bgeometry_m.
getBoundingBoxInLabCoords()
BoundingBox ElementBase::getBoundingBoxInLabCoords () const virtual inherited
Definition at line 263 of file ElementBase.cpp.
References csTrafoGlobal2Local_m, getEdgeToBegin(), and getEdgeToEnd().
getBoundingBoxLength()
double MultipoleT::getBoundingBoxLength () const inline inherited
Get the bounding box size
Definition at line 209 of file MultipoleT.h.
References config_m.
getChannel()
Channel * ElementBase::getChannel (const std::string & aKey, bool create = false) virtual inherited
Construct a read/write channel.
Reimplemented in ConstantEFieldCavityRep, DriftRep, LaserRep, MonitorRep, MultipoleRep, ProbeRep, RBendRep, RFCavityRep, SBendRep, SolenoidRep, and TravelingWaveRep.
Definition at line 181 of file ElementBase.cpp.
References userAttribs.
Referenced by ConstantEFieldCavityRep::getChannel(), DriftRep::getChannel(), LaserRep::getChannel(), MonitorRep::getChannel(), MultipoleRep::getChannel(), ProbeRep::getChannel(), RBendRep::getChannel(), RFCavityRep::getChannel(), SBendRep::getChannel(), SolenoidRep::getChannel(), TravelingWaveRep::getChannel(), getConstChannel(), and setAttribute().
getConfig()
MultipoleTConfig & MultipoleT::getConfig () inline inherited
Definition at line 229 of file MultipoleT.h.
References config_m.
getConstChannel()
const ConstChannel * ElementBase::getConstChannel (const std::string & aKey) const virtual inherited
Construct a read-only channel.
Definition at line 185 of file ElementBase.cpp.
References ElementBase(), and getChannel().
Referenced by getAttribute(), and hasAttribute().
getCSTrafoGlobal2Local()
CoordinateSystemTrafo ElementBase::getCSTrafoGlobal2Local () const inline inherited
Definition at line 528 of file ElementBase.h.
References csTrafoGlobal2Local_m.
Referenced by getPlacementPose(), OpalRBend::update(), and OpalSBend::update().
getDesign()
const ElementBase & Component::getDesign () const virtual inherited
Return design element.
Definition at line 33 of file Component.cpp.
References ElementBase::ElementBase().
getDesignEnergy()
double Component::getDesignEnergy () const inline virtual inherited
Reimplemented in BendBase, and RFCavity.
Definition at line 254 of file Component.h.
getEdgeToBegin()
CoordinateSystemTrafo ElementBase::getEdgeToBegin () const inline virtual inherited
Reimplemented in BendBase, RFCavity, Solenoid, and TravelingWave.
Definition at line 532 of file ElementBase.h.
Referenced by getBoundingBoxInLabCoords(), getEntryPort(), and isInsideTransverse().
getEdgeToEnd()
CoordinateSystemTrafo ElementBase::getEdgeToEnd () const inline virtual inherited
Reimplemented in BendBase, RFCavity, Solenoid, and TravelingWave.
Definition at line 537 of file ElementBase.h.
References getElementLength().
Referenced by getBoundingBoxInLabCoords(), and getExitPort().
getElementDimensions()
virtual void ElementBase::getElementDimensions (double & begin, double & end) const inline virtual inherited
Return the nominal body extent of the element.
The first placement redesign stage distinguishes between the nominal body extent and the field-support extent. The body extent is the canonical longitudinal interval of the placed hardware, \([z_\mathrm{body}^{\mathrm{begin}}, z_\mathrm{body}^{\mathrm{end}}]\), and therefore drives ports, placement, and visualization. By default it coincides with the geometry length \([0, L]\) in the local chart.
Reimplemented in RFCavity, Solenoid, and TravelingWave.
Definition at line 177 of file ElementBase.h.
References getElementLength().
Referenced by MeshGenerator::add().
getElementLength()
double ElementBase::getElementLength () const inline virtual inherited
Get design length.
Reimplemented in MarkerRep, RFCavity, TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 480 of file ElementBase.h.
References BGeometryBase::getElementLength(), and getGeometry().
Referenced by MeshGenerator::add(), BendBase::apply(), Component::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Multipole::apply(), Multipole::apply(), Multipole::apply(), VariableRFCavity::apply(), VariableRFCavity::apply(), VariableRFCavity::apply(), Component::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), getEdgeToEnd(), Solenoid::getEdgeToEnd(), getElementDimensions(), Solenoid::getElementDimensions(), RFCavity::getElementLength(), BendBase::getFieldExtend(), ConstantEFieldCavity::getFieldExtend(), Corrector::getFieldExtend(), Drift::getFieldExtend(), Laser::getFieldExtend(), Multipole::getFieldExtend(), MultipoleT::getFieldExtend(), VariableRFCavity::getFieldExtend(), BendBase::getLength(), BendBase::initialise(), ConstantEFieldCavity::initialise(), Corrector::initialise(), Drift::initialise(), Laser::initialise(), Multipole::initialise(), BendBase::isInside(), isInside(), Monitor::isInside(), Multipole::isInside(), isInsideTransverse(), and TEST_F().
getElementPosition()
double ElementBase::getElementPosition () const inline inherited
Definition at line 617 of file ElementBase.h.
References elemedgeSet_m, elementPosition_m, and getName().
getEntrance()
double ElementBase::getEntrance () const inline virtual inherited
Get entrance position.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 486 of file ElementBase.h.
References BGeometryBase::getEntrance(), and getGeometry().
Referenced by BendBase::getDesignPath().
getEntranceAngle()
double MultipoleT::getEntranceAngle () const inline inherited
Get the entrance angle
Definition at line 180 of file MultipoleT.h.
References config_m.
getEntranceFrame()
Euclid3D ElementBase::getEntranceFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 498 of file ElementBase.h.
References BGeometryBase::getEntranceFrame(), and getGeometry().
Referenced by BendBase::getChordLength(), and BendBase::getEdgeToBegin().
getEntrancePatch()
Euclid3D ElementBase::getEntrancePatch () const inline virtual inherited
Get patch.
Definition at line 502 of file ElementBase.h.
References BGeometryBase::getEntrancePatch(), and getGeometry().
getEntryOffset()
double MultipoleT::getEntryOffset () const inline inherited
Get the offset of the entry point from the standard position
Definition at line 172 of file MultipoleT.h.
References config_m.
getEntryPort()
Port ElementBase::getEntryPort () const inline virtual inherited
Return the entrance port of the canonical local chart.
In the placement-note language, this is the marked entrance port \(p_{i,\mathrm{entry}}\) of element \(i\). For straight elements in the bridge stage, the body-to-entry transform is taken from the legacy getEdgeToBegin() result.
Definition at line 544 of file ElementBase.h.
References getEdgeToBegin().
Referenced by getPlacementGeometry(), and TEST_F().
getExit()
double ElementBase::getExit () const inline virtual inherited
Get exit position.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 488 of file ElementBase.h.
References BGeometryBase::getExit(), and getGeometry().
Referenced by BendBase::getDesignPath().
getExitFrame()
Euclid3D ElementBase::getExitFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 500 of file ElementBase.h.
References BGeometryBase::getExitFrame(), and getGeometry().
Referenced by BendBase::getChordLength(), and BendBase::getEdgeToEnd().
getExitPatch()
Euclid3D ElementBase::getExitPatch () const inline virtual inherited
Get patch.
Definition at line 504 of file ElementBase.h.
References BGeometryBase::getExitPatch(), and getGeometry().
getExitPort()
Port ElementBase::getExitPort () const inline virtual inherited
Return the exit port of the canonical local chart.
In the placement-note language, this is the marked exit port \(p_{i,\mathrm{exit}}\). For straight elements in the bridge stage, the body-to-exit transform is taken from the legacy getEdgeToEnd() result.
Definition at line 548 of file ElementBase.h.
References getEdgeToEnd().
Referenced by getPlacementGeometry(), and TEST_F().
getField() [1/2]
const EMField & MultipoleT::getField () const inline override virtual inherited
Return a dummy field value
Implements Component.
Definition at line 93 of file MultipoleT.h.
References dummy.
getField() [2/2]
EMField & MultipoleT::getField () inline override virtual inherited
Return a dummy field value
Implements Component.
Definition at line 91 of file MultipoleT.h.
References dummy.
Referenced by TEST_F().
getFieldExtend()
void MultipoleT::getFieldExtend (double & zBegin, double & zEnd) const inline override virtual inherited
Return the longitudinal field-support extent.
For the current MultipoleT implementation the field support is defined on the full local body interval latexmath:[z \in [0, L)].
Implements Component.
Definition at line 220 of file MultipoleT.h.
References ElementBase::getElementLength().
getFlagDeleteOnTransverseExit()
bool ElementBase::getFlagDeleteOnTransverseExit () const inline inherited
Definition at line 633 of file ElementBase.h.
References deleteOnTransverseExit_m.
Referenced by BendBase::apply(), BendBase::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Multipole::apply(), Multipole::apply(), RFCavity::apply(), Solenoid::apply(), and TravelingWave::apply().
getFringeField()
std::tuple< double, double, double > MultipoleT::getFringeField () const inherited
Get the fringe field model
Returns
{s0, leftFringe, rightFringe}
Definition at line 96 of file MultipoleT.cpp.
References config_m.
getGeometry() [1/2]
const BGeometryBase & MultipoleT::getGeometry () const override virtual inherited
Return the cell geometry
Implements ElementBase.
Definition at line 189 of file MultipoleT.cpp.
References implementation_.
getGeometry() [2/2]
BGeometryBase & MultipoleT::getGeometry () override virtual inherited
Return the cell geometry
Implements ElementBase.
Definition at line 187 of file MultipoleT.cpp.
References implementation_.
Referenced by TEST_F(), and TEST_F().
getLength()
double MultipoleT::getLength () const inline inherited
Get the length of the magnet
Definition at line 187 of file MultipoleT.h.
References config_m.
getMaxFOrder()
size_t MultipoleT::getMaxFOrder () const inline inherited
Get the number of terms used in calculation of field components
Definition at line 132 of file MultipoleT.h.
References config_m.
getMaxXOrder()
size_t MultipoleT::getMaxXOrder () const inline inherited
Definition at line 133 of file MultipoleT.h.
References config_m.
getMisalignment() [1/2]
CoordinateSystemTrafo ElementBase::getMisalignment () const inline inherited
Definition at line 592 of file ElementBase.h.
References misalignment_m.
Referenced by getPlacementMisalignment().
getMisalignment() [2/2]
void ElementBase::getMisalignment (double & x, double & y, double & s) const inherited
getName()
const std::string & ElementBase::getName () const virtual inherited
Get element name.
Definition at line 131 of file ElementBase.cpp.
References elementID.
Referenced by Ring::appendElement(), TBeamline< T >::clone(), TBeamline< T >::copyStructure(), Probe::doGoOffline(), PlaceRep::enter(), getElementPosition(), RFCavity::getMomentaKick(), getOutputFN(), CavityAutophaser::getPhaseAtMaxEnergy(), Selector::handleElement(), RFCavity::initialise(), Ring::initialise(), Solenoid::initialise(), PlaceRep::leave(), VariableRFCavity::operator=(), Sequence::print(), Ring::Ring(), BeamlineFieldElement::SortAsc(), TEST_F(), Component::trackBunch(), Component::trackMap(), OpalRBend::update(), OpalSBend::update(), Sequence::updateList(), ParallelTracker::updateRFElement(), and Replacer::visitFlaggedElmPtr().
getOrigin()
double ElementBase::getOrigin () const inline virtual inherited
Get origin position.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 484 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getOrigin().
getOutputFN()
std::string ElementBase::getOutputFN () const inherited
Get output filename.
Definition at line 137 of file ElementBase.cpp.
References getName(), and outputfn_m.
Referenced by Probe::doInitialise(), Monitor::initialise(), and PluginElement::initialise().
getParticleMatterInteraction()
ParticleMatterInteractionHandler * ElementBase::getParticleMatterInteraction () const inline virtual inherited
Definition at line 516 of file ElementBase.h.
References parmatint_m.
getPlacedElement()
PlacedElement ElementBase::getPlacedElement () const inline inherited
Return a placed-element view assembled from the current bridge objects.
Definition at line 570 of file ElementBase.h.
References getPlacementGeometry(), getPlacementMisalignment(), getPlacementPose(), and getPlacementSupport().
Referenced by MeshGenerator::add(), and TEST_F().
getPlacementGeometry()
ElementGeometry ElementBase::getPlacementGeometry () const inline inherited
Return the bridge geometry ports assembled from legacy edge state.
The first redesign stage defines a minimal explicit port contract with three named body-relative ports: \(p_{i,\mathrm{entry}}\), \(p_{i,\mathrm{body}}\), \(p_{i,\mathrm{exit}}\). The default bridge preserves current OPALX behavior by deriving those ports from getEntryPort(), getBodyPort(), and getExitPort(), whose straight-element implementations are backed by the legacy getEdgeToBegin() and getEdgeToEnd() methods.
Definition at line 562 of file ElementBase.h.
References getBodyPort(), getEntryPort(), and getExitPort().
Referenced by getPlacedElement().
getPlacementMisalignment()
Misalignment ElementBase::getPlacementMisalignment () const inline inherited
Return the local nominal-to-actual correction stored for the element.
Definition at line 558 of file ElementBase.h.
References getMisalignment().
Referenced by getPlacedElement().
getPlacementPose()
PlacementPose ElementBase::getPlacementPose () const inline inherited
Return the nominal rigid placement transform of the element.
This is the bridge from the legacy stored CoordinateSystemTrafo to the new placement vocabulary. It preserves current nominal placement semantics and does not apply misalignment.
Definition at line 550 of file ElementBase.h.
References getCSTrafoGlobal2Local().
Referenced by getPlacedElement().
getPlacementSupport()
SupportPlacement ElementBase::getPlacementSupport () const inline inherited
Return the support-frame bridge object. The default is the body frame.
Definition at line 566 of file ElementBase.h.
Referenced by getPlacedElement().
getPotential()
virtual bool Component::getPotential (const Vector_t< double, 3 > & , const double & , Vector_t< double, 3 > & , double &) inline virtual inherited
Calculate the four-potential at some position relative to the component.
Parameters
R position in the local coordinate system of the component
t time
A filled with the calculated magnetic vector potential
phi filled with the calculated electric potential Note that any existing values in A and phi may be overwritten by this method.
Returns
true if particle is outside the field map, else false Default for component is to return false and make no change to A and phi
Definition at line 155 of file Component.h.
getRequiredNumberOfTimeSteps()
int ElementBase::getRequiredNumberOfTimeSteps () const inline virtual inherited
Reimplemented in BendBase, Drift, Laser, Marker, and Monitor.
Definition at line 627 of file ElementBase.h.
getRotation()
double MultipoleT::getRotation () const inline inherited
Get the angle of rotation of the magnet around its axis
Definition at line 207 of file MultipoleT.h.
References config_m.
getRotationAboutZ()
double ElementBase::getRotationAboutZ () const inline inherited
Definition at line 608 of file ElementBase.h.
References rotationZAxis_m.
Referenced by OpalBeamline::compileCompatibilityPlacement().
getScaling()
double MultipoleT::getScaling (double t) const protected inherited
Definition at line 41 of file MultipoleT.cpp.
References scalingTD_m.
Referenced by apply(), apply(), and apply().
getScalingName()
std::string MultipoleT::getScalingName () const inline inherited
Definition at line 226 of file MultipoleT.h.
References scalingName_m.
getTotalTransform()
Euclid3D ElementBase::getTotalTransform () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 494 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getTotalTransform().
getTransform() [1/2]
Euclid3D ElementBase::getTransform (double fromS, double toS) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 490 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getTransform().
Referenced by BendBase::getDesignPath(), and TBeamline< T >::getTransform().
getTransform() [2/2]
Euclid3D ElementBase::getTransform (double s) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 496 of file ElementBase.h.
References getGeometry(), and BGeometryBase::getTransform().
getTransMaxOrder()
std::size_t MultipoleT::getTransMaxOrder () const inline inherited
Get the maximum order in the given transverse profile
Definition at line 140 of file MultipoleT.h.
References config_m.
getTransProfile()
const Kokkos::Array< double, MultipoleTConfig::NumPoles > & MultipoleT::getTransProfile () const inline inherited
Get all terms of transverse profile
Definition at line 146 of file MultipoleT.h.
References config_m.
getType()
ElementType Component::getType () const virtual inherited
Get element type std::string.
Implements ElementBase.
Reimplemented in ConstantEFieldCavity, Corrector, Drift, Laser, Marker, Monitor, Multipole, Probe, RBend, RFCavity, SBend, Solenoid, and TravelingWave.
Definition at line 49 of file Component.cpp.
References ANY.
Referenced by ParallelTracker::visitComponent().
getTypeString() [1/2]
std::string ElementBase::getTypeString () const inline inherited
Definition at line 610 of file ElementBase.h.
References getType(), and getTypeString().
Referenced by getTypeString().
getTypeString() [2/2]
std::string ElementBase::getTypeString (ElementType type) static inherited
Definition at line 191 of file ElementBase.cpp.
References elementTypeToString_s.
getVariableRadius()
bool MultipoleT::getVariableRadius () const inline inherited
Get the variable radius of the magnet
Definition at line 174 of file MultipoleT.h.
References config_m.
getWake()
WakeFunction * ElementBase::getWake () const inline virtual inherited
return the attached wake object if there is any
Definition at line 508 of file ElementBase.h.
References wake_m.
goOffline()
void Component::goOffline () virtual inherited
Reimplemented in Monitor, PluginElement, RFCavity, Solenoid, and TravelingWave.
Definition at line 45 of file Component.cpp.
References online_m.
goOnline()
void Component::goOnline (const double & kineticEnergy) virtual inherited
Reimplemented in Corrector, Monitor, RFCavity, Solenoid, and TravelingWave.
Definition at line 43 of file Component.cpp.
References online_m.
Referenced by PluginElement::initialise().
grabLongitudinalDivCurlLine()
void TestMultipoleTStraight::grabLongitudinalDivCurlLine (std::vector< double > & fieldLine, std::vector< double > & divLine, std::vector< Vector_t< double, 3 > > & curlLine, const double x, const double length, const Vector_t< double, 3 > & elementEntry, const double elementLength, const double dr) inline
Definition at line 132 of file TestMultipoleTStraight.cpp.
References MultipoleT::apply(), and curvilinearToGlobal().
grabTransverseDataLine()
void TestMultipoleTStraight::grabTransverseDataLine (std::vector< double > & line, const double s, const double width, const Vector_t< double, 3 > & elementEntry, const double elementLength) inline
Definition at line 58 of file TestMultipoleTStraight.cpp.
References MultipoleT::apply(), curvilinearToGlobal(), MultipoleT::initialise(), and makeBunch().
grabVerticalDataLine()
void TestMultipoleTStraight::grabVerticalDataLine (std::vector< double > & line, const double s, const double height, const Vector_t< double, 3 > & elementEntry, const double elementLength) inline
Definition at line 95 of file TestMultipoleTStraight.cpp.
References MultipoleT::apply(), curvilinearToGlobal(), MultipoleT::initialise(), and makeBunch().
hasAttribute()
bool ElementBase::hasAttribute (const std::string & aKey) const virtual inherited
Test for existence of an attribute.
Definition at line 158 of file ElementBase.cpp.
References getConstChannel().
hasBoundaryGeometry()
bool ElementBase::hasBoundaryGeometry () const inline virtual inherited
Definition at line 514 of file ElementBase.h.
References bgeometry_m.
hasParticleMatterInteraction()
bool ElementBase::hasParticleMatterInteraction () const inline virtual inherited
Definition at line 520 of file ElementBase.h.
References parmatint_m.
hasWake()
bool ElementBase::hasWake () const inline virtual inherited
Definition at line 510 of file ElementBase.h.
References wake_m.
initialise()
void MultipoleT::initialise (PartBunch_t * bunch, double & startField, double & endField) override virtual inherited
Initialise the MultipoleT
Parameters
bunch -> Bunch the global bunch object
startField -> Not used
endField -> Not used
Implements Component.
Definition at line 167 of file MultipoleT.cpp.
References implementation_, and Component::RefPartBunch_m.
Referenced by TestMultipoleTCurvedConstRadius::grabTransverseDataLine(), TestMultipoleTStraight::grabTransverseDataLine(), TestMultipoleTCurvedConstRadius::grabVerticalDataLine(), and TestMultipoleTStraight::grabVerticalDataLine().
initialiseTimeDependencies()
void MultipoleT::initialiseTimeDependencies () const inherited
Definition at line 180 of file MultipoleT.cpp.
References AbstractTimeDependence::getTimeDependence(), scalingName_m, and scalingTD_m.
Referenced by accept().
isElementPositionSet()
bool ElementBase::isElementPositionSet () const inline inherited
Definition at line 625 of file ElementBase.h.
References elemedgeSet_m.
isInside()
bool ElementBase::isInside (const Vector_t< double, 3 > & r) const inline virtual inherited
Reimplemented in BendBase, Monitor, Multipole, RFCavity, Solenoid, and TravelingWave.
Definition at line 585 of file ElementBase.h.
References getElementLength(), and isInsideTransverse().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
isInsideTransverse()
bool ElementBase::isInsideTransverse (const Vector_t< double, 3 > & r) const protected inherited
Definition at line 232 of file ElementBase.cpp.
References aperture_m, CONIC_ELLIPTICAL, CONIC_RECTANGULAR, getEdgeToBegin(), getElementLength(), and CoordinateSystemTrafo::transformTo().
Referenced by BendBase::apply(), BendBase::apply(), Component::apply(), ConstantEFieldCavity::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Multipole::apply(), Multipole::apply(), BendBase::applyToReferenceParticle(), Component::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), BendBase::isInside(), isInside(), Monitor::isInside(), Multipole::isInside(), RFCavity::isInside(), Solenoid::isInside(), and TravelingWave::isInside().
isPositioned()
bool ElementBase::isPositioned () const inline inherited
Definition at line 598 of file ElementBase.h.
References positionIsFixed.
Referenced by OpalRBend::update(), and OpalSBend::update().
isSharable()
bool ElementBase::isSharable () const inline inherited
Test if the element can be shared.
Definition at line 506 of file ElementBase.h.
References shareFlag.
Referenced by copyStructure(), TBeamline< T >::copyStructure(), and Sequence::updateList().
makeBunch()
std::shared_ptr< PartBunch_t > TestMultipoleTStraight::makeBunch (const size_t numParticles) inline
Definition at line 189 of file TestMultipoleTStraight.cpp.
References dataSink_m, Beam::find(), and fsCmdBase_m.
Referenced by grabTransverseDataLine(), and grabVerticalDataLine().
makeSharable()
void ElementBase::makeSharable () virtual inherited
Set sharable flag.
Reimplemented in TBeamline< T >, TBeamline< FlaggedElmPtr >, and TBeamline< SequenceMember >.
Definition at line 201 of file ElementBase.cpp.
References shareFlag.
Referenced by OpalMarker::OpalMarker().
Online()
bool Component::Online () virtual inherited
Definition at line 47 of file Component.cpp.
References online_m.
releasePosition()
void ElementBase::releasePosition () inline inherited
Definition at line 594 of file ElementBase.h.
References positionIsFixed.
Referenced by OpalRBend::update(), and OpalSBend::update().
removeAttribute()
void ElementBase::removeAttribute (const std::string & aKey) virtual inherited
Remove an existing attribute.
Definition at line 169 of file ElementBase.cpp.
References userAttribs.
setActionRange()
void ElementBase::setActionRange (const std::queue< std::pair< double, double > > & range) inline inherited
Definition at line 600 of file ElementBase.h.
References actionRange_m, and elementEdge_m.
setAperture() [1/2]
void ElementBase::setAperture (const ApertureType & type, const std::vector< double > & args) inline inherited
Definition at line 576 of file ElementBase.h.
References aperture_m.
Referenced by Component::Component(), TEST_F(), TEST_F(), TEST_F(), OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
setAperture() [2/2]
void MultipoleT::setAperture (const double & vertAp, const double & horizAp) inherited
Set the aperture dimensions
This element only supports a rectangular aperture
Parameters
vertAp -> Vertical aperture length
horizAp -> Horisontal aperture length
Definition at line 129 of file MultipoleT.cpp.
References config_m.
setAttribute()
void ElementBase::setAttribute (const std::string & aKey, double val) virtual inherited
Set value of an attribute.
Definition at line 171 of file ElementBase.cpp.
References getChannel(), and Channel::isSettable().
Referenced by update(), and OpalElement::updateUnknown().
setBendAngle()
void MultipoleT::setBendAngle (double angle, bool variableRadius) inherited
Set the bending angle of the magnet
Definition at line 110 of file MultipoleT.cpp.
References chooseImplementation(), and config_m.
setBoundaryGeometry()
void ElementBase::setBoundaryGeometry (BoundaryGeometry * geo) virtual inherited
attach a boundary geometry field to the element
Definition at line 215 of file ElementBase.cpp.
References bgeometry_m.
setBoundingBoxLength()
void MultipoleT::setBoundingBoxLength (double boundingBoxLength) inherited
Set the bounding box size. This controls the region for
Parameters
boundingBoxLength -> Distance between centre and entrance
Definition at line 134 of file MultipoleT.cpp.
References config_m.
setCSTrafoGlobal2Local()
void ElementBase::setCSTrafoGlobal2Local (const CoordinateSystemTrafo & ori) inline inherited
Definition at line 522 of file ElementBase.h.
References csTrafoGlobal2Local_m, and positionIsFixed.
Referenced by setPlacementPose(), TEST_F(), OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
setCurrentSCoordinate()
void ElementBase::setCurrentSCoordinate (double s) inherited
Definition at line 223 of file ElementBase.cpp.
References actionRange_m, and elementEdge_m.
setDesignEnergy()
void Component::setDesignEnergy (const double & energy, bool changeable = true) inline virtual inherited
Reimplemented in BendBase, Corrector, and RFCavity.
Definition at line 252 of file Component.h.
setElementLength()
void MultipoleT::setElementLength (double length) override virtual inherited
Set the length of the magnet If straight-> Actual length If curved -> Arc length
Reimplemented from ElementBase.
Definition at line 102 of file MultipoleT.cpp.
References config_m, implementation_, and ElementBase::setElementLength().
Referenced by OpalMultipoleT::update().
setElementPosition()
void ElementBase::setElementPosition (double elemedge) inline inherited
Access to ELEMEDGE attribute.
Definition at line 612 of file ElementBase.h.
References elemedgeSet_m, and elementPosition_m.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and OpalElement::update().
setEntranceAngle()
void MultipoleT::setEntranceAngle (double entranceAngle) inherited
Set the entrance angle
Parameters
entranceAngle -> Entrance angle
Definition at line 159 of file MultipoleT.cpp.
References config_m.
setEntryOffset()
void MultipoleT::setEntryOffset (double offset) inherited
Set the offset of the entry point from the standard position
Parameters
offset positive for further away from the center
Definition at line 163 of file MultipoleT.cpp.
References config_m.
setExitFaceSlope()
void Component::setExitFaceSlope (const double & m) inline inherited
Definition at line 250 of file Component.h.
References exit_face_slope_m.
setFlagDeleteOnTransverseExit()
void ElementBase::setFlagDeleteOnTransverseExit (bool flag = true) inline inherited
Definition at line 629 of file ElementBase.h.
References deleteOnTransverseExit_m.
Referenced by OpalElement::update().
setFringeField()
void MultipoleT::setFringeField (const double & s0, const double & lambda_left, const double & lambda_right) inherited
Set fringe field model
Tanh model used here
\[ 1/2 * \left [tanh \left(\frac{s + s_0}{\lambda_{left}} \right) - tanh \left(\frac{s - s_0}{\lambda_{right}} \right) \right] \]
Parameters
s0 -> Centre field length and
lambda_left -> Left end field length
lambda_right -> Right end field length
Definition at line 88 of file MultipoleT.cpp.
References config_m, and implementation_.
setMaxOrder()
void MultipoleT::setMaxOrder (size_t orderZ, size_t orderX) inherited
Set the number of terms used in calculation of field components
Parameters
orderZ -> Number of terms in expansion in z
orderX -> Number of terms in expansion in x
Definition at line 151 of file MultipoleT.cpp.
References config_m, and implementation_.
setMisalignment()
void ElementBase::setMisalignment (const CoordinateSystemTrafo & cst) inline inherited
Definition at line 590 of file ElementBase.h.
References misalignment_m.
Referenced by TEST_F(), and OpalElement::update().
setName()
void ElementBase::setName (const std::string & name) virtual inherited
Set element name.
Definition at line 133 of file ElementBase.cpp.
References elementID.
Referenced by Sequence::insertDrifts(), and VariableRFCavity::operator=().
setOutputFN()
void ElementBase::setOutputFN (std::string fn) inherited
Set output filename.
Definition at line 135 of file ElementBase.cpp.
Referenced by OpalMonitor::update(), and OpalProbe::update().
setParticleMatterInteraction()
void ElementBase::setParticleMatterInteraction (ParticleMatterInteractionHandler * spys) virtual inherited
Definition at line 219 of file ElementBase.cpp.
References parmatint_m.
setPlacementPose()
void ElementBase::setPlacementPose (const PlacementPose & pose) inline inherited
Set the nominal rigid placement transform of the element.
This bridge setter preserves the existing storage model by delegating to setCSTrafoGlobal2Local().
Definition at line 554 of file ElementBase.h.
References PlacementPose::getParentToNominal(), and setCSTrafoGlobal2Local().
setRotation()
void MultipoleT::setRotation (double rot) inherited
Set the angle of rotation of the magnet around its axis
To make skew components
Parameters
rot -> Angle of rotation
Definition at line 157 of file MultipoleT.cpp.
References config_m.
setRotationAboutZ()
void ElementBase::setRotationAboutZ (double rotation) inline inherited
Set rotation about z axis in bend frame.
Definition at line 606 of file ElementBase.h.
References rotationZAxis_m.
Referenced by OpalElement::update().
setScalingName()
void MultipoleT::setScalingName (const std::string & name) inherited
Definition at line 172 of file MultipoleT.cpp.
References scalingName_m.
setTransProfile()
void MultipoleT::setTransProfile (const std::vector< double > & profile) inherited
Set the the transverse profile
Parameters
profile -> Multipole field profile
Definition at line 138 of file MultipoleT.cpp.
References config_m, and MultipoleTConfig::NumPoles.
SetUpTestSuite()
void TestMultipoleTStraight::SetUpTestSuite () inline static
Definition at line 29 of file TestMultipoleTStraight.cpp.
References Options::enableHDF5, OpalData::getInstance(), gmsg, and OpalData::storeInputFn().
setWake()
void ElementBase::setWake (WakeFunction * wf) virtual inherited
attach a wake field to the element
Definition at line 211 of file ElementBase.cpp.
References wake_m.
TearDownTestSuite()
void TestMultipoleTStraight::TearDownTestSuite () inline static
Definition at line 42 of file TestMultipoleTStraight.cpp.
References gmsg.
trackBunch()
void Component::trackBunch (PartBunch_t & bunch, const PartData & , bool revBeam, bool revTrack) const virtual inherited
Track a borrowed particle bunch through a non-standard component.
The default implementation throws a LogicalError.
Parameters
bunch Particle bunch to track. The component does not take ownership.
Definition at line 35 of file Component.cpp.
References ElementBase::getName().
Referenced by Tracker::visitComponent().
trackMap()
void Component::trackMap (FVps< double, 6 > & map, const PartData & , bool revBeam, bool revTrack) const virtual inherited
Track a map.
Definition at line 39 of file Component.cpp.
References ElementBase::getName().
update()
bool ElementBase::update (const AttributeSet & set) inherited
Update element.
Definition at line 203 of file ElementBase.cpp.
References AttributeSet::begin(), AttributeSet::end(), and setAttribute().
validateConfiguration()
void MultipoleT::validateConfiguration () const protected inherited
Definition at line 191 of file MultipoleT.cpp.
References config_m, and MultipoleTBase::MaxDerivatives.
Referenced by apply(), apply(), and apply().
Member Data Documentation
actionRange_m
std::queue<std::pair<double, double> > ElementBase::actionRange_m private inherited
Definition at line 468 of file ElementBase.h.
Referenced by setActionRange(), and setCurrentSCoordinate().
aperture_m
std::pair<ApertureType, std::vector<double> > ElementBase::aperture_m protected inherited
Definition at line 439 of file ElementBase.h.
Referenced by ElementBase(), getAperture(), isInsideTransverse(), and setAperture().
bgeometry_m
BoundaryGeometry* ElementBase::bgeometry_m private inherited
Definition at line 459 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getBoundaryGeometry(), hasBoundaryGeometry(), and setBoundaryGeometry().
config_m
MultipoleTConfig MultipoleT::config_m protected inherited
The magnet configuration
Definition at line 233 of file MultipoleT.h.
Referenced by bends(), chooseImplementation(), getAperture(), getBendAngle(), getBoundingBoxLength(), getConfig(), getEntranceAngle(), getEntryOffset(), getFringeField(), getLength(), getMaxFOrder(), getMaxXOrder(), getRotation(), getTransMaxOrder(), getTransProfile(), getVariableRadius(), MultipoleT(), setAperture(), setBendAngle(), setBoundingBoxLength(), setElementLength(), setEntranceAngle(), setEntryOffset(), setFringeField(), setMaxOrder(), setRotation(), setTransProfile(), and validateConfiguration().
csTrafoGlobal2Local_m
CoordinateSystemTrafo ElementBase::csTrafoGlobal2Local_m protected inherited
Definition at line 436 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getBoundingBoxInLabCoords(), getCSTrafoGlobal2Local(), and setCSTrafoGlobal2Local().
dataSink_m
std::shared_ptr<DataSink> TestMultipoleTStraight::dataSink_m
Definition at line 187 of file TestMultipoleTStraight.cpp.
Referenced by makeBunch().
defaultAperture_m
const std::vector< double > Component::defaultAperture_m = std::vector<double>({1e6, 1e6, 1.0}) static protected inherited
Definition at line 221 of file Component.h.
Referenced by Component().
deleteOnTransverseExit_m
bool ElementBase::deleteOnTransverseExit_m = true private inherited
Definition at line 472 of file ElementBase.h.
Referenced by ElementBase(), getFlagDeleteOnTransverseExit(), and setFlagDeleteOnTransverseExit().
dummy
BMultipoleField MultipoleT::dummy protected inherited
Not implemented
Definition at line 240 of file MultipoleT.h.
Referenced by getField(), and getField().
elemedgeSet_m
bool ElementBase::elemedgeSet_m private inherited
Definition at line 466 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getElementPosition(), isElementPositionSet(), and setElementPosition().
elementEdge_m
double ElementBase::elementEdge_m protected inherited
Definition at line 441 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), setActionRange(), and setCurrentSCoordinate().
elementID
std::string ElementBase::elementID private inherited
Definition at line 450 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getName(), and setName().
elementPosition_m
double ElementBase::elementPosition_m private inherited
ELEMEDGE attribute.
Definition at line 465 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getElementPosition(), and setElementPosition().
elementTypeToString_s
const std::map< ElementType, std::string > ElementBase::elementTypeToString_s static private inherited
Initial value:
= {
        {ElementType::ANY, "Any"},
        {ElementType::BEAMLINE, "Beamline"},
        {ElementType::DRIFT, "Drift"},
        {ElementType::LASER, "Laser"},
        {ElementType::MARKER, "Marker"},
        {ElementType::MULTIPOLE, "Multipole"},
        {ElementType::RFCAVITY, "RFCavity"},
        {ElementType::TRAVELINGWAVE, "TravelingWave"},
        {ElementType::SBEND, "SBEND"},
        {ElementType::RBEND, "RBEND"},
        {ElementType::RBEND3D, "RBEND3D"},
        {ElementType::RING, "Ring"},
        {ElementType::SOURCE, "SOURCE"},
        {ElementType::SOLENOID, "SOLENOID"},
        {ElementType::PROBE, "Probe"},
        {ElementType::VACUUM, "Vacuum"},
        {ElementType::CONSTANTEFIELDCAVITY, "ConstantEFieldCavity"}}
Definition at line 73 of file ElementBase.h.
Referenced by getTypeString().
exit_face_slope_m
double Component::exit_face_slope_m protected inherited
Definition at line 222 of file Component.h.
Referenced by Component(), Component(), and setExitFaceSlope().
fsCmdBase_m
std::shared_ptr<FieldSolverCmd> TestMultipoleTStraight::fsCmdBase_m
Definition at line 186 of file TestMultipoleTStraight.cpp.
Referenced by makeBunch().
implementation_
std::unique_ptr<MultipoleTBase> MultipoleT::implementation_ {} protected inherited
Definition at line 247 of file MultipoleT.h.
Referenced by apply(), apply(), apply(), chooseImplementation(), getGeometry(), getGeometry(), initialise(), setElementLength(), setFringeField(), and setMaxOrder().
misalignment_m
CoordinateSystemTrafo ElementBase::misalignment_m protected inherited
Definition at line 437 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getMisalignment(), and setMisalignment().
online_m
bool Component::online_m protected inherited
Definition at line 226 of file Component.h.
Referenced by Component(), Component(), Probe::doGoOffline(), BendBase::finalise(), Multipole::finalise(), PluginElement::finalise(), Ring::finalise(), goOffline(), PluginElement::goOffline(), RFCavity::goOffline(), Solenoid::goOffline(), goOnline(), Corrector::goOnline(), Monitor::goOnline(), RFCavity::goOnline(), Solenoid::goOnline(), TravelingWave::goOnline(), BendBase::initialise(), Multipole::initialise(), Ring::initialise(), Online(), and PluginElement::~PluginElement().
outputfn_m
std::string ElementBase::outputfn_m private inherited
The name of the outputfile
Definition at line 470 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), and getOutputFN().
parmatint_m
ParticleMatterInteractionHandler* ElementBase::parmatint_m private inherited
Definition at line 461 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getParticleMatterInteraction(), hasParticleMatterInteraction(), and setParticleMatterInteraction().
positionIsFixed
bool ElementBase::positionIsFixed private inherited
Definition at line 463 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), fixPosition(), isPositioned(), releasePosition(), and setCSTrafoGlobal2Local().
RefPartBunch_m
PartBunch_t* Component::RefPartBunch_m protected inherited
Definition at line 225 of file Component.h.
Referenced by BendBase::apply(), ConstantEFieldCavity::apply(), Corrector::apply(), Corrector::apply(), Multipole::apply(), MultipoleT::apply(), MultipoleT::apply(), RFCavity::apply(), RFCavity::apply(), Ring::apply(), ScalingFFAMagnet::apply(), Solenoid::apply(), TravelingWave::apply(), TravelingWave::apply(), VariableRFCavity::apply(), VariableRFCavity::apply(), VerticalFFAMagnet::apply(), BendBase::calcDesignRadius(), BendBase::calcFieldAmplitude(), BendBase::calcGamma(), Component(), MultipoleT::finalise(), ScalingFFAMagnet::finalise(), VariableRFCavity::finalise(), VerticalFFAMagnet::finalise(), Corrector::goOnline(), BendBase::initialise(), ConstantEFieldCavity::initialise(), Corrector::initialise(), Drift::initialise(), Laser::initialise(), Marker::initialise(), Monitor::initialise(), Multipole::initialise(), MultipoleT::initialise(), PluginElement::initialise(), RFCavity::initialise(), RFCavity::initialise(), ScalingFFAMagnet::initialise(), Solenoid::initialise(), TravelingWave::initialise(), VariableRFCavity::initialise(), VerticalFFAMagnet::initialise(), VariableRFCavity::initNull(), Multipole::isFocusing(), MultipoleT::MultipoleT(), ScalingFFAMagnet::ScalingFFAMagnet(), Corrector::setDesignEnergy(), Ring::setRefPartBunch(), RFCavity::trackOnAxisParticle(), and VerticalFFAMagnet::VerticalFFAMagnet().
rotationZAxis_m
double ElementBase::rotationZAxis_m protected inherited
Definition at line 443 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getRotationAboutZ(), and setRotationAboutZ().
scalingName_m
std::string MultipoleT::scalingName_m protected inherited
Definition at line 243 of file MultipoleT.h.
Referenced by getScalingName(), initialiseTimeDependencies(), MultipoleT(), and setScalingName().
scalingTD_m
std::shared_ptr<AbstractTimeDependence> MultipoleT::scalingTD_m mutable protected inherited
Definition at line 244 of file MultipoleT.h.
Referenced by getScaling(), initialiseTimeDependencies(), and MultipoleT().
shareFlag
bool ElementBase::shareFlag mutable protected inherited
Definition at line 434 of file ElementBase.h.
Referenced by Beamline::Beamline(), Beamline::Beamline(), Beamline::Beamline(), ElementBase(), ElementBase(), isSharable(), makeSharable(), and TBeamline< T >::makeSharable().
userAttribs
AttributeSet ElementBase::userAttribs private inherited
Definition at line 455 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getChannel(), and removeAttribute().
wake_m
WakeFunction* ElementBase::wake_m private inherited
Definition at line 457 of file ElementBase.h.
Referenced by ElementBase(), ElementBase(), getWake(), hasWake(), and setWake().
The documentation for this class was generated from the following file:
TestMultipoleTStraight.cpp