OPALX (Object Oriented Parallel Accelerator Library for Exascal): RealConstant Class Reference
RealConstant Class Reference
#include <RealConstant.h>
Public Member Functions
RealConstant ()
Exemplar constructor.
RealConstant (const std::string &name, RealConstant *parent, double value)
Constructor for built-in constants.
virtual ~RealConstant ()
virtual bool canReplaceBy (Object *object)
Test if object can be replaced.
virtual RealConstant * clone (const std::string &name)
Make clone.
virtual void print (std::ostream &) const
Print the constant.
virtual void printValue (std::ostream &os) const
Print its value.
virtual double getReal () const
Return value.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual bool getBool () const
Return logical value.
virtual bool getBoolComponent (int) const
Return indexed logical value.
virtual double getRealComponent (int) const
Return indexed real value.
virtual std::string getString () const
Return string value.
virtual std::string getStringComponent (int) const
Return indexed string value.
Attribute & value ()
Return the attribute representing the value of the definition.
const Attribute & value () const
Return the attribute representing the value of the definition.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Attributes
std::vector< Attribute > itsAttr
The object attributes.
Protected Attributes
const std::string itsPrefix
The declaration prefix.
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Private Member Functions
RealConstant (const RealConstant &)
void operator= (const RealConstant &)
RealConstant (const std::string &name, RealConstant *parent)
Private Attributes
Object * itsParent
std::string itsName
std::string itsHelp
int occurrence
double timeStamp
std::set< Invalidator * > references
bool sharedFlag
Detailed Description
Definition at line 23 of file RealConstant.h.
Constructor & Destructor Documentation
RealConstant() [1/4]
RealConstant::RealConstant ()
Exemplar constructor.
Definition at line 31 of file RealConstant.cpp.
References Physics::amu, Physics::c, OpalData::create(), Units::deg2rad, Physics::e, OpalData::getInstance(), Object::itsAttr, Physics::m_alpha, Physics::m_c, Physics::m_d, Physics::m_e, Physics::m_h2p, Physics::m_hm, Physics::m_mu, Physics::m_p, Physics::m_u, Physics::m_xe, Attributes::makeReal(), Physics::pi, Units::rad2deg, RealConstant(), Object::registerOwnership(), AttributeHandler::STATEMENT, and Physics::two_pi.
Referenced by clone(), and RealConstant().
RealConstant() [2/4]
RealConstant::RealConstant (const std::string & name, RealConstant * parent, double value)
Constructor for built-in constants.
Definition at line 73 of file RealConstant.cpp.
References Object::builtin, Object::itsAttr, Attributes::setReal(), and ValueDefinition::value().
~RealConstant()
RealConstant::~RealConstant () virtual
Definition at line 80 of file RealConstant.cpp.
RealConstant() [3/4]
RealConstant::RealConstant (const RealConstant &) private
RealConstant() [4/4]
RealConstant::RealConstant (const std::string & name, RealConstant * parent) private
Definition at line 70 of file RealConstant.cpp.
Member Function Documentation
canReplaceBy()
bool RealConstant::canReplaceBy (Object * object) virtual
Test if object can be replaced.
Reimplemented from Object.
Definition at line 82 of file RealConstant.cpp.
clear()
void Object::clear () inherited
Clear the occurrence counter.
Definition at line 285 of file Object.cpp.
References Object::occurrence.
clone()
RealConstant * RealConstant::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 84 of file RealConstant.cpp.
References RealConstant().
copyAttributes()
void Object::copyAttributes (const Object & source) inherited
Copy attributes from another object.
Definition at line 50 of file Object.cpp.
References Object::itsAttr.
Referenced by SequenceTemplate::makeInstance(), and LineTemplate::makeInstance().
execute()
void Object::execute () virtual inherited
Execute the command.
Reimplemented in Call, Echo, Help, Option, PSystem, Quit, Select, Stop, System, Title, Value, Distribution, EmissionSourceList, MacroCmd, Beam, BinningCmd, BoundaryGeometry, EmissionSource, FieldSolverCmd, TrackCmd, TrackEnd, TrackRun, OpalFilter, and DumpEMFields.
Definition at line 52 of file Object.cpp.
findAttribute() [1/2]
Attribute * Object::findAttribute (const std::string & name) virtual inherited
Find an attribute by name.
Definition at line 56 of file Object.cpp.
References Object::itsAttr.
Referenced by SequenceParser::findNeighbourPositions(), OpalElement::getParticleMatterInteraction(), OpalElement::getTypeName(), OpalElement::getWakeF(), Object::parse(), OpalElement::parse(), Line::parse(), OpalParser::parseAssign(), SequenceParser::parsePosition(), TrackRun::print(), and TEST().
findAttribute() [2/2]
const Attribute * Object::findAttribute (const std::string & name) const virtual inherited
Find an attribute by name.
Definition at line 63 of file Object.cpp.
References Object::itsAttr.
getBaseObject()
const Object * Object::getBaseObject () const inherited
Return the object's base type object.
Definition at line 260 of file Object.cpp.
References Object::itsParent.
getBool()
bool ValueDefinition::getBool () const virtual inherited
Return logical value.
Reimplemented in BoolConstant.
Definition at line 35 of file ValueDefinition.cpp.
References Object::getOpalName().
getBoolComponent()
bool ValueDefinition::getBoolComponent (int) const virtual inherited
Return indexed logical value.
Definition at line 41 of file ValueDefinition.cpp.
References Object::getOpalName().
getCategory()
const std::string ValueDefinition::getCategory () const virtual inherited
Return the object category as a string.
Implements Object.
Definition at line 29 of file ValueDefinition.cpp.
getOpalName()
const std::string & Object::getOpalName () const inherited
Return object name.
Definition at line 267 of file Object.cpp.
References Object::itsName.
Referenced by OpalVariableRFCavity::clone(), Macro::clone(), OpalData::create(), OpalData::define(), Sequence::findDriftLength(), SequenceParser::findNeighbourPositions(), ValueDefinition::getBool(), ValueDefinition::getBoolComponent(), ValueDefinition::getReal(), ValueDefinition::getRealComponent(), ValueDefinition::getString(), ValueDefinition::getStringComponent(), Object::makeInstance(), SequenceTemplate::makeInstance(), LineTemplate::makeInstance(), Object::parse(), SequenceParser::parseMember(), SequenceParser::parsePosition(), Object::print(), OpalElement::print(), Sequence::print(), TrackRun::print(), BoolConstant::print(), print(), RealVariable::print(), RealVector::print(), StringConstant::print(), Beam::print(), OpalFilter::print(), Line::print(), BinningCmd::printInfo(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), OpalElement::registerOwnership(), Object::registerOwnership(), Line::replace(), Sequence::replace(), PartBunch< T, Dim >::setBins(), TEST(), TEST(), TEST(), TEST_F(), Beam::update(), BoundaryGeometry::update(), OpalFilter::update(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), and OpalSplineTimeDependence::update().
getParent()
Object * Object::getParent () const inherited
Return parent pointer.
Definition at line 269 of file Object.cpp.
References Object::itsParent.
Referenced by OpalData::erase(), Object::print(), OpalElement::print(), OpalElement::registerOwnership(), and Object::registerOwnership().
getReal()
double RealConstant::getReal () const virtual
Return value.
Reimplemented from ValueDefinition.
Definition at line 86 of file RealConstant.cpp.
References Attributes::getReal(), and Object::itsAttr.
getRealComponent()
double ValueDefinition::getRealComponent (int) const virtual inherited
Return indexed real value.
Reimplemented in RealVector.
Definition at line 53 of file ValueDefinition.cpp.
References Object::getOpalName().
getString()
std::string ValueDefinition::getString () const virtual inherited
Return string value.
Reimplemented in StringConstant.
Definition at line 59 of file ValueDefinition.cpp.
References Object::getOpalName().
getStringComponent()
std::string ValueDefinition::getStringComponent (int) const virtual inherited
Return indexed string value.
Definition at line 65 of file ValueDefinition.cpp.
References Object::getOpalName().
increment()
int Object::increment () inherited
Increment and return the occurrence counter.
Definition at line 287 of file Object.cpp.
References Object::occurrence.
Referenced by Line::parse(), and Sequence::storeLine().
isBuiltin()
bool Object::isBuiltin () const inherited
True, if [b]this[/b] is a built-in object.
Definition at line 243 of file Object.cpp.
References Object::builtin.
Referenced by OpalData::define(), and OpalData::getVariableNames().
isDirty()
bool Object::isDirty () const inherited
True, if the [b]modified[/b] flag is set.
Definition at line 254 of file Object.cpp.
References Object::modified.
isFlagged()
bool Object::isFlagged () const inherited
True, if [b]this[/b] is flagged by setFlag(true).
Definition at line 258 of file Object.cpp.
References Object::flagged.
isShared()
bool Object::isShared () const virtual inherited
Shared flag.
Definition at line 245 of file Object.cpp.
References Object::sharedFlag.
Referenced by Sequence::print().
isTreeMember()
bool Object::isTreeMember (const Object * subTree) const inherited
Test for tree membership.
Definition at line 271 of file Object.cpp.
References Object::itsParent.
Referenced by Selector::handleElement(), and OpalParser::parseAssign().
makeInstance()
Object * Object::makeInstance (const std::string & name, Statement & , const Parser *) virtual inherited
Macro handler function.
Reimplemented in SequenceTemplate, MacroCmd, and LineTemplate.
Definition at line 76 of file Object.cpp.
References Object::getOpalName().
Referenced by OpalParser::parseDefine(), and OpalParser::parseMacro().
makeTemplate()
Object * Object::makeTemplate (const std::string & name, TokenStream & , Statement &) virtual inherited
Macro handler function.
Reimplemented in LineTemplate, Sequence, MacroCmd, SequenceTemplate, and Line.
Definition at line 71 of file Object.cpp.
Referenced by OpalParser::parseMacro().
occurrenceCount()
int Object::occurrenceCount () inherited
Return the occurrence counter.
Definition at line 289 of file Object.cpp.
References Object::occurrence.
operator=()
void RealConstant::operator= (const RealConstant &) private
parse()
void Object::parse (Statement & stat) virtual inherited
Parse the object.
Reimplemented in Call, Echo, Help, PSystem, System, Title, Value, OpalElement, Sequence, EmissionSourceList, and Line.
Definition at line 82 of file Object.cpp.
References Statement::delimiter(), Object::findAttribute(), Object::getOpalName(), Expressions::parseDelimiter(), Expressions::parseRealConst(), and Expressions::parseString().
Referenced by Sequence::parse(), OpalParser::parseAction(), OpalParser::parseDefine(), and SequenceTemplate::parseTemplate().
parseShortcut()
void Object::parseShortcut (Statement & stat, bool eval = true) virtual inherited
Parser for single-attribute commands.
Definition at line 113 of file Object.cpp.
Referenced by Call::parse(), Echo::parse(), Help::parse(), PSystem::parse(), System::parse(), Title::parse(), and Value::parse().
print()
void RealConstant::print (std::ostream & os) const virtual
Print the constant.
Reimplemented from Object.
Definition at line 88 of file RealConstant.cpp.
References Object::getOpalName(), and Object::itsAttr.
printHelp()
void Object::printHelp (std::ostream &) const virtual inherited
Print help.
Definition at line 179 of file Object.cpp.
References gmsg, Object::itsAttr, and Object::itsHelp.
Referenced by Help::execute().
printValue()
void RealConstant::printValue (std::ostream & os) const virtual
Print its value.
Reimplemented from Object.
Definition at line 93 of file RealConstant.cpp.
References Object::itsAttr.
registerOwnership()
void Object::registerOwnership (const AttributeHandler::OwnerType & itsClass) const inherited
Definition at line 169 of file Object.cpp.
References AttributeHandler::addAttributeOwner(), Object::getOpalName(), Object::getParent(), and Object::itsAttr.
Referenced by Beam::Beam(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), Call::Call(), Distribution::Distribution(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), EmissionSourceList::EmissionSourceList(), Help::Help(), Line::Line(), OpalFilter::OpalFilter(), Option::Option(), PSystem::PSystem(), RealConstant(), RealVariable::RealVariable(), RealVector::RealVector(), Select::Select(), Sequence::Sequence(), StringConstant::StringConstant(), System::System(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), and Value::Value().
registerReference()
void Object::registerReference (Invalidator * a) inherited
Register a reference to this object.
Definition at line 165 of file Object.cpp.
References Object::references.
replace()
void Object::replace (Object * oldObject, Object * newObject) virtual inherited
Replace references.
Reimplemented in Line, and Sequence.
Definition at line 235 of file Object.cpp.
setDirty()
void Object::setDirty (bool dirty) inherited
Set/reset the [b]modified[/b] flag.
Definition at line 249 of file Object.cpp.
References Object::modified.
Referenced by OpalData::define(), OpalData::makeDirty(), and RealVariable::RealVariable().
setFlag()
void Object::setFlag (bool flag) inherited
Flag/unflag this object, e. g. to control output of objects for.
Definition at line 256 of file Object.cpp.
References Object::flagged.
setOpalName()
void Object::setOpalName (const std::string & name) inherited
Set object name.
Definition at line 281 of file Object.cpp.
References Object::itsName.
Referenced by TEST(), TEST(), TEST(), Beam::update(), BoundaryGeometry::update(), and OpalFilter::update().
setParent()
void Object::setParent (Object * parent) inherited
Set parent object.
Definition at line 283 of file Object.cpp.
References Object::itsParent.
Referenced by OpalData::erase().
setShared()
void Object::setShared (bool flag) virtual inherited
Set/reset shared flag.
Reimplemented in Element.
Definition at line 247 of file Object.cpp.
References Object::sharedFlag.
Referenced by OpalParser::parseDefine(), and Element::setShared().
shouldTrace()
bool ValueDefinition::shouldTrace () const virtual inherited
Trace flag.
Implements Object.
Definition at line 31 of file ValueDefinition.cpp.
shouldUpdate()
bool ValueDefinition::shouldUpdate () const virtual inherited
Update flag.
Implements Object.
Definition at line 33 of file ValueDefinition.cpp.
unregisterReference()
void Object::unregisterReference (Invalidator * a) inherited
Unegister a reference to this object.
Definition at line 167 of file Object.cpp.
References Object::references.
update()
void Object::update () virtual inherited
Update this object.
Reimplemented in Option, OpalCavity, OpalConstantEFieldCavity, OpalDrift, OpalElement, OpalMarker, OpalMonitor, OpalMultipole, OpalProbe, OpalQuadrupole, OpalRBend, OpalRingDefinition, OpalSBend, OpalSolenoid, OpalSource, OpalTravelingWave, OpalVacuum, OpalVerticalFFAMagnet, Sequence, Beam, BinningCmd, BoundaryGeometry, FieldSolverCmd, OpalFilter, OpalLaser, OpalMultipoleT, OpalPolynomialTimeDependence, OpalSinusoidalTimeDependence, OpalSplineTimeDependence, and OpalVariableRFCavity.
Definition at line 239 of file Object.cpp.
Referenced by Distribution::execute().
value() [1/2]
Attribute & ValueDefinition::value () inherited
Return the attribute representing the value of the definition.
Definition at line 71 of file ValueDefinition.cpp.
References Object::itsAttr.
Referenced by RealConstant(), RealVariable::RealVariable(), and StringConstant::StringConstant().
value() [2/2]
const Attribute & ValueDefinition::value () const inherited
Return the attribute representing the value of the definition.
Definition at line 73 of file ValueDefinition.cpp.
References Object::itsAttr.
Member Data Documentation
builtin
bool Object::builtin protected inherited
Built-in flag.
Definition at line 226 of file Object.h.
Referenced by Beam::Beam(), BoundaryGeometry::BoundaryGeometry(), Object::isBuiltin(), Object::Object(), Object::Object(), OpalFilter::OpalFilter(), OpalMarker::OpalMarker(), RealConstant(), StringConstant::StringConstant(), and Table::~Table().
flagged
bool Object::flagged protected inherited
Object flag.
Definition at line 235 of file Object.h.
Referenced by Object::isFlagged(), Object::Object(), Object::Object(), and Object::setFlag().
itsAttr
std::vector<Attribute> Object::itsAttr inherited
The object attributes.
Definition at line 210 of file Object.h.
Referenced by Beam::Beam(), BinningCmd::BinningCmd(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), BoundaryGeometry::BoundaryGeometry(), DumpEMFields::buildGrid(), Call::Call(), FieldSolverCmd::constructBCHandler(), Object::copyAttributes(), Distribution::Distribution(), BinningCmd::dumpBinsToFile(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), Call::execute(), Echo::execute(), Help::execute(), Option::execute(), PSystem::execute(), Select::execute(), System::execute(), Title::execute(), Value::execute(), Beam::execute(), TrackCmd::execute(), TrackRun::execute(), FieldSolverCmd::FieldSolverCmd(), Object::findAttribute(), Object::findAttribute(), BoundaryGeometry::getA(), OpalElement::getApert(), BoundaryGeometry::getB(), BinningCmd::getBinningAlpha(), BinningCmd::getBinningBeta(), FieldSolverCmd::getBinsName(), BoolConstant::getBool(), FieldSolverCmd::getBoxIncr(), Beam::getBunchCharge(), BoundaryGeometry::getC(), Beam::getCharge(), Beam::getCurrent(), Beam::getDaughterBeamName(), BinningCmd::getDesiredWidth(), EmissionSource::getDistributionName(), FieldSolverCmd::getDomDec(), TrackCmd::getDT(), TrackCmd::getDTAU(), TrackCmd::getDTSCINIT(), BinningCmd::getDumpBinsFileName(), BinningCmd::getDumpBinsFrequency(), EmissionSource::getEmissionModel(), Beam::getEmissionSourceListName(), Distribution::getFilename(), BoundaryGeometry::getFilename(), Beam::getFrequency(), Beam::getGlobalProcessNames(), BoundaryGeometry::getL1(), BoundaryGeometry::getL2(), BoundaryGeometry::getLength(), OpalElement::getLength(), Line::getLength(), Sequence::getLength(), Beam::getMass(), BinningCmd::getMaxBins(), TrackCmd::getMaxSteps(), Beam::getNumAlloc(), FieldSolverCmd::getNX(), FieldSolverCmd::getNY(), FieldSolverCmd::getNZ(), EmissionSource::getP0(), BinningCmd::getParameter(), Beam::getParticleName(), EmissionSource::getR0(), getReal(), RealVariable::getReal(), RealVector::getRealComponent(), Sequence::getReference(), BoundaryGeometry::getS(), EmissionSource::getShiftedGreensFunction(), TrackCmd::getStepsPerTurn(), StringConstant::getString(), EmissionSource::getT0(), TrackCmd::getT0(), BinningCmd::getTablePrintFrequency(), TrackCmd::getTimeIntegrator(), BoundaryGeometry::getTopology(), FieldSolverCmd::getType(), EmissionSource::getZerofaceMaxSteps(), EmissionSource::getZeroFacePlaneDumpFrequency(), EmissionSource::getZeroFaceR0Z(), TrackCmd::getZStart(), TrackCmd::getZStop(), Beam::hasExplicitEnergy(), Help::Help(), BoundaryGeometry::initialize(), OpalFilter::initOpalFilter(), Beam::isPhoton(), Line::Line(), OpalBend::OpalBend(), OpalCavity::OpalCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalDrift::OpalDrift(), OpalElement::OpalElement(), OpalFilter::OpalFilter(), OpalLaser::OpalLaser(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalPolynomialTimeDependence::OpalPolynomialTimeDependence(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalRingDefinition::OpalRingDefinition(), OpalSinusoidalTimeDependence::OpalSinusoidalTimeDependence(), OpalSolenoid::OpalSolenoid(), OpalSplineTimeDependence::OpalSplineTimeDependence(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), Option::Option(), Option::Option(), Sequence::parse(), Line::parse(), DumpEMFields::parseCoordinateSystem(), Object::print(), Sequence::print(), BoolConstant::print(), print(), RealVariable::print(), RealVector::print(), StringConstant::print(), Beam::print(), OpalFilter::print(), DumpEMFields::print(), Object::printHelp(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), BoolConstant::printValue(), printValue(), RealVariable::printValue(), RealVector::printValue(), StringConstant::printValue(), PSystem::PSystem(), RealConstant(), RealConstant(), RealVariable::RealVariable(), RealVariable::RealVariable(), RealVector::RealVector(), OpalElement::registerOwnership(), Object::registerOwnership(), Select::Select(), Select::select(), Sequence::Sequence(), Distribution::setAttributes(), TestMultipoleT::TestableFieldSolverCmd::setBCX(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCX(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCX(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCX(), TestVariableRFCavity::TestableFieldSolverCmd::setBCX(), OrbitThreaderTest::TestableFieldSolverCmd::setBCX(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCX(), TestMultipoleT::TestableFieldSolverCmd::setBCY(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCY(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCY(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCY(), TestVariableRFCavity::TestableFieldSolverCmd::setBCY(), OrbitThreaderTest::TestableFieldSolverCmd::setBCY(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCY(), TestMultipoleT::TestableFieldSolverCmd::setBCZ(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCZ(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCZ(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCZ(), TestVariableRFCavity::TestableFieldSolverCmd::setBCZ(), OrbitThreaderTest::TestableFieldSolverCmd::setBCZ(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCZ(), TestableBinningCmd::setBinningAlpha(), TestableBinningCmd::setBinningBeta(), TestableBinningCmd::setDesiredWidth(), Distribution::setDistParametersFlatTop(), Distribution::setDistParametersMultiVariateGauss(), Distribution::setDistType(), TestableBinningCmd::setDumpBinsFile(), TestableBinningCmd::setDumpBinsFreq(), TestableBinningCmd::setMaxBins(), FieldSolverCmd::setNX(), FieldSolverCmd::setNY(), FieldSolverCmd::setNZ(), TestableBinningCmd::setParameterString(), TrackRun::setRunMethod(), Distribution::setSigmaP_m(), Distribution::setSigmaR_m(), TestableBinningCmd::setTablePrintFrequency(), TestMultipoleT::TestableFieldSolverCmd::setType(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setType(), TestMultipoleTStraight::TestableFieldSolverCmd::setType(), SolenoidPlacementTest::TestableFieldSolverCmd::setType(), TestVariableRFCavity::TestableFieldSolverCmd::setType(), OrbitThreaderTest::TestableFieldSolverCmd::setType(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setType(), TrackRun::setupBoundaryGeometry(), StringConstant::StringConstant(), StringConstant::StringConstant(), System::System(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), OpalCavity::update(), OpalConstantEFieldCavity::update(), OpalDrift::update(), OpalElement::update(), OpalMonitor::update(), OpalMultipole::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalRBend::update(), OpalRingDefinition::update(), OpalSBend::update(), OpalSolenoid::update(), OpalTravelingWave::update(), OpalVacuum::update(), OpalVerticalFFAMagnet::update(), Beam::update(), BinningCmd::update(), FieldSolverCmd::update(), OpalLaser::update(), OpalMultipoleT::update(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), OpalSplineTimeDependence::update(), OpalVariableRFCavity::update(), Option::update(), OpalElement::updateUnknown(), ValueDefinition::value(), Value::Value(), and ValueDefinition::value().
itsHelp
std::string Object::itsHelp private inherited
Definition at line 250 of file Object.h.
Referenced by Object::printHelp().
itsName
std::string Object::itsName private inherited
Definition at line 247 of file Object.h.
Referenced by Object::getOpalName(), and Object::setOpalName().
itsParent
Object* Object::itsParent private inherited
Definition at line 244 of file Object.h.
Referenced by Object::getBaseObject(), Object::getParent(), Object::isTreeMember(), and Object::setParent().
itsPrefix
const std::string ValueDefinition::itsPrefix protected inherited
The declaration prefix.
Definition at line 90 of file ValueDefinition.h.
modified
bool Object::modified protected inherited
Dirty flag.
Definition at line 231 of file Object.h.
Referenced by Object::isDirty(), Object::Object(), Object::Object(), and Object::setDirty().
occurrence
int Object::occurrence private inherited
Definition at line 253 of file Object.h.
Referenced by Object::clear(), Object::increment(), and Object::occurrenceCount().
references
std::set<Invalidator*> Object::references private inherited
Definition at line 260 of file Object.h.
Referenced by Object::registerReference(), Object::unregisterReference(), and Object::~Object().
sharedFlag
bool Object::sharedFlag private inherited
Definition at line 263 of file Object.h.
Referenced by Object::isShared(), and Object::setShared().
timeStamp
double Object::timeStamp private inherited
Definition at line 256 of file Object.h.
The documentation for this class was generated from the following files:
RealConstant.h
RealConstant.cpp