OPALX (Object Oriented Parallel Accelerator Library for Exascal): SDDS::parser::SimpleParser Class Reference
SDDS::parser::SimpleParser Class Reference
#include <simple_parser.hpp>
Public Member Functions
SimpleParser (const std::string &input)
file parse ()
Private Member Functions
void skipWhitespace ()
bool match (const std::string &str)
bool match (char c)
void expect (const std::string &str)
void expect (char c)
std::string parseQuotedString ()
std::string parseIdentifier ()
std::string parseString ()
version parseVersion ()
description parseDescription ()
parameter parseParameter ()
column parseColumn ()
associate parseAssociate ()
array parseArray ()
include parseInclude ()
data parseData ()
Private Attributes
std::string input_
size_t pos_
Detailed Description
Definition at line 29 of file simple_parser.hpp.
Constructor & Destructor Documentation
SimpleParser()
SDDS::parser::SimpleParser::SimpleParser (const std::string & input) inline
Definition at line 31 of file simple_parser.hpp.
References input_, and pos_.
Member Function Documentation
expect() [1/2]
void SDDS::parser::SimpleParser::expect (char c) inline private
Definition at line 115 of file simple_parser.hpp.
References match().
expect() [2/2]
void SDDS::parser::SimpleParser::expect (const std::string & str) inline private
Definition at line 109 of file simple_parser.hpp.
References match().
Referenced by parseArray(), parseAssociate(), parseColumn(), parseData(), parseDescription(), parseInclude(), parseParameter(), and parseVersion().
match() [1/2]
bool SDDS::parser::SimpleParser::match (char c) inline private
Definition at line 100 of file simple_parser.hpp.
References input_, pos_, and skipWhitespace().
match() [2/2]
bool SDDS::parser::SimpleParser::match (const std::string & str) inline private
Definition at line 91 of file simple_parser.hpp.
References input_, pos_, and skipWhitespace().
Referenced by expect(), expect(), parse(), parseArray(), parseAssociate(), parseColumn(), parseData(), parseDescription(), parseInclude(), and parseParameter().
parse()
file SDDS::parser::SimpleParser::parse () inline
Definition at line 33 of file simple_parser.hpp.
References input_, match(), parseArray(), parseAssociate(), parseColumn(), parseData(), parseDescription(), parseInclude(), parseParameter(), parseVersion(), pos_, SDDS::file::sddsArrays_m, SDDS::file::sddsAssociates_m, SDDS::file::sddsColumns_m, SDDS::file::sddsData_m, SDDS::file::sddsDescription_m, SDDS::file::sddsIncludes_m, SDDS::file::sddsParameters_m, SDDS::file::sddsVersion_m, and skipWhitespace().
parseArray()
array SDDS::parser::SimpleParser::parseArray () inline private
Definition at line 320 of file simple_parser.hpp.
References expect(), input_, match(), parseString(), pos_, and skipWhitespace().
Referenced by parse().
parseAssociate()
associate SDDS::parser::SimpleParser::parseAssociate () inline private
Definition at line 306 of file simple_parser.hpp.
References expect(), input_, match(), parseString(), pos_, and skipWhitespace().
Referenced by parse().
parseColumn()
column SDDS::parser::SimpleParser::parseColumn () inline private
Definition at line 257 of file simple_parser.hpp.
References SDDS::ast::CHARACTER, SDDS::column::description_m, SDDS::ast::DOUBLE, expect(), SDDS::ast::FLOAT, input_, SDDS::ast::LONG, match(), SDDS::column::name_m, parseString(), pos_, SDDS::ast::SHORT, skipWhitespace(), SDDS::ast::STRING, SDDS::column::type_m, and SDDS::column::units_m.
Referenced by parse().
parseData()
data SDDS::parser::SimpleParser::parseData () inline private
Definition at line 348 of file simple_parser.hpp.
References SDDS::ast::ASCII, SDDS::ast::BINARY, expect(), match(), SDDS::data::mode_m, parseString(), and skipWhitespace().
Referenced by parse().
parseDescription()
description SDDS::parser::SimpleParser::parseDescription () inline private
Definition at line 184 of file simple_parser.hpp.
References SDDS::description::content_m, expect(), input_, match(), parseString(), pos_, skipWhitespace(), and SDDS::description::text_m.
Referenced by parse().
parseIdentifier()
std::string SDDS::parser::SimpleParser::parseIdentifier () inline private
Definition at line 142 of file simple_parser.hpp.
References input_, pos_, and skipWhitespace().
Referenced by parseString().
parseInclude()
include SDDS::parser::SimpleParser::parseInclude () inline private
Definition at line 334 of file simple_parser.hpp.
References expect(), input_, match(), parseString(), pos_, and skipWhitespace().
Referenced by parse().
parseParameter()
parameter SDDS::parser::SimpleParser::parseParameter () inline private
Definition at line 208 of file simple_parser.hpp.
References SDDS::ast::CHARACTER, SDDS::parameter::description_m, SDDS::ast::DOUBLE, expect(), SDDS::ast::FLOAT, input_, SDDS::ast::LONG, match(), SDDS::parameter::name_m, parseString(), pos_, SDDS::ast::SHORT, skipWhitespace(), SDDS::ast::STRING, SDDS::parameter::type_m, and SDDS::parameter::units_m.
Referenced by parse().
parseQuotedString()
std::string SDDS::parser::SimpleParser::parseQuotedString () inline private
Definition at line 121 of file simple_parser.hpp.
References input_, and pos_.
Referenced by parseString().
parseString()
std::string SDDS::parser::SimpleParser::parseString () inline private
Definition at line 159 of file simple_parser.hpp.
References input_, parseIdentifier(), parseQuotedString(), pos_, and skipWhitespace().
Referenced by parseArray(), parseAssociate(), parseColumn(), parseData(), parseDescription(), parseInclude(), and parseParameter().
parseVersion()
version SDDS::parser::SimpleParser::parseVersion () inline private
Definition at line 167 of file simple_parser.hpp.
References expect(), input_, SDDS::version::layoutVersion_m, pos_, and skipWhitespace().
Referenced by parse().
skipWhitespace()
void SDDS::parser::SimpleParser::skipWhitespace () inline private
Definition at line 76 of file simple_parser.hpp.
References input_, and pos_.
Referenced by match(), match(), parse(), parseArray(), parseAssociate(), parseColumn(), parseData(), parseDescription(), parseIdentifier(), parseInclude(), parseParameter(), parseString(), and parseVersion().
Member Data Documentation
input_
std::string SDDS::parser::SimpleParser::input_ private
Definition at line 73 of file simple_parser.hpp.
Referenced by match(), match(), parse(), parseArray(), parseAssociate(), parseColumn(), parseDescription(), parseIdentifier(), parseInclude(), parseParameter(), parseQuotedString(), parseString(), parseVersion(), SimpleParser(), and skipWhitespace().
pos_
size_t SDDS::parser::SimpleParser::pos_ private
Definition at line 74 of file simple_parser.hpp.
Referenced by match(), match(), parse(), parseArray(), parseAssociate(), parseColumn(), parseDescription(), parseIdentifier(), parseInclude(), parseParameter(), parseQuotedString(), parseString(), parseVersion(), SimpleParser(), and skipWhitespace().
The documentation for this class was generated from the following file:
simple_parser.hpp