OPALX (Object Oriented Parallel Accelerator Library for Exascal): Selector Class Reference
Selector Class Reference
#include <Selector.h>
Public Member Functions
Selector (const Beamline &, const RangeRep &range, const std::string &cName, const std::string &tName, const std::string &pString)
Constructor.
virtual ~Selector ()
virtual void execute ()
Execute the selection.
int getCount () const
Return the count of selected elements.
virtual void visitFlaggedElmPtr (const FlaggedElmPtr &)
Apply the visitor to an FlaggedElmPtr.
void visitComponent (const Component &) override
Apply the algorithm to an arbitrary component.
void visitBeamline (const Beamline &) override
Apply the algorithm to a beam line.
void visitConstantEFieldCavity (const ConstantEFieldCavity &) override
Apply the algorithm to a constant E-field cavity element.
void visitDrift (const Drift &) override
Apply the algorithm to a drift space.
void visitLaser (const Laser &) override
Apply the algorithm to a laser.
void visitMarker (const Marker &) override
Apply the algorithm to a marker.
void visitMonitor (const Monitor &) override
Apply the algorithm to a beam position monitor.
void visitMultipole (const Multipole &) override
Apply the algorithm to a multipole.
void visitMultipoleT (const MultipoleT &) override
Apply the algorithm to an arbitrary multipole.
void visitRBend (const RBend &) override
Apply the algorithm to a rectangular bend.
void visitRing (const Ring &) override
Apply the algorithm to a Ring.
void visitSBend (const SBend &) override
Apply the algorithm to a sector bend.
void visitRFCavity (const RFCavity &) override
Apply the algorithm to a RF cavity.
void visitSolenoid (const Solenoid &) override
Apply the algorithm to a Solenoid.
void visitTravelingWave (const TravelingWave &) override
Apply the algorithm to a traveling wave.
void visitScalingFFAMagnet (const ScalingFFAMagnet &spiral) override
Apply the algorithm to a scaling FFA magnet.
void visitVerticalFFAMagnet (const VerticalFFAMagnet &) override
Apply the algorithm to a vertical FFA magnet.
void visitVariableRFCavity (const VariableRFCavity &) override
Apply the algorithm to a variable RF cavity.
void visitProbe (const Probe &prob) override
Apply the algorithm to a Probe.
Protected Member Functions
virtual void handleElement (const FlaggedElmPtr &)
The operation to be done for elements.
virtual void handleBeamline (const FlaggedElmPtr &)
The operation to be done for beamlines.
Protected Attributes
RangeRep itsRange
Working data for range.
const Beamline & itsLine
bool back_beam
bool back_track
bool back_path
double flip_B
double flip_s
Private Member Functions
Selector ()
Selector (const Selector &)
void operator= (const Selector &)
virtual void applyDefault (const ElementBase &)
Private Attributes
const Element * itsClass
const std::string itsType
const RegularExpression * itsPattern
int itsCount
bool local_flip
Detailed Description
Definition at line 28 of file Selector.h.
Constructor & Destructor Documentation
Selector() [1/3]
Selector::Selector (const Beamline & bl, const RangeRep & range, const std::string & cName, const std::string & tName, const std::string & pString)
Constructor.
Definition at line 29 of file Selector.cpp.
References Element::find(), itsClass, itsPattern, and Options::warn.
~Selector()
Selector::~Selector () virtual
Definition at line 46 of file Selector.cpp.
References itsPattern.
Selector() [2/3]
Selector::Selector () private
Selector() [3/3]
Selector::Selector (const Selector &) private
Member Function Documentation
applyDefault()
void DefaultVisitor::applyDefault (const ElementBase &) private virtual inherited
Definition at line 113 of file DefaultVisitor.cpp.
Referenced by DefaultVisitor::visitComponent(), DefaultVisitor::visitConstantEFieldCavity(), DefaultVisitor::visitDrift(), DefaultVisitor::visitLaser(), DefaultVisitor::visitMarker(), DefaultVisitor::visitMonitor(), DefaultVisitor::visitMultipole(), DefaultVisitor::visitMultipoleT(), DefaultVisitor::visitProbe(), DefaultVisitor::visitRBend(), DefaultVisitor::visitRFCavity(), DefaultVisitor::visitRing(), DefaultVisitor::visitSBend(), DefaultVisitor::visitScalingFFAMagnet(), DefaultVisitor::visitSolenoid(), DefaultVisitor::visitTravelingWave(), DefaultVisitor::visitVariableRFCavity(), and DefaultVisitor::visitVerticalFFAMagnet().
execute()
void Selector::execute () virtual
Execute the selection.
Reimplemented from RangeSelector.
Definition at line 48 of file Selector.cpp.
References RangeSelector::execute(), and itsCount.
Referenced by Select::select().
getCount()
int Selector::getCount () const
Return the count of selected elements.
Definition at line 79 of file Selector.cpp.
References itsCount.
Referenced by Select::select().
handleBeamline()
void RangeSelector::handleBeamline (const FlaggedElmPtr & fep) protected virtual inherited
The operation to be done for beamlines.
Definition at line 57 of file RangeSelector.cpp.
References DefaultVisitor::visitFlaggedElmPtr().
Referenced by RangeSelector::visitFlaggedElmPtr().
handleElement()
void Selector::handleElement (const FlaggedElmPtr & fep) protected virtual
The operation to be done for elements.
Reimplemented from RangeSelector.
Definition at line 53 of file Selector.cpp.
References Element::find(), ElmPtr::getElement(), ElementBase::getName(), OpalElement::getTypeName(), RangeRep::isActive(), Object::isTreeMember(), itsClass, itsCount, itsPattern, RangeSelector::itsRange, itsType, RegularExpression::match(), and FlaggedElmPtr::setSelectionFlag().
operator=()
void Selector::operator= (const Selector &) private
visitBeamline()
void DefaultVisitor::visitBeamline (const Beamline & bl) override virtual inherited
Apply the algorithm to a beam line.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 97 of file DefaultVisitor.cpp.
References Beamline::iterate(), and DefaultVisitor::local_flip.
visitComponent()
void DefaultVisitor::visitComponent (const Component &) override virtual inherited
Apply the algorithm to an arbitrary component.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker, and Tracker.
Definition at line 59 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitConstantEFieldCavity()
void DefaultVisitor::visitConstantEFieldCavity (const ConstantEFieldCavity & cav) override virtual inherited
Apply the algorithm to a constant E-field cavity element.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 61 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitDrift()
void DefaultVisitor::visitDrift (const Drift & drf) override virtual inherited
Apply the algorithm to a drift space.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 65 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitFlaggedElmPtr()
void RangeSelector::visitFlaggedElmPtr (const FlaggedElmPtr & fep) virtual inherited
Apply the visitor to an FlaggedElmPtr.
Reimplemented from DefaultVisitor.
Definition at line 40 of file RangeSelector.cpp.
References RangeRep::enter(), ElmPtr::getElement(), RangeSelector::handleBeamline(), RangeSelector::handleElement(), RangeSelector::itsRange, and RangeRep::leave().
visitLaser()
void DefaultVisitor::visitLaser (const Laser & laser) override virtual inherited
Apply the algorithm to a laser.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 67 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitMarker()
void DefaultVisitor::visitMarker (const Marker & mark) override virtual inherited
Apply the algorithm to a marker.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 69 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitMonitor()
void DefaultVisitor::visitMonitor (const Monitor & mon) override virtual inherited
Apply the algorithm to a beam position monitor.
Implements BeamlineVisitor.
Definition at line 71 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitMultipole()
void DefaultVisitor::visitMultipole (const Multipole & mult) override virtual inherited
Apply the algorithm to a multipole.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 73 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitMultipoleT()
void DefaultVisitor::visitMultipoleT (const MultipoleT & multT) override virtual inherited
Apply the algorithm to an arbitrary multipole.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 75 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitProbe()
void DefaultVisitor::visitProbe (const Probe & prob) override virtual inherited
Apply the algorithm to a Probe.
Implements BeamlineVisitor.
Definition at line 95 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitRBend()
void DefaultVisitor::visitRBend (const RBend & bend) override virtual inherited
Apply the algorithm to a rectangular bend.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 77 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitRFCavity()
void DefaultVisitor::visitRFCavity (const RFCavity & cav) override virtual inherited
Apply the algorithm to a RF cavity.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 81 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitRing()
void DefaultVisitor::visitRing (const Ring & ring) override virtual inherited
Apply the algorithm to a Ring.
Implements BeamlineVisitor.
Definition at line 79 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitSBend()
void DefaultVisitor::visitSBend (const SBend & bend) override virtual inherited
Apply the algorithm to a sector bend.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 83 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitScalingFFAMagnet()
void DefaultVisitor::visitScalingFFAMagnet (const ScalingFFAMagnet & spiral) override virtual inherited
Apply the algorithm to a scaling FFA magnet.
Implements BeamlineVisitor.
Definition at line 89 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitSolenoid()
void DefaultVisitor::visitSolenoid (const Solenoid & so) override virtual inherited
Apply the algorithm to a Solenoid.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 85 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitTravelingWave()
void DefaultVisitor::visitTravelingWave (const TravelingWave & trw) override virtual inherited
Apply the algorithm to a traveling wave.
Implements BeamlineVisitor.
Reimplemented in ParallelTracker.
Definition at line 87 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitVariableRFCavity()
void DefaultVisitor::visitVariableRFCavity (const VariableRFCavity & cavity) override virtual inherited
Apply the algorithm to a variable RF cavity.
Implements BeamlineVisitor.
Definition at line 93 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
visitVerticalFFAMagnet()
void DefaultVisitor::visitVerticalFFAMagnet (const VerticalFFAMagnet & mag) override virtual inherited
Apply the algorithm to a vertical FFA magnet.
Implements BeamlineVisitor.
Definition at line 91 of file DefaultVisitor.cpp.
References DefaultVisitor::applyDefault().
Member Data Documentation
back_beam
bool DefaultVisitor::back_beam protected inherited
Definition at line 110 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor(), DefaultVisitor::execute(), and Tracker::visitComponent().
back_path
bool DefaultVisitor::back_path protected inherited
Definition at line 112 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor().
back_track
bool DefaultVisitor::back_track protected inherited
Definition at line 111 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor(), DefaultVisitor::execute(), and Tracker::visitComponent().
flip_B
double DefaultVisitor::flip_B protected inherited
Definition at line 115 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor().
flip_s
double DefaultVisitor::flip_s protected inherited
Definition at line 116 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor().
itsClass
const Element* Selector::itsClass private
Definition at line 57 of file Selector.h.
Referenced by handleElement(), and Selector().
itsCount
int Selector::itsCount private
Definition at line 66 of file Selector.h.
Referenced by execute(), getCount(), and handleElement().
itsLine
const Beamline& DefaultVisitor::itsLine protected inherited
Definition at line 107 of file DefaultVisitor.h.
Referenced by DefaultVisitor::execute().
itsPattern
const RegularExpression* Selector::itsPattern private
Definition at line 63 of file Selector.h.
Referenced by handleElement(), Selector(), and ~Selector().
itsRange
RangeRep RangeSelector::itsRange protected inherited
Working data for range.
Definition at line 51 of file RangeSelector.h.
Referenced by RangeSelector::execute(), RangeSelector::handleElement(), handleElement(), and RangeSelector::visitFlaggedElmPtr().
itsType
const std::string Selector::itsType private
Definition at line 60 of file Selector.h.
Referenced by handleElement().
local_flip
bool DefaultVisitor::local_flip private inherited
Definition at line 130 of file DefaultVisitor.h.
Referenced by DefaultVisitor::DefaultVisitor(), DefaultVisitor::execute(), DefaultVisitor::visitBeamline(), and DefaultVisitor::visitFlaggedElmPtr().
The documentation for this class was generated from the following files:
Selector.h
Selector.cpp