OPALX (Object Oriented Parallel Accelerator Library for Exascal): WhileStatement Class Reference
WhileStatement Class Reference
While statement.
#include <WhileStatement.h>
Public Types
typedef std::list< Token > TokenList
The type of the enclosed token list.
Public Member Functions
WhileStatement (const Parser &, TokenStream &)
Constructor.
virtual ~WhileStatement ()
virtual void execute (const Parser &)
Execute.
void append (const Token &)
Append a token.
bool atEnd () const
Test for end of command.
bool boolean (bool &value)
Return boolean value.
bool delimiter (char c)
Test for delimiter.
bool delimiter (const char *s)
Test for delimiter choice.
Token & getCurrent ()
Return current token and skip it.
bool integer (int &value)
Return signed integer.
bool integer (unsigned &value)
Return unsigned integer.
bool keyword (const char *s)
Test for keyword.
bool real (double &value)
Return real value.
bool str (std::string &value)
Return string value.
std::string str () const
bool word (std::string &value)
Return word value.
void mark ()
Mark position in command.
void restore ()
Return to marked position.
void start ()
Return to start.
void skip ()
Skip.
unsigned int position () const
Return current character number in line.
virtual void print (std::ostream &os) const
Print statement.
virtual void printWhere (Inform &msg, bool withToken) const
Print position.
Protected Attributes
int stat_line
std::string buffer_name
TokenList tokens
TokenList::iterator curr
TokenList::iterator keep
Private Member Functions
WhileStatement ()
WhileStatement (const WhileStatement &)
void operator= (const WhileStatement &)
Private Attributes
Statement * while_block
Detailed Description
While statement.
Definition at line 34 of file WhileStatement.h.
Member Typedef Documentation
TokenList
typedef std::list<Token> Statement::TokenList inherited
The type of the enclosed token list.
Definition at line 40 of file Statement.h.
Constructor & Destructor Documentation
WhileStatement() [1/3]
WhileStatement::WhileStatement (const Parser & parser, TokenStream & is)
Constructor.
Definition at line 36 of file WhileStatement.cpp.
References Token::isDel(), Token::isKey(), Parser::readStatement(), TokenStream::readToken(), Statement::Statement(), and while_block.
Referenced by operator=(), and WhileStatement().
~WhileStatement()
WhileStatement::~WhileStatement () virtual
Definition at line 65 of file WhileStatement.cpp.
References while_block.
WhileStatement() [2/3]
WhileStatement::WhileStatement () private
WhileStatement() [3/3]
WhileStatement::WhileStatement (const WhileStatement &) private
References WhileStatement().
Member Function Documentation
append()
void Statement::append (const Token & token) inherited
Append a token.
Definition at line 39 of file Statement.cpp.
References tokens.
Referenced by LineTemplate::makeInstance(), OpalParser::parseBracketList(), OpalParser::parseTokenList(), and OpalParser::readStatement().
atEnd()
bool Statement::atEnd () const inherited
Test for end of command.
Definition at line 41 of file Statement.cpp.
References curr, and tokens.
Referenced by MacroCmd::makeTemplate(), OpalParser::parse(), Expressions::parseBracketList(), OpalParser::parseEnd(), LineTemplate::parseTemplate(), Expressions::parseTokenList(), and skip().
boolean()
bool Statement::boolean (bool & value) inherited
Return boolean value.
Definition at line 43 of file Statement.cpp.
References curr, tokens, and word().
Referenced by Expressions::parseRelation().
delimiter() [1/2]
bool Statement::delimiter (char c) inherited
Test for delimiter.
Definition at line 83 of file Statement.cpp.
References curr, and tokens.
Referenced by MacroCmd::makeTemplate(), Line::parse(), Object::parse(), OpalElement::parse(), OpalParser::parse(), OpalParser::parseAction(), Macro::parseActuals(), Expressions::parseAnd(), Expressions::parseArrayFactor(), Expressions::parseArrayPrimary(), Expressions::parseArrayTerm(), OpalParser::parseAssign(), Expressions::parseBool(), Expressions::parseBoolArray(), Expressions::parseBracketList(), Expressions::parseColumnGenerator(), OpalParser::parseDefine(), Expressions::parseDelimiter(), Expressions::parseDelimiter(), OpalParser::parseEnd(), Expressions::parseFactor(), Macro::parseFormals(), EmissionSourceList::parseList(), Line::parseList(), OpalParser::parseMacro(), SequenceParser::parseMember(), Expressions::parsePlace(), SequenceParser::parsePosition(), Expressions::parsePrimary(), Expressions::parseRange(), Expressions::parseReal(), Expressions::parseRealArray(), Expressions::parseReference(), Expressions::parseRelation(), Expressions::parseRowGenerator(), Expressions::parseString(), Expressions::parseStringArray(), Expressions::parseStringValue(), Expressions::parseTableGenerator(), Expressions::parseTerm(), Expressions::parseTokenListArray(), and TrackRun::print().
delimiter() [2/2]
bool Statement::delimiter (const char * s) inherited
Test for delimiter choice.
Definition at line 92 of file Statement.cpp.
References curr, and tokens.
execute()
void WhileStatement::execute (const Parser & parser) virtual
Execute.
Implements Statement.
Definition at line 68 of file WhileStatement.cpp.
References Statement::curr, Attributes::getBool(), OpalData::getInstance(), Statement::keep, Attributes::makeBool(), Attribute::parse(), Statement::print(), Statement::tokens, OpalData::update(), and while_block.
getCurrent()
Token & Statement::getCurrent () inherited
Return current token and skip it.
Definition at line 61 of file Statement.cpp.
References curr.
Referenced by MacroCmd::makeTemplate(), OpalParser::parse(), Macro::parseActuals(), Expressions::parseBracketList(), OpalParser::parseMacro(), LineTemplate::parseTemplate(), and Expressions::parseTokenList().
integer() [1/2]
bool Statement::integer (int & value) inherited
Return signed integer.
Definition at line 63 of file Statement.cpp.
References curr, and tokens.
Referenced by Line::parseList().
integer() [2/2]
bool Statement::integer (unsigned & value) inherited
Return unsigned integer.
Definition at line 73 of file Statement.cpp.
References curr, and tokens.
keyword()
bool Statement::keyword (const char * s) inherited
Test for keyword.
Definition at line 101 of file Statement.cpp.
References curr, and tokens.
Referenced by MacroCmd::makeTemplate(), OpalParser::parse(), SequenceParser::parse(), Expressions::parseArrayPrimary(), OpalParser::parseAssign(), OpalParser::parseDefine(), Expressions::parsePlace(), SequenceParser::parsePosition(), Expressions::parseRange(), LineTemplate::parseTemplate(), and SequenceTemplate::parseTemplate().
mark()
void Statement::mark () inherited
Mark position in command.
Definition at line 146 of file Statement.cpp.
References curr, and keep.
Referenced by OpalParser::parse(), OpalParser::parseMacro(), Expressions::parseRelation(), Expressions::parseTokenList(), and TrackRun::print().
operator=()
void WhileStatement::operator= (const WhileStatement &) private
References WhileStatement().
position()
unsigned int Statement::position () const inherited
Return current character number in line.
Definition at line 157 of file Statement.cpp.
References curr, and tokens.
Referenced by OpalParser::parse(), and OpalParser::parseEnd().
print()
void Statement::print (std::ostream & os) const virtual inherited
Print statement.
Definition at line 171 of file Statement.cpp.
References tokens.
Referenced by IfStatement::execute(), WhileStatement::execute(), operator<<(), operator<<(), OpalParser::parse(), OpalParser::parseEnd(), and str().
printWhere()
void Statement::printWhere (Inform & msg, bool withToken) const virtual inherited
Print position.
Definition at line 183 of file Statement.cpp.
References buffer_name, curr, stat_line, and tokens.
real()
bool Statement::real (double & value) inherited
Return real value.
Definition at line 110 of file Statement.cpp.
References curr, and tokens.
Referenced by Expressions::parseArrayPrimary(), and Expressions::parsePrimary().
restore()
void Statement::restore () inherited
Return to marked position.
Definition at line 148 of file Statement.cpp.
References curr, and keep.
Referenced by OpalParser::parse(), OpalParser::parseMacro(), Expressions::parseRelation(), and Expressions::parseTokenList().
skip()
void Statement::skip () inherited
Skip.
Definition at line 152 of file Statement.cpp.
References atEnd(), and curr.
start()
void Statement::start () inherited
Return to start.
Definition at line 150 of file Statement.cpp.
References curr, and tokens.
Referenced by IfStatement::execute(), LineTemplate::makeInstance(), OpalParser::parse(), SequenceParser::parse(), OpalParser::parseAction(), OpalParser::parseAssign(), OpalParser::parseDefine(), and OpalParser::readStatement().
str() [1/2]
std::string Statement::str () const inherited
Definition at line 197 of file Statement.cpp.
References print(), and str().
str() [2/2]
bool Statement::str (std::string & value) inherited
Return string value.
Definition at line 126 of file Statement.cpp.
References curr, and tokens.
Referenced by Expressions::parseString(), Expressions::parseStringValue(), and str().
word()
bool Statement::word (std::string & value) inherited
Return word value.
Definition at line 136 of file Statement.cpp.
References curr, and tokens.
Referenced by boolean(), Expressions::parseRelation(), Expressions::parseString(), Expressions::parseStringValue(), and TrackRun::print().
Member Data Documentation
buffer_name
std::string Statement::buffer_name protected inherited
Definition at line 173 of file Statement.h.
Referenced by CompoundStatement::CompoundStatement(), printWhere(), Statement(), and Statement().
curr
TokenList::iterator Statement::curr protected inherited
Definition at line 177 of file Statement.h.
Referenced by atEnd(), boolean(), delimiter(), delimiter(), SimpleStatement::execute(), WhileStatement::execute(), getCurrent(), integer(), integer(), keyword(), mark(), position(), printWhere(), real(), restore(), skip(), start(), Statement(), str(), and word().
keep
TokenList::iterator Statement::keep protected inherited
Definition at line 178 of file Statement.h.
Referenced by SimpleStatement::execute(), WhileStatement::execute(), mark(), and restore().
stat_line
int Statement::stat_line protected inherited
Definition at line 170 of file Statement.h.
Referenced by CompoundStatement::CompoundStatement(), printWhere(), Statement(), and Statement().
tokens
TokenList Statement::tokens protected inherited
Definition at line 176 of file Statement.h.
Referenced by append(), atEnd(), boolean(), delimiter(), delimiter(), SimpleStatement::execute(), WhileStatement::execute(), integer(), integer(), keyword(), position(), print(), printWhere(), real(), start(), Statement(), Statement(), str(), word(), and ~Statement().
while_block
Statement* WhileStatement::while_block private
Definition at line 52 of file WhileStatement.h.
Referenced by execute(), WhileStatement(), and ~WhileStatement().
The documentation for this class was generated from the following files:
WhileStatement.h
WhileStatement.cpp