OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions::ADeferred< T > Class Template Reference
Expressions::ADeferred< T > Class Template Reference
Object attribute with a `‘deferred’' array value.
#include <ADeferred.h>
Public Member Functions
ADeferred ()
Default constructor.
ADeferred (PtrToArray< T > expr)
Constructor.
ADeferred (const std::vector< T > &val)
Constructor.
ADeferred (ArrayOfPtrs< T > expr)
Constructor.
ADeferred (const ADeferred< T > &)
virtual ~ADeferred ()
virtual ADeferred< T > * clone () const
Make clone.
virtual std::vector< T > evaluate ()
Evaluate.
virtual bool isExpression () const
Get expression flag.
virtual void print (std::ostream &) const
Print the attribute value.
void setComponent (int i, const PtrToScalar< T > expr)
Set a component of the value.
std::string getImage () const
Convert to string.
virtual void invalidate ()
Force re-evaluation.
Protected Attributes
PtrToArray< T > itsLaw
The generating law for the array expression.
ArrayOfPtrs< T > itsOverrides
Overrides for single components.
std::vector< T > value
The value of the attribute.
Private Member Functions
void operator= (const ADeferred< T > &)
Private Attributes
bool in_evaluation
Detailed Description
template<class T>
class Expressions::ADeferred< T >
Object attribute with a `‘deferred’' array value.
Definition at line 40 of file ADeferred.h.
Constructor & Destructor Documentation
ADeferred() [1/5]
template<class T> Expressions::ADeferred< T >::ADeferred ()
Default constructor.
Definition at line 102 of file ADeferred.h.
References Expressions::AValue< T >::AValue(), in_evaluation, itsLaw, and itsOverrides.
Referenced by Expressions::AAutomatic< T >::AAutomatic(), Expressions::AAutomatic< T >::AAutomatic(), ADeferred(), clone(), and operator=().
ADeferred() [2/5]
template<class T> Expressions::ADeferred< T >::ADeferred (PtrToArray< T > expr) explicit
Constructor.
Definition at line 120 of file ADeferred.h.
References Expressions::AValue< T >::AValue(), in_evaluation, itsLaw, and itsOverrides.
ADeferred() [3/5]
template<class T> Expressions::ADeferred< T >::ADeferred (const std::vector< T > & val) explicit
Constructor.
Definition at line 116 of file ADeferred.h.
References Expressions::AValue< T >::AValue(), in_evaluation, itsLaw, and itsOverrides.
ADeferred() [4/5]
template<class T> Expressions::ADeferred< T >::ADeferred (ArrayOfPtrs< T > expr) explicit
Constructor.
Definition at line 124 of file ADeferred.h.
References Expressions::AValue< T >::AValue(), in_evaluation, itsLaw, and itsOverrides.
ADeferred() [5/5]
template<class T> Expressions::ADeferred< T >::ADeferred (const ADeferred< T > & rhs)
Definition at line 105 of file ADeferred.h.
References ADeferred(), Expressions::AValue< T >::AValue(), clone(), in_evaluation, itsLaw, and itsOverrides.
~ADeferred()
template<class T> Expressions::ADeferred< T >::~ADeferred () virtual
Definition at line 128 of file ADeferred.h.
Member Function Documentation
clone()
template<class T> ADeferred< T > * Expressions::ADeferred< T >::clone () const virtual
Make clone.
Reimplemented from Expressions::AValue< T >.
Reimplemented in Expressions::AAutomatic< T >.
Definition at line 131 of file ADeferred.h.
References ADeferred().
Referenced by ADeferred().
evaluate()
template<class T> std::vector< T > Expressions::ADeferred< T >::evaluate () virtual
Evaluate.
Reimplemented from Expressions::AValue< T >.
Reimplemented in Expressions::AAutomatic< T >.
Definition at line 136 of file ADeferred.h.
References AttributeBase::getImage(), in_evaluation, itsLaw, itsOverrides, Expressions::AValue< T >::value, OpalException::what(), and OpalException::where().
Referenced by Expressions::AAutomatic< T >::evaluate().
getImage()
std::string AttributeBase::getImage () const inherited
Convert to string.
Definition at line 29 of file AttributeBase.cpp.
References print().
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), and Expressions::SRefAttr< T >::evaluate().
invalidate()
void Invalidator::invalidate () virtual inherited
Force re-evaluation.
Reimplemented in Expressions::AAutomatic< T >, Expressions::SAutomatic< T >, Expressions::SRefAttr< T >, and Expressions::SRefExpr< T >.
Definition at line 25 of file Invalidator.cpp.
isExpression()
template<class T> bool Expressions::ADeferred< T >::isExpression () const virtual
Get expression flag.
Reimplemented from AttributeBase.
Definition at line 176 of file ADeferred.h.
References itsLaw, and itsOverrides.
operator=()
template<class T> void Expressions::ADeferred< T >::operator= (const ADeferred< T > &) private
References ADeferred().
print()
template<class T> void Expressions::ADeferred< T >::print (std::ostream & os) const virtual
Print the attribute value.
Reimplemented from Expressions::AValue< T >.
Definition at line 181 of file ADeferred.h.
References itsLaw, and itsOverrides.
setComponent()
template<class T> void Expressions::ADeferred< T >::setComponent (int i, const PtrToScalar< T > expr)
Set a component of the value.
Definition at line 203 of file ADeferred.h.
References itsOverrides.
Referenced by Attributes::BoolArray::parseComponent(), and Attributes::RealArray::parseComponent().
Member Data Documentation
in_evaluation
template<class T> bool Expressions::ADeferred< T >::in_evaluation mutable private
Definition at line 95 of file ADeferred.h.
Referenced by ADeferred(), ADeferred(), ADeferred(), ADeferred(), ADeferred(), and evaluate().
itsLaw
template<class T> PtrToArray<T> Expressions::ADeferred< T >::itsLaw protected
The generating law for the array expression.
Definition at line 82 of file ADeferred.h.
Referenced by ADeferred(), ADeferred(), ADeferred(), ADeferred(), ADeferred(), evaluate(), isExpression(), and print().
itsOverrides
template<class T> ArrayOfPtrs<T> Expressions::ADeferred< T >::itsOverrides protected
Overrides for single components.
Definition at line 88 of file ADeferred.h.
Referenced by ADeferred(), ADeferred(), ADeferred(), ADeferred(), ADeferred(), evaluate(), isExpression(), print(), and setComponent().
value
template<class T> std::vector<T> Expressions::AValue< T >::value mutable protected inherited
The value of the attribute.
Definition at line 60 of file AValue.h.
Referenced by AValue(), AValue(), clone(), Expressions::AAutomatic< T >::evaluate(), Expressions::ADeferred< T >::evaluate(), evaluate(), and print().
The documentation for this class was generated from the following file:
ADeferred.h