OPALX (Object Oriented Parallel Accelerator Library for Exascal): ElmPtr Class Reference
ElmPtr Class Reference
A section of a beam line.
#include <ElmPtr.h>
Public Member Functions
ElmPtr ()
ElmPtr (const ElmPtr &)
ElmPtr (ElementBase *elem)
ElmPtr (std::shared_ptr< ElementBase > elem)
virtual ~ElmPtr ()
virtual void accept (BeamlineVisitor &) const
Apply visitor.
ElementBase * getElement () const
Get the element pointer.
void setElement (ElementBase *)
Set the element pointer.
void setElement (std::shared_ptr< ElementBase > elem)
Protected Attributes
std::shared_ptr< ElementBase > itsElement
Detailed Description
A section of a beam line.
Definition at line 33 of file ElmPtr.h.
Constructor & Destructor Documentation
ElmPtr() [1/4]
ElmPtr::ElmPtr ()
Definition at line 26 of file ElmPtr.cpp.
ElmPtr() [2/4]
ElmPtr::ElmPtr (const ElmPtr & rhs)
Definition at line 31 of file ElmPtr.cpp.
ElmPtr() [3/4]
ElmPtr::ElmPtr (ElementBase * elem)
Definition at line 36 of file ElmPtr.cpp.
ElmPtr() [4/4]
ElmPtr::ElmPtr (std::shared_ptr< ElementBase > elem) explicit
Definition at line 41 of file ElmPtr.cpp.
~ElmPtr()
ElmPtr::~ElmPtr () virtual
Definition at line 46 of file ElmPtr.cpp.
Member Function Documentation
accept()
void ElmPtr::accept (BeamlineVisitor & visitor) const virtual
Apply visitor.
Reimplemented in FlaggedElmPtr.
Definition at line 50 of file ElmPtr.cpp.
References itsElement.
getElement()
ElementBase * ElmPtr::getElement () const inline
Get the element pointer.
Definition at line 61 of file ElmPtr.h.
References itsElement.
Referenced by Sequence::copy(), PlaceRep::enter(), Selector::handleElement(), PlaceRep::leave(), Sequence::print(), SequenceMember::setLength(), SpecificElementVisitor< ELEM >::visitFlaggedElmPtr(), Replacer::visitFlaggedElmPtr(), RangeSelector::visitFlaggedElmPtr(), and DefaultVisitor::visitFlaggedElmPtr().
setElement() [1/2]
void ElmPtr::setElement (ElementBase * elem) inline
Set the element pointer.
Definition at line 66 of file ElmPtr.h.
References itsElement.
Referenced by Sequence::addEndMarkers(), Sequence::copy(), Sequence::insertDrifts(), and SequenceParser::parseMember().
setElement() [2/2]
void ElmPtr::setElement (std::shared_ptr< ElementBase > elem) inline
Definition at line 83 of file ElmPtr.h.
References itsElement.
Member Data Documentation
itsElement
std::shared_ptr<ElementBase> ElmPtr::itsElement protected
Definition at line 57 of file ElmPtr.h.
Referenced by accept(), getElement(), setElement(), and setElement().
The documentation for this class was generated from the following files:
ElmPtr.h
ElmPtr.cpp