OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions::AUnary< T, U > Class Template Reference
Expressions::AUnary< T, U > Class Template Reference
An array expression with one array operand.
#include <AUnary.h>
Public Member Functions
AUnary (const TFunction1< T, U > &function, PtrToArray< U > operand)
Constructor.
AUnary (const AUnary< T, U > &)
virtual ~AUnary ()
virtual OArray< T > * clone () const
Make clone.
virtual std::vector< T > evaluate () const
Evaluate.
virtual void print (std::ostream &, int precedence=99) const
Print expression.
virtual bool isConstant () const
Test for constant.
Protected Attributes
ArrayOfPtrs< T > itsValue
The vector of expressions.
Private Member Functions
AUnary ()
void operator= (const AUnary &)
Private Attributes
const TFunction1< T, U > & fun
PtrToArray< U > opr
Detailed Description
template<class T, class U>
class Expressions::AUnary< T, U >
An array expression with one array operand.
Definition at line 39 of file AUnary.h.
Constructor & Destructor Documentation
AUnary() [1/3]
template<class T, class U> Expressions::AUnary< T, U >::AUnary (const TFunction1< T, U > & function, PtrToArray< U > operand) inline
Constructor.
Definition at line 77 of file AUnary.h.
References Expressions::AList< T >::AList(), fun, and opr.
Referenced by AUnary(), clone(), and operator=().
AUnary() [2/3]
template<class T, class U> Expressions::AUnary< T, U >::AUnary (const AUnary< T, U > & rhs) inline
Definition at line 73 of file AUnary.h.
References Expressions::AList< T >::AList(), AUnary(), clone(), fun, and opr.
~AUnary()
template<class T, class U> Expressions::AUnary< T, U >::~AUnary () inline virtual
Definition at line 81 of file AUnary.h.
AUnary() [3/3]
template<class T, class U> Expressions::AUnary< T, U >::AUnary () private
Member Function Documentation
clone()
template<class T, class U> OArray< T > * Expressions::AUnary< T, U >::clone () const inline virtual
Make clone.
Reimplemented from Expressions::AList< T >.
Definition at line 84 of file AUnary.h.
References AUnary().
Referenced by AUnary().
evaluate()
template<class T, class U> std::vector< T > Expressions::AUnary< T, U >::evaluate () const inline virtual
Evaluate.
Reimplemented from Expressions::AList< T >.
Definition at line 89 of file AUnary.h.
References fun, and opr.
isConstant()
template<class T> bool Expressions::OArray< T >::isConstant () const inline virtual inherited
Test for constant.
Definition at line 304 of file AbstractObjects/Expressions.h.
operator=()
template<class T, class U> void Expressions::AUnary< T, U >::operator= (const AUnary< T, U > &) private
References AUnary().
print()
template<class T, class U> void Expressions::AUnary< T, U >::print (std::ostream & os, int precedence = 99) const inline virtual
Print expression.
Reimplemented from Expressions::AList< T >.
Definition at line 113 of file AUnary.h.
References fun, and opr.
Member Data Documentation
fun
template<class T, class U> const TFunction1<T, U>& Expressions::AUnary< T, U >::fun private
Definition at line 63 of file AUnary.h.
Referenced by AUnary(), AUnary(), evaluate(), and print().
itsValue
template<class T> ArrayOfPtrs<T> Expressions::AList< T >::itsValue protected inherited
The vector of expressions.
Definition at line 59 of file AList.h.
Referenced by AList(), AList(), evaluate(), and print().
opr
template<class T, class U> PtrToArray<U> Expressions::AUnary< T, U >::opr private
Definition at line 66 of file AUnary.h.
Referenced by AUnary(), AUnary(), evaluate(), and print().
The documentation for this class was generated from the following file:
AUnary.h