OPALX (Object Oriented Parallel Accelerator Library for Exascal): Line Class Reference
Line Class Reference
#include <Line.h>
Public Types
enum ReferenceType { IS_ENTRY , IS_CENTRE , IS_EXIT }
Reference for element positioning.
Public Member Functions
Line ()
Exemplar constructor.
virtual ~Line ()
virtual Line * clone (const std::string &name)
Make clone.
virtual Line * copy (const std::string &name)
Make complete copy.
virtual double getLength () const
Return line length.
virtual Object * makeTemplate (const std::string &name, TokenStream &is, Statement &stat)
Make a line template.
virtual void parse (Statement &stat)
Parse the line object.
virtual void print (std::ostream &stream) const
Print the line.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual double getEntrance (ReferenceType) const
Return arc length from origin to entrance (negative !).
virtual double getExit (ReferenceType) const
Return arc length from origin to exit (positive !).
virtual void setShared (bool)
Set shared flag.
ElementBase * getElement () const
Return the embedded OPALX element.
std::shared_ptr< ElementBase > getElementPtr () const
Return the embedded OPALX element as shared_ptr.
void setElement (ElementBase *)
Assign new OPALX element.
void setElement (std::shared_ptr< ElementBase > base)
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Static Public Member Functions
static BeamSequence * find (const std::string &name)
Find a BeamSequence by name.
Public Attributes
std::vector< Attribute > itsAttr
The object attributes.
Protected Attributes
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Private Member Functions
Line (const Line &)
void operator= (const Line &)
Line (const std::string &name, Line *parent)
virtual FlaggedBeamline * fetchLine () const
Return the embedded OPALX beam line.
void parseList (Statement &)
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
Private Attributes
std::shared_ptr< ElementBase > itsOPALXElement
Object * itsParent
std::string itsName
std::string itsHelp
int occurrence
double timeStamp
std::set< Invalidator * > references
bool sharedFlag
Friends
class LineTemplate
Detailed Description
Definition at line 30 of file Line.h.
Member Enumeration Documentation
ReferenceType
enum Element::ReferenceType inherited
Reference for element positioning.
Enumerator
IS_ENTRY
IS_CENTRE
IS_EXIT
Definition at line 43 of file Element.h.
Constructor & Destructor Documentation
Line() [1/3]
Line::Line ()
Exemplar constructor.
Definition at line 64 of file Line.cpp.
References Object::itsAttr, Attributes::makeReal(), Attributes::makeRealArray(), Attributes::makeString(), Object::registerOwnership(), Element::setElement(), and AttributeHandler::STATEMENT.
Referenced by clone(), and copy().
~Line()
Line::~Line () virtual
Definition at line 108 of file Line.cpp.
Line() [2/3]
Line::Line (const Line &) private
Line() [3/3]
Line::Line (const std::string & name, Line * parent) private
Definition at line 102 of file Line.cpp.
References Element::setElement().
Member Function Documentation
canReplaceBy()
bool Element::canReplaceBy (Object * object) virtual inherited
Test if replacement is allowed.
Reimplemented from Object.
Definition at line 37 of file Element.cpp.
clear()
void Object::clear () inherited
Clear the occurrence counter.
Definition at line 285 of file Object.cpp.
References Object::occurrence.
clone()
Line * Line::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 110 of file Line.cpp.
References Line().
Referenced by copy(), and LineTemplate::makeInstance().
copy()
Line * Line::copy (const std::string & name) virtual
Make complete copy.
Implements BeamSequence.
Definition at line 112 of file Line.cpp.
References clone(), fetchLine(), and Line().
copyAttributes()
void Object::copyAttributes (const Object & source) inherited
Copy attributes from another object.
Definition at line 50 of file Object.cpp.
References Object::itsAttr.
Referenced by SequenceTemplate::makeInstance(), and LineTemplate::makeInstance().
execute()
void Object::execute () virtual inherited
Execute the command.
Reimplemented in Call, Echo, Help, Option, PSystem, Quit, Select, Stop, System, Title, Value, Distribution, EmissionSourceList, MacroCmd, Beam, BinningCmd, BoundaryGeometry, EmissionSource, FieldSolverCmd, TrackCmd, TrackEnd, TrackRun, OpalFilter, and DumpEMFields.
Definition at line 52 of file Object.cpp.
fetchLine()
FlaggedBeamline * Line::fetchLine () const private virtual
Return the embedded OPALX beam line.
Implements BeamSequence.
Definition at line 271 of file Line.cpp.
References Element::getElement().
Referenced by copy(), parse(), parseList(), print(), and replace().
find()
BeamSequence * BeamSequence::find (const std::string & name) static inherited
Find a BeamSequence by name.
Definition at line 30 of file BeamSequence.cpp.
References OpalData::find(), and OpalData::getInstance().
Referenced by TrackCmd::execute().
findAttribute() [1/2]
Attribute * Object::findAttribute (const std::string & name) virtual inherited
Find an attribute by name.
Definition at line 56 of file Object.cpp.
References Object::itsAttr.
Referenced by SequenceParser::findNeighbourPositions(), OpalElement::getParticleMatterInteraction(), OpalElement::getTypeName(), OpalElement::getWakeF(), Object::parse(), OpalElement::parse(), parse(), OpalParser::parseAssign(), SequenceParser::parsePosition(), TrackRun::print(), and TEST().
findAttribute() [2/2]
const Attribute * Object::findAttribute (const std::string & name) const virtual inherited
Find an attribute by name.
Definition at line 63 of file Object.cpp.
References Object::itsAttr.
getBaseObject()
const Object * Object::getBaseObject () const inherited
Return the object's base type object.
Definition at line 260 of file Object.cpp.
References Object::itsParent.
getCategory()
const std::string BeamSequence::getCategory () const virtual inherited
Return the object category as a string.
Reimplemented from Element.
Definition at line 28 of file BeamSequence.cpp.
getElement()
ElementBase * Element::getElement () const inline inherited
Return the embedded OPALX element.
Definition at line 119 of file Element.h.
References Element::itsOPALXElement.
Referenced by fetchLine(), Sequence::fetchLine(), OpalMarker::OpalMarker(), OpalVariableRFCavity::OpalVariableRFCavity(), replace(), Sequence::replace(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), OpalCavity::update(), OpalConstantEFieldCavity::update(), OpalDrift::update(), OpalElement::update(), OpalMarker::update(), OpalMonitor::update(), OpalMultipole::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalRBend::update(), OpalRingDefinition::update(), OpalSBend::update(), OpalSolenoid::update(), OpalTravelingWave::update(), OpalVacuum::update(), OpalVerticalFFAMagnet::update(), OpalLaser::update(), OpalMultipoleT::update(), and OpalVariableRFCavity::update().
getElementPtr()
std::shared_ptr< ElementBase > Element::getElementPtr () const inline inherited
Return the embedded OPALX element as shared_ptr.
Definition at line 121 of file Element.h.
References Element::itsOPALXElement.
Referenced by Sequence::addEndMarkers(), and parse().
getEntrance()
double Element::getEntrance (ReferenceType ref) const virtual inherited
Return arc length from origin to entrance (negative !).
Reimplemented in Sequence.
Definition at line 54 of file Element.cpp.
References Element::getLength(), Element::IS_CENTRE, and Element::IS_EXIT.
Referenced by Sequence::getEntrance().
getExit()
double Element::getExit (ReferenceType ref) const virtual inherited
Return arc length from origin to exit (positive !).
Reimplemented in Sequence.
Definition at line 67 of file Element.cpp.
References Element::getLength(), Element::IS_CENTRE, and Element::IS_ENTRY.
Referenced by Sequence::getExit().
getLength()
double Line::getLength () const virtual
Return line length.
Implements Element.
Definition at line 120 of file Line.cpp.
References Attributes::getReal(), and Object::itsAttr.
getOpalName()
const std::string & Object::getOpalName () const inherited
Return object name.
Definition at line 267 of file Object.cpp.
References Object::itsName.
Referenced by OpalVariableRFCavity::clone(), Macro::clone(), OpalData::create(), OpalData::define(), Sequence::findDriftLength(), SequenceParser::findNeighbourPositions(), ValueDefinition::getBool(), ValueDefinition::getBoolComponent(), ValueDefinition::getReal(), ValueDefinition::getRealComponent(), ValueDefinition::getString(), ValueDefinition::getStringComponent(), Object::makeInstance(), SequenceTemplate::makeInstance(), LineTemplate::makeInstance(), Object::parse(), SequenceParser::parseMember(), SequenceParser::parsePosition(), Object::print(), OpalElement::print(), Sequence::print(), TrackRun::print(), BoolConstant::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), StringConstant::print(), Beam::print(), OpalFilter::print(), print(), BinningCmd::printInfo(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), OpalElement::registerOwnership(), Object::registerOwnership(), replace(), Sequence::replace(), PartBunch< T, Dim >::setBins(), TEST(), TEST(), TEST(), TEST_F(), Beam::update(), BoundaryGeometry::update(), OpalFilter::update(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), and OpalSplineTimeDependence::update().
getParent()
Object * Object::getParent () const inherited
Return parent pointer.
Definition at line 269 of file Object.cpp.
References Object::itsParent.
Referenced by OpalData::erase(), Object::print(), OpalElement::print(), OpalElement::registerOwnership(), and Object::registerOwnership().
increment()
int Object::increment () inherited
Increment and return the occurrence counter.
Definition at line 287 of file Object.cpp.
References Object::occurrence.
Referenced by parse(), and Sequence::storeLine().
isBuiltin()
bool Object::isBuiltin () const inherited
True, if [b]this[/b] is a built-in object.
Definition at line 243 of file Object.cpp.
References Object::builtin.
Referenced by OpalData::define(), and OpalData::getVariableNames().
isDirty()
bool Object::isDirty () const inherited
True, if the [b]modified[/b] flag is set.
Definition at line 254 of file Object.cpp.
References Object::modified.
isFlagged()
bool Object::isFlagged () const inherited
True, if [b]this[/b] is flagged by setFlag(true).
Definition at line 258 of file Object.cpp.
References Object::flagged.
isShared()
bool Object::isShared () const virtual inherited
Shared flag.
Definition at line 245 of file Object.cpp.
References Object::sharedFlag.
Referenced by Sequence::print().
isTreeMember()
bool Object::isTreeMember (const Object * subTree) const inherited
Test for tree membership.
Definition at line 271 of file Object.cpp.
References Object::itsParent.
Referenced by Selector::handleElement(), and OpalParser::parseAssign().
makeInstance()
Object * Object::makeInstance (const std::string & name, Statement & , const Parser *) virtual inherited
Macro handler function.
Reimplemented in SequenceTemplate, MacroCmd, and LineTemplate.
Definition at line 76 of file Object.cpp.
References Object::getOpalName().
Referenced by OpalParser::parseDefine(), and OpalParser::parseMacro().
makeTemplate()
Object * Line::makeTemplate (const std::string & name, TokenStream & is, Statement & stat) virtual
Make a line template.
Reimplemented from Object.
Definition at line 122 of file Line.cpp.
References LineTemplate, and LineTemplate::parseTemplate().
occurrenceCount()
int Object::occurrenceCount () inherited
Return the occurrence counter.
Definition at line 289 of file Object.cpp.
References Object::occurrence.
operator=()
void Line::operator= (const Line &) private
parse()
void Line::parse (Statement & stat) virtual
Parse the line object.
Reimplemented from Object.
Definition at line 135 of file Line.cpp.
References OpalData::apply(), ElementBase::copyStructure(), Statement::delimiter(), fetchLine(), Element::find(), Object::findAttribute(), Element::getElementPtr(), OpalData::getInstance(), Attributes::getReal(), Attributes::getRealArray(), Object::increment(), Expressions::PtrToScalar< T >::isValid(), Object::itsAttr, Expressions::SBinary< T, U >::make(), Attribute::parse(), Expressions::parseDelimiter(), parseList(), Expressions::parseString(), Attribute::setDefault(), TBeamline< T >::setInitialDirection(), TBeamline< T >::setOrigin3D(), and TBeamline< T >::setRelativeFlag().
Referenced by LineTemplate::makeInstance().
parseList()
void Line::parseList (Statement & stat) private
Definition at line 273 of file Line.cpp.
References Statement::delimiter(), fetchLine(), OpalData::find(), OpalData::getInstance(), Statement::integer(), Expressions::parseDelimiter(), parseList(), Expressions::parseString(), and FlaggedElmPtr::setReflectionFlag().
Referenced by parse(), and parseList().
parseShortcut()
void Object::parseShortcut (Statement & stat, bool eval = true) virtual inherited
Parser for single-attribute commands.
Definition at line 113 of file Object.cpp.
Referenced by Call::parse(), Echo::parse(), Help::parse(), PSystem::parse(), System::parse(), Title::parse(), and Value::parse().
print()
void Line::print (std::ostream & stream) const virtual
Print the line.
Reimplemented from Object.
Definition at line 251 of file Line.cpp.
References fetchLine(), and Object::getOpalName().
printHelp()
void Object::printHelp (std::ostream &) const virtual inherited
Print help.
Definition at line 179 of file Object.cpp.
References gmsg, Object::itsAttr, and Object::itsHelp.
Referenced by Help::execute().
printValue()
void Object::printValue (std::ostream & os) const inline virtual inherited
Reimplemented in BoolConstant, RealConstant, RealVariable, RealVector, and StringConstant.
Definition at line 270 of file Object.h.
References Object::print().
registerOwnership()
void Object::registerOwnership (const AttributeHandler::OwnerType & itsClass) const inherited
Definition at line 169 of file Object.cpp.
References AttributeHandler::addAttributeOwner(), Object::getOpalName(), Object::getParent(), and Object::itsAttr.
Referenced by Beam::Beam(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), Call::Call(), Distribution::Distribution(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), EmissionSourceList::EmissionSourceList(), Help::Help(), Line(), OpalFilter::OpalFilter(), Option::Option(), PSystem::PSystem(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVector::RealVector(), Select::Select(), Sequence::Sequence(), StringConstant::StringConstant(), System::System(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), and Value::Value().
registerReference()
void Object::registerReference (Invalidator * a) inherited
Register a reference to this object.
Definition at line 165 of file Object.cpp.
References Object::references.
replace()
void Line::replace (Object * oldObject, Object * newObject) private virtual
Replace references.
Reimplemented from Object.
Definition at line 341 of file Line.cpp.
References DefaultVisitor::execute(), fetchLine(), Element::getElement(), and Object::getOpalName().
setDirty()
void Object::setDirty (bool dirty) inherited
Set/reset the [b]modified[/b] flag.
Definition at line 249 of file Object.cpp.
References Object::modified.
Referenced by OpalData::define(), OpalData::makeDirty(), and RealVariable::RealVariable().
setElement() [1/2]
void Element::setElement (ElementBase * base) inline inherited
Assign new OPALX element.
Definition at line 123 of file Element.h.
References Element::itsOPALXElement.
Referenced by Line(), Line(), OpalCavity::OpalCavity(), OpalCavity::OpalCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalDrift::OpalDrift(), OpalDrift::OpalDrift(), OpalLaser::OpalLaser(), OpalLaser::OpalLaser(), OpalMarker::OpalMarker(), OpalMarker::OpalMarker(), OpalMonitor::OpalMonitor(), OpalMonitor::OpalMonitor(), OpalMultipole::OpalMultipole(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalMultipoleT::OpalMultipoleT(), OpalProbe::OpalProbe(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalQuadrupole::OpalQuadrupole(), OpalRBend::OpalRBend(), OpalRBend::OpalRBend(), OpalRingDefinition::OpalRingDefinition(), OpalRingDefinition::OpalRingDefinition(), OpalSBend::OpalSBend(), OpalSBend::OpalSBend(), OpalSolenoid::OpalSolenoid(), OpalSolenoid::OpalSolenoid(), OpalTravelingWave::OpalTravelingWave(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), Sequence::Sequence(), Sequence::Sequence(), and OpalVariableRFCavity::update().
setElement() [2/2]
void Element::setElement (std::shared_ptr< ElementBase > base) inline inherited
Definition at line 130 of file Element.h.
References Element::itsOPALXElement.
setFlag()
void Object::setFlag (bool flag) inherited
Flag/unflag this object, e. g. to control output of objects for.
Definition at line 256 of file Object.cpp.
References Object::flagged.
setOpalName()
void Object::setOpalName (const std::string & name) inherited
Set object name.
Definition at line 281 of file Object.cpp.
References Object::itsName.
Referenced by TEST(), TEST(), TEST(), Beam::update(), BoundaryGeometry::update(), and OpalFilter::update().
setParent()
void Object::setParent (Object * parent) inherited
Set parent object.
Definition at line 283 of file Object.cpp.
References Object::itsParent.
Referenced by OpalData::erase().
setShared()
void Element::setShared (bool flag) virtual inherited
Set shared flag.
Reimplemented from Object.
Definition at line 80 of file Element.cpp.
References Element::itsOPALXElement, and Object::setShared().
shouldTrace()
bool Element::shouldTrace () const virtual inherited
Trace flag.
Implements Object.
Definition at line 50 of file Element.cpp.
shouldUpdate()
bool Element::shouldUpdate () const virtual inherited
Update flag.
Implements Object.
Definition at line 52 of file Element.cpp.
unregisterReference()
void Object::unregisterReference (Invalidator * a) inherited
Unegister a reference to this object.
Definition at line 167 of file Object.cpp.
References Object::references.
update()
void Object::update () virtual inherited
Update this object.
Reimplemented in Option, OpalCavity, OpalConstantEFieldCavity, OpalDrift, OpalElement, OpalMarker, OpalMonitor, OpalMultipole, OpalProbe, OpalQuadrupole, OpalRBend, OpalRingDefinition, OpalSBend, OpalSolenoid, OpalSource, OpalTravelingWave, OpalVacuum, OpalVerticalFFAMagnet, Sequence, Beam, BinningCmd, BoundaryGeometry, FieldSolverCmd, OpalFilter, OpalLaser, OpalMultipoleT, OpalPolynomialTimeDependence, OpalSinusoidalTimeDependence, OpalSplineTimeDependence, and OpalVariableRFCavity.
Definition at line 239 of file Object.cpp.
Referenced by Distribution::execute().
Friends And Related Symbol Documentation
LineTemplate
friend class LineTemplate friend
Definition at line 31 of file Line.h.
Referenced by makeTemplate().
Member Data Documentation
builtin
bool Object::builtin protected inherited
Built-in flag.
Definition at line 226 of file Object.h.
Referenced by Beam::Beam(), BoundaryGeometry::BoundaryGeometry(), Object::isBuiltin(), Object::Object(), Object::Object(), OpalFilter::OpalFilter(), OpalMarker::OpalMarker(), RealConstant::RealConstant(), StringConstant::StringConstant(), and Table::~Table().
flagged
bool Object::flagged protected inherited
Object flag.
Definition at line 235 of file Object.h.
Referenced by Object::isFlagged(), Object::Object(), Object::Object(), and Object::setFlag().
itsAttr
std::vector<Attribute> Object::itsAttr inherited
The object attributes.
Definition at line 210 of file Object.h.
Referenced by Beam::Beam(), BinningCmd::BinningCmd(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), BoundaryGeometry::BoundaryGeometry(), DumpEMFields::buildGrid(), Call::Call(), FieldSolverCmd::constructBCHandler(), Object::copyAttributes(), Distribution::Distribution(), BinningCmd::dumpBinsToFile(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), Call::execute(), Echo::execute(), Help::execute(), Option::execute(), PSystem::execute(), Select::execute(), System::execute(), Title::execute(), Value::execute(), Beam::execute(), TrackCmd::execute(), TrackRun::execute(), FieldSolverCmd::FieldSolverCmd(), Object::findAttribute(), Object::findAttribute(), BoundaryGeometry::getA(), OpalElement::getApert(), BoundaryGeometry::getB(), BinningCmd::getBinningAlpha(), BinningCmd::getBinningBeta(), FieldSolverCmd::getBinsName(), BoolConstant::getBool(), FieldSolverCmd::getBoxIncr(), Beam::getBunchCharge(), BoundaryGeometry::getC(), Beam::getCharge(), Beam::getCurrent(), Beam::getDaughterBeamName(), BinningCmd::getDesiredWidth(), EmissionSource::getDistributionName(), FieldSolverCmd::getDomDec(), TrackCmd::getDT(), TrackCmd::getDTAU(), TrackCmd::getDTSCINIT(), BinningCmd::getDumpBinsFileName(), BinningCmd::getDumpBinsFrequency(), EmissionSource::getEmissionModel(), Beam::getEmissionSourceListName(), Distribution::getFilename(), BoundaryGeometry::getFilename(), Beam::getFrequency(), Beam::getGlobalProcessNames(), BoundaryGeometry::getL1(), BoundaryGeometry::getL2(), BoundaryGeometry::getLength(), OpalElement::getLength(), getLength(), Sequence::getLength(), Beam::getMass(), BinningCmd::getMaxBins(), TrackCmd::getMaxSteps(), Beam::getNumAlloc(), FieldSolverCmd::getNX(), FieldSolverCmd::getNY(), FieldSolverCmd::getNZ(), EmissionSource::getP0(), BinningCmd::getParameter(), Beam::getParticleName(), EmissionSource::getR0(), RealConstant::getReal(), RealVariable::getReal(), RealVector::getRealComponent(), Sequence::getReference(), BoundaryGeometry::getS(), EmissionSource::getShiftedGreensFunction(), TrackCmd::getStepsPerTurn(), StringConstant::getString(), EmissionSource::getT0(), TrackCmd::getT0(), BinningCmd::getTablePrintFrequency(), TrackCmd::getTimeIntegrator(), BoundaryGeometry::getTopology(), FieldSolverCmd::getType(), EmissionSource::getZerofaceMaxSteps(), EmissionSource::getZeroFacePlaneDumpFrequency(), EmissionSource::getZeroFaceR0Z(), TrackCmd::getZStart(), TrackCmd::getZStop(), Beam::hasExplicitEnergy(), Help::Help(), BoundaryGeometry::initialize(), OpalFilter::initOpalFilter(), Beam::isPhoton(), Line(), OpalBend::OpalBend(), OpalCavity::OpalCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalDrift::OpalDrift(), OpalElement::OpalElement(), OpalFilter::OpalFilter(), OpalLaser::OpalLaser(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalPolynomialTimeDependence::OpalPolynomialTimeDependence(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalRingDefinition::OpalRingDefinition(), OpalSinusoidalTimeDependence::OpalSinusoidalTimeDependence(), OpalSolenoid::OpalSolenoid(), OpalSplineTimeDependence::OpalSplineTimeDependence(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), Option::Option(), Option::Option(), Sequence::parse(), parse(), DumpEMFields::parseCoordinateSystem(), Object::print(), Sequence::print(), BoolConstant::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), StringConstant::print(), Beam::print(), OpalFilter::print(), DumpEMFields::print(), Object::printHelp(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), BoolConstant::printValue(), RealConstant::printValue(), RealVariable::printValue(), RealVector::printValue(), StringConstant::printValue(), PSystem::PSystem(), RealConstant::RealConstant(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVariable::RealVariable(), RealVector::RealVector(), OpalElement::registerOwnership(), Object::registerOwnership(), Select::Select(), Select::select(), Sequence::Sequence(), Distribution::setAttributes(), TestMultipoleT::TestableFieldSolverCmd::setBCX(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCX(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCX(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCX(), TestVariableRFCavity::TestableFieldSolverCmd::setBCX(), OrbitThreaderTest::TestableFieldSolverCmd::setBCX(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCX(), TestMultipoleT::TestableFieldSolverCmd::setBCY(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCY(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCY(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCY(), TestVariableRFCavity::TestableFieldSolverCmd::setBCY(), OrbitThreaderTest::TestableFieldSolverCmd::setBCY(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCY(), TestMultipoleT::TestableFieldSolverCmd::setBCZ(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCZ(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCZ(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCZ(), TestVariableRFCavity::TestableFieldSolverCmd::setBCZ(), OrbitThreaderTest::TestableFieldSolverCmd::setBCZ(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCZ(), TestableBinningCmd::setBinningAlpha(), TestableBinningCmd::setBinningBeta(), TestableBinningCmd::setDesiredWidth(), Distribution::setDistParametersFlatTop(), Distribution::setDistParametersMultiVariateGauss(), Distribution::setDistType(), TestableBinningCmd::setDumpBinsFile(), TestableBinningCmd::setDumpBinsFreq(), TestableBinningCmd::setMaxBins(), FieldSolverCmd::setNX(), FieldSolverCmd::setNY(), FieldSolverCmd::setNZ(), TestableBinningCmd::setParameterString(), TrackRun::setRunMethod(), Distribution::setSigmaP_m(), Distribution::setSigmaR_m(), TestableBinningCmd::setTablePrintFrequency(), TestMultipoleT::TestableFieldSolverCmd::setType(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setType(), TestMultipoleTStraight::TestableFieldSolverCmd::setType(), SolenoidPlacementTest::TestableFieldSolverCmd::setType(), TestVariableRFCavity::TestableFieldSolverCmd::setType(), OrbitThreaderTest::TestableFieldSolverCmd::setType(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setType(), TrackRun::setupBoundaryGeometry(), StringConstant::StringConstant(), StringConstant::StringConstant(), System::System(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), OpalCavity::update(), OpalConstantEFieldCavity::update(), OpalDrift::update(), OpalElement::update(), OpalMonitor::update(), OpalMultipole::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalRBend::update(), OpalRingDefinition::update(), OpalSBend::update(), OpalSolenoid::update(), OpalTravelingWave::update(), OpalVacuum::update(), OpalVerticalFFAMagnet::update(), Beam::update(), BinningCmd::update(), FieldSolverCmd::update(), OpalLaser::update(), OpalMultipoleT::update(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), OpalSplineTimeDependence::update(), OpalVariableRFCavity::update(), Option::update(), OpalElement::updateUnknown(), ValueDefinition::value(), Value::Value(), and ValueDefinition::value().
itsHelp
std::string Object::itsHelp private inherited
Definition at line 250 of file Object.h.
Referenced by Object::printHelp().
itsName
std::string Object::itsName private inherited
Definition at line 247 of file Object.h.
Referenced by Object::getOpalName(), and Object::setOpalName().
itsOPALXElement
std::shared_ptr<ElementBase> Element::itsOPALXElement private inherited
Definition at line 113 of file Element.h.
Referenced by Element::getElement(), Element::getElementPtr(), Element::setElement(), Element::setElement(), and Element::setShared().
itsParent
Object* Object::itsParent private inherited
Definition at line 244 of file Object.h.
Referenced by Object::getBaseObject(), Object::getParent(), Object::isTreeMember(), and Object::setParent().
modified
bool Object::modified protected inherited
Dirty flag.
Definition at line 231 of file Object.h.
Referenced by Object::isDirty(), Object::Object(), Object::Object(), and Object::setDirty().
occurrence
int Object::occurrence private inherited
Definition at line 253 of file Object.h.
Referenced by Object::clear(), Object::increment(), and Object::occurrenceCount().
references
std::set<Invalidator*> Object::references private inherited
Definition at line 260 of file Object.h.
Referenced by Object::registerReference(), Object::unregisterReference(), and Object::~Object().
sharedFlag
bool Object::sharedFlag private inherited
Definition at line 263 of file Object.h.
Referenced by Object::isShared(), and Object::setShared().
timeStamp
double Object::timeStamp private inherited
Definition at line 256 of file Object.h.
The documentation for this class was generated from the following files:
Line.h
Line.cpp