OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions::PtrToArray< T > Class Template Reference
Expressions::PtrToArray< T > Class Template Reference
A pointer to an array expression.
#include <Expressions.h>
Public Member Functions
PtrToArray (OArray< T > *rhs)
Constructor from object just created.
PtrToArray ()
PtrToArray (const PtrToArray &rhs)
PtrToArray (PtrToArray &&rhs) noexcept=default
~PtrToArray ()
PtrToArray & operator= (const PtrToArray< T > &)
PtrToArray & operator= (PtrToArray &&) noexcept=default
PtrToArray & operator= (OArray< T > *rhs)
OArray< T > * operator-> () const
OArray< T > & operator* () const
operator bool () const
bool isValid () const
OArray< T > * release ()
OArray< T > * get () const
Private Attributes
std::unique_ptr< OArray< T > > ptr_m
Detailed Description
template<class T>
class Expressions::PtrToArray< T >
A pointer to an array expression.
Definition at line 182 of file AbstractObjects/Expressions.h.
Constructor & Destructor Documentation
PtrToArray() [1/4]
template<class T> Expressions::PtrToArray< T >::PtrToArray (OArray< T > * rhs) inline
Constructor from object just created.
Definition at line 363 of file AbstractObjects/Expressions.h.
References ptr_m.
Referenced by operator=(), operator=(), operator=(), PtrToArray(), and PtrToArray().
PtrToArray() [2/4]
template<class T> Expressions::PtrToArray< T >::PtrToArray () inline
Definition at line 357 of file AbstractObjects/Expressions.h.
References ptr_m.
PtrToArray() [3/4]
template<class T> Expressions::PtrToArray< T >::PtrToArray (const PtrToArray< T > & rhs) inline
Definition at line 360 of file AbstractObjects/Expressions.h.
References ptr_m, and PtrToArray().
PtrToArray() [4/4]
template<class T> Expressions::PtrToArray< T >::PtrToArray (PtrToArray< T > && rhs) default noexcept
References PtrToArray().
~PtrToArray()
template<class T> Expressions::PtrToArray< T >::~PtrToArray () inline
Definition at line 366 of file AbstractObjects/Expressions.h.
Member Function Documentation
get()
template<class T> OArray< T > * Expressions::PtrToArray< T >::get () const inline
Definition at line 200 of file AbstractObjects/Expressions.h.
References ptr_m.
isValid()
template<class T> bool Expressions::PtrToArray< T >::isValid () const inline
Definition at line 198 of file AbstractObjects/Expressions.h.
References ptr_m.
operator bool()
template<class T> Expressions::PtrToArray< T >::operator bool () const inline explicit
Definition at line 197 of file AbstractObjects/Expressions.h.
References ptr_m.
operator*()
template<class T> OArray< T > & Expressions::PtrToArray< T >::operator* () const inline
Definition at line 196 of file AbstractObjects/Expressions.h.
References ptr_m.
operator->()
template<class T> OArray< T > * Expressions::PtrToArray< T >::operator-> () const inline
Definition at line 195 of file AbstractObjects/Expressions.h.
References ptr_m.
operator=() [1/3]
template<class T> PtrToArray & Expressions::PtrToArray< T >::operator= (const PtrToArray< T > &)
References PtrToArray().
operator=() [2/3]
template<class T> PtrToArray< T > & Expressions::PtrToArray< T >::operator= (OArray< T > * rhs) inline
Definition at line 377 of file AbstractObjects/Expressions.h.
References ptr_m, and PtrToArray().
operator=() [3/3]
template<class T> PtrToArray & Expressions::PtrToArray< T >::operator= (PtrToArray< T > &&) default noexcept
References PtrToArray().
release()
template<class T> OArray< T > * Expressions::PtrToArray< T >::release () inline
Definition at line 199 of file AbstractObjects/Expressions.h.
References ptr_m.
Member Data Documentation
ptr_m
template<class T> std::unique_ptr<OArray<T> > Expressions::PtrToArray< T >::ptr_m mutable private
Definition at line 204 of file AbstractObjects/Expressions.h.
Referenced by get(), isValid(), operator bool(), operator*(), operator->(), operator=(), PtrToArray(), PtrToArray(), PtrToArray(), and release().
The documentation for this class was generated from the following file:
AbstractObjects/Expressions.h