OPALX (Object Oriented Parallel Accelerator Library for Exascal): ConstBzField Class Reference
ConstBzField Class Reference
A homogeneous magnetostatic field in z-direction.
#include <ConstBzField.h>
Public Member Functions
ConstBzField ()
Default constructor.
virtual ~ConstBzField ()
virtual BVector Bfield (const Point3D &P) const
Get field.
virtual BVector Bfield (const Point3D &P, double t) const
Get field.
virtual double getBz () const
Get component.
virtual void setBz (double Bz)
Set component.
virtual void scale (double scalar)
Scale the field.
virtual double getBx () const
Get component.
virtual double getBy () const
Get component.
virtual void setBx (double)
Set component.
virtual void setBy (double)
Set component.
virtual EVector Efield (const Point3D &P) const
Get field.
virtual EVector Efield (const Point3D &P, double t) const
Get field.
virtual EBVectors EBfield (const Point3D &P) const
Get field.
virtual EBVectors EBfield (const Point3D &P, double t) const
Get field.
Static Public Attributes
static const EVector ZeroEfield
The constant representing a zero electric field.
static const BVector ZeroBfield
The constant representing a zero magnetic field.
static const EBVectors ZeroEBfield
The constant representing a zero electromagnetic field.
Private Attributes
double Bz
Detailed Description
A homogeneous magnetostatic field in z-direction.
Definition at line 29 of file ConstBzField.h.
Constructor & Destructor Documentation
ConstBzField()
ConstBzField::ConstBzField ()
Default constructor.
Definition at line 26 of file ConstBzField.cpp.
~ConstBzField()
ConstBzField::~ConstBzField () virtual
Definition at line 28 of file ConstBzField.cpp.
Member Function Documentation
Bfield() [1/2]
BVector ConstBzField::Bfield (const Point3D & P) const virtual
Get field.
Reimplemented from EMField.
Definition at line 30 of file ConstBzField.cpp.
References Bz.
Bfield() [2/2]
BVector ConstBzField::Bfield (const Point3D & P, double t) const virtual
Get field.
Reimplemented from EMField.
Definition at line 32 of file ConstBzField.cpp.
References Bz.
EBfield() [1/2]
EBVectors EMField::EBfield (const Point3D & P) const virtual inherited
Get field.
Definition at line 127 of file EMField.cpp.
References EMField::Bfield(), and EMField::Efield().
Referenced by Component::EBfield(), Component::EBfield(), and EMField::EBfield().
EBfield() [2/2]
EBVectors EMField::EBfield (const Point3D & P, double t) const virtual inherited
Get field.
Definition at line 129 of file EMField.cpp.
References EMField::EBfield().
Efield() [1/2]
EVector EMField::Efield (const Point3D & P) const virtual inherited
Get field.
Reimplemented in ConstEzField, and OscillatingField< ConstEzField >.
Definition at line 119 of file EMField.cpp.
References EMField::ZeroEfield.
Referenced by EMField::EBfield(), Component::Efield(), Component::Efield(), and EMField::Efield().
Efield() [2/2]
EVector EMField::Efield (const Point3D & P, double t) const virtual inherited
Get field.
Reimplemented in ConstEzField, and OscillatingField< ConstEzField >.
Definition at line 123 of file EMField.cpp.
References EMField::Efield().
getBx()
double ConstBField::getBx () const virtual inherited
Get component.
Reimplemented in BDipoleField.
Definition at line 30 of file ConstBField.cpp.
getBy()
double ConstBField::getBy () const virtual inherited
Get component.
Reimplemented in BDipoleField.
Definition at line 32 of file ConstBField.cpp.
getBz()
double ConstBzField::getBz () const virtual
Get component.
Reimplemented from ConstBField.
Definition at line 34 of file ConstBzField.cpp.
References Bz.
Referenced by SolenoidRep::getBz().
scale()
void ConstBzField::scale (double scalar) virtual
Scale the field.
Implements EMField.
Definition at line 38 of file ConstBzField.cpp.
References Bz.
setBx()
void ConstBField::setBx (double) virtual inherited
Set component.
Reimplemented in BDipoleField.
Definition at line 36 of file ConstBField.cpp.
setBy()
void ConstBField::setBy (double) virtual inherited
Set component.
Reimplemented in BDipoleField.
Definition at line 38 of file ConstBField.cpp.
setBz()
void ConstBzField::setBz (double Bz) virtual
Set component.
Reimplemented from ConstBField.
Definition at line 36 of file ConstBzField.cpp.
References Bz.
Referenced by SolenoidRep::setBz().
Member Data Documentation
Bz
double ConstBzField::Bz private
Definition at line 61 of file ConstBzField.h.
Referenced by Bfield(), Bfield(), getBz(), scale(), and setBz().
ZeroBfield
const BVector EMField::ZeroBfield static inherited
The constant representing a zero magnetic field.
Definition at line 220 of file EMField.h.
Referenced by EMField::Bfield().
ZeroEBfield
const EBVectors EMField::ZeroEBfield static inherited
The constant representing a zero electromagnetic field.
Definition at line 223 of file EMField.h.
ZeroEfield
const EVector EMField::ZeroEfield static inherited
The constant representing a zero electric field.
Definition at line 217 of file EMField.h.
Referenced by EMField::Efield().
The documentation for this class was generated from the following files:
ConstBzField.h
ConstBzField.cpp