OPALX (Object Oriented Parallel Accelerator Library for Exascal): Misalignment Class Reference
Misalignment Class Reference
Local nominal-to-actual correction transform.
#include <Misalignment.h>
Public Member Functions
Misalignment ()=default
Misalignment (const CoordinateSystemTrafo &nominalToActual)
const CoordinateSystemTrafo & getNominalToActual () const
Private Attributes
CoordinateSystemTrafo nominalToActual_m
Detailed Description
Local nominal-to-actual correction transform.
The transform maps coordinates from the nominal element body frame into the actual body frame after local survey or misalignment corrections.
Definition at line 13 of file Misalignment.h.
Constructor & Destructor Documentation
Misalignment() [1/2]
Misalignment::Misalignment () default
Misalignment() [2/2]
Misalignment::Misalignment (const CoordinateSystemTrafo & nominalToActual) inline explicit
Definition at line 16 of file Misalignment.h.
Member Function Documentation
getNominalToActual()
const CoordinateSystemTrafo & Misalignment::getNominalToActual () const inline
Definition at line 19 of file Misalignment.h.
References nominalToActual_m.
Referenced by PlacedElement::getActualBodyTransform(), OpalBeamline::getMisalignment(), TEST_F(), and TEST_F().
Member Data Documentation
nominalToActual_m
CoordinateSystemTrafo Misalignment::nominalToActual_m private
Definition at line 22 of file Misalignment.h.
Referenced by getNominalToActual().
The documentation for this class was generated from the following file:
Misalignment.h