OPALX (Object Oriented Parallel Accelerator Library for Exascal): SolenoidPlacementTest::TestableFieldSolverCmd Class Reference
SolenoidPlacementTest::TestableFieldSolverCmd Class Reference
Public Member Functions
void setType (const std::string &t)
void setBCX (const std::string &bc)
void setBCY (const std::string &bc)
void setBCZ (const std::string &bc)
virtual FieldSolverCmd * clone (const std::string &name)
Make clone.
std::string getType ()
std::string getBinsName () const
BinningCmd * getBinningCmd () const
BCHandler< 3 > constructBCHandler () const
Returns solver boundary conditions handler object.
double getNX () const
Return meshsize.
double getNY () const
Return meshsize.
double getNZ () const
Return meshsize.
void setNX (double)
void setNY (double)
void setNZ (double)
double getBoxIncr () const
virtual void update ()
Update the field solver data.
virtual void execute ()
Execute (init) the field solver data.
bool hasValidSolver ()
bool hasBinningCmd () const
void setFieldSolverCmdType ()
FieldSolverCmdType getFieldSolverCmdType () const
ippl::Vector< bool, 3 > getDomDec () const
Inform & printInfo (Inform &os) const
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Static Public Member Functions
static FieldSolverCmd * find (const std::string &name)
Find named FieldSolverCmd.
Public Attributes
std::vector< Attribute > itsAttr
The object attributes.
Protected Attributes
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Private Attributes
std::string fsName_m
FieldSolverCmdType fsType_m
Object * itsParent
std::string itsName
std::string itsHelp
int occurrence
double timeStamp
std::set< Invalidator * > references
bool sharedFlag
Detailed Description
Definition at line 58 of file TestSolenoid.cpp.
Member Function Documentation
canReplaceBy()
bool Object::canReplaceBy (Object * object) virtual inherited
Test if replacement is allowed.
Reimplemented in Table, Action, Element, Distribution, EmissionSourceList, Beam, BoundaryGeometry, EmissionSource, OpalFilter, BoolConstant, RealConstant, StringConstant, RealVariable, and RealVector.
Definition at line 45 of file Object.cpp.
Referenced by OpalData::define().
clear()
void Object::clear () inherited
Clear the occurrence counter.
Definition at line 285 of file Object.cpp.
References Object::occurrence.
clone()
FieldSolverCmd * FieldSolverCmd::clone (const std::string & name) virtual inherited
Make clone.
Implements Object.
Definition at line 87 of file FieldSolverCmd.cpp.
References FieldSolverCmd::FieldSolverCmd().
constructBCHandler()
BCHandler< 3 > FieldSolverCmd::constructBCHandler () const inherited
Returns solver boundary conditions handler object.
Todo:
remove this restriction when more BC configurations are implemented
Add an additional check weather the boundary conditions are valid, which currently means either OPEN or PERIODIC in all dimensions.
Definition at line 111 of file FieldSolverCmd.cpp.
References FIELDSOLVER::BCFFTX, FIELDSOLVER::BCFFTY, FIELDSOLVER::BCFFTZ, Attributes::getString(), and Object::itsAttr.
Referenced by PartBunch< T, Dim >::PartBunch().
copyAttributes()
void Object::copyAttributes (const Object & source) inherited
Copy attributes from another object.
Definition at line 50 of file Object.cpp.
References Object::itsAttr.
Referenced by SequenceTemplate::makeInstance(), and LineTemplate::makeInstance().
execute()
void FieldSolverCmd::execute () virtual inherited
Execute (init) the field solver data.
Reimplemented from Object.
Definition at line 91 of file FieldSolverCmd.cpp.
References FieldSolverCmd::setFieldSolverCmdType(), and FieldSolverCmd::update().
find()
FieldSolverCmd * FieldSolverCmd::find (const std::string & name) static inherited
Find named FieldSolverCmd.
Definition at line 96 of file FieldSolverCmd.cpp.
References OpalData::find(), and OpalData::getInstance().
Referenced by TrackRun::execute().
findAttribute() [1/2]
Attribute * Object::findAttribute (const std::string & name) virtual inherited
Find an attribute by name.
Definition at line 56 of file Object.cpp.
References Object::itsAttr.
Referenced by SequenceParser::findNeighbourPositions(), OpalElement::getParticleMatterInteraction(), OpalElement::getTypeName(), OpalElement::getWakeF(), Object::parse(), OpalElement::parse(), Line::parse(), OpalParser::parseAssign(), SequenceParser::parsePosition(), TrackRun::print(), and TEST().
findAttribute() [2/2]
const Attribute * Object::findAttribute (const std::string & name) const virtual inherited
Find an attribute by name.
Definition at line 63 of file Object.cpp.
References Object::itsAttr.
getBaseObject()
const Object * Object::getBaseObject () const inherited
Return the object's base type object.
Definition at line 260 of file Object.cpp.
References Object::itsParent.
getBinningCmd()
BinningCmd * FieldSolverCmd::getBinningCmd () const inherited
Definition at line 177 of file FieldSolverCmd.cpp.
References BinningCmd::find(), and FieldSolverCmd::getBinsName().
Referenced by TrackRun::execute(), and FieldSolverCmd::hasBinningCmd().
getBinsName()
std::string FieldSolverCmd::getBinsName () const inherited
Definition at line 107 of file FieldSolverCmd.cpp.
References FIELDSOLVER::BINS, Attributes::getString(), and Object::itsAttr.
Referenced by FieldSolverCmd::getBinningCmd(), and FieldSolverCmd::printInfo().
getBoxIncr()
double FieldSolverCmd::getBoxIncr () const inherited
Definition at line 147 of file FieldSolverCmd.cpp.
References FIELDSOLVER::BBOXINCR, Attributes::getReal(), and Object::itsAttr.
getCategory()
const std::string Definition::getCategory () const virtual inherited
Return the object category as a string.
Implements Object.
Definition at line 26 of file Definition.cpp.
getDomDec()
ippl::Vector< bool, 3 > FieldSolverCmd::getDomDec () const inline inherited
Definition at line 122 of file FieldSolverCmd.h.
References Attributes::getBool(), Object::itsAttr, FIELDSOLVER::PARFFTX, FIELDSOLVER::PARFFTY, and FIELDSOLVER::PARFFTZ.
Referenced by PartBunch< T, Dim >::PartBunch().
getFieldSolverCmdType()
FieldSolverCmdType FieldSolverCmd::getFieldSolverCmdType () const inline inherited
Definition at line 121 of file FieldSolverCmd.h.
References FieldSolverCmd::fsType_m.
getNX()
double FieldSolverCmd::getNX () const inherited
Return meshsize.
Definition at line 135 of file FieldSolverCmd.cpp.
References Attributes::getReal(), Object::itsAttr, and FIELDSOLVER::NX.
Referenced by PartBunch< T, Dim >::PartBunch().
getNY()
double FieldSolverCmd::getNY () const inherited
Return meshsize.
Definition at line 137 of file FieldSolverCmd.cpp.
References Attributes::getReal(), Object::itsAttr, and FIELDSOLVER::NY.
Referenced by PartBunch< T, Dim >::PartBunch().
getNZ()
double FieldSolverCmd::getNZ () const inherited
Return meshsize.
Definition at line 139 of file FieldSolverCmd.cpp.
References Attributes::getReal(), Object::itsAttr, and FIELDSOLVER::NZ.
Referenced by PartBunch< T, Dim >::PartBunch().
getOpalName()
const std::string & Object::getOpalName () const inherited
Return object name.
Definition at line 267 of file Object.cpp.
References Object::itsName.
Referenced by OpalVariableRFCavity::clone(), Macro::clone(), OpalData::create(), OpalData::define(), Sequence::findDriftLength(), SequenceParser::findNeighbourPositions(), ValueDefinition::getBool(), ValueDefinition::getBoolComponent(), ValueDefinition::getReal(), ValueDefinition::getRealComponent(), ValueDefinition::getString(), ValueDefinition::getStringComponent(), Object::makeInstance(), SequenceTemplate::makeInstance(), LineTemplate::makeInstance(), Object::parse(), SequenceParser::parseMember(), SequenceParser::parsePosition(), Object::print(), OpalElement::print(), Sequence::print(), TrackRun::print(), BoolConstant::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), StringConstant::print(), Beam::print(), OpalFilter::print(), Line::print(), BinningCmd::printInfo(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), OpalElement::registerOwnership(), Object::registerOwnership(), Line::replace(), Sequence::replace(), PartBunch< T, Dim >::setBins(), TEST(), TEST(), TEST(), TEST_F(), Beam::update(), BoundaryGeometry::update(), OpalFilter::update(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), and OpalSplineTimeDependence::update().
getParent()
Object * Object::getParent () const inherited
Return parent pointer.
Definition at line 269 of file Object.cpp.
References Object::itsParent.
Referenced by OpalData::erase(), Object::print(), OpalElement::print(), OpalElement::registerOwnership(), and Object::registerOwnership().
getType()
std::string FieldSolverCmd::getType () inherited
Definition at line 105 of file FieldSolverCmd.cpp.
References Attributes::getString(), Object::itsAttr, and FIELDSOLVER::TYPE.
Referenced by TrackRun::configureImageChargeFromSources(), FieldSolverCmd::setFieldSolverCmdType(), and FieldSolverCmd::update().
hasBinningCmd()
bool FieldSolverCmd::hasBinningCmd () const inline inherited
Definition at line 100 of file FieldSolverCmd.h.
References FieldSolverCmd::getBinningCmd().
Referenced by TrackRun::execute().
hasValidSolver()
bool FieldSolverCmd::hasValidSolver () inherited
Definition at line 175 of file FieldSolverCmd.cpp.
increment()
int Object::increment () inherited
Increment and return the occurrence counter.
Definition at line 287 of file Object.cpp.
References Object::occurrence.
Referenced by Line::parse(), and Sequence::storeLine().
isBuiltin()
bool Object::isBuiltin () const inherited
True, if [b]this[/b] is a built-in object.
Definition at line 243 of file Object.cpp.
References Object::builtin.
Referenced by OpalData::define(), and OpalData::getVariableNames().
isDirty()
bool Object::isDirty () const inherited
True, if the [b]modified[/b] flag is set.
Definition at line 254 of file Object.cpp.
References Object::modified.
isFlagged()
bool Object::isFlagged () const inherited
True, if [b]this[/b] is flagged by setFlag(true).
Definition at line 258 of file Object.cpp.
References Object::flagged.
isShared()
bool Object::isShared () const virtual inherited
Shared flag.
Definition at line 245 of file Object.cpp.
References Object::sharedFlag.
Referenced by Sequence::print().
isTreeMember()
bool Object::isTreeMember (const Object * subTree) const inherited
Test for tree membership.
Definition at line 271 of file Object.cpp.
References Object::itsParent.
Referenced by Selector::handleElement(), and OpalParser::parseAssign().
makeInstance()
Object * Object::makeInstance (const std::string & name, Statement & , const Parser *) virtual inherited
Macro handler function.
Reimplemented in SequenceTemplate, MacroCmd, and LineTemplate.
Definition at line 76 of file Object.cpp.
References Object::getOpalName().
Referenced by OpalParser::parseDefine(), and OpalParser::parseMacro().
makeTemplate()
Object * Object::makeTemplate (const std::string & name, TokenStream & , Statement &) virtual inherited
Macro handler function.
Reimplemented in LineTemplate, Sequence, MacroCmd, SequenceTemplate, and Line.
Definition at line 71 of file Object.cpp.
Referenced by OpalParser::parseMacro().
occurrenceCount()
int Object::occurrenceCount () inherited
Return the occurrence counter.
Definition at line 289 of file Object.cpp.
References Object::occurrence.
parse()
void Object::parse (Statement & stat) virtual inherited
Parse the object.
Reimplemented in Call, Echo, Help, PSystem, System, Title, Value, OpalElement, Sequence, EmissionSourceList, and Line.
Definition at line 82 of file Object.cpp.
References Statement::delimiter(), Object::findAttribute(), Object::getOpalName(), Expressions::parseDelimiter(), Expressions::parseRealConst(), and Expressions::parseString().
Referenced by Sequence::parse(), OpalParser::parseAction(), OpalParser::parseDefine(), and SequenceTemplate::parseTemplate().
parseShortcut()
void Object::parseShortcut (Statement & stat, bool eval = true) virtual inherited
Parser for single-attribute commands.
Definition at line 113 of file Object.cpp.
Referenced by Call::parse(), Echo::parse(), Help::parse(), PSystem::parse(), System::parse(), Title::parse(), and Value::parse().
print()
void Object::print (std::ostream & msg) const virtual inherited
Print the object.
Reimplemented in OpalBend, OpalElement, OpalMarker, OpalMultipole, OpalQuadrupole, OpalRingDefinition, Sequence, TrackRun, BoolConstant, RealConstant, RealVariable, RealVector, StringConstant, OpalPolynomialTimeDependence, OpalSinusoidalTimeDependence, OpalSplineTimeDependence, Beam, OpalFilter, DumpEMFields, OpalMultipoleT, and Line.
Definition at line 146 of file Object.cpp.
References Object::getOpalName(), Object::getParent(), and Object::itsAttr.
Referenced by Object::printValue().
printHelp()
void Object::printHelp (std::ostream &) const virtual inherited
Print help.
Definition at line 179 of file Object.cpp.
References gmsg, Object::itsAttr, and Object::itsHelp.
Referenced by Help::execute().
printInfo()
Inform & FieldSolverCmd::printInfo (Inform & os) const inherited
Definition at line 185 of file FieldSolverCmd.cpp.
References FIELDSOLVER::BBOXINCR, FieldSolverCmd::fsName_m, FieldSolverCmd::getBinsName(), Attributes::getBool(), Object::getOpalName(), Attributes::getReal(), Attributes::getString(), FIELDSOLVER::GREENSF, Object::itsAttr, FIELDSOLVER::NX, FIELDSOLVER::NY, FIELDSOLVER::NZ, FIELDSOLVER::PARFFTX, FIELDSOLVER::PARFFTY, and FIELDSOLVER::PARFFTZ.
Referenced by operator<<().
printValue()
void Object::printValue (std::ostream & os) const inline virtual inherited
Reimplemented in BoolConstant, RealConstant, RealVariable, RealVector, and StringConstant.
Definition at line 270 of file Object.h.
References Object::print().
registerOwnership()
void Object::registerOwnership (const AttributeHandler::OwnerType & itsClass) const inherited
Definition at line 169 of file Object.cpp.
References AttributeHandler::addAttributeOwner(), Object::getOpalName(), Object::getParent(), and Object::itsAttr.
Referenced by Beam::Beam(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), Call::Call(), Distribution::Distribution(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), EmissionSourceList::EmissionSourceList(), Help::Help(), Line::Line(), OpalFilter::OpalFilter(), Option::Option(), PSystem::PSystem(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVector::RealVector(), Select::Select(), Sequence::Sequence(), StringConstant::StringConstant(), System::System(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), and Value::Value().
registerReference()
void Object::registerReference (Invalidator * a) inherited
Register a reference to this object.
Definition at line 165 of file Object.cpp.
References Object::references.
replace()
void Object::replace (Object * oldObject, Object * newObject) virtual inherited
Replace references.
Reimplemented in Line, and Sequence.
Definition at line 235 of file Object.cpp.
setBCX()
void SolenoidPlacementTest::TestableFieldSolverCmd::setBCX (const std::string & bc) inline
Definition at line 64 of file TestSolenoid.cpp.
References FIELDSOLVER::BCFFTX, Object::itsAttr, and Attributes::setPredefinedString().
setBCY()
void SolenoidPlacementTest::TestableFieldSolverCmd::setBCY (const std::string & bc) inline
Definition at line 68 of file TestSolenoid.cpp.
References FIELDSOLVER::BCFFTY, Object::itsAttr, and Attributes::setPredefinedString().
setBCZ()
void SolenoidPlacementTest::TestableFieldSolverCmd::setBCZ (const std::string & bc) inline
Definition at line 72 of file TestSolenoid.cpp.
References FIELDSOLVER::BCFFTZ, Object::itsAttr, and Attributes::setPredefinedString().
setDirty()
void Object::setDirty (bool dirty) inherited
Set/reset the [b]modified[/b] flag.
Definition at line 249 of file Object.cpp.
References Object::modified.
Referenced by OpalData::define(), OpalData::makeDirty(), and RealVariable::RealVariable().
setFieldSolverCmdType()
void FieldSolverCmd::setFieldSolverCmdType () inherited
Definition at line 157 of file FieldSolverCmd.cpp.
References CG, FFT, FieldSolverCmd::fsName_m, FieldSolverCmd::fsType_m, FieldSolverCmd::getType(), NONE, and OPEN.
Referenced by FieldSolverCmd::execute().
setFlag()
void Object::setFlag (bool flag) inherited
Flag/unflag this object, e. g. to control output of objects for.
Definition at line 256 of file Object.cpp.
References Object::flagged.
setNX()
void FieldSolverCmd::setNX (double value) inherited
Definition at line 141 of file FieldSolverCmd.cpp.
References Object::itsAttr, FIELDSOLVER::NX, and Attributes::setReal().
setNY()
void FieldSolverCmd::setNY (double value) inherited
Definition at line 143 of file FieldSolverCmd.cpp.
References Object::itsAttr, FIELDSOLVER::NY, and Attributes::setReal().
setNZ()
void FieldSolverCmd::setNZ (double value) inherited
Definition at line 145 of file FieldSolverCmd.cpp.
References Object::itsAttr, FIELDSOLVER::NZ, and Attributes::setReal().
setOpalName()
void Object::setOpalName (const std::string & name) inherited
Set object name.
Definition at line 281 of file Object.cpp.
References Object::itsName.
Referenced by TEST(), TEST(), TEST(), Beam::update(), BoundaryGeometry::update(), and OpalFilter::update().
setParent()
void Object::setParent (Object * parent) inherited
Set parent object.
Definition at line 283 of file Object.cpp.
References Object::itsParent.
Referenced by OpalData::erase().
setShared()
void Object::setShared (bool flag) virtual inherited
Set/reset shared flag.
Reimplemented in Element.
Definition at line 247 of file Object.cpp.
References Object::sharedFlag.
Referenced by OpalParser::parseDefine(), and Element::setShared().
setType()
void SolenoidPlacementTest::TestableFieldSolverCmd::setType (const std::string & t) inline
Definition at line 60 of file TestSolenoid.cpp.
References Object::itsAttr, Attributes::setPredefinedString(), and FIELDSOLVER::TYPE.
shouldTrace()
bool Definition::shouldTrace () const virtual inherited
Trace flag.
Implements Object.
Definition at line 28 of file Definition.cpp.
shouldUpdate()
bool Definition::shouldUpdate () const virtual inherited
Update flag.
Implements Object.
Definition at line 30 of file Definition.cpp.
unregisterReference()
void Object::unregisterReference (Invalidator * a) inherited
Unegister a reference to this object.
Definition at line 167 of file Object.cpp.
References Object::references.
update()
void FieldSolverCmd::update () virtual inherited
Update the field solver data.
Reimplemented from Object.
Definition at line 151 of file FieldSolverCmd.cpp.
References FieldSolverCmd::fsName_m, FieldSolverCmd::getType(), Object::itsAttr, and FIELDSOLVER::TYPE.
Referenced by FieldSolverCmd::execute().
Member Data Documentation
builtin
bool Object::builtin protected inherited
Built-in flag.
Definition at line 226 of file Object.h.
Referenced by Beam::Beam(), BoundaryGeometry::BoundaryGeometry(), Object::isBuiltin(), Object::Object(), Object::Object(), OpalFilter::OpalFilter(), OpalMarker::OpalMarker(), RealConstant::RealConstant(), StringConstant::StringConstant(), and Table::~Table().
flagged
bool Object::flagged protected inherited
Object flag.
Definition at line 235 of file Object.h.
Referenced by Object::isFlagged(), Object::Object(), Object::Object(), and Object::setFlag().
fsName_m
std::string FieldSolverCmd::fsName_m private inherited
Definition at line 117 of file FieldSolverCmd.h.
Referenced by FieldSolverCmd::printInfo(), FieldSolverCmd::setFieldSolverCmdType(), and FieldSolverCmd::update().
fsType_m
FieldSolverCmdType FieldSolverCmd::fsType_m private inherited
Definition at line 118 of file FieldSolverCmd.h.
Referenced by FieldSolverCmd::getFieldSolverCmdType(), and FieldSolverCmd::setFieldSolverCmdType().
itsAttr
std::vector<Attribute> Object::itsAttr inherited
The object attributes.
Definition at line 210 of file Object.h.
Referenced by Beam::Beam(), BinningCmd::BinningCmd(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), BoundaryGeometry::BoundaryGeometry(), DumpEMFields::buildGrid(), Call::Call(), FieldSolverCmd::constructBCHandler(), Object::copyAttributes(), Distribution::Distribution(), BinningCmd::dumpBinsToFile(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), Call::execute(), Echo::execute(), Help::execute(), Option::execute(), PSystem::execute(), Select::execute(), System::execute(), Title::execute(), Value::execute(), Beam::execute(), TrackCmd::execute(), TrackRun::execute(), FieldSolverCmd::FieldSolverCmd(), Object::findAttribute(), Object::findAttribute(), BoundaryGeometry::getA(), OpalElement::getApert(), BoundaryGeometry::getB(), BinningCmd::getBinningAlpha(), BinningCmd::getBinningBeta(), FieldSolverCmd::getBinsName(), BoolConstant::getBool(), FieldSolverCmd::getBoxIncr(), Beam::getBunchCharge(), BoundaryGeometry::getC(), Beam::getCharge(), Beam::getCurrent(), Beam::getDaughterBeamName(), BinningCmd::getDesiredWidth(), EmissionSource::getDistributionName(), FieldSolverCmd::getDomDec(), TrackCmd::getDT(), TrackCmd::getDTAU(), TrackCmd::getDTSCINIT(), BinningCmd::getDumpBinsFileName(), BinningCmd::getDumpBinsFrequency(), EmissionSource::getEmissionModel(), Beam::getEmissionSourceListName(), Distribution::getFilename(), BoundaryGeometry::getFilename(), Beam::getFrequency(), Beam::getGlobalProcessNames(), BoundaryGeometry::getL1(), BoundaryGeometry::getL2(), BoundaryGeometry::getLength(), OpalElement::getLength(), Line::getLength(), Sequence::getLength(), Beam::getMass(), BinningCmd::getMaxBins(), TrackCmd::getMaxSteps(), Beam::getNumAlloc(), FieldSolverCmd::getNX(), FieldSolverCmd::getNY(), FieldSolverCmd::getNZ(), EmissionSource::getP0(), BinningCmd::getParameter(), Beam::getParticleName(), EmissionSource::getR0(), RealConstant::getReal(), RealVariable::getReal(), RealVector::getRealComponent(), Sequence::getReference(), BoundaryGeometry::getS(), EmissionSource::getShiftedGreensFunction(), TrackCmd::getStepsPerTurn(), StringConstant::getString(), EmissionSource::getT0(), TrackCmd::getT0(), BinningCmd::getTablePrintFrequency(), TrackCmd::getTimeIntegrator(), BoundaryGeometry::getTopology(), FieldSolverCmd::getType(), EmissionSource::getZerofaceMaxSteps(), EmissionSource::getZeroFacePlaneDumpFrequency(), EmissionSource::getZeroFaceR0Z(), TrackCmd::getZStart(), TrackCmd::getZStop(), Beam::hasExplicitEnergy(), Help::Help(), BoundaryGeometry::initialize(), OpalFilter::initOpalFilter(), Beam::isPhoton(), Line::Line(), OpalBend::OpalBend(), OpalCavity::OpalCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalDrift::OpalDrift(), OpalElement::OpalElement(), OpalFilter::OpalFilter(), OpalLaser::OpalLaser(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalPolynomialTimeDependence::OpalPolynomialTimeDependence(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalRingDefinition::OpalRingDefinition(), OpalSinusoidalTimeDependence::OpalSinusoidalTimeDependence(), OpalSolenoid::OpalSolenoid(), OpalSplineTimeDependence::OpalSplineTimeDependence(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), Option::Option(), Option::Option(), Sequence::parse(), Line::parse(), DumpEMFields::parseCoordinateSystem(), Object::print(), Sequence::print(), BoolConstant::print(), RealConstant::print(), RealVariable::print(), RealVector::print(), StringConstant::print(), Beam::print(), OpalFilter::print(), DumpEMFields::print(), Object::printHelp(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), BoolConstant::printValue(), RealConstant::printValue(), RealVariable::printValue(), RealVector::printValue(), StringConstant::printValue(), PSystem::PSystem(), RealConstant::RealConstant(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVariable::RealVariable(), RealVector::RealVector(), OpalElement::registerOwnership(), Object::registerOwnership(), Select::Select(), Select::select(), Sequence::Sequence(), Distribution::setAttributes(), TestMultipoleT::TestableFieldSolverCmd::setBCX(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCX(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCX(), setBCX(), TestVariableRFCavity::TestableFieldSolverCmd::setBCX(), OrbitThreaderTest::TestableFieldSolverCmd::setBCX(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCX(), TestMultipoleT::TestableFieldSolverCmd::setBCY(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCY(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCY(), setBCY(), TestVariableRFCavity::TestableFieldSolverCmd::setBCY(), OrbitThreaderTest::TestableFieldSolverCmd::setBCY(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCY(), TestMultipoleT::TestableFieldSolverCmd::setBCZ(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCZ(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCZ(), setBCZ(), TestVariableRFCavity::TestableFieldSolverCmd::setBCZ(), OrbitThreaderTest::TestableFieldSolverCmd::setBCZ(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCZ(), TestableBinningCmd::setBinningAlpha(), TestableBinningCmd::setBinningBeta(), TestableBinningCmd::setDesiredWidth(), Distribution::setDistParametersFlatTop(), Distribution::setDistParametersMultiVariateGauss(), Distribution::setDistType(), TestableBinningCmd::setDumpBinsFile(), TestableBinningCmd::setDumpBinsFreq(), TestableBinningCmd::setMaxBins(), FieldSolverCmd::setNX(), FieldSolverCmd::setNY(), FieldSolverCmd::setNZ(), TestableBinningCmd::setParameterString(), TrackRun::setRunMethod(), Distribution::setSigmaP_m(), Distribution::setSigmaR_m(), TestableBinningCmd::setTablePrintFrequency(), TestMultipoleT::TestableFieldSolverCmd::setType(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setType(), TestMultipoleTStraight::TestableFieldSolverCmd::setType(), setType(), TestVariableRFCavity::TestableFieldSolverCmd::setType(), OrbitThreaderTest::TestableFieldSolverCmd::setType(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setType(), TrackRun::setupBoundaryGeometry(), StringConstant::StringConstant(), StringConstant::StringConstant(), System::System(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), OpalCavity::update(), OpalConstantEFieldCavity::update(), OpalDrift::update(), OpalElement::update(), OpalMonitor::update(), OpalMultipole::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalRBend::update(), OpalRingDefinition::update(), OpalSBend::update(), OpalSolenoid::update(), OpalTravelingWave::update(), OpalVacuum::update(), OpalVerticalFFAMagnet::update(), Beam::update(), BinningCmd::update(), FieldSolverCmd::update(), OpalLaser::update(), OpalMultipoleT::update(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), OpalSplineTimeDependence::update(), OpalVariableRFCavity::update(), Option::update(), OpalElement::updateUnknown(), ValueDefinition::value(), Value::Value(), and ValueDefinition::value().
itsHelp
std::string Object::itsHelp private inherited
Definition at line 250 of file Object.h.
Referenced by Object::printHelp().
itsName
std::string Object::itsName private inherited
Definition at line 247 of file Object.h.
Referenced by Object::getOpalName(), and Object::setOpalName().
itsParent
Object* Object::itsParent private inherited
Definition at line 244 of file Object.h.
Referenced by Object::getBaseObject(), Object::getParent(), Object::isTreeMember(), and Object::setParent().
modified
bool Object::modified protected inherited
Dirty flag.
Definition at line 231 of file Object.h.
Referenced by Object::isDirty(), Object::Object(), Object::Object(), and Object::setDirty().
occurrence
int Object::occurrence private inherited
Definition at line 253 of file Object.h.
Referenced by Object::clear(), Object::increment(), and Object::occurrenceCount().
references
std::set<Invalidator*> Object::references private inherited
Definition at line 260 of file Object.h.
Referenced by Object::registerReference(), Object::unregisterReference(), and Object::~Object().
sharedFlag
bool Object::sharedFlag private inherited
Definition at line 263 of file Object.h.
Referenced by Object::isShared(), and Object::setShared().
timeStamp
double Object::timeStamp private inherited
Definition at line 256 of file Object.h.
The documentation for this class was generated from the following file:
TestSolenoid.cpp