OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions::SAutomatic< T > Class Template Reference
Expressions::SAutomatic< T > Class Template Reference
Object attribute with an `‘automatic’' scalar value.
#include <SAutomatic.h>
Public Member Functions
SAutomatic (PtrToScalar< T > expr)
Constructor.
SAutomatic (const SAutomatic< T > &)
virtual ~SAutomatic ()
virtual SAutomatic< T > * clone () const
Make clone.
virtual T evaluate ()
Evaluate.
virtual void invalidate ()
Invalidate.
virtual bool isExpression () const
Return expression flag.
virtual void print (std::ostream &) const
Print the attribute value.
std::string getImage () const
Convert to string.
Protected Attributes
PtrToScalar< T > expr_ptr
Pointer to expression.
T value
The value of the attribute.
Private Member Functions
SAutomatic ()
void operator= (const SAutomatic< T > &)
Private Attributes
bool is_known
bool in_evaluation
Detailed Description
template<class T>
class Expressions::SAutomatic< T >
Object attribute with an `‘automatic’' scalar value.
Definition at line 38 of file SAutomatic.h.
Constructor & Destructor Documentation
SAutomatic() [1/3]
template<class T> Expressions::SAutomatic< T >::SAutomatic (PtrToScalar< T > expr) explicit
Constructor.
Definition at line 76 of file SAutomatic.h.
References OpalData::getInstance(), is_known, OpalData::registerExpression(), and Expressions::SDeferred< T >::SDeferred().
Referenced by clone(), operator=(), and SAutomatic().
SAutomatic() [2/3]
template<class T> Expressions::SAutomatic< T >::SAutomatic (const SAutomatic< T > & rhs)
Definition at line 71 of file SAutomatic.h.
References OpalData::getInstance(), is_known, OpalData::registerExpression(), SAutomatic(), and Expressions::SDeferred< T >::SDeferred().
~SAutomatic()
template<class T> Expressions::SAutomatic< T >::~SAutomatic () virtual
Definition at line 81 of file SAutomatic.h.
References OpalData::getInstance(), and OpalData::unregisterExpression().
SAutomatic() [3/3]
template<class T> Expressions::SAutomatic< T >::SAutomatic () private
Member Function Documentation
clone()
template<class T> SAutomatic< T > * Expressions::SAutomatic< T >::clone () const virtual
Make clone.
Reimplemented from Expressions::SDeferred< T >.
Definition at line 87 of file SAutomatic.h.
References SAutomatic().
evaluate()
template<class T> T Expressions::SAutomatic< T >::evaluate () virtual
Evaluate.
Reimplemented from Expressions::SDeferred< T >.
Definition at line 92 of file SAutomatic.h.
References Expressions::SDeferred< T >::evaluate(), is_known, and Expressions::SValue< T >::value.
getImage()
std::string AttributeBase::getImage () const inherited
Convert to string.
Definition at line 29 of file AttributeBase.cpp.
References print().
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), and Expressions::SRefAttr< T >::evaluate().
invalidate()
template<class T> void Expressions::SAutomatic< T >::invalidate () virtual
Invalidate.
Reimplemented from Invalidator.
Definition at line 102 of file SAutomatic.h.
References is_known.
isExpression()
template<class T> bool Expressions::SDeferred< T >::isExpression () const virtual inherited
Return expression flag.
Reimplemented from AttributeBase.
Definition at line 125 of file SDeferred.h.
operator=()
template<class T> void Expressions::SAutomatic< T >::operator= (const SAutomatic< T > &) private
References SAutomatic().
print()
template<class T> void Expressions::SDeferred< T >::print (std::ostream & stream) const virtual inherited
Print the attribute value.
Reimplemented from Expressions::SValue< T >.
Definition at line 130 of file SDeferred.h.
References expr_ptr.
Member Data Documentation
expr_ptr
template<class T> PtrToScalar<T> Expressions::SDeferred< T >::expr_ptr protected inherited
Pointer to expression.
Definition at line 64 of file SDeferred.h.
Referenced by evaluate(), print(), SDeferred(), and SDeferred().
in_evaluation
template<class T> bool Expressions::SDeferred< T >::in_evaluation mutable private inherited
Definition at line 72 of file SDeferred.h.
Referenced by evaluate(), SDeferred(), and SDeferred().
is_known
template<class T> bool Expressions::SAutomatic< T >::is_known mutable private
Definition at line 64 of file SAutomatic.h.
Referenced by evaluate(), invalidate(), SAutomatic(), and SAutomatic().
value
template<class T> T Expressions::SValue< T >::value mutable protected inherited
The value of the attribute.
Definition at line 59 of file SValue.h.
Referenced by clone(), Expressions::SAutomatic< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), evaluate(), print(), print(), SValue(), SValue(), and SValue().
The documentation for this class was generated from the following file:
SAutomatic.h