OPALX (Object Oriented Parallel Accelerator Library for Exascal): Parser Class Reference
Parser Class Reference abstract
Interface for abstract language parser.
#include <Parser.h>
Public Member Functions
Parser ()
virtual ~Parser ()
virtual void parse (Statement &stat) const =0
Parse and execute the statement.
virtual Statement * readStatement (TokenStream *ts) const =0
Read complete statement from token stream.
virtual void run (TokenStream *ts) const =0
Read statements and parse.
Private Member Functions
Parser (const Parser &)
void operator= (const Parser &)
Detailed Description
Interface for abstract language parser.
Definition at line 30 of file Parser.h.
Constructor & Destructor Documentation
Parser() [1/2]
Parser::Parser () inline
Definition at line 51 of file Parser.h.
Referenced by operator=(), and Parser().
~Parser()
Parser::~Parser () inline virtual
Definition at line 53 of file Parser.h.
Parser() [2/2]
Parser::Parser (const Parser &) private
References Parser().
Member Function Documentation
operator=()
void Parser::operator= (const Parser &) private
References Parser().
parse()
virtual void Parser::parse (Statement & stat) const pure virtual
Parse and execute the statement.
Implemented in OpalParser, and SequenceParser.
Referenced by SimpleStatement::execute().
readStatement()
virtual Statement * Parser::readStatement (TokenStream * ts) const pure virtual
Read complete statement from token stream.
Implemented in OpalParser.
Referenced by IfStatement::IfStatement(), and WhileStatement::WhileStatement().
run()
virtual void Parser::run (TokenStream * ts) const pure virtual
Read statements and parse.
Implemented in OpalParser.
Referenced by CompoundStatement::execute().
The documentation for this class was generated from the following file:
Parser.h