OPALX (Object Oriented Parallel Accelerator Library for Exascal): SFunction Class Reference
SFunction Class Reference
Functions of arc length.
#include <SFunction.h>
Public Member Functions
SFunction ()
Default constructor.
~SFunction ()
Destructor.
void reset ()
Reset the arc length to zero.
void update (double length)
Advance position by element length.
Static Public Member Functions
static double arcIn ()
Return arc length at entrance SI().
static double arcCtr ()
Return arc length at center SC().
static double arcOut ()
Return arc length at exit SO().
Private Member Functions
SFunction (const SFunction &)
void operator= (const SFunction &)
double position (double flag) const
Private Attributes
double elementLength
double exitArc
Static Private Attributes
static const SFunction * sfun = 0
Detailed Description
Functions of arc length.
Definition at line 30 of file SFunction.h.
Constructor & Destructor Documentation
SFunction() [1/2]
SFunction::SFunction ()
Default constructor.
Definition at line 30 of file SFunction.cpp.
References reset(), and sfun.
~SFunction()
SFunction::~SFunction ()
Destructor.
Definition at line 35 of file SFunction.cpp.
References sfun.
SFunction() [2/2]
SFunction::SFunction (const SFunction &) private
Member Function Documentation
arcCtr()
double SFunction::arcCtr () static
Return arc length at center SC().
Definition at line 48 of file SFunction.cpp.
References position(), and sfun.
arcIn()
double SFunction::arcIn () static
Return arc length at entrance SI().
Definition at line 37 of file SFunction.cpp.
References position(), and sfun.
arcOut()
double SFunction::arcOut () static
Return arc length at exit SO().
Definition at line 59 of file SFunction.cpp.
References position(), and sfun.
operator=()
void SFunction::operator= (const SFunction &) private
position()
double SFunction::position (double flag) const private
Definition at line 80 of file SFunction.cpp.
References elementLength, and exitArc.
Referenced by arcCtr(), arcIn(), and arcOut().
reset()
void SFunction::reset ()
Reset the arc length to zero.
Definition at line 70 of file SFunction.cpp.
References elementLength, and exitArc.
Referenced by SFunction().
update()
void SFunction::update (double length)
Advance position by element length.
Definition at line 75 of file SFunction.cpp.
References elementLength, and exitArc.
Member Data Documentation
elementLength
double SFunction::elementLength private
Definition at line 66 of file SFunction.h.
Referenced by position(), reset(), and update().
exitArc
double SFunction::exitArc private
Definition at line 69 of file SFunction.h.
Referenced by position(), reset(), and update().
sfun
const SFunction * SFunction::sfun = 0 static private
Definition at line 73 of file SFunction.h.
Referenced by arcCtr(), arcIn(), arcOut(), SFunction(), and ~SFunction().
The documentation for this class was generated from the following files:
SFunction.h
SFunction.cpp