OPALX (Object Oriented Parallel Accelerator Library for Exascal): DummyField Class Reference
DummyField Class Reference
Public Member Functions
void scale (double) override
Scale the field.
virtual EVector Efield (const Point3D &P) const
Get field.
virtual EVector Efield (const Point3D &P, double t) const
Get field.
virtual BVector Bfield (const Point3D &P) const
Get field.
virtual BVector Bfield (const Point3D &P, double t) const
Get field.
virtual EBVectors EBfield (const Point3D &P) const
Get field.
virtual EBVectors EBfield (const Point3D &P, double t) const
Get field.
Static Public Attributes
static const EVector ZeroEfield
The constant representing a zero electric field.
static const BVector ZeroBfield
The constant representing a zero magnetic field.
static const EBVectors ZeroEBfield
The constant representing a zero electromagnetic field.
Detailed Description
Definition at line 133 of file TestRFCavity.cpp.
Member Function Documentation
Bfield() [1/2]
BVector EMField::Bfield (const Point3D & P) const virtual inherited
Get field.
Reimplemented in BDipoleField, BMultipoleField, ConstBzField, and OscillatingField< ConstEzField >.
Definition at line 121 of file EMField.cpp.
References ZeroBfield.
Referenced by Component::Bfield(), Component::Bfield(), Bfield(), and EBfield().
Bfield() [2/2]
BVector EMField::Bfield (const Point3D & P, double t) const virtual inherited
Get field.
Reimplemented in BDipoleField, BMultipoleField, ConstBzField, and OscillatingField< ConstEzField >.
Definition at line 125 of file EMField.cpp.
References Bfield().
EBfield() [1/2]
EBVectors EMField::EBfield (const Point3D & P) const virtual inherited
Get field.
Definition at line 127 of file EMField.cpp.
References Bfield(), and Efield().
Referenced by Component::EBfield(), Component::EBfield(), and EBfield().
EBfield() [2/2]
EBVectors EMField::EBfield (const Point3D & P, double t) const virtual inherited
Get field.
Definition at line 129 of file EMField.cpp.
References EBfield().
Efield() [1/2]
EVector EMField::Efield (const Point3D & P) const virtual inherited
Get field.
Reimplemented in ConstEzField, and OscillatingField< ConstEzField >.
Definition at line 119 of file EMField.cpp.
References ZeroEfield.
Referenced by EBfield(), Component::Efield(), Component::Efield(), and Efield().
Efield() [2/2]
EVector EMField::Efield (const Point3D & P, double t) const virtual inherited
Get field.
Reimplemented in ConstEzField, and OscillatingField< ConstEzField >.
Definition at line 123 of file EMField.cpp.
References Efield().
scale()
void DummyField::scale (double scalar) inline override virtual
Scale the field.
Implements EMField.
Definition at line 135 of file TestRFCavity.cpp.
Member Data Documentation
ZeroBfield
const BVector EMField::ZeroBfield static inherited
The constant representing a zero magnetic field.
Definition at line 220 of file EMField.h.
Referenced by Bfield().
ZeroEBfield
const EBVectors EMField::ZeroEBfield static inherited
The constant representing a zero electromagnetic field.
Definition at line 223 of file EMField.h.
ZeroEfield
const EVector EMField::ZeroEfield static inherited
The constant representing a zero electric field.
Definition at line 217 of file EMField.h.
Referenced by Efield().
The documentation for this class was generated from the following file:
TestRFCavity.cpp