OPALX (Object Oriented Parallel Accelerator Library for Exascal): FlaggedElmPtr Class Reference
FlaggedElmPtr Class Reference
A section of a beam line.
#include <FlaggedElmPtr.h>
Public Member Functions
FlaggedElmPtr (const ElmPtr &, bool reflected=false, bool selected=false)
Constructor.
FlaggedElmPtr (const FlaggedElmPtr &)
Copy constructor.
FlaggedElmPtr ()
virtual ~FlaggedElmPtr ()
virtual void accept (BeamlineVisitor &) const
Apply visitor.
int getCounter () const
Get clone counter.
bool getReflectionFlag () const
Get reflection flag.
bool getSelectionFlag () const
Get selection flag.
void setCounter (int) const
Set clone counter.
void setReflectionFlag (bool flag) const
Set reflection flag.
void setSelectionFlag (bool flag) const
Get selection flag.
ElementBase * getElement () const
Get the element pointer.
void setElement (ElementBase *)
Set the element pointer.
void setElement (std::shared_ptr< ElementBase > elem)
Protected Attributes
int itsCounter
Clone counter.
bool isReflected
The reflection flag.
bool isSelected
The selection flag.
std::shared_ptr< ElementBase > itsElement
Detailed Description
A section of a beam line.
Definition at line 35 of file FlaggedElmPtr.h.
Constructor & Destructor Documentation
FlaggedElmPtr() [1/3]
FlaggedElmPtr::FlaggedElmPtr (const ElmPtr & elem, bool reflected = false, bool selected = false) explicit
Constructor.
Definition at line 28 of file FlaggedElmPtr.cpp.
FlaggedElmPtr() [2/3]
FlaggedElmPtr::FlaggedElmPtr (const FlaggedElmPtr & rhs)
Copy constructor.
Definition at line 33 of file FlaggedElmPtr.cpp.
FlaggedElmPtr() [3/3]
FlaggedElmPtr::FlaggedElmPtr ()
Definition at line 31 of file FlaggedElmPtr.cpp.
~FlaggedElmPtr()
FlaggedElmPtr::~FlaggedElmPtr () virtual
Definition at line 39 of file FlaggedElmPtr.cpp.
Member Function Documentation
accept()
void FlaggedElmPtr::accept (BeamlineVisitor & v) const virtual
Apply visitor.
Reimplemented from ElmPtr.
Definition at line 41 of file FlaggedElmPtr.cpp.
References BeamlineVisitor::visitFlaggedElmPtr().
getCounter()
int FlaggedElmPtr::getCounter () const inline
Get clone counter.
Definition at line 90 of file FlaggedElmPtr.h.
References itsCounter.
Referenced by PlaceRep::enter(), and PlaceRep::leave().
getElement()
ElementBase * ElmPtr::getElement () const inline inherited
Get the element pointer.
Definition at line 56 of file ElmPtr.h.
References ElmPtr::itsElement.
Referenced by Sequence::copy(), PlaceRep::enter(), Selector::handleElement(), PlaceRep::leave(), Sequence::print(), SequenceMember::setLength(), SpecificElementVisitor< ELEM >::visitFlaggedElmPtr(), Replacer::visitFlaggedElmPtr(), RangeSelector::visitFlaggedElmPtr(), and DefaultVisitor::visitFlaggedElmPtr().
getReflectionFlag()
bool FlaggedElmPtr::getReflectionFlag () const inline
Get reflection flag.
Definition at line 92 of file FlaggedElmPtr.h.
References isReflected.
Referenced by Sequence::print(), and DefaultVisitor::visitFlaggedElmPtr().
getSelectionFlag()
bool FlaggedElmPtr::getSelectionFlag () const inline
Get selection flag.
Definition at line 94 of file FlaggedElmPtr.h.
References isSelected.
setCounter()
void FlaggedElmPtr::setCounter (int count) const inline
Set clone counter.
Definition at line 96 of file FlaggedElmPtr.h.
References itsCounter.
setElement() [1/2]
void ElmPtr::setElement (ElementBase * elem) inline inherited
Set the element pointer.
Definition at line 58 of file ElmPtr.h.
References ElmPtr::itsElement.
Referenced by Sequence::addEndMarkers(), Sequence::copy(), Sequence::insertDrifts(), and SequenceParser::parseMember().
setElement() [2/2]
void ElmPtr::setElement (std::shared_ptr< ElementBase > elem) inline inherited
Definition at line 74 of file ElmPtr.h.
References ElmPtr::itsElement.
setReflectionFlag()
void FlaggedElmPtr::setReflectionFlag (bool flag) const inline
Set reflection flag.
Definition at line 98 of file FlaggedElmPtr.h.
References isReflected.
Referenced by Line::parseList(), and SequenceParser::parseMember().
setSelectionFlag()
void FlaggedElmPtr::setSelectionFlag (bool flag) const inline
Get selection flag.
Definition at line 100 of file FlaggedElmPtr.h.
References isSelected.
Referenced by Selector::handleElement(), and Flagger::visitFlaggedElmPtr().
Member Data Documentation
isReflected
bool FlaggedElmPtr::isReflected mutable protected
The reflection flag.
Definition at line 82 of file FlaggedElmPtr.h.
Referenced by getReflectionFlag(), and setReflectionFlag().
isSelected
bool FlaggedElmPtr::isSelected mutable protected
The selection flag.
Definition at line 87 of file FlaggedElmPtr.h.
Referenced by getSelectionFlag(), and setSelectionFlag().
itsCounter
int FlaggedElmPtr::itsCounter mutable protected
Clone counter.
Definition at line 77 of file FlaggedElmPtr.h.
Referenced by getCounter(), and setCounter().
itsElement
std::shared_ptr<ElementBase> ElmPtr::itsElement protected inherited
Definition at line 53 of file ElmPtr.h.
Referenced by ElmPtr::accept(), ElmPtr::getElement(), ElmPtr::setElement(), and ElmPtr::setElement().
The documentation for this class was generated from the following files:
FlaggedElmPtr.h
FlaggedElmPtr.cpp