OPALX (Object Oriented Parallel Accelerator Library for Exascal): StatWriter Class Reference
StatWriter Class Reference
#include <StatWriter.h>
Public Types
typedef std::vector< std::pair< std::string, unsigned int > > losses_t
typedef std::pair< std::string, std::string > desc_t
typedef std::tuple< std::string, std::string, std::string > param_t
typedef std::pair< std::string, size_t > data_t
typedef std::tuple< std::string, std::string, std::string, std::string > cols_t
Public Member Functions
StatWriter (const std::string &fname, bool restart)
void write (PartBunch_t &beam, Vector_t< double, 3 > FDext[], const losses_t &losses=losses_t(), const double &azimuth=-1, const size_t npOutside=0, size_t particleContainerIndex=0)
Write statistical data.
virtual void write (const PartBunch_t &)
unsigned int rewindToSpos (double maxSpos)
delete the last 'numberOfLines' lines of the statistics file
void rewindLines (size_t numberOfLines)
delete the last 'numberOfLines' lines of the file 'fileName'
void replaceVersionString ()
double getLastValue (const std::string &column)
bool exists () const
Protected Member Functions
void addDescription (const std::string &text, const std::string &content)
template<typename T >
void addParameter (const std::string &name, const std::string &type, const std::string &desc, const T &value)
void addDefaultParameters ()
void addColumn (const std::string &name, const std::string &type, const std::string &unit, const std::string &desc)
void addInfo (const std::string &mode, const size_t &no_row_counts)
void writeRow ()
void open ()
void close ()
void writeHeader ()
Write SDDS header.
template<typename T >
std::string toString (const T &val)
bool hasColumns () const
Protected Attributes
std::string fname_m
std::ios_base::openmode mode_m
First write to the statistics output file.
SDDSColumnSet columns_m
Private Member Functions
void fillHeader (const losses_t &losses=losses_t(), const std::string &species="")
void writeDescription ()
void writeParameters ()
void writeColumns ()
void writeInfo ()
Private Attributes
std::ofstream os_m
std::string indent_m
desc_t desc_m
std::queue< param_t > params_m
std::queue< std::string > paramValues_m
data_t info_m
Static Private Attributes
static constexpr unsigned int precision_m = 15
Detailed Description
Definition at line 24 of file StatWriter.h.
Member Typedef Documentation
cols_t
typedef std::tuple<std::string, std::string, std::string, std::string> SDDSWriter::cols_t inherited
Definition at line 50 of file SDDSWriter.h.
data_t
typedef std::pair<std::string, size_t> SDDSWriter::data_t inherited
Definition at line 47 of file SDDSWriter.h.
desc_t
typedef std::pair<std::string, std::string> SDDSWriter::desc_t inherited
Definition at line 41 of file SDDSWriter.h.
losses_t
typedef std::vector<std::pair<std::string, unsigned int> > StatWriter::losses_t
Definition at line 26 of file StatWriter.h.
param_t
typedef std::tuple<std::string, std::string, std::string> SDDSWriter::param_t inherited
Definition at line 44 of file SDDSWriter.h.
Constructor & Destructor Documentation
StatWriter()
StatWriter::StatWriter (const std::string & fname, bool restart)
Definition at line 41 of file StatWriter.cpp.
Member Function Documentation
addColumn()
void SDDSWriter::addColumn (const std::string & name, const std::string & type, const std::string & unit, const std::string & desc) protected inherited
addDefaultParameters()
void SDDSWriter::addDefaultParameters () protected inherited
Definition at line 199 of file SDDSWriter.cpp.
References SDDSWriter::addParameter(), Util::getGitRevision(), and OpalData::getInstance().
Referenced by ElementPositionWriter::fillHeader(), LBalWriter::fillHeader(), MonitorStatisticsWriter::fillHeader(), and MemoryProfiler::header().
addDescription()
void SDDSWriter::addDescription (const std::string & text, const std::string & content) inline protected inherited
Definition at line 142 of file SDDSWriter.h.
References SDDSWriter::desc_m.
Referenced by ElementPositionWriter::fillHeader(), LBalWriter::fillHeader(), MonitorStatisticsWriter::fillHeader(), fillHeader(), and MemoryProfiler::header().
addInfo()
void SDDSWriter::addInfo (const std::string & mode, const size_t & no_row_counts) inline protected inherited
Definition at line 155 of file SDDSWriter.h.
References SDDSWriter::info_m.
Referenced by ElementPositionWriter::fillHeader(), LBalWriter::fillHeader(), MonitorStatisticsWriter::fillHeader(), fillHeader(), and MemoryProfiler::header().
addParameter()
template<typename T > void SDDSWriter::addParameter (const std::string & name, const std::string & type, const std::string & desc, const T & value) protected inherited
Definition at line 147 of file SDDSWriter.h.
References SDDSWriter::params_m, and SDDSWriter::paramValues_m.
Referenced by SDDSWriter::addDefaultParameters(), and fillHeader().
close()
void SDDSWriter::close () protected inherited
Definition at line 137 of file SDDSWriter.cpp.
References SDDSWriter::os_m.
Referenced by MonitorStatisticsWriter::addRow(), ElementPositionWriter::addRow(), LBalWriter::write(), MemoryProfiler::write(), and write().
exists()
bool SDDSWriter::exists () const inline inherited
Definition at line 138 of file SDDSWriter.h.
References SDDSWriter::fname_m.
fillHeader()
void StatWriter::fillHeader (const losses_t & losses = losses_t(), const std::string & species = "") private
Todo:
Options::computePercentiles needs to be brought back
Definition at line 44 of file StatWriter.cpp.
References SDDSColumnSet::addColumn(), SDDSWriter::addDescription(), SDDSWriter::addInfo(), SDDSWriter::addParameter(), SDDSWriter::columns_m, OPALTimer::Timer::date(), Util::getGitRevision(), OpalData::getInputFn(), OpalData::getInstance(), SDDSWriter::hasColumns(), SDDSWriter::mode_m, and OPALTimer::Timer::time().
Referenced by write().
getLastValue()
double SDDSWriter::getLastValue (const std::string & column) inherited
Definition at line 120 of file SDDSWriter.cpp.
References SDDSWriter::fname_m, SDDS::SDDSParser::getValue(), and SDDS::SDDSParser::run().
hasColumns()
bool SDDSWriter::hasColumns () const inline protected inherited
Definition at line 171 of file SDDSWriter.h.
References SDDSWriter::columns_m, and SDDSColumnSet::hasColumns().
Referenced by ElementPositionWriter::fillHeader(), LBalWriter::fillHeader(), MonitorStatisticsWriter::fillHeader(), fillHeader(), and MemoryProfiler::header().
open()
void SDDSWriter::open () protected inherited
Definition at line 128 of file SDDSWriter.cpp.
References SDDSWriter::fname_m, SDDSWriter::mode_m, SDDSWriter::os_m, and SDDSWriter::precision_m.
Referenced by MonitorStatisticsWriter::addRow(), ElementPositionWriter::addRow(), LBalWriter::write(), MemoryProfiler::write(), and write().
replaceVersionString()
void SDDSWriter::replaceVersionString () inherited
Definition at line 76 of file SDDSWriter.cpp.
References SDDSWriter::fname_m, Util::getGitRevision(), SDDS::SDDSParser::getParameterValue(), and SDDS::SDDSParser::run().
rewindLines()
void SDDSWriter::rewindLines (size_t numberOfLines) inherited
delete the last 'numberOfLines' lines of the file 'fileName'
Definition at line 45 of file SDDSWriter.cpp.
References SDDSWriter::fname_m.
rewindToSpos()
unsigned int StatBaseWriter::rewindToSpos (double maxSpos) inline inherited
delete the last 'numberOfLines' lines of the statistics file
Definition at line 37 of file StatBaseWriter.h.
References SDDSWriter::fname_m, and Util::rewindLinesSDDS().
toString()
template<typename T > std::string SDDSWriter::toString (const T & val) protected inherited
Definition at line 164 of file SDDSWriter.h.
References SDDSWriter::precision_m.
Referenced by MemoryProfiler::write().
write() [1/2]
virtual void SDDSWriter::write (const PartBunch_t &) inline virtual
Reimplemented from SDDSWriter.
Definition at line 56 of file SDDSWriter.h.
write() [2/2]
void StatWriter::write (PartBunch_t & beam, Vector_t< double, 3 > FDext[], const losses_t & losses = losses_t(), const double & azimuth = -1, const size_t npOutside = 0, size_t particleContainerIndex = 0)
Write statistical data.
Writes statistical beam data to proper output file. This is information such as RMS beam parameters etc.
Also gathers and writes load balancing data to load balance statistics file.
Parameters
beam The beam.
FDext The external E and B field for the head, reference and tail particles. The vector array has the following layout:
FDext[0] = B at head particle location (in x, y and z).
FDext[1] = E at head particle location (in x, y and z).
FDext[2] = B at reference particle location (in x, y and z).
FDext[3] = E at reference particle location (in x, y and z).
FDext[4] = B at tail particle location (in x, y, and z).
FDext[5] = E at tail particle location (in x, y, and z).
Definition at line 217 of file StatWriter.cpp.
References SDDSColumnSet::addColumnValue(), SDDSWriter::close(), SDDSWriter::columns_m, fillHeader(), PartBunch< T, Dim >::get_halo(), PartBunch< T, Dim >::get_rmsDensity(), PartBunch< T, Dim >::getCurrentNBins(), PartBunch< T, Dim >::getdT(), OpalData::getInstance(), PartBunch< T, Dim >::getParticleName(), PartBunch< T, Dim >::getT(), SDDSWriter::open(), Units::s2ns, SDDSWriter::writeHeader(), and SDDSWriter::writeRow().
writeColumns()
void SDDSWriter::writeColumns () private inherited
Definition at line 180 of file SDDSWriter.cpp.
References SDDSWriter::columns_m, SDDSWriter::indent_m, SDDSWriter::os_m, and SDDSColumnSet::writeHeader().
Referenced by SDDSWriter::writeHeader().
writeDescription()
void SDDSWriter::writeDescription () private inherited
Definition at line 158 of file SDDSWriter.cpp.
References SDDSWriter::desc_m, SDDSWriter::indent_m, and SDDSWriter::os_m.
Referenced by SDDSWriter::writeHeader().
writeHeader()
void SDDSWriter::writeHeader () protected inherited
Write SDDS header.
Writes the appropriate SDDS format header information, The SDDS tools can be used for plotting data.
Definition at line 143 of file SDDSWriter.cpp.
References SDDSWriter::mode_m, SDDSWriter::writeColumns(), SDDSWriter::writeDescription(), SDDSWriter::writeInfo(), and SDDSWriter::writeParameters().
Referenced by MonitorStatisticsWriter::addRow(), ElementPositionWriter::addRow(), LBalWriter::write(), MemoryProfiler::write(), and write().
writeInfo()
void SDDSWriter::writeInfo () private inherited
Definition at line 184 of file SDDSWriter.cpp.
References SDDSWriter::indent_m, SDDSWriter::info_m, SDDSWriter::os_m, and SDDSWriter::paramValues_m.
Referenced by SDDSWriter::writeHeader().
writeParameters()
void SDDSWriter::writeParameters () private inherited
Definition at line 166 of file SDDSWriter.cpp.
References SDDSWriter::indent_m, SDDSWriter::os_m, and SDDSWriter::params_m.
Referenced by SDDSWriter::writeHeader().
writeRow()
void SDDSWriter::writeRow () inline protected inherited
Definition at line 159 of file SDDSWriter.h.
References SDDSWriter::columns_m, SDDSWriter::os_m, and SDDSColumnSet::writeRow().
Referenced by MonitorStatisticsWriter::addRow(), ElementPositionWriter::addRow(), LBalWriter::write(), MemoryProfiler::write(), and write().
Member Data Documentation
columns_m
SDDSColumnSet SDDSWriter::columns_m protected inherited
Definition at line 110 of file SDDSWriter.h.
Referenced by MonitorStatisticsWriter::addRow(), ElementPositionWriter::addRow(), ElementPositionWriter::fillHeader(), LBalWriter::fillHeader(), MonitorStatisticsWriter::fillHeader(), fillHeader(), SDDSWriter::hasColumns(), MemoryProfiler::header(), LBalWriter::write(), MemoryProfiler::write(), write(), SDDSWriter::writeColumns(), and SDDSWriter::writeRow().
desc_m
desc_t SDDSWriter::desc_m private inherited
Definition at line 130 of file SDDSWriter.h.
Referenced by SDDSWriter::addDescription(), and SDDSWriter::writeDescription().
fname_m
std::string SDDSWriter::fname_m protected inherited
Definition at line 100 of file SDDSWriter.h.
Referenced by SDDSWriter::exists(), SDDSWriter::getLastValue(), SDDSWriter::open(), SDDSWriter::replaceVersionString(), SDDSWriter::rewindLines(), StatBaseWriter::rewindToSpos(), and SDDSWriter::SDDSWriter().
indent_m
std::string SDDSWriter::indent_m private inherited
Definition at line 128 of file SDDSWriter.h.
Referenced by SDDSWriter::writeColumns(), SDDSWriter::writeDescription(), SDDSWriter::writeInfo(), and SDDSWriter::writeParameters().
info_m
data_t SDDSWriter::info_m private inherited
Definition at line 133 of file SDDSWriter.h.
Referenced by SDDSWriter::addInfo(), and SDDSWriter::writeInfo().
mode_m
std::ios_base::openmode SDDSWriter::mode_m protected inherited
First write to the statistics output file.
Initially set to std::ios::out so that SDDS format header information is written to file during the first write call to the statistics output file. Variable is then reset to std::ios::app so that header information is only written once.
Definition at line 108 of file SDDSWriter.h.
Referenced by LBalWriter::fillHeader(), fillHeader(), MemoryProfiler::header(), SDDSWriter::open(), SDDSWriter::SDDSWriter(), and SDDSWriter::writeHeader().
os_m
std::ofstream SDDSWriter::os_m private inherited
Definition at line 126 of file SDDSWriter.h.
Referenced by SDDSWriter::close(), SDDSWriter::open(), SDDSWriter::writeColumns(), SDDSWriter::writeDescription(), SDDSWriter::writeInfo(), SDDSWriter::writeParameters(), and SDDSWriter::writeRow().
params_m
std::queue<param_t> SDDSWriter::params_m private inherited
Definition at line 131 of file SDDSWriter.h.
Referenced by SDDSWriter::addParameter(), and SDDSWriter::writeParameters().
paramValues_m
std::queue<std::string> SDDSWriter::paramValues_m private inherited
Definition at line 132 of file SDDSWriter.h.
Referenced by SDDSWriter::addParameter(), and SDDSWriter::writeInfo().
precision_m
constexpr unsigned int SDDSWriter::precision_m = 15 static constexpr private inherited
Definition at line 135 of file SDDSWriter.h.
Referenced by SDDSWriter::open(), and SDDSWriter::toString().
The documentation for this class was generated from the following files:
StatWriter.h
StatWriter.cpp