OPALX (Object Oriented Parallel Accelerator Library for Exascal): ArithmeticError Class Reference
ArithmeticError Class Reference
The abstract base class for all OPALX arithmetic exceptions.
#include <ArithmeticError.h>
Public Member Functions
virtual const std::string & what () const
Return the message string for the exception.
virtual const std::string & where () const
Return the name of the method or function which detected the exception.
Protected Member Functions
ArithmeticError (const std::string &meth, const std::string &msg)
The usual constructor.
ArithmeticError (const ArithmeticError &)
virtual ~ArithmeticError ()
Private Member Functions
ArithmeticError ()
Private Attributes
const std::string message
const std::string method
Detailed Description
The abstract base class for all OPALX arithmetic exceptions.
Definition at line 33 of file ArithmeticError.h.
Constructor & Destructor Documentation
ArithmeticError() [1/3]
ArithmeticError::ArithmeticError (const std::string & meth, const std::string & msg) protected
The usual constructor.
Definition at line 26 of file ArithmeticError.cpp.
References OpalException::OpalException().
Referenced by ArithmeticError(), CLRangeError::CLRangeError(), CLRangeError::CLRangeError(), ConvergenceError::ConvergenceError(), ConvergenceError::ConvergenceError(), DivideError::DivideError(), DivideError::DivideError(), DomainError::DomainError(), DomainError::DomainError(), OverflowError::OverflowError(), and OverflowError::OverflowError().
ArithmeticError() [2/3]
ArithmeticError::ArithmeticError (const ArithmeticError & rhs) protected
Definition at line 29 of file ArithmeticError.cpp.
References ArithmeticError(), and OpalException::OpalException().
~ArithmeticError()
ArithmeticError::~ArithmeticError () protected virtual
Definition at line 31 of file ArithmeticError.cpp.
ArithmeticError() [3/3]
ArithmeticError::ArithmeticError () private
Member Function Documentation
what()
const std::string & OpalException::what () const virtual inherited
Return the message string for the exception.
Definition at line 31 of file OpalException.cpp.
References message.
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), main(), OpalParser::readStatement(), OpalParser::run(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and TEST_F().
where()
const std::string & OpalException::where () const virtual inherited
Return the name of the method or function which detected the exception.
Definition at line 33 of file OpalException.cpp.
References method.
Referenced by Expressions::ADeferred< T >::evaluate(), Expressions::SDeferred< T >::evaluate(), main(), OpalParser::run(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and TEST_F().
Member Data Documentation
message
const std::string OpalException::message private inherited
Definition at line 56 of file OpalException.h.
Referenced by OpalException(), OpalException(), and what().
method
const std::string OpalException::method private inherited
Definition at line 57 of file OpalException.h.
Referenced by DivideError::DivideError(), OpalException(), OpalException(), and where().
The documentation for this class was generated from the following files:
ArithmeticError.h
ArithmeticError.cpp