OPALX (Object Oriented Parallel Accelerator Library for Exascal): RFCavity Class Reference
RFCavity Class Reference abstract
Interface for standing wave cavities.
#include <RFCavity.h>
Public Member Functions
RFCavity (const std::string &name)
Constructor with given name.
RFCavity ()
RFCavity (const RFCavity &)
virtual ~RFCavity ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to RFCavity.
virtual double getAmplitude () const =0
Get RF amplitude.
virtual double getFrequency () const =0
Get RF frequency.
void setFrequency (double freq)
virtual double getPhase () const =0
Get RF phase.
void dropFieldmaps ()
virtual void setFieldMapFN (const std::string &fmapfn)
Set the name of the field map.
virtual std::string getFieldMapFN () const
virtual void setAmplitudem (double vPeak)
virtual double getAmplitudem () const
virtual void setAmplitudeError (double vPeakError)
virtual double getAmplitudeError () const
virtual void setFrequencym (double freq)
virtual double getFrequencym () const
virtual void setPhasem (double phase)
virtual double getPhasem () const
double getPhasem (double t) const
virtual void setPhaseError (double phaseError)
virtual double getPhaseError () const
void setCavityType (const std::string &type)
CavityType getCavityType () const
std::string getCavityTypeString () const
virtual void setFast (bool fast)
virtual bool getFast () const
virtual void setAutophaseVeto (bool veto=true)
virtual bool getAutophaseVeto () const
virtual double getAutoPhaseEstimate (const double &E0, const double &t0, const double &q, const double &m)
virtual double getAutoPhaseEstimateFallback (double E0, double t0, double q, double m)
virtual std::pair< double, double > trackOnAxisParticle (const double &p0, const double &t0, const double &dt, const double &q, const double &mass, std::ofstream *out=nullptr)
virtual bool apply (const std::shared_ptr< ParticleContainer_t > &pc) override
Applies the Standing Wave RF Cavity field to all particles inside the RF cavity.
virtual bool apply (const size_t &i, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
Apply to particle i.
virtual bool apply (const Vector_t< double, 3 > &R, const Vector_t< double, 3 > &P, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
Apply to particle with position R and momentum P.
virtual bool applyToReferenceParticle (const Vector_t< double, 3 > &R, const Vector_t< double, 3 > &P, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
Apply to reference particle with position R and momemtum P.
virtual void initialise (PartBunch_t *bunch, double &startField, double &endField) override
virtual void initialise (PartBunch_t *bunch, std::shared_ptr< AbstractTimeDependence > freq_atd, std::shared_ptr< AbstractTimeDependence > ampl_atd, std::shared_ptr< AbstractTimeDependence > phase_atd)
virtual void finalise () override
virtual bool bends () const override
virtual void goOnline (const double &kineticEnergy) override
virtual void goOffline () override
virtual void setDesignEnergy (const double &ekin, bool changeable=true) override
virtual double getDesignEnergy () const override
void setRmin (double rmin)
virtual double getRmin () const
void setRmax (double rmax)
virtual double getRmax () const
void setAzimuth (double angle)
virtual double getAzimuth () const
void setPerpenDistance (double pdis)
virtual double getPerpenDistance () const
void setGapWidth (double gapwidth)
virtual double getGapWidth () const
void setPhi0 (double phi0)
virtual double getPhi0 () const
virtual double getCosAzimuth () const
virtual double getSinAzimuth () const
virtual double getCycFrequency () const
void getMomentaKick (const double normalRadius, double momentum[], const double t, const double dtCorrt, const int PID, const double restMass, const int chargenumber)
used in OPAL-cycl
double spline (double z, double *za)
virtual ElementType getType () const override
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const override
virtual bool isInside (const Vector_t< double, 3 > &r) const override
void setAmplitudeModel (std::shared_ptr< AbstractTimeDependence > time_dep)
void setAmplitudeModelName (std::string name)
std::string getAmplitudeModelName ()
void setPhaseModel (std::shared_ptr< AbstractTimeDependence > time_dep)
void setPhaseModelName (std::string name)
std::string getPhaseModelName ()
void setFrequencyModel (std::shared_ptr< AbstractTimeDependence > time_dep)
void setFrequencyModelName (std::string name)
std::string getFrequencyModelName ()
virtual double getElementLength () const override
Get design length.
virtual void getElementDimensions (double &begin, double &end) const override
virtual CoordinateSystemTrafo getEdgeToBegin () const override
virtual CoordinateSystemTrafo getEdgeToEnd () const override
virtual EMField & getField ()=0
Return field.
virtual const EMField & getField () const =0
Return field.
EVector Efield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool getPotential (const Vector_t< double, 3 > &, const double &, Vector_t< double, 3 > &, double &)
Calculate the four-potential at some position relative to the component.
virtual bool Online ()
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunch_t &bunch, const PartData &, bool revBeam, bool revTrack) const
Track a borrowed particle bunch through a non-standard component.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual BGeometryBase & getGeometry ()=0
Get geometry.
virtual const BGeometryBase & getGeometry () const =0
Get geometry.
virtual double getArcLength () const
Get arc length.
virtual void setElementLength (double length)
Set design length.
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * clone () const =0
Return clone.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Static Public Member Functions
static std::string getTypeString (ElementType type)
Protected Member Functions
bool isInsideTransverse (const Vector_t< double, 3 > &r) const
Protected Attributes
std::shared_ptr< AbstractTimeDependence > phaseTD_m
std::string phaseName_m
std::shared_ptr< AbstractTimeDependence > amplitudeTD_m
std::string amplitudeName_m
std::shared_ptr< AbstractTimeDependence > frequencyTD_m
std::string frequencyName_m
std::string filename_m
double scale_m
double scaleError_m
double phase_m
double phaseError_m
double frequency_m
bool fast_m
bool autophaseVeto_m
double designEnergy_m
Fieldmap * fieldmap_m
double startField_m
double exit_face_slope_m
PartBunch_t * RefPartBunch_m
bool online_m
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes
static const std::vector< double > defaultAperture_m
Private Member Functions
double getdE (const int &i, const std::vector< double > &t, const double &dz, const double &phi, const double &frequency, const std::vector< double > &F) const
double getdT (const int &i, const std::vector< double > &E, const double &dz, const double mass) const
double getdA (const int &i, const std::vector< double > &t, const double &dz, const double &frequency, const std::vector< double > &F) const
double getdB (const int &i, const std::vector< double > &t, const double &dz, const double &frequency, const std::vector< double > &F) const
void operator= (const RFCavity &)
Private Attributes
double endField_m
CavityType type_m
double rmin_m
double rmax_m
double angle_m
double sinAngle_m
double cosAngle_m
double pdis_m
double gapwidth_m
double phi0_m
std::unique_ptr< double[]> RNormal_m
std::unique_ptr< double[]> VrNormal_m
std::unique_ptr< double[]> DvDr_m
int num_points_m
std::string elementID
AttributeSet userAttribs
WakeFunction * wake_m
BoundaryGeometry * bgeometry_m
ParticleMatterInteractionHandler * parmatint_m
bool positionIsFixed
std::queue< std::pair< double, double > > actionRange_m
std::string outputfn_m
bool deleteOnTransverseExit_m = true
double elementPosition_m
ELEMEDGE attribute.
bool elemedgeSet_m
Static Private Attributes
static const BiMap< CavityType, std::string > bmCavityTypeString_s
static const std::map< ElementType, std::string > elementTypeToString_s
Detailed Description
Interface for standing wave cavities.
Class RFCavity defines the abstract interface for Standing Wave RF cavities.
SW: Standing Wave Cavity
Definition at line 34 of file RFCavity.h.
Constructor & Destructor Documentation
RFCavity() [1/3]
RFCavity::RFCavity (const std::string & name) explicit
Constructor with given name.
Definition at line 76 of file RFCavity.cpp.
RFCavity() [2/3]
RFCavity::RFCavity ()
Definition at line 38 of file RFCavity.cpp.
RFCavity() [3/3]
RFCavity::RFCavity (const RFCavity & right)
Definition at line 41 of file RFCavity.cpp.
~RFCavity()
RFCavity::~RFCavity () virtual
Definition at line 108 of file RFCavity.cpp.
Member Function Documentation
accept()
void RFCavity::accept (BeamlineVisitor & visitor) const override virtual
Apply visitor to RFCavity.
Implements ElementBase.
Reimplemented in TravelingWave.
Definition at line 111 of file RFCavity.cpp.
References BeamlineVisitor::visitRFCavity().
apply() [1/3]
bool RFCavity::apply (const size_t & i, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual
Apply to particle i.
Parameters
i Particle index
t Time
E Electric Field
B Magnetic Field
Returns
true if particle is out-of-bounds (lost), false otherwise
Reimplemented from Component.
Reimplemented in TravelingWave.
Definition at line 158 of file RFCavity.cpp.
References apply(), PartBunch< T, Dim >::R(), and Component::RefPartBunch_m.
apply() [2/3]
bool RFCavity::apply (const std::shared_ptr< ParticleContainer_t > & pc) override virtual
Applies the Standing Wave RF Cavity field to all particles inside the RF cavity.
Note
TODO: Check if getFieldstrength(R, tmpE, tmpB) returns 0 outside of RF cavity to skip if statement
Reimplemented from Component.
Reimplemented in TravelingWave.
Definition at line 123 of file RFCavity.cpp.
References fieldmap_m, frequency_m, PartBunch< T, Dim >::getdT(), getElementLength(), PartBunch< T, Dim >::getT(), phase_m, phaseError_m, Component::RefPartBunch_m, scale_m, scaleError_m, and startField_m.
Referenced by apply().
apply() [3/3]
bool RFCavity::apply (const Vector_t< double, 3 > & R, const Vector_t< double, 3 > & P, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual
Apply to particle with position R and momentum P.
Parameters
R Position
P Momentum
t Time
E Electric Field
B Magnetic Field
Returns
true if particle is out-of-bounds (lost), false otherwise
Reimplemented from Component.
Reimplemented in TravelingWave.
Definition at line 170 of file RFCavity.cpp.
References fieldmap_m, frequency_m, getElementLength(), Fieldmap::getFieldstrength(), ElementBase::getFlagDeleteOnTransverseExit(), phase_m, phaseError_m, scale_m, scaleError_m, and startField_m.
applyToReferenceParticle()
bool RFCavity::applyToReferenceParticle (const Vector_t< double, 3 > & R, const Vector_t< double, 3 > & P, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual
Apply to reference particle with position R and momemtum P.
Parameters
R Position
P Momentum
t Time
E Electric Field
B Magnetic Field
Returns
true if particle is out-of-bounds (lost), false otherwise
Reimplemented from Component.
Reimplemented in TravelingWave.
Definition at line 186 of file RFCavity.cpp.
References fieldmap_m, frequency_m, getElementLength(), Fieldmap::getFieldstrength(), phase_m, scale_m, and startField_m.
Referenced by trackOnAxisParticle().
bends()
bool RFCavity::bends () const override virtual
Implements Component.
Reimplemented in TravelingWave.
Definition at line 285 of file RFCavity.cpp.
Bfield() [1/2]
BVector Component::Bfield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 248 of file Component.h.
References EMField::Bfield(), and Component::getField().
Bfield() [2/2]
BVector Component::Bfield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 256 of file Component.h.
References EMField::Bfield(), and Component::getField().
clone()
virtual ElementBase * ElementBase::clone () const pure virtual inherited
Return clone.
Implemented in VerticalFFAMagnet, DriftRep, MarkerRep, MonitorRep, MultipoleRep, ProbeRep, RFCavityRep, SolenoidRep, TravelingWaveRep, TBeamline< T >, MultipoleT, Ring, ScalingFFAMagnet, VariableRFCavity, ConstantEFieldCavityRep, LaserRep, TestRFCavity, DummyBeamline, and TestTravelingWave.
Referenced by Ring::appendElement(), Sequence::copy(), ElementBase::copyStructure(), and RingSection::operator=().
copyStructure()
ElementBase * ElementBase::copyStructure () virtual inherited
Make a structural copy.
Reimplemented in TBeamline< T >.
Definition at line 205 of file ElementBase.cpp.
References ElementBase::clone(), and ElementBase::isSharable().
Referenced by Sequence::copy(), Line::parse(), SequenceParser::parseMember(), and Replacer::visitFlaggedElmPtr().
dropFieldmaps()
void RFCavity::dropFieldmaps () inline
Definition at line 310 of file RFCavity.h.
References fieldmap_m.
Referenced by OpalCavity::update().
EBfield() [1/2]
EBVectors Component::EBfield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 260 of file Component.h.
References EMField::EBfield(), and Component::getField().
EBfield() [2/2]
EBVectors Component::EBfield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 264 of file Component.h.
References EMField::EBfield(), and Component::getField().
Efield() [1/2]
EVector Component::Efield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 244 of file Component.h.
References EMField::Efield(), and Component::getField().
Efield() [2/2]
EVector Component::Efield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 252 of file Component.h.
References EMField::Efield(), and Component::getField().
finalise()
void RFCavity::finalise () override virtual
Implements Component.
Reimplemented in TravelingWave.
Definition at line 282 of file RFCavity.cpp.
fixPosition()
void ElementBase::fixPosition () inline inherited
Definition at line 523 of file ElementBase.h.
References ElementBase::positionIsFixed.
Referenced by OpalElement::update().
getAmplitude()
virtual double RFCavity::getAmplitude () const pure virtual
Get RF amplitude.
Implemented in RFCavityRep, TravelingWaveRep, TestRFCavity, TestTravelingWave, and TravelingWave.
getAmplitudeError()
double RFCavity::getAmplitudeError () const inline virtual
Definition at line 330 of file RFCavity.h.
References scaleError_m.
getAmplitudem()
double RFCavity::getAmplitudem () const inline virtual
Definition at line 322 of file RFCavity.h.
References scale_m.
Referenced by CavityAutophaser::getPhaseAtMaxEnergy().
getAmplitudeModelName()
std::string RFCavity::getAmplitudeModelName () inline
Definition at line 394 of file RFCavity.h.
References amplitudeName_m.
getAperture()
std::pair< ApertureType, std::vector< double > > ElementBase::getAperture () const inline inherited
Definition at line 502 of file ElementBase.h.
References ElementBase::aperture_m.
Referenced by MeshGenerator::add(), Solenoid::getSupportEnvelope(), and MeshGenerator::getTransverseSupport().
getArcLength()
double ElementBase::getArcLength () const inline virtual inherited
Get arc length.
Reimplemented in MarkerRep, and TBeamline< T >.
Definition at line 394 of file ElementBase.h.
References BGeometryBase::getArcLength(), and ElementBase::getGeometry().
Referenced by BeamlineGeometry::getArcLength(), and TBeamline< T >::getTransform().
getAttribute()
double ElementBase::getAttribute (const std::string & aKey) const virtual inherited
Get attribute value.
Definition at line 154 of file ElementBase.cpp.
References ElementBase::getConstChannel().
getAutoPhaseEstimate()
double RFCavity::getAutoPhaseEstimate (const double & E0, const double & t0, const double & q, const double & m) virtual
Reimplemented in TravelingWave.
Definition at line 571 of file RFCavity.cpp.
References Physics::c, Units::deg2rad, fieldmap_m, frequency_m, getAutoPhaseEstimateFallback(), Util::getBetaGamma(), getdA(), getdB(), getdE(), getdT(), Fieldmap::getOnaxisEz(), gsl_interp_accel_alloc(), gsl_interp_accel_free(), gsl_interp_cspline, gsl_spline_alloc(), gsl_spline_eval(), gsl_spline_free(), gsl_spline_init(), Physics::pi, Units::rad2deg, scale_m, and Physics::two_pi.
Referenced by CavityAutophaser::guessCavityPhase().
getAutoPhaseEstimateFallback()
double RFCavity::getAutoPhaseEstimateFallback (double E0, double t0, double q, double m) virtual
Definition at line 528 of file RFCavity.cpp.
References Util::getBetaGamma(), Util::getKineticEnergy(), getPhasem(), Physics::pi, Units::rad2deg, setPhasem(), trackOnAxisParticle(), and Physics::two_pi.
Referenced by getAutoPhaseEstimate().
getAutophaseVeto()
bool RFCavity::getAutophaseVeto () const inline virtual
Definition at line 382 of file RFCavity.h.
References autophaseVeto_m.
Referenced by ParallelTracker::autophaseCavities(), CavityAutophaser::getPhaseAtMaxEnergy(), CavityAutophaser::guessCavityPhase(), and CavityAutophaser::optimizeCavityPhase().
getAzimuth()
double RFCavity::getAzimuth () const virtual
Definition at line 333 of file RFCavity.cpp.
References angle_m.
getBoundaryGeometry()
BoundaryGeometry * ElementBase::getBoundaryGeometry () const inline virtual inherited
return the attached boundary geometrt object if there is any
Definition at line 458 of file ElementBase.h.
References ElementBase::bgeometry_m.
getBoundingBoxInLabCoords()
BoundingBox ElementBase::getBoundingBoxInLabCoords () const virtual inherited
Definition at line 273 of file ElementBase.cpp.
References ElementBase::aperture_m, ElementBase::csTrafoGlobal2Local_m, BoundingBox::getBoundingBox(), ElementBase::getEdgeToBegin(), ElementBase::getEdgeToEnd(), and CoordinateSystemTrafo::transformFrom().
getCavityType()
CavityType RFCavity::getCavityType () const inline
Definition at line 366 of file RFCavity.h.
References type_m.
getCavityTypeString()
std::string RFCavity::getCavityTypeString () const
Definition at line 366 of file RFCavity.cpp.
References bmCavityTypeString_s, BiMap< Left, Right >::left, and type_m.
getChannel()
Channel * ElementBase::getChannel (const std::string & aKey, bool create = false) virtual inherited
Construct a read/write channel.
Reimplemented in LaserRep, DriftRep, MonitorRep, MultipoleRep, ProbeRep, RFCavityRep, SolenoidRep, TravelingWaveRep, and ConstantEFieldCavityRep.
Definition at line 191 of file ElementBase.cpp.
References AttributeSet::getChannel(), and ElementBase::userAttribs.
Referenced by LaserRep::getChannel(), DriftRep::getChannel(), MonitorRep::getChannel(), MultipoleRep::getChannel(), ProbeRep::getChannel(), RFCavityRep::getChannel(), SolenoidRep::getChannel(), TravelingWaveRep::getChannel(), ConstantEFieldCavityRep::getChannel(), ElementBase::getConstChannel(), and ElementBase::setAttribute().
getConstChannel()
const ConstChannel * ElementBase::getConstChannel (const std::string & aKey) const virtual inherited
Construct a read-only channel.
Definition at line 195 of file ElementBase.cpp.
References ElementBase::getChannel().
Referenced by ElementBase::getAttribute(), and ElementBase::hasAttribute().
getCosAzimuth()
double RFCavity::getCosAzimuth () const virtual
Definition at line 341 of file RFCavity.cpp.
References cosAngle_m.
getCSTrafoGlobal2Local()
CoordinateSystemTrafo ElementBase::getCSTrafoGlobal2Local () const inline inherited
Definition at line 481 of file ElementBase.h.
References ElementBase::csTrafoGlobal2Local_m.
Referenced by MeshGenerator::add().
getCycFrequency()
double RFCavity::getCycFrequency () const virtual
Definition at line 385 of file RFCavity.cpp.
References frequency_m.
getdA()
double RFCavity::getdA (const int & i, const std::vector< double > & t, const double & dz, const double & frequency, const std::vector< double > & F) const inline private
Definition at line 282 of file RFCavity.h.
Referenced by getAutoPhaseEstimate().
getdB()
double RFCavity::getdB (const int & i, const std::vector< double > & t, const double & dz, const double & frequency, const std::vector< double > & F) const inline private
Definition at line 292 of file RFCavity.h.
Referenced by getAutoPhaseEstimate().
getdE()
double RFCavity::getdE (const int & i, const std::vector< double > & t, const double & dz, const double & phi, const double & frequency, const std::vector< double > & F) const inline private
Definition at line 245 of file RFCavity.h.
Referenced by getAutoPhaseEstimate().
getDesign()
const ElementBase & Component::getDesign () const virtual inherited
Return design element.
Definition at line 41 of file Component.cpp.
getDesignEnergy()
double RFCavity::getDesignEnergy () const inline override virtual
Reimplemented from Component.
Definition at line 306 of file RFCavity.h.
References designEnergy_m.
Referenced by OrbitThreader::getMaxDesignEnergy(), and CavityAutophaser::getPhaseAtMaxEnergy().
getDimensions()
void RFCavity::getDimensions (double & zBegin, double & zEnd) const override virtual
Implements Component.
Reimplemented in TravelingWave.
Definition at line 519 of file RFCavity.cpp.
References endField_m, and startField_m.
getdT()
double RFCavity::getdT (const int & i, const std::vector< double > & E, const double & dz, const double mass) const inline private
Definition at line 256 of file RFCavity.h.
References Physics::c.
Referenced by getAutoPhaseEstimate().
getEdgeToBegin()
CoordinateSystemTrafo RFCavity::getEdgeToBegin () const inline override virtual
Reimplemented from ElementBase.
Reimplemented in TravelingWave.
Definition at line 422 of file RFCavity.h.
References startField_m.
getEdgeToEnd()
CoordinateSystemTrafo RFCavity::getEdgeToEnd () const inline override virtual
Reimplemented from ElementBase.
Reimplemented in TravelingWave.
Definition at line 427 of file RFCavity.h.
References getElementLength(), and startField_m.
getElementDimensions()
void RFCavity::getElementDimensions (double & begin, double & end) const override virtual
Reimplemented from ElementBase.
Reimplemented in TravelingWave.
Definition at line 777 of file RFCavity.cpp.
References fieldmap_m, and Fieldmap::getFieldDimensions().
getElementLength()
double RFCavity::getElementLength () const override virtual
Get design length.
Reimplemented from ElementBase.
Reimplemented in TestTravelingWave.
Definition at line 766 of file RFCavity.cpp.
References fieldmap_m, ElementBase::getElementLength(), and Fieldmap::getFieldDimensions().
Referenced by apply(), TravelingWave::apply(), apply(), TravelingWave::apply(), applyToReferenceParticle(), TravelingWave::applyToReferenceParticle(), TravelingWave::getDimensions(), getEdgeToEnd(), TravelingWave::getEdgeToEnd(), TravelingWave::getElementDimensions(), and trackOnAxisParticle().
getElementPosition()
double ElementBase::getElementPosition () const inline inherited
Definition at line 555 of file ElementBase.h.
References ElementBase::elemedgeSet_m, ElementBase::elementPosition_m, and ElementBase::getName().
getEntrance()
double ElementBase::getEntrance () const inline virtual inherited
Get entrance position.
Reimplemented in TBeamline< T >.
Definition at line 410 of file ElementBase.h.
References BGeometryBase::getEntrance(), and ElementBase::getGeometry().
Referenced by BeamlineGeometry::getEntrance().
getEntranceFrame()
Euclid3D ElementBase::getEntranceFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 430 of file ElementBase.h.
References BGeometryBase::getEntranceFrame(), and ElementBase::getGeometry().
Referenced by BeamlineGeometry::getEntranceFrame().
getEntrancePatch()
Euclid3D ElementBase::getEntrancePatch () const inline virtual inherited
Get patch.
Definition at line 438 of file ElementBase.h.
References BGeometryBase::getEntrancePatch(), and ElementBase::getGeometry().
getExit()
double ElementBase::getExit () const inline virtual inherited
Get exit position.
Reimplemented in TBeamline< T >.
Definition at line 414 of file ElementBase.h.
References BGeometryBase::getExit(), and ElementBase::getGeometry().
Referenced by BeamlineGeometry::getExit().
getExitFrame()
Euclid3D ElementBase::getExitFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 434 of file ElementBase.h.
References BGeometryBase::getExitFrame(), and ElementBase::getGeometry().
Referenced by BeamlineGeometry::getExitFrame().
getExitPatch()
Euclid3D ElementBase::getExitPatch () const inline virtual inherited
Get patch.
Definition at line 442 of file ElementBase.h.
References BGeometryBase::getExitPatch(), and ElementBase::getGeometry().
getFast()
bool RFCavity::getFast () const inline virtual
Definition at line 374 of file RFCavity.h.
References fast_m.
getField() [1/2]
virtual const EMField & Component::getField () const pure virtual inherited
Return field.
Implemented in VerticalFFAMagnet, DriftRep, MarkerRep, MonitorRep, MultipoleRep, ProbeRep, RFCavityRep, SolenoidRep, TravelingWaveRep, Corrector, MultipoleT, Ring, ScalingFFAMagnet, VariableRFCavity, ConstantEFieldCavityRep, LaserRep, TestRFCavity, TestTravelingWave, and Multipole.
getField() [2/2]
virtual EMField & Component::getField () pure virtual inherited
Return field.
Implemented in VerticalFFAMagnet, DriftRep, MarkerRep, MonitorRep, MultipoleRep, ProbeRep, RFCavityRep, SolenoidRep, TravelingWaveRep, MultipoleT, Ring, ScalingFFAMagnet, VariableRFCavity, ConstantEFieldCavityRep, LaserRep, TestRFCavity, TestTravelingWave, Multipole, and Corrector.
Referenced by Component::Bfield(), Component::Bfield(), Component::EBfield(), Component::EBfield(), Component::Efield(), and Component::Efield().
getFieldMapFN()
std::string RFCavity::getFieldMapFN () const virtual
Definition at line 370 of file RFCavity.cpp.
References filename_m.
getFlagDeleteOnTransverseExit()
bool ElementBase::getFlagDeleteOnTransverseExit () const inline inherited
Definition at line 576 of file ElementBase.h.
References ElementBase::deleteOnTransverseExit_m.
Referenced by ConstantEFieldCavity::apply(), Multipole::apply(), Corrector::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), apply(), Solenoid::apply(), and TravelingWave::apply().
getFrequency()
virtual double RFCavity::getFrequency () const pure virtual
Get RF frequency.
Implemented in RFCavityRep, TravelingWaveRep, TestRFCavity, TestTravelingWave, and TravelingWave.
getFrequencym()
double RFCavity::getFrequencym () const inline virtual
Definition at line 342 of file RFCavity.h.
References frequency_m.
Referenced by CavityAutophaser::getPhaseAtMaxEnergy(), and CavityAutophaser::optimizeCavityPhase().
getFrequencyModelName()
std::string RFCavity::getFrequencyModelName () inline
Definition at line 418 of file RFCavity.h.
References frequencyName_m.
getGapWidth()
double RFCavity::getGapWidth () const virtual
Definition at line 349 of file RFCavity.cpp.
References gapwidth_m.
getGeometry() [1/2]
virtual const BGeometryBase & ElementBase::getGeometry () const pure virtual inherited
Get geometry.
Implemented in VerticalFFAMagnet, DriftRep, MarkerRep, MonitorRep, MultipoleRep, ProbeRep, RFCavityRep, SolenoidRep, TravelingWaveRep, TBeamline< T >, Corrector, MultipoleT, Ring, ScalingFFAMagnet, VariableRFCavity, ConstantEFieldCavityRep, LaserRep, TestRFCavity, DummyBeamline, TestTravelingWave, Monitor, and Multipole.
getGeometry() [2/2]
virtual BGeometryBase & ElementBase::getGeometry () pure virtual inherited
Get geometry.
Implemented in VerticalFFAMagnet, DriftRep, MarkerRep, MonitorRep, MultipoleRep, ProbeRep, RFCavityRep, SolenoidRep, TravelingWaveRep, TBeamline< T >, MultipoleT, Ring, ScalingFFAMagnet, VariableRFCavity, ConstantEFieldCavityRep, LaserRep, TestRFCavity, DummyBeamline, TestTravelingWave, Monitor, Multipole, and Corrector.
Referenced by Ring::appendElement(), ElementBase::getArcLength(), ElementBase::getElementLength(), ElementBase::getEntrance(), ElementBase::getEntranceFrame(), ElementBase::getEntrancePatch(), ElementBase::getExit(), ElementBase::getExitFrame(), ElementBase::getExitPatch(), ElementBase::getOrigin(), ElementBase::getTotalTransform(), ElementBase::getTransform(), ElementBase::getTransform(), and ElementBase::setElementLength().
getMisalignment() [1/2]
CoordinateSystemTrafo ElementBase::getMisalignment () const inline inherited
Definition at line 515 of file ElementBase.h.
References ElementBase::misalignment_m.
getMisalignment() [2/2]
void ElementBase::getMisalignment (double & x, double & y, double & s) const inherited
getMomentaKick()
void RFCavity::getMomentaKick (const double normalRadius, double momentum[], const double t, const double dtCorrt, const int PID, const double restMass, const int chargenumber)
used in OPAL-cycl
Is called from OPAL-cycl and can handle time dependent frequency, amplitude and phase
At the moment (test) only the frequency is time dependent
B field effects
Definition at line 399 of file RFCavity.cpp.
References Physics::c, cosAngle_m, Units::deg2rad, Units::eV2MeV, frequency_m, frequencyTD_m, gapwidth_m, ElementBase::getName(), gmsg, Units::mm2m, Units::MVpm2Vpm, Units::ns2s, phi0_m, Units::rad2deg, rmax_m, rmin_m, scale_m, sinAngle_m, spline(), and Physics::two_pi.
getName()
const std::string & ElementBase::getName () const virtual inherited
Get element name.
Definition at line 133 of file ElementBase.cpp.
References ElementBase::elementID.
Referenced by Ring::appendElement(), Probe::doGoOffline(), PlaceRep::enter(), ElementBase::getElementPosition(), getMomentaKick(), ElementBase::getOutputFN(), CavityAutophaser::getPhaseAtMaxEnergy(), Selector::handleElement(), Ring::initialise(), initialise(), Solenoid::initialise(), PlaceRep::leave(), VariableRFCavity::operator=(), Sequence::print(), TEST_F(), Component::trackBunch(), Component::trackMap(), Sequence::updateList(), ParallelTracker::updateRFElement(), and Replacer::visitFlaggedElmPtr().
getOrigin()
double ElementBase::getOrigin () const inline virtual inherited
Get origin position.
Reimplemented in TBeamline< T >.
Definition at line 406 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getOrigin().
Referenced by BeamlineGeometry::getOrigin().
getOutputFN()
std::string ElementBase::getOutputFN () const inherited
Get output filename.
Definition at line 145 of file ElementBase.cpp.
References ElementBase::getName(), and ElementBase::outputfn_m.
Referenced by Probe::doInitialise(), PluginElement::initialise(), and Monitor::initialise().
getParticleMatterInteraction()
ParticleMatterInteractionHandler * ElementBase::getParticleMatterInteraction () const inline virtual inherited
Definition at line 466 of file ElementBase.h.
References ElementBase::parmatint_m.
getPerpenDistance()
double RFCavity::getPerpenDistance () const virtual
Definition at line 345 of file RFCavity.cpp.
References pdis_m.
getPhase()
virtual double RFCavity::getPhase () const pure virtual
Get RF phase.
Implemented in RFCavityRep, TravelingWaveRep, TestRFCavity, TestTravelingWave, and TravelingWave.
getPhaseError()
double RFCavity::getPhaseError () const inline virtual
Definition at line 362 of file RFCavity.h.
References phaseError_m.
getPhasem() [1/2]
double RFCavity::getPhasem () const inline virtual
Definition at line 350 of file RFCavity.h.
References phase_m.
Referenced by getAutoPhaseEstimateFallback(), CavityAutophaser::getPhaseAtMaxEnergy(), CavityAutophaser::guessCavityPhase(), CavityAutophaser::optimizeCavityPhase(), and CavityAutophaser::track().
getPhasem() [2/2]
double RFCavity::getPhasem (double t) const inline
Definition at line 354 of file RFCavity.h.
References frequency_m, and phase_m.
getPhaseModelName()
std::string RFCavity::getPhaseModelName () inline
Definition at line 406 of file RFCavity.h.
References phaseName_m.
getPhi0()
double RFCavity::getPhi0 () const virtual
Definition at line 353 of file RFCavity.cpp.
References phi0_m.
getPotential()
virtual bool Component::getPotential (const Vector_t< double, 3 > & , const double & , Vector_t< double, 3 > & , double &) inline virtual inherited
Calculate the four-potential at some position relative to the component.
Parameters
R position in the local coordinate system of the component
t time
A filled with the calculated magnetic vector potential
phi filled with the calculated electric potential Note that any existing values in A and phi may be overwritten by this method.
Returns
true if particle is outside the field map, else false Default for component is to return false and make no change to A and phi
Definition at line 164 of file Component.h.
getRequiredNumberOfTimeSteps()
int ElementBase::getRequiredNumberOfTimeSteps () const inline virtual inherited
Reimplemented in Drift, Laser, Marker, and Monitor.
Definition at line 568 of file ElementBase.h.
getRmax()
double RFCavity::getRmax () const virtual
Definition at line 329 of file RFCavity.cpp.
References rmax_m.
getRmin()
double RFCavity::getRmin () const virtual
Definition at line 325 of file RFCavity.cpp.
References rmin_m.
getRotationAboutZ()
double ElementBase::getRotationAboutZ () const inline inherited
Definition at line 542 of file ElementBase.h.
References ElementBase::rotationZAxis_m.
getSinAzimuth()
double RFCavity::getSinAzimuth () const virtual
Definition at line 337 of file RFCavity.cpp.
References sinAngle_m.
getTotalTransform()
Euclid3D ElementBase::getTotalTransform () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 422 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getTotalTransform().
Referenced by BeamlineGeometry::getTotalTransform().
getTransform() [1/2]
Euclid3D ElementBase::getTransform (double fromS, double toS) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 418 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getTransform().
Referenced by BeamlineGeometry::getTransform(), TBeamline< T >::getTransform(), and BeamlineGeometry::getTransform().
getTransform() [2/2]
Euclid3D ElementBase::getTransform (double s) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 426 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getTransform().
getType()
ElementType RFCavity::getType () const override virtual
Get element type std::string.
Reimplemented from Component.
Reimplemented in TravelingWave.
Definition at line 524 of file RFCavity.cpp.
References RFCAVITY.
getTypeString() [1/2]
std::string ElementBase::getTypeString () const inline inherited
Definition at line 546 of file ElementBase.h.
References ElementBase::getType(), and ElementBase::getTypeString().
Referenced by ElementBase::getTypeString().
getTypeString() [2/2]
std::string ElementBase::getTypeString (ElementType type) static inherited
Definition at line 201 of file ElementBase.cpp.
References ElementBase::elementTypeToString_s.
getWake()
WakeFunction * ElementBase::getWake () const inline virtual inherited
return the attached wake object if there is any
Definition at line 450 of file ElementBase.h.
References ElementBase::wake_m.
goOffline()
void RFCavity::goOffline () override virtual
Reimplemented from Component.
Reimplemented in TravelingWave.
Definition at line 295 of file RFCavity.cpp.
References filename_m, and Component::online_m.
goOnline()
void RFCavity::goOnline (const double & kineticEnergy) override virtual
Reimplemented from Component.
Reimplemented in TravelingWave.
Definition at line 289 of file RFCavity.cpp.
References filename_m, and Component::online_m.
hasAttribute()
bool ElementBase::hasAttribute (const std::string & aKey) const virtual inherited
Test for existence of an attribute.
Definition at line 166 of file ElementBase.cpp.
References ElementBase::getConstChannel().
hasBoundaryGeometry()
bool ElementBase::hasBoundaryGeometry () const inline virtual inherited
Definition at line 462 of file ElementBase.h.
References ElementBase::bgeometry_m.
hasParticleMatterInteraction()
bool ElementBase::hasParticleMatterInteraction () const inline virtual inherited
Definition at line 470 of file ElementBase.h.
References ElementBase::parmatint_m.
hasWake()
bool ElementBase::hasWake () const inline virtual inherited
Definition at line 454 of file ElementBase.h.
References ElementBase::wake_m.
initialise() [1/2]
void RFCavity::initialise (PartBunch_t * bunch, double & startField, double & endField) override virtual
Implements Component.
Reimplemented in TravelingWave.
Definition at line 202 of file RFCavity.cpp.
References endField_m, fast_m, fieldmap_m, filename_m, frequency_m, Fieldmap::getFieldDimensions(), Fieldmap::getFrequency(), Fieldmap::getInfo(), ElementBase::getName(), gmsg, Units::Hz2MHz, Component::RefPartBunch_m, ElementBase::setElementLength(), startField_m, and Physics::two_pi.
Referenced by TravelingWave::initialise().
initialise() [2/2]
void RFCavity::initialise (PartBunch_t * bunch, std::shared_ptr< AbstractTimeDependence > freq_atd, std::shared_ptr< AbstractTimeDependence > ampl_atd, std::shared_ptr< AbstractTimeDependence > phase_atd) virtual
set the time dependent models
Reimplemented in TravelingWave.
Definition at line 242 of file RFCavity.cpp.
References angle_m, cosAngle_m, Units::deg2rad, DvDr_m, filename_m, frequencyName_m, PartBunch< T, Dim >::getTotalCharge(), gmsg, num_points_m, Component::RefPartBunch_m, RNormal_m, setAmplitudeModel(), setFrequencyModel(), setPhaseModel(), sinAngle_m, and VrNormal_m.
isElementPositionSet()
bool ElementBase::isElementPositionSet () const inline inherited
Definition at line 564 of file ElementBase.h.
References ElementBase::elemedgeSet_m.
isInside()
bool RFCavity::isInside (const Vector_t< double, 3 > & r) const override virtual
Reimplemented from ElementBase.
Reimplemented in TravelingWave.
Definition at line 758 of file RFCavity.cpp.
References fieldmap_m, Fieldmap::isInside(), and ElementBase::isInsideTransverse().
isInsideTransverse()
bool ElementBase::isInsideTransverse (const Vector_t< double, 3 > & r) const protected inherited
Definition at line 246 of file ElementBase.cpp.
References ElementBase::aperture_m, CONIC_ELLIPTICAL, CONIC_RECTANGULAR, ELLIPTICAL, ElementBase::getEdgeToBegin(), ElementBase::getElementLength(), RECTANGULAR, and CoordinateSystemTrafo::transformTo().
Referenced by ConstantEFieldCavity::apply(), Multipole::apply(), Component::apply(), Corrector::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), Component::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), ElementBase::isInside(), Monitor::isInside(), Multipole::isInside(), isInside(), Solenoid::isInside(), and TravelingWave::isInside().
isPositioned()
bool ElementBase::isPositioned () const inline inherited
Definition at line 527 of file ElementBase.h.
References ElementBase::positionIsFixed.
isSharable()
bool ElementBase::isSharable () const inline inherited
Test if the element can be shared.
Definition at line 446 of file ElementBase.h.
References ElementBase::shareFlag.
Referenced by ElementBase::copyStructure(), and Sequence::updateList().
makeSharable()
void ElementBase::makeSharable () virtual inherited
Set sharable flag.
Reimplemented in TBeamline< T >.
Definition at line 213 of file ElementBase.cpp.
References ElementBase::shareFlag.
Referenced by OpalMarker::OpalMarker().
Online()
bool Component::Online () virtual inherited
Definition at line 71 of file Component.cpp.
References Component::online_m.
operator=()
void RFCavity::operator= (const RFCavity &) private
releasePosition()
void ElementBase::releasePosition () inline inherited
Definition at line 519 of file ElementBase.h.
References ElementBase::positionIsFixed.
removeAttribute()
void ElementBase::removeAttribute (const std::string & aKey) virtual inherited
Remove an existing attribute.
Definition at line 177 of file ElementBase.cpp.
References AttributeSet::removeAttribute(), and ElementBase::userAttribs.
setActionRange()
void ElementBase::setActionRange (const std::queue< std::pair< double, double > > & range) inline inherited
Definition at line 531 of file ElementBase.h.
References ElementBase::actionRange_m, and ElementBase::elementEdge_m.
setAmplitudeError()
void RFCavity::setAmplitudeError (double vPeakError) inline virtual
Definition at line 326 of file RFCavity.h.
References scaleError_m.
Referenced by OpalCavity::update(), and OpalTravelingWave::update().
setAmplitudem()
void RFCavity::setAmplitudem (double vPeak) inline virtual
Definition at line 318 of file RFCavity.h.
References scale_m.
Referenced by CavityAutophaser::getPhaseAtMaxEnergy(), OpalCavity::update(), and OpalTravelingWave::update().
setAmplitudeModel()
void RFCavity::setAmplitudeModel (std::shared_ptr< AbstractTimeDependence > time_dep) inline
Definition at line 386 of file RFCavity.h.
References amplitudeTD_m.
Referenced by initialise().
setAmplitudeModelName()
void RFCavity::setAmplitudeModelName (std::string name) inline
Definition at line 390 of file RFCavity.h.
References amplitudeName_m.
Referenced by OpalCavity::update().
setAperture()
void ElementBase::setAperture (const ApertureType & type, const std::vector< double > & args) inline inherited
Definition at line 497 of file ElementBase.h.
References ElementBase::aperture_m.
Referenced by Component::Component(), TEST_F(), TEST_F(), TEST_F(), and OpalElement::update().
setAttribute()
void ElementBase::setAttribute (const std::string & aKey, double val) virtual inherited
Set value of an attribute.
Definition at line 181 of file ElementBase.cpp.
References ElementBase::getChannel(), and Channel::isSettable().
Referenced by ElementBase::update(), and OpalElement::updateUnknown().
setAutophaseVeto()
void RFCavity::setAutophaseVeto (bool veto = true) inline virtual
Definition at line 378 of file RFCavity.h.
References autophaseVeto_m.
Referenced by CavityAutophaser::getPhaseAtMaxEnergy(), OpalCavity::update(), OpalTravelingWave::update(), and ParallelTracker::updateRFElement().
setAzimuth()
void RFCavity::setAzimuth (double angle)
Definition at line 309 of file RFCavity.cpp.
References angle_m.
Referenced by OpalCavity::update().
setBoundaryGeometry()
void ElementBase::setBoundaryGeometry (BoundaryGeometry * geo) virtual inherited
attach a boundary geometry field to the element
Definition at line 229 of file ElementBase.cpp.
References ElementBase::bgeometry_m.
setCavityType()
void RFCavity::setCavityType (const std::string & type)
Definition at line 357 of file RFCavity.cpp.
References bmCavityTypeString_s, BiMap< Left, Right >::right, SW, and type_m.
Referenced by OpalCavity::update().
setCSTrafoGlobal2Local()
void ElementBase::setCSTrafoGlobal2Local (const CoordinateSystemTrafo & ori) inline inherited
Definition at line 474 of file ElementBase.h.
References ElementBase::csTrafoGlobal2Local_m, and ElementBase::positionIsFixed.
Referenced by OpalElement::update().
setCurrentSCoordinate()
void ElementBase::setCurrentSCoordinate (double s) inherited
Definition at line 237 of file ElementBase.cpp.
References ElementBase::actionRange_m, and ElementBase::elementEdge_m.
setDesignEnergy()
void RFCavity::setDesignEnergy (const double & ekin, bool changeable = true) inline override virtual
Reimplemented from Component.
Definition at line 302 of file RFCavity.h.
References designEnergy_m.
Referenced by OpalCavity::update(), and OpalTravelingWave::update().
setElementLength()
void ElementBase::setElementLength (double length) inline virtual inherited
Set design length.
Reimplemented in MultipoleT, and ConstantEFieldCavityRep.
Definition at line 402 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::setElementLength().
Referenced by initialise(), Solenoid::initialise(), TravelingWave::initialise(), MultipoleT::setElementLength(), SequenceMember::setLength(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), OpalCavity::update(), OpalMonitor::update(), OpalMultipole::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalSolenoid::update(), and OpalTravelingWave::update().
setElementPosition()
void ElementBase::setElementPosition (double elemedge) inline inherited
Access to ELEMEDGE attribute.
Definition at line 550 of file ElementBase.h.
References ElementBase::elemedgeSet_m, and ElementBase::elementPosition_m.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and OpalElement::update().
setExitFaceSlope()
void Component::setExitFaceSlope (const double & m) inline inherited
Definition at line 268 of file Component.h.
References Component::exit_face_slope_m.
setFast()
void RFCavity::setFast (bool fast) inline virtual
Definition at line 370 of file RFCavity.h.
References fast_m.
Referenced by OpalCavity::update(), and OpalTravelingWave::update().
setFieldMapFN()
void RFCavity::setFieldMapFN (const std::string & fmapfn) inline virtual
Set the name of the field map.
Definition at line 314 of file RFCavity.h.
References filename_m.
Referenced by OpalCavity::update(), and OpalTravelingWave::update().
setFlagDeleteOnTransverseExit()
void ElementBase::setFlagDeleteOnTransverseExit (bool flag = true) inline inherited
Definition at line 572 of file ElementBase.h.
References ElementBase::deleteOnTransverseExit_m.
Referenced by OpalElement::update().
setFrequency()
void RFCavity::setFrequency (double freq) inline
Definition at line 334 of file RFCavity.h.
References frequency_m.
setFrequencym()
void RFCavity::setFrequencym (double freq) inline virtual
Definition at line 338 of file RFCavity.h.
References frequency_m.
Referenced by OpalCavity::update(), and OpalTravelingWave::update().
setFrequencyModel()
void RFCavity::setFrequencyModel (std::shared_ptr< AbstractTimeDependence > time_dep) inline
Definition at line 410 of file RFCavity.h.
References frequencyTD_m.
Referenced by initialise().
setFrequencyModelName()
void RFCavity::setFrequencyModelName (std::string name) inline
Definition at line 414 of file RFCavity.h.
References frequencyName_m.
Referenced by OpalCavity::update().
setGapWidth()
void RFCavity::setGapWidth (double gapwidth)
Definition at line 317 of file RFCavity.cpp.
References gapwidth_m.
Referenced by OpalCavity::update().
setMisalignment()
void ElementBase::setMisalignment (const CoordinateSystemTrafo & cst) inline inherited
Definition at line 511 of file ElementBase.h.
References ElementBase::misalignment_m.
Referenced by OpalElement::update().
setName()
void ElementBase::setName (const std::string & name) virtual inherited
Set element name.
Definition at line 137 of file ElementBase.cpp.
References ElementBase::elementID.
Referenced by Sequence::insertDrifts(), and VariableRFCavity::operator=().
setOutputFN()
void ElementBase::setOutputFN (std::string fn) inherited
Set output filename.
Definition at line 141 of file ElementBase.cpp.
References ElementBase::outputfn_m.
Referenced by OpalMonitor::update(), and OpalProbe::update().
setParticleMatterInteraction()
void ElementBase::setParticleMatterInteraction (ParticleMatterInteractionHandler * spys) virtual inherited
Definition at line 233 of file ElementBase.cpp.
References ElementBase::parmatint_m.
setPerpenDistance()
void RFCavity::setPerpenDistance (double pdis)
Definition at line 313 of file RFCavity.cpp.
References pdis_m.
Referenced by OpalCavity::update().
setPhaseError()
void RFCavity::setPhaseError (double phaseError) inline virtual
Definition at line 358 of file RFCavity.h.
References phaseError_m.
Referenced by OpalCavity::update(), and OpalTravelingWave::update().
setPhasem()
void RFCavity::setPhasem (double phase) inline virtual
Reimplemented in TravelingWave.
Definition at line 346 of file RFCavity.h.
References phase_m.
Referenced by getAutoPhaseEstimateFallback(), CavityAutophaser::getPhaseAtMaxEnergy(), CavityAutophaser::track(), OpalCavity::update(), and ParallelTracker::updateRFElement().
setPhaseModel()
void RFCavity::setPhaseModel (std::shared_ptr< AbstractTimeDependence > time_dep) inline
Definition at line 398 of file RFCavity.h.
References phaseTD_m.
Referenced by initialise().
setPhaseModelName()
void RFCavity::setPhaseModelName (std::string name) inline
Definition at line 402 of file RFCavity.h.
References phaseName_m.
Referenced by OpalCavity::update().
setPhi0()
void RFCavity::setPhi0 (double phi0)
Definition at line 321 of file RFCavity.cpp.
References phi0_m.
Referenced by OpalCavity::update().
setRmax()
void RFCavity::setRmax (double rmax)
Definition at line 305 of file RFCavity.cpp.
References rmax_m.
Referenced by OpalCavity::update().
setRmin()
void RFCavity::setRmin (double rmin)
Definition at line 301 of file RFCavity.cpp.
References rmin_m.
Referenced by OpalCavity::update().
setRotationAboutZ()
void ElementBase::setRotationAboutZ (double rotation) inline inherited
Set rotation about z axis in bend frame.
Definition at line 538 of file ElementBase.h.
References ElementBase::rotationZAxis_m.
Referenced by OpalElement::update().
setWake()
void ElementBase::setWake (WakeFunction * wf) virtual inherited
attach a wake field to the element
Definition at line 225 of file ElementBase.cpp.
References ElementBase::wake_m.
spline()
double RFCavity::spline (double z, double * za)
Definition at line 460 of file RFCavity.cpp.
References DvDr_m, num_points_m, RNormal_m, and VrNormal_m.
Referenced by getMomentaKick().
trackBunch()
void Component::trackBunch (PartBunch_t & bunch, const PartData & , bool revBeam, bool revTrack) const virtual inherited
Track a borrowed particle bunch through a non-standard component.
The default implementation throws a LogicalError.
Parameters
bunch Particle bunch to track. The component does not take ownership.
Definition at line 45 of file Component.cpp.
References ElementBase::getName().
Referenced by Tracker::visitComponent().
trackMap()
void Component::trackMap (FVps< double, 6 > & map, const PartData & , bool revBeam, bool revTrack) const virtual inherited
Track a map.
Definition at line 54 of file Component.cpp.
References ElementBase::getName().
trackOnAxisParticle()
std::pair< double, double > RFCavity::trackOnAxisParticle (const double & p0, const double & t0, const double & dt, const double & q, const double & mass, std::ofstream * out = nullptr) virtual
Definition at line 709 of file RFCavity.cpp.
References applyToReferenceParticle(), Physics::c, dot(), getElementLength(), Util::getGamma(), Util::getKineticEnergy(), PartData::getM(), PartData::getQ(), PartBunch< T, Dim >::getReference(), BorisPusher::kick(), BorisPusher::push(), Component::RefPartBunch_m, and startField_m.
Referenced by getAutoPhaseEstimateFallback(), and CavityAutophaser::track().
update()
bool ElementBase::update (const AttributeSet & set) inherited
Update element.
Definition at line 217 of file ElementBase.cpp.
References AttributeSet::begin(), AttributeSet::end(), and ElementBase::setAttribute().
Member Data Documentation
actionRange_m
std::queue<std::pair<double, double> > ElementBase::actionRange_m private inherited
Definition at line 384 of file ElementBase.h.
Referenced by ElementBase::setActionRange(), and ElementBase::setCurrentSCoordinate().
amplitudeName_m
std::string RFCavity::amplitudeName_m protected
Definition at line 185 of file RFCavity.h.
Referenced by getAmplitudeModelName(), and setAmplitudeModelName().
amplitudeTD_m
std::shared_ptr<AbstractTimeDependence> RFCavity::amplitudeTD_m protected
Definition at line 184 of file RFCavity.h.
Referenced by setAmplitudeModel().
angle_m
double RFCavity::angle_m private
Definition at line 214 of file RFCavity.h.
Referenced by getAzimuth(), initialise(), and setAzimuth().
aperture_m
std::pair<ApertureType, std::vector<double> > ElementBase::aperture_m protected inherited
Definition at line 355 of file ElementBase.h.
Referenced by ElementBase::getAperture(), ElementBase::getBoundingBoxInLabCoords(), ElementBase::isInsideTransverse(), and ElementBase::setAperture().
autophaseVeto_m
bool RFCavity::autophaseVeto_m protected
Definition at line 198 of file RFCavity.h.
Referenced by getAutophaseVeto(), and setAutophaseVeto().
bgeometry_m
BoundaryGeometry* ElementBase::bgeometry_m private inherited
Definition at line 375 of file ElementBase.h.
Referenced by ElementBase::getBoundaryGeometry(), ElementBase::hasBoundaryGeometry(), and ElementBase::setBoundaryGeometry().
bmCavityTypeString_s
const BiMap< CavityType, std::string > RFCavity::bmCavityTypeString_s static private
Initial value:
= []() {
    BiMap<CavityType, std::string> bimap;
    bimap.insert(CavityType::SW, "STANDING");
    bimap.insert(CavityType::SGSW, "SINGLEGAP");
    return bimap;
}()
Definition at line 31 of file RFCavity.h.
Referenced by getCavityTypeString(), and setCavityType().
cosAngle_m
double RFCavity::cosAngle_m private
Definition at line 216 of file RFCavity.h.
Referenced by getCosAzimuth(), getMomentaKick(), and initialise().
csTrafoGlobal2Local_m
CoordinateSystemTrafo ElementBase::csTrafoGlobal2Local_m protected inherited
Definition at line 352 of file ElementBase.h.
Referenced by ElementBase::getBoundingBoxInLabCoords(), ElementBase::getCSTrafoGlobal2Local(), and ElementBase::setCSTrafoGlobal2Local().
defaultAperture_m
const std::vector< double > Component::defaultAperture_m static protected inherited
Initial value:
=
    std::vector<double>({1e6, 1e6, 1.0})
Definition at line 233 of file Component.h.
Referenced by Component::Component().
deleteOnTransverseExit_m
bool ElementBase::deleteOnTransverseExit_m = true private inherited
Definition at line 388 of file ElementBase.h.
Referenced by ElementBase::getFlagDeleteOnTransverseExit(), and ElementBase::setFlagDeleteOnTransverseExit().
designEnergy_m
double RFCavity::designEnergy_m protected
Definition at line 200 of file RFCavity.h.
Referenced by getDesignEnergy(), and setDesignEnergy().
DvDr_m
std::unique_ptr<double[]> RFCavity::DvDr_m private
Definition at line 223 of file RFCavity.h.
Referenced by initialise(), and spline().
elemedgeSet_m
bool ElementBase::elemedgeSet_m private inherited
Definition at line 382 of file ElementBase.h.
Referenced by ElementBase::getElementPosition(), ElementBase::isElementPositionSet(), and ElementBase::setElementPosition().
elementEdge_m
double ElementBase::elementEdge_m protected inherited
Definition at line 357 of file ElementBase.h.
Referenced by ElementBase::setActionRange(), and ElementBase::setCurrentSCoordinate().
elementID
std::string ElementBase::elementID private inherited
Definition at line 366 of file ElementBase.h.
Referenced by ElementBase::getName(), and ElementBase::setName().
elementPosition_m
double ElementBase::elementPosition_m private inherited
ELEMEDGE attribute.
Definition at line 381 of file ElementBase.h.
Referenced by ElementBase::getElementPosition(), and ElementBase::setElementPosition().
elementTypeToString_s
const std::map< ElementType, std::string > ElementBase::elementTypeToString_s static private inherited
Initial value:
= {
    {ElementType::ANY, "Any"},
    {ElementType::BEAMLINE, "Beamline"},
    {ElementType::DRIFT, "Drift"},
    {ElementType::LASER, "Laser"},
    {ElementType::MARKER, "Marker"},
    {ElementType::MULTIPOLE, "Multipole"},
    {ElementType::RFCAVITY, "RFCavity"},
    {ElementType::TRAVELINGWAVE, "TravelingWave"},
    {ElementType::SBEND, "SBEND"},
    {ElementType::RBEND, "RBEND"},
    {ElementType::RBEND3D, "RBEND3D"},
    {ElementType::RING, "Ring"},
    {ElementType::SOURCE, "SOURCE"},
    {ElementType::SOLENOID, "SOLENOID"},
    {ElementType::PROBE, "Probe"},
    {ElementType::VACUUM, "Vacuum"},
    {ElementType::CONSTANTEFIELDCAVITY, "ConstantEFieldCavity"}}
Definition at line 69 of file ElementBase.h.
Referenced by ElementBase::getTypeString().
endField_m
double RFCavity::endField_m private
Definition at line 206 of file RFCavity.h.
Referenced by getDimensions(), and initialise().
exit_face_slope_m
double Component::exit_face_slope_m protected inherited
Definition at line 234 of file Component.h.
Referenced by Component::setExitFaceSlope().
fast_m
bool RFCavity::fast_m protected
Definition at line 197 of file RFCavity.h.
Referenced by getFast(), initialise(), and setFast().
fieldmap_m
Fieldmap* RFCavity::fieldmap_m protected
Definition at line 202 of file RFCavity.h.
Referenced by apply(), TravelingWave::apply(), apply(), TravelingWave::apply(), applyToReferenceParticle(), TravelingWave::applyToReferenceParticle(), dropFieldmaps(), getAutoPhaseEstimate(), TravelingWave::getAutoPhaseEstimate(), getElementDimensions(), getElementLength(), initialise(), isInside(), TestRFCavity::setFieldmap(), and TestTravelingWave::setFieldmap().
filename_m
std::string RFCavity::filename_m protected
The name of the inputfile
Definition at line 189 of file RFCavity.h.
Referenced by getFieldMapFN(), goOffline(), TravelingWave::goOffline(), goOnline(), TravelingWave::goOnline(), initialise(), initialise(), and setFieldMapFN().
frequency_m
double RFCavity::frequency_m protected
Read in frequency of time varying field(Hz)
Definition at line 195 of file RFCavity.h.
Referenced by apply(), TravelingWave::apply(), apply(), TravelingWave::apply(), applyToReferenceParticle(), TravelingWave::applyToReferenceParticle(), getAutoPhaseEstimate(), TravelingWave::getAutoPhaseEstimate(), getCycFrequency(), TravelingWave::getdA(), TravelingWave::getdB(), TravelingWave::getdE(), getFrequencym(), getMomentaKick(), getPhasem(), initialise(), setFrequency(), TestRFCavity::setFrequencyInternal(), TestTravelingWave::setFrequencyInternal(), and setFrequencym().
frequencyName_m
std::string RFCavity::frequencyName_m protected
Definition at line 187 of file RFCavity.h.
Referenced by getFrequencyModelName(), initialise(), and setFrequencyModelName().
frequencyTD_m
std::shared_ptr<AbstractTimeDependence> RFCavity::frequencyTD_m protected
Definition at line 186 of file RFCavity.h.
Referenced by getMomentaKick(), and setFrequencyModel().
gapwidth_m
double RFCavity::gapwidth_m private
Definition at line 218 of file RFCavity.h.
Referenced by getGapWidth(), getMomentaKick(), and setGapWidth().
misalignment_m
CoordinateSystemTrafo ElementBase::misalignment_m protected inherited
Definition at line 353 of file ElementBase.h.
Referenced by ElementBase::getMisalignment(), and ElementBase::setMisalignment().
num_points_m
int RFCavity::num_points_m private
Definition at line 224 of file RFCavity.h.
Referenced by initialise(), and spline().
online_m
bool Component::online_m protected inherited
Definition at line 238 of file Component.h.
Referenced by Probe::doGoOffline(), PluginElement::finalise(), Multipole::finalise(), Ring::finalise(), Component::goOffline(), PluginElement::goOffline(), goOffline(), Solenoid::goOffline(), Component::goOnline(), Corrector::goOnline(), Monitor::goOnline(), goOnline(), Solenoid::goOnline(), TravelingWave::goOnline(), Ring::initialise(), Multipole::initialise(), Component::Online(), and PluginElement::~PluginElement().
outputfn_m
std::string ElementBase::outputfn_m private inherited
The name of the outputfile
Definition at line 386 of file ElementBase.h.
Referenced by ElementBase::getOutputFN(), and ElementBase::setOutputFN().
parmatint_m
ParticleMatterInteractionHandler* ElementBase::parmatint_m private inherited
Definition at line 377 of file ElementBase.h.
Referenced by ElementBase::getParticleMatterInteraction(), ElementBase::hasParticleMatterInteraction(), and ElementBase::setParticleMatterInteraction().
pdis_m
double RFCavity::pdis_m private
Definition at line 217 of file RFCavity.h.
Referenced by getPerpenDistance(), and setPerpenDistance().
phase_m
double RFCavity::phase_m protected
phase shift of time varying field (rad)
Definition at line 193 of file RFCavity.h.
Referenced by apply(), TravelingWave::apply(), apply(), TravelingWave::apply(), applyToReferenceParticle(), TravelingWave::applyToReferenceParticle(), TravelingWave::getAutoPhaseEstimate(), getPhasem(), getPhasem(), TravelingWave::initialise(), TestRFCavity::setPhaseInternal(), TestTravelingWave::setPhaseInternal(), setPhasem(), and TravelingWave::setPhasem().
phaseError_m
double RFCavity::phaseError_m protected
phase shift error (rad)
Definition at line 194 of file RFCavity.h.
Referenced by apply(), TravelingWave::apply(), apply(), TravelingWave::apply(), getPhaseError(), and setPhaseError().
phaseName_m
std::string RFCavity::phaseName_m protected
Definition at line 183 of file RFCavity.h.
Referenced by getPhaseModelName(), and setPhaseModelName().
phaseTD_m
std::shared_ptr<AbstractTimeDependence> RFCavity::phaseTD_m protected
Definition at line 182 of file RFCavity.h.
Referenced by setPhaseModel().
phi0_m
double RFCavity::phi0_m private
Definition at line 219 of file RFCavity.h.
Referenced by getMomentaKick(), getPhi0(), and setPhi0().
positionIsFixed
bool ElementBase::positionIsFixed private inherited
Definition at line 379 of file ElementBase.h.
Referenced by ElementBase::fixPosition(), ElementBase::isPositioned(), ElementBase::releasePosition(), and ElementBase::setCSTrafoGlobal2Local().
RefPartBunch_m
PartBunch_t* Component::RefPartBunch_m protected inherited
Definition at line 237 of file Component.h.
Referenced by Corrector::apply(), VerticalFFAMagnet::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), MultipoleT::apply(), apply(), ScalingFFAMagnet::apply(), Solenoid::apply(), TravelingWave::apply(), VariableRFCavity::apply(), Ring::apply(), MultipoleT::apply(), apply(), TravelingWave::apply(), VariableRFCavity::apply(), Corrector::apply(), VerticalFFAMagnet::finalise(), MultipoleT::finalise(), ScalingFFAMagnet::finalise(), VariableRFCavity::finalise(), Corrector::goOnline(), PluginElement::initialise(), Corrector::initialise(), VerticalFFAMagnet::initialise(), ConstantEFieldCavity::initialise(), Drift::initialise(), Laser::initialise(), Marker::initialise(), Monitor::initialise(), Multipole::initialise(), MultipoleT::initialise(), initialise(), ScalingFFAMagnet::initialise(), Solenoid::initialise(), TravelingWave::initialise(), VariableRFCavity::initialise(), initialise(), VariableRFCavity::initNull(), Multipole::isFocusing(), MultipoleT::MultipoleT(), ScalingFFAMagnet::ScalingFFAMagnet(), Corrector::setDesignEnergy(), Ring::setRefPartBunch(), trackOnAxisParticle(), and VerticalFFAMagnet::VerticalFFAMagnet().
rmax_m
double RFCavity::rmax_m private
Definition at line 213 of file RFCavity.h.
Referenced by getMomentaKick(), getRmax(), and setRmax().
rmin_m
double RFCavity::rmin_m private
Definition at line 212 of file RFCavity.h.
Referenced by getMomentaKick(), getRmin(), and setRmin().
RNormal_m
std::unique_ptr<double[]> RFCavity::RNormal_m private
Definition at line 221 of file RFCavity.h.
Referenced by initialise(), and spline().
rotationZAxis_m
double ElementBase::rotationZAxis_m protected inherited
Definition at line 359 of file ElementBase.h.
Referenced by ElementBase::getRotationAboutZ(), and ElementBase::setRotationAboutZ().
scale_m
double RFCavity::scale_m protected
scale multiplier
Definition at line 191 of file RFCavity.h.
Referenced by apply(), TravelingWave::apply(), apply(), TravelingWave::apply(), applyToReferenceParticle(), TravelingWave::applyToReferenceParticle(), getAmplitudem(), getAutoPhaseEstimate(), TravelingWave::getAutoPhaseEstimate(), getMomentaKick(), TravelingWave::initialise(), setAmplitudem(), TestRFCavity::setScale(), and TestTravelingWave::setScale().
scaleError_m
double RFCavity::scaleError_m protected
additive scale error
Definition at line 192 of file RFCavity.h.
Referenced by apply(), TravelingWave::apply(), apply(), TravelingWave::apply(), getAmplitudeError(), TravelingWave::initialise(), setAmplitudeError(), and TestTravelingWave::setScaleError().
shareFlag
bool ElementBase::shareFlag mutable protected inherited
Definition at line 350 of file ElementBase.h.
Referenced by Beamline::Beamline(), Beamline::Beamline(), Beamline::Beamline(), ElementBase::isSharable(), and ElementBase::makeSharable().
sinAngle_m
double RFCavity::sinAngle_m private
Definition at line 215 of file RFCavity.h.
Referenced by getMomentaKick(), getSinAzimuth(), and initialise().
startField_m
double RFCavity::startField_m protected
starting point of field(m)
Definition at line 203 of file RFCavity.h.
Referenced by apply(), TravelingWave::apply(), apply(), applyToReferenceParticle(), getDimensions(), getEdgeToBegin(), getEdgeToEnd(), initialise(), TravelingWave::initialise(), TestTravelingWave::setStartField(), TestRFCavity::setStartField(), and trackOnAxisParticle().
type_m
CavityType RFCavity::type_m private
Definition at line 208 of file RFCavity.h.
Referenced by getCavityType(), getCavityTypeString(), and setCavityType().
userAttribs
AttributeSet ElementBase::userAttribs private inherited
Definition at line 371 of file ElementBase.h.
Referenced by ElementBase::getChannel(), and ElementBase::removeAttribute().
VrNormal_m
std::unique_ptr<double[]> RFCavity::VrNormal_m private
Definition at line 222 of file RFCavity.h.
Referenced by initialise(), and spline().
wake_m
WakeFunction* ElementBase::wake_m private inherited
Definition at line 373 of file ElementBase.h.
Referenced by ElementBase::getWake(), ElementBase::hasWake(), and ElementBase::setWake().
The documentation for this class was generated from the following files:
RFCavity.h
RFCavity.cpp