OPALX (Object Oriented Parallel Accelerator Library for Exascal): ParticleProperties Class Reference
ParticleProperties Class Reference
#include <ParticleProperties.h>
Static Public Member Functions
static ParticleType getParticleType (const std::string &str)
static std::string getParticleTypeString (const ParticleType &type)
static double getParticleMass (const ParticleType &type)
static double getParticleCharge (const ParticleType &type)
static double getParticleChargeInCoulomb (const ParticleType &type)
static double getParticleLifetime (const ParticleType &type)
Return the mean rest-frame lifetime [s]. Throws if the particle is stable.
Static Private Attributes
static const BiMap< ParticleType, std::string > bmParticleType_s
static const std::map< ParticleType, double > particleMass_m
static const std::map< ParticleType, double > particleCharge_m
static const std::map< ParticleType, double > particleLifetime_m
Detailed Description
Definition at line 48 of file ParticleProperties.h.
Member Function Documentation
getParticleCharge()
double ParticleProperties::getParticleCharge (const ParticleType & type) static
Definition at line 40 of file ParticleProperties.cpp.
References particleCharge_m.
Referenced by getParticleChargeInCoulomb(), and Beam::update().
getParticleChargeInCoulomb()
double ParticleProperties::getParticleChargeInCoulomb (const ParticleType & type) static
Definition at line 44 of file ParticleProperties.cpp.
References getParticleCharge(), and Physics::q_e.
getParticleLifetime()
double ParticleProperties::getParticleLifetime (const ParticleType & type) static
Return the mean rest-frame lifetime [s]. Throws if the particle is stable.
Definition at line 48 of file ParticleProperties.cpp.
References getParticleTypeString(), and particleLifetime_m.
getParticleMass()
double ParticleProperties::getParticleMass (const ParticleType & type) static
Definition at line 36 of file ParticleProperties.cpp.
References particleMass_m.
Referenced by Beam::update().
getParticleType()
ParticleType ParticleProperties::getParticleType (const std::string & str) static
Definition at line 23 of file ParticleProperties.cpp.
References bmParticleType_s, BiMap< Left, Right >::right, and UNNAMED.
Referenced by MuonDecay::MuonDecay(), PartBunch< T, Dim >::PartBunch(), PionDecay::PionDecay(), and Beam::update().
getParticleTypeString()
std::string ParticleProperties::getParticleTypeString (const ParticleType & type) static
Definition at line 32 of file ParticleProperties.cpp.
References bmParticleType_s, and BiMap< Left, Right >::left.
Referenced by getParticleLifetime(), and Decay::setDaughterContainer().
Member Data Documentation
bmParticleType_s
const BiMap< ParticleType, std::string > ParticleProperties::bmParticleType_s static private
Initial value:
= []() {
    BiMap<ParticleType, std::string> bimap;
    bimap.insert(ParticleType::UNNAMED, "UNNAMED");
    bimap.insert(ParticleType::PHOTON, "PHOTON");
    bimap.insert(ParticleType::ELECTRON, "ELECTRON");
    bimap.insert(ParticleType::POSITRON, "POSITRON");
    bimap.insert(ParticleType::MUON, "MUON");
    bimap.insert(ParticleType::PION, "PION");
    bimap.insert(ParticleType::PROTON, "PROTON");
    bimap.insert(ParticleType::ANTIPROTON, "ANTIPROTON");
    bimap.insert(ParticleType::DEUTERON, "DEUTERON");
    bimap.insert(ParticleType::HMINUS, "HMINUS");
    bimap.insert(ParticleType::HYDROGEN, "HYDROGEN");
    bimap.insert(ParticleType::H2P, "H2P");
    bimap.insert(ParticleType::H3P, "H3P");
    bimap.insert(ParticleType::ALPHA, "ALPHA");
    bimap.insert(ParticleType::CARBON, "CARBON");
    bimap.insert(ParticleType::XENON, "XENON");
    bimap.insert(ParticleType::URANIUM, "URANIUM");
    return bimap;
}()
Definition at line 58 of file ParticleProperties.h.
Referenced by getParticleType(), and getParticleTypeString().
particleCharge_m
const std::map< ParticleType, double > ParticleProperties::particleCharge_m static private
Initial value:
= {
        {ParticleType::PHOTON, 0.0},      {ParticleType::ELECTRON, -1.0},
        {ParticleType::POSITRON, 1.0},    {ParticleType::MUON, -1.0},
        {ParticleType::PION, 1.0},        {ParticleType::PROTON, 1.0},
        {ParticleType::ANTIPROTON, -1.0}, {ParticleType::DEUTERON, 1.0},
        {ParticleType::HMINUS, -1.0},     {ParticleType::HYDROGEN, 0.0},
        {ParticleType::H2P, 1.0},         {ParticleType::H3P, 1.0},
        {ParticleType::ALPHA, 2.0},       {ParticleType::CARBON, 6.0},
        {ParticleType::XENON, 54.0},      {ParticleType::URANIUM, 92.0}}
Definition at line 98 of file ParticleProperties.h.
Referenced by getParticleCharge().
particleLifetime_m
const std::map< ParticleType, double > ParticleProperties::particleLifetime_m static private
Initial value:
= {
        {ParticleType::MUON, Physics::tau_mu}, {ParticleType::PION, Physics::tau_pi}}
Definition at line 108 of file ParticleProperties.h.
Referenced by getParticleLifetime().
particleMass_m
const std::map< ParticleType, double > ParticleProperties::particleMass_m static private
Initial value:
= {
        {ParticleType::PHOTON, 0.0},
        {ParticleType::ELECTRON, Physics::m_e},
        {ParticleType::POSITRON, Physics::m_e},
        {ParticleType::MUON, Physics::m_mu},
        {ParticleType::PION, Physics::m_pi},
        {ParticleType::PROTON, Physics::m_p},
        {ParticleType::ANTIPROTON, Physics::m_p},
        {ParticleType::DEUTERON, Physics::m_d},
        {ParticleType::HMINUS, Physics::m_hm},
        {ParticleType::HYDROGEN, Physics::m_h},
        {ParticleType::H2P, Physics::m_h2p},
        {ParticleType::H3P, Physics::m_h3p},
        {ParticleType::ALPHA, Physics::m_alpha},
        {ParticleType::CARBON, Physics::m_c},
        {ParticleType::XENON, Physics::m_xe},
        {ParticleType::URANIUM, Physics::m_u}}
Definition at line 80 of file ParticleProperties.h.
Referenced by getParticleMass().
The documentation for this class was generated from the following files:
ParticleProperties.h
ParticleProperties.cpp