OPALX (Object Oriented Parallel Accelerator Library for Exascal): SolenoidRep Class Reference
SolenoidRep Class Reference
#include <SolenoidRep.h>
Public Member Functions
SolenoidRep (const std::string &name)
Constructor with given name.
SolenoidRep ()
SolenoidRep (const SolenoidRep &)
virtual ~SolenoidRep ()
virtual ElementBase * clone () const
Return clone.
virtual Channel * getChannel (const std::string &aKey, bool=false)
Construct a read/write channel.
virtual ConstBzField & getField ()
Get field.
virtual const ConstBzField & getField () const
Get field.
virtual StraightGeometry & getGeometry ()
Get geometry.
virtual const StraightGeometry & getGeometry () const
Get geometry.
virtual double getBz () const
Get field.
virtual void setBz (double Bz)
Set field.
virtual bool apply (const std::shared_ptr< ParticleContainer_t > &pc) override
apply the solenoid field to all particles in the bunch
virtual bool apply (const size_t &i, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
apply the solenoid field to particle i
virtual bool apply (const Vector_t< double, 3 > &R, const Vector_t< double, 3 > &P, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
Apply to particle with position R and momentum P.
virtual bool applyToReferenceParticle (const Vector_t< double, 3 > &R, const Vector_t< double, 3 > &P, const double &t, Vector_t< double, 3 > &E, Vector_t< double, 3 > &B) override
Apply to reference particle with position R and momemtum P.
virtual void accept (BeamlineVisitor &) const override
Apply visitor to Solenoid.
void setKS (double ks)
Set the strength scaling factor ks.
void setDKS (double ks)
Set the strength scaling error dks.
virtual void initialise (PartBunch_t *bunch, double &startField, double &endField) override
initialise the solenoid element
virtual void finalise () override
virtual bool bends () const override
virtual void goOnline (const double &kineticEnergy) override
Load field map and go online.
virtual void goOffline () override
Free field map and go offline.
void setFieldMapFN (std::string fn)
Assign the field filename.
void setFast (bool fast)
Set the fast flag.
bool getFast () const
Get the fast flag.
virtual ElementType getType () const override
Get the element type.
virtual void getFieldExtend (double &zBegin, double &zEnd) const override
Return the local field-support interval of the solenoid.
virtual void getElementDimensions (double &zBegin, double &zEnd) const override
Return the nominal body extent of the solenoid.
bool getSupportEnvelope (double &horizontalRadius, double &verticalRadius) const
Get a finite transverse support envelope for placement/export.
virtual bool isInside (const Vector_t< double, 3 > &r) const override
Check if position r is inside the field map.
virtual CoordinateSystemTrafo getEdgeToBegin () const override
Get the coordinate transformation to the begin of the element.
virtual CoordinateSystemTrafo getEdgeToEnd () const override
Get the coordinate transformation to the end of the element.
EVector Efield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool getPotential (const Vector_t< double, 3 > &, const double &, Vector_t< double, 3 > &, double &)
Calculate the four-potential at some position relative to the component.
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual bool Online ()
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunch_t &bunch, const PartData &, bool revBeam, bool revTrack) const
Track a borrowed particle bunch through a non-standard component.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual Port getEntryPort () const
Return the entrance port of the canonical local chart.
virtual Port getBodyPort () const
Return the body port of the canonical local chart.
virtual Port getExitPort () const
Return the exit port of the canonical local chart.
PlacementPose getPlacementPose () const
Return the nominal rigid placement transform of the element.
void setPlacementPose (const PlacementPose &pose)
Set the nominal rigid placement transform of the element.
Misalignment getPlacementMisalignment () const
Return the local nominal-to-actual correction stored for the element.
ElementGeometry getPlacementGeometry () const
Return the bridge geometry ports assembled from legacy edge state.
SupportPlacement getPlacementSupport () const
Return the support-frame bridge object. The default is the body frame.
PlacedElement getPlacedElement () const
Return a placed-element view assembled from the current bridge objects.
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Static Public Member Functions
static std::string getTypeString (ElementType type)
Protected Member Functions
bool isInsideTransverse (const Vector_t< double, 3 > &r) const
Protected Attributes
double exit_face_slope_m
PartBunch_t * RefPartBunch_m
bool online_m
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes
static const std::vector< double > defaultAperture_m = std::vector<double>({1e6, 1e6, 1.0})
Private Member Functions
void operator= (const SolenoidRep &)
Private Attributes
StraightGeometry geometry
The solenoid geometry.
ConstBzField field
The solenoid field.
std::string filename_m
Name of the field map file.
Fieldmap * fieldmap_m
Fieldmap pointer.
double scale_m
Scale multiplier.
double scaleError_m
Scale error multiplier.
double startField_m
Starting point of the field.
double endField_m
End point of the field support in the local chart.
bool fast_m
Fast tracking flag.
std::string elementID
AttributeSet userAttribs
WakeFunction * wake_m
BoundaryGeometry * bgeometry_m
ParticleMatterInteractionHandler * parmatint_m
bool positionIsFixed
std::queue< std::pair< double, double > > actionRange_m
std::string outputfn_m
bool deleteOnTransverseExit_m = true
double elementPosition_m
ELEMEDGE attribute.
bool elemedgeSet_m
Static Private Attributes
static const std::map< ElementType, std::string > elementTypeToString_s
Detailed Description
Definition at line 25 of file SolenoidRep.h.
Constructor & Destructor Documentation
SolenoidRep() [1/3]
SolenoidRep::SolenoidRep (const std::string & name) explicit
Constructor with given name.
Definition at line 39 of file SolenoidRep.cpp.
SolenoidRep() [2/3]
SolenoidRep::SolenoidRep ()
Definition at line 34 of file SolenoidRep.cpp.
Referenced by clone().
SolenoidRep() [3/3]
SolenoidRep::SolenoidRep (const SolenoidRep & right)
Definition at line 36 of file SolenoidRep.cpp.
~SolenoidRep()
SolenoidRep::~SolenoidRep () virtual
Definition at line 41 of file SolenoidRep.cpp.
Member Function Documentation
accept()
void Solenoid::accept (BeamlineVisitor & visitor) const override virtual inherited
Apply visitor to Solenoid.
Implements ElementBase.
Definition at line 153 of file Solenoid.cpp.
References BeamlineVisitor::visitSolenoid().
apply() [1/3]
bool Solenoid::apply (const size_t & i, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual inherited
apply the solenoid field to particle i
Parameters
i Particle index
t Time
E Electric Field
B Magnetic Field
Returns
true if particle is lost, false otherwise
Reimplemented from Component.
Definition at line 86 of file Solenoid.cpp.
References Solenoid::apply(), PartBunch< T, Dim >::R(), and Component::RefPartBunch_m.
apply() [2/3]
bool Solenoid::apply (const std::shared_ptr< ParticleContainer_t > & pc) override virtual inherited
apply the solenoid field to all particles in the bunch
Returns
true if at least one particle is lost, false otherwise
Note
currently not implemented
Returns
true if at least one particle is lost, false otherwise (not implemented, always returns false)
Reimplemented from Component.
Definition at line 67 of file Solenoid.cpp.
References Fieldmap::applyField(), Solenoid::fieldmap_m, Solenoid::scale_m, and Solenoid::scaleError_m.
Referenced by Solenoid::apply().
apply() [3/3]
bool Solenoid::apply (const Vector_t< double, 3 > & R, const Vector_t< double, 3 > & P, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual inherited
Apply to particle with position R and momentum P.
Parameters
R Position
P Momentum
t Time
E Electric Field
B Magnetic Field
Returns
true if particle is lost, false otherwise
Reimplemented from Component.
Definition at line 108 of file Solenoid.cpp.
References Solenoid::endField_m, Solenoid::fieldmap_m, Fieldmap::getFieldstrength(), ElementBase::getFlagDeleteOnTransverseExit(), Solenoid::scale_m, Solenoid::scaleError_m, and Solenoid::startField_m.
applyToReferenceParticle()
bool Solenoid::applyToReferenceParticle (const Vector_t< double, 3 > & R, const Vector_t< double, 3 > & P, const double & t, Vector_t< double, 3 > & E, Vector_t< double, 3 > & B) override virtual inherited
Apply to reference particle with position R and momemtum P.
Parameters
R Position
P Momentum
t Time
E Electric Field
B Magnetic Field
Returns
true if particle is lost, false otherwise
Reimplemented from Component.
Definition at line 136 of file Solenoid.cpp.
References Solenoid::endField_m, Solenoid::fieldmap_m, Fieldmap::getFieldstrength(), Solenoid::scale_m, and Solenoid::startField_m.
bends()
bool Solenoid::bends () const override virtual inherited
Implements Component.
Definition at line 198 of file Solenoid.cpp.
Bfield() [1/2]
BVector Component::Bfield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 234 of file Component.h.
References EMField::Bfield(), and Component::getField().
Bfield() [2/2]
BVector Component::Bfield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 240 of file Component.h.
References EMField::Bfield(), and Component::getField().
clone()
ElementBase * SolenoidRep::clone () const virtual
Return clone.
Implements ElementBase.
Definition at line 43 of file SolenoidRep.cpp.
References SolenoidRep().
copyStructure()
ElementBase * ElementBase::copyStructure () virtual inherited
Make a structural copy.
Reimplemented in TBeamline< T >.
Definition at line 193 of file ElementBase.cpp.
References ElementBase::clone(), and ElementBase::isSharable().
Referenced by Sequence::copy(), Line::parse(), SequenceParser::parseMember(), and Replacer::visitFlaggedElmPtr().
EBfield() [1/2]
EBVectors Component::EBfield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 244 of file Component.h.
References EMField::EBfield(), and Component::getField().
EBfield() [2/2]
EBVectors Component::EBfield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 246 of file Component.h.
References EMField::EBfield(), and Component::getField().
Efield() [1/2]
EVector Component::Efield (const Point3D & P) const inline inherited
Return the field in a point.
Definition at line 232 of file Component.h.
References EMField::Efield(), and Component::getField().
Efield() [2/2]
EVector Component::Efield (const Point3D & P, double t) const inline inherited
Return the field in a point.
Definition at line 236 of file Component.h.
References EMField::Efield(), and Component::getField().
finalise()
void Solenoid::finalise () override virtual inherited
Note
not implemented
Implements Component.
Definition at line 196 of file Solenoid.cpp.
fixPosition()
void ElementBase::fixPosition () inline inherited
Definition at line 596 of file ElementBase.h.
References ElementBase::positionIsFixed.
Referenced by OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
getAperture()
std::pair< ApertureType, std::vector< double > > ElementBase::getAperture () const inline inherited
Definition at line 581 of file ElementBase.h.
References ElementBase::aperture_m.
Referenced by MeshGenerator::add(), Solenoid::getSupportEnvelope(), and MeshGenerator::getTransverseSupport().
getArcLength()
double ElementBase::getArcLength () const inline virtual inherited
Get arc length.
Reimplemented in MarkerRep, and TBeamline< T >.
Definition at line 478 of file ElementBase.h.
References BGeometryBase::getArcLength(), and ElementBase::getGeometry().
Referenced by BeamlineGeometry::getArcLength(), and TBeamline< T >::getTransform().
getAttribute()
double ElementBase::getAttribute (const std::string & aKey) const virtual inherited
Get attribute value.
Definition at line 146 of file ElementBase.cpp.
References ElementBase::getConstChannel().
getBodyPort()
Port ElementBase::getBodyPort () const inline virtual inherited
Return the body port of the canonical local chart.
The body port \(p_{i,\mathrm{body}}\) is the identity port of the element's canonical local chart. Its rigid transform is therefore the identity element of \(SE(3)\) in the first redesign stage.
Definition at line 546 of file ElementBase.h.
Referenced by ElementBase::getPlacementGeometry(), and TEST_F().
getBoundaryGeometry()
BoundaryGeometry * ElementBase::getBoundaryGeometry () const inline virtual inherited
return the attached boundary geometrt object if there is any
Definition at line 512 of file ElementBase.h.
References ElementBase::bgeometry_m.
getBoundingBoxInLabCoords()
BoundingBox ElementBase::getBoundingBoxInLabCoords () const virtual inherited
Definition at line 263 of file ElementBase.cpp.
References ElementBase::aperture_m, ElementBase::csTrafoGlobal2Local_m, BoundingBox::getBoundingBox(), ElementBase::getEdgeToBegin(), ElementBase::getEdgeToEnd(), and CoordinateSystemTrafo::transformFrom().
getBz()
double SolenoidRep::getBz () const virtual
Get field.
Implements Solenoid.
Definition at line 63 of file SolenoidRep.cpp.
References field, and ConstBzField::getBz().
getChannel()
Channel * SolenoidRep::getChannel (const std::string & aKey, bool create = false) virtual
Construct a read/write channel.
Reimplemented from ElementBase.
Definition at line 45 of file SolenoidRep.cpp.
References ElementBase::getChannel().
getConstChannel()
const ConstChannel * ElementBase::getConstChannel (const std::string & aKey) const virtual inherited
Construct a read-only channel.
Definition at line 185 of file ElementBase.cpp.
References ElementBase::getChannel().
Referenced by ElementBase::getAttribute(), and ElementBase::hasAttribute().
getCSTrafoGlobal2Local()
CoordinateSystemTrafo ElementBase::getCSTrafoGlobal2Local () const inline inherited
Definition at line 528 of file ElementBase.h.
References ElementBase::csTrafoGlobal2Local_m.
Referenced by ElementBase::getPlacementPose(), OpalRBend::update(), and OpalSBend::update().
getDesign()
const ElementBase & Component::getDesign () const virtual inherited
Return design element.
Definition at line 33 of file Component.cpp.
getDesignEnergy()
double Component::getDesignEnergy () const inline virtual inherited
Reimplemented in BendBase, and RFCavity.
Definition at line 254 of file Component.h.
getEdgeToBegin()
CoordinateSystemTrafo Solenoid::getEdgeToBegin () const inline override virtual inherited
Get the coordinate transformation to the begin of the element.
Get the coordinate transformation to the start of the element.
Returns
CoordinateSystemTrafo to the begin of the element
Reimplemented from ElementBase.
Definition at line 214 of file Solenoid.h.
Referenced by TEST_F().
getEdgeToEnd()
CoordinateSystemTrafo Solenoid::getEdgeToEnd () const inline override virtual inherited
Get the coordinate transformation to the end of the element.
Returns
CoordinateSystemTrafo to the end of the element
Reimplemented from ElementBase.
Definition at line 224 of file Solenoid.h.
References ElementBase::getElementLength().
Referenced by TEST_F().
getElementDimensions()
void Solenoid::getElementDimensions (double & begin, double & end) const override virtual inherited
Return the nominal body extent of the solenoid.
Get the dimensions of the solenoid.
The nominal body extent is the hardware interval \([0, L_\mathrm{body}]\) in the canonical local chart. It is driven by the configured solenoid length and is intentionally kept separate from the field-support interval so that body placement and fringe-field support can differ.
Parameters
begin Start position
end End position
Reimplemented from ElementBase.
Definition at line 243 of file Solenoid.cpp.
References ElementBase::getElementLength().
Referenced by TEST_F().
getElementLength()
double ElementBase::getElementLength () const inline virtual inherited
Get design length.
Reimplemented in MarkerRep, TBeamline< T >, and RFCavity.
Definition at line 480 of file ElementBase.h.
References BGeometryBase::getElementLength(), and ElementBase::getGeometry().
Referenced by MeshGenerator::add(), ConstantEFieldCavity::apply(), Multipole::apply(), VariableRFCavity::apply(), BendBase::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), VariableRFCavity::apply(), Component::apply(), Corrector::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), VariableRFCavity::apply(), Component::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), ElementBase::getEdgeToEnd(), Solenoid::getEdgeToEnd(), ElementBase::getElementDimensions(), Solenoid::getElementDimensions(), BeamlineGeometry::getElementLength(), RFCavity::getElementLength(), Corrector::getFieldExtend(), BendBase::getFieldExtend(), ConstantEFieldCavity::getFieldExtend(), Drift::getFieldExtend(), Laser::getFieldExtend(), Multipole::getFieldExtend(), MultipoleT::getFieldExtend(), VariableRFCavity::getFieldExtend(), BendBase::getLength(), Corrector::initialise(), BendBase::initialise(), ConstantEFieldCavity::initialise(), Drift::initialise(), Laser::initialise(), Multipole::initialise(), ElementBase::isInside(), BendBase::isInside(), Monitor::isInside(), Multipole::isInside(), ElementBase::isInsideTransverse(), and TEST_F().
getElementPosition()
double ElementBase::getElementPosition () const inline inherited
Definition at line 617 of file ElementBase.h.
References ElementBase::elemedgeSet_m, ElementBase::elementPosition_m, and ElementBase::getName().
getEntrance()
double ElementBase::getEntrance () const inline virtual inherited
Get entrance position.
Reimplemented in TBeamline< T >.
Definition at line 486 of file ElementBase.h.
References BGeometryBase::getEntrance(), and ElementBase::getGeometry().
Referenced by BendBase::getDesignPath(), and BeamlineGeometry::getEntrance().
getEntranceFrame()
Euclid3D ElementBase::getEntranceFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 498 of file ElementBase.h.
References BGeometryBase::getEntranceFrame(), and ElementBase::getGeometry().
Referenced by BendBase::getChordLength(), BendBase::getEdgeToBegin(), and BeamlineGeometry::getEntranceFrame().
getEntrancePatch()
Euclid3D ElementBase::getEntrancePatch () const inline virtual inherited
Get patch.
Definition at line 502 of file ElementBase.h.
References BGeometryBase::getEntrancePatch(), and ElementBase::getGeometry().
getEntryPort()
Port ElementBase::getEntryPort () const inline virtual inherited
Return the entrance port of the canonical local chart.
In the placement-note language, this is the marked entrance port \(p_{i,\mathrm{entry}}\) of element \(i\). For straight elements in the bridge stage, the body-to-entry transform is taken from the legacy getEdgeToBegin() result.
Definition at line 544 of file ElementBase.h.
References ElementBase::getEdgeToBegin().
Referenced by ElementBase::getPlacementGeometry(), and TEST_F().
getExit()
double ElementBase::getExit () const inline virtual inherited
Get exit position.
Reimplemented in TBeamline< T >.
Definition at line 488 of file ElementBase.h.
References BGeometryBase::getExit(), and ElementBase::getGeometry().
Referenced by BendBase::getDesignPath(), and BeamlineGeometry::getExit().
getExitFrame()
Euclid3D ElementBase::getExitFrame () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 500 of file ElementBase.h.
References BGeometryBase::getExitFrame(), and ElementBase::getGeometry().
Referenced by BendBase::getChordLength(), BendBase::getEdgeToEnd(), and BeamlineGeometry::getExitFrame().
getExitPatch()
Euclid3D ElementBase::getExitPatch () const inline virtual inherited
Get patch.
Definition at line 504 of file ElementBase.h.
References BGeometryBase::getExitPatch(), and ElementBase::getGeometry().
getExitPort()
Port ElementBase::getExitPort () const inline virtual inherited
Return the exit port of the canonical local chart.
In the placement-note language, this is the marked exit port \(p_{i,\mathrm{exit}}\). For straight elements in the bridge stage, the body-to-exit transform is taken from the legacy getEdgeToEnd() result.
Definition at line 548 of file ElementBase.h.
References ElementBase::getEdgeToEnd().
Referenced by ElementBase::getPlacementGeometry(), and TEST_F().
getFast()
bool Solenoid::getFast () const inherited
Get the fast flag.
Definition at line 219 of file Solenoid.cpp.
References Solenoid::fast_m.
getField() [1/2]
ConstBzField & SolenoidRep::getField () virtual
Get field.
Implements Component.
Definition at line 55 of file SolenoidRep.cpp.
References field.
getField() [2/2]
const ConstBzField & SolenoidRep::getField () const virtual
Get field.
Implements Component.
Definition at line 57 of file SolenoidRep.cpp.
References field.
getFieldExtend()
void Solenoid::getFieldExtend (double & zBegin, double & zEnd) const override virtual inherited
Return the local field-support interval of the solenoid.
Get the dimensions of the solenoid.
For the extent split used in the element-placement redesign, this method returns the interval on which the solenoid field map is defined, \([z_\mathrm{field}^{\mathrm{begin}}, z_\mathrm{field}^{\mathrm{end}}]\). It may differ from the nominal body extent and therefore also from the entry/exit ports used for placement and visualization.
Parameters
zBegin Start position
zEnd End position
Implements Component.
Definition at line 224 of file Solenoid.cpp.
References Solenoid::endField_m, and Solenoid::startField_m.
Referenced by TEST_F().
getFlagDeleteOnTransverseExit()
bool ElementBase::getFlagDeleteOnTransverseExit () const inline inherited
Definition at line 633 of file ElementBase.h.
References ElementBase::deleteOnTransverseExit_m.
Referenced by BendBase::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), Corrector::apply(), BendBase::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), RFCavity::apply(), Solenoid::apply(), and TravelingWave::apply().
getGeometry() [1/2]
StraightGeometry & SolenoidRep::getGeometry () virtual
Get geometry.
Implements ElementBase.
Definition at line 59 of file SolenoidRep.cpp.
References geometry.
getGeometry() [2/2]
const StraightGeometry & SolenoidRep::getGeometry () const virtual
Get geometry.
Implements ElementBase.
Definition at line 61 of file SolenoidRep.cpp.
References geometry.
getMisalignment() [1/2]
CoordinateSystemTrafo ElementBase::getMisalignment () const inline inherited
Definition at line 592 of file ElementBase.h.
References ElementBase::misalignment_m.
Referenced by ElementBase::getPlacementMisalignment().
getMisalignment() [2/2]
void ElementBase::getMisalignment (double & x, double & y, double & s) const inherited
getName()
const std::string & ElementBase::getName () const virtual inherited
Get element name.
Definition at line 131 of file ElementBase.cpp.
References ElementBase::elementID.
Referenced by Ring::appendElement(), Probe::doGoOffline(), PlaceRep::enter(), ElementBase::getElementPosition(), RFCavity::getMomentaKick(), ElementBase::getOutputFN(), CavityAutophaser::getPhaseAtMaxEnergy(), Selector::handleElement(), Ring::initialise(), RFCavity::initialise(), Solenoid::initialise(), PlaceRep::leave(), VariableRFCavity::operator=(), Sequence::print(), TEST_F(), Component::trackBunch(), Component::trackMap(), OpalRBend::update(), OpalSBend::update(), Sequence::updateList(), ParallelTracker::updateRFElement(), and Replacer::visitFlaggedElmPtr().
getOrigin()
double ElementBase::getOrigin () const inline virtual inherited
Get origin position.
Reimplemented in TBeamline< T >.
Definition at line 484 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getOrigin().
Referenced by BeamlineGeometry::getOrigin().
getOutputFN()
std::string ElementBase::getOutputFN () const inherited
Get output filename.
Definition at line 137 of file ElementBase.cpp.
References ElementBase::getName(), and ElementBase::outputfn_m.
Referenced by Probe::doInitialise(), PluginElement::initialise(), and Monitor::initialise().
getParticleMatterInteraction()
ParticleMatterInteractionHandler * ElementBase::getParticleMatterInteraction () const inline virtual inherited
Definition at line 516 of file ElementBase.h.
References ElementBase::parmatint_m.
getPlacedElement()
PlacedElement ElementBase::getPlacedElement () const inline inherited
Return a placed-element view assembled from the current bridge objects.
Definition at line 570 of file ElementBase.h.
References ElementBase::getPlacementGeometry(), ElementBase::getPlacementMisalignment(), ElementBase::getPlacementPose(), and ElementBase::getPlacementSupport().
Referenced by MeshGenerator::add(), and TEST_F().
getPlacementGeometry()
ElementGeometry ElementBase::getPlacementGeometry () const inline inherited
Return the bridge geometry ports assembled from legacy edge state.
The first redesign stage defines a minimal explicit port contract with three named body-relative ports: \(p_{i,\mathrm{entry}}\), \(p_{i,\mathrm{body}}\), \(p_{i,\mathrm{exit}}\). The default bridge preserves current OPALX behavior by deriving those ports from getEntryPort(), getBodyPort(), and getExitPort(), whose straight-element implementations are backed by the legacy getEdgeToBegin() and getEdgeToEnd() methods.
Definition at line 562 of file ElementBase.h.
References ElementBase::getBodyPort(), ElementBase::getEntryPort(), and ElementBase::getExitPort().
Referenced by ElementBase::getPlacedElement().
getPlacementMisalignment()
Misalignment ElementBase::getPlacementMisalignment () const inline inherited
Return the local nominal-to-actual correction stored for the element.
Definition at line 558 of file ElementBase.h.
References ElementBase::getMisalignment().
Referenced by ElementBase::getPlacedElement().
getPlacementPose()
PlacementPose ElementBase::getPlacementPose () const inline inherited
Return the nominal rigid placement transform of the element.
This is the bridge from the legacy stored CoordinateSystemTrafo to the new placement vocabulary. It preserves current nominal placement semantics and does not apply misalignment.
Definition at line 550 of file ElementBase.h.
References ElementBase::getCSTrafoGlobal2Local().
Referenced by ElementBase::getPlacedElement().
getPlacementSupport()
SupportPlacement ElementBase::getPlacementSupport () const inline inherited
Return the support-frame bridge object. The default is the body frame.
Definition at line 566 of file ElementBase.h.
Referenced by ElementBase::getPlacedElement().
getPotential()
virtual bool Component::getPotential (const Vector_t< double, 3 > & , const double & , Vector_t< double, 3 > & , double &) inline virtual inherited
Calculate the four-potential at some position relative to the component.
Parameters
R position in the local coordinate system of the component
t time
A filled with the calculated magnetic vector potential
phi filled with the calculated electric potential Note that any existing values in A and phi may be overwritten by this method.
Returns
true if particle is outside the field map, else false Default for component is to return false and make no change to A and phi
Definition at line 155 of file Component.h.
getRequiredNumberOfTimeSteps()
int ElementBase::getRequiredNumberOfTimeSteps () const inline virtual inherited
Reimplemented in BendBase, Drift, Laser, Marker, and Monitor.
Definition at line 627 of file ElementBase.h.
getRotationAboutZ()
double ElementBase::getRotationAboutZ () const inline inherited
Definition at line 608 of file ElementBase.h.
References ElementBase::rotationZAxis_m.
Referenced by OpalBeamline::compileCompatibilityPlacement().
getSupportEnvelope()
bool Solenoid::getSupportEnvelope (double & horizontalRadius, double & verticalRadius) const inherited
Get a finite transverse support envelope for placement/export.
The tracking aperture of generic components defaults to a very large ellipse. For solenoids, placement/export code instead needs a physically meaningful support radius. This method first prefers a finite configured aperture and otherwise falls back to the loaded field-map bounding box.
Parameters
horizontalRadius Output half-width in x [m].
verticalRadius Output half-width in y [m].
Returns
true if a finite support envelope is available.
Definition at line 248 of file Solenoid.cpp.
References Solenoid::fieldmap_m, ElementBase::getAperture(), and Fieldmap::getFieldDimensions().
Referenced by TEST_F().
getTotalTransform()
Euclid3D ElementBase::getTotalTransform () const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 494 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getTotalTransform().
Referenced by BeamlineGeometry::getTotalTransform().
getTransform() [1/2]
Euclid3D ElementBase::getTransform (double fromS, double toS) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 490 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getTransform().
Referenced by BendBase::getDesignPath(), BeamlineGeometry::getTransform(), TBeamline< T >::getTransform(), and BeamlineGeometry::getTransform().
getTransform() [2/2]
Euclid3D ElementBase::getTransform (double s) const inline virtual inherited
Get transform.
Reimplemented in TBeamline< T >.
Definition at line 496 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::getTransform().
getType()
ElementType Solenoid::getType () const override virtual inherited
Get the element type.
Returns
ElementType::SOLENOID
Reimplemented from Component.
Definition at line 231 of file Solenoid.cpp.
References SOLENOID.
getTypeString() [1/2]
std::string ElementBase::getTypeString () const inline inherited
Definition at line 610 of file ElementBase.h.
References ElementBase::getType(), and ElementBase::getTypeString().
Referenced by ElementBase::getTypeString().
getTypeString() [2/2]
std::string ElementBase::getTypeString (ElementType type) static inherited
Definition at line 191 of file ElementBase.cpp.
References ElementBase::elementTypeToString_s.
getWake()
WakeFunction * ElementBase::getWake () const inline virtual inherited
return the attached wake object if there is any
Definition at line 508 of file ElementBase.h.
References ElementBase::wake_m.
goOffline()
void Solenoid::goOffline () override virtual inherited
Free field map and go offline.
Reimplemented from Component.
Definition at line 207 of file Solenoid.cpp.
References Solenoid::filename_m, and Component::online_m.
goOnline()
void Solenoid::goOnline (const double & kineticEnergy) override virtual inherited
Load field map and go online.
Read field map and go online.
Reimplemented from Component.
Definition at line 201 of file Solenoid.cpp.
References Solenoid::filename_m, and Component::online_m.
hasAttribute()
bool ElementBase::hasAttribute (const std::string & aKey) const virtual inherited
Test for existence of an attribute.
Definition at line 158 of file ElementBase.cpp.
References ElementBase::getConstChannel().
hasBoundaryGeometry()
bool ElementBase::hasBoundaryGeometry () const inline virtual inherited
Definition at line 514 of file ElementBase.h.
References ElementBase::bgeometry_m.
hasParticleMatterInteraction()
bool ElementBase::hasParticleMatterInteraction () const inline virtual inherited
Definition at line 520 of file ElementBase.h.
References ElementBase::parmatint_m.
hasWake()
bool ElementBase::hasWake () const inline virtual inherited
Definition at line 510 of file ElementBase.h.
References ElementBase::wake_m.
initialise()
void Solenoid::initialise (PartBunch_t * bunch, double & startField, double & endField) override virtual inherited
initialise the solenoid element
Initialises the solenoid elements by reading the header of the fieldmap, saving the start and endpoints of the fieldmaps.
Parameters
bunch Particle bunch
startField Starting position of the field
endField Ending position of the field
Implements Component.
Definition at line 169 of file Solenoid.cpp.
References Solenoid::endField_m, Solenoid::fast_m, Solenoid::fieldmap_m, Solenoid::filename_m, Fieldmap::getFieldDimensions(), Fieldmap::getInfo(), ElementBase::getName(), gmsg, Component::RefPartBunch_m, and Solenoid::startField_m.
Referenced by TEST_F().
isElementPositionSet()
bool ElementBase::isElementPositionSet () const inline inherited
Definition at line 625 of file ElementBase.h.
References ElementBase::elemedgeSet_m.
isInside()
bool Solenoid::isInside (const Vector_t< double, 3 > & r) const override virtual inherited
Check if position r is inside the field map.
Check if a point is inside the solenoid.
Parameters
r Position
Returns
true if inside, false otherwise
Reimplemented from ElementBase.
Definition at line 236 of file Solenoid.cpp.
References Solenoid::fieldmap_m, Fieldmap::isInside(), and ElementBase::isInsideTransverse().
Referenced by TEST_F().
isInsideTransverse()
bool ElementBase::isInsideTransverse (const Vector_t< double, 3 > & r) const protected inherited
Definition at line 232 of file ElementBase.cpp.
References ElementBase::aperture_m, CONIC_ELLIPTICAL, CONIC_RECTANGULAR, ELLIPTICAL, ElementBase::getEdgeToBegin(), ElementBase::getElementLength(), RECTANGULAR, and CoordinateSystemTrafo::transformTo().
Referenced by BendBase::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), Component::apply(), Corrector::apply(), BendBase::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), Component::applyToReferenceParticle(), BendBase::applyToReferenceParticle(), ConstantEFieldCavity::applyToReferenceParticle(), Multipole::applyToReferenceParticle(), ElementBase::isInside(), BendBase::isInside(), Monitor::isInside(), Multipole::isInside(), RFCavity::isInside(), Solenoid::isInside(), and TravelingWave::isInside().
isPositioned()
bool ElementBase::isPositioned () const inline inherited
Definition at line 598 of file ElementBase.h.
References ElementBase::positionIsFixed.
Referenced by OpalRBend::update(), and OpalSBend::update().
isSharable()
bool ElementBase::isSharable () const inline inherited
Test if the element can be shared.
Definition at line 506 of file ElementBase.h.
References ElementBase::shareFlag.
Referenced by ElementBase::copyStructure(), and Sequence::updateList().
makeSharable()
void ElementBase::makeSharable () virtual inherited
Set sharable flag.
Reimplemented in TBeamline< T >.
Definition at line 201 of file ElementBase.cpp.
References ElementBase::shareFlag.
Referenced by OpalMarker::OpalMarker().
Online()
bool Component::Online () virtual inherited
Definition at line 47 of file Component.cpp.
References Component::online_m.
operator=()
void SolenoidRep::operator= (const SolenoidRep &) private
releasePosition()
void ElementBase::releasePosition () inline inherited
Definition at line 594 of file ElementBase.h.
References ElementBase::positionIsFixed.
Referenced by OpalRBend::update(), and OpalSBend::update().
removeAttribute()
void ElementBase::removeAttribute (const std::string & aKey) virtual inherited
Remove an existing attribute.
Definition at line 169 of file ElementBase.cpp.
References AttributeSet::removeAttribute(), and ElementBase::userAttribs.
setActionRange()
void ElementBase::setActionRange (const std::queue< std::pair< double, double > > & range) inline inherited
Definition at line 600 of file ElementBase.h.
References ElementBase::actionRange_m, and ElementBase::elementEdge_m.
setAperture()
void ElementBase::setAperture (const ApertureType & type, const std::vector< double > & args) inline inherited
Definition at line 576 of file ElementBase.h.
References ElementBase::aperture_m.
Referenced by Component::Component(), TEST_F(), TEST_F(), TEST_F(), OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
setAttribute()
void ElementBase::setAttribute (const std::string & aKey, double val) virtual inherited
Set value of an attribute.
Definition at line 171 of file ElementBase.cpp.
References ElementBase::getChannel(), and Channel::isSettable().
Referenced by ElementBase::update(), and OpalElement::updateUnknown().
setBoundaryGeometry()
void ElementBase::setBoundaryGeometry (BoundaryGeometry * geo) virtual inherited
attach a boundary geometry field to the element
Definition at line 215 of file ElementBase.cpp.
References ElementBase::bgeometry_m.
setBz()
void SolenoidRep::setBz (double Bz) virtual
Set field.
Definition at line 65 of file SolenoidRep.cpp.
References field, and ConstBzField::setBz().
Referenced by OpalSolenoid::update().
setCSTrafoGlobal2Local()
void ElementBase::setCSTrafoGlobal2Local (const CoordinateSystemTrafo & ori) inline inherited
Definition at line 522 of file ElementBase.h.
References ElementBase::csTrafoGlobal2Local_m, and ElementBase::positionIsFixed.
Referenced by ElementBase::setPlacementPose(), TEST_F(), OpalElement::update(), OpalRBend::update(), and OpalSBend::update().
setCurrentSCoordinate()
void ElementBase::setCurrentSCoordinate (double s) inherited
Definition at line 223 of file ElementBase.cpp.
References ElementBase::actionRange_m, and ElementBase::elementEdge_m.
setDesignEnergy()
void Component::setDesignEnergy (const double & energy, bool changeable = true) inline virtual inherited
Reimplemented in Corrector, RFCavity, and BendBase.
Definition at line 252 of file Component.h.
setDKS()
void Solenoid::setDKS (double ks) inherited
Set the strength scaling error dks.
Definition at line 159 of file Solenoid.cpp.
References Solenoid::scaleError_m.
Referenced by OpalSolenoid::update().
setElementLength()
void ElementBase::setElementLength (double length) inline virtual inherited
Set design length.
Reimplemented in MultipoleT, and ConstantEFieldCavityRep.
Definition at line 482 of file ElementBase.h.
References ElementBase::getGeometry(), and BGeometryBase::setElementLength().
Referenced by MultipoleT::setElementLength(), SequenceMember::setLength(), BendBase::setLength(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), OpalCavity::update(), OpalMonitor::update(), OpalMultipole::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalSolenoid::update(), and OpalTravelingWave::update().
setElementPosition()
void ElementBase::setElementPosition (double elemedge) inline inherited
Access to ELEMEDGE attribute.
Definition at line 612 of file ElementBase.h.
References ElementBase::elemedgeSet_m, and ElementBase::elementPosition_m.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and OpalElement::update().
setExitFaceSlope()
void Component::setExitFaceSlope (const double & m) inline inherited
Definition at line 250 of file Component.h.
References Component::exit_face_slope_m.
setFast()
void Solenoid::setFast (bool fast) inherited
Set the fast flag.
Definition at line 216 of file Solenoid.cpp.
References Solenoid::fast_m.
Referenced by OpalSolenoid::update().
setFieldMapFN()
void Solenoid::setFieldMapFN (std::string fn) inherited
Assign the field filename.
Definition at line 213 of file Solenoid.cpp.
References Solenoid::filename_m.
Referenced by TEST_F(), TEST_F(), TEST_F(), and OpalSolenoid::update().
setFlagDeleteOnTransverseExit()
void ElementBase::setFlagDeleteOnTransverseExit (bool flag = true) inline inherited
Definition at line 629 of file ElementBase.h.
References ElementBase::deleteOnTransverseExit_m.
Referenced by OpalElement::update().
setKS()
void Solenoid::setKS (double ks) inherited
Set the strength scaling factor ks.
Definition at line 156 of file Solenoid.cpp.
References Solenoid::scale_m.
Referenced by OpalSolenoid::update().
setMisalignment()
void ElementBase::setMisalignment (const CoordinateSystemTrafo & cst) inline inherited
Definition at line 590 of file ElementBase.h.
References ElementBase::misalignment_m.
Referenced by TEST_F(), and OpalElement::update().
setName()
void ElementBase::setName (const std::string & name) virtual inherited
Set element name.
Definition at line 133 of file ElementBase.cpp.
References ElementBase::elementID.
Referenced by Sequence::insertDrifts(), and VariableRFCavity::operator=().
setOutputFN()
void ElementBase::setOutputFN (std::string fn) inherited
Set output filename.
Definition at line 135 of file ElementBase.cpp.
References ElementBase::outputfn_m.
Referenced by OpalMonitor::update(), and OpalProbe::update().
setParticleMatterInteraction()
void ElementBase::setParticleMatterInteraction (ParticleMatterInteractionHandler * spys) virtual inherited
Definition at line 219 of file ElementBase.cpp.
References ElementBase::parmatint_m.
setPlacementPose()
void ElementBase::setPlacementPose (const PlacementPose & pose) inline inherited
Set the nominal rigid placement transform of the element.
This bridge setter preserves the existing storage model by delegating to setCSTrafoGlobal2Local().
Definition at line 554 of file ElementBase.h.
References PlacementPose::getParentToNominal(), and ElementBase::setCSTrafoGlobal2Local().
setRotationAboutZ()
void ElementBase::setRotationAboutZ (double rotation) inline inherited
Set rotation about z axis in bend frame.
Definition at line 606 of file ElementBase.h.
References ElementBase::rotationZAxis_m.
Referenced by OpalElement::update().
setWake()
void ElementBase::setWake (WakeFunction * wf) virtual inherited
attach a wake field to the element
Definition at line 211 of file ElementBase.cpp.
References ElementBase::wake_m.
trackBunch()
void Component::trackBunch (PartBunch_t & bunch, const PartData & , bool revBeam, bool revTrack) const virtual inherited
Track a borrowed particle bunch through a non-standard component.
The default implementation throws a LogicalError.
Parameters
bunch Particle bunch to track. The component does not take ownership.
Definition at line 35 of file Component.cpp.
References ElementBase::getName().
Referenced by Tracker::visitComponent().
trackMap()
void Component::trackMap (FVps< double, 6 > & map, const PartData & , bool revBeam, bool revTrack) const virtual inherited
Track a map.
Definition at line 39 of file Component.cpp.
References ElementBase::getName().
update()
bool ElementBase::update (const AttributeSet & set) inherited
Update element.
Definition at line 203 of file ElementBase.cpp.
References AttributeSet::begin(), AttributeSet::end(), and ElementBase::setAttribute().
Member Data Documentation
actionRange_m
std::queue<std::pair<double, double> > ElementBase::actionRange_m private inherited
Definition at line 468 of file ElementBase.h.
Referenced by ElementBase::setActionRange(), and ElementBase::setCurrentSCoordinate().
aperture_m
std::pair<ApertureType, std::vector<double> > ElementBase::aperture_m protected inherited
Definition at line 439 of file ElementBase.h.
Referenced by ElementBase::getAperture(), ElementBase::getBoundingBoxInLabCoords(), ElementBase::isInsideTransverse(), and ElementBase::setAperture().
bgeometry_m
BoundaryGeometry* ElementBase::bgeometry_m private inherited
Definition at line 459 of file ElementBase.h.
Referenced by ElementBase::getBoundaryGeometry(), ElementBase::hasBoundaryGeometry(), and ElementBase::setBoundaryGeometry().
csTrafoGlobal2Local_m
CoordinateSystemTrafo ElementBase::csTrafoGlobal2Local_m protected inherited
Definition at line 436 of file ElementBase.h.
Referenced by ElementBase::getBoundingBoxInLabCoords(), ElementBase::getCSTrafoGlobal2Local(), and ElementBase::setCSTrafoGlobal2Local().
defaultAperture_m
const std::vector< double > Component::defaultAperture_m = std::vector<double>({1e6, 1e6, 1.0}) static protected inherited
Definition at line 221 of file Component.h.
Referenced by Component::Component().
deleteOnTransverseExit_m
bool ElementBase::deleteOnTransverseExit_m = true private inherited
Definition at line 472 of file ElementBase.h.
Referenced by ElementBase::getFlagDeleteOnTransverseExit(), and ElementBase::setFlagDeleteOnTransverseExit().
elemedgeSet_m
bool ElementBase::elemedgeSet_m private inherited
Definition at line 466 of file ElementBase.h.
Referenced by ElementBase::getElementPosition(), ElementBase::isElementPositionSet(), and ElementBase::setElementPosition().
elementEdge_m
double ElementBase::elementEdge_m protected inherited
Definition at line 441 of file ElementBase.h.
Referenced by ElementBase::setActionRange(), and ElementBase::setCurrentSCoordinate().
elementID
std::string ElementBase::elementID private inherited
Definition at line 450 of file ElementBase.h.
Referenced by ElementBase::getName(), and ElementBase::setName().
elementPosition_m
double ElementBase::elementPosition_m private inherited
ELEMEDGE attribute.
Definition at line 465 of file ElementBase.h.
Referenced by ElementBase::getElementPosition(), and ElementBase::setElementPosition().
elementTypeToString_s
const std::map< ElementType, std::string > ElementBase::elementTypeToString_s static private inherited
Initial value:
= {
        {ElementType::ANY, "Any"},
        {ElementType::BEAMLINE, "Beamline"},
        {ElementType::DRIFT, "Drift"},
        {ElementType::LASER, "Laser"},
        {ElementType::MARKER, "Marker"},
        {ElementType::MULTIPOLE, "Multipole"},
        {ElementType::RFCAVITY, "RFCavity"},
        {ElementType::TRAVELINGWAVE, "TravelingWave"},
        {ElementType::SBEND, "SBEND"},
        {ElementType::RBEND, "RBEND"},
        {ElementType::RBEND3D, "RBEND3D"},
        {ElementType::RING, "Ring"},
        {ElementType::SOURCE, "SOURCE"},
        {ElementType::SOLENOID, "SOLENOID"},
        {ElementType::PROBE, "Probe"},
        {ElementType::VACUUM, "Vacuum"},
        {ElementType::CONSTANTEFIELDCAVITY, "ConstantEFieldCavity"}}
Definition at line 73 of file ElementBase.h.
Referenced by ElementBase::getTypeString().
endField_m
double Solenoid::endField_m private inherited
End point of the field support in the local chart.
Definition at line 200 of file Solenoid.h.
Referenced by Solenoid::apply(), Solenoid::applyToReferenceParticle(), Solenoid::getFieldExtend(), and Solenoid::initialise().
exit_face_slope_m
double Component::exit_face_slope_m protected inherited
Definition at line 222 of file Component.h.
Referenced by Component::setExitFaceSlope().
fast_m
bool Solenoid::fast_m private inherited
Fast tracking flag.
Note
currently not implemented
Definition at line 203 of file Solenoid.h.
Referenced by Solenoid::getFast(), Solenoid::initialise(), and Solenoid::setFast().
field
ConstBzField SolenoidRep::field private
The solenoid field.
Definition at line 76 of file SolenoidRep.h.
Referenced by getBz(), getField(), getField(), and setBz().
fieldmap_m
Fieldmap* Solenoid::fieldmap_m private inherited
Fieldmap pointer.
Definition at line 188 of file Solenoid.h.
Referenced by Solenoid::apply(), Solenoid::apply(), Solenoid::applyToReferenceParticle(), Solenoid::getSupportEnvelope(), Solenoid::initialise(), and Solenoid::isInside().
filename_m
std::string Solenoid::filename_m private inherited
Name of the field map file.
Definition at line 185 of file Solenoid.h.
Referenced by Solenoid::goOffline(), Solenoid::goOnline(), Solenoid::initialise(), and Solenoid::setFieldMapFN().
geometry
StraightGeometry SolenoidRep::geometry private
The solenoid geometry.
Definition at line 73 of file SolenoidRep.h.
Referenced by getGeometry(), and getGeometry().
misalignment_m
CoordinateSystemTrafo ElementBase::misalignment_m protected inherited
Definition at line 437 of file ElementBase.h.
Referenced by ElementBase::getMisalignment(), and ElementBase::setMisalignment().
online_m
bool Component::online_m protected inherited
Definition at line 226 of file Component.h.
Referenced by Probe::doGoOffline(), PluginElement::finalise(), BendBase::finalise(), Multipole::finalise(), Ring::finalise(), Component::goOffline(), PluginElement::goOffline(), RFCavity::goOffline(), Solenoid::goOffline(), Component::goOnline(), Corrector::goOnline(), Monitor::goOnline(), RFCavity::goOnline(), Solenoid::goOnline(), TravelingWave::goOnline(), Ring::initialise(), BendBase::initialise(), Multipole::initialise(), Component::Online(), and PluginElement::~PluginElement().
outputfn_m
std::string ElementBase::outputfn_m private inherited
The name of the outputfile
Definition at line 470 of file ElementBase.h.
Referenced by ElementBase::getOutputFN(), and ElementBase::setOutputFN().
parmatint_m
ParticleMatterInteractionHandler* ElementBase::parmatint_m private inherited
Definition at line 461 of file ElementBase.h.
Referenced by ElementBase::getParticleMatterInteraction(), ElementBase::hasParticleMatterInteraction(), and ElementBase::setParticleMatterInteraction().
positionIsFixed
bool ElementBase::positionIsFixed private inherited
Definition at line 463 of file ElementBase.h.
Referenced by ElementBase::fixPosition(), ElementBase::isPositioned(), ElementBase::releasePosition(), and ElementBase::setCSTrafoGlobal2Local().
RefPartBunch_m
PartBunch_t* Component::RefPartBunch_m protected inherited
Definition at line 225 of file Component.h.
Referenced by Corrector::apply(), VerticalFFAMagnet::apply(), BendBase::apply(), ConstantEFieldCavity::apply(), Multipole::apply(), MultipoleT::apply(), RFCavity::apply(), ScalingFFAMagnet::apply(), Solenoid::apply(), TravelingWave::apply(), VariableRFCavity::apply(), Ring::apply(), MultipoleT::apply(), RFCavity::apply(), TravelingWave::apply(), VariableRFCavity::apply(), Corrector::apply(), BendBase::calcDesignRadius(), BendBase::calcFieldAmplitude(), BendBase::calcGamma(), VerticalFFAMagnet::finalise(), MultipoleT::finalise(), ScalingFFAMagnet::finalise(), VariableRFCavity::finalise(), Corrector::goOnline(), PluginElement::initialise(), Corrector::initialise(), VerticalFFAMagnet::initialise(), BendBase::initialise(), ConstantEFieldCavity::initialise(), Drift::initialise(), Laser::initialise(), Marker::initialise(), Monitor::initialise(), Multipole::initialise(), MultipoleT::initialise(), RFCavity::initialise(), ScalingFFAMagnet::initialise(), Solenoid::initialise(), TravelingWave::initialise(), VariableRFCavity::initialise(), RFCavity::initialise(), VariableRFCavity::initNull(), Multipole::isFocusing(), MultipoleT::MultipoleT(), ScalingFFAMagnet::ScalingFFAMagnet(), Corrector::setDesignEnergy(), Ring::setRefPartBunch(), RFCavity::trackOnAxisParticle(), and VerticalFFAMagnet::VerticalFFAMagnet().
rotationZAxis_m
double ElementBase::rotationZAxis_m protected inherited
Definition at line 443 of file ElementBase.h.
Referenced by ElementBase::getRotationAboutZ(), and ElementBase::setRotationAboutZ().
scale_m
double Solenoid::scale_m private inherited
Scale multiplier.
Definition at line 191 of file Solenoid.h.
Referenced by Solenoid::apply(), Solenoid::apply(), Solenoid::applyToReferenceParticle(), and Solenoid::setKS().
scaleError_m
double Solenoid::scaleError_m private inherited
Scale error multiplier.
Definition at line 194 of file Solenoid.h.
Referenced by Solenoid::apply(), Solenoid::apply(), and Solenoid::setDKS().
shareFlag
bool ElementBase::shareFlag mutable protected inherited
Definition at line 434 of file ElementBase.h.
Referenced by Beamline::Beamline(), Beamline::Beamline(), Beamline::Beamline(), ElementBase::isSharable(), and ElementBase::makeSharable().
startField_m
double Solenoid::startField_m private inherited
Starting point of the field.
Definition at line 197 of file Solenoid.h.
Referenced by Solenoid::apply(), Solenoid::applyToReferenceParticle(), Solenoid::getFieldExtend(), and Solenoid::initialise().
userAttribs
AttributeSet ElementBase::userAttribs private inherited
Definition at line 455 of file ElementBase.h.
Referenced by ElementBase::getChannel(), and ElementBase::removeAttribute().
wake_m
WakeFunction* ElementBase::wake_m private inherited
Definition at line 457 of file ElementBase.h.
Referenced by ElementBase::getWake(), ElementBase::hasWake(), and ElementBase::setWake().
The documentation for this class was generated from the following files:
SolenoidRep.h
SolenoidRep.cpp