var dir_fb8bdcd0f0d978eb351f718e3f696688 =
[
    [ "Interpolation", "dir_b70e205c179d1cbf89dd9add5344e749.html", "dir_b70e205c179d1cbf89dd9add5344e749" ],
    [ "AcceleratingField.h", "AcceleratingField_8h.html", "AcceleratingField_8h" ],
    [ "Astra1DDynamic.cpp", "Astra1DDynamic_8cpp.html", null ],
    [ "Astra1DDynamic.h", "Astra1DDynamic_8h.html", "Astra1DDynamic_8h" ],
    [ "BDipoleField.cpp", "BDipoleField_8cpp.html", null ],
    [ "BDipoleField.h", "BDipoleField_8h.html", "BDipoleField_8h" ],
    [ "BMultipoleField.cpp", "BMultipoleField_8cpp.html", null ],
    [ "BMultipoleField.h", "BMultipoleField_8h.html", "BMultipoleField_8h" ],
    [ "ConstBField.cpp", "ConstBField_8cpp.html", null ],
    [ "ConstBField.h", "ConstBField_8h.html", "ConstBField_8h" ],
    [ "ConstBzField.cpp", "ConstBzField_8cpp.html", null ],
    [ "ConstBzField.h", "ConstBzField_8h.html", "ConstBzField_8h" ],
    [ "ConstEzField.cpp", "ConstEzField_8cpp.html", null ],
    [ "ConstEzField.h", "ConstEzField_8h.html", "ConstEzField_8h" ],
    [ "Definitions.h", "Definitions_8h.html", "Definitions_8h" ],
    [ "EMField.cpp", "EMField_8cpp.html", null ],
    [ "EMField.h", "EMField_8h.html", "EMField_8h" ],
    [ "Fieldmap.cpp", "Fieldmap_8cpp.html", "Fieldmap_8cpp" ],
    [ "Fieldmap.h", "Fieldmap_8h.html", "Fieldmap_8h" ],
    [ "Fieldmap.hpp", "Fieldmap_8hpp.html", null ],
    [ "FM2DDynamic.cpp", "FM2DDynamic_8cpp.html", null ],
    [ "FM2DDynamic.h", "FM2DDynamic_8h.html", "FM2DDynamic_8h" ],
    [ "FM2DMagnetoStatic.cpp", "FM2DMagnetoStatic_8cpp.html", null ],
    [ "FM2DMagnetoStatic.h", "FM2DMagnetoStatic_8h.html", "FM2DMagnetoStatic_8h" ],
    [ "NullField.cpp", "NullField_8cpp.html", null ],
    [ "NullField.h", "NullField_8h.html", "NullField_8h" ],
    [ "OscillatingField.h", "OscillatingField_8h.html", "OscillatingField_8h" ],
    [ "StaticElectricField.cpp", "StaticElectricField_8cpp.html", null ],
    [ "StaticElectricField.h", "StaticElectricField_8h.html", "StaticElectricField_8h" ],
    [ "StaticMagneticField.cpp", "StaticMagneticField_8cpp.html", null ],
    [ "StaticMagneticField.h", "StaticMagneticField_8h.html", "StaticMagneticField_8h" ]
];