var dir_0df09a091a4eb5e56719829019e3d2f9 =
[
    [ "Air.h", "Air_8h.html", "Air_8h" ],
    [ "AluminaAL2O3.h", "AluminaAL2O3_8h.html", "AluminaAL2O3_8h" ],
    [ "Aluminum.h", "Aluminum_8h.html", "Aluminum_8h" ],
    [ "Beryllium.h", "Beryllium_8h.html", "Beryllium_8h" ],
    [ "BoronCarbide.h", "BoronCarbide_8h.html", "BoronCarbide_8h" ],
    [ "Copper.h", "Copper_8h.html", "Copper_8h" ],
    [ "Gold.h", "Gold_8h.html", "Gold_8h" ],
    [ "Graphite.h", "Graphite_8h.html", "Graphite_8h" ],
    [ "GraphiteR6710.h", "GraphiteR6710_8h.html", "GraphiteR6710_8h" ],
    [ "Kapton.h", "Kapton_8h.html", "Kapton_8h" ],
    [ "LinearBreitWheeler.cpp", "LinearBreitWheeler_8cpp.html", "LinearBreitWheeler_8cpp" ],
    [ "LinearBreitWheeler.h", "LinearBreitWheeler_8h.html", "LinearBreitWheeler_8h" ],
    [ "LinearCompton.cpp", "LinearCompton_8cpp.html", "LinearCompton_8cpp" ],
    [ "LinearCompton.h", "LinearCompton_8h.html", "LinearCompton_8h" ],
    [ "Material.cpp", "Material_8cpp.html", null ],
    [ "Material.h", "Material_8h.html", "Material_8h" ],
    [ "Molybdenum.h", "Molybdenum_8h.html", "Molybdenum_8h" ],
    [ "MuonDecay.h", "Physics_2MuonDecay_8h.html", "Physics_2MuonDecay_8h" ],
    [ "Mylar.h", "Mylar_8h.html", "Mylar_8h" ],
    [ "ParticleProperties.cpp", "ParticleProperties_8cpp.html", null ],
    [ "ParticleProperties.h", "ParticleProperties_8h.html", "ParticleProperties_8h" ],
    [ "Physics.h", "Physics_8h.html", "Physics_8h" ],
    [ "Titanium.h", "Titanium_8h.html", "Titanium_8h" ],
    [ "Units.h", "Units_8h.html", "Units_8h" ],
    [ "Water.h", "Water_8h.html", "Water_8h" ]
];