OPALX (Object Oriented Parallel Accelerator Library for Exascal): GSLEigen.h File Reference
GSLEigen.h File Reference
#include "Utilities/GSLMatrix.h"
#include "Utilities/GSLComplex.h"
#include <vector>
#include <cmath>
#include <complex>
Classes
struct gsl_eigen_nonsymm_workspace
Workspace for nonsymmetric eigenvalue computation.
struct gsl_eigen_nonsymmv_workspace
Workspace for nonsymmetric eigenvalues/eigenvectors.
Functions
gsl_eigen_nonsymm_workspace * gsl_eigen_nonsymm_alloc (size_t n)
Allocate a nonsymmetric eigenvalue workspace for \(n \times n\) matrices.
void gsl_eigen_nonsymm_params (int, int, gsl_eigen_nonsymm_workspace *)
Accept GSL-style parameters (no-op in this implementation).
void gsl_eigen_nonsymm_free (gsl_eigen_nonsymm_workspace *w)
Free a workspace allocated by gsl_eigen_nonsymm_alloc.
gsl_eigen_nonsymmv_workspace * gsl_eigen_nonsymmv_alloc (size_t n)
Allocate a nonsymmetric eigenvalue/vector workspace for \(n \times n\) matrices.
void gsl_eigen_nonsymmv_free (gsl_eigen_nonsymmv_workspace *w)
Free a workspace allocated by gsl_eigen_nonsymmv_alloc.
int gsl_eigen_nonsymm (gsl_matrix *A, gsl_vector_complex *eval, gsl_eigen_nonsymm_workspace *)
Compute eigenvalues of a real nonsymmetric matrix.
int gsl_eigen_nonsymmv (gsl_matrix *A, gsl_vector_complex *eval, gsl_matrix_complex *evec, gsl_eigen_nonsymmv_workspace *w)
Compute eigenvalues and a simplified set of eigenvectors.
Function Documentation
gsl_eigen_nonsymm()
int gsl_eigen_nonsymm (gsl_matrix * A, gsl_vector_complex * eval, gsl_eigen_nonsymm_workspace *) inline
Compute eigenvalues of a real nonsymmetric matrix.
See also
https://www.gnu.org/software/gsl/doc/html/eigen.html
Uses a basic QR iteration to approximate eigenvalues for small matrices.
Parameters
A Input: matrix (read-only; may be modified by algorithm).
eval Output: vector of eigenvalues (complex).
w Input: workspace (unused).
Returns
Output: 0 on success, -1 on size mismatch.
Definition at line 97 of file GSLEigen.h.
References dot(), gsl_matrix_ptr(), gsl_vector_complex_ptr(), gsl_vector_complex::size, gsl_matrix::size1, and gsl_matrix::size2.
Referenced by interpolation::MMatrix< Tmplt >::eigenvalues(), gsl_eigen_nonsymmv(), TEST_F(), TEST_F(), and TEST_F().
gsl_eigen_nonsymm_alloc()
gsl_eigen_nonsymm_workspace * gsl_eigen_nonsymm_alloc (size_t n) inline
Allocate a nonsymmetric eigenvalue workspace for \(n \times n\) matrices.
See also
https://www.gnu.org/software/gsl/doc/html/eigen.html
Parameters
n Input: matrix dimension.
Returns
Output: workspace pointer.
Definition at line 49 of file GSLEigen.h.
References gsl_eigen_nonsymm_workspace::n, and gsl_eigen_nonsymm_workspace::work.
Referenced by interpolation::MMatrix< Tmplt >::eigenvalues(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
gsl_eigen_nonsymm_free()
void gsl_eigen_nonsymm_free (gsl_eigen_nonsymm_workspace * w) inline
Free a workspace allocated by gsl_eigen_nonsymm_alloc.
See also
https://www.gnu.org/software/gsl/doc/html/eigen.html
Parameters
w Input: workspace to release (can be null).
Definition at line 68 of file GSLEigen.h.
Referenced by interpolation::MMatrix< Tmplt >::eigenvalues(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
gsl_eigen_nonsymm_params()
void gsl_eigen_nonsymm_params (int , int , gsl_eigen_nonsymm_workspace *) inline
Accept GSL-style parameters (no-op in this implementation).
See also
https://www.gnu.org/software/gsl/doc/html/eigen.html
Parameters
balance Input: balancing flag (unused).
compute_shur Input: Schur computation flag (unused).
w Input: workspace (unused).
Definition at line 61 of file GSLEigen.h.
Referenced by interpolation::MMatrix< Tmplt >::eigenvalues().
gsl_eigen_nonsymmv()
int gsl_eigen_nonsymmv (gsl_matrix * A, gsl_vector_complex * eval, gsl_matrix_complex * evec, gsl_eigen_nonsymmv_workspace * w) inline
Compute eigenvalues and a simplified set of eigenvectors.
See also
https://www.gnu.org/software/gsl/doc/html/eigen.html
Eigenvectors are approximated with a basic heuristic per eigenvalue.
Parameters
A Input: matrix (read-only; may be modified by algorithm).
eval Output: vector of eigenvalues (complex).
evec Output: matrix of eigenvectors in columns.
w Input: workspace (unused aside from type).
Returns
Output: 0 on success, -1 on size mismatch.
Definition at line 196 of file GSLEigen.h.
References gsl_complex_sub(), gsl_eigen_nonsymm(), gsl_matrix_complex_alloc(), gsl_matrix_complex_free(), gsl_matrix_complex_ptr(), gsl_matrix_ptr(), gsl_vector_complex_ptr(), and gsl_matrix::size1.
Referenced by interpolation::MMatrix< Tmplt >::eigenvectors(), TEST_F(), and TEST_F().
gsl_eigen_nonsymmv_alloc()
gsl_eigen_nonsymmv_workspace * gsl_eigen_nonsymmv_alloc (size_t n) inline
Allocate a nonsymmetric eigenvalue/vector workspace for \(n \times n\) matrices.
See also
https://www.gnu.org/software/gsl/doc/html/eigen.html
Parameters
n Input: matrix dimension.
Returns
Output: workspace pointer.
Definition at line 76 of file GSLEigen.h.
References gsl_eigen_nonsymmv_workspace::n, and gsl_eigen_nonsymmv_workspace::work.
Referenced by interpolation::MMatrix< Tmplt >::eigenvectors(), TEST_F(), TEST_F(), and TEST_F().
gsl_eigen_nonsymmv_free()
void gsl_eigen_nonsymmv_free (gsl_eigen_nonsymmv_workspace * w) inline
Free a workspace allocated by gsl_eigen_nonsymmv_alloc.
See also
https://www.gnu.org/software/gsl/doc/html/eigen.html
Parameters
w Input: workspace to release (can be null).
Definition at line 86 of file GSLEigen.h.
Referenced by interpolation::MMatrix< Tmplt >::eigenvectors(), TEST_F(), TEST_F(), and TEST_F().