OPALX (Object Oriented Parallel Accelerator Library for Exascal): GSLIntegration.h File Reference
GSLIntegration.h File Reference
#include <cmath>
#include <functional>
#include <vector>
Classes
struct gsl_integration_workspace
Workspace for adaptive integration routines.
struct gsl_function
Function wrapper used by integration routines.
Functions
gsl_integration_workspace * gsl_integration_workspace_alloc (size_t n)
Allocate integration workspace with limit \(n\).
void gsl_integration_workspace_free (gsl_integration_workspace *w)
Free a workspace allocated by gsl_integration_workspace_alloc.
int gsl_integration_qag (const gsl_function *f, double a, double b, double epsabs, double epsrel, size_t, int, gsl_integration_workspace *, double *result, double *abserr)
Adaptive integration on \([a,b]\) using Simpson refinement.
Variables
constexpr int GSL_INTEG_GAUSS15 = 1
Integration rule identifiers (accepted but not used in this implementation).
constexpr int GSL_INTEG_GAUSS21 = 2
constexpr int GSL_INTEG_GAUSS31 = 3
constexpr int GSL_INTEG_GAUSS41 = 4
constexpr int GSL_INTEG_GAUSS51 = 5
constexpr int GSL_INTEG_GAUSS61 = 6
Class Documentation
gsl_function
struct gsl_function
Function wrapper used by integration routines.
See also
https://www.gnu.org/software/gsl/doc/html/roots.html
Parameters
function Input: callback \(f(x,\mathrm{params})\).
params Input: opaque parameters passed to function.
Definition at line 67 of file GSLIntegration.h.
Class Members
double(*)(double x, void *params) function
void * params
Function Documentation
gsl_integration_qag()
int gsl_integration_qag (const gsl_function * f, double a, double b, double epsabs, double epsrel, size_t , int , gsl_integration_workspace * , double * result, double * abserr) inline
Adaptive integration on \([a,b]\) using Simpson refinement.
See also
https://www.gnu.org/software/gsl/doc/html/integration.html
Computes an approximation of \(\int_a^b f(x)\,dx\) with absolute tolerance epsabs and relative tolerance epsrel.
Parameters
f Input: integrand.
a Input: lower limit.
b Input: upper limit.
epsabs Input: absolute error tolerance.
epsrel Input: relative error tolerance.
limit Input: maximum subintervals (unused).
key Input: quadrature rule selector (unused).
workspace Input: workspace (unused).
result Output: estimated integral value.
abserr Output: estimated absolute error.
Returns
Output: 0 on success.
Definition at line 121 of file GSLIntegration.h.
References gsl_function::function, and gsl_function::params.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
gsl_integration_workspace_alloc()
gsl_integration_workspace * gsl_integration_workspace_alloc (size_t n) inline
Allocate integration workspace with limit \(n\).
See also
https://www.gnu.org/software/gsl/doc/html/integration.html
Parameters
n Input: maximum number of subintervals.
Returns
Output: pointer to newly allocated workspace.
Definition at line 47 of file GSLIntegration.h.
References gsl_integration_workspace::alist, gsl_integration_workspace::blist, gsl_integration_workspace::elist, gsl_integration_workspace::limit, gsl_integration_workspace::order, and gsl_integration_workspace::rlist.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
gsl_integration_workspace_free()
void gsl_integration_workspace_free (gsl_integration_workspace * w) inline
Free a workspace allocated by gsl_integration_workspace_alloc.
See also
https://www.gnu.org/software/gsl/doc/html/integration.html
Parameters
w Input: workspace to release (can be null).
Definition at line 61 of file GSLIntegration.h.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
Variable Documentation
GSL_INTEG_GAUSS15
int GSL_INTEG_GAUSS15 = 1 constexpr
Integration rule identifiers (accepted but not used in this implementation).
Definition at line 140 of file GSLIntegration.h.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
GSL_INTEG_GAUSS21
int GSL_INTEG_GAUSS21 = 2 constexpr
Definition at line 141 of file GSLIntegration.h.
GSL_INTEG_GAUSS31
int GSL_INTEG_GAUSS31 = 3 constexpr
Definition at line 142 of file GSLIntegration.h.
GSL_INTEG_GAUSS41
int GSL_INTEG_GAUSS41 = 4 constexpr
Definition at line 143 of file GSLIntegration.h.
GSL_INTEG_GAUSS51
int GSL_INTEG_GAUSS51 = 5 constexpr
Definition at line 144 of file GSLIntegration.h.
GSL_INTEG_GAUSS61
int GSL_INTEG_GAUSS61 = 6 constexpr
Definition at line 145 of file GSLIntegration.h.