OPALX (Object Oriented Parallel Accelerator Library for Exascal): GSLSpline.h File Reference
GSLSpline.h File Reference
#include "CubicSpline.h"
#include "LinearSpline.h"
Typedefs
using gsl_spline = AbstractSpline
GSL-compatible spline type alias.
using gsl_interp_accel = AbstractSpline::Accelerator
GSL-compatible accelerator type alias.
Functions
gsl_spline * gsl_spline_alloc (const int type, size_t)
Allocate a spline instance (size ignored).
gsl_interp_accel * gsl_interp_accel_alloc ()
Allocate an interpolation accelerator.
void gsl_spline_init (gsl_spline *spline, const double *x, const double *y, const size_t n)
Initialize a spline with tabulated data.
double gsl_spline_eval (const gsl_spline *spline, const double x, gsl_interp_accel *accel)
Evaluate a spline at x using an accelerator.
double gsl_spline_eval_integ (const gsl_spline *spline, const double xa, const double xb, gsl_interp_accel *accel)
Evaluate the integral of a spline at x using an accelerator.
void gsl_spline_free (const gsl_spline *spline)
Free a spline instance.
void gsl_interp_accel_free (const gsl_interp_accel *accel)
Free an accelerator instance.
void gsl_interp_accel_reset (gsl_interp_accel *accel)
Reset an accelerator to the initial state.
Variables
constexpr int gsl_interp_linear = 1
GSL linear interpolation type identifiers.
constexpr int gsl_interp_cspline = 0
Typedef Documentation
gsl_interp_accel
using gsl_interp_accel = AbstractSpline::Accelerator
GSL-compatible accelerator type alias.
Definition at line 32 of file GSLSpline.h.
gsl_spline
using gsl_spline = AbstractSpline
GSL-compatible spline type alias.
Definition at line 29 of file GSLSpline.h.
Function Documentation
gsl_interp_accel_alloc()
gsl_interp_accel * gsl_interp_accel_alloc () inline
Allocate an interpolation accelerator.
Returns
Output: accelerator pointer.
Definition at line 50 of file GSLSpline.h.
Referenced by RFCavity::getAutoPhaseEstimate(), Astra1DDynamic::readMap(), and TEST_F().
gsl_interp_accel_free()
void gsl_interp_accel_free (const gsl_interp_accel * accel) inline
Free an accelerator instance.
Parameters
accel Input: accelerator to release (can be null).
Definition at line 87 of file GSLSpline.h.
Referenced by RFCavity::getAutoPhaseEstimate(), Astra1DDynamic::readMap(), and TEST_F().
gsl_interp_accel_reset()
void gsl_interp_accel_reset (gsl_interp_accel * accel) inline
Reset an accelerator to the initial state.
Parameters
accel Input/Output: accelerator to reset.
Definition at line 91 of file GSLSpline.h.
References AbstractSpline::Accelerator::reset().
Referenced by TEST_F().
gsl_spline_alloc()
gsl_spline * gsl_spline_alloc (const int type, size_t) inline
Allocate a spline instance (size ignored).
Parameters
type Input: interpolation type
size Input: number of points (unused).
Returns
Output: spline pointer.
Definition at line 38 of file GSLSpline.h.
References gsl_interp_cspline, and gsl_interp_linear.
Referenced by RFCavity::getAutoPhaseEstimate(), Astra1DDynamic::readMap(), and TEST_F().
gsl_spline_eval()
double gsl_spline_eval (const gsl_spline * spline, const double x, gsl_interp_accel * accel) inline
Evaluate a spline at x using an accelerator.
Parameters
spline Input: spline to evaluate.
x Input: x-coordinate.
accel Input/Output: accelerator cache.
Returns
Output: interpolated value.
Definition at line 66 of file GSLSpline.h.
References AbstractSpline::eval().
Referenced by Fieldmap::checkMap(), RFCavity::getAutoPhaseEstimate(), Astra1DDynamic::readMap(), and TEST_F().
gsl_spline_eval_integ()
double gsl_spline_eval_integ (const gsl_spline * spline, const double xa, const double xb, gsl_interp_accel * accel) inline
Evaluate the integral of a spline at x using an accelerator.
Parameters
spline Input: spline to evaluate.
xa Input: lower bound x-coordinate.
xb Input: upper bound x-coordinate.
accel Input/Output: accelerator cache.
Returns
Output: integrated value.
Definition at line 76 of file GSLSpline.h.
References AbstractSpline::evalIntegral().
Referenced by TEST_F().
gsl_spline_free()
void gsl_spline_free (const gsl_spline * spline) inline
Free a spline instance.
Parameters
spline Input: spline to release (can be null).
Definition at line 83 of file GSLSpline.h.
Referenced by RFCavity::getAutoPhaseEstimate(), Astra1DDynamic::readMap(), and TEST_F().
gsl_spline_init()
void gsl_spline_init (gsl_spline * spline, const double * x, const double * y, const size_t n) inline
Initialize a spline with tabulated data.
Parameters
spline Input/Output: spline to initialize.
x Input: strictly increasing x-coordinates.
y Input: y-values corresponding to x.
n Input: number of samples.
Definition at line 57 of file GSLSpline.h.
References AbstractSpline::init().
Referenced by RFCavity::getAutoPhaseEstimate(), Astra1DDynamic::readMap(), and TEST_F().
Variable Documentation
gsl_interp_cspline
constexpr int gsl_interp_cspline = 0 constexpr
Definition at line 26 of file GSLSpline.h.
Referenced by RFCavity::getAutoPhaseEstimate(), gsl_spline_alloc(), Astra1DDynamic::readMap(), and TEST_F().
gsl_interp_linear
constexpr int gsl_interp_linear = 1 constexpr
GSL linear interpolation type identifiers.
Definition at line 25 of file GSLSpline.h.
Referenced by gsl_spline_alloc().