OPALX (Object Oriented Parallel Accelerator Library for Exascal): LinearBreitWheelerBenchmark.cpp File Reference
LinearBreitWheelerBenchmark.cpp File Reference
#include "LinearBreitWheelerBenchmarkCommon.h"
#include "Utilities/Options.h"
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <string>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 129 of file LinearBreitWheelerBenchmark.cpp.
References LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::centralHighEnergyPhotonEnergyGeV, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::centralHighEnergyPhotonEnergyGeV, LinearBreitWheelerBenchmark::JointHistogramConfig::energyBins, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::energyBins, LinearBreitWheelerBenchmark::JointHistogramConfig::energyMaxGeV, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::energyMaxGeV, LinearBreitWheelerBenchmark::JointHistogramConfig::energyMinGeV, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::energyMinGeV, LinearBreitWheelerBenchmark::JointHistogramConfig::highEnergyDirection, LinearBreitWheelerBenchmark::JointHistogramConfig::highEnergyPhotonEnergyGeV, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserDirection, LinearBreitWheelerBenchmark::JointHistogramConfig::laserDirection, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::laserDirection, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserRayleighX_m, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::laserRayleighX_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserRayleighY_m, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::laserRayleighY_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserSigmaT_m, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::laserSigmaT_m, Physics::LinearBreitWheeler::makeHostRandomEngine(), Physics::LinearBreitWheeler::makeSamplingKernel(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::overlapWeighting, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::overlapWeighting, Physics::LinearBreitWheeler::photonEnergyFromWavelengthGeV(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::referenceHighEnergyDirection, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::referenceHighEnergyDirection, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::relativeEnergySpread, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::relativeEnergySpread, LinearBreitWheelerBenchmark::sampledObservable(), Physics::LinearBreitWheeler::sampleEvent(), LinearBreitWheelerBenchmark::sampleFinitePhotonBeamJointHistogram(), LinearBreitWheelerBenchmark::sampleJointHistogram(), LinearBreitWheelerBenchmark::sampleOverlapPhotonBeamState(), LinearBreitWheelerBenchmark::samplePhotonBeamState(), Options::seed, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaS_m, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaS_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaXRad, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaThetaXRad, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaYRad, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaThetaYRad, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaX_m, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaX_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaY_m, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaY_m, LinearBreitWheelerBenchmark::JointHistogramConfig::thetaBins, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::thetaBins, LinearBreitWheelerBenchmark::JointHistogramConfig::thetaMaxRad, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::thetaMaxRad, LinearBreitWheelerBenchmark::JointHistogramConfig::thetaMinRad, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::thetaMinRad, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::wavelength_m, LinearBreitWheelerBenchmark::JointHistogramConfig::wavelength_m, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::wavelength_m, and LinearBreitWheelerBenchmark::writeJointHistogramCSV().