OPALX (Object Oriented Parallel Accelerator Library for Exascal): Matrix.h File Reference
Matrix.h File Reference
#include <Kokkos_Core.hpp>
#include <cassert>
#include <vector>
#include "Ippl.h"
Classes
struct matrix_t< Rows, Cols >
Typedefs
using matrix3x3_t = matrix_t< 3, 3 >
using matrix6x6_t = matrix_t< 6, 6 >
template<unsigned Size>
using vector_t = ippl::Vector< double, Size >
Functions
template<int Rows, int Cols, class T >
KOKKOS_INLINE_FUNCTION T prod_vector (const matrix_t< Rows, Cols > &rotation, const T &vect)
template<int Rows, int Cols, class T >
KOKKOS_INLINE_FUNCTION T prod_vector_transpose (const matrix_t< Rows, Cols > &rotation, const T &vect)
template<int Rows, int Cols>
KOKKOS_INLINE_FUNCTION matrix_t< Cols, Rows > get_transpose (const matrix_t< Rows, Cols > &rotation)
template<int Rows1, int Cols1, int Rows2, int Cols2>
KOKKOS_INLINE_FUNCTION matrix_t< Rows1, Cols2 > prod (const matrix_t< Rows1, Cols1 > &a, const matrix_t< Rows2, Cols2 > &b)
template<int Rows, int Cols>
KOKKOS_INLINE_FUNCTION ippl::Vector< double, static_cast< unsigned >(Rows)> prod_matrix_vector (const matrix_t< Rows, Cols > &m, const ippl::Vector< double, static_cast< unsigned >(Cols)> &v)
Typedef Documentation
matrix3x3_t
using matrix3x3_t = matrix_t<3, 3>
Definition at line 101 of file Matrix.h.
matrix6x6_t
using matrix6x6_t = matrix_t<6, 6>
Definition at line 102 of file Matrix.h.
vector_t
template<unsigned Size> using vector_t = ippl::Vector<double, Size>
Definition at line 107 of file Matrix.h.
Function Documentation
get_transpose()
template<int Rows, int Cols> KOKKOS_INLINE_FUNCTION matrix_t< Cols, Rows > get_transpose (const matrix_t< Rows, Cols > & rotation)
Definition at line 146 of file Matrix.h.
Referenced by CoordinateSystemTrafo::invert().
prod()
template<int Rows1, int Cols1, int Rows2, int Cols2> KOKKOS_INLINE_FUNCTION matrix_t< Rows1, Cols2 > prod (const matrix_t< Rows1, Cols1 > & a, const matrix_t< Rows2, Cols2 > & b)
Definition at line 159 of file Matrix.h.
Referenced by mslang::AffineTransformation::mult(), and TEST_F().
prod_matrix_vector()
template<int Rows, int Cols> KOKKOS_INLINE_FUNCTION ippl::Vector< double, static_cast< unsigned >(Rows)> prod_matrix_vector (const matrix_t< Rows, Cols > & m, const ippl::Vector< double, static_cast< unsigned >(Cols)> & v)
Definition at line 177 of file Matrix.h.
Referenced by mslang::AffineTransformation::transformTo().
prod_vector()
template<int Rows, int Cols, class T > KOKKOS_INLINE_FUNCTION T prod_vector (const matrix_t< Rows, Cols > & rotation, const T & vect)
Definition at line 112 of file Matrix.h.
Referenced by CoordinateSystemTrafo::rotateBunchTo(), CoordinateSystemTrafo::rotateTo(), CoordinateSystemTrafo::transformBunchTo(), and CoordinateSystemTrafo::transformTo().
prod_vector_transpose()
template<int Rows, int Cols, class T > KOKKOS_INLINE_FUNCTION T prod_vector_transpose (const matrix_t< Rows, Cols > & rotation, const T & vect)
Definition at line 129 of file Matrix.h.
Referenced by CoordinateSystemTrafo::rotateBunchFrom(), CoordinateSystemTrafo::rotateFrom(), and CoordinateSystemTrafo::transformBunchFrom().