OPALX (Object Oriented Parallel Accelerator Library for Exascal): cmp_ulp Namespace Reference
cmp_ulp Namespace Reference
Functions
bool almost_eq (double A, double B, double maxDiff=1e-20, int maxUlps=1000)
bool almost_eq_zero (double A, double maxDiff=1e-15)
bool eq (double x, double y)
bool eq_zero (double x)
bool le (double x, double y)
bool le_zero (double x)
bool lt (double x, double y)
bool lt_zero (double x)
bool ge (double x, double y)
bool ge_zero (double x)
bool gt (double x, double y)
bool gt_zero (double x)
Function Documentation
almost_eq()
bool cmp_ulp::almost_eq (double A, double B, double maxDiff = 1e-20, int maxUlps = 1000) inline
Definition at line 237 of file BoundaryGeometry.cpp.
almost_eq_zero()
bool cmp_ulp::almost_eq_zero (double A, double maxDiff = 1e-15) inline
Definition at line 261 of file BoundaryGeometry.cpp.
eq()
bool cmp_ulp::eq (double x, double y) inline
Definition at line 264 of file BoundaryGeometry.cpp.
eq_zero()
bool cmp_ulp::eq_zero (double x) inline
Definition at line 265 of file BoundaryGeometry.cpp.
Referenced by BoundaryGeometry::intersectLineTriangle(), and BoundaryGeometry::intersectTinyLineSegmentBoundary().
ge()
bool cmp_ulp::ge (double x, double y) inline
Definition at line 270 of file BoundaryGeometry.cpp.
Referenced by Voxel::isInside().
ge_zero()
bool cmp_ulp::ge_zero (double x) inline
Definition at line 271 of file BoundaryGeometry.cpp.
Referenced by Voxel::intersect(), and BoundaryGeometry::intersectLineTriangle().
gt()
bool cmp_ulp::gt (double x, double y) inline
Definition at line 272 of file BoundaryGeometry.cpp.
Referenced by Voxel::intersect(), and BoundaryGeometry::intersectLineTriangle().
gt_zero()
bool cmp_ulp::gt_zero (double x) inline
Definition at line 273 of file BoundaryGeometry.cpp.
le()
bool cmp_ulp::le (double x, double y) inline
Definition at line 266 of file BoundaryGeometry.cpp.
Referenced by BoundaryGeometry::intersectLineTriangle(), and Voxel::isInside().
le_zero()
bool cmp_ulp::le_zero (double x) inline
Definition at line 267 of file BoundaryGeometry.cpp.
lt()
bool cmp_ulp::lt (double x, double y) inline
Definition at line 268 of file BoundaryGeometry.cpp.
Referenced by Voxel::intersect(), BoundaryGeometry::intersectLineTriangle(), and BoundaryGeometry::isInside().
lt_zero()
bool cmp_ulp::lt_zero (double x) inline
Definition at line 269 of file BoundaryGeometry.cpp.
Referenced by BoundaryGeometry::intersectLineTriangle().