OPALX (Object Oriented Parallel Accelerator Library for Exascal): Expressions Namespace Reference
Expressions Namespace Reference
Representation objects and parsers for attribute expressions.
Classes
class AAutomatic
Object attribute with an `‘automatic’' array value.
class ABinary
An array expression with two array operands.
class AColumn
An array expression defined as a table column.
class ADeferred
Object attribute with a `‘deferred’' array value.
class AList
An array expression defined by a list of scalar expressions.
class ARefExpr
An expression defined as a reference to an array.
class ARow
An array expression defined as a table row.
class ArrayOfPtrs
An array of pointers to scalar expressions.
class ASUnary
A scalar expression with one array operand.
class ATable
An array expression generated from a TABLE() function.
class AUnary
An array expression with one array operand.
class AValue
Object attribute with a constant array value.
class Indexer
A scalar expression to retrieve an indexed component from an array.
class OArray
An array expression.
class PtrToArray
A pointer to an array expression.
class PtrToScalar
A pointer to a scalar expression.
class SAutomatic
Object attribute with an `‘automatic’' scalar value.
class SBinary
A scalar expression with two scalar operands.
class Scalar
A scalar expression.
class SCell
A scalar expression referring to a table cell.
class SConstant
A scalar constant expression.
class SDeferred
Object attribute with a `‘deferred’' scalar value.
class SHash
A scalar expression.
class SNull
A scalar expression without operands.
class SRefAttr
An attribute defined as a reference to a scalar.
class SRefExpr
An expression defined as a reference to a scalar.
class SUnary
A scalar expression with one scalar operand.
class SValue
Object attribute with a constant scalar value.
struct TFunction0
An operand-less function returning a T.
struct TFunction1
A function of one U, returning a T.
struct TFunction2
A function of two U's returning a T.
Typedefs
typedef TFunction1< double, const std::vector< double > & > ArrayFun
Functions
PtrToScalar< bool > parseBool (Statement &)
Parse boolean expression.
PtrToScalar< double > parseReal (Statement &)
Parse real expression.
double parseRealConst (Statement &)
Parse real constant.
std::string parseString (Statement &, const char msg[])
Parse string value.
std::string parseStringValue (Statement &, const char msg[])
PtrToArray< bool > parseBoolArray (Statement &)
Parse boolean array expression.
PtrToArray< double > parseRealArray (Statement &)
Parse real array expression.
PtrToArray< double > parseRealConstArray (Statement &)
Parse real array constant.
std::vector< std::string > parseStringArray (Statement &)
Parse string array.
void parseDelimiter (Statement &stat, char delim)
Test for one-character delimiter.
void parseDelimiter (Statement &stat, const char delim[2])
Test for two-character delimiter.
PlaceRep parsePlace (Statement &)
Parse place specification.
RangeRep parseRange (Statement &)
Parse range specification.
SRefAttr< double > * parseReference (Statement &)
Parse variable reference.
TableRowRep parseTableRow (Statement &)
Parse a token list (for macro argument and the like).
std::list< Token > parseTokenList (Statement &)
Parse a token list (for macro argument and the like).
std::vector< std::list< Token > > parseTokenListArray (Statement &)
Parse a token list array (for LIST commands).
PtrToScalar< double > parseTableExpression (Statement &, const Table *)
Parse table expression (depends on a table's rows).
bool Or (bool a, bool b)
bool And (bool a, bool b)
bool Le (double a, double b)
bool Lt (double a, double b)
bool Ge (double a, double b)
bool Gt (double a, double b)
bool Eq (double a, double b)
bool Ne (double a, double b)
double Neg (double a)
double Sign (double a)
double Tgauss (double a)
double Add (double a, double b)
double Sub (double a, double b)
double Mpy (double a, double b)
double Div (double a, double b)
double getEkin ()
double ranf ()
double gauss ()
double Max (double a, double b)
double Min (double a, double b)
double Mod (double a, double b)
double Mina (const std::vector< double > &array)
double Maxa (const std::vector< double > &array)
double Rmsa (const std::vector< double > &array)
double AbsMax (const std::vector< double > &array)
PtrToScalar< bool > parseAnd (Statement &stat)
PtrToArray< double > parseArrayFactor (Statement &stat)
PtrToArray< double > parseArrayPrimary (Statement &stat)
PtrToArray< double > parseArrayTerm (Statement &stat)
void parseBracketList (Statement &stat, char close, std::list< Token > &result)
PtrToScalar< double > parseFactor (Statement &stat)
PtrToScalar< double > parsePrimary (Statement &stat)
PtrToScalar< bool > parseRelation (Statement &stat)
PtrToScalar< double > parseTerm (Statement &stat)
PtrToArray< double > parseColumnGenerator (Statement &stat)
PtrToArray< double > parseRowGenerator (Statement &stat)
PtrToArray< double > parseTableGenerator (Statement &stat)
template<class T>
std::ostream & operator<< (std::ostream &os, const SRefAttr< T > &a)
template<class T>
const T * find (const T table[], const std::string &name)
Look up name.
Variables
const Table * currentTable = 0
std::unique_ptr< ATable > currentArray
Detailed Description
Representation objects and parsers for attribute expressions.
Class Documentation
Expressions::TFunction0
struct Expressions::TFunction0
template<class T>
struct Expressions::TFunction0< T >
An operand-less function returning a T.
Definition at line 31 of file TFunction0.h.
Class Members
T(*)() function The actual operation.
const char * name The function name or operator representation.
int precedence The operator precedence.
Expressions::TFunction1
struct Expressions::TFunction1
template<class T, class U>
struct Expressions::TFunction1< T, U >
A function of one U, returning a T.
Definition at line 31 of file TFunction1.h.
Class Members
T(*)(U) function The actual operation.
const char * name The function name or operator representation.
int precedence The operator precedence.
Expressions::TFunction2
struct Expressions::TFunction2
template<class T, class U>
struct Expressions::TFunction2< T, U >
A function of two U's returning a T.
Definition at line 31 of file TFunction2.h.
Class Members
T(*)(U, U) function The actual operation.
const char * name The function name or operator representation.
int precedence The operator precedence.
Typedef Documentation
ArrayFun
typedef TFunction1<double, const std::vector<double>&> Expressions::ArrayFun
Definition at line 254 of file Expressions.cpp.
Function Documentation
AbsMax()
double Expressions::AbsMax (const std::vector< double > & array)
Definition at line 241 of file Expressions.cpp.
References Options::warn.
Add()
double Expressions::Add (double a, double b)
Definition at line 113 of file Expressions.cpp.
And()
bool Expressions::And (bool a, bool b)
Definition at line 75 of file Expressions.cpp.
Div()
double Expressions::Div (double a, double b)
Definition at line 125 of file Expressions.cpp.
Eq()
bool Expressions::Eq (double a, double b)
Definition at line 90 of file Expressions.cpp.
find()
template<class T> const T * Expressions::find (const T table[], const std::string & name) inline
Look up name.
Definition at line 33 of file TFind.h.
Referenced by parseArrayPrimary(), and parsePrimary().
gauss()
double Expressions::gauss ()
Definition at line 155 of file Expressions.cpp.
References Options::rangen.
Ge()
bool Expressions::Ge (double a, double b)
Definition at line 84 of file Expressions.cpp.
getEkin()
double Expressions::getEkin ()
Definition at line 139 of file Expressions.cpp.
References OpalData::getInstance(), and OpalData::getPartBunch().
Gt()
bool Expressions::Gt (double a, double b)
Definition at line 87 of file Expressions.cpp.
Le()
bool Expressions::Le (double a, double b)
Definition at line 78 of file Expressions.cpp.
Lt()
bool Expressions::Lt (double a, double b)
Definition at line 81 of file Expressions.cpp.
Max()
double Expressions::Max (double a, double b)
Definition at line 184 of file Expressions.cpp.
Maxa()
double Expressions::Maxa (const std::vector< double > & array)
Definition at line 215 of file Expressions.cpp.
References Options::warn.
Min()
double Expressions::Min (double a, double b)
Definition at line 186 of file Expressions.cpp.
Referenced by Mina().
Mina()
double Expressions::Mina (const std::vector< double > & array)
Definition at line 202 of file Expressions.cpp.
References Min(), and Options::warn.
Mod()
double Expressions::Mod (double a, double b)
Definition at line 188 of file Expressions.cpp.
Mpy()
double Expressions::Mpy (double a, double b)
Definition at line 121 of file Expressions.cpp.
Ne()
bool Expressions::Ne (double a, double b)
Definition at line 93 of file Expressions.cpp.
Neg()
double Expressions::Neg (double a)
Definition at line 99 of file Expressions.cpp.
operator<<()
template<class T> std::ostream & Expressions::operator<< (std::ostream & os, const SRefAttr< T > & a) inline
Definition at line 101 of file SRefAttr.h.
References Expressions::SRefAttr< T >::print().
Or()
bool Expressions::Or (bool a, bool b)
Definition at line 72 of file Expressions.cpp.
parseAnd()
PtrToScalar< bool > Expressions::parseAnd (Statement & stat)
Definition at line 671 of file Expressions.cpp.
References Statement::delimiter(), Expressions::SBinary< T, U >::make(), and parseRelation().
Referenced by parseBool().
parseArrayFactor()
PtrToArray< double > Expressions::parseArrayFactor (Statement & stat)
Definition at line 683 of file Expressions.cpp.
References Statement::delimiter(), and parseArrayPrimary().
Referenced by parseArrayTerm().
parseArrayPrimary()
PtrToArray< double > Expressions::parseArrayPrimary (Statement & stat)
Definition at line 695 of file Expressions.cpp.
References Statement::delimiter(), find(), Statement::keyword(), Expressions::SNull< T >::make(), parseColumnGenerator(), parseDelimiter(), parsePlace(), parseReal(), parseRealArray(), parseRealConstArray(), parseRowGenerator(), parseString(), parseStringArray(), parseTableGenerator(), and Statement::real().
Referenced by parseArrayFactor().
parseArrayTerm()
PtrToArray< double > Expressions::parseArrayTerm (Statement & stat)
Definition at line 770 of file Expressions.cpp.
References Statement::delimiter(), and parseArrayFactor().
Referenced by parseRealArray().
parseBool()
PtrToScalar< bool > Expressions::parseBool (Statement & stat) extern
Parse boolean expression.
Definition at line 309 of file Expressions.cpp.
References Statement::delimiter(), Expressions::SBinary< T, U >::make(), and parseAnd().
Referenced by Attributes::Bool::parse(), parseBoolArray(), Attributes::BoolArray::parseComponent(), and parseRelation().
parseBoolArray()
PtrToArray< bool > Expressions::parseBoolArray (Statement & stat) extern
Parse boolean array expression.
Definition at line 436 of file Expressions.cpp.
References Statement::delimiter(), parseBool(), and parseDelimiter().
Referenced by Attributes::BoolArray::parse().
parseBracketList()
void Expressions::parseBracketList (Statement & stat, char close, std::list< Token > & result)
Definition at line 789 of file Expressions.cpp.
References Statement::atEnd(), Statement::delimiter(), Statement::getCurrent(), Token::isDel(), and parseBracketList().
Referenced by parseBracketList(), and parseTokenList().
parseColumnGenerator()
PtrToArray< double > Expressions::parseColumnGenerator (Statement & stat)
Definition at line 976 of file Expressions.cpp.
References Statement::delimiter(), parseDelimiter(), parseRange(), and parseString().
Referenced by parseArrayPrimary().
parseDelimiter() [1/2]
void Expressions::parseDelimiter (Statement & stat, char delim) extern
Test for one-character delimiter.
Definition at line 514 of file Expressions.cpp.
References Statement::delimiter().
Referenced by EmissionSourceList::parse(), Line::parse(), Object::parse(), OpalElement::parse(), parseArrayPrimary(), OpalParser::parseAssign(), parseBoolArray(), parseColumnGenerator(), Macro::parseFormals(), Line::parseList(), parsePlace(), SequenceParser::parsePosition(), parsePrimary(), parseReference(), parseRelation(), parseRowGenerator(), parseString(), parseStringArray(), parseStringValue(), parseTableGenerator(), parseTableRow(), and parseTokenListArray().
parseDelimiter() [2/2]
void Expressions::parseDelimiter (Statement & stat, const char delim[2]) extern
Test for two-character delimiter.
Definition at line 522 of file Expressions.cpp.
References Statement::delimiter().
parseFactor()
PtrToScalar< double > Expressions::parseFactor (Statement & stat)
Definition at line 812 of file Expressions.cpp.
References Statement::delimiter(), Expressions::SBinary< T, U >::make(), and parsePrimary().
Referenced by parseTerm().
parsePlace()
PlaceRep Expressions::parsePlace (Statement & stat) extern
Parse place specification.
Definition at line 530 of file Expressions.cpp.
References PlaceRep::append(), Statement::delimiter(), Statement::keyword(), parseDelimiter(), parseRealConst(), and parseString().
Referenced by Attributes::Place::parse(), parseArrayPrimary(), parsePrimary(), parseRange(), parseRowGenerator(), and parseTableRow().
parsePrimary()
PtrToScalar< double > Expressions::parsePrimary (Statement & stat)
Definition at line 824 of file Expressions.cpp.
References currentArray, currentTable, Statement::delimiter(), find(), Expressions::PtrToScalar< T >::isValid(), Expressions::SBinary< T, U >::make(), Expressions::SNull< T >::make(), Expressions::SUnary< T, U >::make(), parseDelimiter(), parsePlace(), parseReal(), parseRealArray(), parseRealConst(), parseString(), and Statement::real().
Referenced by parseFactor().
parseRange()
RangeRep Expressions::parseRange (Statement & stat) extern
Parse range specification.
Definition at line 568 of file Expressions.cpp.
References Statement::delimiter(), Statement::keyword(), and parsePlace().
Referenced by Attributes::Range::parse(), and parseColumnGenerator().
parseReal()
PtrToScalar< double > Expressions::parseReal (Statement & stat) extern
Parse real expression.
Definition at line 321 of file Expressions.cpp.
References Statement::delimiter(), Expressions::SBinary< T, U >::make(), Expressions::SUnary< T, U >::make(), and parseTerm().
Referenced by Attributes::Real::parse(), parseArrayPrimary(), Attributes::RealArray::parseComponent(), parsePrimary(), parseRealConst(), parseRelation(), parseTableExpression(), and parseTableGenerator().
parseRealArray()
PtrToArray< double > Expressions::parseRealArray (Statement & stat) extern
Parse real array expression.
Definition at line 454 of file Expressions.cpp.
References Statement::delimiter(), and parseArrayTerm().
Referenced by Attributes::RealArray::parse(), parseArrayPrimary(), parsePrimary(), and parseRealConstArray().
parseRealConst()
double Expressions::parseRealConst (Statement & stat) extern
Parse real constant.
Definition at line 351 of file Expressions.cpp.
References parseReal().
Referenced by Object::parse(), OpalElement::parse(), OpalParser::parseAssign(), parsePlace(), SequenceParser::parsePosition(), parsePrimary(), parseReference(), parseString(), parseStringValue(), and parseTableGenerator().
parseRealConstArray()
PtrToArray< double > Expressions::parseRealConstArray (Statement & stat) extern
Parse real array constant.
Definition at line 484 of file Expressions.cpp.
References parseRealArray().
Referenced by parseArrayPrimary().
parseReference()
SRefAttr< double > * Expressions::parseReference (Statement & stat) extern
Parse variable reference.
Definition at line 579 of file Expressions.cpp.
References Statement::delimiter(), parseDelimiter(), parseRealConst(), and parseString().
Referenced by Attributes::Reference::parse().
parseRelation()
PtrToScalar< bool > Expressions::parseRelation (Statement & stat)
Definition at line 912 of file Expressions.cpp.
References Statement::boolean(), Statement::delimiter(), BoolConstant::getBool(), OpalData::getInstance(), Expressions::SBinary< T, U >::make(), Statement::mark(), parseBool(), parseDelimiter(), parseReal(), Statement::restore(), and Statement::word().
Referenced by parseAnd().
parseRowGenerator()
PtrToArray< double > Expressions::parseRowGenerator (Statement & stat)
Definition at line 998 of file Expressions.cpp.
References Statement::delimiter(), parseDelimiter(), parsePlace(), parseString(), and parseStringArray().
Referenced by parseArrayPrimary().
parseString()
std::string Expressions::parseString (Statement & stat, const char msg[]) extern
Parse string value.
Definition at line 356 of file Expressions.cpp.
References Statement::delimiter(), parseDelimiter(), parseRealConst(), Statement::str(), and Statement::word().
Referenced by Line::parse(), Object::parse(), OpalElement::parse(), OpalParser::parse(), OpalParser::parseAction(), parseArrayPrimary(), OpalParser::parseAssign(), parseColumnGenerator(), OpalParser::parseDefine(), Macro::parseFormals(), EmissionSourceList::parseList(), Line::parseList(), OpalParser::parseMacro(), SequenceParser::parseMember(), parsePlace(), SequenceParser::parsePosition(), parsePrimary(), parseReference(), parseRowGenerator(), and parseTableRow().
parseStringArray()
std::vector< std::string > Expressions::parseStringArray (Statement & stat) extern
Parse string array.
Definition at line 496 of file Expressions.cpp.
References Statement::delimiter(), parseDelimiter(), and parseStringValue().
Referenced by Attributes::StringArray::parse(), Attributes::UpperCaseStringArray::parse(), parseArrayPrimary(), and parseRowGenerator().
parseStringValue()
std::string Expressions::parseStringValue (Statement & stat, const char msg[]) extern
Definition at line 386 of file Expressions.cpp.
References Statement::delimiter(), OpalData::find(), OpalData::getInstance(), StringConstant::getString(), parseDelimiter(), parseRealConst(), Statement::str(), and Statement::word().
Referenced by Attributes::PredefinedString::parse(), Attributes::String::parse(), Attributes::UpperCaseString::parse(), Attributes::StringArray::parseComponent(), Attributes::UpperCaseStringArray::parseComponent(), and parseStringArray().
parseTableExpression()
PtrToScalar< double > Expressions::parseTableExpression (Statement & stat, const Table * t) extern
Parse table expression (depends on a table's rows).
Definition at line 615 of file Expressions.cpp.
References currentTable, and parseReal().
parseTableGenerator()
PtrToArray< double > Expressions::parseTableGenerator (Statement & stat)
Definition at line 1020 of file Expressions.cpp.
References currentArray, Statement::delimiter(), parseDelimiter(), parseReal(), and parseRealConst().
Referenced by parseArrayPrimary().
parseTableRow()
TableRowRep Expressions::parseTableRow (Statement & stat) extern
Parse a token list (for macro argument and the like).
Definition at line 606 of file Expressions.cpp.
References parseDelimiter(), parsePlace(), and parseString().
Referenced by Attributes::TableRow::parse().
parseTerm()
PtrToScalar< double > Expressions::parseTerm (Statement & stat)
Definition at line 957 of file Expressions.cpp.
References Statement::delimiter(), Expressions::SBinary< T, U >::make(), and parseFactor().
Referenced by parseReal().
parseTokenList()
std::list< Token > Expressions::parseTokenList (Statement & stat) extern
Parse a token list (for macro argument and the like).
Definition at line 622 of file Expressions.cpp.
References Statement::atEnd(), Statement::getCurrent(), Token::isDel(), Statement::mark(), parseBracketList(), and Statement::restore().
Referenced by Attributes::TokenList::parse(), Attributes::TokenListArray::parseComponent(), and parseTokenListArray().
parseTokenListArray()
std::vector< std::list< Token > > Expressions::parseTokenListArray (Statement & stat) extern
Parse a token list array (for LIST commands).
Definition at line 652 of file Expressions.cpp.
References Statement::delimiter(), parseDelimiter(), and parseTokenList().
Referenced by Attributes::TokenListArray::parse().
ranf()
double Expressions::ranf ()
Definition at line 153 of file Expressions.cpp.
References Options::rangen.
Rmsa()
double Expressions::Rmsa (const std::vector< double > & array)
Definition at line 228 of file Expressions.cpp.
References Options::warn.
Sign()
double Expressions::Sign (double a)
Definition at line 103 of file Expressions.cpp.
Sub()
double Expressions::Sub (double a, double b)
Definition at line 117 of file Expressions.cpp.
Tgauss()
double Expressions::Tgauss (double a)
Definition at line 105 of file Expressions.cpp.
References Options::rangen.
Variable Documentation
currentArray
std::unique_ptr<ATable> Expressions::currentArray
Definition at line 264 of file Expressions.cpp.
Referenced by parsePrimary(), and parseTableGenerator().
currentTable
const Table* Expressions::currentTable = 0
Definition at line 263 of file Expressions.cpp.
Referenced by parsePrimary(), and parseTableExpression().