OPALX (Object Oriented Parallel Accelerator Library for Exascal): OPALXMAIN Namespace Reference
OPALXMAIN Namespace Reference
Functions
void printStdoutHeader ()
void printHelp ()
Function Documentation
printHelp()
void OPALXMAIN::printHelp ()
Definition at line 105 of file Main.cpp.
References gmsg.
Referenced by main().
printStdoutHeader()
void OPALXMAIN::printStdoutHeader ()
Definition at line 62 of file Main.cpp.
References OPALTimer::Timer::date(), Util::getGitRevision(), gmsg, and OPALTimer::Timer::time().
Referenced by main().