OPALX (Object Oriented Parallel Accelerator Library for Exascal): Attributes Namespace Reference
Attributes Namespace Reference
A collection of routines to construct object Attributes and retrieve.
Classes
class Bool
Parser for attribute of type logical.
class BoolArray
Parser for an attribute of type logical array.
class Place
Parser for an attribute of type place reference.
class PredefinedString
Parser for an attribute of type string.
class Range
Parser for an attribute of type range definition.
class Real
Parser for an attribute of type real.
class RealArray
Parser for an attribute of type real array.
class Reference
Parser for an attribute of type attribute reference.
class String
Parser for an attribute of type string.
class StringArray
Parser for an attribute of type string array.
class TableRow
Parser for an attribute of type table row reference.
class TokenList
Parser for an attribute of type token list.
class TokenListArray
Parser for an attribute of type token list array.
class UpperCaseString
Parser for an attribute of type string.
class UpperCaseStringArray
Parser for an attribute of type string array.
Functions
Attribute makeBool (const std::string &name, const std::string &help)
Make logical attribute.
Attribute makeBool (const std::string &name, const std::string &help, bool initial)
Make logical attribute.
bool getBool (const Attribute &)
Return logical value.
void setBool (Attribute &, bool)
Set logical value.
Attribute makeBoolArray (const std::string &name, const std::string &help)
Create a logical array attribute.
std::vector< bool > getBoolArray (const Attribute &)
Get logical array value.
void setBoolArray (Attribute &, const std::vector< bool > &)
Set logical array value.
Attribute makePlace (const std::string &name, const std::string &help)
Create a place attribute.
PlaceRep getPlace (const Attribute &)
Get place value.
void setPlace (Attribute &, const PlaceRep &)
Set place value.
Attribute makeRange (const std::string &name, const std::string &help)
Create a range attribute.
RangeRep getRange (const Attribute &)
Get range value.
void setRange (Attribute &, const RangeRep &)
Set range value.
Attribute makeReal (const std::string &name, const std::string &help)
Make real attribute.
Attribute makeReal (const std::string &name, const std::string &help, double initial)
Make real attribute.
double getReal (const Attribute &attr)
Return real value.
void setReal (Attribute &attr, double val)
Set real value.
Attribute makeRealArray (const std::string &name, const std::string &help)
Create real array attribute.
std::vector< double > getRealArray (const Attribute &)
Get array value.
void setRealArray (Attribute &, const std::vector< double > &)
Set array value.
Attribute makeReference (const std::string &name, const std::string &help)
Create a reference attribute.
Attribute makeString (const std::string &name, const std::string &help)
Make string attribute.
Attribute makeString (const std::string &name, const std::string &help, const std::string &initial)
Make string attribute.
std::string getString (const Attribute &attr)
Get string value.
void setString (Attribute &attr, const std::string &val)
Set string value.
Attribute makePredefinedString (const std::string &name, const std::string &help, const std::initializer_list< std::string > &predefinedStrings)
Make predefined string attribute.
Attribute makePredefinedString (const std::string &name, const std::string &help, const std::initializer_list< std::string > &predefinedStrings, const std::string &initial)
Make predefined string attribute.
void setPredefinedString (Attribute &attr, const std::string &val)
Set predefined string value.
Attribute makeUpperCaseString (const std::string &name, const std::string &help)
Make uppercase string attribute.
Attribute makeUpperCaseString (const std::string &name, const std::string &help, const std::string &initial)
Make uppercase string attribute.
void setUpperCaseString (Attribute &attr, const std::string &val)
Set uppercase string value.
Attribute makeStringArray (const std::string &name, const std::string &help)
Create a string array attribute.
std::vector< std::string > getStringArray (const Attribute &)
Get string array value.
void setStringArray (Attribute &, const std::vector< std::string > &)
Set string array value.
Attribute makeUpperCaseStringArray (const std::string &name, const std::string &help)
Make uppercase string array attribute.
void setUpperCaseStringArray (Attribute &, const std::vector< std::string > &)
Set upper case string array value.
Attribute makeTableRow (const std::string &name, const std::string &help)
Create a table row attribute.
TableRowRep getTableRow (const Attribute &)
Get table row value.
void setTableRow (Attribute &, const TableRowRep &)
Set table row value.
Attribute makeTokenList (const std::string &name, const std::string &help)
Make token list attribute.
std::list< Token > getTokenList (const Attribute &attr)
Return token list value.
void setTokenList (Attribute &attr, const std::list< Token > &)
Set token list value.
Attribute makeTokenListArray (const std::string &name, const std::string &help)
Make token list attribute.
std::vector< std::list< Token > > getTokenListArray (const Attribute &attr)
Return token list array value.
void setTokenListArray (Attribute &attr, const std::vector< std::list< Token > > &)
Set token list array value.
Detailed Description
A collection of routines to construct object Attributes and retrieve.
Function Documentation
getBool()
bool Attributes::getBool (const Attribute & attr)
Return logical value.
Definition at line 99 of file Attributes.cpp.
References Expressions::SRefAttr< T >::evaluate(), Attribute::getBase(), Attribute::getHandler(), Attribute::getName(), and Attribute::isBaseAllocated().
Referenced by Option::execute(), IfStatement::execute(), WhileStatement::execute(), BoolConstant::getBool(), FieldSolverCmd::getDomDec(), EmissionSource::getShiftedGreensFunction(), EmissionSource::getZeroFaceR0Z(), FieldSolverCmd::printInfo(), Select::select(), Distribution::setDistParametersFlatTop(), OpalCavity::update(), OpalElement::update(), OpalRingDefinition::update(), OpalSolenoid::update(), OpalTravelingWave::update(), OpalVacuum::update(), and OpalMultipoleT::update().
getBoolArray()
std::vector< bool > Attributes::getBoolArray (const Attribute & attr)
Get logical array value.
Definition at line 140 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getName(), and Attribute::isBaseAllocated().
getPlace()
PlaceRep Attributes::getPlace (const Attribute & attr)
Get place value.
Definition at line 174 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getName(), and Attribute::isBaseAllocated().
getRange()
RangeRep Attributes::getRange (const Attribute & attr)
Get range value.
Definition at line 205 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getName(), and Attribute::isBaseAllocated().
Referenced by Select::select().
getReal()
double Attributes::getReal (const Attribute & attr)
Return real value.
Definition at line 240 of file Attributes.cpp.
References Expressions::SRefAttr< T >::evaluate(), Attribute::getBase(), Attribute::getHandler(), Attribute::getName(), and Attribute::isBaseAllocated().
Referenced by DumpEMFields::buildGrid(), Option::execute(), Beam::execute(), TrackCmd::execute(), SequenceParser::findNeighbourPositions(), BoundaryGeometry::getA(), BoundaryGeometry::getB(), BinningCmd::getBinningAlpha(), BinningCmd::getBinningBeta(), FieldSolverCmd::getBoxIncr(), Beam::getBunchCharge(), BoundaryGeometry::getC(), Beam::getCharge(), Beam::getCurrent(), BinningCmd::getDesiredWidth(), TrackCmd::getDTAU(), TrackCmd::getDTSCINIT(), BinningCmd::getDumpBinsFrequency(), Beam::getFrequency(), BoundaryGeometry::getL1(), BoundaryGeometry::getL2(), BoundaryGeometry::getLength(), OpalElement::getLength(), Line::getLength(), Sequence::getLength(), Beam::getMass(), BinningCmd::getMaxBins(), Beam::getNumAlloc(), FieldSolverCmd::getNX(), FieldSolverCmd::getNY(), FieldSolverCmd::getNZ(), EmissionSource::getP0(), EmissionSource::getR0(), RealConstant::getReal(), RealVariable::getReal(), BoundaryGeometry::getS(), TrackCmd::getStepsPerTurn(), EmissionSource::getT0(), TrackCmd::getT0(), BinningCmd::getTablePrintFrequency(), EmissionSource::getZerofaceMaxSteps(), EmissionSource::getZeroFacePlaneDumpFrequency(), TrackCmd::getZStart(), BoundaryGeometry::initialize(), OpalFilter::initOpalFilter(), Line::parse(), Beam::print(), OpalFilter::print(), DumpEMFields::print(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), OpalElement::printMultipoleStrength(), Distribution::setAttributes(), Distribution::setDistParametersFlatTop(), Distribution::setSigmaP_m(), Distribution::setSigmaR_m(), OpalCavity::update(), OpalConstantEFieldCavity::update(), OpalDrift::update(), OpalElement::update(), OpalMonitor::update(), OpalProbe::update(), OpalQuadrupole::update(), OpalRBend::update(), OpalRingDefinition::update(), OpalSBend::update(), OpalSolenoid::update(), OpalTravelingWave::update(), OpalVacuum::update(), OpalVerticalFFAMagnet::update(), Beam::update(), BinningCmd::update(), OpalLaser::update(), OpalMultipoleT::update(), OpalPolynomialTimeDependence::update(), OpalSplineTimeDependence::update(), OpalVariableRFCavity::update(), and OpalElement::updateUnknown().
getRealArray()
std::vector< double > Attributes::getRealArray (const Attribute & attr)
Get array value.
Definition at line 282 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getHandler(), Attribute::getName(), and Attribute::isBaseAllocated().
Referenced by Value::execute(), TrackCmd::getDT(), TrackCmd::getMaxSteps(), RealVector::getRealComponent(), TrackCmd::getZStop(), BoundaryGeometry::initialize(), Line::parse(), Distribution::setDistParametersMultiVariateGauss(), OpalElement::update(), OpalMultipole::update(), OpalMultipoleT::update(), OpalPolynomialTimeDependence::update(), OpalSinusoidalTimeDependence::update(), and OpalSplineTimeDependence::update().
getString()
std::string Attributes::getString (const Attribute & attr)
Get string value.
Definition at line 328 of file Attributes.cpp.
References Expressions::SRefAttr< T >::evaluate(), Attribute::getBase(), Attribute::getHandler(), OpalData::getInstance(), Attribute::getName(), Attribute::isBaseAllocated(), and Util::toUpper().
Referenced by BoundaryGeometry::BoundaryGeometry(), BoundaryGeometry::BoundaryGeometry(), DumpEMFields::buildGrid(), FieldSolverCmd::constructBCHandler(), BinningCmd::dumpBinsToFile(), Call::execute(), Echo::execute(), Help::execute(), Option::execute(), PSystem::execute(), Select::execute(), System::execute(), Title::execute(), TrackCmd::execute(), TrackRun::execute(), SequenceParser::findNeighbourPositions(), OpalElement::getApert(), FieldSolverCmd::getBinsName(), Beam::getDaughterBeamName(), EmissionSource::getDistributionName(), BinningCmd::getDumpBinsFileName(), EmissionSource::getEmissionModel(), Beam::getEmissionSourceListName(), Distribution::getFilename(), BoundaryGeometry::getFilename(), BinningCmd::getParameter(), OpalElement::getParticleMatterInteraction(), Beam::getParticleName(), Sequence::getReference(), StringConstant::getString(), TrackCmd::getTimeIntegrator(), BoundaryGeometry::getTopology(), FieldSolverCmd::getType(), OpalElement::getTypeName(), OpalElement::getWakeF(), OpalFilter::initOpalFilter(), Sequence::parse(), DumpEMFields::parseCoordinateSystem(), Beam::print(), OpalFilter::print(), DumpEMFields::print(), BoundaryGeometry::printInfo(), FieldSolverCmd::printInfo(), Select::select(), Distribution::setDistType(), TrackRun::setRunMethod(), TrackRun::setupBoundaryGeometry(), TEST(), OpalCavity::update(), OpalMonitor::update(), OpalProbe::update(), OpalRBend::update(), OpalSBend::update(), OpalSolenoid::update(), OpalTravelingWave::update(), OpalVacuum::update(), BinningCmd::update(), OpalMultipoleT::update(), and OpalVariableRFCavity::update().
getStringArray()
std::vector< std::string > Attributes::getStringArray (const Attribute & attr)
Get string array value.
Definition at line 465 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getHandler(), OpalData::getInstance(), Attribute::getName(), Attribute::isBaseAllocated(), RealVariable::printValue(), and Util::toUpper().
Referenced by TrackCmd::execute(), Beam::getGlobalProcessNames(), Attributes::StringArray::parseComponent(), and Attributes::UpperCaseStringArray::parseComponent().
getTableRow()
TableRowRep Attributes::getTableRow (const Attribute & attr)
Get table row value.
Definition at line 555 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getName(), and Attribute::isBaseAllocated().
getTokenList()
std::list< Token > Attributes::getTokenList (const Attribute & attr)
Return token list value.
Definition at line 586 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getHandler(), Attribute::getName(), and Attribute::isBaseAllocated().
getTokenListArray()
std::vector< std::list< Token > > Attributes::getTokenListArray (const Attribute & attr)
Return token list array value.
Definition at line 618 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getHandler(), Attribute::getName(), and Attribute::isBaseAllocated().
makeBool() [1/2]
Attribute Attributes::makeBool (const std::string & name, const std::string & help)
Make logical attribute.
Definition at line 91 of file Attributes.cpp.
Referenced by BoolConstant::BoolConstant(), Distribution::Distribution(), EmissionSource::EmissionSource(), IfStatement::execute(), WhileStatement::execute(), FieldSolverCmd::FieldSolverCmd(), OpalBend::OpalBend(), OpalCavity::OpalCavity(), OpalElement::OpalElement(), OpalMultipoleT::OpalMultipoleT(), OpalRingDefinition::OpalRingDefinition(), OpalSolenoid::OpalSolenoid(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), Option::Option(), Select::Select(), and TrackRun::TrackRun().
makeBool() [2/2]
Attribute Attributes::makeBool (const std::string & name, const std::string & help, bool ini)
Make logical attribute.
Definition at line 95 of file Attributes.cpp.
makeBoolArray()
Attribute Attributes::makeBoolArray (const std::string & name, const std::string & help)
Create a logical array attribute.
Definition at line 136 of file Attributes.cpp.
makePlace()
Attribute Attributes::makePlace (const std::string & name, const std::string & help)
Create a place attribute.
Definition at line 170 of file Attributes.cpp.
makePredefinedString() [1/2]
Attribute Attributes::makePredefinedString (const std::string & name, const std::string & help, const std::initializer_list< std::string > & predefinedStrings)
Make predefined string attribute.
Definition at line 398 of file Attributes.cpp.
Referenced by Beam::Beam(), BinningCmd::BinningCmd(), BoundaryGeometry::BoundaryGeometry(), Distribution::Distribution(), DumpEMFields::DumpEMFields(), EmissionSource::EmissionSource(), FieldSolverCmd::FieldSolverCmd(), OpalElement::OpalElement(), OpalFilter::OpalFilter(), OpalVacuum::OpalVacuum(), Option::Option(), TrackCmd::TrackCmd(), and TrackRun::TrackRun().
makePredefinedString() [2/2]
Attribute Attributes::makePredefinedString (const std::string & name, const std::string & help, const std::initializer_list< std::string > & predefinedStrings, const std::string & initial)
Make predefined string attribute.
Definition at line 404 of file Attributes.cpp.
References Util::toUpper().
makeRange()
Attribute Attributes::makeRange (const std::string & name, const std::string & help)
Create a range attribute.
Definition at line 201 of file Attributes.cpp.
Referenced by Select::Select().
makeReal() [1/2]
Attribute Attributes::makeReal (const std::string & name, const std::string & help)
Make real attribute.
Definition at line 232 of file Attributes.cpp.
Referenced by Beam::Beam(), BinningCmd::BinningCmd(), BoundaryGeometry::BoundaryGeometry(), Distribution::Distribution(), DumpEMFields::DumpEMFields(), EmissionSource::EmissionSource(), FieldSolverCmd::FieldSolverCmd(), Line::Line(), OpalBend::OpalBend(), OpalCavity::OpalCavity(), OpalConstantEFieldCavity::OpalConstantEFieldCavity(), OpalDrift::OpalDrift(), OpalElement::OpalElement(), OpalFilter::OpalFilter(), OpalLaser::OpalLaser(), OpalMultipoleT::OpalMultipoleT(), OpalPolynomialTimeDependence::OpalPolynomialTimeDependence(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalRingDefinition::OpalRingDefinition(), OpalSolenoid::OpalSolenoid(), OpalSplineTimeDependence::OpalSplineTimeDependence(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), Option::Option(), RealConstant::RealConstant(), RealVariable::RealVariable(), Sequence::Sequence(), TrackCmd::TrackCmd(), and TrackRun::TrackRun().
makeReal() [2/2]
Attribute Attributes::makeReal (const std::string & name, const std::string & help, double initial)
Make real attribute.
Definition at line 236 of file Attributes.cpp.
makeRealArray()
Attribute Attributes::makeRealArray (const std::string & name, const std::string & help)
Create real array attribute.
Definition at line 278 of file Attributes.cpp.
Referenced by BoundaryGeometry::BoundaryGeometry(), Distribution::Distribution(), Line::Line(), OpalElement::OpalElement(), OpalLaser::OpalLaser(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalPolynomialTimeDependence::OpalPolynomialTimeDependence(), OpalSinusoidalTimeDependence::OpalSinusoidalTimeDependence(), OpalSplineTimeDependence::OpalSplineTimeDependence(), RealVector::RealVector(), TrackCmd::TrackCmd(), and Value::Value().
makeReference()
Attribute Attributes::makeReference (const std::string & name, const std::string & help)
Create a reference attribute.
Definition at line 312 of file Attributes.cpp.
makeString() [1/2]
Attribute Attributes::makeString (const std::string & name, const std::string & help)
Make string attribute.
Definition at line 319 of file Attributes.cpp.
Referenced by Beam::Beam(), BinningCmd::BinningCmd(), BoundaryGeometry::BoundaryGeometry(), Call::Call(), Distribution::Distribution(), DumpEMFields::DumpEMFields(), Echo::Echo(), EmissionSource::EmissionSource(), FieldSolverCmd::FieldSolverCmd(), Help::Help(), Line::Line(), OpalBend::OpalBend(), OpalCavity::OpalCavity(), OpalDrift::OpalDrift(), OpalElement::OpalElement(), OpalSolenoid::OpalSolenoid(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), Option::Option(), PSystem::PSystem(), Select::Select(), Sequence::Sequence(), StringConstant::StringConstant(), System::System(), Title::Title(), TrackCmd::TrackCmd(), and TrackRun::TrackRun().
makeString() [2/2]
Attribute Attributes::makeString (const std::string & name, const std::string & help, const std::string & initial)
Make string attribute.
Definition at line 323 of file Attributes.cpp.
makeStringArray()
Attribute Attributes::makeStringArray (const std::string & name, const std::string & help)
Create a string array attribute.
Definition at line 461 of file Attributes.cpp.
Referenced by TrackCmd::TrackCmd().
makeTableRow()
Attribute Attributes::makeTableRow (const std::string & name, const std::string & help)
Create a table row attribute.
Definition at line 551 of file Attributes.cpp.
makeTokenList()
Attribute Attributes::makeTokenList (const std::string & name, const std::string & help)
Make token list attribute.
Definition at line 582 of file Attributes.cpp.
makeTokenListArray()
Attribute Attributes::makeTokenListArray (const std::string & name, const std::string & help)
Make token list attribute.
Definition at line 614 of file Attributes.cpp.
makeUpperCaseString() [1/2]
Attribute Attributes::makeUpperCaseString (const std::string & name, const std::string & help)
Make uppercase string attribute.
Definition at line 433 of file Attributes.cpp.
Referenced by OpalMultipoleT::OpalMultipoleT(), and OpalVariableRFCavity::OpalVariableRFCavity().
makeUpperCaseString() [2/2]
Attribute Attributes::makeUpperCaseString (const std::string & name, const std::string & help, const std::string & initial)
Make uppercase string attribute.
Definition at line 437 of file Attributes.cpp.
References Util::toUpper().
makeUpperCaseStringArray()
Attribute Attributes::makeUpperCaseStringArray (const std::string & name, const std::string & help)
Make uppercase string array attribute.
Definition at line 527 of file Attributes.cpp.
Referenced by Beam::Beam().
setBool()
void Attributes::setBool (Attribute & attr, bool val)
Set logical value.
Definition at line 118 of file Attributes.cpp.
References Expressions::SValue< T >::evaluate(), Attribute::getBase(), Attribute::getHandler(), Attribute::getName(), Attribute::isBaseAllocated(), Attribute::set(), and Expressions::SRefAttr< T >::set().
Referenced by Option::Option(), TEST_F(), TEST_F(), and TEST_F().
setBoolArray()
void Attributes::setBoolArray (Attribute & attr, const std::vector< bool > & value)
Set logical array value.
Definition at line 155 of file Attributes.cpp.
References Attribute::getHandler(), Attribute::getName(), and Attribute::set().
setPlace()
void Attributes::setPlace (Attribute & attr, const PlaceRep & rep)
Set place value.
Definition at line 188 of file Attributes.cpp.
References Attribute::getHandler(), Attribute::getName(), and Attribute::set().
setPredefinedString()
void Attributes::setPredefinedString (Attribute & attr, const std::string & val)
Set predefined string value.
Definition at line 413 of file Attributes.cpp.
References Expressions::SValue< T >::evaluate(), Attribute::getBase(), Attribute::getHandler(), Attribute::getName(), Attribute::isBaseAllocated(), Attribute::set(), Expressions::SRefAttr< T >::set(), and Util::toUpper().
Referenced by Option::Option(), Attributes::PredefinedString::parse(), TestMultipoleT::TestableFieldSolverCmd::setBCX(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCX(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCX(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCX(), TestVariableRFCavity::TestableFieldSolverCmd::setBCX(), OrbitThreaderTest::TestableFieldSolverCmd::setBCX(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCX(), TestMultipoleT::TestableFieldSolverCmd::setBCY(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCY(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCY(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCY(), TestVariableRFCavity::TestableFieldSolverCmd::setBCY(), OrbitThreaderTest::TestableFieldSolverCmd::setBCY(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCY(), TestMultipoleT::TestableFieldSolverCmd::setBCZ(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setBCZ(), TestMultipoleTStraight::TestableFieldSolverCmd::setBCZ(), SolenoidPlacementTest::TestableFieldSolverCmd::setBCZ(), TestVariableRFCavity::TestableFieldSolverCmd::setBCZ(), OrbitThreaderTest::TestableFieldSolverCmd::setBCZ(), OpalBeamlinePlacementTest::TestableFieldSolverCmd::setBCZ(), TestableBinningCmd::setParameterString(), TestMultipoleT::TestableFieldSolverCmd::setType(), TestMultipoleTCurvedConstRadius::TestableFieldSolverCmd::setType(), TestMultipoleTStraight::TestableFieldSolverCmd::setType(), SolenoidPlacementTest::TestableFieldSolverCmd::setType(), TestVariableRFCavity::TestableFieldSolverCmd::setType(), OrbitThreaderTest::TestableFieldSolverCmd::setType(), and OpalBeamlinePlacementTest::TestableFieldSolverCmd::setType().
setRange()
void Attributes::setRange (Attribute & attr, const RangeRep & rep)
Set range value.
Definition at line 219 of file Attributes.cpp.
References Attribute::getHandler(), Attribute::getName(), and Attribute::set().
setReal()
void Attributes::setReal (Attribute & attr, double val)
Set real value.
Definition at line 260 of file Attributes.cpp.
References Expressions::SValue< T >::evaluate(), Attribute::getBase(), Attribute::getHandler(), Attribute::getName(), Attribute::isBaseAllocated(), Attribute::set(), and Expressions::SRefAttr< T >::set().
Referenced by Option::Option(), RealConstant::RealConstant(), RealVariable::RealVariable(), TestableBinningCmd::setBinningAlpha(), TestableBinningCmd::setBinningBeta(), TestableBinningCmd::setDesiredWidth(), TestableBinningCmd::setDumpBinsFreq(), TestableBinningCmd::setMaxBins(), FieldSolverCmd::setNX(), FieldSolverCmd::setNY(), FieldSolverCmd::setNZ(), TestableBinningCmd::setTablePrintFrequency(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and Beam::update().
setRealArray()
void Attributes::setRealArray (Attribute & attr, const std::vector< double > & value)
Set array value.
Definition at line 297 of file Attributes.cpp.
References Attribute::getHandler(), Attribute::getName(), and Attribute::set().
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), and TEST_F().
setString()
void Attributes::setString (Attribute & attr, const std::string & val)
Set string value.
Definition at line 379 of file Attributes.cpp.
References Expressions::SValue< T >::evaluate(), Attribute::getBase(), Attribute::getHandler(), Attribute::getName(), Attribute::isBaseAllocated(), Attribute::set(), and Expressions::SRefAttr< T >::set().
Referenced by Option::Option(), TestableBinningCmd::setDumpBinsFile(), StringConstant::StringConstant(), and BinningCmd::update().
setStringArray()
void Attributes::setStringArray (Attribute & attr, const std::vector< std::string > & value)
Set string array value.
Definition at line 514 of file Attributes.cpp.
References Attribute::getHandler(), Attribute::getName(), and Attribute::set().
Referenced by Attributes::StringArray::parse(), and Attributes::StringArray::parseComponent().
setTableRow()
void Attributes::setTableRow (Attribute & attr, const TableRowRep & rep)
Set table row value.
Definition at line 569 of file Attributes.cpp.
References Attribute::getHandler(), Attribute::getName(), and Attribute::set().
setTokenList()
void Attributes::setTokenList (Attribute & attr, const std::list< Token > & val)
Set token list value.
Definition at line 601 of file Attributes.cpp.
References Attribute::getHandler(), Attribute::getName(), and Attribute::set().
setTokenListArray()
void Attributes::setTokenListArray (Attribute & attr, const std::vector< std::list< Token > > & value)
Set token list array value.
Definition at line 633 of file Attributes.cpp.
References Attribute::set().
Referenced by Attributes::TokenListArray::parse(), and Attributes::TokenListArray::parseComponent().
setUpperCaseString()
void Attributes::setUpperCaseString (Attribute & attr, const std::string & val)
Set uppercase string value.
Definition at line 443 of file Attributes.cpp.
References Expressions::SValue< T >::evaluate(), Attribute::getBase(), Attribute::getHandler(), Attribute::getName(), Attribute::isBaseAllocated(), Attribute::set(), Expressions::SRefAttr< T >::set(), and Util::toUpper().
Referenced by Attributes::UpperCaseString::parse(), TEST_F(), TEST_F(), and TEST_F().
setUpperCaseStringArray()
void Attributes::setUpperCaseStringArray (Attribute & attr, const std::vector< std::string > & value)
Set upper case string array value.
Definition at line 531 of file Attributes.cpp.
References Attribute::getHandler(), Attribute::getName(), and Attribute::set().
Referenced by Attributes::UpperCaseStringArray::parse(), and Attributes::UpperCaseStringArray::parseComponent().