OPALX (Object Oriented Parallel Accelerator Library for Exascal): matheval Namespace Reference
matheval Namespace Reference
Namespaces
namespace detail
Classes
class Parser
Class interface.
Functions
template<typename real_t, typename Iterator>
real_t parse (Iterator first, Iterator last, typename detail::eval_ast< real_t >::symbol_table_t const &st)
Convenience function.
template<typename real_t>
real_t parse (std::string const &str, typename detail::eval_ast< real_t >::symbol_table_t const &st)
Function Documentation
parse() [1/2]
template<typename real_t, typename Iterator> real_t matheval::parse (Iterator first, Iterator last, typename detail::eval_ast< real_t >::symbol_table_t const & st)
Convenience function.
This function builds the parser, parses the iterator to an AST, evaluates it, and returns the result.
Parameters
[in] first iterator to the start of the input sequence
[in] last iterator to the end of the input sequence
[in] st the symbol table for variables
Definition at line 743 of file matheval.hpp.
References matheval::Parser< real_t >::evaluate(), and matheval::Parser< real_t >::parse().
Referenced by mslang::parseMathExpression().
parse() [2/2]
template<typename real_t> real_t matheval::parse (std::string const & str, typename detail::eval_ast< real_t >::symbol_table_t const & st)
Definition at line 754 of file matheval.hpp.
References matheval::detail::parse().