OPALX (Object Oriented Parallel Accelerator Library for Exascal): LinearBreitWheelerBenchmark Namespace Reference
LinearBreitWheelerBenchmark Namespace Reference
Classes
struct FinitePhotonBeamConfig
Configuration for folding the linear Breit-Wheeler kernel over a finite incoming photon beam.
struct FinitePhotonBeamJointConfig
struct Histogram
struct HistogramConfig
struct JointHistogram
struct JointHistogramConfig
struct SampledPhotonBeamState
Enumerations
enum class FinalState { Electron , Positron }
enum class Observable { Energy , Theta }
Functions
double polarAngleRad (const Vector_t< double, 3 > &momentum)
double sampledObservable (const Physics::LinearBreitWheeler::SampledEvent &event, FinalState state, Observable observable)
double sampleHighEnergyPhotonEnergyGeV (double centralEnergyGeV, double relativeEnergySpread, std::mt19937_64 &engine)
void buildTransverseBasis (const Vector_t< double, 3 > &referenceDirection, Vector_t< double, 3 > &axis1, Vector_t< double, 3 > &axis2)
SampledPhotonBeamState samplePhotonBeamState (const Vector_t< double, 3 > &referenceDirection, double sigmaThetaXRad, double sigmaThetaYRad, double sigmaX_m, double sigmaY_m, double sigmaS_m, double centralEnergyGeV, double relativeEnergySpread, std::mt19937_64 &engine)
Vector_t< double, 3 > samplePhotonBeamDirection (const Vector_t< double, 3 > &referenceDirection, double sigmaThetaXRad, double sigmaThetaYRad, std::mt19937_64 &engine)
double effectiveSpatialOverlapSigma (double beamSigma_m, double waist_m)
double effectiveTemporalOverlapSigma (double beamSigmaS_m, double laserSigmaT_m)
SampledPhotonBeamState sampleOverlapPhotonBeamState (const FinitePhotonBeamConfig &config, std::mt19937_64 &engine)
SampledPhotonBeamState sampleOverlapPhotonBeamState (const FinitePhotonBeamJointConfig &config, std::mt19937_64 &engine)
Histogram sampleFinitePhotonBeamHistogram (const FinitePhotonBeamConfig &config, FinalState state, Observable observable, std::size_t sampleCount, std::uint64_t streamIndex=0)
Sample a one-dimensional Breit-Wheeler histogram for a finite incoming photon beam.
Histogram sampleHistogram (const HistogramConfig &config, FinalState state, Observable observable, std::size_t sampleCount, std::uint64_t streamIndex=0)
Sample a one-dimensional Breit-Wheeler benchmark histogram.
JointHistogram sampleFinitePhotonBeamJointHistogram (const FinitePhotonBeamJointConfig &config, FinalState state, std::size_t sampleCount, std::uint64_t streamIndex=0)
Sample the joint Breit-Wheeler laboratory distribution in energy and polar angle.
JointHistogram sampleJointHistogram (const JointHistogramConfig &config, FinalState state, std::size_t sampleCount, std::uint64_t streamIndex=0)
void writeHistogramCSV (const Histogram &histogram, const std::filesystem::path &outputPath)
void writeJointHistogramCSV (const JointHistogram &histogram, const std::filesystem::path &outputPath)
Histogram readHistogramCSV (const std::filesystem::path &inputPath)
JointHistogram readJointHistogramCSV (const std::filesystem::path &inputPath)
double histogramArea (const Histogram &histogram)
double histogramMean (const Histogram &histogram)
double histogramL1Distance (const Histogram &lhs, const Histogram &rhs)
double jointHistogramArea (const JointHistogram &histogram)
double jointHistogramMeanEnergyGeV (const JointHistogram &histogram)
double jointHistogramMeanThetaRad (const JointHistogram &histogram)
double jointHistogramL1Distance (const JointHistogram &lhs, const JointHistogram &rhs)
Class Documentation
LinearBreitWheelerBenchmark::FinitePhotonBeamConfig
struct LinearBreitWheelerBenchmark::FinitePhotonBeamConfig
Configuration for folding the linear Breit-Wheeler kernel over a finite incoming photon beam.
This benchmark keeps the laser photon fixed and samples only the incoming high-energy photon beam. The present implementation models the beam by a Gaussian spread in the transverse photon slopes around the reference beam axis and, optionally, by a Gaussian relative energy spread.
The benchmark intentionally stays momentum-space only. It does not model photon-beam position spread or laser-overlap weighting yet.
Definition at line 40 of file LinearBreitWheelerBenchmarkCommon.h.
Class Members
size_t bins = 80
double centralHighEnergyPhotonEnergyGeV = 0.5
Vector_t< double, 3 > laserDirection
double laserRayleighX_m = 1.0e-6
double laserRayleighY_m = 1.0e-6
double laserSigmaT_m = 5.0e-12 * Physics::c
double maxValue = 0.5
double minValue = 0.0
bool overlapWeighting = false
Vector_t< double, 3 > referenceHighEnergyDirection
double relativeEnergySpread = 0.0
double sigmaS_m = 0.0
double sigmaThetaXRad = 1.0e-3
double sigmaThetaYRad = 1.0e-3
double sigmaX_m = 0.0
double sigmaY_m = 0.0
double wavelength_m = 1.0e-9
LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig
struct LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig
Definition at line 115 of file LinearBreitWheelerBenchmarkCommon.h.
Class Members
double centralHighEnergyPhotonEnergyGeV = 0.5
size_t energyBins = 80
double energyMaxGeV = 0.5
double energyMinGeV = 0.0
Vector_t< double, 3 > laserDirection
double laserRayleighX_m = 1.0e-6
double laserRayleighY_m = 1.0e-6
double laserSigmaT_m = 5.0e-12 * Physics::c
bool overlapWeighting = false
Vector_t< double, 3 > referenceHighEnergyDirection
double relativeEnergySpread = 0.0
double sigmaS_m = 0.0
double sigmaThetaXRad = 1.0e-3
double sigmaThetaYRad = 1.0e-3
double sigmaX_m = 0.0
double sigmaY_m = 0.0
size_t thetaBins = 80
double thetaMaxRad = 0.0060
double thetaMinRad = 0.0
double wavelength_m = 1.0e-9
LinearBreitWheelerBenchmark::Histogram
struct LinearBreitWheelerBenchmark::Histogram
Definition at line 86 of file LinearBreitWheelerBenchmarkCommon.h.
Class Members
double binWidth = 0.0
vector< double > centers
vector< double > counts
vector< double > density
double totalWeight = 0.0
LinearBreitWheelerBenchmark::HistogramConfig
struct LinearBreitWheelerBenchmark::HistogramConfig
Definition at line 68 of file LinearBreitWheelerBenchmarkCommon.h.
Class Members
size_t bins = 80
Vector_t< double, 3 > highEnergyDirection
double highEnergyPhotonEnergyGeV = 0.5
Vector_t< double, 3 > laserDirection
double maxValue = 0.5
double minValue = 0.0
double wavelength_m = 1.0e-9
LinearBreitWheelerBenchmark::JointHistogram
struct LinearBreitWheelerBenchmark::JointHistogram
Definition at line 146 of file LinearBreitWheelerBenchmarkCommon.h.
Class Members
vector< vector< double > > counts
vector< vector< double > > densityPerGeVRad
double energyBinWidthGeV = 0.0
vector< double > energyCentersGeV
double thetaBinWidthRad = 0.0
vector< double > thetaCentersRad
double totalWeight = 0.0
LinearBreitWheelerBenchmark::JointHistogramConfig
struct LinearBreitWheelerBenchmark::JointHistogramConfig
Definition at line 94 of file LinearBreitWheelerBenchmarkCommon.h.
Class Members
size_t energyBins = 80
double energyMaxGeV = 0.5
double energyMinGeV = 0.0
Vector_t< double, 3 > highEnergyDirection
double highEnergyPhotonEnergyGeV = 0.5
Vector_t< double, 3 > laserDirection
size_t thetaBins = 80
double thetaMaxRad = 0.0045
double thetaMinRad = 0.0
double wavelength_m = 1.0e-9
LinearBreitWheelerBenchmark::SampledPhotonBeamState
struct LinearBreitWheelerBenchmark::SampledPhotonBeamState
Definition at line 175 of file LinearBreitWheelerBenchmarkCommon.h.
Class Members
Vector_t< double, 3 > direction
double energyGeV = 0.0
double s_m = 0.0
double slopeXRad = 0.0
double slopeYRad = 0.0
double x_m = 0.0
double y_m = 0.0
Enumeration Type Documentation
FinalState
enum class LinearBreitWheelerBenchmark::FinalState strong
Enumerator
Electron
Positron
Definition at line 19 of file LinearBreitWheelerBenchmarkCommon.h.
Observable
enum class LinearBreitWheelerBenchmark::Observable strong
Enumerator
Energy
Theta
Definition at line 24 of file LinearBreitWheelerBenchmarkCommon.h.
Function Documentation
buildTransverseBasis()
void LinearBreitWheelerBenchmark::buildTransverseBasis (const Vector_t< double, 3 > & referenceDirection, Vector_t< double, 3 > & axis1, Vector_t< double, 3 > & axis2) inline
Definition at line 193 of file LinearBreitWheelerBenchmarkCommon.h.
References cross(), and dot().
Referenced by samplePhotonBeamState().
effectiveSpatialOverlapSigma()
double LinearBreitWheelerBenchmark::effectiveSpatialOverlapSigma (double beamSigma_m, double waist_m) inline
Definition at line 252 of file LinearBreitWheelerBenchmarkCommon.h.
Referenced by sampleOverlapPhotonBeamState(), and sampleOverlapPhotonBeamState().
effectiveTemporalOverlapSigma()
double LinearBreitWheelerBenchmark::effectiveTemporalOverlapSigma (double beamSigmaS_m, double laserSigmaT_m) inline
Definition at line 265 of file LinearBreitWheelerBenchmarkCommon.h.
Referenced by sampleOverlapPhotonBeamState(), and sampleOverlapPhotonBeamState().
histogramArea()
double LinearBreitWheelerBenchmark::histogramArea (const Histogram & histogram) inline
Definition at line 791 of file LinearBreitWheelerBenchmarkCommon.h.
References LinearBreitWheelerBenchmark::Histogram::binWidth, and LinearBreitWheelerBenchmark::Histogram::density.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
histogramL1Distance()
double LinearBreitWheelerBenchmark::histogramL1Distance (const Histogram & lhs, const Histogram & rhs) inline
Definition at line 807 of file LinearBreitWheelerBenchmarkCommon.h.
References LinearBreitWheelerBenchmark::Histogram::binWidth, LinearBreitWheelerBenchmark::Histogram::centers, and LinearBreitWheelerBenchmark::Histogram::density.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
histogramMean()
double LinearBreitWheelerBenchmark::histogramMean (const Histogram & histogram) inline
Definition at line 799 of file LinearBreitWheelerBenchmarkCommon.h.
References LinearBreitWheelerBenchmark::Histogram::binWidth, LinearBreitWheelerBenchmark::Histogram::centers, and LinearBreitWheelerBenchmark::Histogram::density.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
jointHistogramArea()
double LinearBreitWheelerBenchmark::jointHistogramArea (const JointHistogram & histogram) inline
Definition at line 819 of file LinearBreitWheelerBenchmarkCommon.h.
References LinearBreitWheelerBenchmark::JointHistogram::densityPerGeVRad, LinearBreitWheelerBenchmark::JointHistogram::energyBinWidthGeV, and LinearBreitWheelerBenchmark::JointHistogram::thetaBinWidthRad.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
jointHistogramL1Distance()
double LinearBreitWheelerBenchmark::jointHistogramL1Distance (const JointHistogram & lhs, const JointHistogram & rhs) inline
Definition at line 851 of file LinearBreitWheelerBenchmarkCommon.h.
References LinearBreitWheelerBenchmark::JointHistogram::densityPerGeVRad, LinearBreitWheelerBenchmark::JointHistogram::energyBinWidthGeV, LinearBreitWheelerBenchmark::JointHistogram::energyCentersGeV, LinearBreitWheelerBenchmark::JointHistogram::thetaBinWidthRad, and LinearBreitWheelerBenchmark::JointHistogram::thetaCentersRad.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
jointHistogramMeanEnergyGeV()
double LinearBreitWheelerBenchmark::jointHistogramMeanEnergyGeV (const JointHistogram & histogram) inline
Definition at line 829 of file LinearBreitWheelerBenchmarkCommon.h.
References LinearBreitWheelerBenchmark::JointHistogram::densityPerGeVRad, LinearBreitWheelerBenchmark::JointHistogram::energyBinWidthGeV, LinearBreitWheelerBenchmark::JointHistogram::energyCentersGeV, LinearBreitWheelerBenchmark::JointHistogram::thetaBinWidthRad, and LinearBreitWheelerBenchmark::JointHistogram::thetaCentersRad.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
jointHistogramMeanThetaRad()
double LinearBreitWheelerBenchmark::jointHistogramMeanThetaRad (const JointHistogram & histogram) inline
Definition at line 840 of file LinearBreitWheelerBenchmarkCommon.h.
References LinearBreitWheelerBenchmark::JointHistogram::densityPerGeVRad, LinearBreitWheelerBenchmark::JointHistogram::energyBinWidthGeV, LinearBreitWheelerBenchmark::JointHistogram::energyCentersGeV, LinearBreitWheelerBenchmark::JointHistogram::thetaBinWidthRad, and LinearBreitWheelerBenchmark::JointHistogram::thetaCentersRad.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
polarAngleRad()
double LinearBreitWheelerBenchmark::polarAngleRad (const Vector_t< double, 3 > & momentum) inline
Definition at line 156 of file LinearBreitWheelerBenchmarkCommon.h.
Referenced by sampledObservable().
readHistogramCSV()
Histogram LinearBreitWheelerBenchmark::readHistogramCSV (const std::filesystem::path & inputPath) inline
Definition at line 675 of file LinearBreitWheelerBenchmarkCommon.h.
References LinearBreitWheelerBenchmark::Histogram::binWidth, LinearBreitWheelerBenchmark::Histogram::centers, LinearBreitWheelerBenchmark::Histogram::counts, LinearBreitWheelerBenchmark::Histogram::density, and LinearBreitWheelerBenchmark::Histogram::totalWeight.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
readJointHistogramCSV()
JointHistogram LinearBreitWheelerBenchmark::readJointHistogramCSV (const std::filesystem::path & inputPath) inline
Definition at line 712 of file LinearBreitWheelerBenchmarkCommon.h.
References LinearBreitWheelerBenchmark::JointHistogram::counts, LinearBreitWheelerBenchmark::JointHistogram::densityPerGeVRad, LinearBreitWheelerBenchmark::JointHistogram::energyBinWidthGeV, LinearBreitWheelerBenchmark::JointHistogram::energyCentersGeV, LinearBreitWheelerBenchmark::JointHistogram::thetaBinWidthRad, LinearBreitWheelerBenchmark::JointHistogram::thetaCentersRad, and LinearBreitWheelerBenchmark::JointHistogram::totalWeight.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
sampledObservable()
double LinearBreitWheelerBenchmark::sampledObservable (const Physics::LinearBreitWheeler::SampledEvent & event, FinalState state, Observable observable) inline
Definition at line 161 of file LinearBreitWheelerBenchmarkCommon.h.
References Physics::LinearBreitWheeler::SampledEvent::electronMomentumLabGeV, polarAngleRad(), Positron, Physics::LinearBreitWheeler::SampledEvent::positronMomentumLabGeV, and Theta.
Referenced by main(), sampleFinitePhotonBeamHistogram(), sampleFinitePhotonBeamJointHistogram(), sampleHistogram(), and sampleJointHistogram().
sampleFinitePhotonBeamHistogram()
Histogram LinearBreitWheelerBenchmark::sampleFinitePhotonBeamHistogram (const FinitePhotonBeamConfig & config, FinalState state, Observable observable, std::size_t sampleCount, std::uint64_t streamIndex = 0) inline
Sample a one-dimensional Breit-Wheeler histogram for a finite incoming photon beam.
The laser photon stays fixed. For each sampled event the incoming high-energy photon direction is drawn from a Gaussian angular spread around the reference beam axis, and the energy is optionally smeared by a Gaussian relative energy spread. The resulting per-event kernel is then sampled with the same host-side Breit-Wheeler event generator used in the fixed-geometry benchmark.
Definition at line 342 of file LinearBreitWheelerBenchmarkCommon.h.
References LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::bins, LinearBreitWheelerBenchmark::Histogram::binWidth, LinearBreitWheelerBenchmark::Histogram::centers, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::centralHighEnergyPhotonEnergyGeV, LinearBreitWheelerBenchmark::Histogram::counts, LinearBreitWheelerBenchmark::Histogram::density, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserDirection, Physics::LinearBreitWheeler::makeHostRandomEngine(), Physics::LinearBreitWheeler::makeSamplingKernel(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::maxValue, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::minValue, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::overlapWeighting, Physics::LinearBreitWheeler::photonEnergyFromWavelengthGeV(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::referenceHighEnergyDirection, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::relativeEnergySpread, sampledObservable(), Physics::LinearBreitWheeler::sampleEvent(), sampleOverlapPhotonBeamState(), samplePhotonBeamState(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaS_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaXRad, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaYRad, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaX_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaY_m, LinearBreitWheelerBenchmark::Histogram::totalWeight, and LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::wavelength_m.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
sampleFinitePhotonBeamJointHistogram()
JointHistogram LinearBreitWheelerBenchmark::sampleFinitePhotonBeamJointHistogram (const FinitePhotonBeamJointConfig & config, FinalState state, std::size_t sampleCount, std::uint64_t streamIndex = 0) inline
Sample the joint Breit-Wheeler laboratory distribution in energy and polar angle.
Each sampled event contributes to a two-dimensional histogram in \((E,\theta)\) for either the outgoing electron or positron. The resulting density is normalized so that integrating over the full histogram cell area yields unity.
Definition at line 478 of file LinearBreitWheelerBenchmarkCommon.h.
References LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::centralHighEnergyPhotonEnergyGeV, LinearBreitWheelerBenchmark::JointHistogram::counts, LinearBreitWheelerBenchmark::JointHistogram::densityPerGeVRad, Energy, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::energyBins, LinearBreitWheelerBenchmark::JointHistogram::energyBinWidthGeV, LinearBreitWheelerBenchmark::JointHistogram::energyCentersGeV, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::energyMaxGeV, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::energyMinGeV, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::laserDirection, Physics::LinearBreitWheeler::makeHostRandomEngine(), Physics::LinearBreitWheeler::makeSamplingKernel(), LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::overlapWeighting, Physics::LinearBreitWheeler::photonEnergyFromWavelengthGeV(), LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::referenceHighEnergyDirection, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::relativeEnergySpread, sampledObservable(), Physics::LinearBreitWheeler::sampleEvent(), sampleOverlapPhotonBeamState(), samplePhotonBeamState(), LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaS_m, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaThetaXRad, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaThetaYRad, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaX_m, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaY_m, Theta, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::thetaBins, LinearBreitWheelerBenchmark::JointHistogram::thetaBinWidthRad, LinearBreitWheelerBenchmark::JointHistogram::thetaCentersRad, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::thetaMaxRad, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::thetaMinRad, LinearBreitWheelerBenchmark::JointHistogram::totalWeight, and LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::wavelength_m.
Referenced by main(), TEST(), TEST(), TEST(), and TEST().
sampleHighEnergyPhotonEnergyGeV()
double LinearBreitWheelerBenchmark::sampleHighEnergyPhotonEnergyGeV (double centralEnergyGeV, double relativeEnergySpread, std::mt19937_64 & engine) inline
Definition at line 318 of file LinearBreitWheelerBenchmarkCommon.h.
Referenced by samplePhotonBeamState().
sampleHistogram()
Histogram LinearBreitWheelerBenchmark::sampleHistogram (const HistogramConfig & config, FinalState state, Observable observable, std::size_t sampleCount, std::uint64_t streamIndex = 0) inline
Sample a one-dimensional Breit-Wheeler benchmark histogram.
The first CAIN-backed OPALX validation path is intentionally host-only and fixed-geometry. This helper mirrors the standalone benchmark executable: it builds one cached LinearBreitWheeler::SamplingKernel, draws a fixed number of sampled events, and bins either the outgoing electron or positron energy or polar angle in the lab frame.
Definition at line 418 of file LinearBreitWheelerBenchmarkCommon.h.
References LinearBreitWheelerBenchmark::HistogramConfig::bins, LinearBreitWheelerBenchmark::Histogram::binWidth, LinearBreitWheelerBenchmark::Histogram::centers, LinearBreitWheelerBenchmark::Histogram::counts, LinearBreitWheelerBenchmark::Histogram::density, LinearBreitWheelerBenchmark::HistogramConfig::highEnergyDirection, LinearBreitWheelerBenchmark::HistogramConfig::highEnergyPhotonEnergyGeV, LinearBreitWheelerBenchmark::HistogramConfig::laserDirection, Physics::LinearBreitWheeler::makeHostRandomEngine(), Physics::LinearBreitWheeler::makeSamplingKernel(), LinearBreitWheelerBenchmark::HistogramConfig::maxValue, LinearBreitWheelerBenchmark::HistogramConfig::minValue, Physics::LinearBreitWheeler::photonEnergyFromWavelengthGeV(), sampledObservable(), Physics::LinearBreitWheeler::sampleEvent(), LinearBreitWheelerBenchmark::Histogram::totalWeight, and LinearBreitWheelerBenchmark::HistogramConfig::wavelength_m.
Referenced by TEST(), TEST(), TEST(), and TEST().
sampleJointHistogram()
JointHistogram LinearBreitWheelerBenchmark::sampleJointHistogram (const JointHistogramConfig & config, FinalState state, std::size_t sampleCount, std::uint64_t streamIndex = 0) inline
Definition at line 567 of file LinearBreitWheelerBenchmarkCommon.h.
References LinearBreitWheelerBenchmark::JointHistogram::counts, LinearBreitWheelerBenchmark::JointHistogram::densityPerGeVRad, Energy, LinearBreitWheelerBenchmark::JointHistogramConfig::energyBins, LinearBreitWheelerBenchmark::JointHistogram::energyBinWidthGeV, LinearBreitWheelerBenchmark::JointHistogram::energyCentersGeV, LinearBreitWheelerBenchmark::JointHistogramConfig::energyMaxGeV, LinearBreitWheelerBenchmark::JointHistogramConfig::energyMinGeV, LinearBreitWheelerBenchmark::JointHistogramConfig::highEnergyDirection, LinearBreitWheelerBenchmark::JointHistogramConfig::highEnergyPhotonEnergyGeV, LinearBreitWheelerBenchmark::JointHistogramConfig::laserDirection, Physics::LinearBreitWheeler::makeHostRandomEngine(), Physics::LinearBreitWheeler::makeSamplingKernel(), Physics::LinearBreitWheeler::photonEnergyFromWavelengthGeV(), sampledObservable(), Physics::LinearBreitWheeler::sampleEvent(), Theta, LinearBreitWheelerBenchmark::JointHistogramConfig::thetaBins, LinearBreitWheelerBenchmark::JointHistogram::thetaBinWidthRad, LinearBreitWheelerBenchmark::JointHistogram::thetaCentersRad, LinearBreitWheelerBenchmark::JointHistogramConfig::thetaMaxRad, LinearBreitWheelerBenchmark::JointHistogramConfig::thetaMinRad, LinearBreitWheelerBenchmark::JointHistogram::totalWeight, and LinearBreitWheelerBenchmark::JointHistogramConfig::wavelength_m.
Referenced by main(), TEST(), and TEST().
sampleOverlapPhotonBeamState() [1/2]
SampledPhotonBeamState LinearBreitWheelerBenchmark::sampleOverlapPhotonBeamState (const FinitePhotonBeamConfig & config, std::mt19937_64 & engine) inline
Definition at line 278 of file LinearBreitWheelerBenchmarkCommon.h.
References LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::centralHighEnergyPhotonEnergyGeV, effectiveSpatialOverlapSigma(), effectiveTemporalOverlapSigma(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserRayleighX_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserRayleighY_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserSigmaT_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::referenceHighEnergyDirection, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::relativeEnergySpread, samplePhotonBeamState(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaS_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaXRad, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaYRad, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaX_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaY_m, and LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::wavelength_m.
Referenced by main(), sampleFinitePhotonBeamHistogram(), and sampleFinitePhotonBeamJointHistogram().
sampleOverlapPhotonBeamState() [2/2]
SampledPhotonBeamState LinearBreitWheelerBenchmark::sampleOverlapPhotonBeamState (const FinitePhotonBeamJointConfig & config, std::mt19937_64 & engine) inline
Definition at line 298 of file LinearBreitWheelerBenchmarkCommon.h.
References LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::centralHighEnergyPhotonEnergyGeV, effectiveSpatialOverlapSigma(), effectiveTemporalOverlapSigma(), LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::laserRayleighX_m, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::laserRayleighY_m, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::laserSigmaT_m, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::referenceHighEnergyDirection, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::relativeEnergySpread, samplePhotonBeamState(), LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaS_m, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaThetaXRad, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaThetaYRad, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaX_m, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaY_m, and LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::wavelength_m.
samplePhotonBeamDirection()
Vector_t< double, 3 > LinearBreitWheelerBenchmark::samplePhotonBeamDirection (const Vector_t< double, 3 > & referenceDirection, double sigmaThetaXRad, double sigmaThetaYRad, std::mt19937_64 & engine) inline
Definition at line 237 of file LinearBreitWheelerBenchmarkCommon.h.
References LinearBreitWheelerBenchmark::SampledPhotonBeamState::direction, and samplePhotonBeamState().
samplePhotonBeamState()
SampledPhotonBeamState LinearBreitWheelerBenchmark::samplePhotonBeamState (const Vector_t< double, 3 > & referenceDirection, double sigmaThetaXRad, double sigmaThetaYRad, double sigmaX_m, double sigmaY_m, double sigmaS_m, double centralEnergyGeV, double relativeEnergySpread, std::mt19937_64 & engine) inline
Definition at line 210 of file LinearBreitWheelerBenchmarkCommon.h.
References buildTransverseBasis(), LinearBreitWheelerBenchmark::SampledPhotonBeamState::direction, dot(), LinearBreitWheelerBenchmark::SampledPhotonBeamState::energyGeV, LinearBreitWheelerBenchmark::SampledPhotonBeamState::s_m, sampleHighEnergyPhotonEnergyGeV(), LinearBreitWheelerBenchmark::SampledPhotonBeamState::slopeXRad, LinearBreitWheelerBenchmark::SampledPhotonBeamState::slopeYRad, LinearBreitWheelerBenchmark::SampledPhotonBeamState::x_m, and LinearBreitWheelerBenchmark::SampledPhotonBeamState::y_m.
Referenced by main(), sampleFinitePhotonBeamHistogram(), sampleFinitePhotonBeamJointHistogram(), sampleOverlapPhotonBeamState(), sampleOverlapPhotonBeamState(), and samplePhotonBeamDirection().
writeHistogramCSV()
void LinearBreitWheelerBenchmark::writeHistogramCSV (const Histogram & histogram, const std::filesystem::path & outputPath) inline
Definition at line 640 of file LinearBreitWheelerBenchmarkCommon.h.
References LinearBreitWheelerBenchmark::Histogram::centers, LinearBreitWheelerBenchmark::Histogram::counts, and LinearBreitWheelerBenchmark::Histogram::density.
writeJointHistogramCSV()
void LinearBreitWheelerBenchmark::writeJointHistogramCSV (const JointHistogram & histogram, const std::filesystem::path & outputPath) inline
Definition at line 656 of file LinearBreitWheelerBenchmarkCommon.h.
References LinearBreitWheelerBenchmark::JointHistogram::counts, LinearBreitWheelerBenchmark::JointHistogram::densityPerGeVRad, LinearBreitWheelerBenchmark::JointHistogram::energyCentersGeV, and LinearBreitWheelerBenchmark::JointHistogram::thetaCentersRad.
Referenced by main().