OPALX (Object Oriented Parallel Accelerator Library for Exascal): matheval::detail Namespace Reference
matheval::detail Namespace Reference
Namespaces
namespace math
Classes
struct binary_op
Store a binary operator and its argument trees.
struct ConstantFolder
class eval_ast
Evaluate the Abstract Syntax Tree.
struct expr_ast
Abstract Syntax Tree.
struct holds_alternative_impl
struct nil
struct recursive_wrapper
class SimpleMathParser
struct unary_op
Store a unary operator and its argument tree.
Functions
template<typename T, typename... Ts>
bool holds_alternative (std::variant< Ts... > const &v)
template<typename real_t, typename Iterator>
expr_ast< real_t > parse (Iterator first, Iterator last)
Parse an expression.
Class Documentation
matheval::detail::nil
struct matheval::detail::nil
Definition at line 93 of file matheval.hpp.
Function Documentation
holds_alternative()
template<typename T, typename... Ts> bool matheval::detail::holds_alternative (std::variant< Ts... > const & v)
Definition at line 344 of file matheval.hpp.
Referenced by matheval::detail::ConstantFolder< real_t >::operator()(), and matheval::detail::ConstantFolder< real_t >::operator()().
parse()
template<typename real_t, typename Iterator> expr_ast< real_t > matheval::detail::parse (Iterator first, Iterator last)
Parse an expression.
This function builds the parser and parses the string into an AST.
Parameters
[in] first iterator to the start of the input sequence
[in] last iterator to the end of the input sequence
Definition at line 685 of file matheval.hpp.
References matheval::detail::SimpleMathParser< real_t >::parse().
Referenced by matheval::parse(), and matheval::Parser< real_t >::parse().