OPALX (Object Oriented Parallel Accelerator Library for Exascal): LinearComptonBenchmark Namespace Reference
LinearComptonBenchmark Namespace Reference
Classes
struct AngleConfig
struct AngleHistogram
struct JointConfig
struct JointHistogram
struct SpectrumConfig
struct SpectrumHistogram
Functions
SpectrumHistogram integrateLabSpectrum (const SpectrumConfig &config)
SpectrumHistogram sampleLabSpectrum (const SpectrumConfig &config, std::size_t sampleCount, std::uint64_t streamIndex=0)
void writeSpectrumCSV (const SpectrumHistogram &histogram, const std::filesystem::path &outputPath)
SpectrumHistogram readSpectrumCSV (const std::filesystem::path &inputPath)
double histogramMeanEnergyGeV (const SpectrumHistogram &histogram)
double histogramArea (const SpectrumHistogram &histogram)
double histogramL1Distance (const SpectrumHistogram &lhs, const SpectrumHistogram &rhs)
double photonPolarAngleRad (const Vector_t< double, 3 > &photonDirection, const Vector_t< double, 3 > &beamDirection)
AngleHistogram integrateLabAngularSpectrum (const AngleConfig &config)
AngleHistogram sampleLabAngularSpectrum (const AngleConfig &config, std::size_t sampleCount, std::uint64_t streamIndex=0)
void writeAngleCSV (const AngleHistogram &histogram, const std::filesystem::path &outputPath)
AngleHistogram readAngleCSV (const std::filesystem::path &inputPath)
double angleHistogramMeanRad (const AngleHistogram &histogram)
double angleHistogramArea (const AngleHistogram &histogram)
double angleHistogramL1Distance (const AngleHistogram &lhs, const AngleHistogram &rhs)
std::size_t jointHistogramIndex (const JointHistogram &histogram, std::size_t energyBin, std::size_t thetaBin)
JointHistogram integrateLabJointSpectrum (const JointConfig &config)
JointHistogram sampleLabJointSpectrum (const JointConfig &config, std::size_t sampleCount, std::uint64_t streamIndex=0)
void writeJointCSV (const JointHistogram &histogram, const std::filesystem::path &outputPath)
JointHistogram readJointCSV (const std::filesystem::path &inputPath)
double jointHistogramArea (const JointHistogram &histogram)
double jointHistogramMeanEnergyGeV (const JointHistogram &histogram)
double jointHistogramMeanThetaRad (const JointHistogram &histogram)
double jointHistogramL1Distance (const JointHistogram &lhs, const JointHistogram &rhs)
Class Documentation
LinearComptonBenchmark::AngleConfig
struct LinearComptonBenchmark::AngleConfig
Definition at line 251 of file LinearComptonSpectrumCommon.h.
Class Members
int azimuthPanels = 720
Vector_t< double, 3 > beamDirection
size_t bins = 80
int cosinePanels = 720
double electronTotalEnergyGeV = 1.0
Vector_t< double, 3 > laserDirection
double thetaMaxRad = 0.02
double thetaMinRad = 0.0
double wavelength_m = 1.03e-6
LinearComptonBenchmark::AngleHistogram
struct LinearComptonBenchmark::AngleHistogram
Definition at line 271 of file LinearComptonSpectrumCommon.h.
Class Members
double binWidthRad = 0.0
vector< double > centersRad
vector< double > counts
vector< double > densityPerRad
double totalWeight = 0.0
LinearComptonBenchmark::JointConfig
struct LinearComptonBenchmark::JointConfig
Definition at line 495 of file LinearComptonSpectrumCommon.h.
Class Members
int azimuthPanels = 720
Vector_t< double, 3 > beamDirection
int cosinePanels = 720
double electronTotalEnergyGeV = 1.0
size_t energyBins = 60
double energyMaxGeV = 0.01
double energyMinGeV = 0.0
Vector_t< double, 3 > laserDirection
size_t thetaBins = 60
double thetaMaxRad = 0.02
double thetaMinRad = 0.0
double wavelength_m = 1.03e-6
LinearComptonBenchmark::JointHistogram
struct LinearComptonBenchmark::JointHistogram
Definition at line 518 of file LinearComptonSpectrumCommon.h.
Class Members
vector< double > counts
vector< double > densityPerGeVRad
double energyBinWidthGeV = 0.0
vector< double > energyCentersGeV
double thetaBinWidthRad = 0.0
vector< double > thetaCentersRad
double totalWeight = 0.0
LinearComptonBenchmark::SpectrumConfig
struct LinearComptonBenchmark::SpectrumConfig
Definition at line 20 of file LinearComptonSpectrumCommon.h.
Class Members
int azimuthPanels = 720
Vector_t< double, 3 > beamDirection
size_t bins = 80
int cosinePanels = 720
double electronTotalEnergyGeV = 1.0
double energyMaxGeV = 0.01
double energyMinGeV = 0.0
Vector_t< double, 3 > laserDirection
double wavelength_m = 1.03e-6
LinearComptonBenchmark::SpectrumHistogram
struct LinearComptonBenchmark::SpectrumHistogram
Definition at line 40 of file LinearComptonSpectrumCommon.h.
Class Members
double binWidthGeV = 0.0
vector< double > centersGeV
vector< double > counts
vector< double > densityPerGeV
double totalWeight = 0.0
Function Documentation
angleHistogramArea()
double LinearComptonBenchmark::angleHistogramArea (const AngleHistogram & histogram) inline
Definition at line 473 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::AngleHistogram::binWidthRad, and LinearComptonBenchmark::AngleHistogram::densityPerRad.
Referenced by main(), TEST(), TEST(), TEST(), TEST(), and TEST().
angleHistogramL1Distance()
double LinearComptonBenchmark::angleHistogramL1Distance (const AngleHistogram & lhs, const AngleHistogram & rhs) inline
Definition at line 481 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::AngleHistogram::binWidthRad, LinearComptonBenchmark::AngleHistogram::centersRad, and LinearComptonBenchmark::AngleHistogram::densityPerRad.
Referenced by TEST(), TEST(), TEST(), TEST(), and TEST().
angleHistogramMeanRad()
double LinearComptonBenchmark::angleHistogramMeanRad (const AngleHistogram & histogram) inline
Definition at line 465 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::AngleHistogram::binWidthRad, LinearComptonBenchmark::AngleHistogram::centersRad, and LinearComptonBenchmark::AngleHistogram::densityPerRad.
Referenced by main(), TEST(), TEST(), TEST(), TEST(), and TEST().
histogramArea()
double LinearComptonBenchmark::histogramArea (const SpectrumHistogram & histogram) inline
Definition at line 229 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::SpectrumHistogram::binWidthGeV, and LinearComptonBenchmark::SpectrumHistogram::densityPerGeV.
Referenced by main(), TEST(), TEST(), TEST(), TEST(), and TEST().
histogramL1Distance()
double LinearComptonBenchmark::histogramL1Distance (const SpectrumHistogram & lhs, const SpectrumHistogram & rhs) inline
Definition at line 237 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::SpectrumHistogram::binWidthGeV, LinearComptonBenchmark::SpectrumHistogram::centersGeV, and LinearComptonBenchmark::SpectrumHistogram::densityPerGeV.
Referenced by TEST(), TEST(), TEST(), TEST(), and TEST().
histogramMeanEnergyGeV()
double LinearComptonBenchmark::histogramMeanEnergyGeV (const SpectrumHistogram & histogram) inline
Definition at line 221 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::SpectrumHistogram::binWidthGeV, LinearComptonBenchmark::SpectrumHistogram::centersGeV, and LinearComptonBenchmark::SpectrumHistogram::densityPerGeV.
Referenced by main(), TEST(), TEST(), TEST(), TEST(), and TEST().
integrateLabAngularSpectrum()
AngleHistogram LinearComptonBenchmark::integrateLabAngularSpectrum (const AngleConfig & config) inline
Definition at line 291 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::AngleConfig::azimuthPanels, LinearComptonBenchmark::AngleConfig::beamDirection, LinearComptonBenchmark::AngleConfig::bins, LinearComptonBenchmark::AngleHistogram::binWidthRad, LinearComptonBenchmark::AngleHistogram::centersRad, LinearComptonBenchmark::AngleConfig::cosinePanels, LinearComptonBenchmark::AngleHistogram::counts, LinearComptonBenchmark::AngleHistogram::densityPerRad, Physics::LinearCompton::differentialCrossSectionSolidAngleERF(), LinearComptonBenchmark::AngleConfig::electronTotalEnergyGeV, Physics::LinearCompton::labPhotonDirection(), LinearComptonBenchmark::AngleConfig::laserDirection, Physics::LinearCompton::photonEnergyFromWavelengthGeV(), photonPolarAngleRad(), Physics::LinearCompton::restFrameIncomingPhotonEnergyGeV(), LinearComptonBenchmark::AngleConfig::thetaMaxRad, LinearComptonBenchmark::AngleConfig::thetaMinRad, LinearComptonBenchmark::AngleHistogram::totalWeight, Physics::two_pi, and LinearComptonBenchmark::AngleConfig::wavelength_m.
Referenced by main(), and TEST().
integrateLabJointSpectrum()
JointHistogram LinearComptonBenchmark::integrateLabJointSpectrum (const JointConfig & config) inline
Definition at line 534 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::JointConfig::azimuthPanels, LinearComptonBenchmark::JointConfig::beamDirection, LinearComptonBenchmark::JointConfig::cosinePanels, LinearComptonBenchmark::JointHistogram::counts, LinearComptonBenchmark::JointHistogram::densityPerGeVRad, Physics::LinearCompton::differentialCrossSectionSolidAngleERF(), LinearComptonBenchmark::JointConfig::electronTotalEnergyGeV, LinearComptonBenchmark::JointConfig::energyBins, LinearComptonBenchmark::JointHistogram::energyBinWidthGeV, LinearComptonBenchmark::JointHistogram::energyCentersGeV, LinearComptonBenchmark::JointConfig::energyMaxGeV, LinearComptonBenchmark::JointConfig::energyMinGeV, jointHistogramIndex(), Physics::LinearCompton::labPhotonDirection(), Physics::LinearCompton::labPhotonEnergyGeV(), LinearComptonBenchmark::JointConfig::laserDirection, Physics::LinearCompton::photonEnergyFromWavelengthGeV(), photonPolarAngleRad(), Physics::LinearCompton::restFrameIncomingPhotonEnergyGeV(), LinearComptonBenchmark::JointConfig::thetaBins, LinearComptonBenchmark::JointHistogram::thetaBinWidthRad, LinearComptonBenchmark::JointHistogram::thetaCentersRad, LinearComptonBenchmark::JointConfig::thetaMaxRad, LinearComptonBenchmark::JointConfig::thetaMinRad, LinearComptonBenchmark::JointHistogram::totalWeight, Physics::two_pi, and LinearComptonBenchmark::JointConfig::wavelength_m.
Referenced by main(), and TEST().
integrateLabSpectrum()
SpectrumHistogram LinearComptonBenchmark::integrateLabSpectrum (const SpectrumConfig & config) inline
Definition at line 48 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::SpectrumConfig::azimuthPanels, LinearComptonBenchmark::SpectrumConfig::beamDirection, LinearComptonBenchmark::SpectrumConfig::bins, LinearComptonBenchmark::SpectrumHistogram::binWidthGeV, LinearComptonBenchmark::SpectrumHistogram::centersGeV, LinearComptonBenchmark::SpectrumConfig::cosinePanels, LinearComptonBenchmark::SpectrumHistogram::counts, LinearComptonBenchmark::SpectrumHistogram::densityPerGeV, Physics::LinearCompton::differentialCrossSectionSolidAngleERF(), LinearComptonBenchmark::SpectrumConfig::electronTotalEnergyGeV, LinearComptonBenchmark::SpectrumConfig::energyMaxGeV, LinearComptonBenchmark::SpectrumConfig::energyMinGeV, Physics::LinearCompton::labPhotonEnergyGeV(), LinearComptonBenchmark::SpectrumConfig::laserDirection, Physics::LinearCompton::photonEnergyFromWavelengthGeV(), Physics::LinearCompton::restFrameIncomingPhotonEnergyGeV(), LinearComptonBenchmark::SpectrumHistogram::totalWeight, Physics::two_pi, and LinearComptonBenchmark::SpectrumConfig::wavelength_m.
Referenced by main(), and TEST().
jointHistogramArea()
double LinearComptonBenchmark::jointHistogramArea (const JointHistogram & histogram) inline
Definition at line 792 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::JointHistogram::densityPerGeVRad, LinearComptonBenchmark::JointHistogram::energyBinWidthGeV, and LinearComptonBenchmark::JointHistogram::thetaBinWidthRad.
Referenced by main(), TEST(), TEST(), TEST(), and TEST().
jointHistogramIndex()
std::size_t LinearComptonBenchmark::jointHistogramIndex (const JointHistogram & histogram, std::size_t energyBin, std::size_t thetaBin) inline
Definition at line 528 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::JointHistogram::thetaCentersRad.
Referenced by integrateLabJointSpectrum(), jointHistogramMeanEnergyGeV(), jointHistogramMeanThetaRad(), readJointCSV(), sampleLabJointSpectrum(), and writeJointCSV().
jointHistogramL1Distance()
double LinearComptonBenchmark::jointHistogramL1Distance (const JointHistogram & lhs, const JointHistogram & rhs) inline
Definition at line 825 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::JointHistogram::densityPerGeVRad, LinearComptonBenchmark::JointHistogram::energyBinWidthGeV, LinearComptonBenchmark::JointHistogram::energyCentersGeV, LinearComptonBenchmark::JointHistogram::thetaBinWidthRad, and LinearComptonBenchmark::JointHistogram::thetaCentersRad.
Referenced by TEST(), TEST(), TEST(), and TEST().
jointHistogramMeanEnergyGeV()
double LinearComptonBenchmark::jointHistogramMeanEnergyGeV (const JointHistogram & histogram) inline
Definition at line 801 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::JointHistogram::densityPerGeVRad, LinearComptonBenchmark::JointHistogram::energyBinWidthGeV, LinearComptonBenchmark::JointHistogram::energyCentersGeV, jointHistogramIndex(), LinearComptonBenchmark::JointHistogram::thetaBinWidthRad, and LinearComptonBenchmark::JointHistogram::thetaCentersRad.
Referenced by main(), TEST(), TEST(), TEST(), and TEST().
jointHistogramMeanThetaRad()
double LinearComptonBenchmark::jointHistogramMeanThetaRad (const JointHistogram & histogram) inline
Definition at line 813 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::JointHistogram::densityPerGeVRad, LinearComptonBenchmark::JointHistogram::energyBinWidthGeV, LinearComptonBenchmark::JointHistogram::energyCentersGeV, jointHistogramIndex(), LinearComptonBenchmark::JointHistogram::thetaBinWidthRad, and LinearComptonBenchmark::JointHistogram::thetaCentersRad.
Referenced by main(), TEST(), TEST(), TEST(), and TEST().
photonPolarAngleRad()
double LinearComptonBenchmark::photonPolarAngleRad (const Vector_t< double, 3 > & photonDirection, const Vector_t< double, 3 > & beamDirection) inline
Definition at line 279 of file LinearComptonSpectrumCommon.h.
References dot().
Referenced by integrateLabAngularSpectrum(), integrateLabJointSpectrum(), sampleLabAngularSpectrum(), and sampleLabJointSpectrum().
readAngleCSV()
AngleHistogram LinearComptonBenchmark::readAngleCSV (const std::filesystem::path & inputPath) inline
Definition at line 425 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::AngleHistogram::binWidthRad, LinearComptonBenchmark::AngleHistogram::centersRad, LinearComptonBenchmark::AngleHistogram::counts, LinearComptonBenchmark::AngleHistogram::densityPerRad, and LinearComptonBenchmark::AngleHistogram::totalWeight.
Referenced by TEST(), TEST(), TEST(), TEST(), and TEST().
readJointCSV()
JointHistogram LinearComptonBenchmark::readJointCSV (const std::filesystem::path & inputPath) inline
Definition at line 703 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::JointHistogram::counts, LinearComptonBenchmark::JointHistogram::densityPerGeVRad, LinearComptonBenchmark::JointHistogram::energyBinWidthGeV, LinearComptonBenchmark::JointHistogram::energyCentersGeV, jointHistogramIndex(), LinearComptonBenchmark::JointHistogram::thetaBinWidthRad, LinearComptonBenchmark::JointHistogram::thetaCentersRad, and LinearComptonBenchmark::JointHistogram::totalWeight.
Referenced by TEST(), TEST(), TEST(), and TEST().
readSpectrumCSV()
SpectrumHistogram LinearComptonBenchmark::readSpectrumCSV (const std::filesystem::path & inputPath) inline
Definition at line 181 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::SpectrumHistogram::binWidthGeV, LinearComptonBenchmark::SpectrumHistogram::centersGeV, LinearComptonBenchmark::SpectrumHistogram::counts, LinearComptonBenchmark::SpectrumHistogram::densityPerGeV, and LinearComptonBenchmark::SpectrumHistogram::totalWeight.
Referenced by TEST(), TEST(), TEST(), TEST(), and TEST().
sampleLabAngularSpectrum()
AngleHistogram LinearComptonBenchmark::sampleLabAngularSpectrum (const AngleConfig & config, std::size_t sampleCount, std::uint64_t streamIndex = 0) inline
Definition at line 357 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::AngleConfig::beamDirection, LinearComptonBenchmark::AngleConfig::bins, LinearComptonBenchmark::AngleHistogram::binWidthRad, LinearComptonBenchmark::AngleHistogram::centersRad, LinearComptonBenchmark::AngleHistogram::counts, LinearComptonBenchmark::AngleHistogram::densityPerRad, LinearComptonBenchmark::AngleConfig::electronTotalEnergyGeV, LinearComptonBenchmark::AngleConfig::laserDirection, Physics::LinearCompton::makeHostRandomEngine(), Physics::LinearCompton::makeSamplingKernel(), Physics::LinearCompton::photonEnergyFromWavelengthGeV(), photonPolarAngleRad(), Physics::LinearCompton::sampleEvent(), LinearComptonBenchmark::AngleConfig::thetaMaxRad, LinearComptonBenchmark::AngleConfig::thetaMinRad, LinearComptonBenchmark::AngleHistogram::totalWeight, and LinearComptonBenchmark::AngleConfig::wavelength_m.
Referenced by main(), and TEST().
sampleLabJointSpectrum()
JointHistogram LinearComptonBenchmark::sampleLabJointSpectrum (const JointConfig & config, std::size_t sampleCount, std::uint64_t streamIndex = 0) inline
Definition at line 618 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::JointConfig::beamDirection, LinearComptonBenchmark::JointHistogram::counts, LinearComptonBenchmark::JointHistogram::densityPerGeVRad, LinearComptonBenchmark::JointConfig::electronTotalEnergyGeV, LinearComptonBenchmark::JointConfig::energyBins, LinearComptonBenchmark::JointHistogram::energyBinWidthGeV, LinearComptonBenchmark::JointHistogram::energyCentersGeV, LinearComptonBenchmark::JointConfig::energyMaxGeV, LinearComptonBenchmark::JointConfig::energyMinGeV, jointHistogramIndex(), LinearComptonBenchmark::JointConfig::laserDirection, Physics::LinearCompton::makeHostRandomEngine(), Physics::LinearCompton::makeSamplingKernel(), Physics::LinearCompton::photonEnergyFromWavelengthGeV(), photonPolarAngleRad(), Physics::LinearCompton::sampleEvent(), LinearComptonBenchmark::JointConfig::thetaBins, LinearComptonBenchmark::JointHistogram::thetaBinWidthRad, LinearComptonBenchmark::JointHistogram::thetaCentersRad, LinearComptonBenchmark::JointConfig::thetaMaxRad, LinearComptonBenchmark::JointConfig::thetaMinRad, LinearComptonBenchmark::JointHistogram::totalWeight, and LinearComptonBenchmark::JointConfig::wavelength_m.
Referenced by main(), and TEST().
sampleLabSpectrum()
SpectrumHistogram LinearComptonBenchmark::sampleLabSpectrum (const SpectrumConfig & config, std::size_t sampleCount, std::uint64_t streamIndex = 0) inline
Definition at line 114 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::SpectrumConfig::beamDirection, LinearComptonBenchmark::SpectrumConfig::bins, LinearComptonBenchmark::SpectrumHistogram::binWidthGeV, LinearComptonBenchmark::SpectrumHistogram::centersGeV, LinearComptonBenchmark::SpectrumHistogram::counts, LinearComptonBenchmark::SpectrumHistogram::densityPerGeV, LinearComptonBenchmark::SpectrumConfig::electronTotalEnergyGeV, LinearComptonBenchmark::SpectrumConfig::energyMaxGeV, LinearComptonBenchmark::SpectrumConfig::energyMinGeV, LinearComptonBenchmark::SpectrumConfig::laserDirection, Physics::LinearCompton::makeHostRandomEngine(), Physics::LinearCompton::makeSamplingKernel(), Physics::LinearCompton::photonEnergyFromWavelengthGeV(), Physics::LinearCompton::sampleEvent(), LinearComptonBenchmark::SpectrumHistogram::totalWeight, and LinearComptonBenchmark::SpectrumConfig::wavelength_m.
Referenced by main(), and TEST().
writeAngleCSV()
void LinearComptonBenchmark::writeAngleCSV (const AngleHistogram & histogram, const std::filesystem::path & outputPath) inline
Definition at line 408 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::AngleHistogram::centersRad, LinearComptonBenchmark::AngleHistogram::counts, and LinearComptonBenchmark::AngleHistogram::densityPerRad.
Referenced by main().
writeJointCSV()
void LinearComptonBenchmark::writeJointCSV (const JointHistogram & histogram, const std::filesystem::path & outputPath) inline
Definition at line 682 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::JointHistogram::counts, LinearComptonBenchmark::JointHistogram::densityPerGeVRad, LinearComptonBenchmark::JointHistogram::energyCentersGeV, jointHistogramIndex(), and LinearComptonBenchmark::JointHistogram::thetaCentersRad.
Referenced by main().
writeSpectrumCSV()
void LinearComptonBenchmark::writeSpectrumCSV (const SpectrumHistogram & histogram, const std::filesystem::path & outputPath) inline
Definition at line 164 of file LinearComptonSpectrumCommon.h.
References LinearComptonBenchmark::SpectrumHistogram::centersGeV, LinearComptonBenchmark::SpectrumHistogram::counts, and LinearComptonBenchmark::SpectrumHistogram::densityPerGeV.
Referenced by main().