OPALX (Object Oriented Parallel Accelerator Library for Exascal): mslang Namespace Reference
mslang Namespace Reference
Classes
struct AffineTransformation
struct ArgumentExtractor
struct Base
struct BoundingBox2D
struct Difference
struct Ellipse
struct Function
struct Intersection
struct Mask
struct Polygon
struct QuadTree
struct Rectangle
struct Repeat
struct Rotation
struct Shear
struct SymmetricDifference
struct Translation
struct Triangle
struct Union
Typedefs
typedef std::string::iterator iterator
Functions
bool parse (std::string str, Function *&fun)
double euclidean_norm2D (Vector_t< double, 3 > v)
std::ostream & operator<< (std::ostream &out, const BoundingBox2D &bb)
double parseMathExpression (const std::string &str)
Typedef Documentation
iterator
typedef std::string::iterator mslang::iterator
Definition at line 14 of file MSLang.h.
Function Documentation
euclidean_norm2D()
double mslang::euclidean_norm2D (Vector_t< double, 3 > v) inline
Definition at line 16 of file MSLang.h.
References euclidean_norm().
Referenced by Mesher::computeMinimumAngle(), and getAngleBetweenEdges().
operator<<()
std::ostream & mslang::operator<< (std::ostream & out, const BoundingBox2D & bb)
Definition at line 68 of file BoundingBox2D.cpp.
References mslang::BoundingBox2D::print().
parse()
bool mslang::parse (std::string str, Function *& fun)
Definition at line 36 of file MSLang.cpp.
References mslang::Function::parse().
parseMathExpression()
double mslang::parseMathExpression (const std::string & str)
Definition at line 4 of file matheval.cpp.
References matheval::parse().
Referenced by mslang::Ellipse::parse_detail(), mslang::Mask::parse_detail(), mslang::Polygon::parse_detail(), mslang::Rectangle::parse_detail(), mslang::Repeat::parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), and mslang::Translation::parse_detail().