OPALX (Object Oriented Parallel Accelerator Library for Exascal): interpolation Namespace Reference
interpolation Namespace Reference
Classes
class Interpolator3dGridTo1d
class Interpolator3dGridTo3d
class Mesh
Base class for meshing routines.
class MMatrix
class MVector
class NDGrid
class PolynomialCoefficient
PolynomialCoefficient represents a coefficient in a multi-dimensional polynomial.
class PolynomialPatch
Patches together many SquarePolynomialVectors to make a multidimensional polynomial spline.
class PPSolveFactory
PPSolveFactory solves the system of linear equations to interpolate from a grid of points using higher order polynomials, creating a PolynomialPatch object. The order of the polynomial is user-defined.
class SolveFactory
SolveFactory is a factory class for solving a set of linear equations to generate a polynomial based on nearby points.
class SquarePolynomialVector
SquarePolynomialVector describes a vector of multivariate polynomials.
class ThreeDGrid
class TriLinearInterpolator
class VectorMap
Typedefs
typedef gsl_complex m_complex
typedef PolynomialCoefficient Coeff
Functions
std::ostream & operator<< (std::ostream &out, const Mesh::Iterator &it)
Mesh::Iterator & operator++ (Mesh::Iterator &lhs)
Mesh::Iterator & operator-- (Mesh::Iterator &lhs)
Mesh::Iterator operator++ (Mesh::Iterator &lhs, int)
Mesh::Iterator operator-- (Mesh::Iterator &lhs, int)
Mesh::Iterator operator- (const Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
Mesh::Iterator operator+ (const Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
Mesh::Iterator & operator-= (Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
Mesh::Iterator & operator+= (Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
Mesh::Iterator operator- (const Mesh::Iterator &lhs, const int &rhs)
Mesh::Iterator operator+ (const Mesh::Iterator &lhs, const int &rhs)
Mesh::Iterator & operator-= (Mesh::Iterator &lhs, const int &rhs)
Mesh::Iterator & operator+= (Mesh::Iterator &lhs, const int &rhs)
bool operator== (const Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
bool operator!= (const Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
bool operator>= (const Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
bool operator<= (const Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
bool operator< (const Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
bool operator> (const Mesh::Iterator &lhs, const Mesh::Iterator &rhs)
template std::istream & operator>> (std::istream &in, MMatrix< double > &mat)
template std::istream & operator>> (std::istream &in, MMatrix< m_complex > &mat)
MMatrix< double > & operator*= (MMatrix< double > &m1, MMatrix< double > m2)
MMatrix< m_complex > & operator*= (MMatrix< m_complex > &m1, MMatrix< m_complex > m2)
template<class Tmplt>
std::ostream & operator<< (std::ostream &out, MMatrix< Tmplt > mat)
template std::ostream & operator<< (std::ostream &out, MMatrix< double > mat)
template std::ostream & operator<< (std::ostream &out, MMatrix< m_complex > mat)
template<class Tmplt>
std::istream & operator>> (std::istream &in, MMatrix< Tmplt > &mat)
MMatrix< double > re (MMatrix< m_complex > mc)
MMatrix< double > im (MMatrix< m_complex > mc)
MMatrix< m_complex > complex (MMatrix< double > real)
MMatrix< m_complex > complex (MMatrix< double > real, MMatrix< double > imaginary)
MMatrix< m_complex > & operator*= (MMatrix< m_complex > &m, m_complex c)
MMatrix< double > & operator*= (MMatrix< double > &m, double d)
MVector< m_complex > operator* (MMatrix< m_complex > m, MVector< m_complex > v)
MVector< double > operator* (MMatrix< double > m, MVector< double > v)
MMatrix< m_complex > & operator+= (MMatrix< m_complex > &m1, const MMatrix< m_complex > &m2)
MMatrix< double > & operator+= (MMatrix< double > &m1, const MMatrix< double > &m2)
template<class Tmplt>
MMatrix< Tmplt > & operator-= (MMatrix< double > &m1, MMatrix< double > m2)
template<class Tmplt>
MMatrix< Tmplt > operator* (MMatrix< Tmplt >, MMatrix< Tmplt >)
template<class Tmplt>
MMatrix< Tmplt > operator* (MMatrix< Tmplt >, MVector< Tmplt >)
template<class Tmplt>
MMatrix< Tmplt > operator* (MMatrix< Tmplt >, Tmplt)
template<class Tmplt>
MMatrix< Tmplt > operator/ (MMatrix< Tmplt >, Tmplt)
template<class Tmplt>
MMatrix< Tmplt > operator+ (MMatrix< Tmplt >, MMatrix< Tmplt >)
template<class Tmplt>
MMatrix< Tmplt > operator- (MMatrix< Tmplt >, MMatrix< Tmplt >)
template<class Tmplt>
MMatrix< Tmplt > operator- (MMatrix< Tmplt >)
template<class Tmplt>
bool operator== (const MMatrix< Tmplt > &c1, const MMatrix< Tmplt > &c2)
template<class Tmplt>
bool operator!= (const MMatrix< Tmplt > &c1, const MMatrix< Tmplt > &c2)
template<class Tmplt>
MMatrix< Tmplt > inline & operator/= (MMatrix< Tmplt > &m, Tmplt t)
template<class Tmplt>
MMatrix< Tmplt > inline & operator-= (MMatrix< Tmplt > &m1, MMatrix< Tmplt > m2)
std::ostream & operator<< (std::ostream &out, m_complex c)
std::istream & operator>> (std::istream &in, m_complex &c)
template std::ostream & operator<< (std::ostream &out, MVector< double > v)
template std::ostream & operator<< (std::ostream &out, MVector< m_complex > v)
template std::istream & operator>> (std::istream &out, MVector< double > &v)
template std::istream & operator>> (std::istream &out, MVector< m_complex > &v)
template<class Tmplt>
bool operator== (const MVector< Tmplt > &c1, const MVector< Tmplt > &c2)
template bool operator== (const MVector< double > &c1, const MVector< double > &c2)
template bool operator== (const MVector< m_complex > &c1, const MVector< m_complex > &c2)
template<class Tmplt>
std::ostream & operator<< (std::ostream &out, MVector< Tmplt > v)
template<class Tmplt>
std::istream & operator>> (std::istream &in, MVector< Tmplt > &v)
MVector< m_complex > complex (MVector< double > real)
MVector< m_complex > complex (MVector< double > real, MVector< double > im)
MVector< double > re (MVector< m_complex > c)
MVector< double > im (MVector< m_complex > c)
m_complex m_complex_build (double r, double i)
m_complex m_complex_build (double r)
m_complex operator* (m_complex c, double d)
m_complex operator* (double d, m_complex c)
m_complex operator* (m_complex c1, m_complex c2)
m_complex operator/ (m_complex c, double d)
m_complex operator/ (m_complex c1, m_complex c2)
m_complex operator/ (double d, m_complex c)
m_complex operator+ (m_complex c, double d)
m_complex operator+ (double d, m_complex c)
m_complex operator+ (m_complex c1, m_complex c2)
m_complex operator- (m_complex c)
m_complex operator- (m_complex c, double d)
m_complex operator- (double d, m_complex c)
m_complex operator- (m_complex c1, m_complex c2)
m_complex & operator*= (m_complex &c, double d)
m_complex & operator*= (m_complex &c1, m_complex c2)
m_complex & operator/= (m_complex &c, double d)
m_complex & operator/= (m_complex &c1, m_complex c2)
m_complex & operator+= (m_complex &c, double d)
m_complex & operator+= (m_complex &c1, m_complex c2)
m_complex & operator-= (m_complex &c, double d)
m_complex & operator-= (m_complex &c1, m_complex c2)
bool operator== (m_complex c1, m_complex c2)
bool operator!= (m_complex c1, m_complex c2)
double & re (m_complex &c)
double & im (m_complex &c)
const double & re (const m_complex &c)
const double & im (const m_complex &c)
m_complex conj (const m_complex &c)
template<class Tmplt>
bool operator!= (const MVector< Tmplt > &v1, const MVector< Tmplt > &v2)
MVector< m_complex > & operator*= (MVector< m_complex > &v, m_complex c)
MVector< double > & operator*= (MVector< double > &v, double d)
template<class Tmplt>
MVector< Tmplt > operator* (MVector< Tmplt > v, Tmplt t)
template<class Tmplt>
MVector< Tmplt > operator* (Tmplt t, MVector< Tmplt > v)
template<class Tmplt>
MVector< Tmplt > & operator/= (MVector< Tmplt > &v, Tmplt t)
template<class Tmplt>
MVector< Tmplt > operator/ (MVector< Tmplt > v, Tmplt t)
template<class Tmplt>
MVector< Tmplt > operator/ (Tmplt t, MVector< Tmplt > v)
MVector< m_complex > & operator+= (MVector< m_complex > &v1, MVector< m_complex > v2)
MVector< double > & operator+= (MVector< double > &v1, MVector< double > v2)
template<class Tmplt>
MVector< Tmplt > operator+ (MVector< Tmplt > v1, MVector< Tmplt > v2)
template<class Tmplt>
MVector< Tmplt > & operator-= (MVector< Tmplt > &v1, MVector< Tmplt > v2)
template<class Tmplt>
MVector< Tmplt > operator- (MVector< Tmplt > v1, MVector< Tmplt > v2)
template<class Tmplt>
MVector< Tmplt > operator- (const MVector< Tmplt > &v)
template<class Tmplt>
MVector< Tmplt > inline & operator/= (MVector< Tmplt > &v, Tmplt d)
template<class Tmplt>
MVector< Tmplt > inline & operator-= (MVector< Tmplt > &v1, MVector< Tmplt > v2)
std::ostream & operator<< (std::ostream &out, const PolynomialCoefficient &coeff)
std::ostream & operator<< (std::ostream &out, const SquarePolynomialVector &spv)
Typedef Documentation
Coeff
typedef PolynomialCoefficient interpolation::Coeff
Definition at line 47 of file PPSolveFactory.cpp.
m_complex
typedef gsl_complex interpolation::m_complex
Wrapper for GSL vector and gsl_complex
MVector class handles maths operators and a few other operators
Use template to define two types: (i) MVector<double> is a vector of doubles (ii) MVector<m_complex> is a vector of m_complex
Maths operators and a few others are defined, but maths operators don't allow operations between types - i.e. you can't multiply a complex matrix by a double matrix. Instead use interface methods like real() and complex() to convert between types first
Definition at line 58 of file MVector.h.
Function Documentation
complex() [1/4]
MMatrix< m_complex > interpolation::complex (MMatrix< double > real)
Definition at line 399 of file MMatrix.cpp.
References m_complex_build(), interpolation::MMatrix< Tmplt >::num_col(), and interpolation::MMatrix< Tmplt >::num_row().
complex() [2/4]
MMatrix< m_complex > interpolation::complex (MMatrix< double > real, MMatrix< double > imaginary)
Definition at line 407 of file MMatrix.cpp.
References m_complex_build(), interpolation::MMatrix< Tmplt >::num_col(), and interpolation::MMatrix< Tmplt >::num_row().
complex() [3/4]
MVector< m_complex > interpolation::complex (MVector< double > real)
Definition at line 202 of file MVector.cpp.
References m_complex_build(), and interpolation::MVector< Tmplt >::num_row().
complex() [4/4]
MVector< m_complex > interpolation::complex (MVector< double > real, MVector< double > im)
Definition at line 209 of file MVector.cpp.
References im(), m_complex_build(), and interpolation::MVector< Tmplt >::num_row().
conj()
m_complex interpolation::conj (const m_complex & c) inline
Definition at line 142 of file MVector.h.
References im(), m_complex_build(), and re().
im() [1/4]
const double & interpolation::im (const m_complex & c) inline
Definition at line 139 of file MVector.h.
im() [2/4]
double & interpolation::im (m_complex & c) inline
Definition at line 137 of file MVector.h.
im() [3/4]
MMatrix< double > interpolation::im (MMatrix< m_complex > mc)
Definition at line 391 of file MMatrix.cpp.
References im(), interpolation::MMatrix< Tmplt >::num_col(), and interpolation::MMatrix< Tmplt >::num_row().
Referenced by complex(), conj(), im(), im(), operator<<(), and operator>>().
im() [4/4]
MVector< double > interpolation::im (MVector< m_complex > c)
Definition at line 223 of file MVector.cpp.
References im().
m_complex_build() [1/2]
m_complex interpolation::m_complex_build (double r) inline
Definition at line 64 of file MVector.h.
m_complex_build() [2/2]
m_complex interpolation::m_complex_build (double r, double i) inline
Definition at line 60 of file MVector.h.
Referenced by complex(), complex(), complex(), complex(), conj(), interpolation::MMatrix< Tmplt >::eigenvalues(), interpolation::MMatrix< Tmplt >::operator*, interpolation::MMatrix< Tmplt >::operator*=, and operator/().
operator!=() [1/4]
bool interpolation::operator!= (const Mesh::Iterator & lhs, const Mesh::Iterator & rhs) inline
Return true if lhs does not index the same position as rhs
operator!=() [2/4]
template<class Tmplt> bool interpolation::operator!= (const MMatrix< Tmplt > & c1, const MMatrix< Tmplt > & c2) inline
Definition at line 386 of file MMatrix.h.
operator!=() [3/4]
template<class Tmplt> bool interpolation::operator!= (const MVector< Tmplt > & v1, const MVector< Tmplt > & v2) inline
Definition at line 331 of file MVector.h.
operator!=() [4/4]
bool interpolation::operator!= (m_complex c1, m_complex c2) inline
Definition at line 133 of file MVector.h.
operator*() [1/10]
m_complex interpolation::operator* (double d, m_complex c) inline
Definition at line 70 of file MVector.h.
References gsl_complex_mul_real().
operator*() [2/10]
m_complex interpolation::operator* (m_complex c, double d) inline
Definition at line 69 of file MVector.h.
References gsl_complex_mul_real().
operator*() [3/10]
m_complex interpolation::operator* (m_complex c1, m_complex c2) inline
Definition at line 71 of file MVector.h.
References gsl_complex_mul().
operator*() [4/10]
MVector< double > interpolation::operator* (MMatrix< double > m, MVector< double > v) inline
Definition at line 293 of file MMatrix.h.
operator*() [5/10]
MVector< m_complex > interpolation::operator* (MMatrix< m_complex > m, MVector< m_complex > v) inline
Definition at line 284 of file MMatrix.h.
operator*() [6/10]
template<class Tmplt> MMatrix< Tmplt > interpolation::operator* (MMatrix< Tmplt > m1, MMatrix< Tmplt > m2) inline
Definition at line 320 of file MMatrix.h.
operator*() [7/10]
template<class Tmplt> MMatrix< Tmplt > interpolation::operator* (MMatrix< Tmplt > m, MVector< Tmplt > v) inline
Definition at line 325 of file MMatrix.h.
operator*() [8/10]
template<class Tmplt> MMatrix< Tmplt > interpolation::operator* (MMatrix< Tmplt > m, Tmplt t) inline
Definition at line 330 of file MMatrix.h.
operator*() [9/10]
template<class Tmplt> MVector< Tmplt > interpolation::operator* (MVector< Tmplt > v, Tmplt t) inline
Definition at line 284 of file MVector.h.
operator*() [10/10]
template<class Tmplt> MVector< Tmplt > interpolation::operator* (Tmplt t, MVector< Tmplt > v) inline
Definition at line 288 of file MVector.h.
operator*=() [1/8]
m_complex & interpolation::operator*= (m_complex & c, double d) inline
Definition at line 94 of file MVector.h.
References gsl_complex_mul_real().
operator*=() [2/8]
m_complex & interpolation::operator*= (m_complex & c1, m_complex c2) inline
Definition at line 98 of file MVector.h.
References gsl_complex_mul().
operator*=() [3/8]
MMatrix< double > inline & interpolation::operator*= (MMatrix< double > & m, double d)
Definition at line 279 of file MMatrix.h.
operator*=() [4/8]
MMatrix< double > & interpolation::operator*= (MMatrix< double > & m1, MMatrix< double > m2)
Definition at line 337 of file MMatrix.cpp.
operator*=() [5/8]
MMatrix< m_complex > inline & interpolation::operator*= (MMatrix< m_complex > & m, m_complex c)
Definition at line 274 of file MMatrix.h.
operator*=() [6/8]
MMatrix< m_complex > & interpolation::operator*= (MMatrix< m_complex > & m1, MMatrix< m_complex > m2)
Definition at line 346 of file MMatrix.cpp.
operator*=() [7/8]
MVector< double > inline & interpolation::operator*= (MVector< double > & v, double d)
Definition at line 278 of file MVector.h.
operator*=() [8/8]
MVector< m_complex > inline & interpolation::operator*= (MVector< m_complex > & v, m_complex c)
Definition at line 274 of file MVector.h.
operator+() [1/7]
Mesh::Iterator interpolation::operator+ (const Mesh::Iterator & lhs, const int & rhs) inline
Addition operator - adds rhs to lhs and returns copy of lhs
operator+() [2/7]
Mesh::Iterator interpolation::operator+ (const Mesh::Iterator & lhs, const Mesh::Iterator & rhs) inline
Addition operator - adds offset of rhs of rhs relative to Begin() to lhs
operator+() [3/7]
m_complex interpolation::operator+ (double d, m_complex c) inline
Definition at line 81 of file MVector.h.
References gsl_complex_add_real().
operator+() [4/7]
m_complex interpolation::operator+ (m_complex c, double d) inline
Definition at line 80 of file MVector.h.
References gsl_complex_add_real().
operator+() [5/7]
m_complex interpolation::operator+ (m_complex c1, m_complex c2) inline
Definition at line 82 of file MVector.h.
References gsl_complex_add().
operator+() [6/7]
template<class Tmplt> MMatrix< Tmplt > interpolation::operator+ (MMatrix< Tmplt > m1, MMatrix< Tmplt > m2) inline
Definition at line 344 of file MMatrix.h.
operator+() [7/7]
template<class Tmplt> MVector< Tmplt > interpolation::operator+ (MVector< Tmplt > v1, MVector< Tmplt > v2) inline
Definition at line 310 of file MVector.h.
operator++() [1/2]
Mesh::Iterator & interpolation::operator++ (Mesh::Iterator & lhs) inline
Prefix increment operator ++it
operator++() [2/2]
Mesh::Iterator interpolation::operator++ (Mesh::Iterator & lhs, int) inline
Postfix increment operator it++ advances iterator by one
operator+=() [1/8]
m_complex & interpolation::operator+= (m_complex & c, double d) inline
Definition at line 112 of file MVector.h.
References gsl_complex_add_real().
operator+=() [2/8]
m_complex & interpolation::operator+= (m_complex & c1, m_complex c2) inline
Definition at line 116 of file MVector.h.
References gsl_complex_add().
operator+=() [3/8]
Mesh::Iterator & interpolation::operator+= (Mesh::Iterator & lhs, const int & rhs) inline
Addition operator - subtracts rhs from lhs and returns lhs
operator+=() [4/8]
Mesh::Iterator & interpolation::operator+= (Mesh::Iterator & lhs, const Mesh::Iterator & rhs) inline
Addition operator - adds offset of rhs of rhs relative to Begin() to lhs and returns lhs
operator+=() [5/8]
MMatrix< double > inline & interpolation::operator+= (MMatrix< double > & m1, const MMatrix< double > & m2)
Definition at line 306 of file MMatrix.h.
operator+=() [6/8]
MMatrix< m_complex > inline & interpolation::operator+= (MMatrix< m_complex > & m1, const MMatrix< m_complex > & m2)
Definition at line 301 of file MMatrix.h.
operator+=() [7/8]
MVector< double > inline & interpolation::operator+= (MVector< double > & v1, MVector< double > v2)
Definition at line 305 of file MVector.h.
operator+=() [8/8]
MVector< m_complex > inline & interpolation::operator+= (MVector< m_complex > & v1, MVector< m_complex > v2)
Definition at line 301 of file MVector.h.
operator-() [1/10]
Mesh::Iterator interpolation::operator- (const Mesh::Iterator & lhs, const int & rhs) inline
Subtraction operator - subtracts from lhs and returns copy of lhs
operator-() [2/10]
Mesh::Iterator interpolation::operator- (const Mesh::Iterator & lhs, const Mesh::Iterator & rhs) inline
Subtraction operator - subtracts offset of rhs relative to Begin() from lhs
operator-() [3/10]
template<class Tmplt> MVector< Tmplt > interpolation::operator- (const MVector< Tmplt > & v) inline
Definition at line 315 of file MVector.h.
References interpolation::MVector< Tmplt >::num_row().
operator-() [4/10]
m_complex interpolation::operator- (double d, m_complex c) inline
Definition at line 90 of file MVector.h.
References gsl_complex_sub_real().
operator-() [5/10]
m_complex interpolation::operator- (m_complex c) inline
Definition at line 84 of file MVector.h.
operator-() [6/10]
m_complex interpolation::operator- (m_complex c, double d) inline
Definition at line 89 of file MVector.h.
References gsl_complex_sub_real().
operator-() [7/10]
m_complex interpolation::operator- (m_complex c1, m_complex c2) inline
Definition at line 91 of file MVector.h.
References gsl_complex_sub().
operator-() [8/10]
template<class Tmplt> MMatrix< Tmplt > interpolation::operator- (MMatrix< Tmplt > m1) inline
Definition at line 312 of file MMatrix.h.
References interpolation::MMatrix< Tmplt >::num_col(), and interpolation::MMatrix< Tmplt >::num_row().
operator-() [9/10]
template<class Tmplt> MMatrix< Tmplt > interpolation::operator- (MMatrix< Tmplt > m1, MMatrix< Tmplt > m2) inline
Definition at line 354 of file MMatrix.h.
operator-() [10/10]
template<class Tmplt> MVector< Tmplt > interpolation::operator- (MVector< Tmplt > v1, MVector< Tmplt > v2) inline
Definition at line 326 of file MVector.h.
operator--() [1/2]
Mesh::Iterator & interpolation::operator-- (Mesh::Iterator & lhs) inline
Prefix decrement operator –it retreats iterator by one
operator--() [2/2]
Mesh::Iterator interpolation::operator-- (Mesh::Iterator & lhs, int) inline
Postfix decrement operator it– retreats iterator by one
operator-=() [1/8]
m_complex & interpolation::operator-= (m_complex & c, double d) inline
Definition at line 121 of file MVector.h.
References gsl_complex_sub_real().
operator-=() [2/8]
m_complex & interpolation::operator-= (m_complex & c1, m_complex c2) inline
Definition at line 125 of file MVector.h.
References gsl_complex_sub().
operator-=() [3/8]
Mesh::Iterator & interpolation::operator-= (Mesh::Iterator & lhs, const int & rhs) inline
Subtraction operator - subtracts rhs from lhs and returns lhs
operator-=() [4/8]
Mesh::Iterator & interpolation::operator-= (Mesh::Iterator & lhs, const Mesh::Iterator & rhs) inline
Subtraction operator - subtracts offset of rhs relative to Begin() from lhs and returns lhs
operator-=() [5/8]
template<class Tmplt> MMatrix< Tmplt > & interpolation::operator-= (MMatrix< double > & m1, MMatrix< double > m2)
operator-=() [6/8]
template<class Tmplt> MMatrix< Tmplt > inline & interpolation::operator-= (MMatrix< Tmplt > & m1, MMatrix< Tmplt > m2)
Definition at line 350 of file MMatrix.h.
operator-=() [7/8]
template<class Tmplt> MVector< Tmplt > & interpolation::operator-= (MVector< Tmplt > & v1, MVector< Tmplt > v2)
Definition at line 322 of file MVector.h.
operator-=() [8/8]
template<class Tmplt> MVector< Tmplt > inline & interpolation::operator-= (MVector< Tmplt > & v1, MVector< Tmplt > v2)
Definition at line 322 of file MVector.h.
operator/() [1/6]
m_complex interpolation::operator/ (double d, m_complex c) inline
Definition at line 75 of file MVector.h.
References gsl_complex_div(), and m_complex_build().
operator/() [2/6]
m_complex interpolation::operator/ (m_complex c, double d) inline
Definition at line 73 of file MVector.h.
References gsl_complex_div_real().
operator/() [3/6]
m_complex interpolation::operator/ (m_complex c1, m_complex c2) inline
Definition at line 74 of file MVector.h.
References gsl_complex_div().
operator/() [4/6]
template<class Tmplt> MMatrix< Tmplt > interpolation::operator/ (MMatrix< Tmplt > m, Tmplt t) inline
Definition at line 339 of file MMatrix.h.
operator/() [5/6]
template<class Tmplt> MVector< Tmplt > interpolation::operator/ (MVector< Tmplt > v, Tmplt t) inline
Definition at line 297 of file MVector.h.
operator/() [6/6]
template<class Tmplt> MVector< Tmplt > interpolation::operator/ (Tmplt t, MVector< Tmplt > v)
operator/=() [1/5]
m_complex & interpolation::operator/= (m_complex & c, double d) inline
Definition at line 103 of file MVector.h.
References gsl_complex_div_real().
operator/=() [2/5]
m_complex & interpolation::operator/= (m_complex & c1, m_complex c2) inline
Definition at line 107 of file MVector.h.
References gsl_complex_div().
operator/=() [3/5]
template<class Tmplt> MMatrix< Tmplt > inline & interpolation::operator/= (MMatrix< Tmplt > & m, Tmplt t)
Definition at line 335 of file MMatrix.h.
operator/=() [4/5]
template<class Tmplt> MVector< Tmplt > inline & interpolation::operator/= (MVector< Tmplt > & v, Tmplt d)
Definition at line 293 of file MVector.h.
operator/=() [5/5]
template<class Tmplt> MVector< Tmplt > & interpolation::operator/= (MVector< Tmplt > & v, Tmplt t)
Definition at line 293 of file MVector.h.
operator<()
bool interpolation::operator< (const Mesh::Iterator & lhs, const Mesh::Iterator & rhs) inline
Return true if lhs indexes a position less than rhs i.e. successive operation of decrement operator would eventually reach lhs
operator<<() [1/10]
std::ostream & interpolation::operator<< (std::ostream & out, const Mesh::Iterator & it)
Output iterator to a std ostream object
Definition at line 33 of file Mesh.cpp.
References interpolation::Mesh::Iterator::getPosition(), interpolation::Mesh::Iterator::getState(), and interpolation::Mesh::Iterator::toInteger().
operator<<() [2/10]
std::ostream & interpolation::operator<< (std::ostream & out, const PolynomialCoefficient & coeff)
Definition at line 3 of file PolynomialCoefficient.cpp.
References interpolation::PolynomialCoefficient::Coefficient(), interpolation::PolynomialCoefficient::InVariables(), and interpolation::PolynomialCoefficient::OutVariable().
operator<<() [3/10]
std::ostream & interpolation::operator<< (std::ostream & out, const SquarePolynomialVector & spv)
Write out the PolynomialVector (effectively just polyCoeffs).
Definition at line 208 of file SquarePolynomialVector.cpp.
operator<<() [4/10]
std::ostream & interpolation::operator<< (std::ostream & out, m_complex c)
Definition at line 34 of file MVector.cpp.
References im(), and re().
operator<<() [5/10]
template std::ostream & interpolation::operator<< (std::ostream & out, MMatrix< double > mat)
operator<<() [6/10]
template std::ostream & interpolation::operator<< (std::ostream & out, MMatrix< m_complex > mat)
operator<<() [7/10]
template<class Tmplt> std::ostream & interpolation::operator<< (std::ostream & out, MMatrix< Tmplt > mat)
Definition at line 357 of file MMatrix.cpp.
References interpolation::MMatrix< Tmplt >::num_col(), and interpolation::MMatrix< Tmplt >::num_row().
operator<<() [8/10]
template std::ostream & interpolation::operator<< (std::ostream & out, MVector< double > v)
operator<<() [9/10]
template std::ostream & interpolation::operator<< (std::ostream & out, MVector< m_complex > v)
operator<<() [10/10]
template<class Tmplt> std::ostream & interpolation::operator<< (std::ostream & out, MVector< Tmplt > v)
Definition at line 177 of file MVector.cpp.
References interpolation::MVector< Tmplt >::num_row().
operator<=()
bool interpolation::operator<= (const Mesh::Iterator & lhs, const Mesh::Iterator & rhs) inline
Return true if lhs indexes a position less than or equal to rhs i.e. successive operation of decrement operator would eventually reach lhs
operator==() [1/6]
bool interpolation::operator== (const Mesh::Iterator & lhs, const Mesh::Iterator & rhs) inline
Return true if lhs indexes the same position as rhs
operator==() [2/6]
template<class Tmplt> bool interpolation::operator== (const MMatrix< Tmplt > & c1, const MMatrix< Tmplt > & c2)
Definition at line 377 of file MMatrix.h.
References interpolation::MMatrix< Tmplt >::num_col(), and interpolation::MMatrix< Tmplt >::num_row().
operator==() [3/6]
template bool interpolation::operator== (const MVector< double > & c1, const MVector< double > & c2)
operator==() [4/6]
template bool interpolation::operator== (const MVector< m_complex > & c1, const MVector< m_complex > & c2)
operator==() [5/6]
template<class Tmplt> bool interpolation::operator== (const MVector< Tmplt > & c1, const MVector< Tmplt > & c2)
Definition at line 140 of file MVector.cpp.
References interpolation::MVector< Tmplt >::num_row().
operator==() [6/6]
bool interpolation::operator== (m_complex c1, m_complex c2) inline
Definition at line 130 of file MVector.h.
References gsl_complex::dat.
operator>()
bool interpolation::operator> (const Mesh::Iterator & lhs, const Mesh::Iterator & rhs) inline
Return true if lhs indexes a position greater than rhs i.e. successive operation of increment operator would eventually reach lhs
operator>=()
bool interpolation::operator>= (const Mesh::Iterator & lhs, const Mesh::Iterator & rhs) inline
Return true if lhs indexes a position greater than or equal to rhs i.e. successive operation of increment operator would eventually reach lhs
operator>>() [1/7]
std::istream & interpolation::operator>> (std::istream & in, m_complex & c)
Definition at line 39 of file MVector.cpp.
References im(), and re().
operator>>() [2/7]
template std::istream & interpolation::operator>> (std::istream & in, MMatrix< double > & mat)
operator>>() [3/7]
template std::istream & interpolation::operator>> (std::istream & in, MMatrix< m_complex > & mat)
operator>>() [4/7]
template<class Tmplt> std::istream & interpolation::operator>> (std::istream & in, MMatrix< Tmplt > & mat)
Definition at line 371 of file MMatrix.cpp.
References nr.
operator>>() [5/7]
template<class Tmplt> std::istream & interpolation::operator>> (std::istream & in, MVector< Tmplt > & v)
Definition at line 185 of file MVector.cpp.
References interpolation::MVector< Tmplt >::num_row().
operator>>() [6/7]
template std::istream & interpolation::operator>> (std::istream & out, MVector< double > & v)
operator>>() [7/7]
template std::istream & interpolation::operator>> (std::istream & out, MVector< m_complex > & v)
re() [1/4]
const double & interpolation::re (const m_complex & c) inline
Definition at line 138 of file MVector.h.
re() [2/4]
double & interpolation::re (m_complex & c) inline
Definition at line 136 of file MVector.h.
re() [3/4]
MMatrix< double > interpolation::re (MMatrix< m_complex > mc)
Definition at line 383 of file MMatrix.cpp.
References interpolation::MMatrix< Tmplt >::num_col(), interpolation::MMatrix< Tmplt >::num_row(), and re().
Referenced by conj(), operator<<(), operator>>(), re(), and re().
re() [4/4]
MVector< double > interpolation::re (MVector< m_complex > c)
Definition at line 216 of file MVector.cpp.
References re().