OPALX (Object Oriented Parallel Accelerator Library for Exascal): QuasiRandom.h File Reference
QuasiRandom.h File Reference
#include <cmath>
#include <string>
#include <vector>
Classes
class gsl_qrng
Functions
gsl_qrng * gsl_qrng_alloc (const char *, unsigned int dimension)
void gsl_qrng_get (const gsl_qrng *q, double *x)
void gsl_qrng_free (gsl_qrng *q)
Function Documentation
gsl_qrng_alloc()
gsl_qrng * gsl_qrng_alloc (const char * , unsigned int dimension) inline
Definition at line 78 of file QuasiRandom.h.
References gsl_qrng::init().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
gsl_qrng_free()
void gsl_qrng_free (gsl_qrng * q) inline
Definition at line 86 of file QuasiRandom.h.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
gsl_qrng_get()
void gsl_qrng_get (const gsl_qrng * q, double * x) inline
Definition at line 84 of file QuasiRandom.h.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().