OPALX (Object Oriented Parallel Accelerator Library for Exascal): Random.h File Reference
Random.h File Reference
#include <cstddef>
#include <memory>
#include <random>
Classes
class gsl_rng
struct gsl_rng_type
Macros
#define gsl_rng_default (get_gsl_rng_default())
Functions
void gsl_rng_env_setup ()
gsl_rng * gsl_rng_alloc (const gsl_rng_type *)
void gsl_rng_free (gsl_rng *rng)
double gsl_rng_uniform (gsl_rng *rng)
double gsl_ran_gaussian (gsl_rng *rng, double sigma)
const gsl_rng_type * get_gsl_rng_default ()
Variables
const gsl_rng_type * gsl_rng_default
Class Documentation
gsl_rng_type
struct gsl_rng_type
Definition at line 48 of file Random.h.
Class Members
const char * name
Macro Definition Documentation
gsl_rng_default
#define gsl_rng_default (get_gsl_rng_default())
Definition at line 73 of file Random.h.
Referenced by BoundaryGeometry::BoundaryGeometry(), BoundaryGeometry::BoundaryGeometry(), RandomTest::SetUp(), LaserProfile::setupRNG(), TEST_F(), and TEST_F().
Function Documentation
get_gsl_rng_default()
const gsl_rng_type * get_gsl_rng_default () inline
Definition at line 69 of file Random.h.
gsl_ran_gaussian()
double gsl_ran_gaussian (gsl_rng * rng, double sigma) inline
Definition at line 66 of file Random.h.
References gsl_rng::gaussian().
Referenced by TEST_F(), and TEST_F().
gsl_rng_alloc()
gsl_rng * gsl_rng_alloc (const gsl_rng_type *) inline
Definition at line 60 of file Random.h.
Referenced by BoundaryGeometry::BoundaryGeometry(), BoundaryGeometry::BoundaryGeometry(), RandomTest::SetUp(), LaserProfile::setupRNG(), TEST_F(), and TEST_F().
gsl_rng_env_setup()
void gsl_rng_env_setup () inline
Definition at line 56 of file Random.h.
Referenced by BoundaryGeometry::BoundaryGeometry(), BoundaryGeometry::BoundaryGeometry(), and LaserProfile::setupRNG().
gsl_rng_free()
void gsl_rng_free (gsl_rng * rng) inline
Definition at line 62 of file Random.h.
Referenced by RandomTest::TearDown(), TEST_F(), TEST_F(), BoundaryGeometry::~BoundaryGeometry(), and LaserProfile::~LaserProfile().
gsl_rng_uniform()
double gsl_rng_uniform (gsl_rng * rng) inline
Definition at line 64 of file Random.h.
References gsl_rng::uniform().
Referenced by LaserProfile::getXY(), BoundaryGeometry::initialize(), TEST_F(), TEST_F(), and TEST_F().
Variable Documentation
gsl_rng_default
const gsl_rng_type* gsl_rng_default extern