OPALX (Object Oriented Parallel Accelerator Library for Exascal): SavitzkyGolay.cpp File Reference
SavitzkyGolay.cpp File Reference
#include "Filters/SavitzkyGolay.h"
#include <iostream>
#include "Utilities/GSLFFT.h"
#include <cmath>
Functions
void savgol (std::vector< double > &c, const int &np, const int &nl, const int &nr, const int &ld, const int &m)
void convlv (const std::vector< double > &data, const std::vector< double > &respns, const int &isign, std::vector< double > &ans)
void ludcmp (std::vector< double > &a, std::vector< int > &indx, double &d)
void lubksb (std::vector< double > &a, std::vector< int > &indx, std::vector< double > &b)
Function Documentation
convlv()
void convlv (const std::vector< double > & data, const std::vector< double > & respns, const int & isign, std::vector< double > & ans)
Definition at line 74 of file SavitzkyGolay.cpp.
References gsl_fft_halfcomplex_inverse(), gsl_fft_halfcomplex_wavetable_alloc(), gsl_fft_halfcomplex_wavetable_free(), gsl_fft_real_transform(), gsl_fft_real_wavetable_alloc(), gsl_fft_real_wavetable_free(), gsl_fft_real_workspace_alloc(), and gsl_fft_real_workspace_free().
Referenced by SavitzkyGolayFilter::apply(), and SavitzkyGolayFilter::calc_derivative().
lubksb()
void lubksb (std::vector< double > & a, std::vector< int > & indx, std::vector< double > & b)
Definition at line 186 of file SavitzkyGolay.cpp.
Referenced by savgol().
ludcmp()
void ludcmp (std::vector< double > & a, std::vector< int > & indx, double & d)
Definition at line 127 of file SavitzkyGolay.cpp.
Referenced by savgol().
savgol()
void savgol (std::vector< double > & c, const int & np, const int & nl, const int & nr, const int & ld, const int & m)
Definition at line 31 of file SavitzkyGolay.cpp.
References lubksb(), ludcmp(), and nr.
Referenced by SavitzkyGolayFilter::SavitzkyGolayFilter().