OPALX (Object Oriented Parallel Accelerator Library for Exascal): mslang::Difference Struct Reference
mslang::Difference Struct Reference
#include <Difference.h>
Public Member Functions
Difference ()
Difference (const Difference &right)
virtual ~Difference ()
virtual void print (int indentwidth)
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *&fun)
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
Function * dividend_m
Function * divisor_m
Static Public Attributes
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\‍((.*)"
Detailed Description
Definition at line 7 of file Difference.h.
Constructor & Destructor Documentation
Difference() [1/2]
mslang::Difference::Difference () inline
Definition at line 11 of file Difference.h.
Difference() [2/2]
mslang::Difference::Difference (const Difference & right) inline
Definition at line 13 of file Difference.h.
~Difference()
virtual mslang::Difference::~Difference () inline virtual
Definition at line 16 of file Difference.h.
References dividend_m, and divisor_m.
Member Function Documentation
apply()
void mslang::Difference::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Implements mslang::Function.
Definition at line 15 of file Difference.cpp.
References mslang::Function::apply(), dividend_m, and divisor_m.
parse()
bool mslang::Function::parse (iterator & it, const iterator & end, Function *& fun) static inherited
Definition at line 47 of file MSLang.cpp.
References mslang::Function::FCall, parse_detail(), mslang::Intersection::parse_detail(), mslang::Mask::parse_detail(), mslang::Polygon::parse_detail(), mslang::Repeat::parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), mslang::Union::parse_detail(), mslang::Ellipse::parse_detail(), and mslang::Rectangle::parse_detail().
Referenced by mslang::parse(), parse_detail(), mslang::Intersection::parse_detail(), mslang::Repeat::parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), and mslang::Union::parse_detail().
parse_detail()
bool mslang::Difference::parse_detail (iterator & it, const iterator & end, Function *& fun) static
Definition at line 31 of file Difference.cpp.
References dividend_m, divisor_m, and mslang::Function::parse().
Referenced by mslang::Function::parse().
print()
void mslang::Difference::print (int indentwidth) virtual
Implements mslang::Function.
Definition at line 6 of file Difference.cpp.
References dividend_m, divisor_m, and mslang::Function::print().
Member Data Documentation
dividend_m
Function* mslang::Difference::dividend_m
Definition at line 8 of file Difference.h.
Referenced by apply(), parse_detail(), print(), and ~Difference().
divisor_m
Function* mslang::Difference::divisor_m
Definition at line 9 of file Difference.h.
Referenced by apply(), parse_detail(), print(), and ~Difference().
Double
const std::string mslang::Function::Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 32 of file MSLang.h.
FCall
const std::string mslang::Function::FCall = "([a-z_]*)\\‍((.*)" static inherited
Definition at line 34 of file MSLang.h.
Referenced by mslang::Function::parse().
UDouble
const std::string mslang::Function::UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 31 of file MSLang.h.
Referenced by mslang::Rectangle::parse_detail().
UInt
const std::string mslang::Function::UInt = "([0-9]+)" static inherited
Definition at line 33 of file MSLang.h.
The documentation for this struct was generated from the following files:
Difference.h
Difference.cpp