OPALX (Object Oriented Parallel Accelerator Library for Exascal): mslang::Shear Struct Reference
mslang::Shear Struct Reference
#include <Shear.h>
Public Member Functions
virtual ~Shear ()
virtual void print (int indentwidth)
void applyShear (std::vector< std::shared_ptr< Base > > &bfuncs)
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *&fun)
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
Function * func_m
double angleX_m
double angleY_m
Static Public Attributes
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\‍((.*)"
Detailed Description
Definition at line 7 of file Shear.h.
Constructor & Destructor Documentation
~Shear()
virtual mslang::Shear::~Shear () inline virtual
Definition at line 12 of file Shear.h.
References func_m.
Member Function Documentation
apply()
void mslang::Shear::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Implements mslang::Function.
Definition at line 37 of file Shear.cpp.
References mslang::Function::apply(), applyShear(), and func_m.
applyShear()
void mslang::Shear::applyShear (std::vector< std::shared_ptr< Base > > & bfuncs)
Definition at line 22 of file Shear.cpp.
References angleX_m, angleY_m, and applyShear().
Referenced by apply(), and applyShear().
parse()
bool mslang::Function::parse (iterator & it, const iterator & end, Function *& fun) static inherited
Definition at line 47 of file MSLang.cpp.
References mslang::Function::FCall, mslang::Difference::parse_detail(), mslang::Intersection::parse_detail(), mslang::Mask::parse_detail(), mslang::Polygon::parse_detail(), mslang::Repeat::parse_detail(), mslang::Rotation::parse_detail(), parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), mslang::Union::parse_detail(), mslang::Ellipse::parse_detail(), and mslang::Rectangle::parse_detail().
Referenced by mslang::parse(), mslang::Difference::parse_detail(), mslang::Intersection::parse_detail(), mslang::Repeat::parse_detail(), mslang::Rotation::parse_detail(), parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), and mslang::Union::parse_detail().
parse_detail()
bool mslang::Shear::parse_detail (iterator & it, const iterator & end, Function *& fun) static
Definition at line 42 of file Shear.cpp.
References angleX_m, angleY_m, func_m, mslang::ArgumentExtractor::get(), mslang::ArgumentExtractor::getLengthConsumed(), mslang::Function::parse(), and mslang::parseMathExpression().
Referenced by mslang::Function::parse().
print()
void mslang::Shear::print (int indentwidth) virtual
Implements mslang::Function.
Definition at line 8 of file Shear.cpp.
References angleX_m, angleY_m, func_m, and mslang::Function::print().
Member Data Documentation
angleX_m
double mslang::Shear::angleX_m
Definition at line 9 of file Shear.h.
Referenced by applyShear(), parse_detail(), and print().
angleY_m
double mslang::Shear::angleY_m
Definition at line 10 of file Shear.h.
Referenced by applyShear(), parse_detail(), and print().
Double
const std::string mslang::Function::Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 34 of file MSLang.h.
FCall
const std::string mslang::Function::FCall = "([a-z_]*)\\‍((.*)" static inherited
Definition at line 36 of file MSLang.h.
Referenced by mslang::Function::parse().
func_m
Function* mslang::Shear::func_m
Definition at line 8 of file Shear.h.
Referenced by apply(), parse_detail(), print(), and ~Shear().
UDouble
const std::string mslang::Function::UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 33 of file MSLang.h.
Referenced by mslang::Rectangle::parse_detail().
UInt
const std::string mslang::Function::UInt = "([0-9]+)" static inherited
Definition at line 35 of file MSLang.h.
The documentation for this struct was generated from the following files:
Shear.h
Shear.cpp