OPALX (Object Oriented Parallel Accelerator Library for Exascal): mslang::Repeat Struct Reference
mslang::Repeat Struct Reference
#include <Repeat.h>
Public Member Functions
virtual ~Repeat ()
virtual void print (int indentwidth)
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *&fun)
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
Function * func_m
unsigned int N_m
double shiftx_m
double shifty_m
double rot_m
Static Public Attributes
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\‍((.*)"
Detailed Description
Definition at line 7 of file Repeat.h.
Constructor & Destructor Documentation
~Repeat()
virtual mslang::Repeat::~Repeat () inline virtual
Definition at line 14 of file Repeat.h.
References func_m.
Member Function Documentation
apply()
void mslang::Repeat::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Implements mslang::Function.
Definition at line 17 of file Repeat.cpp.
References mslang::Function::apply(), func_m, mslang::AffineTransformation::mult(), N_m, rot_m, shiftx_m, and shifty_m.
parse()
bool mslang::Function::parse (iterator & it, const iterator & end, Function *& fun) static inherited
Definition at line 47 of file MSLang.cpp.
References mslang::Function::FCall, mslang::Difference::parse_detail(), mslang::Intersection::parse_detail(), mslang::Mask::parse_detail(), mslang::Polygon::parse_detail(), parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), mslang::Union::parse_detail(), mslang::Ellipse::parse_detail(), and mslang::Rectangle::parse_detail().
Referenced by mslang::parse(), mslang::Difference::parse_detail(), mslang::Intersection::parse_detail(), parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), and mslang::Union::parse_detail().
parse_detail()
bool mslang::Repeat::parse_detail (iterator & it, const iterator & end, Function *& fun) static
Definition at line 36 of file Repeat.cpp.
References func_m, mslang::ArgumentExtractor::get(), mslang::ArgumentExtractor::getLengthConsumed(), mslang::ArgumentExtractor::getNumArguments(), N_m, mslang::Function::parse(), mslang::parseMathExpression(), rot_m, shiftx_m, and shifty_m.
Referenced by mslang::Function::parse().
print()
void mslang::Repeat::print (int indentwidth) virtual
Implements mslang::Function.
Definition at line 6 of file Repeat.cpp.
References func_m, N_m, mslang::Function::print(), shiftx_m, and shifty_m.
Member Data Documentation
Double
const std::string mslang::Function::Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 34 of file MSLang.h.
FCall
const std::string mslang::Function::FCall = "([a-z_]*)\\‍((.*)" static inherited
Definition at line 36 of file MSLang.h.
Referenced by mslang::Function::parse().
func_m
Function* mslang::Repeat::func_m
Definition at line 8 of file Repeat.h.
Referenced by apply(), parse_detail(), print(), and ~Repeat().
N_m
unsigned int mslang::Repeat::N_m
Definition at line 9 of file Repeat.h.
Referenced by apply(), parse_detail(), and print().
rot_m
double mslang::Repeat::rot_m
Definition at line 12 of file Repeat.h.
Referenced by apply(), and parse_detail().
shiftx_m
double mslang::Repeat::shiftx_m
Definition at line 10 of file Repeat.h.
Referenced by apply(), parse_detail(), and print().
shifty_m
double mslang::Repeat::shifty_m
Definition at line 11 of file Repeat.h.
Referenced by apply(), parse_detail(), and print().
UDouble
const std::string mslang::Function::UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 33 of file MSLang.h.
Referenced by mslang::Rectangle::parse_detail().
UInt
const std::string mslang::Function::UInt = "([0-9]+)" static inherited
Definition at line 35 of file MSLang.h.
The documentation for this struct was generated from the following files:
Repeat.h
Repeat.cpp