OPALX (Object Oriented Parallel Accelerator Library for Exascal): mslang::AffineTransformation Struct Reference
mslang::AffineTransformation Struct Reference
#include <AffineTransformation.h>
Public Member Functions
AffineTransformation (const Vector_t< double, 3 > &row0, const Vector_t< double, 3 > &row1)
AffineTransformation ()
double & operator() (int i, int j)
double operator() (int i, int j) const
AffineTransformation getInverse () const
Vector_t< double, 3 > getOrigin () const
double getAngle () const
Vector_t< double, 3 > transformTo (const Vector_t< double, 3 > &v) const
Vector_t< double, 3 > transformFrom (const Vector_t< double, 3 > &v) const
AffineTransformation mult (const AffineTransformation &B)
Public Attributes
matrix3x3_t data_
Detailed Description
Definition at line 8 of file AffineTransformation.h.
Constructor & Destructor Documentation
AffineTransformation() [1/2]
mslang::AffineTransformation::AffineTransformation (const Vector_t< double, 3 > & row0, const Vector_t< double, 3 > & row1) inline
Definition at line 11 of file AffineTransformation.h.
References data_.
AffineTransformation() [2/2]
mslang::AffineTransformation::AffineTransformation () inline
Definition at line 24 of file AffineTransformation.h.
Member Function Documentation
getAngle()
double mslang::AffineTransformation::getAngle () const inline
Definition at line 53 of file AffineTransformation.h.
Referenced by mslang::Ellipse::print(), mslang::Rectangle::print(), and mslang::Triangle::print().
getInverse()
AffineTransformation mslang::AffineTransformation::getInverse () const inline
Definition at line 33 of file AffineTransformation.h.
Referenced by transformFrom().
getOrigin()
Vector_t< double, 3 > mslang::AffineTransformation::getOrigin () const inline
Definition at line 49 of file AffineTransformation.h.
Referenced by mslang::Ellipse::print(), mslang::Rectangle::print(), and mslang::Triangle::print().
mult()
AffineTransformation mslang::AffineTransformation::mult (const AffineTransformation & B) inline
Definition at line 69 of file AffineTransformation.h.
References data_, and prod().
Referenced by mslang::Repeat::apply().
operator()() [1/2]
double & mslang::AffineTransformation::operator() (int i, int j) inline
Definition at line 29 of file AffineTransformation.h.
References data_.
operator()() [2/2]
double mslang::AffineTransformation::operator() (int i, int j) const inline
Definition at line 31 of file AffineTransformation.h.
References data_.
transformFrom()
Vector_t< double, 3 > mslang::AffineTransformation::transformFrom (const Vector_t< double, 3 > & v) const inline
Definition at line 64 of file AffineTransformation.h.
References getInverse(), and transformTo().
Referenced by mslang::Ellipse::computeBoundingBox(), mslang::Rectangle::computeBoundingBox(), mslang::Triangle::computeBoundingBox(), mslang::Ellipse::writeGnuplot(), mslang::Rectangle::writeGnuplot(), and mslang::Triangle::writeGnuplot().
transformTo()
Vector_t< double, 3 > mslang::AffineTransformation::transformTo (const Vector_t< double, 3 > & v) const inline
Definition at line 55 of file AffineTransformation.h.
References data_, and prod_matrix_vector().
Referenced by mslang::Ellipse::isInside(), mslang::Rectangle::isInside(), mslang::Triangle::isInside(), and transformFrom().
Member Data Documentation
data_
matrix3x3_t mslang::AffineTransformation::data_
Definition at line 9 of file AffineTransformation.h.
Referenced by AffineTransformation(), mult(), operator()(), operator()(), and transformTo().
The documentation for this struct was generated from the following file:
AffineTransformation.h