OPALX (Object Oriented Parallel Accelerator Library for Exascal): mslang::Base Struct Reference
mslang::Base Struct Reference abstract
#include <MSLang.h>
Public Member Functions
Base ()
Base (const Base &right)
virtual ~Base ()
virtual std::shared_ptr< Base > clone () const =0
virtual void writeGnuplot (std::ofstream &out) const =0
virtual void computeBoundingBox ()=0
virtual bool isInside (const Vector_t< double, 3 > &R) const =0
virtual void divideBy (std::vector< std::shared_ptr< Base > > &divisors)
virtual void print (int indent)=0
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)=0
Static Public Member Functions
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
AffineTransformation trafo_m
BoundingBox2D bb_m
std::vector< std::shared_ptr< Base > > divisor_m
Static Public Attributes
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\‍((.*)"
Detailed Description
Definition at line 37 of file MSLang.h.
Constructor & Destructor Documentation
Base() [1/2]
mslang::Base::Base () inline
Definition at line 42 of file MSLang.h.
Base() [2/2]
mslang::Base::Base (const Base & right) inline
Definition at line 44 of file MSLang.h.
~Base()
virtual mslang::Base::~Base () inline virtual
Definition at line 46 of file MSLang.h.
References divisor_m.
Member Function Documentation
apply()
virtual void mslang::Function::apply (std::vector< std::shared_ptr< Base > > & bfuncs) pure virtual inherited
Implemented in mslang::Difference, mslang::Ellipse, mslang::Intersection, mslang::Mask, mslang::Polygon, mslang::Rectangle, mslang::Repeat, mslang::Rotation, mslang::Shear, mslang::SymmetricDifference, mslang::Translation, mslang::Triangle, and mslang::Union.
Referenced by mslang::Difference::apply(), mslang::Intersection::apply(), mslang::Repeat::apply(), mslang::Rotation::apply(), mslang::Shear::apply(), mslang::SymmetricDifference::apply(), mslang::Translation::apply(), and mslang::Union::apply().
clone()
virtual std::shared_ptr< Base > mslang::Base::clone () const pure virtual
Implemented in mslang::Ellipse, mslang::Rectangle, and mslang::Triangle.
computeBoundingBox()
virtual void mslang::Base::computeBoundingBox () pure virtual
Implemented in mslang::Ellipse, mslang::Rectangle, and mslang::Triangle.
divideBy()
virtual void mslang::Base::divideBy (std::vector< std::shared_ptr< Base > > & divisors) inline virtual
Definition at line 57 of file MSLang.h.
References bb_m, divisor_m, and mslang::BoundingBox2D::doesIntersect().
isInside()
virtual bool mslang::Base::isInside (const Vector_t< double, 3 > & R) const pure virtual
Implemented in mslang::Ellipse, mslang::Rectangle, and mslang::Triangle.
parse()
bool mslang::Function::parse (iterator & it, const iterator & end, Function *& fun) static inherited
Definition at line 47 of file MSLang.cpp.
References mslang::Function::FCall, mslang::Difference::parse_detail(), mslang::Intersection::parse_detail(), mslang::Mask::parse_detail(), mslang::Polygon::parse_detail(), mslang::Repeat::parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), mslang::Union::parse_detail(), mslang::Ellipse::parse_detail(), and mslang::Rectangle::parse_detail().
Referenced by mslang::parse(), mslang::Difference::parse_detail(), mslang::Intersection::parse_detail(), mslang::Repeat::parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), and mslang::Union::parse_detail().
print()
virtual void mslang::Function::print (int indent) pure virtual inherited
Implemented in mslang::Mask, mslang::Polygon, mslang::Difference, mslang::Ellipse, mslang::Intersection, mslang::Rectangle, mslang::Repeat, mslang::Rotation, mslang::Shear, mslang::SymmetricDifference, mslang::Translation, mslang::Triangle, and mslang::Union.
Referenced by mslang::Difference::print(), mslang::Intersection::print(), mslang::Repeat::print(), mslang::Rotation::print(), mslang::Shear::print(), mslang::SymmetricDifference::print(), and mslang::Translation::print().
writeGnuplot()
virtual void mslang::Base::writeGnuplot (std::ofstream & out) const pure virtual
Implemented in mslang::Ellipse, mslang::Rectangle, and mslang::Triangle.
Member Data Documentation
bb_m
BoundingBox2D mslang::Base::bb_m
Definition at line 39 of file MSLang.h.
Referenced by mslang::Ellipse::clone(), mslang::Rectangle::clone(), mslang::Triangle::clone(), mslang::Ellipse::computeBoundingBox(), mslang::Rectangle::computeBoundingBox(), mslang::Triangle::computeBoundingBox(), divideBy(), mslang::Ellipse::isInside(), and mslang::Rectangle::isInside().
divisor_m
std::vector<std::shared_ptr<Base> > mslang::Base::divisor_m
Definition at line 40 of file MSLang.h.
Referenced by mslang::Ellipse::clone(), mslang::Rectangle::clone(), mslang::Triangle::clone(), mslang::Ellipse::computeBoundingBox(), mslang::Rectangle::computeBoundingBox(), mslang::Triangle::computeBoundingBox(), divideBy(), mslang::Ellipse::isInside(), mslang::Rectangle::isInside(), mslang::Triangle::isInside(), mslang::Ellipse::writeGnuplot(), mslang::Rectangle::writeGnuplot(), mslang::Triangle::writeGnuplot(), and ~Base().
Double
const std::string mslang::Function::Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 32 of file MSLang.h.
FCall
const std::string mslang::Function::FCall = "([a-z_]*)\\‍((.*)" static inherited
Definition at line 34 of file MSLang.h.
Referenced by mslang::Function::parse().
trafo_m
AffineTransformation mslang::Base::trafo_m
Definition at line 38 of file MSLang.h.
Referenced by mslang::Ellipse::clone(), mslang::Rectangle::clone(), mslang::Triangle::clone(), mslang::Ellipse::computeBoundingBox(), mslang::Rectangle::computeBoundingBox(), mslang::Triangle::computeBoundingBox(), mslang::Ellipse::isInside(), mslang::Rectangle::isInside(), mslang::Triangle::isInside(), mslang::Mask::parse_detail(), mslang::Ellipse::print(), mslang::Rectangle::print(), mslang::Triangle::print(), mslang::Ellipse::writeGnuplot(), mslang::Rectangle::writeGnuplot(), and mslang::Triangle::writeGnuplot().
UDouble
const std::string mslang::Function::UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 31 of file MSLang.h.
Referenced by mslang::Rectangle::parse_detail().
UInt
const std::string mslang::Function::UInt = "([0-9]+)" static inherited
Definition at line 33 of file MSLang.h.
The documentation for this struct was generated from the following file:
MSLang.h