OPALX (Object Oriented Parallel Accelerator Library for Exascal): mslang::Union Struct Reference
mslang::Union Struct Reference
#include <Union.h>
Public Member Functions
virtual ~Union ()
virtual void print (int indentwidth)
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *&fun)
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
std::vector< Function * > funcs_m
Static Public Attributes
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\‍((.*)"
Detailed Description
Definition at line 7 of file Union.h.
Constructor & Destructor Documentation
~Union()
virtual mslang::Union::~Union () inline virtual
Definition at line 10 of file Union.h.
References funcs_m.
Member Function Documentation
apply()
void mslang::Union::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Implements mslang::Function.
Definition at line 22 of file Union.cpp.
References mslang::Function::apply(), and funcs_m.
parse()
bool mslang::Function::parse (iterator & it, const iterator & end, Function *& fun) static inherited
Definition at line 47 of file MSLang.cpp.
References mslang::Function::FCall, mslang::Difference::parse_detail(), mslang::Intersection::parse_detail(), mslang::Mask::parse_detail(), mslang::Polygon::parse_detail(), mslang::Repeat::parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), parse_detail(), mslang::Ellipse::parse_detail(), and mslang::Rectangle::parse_detail().
Referenced by mslang::parse(), mslang::Difference::parse_detail(), mslang::Intersection::parse_detail(), mslang::Repeat::parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), and parse_detail().
parse_detail()
bool mslang::Union::parse_detail (iterator & it, const iterator & end, Function *& fun) static
Definition at line 31 of file Union.cpp.
References funcs_m, and mslang::Function::parse().
Referenced by mslang::Function::parse().
print()
void mslang::Union::print (int indentwidth) virtual
Implements mslang::Function.
Definition at line 6 of file Union.cpp.
References funcs_m.
Member Data Documentation
Double
const std::string mslang::Function::Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 34 of file MSLang.h.
FCall
const std::string mslang::Function::FCall = "([a-z_]*)\\‍((.*)" static inherited
Definition at line 36 of file MSLang.h.
Referenced by mslang::Function::parse().
funcs_m
std::vector<Function*> mslang::Union::funcs_m
Definition at line 8 of file Union.h.
Referenced by apply(), parse_detail(), print(), and ~Union().
UDouble
const std::string mslang::Function::UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 33 of file MSLang.h.
Referenced by mslang::Rectangle::parse_detail().
UInt
const std::string mslang::Function::UInt = "([0-9]+)" static inherited
Definition at line 35 of file MSLang.h.
The documentation for this struct was generated from the following files:
Union.h
Union.cpp