OPALX (Object Oriented Parallel Accelerator Library for Exascal): BMultipoleField::Pair Struct Reference
BMultipoleField::Pair Struct Reference
Public Member Functions
Pair ()
Pair (double normal, double skewed=0.0)
Pair (const Pair &)
~Pair ()
void operator= (const Pair &)
Pair operator+ (const Pair &) const
Pair operator- (const Pair &) const
Pair operator* (double scale) const
void operator+= (const Pair &)
void operator-= (const Pair &)
void operator*= (double scale)
Pair operator- () const
Public Attributes
double B
double A
Detailed Description
Definition at line 96 of file BMultipoleField.h.
Constructor & Destructor Documentation
Pair() [1/3]
BMultipoleField::Pair::Pair () inline
Definition at line 30 of file BMultipoleField.cpp.
References A, and B.
Referenced by operator*(), operator+(), operator+=(), operator-(), operator-(), operator-=(), operator=(), and Pair().
Pair() [2/3]
BMultipoleField::Pair::Pair (double normal, double skewed = 0.0) inline
Definition at line 32 of file BMultipoleField.cpp.
References A, B, and BMultipoleField::normal().
Pair() [3/3]
BMultipoleField::Pair::Pair (const Pair & rhs) inline
Definition at line 37 of file BMultipoleField.cpp.
References A, B, and Pair().
~Pair()
BMultipoleField::Pair::~Pair () inline
Definition at line 42 of file BMultipoleField.cpp.
Member Function Documentation
operator*()
BMultipoleField::Pair BMultipoleField::Pair::operator* (double scale) const inline
Definition at line 57 of file BMultipoleField.cpp.
References A, B, Pair(), and BMultipoleField::scale().
operator*=()
void BMultipoleField::Pair::operator*= (double scale) inline
Definition at line 71 of file BMultipoleField.cpp.
References A, B, and BMultipoleField::scale().
operator+()
BMultipoleField::Pair BMultipoleField::Pair::operator+ (const Pair & rhs) const inline
Definition at line 49 of file BMultipoleField.cpp.
References A, B, and Pair().
operator+=()
void BMultipoleField::Pair::operator+= (const Pair & rhs) inline
Definition at line 61 of file BMultipoleField.cpp.
References A, B, and Pair().
operator-() [1/2]
BMultipoleField::Pair BMultipoleField::Pair::operator- () const inline
Definition at line 76 of file BMultipoleField.cpp.
References A, B, and Pair().
operator-() [2/2]
BMultipoleField::Pair BMultipoleField::Pair::operator- (const Pair & rhs) const inline
Definition at line 53 of file BMultipoleField.cpp.
References A, B, and Pair().
operator-=()
void BMultipoleField::Pair::operator-= (const Pair & rhs) inline
Definition at line 66 of file BMultipoleField.cpp.
References A, B, and Pair().
operator=()
void BMultipoleField::Pair::operator= (const Pair & rhs) inline
Definition at line 44 of file BMultipoleField.cpp.
References A, B, and Pair().
Member Data Documentation
A
double BMultipoleField::Pair::A
Definition at line 114 of file BMultipoleField.h.
Referenced by operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-(), operator-=(), operator=(), Pair(), Pair(), and Pair().
B
double BMultipoleField::Pair::B
Definition at line 113 of file BMultipoleField.h.
Referenced by operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-(), operator-=(), operator=(), Pair(), Pair(), and Pair().
The documentation for this struct was generated from the following files:
BMultipoleField.h
BMultipoleField.cpp