OPALX (Object Oriented Parallel Accelerator Library for Exascal): mslang::SymmetricDifference Struct Reference
mslang::SymmetricDifference Struct Reference
#include <SymmetricDifference.h>
Public Member Functions
SymmetricDifference ()
SymmetricDifference (const SymmetricDifference &right)
virtual ~SymmetricDifference ()
virtual void print (int indentwidth)
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *&fun)
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
Function * firstOperand_m
Function * secondOperand_m
Static Public Attributes
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\‍((.*)"
Detailed Description
Definition at line 7 of file SymmetricDifference.h.
Constructor & Destructor Documentation
SymmetricDifference() [1/2]
mslang::SymmetricDifference::SymmetricDifference () inline
Definition at line 11 of file SymmetricDifference.h.
Referenced by parse_detail(), and SymmetricDifference().
SymmetricDifference() [2/2]
mslang::SymmetricDifference::SymmetricDifference (const SymmetricDifference & right) inline
Definition at line 13 of file SymmetricDifference.h.
References firstOperand_m, secondOperand_m, and SymmetricDifference().
~SymmetricDifference()
virtual mslang::SymmetricDifference::~SymmetricDifference () inline virtual
Definition at line 16 of file SymmetricDifference.h.
References firstOperand_m, and secondOperand_m.
Member Function Documentation
apply()
void mslang::SymmetricDifference::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Implements mslang::Function.
Definition at line 15 of file SymmetricDifference.cpp.
References firstOperand_m, and secondOperand_m.
parse()
bool mslang::Function::parse (iterator & it, const iterator & end, Function *& fun) static inherited
Definition at line 47 of file MSLang.cpp.
References FCall, mslang::Difference::parse_detail(), mslang::Ellipse::parse_detail(), mslang::Intersection::parse_detail(), mslang::Mask::parse_detail(), mslang::Polygon::parse_detail(), mslang::Rectangle::parse_detail(), mslang::Repeat::parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), and mslang::Union::parse_detail().
Referenced by mslang::parse(), mslang::Difference::parse_detail(), mslang::Intersection::parse_detail(), mslang::Repeat::parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), and mslang::Union::parse_detail().
parse_detail()
bool mslang::SymmetricDifference::parse_detail (iterator & it, const iterator & end, Function *& fun) static
Definition at line 42 of file SymmetricDifference.cpp.
References firstOperand_m, mslang::Function::parse(), secondOperand_m, and SymmetricDifference().
Referenced by mslang::Function::parse().
print()
void mslang::SymmetricDifference::print (int indentwidth) virtual
Implements mslang::Function.
Definition at line 6 of file SymmetricDifference.cpp.
References firstOperand_m, and secondOperand_m.
Member Data Documentation
Double
const std::string mslang::Function::Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 32 of file MSLang.h.
FCall
const std::string mslang::Function::FCall = "([a-z_]*)\\‍((.*)" static inherited
Definition at line 34 of file MSLang.h.
Referenced by parse().
firstOperand_m
Function* mslang::SymmetricDifference::firstOperand_m
Definition at line 8 of file SymmetricDifference.h.
Referenced by apply(), parse_detail(), print(), SymmetricDifference(), and ~SymmetricDifference().
secondOperand_m
Function* mslang::SymmetricDifference::secondOperand_m
Definition at line 9 of file SymmetricDifference.h.
Referenced by apply(), parse_detail(), print(), SymmetricDifference(), and ~SymmetricDifference().
UDouble
const std::string mslang::Function::UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 31 of file MSLang.h.
Referenced by mslang::Rectangle::parse_detail().
UInt
const std::string mslang::Function::UInt = "([0-9]+)" static inherited
Definition at line 33 of file MSLang.h.
The documentation for this struct was generated from the following files:
SymmetricDifference.h
SymmetricDifference.cpp