OPALX (Object Oriented Parallel Accelerator Library for Exascal): matheval::detail::recursive_wrapper< T > Struct Template Reference
matheval::detail::recursive_wrapper< T > Struct Template Reference
#include <matheval.hpp>
Public Member Functions
recursive_wrapper ()
recursive_wrapper (const T &t)
recursive_wrapper (T &&t)
recursive_wrapper (const recursive_wrapper &other)
recursive_wrapper (recursive_wrapper &&other) noexcept=default
recursive_wrapper & operator= (const recursive_wrapper &other)
recursive_wrapper & operator= (recursive_wrapper &&other) noexcept=default
T & get ()
const T & get () const
operator T& ()
operator const T & () const
Private Attributes
std::unique_ptr< T > ptr
Detailed Description
template<typename T>
struct matheval::detail::recursive_wrapper< T >
Definition at line 97 of file matheval.hpp.
Constructor & Destructor Documentation
recursive_wrapper() [1/5]
template<typename T> matheval::detail::recursive_wrapper< T >::recursive_wrapper () inline
Definition at line 98 of file matheval.hpp.
References ptr.
Referenced by operator=(), operator=(), recursive_wrapper(), and recursive_wrapper().
recursive_wrapper() [2/5]
template<typename T> matheval::detail::recursive_wrapper< T >::recursive_wrapper (const T & t) inline
Definition at line 99 of file matheval.hpp.
References ptr.
recursive_wrapper() [3/5]
template<typename T> matheval::detail::recursive_wrapper< T >::recursive_wrapper (T && t) inline
Definition at line 100 of file matheval.hpp.
References ptr.
recursive_wrapper() [4/5]
template<typename T> matheval::detail::recursive_wrapper< T >::recursive_wrapper (const recursive_wrapper< T > & other) inline
Definition at line 101 of file matheval.hpp.
References ptr, and recursive_wrapper().
recursive_wrapper() [5/5]
template<typename T> matheval::detail::recursive_wrapper< T >::recursive_wrapper (recursive_wrapper< T > && other) default noexcept
References recursive_wrapper().
Member Function Documentation
get() [1/2]
template<typename T> T & matheval::detail::recursive_wrapper< T >::get () inline
Definition at line 114 of file matheval.hpp.
References ptr.
get() [2/2]
template<typename T> const T & matheval::detail::recursive_wrapper< T >::get () const inline
Definition at line 115 of file matheval.hpp.
References ptr.
operator const T &()
template<typename T> matheval::detail::recursive_wrapper< T >::operator const T & () const inline
Definition at line 118 of file matheval.hpp.
References ptr.
operator T&()
template<typename T> matheval::detail::recursive_wrapper< T >::operator T& () inline
Definition at line 117 of file matheval.hpp.
References ptr.
operator=() [1/2]
template<typename T> recursive_wrapper & matheval::detail::recursive_wrapper< T >::operator= (const recursive_wrapper< T > & other) inline
Definition at line 105 of file matheval.hpp.
References ptr, and recursive_wrapper().
operator=() [2/2]
template<typename T> recursive_wrapper & matheval::detail::recursive_wrapper< T >::operator= (recursive_wrapper< T > && other) default noexcept
References recursive_wrapper().
Member Data Documentation
ptr
template<typename T> std::unique_ptr<T> matheval::detail::recursive_wrapper< T >::ptr private
Definition at line 121 of file matheval.hpp.
Referenced by get(), get(), operator const T &(), operator T&(), operator=(), recursive_wrapper(), recursive_wrapper(), recursive_wrapper(), and recursive_wrapper().
The documentation for this struct was generated from the following file:
matheval.hpp