OPALX (Object Oriented Parallel Accelerator Library for Exascal): mslang::Function Struct Reference
mslang::Function Struct Reference abstract
#include <MSLang.h>
Public Member Functions
virtual ~Function ()
virtual void print (int indent)=0
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)=0
Static Public Member Functions
static bool parse (iterator &it, const iterator &end, Function *&fun)
Static Public Attributes
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\‍((.*)"
Detailed Description
Definition at line 23 of file MSLang.h.
Constructor & Destructor Documentation
~Function()
virtual mslang::Function::~Function () inline virtual
Definition at line 24 of file MSLang.h.
Member Function Documentation
apply()
virtual void mslang::Function::apply (std::vector< std::shared_ptr< Base > > & bfuncs) pure virtual
Implemented in mslang::Difference, mslang::Ellipse, mslang::Intersection, mslang::Mask, mslang::Polygon, mslang::Rectangle, mslang::Repeat, mslang::Rotation, mslang::Shear, mslang::SymmetricDifference, mslang::Translation, mslang::Triangle, and mslang::Union.
Referenced by mslang::Union::apply().
parse()
bool mslang::Function::parse (iterator & it, const iterator & end, Function *& fun) static
Definition at line 47 of file MSLang.cpp.
References FCall, mslang::Difference::parse_detail(), mslang::Ellipse::parse_detail(), mslang::Intersection::parse_detail(), mslang::Mask::parse_detail(), mslang::Polygon::parse_detail(), mslang::Rectangle::parse_detail(), mslang::Repeat::parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), and mslang::Union::parse_detail().
Referenced by mslang::parse(), mslang::Difference::parse_detail(), mslang::Intersection::parse_detail(), mslang::Repeat::parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), and mslang::Union::parse_detail().
print()
virtual void mslang::Function::print (int indent) pure virtual
Implemented in mslang::Difference, mslang::Ellipse, mslang::Intersection, mslang::Mask, mslang::Polygon, mslang::Rectangle, mslang::Repeat, mslang::Rotation, mslang::Shear, mslang::SymmetricDifference, mslang::Translation, mslang::Triangle, and mslang::Union.
Member Data Documentation
Double
const std::string mslang::Function::Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static
Definition at line 32 of file MSLang.h.
FCall
const std::string mslang::Function::FCall = "([a-z_]*)\\‍((.*)" static
Definition at line 34 of file MSLang.h.
Referenced by parse().
UDouble
const std::string mslang::Function::UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static
Definition at line 31 of file MSLang.h.
Referenced by mslang::Rectangle::parse_detail().
UInt
const std::string mslang::Function::UInt = "([0-9]+)" static
Definition at line 33 of file MSLang.h.
The documentation for this struct was generated from the following files:
MSLang.h
MSLang.cpp