OPALX (Object Oriented Parallel Accelerator Library for Exascal): SDDS::parameter Struct Reference
SDDS::parameter Struct Reference
#include <parameter.hpp>
Classes
struct complainUnsupported
Public Types
enum attributes {
NAME , SYMBOL , UNITS , DESCRIPTION ,
FORMAT_STRING , TYPE , FIXED_VALUE
}
Public Member Functions
bool checkMandatories () const
bool parse (const std::string &input, size_t &pos)
Public Attributes
unsigned int order_m
std::optional< std::string > name_m
std::optional< std::string > units_m
std::optional< std::string > description_m
std::optional< ast::datatype > type_m
ast::variant_t value_m
Static Public Attributes
static unsigned int count_m
Detailed Description
Definition at line 30 of file parameter.hpp.
Member Enumeration Documentation
attributes
enum SDDS::parameter::attributes
Enumerator
NAME
SYMBOL
UNITS
DESCRIPTION
FORMAT_STRING
TYPE
FIXED_VALUE
Definition at line 32 of file parameter.hpp.
Member Function Documentation
checkMandatories()
bool SDDS::parameter::checkMandatories () const inline
Definition at line 49 of file parameter.hpp.
References name_m, and type_m.
parse()
bool SDDS::parameter::parse (const std::string & input, size_t & pos) inline
Definition at line 79 of file parameter.hpp.
References SDDS::ast::CHARACTER, SDDS::ast::DOUBLE, SDDS::ast::FLOAT, SDDS::parser::ValueParser::getPosition(), SDDS::ast::LONG, SDDS::parser::ValueParser::parseChar(), SDDS::parser::ValueParser::parseDouble(), SDDS::parser::ValueParser::parseFloat(), SDDS::parser::ValueParser::parseLong(), SDDS::parser::ValueParser::parseShort(), SDDS::parser::ValueParser::parseString(), SDDS::ast::SHORT, and SDDS::ast::STRING.
Member Data Documentation
count_m
unsigned int SDDS::parameter::count_m static
Definition at line 47 of file parameter.hpp.
Referenced by SDDS::parameterOrder< Iterator >::operator()().
description_m
std::optional<std::string> SDDS::parameter::description_m
Definition at line 44 of file parameter.hpp.
Referenced by SDDS::operator<<(), and SDDS::parser::SimpleParser::parseParameter().
name_m
std::optional<std::string> SDDS::parameter::name_m
Definition at line 42 of file parameter.hpp.
Referenced by checkMandatories(), SDDS::operator<<(), and SDDS::parser::SimpleParser::parseParameter().
order_m
unsigned int SDDS::parameter::order_m
Definition at line 41 of file parameter.hpp.
Referenced by SDDS::parameterOrder< Iterator >::operator()(), and SDDS::operator<<().
type_m
std::optional<ast::datatype> SDDS::parameter::type_m
Definition at line 45 of file parameter.hpp.
Referenced by checkMandatories(), SDDS::operator<<(), and SDDS::parser::SimpleParser::parseParameter().
units_m
std::optional<std::string> SDDS::parameter::units_m
Definition at line 43 of file parameter.hpp.
Referenced by SDDS::operator<<(), and SDDS::parser::SimpleParser::parseParameter().
value_m
ast::variant_t SDDS::parameter::value_m
Definition at line 46 of file parameter.hpp.
The documentation for this struct was generated from the following file:
parameter.hpp