OPALX (Object Oriented Parallel Accelerator Library for Exascal): SDDS::column Struct Reference
SDDS::column Struct Reference
#include <column.hpp>
Classes
struct complainUnsupported
Public Types
enum attributes {
NAME , SYMBOL , UNITS , DESCRIPTION ,
FORMAT_STRING , TYPE , FIELD_LENGTH
}
Public Member Functions
bool checkMandatories () const
bool parse (const std::string &input, size_t &pos)
Public Attributes
unsigned int order_m
std::optional< std::string > name_m
std::optional< std::string > units_m
std::optional< std::string > description_m
std::optional< ast::datatype > type_m
ast::columnData_t values_m
Static Public Attributes
static unsigned int count_m
Detailed Description
Definition at line 30 of file column.hpp.
Member Enumeration Documentation
attributes
enum SDDS::column::attributes
Enumerator
NAME
SYMBOL
UNITS
DESCRIPTION
FORMAT_STRING
TYPE
FIELD_LENGTH
Definition at line 32 of file column.hpp.
Member Function Documentation
checkMandatories()
bool SDDS::column::checkMandatories () const inline
Definition at line 49 of file column.hpp.
References name_m, and type_m.
parse()
bool SDDS::column::parse (const std::string & input, size_t & pos) inline
Definition at line 79 of file column.hpp.
References SDDS::ast::CHARACTER, SDDS::ast::DOUBLE, SDDS::ast::FLOAT, SDDS::parser::ValueParser::getPosition(), SDDS::ast::LONG, SDDS::parser::ValueParser::parseChar(), SDDS::parser::ValueParser::parseDouble(), SDDS::parser::ValueParser::parseFloat(), SDDS::parser::ValueParser::parseLong(), SDDS::parser::ValueParser::parseQuotedString(), SDDS::parser::ValueParser::parseShort(), SDDS::ast::SHORT, and SDDS::ast::STRING.
Member Data Documentation
count_m
unsigned int SDDS::column::count_m static
Definition at line 47 of file column.hpp.
Referenced by SDDS::columnOrder< Iterator >::operator()().
description_m
std::optional<std::string> SDDS::column::description_m
Definition at line 44 of file column.hpp.
Referenced by SDDS::operator<<(), and SDDS::parser::SimpleParser::parseColumn().
name_m
std::optional<std::string> SDDS::column::name_m
Definition at line 42 of file column.hpp.
Referenced by checkMandatories(), SDDS::operator<<(), and SDDS::parser::SimpleParser::parseColumn().
order_m
unsigned int SDDS::column::order_m
Definition at line 41 of file column.hpp.
Referenced by SDDS::columnOrder< Iterator >::operator()(), and SDDS::operator<<().
type_m
std::optional<ast::datatype> SDDS::column::type_m
Definition at line 45 of file column.hpp.
Referenced by checkMandatories(), SDDS::operator<<(), and SDDS::parser::SimpleParser::parseColumn().
units_m
std::optional<std::string> SDDS::column::units_m
Definition at line 43 of file column.hpp.
Referenced by SDDS::operator<<(), and SDDS::parser::SimpleParser::parseColumn().
values_m
ast::columnData_t SDDS::column::values_m
Definition at line 46 of file column.hpp.
The documentation for this struct was generated from the following file:
column.hpp