OPALX (Object Oriented Parallel Accelerator Library for Exascal): mslang::QuadTree Struct Reference
mslang::QuadTree Struct Reference
#include <QuadTree.h>
Public Member Functions
QuadTree ()
QuadTree (int l, const BoundingBox2D &b)
QuadTree (const QuadTree &right)
~QuadTree ()
void reset ()
void operator= (const QuadTree &right)
void transferIfInside (std::list< std::shared_ptr< Base > > &objs)
void buildUp ()
void writeGnuplot (std::ostream &out) const
bool isInside (const Vector_t< double, 3 > &R) const
void getDepth (unsigned int &d) const
Public Attributes
int level_m
std::list< std::shared_ptr< Base > > objects_m
BoundingBox2D bb_m
std::vector< std::shared_ptr< QuadTree > > nodes_m
Detailed Description
Definition at line 9 of file QuadTree.h.
Constructor & Destructor Documentation
QuadTree() [1/3]
mslang::QuadTree::QuadTree () inline
Definition at line 15 of file QuadTree.h.
References bb_m, level_m, and nodes_m.
Referenced by buildUp(), operator=(), and QuadTree().
QuadTree() [2/3]
mslang::QuadTree::QuadTree (int l, const BoundingBox2D & b) inline
Definition at line 17 of file QuadTree.h.
References bb_m, level_m, and nodes_m.
QuadTree() [3/3]
mslang::QuadTree::QuadTree (const QuadTree & right)
Definition at line 5 of file QuadTree.cpp.
References bb_m, level_m, nodes_m, objects_m, and QuadTree().
~QuadTree()
mslang::QuadTree::~QuadTree ()
Definition at line 17 of file QuadTree.cpp.
References nodes_m, objects_m, and ~QuadTree().
Referenced by ~QuadTree().
Member Function Documentation
buildUp()
void mslang::QuadTree::buildUp ()
Definition at line 56 of file QuadTree.cpp.
References bb_m, buildUp(), level_m, nodes_m, objects_m, and QuadTree().
Referenced by buildUp().
getDepth()
void mslang::QuadTree::getDepth (unsigned int & d) const
Definition at line 123 of file QuadTree.cpp.
References getDepth(), level_m, and nodes_m.
Referenced by getDepth().
isInside()
bool mslang::QuadTree::isInside (const Vector_t< double, 3 > & R) const
Definition at line 103 of file QuadTree.cpp.
References bb_m, isInside(), nodes_m, and objects_m.
Referenced by isInside().
operator=()
void mslang::QuadTree::operator= (const QuadTree & right)
Definition at line 30 of file QuadTree.cpp.
References bb_m, level_m, nodes_m, objects_m, operator=(), and QuadTree().
Referenced by operator=().
reset()
void mslang::QuadTree::reset ()
Definition at line 25 of file QuadTree.cpp.
References nodes_m, objects_m, and reset().
Referenced by reset().
transferIfInside()
void mslang::QuadTree::transferIfInside (std::list< std::shared_ptr< Base > > & objs)
Definition at line 44 of file QuadTree.cpp.
References bb_m, objects_m, and transferIfInside().
Referenced by transferIfInside().
writeGnuplot()
void mslang::QuadTree::writeGnuplot (std::ostream & out) const
Definition at line 90 of file QuadTree.cpp.
References bb_m, level_m, nodes_m, objects_m, and writeGnuplot().
Referenced by writeGnuplot().
Member Data Documentation
bb_m
BoundingBox2D mslang::QuadTree::bb_m
Definition at line 12 of file QuadTree.h.
Referenced by buildUp(), isInside(), operator=(), QuadTree(), QuadTree(), QuadTree(), transferIfInside(), and writeGnuplot().
level_m
int mslang::QuadTree::level_m
Definition at line 10 of file QuadTree.h.
Referenced by buildUp(), getDepth(), operator=(), QuadTree(), QuadTree(), QuadTree(), and writeGnuplot().
nodes_m
std::vector<std::shared_ptr<QuadTree> > mslang::QuadTree::nodes_m
Definition at line 13 of file QuadTree.h.
Referenced by buildUp(), getDepth(), isInside(), operator=(), QuadTree(), QuadTree(), QuadTree(), reset(), writeGnuplot(), and ~QuadTree().
objects_m
std::list<std::shared_ptr<Base> > mslang::QuadTree::objects_m
Definition at line 11 of file QuadTree.h.
Referenced by buildUp(), isInside(), operator=(), QuadTree(), reset(), transferIfInside(), writeGnuplot(), and ~QuadTree().
The documentation for this struct was generated from the following files:
QuadTree.h
QuadTree.cpp