OPALX (Object Oriented Parallel Accelerator Library for Exascal): matheval::detail::unary_op< real_t > Struct Template Reference
matheval::detail::unary_op< real_t > Struct Template Reference
Store a unary operator and its argument tree.
#include <matheval.hpp>
Public Types
using op_t = std::function<real_t(real_t)>
Signature of a unary operator: op(x)
Public Member Functions
unary_op (op_t op, expr_ast< real_t > rhs)
Save the operator and the argument tree.
unary_op (const unary_op &other)
unary_op (unary_op &&) noexcept=default
unary_op & operator= (const unary_op &other)
unary_op & operator= (unary_op &&) noexcept=default
Public Attributes
op_t op
Stored operator.
std::unique_ptr< expr_ast< real_t > > rhs
Stored argument tree.
Detailed Description
template<typename real_t>
struct matheval::detail::unary_op< real_t >
Store a unary operator and its argument tree.
Definition at line 175 of file matheval.hpp.
Member Typedef Documentation
op_t
template<typename real_t> using matheval::detail::unary_op< real_t >::op_t = std::function<real_t(real_t)>
Signature of a unary operator: op(x)
Definition at line 177 of file matheval.hpp.
Constructor & Destructor Documentation
unary_op() [1/3]
template<typename real_t> matheval::detail::unary_op< real_t >::unary_op (op_t op, expr_ast< real_t > rhs) inline
Save the operator and the argument tree.
Definition at line 180 of file matheval.hpp.
References op, and rhs.
Referenced by operator=(), operator=(), unary_op(), and unary_op().
unary_op() [2/3]
template<typename real_t> matheval::detail::unary_op< real_t >::unary_op (const unary_op< real_t > & other) inline
Definition at line 183 of file matheval.hpp.
References op, rhs, and unary_op().
unary_op() [3/3]
template<typename real_t> matheval::detail::unary_op< real_t >::unary_op (unary_op< real_t > &&) default noexcept
References unary_op().
Member Function Documentation
operator=() [1/2]
template<typename real_t> unary_op & matheval::detail::unary_op< real_t >::operator= (const unary_op< real_t > & other) inline
Definition at line 188 of file matheval.hpp.
References op, rhs, and unary_op().
operator=() [2/2]
template<typename real_t> unary_op & matheval::detail::unary_op< real_t >::operator= (unary_op< real_t > &&) default noexcept
References unary_op().
Member Data Documentation
op
template<typename real_t> op_t matheval::detail::unary_op< real_t >::op
Stored operator.
Definition at line 199 of file matheval.hpp.
Referenced by matheval::detail::ConstantFolder< real_t >::operator()(), matheval::detail::eval_ast< real_t >::operator()(), operator=(), unary_op(), and unary_op().
rhs
template<typename real_t> std::unique_ptr<expr_ast<real_t> > matheval::detail::unary_op< real_t >::rhs
Stored argument tree.
Definition at line 201 of file matheval.hpp.
Referenced by matheval::detail::ConstantFolder< real_t >::operator()(), matheval::detail::eval_ast< real_t >::operator()(), matheval::detail::expr_ast< real_t >::operator*=(), matheval::detail::expr_ast< real_t >::operator+=(), matheval::detail::expr_ast< real_t >::operator-=(), matheval::detail::expr_ast< real_t >::operator/=(), operator=(), unary_op(), and unary_op().
The documentation for this struct was generated from the following file:
matheval.hpp