OPALX (Object Oriented Parallel Accelerator Library for Exascal): mslang::Rotation Struct Reference
mslang::Rotation Struct Reference
#include <Rotation.h>
Public Member Functions
virtual ~Rotation ()
virtual void print (int indentwidth)
void applyRotation (std::vector< std::shared_ptr< Base > > &bfuncs)
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *&fun)
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
Function * func_m
double angle_m
Static Public Attributes
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\‍((.*)"
Detailed Description
Definition at line 7 of file Rotation.h.
Constructor & Destructor Documentation
~Rotation()
virtual mslang::Rotation::~Rotation () inline virtual
Definition at line 11 of file Rotation.h.
References func_m.
Member Function Documentation
apply()
void mslang::Rotation::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Implements mslang::Function.
Definition at line 33 of file Rotation.cpp.
References mslang::Function::apply(), applyRotation(), and func_m.
applyRotation()
void mslang::Rotation::applyRotation (std::vector< std::shared_ptr< Base > > & bfuncs)
Definition at line 17 of file Rotation.cpp.
References angle_m, and applyRotation().
Referenced by apply(), and applyRotation().
parse()
bool mslang::Function::parse (iterator & it, const iterator & end, Function *& fun) static inherited
Definition at line 47 of file MSLang.cpp.
References mslang::Function::FCall, mslang::Difference::parse_detail(), mslang::Intersection::parse_detail(), mslang::Mask::parse_detail(), mslang::Polygon::parse_detail(), mslang::Repeat::parse_detail(), parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), mslang::Union::parse_detail(), mslang::Ellipse::parse_detail(), and mslang::Rectangle::parse_detail().
Referenced by mslang::parse(), mslang::Difference::parse_detail(), mslang::Intersection::parse_detail(), mslang::Repeat::parse_detail(), parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), and mslang::Union::parse_detail().
parse_detail()
bool mslang::Rotation::parse_detail (iterator & it, const iterator & end, Function *& fun) static
Definition at line 38 of file Rotation.cpp.
References angle_m, func_m, mslang::ArgumentExtractor::get(), mslang::ArgumentExtractor::getLengthConsumed(), mslang::Function::parse(), and mslang::parseMathExpression().
Referenced by mslang::Function::parse().
print()
void mslang::Rotation::print (int indentwidth) virtual
Implements mslang::Function.
Definition at line 8 of file Rotation.cpp.
References angle_m, func_m, and mslang::Function::print().
Member Data Documentation
angle_m
double mslang::Rotation::angle_m
Definition at line 9 of file Rotation.h.
Referenced by applyRotation(), parse_detail(), and print().
Double
const std::string mslang::Function::Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 34 of file MSLang.h.
FCall
const std::string mslang::Function::FCall = "([a-z_]*)\\‍((.*)" static inherited
Definition at line 36 of file MSLang.h.
Referenced by mslang::Function::parse().
func_m
Function* mslang::Rotation::func_m
Definition at line 8 of file Rotation.h.
Referenced by apply(), parse_detail(), print(), and ~Rotation().
UDouble
const std::string mslang::Function::UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 33 of file MSLang.h.
Referenced by mslang::Rectangle::parse_detail().
UInt
const std::string mslang::Function::UInt = "([0-9]+)" static inherited
Definition at line 35 of file MSLang.h.
The documentation for this struct was generated from the following files:
Rotation.h
Rotation.cpp