OPALX (Object Oriented Parallel Accelerator Library for Exascal): mslang::Rectangle Struct Reference
mslang::Rectangle Struct Reference
#include <Rectangle.h>
Public Member Functions
Rectangle ()
Rectangle (const Rectangle &right)
virtual ~Rectangle ()
virtual void print (int indentwidth)
virtual void computeBoundingBox ()
virtual bool isInside (const Vector_t< double, 3 > &R) const
virtual void writeGnuplot (std::ofstream &out) const
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
virtual std::shared_ptr< Base > clone () const
virtual void divideBy (std::vector< std::shared_ptr< Base > > &divisors)
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *fun)
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
double width_m
double height_m
AffineTransformation trafo_m
BoundingBox2D bb_m
std::vector< std::shared_ptr< Base > > divisor_m
Static Public Attributes
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\‍((.*)"
Detailed Description
Definition at line 7 of file Rectangle.h.
Constructor & Destructor Documentation
Rectangle() [1/2]
mslang::Rectangle::Rectangle () inline
Definition at line 11 of file Rectangle.h.
References mslang::Base::Base(), height_m, and width_m.
Referenced by clone(), parse_detail(), and Rectangle().
Rectangle() [2/2]
mslang::Rectangle::Rectangle (const Rectangle & right) inline
Definition at line 13 of file Rectangle.h.
References mslang::Base::Base(), height_m, Rectangle(), and width_m.
~Rectangle()
virtual mslang::Rectangle::~Rectangle () inline virtual
Definition at line 16 of file Rectangle.h.
Member Function Documentation
apply()
void mslang::Rectangle::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Implements mslang::Function.
Definition at line 94 of file Rectangle.cpp.
References clone().
clone()
std::shared_ptr< Base > mslang::Rectangle::clone () const virtual
Implements mslang::Base.
Definition at line 98 of file Rectangle.cpp.
References mslang::Base::bb_m, mslang::Base::divisor_m, height_m, Rectangle(), mslang::Base::trafo_m, and width_m.
Referenced by apply().
computeBoundingBox()
void mslang::Rectangle::computeBoundingBox () virtual
Implements mslang::Base.
Definition at line 27 of file Rectangle.cpp.
References mslang::Base::bb_m, mslang::Base::divisor_m, height_m, mslang::Base::trafo_m, and width_m.
divideBy()
virtual void mslang::Base::divideBy (std::vector< std::shared_ptr< Base > > & divisors) inline virtual inherited
Definition at line 57 of file MSLang.h.
References bb_m, and divisor_m.
isInside()
bool mslang::Rectangle::isInside (const Vector_t< double, 3 > & R) const virtual
Implements mslang::Base.
Definition at line 58 of file Rectangle.cpp.
References mslang::Base::bb_m, mslang::Base::divisor_m, height_m, mslang::Base::trafo_m, and width_m.
parse()
bool mslang::Function::parse (iterator & it, const iterator & end, Function *& fun) static inherited
Definition at line 47 of file MSLang.cpp.
References FCall, mslang::Difference::parse_detail(), mslang::Ellipse::parse_detail(), mslang::Intersection::parse_detail(), mslang::Mask::parse_detail(), mslang::Polygon::parse_detail(), mslang::Rectangle::parse_detail(), mslang::Repeat::parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), and mslang::Union::parse_detail().
Referenced by mslang::parse(), mslang::Difference::parse_detail(), mslang::Intersection::parse_detail(), mslang::Repeat::parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), and mslang::Union::parse_detail().
parse_detail()
bool mslang::Rectangle::parse_detail (iterator & it, const iterator & end, Function * fun) static
Definition at line 112 of file Rectangle.cpp.
References mslang::ArgumentExtractor::get(), mslang::ArgumentExtractor::getLengthConsumed(), height_m, mslang::parseMathExpression(), Rectangle(), mslang::Function::UDouble, and width_m.
Referenced by mslang::Function::parse().
print()
void mslang::Rectangle::print (int indentwidth) virtual
Implements mslang::Function.
Definition at line 9 of file Rectangle.cpp.
References height_m, Units::rad2deg, mslang::Base::trafo_m, and width_m.
writeGnuplot()
void mslang::Rectangle::writeGnuplot (std::ofstream & out) const virtual
Implements mslang::Base.
Definition at line 72 of file Rectangle.cpp.
References mslang::Base::divisor_m, height_m, mslang::Base::trafo_m, and width_m.
Member Data Documentation
bb_m
BoundingBox2D mslang::Base::bb_m inherited
Definition at line 39 of file MSLang.h.
Referenced by Base(), mslang::Ellipse::clone(), mslang::Rectangle::clone(), mslang::Triangle::clone(), mslang::Ellipse::computeBoundingBox(), mslang::Rectangle::computeBoundingBox(), mslang::Triangle::computeBoundingBox(), divideBy(), mslang::Ellipse::isInside(), and mslang::Rectangle::isInside().
divisor_m
std::vector<std::shared_ptr<Base> > mslang::Base::divisor_m inherited
Definition at line 40 of file MSLang.h.
Referenced by mslang::Ellipse::clone(), mslang::Rectangle::clone(), mslang::Triangle::clone(), mslang::Ellipse::computeBoundingBox(), mslang::Rectangle::computeBoundingBox(), mslang::Triangle::computeBoundingBox(), divideBy(), mslang::Ellipse::isInside(), mslang::Rectangle::isInside(), mslang::Triangle::isInside(), mslang::Ellipse::writeGnuplot(), mslang::Rectangle::writeGnuplot(), mslang::Triangle::writeGnuplot(), and ~Base().
Double
const std::string mslang::Function::Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 32 of file MSLang.h.
FCall
const std::string mslang::Function::FCall = "([a-z_]*)\\‍((.*)" static inherited
Definition at line 34 of file MSLang.h.
Referenced by parse().
height_m
double mslang::Rectangle::height_m
Definition at line 9 of file Rectangle.h.
Referenced by clone(), computeBoundingBox(), isInside(), mslang::Mask::parse_detail(), parse_detail(), print(), Rectangle(), Rectangle(), and writeGnuplot().
trafo_m
AffineTransformation mslang::Base::trafo_m inherited
Definition at line 38 of file MSLang.h.
Referenced by Base(), Base(), mslang::Ellipse::clone(), mslang::Rectangle::clone(), mslang::Triangle::clone(), mslang::Ellipse::computeBoundingBox(), mslang::Rectangle::computeBoundingBox(), mslang::Triangle::computeBoundingBox(), mslang::Ellipse::isInside(), mslang::Rectangle::isInside(), mslang::Triangle::isInside(), mslang::Mask::parse_detail(), mslang::Ellipse::print(), mslang::Rectangle::print(), mslang::Triangle::print(), mslang::Ellipse::writeGnuplot(), mslang::Rectangle::writeGnuplot(), and mslang::Triangle::writeGnuplot().
UDouble
const std::string mslang::Function::UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 31 of file MSLang.h.
Referenced by mslang::Rectangle::parse_detail().
UInt
const std::string mslang::Function::UInt = "([0-9]+)" static inherited
Definition at line 33 of file MSLang.h.
width_m
double mslang::Rectangle::width_m
Definition at line 8 of file Rectangle.h.
Referenced by clone(), computeBoundingBox(), isInside(), mslang::Mask::parse_detail(), parse_detail(), print(), Rectangle(), Rectangle(), and writeGnuplot().
The documentation for this struct was generated from the following files:
Rectangle.h
Rectangle.cpp