OPALX (Object Oriented Parallel Accelerator Library for Exascal): ParticleBinning::ArrayReduction< SizeType, IndexType, N > Struct Template Reference
ParticleBinning::ArrayReduction< SizeType, IndexType, N > Struct Template Reference
A templated structure for performing array-based reductions in parallel computations.
#include <ParallelReduceTools.h>
Public Member Functions
KOKKOS_INLINE_FUNCTION ArrayReduction ()
KOKKOS_INLINE_FUNCTION ArrayReduction (const ArrayReduction &rhs)
KOKKOS_INLINE_FUNCTION ArrayReduction & operator= (const ArrayReduction &rhs)
KOKKOS_INLINE_FUNCTION ArrayReduction & operator+= (const ArrayReduction &src)
Public Attributes
SizeType the_array [N]
Detailed Description
template<typename SizeType, typename IndexType, IndexType N>
struct ParticleBinning::ArrayReduction< SizeType, IndexType, N >
A templated structure for performing array-based reductions in parallel computations.
Template Parameters
SizeType The type used for the elements of the array.
IndexType The type used for indexing the array.
N The fixed size of the array.
This structure provides functionality to initialize, copy, assign, and perform element-wise addition on arrays of fixed size. It is designed to be used in parallel reduction operations with Kokkos.
Member Functions:
ArrayReduction(): Default constructor that initializes all elements of the array to zero.
ArrayReduction(const ArrayReduction& rhs): Copy constructor that performs a deep copy of the array.
ArrayReduction& operator=(const ArrayReduction& rhs): Assignment operator that performs a deep copy of the array.
ArrayReduction& operator+=(const ArrayReduction& src): Element-wise addition operator that adds the elements of another ArrayReduction instance to the current instance.
Definition at line 39 of file ParallelReduceTools.h.
Constructor & Destructor Documentation
ArrayReduction() [1/2]
template<typename SizeType, typename IndexType, IndexType N> KOKKOS_INLINE_FUNCTION ParticleBinning::ArrayReduction< SizeType, IndexType, N >::ArrayReduction () inline
Definition at line 43 of file ParallelReduceTools.h.
References the_array.
Referenced by ArrayReduction(), operator+=(), and operator=().
ArrayReduction() [2/2]
template<typename SizeType, typename IndexType, IndexType N> KOKKOS_INLINE_FUNCTION ParticleBinning::ArrayReduction< SizeType, IndexType, N >::ArrayReduction (const ArrayReduction< SizeType, IndexType, N > & rhs) inline
Definition at line 49 of file ParallelReduceTools.h.
References ArrayReduction(), and the_array.
Member Function Documentation
operator+=()
template<typename SizeType, typename IndexType, IndexType N> KOKKOS_INLINE_FUNCTION ArrayReduction & ParticleBinning::ArrayReduction< SizeType, IndexType, N >::operator+= (const ArrayReduction< SizeType, IndexType, N > & src) inline
Definition at line 64 of file ParallelReduceTools.h.
References ArrayReduction(), and the_array.
operator=()
template<typename SizeType, typename IndexType, IndexType N> KOKKOS_INLINE_FUNCTION ArrayReduction & ParticleBinning::ArrayReduction< SizeType, IndexType, N >::operator= (const ArrayReduction< SizeType, IndexType, N > & rhs) inline
Definition at line 55 of file ParallelReduceTools.h.
References ArrayReduction(), and the_array.
Member Data Documentation
the_array
template<typename SizeType, typename IndexType, IndexType N> SizeType ParticleBinning::ArrayReduction< SizeType, IndexType, N >::the_array[N]
Definition at line 40 of file ParallelReduceTools.h.
Referenced by ArrayReduction(), ArrayReduction(), operator+=(), operator=(), TEST_F(), TEST_F(), and TEST_F().
The documentation for this struct was generated from the following file:
ParallelReduceTools.h