OPALX (Object Oriented Parallel Accelerator Library for Exascal): mslang::Translation Struct Reference
mslang::Translation Struct Reference
#include <Translation.h>
Public Member Functions
virtual ~Translation ()
virtual void print (int indentwidth)
void applyTranslation (std::vector< std::shared_ptr< Base > > &bfuncs)
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *&fun)
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
Function * func_m
double shiftx_m
double shifty_m
Static Public Attributes
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\‍((.*)"
Detailed Description
Definition at line 7 of file Translation.h.
Constructor & Destructor Documentation
~Translation()
virtual mslang::Translation::~Translation () inline virtual
Definition at line 12 of file Translation.h.
References func_m.
Member Function Documentation
apply()
void mslang::Translation::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Implements mslang::Function.
Definition at line 34 of file Translation.cpp.
References mslang::Function::apply(), applyTranslation(), and func_m.
applyTranslation()
void mslang::Translation::applyTranslation (std::vector< std::shared_ptr< Base > > & bfuncs)
Definition at line 20 of file Translation.cpp.
References applyTranslation(), shiftx_m, and shifty_m.
Referenced by apply(), and applyTranslation().
parse()
bool mslang::Function::parse (iterator & it, const iterator & end, Function *& fun) static inherited
Definition at line 47 of file MSLang.cpp.
References mslang::Function::FCall, mslang::Difference::parse_detail(), mslang::Intersection::parse_detail(), mslang::Mask::parse_detail(), mslang::Polygon::parse_detail(), mslang::Repeat::parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), parse_detail(), mslang::Union::parse_detail(), mslang::Ellipse::parse_detail(), and mslang::Rectangle::parse_detail().
Referenced by mslang::parse(), mslang::Difference::parse_detail(), mslang::Intersection::parse_detail(), mslang::Repeat::parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), parse_detail(), and mslang::Union::parse_detail().
parse_detail()
bool mslang::Translation::parse_detail (iterator & it, const iterator & end, Function *& fun) static
Definition at line 39 of file Translation.cpp.
References func_m, mslang::ArgumentExtractor::get(), mslang::ArgumentExtractor::getLengthConsumed(), mslang::Function::parse(), mslang::parseMathExpression(), shiftx_m, and shifty_m.
Referenced by mslang::Function::parse().
print()
void mslang::Translation::print (int indentwidth) virtual
Implements mslang::Function.
Definition at line 10 of file Translation.cpp.
References func_m, mslang::Function::print(), shiftx_m, and shifty_m.
Member Data Documentation
Double
const std::string mslang::Function::Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 34 of file MSLang.h.
FCall
const std::string mslang::Function::FCall = "([a-z_]*)\\‍((.*)" static inherited
Definition at line 36 of file MSLang.h.
Referenced by mslang::Function::parse().
func_m
Function* mslang::Translation::func_m
Definition at line 8 of file Translation.h.
Referenced by apply(), parse_detail(), print(), and ~Translation().
shiftx_m
double mslang::Translation::shiftx_m
Definition at line 9 of file Translation.h.
Referenced by applyTranslation(), parse_detail(), and print().
shifty_m
double mslang::Translation::shifty_m
Definition at line 10 of file Translation.h.
Referenced by applyTranslation(), parse_detail(), and print().
UDouble
const std::string mslang::Function::UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 33 of file MSLang.h.
Referenced by mslang::Rectangle::parse_detail().
UInt
const std::string mslang::Function::UInt = "([0-9]+)" static inherited
Definition at line 35 of file MSLang.h.
The documentation for this struct was generated from the following files:
Translation.h
Translation.cpp