OPALX (Object Oriented Parallel Accelerator Library for Exascal): mslang::Polygon Struct Reference
mslang::Polygon Struct Reference
#include <Polygon.h>
Public Member Functions
void triangulize (std::vector< Vector_t< double, 3 > > &nodes)
virtual void print (int ident)
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *&fun)
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
std::vector< Triangle > triangles_m
Static Public Attributes
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\‍((.*)"
Detailed Description
Definition at line 8 of file Polygon.h.
Member Function Documentation
apply()
void mslang::Polygon::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Implements mslang::Function.
Definition at line 44 of file Polygon.cpp.
References triangles_m.
parse()
bool mslang::Function::parse (iterator & it, const iterator & end, Function *& fun) static inherited
Definition at line 47 of file MSLang.cpp.
References mslang::Function::FCall, mslang::Difference::parse_detail(), mslang::Intersection::parse_detail(), mslang::Mask::parse_detail(), parse_detail(), mslang::Repeat::parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), mslang::Union::parse_detail(), mslang::Ellipse::parse_detail(), and mslang::Rectangle::parse_detail().
Referenced by mslang::parse(), mslang::Difference::parse_detail(), mslang::Intersection::parse_detail(), mslang::Repeat::parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Translation::parse_detail(), and mslang::Union::parse_detail().
parse_detail()
bool mslang::Polygon::parse_detail (iterator & it, const iterator & end, Function *& fun) static
Definition at line 15 of file Polygon.cpp.
References mslang::ArgumentExtractor::get(), mslang::ArgumentExtractor::getLengthConsumed(), mslang::ArgumentExtractor::getNumArguments(), mslang::parseMathExpression(), and triangulize().
Referenced by mslang::Function::parse().
print()
void mslang::Polygon::print (int ident) virtual
Implements mslang::Function.
Definition at line 40 of file Polygon.cpp.
triangulize()
void mslang::Polygon::triangulize (std::vector< Vector_t< double, 3 > > & nodes)
Definition at line 10 of file Polygon.cpp.
References Mesher::getTriangles(), and triangles_m.
Referenced by parse_detail().
Member Data Documentation
Double
const std::string mslang::Function::Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 34 of file MSLang.h.
FCall
const std::string mslang::Function::FCall = "([a-z_]*)\\‍((.*)" static inherited
Definition at line 36 of file MSLang.h.
Referenced by mslang::Function::parse().
triangles_m
std::vector<Triangle> mslang::Polygon::triangles_m
Definition at line 9 of file Polygon.h.
Referenced by apply(), and triangulize().
UDouble
const std::string mslang::Function::UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static inherited
Definition at line 33 of file MSLang.h.
Referenced by mslang::Rectangle::parse_detail().
UInt
const std::string mslang::Function::UInt = "([0-9]+)" static inherited
Definition at line 35 of file MSLang.h.
The documentation for this struct was generated from the following files:
Polygon.h
Polygon.cpp