OPALX (Object Oriented Parallel Accelerator Library for Exascal): CastsTrait< ELEM1, ELEM2 > Struct Template Reference
CastsTrait< ELEM1, ELEM2 > Struct Template Reference
#include <SpecificElementVisitor.h>
Public Types
typedef std::list< const ELEM1 * > ElementList_t
Static Public Member Functions
static void apply (ElementList_t &, const ELEM2 &)
Detailed Description
template<class ELEM1, class ELEM2>
struct CastsTrait< ELEM1, ELEM2 >
Definition at line 65 of file SpecificElementVisitor.h.
Member Typedef Documentation
ElementList_t
template<class ELEM1 , class ELEM2 > typedef std::list<const ELEM1*> CastsTrait< ELEM1, ELEM2 >::ElementList_t
Definition at line 66 of file SpecificElementVisitor.h.
Member Function Documentation
apply()
template<class ELEM1 , class ELEM2 > static void CastsTrait< ELEM1, ELEM2 >::apply (ElementList_t & , const ELEM2 &) inline static
Definition at line 68 of file SpecificElementVisitor.h.
Referenced by SpecificElementVisitor< ELEM >::visitCCollimator(), SpecificElementVisitor< ELEM >::visitComponent(), SpecificElementVisitor< ELEM >::visitConstantEFieldCavity(), SpecificElementVisitor< ELEM >::visitCorrector(), SpecificElementVisitor< ELEM >::visitCyclotron(), SpecificElementVisitor< ELEM >::visitDegrader(), SpecificElementVisitor< ELEM >::visitDrift(), SpecificElementVisitor< ELEM >::visitFlexibleCollimator(), SpecificElementVisitor< ELEM >::visitLaser(), SpecificElementVisitor< ELEM >::visitMarker(), SpecificElementVisitor< ELEM >::visitMonitor(), SpecificElementVisitor< ELEM >::visitMultipole(), SpecificElementVisitor< ELEM >::visitMultipoleT(), SpecificElementVisitor< ELEM >::visitMultipoleTCurvedConstRadius(), SpecificElementVisitor< ELEM >::visitMultipoleTCurvedVarRadius(), SpecificElementVisitor< ELEM >::visitMultipoleTStraight(), SpecificElementVisitor< ELEM >::visitProbe(), SpecificElementVisitor< ELEM >::visitRBend(), SpecificElementVisitor< ELEM >::visitRBend3D(), SpecificElementVisitor< ELEM >::visitRFCavity(), SpecificElementVisitor< ELEM >::visitRing(), SpecificElementVisitor< ELEM >::visitSBend(), SpecificElementVisitor< ELEM >::visitSBend3D(), SpecificElementVisitor< ELEM >::visitScalingFFAMagnet(), SpecificElementVisitor< ELEM >::visitSeptum(), SpecificElementVisitor< ELEM >::visitSolenoid(), SpecificElementVisitor< ELEM >::visitSource(), SpecificElementVisitor< ELEM >::visitStripper(), SpecificElementVisitor< ELEM >::visitTravelingWave(), SpecificElementVisitor< ELEM >::visitVacuum(), SpecificElementVisitor< ELEM >::visitVariableRFCavity(), SpecificElementVisitor< ELEM >::visitVariableRFCavityFringeField(), and SpecificElementVisitor< ELEM >::visitVerticalFFAMagnet().
The documentation for this struct was generated from the following file:
SpecificElementVisitor.h