OPALX (Object Oriented Parallel Accelerator Library for Exascal): SDDS::error_handler< Iterator > Struct Template Reference
SDDS::error_handler< Iterator > Struct Template Reference
#include <error_handler.hpp>
Classes
struct result
Public Member Functions
error_handler (Iterator first, Iterator last)
template<typename Message , typename What >
void operator() (Message const &message, What const &what, Iterator err_pos) const
Iterator get_pos (Iterator err_pos, int &line) const
std::string get_line (Iterator err_pos) const
Public Attributes
Iterator first
Iterator last
std::vector< Iterator > iters
Detailed Description
template<typename Iterator>
struct SDDS::error_handler< Iterator >
Definition at line 29 of file error_handler.hpp.
Class Documentation
SDDS::error_handler::result
struct SDDS::error_handler::result
template<typename Iterator>
template<typename, typename, typename>
struct SDDS::error_handler< Iterator >::result< typename, typename, typename >
Definition at line 31 of file error_handler.hpp.
Class Members
typedef void type
Constructor & Destructor Documentation
error_handler()
template<typename Iterator > SDDS::error_handler< Iterator >::error_handler (Iterator first, Iterator last) inline
Definition at line 35 of file error_handler.hpp.
Member Function Documentation
get_line()
template<typename Iterator > std::string SDDS::error_handler< Iterator >::get_line (Iterator err_pos) const inline
Definition at line 77 of file error_handler.hpp.
References SDDS::error_handler< Iterator >::last.
Referenced by SDDS::error_handler< Iterator >::operator()().
get_pos()
template<typename Iterator > Iterator SDDS::error_handler< Iterator >::get_pos (Iterator err_pos, int & line) const inline
Definition at line 53 of file error_handler.hpp.
References SDDS::error_handler< Iterator >::first.
Referenced by SDDS::error_handler< Iterator >::operator()().
operator()()
template<typename Iterator > template<typename Message , typename What > void SDDS::error_handler< Iterator >::operator() (Message const & message, What const & what, Iterator err_pos) const inline
Definition at line 38 of file error_handler.hpp.
References SDDS::error_handler< Iterator >::get_line(), SDDS::error_handler< Iterator >::get_pos(), and SDDS::error_handler< Iterator >::last.
Member Data Documentation
first
template<typename Iterator > Iterator SDDS::error_handler< Iterator >::first
Definition at line 85 of file error_handler.hpp.
Referenced by SDDS::error_handler< Iterator >::get_pos().
iters
template<typename Iterator > std::vector<Iterator> SDDS::error_handler< Iterator >::iters
Definition at line 87 of file error_handler.hpp.
last
template<typename Iterator > Iterator SDDS::error_handler< Iterator >::last
Definition at line 86 of file error_handler.hpp.
Referenced by SDDS::error_handler< Iterator >::get_line(), and SDDS::error_handler< Iterator >::operator()().
The documentation for this struct was generated from the following file:
error_handler.hpp