OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestDistributionMoments.cpp File Reference
TestDistributionMoments.cpp File Reference
#include <gtest/gtest.h>
#include <cmath>
#include <vector>
#include "Algorithms/DistributionMoments.h"
#include "Ippl.h"
#include "PartBunch/BunchStateHandler.h"
#include "Physics/Physics.h"
#include "Physics/Units.h"
Classes
class DistributionMomentsTest
Functions
TEST_F (DistributionMomentsTest, ComputeMoments_MeanStdEmittanceEnergyDispersion)
Function Documentation
TEST_F()
TEST_F (DistributionMomentsTest , ComputeMoments_MeanStdEmittanceEnergyDispersion)
Definition at line 134 of file TestDistributionMoments.cpp.
References DistributionMoments::computeMoments(), DistributionMoments::getDDx(), DistributionMoments::getDDy(), DistributionMoments::getDx(), DistributionMoments::getDy(), DistributionMoments::getGeometricEmittance(), DistributionMoments::getMeanGamma(), DistributionMoments::getMeanGammaZ(), DistributionMoments::getMeanKineticEnergy(), DistributionMoments::getMeanMomentum(), DistributionMoments::getMeanPosition(), DistributionMoments::getNormalizedEmittance(), DistributionMoments::getStandardDeviationMomentum(), DistributionMoments::getStandardDeviationPosition(), DistributionMoments::getStdKineticEnergy(), Physics::m_e, and DistributionMoments::setContainerState().