OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestMultipoleT.cpp File Reference
TestMultipoleT.cpp File Reference
#include <csignal>
#include "AbstractObjects/OpalData.h"
#include "AbsBeamline/BeamlineVisitor.h"
#include "AbsBeamline/MultipoleT.h"
#include "Algorithms/SplineTimeDependence.h"
#include "Attributes/Attributes.h"
#include "Structure/Beam.h"
#include "Structure/DataSink.h"
#include "Structure/FieldSolverCmd.h"
#include "Utilities/OpalException.h"
#include "Utilities/Options.h"
#include "Utility/Inform.h"
#include "gtest/gtest.h"
Classes
class TestMultipoleT
class TestMultipoleT::TestableFieldSolverCmd
Functions
TEST_F (TestMultipoleT, Cloning)
TEST_F (TestMultipoleT, TimeDependency)
TEST_F (TestMultipoleT, Bends)
TEST_F (TestMultipoleT, ConfigurationValidation)
TEST_F (TestMultipoleT, OddApis)
TEST_F (TestMultipoleT, ApplySingleParticleThrowsForMultiContainerBunch)
Function Documentation
TEST_F() [1/6]
TEST_F (TestMultipoleT , ApplySingleParticleThrowsForMultiContainerBunch)
Definition at line 213 of file TestMultipoleT.cpp.
References Beam::find().
TEST_F() [2/6]
TEST_F (TestMultipoleT , Bends)
Definition at line 178 of file TestMultipoleT.cpp.
TEST_F() [3/6]
TEST_F (TestMultipoleT , Cloning)
Definition at line 111 of file TestMultipoleT.cpp.
TEST_F() [4/6]
TEST_F (TestMultipoleT , ConfigurationValidation)
Definition at line 186 of file TestMultipoleT.cpp.
TEST_F() [5/6]
TEST_F (TestMultipoleT , OddApis)
Definition at line 199 of file TestMultipoleT.cpp.
References MultipoleT::getField().
TEST_F() [6/6]
TEST_F (TestMultipoleT , TimeDependency)
Definition at line 146 of file TestMultipoleT.cpp.
References AbstractTimeDependence::setTimeDependence().