OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestOpalSinusoidalTimeDependence.cpp File Reference
TestOpalSinusoidalTimeDependence.cpp File Reference
#include <sstream>
#include "Algorithms/SinusoidalTimeDependence.h"
#include "Attributes/Attributes.h"
#include "Elements/OpalSinusoidalTimeDependence.h"
#include "gtest/gtest.h"
Functions
TEST (TestOpalSinusoidalTimeDependence, UserInterface)
TEST (TestOpalSinusoidalTimeDependence, ConstructorTest)
TEST (TestOpalSinusoidalTimeDependence, PrintTest)
Function Documentation
TEST() [1/3]
TEST (TestOpalSinusoidalTimeDependence , ConstructorTest)
Definition at line 42 of file TestOpalSinusoidalTimeDependence.cpp.
References OpalSinusoidalTimeDependence::clone(), and Object::getOpalName().
TEST() [2/3]
TEST (TestOpalSinusoidalTimeDependence , PrintTest)
Definition at line 48 of file TestOpalSinusoidalTimeDependence.cpp.
References OpalSinusoidalTimeDependence::print().
TEST() [3/3]
TEST (TestOpalSinusoidalTimeDependence , UserInterface)
Definition at line 22 of file TestOpalSinusoidalTimeDependence.cpp.
References OpalSinusoidalTimeDependence::AMPLITUDES, OpalSinusoidalTimeDependence::DC_OFFSETS, OpalSinusoidalTimeDependence::FREQUENCIES, AbstractTimeDependence::getTimeDependence(), Object::itsAttr, OpalSinusoidalTimeDependence::PHASE_OFFSETS, Attributes::setRealArray(), and OpalSinusoidalTimeDependence::update().