OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestPolynomialTimeDependence.cpp File Reference
TestPolynomialTimeDependence.cpp File Reference
#include "Algorithms/PolynomialTimeDependence.h"
#include "Attributes/Attributes.h"
#include "Ippl.h"
#include "Utilities/GeneralOpalException.h"
#include "gtest/gtest.h"
Functions
TEST (TestPolynomialTimeDependence, PolynomialTimeDependenceTest)
TEST (TestPolynomialTimeDependence, TDMapTest)
TEST (TestPolynomialTimeDependence, TDMapNameLookupTest)
TEST (TestPolynomialTimeDependence, Integral)
TEST (TestPolynomialTimeDependence, Print)
Function Documentation
TEST() [1/5]
TEST (TestPolynomialTimeDependence , Integral)
Definition at line 80 of file TestPolynomialTimeDependence.cpp.
TEST() [2/5]
TEST (TestPolynomialTimeDependence , PolynomialTimeDependenceTest)
Definition at line 22 of file TestPolynomialTimeDependence.cpp.
References PolynomialTimeDependence::clone(), and PolynomialTimeDependence::getValue().
TEST() [3/5]
TEST (TestPolynomialTimeDependence , Print)
Definition at line 94 of file TestPolynomialTimeDependence.cpp.
TEST() [4/5]
TEST (TestPolynomialTimeDependence , TDMapNameLookupTest)
Definition at line 64 of file TestPolynomialTimeDependence.cpp.
References PolynomialTimeDependence::clone(), AbstractTimeDependence::getName(), and AbstractTimeDependence::setTimeDependence().
TEST() [5/5]
TEST (TestPolynomialTimeDependence , TDMapTest)
Definition at line 45 of file TestPolynomialTimeDependence.cpp.
References AbstractTimeDependence::getTimeDependence(), and AbstractTimeDependence::setTimeDependence().