OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestAstra1DDynamic.cpp File Reference
TestAstra1DDynamic.cpp File Reference
Unit tests for Astra1DDynamic fieldmap class.
#include <gtest/gtest.h>
#include "Fields/Astra1DDynamic.h"
#include "Fields/Fieldmap.h"
#include "PartBunch/PartBunch.h"
#include "Physics/Physics.h"
#include "Physics/Units.h"
#include "Utilities/GeneralOpalException.h"
#include "Ippl.h"
#include <cmath>
#include <filesystem>
#include <fstream>
#include <vector>
#include <iomanip>
#include <string>
Classes
class Astra1DDynamicTest
Functions
TEST_F (Astra1DDynamicTest, ParseAndDimensions)
TEST_F (Astra1DDynamicTest, FrequencyParsing)
TEST_F (Astra1DDynamicTest, IsInside)
TEST_F (Astra1DDynamicTest, UniformFieldStrengthOnAxis)
TEST_F (Astra1DDynamicTest, NoNormalization)
TEST_F (Astra1DDynamicTest, OutsideZRange)
TEST_F (Astra1DDynamicTest, FieldAccumulation)
TEST_F (Astra1DDynamicTest, FieldDerivativeConstantField)
TEST_F (Astra1DDynamicTest, GetOnaxisEzReturnsNormalizedRawProfile)
TEST_F (Astra1DDynamicTest, ComputeFieldStaticConstantCoefficient)
TEST_F (Astra1DDynamicTest, SwapNoCrash)
TEST_F (Astra1DDynamicTest, GetInfoNoCrash)
TEST_F (Astra1DDynamicTest, MissingFile)
TEST_F (Astra1DDynamicTest, DictionaryCaching)
TEST_F (Astra1DDynamicTest, ReadFreeCycle)
TEST_F (Astra1DDynamicTest, ComputeTravelingWaveFieldEntryRegion)
TEST_F (Astra1DDynamicTest, ComputeTravelingWaveFieldCoreRegion)
TEST_F (Astra1DDynamicTest, ComputeTravelingWaveFieldExitRegion)
TEST_F (Astra1DDynamicTest, ComputeTravelingWaveFieldOutsideRange)
Detailed Description
Unit tests for Astra1DDynamic fieldmap class.
Tests cover:
Parsing & metadata:
File parsing
Frequency parsing and conversion (MHz -> angular frequency)
Field dimension retrieval (z-bounds)
Field evaluation:
Point field evaluation via getFieldstrength()
Uniform on-axis field correctness
Static computeField() correctness for simple coefficients
Reconstructed on-axis field via getOnaxisEz()
Device-safe traveling-wave application via applyTravelingWave()
Geometry & bounds:
Behaviour outside z-range
isInside() helper (boundary semantics)
API behaviour:
getFieldDerivative() for simple constant field
getFrequency() correctness
getInfo() does not crash
swap() does not crash
Robustness:
Missing / invalid file handling
Fieldmap dictionary caching
readMap() / freeMap() lifecycle correctness
Semantics:
Field accumulation: E and B are accumulated, not overwritten
Notes:
The current Astra1DDynamic preprocessing / Fourier reconstruction yields an amplitude factor of (nz - 1) / nz for uniform input fields. The tests reflect the current implementation behaviour.
Definition in file TestAstra1DDynamic.cpp.
Function Documentation
TEST_F() [1/19]
TEST_F (Astra1DDynamicTest , ComputeFieldStaticConstantCoefficient)
Definition at line 421 of file TestAstra1DDynamic.cpp.
TEST_F() [2/19]
TEST_F (Astra1DDynamicTest , ComputeTravelingWaveFieldCoreRegion)
Definition at line 566 of file TestAstra1DDynamic.cpp.
TEST_F() [3/19]
TEST_F (Astra1DDynamicTest , ComputeTravelingWaveFieldEntryRegion)
Definition at line 530 of file TestAstra1DDynamic.cpp.
TEST_F() [4/19]
TEST_F (Astra1DDynamicTest , ComputeTravelingWaveFieldExitRegion)
Definition at line 611 of file TestAstra1DDynamic.cpp.
TEST_F() [5/19]
TEST_F (Astra1DDynamicTest , ComputeTravelingWaveFieldOutsideRange)
Definition at line 655 of file TestAstra1DDynamic.cpp.
TEST_F() [6/19]
TEST_F (Astra1DDynamicTest , DictionaryCaching)
Definition at line 488 of file TestAstra1DDynamic.cpp.
TEST_F() [7/19]
TEST_F (Astra1DDynamicTest , FieldAccumulation)
Definition at line 325 of file TestAstra1DDynamic.cpp.
References Fieldmap::getFieldstrength().
TEST_F() [8/19]
TEST_F (Astra1DDynamicTest , FieldDerivativeConstantField)
Definition at line 357 of file TestAstra1DDynamic.cpp.
References DZ.
TEST_F() [9/19]
TEST_F (Astra1DDynamicTest , FrequencyParsing)
Definition at line 181 of file TestAstra1DDynamic.cpp.
References Units::MHz2Hz, and Physics::two_pi.
TEST_F() [10/19]
TEST_F (Astra1DDynamicTest , GetInfoNoCrash)
Definition at line 466 of file TestAstra1DDynamic.cpp.
References Fieldmap::getInfo().
TEST_F() [11/19]
TEST_F (Astra1DDynamicTest , GetOnaxisEzReturnsNormalizedRawProfile)
Definition at line 380 of file TestAstra1DDynamic.cpp.
TEST_F() [12/19]
TEST_F (Astra1DDynamicTest , IsInside)
Definition at line 199 of file TestAstra1DDynamic.cpp.
TEST_F() [13/19]
TEST_F (Astra1DDynamicTest , MissingFile)
Definition at line 480 of file TestAstra1DDynamic.cpp.
TEST_F() [14/19]
TEST_F (Astra1DDynamicTest , NoNormalization)
Definition at line 254 of file TestAstra1DDynamic.cpp.
References Fieldmap::getFieldstrength().
TEST_F() [15/19]
TEST_F (Astra1DDynamicTest , OutsideZRange)
Definition at line 280 of file TestAstra1DDynamic.cpp.
References Fieldmap::getFieldstrength().
TEST_F() [16/19]
TEST_F (Astra1DDynamicTest , ParseAndDimensions)
Definition at line 155 of file TestAstra1DDynamic.cpp.
References Fieldmap::getFieldDimensions(), Fieldmap::getType(), and TAstraDynamic.
TEST_F() [17/19]
TEST_F (Astra1DDynamicTest , ReadFreeCycle)
Definition at line 501 of file TestAstra1DDynamic.cpp.
References Fieldmap::freeMap(), Fieldmap::getFieldstrength(), and Fieldmap::readMap().
TEST_F() [18/19]
TEST_F (Astra1DDynamicTest , SwapNoCrash)
Definition at line 453 of file TestAstra1DDynamic.cpp.
TEST_F() [19/19]
TEST_F (Astra1DDynamicTest , UniformFieldStrengthOnAxis)
Definition at line 215 of file TestAstra1DDynamic.cpp.
References Fieldmap::getFieldstrength().