OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestSplineTimeDependence.cpp File Reference
TestSplineTimeDependence.cpp File Reference
#include "Algorithms/SplineTimeDependence.h"
#include "Utilities/GeneralOpalException.h"
#include "Utilities/OpalException.h"
#include "gtest/gtest.h"
Classes
class TestSplineTimeDependence
Functions
TEST_F (TestSplineTimeDependence, ConstructorTest)
TEST_F (TestSplineTimeDependence, LinearLookupTest)
TEST_F (TestSplineTimeDependence, CubicLookupTest)
TEST_F (TestSplineTimeDependence, Integral)
TEST_F (TestSplineTimeDependence, Print)
Function Documentation
TEST_F() [1/5]
TEST_F (TestSplineTimeDependence , ConstructorTest)
Definition at line 34 of file TestSplineTimeDependence.cpp.
References SplineTimeDependence::clone(), SplineTimeDependence::getValue(), OpalException::what(), and OpalException::where().
TEST_F() [2/5]
TEST_F (TestSplineTimeDependence , CubicLookupTest)
Definition at line 85 of file TestSplineTimeDependence.cpp.
References SplineTimeDependence::getValue().
TEST_F() [3/5]
TEST_F (TestSplineTimeDependence , Integral)
Definition at line 97 of file TestSplineTimeDependence.cpp.
References SplineTimeDependence::getIntegral().
TEST_F() [4/5]
TEST_F (TestSplineTimeDependence , LinearLookupTest)
Definition at line 72 of file TestSplineTimeDependence.cpp.
References SplineTimeDependence::getIntegral(), and SplineTimeDependence::getValue().
TEST_F() [5/5]
TEST_F (TestSplineTimeDependence , Print)
Definition at line 105 of file TestSplineTimeDependence.cpp.