OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestOpalVariableRFCavity.cpp File Reference
TestOpalVariableRFCavity.cpp File Reference
#include "AbsBeamline/VariableRFCavity.h"
#include "Algorithms/PolynomialTimeDependence.h"
#include "Attributes/Attributes.h"
#include "Elements/OpalVariableRFCavity.h"
#include "Structure/DataSink.h"
#include "gtest/gtest.h"
Classes
class TestOpalVariableRFCavity
Functions
TEST_F (TestOpalVariableRFCavity, ConstructorDestructor)
TEST_F (TestOpalVariableRFCavity, UserInterface)
Function Documentation
TEST_F() [1/2]
TEST_F (TestOpalVariableRFCavity , ConstructorDestructor)
Definition at line 43 of file TestOpalVariableRFCavity.cpp.
References OpalVariableRFCavity::clone(), and Object::getOpalName().
TEST_F() [2/2]
TEST_F (TestOpalVariableRFCavity , UserInterface)
Definition at line 54 of file TestOpalVariableRFCavity.cpp.
References OpalVariableRFCavity::AMPLITUDE_MODEL, OpalVariableRFCavity::FREQUENCY_MODEL, Element::getElement(), OpalVariableRFCavity::HEIGHT, Object::itsAttr, OpalElement::LENGTH, OpalVariableRFCavity::PHASE_MODEL, Attributes::setReal(), AbstractTimeDependence::setTimeDependence(), Attributes::setUpperCaseString(), OpalVariableRFCavity::update(), and OpalVariableRFCavity::WIDTH.