OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestOpalException.cpp File Reference
TestOpalException.cpp File Reference
#include "Utilities/DomainError.h"
#include "Utilities/GeneralOpalException.h"
#include "Utilities/OpalException.h"
#include "Utilities/ParseError.h"
#include "Utilities/SDDSParser/SDDSParserException.h"
#include <gtest/gtest.h>
Functions
TEST (OpalExceptionTest, StoresLocationAndMessage)
TEST (OpalExceptionTest, CopyPreservesLocationAndMessage)
TEST (OpalExceptionTest, GenericExceptionIsCaughtAsOpalException)
TEST (OpalExceptionTest, ParserExceptionsAreCaughtAsOpalException)
TEST (OpalExceptionTest, ArithmeticDerivedExceptionsAreCaughtAsOpalException)
Function Documentation
TEST() [1/5]
TEST (OpalExceptionTest , ArithmeticDerivedExceptionsAreCaughtAsOpalException)
Definition at line 41 of file TestOpalException.cpp.
TEST() [2/5]
TEST (OpalExceptionTest , CopyPreservesLocationAndMessage)
Definition at line 16 of file TestOpalException.cpp.
References OpalException::what(), and OpalException::where().
TEST() [3/5]
TEST (OpalExceptionTest , GenericExceptionIsCaughtAsOpalException)
Definition at line 24 of file TestOpalException.cpp.
References OpalException::what(), and OpalException::where().
TEST() [4/5]
TEST (OpalExceptionTest , ParserExceptionsAreCaughtAsOpalException)
Definition at line 36 of file TestOpalException.cpp.
TEST() [5/5]
TEST (OpalExceptionTest , StoresLocationAndMessage)
Definition at line 9 of file TestOpalException.cpp.
References OpalException::what(), and OpalException::where().