OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestGaussian.cpp File Reference
TestGaussian.cpp File Reference
#include <gtest/gtest.h>
#include <mpi.h>
#include <algorithm>
#include <cmath>
#include <memory>
#include "Distribution/Gaussian.h"
#include "Ippl.h"
#include "PartBunch/BunchStateHandler.h"
#include "Utility/IpplTimings.h"
Classes
class GaussianTest
Functions
template<typename ViewType >
void computeMean (ViewType &view, size_t nlocal, size_t total_nparticles, double meanR[3])
template<typename ViewType >
void computeStdDev (ViewType &view, size_t nlocal, size_t total_nparticles, const double meanR[3], double stddevR[3])
template<typename ViewType >
void computeMaxAbsR (ViewType &view, size_t nlocal, double global_maxAbsR[3], double &global_maxRadius)
TEST_F (GaussianTest, meanR_stddevR)
TEST_F (GaussianTest, cutoffR)
TEST_F (GaussianTest, meanP_and_steddevP)
Function Documentation
computeMaxAbsR()
template<typename ViewType > void computeMaxAbsR (ViewType & view, size_t nlocal, double global_maxAbsR[3], double & global_maxRadius)
Definition at line 116 of file TestGaussian.cpp.
Referenced by TEST_F().
computeMean()
template<typename ViewType > void computeMean (ViewType & view, size_t nlocal, size_t total_nparticles, double meanR[3])
Definition at line 63 of file TestGaussian.cpp.
Referenced by TEST_F(), and TEST_F().
computeStdDev()
template<typename ViewType > void computeStdDev (ViewType & view, size_t nlocal, size_t total_nparticles, const double meanR[3], double stddevR[3])
Definition at line 85 of file TestGaussian.cpp.
Referenced by TEST_F(), and TEST_F().
TEST_F() [1/3]
TEST_F (GaussianTest , cutoffR)
Definition at line 200 of file TestGaussian.cpp.
References computeMaxAbsR(), Gaussian::generateParticles(), and nr.
TEST_F() [2/3]
TEST_F (GaussianTest , meanP_and_steddevP)
Definition at line 229 of file TestGaussian.cpp.
References computeMean(), computeStdDev(), Gaussian::generateParticles(), and nr.
TEST_F() [3/3]
TEST_F (GaussianTest , meanR_stddevR)
Definition at line 167 of file TestGaussian.cpp.
References computeMean(), computeStdDev(), Gaussian::generateParticles(), and nr.