OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestBinningCmd.cpp File Reference
TestBinningCmd.cpp File Reference
Unit tests for BinningCmd (input command parsing/validation and parameter mapping).
#include <gtest/gtest.h>
#include "Ippl.h"
#include "Attributes/Attributes.h"
#include "Structure/BinningCmd.h"
#include "Utilities/OpalException.h"
#include <memory>
#include <string>
Classes
class TestableBinningCmd
class BinningCmdTest
Functions
TEST_F (BinningCmdTest, UpdateAppendsJsonExtensionAndValidatesFreq)
TEST_F (BinningCmdTest, DumpBinsToFileRespectsNoneAndEmpty)
TEST_F (BinningCmdTest, InvalidDumpFreqThrowsWhenDumpingEnabled)
TEST_F (BinningCmdTest, InvalidTablePrintFrequencyThrowsWhenNegative)
TEST_F (BinningCmdTest, ConstructionDefaults)
TEST_F (BinningCmdTest, GettersReflectAttributes)
TEST_F (BinningCmdTest, ExecuteMapsKnownParameters)
TEST_F (BinningCmdTest, ExecuteThrowsOnUnknownParameter)
TEST_F (BinningCmdTest, CloneCopiesState)
TEST_F (BinningCmdTest, PrintInfoDoesNotThrow)
Detailed Description
Unit tests for BinningCmd (input command parsing/validation and parameter mapping).
This file tests the behavior of the OPAL command object BinningCmd, focusing on:
Default construction values (max bins, desired width, alpha/beta, default parameter, print frequency).
Getter/setter consistency via a small test helper (TestableBinningCmd) that writes to internal attributes using the standard Attributes interface.
update() validation logic:
Appending .json to DUMPBINSFILE when a filename is provided without the suffix.
Enforcing that DUMPBINSFREQ is positive when dumping is enabled.
Rejecting negative TABLEPRINTFREQ.
execute() behavior:
Mapping supported PARAMETER strings to the corresponding BinningParameter enum.
Throwing OpalException for unknown/unsupported parameter strings.
clone(name):
Copies attribute state and cached parameter selection into a new named command object.
printInfo():
Smoke test that the informational printing path can be invoked without throwing.
These tests ensure the object properly handles invalid configurations and is stable in its public API.
Definition in file TestBinningCmd.cpp.
Function Documentation
TEST_F() [1/10]
TEST_F (BinningCmdTest , CloneCopiesState)
Definition at line 214 of file TestBinningCmd.cpp.
References BinningCmd::clone(), BinningCmd::execute(), BinningCmd::getBinningAlpha(), BinningCmd::getBinningBeta(), BinningCmd::getDesiredWidth(), BinningCmd::getMaxBins(), BinningCmd::getParameter(), BinningCmd::getParameterType(), TestableBinningCmd::setBinningAlpha(), TestableBinningCmd::setBinningBeta(), TestableBinningCmd::setDesiredWidth(), TestableBinningCmd::setMaxBins(), and TestableBinningCmd::setParameterString().
TEST_F() [2/10]
TEST_F (BinningCmdTest , ConstructionDefaults)
Definition at line 137 of file TestBinningCmd.cpp.
References BinningCmd::getBinningAlpha(), BinningCmd::getBinningBeta(), BinningCmd::getDesiredWidth(), BinningCmd::getMaxBins(), BinningCmd::getParameter(), BinningCmd::getParameterType(), BinningCmd::getTablePrintFrequency(), and VELOCITYZ.
TEST_F() [3/10]
TEST_F (BinningCmdTest , DumpBinsToFileRespectsNoneAndEmpty)
Definition at line 102 of file TestBinningCmd.cpp.
References BinningCmd::dumpBinsToFile(), and TestableBinningCmd::setDumpBinsFile().
TEST_F() [4/10]
TEST_F (BinningCmdTest , ExecuteMapsKnownParameters)
Definition at line 178 of file TestBinningCmd.cpp.
References BinningCmd::execute(), GAMMAZ, BinningCmd::getParameter(), BinningCmd::getParameterType(), POSITIONZ, PZ, TestableBinningCmd::setParameterString(), and VELOCITYZ.
TEST_F() [5/10]
TEST_F (BinningCmdTest , ExecuteThrowsOnUnknownParameter)
Definition at line 203 of file TestBinningCmd.cpp.
References BinningCmd::execute(), and TestableBinningCmd::setParameterString().
TEST_F() [6/10]
TEST_F (BinningCmdTest , GettersReflectAttributes)
Definition at line 153 of file TestBinningCmd.cpp.
References BinningCmd::getBinningAlpha(), BinningCmd::getBinningBeta(), BinningCmd::getDesiredWidth(), BinningCmd::getMaxBins(), BinningCmd::getParameter(), BinningCmd::getTablePrintFrequency(), TestableBinningCmd::setBinningAlpha(), TestableBinningCmd::setBinningBeta(), TestableBinningCmd::setDesiredWidth(), TestableBinningCmd::setMaxBins(), TestableBinningCmd::setParameterString(), TestableBinningCmd::setTablePrintFrequency(), and BinningCmd::update().
TEST_F() [7/10]
TEST_F (BinningCmdTest , InvalidDumpFreqThrowsWhenDumpingEnabled)
Definition at line 117 of file TestBinningCmd.cpp.
References TestableBinningCmd::setDumpBinsFile(), TestableBinningCmd::setDumpBinsFreq(), and BinningCmd::update().
TEST_F() [8/10]
TEST_F (BinningCmdTest , InvalidTablePrintFrequencyThrowsWhenNegative)
Definition at line 128 of file TestBinningCmd.cpp.
References TestableBinningCmd::setTablePrintFrequency(), and BinningCmd::update().
TEST_F() [9/10]
TEST_F (BinningCmdTest , PrintInfoDoesNotThrow)
Definition at line 240 of file TestBinningCmd.cpp.
References BinningCmd::printInfo().
TEST_F() [10/10]
TEST_F (BinningCmdTest , UpdateAppendsJsonExtensionAndValidatesFreq)
Definition at line 86 of file TestBinningCmd.cpp.
References BinningCmd::dumpBinsToFile(), BinningCmd::getDumpBinsFileName(), BinningCmd::getDumpBinsFrequency(), TestableBinningCmd::setDumpBinsFile(), TestableBinningCmd::setDumpBinsFreq(), and BinningCmd::update().