OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestLinearBreitWheeler.cpp File Reference
TestLinearBreitWheeler.cpp File Reference
#include "Physics/LinearBreitWheeler.h"
#include "Physics/Physics.h"
#include "Utilities/Options.h"
#include "gtest/gtest.h"
#include <cmath>
Functions
TEST (TestLinearBreitWheeler, HeadOnThresholdMatchesAnalyticCondition)
TEST (TestLinearBreitWheeler, TotalCrossSectionVanishesBelowThreshold)
TEST (TestLinearBreitWheeler, TotalCrossSectionIsPositiveAboveThreshold)
TEST (TestLinearBreitWheeler, ProposalCoordinateMapsToExpectedScatteringCosine)
TEST (TestLinearBreitWheeler, UnpolarizedAngularWeightMatchesIndependentReference)
TEST (TestLinearBreitWheeler, SampledEventConservesFourMomentumForHeadOnGeometry)
TEST (TestLinearBreitWheeler, FixedSeedProducesDeterministicSampleSequence)
Function Documentation
TEST() [1/7]
TEST (TestLinearBreitWheeler , FixedSeedProducesDeterministicSampleSequence)
Definition at line 154 of file TestLinearBreitWheeler.cpp.
References Physics::LinearBreitWheeler::makeHostRandomEngine(), Physics::LinearBreitWheeler::makeSamplingKernel(), Physics::LinearBreitWheeler::photonEnergyFromWavelengthGeV(), Physics::LinearBreitWheeler::sampleEvent(), and Options::seed.
TEST() [2/7]
TEST (TestLinearBreitWheeler , HeadOnThresholdMatchesAnalyticCondition)
Definition at line 69 of file TestLinearBreitWheeler.cpp.
References Physics::LinearBreitWheeler::invariantSGeV2(), Physics::LinearBreitWheeler::isAboveThreshold(), Physics::m_e, Physics::LinearBreitWheeler::photonEnergyFromWavelengthGeV(), and Physics::LinearBreitWheeler::thresholdInvariantSGeV2().
TEST() [3/7]
TEST (TestLinearBreitWheeler , ProposalCoordinateMapsToExpectedScatteringCosine)
Definition at line 97 of file TestLinearBreitWheeler.cpp.
References Physics::LinearBreitWheeler::proposalZToScatteringCosineCM(), and Physics::LinearBreitWheeler::thresholdInvariantSGeV2().
TEST() [4/7]
TEST (TestLinearBreitWheeler , SampledEventConservesFourMomentumForHeadOnGeometry)
Definition at line 117 of file TestLinearBreitWheeler.cpp.
References Physics::LinearBreitWheeler::makeHostRandomEngine(), Physics::LinearBreitWheeler::makeSamplingKernel(), Physics::LinearBreitWheeler::photonEnergyFromWavelengthGeV(), Physics::LinearBreitWheeler::sampleEvent(), Options::seed, and Physics::two_pi.
TEST() [5/7]
TEST (TestLinearBreitWheeler , TotalCrossSectionIsPositiveAboveThreshold)
Definition at line 91 of file TestLinearBreitWheeler.cpp.
References Physics::m_e, and Physics::LinearBreitWheeler::totalCrossSection().
TEST() [6/7]
TEST (TestLinearBreitWheeler , TotalCrossSectionVanishesBelowThreshold)
Definition at line 86 of file TestLinearBreitWheeler.cpp.
References Physics::LinearBreitWheeler::thresholdInvariantSGeV2(), and Physics::LinearBreitWheeler::totalCrossSection().
TEST() [7/7]
TEST (TestLinearBreitWheeler , UnpolarizedAngularWeightMatchesIndependentReference)
Definition at line 107 of file TestLinearBreitWheeler.cpp.
References Physics::LinearBreitWheeler::thresholdInvariantSGeV2(), and Physics::LinearBreitWheeler::unpolarizedAngularWeight().