OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestGSLEigen.cpp File Reference
TestGSLEigen.cpp File Reference
Unit tests for GSL eigenvalue computation.
#include <gtest/gtest.h>
#include "Utilities/GSLEigen.h"
#include "Utilities/GSLMatrix.h"
#include "Utilities/GSLComplex.h"
#include <cmath>
#include <algorithm>
#include <vector>
Classes
class GSLEigenTest
Functions
TEST_F (GSLEigenTest, EigenNonsymm_Identity)
TEST_F (GSLEigenTest, EigenNonsymm_Diagonal)
TEST_F (GSLEigenTest, EigenNonsymmv_Identity)
TEST_F (GSLEigenTest, EigenNonsymmv_Diagonal)
TEST_F (GSLEigenTest, EigenNonsymm_ErrorHandling)
TEST_F (GSLEigenTest, WorkspaceAllocation)
Detailed Description
Unit tests for GSL eigenvalue computation.
This file contains unit tests for GSL-compatible eigenvalue and eigenvector computation routines. The implementation uses a simplified QR algorithm for computing eigenvalues of non-symmetric matrices.
Test:
GSLEigenTest::EigenNonsymm_Identity Tests eigenvalue computation for the identity matrix. Verifies that all eigenvalues are 1.0 (with zero imaginary part) for the identity matrix, confirming that the eigenvalue algorithm correctly handles this special case.
Test:
GSLEigenTest::EigenNonsymm_Diagonal Tests eigenvalue computation for a diagonal matrix. Verifies that the computed eigenvalues match the diagonal elements (2, 3, 4), confirming that the algorithm correctly identifies eigenvalues for diagonalizable matrices.
Test:
GSLEigenTest::EigenNonsymmv_Identity Tests computation of both eigenvalues and eigenvectors for the identity matrix. Verifies that eigenvalues are correct and that eigenvectors are computed (though the implementation may use simplified eigenvector computation).
Test:
GSLEigenTest::EigenNonsymmv_Diagonal Tests eigenvalue and eigenvector computation for a diagonal matrix. Verifies that eigenvalues match diagonal elements and that the algorithm completes successfully.
Test:
GSLEigenTest::EigenNonsymm_ErrorHandling Tests error handling for invalid input (non-square matrix). Verifies that the function returns an error code when the input matrix dimensions are incompatible with eigenvalue computation.
Test:
GSLEigenTest::WorkspaceAllocation Tests allocation and deallocation of eigenvalue computation workspaces. Verifies that workspaces are correctly initialized with the specified size and that memory is properly managed.
Definition in file TestGSLEigen.cpp.
Function Documentation
TEST_F() [1/6]
TEST_F (GSLEigenTest , EigenNonsymm_Diagonal)
Definition at line 81 of file TestGSLEigen.cpp.
References gsl_eigen_nonsymm(), gsl_eigen_nonsymm_alloc(), gsl_eigen_nonsymm_free(), gsl_matrix_alloc(), gsl_matrix_free(), gsl_matrix_set(), gsl_matrix_set_zero(), GSL_REAL, gsl_vector_complex_alloc(), gsl_vector_complex_free(), and gsl_vector_complex_get().
TEST_F() [2/6]
TEST_F (GSLEigenTest , EigenNonsymm_ErrorHandling)
Definition at line 169 of file TestGSLEigen.cpp.
References gsl_eigen_nonsymm(), gsl_eigen_nonsymm_alloc(), gsl_eigen_nonsymm_free(), gsl_matrix_alloc(), gsl_matrix_free(), gsl_vector_complex_alloc(), and gsl_vector_complex_free().
TEST_F() [3/6]
TEST_F (GSLEigenTest , EigenNonsymm_Identity)
Definition at line 56 of file TestGSLEigen.cpp.
References gsl_eigen_nonsymm(), gsl_eigen_nonsymm_alloc(), gsl_eigen_nonsymm_free(), GSL_IMAG, gsl_matrix_alloc(), gsl_matrix_free(), gsl_matrix_set_identity(), GSL_REAL, gsl_vector_complex_alloc(), gsl_vector_complex_free(), and gsl_vector_complex_get().
TEST_F() [4/6]
TEST_F (GSLEigenTest , EigenNonsymmv_Diagonal)
Definition at line 138 of file TestGSLEigen.cpp.
References gsl_eigen_nonsymmv(), gsl_eigen_nonsymmv_alloc(), gsl_eigen_nonsymmv_free(), gsl_matrix_alloc(), gsl_matrix_complex_alloc(), gsl_matrix_complex_free(), gsl_matrix_free(), gsl_matrix_set(), gsl_matrix_set_zero(), GSL_REAL, gsl_vector_complex_alloc(), gsl_vector_complex_free(), and gsl_vector_complex_get().
TEST_F() [5/6]
TEST_F (GSLEigenTest , EigenNonsymmv_Identity)
Definition at line 112 of file TestGSLEigen.cpp.
References gsl_eigen_nonsymmv(), gsl_eigen_nonsymmv_alloc(), gsl_eigen_nonsymmv_free(), GSL_IMAG, gsl_matrix_alloc(), gsl_matrix_complex_alloc(), gsl_matrix_complex_free(), gsl_matrix_free(), gsl_matrix_set_identity(), GSL_REAL, gsl_vector_complex_alloc(), gsl_vector_complex_free(), and gsl_vector_complex_get().
TEST_F() [6/6]
TEST_F (GSLEigenTest , WorkspaceAllocation)
Definition at line 182 of file TestGSLEigen.cpp.
References gsl_eigen_nonsymm_alloc(), gsl_eigen_nonsymm_free(), gsl_eigen_nonsymmv_alloc(), gsl_eigen_nonsymmv_free(), gsl_eigen_nonsymm_workspace::n, and gsl_eigen_nonsymmv_workspace::n.