OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestPlacedElement.cpp File Reference
TestPlacedElement.cpp File Reference
#include "gtest/gtest.h"
#include "BeamlineCore/DriftRep.h"
#include "BeamlineGeometry/ElementGeometry.h"
#include "BeamlineGeometry/Misalignment.h"
#include "BeamlineGeometry/PlacedElement.h"
#include "BeamlineGeometry/PlacementPose.h"
#include "BeamlineGeometry/Port.h"
#include "BeamlineGeometry/SupportPlacement.h"
#include <cmath>
Classes
class PlacedElementTest
Functions
TEST_F (PlacedElementTest, ActualBodyTransformAppliesCorrectionAfterNominalPlacement)
TEST_F (PlacedElementTest, EntryExitAndSupportTransformsAreDerivedFromBodyFrame)
TEST_F (PlacedElementTest, DefaultGeometryExposesNamedPorts)
TEST_F (PlacedElementTest, ElementBaseBridgeUsesExistingPlacementAndEdgeState)
TEST_F (PlacedElementTest, ElementBaseExposesExplicitStraightElementPortContract)
Function Documentation
TEST_F() [1/5]
TEST_F (PlacedElementTest , ActualBodyTransformAppliesCorrectionAfterNominalPlacement)
Definition at line 41 of file TestPlacedElement.cpp.
References PlacedElement::getActualBodyTransform(), Misalignment::getNominalToActual(), PlacementPose::getParentToNominal(), and CoordinateSystemTrafo::transformTo().
TEST_F() [2/5]
TEST_F (PlacedElementTest , DefaultGeometryExposesNamedPorts)
Definition at line 83 of file TestPlacedElement.cpp.
References ElementGeometry::getBody(), ElementGeometry::getEntry(), ElementGeometry::getExit(), and Port::getName().
TEST_F() [3/5]
TEST_F (PlacedElementTest , ElementBaseBridgeUsesExistingPlacementAndEdgeState)
Definition at line 91 of file TestPlacedElement.cpp.
References ElementGeometry::getEntry(), ElementGeometry::getExit(), PlacedElement::getGeometry(), Port::getName(), PlacedElement::getNominalBodyTransform(), PlacedElement::getNominalEntryTransform(), PlacedElement::getNominalExitTransform(), CoordinateSystemTrafo::getOrigin(), ElementBase::getPlacedElement(), ElementBase::setCSTrafoGlobal2Local(), ElementBase::setElementLength(), and ElementBase::setMisalignment().
TEST_F() [4/5]
TEST_F (PlacedElementTest , ElementBaseExposesExplicitStraightElementPortContract)
Definition at line 107 of file TestPlacedElement.cpp.
References ElementBase::getBodyPort(), Port::getBodyToPort(), ElementBase::getEntryPort(), ElementBase::getExitPort(), Port::getName(), CoordinateSystemTrafo::getOrigin(), and ElementBase::setElementLength().
TEST_F() [5/5]
TEST_F (PlacedElementTest , EntryExitAndSupportTransformsAreDerivedFromBodyFrame)
Definition at line 56 of file TestPlacedElement.cpp.
References PlacedElement::getActualBodyTransform(), ElementGeometry::getBody(), Port::getBodyToPort(), SupportPlacement::getBodyToSupport(), PlacedElement::getBodyTransform(), ElementGeometry::getEntry(), PlacedElement::getEntryTransform(), ElementGeometry::getExit(), PlacedElement::getExitTransform(), PlacedElement::getSupportTransform(), and CoordinateSystemTrafo::transformTo().