OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestCoordinateSystemTrafo.cpp File Reference
TestCoordinateSystemTrafo.cpp File Reference
#include "gtest/gtest.h"
#include "Algorithms/CoordinateSystemTrafo.h"
#include "Ippl.h"
#include <cmath>
Classes
class CoordinateSystemTrafoTest
Functions
TEST_F (CoordinateSystemTrafoTest, DefaultConstructorIsIdentity)
TEST_F (CoordinateSystemTrafoTest, TransformRoundTrip)
TEST_F (CoordinateSystemTrafoTest, RotateRoundTrip)
TEST_F (CoordinateSystemTrafoTest, InverseMatchesTransformFromAndRotateFrom)
TEST_F (CoordinateSystemTrafoTest, InvertInPlaceMatchesInverted)
TEST_F (CoordinateSystemTrafoTest, CompositionAppliesRightThenLeftToPoints)
TEST_F (CoordinateSystemTrafoTest, CompositionAppliesRightThenLeftToVectors)
Function Documentation
TEST_F() [1/7]
TEST_F (CoordinateSystemTrafoTest , CompositionAppliesRightThenLeftToPoints)
Definition at line 103 of file TestCoordinateSystemTrafo.cpp.
References CoordinateSystemTrafo::transformTo().
TEST_F() [2/7]
TEST_F (CoordinateSystemTrafoTest , CompositionAppliesRightThenLeftToVectors)
Definition at line 112 of file TestCoordinateSystemTrafo.cpp.
References CoordinateSystemTrafo::rotateTo().
TEST_F() [3/7]
TEST_F (CoordinateSystemTrafoTest , DefaultConstructorIsIdentity)
Definition at line 44 of file TestCoordinateSystemTrafo.cpp.
References CoordinateSystemTrafo::getOrigin(), CoordinateSystemTrafo::getRotation(), Quaternion::real(), CoordinateSystemTrafo::rotateFrom(), CoordinateSystemTrafo::rotateTo(), CoordinateSystemTrafo::transformFrom(), and CoordinateSystemTrafo::transformTo().
TEST_F() [4/7]
TEST_F (CoordinateSystemTrafoTest , InverseMatchesTransformFromAndRotateFrom)
Definition at line 79 of file TestCoordinateSystemTrafo.cpp.
References CoordinateSystemTrafo::inverted(), CoordinateSystemTrafo::rotateFrom(), CoordinateSystemTrafo::rotateTo(), CoordinateSystemTrafo::transformFrom(), and CoordinateSystemTrafo::transformTo().
TEST_F() [5/7]
TEST_F (CoordinateSystemTrafoTest , InvertInPlaceMatchesInverted)
Definition at line 90 of file TestCoordinateSystemTrafo.cpp.
References CoordinateSystemTrafo::getOrigin(), CoordinateSystemTrafo::getRotation(), CoordinateSystemTrafo::invert(), CoordinateSystemTrafo::inverted(), and Quaternion::real().
TEST_F() [6/7]
TEST_F (CoordinateSystemTrafoTest , RotateRoundTrip)
Definition at line 70 of file TestCoordinateSystemTrafo.cpp.
References CoordinateSystemTrafo::rotateFrom(), and CoordinateSystemTrafo::rotateTo().
TEST_F() [7/7]
TEST_F (CoordinateSystemTrafoTest , TransformRoundTrip)
Definition at line 61 of file TestCoordinateSystemTrafo.cpp.
References CoordinateSystemTrafo::transformFrom(), and CoordinateSystemTrafo::transformTo().