OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestBinConfigWriter.cpp File Reference
TestBinConfigWriter.cpp File Reference
#include <gtest/gtest.h>
#include "Ippl.h"
#include "Structure/BinConfigWriter.h"
#include "Utilities/OpalException.h"
#include <cmath>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
Classes
class BinConfigWriterTest
Functions
TEST_F (BinConfigWriterTest, ConstructionOpensFileAndWritesOpeningBracket)
TEST_F (BinConfigWriterTest, SingleEntryProducesValidJson)
TEST_F (BinConfigWriterTest, MultipleEntriesProduceValidJsonArray)
TEST_F (BinConfigWriterTest, EmptyArraysHandledCorrectly)
TEST_F (BinConfigWriterTest, FileClosedAfterEachEntry)
TEST_F (BinConfigWriterTest, InvalidPathThrows)
Function Documentation
TEST_F() [1/6]
TEST_F (BinConfigWriterTest , ConstructionOpensFileAndWritesOpeningBracket)
Definition at line 57 of file TestBinConfigWriter.cpp.
TEST_F() [2/6]
TEST_F (BinConfigWriterTest , EmptyArraysHandledCorrectly)
Definition at line 112 of file TestBinConfigWriter.cpp.
References BinConfigWriter::writeEntry().
TEST_F() [3/6]
TEST_F (BinConfigWriterTest , FileClosedAfterEachEntry)
Definition at line 130 of file TestBinConfigWriter.cpp.
References BinConfigWriter::writeEntry().
TEST_F() [4/6]
TEST_F (BinConfigWriterTest , InvalidPathThrows)
Definition at line 149 of file TestBinConfigWriter.cpp.
TEST_F() [5/6]
TEST_F (BinConfigWriterTest , MultipleEntriesProduceValidJsonArray)
Definition at line 89 of file TestBinConfigWriter.cpp.
References BinConfigWriter::writeEntry().
TEST_F() [6/6]
TEST_F (BinConfigWriterTest , SingleEntryProducesValidJson)
Definition at line 68 of file TestBinConfigWriter.cpp.
References BinConfigWriter::writeEntry().