OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestSinusoidalTimeDependence.cpp File Reference
TestSinusoidalTimeDependence.cpp File Reference
#include "Algorithms/AbstractTimeDependence.h"
#include "Algorithms/SinusoidalTimeDependence.h"
#include "Ippl.h"
#include "Utilities/GeneralOpalException.h"
#include "gtest/gtest.h"
Functions
TEST (TestSinusoidalTimeDependence, SinusoidalTimeDependenceTest)
TEST (TestSinusoidalTimeDependence, TDMapTest)
TEST (TestSinusoidalTimeDependence, TDMapNameLookupTest)
TEST (TestSinusoidalTimeDependence, Integral)
TEST (TestSinusoidalTimeDependence, Print)
Function Documentation
TEST() [1/5]
TEST (TestSinusoidalTimeDependence , Integral)
Definition at line 85 of file TestSinusoidalTimeDependence.cpp.
TEST() [2/5]
TEST (TestSinusoidalTimeDependence , Print)
Definition at line 107 of file TestSinusoidalTimeDependence.cpp.
TEST() [3/5]
TEST (TestSinusoidalTimeDependence , SinusoidalTimeDependenceTest)
Definition at line 22 of file TestSinusoidalTimeDependence.cpp.
References SinusoidalTimeDependence::clone(), and SinusoidalTimeDependence::getValue().
TEST() [4/5]
TEST (TestSinusoidalTimeDependence , TDMapNameLookupTest)
Definition at line 69 of file TestSinusoidalTimeDependence.cpp.
References AbstractTimeDependence::getName(), and AbstractTimeDependence::setTimeDependence().
TEST() [5/5]
TEST (TestSinusoidalTimeDependence , TDMapTest)
Definition at line 49 of file TestSinusoidalTimeDependence.cpp.
References AbstractTimeDependence::getTimeDependence(), and AbstractTimeDependence::setTimeDependence().