OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestLinearSpline.cpp File Reference
TestLinearSpline.cpp File Reference
#include <gtest/gtest.h>
#include <vector>
#include "Utilities/LinearSpline.h"
Classes
class LinearSplineTest
Functions
TEST_F (LinearSplineTest, BasicInterpolation)
TEST_F (LinearSplineTest, Uninitialised)
TEST_F (LinearSplineTest, Extrapolation)
TEST_F (LinearSplineTest, Accelerator)
TEST_F (LinearSplineTest, InvalidInput)
TEST_F (LinearSplineTest, Integration)
Function Documentation
TEST_F() [1/6]
TEST_F (LinearSplineTest , Accelerator)
Definition at line 78 of file TestLinearSpline.cpp.
References LinearSpline::eval().
TEST_F() [2/6]
TEST_F (LinearSplineTest , BasicInterpolation)
Definition at line 44 of file TestLinearSpline.cpp.
References LinearSpline::eval().
TEST_F() [3/6]
TEST_F (LinearSplineTest , Extrapolation)
Definition at line 65 of file TestLinearSpline.cpp.
References LinearSpline::eval().
TEST_F() [4/6]
TEST_F (LinearSplineTest , Integration)
Definition at line 102 of file TestLinearSpline.cpp.
References LinearSpline::evalIntegral(), and LinearSpline::init().
TEST_F() [5/6]
TEST_F (LinearSplineTest , InvalidInput)
Definition at line 92 of file TestLinearSpline.cpp.
TEST_F() [6/6]
TEST_F (LinearSplineTest , Uninitialised)
Definition at line 58 of file TestLinearSpline.cpp.
References LinearSpline::eval().