OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestVariableRFCavity.cpp File Reference
TestVariableRFCavity.cpp File Reference
#include <vector>
#include "AbsBeamline/BeamlineVisitor.h"
#include "AbsBeamline/VariableRFCavity.h"
#include "AbstractObjects/OpalData.h"
#include "Algorithms/AbstractTimeDependence.h"
#include "Algorithms/PolynomialTimeDependence.h"
#include "Physics/Physics.h"
#include "Physics/Units.h"
#include "Structure/Beam.h"
#include "Structure/DataSink.h"
#include "gtest/gtest.h"
Classes
class TestVariableRFCavity
class TestVariableRFCavity::TestableFieldSolverCmd
Functions
TEST_F (TestVariableRFCavity, TestConstructorEtc)
TEST_F (TestVariableRFCavity, TestGetSet)
TEST_F (TestVariableRFCavity, GetTimeDependencyValues)
TEST_F (TestVariableRFCavity, TimeDependencyNames)
TEST_F (TestVariableRFCavity, TestAssignmentNull)
TEST_F (TestVariableRFCavity, TestAssignmentValue)
TEST_F (TestVariableRFCavity, TestClone)
TEST_F (TestVariableRFCavity, TestInitialiseFinalise)
TEST_F (TestVariableRFCavity, TestGetGeometry)
TEST_F (TestVariableRFCavity, TestApplyField)
TEST_F (TestVariableRFCavity, TestApplyBoundingBox)
TEST_F (TestVariableRFCavity, BunchFields)
TEST_F (TestVariableRFCavity, ReferenceParticle)
TEST_F (TestVariableRFCavity, OddApis)
TEST_F (TestVariableRFCavity, FieldSupportMatchesBodyLength)
Function Documentation
TEST_F() [1/15]
TEST_F (TestVariableRFCavity , BunchFields)
Definition at line 329 of file TestVariableRFCavity.cpp.
References Units::MVpm2Vpm, and Physics::pi.
TEST_F() [2/15]
TEST_F (TestVariableRFCavity , FieldSupportMatchesBodyLength)
Definition at line 431 of file TestVariableRFCavity.cpp.
References Units::MVpm2Vpm, and Physics::pi.
TEST_F() [3/15]
TEST_F (TestVariableRFCavity , GetTimeDependencyValues)
Definition at line 173 of file TestVariableRFCavity.cpp.
References VariableRFCavity::setAmplitudeModel().
TEST_F() [4/15]
TEST_F (TestVariableRFCavity , OddApis)
Definition at line 405 of file TestVariableRFCavity.cpp.
References VariableRFCavity::bends(), VariableRFCavity::getField(), VariableRFCavity::getFieldExtend(), VariableRFCavity::getLength(), and VariableRFCavity::setLength().
TEST_F() [5/15]
TEST_F (TestVariableRFCavity , ReferenceParticle)
Definition at line 386 of file TestVariableRFCavity.cpp.
References Units::MVpm2Vpm, and Physics::pi.
TEST_F() [6/15]
TEST_F (TestVariableRFCavity , TestApplyBoundingBox)
Definition at line 290 of file TestVariableRFCavity.cpp.
References VariableRFCavity::apply(), VariableRFCavity::setAmplitudeModel(), VariableRFCavity::setFrequencyModel(), VariableRFCavity::setHeight(), VariableRFCavity::setLength(), VariableRFCavity::setPhaseModel(), and VariableRFCavity::setWidth().
TEST_F() [7/15]
TEST_F (TestVariableRFCavity , TestApplyField)
Definition at line 260 of file TestVariableRFCavity.cpp.
References VariableRFCavity::apply(), Units::MHz2Hz, Units::MVpm2Vpm, VariableRFCavity::setAmplitudeModel(), VariableRFCavity::setFrequencyModel(), VariableRFCavity::setHeight(), VariableRFCavity::setLength(), VariableRFCavity::setPhaseModel(), VariableRFCavity::setWidth(), and Physics::two_pi.
TEST_F() [8/15]
TEST_F (TestVariableRFCavity , TestAssignmentNull)
Definition at line 211 of file TestVariableRFCavity.cpp.
References VariableRFCavity::getLength().
TEST_F() [9/15]
TEST_F (TestVariableRFCavity , TestAssignmentValue)
Definition at line 221 of file TestVariableRFCavity.cpp.
References VariableRFCavity::getAmplitudeModel(), VariableRFCavity::getFrequencyModel(), VariableRFCavity::getLength(), VariableRFCavity::getPhaseModel(), AbstractTimeDependence::getValue(), VariableRFCavity::setAmplitudeModel(), VariableRFCavity::setFrequencyModel(), VariableRFCavity::setLength(), and VariableRFCavity::setPhaseModel().
TEST_F() [10/15]
TEST_F (TestVariableRFCavity , TestClone)
Definition at line 240 of file TestVariableRFCavity.cpp.
References VariableRFCavity::clone(), VariableRFCavity::getLength(), and VariableRFCavity::setLength().
TEST_F() [11/15]
TEST_F (TestVariableRFCavity , TestConstructorEtc)
Definition at line 148 of file TestVariableRFCavity.cpp.
References ElementBase::getName().
TEST_F() [12/15]
TEST_F (TestVariableRFCavity , TestGetGeometry)
Definition at line 252 of file TestVariableRFCavity.cpp.
References StraightGeometry::getElementLength(), VariableRFCavity::getGeometry(), VariableRFCavity::getLength(), and VariableRFCavity::setLength().
TEST_F() [13/15]
TEST_F (TestVariableRFCavity , TestGetSet)
Definition at line 159 of file TestVariableRFCavity.cpp.
References VariableRFCavity::getAmplitudeModel(), VariableRFCavity::getFrequencyModel(), VariableRFCavity::getHeight(), VariableRFCavity::getLength(), VariableRFCavity::getPhaseModel(), VariableRFCavity::getWidth(), VariableRFCavity::setAmplitudeModel(), VariableRFCavity::setFrequencyModel(), VariableRFCavity::setHeight(), VariableRFCavity::setLength(), VariableRFCavity::setPhaseModel(), and VariableRFCavity::setWidth().
TEST_F() [14/15]
TEST_F (TestVariableRFCavity , TestInitialiseFinalise)
Definition at line 248 of file TestVariableRFCavity.cpp.
TEST_F() [15/15]
TEST_F (TestVariableRFCavity , TimeDependencyNames)
Definition at line 186 of file TestVariableRFCavity.cpp.
References VariableRFCavity::accept(), VariableRFCavity::getAmplitude(), VariableRFCavity::getFrequency(), VariableRFCavity::getPhase(), VariableRFCavity::setAmplitudeName(), VariableRFCavity::setFrequencyName(), VariableRFCavity::setHeight(), VariableRFCavity::setPhaseName(), AbstractTimeDependence::setTimeDependence(), and VariableRFCavity::setWidth().