OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestOpalSplineTimeDependence.cpp File Reference
TestOpalSplineTimeDependence.cpp File Reference
#include <sstream>
#include "Algorithms/SplineTimeDependence.h"
#include "Attributes/Attributes.h"
#include "Elements/OpalSplineTimeDependence.h"
#include "gtest/gtest.h"
Functions
TEST (TestOpalSplineTimeDependence, ConstructorTest)
TEST (TestOpalSplineTimeDependence, PrintTest)
TEST (TestOpalSplineTimeDependence, UserInterface)
TEST (TestOpalSplineTimeDependence, DefaultValues)
TEST (TestOpalSplineTimeDependence, UserInterfaceBadOrder)
Function Documentation
TEST() [1/5]
TEST (TestOpalSplineTimeDependence , ConstructorTest)
Definition at line 22 of file TestOpalSplineTimeDependence.cpp.
References OpalSplineTimeDependence::clone(), and Object::getOpalName().
TEST() [2/5]
TEST (TestOpalSplineTimeDependence , DefaultValues)
Definition at line 53 of file TestOpalSplineTimeDependence.cpp.
References AbstractTimeDependence::getTimeDependence(), Object::itsAttr, OpalSplineTimeDependence::ORDER, Attributes::setReal(), and OpalSplineTimeDependence::update().
TEST() [3/5]
TEST (TestOpalSplineTimeDependence , PrintTest)
Definition at line 28 of file TestOpalSplineTimeDependence.cpp.
References OpalSplineTimeDependence::print().
TEST() [4/5]
TEST (TestOpalSplineTimeDependence , UserInterface)
Definition at line 35 of file TestOpalSplineTimeDependence.cpp.
References AbstractTimeDependence::getTimeDependence(), Object::itsAttr, OpalSplineTimeDependence::ORDER, Attributes::setReal(), Attributes::setRealArray(), OpalSplineTimeDependence::TIMES, OpalSplineTimeDependence::update(), and OpalSplineTimeDependence::VALUES.
TEST() [5/5]
TEST (TestOpalSplineTimeDependence , UserInterfaceBadOrder)
Definition at line 69 of file TestOpalSplineTimeDependence.cpp.
References Object::itsAttr, OpalSplineTimeDependence::ORDER, Attributes::setReal(), Attributes::setRealArray(), OpalSplineTimeDependence::TIMES, OpalSplineTimeDependence::update(), and OpalSplineTimeDependence::VALUES.