OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestIndexMap.cpp File Reference
TestIndexMap.cpp File Reference
#include "gtest/gtest.h"
#include "Algorithms/IndexMap.h"
#include "BeamlineCore/DriftRep.h"
#include <limits>
Functions
TEST (IndexMapTest, RebuildsReferencePathModelFromOrderedRanges)
Function Documentation
TEST()
TEST (IndexMapTest , RebuildsReferencePathModelFromOrderedRanges)
Definition at line 8 of file TestIndexMap.cpp.
References IndexMap::add(), IndexMap::getReferencePathModel(), and ReferencePathModel::size().