OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestOpalMultipoleT.cpp File Reference
TestOpalMultipoleT.cpp File Reference
#include "AbsBeamline/MultipoleT.h"
#include "Attributes/Attributes.h"
#include "Elements/OpalMultipoleT.h"
#include "gtest/gtest.h"
Classes
class TestOpalMultipoleT
Functions
TEST_F (TestOpalMultipoleT, UserInterface)
TEST_F (TestOpalMultipoleT, UserInterfaceClone)
TEST_F (TestOpalMultipoleT, UserInterfaceSanityCheck)
TEST_F (TestOpalMultipoleT, Print)
Function Documentation
TEST_F() [1/4]
TEST_F (TestOpalMultipoleT , Print)
Definition at line 218 of file TestOpalMultipoleT.cpp.
References OpalMultipoleT::print().
TEST_F() [2/4]
TEST_F (TestOpalMultipoleT , UserInterface)
Definition at line 40 of file TestOpalMultipoleT.cpp.
References OpalMultipoleT::ANGLE, OpalMultipoleT::BBLENGTH, OpalMultipoleT::EANGLE, OpalMultipoleT::ENTRYOFFSET, Element::getElement(), OpalMultipoleT::HAPERT, Object::itsAttr, OpalElement::LENGTH, OpalMultipoleT::LFRINGE, OpalMultipoleT::MAXFORDER, OpalMultipoleT::MAXXORDER, OpalMultipoleT::MISALIGN_H, OpalMultipoleT::MISALIGN_PITCH, OpalMultipoleT::MISALIGN_ROLL, OpalMultipoleT::MISALIGN_S, OpalMultipoleT::MISALIGN_V, OpalMultipoleT::MISALIGN_YAW, MultipoleTConfig::NumPoles, OpalMultipoleT::RFRINGE, OpalMultipoleT::ROTATION, OpalMultipoleT::SCALING_MODEL, Attributes::setBool(), Attributes::setReal(), Attributes::setRealArray(), Attributes::setUpperCaseString(), OpalMultipoleT::TP, OpalMultipoleT::update(), OpalMultipoleT::VAPERT, and OpalMultipoleT::VARRADIUS.
TEST_F() [3/4]
TEST_F (TestOpalMultipoleT , UserInterfaceClone)
Definition at line 109 of file TestOpalMultipoleT.cpp.
References OpalMultipoleT::ANGLE, OpalMultipoleT::BBLENGTH, OpalMultipoleT::clone(), OpalMultipoleT::EANGLE, OpalMultipoleT::ENTRYOFFSET, OpalMultipoleT::HAPERT, Object::itsAttr, OpalElement::LENGTH, OpalMultipoleT::LFRINGE, OpalMultipoleT::MAXFORDER, OpalMultipoleT::MAXXORDER, OpalMultipoleT::RFRINGE, OpalMultipoleT::ROTATION, OpalMultipoleT::SCALING_MODEL, Attributes::setBool(), Attributes::setReal(), Attributes::setRealArray(), Attributes::setUpperCaseString(), OpalMultipoleT::TP, OpalMultipoleT::VAPERT, and OpalMultipoleT::VARRADIUS.
TEST_F() [4/4]
TEST_F (TestOpalMultipoleT , UserInterfaceSanityCheck)
Definition at line 163 of file TestOpalMultipoleT.cpp.
References OpalMultipoleT::ANGLE, OpalMultipoleT::BBLENGTH, OpalMultipoleT::EANGLE, OpalMultipoleT::ENTRYOFFSET, OpalMultipoleT::HAPERT, Object::itsAttr, OpalElement::LENGTH, OpalMultipoleT::LFRINGE, OpalMultipoleT::MAXFORDER, OpalMultipoleT::MAXXORDER, OpalMultipoleT::RFRINGE, OpalMultipoleT::ROTATION, Attributes::setBool(), Attributes::setReal(), Attributes::setRealArray(), OpalMultipoleT::TP, OpalMultipoleT::update(), OpalMultipoleT::VAPERT, and OpalMultipoleT::VARRADIUS.