OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestLinearComptonSpectrum.cpp File Reference
TestLinearComptonSpectrum.cpp File Reference
Regression tests for CAIN-validated linear-Compton energy and angle spectra.
#include "LinearComptonSpectrumCommon.h"
#include "Utilities/Options.h"
#include "gtest/gtest.h"
#include <cstdlib>
#include <filesystem>
#include <sstream>
#include <stdexcept>
#include <string>
Functions
TEST (TestLinearComptonSpectrum, WeakFieldSpectrumMatchesCainReference)
TEST (TestLinearComptonSpectrum, WeakFieldSampledSpectrumMatchesCainReference)
TEST (TestLinearComptonSpectrum, WeakFieldAngularSpectrumMatchesCainReference)
TEST (TestLinearComptonSpectrum, WeakFieldSampledAngularSpectrumMatchesCainReference)
TEST (TestLinearComptonSpectrum, WeakFieldJointSpectrumMatchesCainReference)
TEST (TestLinearComptonSpectrum, WeakFieldSampledJointSpectrumMatchesCainReference)
TEST (TestLinearComptonSpectrum, FiniteBeamSpectrumMatchesCainReference)
TEST (TestLinearComptonSpectrum, FiniteBeamAngularSpectrumMatchesCainReference)
TEST (TestLinearComptonSpectrum, FiniteBeamJointSpectrumMatchesCainReference)
TEST (TestLinearComptonSpectrum, FiniteBeamEnergySpreadSpectrumMatchesCainReference)
TEST (TestLinearComptonSpectrum, FiniteBeamEnergySpreadAngularSpectrumMatchesCainReference)
TEST (TestLinearComptonSpectrum, FiniteBeamEnergySpreadJointSpectrumMatchesCainReference)
TEST (TestLinearComptonSpectrum, FiniteBeamOverlapSpectrumMatchesCainReference)
TEST (TestLinearComptonSpectrum, FiniteBeamOverlapAngularSpectrumMatchesCainReference)
Detailed Description
Regression tests for CAIN-validated linear-Compton energy and angle spectra.
This file mixes two validation styles:
direct deterministic comparisons against stored CAIN histograms for the single-electron benchmark, and
subprocess-driven regeneration of finite-beam benchmark CSV files through LinearComptonSpectrumBenchmark, followed by comparison against stored CAIN references.
The histogram checks use area, mean, and L1-distance tolerances instead of pointwise equality. That keeps the tests stable across small Monte Carlo and quadrature differences while still detecting shape regressions in the photon spectra.
Definition in file TestLinearComptonSpectrum.cpp.
Function Documentation
TEST() [1/14]
TEST (TestLinearComptonSpectrum , FiniteBeamAngularSpectrumMatchesCainReference)
Definition at line 301 of file TestLinearComptonSpectrum.cpp.
References LinearComptonBenchmark::angleHistogramArea(), LinearComptonBenchmark::angleHistogramL1Distance(), LinearComptonBenchmark::angleHistogramMeanRad(), and LinearComptonBenchmark::readAngleCSV().
TEST() [2/14]
TEST (TestLinearComptonSpectrum , FiniteBeamEnergySpreadAngularSpectrumMatchesCainReference)
Definition at line 372 of file TestLinearComptonSpectrum.cpp.
References LinearComptonBenchmark::angleHistogramArea(), LinearComptonBenchmark::angleHistogramL1Distance(), LinearComptonBenchmark::angleHistogramMeanRad(), and LinearComptonBenchmark::readAngleCSV().
TEST() [3/14]
TEST (TestLinearComptonSpectrum , FiniteBeamEnergySpreadJointSpectrumMatchesCainReference)
Definition at line 395 of file TestLinearComptonSpectrum.cpp.
References LinearComptonBenchmark::jointHistogramArea(), LinearComptonBenchmark::jointHistogramL1Distance(), LinearComptonBenchmark::jointHistogramMeanEnergyGeV(), LinearComptonBenchmark::jointHistogramMeanThetaRad(), and LinearComptonBenchmark::readJointCSV().
TEST() [4/14]
TEST (TestLinearComptonSpectrum , FiniteBeamEnergySpreadSpectrumMatchesCainReference)
This variant adds a small relative energy spread to the same finite-emittance beam. The tolerance is kept at the same scale as the zero-spread finite-beam case because the stored CAIN reference has high enough statistics to keep the broadened distributions stable.
Definition at line 349 of file TestLinearComptonSpectrum.cpp.
References LinearComptonBenchmark::histogramArea(), LinearComptonBenchmark::histogramL1Distance(), LinearComptonBenchmark::histogramMeanEnergyGeV(), and LinearComptonBenchmark::readSpectrumCSV().
TEST() [5/14]
TEST (TestLinearComptonSpectrum , FiniteBeamJointSpectrumMatchesCainReference)
Definition at line 321 of file TestLinearComptonSpectrum.cpp.
References LinearComptonBenchmark::jointHistogramArea(), LinearComptonBenchmark::jointHistogramL1Distance(), LinearComptonBenchmark::jointHistogramMeanEnergyGeV(), LinearComptonBenchmark::jointHistogramMeanThetaRad(), and LinearComptonBenchmark::readJointCSV().
TEST() [6/14]
TEST (TestLinearComptonSpectrum , FiniteBeamOverlapAngularSpectrumMatchesCainReference)
Definition at line 436 of file TestLinearComptonSpectrum.cpp.
References LinearComptonBenchmark::angleHistogramArea(), LinearComptonBenchmark::angleHistogramL1Distance(), LinearComptonBenchmark::angleHistogramMeanRad(), and LinearComptonBenchmark::readAngleCSV().
TEST() [7/14]
TEST (TestLinearComptonSpectrum , FiniteBeamOverlapSpectrumMatchesCainReference)
Definition at line 419 of file TestLinearComptonSpectrum.cpp.
References LinearComptonBenchmark::histogramArea(), LinearComptonBenchmark::histogramL1Distance(), LinearComptonBenchmark::histogramMeanEnergyGeV(), and LinearComptonBenchmark::readSpectrumCSV().
TEST() [8/14]
TEST (TestLinearComptonSpectrum , FiniteBeamSpectrumMatchesCainReference)
The finite-beam regressions allow a small normalization and shape tolerance because they combine Gaussian beam sampling with stochastic Compton event generation. The mean and L1 checks are the primary regression guards.
Definition at line 282 of file TestLinearComptonSpectrum.cpp.
References LinearComptonBenchmark::histogramArea(), LinearComptonBenchmark::histogramL1Distance(), LinearComptonBenchmark::histogramMeanEnergyGeV(), and LinearComptonBenchmark::readSpectrumCSV().
TEST() [9/14]
TEST (TestLinearComptonSpectrum , WeakFieldAngularSpectrumMatchesCainReference)
Definition at line 187 of file TestLinearComptonSpectrum.cpp.
References LinearComptonBenchmark::angleHistogramArea(), LinearComptonBenchmark::angleHistogramL1Distance(), LinearComptonBenchmark::angleHistogramMeanRad(), LinearComptonBenchmark::integrateLabAngularSpectrum(), and LinearComptonBenchmark::readAngleCSV().
TEST() [10/14]
TEST (TestLinearComptonSpectrum , WeakFieldJointSpectrumMatchesCainReference)
Definition at line 227 of file TestLinearComptonSpectrum.cpp.
References LinearComptonBenchmark::integrateLabJointSpectrum(), LinearComptonBenchmark::jointHistogramArea(), LinearComptonBenchmark::jointHistogramL1Distance(), LinearComptonBenchmark::jointHistogramMeanEnergyGeV(), LinearComptonBenchmark::jointHistogramMeanThetaRad(), and LinearComptonBenchmark::readJointCSV().
TEST() [11/14]
TEST (TestLinearComptonSpectrum , WeakFieldSampledAngularSpectrumMatchesCainReference)
Definition at line 205 of file TestLinearComptonSpectrum.cpp.
References LinearComptonBenchmark::angleHistogramArea(), LinearComptonBenchmark::angleHistogramL1Distance(), LinearComptonBenchmark::angleHistogramMeanRad(), LinearComptonBenchmark::readAngleCSV(), LinearComptonBenchmark::sampleLabAngularSpectrum(), and Options::seed.
TEST() [12/14]
TEST (TestLinearComptonSpectrum , WeakFieldSampledJointSpectrumMatchesCainReference)
Definition at line 250 of file TestLinearComptonSpectrum.cpp.
References LinearComptonBenchmark::jointHistogramArea(), LinearComptonBenchmark::jointHistogramL1Distance(), LinearComptonBenchmark::jointHistogramMeanEnergyGeV(), LinearComptonBenchmark::jointHistogramMeanThetaRad(), LinearComptonBenchmark::readJointCSV(), LinearComptonBenchmark::sampleLabJointSpectrum(), and Options::seed.
TEST() [13/14]
TEST (TestLinearComptonSpectrum , WeakFieldSampledSpectrumMatchesCainReference)
Definition at line 165 of file TestLinearComptonSpectrum.cpp.
References LinearComptonBenchmark::histogramArea(), LinearComptonBenchmark::histogramL1Distance(), LinearComptonBenchmark::histogramMeanEnergyGeV(), LinearComptonBenchmark::readSpectrumCSV(), LinearComptonBenchmark::sampleLabSpectrum(), and Options::seed.
TEST() [14/14]
TEST (TestLinearComptonSpectrum , WeakFieldSpectrumMatchesCainReference)
Definition at line 147 of file TestLinearComptonSpectrum.cpp.
References LinearComptonBenchmark::histogramArea(), LinearComptonBenchmark::histogramL1Distance(), LinearComptonBenchmark::histogramMeanEnergyGeV(), LinearComptonBenchmark::integrateLabSpectrum(), and LinearComptonBenchmark::readSpectrumCSV().