OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestFromFile.cpp File Reference
TestFromFile.cpp File Reference
#include <gtest/gtest.h>
#include <mpi.h>
#include <algorithm>
#include <cstdio>
#include <fstream>
#include <memory>
#include "Distribution/Distribution.h"
#include "Distribution/FromFile.h"
#include "Ippl.h"
#include "PartBunch/BunchStateHandler.h"
#include "Utility/IpplTimings.h"
Classes
class FromFileTest
Functions
TEST_F (FromFileTest, GeneratesParticlesFromAsciiFile)
TEST_F (FromFileTest, ParseHeader_ReorderedColumns)
TEST_F (FromFileTest, ParseHeader_StandardOrderAndAlternateNames)
Function Documentation
TEST_F() [1/3]
TEST_F (FromFileTest , GeneratesParticlesFromAsciiFile)
Definition at line 100 of file TestFromFile.cpp.
References FromFile::generateParticles(), and nr.
TEST_F() [2/3]
TEST_F (FromFileTest , ParseHeader_ReorderedColumns)
Definition at line 147 of file TestFromFile.cpp.
References FromFile::generateParticles(), and nr.
TEST_F() [3/3]
TEST_F (FromFileTest , ParseHeader_StandardOrderAndAlternateNames)
Definition at line 176 of file TestFromFile.cpp.
References FromFile::generateParticles(), and nr.