OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestLinearBreitWheelerSpectrum.cpp File Reference
TestLinearBreitWheelerSpectrum.cpp File Reference
#include "LinearBreitWheelerBenchmarkCommon.h"
#include "Utilities/Options.h"
#include "gtest/gtest.h"
#include <filesystem>
Functions
TEST (TestLinearBreitWheelerSpectrum, ElectronEnergySpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, PositronEnergySpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, ElectronAngularSpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, PositronAngularSpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, ElectronJointSpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, PositronJointSpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, FinitePhotonBeamElectronEnergySpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, FinitePhotonBeamPositronEnergySpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, FinitePhotonBeamElectronAngularSpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, FinitePhotonBeamPositronAngularSpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, FinitePhotonBeamElectronJointSpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, FinitePhotonBeamPositronJointSpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, FinitePhotonBeamEnergySpreadElectronEnergySpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, FinitePhotonBeamEnergySpreadPositronEnergySpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, FinitePhotonBeamEnergySpreadElectronAngularSpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, FinitePhotonBeamEnergySpreadPositronAngularSpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, FinitePhotonBeamEnergySpreadElectronJointSpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, FinitePhotonBeamEnergySpreadPositronJointSpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, OverlapWeightedElectronEnergySpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, OverlapWeightedPositronEnergySpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, OverlapWeightedElectronAngularSpectrumMatchesCainReference)
TEST (TestLinearBreitWheelerSpectrum, OverlapWeightedPositronAngularSpectrumMatchesCainReference)
Function Documentation
TEST() [1/22]
TEST (TestLinearBreitWheelerSpectrum , ElectronAngularSpectrumMatchesCainReference)
Definition at line 185 of file TestLinearBreitWheelerSpectrum.cpp.
References LinearBreitWheelerBenchmark::Electron, LinearBreitWheelerBenchmark::histogramArea(), LinearBreitWheelerBenchmark::histogramL1Distance(), LinearBreitWheelerBenchmark::histogramMean(), LinearBreitWheelerBenchmark::HistogramConfig::maxValue, LinearBreitWheelerBenchmark::HistogramConfig::minValue, LinearBreitWheelerBenchmark::readHistogramCSV(), LinearBreitWheelerBenchmark::sampleHistogram(), Options::seed, and LinearBreitWheelerBenchmark::Theta.
TEST() [2/22]
TEST (TestLinearBreitWheelerSpectrum , ElectronEnergySpectrumMatchesCainReference)
Definition at line 135 of file TestLinearBreitWheelerSpectrum.cpp.
References LinearBreitWheelerBenchmark::Electron, LinearBreitWheelerBenchmark::Energy, LinearBreitWheelerBenchmark::histogramArea(), LinearBreitWheelerBenchmark::histogramL1Distance(), LinearBreitWheelerBenchmark::histogramMean(), LinearBreitWheelerBenchmark::HistogramConfig::maxValue, LinearBreitWheelerBenchmark::HistogramConfig::minValue, LinearBreitWheelerBenchmark::readHistogramCSV(), LinearBreitWheelerBenchmark::sampleHistogram(), and Options::seed.
TEST() [3/22]
TEST (TestLinearBreitWheelerSpectrum , ElectronJointSpectrumMatchesCainReference)
Definition at line 235 of file TestLinearBreitWheelerSpectrum.cpp.
References LinearBreitWheelerBenchmark::Electron, LinearBreitWheelerBenchmark::jointHistogramArea(), LinearBreitWheelerBenchmark::jointHistogramL1Distance(), LinearBreitWheelerBenchmark::jointHistogramMeanEnergyGeV(), LinearBreitWheelerBenchmark::jointHistogramMeanThetaRad(), LinearBreitWheelerBenchmark::readJointHistogramCSV(), LinearBreitWheelerBenchmark::sampleJointHistogram(), and Options::seed.
TEST() [4/22]
TEST (TestLinearBreitWheelerSpectrum , FinitePhotonBeamElectronAngularSpectrumMatchesCainReference)
Definition at line 341 of file TestLinearBreitWheelerSpectrum.cpp.
References LinearBreitWheelerBenchmark::Electron, LinearBreitWheelerBenchmark::histogramArea(), LinearBreitWheelerBenchmark::histogramL1Distance(), LinearBreitWheelerBenchmark::histogramMean(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::maxValue, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::minValue, LinearBreitWheelerBenchmark::readHistogramCSV(), LinearBreitWheelerBenchmark::sampleFinitePhotonBeamHistogram(), Options::seed, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaXRad, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaYRad, and LinearBreitWheelerBenchmark::Theta.
TEST() [5/22]
TEST (TestLinearBreitWheelerSpectrum , FinitePhotonBeamElectronEnergySpectrumMatchesCainReference)
Definition at line 287 of file TestLinearBreitWheelerSpectrum.cpp.
References LinearBreitWheelerBenchmark::Electron, LinearBreitWheelerBenchmark::Energy, LinearBreitWheelerBenchmark::histogramArea(), LinearBreitWheelerBenchmark::histogramL1Distance(), LinearBreitWheelerBenchmark::histogramMean(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::maxValue, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::minValue, LinearBreitWheelerBenchmark::readHistogramCSV(), LinearBreitWheelerBenchmark::sampleFinitePhotonBeamHistogram(), Options::seed, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaXRad, and LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaYRad.
TEST() [6/22]
TEST (TestLinearBreitWheelerSpectrum , FinitePhotonBeamElectronJointSpectrumMatchesCainReference)
Definition at line 396 of file TestLinearBreitWheelerSpectrum.cpp.
References LinearBreitWheelerBenchmark::Electron, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::energyMaxGeV, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::energyMinGeV, LinearBreitWheelerBenchmark::jointHistogramArea(), LinearBreitWheelerBenchmark::jointHistogramL1Distance(), LinearBreitWheelerBenchmark::jointHistogramMeanEnergyGeV(), LinearBreitWheelerBenchmark::jointHistogramMeanThetaRad(), LinearBreitWheelerBenchmark::readJointHistogramCSV(), LinearBreitWheelerBenchmark::sampleFinitePhotonBeamJointHistogram(), Options::seed, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaThetaXRad, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaThetaYRad, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::thetaMaxRad, and LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::thetaMinRad.
TEST() [7/22]
TEST (TestLinearBreitWheelerSpectrum , FinitePhotonBeamEnergySpreadElectronAngularSpectrumMatchesCainReference)
Definition at line 516 of file TestLinearBreitWheelerSpectrum.cpp.
References LinearBreitWheelerBenchmark::Electron, LinearBreitWheelerBenchmark::histogramArea(), LinearBreitWheelerBenchmark::histogramL1Distance(), LinearBreitWheelerBenchmark::histogramMean(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::maxValue, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::minValue, LinearBreitWheelerBenchmark::readHistogramCSV(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::relativeEnergySpread, LinearBreitWheelerBenchmark::sampleFinitePhotonBeamHistogram(), Options::seed, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaXRad, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaYRad, and LinearBreitWheelerBenchmark::Theta.
TEST() [8/22]
TEST (TestLinearBreitWheelerSpectrum , FinitePhotonBeamEnergySpreadElectronEnergySpectrumMatchesCainReference)
Definition at line 460 of file TestLinearBreitWheelerSpectrum.cpp.
References LinearBreitWheelerBenchmark::Electron, LinearBreitWheelerBenchmark::Energy, LinearBreitWheelerBenchmark::histogramArea(), LinearBreitWheelerBenchmark::histogramL1Distance(), LinearBreitWheelerBenchmark::histogramMean(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::maxValue, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::minValue, LinearBreitWheelerBenchmark::readHistogramCSV(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::relativeEnergySpread, LinearBreitWheelerBenchmark::sampleFinitePhotonBeamHistogram(), Options::seed, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaXRad, and LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaYRad.
TEST() [9/22]
TEST (TestLinearBreitWheelerSpectrum , FinitePhotonBeamEnergySpreadElectronJointSpectrumMatchesCainReference)
Definition at line 573 of file TestLinearBreitWheelerSpectrum.cpp.
References LinearBreitWheelerBenchmark::Electron, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::energyMaxGeV, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::energyMinGeV, LinearBreitWheelerBenchmark::jointHistogramArea(), LinearBreitWheelerBenchmark::jointHistogramL1Distance(), LinearBreitWheelerBenchmark::jointHistogramMeanEnergyGeV(), LinearBreitWheelerBenchmark::jointHistogramMeanThetaRad(), LinearBreitWheelerBenchmark::readJointHistogramCSV(), LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::relativeEnergySpread, LinearBreitWheelerBenchmark::sampleFinitePhotonBeamJointHistogram(), Options::seed, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaThetaXRad, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaThetaYRad, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::thetaMaxRad, and LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::thetaMinRad.
TEST() [10/22]
TEST (TestLinearBreitWheelerSpectrum , FinitePhotonBeamEnergySpreadPositronAngularSpectrumMatchesCainReference)
Definition at line 544 of file TestLinearBreitWheelerSpectrum.cpp.
References LinearBreitWheelerBenchmark::histogramArea(), LinearBreitWheelerBenchmark::histogramL1Distance(), LinearBreitWheelerBenchmark::histogramMean(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::maxValue, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::minValue, LinearBreitWheelerBenchmark::Positron, LinearBreitWheelerBenchmark::readHistogramCSV(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::relativeEnergySpread, LinearBreitWheelerBenchmark::sampleFinitePhotonBeamHistogram(), Options::seed, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaXRad, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaYRad, and LinearBreitWheelerBenchmark::Theta.
TEST() [11/22]
TEST (TestLinearBreitWheelerSpectrum , FinitePhotonBeamEnergySpreadPositronEnergySpectrumMatchesCainReference)
Definition at line 488 of file TestLinearBreitWheelerSpectrum.cpp.
References LinearBreitWheelerBenchmark::Energy, LinearBreitWheelerBenchmark::histogramArea(), LinearBreitWheelerBenchmark::histogramL1Distance(), LinearBreitWheelerBenchmark::histogramMean(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::maxValue, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::minValue, LinearBreitWheelerBenchmark::Positron, LinearBreitWheelerBenchmark::readHistogramCSV(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::relativeEnergySpread, LinearBreitWheelerBenchmark::sampleFinitePhotonBeamHistogram(), Options::seed, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaXRad, and LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaYRad.
TEST() [12/22]
TEST (TestLinearBreitWheelerSpectrum , FinitePhotonBeamEnergySpreadPositronJointSpectrumMatchesCainReference)
Definition at line 606 of file TestLinearBreitWheelerSpectrum.cpp.
References LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::energyMaxGeV, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::energyMinGeV, LinearBreitWheelerBenchmark::jointHistogramArea(), LinearBreitWheelerBenchmark::jointHistogramL1Distance(), LinearBreitWheelerBenchmark::jointHistogramMeanEnergyGeV(), LinearBreitWheelerBenchmark::jointHistogramMeanThetaRad(), LinearBreitWheelerBenchmark::Positron, LinearBreitWheelerBenchmark::readJointHistogramCSV(), LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::relativeEnergySpread, LinearBreitWheelerBenchmark::sampleFinitePhotonBeamJointHistogram(), Options::seed, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaThetaXRad, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaThetaYRad, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::thetaMaxRad, and LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::thetaMinRad.
TEST() [13/22]
TEST (TestLinearBreitWheelerSpectrum , FinitePhotonBeamPositronAngularSpectrumMatchesCainReference)
Definition at line 368 of file TestLinearBreitWheelerSpectrum.cpp.
References LinearBreitWheelerBenchmark::histogramArea(), LinearBreitWheelerBenchmark::histogramL1Distance(), LinearBreitWheelerBenchmark::histogramMean(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::maxValue, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::minValue, LinearBreitWheelerBenchmark::Positron, LinearBreitWheelerBenchmark::readHistogramCSV(), LinearBreitWheelerBenchmark::sampleFinitePhotonBeamHistogram(), Options::seed, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaXRad, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaYRad, and LinearBreitWheelerBenchmark::Theta.
TEST() [14/22]
TEST (TestLinearBreitWheelerSpectrum , FinitePhotonBeamPositronEnergySpectrumMatchesCainReference)
Definition at line 314 of file TestLinearBreitWheelerSpectrum.cpp.
References LinearBreitWheelerBenchmark::Energy, LinearBreitWheelerBenchmark::histogramArea(), LinearBreitWheelerBenchmark::histogramL1Distance(), LinearBreitWheelerBenchmark::histogramMean(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::maxValue, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::minValue, LinearBreitWheelerBenchmark::Positron, LinearBreitWheelerBenchmark::readHistogramCSV(), LinearBreitWheelerBenchmark::sampleFinitePhotonBeamHistogram(), Options::seed, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaXRad, and LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaYRad.
TEST() [15/22]
TEST (TestLinearBreitWheelerSpectrum , FinitePhotonBeamPositronJointSpectrumMatchesCainReference)
Definition at line 428 of file TestLinearBreitWheelerSpectrum.cpp.
References LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::energyMaxGeV, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::energyMinGeV, LinearBreitWheelerBenchmark::jointHistogramArea(), LinearBreitWheelerBenchmark::jointHistogramL1Distance(), LinearBreitWheelerBenchmark::jointHistogramMeanEnergyGeV(), LinearBreitWheelerBenchmark::jointHistogramMeanThetaRad(), LinearBreitWheelerBenchmark::Positron, LinearBreitWheelerBenchmark::readJointHistogramCSV(), LinearBreitWheelerBenchmark::sampleFinitePhotonBeamJointHistogram(), Options::seed, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaThetaXRad, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::sigmaThetaYRad, LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::thetaMaxRad, and LinearBreitWheelerBenchmark::FinitePhotonBeamJointConfig::thetaMinRad.
TEST() [16/22]
TEST (TestLinearBreitWheelerSpectrum , OverlapWeightedElectronAngularSpectrumMatchesCainReference)
Definition at line 705 of file TestLinearBreitWheelerSpectrum.cpp.
References Physics::c, LinearBreitWheelerBenchmark::Electron, LinearBreitWheelerBenchmark::histogramArea(), LinearBreitWheelerBenchmark::histogramL1Distance(), LinearBreitWheelerBenchmark::histogramMean(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserRayleighX_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserRayleighY_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserSigmaT_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::maxValue, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::minValue, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::overlapWeighting, LinearBreitWheelerBenchmark::readHistogramCSV(), LinearBreitWheelerBenchmark::sampleFinitePhotonBeamHistogram(), Options::seed, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaS_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaXRad, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaYRad, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaX_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaY_m, and LinearBreitWheelerBenchmark::Theta.
TEST() [17/22]
TEST (TestLinearBreitWheelerSpectrum , OverlapWeightedElectronEnergySpectrumMatchesCainReference)
Definition at line 639 of file TestLinearBreitWheelerSpectrum.cpp.
References Physics::c, LinearBreitWheelerBenchmark::Electron, LinearBreitWheelerBenchmark::Energy, LinearBreitWheelerBenchmark::histogramArea(), LinearBreitWheelerBenchmark::histogramL1Distance(), LinearBreitWheelerBenchmark::histogramMean(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserRayleighX_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserRayleighY_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserSigmaT_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::maxValue, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::minValue, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::overlapWeighting, LinearBreitWheelerBenchmark::readHistogramCSV(), LinearBreitWheelerBenchmark::sampleFinitePhotonBeamHistogram(), Options::seed, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaS_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaXRad, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaYRad, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaX_m, and LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaY_m.
TEST() [18/22]
TEST (TestLinearBreitWheelerSpectrum , OverlapWeightedPositronAngularSpectrumMatchesCainReference)
Definition at line 738 of file TestLinearBreitWheelerSpectrum.cpp.
References Physics::c, LinearBreitWheelerBenchmark::histogramArea(), LinearBreitWheelerBenchmark::histogramL1Distance(), LinearBreitWheelerBenchmark::histogramMean(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserRayleighX_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserRayleighY_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserSigmaT_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::maxValue, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::minValue, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::overlapWeighting, LinearBreitWheelerBenchmark::Positron, LinearBreitWheelerBenchmark::readHistogramCSV(), LinearBreitWheelerBenchmark::sampleFinitePhotonBeamHistogram(), Options::seed, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaS_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaXRad, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaYRad, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaX_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaY_m, and LinearBreitWheelerBenchmark::Theta.
TEST() [19/22]
TEST (TestLinearBreitWheelerSpectrum , OverlapWeightedPositronEnergySpectrumMatchesCainReference)
Definition at line 672 of file TestLinearBreitWheelerSpectrum.cpp.
References Physics::c, LinearBreitWheelerBenchmark::Energy, LinearBreitWheelerBenchmark::histogramArea(), LinearBreitWheelerBenchmark::histogramL1Distance(), LinearBreitWheelerBenchmark::histogramMean(), LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserRayleighX_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserRayleighY_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::laserSigmaT_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::maxValue, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::minValue, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::overlapWeighting, LinearBreitWheelerBenchmark::Positron, LinearBreitWheelerBenchmark::readHistogramCSV(), LinearBreitWheelerBenchmark::sampleFinitePhotonBeamHistogram(), Options::seed, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaS_m, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaXRad, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaThetaYRad, LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaX_m, and LinearBreitWheelerBenchmark::FinitePhotonBeamConfig::sigmaY_m.
TEST() [20/22]
TEST (TestLinearBreitWheelerSpectrum , PositronAngularSpectrumMatchesCainReference)
Definition at line 210 of file TestLinearBreitWheelerSpectrum.cpp.
References LinearBreitWheelerBenchmark::histogramArea(), LinearBreitWheelerBenchmark::histogramL1Distance(), LinearBreitWheelerBenchmark::histogramMean(), LinearBreitWheelerBenchmark::HistogramConfig::maxValue, LinearBreitWheelerBenchmark::HistogramConfig::minValue, LinearBreitWheelerBenchmark::Positron, LinearBreitWheelerBenchmark::readHistogramCSV(), LinearBreitWheelerBenchmark::sampleHistogram(), Options::seed, and LinearBreitWheelerBenchmark::Theta.
TEST() [21/22]
TEST (TestLinearBreitWheelerSpectrum , PositronEnergySpectrumMatchesCainReference)
Definition at line 160 of file TestLinearBreitWheelerSpectrum.cpp.
References LinearBreitWheelerBenchmark::Energy, LinearBreitWheelerBenchmark::histogramArea(), LinearBreitWheelerBenchmark::histogramL1Distance(), LinearBreitWheelerBenchmark::histogramMean(), LinearBreitWheelerBenchmark::HistogramConfig::maxValue, LinearBreitWheelerBenchmark::HistogramConfig::minValue, LinearBreitWheelerBenchmark::Positron, LinearBreitWheelerBenchmark::readHistogramCSV(), LinearBreitWheelerBenchmark::sampleHistogram(), and Options::seed.
TEST() [22/22]
TEST (TestLinearBreitWheelerSpectrum , PositronJointSpectrumMatchesCainReference)
Definition at line 261 of file TestLinearBreitWheelerSpectrum.cpp.
References LinearBreitWheelerBenchmark::jointHistogramArea(), LinearBreitWheelerBenchmark::jointHistogramL1Distance(), LinearBreitWheelerBenchmark::jointHistogramMeanEnergyGeV(), LinearBreitWheelerBenchmark::jointHistogramMeanThetaRad(), LinearBreitWheelerBenchmark::Positron, LinearBreitWheelerBenchmark::readJointHistogramCSV(), LinearBreitWheelerBenchmark::sampleJointHistogram(), and Options::seed.