OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestOrbitThreader.cpp File Reference
TestOrbitThreader.cpp File Reference
#include "gtest/gtest.h"
#include "AbstractObjects/OpalData.h"
#include "Algorithms/DefaultVisitor.h"
#include "Algorithms/OrbitThreader.h"
#include "Algorithms/PartData.h"
#include "BeamlineCore/MultipoleRep.h"
#include "BeamlineGeometry/NullGeometry.h"
#include "BeamlineGeometry/PlacementPose.h"
#include "Beamlines/Beamline.h"
#include "Elements/OpalBeamline.h"
#include "Fields/NullField.h"
#include "Structure/Beam.h"
#include "Structure/DataSink.h"
#include "Structure/FieldSolverCmd.h"
#include "Utilities/Options.h"
#include "Utility/Inform.h"
#include <filesystem>
#include <set>
Classes
class OrbitThreaderTest
class OrbitThreaderTest::TestableFieldSolverCmd
Functions
TEST_F (OrbitThreaderTest, ExposesEmptyReferencePathModelBeforeExecution)
TEST_F (OrbitThreaderTest, ExecutesOverlapAndBuildsTracedAndRegistrationModels)
TEST_F (OrbitThreaderTest, UsesFieldSupportExtentForLengthCheck)
Variables
Inform * gmsg
Function Documentation
TEST_F() [1/3]
TEST_F (OrbitThreaderTest , ExecutesOverlapAndBuildsTracedAndRegistrationModels)
Definition at line 205 of file TestOrbitThreader.cpp.
References ReferencePathModel::empty(), OrbitThreader::execute(), OrbitThreader::getActionRangeRegistrationModel(), OrbitThreader::getReferencePathModel(), ReferencePathModel::getSegments(), OpalBeamline::prepareSections(), StepSizeConfig::push_back(), StepSizeConfig::resetIterator(), ReferencePathModel::size(), and OpalBeamline::visit().
TEST_F() [2/3]
TEST_F (OrbitThreaderTest , ExposesEmptyReferencePathModelBeforeExecution)
Definition at line 190 of file TestOrbitThreader.cpp.
References ReferencePathModel::empty(), OrbitThreader::getActionRangeRegistrationModel(), OrbitThreader::getReferencePathModel(), StepSizeConfig::push_back(), and StepSizeConfig::resetIterator().
TEST_F() [3/3]
TEST_F (OrbitThreaderTest , UsesFieldSupportExtentForLengthCheck)
Definition at line 264 of file TestOrbitThreader.cpp.
References OrbitThreader::execute(), OpalBeamline::prepareSections(), StepSizeConfig::push_back(), StepSizeConfig::resetIterator(), and OpalBeamline::visit().
Variable Documentation
gmsg
Inform* gmsg extern
Definition at line 7 of file changes.cpp.
Referenced by OrbitThreaderTest::SetUpTestSuite(), and OrbitThreaderTest::TearDownTestSuite().