OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestSolenoid.cpp File Reference
TestSolenoid.cpp File Reference
#include "AbsBeamline/Solenoid.h"
#include "AbstractObjects/OpalData.h"
#include "Algorithms/DefaultVisitor.h"
#include "Algorithms/IndexMap.h"
#include "BeamlineCore/DriftRep.h"
#include "BeamlineCore/MultipoleRep.h"
#include "BeamlineCore/RFCavityRep.h"
#include "BeamlineCore/SolenoidRep.h"
#include "BeamlineCore/TravelingWaveRep.h"
#include "BeamlineGeometry/NullGeometry.h"
#include "Beamlines/Beamline.h"
#include "Elements/OpalBeamline.h"
#include "Fields/Fieldmap.h"
#include "Physics/Units.h"
#include "Structure/Beam.h"
#include "Structure/DataSink.h"
#include "Structure/FieldSolverCmd.h"
#include "Structure/MeshGenerator.h"
#include "gtest/gtest.h"
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
Classes
class SolenoidPlacementTest
class SolenoidPlacementTest::TestableFieldSolverCmd
class DummyBeamline
Functions
TEST_F (SolenoidPlacementTest, FieldMapEdgesAndSupportEnvelopeFollowFieldMap)
TEST_F (SolenoidPlacementTest, LatticeExportsUseFieldMapEdgesAndSolenoidMeshType)
TEST_F (SolenoidPlacementTest, ElementPositionsSDDSMarksSolenoidColumn)
TEST_F (SolenoidPlacementTest, DriftMeshesAsBlueCylinderUsingFirstNonDriftReference)
TEST_F (SolenoidPlacementTest, QuadrupoleMeshesAsPoleBodyRatherThanGenericCylinder)
TEST_F (SolenoidPlacementTest, RFCavityMeshesAsBulgedCellStructure)
TEST_F (SolenoidPlacementTest, TravelingWaveMeshesAsPeriodicStructure)
Function Documentation
TEST_F() [1/7]
TEST_F (SolenoidPlacementTest , DriftMeshesAsBlueCylinderUsingFirstNonDriftReference)
Definition at line 318 of file TestSolenoid.cpp.
References OpalBeamline::compute3DLattice(), OpalBeamline::save3DLattice(), ElementBase::setElementLength(), ElementBase::setElementPosition(), Solenoid::setFieldMapFN(), and OpalBeamline::visit().
TEST_F() [2/7]
TEST_F (SolenoidPlacementTest , ElementPositionsSDDSMarksSolenoidColumn)
Definition at line 290 of file TestSolenoid.cpp.
References IndexMap::add(), and IndexMap::saveSDDS().
TEST_F() [3/7]
TEST_F (SolenoidPlacementTest , FieldMapEdgesAndSupportEnvelopeFollowFieldMap)
Definition at line 174 of file TestSolenoid.cpp.
References Solenoid::getEdgeToBegin(), Solenoid::getEdgeToEnd(), Solenoid::getElementDimensions(), ElementBase::getElementLength(), Solenoid::getFieldExtend(), CoordinateSystemTrafo::getOrigin(), Solenoid::getSupportEnvelope(), Solenoid::initialise(), Solenoid::isInside(), ElementBase::setElementLength(), ElementBase::setElementPosition(), Solenoid::setFieldMapFN(), OpalException::what(), and OpalException::where().
TEST_F() [4/7]
TEST_F (SolenoidPlacementTest , LatticeExportsUseFieldMapEdgesAndSolenoidMeshType)
Definition at line 221 of file TestSolenoid.cpp.
References OpalBeamline::compute3DLattice(), OpalBeamline::getElements(), PlacedElement::getNominalEntryTransform(), PlacedElement::getNominalExitTransform(), CoordinateSystemTrafo::getOrigin(), OpalBeamline::getPlacedElement(), OpalBeamline::save3DLattice(), ElementBase::setElementLength(), ElementBase::setElementPosition(), Solenoid::setFieldMapFN(), OpalBeamline::visit(), OpalException::what(), and OpalException::where().
TEST_F() [5/7]
TEST_F (SolenoidPlacementTest , QuadrupoleMeshesAsPoleBodyRatherThanGenericCylinder)
Definition at line 347 of file TestSolenoid.cpp.
References OpalBeamline::compute3DLattice(), ELLIPTICAL, OpalBeamline::save3DLattice(), ElementBase::setAperture(), ElementBase::setElementLength(), ElementBase::setElementPosition(), Multipole::setNormalComponent(), and OpalBeamline::visit().
TEST_F() [6/7]
TEST_F (SolenoidPlacementTest , RFCavityMeshesAsBulgedCellStructure)
Definition at line 370 of file TestSolenoid.cpp.
References MeshGenerator::add(), ELLIPTICAL, ElementBase::setAperture(), ElementBase::setElementLength(), ElementBase::setElementPosition(), and MeshGenerator::write().
TEST_F() [7/7]
TEST_F (SolenoidPlacementTest , TravelingWaveMeshesAsPeriodicStructure)
Definition at line 388 of file TestSolenoid.cpp.
References MeshGenerator::add(), ELLIPTICAL, ElementBase::setAperture(), ElementBase::setElementLength(), ElementBase::setElementPosition(), and MeshGenerator::write().