OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestBunchStateHandler.cpp File Reference
TestBunchStateHandler.cpp File Reference
#include <gtest/gtest.h>
#include "Ippl.h"
#include "PartBunch/BunchStateHandler.h"
#include "Utilities/Options.h"
Classes
class BunchStateHandlerTest
Functions
TEST_F (BunchStateHandlerTest, RegisterContainerReturnsFreshSlot)
TEST_F (BunchStateHandlerTest, BunchWideFirstRepartitionDefault)
TEST_F (BunchStateHandlerTest, UnitlessPositionsToggle)
TEST_F (BunchStateHandlerTest, MomentsDirtyLifecycle)
TEST_F (BunchStateHandlerTest, FirstRepartition)
TEST_F (BunchStateHandlerTest, PerContainerSlotsAreIndependent)
TEST_F (BunchStateHandlerTest, SlotLifetimeFollowsCallerOwnership)
TEST_F (BunchStateHandlerTest, AggressiveSync_MomentsDirty_OrAcrossRanks)
TEST_F (BunchStateHandlerTest, AggressiveSync_ClearOnlyWhenAllAgree)
TEST_F (BunchStateHandlerTest, AggressiveSync_UnitlessPositionsConverge)
TEST_F (BunchStateHandlerTest, AggressiveSync_FirstRepartitionConverge)
TEST_F (BunchStateHandlerTest, AggressiveSync_OffDoesNotSynchronize)
Function Documentation
TEST_F() [1/12]
TEST_F (BunchStateHandlerTest , AggressiveSync_ClearOnlyWhenAllAgree)
Definition at line 140 of file TestBunchStateHandler.cpp.
References Options::aggressiveStateSync, and BunchStateHandler::registerContainer().
TEST_F() [2/12]
TEST_F (BunchStateHandlerTest , AggressiveSync_FirstRepartitionConverge)
Definition at line 178 of file TestBunchStateHandler.cpp.
References Options::aggressiveStateSync, BunchStateHandler::isFirstRepartition(), and BunchStateHandler::setFirstRepartition().
TEST_F() [3/12]
TEST_F (BunchStateHandlerTest , AggressiveSync_MomentsDirty_OrAcrossRanks)
Definition at line 118 of file TestBunchStateHandler.cpp.
References Options::aggressiveStateSync, and BunchStateHandler::registerContainer().
TEST_F() [4/12]
TEST_F (BunchStateHandlerTest , AggressiveSync_OffDoesNotSynchronize)
Definition at line 195 of file TestBunchStateHandler.cpp.
References Options::aggressiveStateSync, and BunchStateHandler::registerContainer().
TEST_F() [5/12]
TEST_F (BunchStateHandlerTest , AggressiveSync_UnitlessPositionsConverge)
Definition at line 162 of file TestBunchStateHandler.cpp.
References Options::aggressiveStateSync, and BunchStateHandler::registerContainer().
TEST_F() [6/12]
TEST_F (BunchStateHandlerTest , BunchWideFirstRepartitionDefault)
Definition at line 30 of file TestBunchStateHandler.cpp.
References BunchStateHandler::isFirstRepartition().
TEST_F() [7/12]
TEST_F (BunchStateHandlerTest , FirstRepartition)
Definition at line 67 of file TestBunchStateHandler.cpp.
References BunchStateHandler::isFirstRepartition(), and BunchStateHandler::setFirstRepartition().
TEST_F() [8/12]
TEST_F (BunchStateHandlerTest , MomentsDirtyLifecycle)
Definition at line 45 of file TestBunchStateHandler.cpp.
References BunchStateHandler::registerContainer().
TEST_F() [9/12]
TEST_F (BunchStateHandlerTest , PerContainerSlotsAreIndependent)
Definition at line 78 of file TestBunchStateHandler.cpp.
References BunchStateHandler::registerContainer().
TEST_F() [10/12]
TEST_F (BunchStateHandlerTest , RegisterContainerReturnsFreshSlot)
Definition at line 22 of file TestBunchStateHandler.cpp.
References BunchStateHandler::registerContainer().
TEST_F() [11/12]
TEST_F (BunchStateHandlerTest , SlotLifetimeFollowsCallerOwnership)
Definition at line 99 of file TestBunchStateHandler.cpp.
References BunchStateHandler::registerContainer().
TEST_F() [12/12]
TEST_F (BunchStateHandlerTest , UnitlessPositionsToggle)
Definition at line 35 of file TestBunchStateHandler.cpp.
References BunchStateHandler::registerContainer().