OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestMultiVariateGaussian.cpp File Reference
TestMultiVariateGaussian.cpp File Reference
#include <gtest/gtest.h>
#include <mpi.h>
#include <algorithm>
#include <cmath>
#include <memory>
#include "Distribution/MultiVariateGaussian.h"
#include "Ippl.h"
#include "PartBunch/BunchStateHandler.h"
#include "Utility/IpplTimings.h"
Classes
class MultiVariateGaussianTest
Functions
template<typename ViewType >
void computeMean (ViewType &view, size_t nlocal, size_t total_nparticles, double meanR[3])
template<typename ViewType >
void computeStdDev (ViewType &view, size_t nlocal, size_t total_nparticles, const double meanR[3], double stddevR[3])
TEST_F (MultiVariateGaussianTest, meanR_varR)
template<typename ViewType >
void computeMaxAbsR (ViewType &view, size_t nlocal, double global_maxAbsR[3], double &global_maxRadius)
TEST_F (MultiVariateGaussianTest, cutoffR)
TEST_F (MultiVariateGaussianTest, meanP_and_varP)
void computeMeanRAndP (const std::shared_ptr< ParticleContainer< double, 3 > > &pc, size_t total_nparticles, double meanSample[6])
void computeCovariance6x6 (const std::shared_ptr< ParticleContainer< double, 3 > > &pc, const double meanSample[6], size_t total_nparticles, double moment[6][6])
TEST_F (MultiVariateGaussianTest, FullCovarianceTest)
Function Documentation
computeCovariance6x6()
void computeCovariance6x6 (const std::shared_ptr< ParticleContainer< double, 3 > > & pc, const double meanSample[6], size_t total_nparticles, double moment[6][6])
Definition at line 300 of file TestMultiVariateGaussian.cpp.
Referenced by TEST_F().
computeMaxAbsR()
template<typename ViewType > void computeMaxAbsR (ViewType & view, size_t nlocal, double global_maxAbsR[3], double & global_maxRadius)
Definition at line 152 of file TestMultiVariateGaussian.cpp.
Referenced by TEST_F().
computeMean()
template<typename ViewType > void computeMean (ViewType & view, size_t nlocal, size_t total_nparticles, double meanR[3])
Definition at line 63 of file TestMultiVariateGaussian.cpp.
Referenced by TEST_F(), and TEST_F().
computeMeanRAndP()
void computeMeanRAndP (const std::shared_ptr< ParticleContainer< double, 3 > > & pc, size_t total_nparticles, double meanSample[6])
Definition at line 263 of file TestMultiVariateGaussian.cpp.
Referenced by TEST_F().
computeStdDev()
template<typename ViewType > void computeStdDev (ViewType & view, size_t nlocal, size_t total_nparticles, const double meanR[3], double stddevR[3])
Definition at line 85 of file TestMultiVariateGaussian.cpp.
Referenced by TEST_F(), and TEST_F().
TEST_F() [1/4]
TEST_F (MultiVariateGaussianTest , cutoffR)
Definition at line 202 of file TestMultiVariateGaussian.cpp.
References computeMaxAbsR(), MultiVariateGaussian::generateParticles(), and nr.
TEST_F() [2/4]
TEST_F (MultiVariateGaussianTest , FullCovarianceTest)
Definition at line 346 of file TestMultiVariateGaussian.cpp.
References computeCovariance6x6(), computeMeanRAndP(), MultiVariateGaussian::generateParticles(), and nr.
TEST_F() [3/4]
TEST_F (MultiVariateGaussianTest , meanP_and_varP)
Definition at line 230 of file TestMultiVariateGaussian.cpp.
References computeMean(), computeStdDev(), MultiVariateGaussian::generateParticles(), and nr.
TEST_F() [4/4]
TEST_F (MultiVariateGaussianTest , meanR_varR)
Definition at line 119 of file TestMultiVariateGaussian.cpp.
References computeMean(), computeStdDev(), MultiVariateGaussian::generateParticles(), and nr.