OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestOpalPolynomialTimeDependence.cpp File Reference
TestOpalPolynomialTimeDependence.cpp File Reference
#include <sstream>
#include "Algorithms/AbstractTimeDependence.h"
#include "Algorithms/PolynomialTimeDependence.h"
#include "Attributes/Attributes.h"
#include "Elements/OpalPolynomialTimeDependence.h"
#include "gtest/gtest.h"
Functions
TEST (TestOpalPolynomialTimeDependence, ConstructorTest)
TEST (TestOpalPolynomialTimeDependence, PrintTest)
TEST (TestOpalPolynomialTimeDependence, UpdateTest)
TEST (TestOpalPolynomialTimeDependence, UpdateTest2)
TEST (TestOpalPolynomialTimeDependence, UpdateTest3)
TEST (TestOpalPolynomialTimeDependence, UserInterfacePN)
TEST (TestOpalPolynomialTimeDependence, UserInterfaceCoeffs)
TEST (TestOpalPolynomialTimeDependence, UserInterfaceBoth)
Function Documentation
TEST() [1/8]
TEST (TestOpalPolynomialTimeDependence , ConstructorTest)
Definition at line 23 of file TestOpalPolynomialTimeDependence.cpp.
References OpalPolynomialTimeDependence::clone(), and Object::getOpalName().
TEST() [2/8]
TEST (TestOpalPolynomialTimeDependence , PrintTest)
Definition at line 29 of file TestOpalPolynomialTimeDependence.cpp.
References OpalPolynomialTimeDependence::print().
TEST() [3/8]
TEST (TestOpalPolynomialTimeDependence , UpdateTest)
Definition at line 36 of file TestOpalPolynomialTimeDependence.cpp.
References AbstractTimeDependence::getTimeDependence(), Object::itsAttr, OpalPolynomialTimeDependence::P0, OpalPolynomialTimeDependence::P1, OpalPolynomialTimeDependence::P2, OpalPolynomialTimeDependence::P3, Object::setOpalName(), Attributes::setReal(), and OpalPolynomialTimeDependence::update().
TEST() [4/8]
TEST (TestOpalPolynomialTimeDependence , UpdateTest2)
Definition at line 50 of file TestOpalPolynomialTimeDependence.cpp.
References OpalPolynomialTimeDependence::COEFFICIENTS, AbstractTimeDependence::getTimeDependence(), Object::itsAttr, Object::setOpalName(), Attributes::setRealArray(), and OpalPolynomialTimeDependence::update().
TEST() [5/8]
TEST (TestOpalPolynomialTimeDependence , UpdateTest3)
Definition at line 62 of file TestOpalPolynomialTimeDependence.cpp.
References OpalPolynomialTimeDependence::COEFFICIENTS, Object::itsAttr, OpalPolynomialTimeDependence::P0, OpalPolynomialTimeDependence::P1, OpalPolynomialTimeDependence::P2, OpalPolynomialTimeDependence::P3, Object::setOpalName(), Attributes::setReal(), Attributes::setRealArray(), and OpalPolynomialTimeDependence::update().
TEST() [6/8]
TEST (TestOpalPolynomialTimeDependence , UserInterfaceBoth)
Definition at line 115 of file TestOpalPolynomialTimeDependence.cpp.
References OpalPolynomialTimeDependence::COEFFICIENTS, Object::itsAttr, OpalPolynomialTimeDependence::P0, OpalPolynomialTimeDependence::P1, OpalPolynomialTimeDependence::P2, OpalPolynomialTimeDependence::P3, Attributes::setReal(), Attributes::setRealArray(), and OpalPolynomialTimeDependence::update().
TEST() [7/8]
TEST (TestOpalPolynomialTimeDependence , UserInterfaceCoeffs)
Definition at line 95 of file TestOpalPolynomialTimeDependence.cpp.
References OpalPolynomialTimeDependence::COEFFICIENTS, AbstractTimeDependence::getTimeDependence(), Object::itsAttr, Attributes::setRealArray(), and OpalPolynomialTimeDependence::update().
TEST() [8/8]
TEST (TestOpalPolynomialTimeDependence , UserInterfacePN)
Definition at line 74 of file TestOpalPolynomialTimeDependence.cpp.
References AbstractTimeDependence::getTimeDependence(), Object::itsAttr, OpalPolynomialTimeDependence::P0, OpalPolynomialTimeDependence::P1, OpalPolynomialTimeDependence::P2, OpalPolynomialTimeDependence::P3, Attributes::setReal(), and OpalPolynomialTimeDependence::update().