OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestOpalBeamlinePlacement.cpp File Reference
TestOpalBeamlinePlacement.cpp File Reference
#include "Algorithms/DefaultVisitor.h"
#include "gtest/gtest.h"
#include "AbstractObjects/OpalData.h"
#include "BeamlineCore/DriftRep.h"
#include "BeamlineGeometry/NullGeometry.h"
#include "Beamlines/Beamline.h"
#include "Elements/OpalBeamline.h"
#include "Structure/Beam.h"
#include "Structure/DataSink.h"
#include "Structure/FieldSolverCmd.h"
#include "Utilities/Options.h"
#include "Utility/Inform.h"
#include <cmath>
Classes
class OpalBeamlinePlacementTest
class OpalBeamlinePlacementTest::TestableFieldSolverCmd
Functions
TEST_F (OpalBeamlinePlacementTest, BridgeReturnsPlacedElementViewAndPreservesNominalQueries)
TEST_F (OpalBeamlinePlacementTest, PositionElementRelativeUsesPlacementPoseBridge)
TEST_F (OpalBeamlinePlacementTest, PrepareSectionsCompilesElementPositionIntoNominalPlacement)
TEST_F (OpalBeamlinePlacementTest, BeamlineOwnsPlacedElementAssemblySnapshot)
Variables
Inform * gmsg
Function Documentation
TEST_F() [1/4]
TEST_F (OpalBeamlinePlacementTest , BeamlineOwnsPlacedElementAssemblySnapshot)
Definition at line 194 of file TestOpalBeamlinePlacement.cpp.
References OpalBeamline::getElements(), PlacedElement::getNominalBodyTransform(), CoordinateSystemTrafo::getOrigin(), OpalBeamline::getPlacedElement(), OpalBeamline::prepareSections(), ElementBase::setElementLength(), ElementBase::setElementPosition(), and OpalBeamline::visit().
TEST_F() [2/4]
TEST_F (OpalBeamlinePlacementTest , BridgeReturnsPlacedElementViewAndPreservesNominalQueries)
Definition at line 118 of file TestOpalBeamlinePlacement.cpp.
References OpalBeamline::getCSTrafoLab2Local(), PlacedElement::getMisalignment(), OpalBeamline::getMisalignment(), PlacedElement::getNominalBodyTransform(), PlacedElement::getNominalEntryTransform(), OpalBeamline::getNominalEntryTransform(), PlacedElement::getNominalExitTransform(), OpalBeamline::getNominalExitTransform(), Misalignment::getNominalToActual(), CoordinateSystemTrafo::getOrigin(), OpalBeamline::getPlacedElement(), CoordinateSystemTrafo::rotateFrom(), OpalBeamline::rotateFromLocalCS(), CoordinateSystemTrafo::rotateTo(), OpalBeamline::rotateToLocalCS(), CoordinateSystemTrafo::transformFrom(), OpalBeamline::transformFromLocalCS(), CoordinateSystemTrafo::transformTo(), and OpalBeamline::transformToLocalCS().
TEST_F() [3/4]
TEST_F (OpalBeamlinePlacementTest , PositionElementRelativeUsesPlacementPoseBridge)
Definition at line 155 of file TestOpalBeamlinePlacement.cpp.
References OpalBeamline::getCSTrafoLab2Local(), PlacedElement::getNominalBodyTransform(), CoordinateSystemTrafo::getOrigin(), OpalBeamline::getPlacedElement(), and OpalBeamline::positionElementRelative().
TEST_F() [4/4]
TEST_F (OpalBeamlinePlacementTest , PrepareSectionsCompilesElementPositionIntoNominalPlacement)
Definition at line 172 of file TestOpalBeamlinePlacement.cpp.
References OpalBeamline::getElements(), OpalBeamline::getPlacedElement(), OpalBeamline::prepareSections(), ElementBase::setElementLength(), ElementBase::setElementPosition(), and OpalBeamline::visit().
Variable Documentation
gmsg
Inform* gmsg extern
Definition at line 7 of file changes.cpp.
Referenced by OpalBeamlinePlacementTest::SetUpTestSuite(), and OpalBeamlinePlacementTest::TearDownTestSuite().