OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestBCHandler.cpp File Reference
TestBCHandler.cpp File Reference
#include <gtest/gtest.h>
#include <mpi.h>
#include <memory>
#include <sstream>
#include "Ippl.h"
#include "PartBunch/BCHandler.hpp"
Classes
class BCHandlerTest
Functions
TEST_F (BCHandlerTest, EnumValues)
TEST_F (BCHandlerTest, strToBCTypeValidOPEN)
TEST_F (BCHandlerTest, strToBCTypeValidPERIODIC)
TEST_F (BCHandlerTest, strToBCTypeValidDIRICHLET)
TEST_F (BCHandlerTest, strToBCTypeInvalid)
TEST_F (BCHandlerTest, VariadicConstructor3D_AllOPEN)
TEST_F (BCHandlerTest, VariadicConstructor3D_AllPERIODIC)
TEST_F (BCHandlerTest, VariadicConstructor3D_Mixed)
TEST_F (BCHandlerTest, VariadicConstructor1D)
TEST_F (BCHandlerTest, VariadicConstructor2D)
TEST_F (BCHandlerTest, VariadicConstructorWrongNumberOfArgs)
TEST_F (BCHandlerTest, CopyConstructor)
TEST_F (BCHandlerTest, isAllReturnsTrueWhenAllMatch)
TEST_F (BCHandlerTest, isAllReturnsFalseWhenNotAllMatch)
TEST_F (BCHandlerTest, isAllForMultipleDimensions)
TEST_F (BCHandlerTest, isAllEqualReturnsTrueWhenAllEqual)
TEST_F (BCHandlerTest, isAllEqualReturnsFalseWhenNotAllEqual)
TEST_F (BCHandlerTest, isAllEqualWithDifferentFirstElement)
TEST_F (BCHandlerTest, isAllEqualWithDifferentLastElement)
TEST_F (BCHandlerTest, isAllEqualForDifferentDimensions)
TEST_F (BCHandlerTest, StreamOutputAllOPEN)
TEST_F (BCHandlerTest, StreamOutputMixed)
TEST_F (BCHandlerTest, StreamOutputFormat)
TEST_F (BCHandlerTest, StreamOutput1D)
TEST_F (BCHandlerTest, StreamOutput2D)
TEST_F (BCHandlerTest, ToIPPLBCondsIntegrationNote)
TEST_F (BCHandlerTest, ConsistencyCheckFromString)
TEST_F (BCHandlerTest, CopyConstructorPreservesState)
TEST_F (BCHandlerTest, MultiDimensionalConstructors)
TEST_F (BCHandlerTest, ExceptionMessageQuality)
Function Documentation
TEST_F() [1/30]
TEST_F (BCHandlerTest , ConsistencyCheckFromString)
Definition at line 258 of file TestBCHandler.cpp.
References BCHandler< Dim >::isAll(), BCHandler< Dim >::isAllEqual(), BCHandler< Dim >::PERIODIC, and BCHandler< Dim >::strToBCType().
TEST_F() [2/30]
TEST_F (BCHandlerTest , CopyConstructor)
Definition at line 104 of file TestBCHandler.cpp.
References BCHandler< Dim >::DIRICHLET, BCHandler< Dim >::isAll(), BCHandler< Dim >::OPEN, and BCHandler< Dim >::PERIODIC.
TEST_F() [3/30]
TEST_F (BCHandlerTest , CopyConstructorPreservesState)
Definition at line 266 of file TestBCHandler.cpp.
References BCHandler< Dim >::DIRICHLET, BCHandler< Dim >::OPEN, and BCHandler< Dim >::PERIODIC.
TEST_F() [4/30]
TEST_F (BCHandlerTest , EnumValues)
Definition at line 32 of file TestBCHandler.cpp.
References BCHandler< Dim >::DIRICHLET, BCHandler< Dim >::OPEN, and BCHandler< Dim >::PERIODIC.
TEST_F() [5/30]
TEST_F (BCHandlerTest , ExceptionMessageQuality)
Definition at line 291 of file TestBCHandler.cpp.
References BCHandler< Dim >::strToBCType().
TEST_F() [6/30]
TEST_F (BCHandlerTest , isAllEqualForDifferentDimensions)
Definition at line 170 of file TestBCHandler.cpp.
References BCHandler< Dim >::isAllEqual(), BCHandler< Dim >::OPEN, and BCHandler< Dim >::PERIODIC.
TEST_F() [7/30]
TEST_F (BCHandlerTest , isAllEqualReturnsFalseWhenNotAllEqual)
Definition at line 152 of file TestBCHandler.cpp.
References BCHandler< Dim >::isAllEqual(), BCHandler< Dim >::OPEN, and BCHandler< Dim >::PERIODIC.
TEST_F() [8/30]
TEST_F (BCHandlerTest , isAllEqualReturnsTrueWhenAllEqual)
Definition at line 146 of file TestBCHandler.cpp.
References BCHandler< Dim >::isAllEqual(), and BCHandler< Dim >::OPEN.
TEST_F() [9/30]
TEST_F (BCHandlerTest , isAllEqualWithDifferentFirstElement)
Definition at line 158 of file TestBCHandler.cpp.
References BCHandler< Dim >::DIRICHLET, BCHandler< Dim >::isAllEqual(), and BCHandler< Dim >::PERIODIC.
TEST_F() [10/30]
TEST_F (BCHandlerTest , isAllEqualWithDifferentLastElement)
Definition at line 164 of file TestBCHandler.cpp.
References BCHandler< Dim >::isAllEqual(), BCHandler< Dim >::OPEN, and BCHandler< Dim >::PERIODIC.
TEST_F() [11/30]
TEST_F (BCHandlerTest , isAllForMultipleDimensions)
Definition at line 131 of file TestBCHandler.cpp.
References BCHandler< Dim >::isAll(), and BCHandler< Dim >::PERIODIC.
TEST_F() [12/30]
TEST_F (BCHandlerTest , isAllReturnsFalseWhenNotAllMatch)
Definition at line 123 of file TestBCHandler.cpp.
References BCHandler< Dim >::DIRICHLET, BCHandler< Dim >::isAll(), BCHandler< Dim >::OPEN, and BCHandler< Dim >::PERIODIC.
TEST_F() [13/30]
TEST_F (BCHandlerTest , isAllReturnsTrueWhenAllMatch)
Definition at line 117 of file TestBCHandler.cpp.
References BCHandler< Dim >::isAll(), and BCHandler< Dim >::OPEN.
TEST_F() [14/30]
TEST_F (BCHandlerTest , MultiDimensionalConstructors)
Definition at line 279 of file TestBCHandler.cpp.
References BCHandler< Dim >::isAllEqual(), BCHandler< Dim >::OPEN, and BCHandler< Dim >::PERIODIC.
TEST_F() [15/30]
TEST_F (BCHandlerTest , StreamOutput1D)
Definition at line 220 of file TestBCHandler.cpp.
References BCHandler< Dim >::PERIODIC.
TEST_F() [16/30]
TEST_F (BCHandlerTest , StreamOutput2D)
Definition at line 230 of file TestBCHandler.cpp.
References BCHandler< Dim >::OPEN, and BCHandler< Dim >::PERIODIC.
TEST_F() [17/30]
TEST_F (BCHandlerTest , StreamOutputAllOPEN)
Definition at line 185 of file TestBCHandler.cpp.
References BCHandler< Dim >::OPEN.
TEST_F() [18/30]
TEST_F (BCHandlerTest , StreamOutputFormat)
Definition at line 209 of file TestBCHandler.cpp.
References BCHandler< Dim >::PERIODIC.
TEST_F() [19/30]
TEST_F (BCHandlerTest , StreamOutputMixed)
Definition at line 196 of file TestBCHandler.cpp.
References BCHandler< Dim >::DIRICHLET, BCHandler< Dim >::OPEN, and BCHandler< Dim >::PERIODIC.
TEST_F() [20/30]
TEST_F (BCHandlerTest , strToBCTypeInvalid)
Definition at line 53 of file TestBCHandler.cpp.
References BCHandler< Dim >::strToBCType().
TEST_F() [21/30]
TEST_F (BCHandlerTest , strToBCTypeValidDIRICHLET)
Definition at line 48 of file TestBCHandler.cpp.
References BCHandler< Dim >::DIRICHLET, and BCHandler< Dim >::strToBCType().
TEST_F() [22/30]
TEST_F (BCHandlerTest , strToBCTypeValidOPEN)
Definition at line 38 of file TestBCHandler.cpp.
References BCHandler< Dim >::OPEN, and BCHandler< Dim >::strToBCType().
TEST_F() [23/30]
TEST_F (BCHandlerTest , strToBCTypeValidPERIODIC)
Definition at line 43 of file TestBCHandler.cpp.
References BCHandler< Dim >::PERIODIC, and BCHandler< Dim >::strToBCType().
TEST_F() [24/30]
TEST_F (BCHandlerTest , ToIPPLBCondsIntegrationNote)
Definition at line 249 of file TestBCHandler.cpp.
TEST_F() [25/30]
TEST_F (BCHandlerTest , VariadicConstructor1D)
Definition at line 86 of file TestBCHandler.cpp.
References BCHandler< Dim >::isAll(), and BCHandler< Dim >::PERIODIC.
TEST_F() [26/30]
TEST_F (BCHandlerTest , VariadicConstructor2D)
Definition at line 91 of file TestBCHandler.cpp.
References BCHandler< Dim >::isAll(), BCHandler< Dim >::OPEN, and BCHandler< Dim >::PERIODIC.
TEST_F() [27/30]
TEST_F (BCHandlerTest , VariadicConstructor3D_AllOPEN)
Definition at line 64 of file TestBCHandler.cpp.
References BCHandler< Dim >::isAll(), BCHandler< Dim >::OPEN, and BCHandler< Dim >::PERIODIC.
TEST_F() [28/30]
TEST_F (BCHandlerTest , VariadicConstructor3D_AllPERIODIC)
Definition at line 71 of file TestBCHandler.cpp.
References BCHandler< Dim >::isAll(), BCHandler< Dim >::OPEN, and BCHandler< Dim >::PERIODIC.
TEST_F() [29/30]
TEST_F (BCHandlerTest , VariadicConstructor3D_Mixed)
Definition at line 78 of file TestBCHandler.cpp.
References BCHandler< Dim >::DIRICHLET, BCHandler< Dim >::isAll(), BCHandler< Dim >::OPEN, and BCHandler< Dim >::PERIODIC.
TEST_F() [30/30]
TEST_F (BCHandlerTest , VariadicConstructorWrongNumberOfArgs)
Definition at line 97 of file TestBCHandler.cpp.