OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestOpalDrift.cpp File Reference
TestOpalDrift.cpp File Reference
#include "AbsBeamline/ElementBase.h"
#include "Attributes/Attributes.h"
#include "Elements/OpalDrift.h"
#include "Utilities/OpalException.h"
#include "gtest/gtest.h"
#include <memory>
#include <optional>
#include <string>
#include <vector>
Functions
TEST_F (TestOpalDrift, CircleDefaultsMatchDefaultApertureBehaviour)
TEST_F (TestOpalDrift, SquareAndRectangleEquivalentBehaviour)
TEST_F (TestOpalDrift, ConicCircleOpeningBehaviour)
TEST_F (TestOpalDrift, ConicCircleClosingBehaviour)
TEST_F (TestOpalDrift, CircleConstantAlongLengthAndLongitudinalBounds)
TEST_F (TestOpalDrift, InvalidConicScaleThrowsOpalException)
TEST_F (TestOpalDrift, MalformedRectangleArgumentsThrow)
TEST_F (TestOpalDrift, ConicEllipseOpeningBehaviour)
Function Documentation
TEST_F() [1/8]
TEST_F (TestOpalDrift , CircleConstantAlongLengthAndLongitudinalBounds)
Definition at line 138 of file TestOpalDrift.cpp.
References ElementBase::isInside().
TEST_F() [2/8]
TEST_F (TestOpalDrift , CircleDefaultsMatchDefaultApertureBehaviour)
Definition at line 46 of file TestOpalDrift.cpp.
References ElementBase::isInside().
TEST_F() [3/8]
TEST_F (TestOpalDrift , ConicCircleClosingBehaviour)
Definition at line 123 of file TestOpalDrift.cpp.
References ElementBase::isInside().
TEST_F() [4/8]
TEST_F (TestOpalDrift , ConicCircleOpeningBehaviour)
Definition at line 105 of file TestOpalDrift.cpp.
References ElementBase::isInside().
TEST_F() [5/8]
TEST_F (TestOpalDrift , ConicEllipseOpeningBehaviour)
Definition at line 171 of file TestOpalDrift.cpp.
References ElementBase::isInside().
TEST_F() [6/8]
TEST_F (TestOpalDrift , InvalidConicScaleThrowsOpalException)
Definition at line 160 of file TestOpalDrift.cpp.
TEST_F() [7/8]
TEST_F (TestOpalDrift , MalformedRectangleArgumentsThrow)
Definition at line 166 of file TestOpalDrift.cpp.
TEST_F() [8/8]
TEST_F (TestOpalDrift , SquareAndRectangleEquivalentBehaviour)
Definition at line 73 of file TestOpalDrift.cpp.
References ElementBase::isInside().