OPALX (Object Oriented Parallel Accelerator Library for Exascal): TestFM2DDynamic.cpp File Reference
TestFM2DDynamic.cpp File Reference
Unit tests for FM2DDynamic fieldmap class.
#include <gtest/gtest.h>
#include "Fields/Fieldmap.h"
#include "Fields/FM2DDynamic.h"
#include "Physics/Units.h"
#include "Utilities/GeneralOpalException.h"
#include "Ippl.h"
#include <cmath>
#include <fstream>
#include <filesystem>
#include <vector>
Classes
class FM2DDynamicTest
Functions
TEST_F (FM2DDynamicTest, ParseXZOrientation)
TEST_F (FM2DDynamicTest, ParseZXOrientation)
TEST_F (FM2DDynamicTest, FrequencyParsing)
TEST_F (FM2DDynamicTest, UniformFieldStrength)
TEST_F (FM2DDynamicTest, OutsideZRange)
TEST_F (FM2DDynamicTest, OutsideRadialRange)
TEST_F (FM2DDynamicTest, IsInside)
TEST_F (FM2DDynamicTest, SwapToggle)
TEST_F (FM2DDynamicTest, Normalization)
TEST_F (FM2DDynamicTest, BilinearInterpolation)
TEST_F (FM2DDynamicTest, ComputeFieldStatic)
TEST_F (FM2DDynamicTest, GetFieldDerivativeThrows)
TEST_F (FM2DDynamicTest, GetFieldDimensions6ArgThrows)
TEST_F (FM2DDynamicTest, GetInfoNoCrash)
TEST_F (FM2DDynamicTest, MissingFile)
TEST_F (FM2DDynamicTest, DictionaryCaching)
TEST_F (FM2DDynamicTest, ReadFreeCycle)
TEST_F (FM2DDynamicTest, GridPointAccuracy)
TEST_F (FM2DDynamicTest, XZvsZXConsistency)
TEST_F (FM2DDynamicTest, FieldProjection)
TEST_F (FM2DDynamicTest, FieldAccumulation)
Detailed Description
Unit tests for FM2DDynamic fieldmap class.
Tests cover:
Parsing & metadata:
File parsing (XZ and ZX orientations)
Frequency parsing and conversion (MHz → angular frequency)
Field dimension retrieval (z-bounds)
Field evaluation:
Point field evaluation via getFieldstrength()
Uniform field correctness (on-axis behaviour)
Bilinear interpolation for spatially varying fields
Exact values at grid points (GridPointAccuracy)
Geometry & bounds:
Behaviour outside z-range (no modification, outside flag)
Behaviour outside radial range
isInside() helper (including boundary semantics)
Physical behaviour:
Normalization and scaling:
Electric field: MV/m → V/m
Magnetic field: Bt → μ0 scaling
Projection of cylindrical components (Er, Bt) into Cartesian (x,y)
Consistency between XZ and ZX orientations
Low-level kernel:
Static computeField() correctness (host views, interpolation, projection)
API behaviour:
swap() toggle (orientation handling)
getFieldDerivative() throws (not implemented)
getFieldDimensions(6-arg) throws
getFrequency() correctness
getInfo() does not crash
Robustness:
Missing / invalid file handling
Fieldmap dictionary caching (singleton behaviour)
readMap() / freeMap() lifecycle correctness
Semantics:
Field accumulation: E and B are accumulated, not overwritten
Definition in file TestFM2DDynamic.cpp.
Function Documentation
TEST_F() [1/21]
TEST_F (FM2DDynamicTest , BilinearInterpolation)
Definition at line 510 of file TestFM2DDynamic.cpp.
References Units::cm2m, Fieldmap::getFieldstrength(), Physics::mu_0, and nr.
TEST_F() [2/21]
TEST_F (FM2DDynamicTest , ComputeFieldStatic)
Definition at line 609 of file TestFM2DDynamic.cpp.
TEST_F() [3/21]
TEST_F (FM2DDynamicTest , DictionaryCaching)
Definition at line 785 of file TestFM2DDynamic.cpp.
References nr.
TEST_F() [4/21]
TEST_F (FM2DDynamicTest , FieldAccumulation)
Definition at line 1005 of file TestFM2DDynamic.cpp.
References Fieldmap::getFieldstrength(), and nr.
TEST_F() [5/21]
TEST_F (FM2DDynamicTest , FieldProjection)
Definition at line 945 of file TestFM2DDynamic.cpp.
References Fieldmap::getFieldstrength(), Physics::mu_0, and nr.
TEST_F() [6/21]
TEST_F (FM2DDynamicTest , FrequencyParsing)
Definition at line 246 of file TestFM2DDynamic.cpp.
References Units::MHz2Hz, nr, and Physics::two_pi.
TEST_F() [7/21]
TEST_F (FM2DDynamicTest , GetFieldDerivativeThrows)
Definition at line 707 of file TestFM2DDynamic.cpp.
References DX, Fieldmap::getFieldDerivative(), and nr.
TEST_F() [8/21]
TEST_F (FM2DDynamicTest , GetFieldDimensions6ArgThrows)
Definition at line 732 of file TestFM2DDynamic.cpp.
References Fieldmap::getFieldDimensions(), and nr.
TEST_F() [9/21]
TEST_F (FM2DDynamicTest , GetInfoNoCrash)
Definition at line 755 of file TestFM2DDynamic.cpp.
References Fieldmap::getInfo(), and nr.
TEST_F() [10/21]
TEST_F (FM2DDynamicTest , GridPointAccuracy)
Definition at line 846 of file TestFM2DDynamic.cpp.
References Units::cm2m, Fieldmap::getFieldstrength(), and nr.
TEST_F() [11/21]
TEST_F (FM2DDynamicTest , IsInside)
Definition at line 412 of file TestFM2DDynamic.cpp.
References nr.
TEST_F() [12/21]
TEST_F (FM2DDynamicTest , MissingFile)
Definition at line 776 of file TestFM2DDynamic.cpp.
TEST_F() [13/21]
TEST_F (FM2DDynamicTest , Normalization)
Definition at line 472 of file TestFM2DDynamic.cpp.
References Fieldmap::getFieldstrength(), and nr.
TEST_F() [14/21]
TEST_F (FM2DDynamicTest , OutsideRadialRange)
Definition at line 374 of file TestFM2DDynamic.cpp.
References Fieldmap::getFieldstrength(), and nr.
TEST_F() [15/21]
TEST_F (FM2DDynamicTest , OutsideZRange)
Definition at line 315 of file TestFM2DDynamic.cpp.
References Fieldmap::getFieldstrength(), and nr.
TEST_F() [16/21]
TEST_F (FM2DDynamicTest , ParseXZOrientation)
Definition at line 193 of file TestFM2DDynamic.cpp.
References Units::cm2m, Fieldmap::getFieldDimensions(), Fieldmap::getType(), nr, and T2DDynamic.
TEST_F() [17/21]
TEST_F (FM2DDynamicTest , ParseZXOrientation)
Definition at line 220 of file TestFM2DDynamic.cpp.
References Units::cm2m, Fieldmap::getFieldDimensions(), and nr.
TEST_F() [18/21]
TEST_F (FM2DDynamicTest , ReadFreeCycle)
Definition at line 805 of file TestFM2DDynamic.cpp.
References Fieldmap::freeMap(), Fieldmap::getFieldstrength(), nr, and Fieldmap::readMap().
TEST_F() [19/21]
TEST_F (FM2DDynamicTest , SwapToggle)
Definition at line 448 of file TestFM2DDynamic.cpp.
References nr.
TEST_F() [20/21]
TEST_F (FM2DDynamicTest , UniformFieldStrength)
Definition at line 269 of file TestFM2DDynamic.cpp.
References Fieldmap::getFieldstrength(), and nr.
TEST_F() [21/21]
TEST_F (FM2DDynamicTest , XZvsZXConsistency)
Definition at line 898 of file TestFM2DDynamic.cpp.
References Fieldmap::getFieldstrength(), and nr.