OPALX (Object Oriented Parallel Accelerator Library for Exascal): Token.cpp File Reference
Token.cpp File Reference
#include "OpalParser/Token.h"
#include <cctype>
#include <iostream>
#include <sstream>
#include "Utilities/ParseError.h"
Functions
std::ostream & operator<< (std::ostream &os, const Token &token)
Function Documentation
operator<<()
std::ostream & operator<< (std::ostream & os, const Token & token)
Definition at line 164 of file Token.cpp.
References Token::getInteger(), Token::getLex(), Token::getReal(), Token::getType(), Token::IS_DELIMITER, Token::IS_EOF, Token::IS_ERROR, Token::IS_INTEGER, Token::IS_REAL, Token::IS_STRING, and Token::IS_WORD.