OPALX (Object Oriented Parallel Accelerator Library for Exascal): Token.h File Reference
Token.h File Reference
#include <iosfwd>
#include <string>
Classes
class Token
Representation of a single input token.
Functions
std::ostream & operator<< (std::ostream &, const Token &)
Function Documentation
operator<<()
std::ostream & operator<< (std::ostream & os, const Token & token)
Definition at line 220 of file Token.cpp.
References Token::getInteger(), Token::getLex(), Token::getReal(), Token::getType(), Token::IS_DELIMITER, Token::IS_EOF, Token::IS_ERROR, Token::IS_INTEGER, Token::IS_REAL, Token::IS_STRING, and Token::IS_WORD.