OPALX (Object Oriented Parallel Accelerator Library for Exascal): VectorMath.h File Reference
VectorMath.h File Reference
#include "Ippl.h"
#include <utility>
Typedefs
template<typename T , unsigned Dim>
using Vector_t = ippl::Vector< T, Dim >
using VectorPair_t = std::pair< Vector_t< double, 3 >, Vector_t< double, 3 > >
Functions
template<class T , unsigned D>
KOKKOS_INLINE_FUNCTION double euclidean_norm (const Vector_t< T, D > &v)
template<class T , unsigned D>
KOKKOS_INLINE_FUNCTION double dot (const Vector_t< T, D > &v, const Vector_t< T, D > &w)
template<class T , unsigned D>
KOKKOS_INLINE_FUNCTION double dot (const Vector_t< T, D > &v)
Typedef Documentation
Vector_t
template<typename T , unsigned Dim> using Vector_t = ippl::Vector<T, Dim>
Definition at line 9 of file VectorMath.h.
VectorPair_t
using VectorPair_t = std::pair<Vector_t<double, 3>, Vector_t<double, 3> >
Definition at line 11 of file VectorMath.h.
Function Documentation
dot() [1/2]
template<class T , unsigned D> KOKKOS_INLINE_FUNCTION double dot (const Vector_t< T, D > & v)
Definition at line 27 of file VectorMath.h.
dot() [2/2]
template<class T , unsigned D> KOKKOS_INLINE_FUNCTION double dot (const Vector_t< T, D > & v, const Vector_t< T, D > & w)
Definition at line 21 of file VectorMath.h.
euclidean_norm()
template<class T , unsigned D> KOKKOS_INLINE_FUNCTION double euclidean_norm (const Vector_t< T, D > & v)
Definition at line 15 of file VectorMath.h.
Referenced by OrbitThreader::checkElementLengths(), OpalBeamline::compileCompatibilityPlacement(), OrbitThreader::computeDriftLengthToBoundingBox(), mslang::euclidean_norm2D(), ParallelTracker::execute(), ParallelTracker::findStartPositions(), FlatTop::generateUniformDisk(), BoundingBox::getIntersectionPoint(), Util::getTaitBryantAngles(), OrbitThreader::integrate(), and OrbitThreader::registerElement().