OPALX (Object Oriented Parallel Accelerator Library for Exascal): Vector3D.cpp File Reference
Vector3D.cpp File Reference
#include "BeamlineGeometry/Vector3D.h"
Functions
Vector3D operator+ (const Vector3D &lhs, const Vector3D &rhs)
Add.
Vector3D operator- (const Vector3D &lhs, const Vector3D &rhs)
Subtract.
Vector3D operator* (const Vector3D &lhs, double rhs)
Multiply.
Vector3D operator* (double lhs, const Vector3D &rhs)
Multiply.
Vector3D cross (const Vector3D &lhs, const Vector3D &rhs)
Vector cross product.
double dot (const Vector3D &lhs, const Vector3D &rhs)
Vector dot product.
Function Documentation
cross()
Vector3D cross (const Vector3D & lhs, const Vector3D & rhs)
Vector cross product.
Definition at line 89 of file Vector3D.cpp.
Referenced by LinearBreitWheelerBenchmark::buildTransverseBasis(), getQuaternion(), BoundaryGeometry::intersectLineTriangle(), BorisPusher::kick(), and Quaternion::operator*=().
dot()
double dot (const Vector3D & lhs, const Vector3D & rhs)
Vector dot product.
Definition at line 95 of file Vector3D.cpp.
Referenced by LinearBreitWheelerBenchmark::buildTransverseBasis(), PluginElement::changeWidth(), DistributionMoments::computeDebyeLength(), DistributionMoments::computeMeans(), DistributionMoments::computeMoments(), ParallelTracker::computeSpaceChargeFields(), Probe::doCheck(), Euclid3DGeometry::getArcLength(), BoundingBox::getIntersectionPoint(), CavityAutophaser::getPhaseAtMaxEnergy(), getQuaternion(), gsl_eigen_nonsymm(), BoundaryGeometry::initialize(), OrbitThreader::integrate(), BoundaryGeometry::intersectLineTriangle(), Physics::LinearBreitWheeler::invariantSGeV2(), BorisPusher::kick(), Physics::LinearCompton::labPhotonDirection(), Physics::LinearCompton::labPhotonEnergyGeV(), Physics::LinearBreitWheeler::makeSamplingKernel(), Quaternion::Norm(), BoundaryGeometry::partInside(), LinearComptonBenchmark::photonPolarAngleRad(), BorisPusher::push(), LF2< FieldFunction, Arguments >::push_m(), Physics::LinearCompton::restFrameIncomingPhotonDirection(), Physics::LinearCompton::restFrameIncomingPhotonEnergyGeV(), Physics::LinearCompton::restFrameScatteringCosineForLabForwardPhoton(), Physics::LinearBreitWheeler::sampleEvent(), LinearBreitWheelerBenchmark::samplePhotonBeamState(), OrbitThreader::setDesignEnergy(), TEST(), RFCavity::trackOnAxisParticle(), and OpalLaser::update().
operator*() [1/2]
Vector3D operator* (const Vector3D & lhs, double rhs)
Multiply.
Definition at line 71 of file Vector3D.cpp.
operator*() [2/2]
Vector3D operator* (double lhs, const Vector3D & rhs)
Multiply.
Definition at line 75 of file Vector3D.cpp.
operator+()
Vector3D operator+ (const Vector3D & lhs, const Vector3D & rhs)
Add.
Definition at line 63 of file Vector3D.cpp.
operator-()
Vector3D operator- (const Vector3D & lhs, const Vector3D & rhs)
Subtract.
Definition at line 67 of file Vector3D.cpp.