OPALX (Object Oriented Parallel Accelerator Library for Exascal): Vector3D.h File Reference
Vector3D.h File Reference
Classes
class Vector3D
A 3-dimension vector.
Functions
Vector3D operator+ (const Vector3D &a, const Vector3D &b)
Add.
Vector3D operator- (const Vector3D &a, const Vector3D &b)
Subtract.
Vector3D operator* (const Vector3D &a, double factor)
Multiply.
Vector3D operator* (double factor, const Vector3D &a)
Multiply.
Vector3D cross (const Vector3D &a, const Vector3D &b)
Vector cross product.
double dot (const Vector3D &a, const Vector3D &b)
Vector dot product.
Function Documentation
cross()
Vector3D cross (const Vector3D & a, const Vector3D & b) extern
Vector cross product.
Definition at line 111 of file Vector3D.cpp.
Referenced by LinearBreitWheelerBenchmark::buildTransverseBasis(), getQuaternion(), BoundaryGeometry::intersectLineTriangle(), BorisPusher::kick(), and Quaternion::operator*=().
dot()
double dot (const Vector3D & a, const Vector3D & b) extern
Vector dot product.
Definition at line 118 of file Vector3D.cpp.
Referenced by LinearBreitWheelerBenchmark::buildTransverseBasis(), PluginElement::changeWidth(), DistributionMoments::computeDebyeLength(), DistributionMoments::computeMeans(), DistributionMoments::computeMoments(), ParallelTracker::computeSpaceChargeFields(), Probe::doCheck(), Euclid3DGeometry::getArcLength(), BoundingBox::getIntersectionPoint(), CavityAutophaser::getPhaseAtMaxEnergy(), getQuaternion(), gsl_eigen_nonsymm(), BoundaryGeometry::initialize(), OrbitThreader::integrate(), BoundaryGeometry::intersectLineTriangle(), Physics::LinearBreitWheeler::invariantSGeV2(), BorisPusher::kick(), Physics::LinearCompton::labPhotonDirection(), Physics::LinearCompton::labPhotonEnergyGeV(), Physics::LinearBreitWheeler::makeSamplingKernel(), Quaternion::Norm(), BoundaryGeometry::partInside(), LinearComptonBenchmark::photonPolarAngleRad(), BorisPusher::push(), LF2< FieldFunction, Arguments >::push_m(), Physics::LinearCompton::restFrameIncomingPhotonDirection(), Physics::LinearCompton::restFrameIncomingPhotonEnergyGeV(), Physics::LinearCompton::restFrameScatteringCosineForLabForwardPhoton(), Physics::LinearBreitWheeler::sampleEvent(), LinearBreitWheelerBenchmark::samplePhotonBeamState(), OrbitThreader::setDesignEnergy(), TEST(), RFCavity::trackOnAxisParticle(), and OpalLaser::update().
operator*() [1/2]
Vector3D operator* (const Vector3D & a, double factor) extern
Multiply.
Definition at line 83 of file Vector3D.cpp.
operator*() [2/2]
Vector3D operator* (double factor, const Vector3D & a) extern
Multiply.
Definition at line 88 of file Vector3D.cpp.
operator+()
Vector3D operator+ (const Vector3D & a, const Vector3D & b) extern
Add.
Definition at line 73 of file Vector3D.cpp.
operator-()
Vector3D operator- (const Vector3D & a, const Vector3D & b) extern
Subtract.
Definition at line 78 of file Vector3D.cpp.