var searchData=
[
  ['jointconfig_0',['JointConfig',['../namespaceLinearComptonBenchmark.html#structLinearComptonBenchmark_1_1JointConfig',1,'LinearComptonBenchmark']]],
  ['jointhistogram_1',['JointHistogram',['../namespaceLinearBreitWheelerBenchmark.html#structLinearBreitWheelerBenchmark_1_1JointHistogram',1,'LinearBreitWheelerBenchmark::JointHistogram'],['../namespaceLinearComptonBenchmark.html#structLinearComptonBenchmark_1_1JointHistogram',1,'LinearComptonBenchmark::JointHistogram']]],
  ['jointhistogramarea_2',['jointHistogramArea',['../namespaceLinearBreitWheelerBenchmark.html#ac563c8f12faea384721f8924ecdc3a1d',1,'LinearBreitWheelerBenchmark::jointHistogramArea()'],['../namespaceLinearComptonBenchmark.html#a781a7565b29c0d026caa565fbb7a7ea8',1,'LinearComptonBenchmark::jointHistogramArea()']]],
  ['jointhistogramconfig_3',['JointHistogramConfig',['../namespaceLinearBreitWheelerBenchmark.html#structLinearBreitWheelerBenchmark_1_1JointHistogramConfig',1,'LinearBreitWheelerBenchmark']]],
  ['jointhistogramindex_4',['jointHistogramIndex',['../namespaceLinearComptonBenchmark.html#a8c88ff63cbb839601a1a20bee8295dcc',1,'LinearComptonBenchmark']]],
  ['jointhistograml1distance_5',['jointHistogramL1Distance',['../namespaceLinearBreitWheelerBenchmark.html#ac41495ca9d568fc4e4728dd191fdd918',1,'LinearBreitWheelerBenchmark::jointHistogramL1Distance()'],['../namespaceLinearComptonBenchmark.html#a6d12d6da74f2e151bfcebedfc9c2661f',1,'LinearComptonBenchmark::jointHistogramL1Distance()']]],
  ['jointhistogrammeanenergygev_6',['jointHistogramMeanEnergyGeV',['../namespaceLinearBreitWheelerBenchmark.html#a8ba0bb5c8dbf9bd05d8c4c92f31e8533',1,'LinearBreitWheelerBenchmark::jointHistogramMeanEnergyGeV()'],['../namespaceLinearComptonBenchmark.html#ae97e8e755c1b3c6bd1f3ef4bedc2fdd6',1,'LinearComptonBenchmark::jointHistogramMeanEnergyGeV()']]],
  ['jointhistogrammeanthetarad_7',['jointHistogramMeanThetaRad',['../namespaceLinearBreitWheelerBenchmark.html#af8bd676d3df0632e9485eedcd298696c',1,'LinearBreitWheelerBenchmark::jointHistogramMeanThetaRad()'],['../namespaceLinearComptonBenchmark.html#aaff3b096dc12279739b530a3b9ddc287',1,'LinearComptonBenchmark::jointHistogramMeanThetaRad()']]]
];
